### ISSUE TITLE
日期显示问题

### ISSUE THREAD

**Issue by zxhycxq** [alibaba/ice#10]
![image](https://user-images.githubusercontent.com/11674203/34760228-d2c88e5a-f619-11e7-8d8f-66182e911f2e.png)

今天是10号，默认是10，但是当点击别的日期之后，10就无法显示。应该是样式的问题。

**Comment by wssgcg1213** [comment]
fixed in @icedesign/skin@0.1.6  
如果已经在本地起过项目, 建议手动升级一下上面这个 npm 包的版本就可以了

**Comment by wssgcg1213** [comment]
![image](https://user-images.githubusercontent.com/3922719/34772543-3ce4b5e2-f643-11e7-9e80-796cd1742579.png)
