### ISSUE TITLE
ice客户端升级到 V2.1.1，软件白屏，代码建议。

### ISSUE THREAD

**Issue by mowatermelon** [alibaba/ice#1000]
## 环境信息

- 操作系统：win7
- Iceworks 版本： 2.11.1
- 网络状况: 良好

## 问题描述

软件升级之后，软件主页面左侧帮助菜单没有出现，右侧显示页也是显示空白，控制台中有错误信息输出，显示尝试对一个null值使用object对象才有的方法，所以代码出错。

![image](https://user-images.githubusercontent.com/18508817/47251166-a8e0fa00-d462-11e8-87c3-2dde2b2fb74a.png)

## 可能导致原因

![image](https://user-images.githubusercontent.com/18508817/47251206-b21e9680-d463-11e8-9eca-05947820e2f9.png)

主要导致是`setProject`这个方法中对于`project`这个形参没有做前置对象检测，直接默认是一个`object`对象，在当前`index.js`中检索发现如下两段代码，即这个对象`project`形参会存在实参为`null`的情况，所以建议，先对`project`这个形参做有效性检测，验证无效之后，直接返回。

![image](https://user-images.githubusercontent.com/18508817/47251247-7df7a580-d464-11e8-82ea-71dda837d0be.png)

![image](https://user-images.githubusercontent.com/18508817/47251210-c5316680-d463-11e8-89cd-21fb32e76edc.png)

## 改进代码

```javascript
//原代码
{
    key: "setProject",
    value: function setProject(project) {
      if (project) {
        recordStorage.set(project.fullPath);
      }

      if (!project.hasOwnProperty('isNodeProject')) {
        if (fs_extra_lib_default.a.existsSync(external_path_default.a.join(project.fullPath, 'client'))) {
          project.isNodeProject = true;
        } else {
          project.isNodeProject = false;
        }
      }

      this.currentProject = project;

      if (this.currentProject && this.currentProject.exists) {
        this.emit('change');
      }
    }
  }

//改进之后代码
{
    key: "setProject",
    value: function setProject(project) {
      const ISRIGHT = false;
      if(!project){
        return ISRIGHT;
      }
      if (project) {
        recordStorage.set(project.fullPath);
      }

      if (!project.hasOwnProperty('isNodeProject')) {
        if (fs_extra_lib_default.a.existsSync(external_path_default.a.join(project.fullPath, 'client'))) {
          project.isNodeProject = true;
        } else {
          project.isNodeProject = false;
        }
      }

      this.currentProject = project;

      if (this.currentProject && this.currentProject.exists) {
        this.emit('change');
      }
    }
  }
```

实测有效，希望官方尽快改进。

![image](https://user-images.githubusercontent.com/18508817/47251287-37567b00-d465-11e8-920a-7a9935825ec7.png)

**Comment by chenbin92** [comment]
fixed
