### ISSUE TITLE
Select.ComboBox可否提供显示隐藏下拉菜单的API命令

### ISSUE THREAD

**Issue by Symous** [alibaba/ice#1001]
## 环境信息

- 操作系统：macOS 10.14
- Iceworks 版本： 2.11.1

## 问题描述

在使用Select.ComboBox时，有一些场景下需要手动控制下拉菜单的显示和隐藏，虽然官方已经提供了visible 属性，但是这样的话我们就需要从头维护visible的值，会很麻烦，如果官方能够提供一个命令式的API让我们可以手动控制显示和隐藏就好了。比如:
```jsx
<Select.ComboBox ref={(cb)=> this.cb = cb} .../>

//开启关闭命令：
this.cb.open();
this.cb.close();
```

**Comment by bindoon** [comment]
won't fix

state 存一个visible 和 存一个ref 一样的成本，完全没必要提供一个api
