### ISSUE TITLE
linux版本不能使用

### ISSUE THREAD

**Issue by cheng87126** [alibaba/ice#1002]
## 环境信息

- 操作系统：ubuntu 14.04 LTS 32位
- Iceworks 版本： Iceworks-x86_64-2.6.0-beta.AppImage

## 问题描述

![2018-10-21 22 41 42](https://user-images.githubusercontent.com/29309472/47268469-1f294d80-d584-11e8-8b70-6aed2cbd2e05.png)

**Comment by chenbin92** [comment]
目前主要以 Windows 和 Mac 为主，Linux 暂不维护

**Comment by levinit** [comment]
有deb包不用 ？ 我archlinux打包用的deb包都能用 
https://github.com/alibaba/ice/wiki/Linux
