### ISSUE TITLE
Table.Column lock属性阴影显示问题

### ISSUE THREAD

**Issue by Symous** [alibaba/ice#1004]
## 环境信息

- 操作系统：macOS 10.14
- Iceworks 版本： 2.11.1

## 问题描述

当使用Table.Cloumn时，设置一列的lock为right时，在移动端下，该列的边缘显示阴影，但是出现了点瑕疵——标题也出现了阴影，这样显示很不美观。之前的版本是仅下方内容显示阴影，标题部分不显示，这种方式是比较好的。
![image](https://user-images.githubusercontent.com/13534034/47294899-e00d0200-d640-11e8-8370-3908d6d239f8.png)
```jsx
<Table ...>
     <Table.Column />
     ...
     <Table.Column lock='right'/>     //这一列标题栏也显示了阴影，如上图所示
</Table>
```

**Comment by youluna** [comment]
header带shadow是正常操作，参考excel锁列
