### ISSUE TITLE
Select Search过滤结果筛选出了不符合关键字的条目

### ISSUE THREAD

**Issue by Symous** [alibaba/ice#1012]
## 环境信息

- 操作系统：macOS 10.14
- Iceworks 版本： 2.11.3

## 问题描述

当我们使用Select组件的Search组件过滤条目时，我没理解错的应该是对label进行过滤，但是仍然把不包含关键字的条目给筛选出来了。目测是因为将value也加入过滤的原因？
> 示例代码： https://codesandbox.io/s/wwzykm0mkl

## 错误信息
没有...

**Comment by noyobo** [comment]
组件体验问题，搜索看到的值与输入的不匹配。

**Comment by youluna** [comment]
demo给的是transfer，跟描述的问题不符

**Comment by chenbin92** [comment]
@Symous 请提供复现的 demo 在重新打开该 issue

**Comment by Symous** [comment]
@youluna 复现：https://codesandbox.io/s/m447z5v99y  我记得ant design是有一个属性可以指定是否将value纳入过滤范围的。
@chenbin92 无法re-open issue.
