### ISSUE TITLE
Transfer搭配FormBinder的valueTransformer无法显示已选条目

### ISSUE THREAD

**Issue by Symous** [alibaba/ice#1013]
## 环境信息

- 操作系统：macOS 10.14 
- Iceworks 版本： 2.11.3

## 问题描述

根据官方文档，Transfer组件接收的value值类型为字符串的数组，在实际应用中当直接使用数字型的数组作为dataSource进行选择后，控制台会报expected string的警告/错误，所以使用了valueTransfer来对value数据中的每个项目转为字符串型，但是却出现了在UI中没有将所选条目移动到已选择区域的情况。这个问题好像是最近才出现的，因为之前这边已经调试成功了。
> 代码示例请参考：https://codesandbox.io/s/wwzykm0mkl
## 错误信息
直接使用数字型数组选择后带来的警告如下图：
![image](https://user-images.githubusercontent.com/13534034/47600602-81f06e00-d9f6-11e8-8e62-dd266358c5fb.png)

PS: 为什么Transfer接收的value选项一定要为字符串型呢？

**Comment by noyobo** [comment]
不需要 valueTransform1er 转换的

**Comment by Symous** [comment]
@noyobo 不转换的话，会报我贴出的错误信息。接收的是string类型。

**Comment by noyobo** [comment]
是你的 dataSource value 是 number 的原因 https://codesandbox.io/s/n75nv6398m

**Comment by noyobo** [comment]
是你的 dataSource value 是 number 的原因 https://codesandbox.io/s/n75nv6398m

**Comment by Symous** [comment]
@noyobo 对啊，因为我后台的数据就是number类型的，我写valueTransformer的原因就是要将他们转为string从而避免这个问题啊。
```js
valueTransformer={value => {
   return value.map(item => {
       return item.toString();
    );
}}
```
