### ISSUE TITLE
项目、模板、区块等资源无法正常加载

### ISSUE THREAD

**Issue by systrive** [alibaba/ice#1016]
## 环境信息

- 操作系统：macOS High Sierra 10.13.4
- Iceworks 版本： 2.11.3

## 问题描述

模板、项目、区块没有结果，一直显示“加载中...”

![image](https://user-images.githubusercontent.com/13051530/47633291-4b4a5d00-db88-11e8-989f-b300e6cda96b.png)

**Comment by chenbin92** [comment]
@systrive  点击 `帮助` > `切换开发人员工具` 看看有无报错信息

**Comment by chenbin92** [comment]
不能重现

**Comment by harry0071** [comment]
我也有相同问题
【项目】一直显示“加载中”
【模板】只有Vue物料源可以显示，其他物料源都是“加载中”
【区块】同样只有Vue有，其他都是“加载中”

**Comment by systrive** [comment]
@chenbin92  帮助 > 切换开发人员工具 没有报错信息，只有一个告警信息
![image](https://user-images.githubusercontent.com/13051530/48695139-4cb3f600-ec19-11e8-8d62-11b932060e8e.png)

而且点“刷新列表”按钮看起来也没有发请求

刚刚更新了版本：iceworks 版本：2.12.1

**Comment by chenbin92** [comment]
@systrive  @harry0071  感谢反馈，能提供一下环境信息吗？  Mac 还是 Windows，我们这边排查下

**Comment by systrive** [comment]
这是我的操作系统和 Iceworks 版本哈：
操作系统：macOS High Sierra 10.13.4
Iceworks 版本： 2.11.3 & 2.12.1

还有一台Mac之前不能更新到数据，现在又可以（中间有可能更新了os版本）
操作系统：macOS Mojave 10.14
iceworks 版本：2.11.3

非常感谢哈~

**Comment by Orange-C** [comment]
@systrive 能再提供一下开发者工具中Network页的信息吗，我们看下是不是网络问题。请问是点击右上角的“刷新列表按钮”多次刷新后都是停留在加载中

**Comment by imsobear** [comment]
@systrive 如果还有问题的话麻烦回复并 open 下 issue，目前问题无法复现我先暂时关掉了。
