### ISSUE TITLE
使用飞冰物料源中的markdown模块，无法高亮代码

### ISSUE THREAD

**Issue by wqh17101** [alibaba/ice#1017]
## 环境信息

- 操作系统：win10
- Iceworks 版本：2.10.0 

## 问题描述

使用飞冰物料源中的markdown模块，无法高亮代码

## 错误信息
代码：
![image](https://user-images.githubusercontent.com/26429138/47638037-70df6280-db98-11e8-9d2d-f421d2ea755d.png)

得到这样的结果：
![image](https://user-images.githubusercontent.com/26429138/47638065-7fc61500-db98-11e8-94a6-66cfbca45ef2.png)

期望结果：
![image](https://user-images.githubusercontent.com/26429138/47638089-92404e80-db98-11e8-88f2-a3ba6dc3959e.png)

**Comment by chenbin92** [comment]
具体参考 https://github.com/rexxars/react-markdown 的使用

**Comment by wqh17101** [comment]
![image](https://user-images.githubusercontent.com/26429138/47644715-ddaf2880-dba9-11e8-90de-54ab19e838d7.png)
他的demo显示的是这样的

通过icework构建出来的是这样的
![image](https://user-images.githubusercontent.com/26429138/47644751-fd465100-dba9-11e8-9150-09e32cb2c8fb.png)
似乎丢失了一些样式 @chenbin92
