### ISSUE TITLE
Upload 友好支持oss, uploadList 支持排序

### ISSUE THREAD

**Issue by xiilei** [alibaba/ice#1019]
#### 1. 增加对 [oss](https://help.aliyun.com/document_detail/31849.html?spm=a2c4g.11186623.6.598.782d7815khNPJ1) 友好支持 : )
Upload 要求 server 响应为
```js
{ code: 1, imgURL: "", size:"" }
```
但是 oss 响应为空,状态码为 204, formatter 无法处理.

#### 2. 增加 uploadList 的排序能力, 上传完成之后可能需要调整一下顺序  : )
谢谢!

**Comment by boiawang** [comment]
@xiilei Upload 组件不会支持.

**Comment by KeithZhang** [comment]
+1 这两个功能算是Upload组件的通用需求吧
