### ISSUE TITLE
[功能增强] 支持css modules

### ISSUE THREAD

**Issue by builden** [alibaba/ice#1020]
一个项目中的样式太多，很容易冲突，希望可以像create-react-app一样，在webpack打包的时候直接支持css-modules

使用者只需要把样式文件命名成 xxx.module.css 或 xxx.module.scss，没有module关键字的依然采用原始的转换方式

**Comment by chenbin92** [comment]
这个有计划在支持的

**Comment by imsobear** [comment]
@chenbin92 简单做的话就用户项目支持 css-modules，区块组件模板之类的保持现状，这样是否可行？

**Comment by imsobear** [comment]
已支持：https://alibaba.github.io/ice/docs/advanced/webpackrc#CSS%20Modules

**Comment by hoverCow1990** [comment]
地址无法进入

> 已支持：https://alibaba.github.io/ice/docs/advanced/webpackrc#CSS%20Modules

该地址链接有问题

**Comment by DoranYun** [comment]
> 地址无法进入
> 
> > 已支持：https://alibaba.github.io/ice/docs/advanced/webpackrc#CSS%20Modules
> 
> 该地址链接有问题

新版文档链接地址 https://ice.work/docs/cli/basic/style#CSS%20Modules
