### ISSUE TITLE
Timeline 组件无法按需显示子项(无法传入 null)

### ISSUE THREAD

**Issue by bdoycn** [alibaba/ice#1025]
## 环境信息

- 操作系统：
- Iceworks 版本： 2.11.3

## 问题描述
因为需要按需显示 Timeline 中的子项, 所以可能会传入 null
但是因为 timeline 组件没有过滤 null 然后使用了 react.cloneElement 导致报错

我目前的解决方法是修改了 timeline 的源码过滤掉了 null 元素
// timeline.js
// 原
 children = _props.children;
// 改
 children = _props.children.filter(item => !!item);

**Comment by boiawang** [comment]
@youluna 看下这个问题有没有解决
