### ISSUE TITLE
如何使用可以刷新的路由

### ISSUE THREAD

**Issue by wqh17101** [alibaba/ice#1027]
## 环境信息

- 操作系统：win10
- Iceworks 版本： 2.10.0

## 问题描述

使用 ICEWebSite Homepage 模板建立的项目，默认使用的是hashrouter
现在有一些样式通过这种router跳转之后不会自动reload，需要刷新页面才行
要怎样才能使用跳转刷新的router
我尝试直接把routerconfig里面的hashrouter改成browserrouter，并不work

**Comment by chenbin92** [comment]
现在开发的是单页应用，基于 react-router 单页应用切换路由不会刷新

了解下单页应用和多页应用的区别

**Comment by wqh17101** [comment]
我明白了，不知道你有没有用过highlight.js用来加载高亮code block，他只会在index加载，如果用hash跳转子页面，就不会加载css，需要reload页面才行，有什么好的解决方案么 @chenbin92

**Comment by chenbin92** [comment]
> 我明白了，不知道你有没有用过highlight.js用来加载高亮code block，他只会在index加载，如果用hash跳转子页面，就不会加载css，需要reload页面才行，有什么好的解决方案么 @chenbin92

可以试试在 index.html 引入对应的 js、css 的 CDN 文件全局加载
