### ISSUE TITLE
Table组件的children支持问题

### ISSUE THREAD

**Issue by Symous** [alibaba/ice#1033]
## 环境信息

- 操作系统：macOS 10.14
- Iceworks 版本： 2.12.0

## 问题描述

Table组件目前仅支持Table.Column,Table.CloumnGroup等children组件，但是这样会带来一些问题：
比如在做权限管理的时候，假如我们想要根据用户不同的身份而控制某一Column是否渲染，使用高阶组件在内部判断权限一个很不错的方法，但是高阶组件并不是目前收支持的组件之一，请问有没有支持类似需求的打算？
## 错误信息
![image](https://user-images.githubusercontent.com/13534034/47950203-cf865100-df89-11e8-8ddd-06843656571f.png)

**Comment by youluna** [comment]
Table仅支持Table.Column,Table.CloumnGroup等作为children，跟实现你的需求不冲突的。
```jsx
<Table>
   <Table.Column />
   <Table.Column />
   { isShow ?  <Table.Column /> : null}
</Table>
```

**Comment by Symous** [comment]
@youluna 这样是可以实现的没错，但是就需要提前把权限判定好，并不是很优雅（不想在页面内写判断的逻辑），如果Table.Column可以直接使用高阶组件包裹，并传入一个auth prop，这样看起来会好很多。
