### ISSUE TITLE
自定义模板取消勾选侧边导航后生成项目报错

### ISSUE THREAD

**Issue by Empireo** [alibaba/ice#1038]
## 环境信息

- 操作系统：Mac OS Sierra 10.12.5
- Iceworks 版本： 2.12.0

## 问题描述

使用自定义模板生成项目 -> 取消勾选侧边导航 -> 安装依赖 -> 启动调试服务 -> 打开页面 -> 报错

![](https://img.alicdn.com/tfs/TB1FGlSnNTpK1RjSZFGXXcHqFXa-750-486.png "")

## 错误信息

![](https://img.alicdn.com/tfs/TB1DoNYnMHqK1RjSZFkXXX.WFXa-1032-1240.png "")

**Comment by ScarboroughCoral** [comment]
我也有这个问题！！！！急需帮忙！！

**Comment by chenbin92** [comment]
已修复
