### ISSUE TITLE
menu 切换，layout 会进行刷新的问题

### ISSUE THREAD

**Issue by guoxunbo** [alibaba/ice#1039]
因为当前设计是route和layout绑定在一块。导致了我可能相同的layout也会导致每次layout都重新加载。
这个有什么好的办法可以解决么。。。看了好久了。没找到解决方案。求助

**Comment by yuanyan** [comment]
我用iceworks里创建了一个项目试了下 layout是不会被重新加载的

**Comment by chenbin92** [comment]
@guoxunbo 参考这里修改一下代码
