### ISSUE TITLE
无法通过模板创建项目

### ISSUE THREAD

**Issue by asktalk** [alibaba/ice#1040]
## 环境信息
window10 

- 操作系统：
- Iceworks 版本： 

## 问题描述

无法通过模板创建项目

## 错误信息
![image](https://user-images.githubusercontent.com/4530218/48057695-9c44fb80-e1ef-11e8-9563-5caafd5b641e.png)

**Comment by yuanyan** [comment]
选择一个空目录进来创建试试

**Comment by Empireo** [comment]
已确定 Windows 系统下部分模板创建 koa 项目会产生这个 bug，我们将在本周发布的版本修复

**Comment by chenbin92** [comment]
Fixed
