### ISSUE TITLE
添加区块弹窗 tab 热键与搜索框冲突

### ISSUE THREAD

**Issue by Empireo** [alibaba/ice#1043]
## 环境信息

- 操作系统：Mac OS
- Iceworks 版本：2.12.0 

## 问题描述

添加区块弹窗中，搜索框获得焦点后，按方向键← →键无法移动搜索框光标，而是切换了 tab

![](https://img.alicdn.com/tfs/TB16ex_n3HqK1RjSZJnXXbNLpXa-982-712.png "")

**Comment by yuanyan** [comment]
感谢反馈，搜索放在了tab切换内部的原因

**Comment by chenbin92** [comment]
Fixed
