### ISSUE TITLE
启动失败：a javascript error occurred in the main process

### ISSUE THREAD

**Issue by ting198791** [alibaba/ice#1053]
## 环境信息

- 操作系统：win10
- Iceworks 版本：  2.12.0

## 问题描述
[启动失败：

## 错误信息

![qq 20181110102431](https://user-images.githubusercontent.com/16252594/48296510-dbff3200-e4d2-11e8-8cb8-0ac125f526ed.png)

**Comment by Empireo** [comment]
启动应用程序失败了？应用程序主窗口可以出现吗

**Comment by imsobear** [comment]
失效问题，如果还存在麻烦再 reopen 下 issue.
