### ISSUE TITLE
win10新建页面无法保存

### ISSUE THREAD

**Issue by renxiang0628** [alibaba/ice#1055]
## 环境信息

- 操作系统：
- Iceworks 版本：

**Comment by Empireo** [comment]
感谢反馈，可能和你的网络环境有关，我们会在之后的版本加强过程提示并设置超时时间

**Comment by fenglai0802** [comment]
最新版本（2.17.0）对网络做了整体优化。你重新使用看看，是否还有相同问题。如果有的话，重新打开这个issue并附上截图信息 方便我们排查 谢谢
