### ISSUE TITLE
node 11.1.0 yarn build fail

### ISSUE THREAD

**Issue by kalsolio** [alibaba/ice#1059]
## 环境信息
node 11.1.0
- 操作系统：
- Iceworks 版本： 

## 错误信息

yarn build
yarn run v1.12.3
warning package.json: No license field
$ ice build
ice-scripts 1.7.1
sassInfo node-sass	4.9.0	(Wrapper)	[JavaScript]
libsass  	3.5.4	(Sass Compiler)	[C/C++]
ReferenceError: internalBinding is not defined
    at fs.js:25:1
ice-scripts exited unexpectedly.

**Comment by imsobear** [comment]
重装依赖试下，看起来是底层依赖问题，如果还有问题再 reopen 下。
