### ISSUE TITLE
构建项目之后index.js 文件很大，工具是否内置压缩功能？

### ISSUE THREAD

**Issue by Jeffery0** [alibaba/ice#1060]
## 环境信息

- 操作系统：
- Iceworks 版本： 
2.12.0
## 问题描述
构建项目之后index.js 文件很大，工具是否内置压缩功能？

**Comment by chenbin92** [comment]
构建生产环境默认就是已经压缩了，可以通过 `ice dev  --analyzer` 看看依赖的分析
