### ISSUE TITLE
Fusion官方物料相关问题

### ISSUE THREAD

**Issue by tao1991123** [alibaba/ice#1061]
## 环境信息

- 操作系统：
- Iceworks 版本： 
2.12.1
## 问题描述

1. 自定义物料 封面无法显示,经查看，iceworks默认给所有alicdn.com域名加了250x250后缀，导致 https://alifd.alicdn.com/materials/@alifd/ice-user-traffic-stastistics/0.1.9/screenshot.png_250x250.jpg 无法访问。
![](https://img.alicdn.com/tfs/TB1nP.8pFzqK1RjSZFvXXcB7VXa-2582-1430.png)

2. fusion官方物料，地址更换为 https://fusion.design/api/v1/sites/1/materials, 文案更换为: Fusion官方物料源。聚合，极致，效率尽在https://fusion.design

**Comment by chenbin92** [comment]
@Empireo  这个问题可以快速修复掉，只对 ice 的物料源做处理就行

**Comment by imsobear** [comment]
@chenbin92 @tao1991123 已修复，下周发版

**Comment by chenbin92** [comment]
@imsobear 效率👍
