### ISSUE TITLE
上传组件ie兼容问题

### ISSUE THREAD

**Issue by sc8816** [alibaba/ice#1062]
## 环境信息

- 操作系统：widows
- Iceworks 版本： 

## 问题描述
上传组件，ie上传会显示文件的路径
谷歌：
![image](https://user-images.githubusercontent.com/30044191/48658246-8fd76300-ea79-11e8-9d89-dca80fd006cc.png)
IE：
![image](https://user-images.githubusercontent.com/30044191/48658254-bbf2e400-ea79-11e8-8220-e24274d97a3c.png)

**Comment by imsobear** [comment]
@sc8816 只是显示的信息不一样？功能有问题吗？

**Comment by sc8816** [comment]
功能是ok的就是显示不一样，看起来有点不雅观

**Comment by tao1991123** [comment]
> 功能是ok的就是显示不一样，看起来有点不雅观

具体是IE几?

**Comment by imsobear** [comment]
@sc8816 我们内部对了下，这个是 IE 的 API 不一致问题导致的，不影响功能的话先保持现状，如果影响到功能使用我们到时候再看下，谢谢反馈 😈

**Comment by sc8816** [comment]
好的，打扰了
