### ISSUE TITLE
hasLimitHint  属性失效

### ISSUE THREAD

**Issue by iamcaochong** [alibaba/ice#1063]
## 环境信息

- 操作系统： Windows7
- Chrome浏览器版本： 59.0.3071.115

## 问题描述
![image](https://user-images.githubusercontent.com/18344969/48659915-aab6d100-ea93-11e8-8e41-4fcae1f4b04f.png)

中文输入法下，输入超出限制的字符数，鼠标左键点击输入框中任意位置，可以输入；
经验证，chrome最新版本不会出现这个问题。

## 错误信息
hasLimitHint 属性失效

**Comment by imsobear** [comment]
@iamcaochong 看起来跟 chrome 版本有关系，现在这个问题是否还存在，不存在的话我先关掉 issue 了
