### ISSUE TITLE
使用树形控件Tree, checkedKeys受控模式下 设置 checkStrictly=false 报错

### ISSUE THREAD

**Issue by liulingli** [alibaba/ice#1096]
使用树形控件Tree, checkedKeys受控模式下 设置 checkStrictly=false 保存
![image](https://user-images.githubusercontent.com/15230114/48976855-85e0e000-f0c9-11e8-8133-e528de53d23a.png)

![image](https://user-images.githubusercontent.com/15230114/50624414-e67dfb00-0f5a-11e9-8893-8fa89d7f90dc.png)
使用递归渲染节点的时候， 节点改变，treeNodesStates 未更新，导致报错

**Comment by imsobear** [comment]
组件问题麻烦给一个重现的 demo: https://codesandbox.io/s/y25zjnzl49

**Comment by liulingli** [comment]
更新版本后，没有问题了

**Comment by chenbin92** [comment]
请提供可复现的 demo 在重新打开该 issue
