### ISSUE TITLE
FormBinder1.0.0 组件warn提示问题

### ISSUE THREAD

**Issue by mopsky** [alibaba/ice#1099]
## 环境信息

- 操作系统：
- Iceworks 版本：  2.12.0

## 问题描述
FormBinder从0.x升级到1.0后，console里一堆的warning
```js
Unknown prop rule in <FormBinder> component，For Details，see https://github.com/yiminghe/async-validator
```
看了下源代码
![formbinder](https://user-images.githubusercontent.com/18085384/49126558-fde41b80-f2fe-11e8-8089-6d12d0177981.png)

这个意思是，props里要把所有的都传进去才不会有warn？有点看不懂

## 错误信息

```js
Unknown prop rule in <FormBinder> component，For Details，see https://github.com/yiminghe/async-validator
```

**Comment by chenbin92** [comment]
https://github.com/alibaba/ice/pull/1108
