### ISSUE TITLE
点击启动调试服务报错

### ISSUE THREAD

**Issue by mowatermelon** [alibaba/ice#111]
> 步骤一 在编辑器中输入以下指令，项目服务启动成功。

```bash
npm rebuild node-sass # success
npm run start # success
```

![image](https://user-images.githubusercontent.com/18508817/35961284-15a8a252-0ce8-11e8-8f4d-4eb0b396e18d.png)

> 步骤二 尝试在`Iceworks`中选择页面模版，进入模版页面直接报错，提示说`node`环境存在指定问题，需要执行`npm rebuild node-sass --force`。

![image](https://user-images.githubusercontent.com/18508817/35961347-45445d1c-0ce8-11e8-82cf-2ad36e1e4d94.png)

> 步骤三 停止编辑器中正在运行的服务，执行`npm rebuild node-sass --force`，命令执行失败。

![image](https://user-images.githubusercontent.com/18508817/35961420-98998154-0ce8-11e8-810d-8b0ab4ca4c17.png)

> 步骤四 到`Iceworks`启动调试服务，直接报错，提示说`node`环境存在指定问题，需要执行`npm rebuild node-sass --force`，错误提示和步骤二一样。

> 总结&&疑惑

`Iceworks`项目是不能在命令行中执行服务吗，必须要使用`Iceworks`默认调试启动吗？

**Comment by yujiangshui** [comment]
node-sass 是一个跟操作系统、node 版本 相关的二进制 binding 包，iceworks 为了彻底包裹 node 等环境，内置了一套 node 工具，与此同时也内置了对应版本的 node-sass 包。

因此使用 iceworks 生成项目并安装依赖、启动、构建等，使用的是 iceworks 内置 node + node-sass。所以当你用命令行启动，需要执行 `npm rebuild node-sass` 重新构建 node-sass 换成跟你系统匹配的版本。

所以当你安装好了跟你系统匹配版本的 node-sass，再在 iceworks 界面中用 iceworks 内置的 node 去启动就会出现问题。

此时如果你需要使用 iceworks 继续操作，需要 rm -rf 掉命令行安装的 node-sass，通过 iceworks 项目列表中的『安装依赖』相关功能进行安装。

**Comment by yujiangshui** [comment]
需要排查给出合理的修复提示或者避免建议。

**Comment by noyobo** [comment]
1. 在 window 环境下的  node-sass 使用问题，这个我排查下。
