### ISSUE TITLE
增加任意区块都提示区块依赖安装失败

### ISSUE THREAD

**Issue by T-baby** [alibaba/ice#1112]
## 环境信息

- 操作系统： Win10 1803
- Iceworks 版本：2.13.0

## 问题描述

增加任意区块都提示区块依赖安装失败

## 错误信息

Cannot read property 'dependencies' of undefined
TypeError: Cannot read property 'dependencies' of undefined
    at file:///C:/Users/xxx/AppData/Local/Programs/iceworks-desktop/resources/app/renderer/home.js:8007:33
    at 

还有就是有其它主题吗？

**Comment by T-baby** [comment]
发现的第二个问题：
生成页面时报错
read ECONNRESET
Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TLSWrap.onread (net.js:615:25)

**Comment by T-baby** [comment]
另外为什么不能可视化删除一个页面或者调整已经有的页面的模块呢？

**Comment by chenbin92** [comment]
@T-baby  删除功能正在做，其实删除和调整页面的模块都是高危操作，比如区块下载到你项目之后，你已经集成了业务逻辑或者页面之间有相关联的依赖，如果通过 GUI 能快速删除，那么正在运行的项目就可能挂了，所有目前我们在做的删除功能也是会分析一些相互的依赖，并给出二次确认提示是否要删除之类的。

**Comment by T-baby** [comment]
增加任意区块都提示区块依赖安装的问题我已经解决了，Iceworks是默认保存在C盘，但是程序没有默认获取管理员权限所以导致无法写入C盘，用管理员权限后正常。

但是生成页面的报错，我还没发现是为什么。

**Comment by chenbin92** [comment]
@T-baby 这个是 iceworks 内部代码引起的错误，更新到 2.17.x 以上的版本已修复
