### ISSUE TITLE
Iceworks 2.13.0 版本无 def 插件

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#1117]
## 环境信息

- 操作系统：
- Iceworks 版本： 

## 问题描述
![](https://static.dingtalk.com/media/lADPDgQ9qXzTQFbNAwjNBZk_1433_776.jpg_620x10000q90g.jpg)

**Comment by imsobear** [comment]
可能是网络问题，没排查出具体结果，暂时通过修改本地配置解决
