### ISSUE TITLE
iceworks 安装依赖失败

### ISSUE THREAD

**Issue by torns** [alibaba/ice#1118]
到 iceworks app 目录下安装依赖遇到
404 Not Found: @ali/iceland-data-engine@^0.4.27

**Comment by chenbin92** [comment]
https://unpkg.com/@ali/iceland-data-engine/ 这个包确实不存在，我们排查一下，感觉反馈

**Comment by imsobear** [comment]
@torns 修复了，麻烦再重试下

**Comment by orchie** [comment]
> @torns 修复了，麻烦再重试下

npm err write after end
出来好几行 然后不动了……
