### ISSUE TITLE
Slide组件路由切换会报错This is a no-op

### ISSUE THREAD

**Issue by j787701730** [alibaba/ice#1125]
## 环境信息

- 操作系统：windows
- Iceworks 版本： 2.12

## 问题描述
![image](https://user-images.githubusercontent.com/23625690/49502126-69099100-f8af-11e8-99d2-abd151624925.png)

## 错误信息
```js
index.js:2178 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in InnerSlider (created by Slider)
    in div (created by Slider)
    in Slider (created by Home)
    in div (created by Col)
    in Col (created by Home)
    in div (created by Row)
    in Row (created by Home)
```

**Comment by chenbin92** [comment]
@j787701730  提供一下复现示例

**Comment by j787701730** [comment]
![image](https://user-images.githubusercontent.com/23625690/49572912-bea97080-f977-11e8-918d-fa9ca3ff4dd3.png)
在isMoble和pc下都有Slider, 在跳转页面或者在改变窗口大小模拟手机端, 会上面的错误.

**Comment by youluna** [comment]
请给下使用的组件版本及最小复现demo https://codesandbox.io/s/kmy7zjr7l3
