### ISSUE TITLE
图片路径报错问题

### ISSUE THREAD

**Issue by supermanzhangbin** [alibaba/ice#1146]
## 环境信息
mac 10.14.4
- 操作系统：
- Iceworks 版本： 
2.13.0
## 问题描述
从已有页面进行添加的区块则需要手动引入,手动引入之后,如果有图片路径,此时src是错误的.
具体错误是多加了一个 "
这是我没改动过的文件:
src={require('./images/TB1R9Ius1uSBuNjy1XcXXcYjFXa-3840-900.jpg"')}

解决方法,手动去掉 "

**Comment by chenbin92** [comment]
手动引用有改变区块的路径吗

**Comment by supermanzhangbin** [comment]
> 手动引用有改变区块的路径吗

没有,就直接引入组件相对路径,如果组件内有图片,图片的src就会莫名多出一个 " , 会报错.

**Comment by chenbin92** [comment]
贴一下示例代码，图片是需要相对路径引用的

**Comment by supermanzhangbin** [comment]
> 贴一下示例代码，图片是需要相对路径引用的

我又试了一下,没有这种问题了.可能修复了.谢谢
