### ISSUE TITLE
如何和服务端进行交互？

### ISSUE THREAD

**Issue by adamqqqplay** [alibaba/ice#115]
请问如何从服务端的api中获取数据更新数据？
我只看见了mock文件夹下的模拟数据，希望能介绍一下，教程里也没看见怎么操作

**Comment by chenbin92** [comment]
在需要数据交互的区块内，我们通过 `mock` 的方式使用 [axios](https://github.com/axios/axios) 模拟异步加载数据的过程，在实际项目中，需要修改对应的 `API` 接口获取真实的数据从服务端获取数据，进行二次开发。我们推荐使用 [axios](https://github.com/axios/axios) 异步请求数据，但是并不限制你使用 axios，你可以自己选择适合的技术方案。

**Comment by adamqqqplay** [comment]
谢谢回复，还想问一下你们通过mock方式模拟axios加载数据的代码在哪个文件中呢？对应的API接口又是在哪呢？我在生成的项目里面找了一下没有找到。

**Comment by chenbin92** [comment]
模拟数据加载的代码在 `src/pages` 对应的区块内，例如：

```

  componentDidMount() {
    this.getData();
  }

  /**
   * 异步获取数据
   */
  getData = () => {
    axios
      .get('/mock/xxx.json')
      .then((response) => {
        this.setState({
          tabData: response.data,
        });
      })
      .catch((error) => {
        console.log(error);
      });
  };
```

* [项目目录结构说明](https://github.com/alibaba/ice/tree/master/scaffords/ice-design-pro#%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84)

* [axios 使用文档](https://github.com/axios/axios)

**Comment by adamqqqplay** [comment]
谢谢
