### ISSUE TITLE
mock服务没有启动？

### ISSUE THREAD

**Issue by onweer** [alibaba/ice#1151]
## 环境信息

- 操作系统：MacOS 10.14.2 
- Iceworks 版本： 2.14.0

## 问题描述

使用icework创建了一个带Koa2的模板后，定义在目录中的mock数据都拿不到，网络请求都是404，启动调试实际拿到的是相同路径API的数据。 启动另一个没带Koa2的项目 mock有效但mock/index.js文件没有热加载。

## 错误信息

![image](https://user-images.githubusercontent.com/11755669/49852951-9494fa00-fe20-11e8-87a5-bed4e7113b78.png)

![image](https://user-images.githubusercontent.com/11755669/49852969-a24a7f80-fe20-11e8-8107-16f6ce227df2.png)

**Comment by chenbin92** [comment]
你反馈的这个问题我试了下确实存在，我们会安排处理。

但既然有 node 服务，你应该直接用 node 端 mock 接口服务

**Comment by chenbin92** [comment]
使用最新版 ice-scripts，已修复
