### ISSUE TITLE
package.json代理设置或如何解决跨域问题

### ISSUE THREAD

**Issue by franplk** [alibaba/ice#1153]
模板：ICE Design Pro ；
在package.json中设置了 proxy 代理后（跨域问题），接口访问还是mock测试里面的接口。
请问，应该如何设置？或如何解决跨域问题

**Comment by franplk** [comment]
package.json 配置如下：
  "proxy": {
    "/api/**": {
      "target": "https://d.anbangjr.com/lcb_webView",
      "changeOrigin": true
    }
  }

**Comment by franplk** [comment]
package.json 代理配置如下：

  "proxy": {
    "/api/**": {
      "target": "https://domain",
      "changeOrigin": true
    }
  }

**Comment by chenbin92** [comment]
参考： https://alibaba.github.io/ice/docs/advanced/webpackrc#%E4%BB%A3%E7%90%86%E9%85%8D%E7%BD%AE%20-%20proxyConfig

**Comment by myyyy** [comment]
@chenbin92 参考文档已打不开
