### ISSUE TITLE
只能通过 ice work 启动吗?

### ISSUE THREAD

**Issue by caoer** [alibaba/ice#117]
只能通过 ice work 启动吗?
我看见在 package.json 里面的 start 命令是 ice start, 但本地并没有 ice 命令. 可以通过命令行启动吗?

好像只有 mac 和 win 版本的 gui. 这样对于 使用ubuntu的用户就不能使用了吗? ╮(╯_╰)╭

**Comment by yujiangshui** [comment]
可以使用命令行启动，需要系统里有 node 环境，然后先执行 npm rebuild node-sass 然后再执行 npm run start 即可。

但是这样项目在 iceworks 使用时，需要删掉依赖用 iceworks 重新安装，详情可以了解 https://github.com/alibaba/ice/issues/111
