### ISSUE TITLE
断网后意外退出

### ISSUE THREAD

**Issue by shankesgk2** [alibaba/ice#1176]
## 环境信息

- 操作系统：MacOS 10.14.3 Beta (18D21c)
- Iceworks 版本： 2.14

## 问题描述

断网后意外退出

**Comment by fenglai0802** [comment]
@shankesgk2 请问是稳定复现的行为吗。有没有报错信息

**Comment by shankesgk2** [comment]
我刚才试了一下意见不闪退了，版本好像也没更新过（V2.14.0），原来是稳定复现的。现在不闪退了，找不到报错信息

**Comment by fenglai0802** [comment]
暂时关闭 需要具体报错信息。
不过iceworks目前是强依赖网络的，离线情况下的展示都不理想，这块目前也在考虑把数据内置到app中作为兜底。
