### ISSUE TITLE
如果使用 registry.npmjs.org 返回 403 forbidden 

### ISSUE THREAD

**Issue by caoer** [alibaba/ice#118]
因为使用了npm 的私有库. 只能用registry.npmjs.org

但安装失败..返回

npm ERR! 403 Forbidden: @icedesign/img@^0.1.0

**Comment by yujiangshui** [comment]
切换 npm 源可以到“设置”里面进行手动切换。为了国内安装速度，默认我们设置为了淘宝镜像源。
