### ISSUE TITLE
打开项目未自动创建.iceworks文件夹，导致无法创建页面

### ISSUE THREAD

**Issue by zxbit2011** [alibaba/ice#1186]
## 环境信息

- 操作系统：win10
- Iceworks 版本： 2.14.0

## 问题描述
打开项目未自动创建.iceworks文件夹，导致无法创建页面

## 错误信息
不是iceworks项目

**Comment by fenglai0802** [comment]
@zxbit2011 请尝试用管理员权限运行iceworks。

**Comment by fenglai0802** [comment]
@zxbit2011 麻烦把报错信息以截图的形式贴一下
