### ISSUE TITLE
iceworks在mac下全屏使用时的疑似bug

### ISSUE THREAD

**Issue by jasonal** [alibaba/ice#119]
具体有两个问题

1、全屏后，鼠标到顶部唤出标题栏的样式是透明的，感觉很怪，但可以理解为就是这么设计的；
2、在全屏模式唤出标题栏关闭软件时，程序没有完全退出，而是黑色背景。需要在dock中退出程序才行。

操作系统版本：10.13.3
机器为：2017版 macbook pro 13

**Comment by wssgcg1213** [comment]
关于这两个问题, 确实是因为没有考虑到全屏下的效果导致的异常

我们会改进一下, 把 iceworks 的全屏定义为在当前视窗占满全屏的操作, 类似网易云音乐的操作, 就能很好的解决这两个问题 cc @noyobo

**Comment by noyobo** [comment]
1. 设置了透明模式下的样式，目前 electron 是这么设计的。对使用造成了不好的体验，这个再考虑下怎么解决。
2. 在全屏模式下的关闭操作存在问题，已确认。

**Comment by noyobo** [comment]
1. 设置了透明模式下的样式，目前 electron 是这么设计的。对使用造成了不好的体验，这个再考虑下怎么解决。
2. 在全屏模式下的关闭操作存在问题，已确认。

**Comment by jasonal** [comment]
新版试了一下，解决了，感谢～！
