### ISSUE TITLE
构建后的引用的js、css、assets路径 错误

### ISSUE THREAD

**Issue by dpsnet** [alibaba/ice#1201]
## 环境信息

- 操作系统：
- Iceworks 版本： 

## 错误信息
生成的路径都包含了该文本“/ice/scaffold-preview/ice-task-management-admin/”

**Comment by chenbin92** [comment]
可以指定 publicPath 自行修改 https://alibaba.github.io/ice/docs/advanced/webpackrc#%E4%BF%AE%E6%94%B9%20publicPath

**Comment by imsobear** [comment]
@dpsnet 怎么重现？自己有改过配置吗？

**Comment by chenbin92** [comment]
测试未能重现，且提供了接口支持配置
