### ISSUE TITLE
React Search 控件没有 blur 方法

### ISSUE THREAD

**Issue by ldsink** [alibaba/ice#1208]
## 问题描述

React Search 控件没有 blur 方法。

在手机端，点击搜索按钮或者下拉框触发的搜索都会从输入框失去焦点。输入法会自动隐藏。

直接在输入法上点击 enter 之类的，会触发搜索，但是没法失去焦点。输入法还是显示的。

请问 Search 怎么通过逻辑使 input blur。文档只有相关的回调函数。

**Comment by Heluwe** [comment]
目前Search控件不支持在手机端直接使用blur方法，如果想使用input的blur，可先拿到Search组件的实例，再去拿到input的实例去调用blur。
