### ISSUE TITLE
 ice-devtools · Workdir D:\Work\node-work\ice_demo is not empty.

### ISSUE THREAD

**Issue by zxbit2011** [alibaba/ice#1211]
```
$ ice-devtools init
$ ice-devtools init ice-materials-template app

   ice-devtools · Workdir D:\Work\node-work\ice_demo is not empty.
```
![image](https://user-images.githubusercontent.com/25721936/50415862-679d0a00-0858-11e9-8057-496549abe021.png)

**Comment by chenbin92** [comment]
看提示，当前目录不为空。找一个空的项目创建

**Comment by zxbit2011** [comment]
```
$ ice-devtools init ice-materials-template app
   ice-devtools · Local path "app" is invalid.
```
如果不为空目录，又会报错
![image](https://user-images.githubusercontent.com/25721936/50416716-fb70d500-085c-11e9-8047-4f64662ed8dc.png)

**Comment by chenbin92** [comment]
你的版本是什么，ice-devtools 2.x 不支持这种命令，直接 `ice-devtools init` 然后回车即可

**Comment by zxbit2011** [comment]
ice-devtools init   代替  ice-devtools init ice-materials-template app ？
这样是可以，但是不能选择vue物料类型，默认是react不能选择
![image](https://user-images.githubusercontent.com/25721936/50416792-7a660d80-085d-11e9-9f92-41d5574a0b05.png)

**Comment by chenbin92** [comment]
2.x 的版本我们还在开发中，这周会发布大版本

**Comment by zxbit2011** [comment]
哦，有空的vue模板目录没，有链接地址吗？我就可以先不用这个工具。

**Comment by chenbin92** [comment]
@zxbit2011 https://alibaba.github.io/ice/scaffold?type=vue
