### ISSUE TITLE
已有的页面列表未显示

### ISSUE THREAD

**Issue by onweer** [alibaba/ice#1212]
## 环境信息

- 操作系统：MacOS 10.14.2
- Iceworks 版本： 2.14.0 

## 问题描述

![image](https://user-images.githubusercontent.com/11755669/50416366-3245eb80-085b-11e9-9100-51b16d75c143.png)

不清楚这个错误如何去调试,为什么会突然找不到页面和布局了,  看文档后发现可能与routerConfig文件有关, 我的routerConfig定义如下 目录在{root}/client/routerConfig.js: 

```
// 以下文件格式为描述路由的协议格式
// 你可以调整 routerConfig 里的内容
// 变量名 routerConfig 为 iceworks 检测关键字，请不要修改名称

import { getRouterData } from './utils/utils';
import { asideMenuConfig } from './menuConfig';

import UserLogin from './pages/UserLogin';
import UserRegister from './pages/UserRegister';
import Dashboard from './pages/Dashboard';
import Charts from './pages/Charts';
import BaiscCharts from './pages/BaiscCharts';
import Portlets from './pages/Portlets';
import Terms from './pages/Terms';
import Result from './pages/Result';
import Empty from './pages/Empty';
import BasicList from './pages/BasicList';
import CardList from './pages/CardList';
import BasicTable from './pages/BasicTable';
import GeneralTable from './pages/GeneralTable';
import Profile from './pages/Profile';
import Setting from './pages/Setting';
import NotFound from './pages/NotFound';
import Fail from './pages/Fail';
import ServerError from './pages/ServerError';
import Forbidden from './pages/Forbidden';

const routerConfig = [
  {
    path: '/portlets/base',
    component: Portlets,
  },
  {
    path: '/dashboard/monitor',
    component: Dashboard,
  },
  {
    path: '/chart/general',
    component: Charts,
  },
  {
    path: '/chart/basic',
    component: BaiscCharts,
  },
  {
    path: '/list/basic',
    component: BasicList,
  },
  {
    path: '/list/card',
    component: CardList,
  },
  {
    path: '/result/success',
    component: Result,
  },
  {
    path: '/result/fail',
    component: Fail,
  },
  {
    path: '/table/basic',
    component: BasicTable,
  },
  {
    path: '/portlets/terms',
    component: Terms,
  },
  {
    path: '/table/general',
    component: GeneralTable,
  },
  {
    path: '/account/profile',
    component: Profile,
  },
  {
    path: '/account/setting',
    component: Setting,
  },
  {
    path: '/exception/500',
    component: ServerError,
  },
  {
    path: '/exception/403',
    component: Forbidden,
  },
  {
    path: '/exception/204',
    component: Empty,
  },
  {
    path: '/exception/404',
    component: NotFound,
  },
  {
    path: '/user/login',
    component: UserLogin,
  },
  {
    path: '/user/register',
    component: UserRegister,
  },
];

const routerData = getRouterData(routerConfig, asideMenuConfig);

export { routerData };

```

router.jsx如下:

```
/**
 * 定义应用路由
 */
import { Switch, Route } from 'react-router-dom';
import React from 'react';

// 页面布局: 如首页,用户操作,后台管理等是不同的布局模版
import UserLayout from './layouts/UserLayout';
import BasicLayout from './layouts/BasicLayout';

// 按照 Layout 分组路由
// UserLayout 对应的路由：/user/xxx
// BasicLayout 对应的路由：/xxx
const router = () => {
  return (
    <Switch>
      <Route path="/user" component={UserLayout} />
      <Route path="/" component={BasicLayout} />
    </Switch>
  );
};

export default router;

```

**Comment by onweer** [comment]
补充: 

可以添加页面,添加后的文件存在 {root}/src/Page 目录下面, 不是client下面

**Comment by imsobear** [comment]
@fenglai0802 这个问题你跟下

**Comment by fenglai0802** [comment]
> 补充:
> 
> 可以添加页面,添加后的文件存在 {root}/src/Page 目录下面, 不是client下面

请问建的是koa项目么

**Comment by onweer** [comment]
@fenglai0802  嗯,是Koa项目. 
![image](https://user-images.githubusercontent.com/11755669/50417615-696bcb00-0862-11e9-8985-aeeb4b07e416.png)

求救新问题:  
![image](https://user-images.githubusercontent.com/11755669/50417746-f747b600-0862-11e9-8ebd-ada6b7b753cc.png)

**Comment by onweer** [comment]
@fenglai0802 

问题找到了:   应该是iceWorks页面列表的刷新按钮没有重新获取package.json里面的templateType字段, 在中途我把 templateType字段改成了 Egg,  点击iceworks刷新按钮后还是页面列表还是存在的. 所以并未意识到修改了templateType字段会影响到iceworks获取页面列表.   切换项目页不会改变.  只有关闭软件重新启动后才会生效..

**Comment by fenglai0802** [comment]
> @fenglai0802
> 
> 问题找到了: 应该是iceWorks页面列表的刷新按钮没有重新获取package.json里面的templateType字段, 在中途我把 templateType字段改成了 Egg, 点击iceworks刷新按钮后还是页面列表还是存在的. 所以并未意识到修改了templateType字段会影响到iceworks获取页面列表. 切换项目也不会改变. 只有关闭软件重新启动后才会生效..

嗯 iceworks是在app启动时判断运行环境的，中途改变如果不重启确实会导致内部环境判断错误。谢谢你的反馈，目前也在考虑加全局环境重置的按钮方便一些配置更新。

**Comment by fenglai0802** [comment]
> @fenglai0802
> 
> 问题找到了: 应该是iceWorks页面列表的刷新按钮没有重新获取package.json里面的templateType字段, 在中途我把 templateType字段改成了 Egg, 点击iceworks刷新按钮后还是页面列表还是存在的. 所以并未意识到修改了templateType字段会影响到iceworks获取页面列表. 切换项目也不会改变. 只有关闭软件重新启动后才会生效..

您可以加一下[ice的用户群](https://ice.alicdn.com/assets/images/qrcode-5.jpg),，issues回复可能会比较慢，sorry

**Comment by fenglai0802** [comment]
> 求救Chrome调试新问题:
> 
> ![image](https://user-images.githubusercontent.com/11755669/50417754-0464a500-0863-11e9-83d4-b6893768eae0.png)

看图应该是断点的位置response还没被赋值，如果已经走到了console，肯定不会是undefined的
