### ISSUE TITLE
proxyConfig为什么不提供 proxy_set_header的功能

### ISSUE THREAD

**Issue by afeiluo** [alibaba/ice#1216]
https://github.com/alibaba/ice/blob/d242a7f83de6fbc0837c03dc78ef1ba321282711/docs/iceworks/plugins-proxy.md

本地配了host: 
127.0.0.1: xxx_local.afeiluo.com
线上登录了xxx.afeiluo.com
本地起前端项目
访问： xxx_local.afeiluo.com:4444
proxyConfig配置:
"proxyConfig": {
    "/api/**": {
      "enable": true,
      "target": "http://xxx.afeiluo.com",
      "set_header": true   ## 把afeiluo.com下面cookie传递给线上后端服务(xxx.afeiluo.com/api)
    }
  }

**Comment by chenbin92** [comment]
https://github.com/alibaba/ice/issues/1216

**Comment by chenbin92** [comment]
与 https://github.com/alibaba/ice/issues/1217 同一个问题，先关掉了

**Comment by afeiluo** [comment]
> 与 #1217 同一个问题，先关掉了
不是同一个问题，#1217是问set_header #1216是问rewrite url
