### ISSUE TITLE
proxyConfig为什么不提供rewrite的功能

### ISSUE THREAD

**Issue by afeiluo** [alibaba/ice#1217]
https://github.com/alibaba/ice/blob/d242a7f83de6fbc0837c03dc78ef1ba321282711/docs/iceworks/plugins-proxy.md

配置了：
"proxyConfig": {
    "/api/**": {
      "enable": true,
      "target": "http://xxx.afeiluo.com"
    }
  }
希望后端收到的请求是: http://xxx.afeiluo.com/** 而不是 http://xxx.afeiluo.com/api/**

**Comment by chenbin92** [comment]
https://github.com/alibaba/ice/issues/1217

**Comment by imsobear** [comment]
https://github.com/chimurai/http-proxy-middleware 请参考这里完整的文档说明

**Comment by imsobear** [comment]
ice-scripts@1.8.10
