### ISSUE TITLE
穿梭框搜索全选后，会选中之前所有的项问题

### ISSUE THREAD

**Issue by tlzzu** [alibaba/ice#1218]
## 环境信息

- 操作系统：window 10
- Iceworks 版本： ^0.2.5
## 问题描述

穿梭框搜索后，点击上面的全选，结果是全选未搜索时的所有项目，而不是搜索之后的项。
如下图：
![image](https://user-images.githubusercontent.com/13477114/50436709-2ec96780-0922-11e9-90f9-3683a96a8517.png)

**Comment by youluna** [comment]
全选按钮在搜索前后都在同一个位置上，功能也应该是一样的，即选择全部数据而非可视区域的数据。
并且Transfer自带的全选会注明当前选择了几项/共几项，不会带来歧义。

如果使用者想改变这样的交互方式，可通过title + defaultLeftChecked/defaultRightChecked实现

**Comment by tlzzu** [comment]
好吧 我们ui要求，左右的全选，改成文字全选，这样就看不到当前选中了多少项了。我们换其他平台的组件了，谢谢
