### ISSUE TITLE
创建项目失败

### ISSUE THREAD

**Issue by daiyun169** [alibaba/ice#122]
依赖添加失败

npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated @types/commander@2.12.2: This is a stub types definition for commander (https://github.com/tj/commander.js). commander provides its own type definitions, so you don't need @types/commander installed!
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN 
> node-sass@4.7.2 install G:\ice\blue\node_modules\node-sass
> node scripts/install.js

lifecycle npm is using C:\Users\qewli12\AppData\Local\Programs\Iceworks\Iceworks.exe but there is no node binary in the current PATH. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
'node' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���

���������ļ���

npm WARN react-transition-group@1.2.1 requires a peer of react-dom@^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN pure-render-decorator@1.2.1 requires a peer of react@^15.0.0 || ^0.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN redbox-react@1.5.0 requires a peer of react-dom@^0.14.0 || ^15.0.0 || ^16.0.0-beta || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @icedesign/scafford-pro@0.1.20 No repository field.
npm WARN @icedesign/scafford-pro@0.1.20 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.7.2 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.7.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\qewli12\AppData\Roaming\npm-cache\_logs\2018-02-12T06_55_52_849Z-debug.log

**Comment by suncunhu** [comment]
也遇到了这个问题， 强烈建议取消自动安装npm依赖包

**Comment by lxlazy** [comment]
widnows环境下自动安装各种报错，我cnpm安装了一次，后面又报了个node-sass的错，安装node-sass就可以运行了……

**Comment by yujiangshui** [comment]
@lxlazy 主要问题在 node-sass 这个 binding 包上面，可以了解下详情： https://github.com/alibaba/ice/issues/111#issuecomment-364034037

这个问题我们还在想怎么优化下，可能需要对是否安装包成功以及 node-sass 报错关键词进行重试或者修复安装等操作，以及提示等。 @noyobo @wssgcg1213
