### ISSUE TITLE
ice自带的终端与iTerm2运行环境不一致?

### ISSUE THREAD

**Issue by onweer** [alibaba/ice#1227]
## 环境信息

- 操作系统： Mac OSX 10.14.2
- Iceworks 版本： 2.14.0

## 问题描述

使用icework安装依赖会报错, 错误是因为有一个ccap@0.6.10包 .
NPM地址:https://www.npmjs.com/package/ccap

icework的日志信息说需要安装 xcode-select. 而iTerm2却不需要, 我的电脑安装了brew时安装了xcode-tool的

在icework中安装如何解决这个问题? 目前直接用iterm2是可以的

## 错误信息

icework安装日志(失败)
![image](https://user-images.githubusercontent.com/11755669/50501551-ef228d00-0a93-11e9-8996-2c790d2702b3.png)

iTeam2安装日志 (成功):

![image](https://user-images.githubusercontent.com/11755669/50501567-08c3d480-0a94-11e9-9d73-4d572e0a006e.png)

**Comment by chenbin92** [comment]
目前 Iceworks 内置了 node/npm 等基础环境， 和系统环境是隔离的。这块正在计划直接复用系统的环境能力。

**Comment by chenbin92** [comment]
更新 2.18.2 版本，默认使用系统环境
