### ISSUE TITLE
浏览器兼容问题

### ISSUE THREAD

**Issue by adamqqqplay** [alibaba/ice#123]
### 1.使用火狐浏览器56.0.2访问预览页面https://alibaba.github.io/ice/#/block/signup-form/preview 时出现错误

页面提示
抱歉, 编译错误: @icedesign/signup-form-block/src/index.js, 麻烦提交 issue 等待修复

按下f12后浏览器提示
Unhandled promise rejection Object { __promise_pendings: Array[0], __promise_progress_listeners: Array[0], __promise_status: "Pending", defer: Object, userConfig: Object, responseData: null, config: Object, timeoutTimer: null, responseText: "", responseXML: null, 等 9 项… }  polyfill.min.js:2:27238

### 2.使用IE11浏览器访问预览页面https://alibaba.github.io/ice/ice-design-pro.html#/ 时出现错误

页面空白，没有任何显示

按下f12后浏览器提示
The above error occurred in the <ProgressTable> component:
    in ProgressTable (created by Dashboard)
    in div (created by Dashboard)
    in Dashboard (created by RouterContext)
    in div (created by IceLayoutMain)
    in IceLayoutMain
    in div (created by IceLayoutSection)
    in IceLayoutSection
    in div (created by IceLayoutLayout)
    in IceLayoutLayout
    in Unknown (created by RouterContext)
    in RouterContext (created by Router)
    in Router

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

SCRIPT438: 对象不支持“from”属性或方法
index.js (56,23695)

SCRIPT5022: undefined
npm (13220,7)

希望能够修复这些浏览器兼容问题，让本项目能在各个浏览器环境中顺利运行

**Comment by yujiangshui** [comment]
@chenbin92 关注下，对于比较新的 IE11 等浏览器，兼容性还是要考虑的。

**Comment by wssgcg1213** [comment]
这里报了两个问题, 1是已知的bug, 站点上这部分对火狐有兼容问题 我会跟进修复

2. 这个我们讨论一下 是我们增加引入 polyfill 还是避免使用这一类静态方法

**Comment by wssgcg1213** [comment]
站点的问题 duplicated to #65

**Comment by luogeng2017** [comment]
https://unpkg.com/@icedesign/ecommerce-scaffold@1.2.3/build/index.html#/goods。
我火狐66.0b1 (64-bit）开发者也存在兼容问题
![标签错位](https://user-images.githubusercontent.com/29565303/51724802-eecce000-2099-11e9-96c6-6635925a0fd5.png)
