### ISSUE TITLE
构建后icon无法显示

### ISSUE THREAD

**Issue by riusksk** [alibaba/ice#1239]
## 环境信息

- 操作系统：macOS 10.14
- Iceworks 版本： 2.14.0

## 问题描述
使用到以下几个icon，调试时正常显示，但构建后直接打开index.html就显示出错：
* ice-icon-stable-gaojingxinxi
* ice-icon-stable-table
* icon-down

![](https://ws4.sinaimg.cn/large/006tNbRwgy1fyrcayj87ij3060022aa8.jpg)

正常显示应该是这样：
![](https://ws3.sinaimg.cn/large/006tNbRwgy1fyrcee69yij305o024t8z.jpg)

**Comment by chenbin92** [comment]
使用的是那个 icon 组件

**Comment by riusksk** [comment]
用的是模板[”ICE Design Lite"](https://unpkg.com/@icedesign/lite-scaffold@1.2.4/build/index.html#/dashboard/monitor)，出错的是左侧边栏icon，以及右上角账号右边的向下箭头
