### ISSUE TITLE
无法找到Sublime Text编辑器

### ISSUE THREAD

**Issue by xb215624874** [alibaba/ice#124]
设置Sublime Text后，打开编辑，error，无法找到编辑器，即使有Sublime Text。另外希望尽快测试webstorm编辑器，习惯了jetbrains家族的东东。

**Comment by yujiangshui** [comment]
麻烦提供下你的操作系统、版本、sublime 配置等，便于我们复现排查。

此外，我们将会在正式版支持唤起 webstorm 编辑器，感谢反馈！ cc @noyobo

**Comment by xb215624874** [comment]
macOS High Sierra 10.13.2; sublime Text2 version 2.0.2;

**Comment by noyobo** [comment]
@xb215624874  支持的是 Sublime Text 3 ，文案部分我优化下。 

现在 Sublime Text 3 已是最新正式版本，麻烦你这边升级版本再尝试下。

**Comment by noyobo** [comment]
webstorm 在 0.1.6 版本发布后支持
