### ISSUE TITLE
Mac,一打开Iceworks就被index.html盖住整个窗口？

### ISSUE THREAD

**Issue by scofield7419** [alibaba/ice#1240]
## 环境信息

- 操作系统：macOS High Sierra
- Iceworks 版本： 2.14.0

## 问题描述
我也是醉了，一打开就被index.html盖住整个窗口？已没有其他的办法可以正常使用icework了。

<img width="870" alt="wx20190102-110059 2x" src="https://user-images.githubusercontent.com/18722770/50579202-012e7200-0e7e-11e9-9f23-f1f426b412ab.png">

**Comment by scofield7419** [comment]
<img width="870" alt="wx20190102-110059 2x" src="https://user-images.githubusercontent.com/18722770/50579223-2327f480-0e7e-11e9-9508-7cb2a13193fd.png">

**Comment by fenglai0802** [comment]
@scofield7419 可以打开 帮助>切换开发人员工具 看下报错的信息是什么。

**Comment by imsobear** [comment]
这个问题 2.17.0 版本已修复，可以重新安装下看看。
