### ISSUE TITLE
Module parse failed: Unexpected character '�' (1:0)

### ISSUE THREAD

**Issue by xb215624874** [alibaba/ice#125]
import img from 'xxx.png';
-------------------------
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)

**Comment by yujiangshui** [comment]
@noyobo @wssgcg1213 应该是目前官方 webpack 配置中没有添加 png 的 loader 导致的？

**Comment by wssgcg1213** [comment]
会在 ice-scripts@1.0.0 中添加

**Comment by wssgcg1213** [comment]
https://github.com/alibaba/ice/pull/116/commits/ab9c6c5adbeb60e130594f1439ff13af8686811e

**Comment by wssgcg1213** [comment]
cc @noyobo
