### ISSUE TITLE
formbinder 动态修改validator时不更新校验规则

### ISSUE THREAD

**Issue by feedcollision** [alibaba/ice#1250]
## 环境信息

- 操作系统：mac&windows
- Iceworks 版本： 2.13.0

## 问题描述

当formbinder的validator动态变化时，实际生效的validator不更新

https://github.com/alibaba/ice/blob/master/react-materials/components/form-binder/src/FormBinder.jsx
应该是上方文件中120行
   JSON.stringify(nextRules) !== JSON.stringify(this.rules)
中对对象中的函数不做JSON.stringify导致未更新

预期能够动态更新validator

**Comment by jasonintju** [comment]
@feedcollision 
@ice/form 组件已支持 rules 的动态更新，可以试用一下
