### ISSUE TITLE
App Unhandled Rejection at:, [object Promise], 'reason:', Error: spawn EACCES

### ISSUE THREAD

**Issue by changqing91** [alibaba/ice#1259]
## 环境信息

- 操作系统：Windows x64
- Iceworks 版本： 2.14.0

## 问题描述

打开后报错，然后一直白屏。

## 错误信息

App Unhandled Rejection at:, [object Promise], 'reason:', Error: spawn EACCES

**Comment by fenglai0802** [comment]
@changqing91 用管理员权限运行看下是否可以解决。
