### ISSUE TITLE
手机适应性问题。

### ISSUE THREAD

**Issue by xb215624874** [alibaba/ice#126]
能不能把高度自适应屏加入判断？让移动终端打开起码不丑。
![b02a3341-0331-498c-8315-a924cabb785a](https://user-images.githubusercontent.com/16144736/36312534-c52b70ec-1369-11e8-8b17-23ea6448872d.png)

**Comment by yuanyan** [comment]
模版里默认暂时需要加viewport meta适配移动端

**Comment by chenbin92** [comment]
@yuanyan  @xb215624874 已处理

**Comment by wssgcg1213** [comment]
今天跟 @chenbin92 讨论了, 整体上移动端适配分两步走  

1. 不乱
2. 响应式

做到第一步只需在 Layout 和 html(meta) 上做处理即可, 第二步需要将所有 block 进行栅格化改造  

第一步方案如下: 
- 增加 viewport width=device-width  
- header, footer 部分固定的 `width: 1200px` 改写成 `width: 100%; max-width: 1200px;` 

手机效果如下 

![image](https://user-images.githubusercontent.com/3922719/36579950-fcf0f7b8-18a0-11e8-8ae0-857dab3ed4d6.png)

**Comment by wssgcg1213** [comment]
已有的项目麻烦 @xb215624874 按照上边的方法操作一下, 脚手架模板我们已经修改掉了, 新创建的会解决

**Comment by xb215624874** [comment]
3Q
