### ISSUE TITLE
基于Ant Design Pro的项目如何接入ice-work

### ISSUE THREAD

**Issue by qianxuemin** [alibaba/ice#1267]
## 环境信息

- 操作系统：macOS
- Iceworks 版本： 2.15.0

## 问题描述

基于 Ant Design Pro 初始化的项目，目录结构与ice-work中的目录结构不太一致，应该如何接入飞冰呢?

**Comment by imsobear** [comment]
@qianxuemin 目前只能支持启动调试和构建两个功能，添加页面、区块的目前不太好支持。

**Comment by qianxuemin** [comment]
后续会考虑支持基于Ant Design Pro 的添加页面，区块功能吗？

**Comment by WongWaiChung1015** [comment]
有ant design的視頻教學嗎？
