### ISSUE TITLE
登录页-物料归类错误

### ISSUE THREAD

**Issue by keepnode** [alibaba/ice#127]
物料中，登录页被归类到“表单”这个分类中。
<img width="636" alt="2018-02-19 3 48 50" src="https://user-images.githubusercontent.com/8043218/36367274-e676d5aa-158c-11e8-80dc-6ebdf428ad64.png">

“登录页”这个分类下不应该是个banner

<img width="327" alt="2018-02-19 3 48 28" src="https://user-images.githubusercontent.com/8043218/36367277-e9f180e0-158c-11e8-961e-8eae07d23826.png">

**Comment by yujiangshui** [comment]
@chenbin92 优化下名字。

@keepnode 登陆页这里可能有点歧义，下面的 登陆页 其实是指用户一进来的页面，有的可能是产品介绍首页，有的后台可能是直接登录。英文中是 LandingPage，但翻译出来的登陆在中文可能会被误解为带登录表单的页面。

**Comment by yuanyan** [comment]
没有其他更好的命名就叫“欢迎页”吧

**Comment by wssgcg1213** [comment]
另外一个问题, 

一方面, 这里的`分类` 其实是`tag`的意思, 区块是允许同时属于多个tag的  
另一方面, 登录页 是不是属于表单 我觉得就这个区块是不属于的
@chenbin92 再评估一下?

**Comment by chenbin92** [comment]
严格意义上可以增加一个“登录注册页”，可以设计不同风格的登录注册模块，主要区别其实还是背景图和表单的区别，这样从字面意义和第一印象比较容易理解
