### ISSUE TITLE
构建好项目后直接打开index.html后浏览器什么都不显示。

### ISSUE THREAD

**Issue by huangzicong** [alibaba/ice#1273]
## 环境信息

- 操作系统：windows10
- Iceworks 版本： 1.80

## 错误信息
[图片][图片]

**Comment by huangzicong** [comment]
> ## 环境信息
> * 操作系统：windows10
> * Iceworks 版本： 1.80
> 
> ## 问题描述
> ## 错误信息
> 
![r ek ca_ef3 y _o0b qd_5](https://user-images.githubusercontent.com/29749654/50805358-f4ea5f00-132c-11e9-996a-c33b2ce0c40f.png)

**Comment by ztMalone** [comment]
you should change the link of the index.css and the index.js in the index.html file .

**Comment by imsobear** [comment]
排查并修正 js 错误即可
