### ISSUE TITLE
tools中iceworks打包失败

### ISSUE THREAD

**Issue by torns** [alibaba/ice#1274]
## 环境信息

- 操作系统：mac 10.13.6
- Iceworks 版本： 2.15.0
- node 版本： 8.11.4

tools中iceworks工程执行  yarn run dist 打包报错

![qq20190108-144621](https://user-images.githubusercontent.com/23144884/50814740-a4d3c280-1355-11e9-8fbe-1c4c05eecf49.png)

**Comment by imsobear** [comment]
排查下系统依赖，看起来是底层依赖的问题。
