### ISSUE TITLE
Dialog添加图片后弹窗无法居中

### ISSUE THREAD

**Issue by Symous** [alibaba/ice#1277]
## 环境信息

- 操作系统：macOS 10.14
- Iceworks 版本： 2.12.1

## 问题描述

给Dialog组件内部添加一张图片后，Dialog无法再正常的显示在屏幕正中央。
> 示例代码：https://codesandbox.io/s/r0pzm9w3kq

**Comment by imsobear** [comment]
请在 Dialog 上使用这个属性 shouldUpdatePosition={true}，文档有说明
