### ISSUE TITLE
‘使用该模板‘无法下载该模板

### ISSUE THREAD

**Issue by Guxingzhe** [alibaba/ice#1279]
## 环境信息

- 操作系统：
win7
- Iceworks 版本： 
2.15.0

## 问题描述
在【模板】模块里面，选择某个模板，点击‘使用该模板‘，创建过程中弹出链接不了的问题

![image](https://user-images.githubusercontent.com/9564255/50872461-d2bf1280-13fa-11e9-924b-b4cc77285cc6.png)

![image](https://user-images.githubusercontent.com/9564255/50872445-c20e9c80-13fa-11e9-9337-8b6851fb93c6.png)

![image](https://user-images.githubusercontent.com/9564255/50873658-d0a98380-13fb-11e9-99db-981cfe0633ca.png)

**Comment by imsobear** [comment]
切换到 cnpm 然后重试下，如果还有问题辛苦再 reopen 下 issue。
