### ISSUE TITLE
ice-devtools 不支持npm registry私有库的配置

### ISSUE THREAD

**Issue by LittleBreak** [alibaba/ice#1283]
## 环境信息

- 操作系统：windows 10 64
- Iceworks 版本： 2.15.0
- ice-devtools 版本： 2.0.2
- node 版本： 8.11.1
- npm 版本： 5.6.0
## 问题描述

npm registry不支持私有库的配置

## 错误信息

在ice-devtools工具中默认使用`http://registry.npmjs.com`作为仓库地址。如果在公司中使用私有库发布的话，就会执行报错。以下方代码为例。

```
npm run generate
```
会提示 未发布! 禁止提交.因为并不会去查找自定义的仓库地址查找包的信息。

![image](https://user-images.githubusercontent.com/16707072/50942780-cf905900-14c4-11e9-9c15-2a228afea4d9.png)

**Comment by imsobear** [comment]
#1691 同样的问题，功能已支持，欢迎参与 Review: https://github.com/alibaba/ice/pull/1705

**Comment by imsobear** [comment]
ice-scripts@1.9.3 ice-devtools@2.2.1 已支持

通过环境变量传递即可：https://www.npmjs.com/package/ice-npm-utils#custom
