### ISSUE TITLE
使用ICE的官网模板，构建之后是压缩的js，怎么生成原始HTML代码

### ISSUE THREAD

**Issue by fastspringcloud** [alibaba/ice#1289]
## 环境信息
ICE
- 操作系统：Mac
- Iceworks 版本： 最新版

## 问题描述
使用ICE的官网模板，构建之后是压缩的js，怎么生成原始HTML代码
生成原始HTML，方便搜索引擎收录，方便SEO优化

**Comment by tao1991123** [comment]
https://github.com/GoogleChromeLabs/prerender-loader

**Comment by chenbin92** [comment]
目前模板开发方式都是使用的 SPA，如果需要做 SEO 的话，可以对首页做 SSR，或者了解一下社区的方案：

* [SSR](https://medium.freecodecamp.org/server-side-rendering-your-react-app-in-three-simple-steps-7a82b95db82e)
* [prerender-spa-plugin](https://www.npmjs.com/package/prerender-spa-plugin)
