### ISSUE TITLE
New Requirements

### ISSUE THREAD

**Issue by lujianmei** [alibaba/ice#129]
Is there a plan for adding some basic material, like button, select, list etc, so that i can add some basic tools by myself.
And Is there a document for how to add my own template, or items?
Thanks

**Comment by yuanyan** [comment]
添加自定义的区块与模版在我们的计划中，技术方案还在迭代中，已经确定的用户操作上只需要在配置一下就可以，模版与区块的自定义接入规则也会同步放出，整体我们希望在正式版后开始着手做这个事情

**Comment by yujiangshui** [comment]
移步关注 https://github.com/alibaba/ice/issues/341
