### ISSUE TITLE
新加页面，导航没有显示图标

### ISSUE THREAD

**Issue by fangaofeng** [alibaba/ice#1293]
## 环境信息

- 操作系统：win10
- Iceworks 版本： 2.15.0

## 问题描述

在icework新加页面，menu自动添加
  {
    name: 'Nav20',
    path: '/page20',
    icon: 'gaojingxinxi',
  },
期望：
nav20显示图标

结果：
![image](https://user-images.githubusercontent.com/15919475/51010658-42b2d180-1590-11e9-89dd-03748884eeb1.png)
nav20没有图标显示。
只有当nav20有二级菜单时，nav20图标才会显示。

**Comment by fenglai0802** [comment]
@fangaofeng 确定下这个图标是否在图标库里面。
