### ISSUE TITLE
Input多行模式下清空按钮样式问题

### ISSUE THREAD

**Issue by Symous** [alibaba/ice#1294]
## 环境信息

- 操作系统：macOS 10.14
- Iceworks 版本： 2.12.1

## 问题描述

当Input为multiple模式时，hasClear的清空按钮样式出现问题，表现为：
1. 当存在hasLimitHint时，clear处在了下方中间位置
```
    <Input size="large" placeholder="Large" maxLength={20} hasLimitHint hasClear multiple rows={3}/>
```
![image](https://user-images.githubusercontent.com/13534034/51011317-0d5bb300-1593-11e9-8a91-0f930b025400.png)

2. 当不存在hasLimitHint时，clear出在了下方右下角，但是溢出
```
    <Input size="large" placeholder="Large" maxLength={20} hasClear multiple rows={3}/>
```
![image](https://user-images.githubusercontent.com/13534034/51011345-206e8300-1593-11e9-902b-1604d9426b17.png)

**Comment by boiawang** [comment]
使用 `Input.Textarea` 代替
