### ISSUE TITLE
飞冰无法设置带用户名密码验证的代理

### ISSUE THREAD

**Issue by SherrymmZhou** [alibaba/ice#1295]
## 环境信息

- 操作系统：Win7
- Iceworks 版本： 
1.0.0
## 问题描述
没有地方能填写代理的用户名和密码，只能填写ip和端口号，还是无法使用网络，一直报错erro 403
![image](https://user-images.githubusercontent.com/27485208/51011970-c15e3d80-1595-11e9-8a88-82aba15aee36.png)
![image](https://user-images.githubusercontent.com/27485208/51011985-d89d2b00-1595-11e9-98c6-41e5d14d405f.png)

## 错误信息

没有log.log文件

**Comment by imsobear** [comment]
跟代理无关，看起来是文件写入权限问题，建议删除 node_modules 然后重试，如果还有问题再 reopen 下 issue。
