### ISSUE TITLE
官方物料源加载失败

### ISSUE THREAD

**Issue by alextiffy** [alibaba/ice#1321]
## 环境信息
Window 7  node 10.15
- 操作系统：
- Iceworks 版本： 2.15

## 问题描述
![image](https://user-images.githubusercontent.com/990468/51103410-90903980-181d-11e9-90b1-c7bc3758f037.png)

打开飞冰主界面什么都不显示，感觉是连不上网路，是不是因为上网需要有代理的缘故，
导致的，

打开开发工具
![image](https://user-images.githubusercontent.com/990468/51103442-ac93db00-181d-11e9-9459-200ad530d517.png)
事实上我直接访问网址是可以 ，连接的

node  代理也设置过

**Comment by chenbin92** [comment]
这周会处理

**Comment by ariyuan** [comment]
> > 这周会处理
> 
> 这个问题好像好没解决吧？ @chenbin92

Same problem...unable to get system(IE) proxy setting, keep "加载中...."

**Comment by fenglai0802** [comment]
> > 这周会处理
> 
> 这个问题好像好没解决吧？ @chenbin92

你这边遇到的问题能具体描述下吗。
也是一直在loading中，浏览器能正常访问这个地址吗    https://ice.alicdn.com/assets/react-materials.json
如果能，浏览器有没有设置代理。

**Comment by fenglai0802** [comment]
@alextiffy 你是设置了代理，所以浏览器能访问吗？因为iceworks内置了一个node，所以你系统中给node设置代理是不生效的

**Comment by alextiffy** [comment]
我的浏览器是有设置代理，怎么修改node设置代理，或者直接使用浏览器的代理 ，我的系统是window win7

在 2019-03-05 22:45:21，"heiyue" <notifications@github.com> 写道：


@alextiffy 你是设置了代理，所以浏览器能访问吗？因为iceworks内置了一个node，所以你系统中给node设置代理是不生效的

**Comment by fenglai0802** [comment]
@alextiffy 你可以尝试在iceworks提供的终端中执行node的配置，或者给系统设置全局的代理，目前没法使用浏览器的代理。我们这边也在尝试通过其他方式解决

**Comment by Null-Ouwenjie** [comment]
> > > 这周会处理
> > 
> > 
> > 这个问题好像好没解决吧？ @chenbin92
> 
> @zteBill 你这边遇到的问题能具体描述下吗。
> 也是一直在loading中，浏览器能正常访问这个地址吗 https://ice.alicdn.com/assets/react-materials.json
> 如果能，浏览器有没有设置代理。

能访问该链接，但是客户端依旧无法加载模块、组件等物料。

**Comment by zteBill** [comment]
> @alextiffy 你是设置了代理，所以浏览器能访问吗？因为iceworks内置了一个node，所以你系统中给node设置代理是不生效的



> > > 这周会处理
> > 
> > 
> > 这个问题好像好没解决吧？ @chenbin92
> 
> @zteBill 你这边遇到的问题能具体描述下吗。
> 也是一直在loading中，浏览器能正常访问这个地址吗 https://ice.alicdn.com/assets/react-materials.json
> 如果能，浏览器有没有设置代理。

对  一直在loading中，浏览器能正常访问这个地址    浏览器有设置代理 @fenglai0802

**Comment by chenbin92** [comment]
@Null-Ouwenjie  最新的 2.17.0 版本已通过降级方案处理，更新下你的版本看下。另外，如果还有问题麻烦加一下飞冰群沟通，以方便排查

**Comment by ZTrainWilliams** [comment]
最新的 2.17.0 版本仍存在这个问题，另外安装的时候腾讯安全管家提示了一次是否运行软件URL访问，点击了允许，不知道是否存在影响，重新安装，未出现安全管家提示

**Comment by tony1991** [comment]
mac 10.14.2下载后，gui也无法加载物料源

**Comment by assmdx** [comment]
just wait，，我等了很久，然后它加载出来了。。

**Comment by chenbin92** [comment]
https://github.com/alibaba/ice/pull/1657

**Comment by jhs1873** [comment]
所以,现在是解决了这个问题吗?
版本 2.7.1

**Comment by Rackar** [comment]
汇报问题，仅仅vue物料源加载失败，在模板和区块中都失败。其他物料源都没有问题

测试过https://cdn.jsdelivr.net/npm/@icedesign/materails-db@latest/lib/vue-materials.json 浏览器可以打开，没有代理。 windows 10， iceworks 2.17.0

**Comment by Rackar** [comment]
> 汇报问题，仅仅vue物料源加载失败，在模板和区块中都失败。其他物料源都没有问题
> 
> 测试过https://cdn.jsdelivr.net/npm/@icedesign/materails-db@latest/lib/vue-materials.json 浏览器可以打开，没有代理。 windows 10， iceworks 2.17.0

更新iceworks 2.17.1后，问题依旧，###  VUE物料不能加载

**Comment by imsobear** [comment]
目前的策略：首先加载 oss 的资源，如果失败了，再加载 cdn.jsdelivr 的备份资源，这里还失败的话就会出现上面的错误，问题主要还是用户端的网络问题（可能是代理、被屏蔽等等）。

下个版本我们会将物料源数据内置一份在本地，这样就可以彻底解决这个问题了，下个版本预计下周四前后发布。

**Comment by huixisheng** [comment]
>更新iceworks 2.17.1后，问题依旧，### VUE物料不能加载

@Rackar  可以先添加自定义物料源 [`https://cdn.jsdelivr.net/npm/@icedesign/materails-db@1.0.12/lib/vue-materials.json`](https://cdn.jsdelivr.net/npm/@icedesign/materails-db@1.0.12/lib/vue-materials.json) 临时处理

**Comment by imsobear** [comment]
@huixisheng 同样的 url 官方 Vue 物料源无法加载，但是自定义物料源就可以加载？React 的也有这个问题吗？

**Comment by Rackar** [comment]
> > 更新iceworks 2.17.1后，问题依旧，### VUE物料不能加载
> 
> @Rackar 可以先添加自定义物料源 https://cdn.jsdelivr.net/npm/@icedesign/materails-db@1.0.12/lib/vue-materials.json 临时处理



> @huixisheng 同样的 url 官方 Vue 物料源无法加载，但是自定义物料源就可以加载？React 的也有这个问题吗？

这个自定义地址可行，原因是地址里里版本非latest而是1.0.12。react一直无问题

**Comment by imsobear** [comment]
@Rackar 是个 bug，今天会修复发个 patch 版本，谢谢反馈。

**Comment by imsobear** [comment]
2.18.1 版本，这个问题理论上已经彻底解决了，如果还会遇到问题，麻烦再 reopen 下。
