### ISSUE TITLE
react ice design pro表格在edge兼容问题

### ISSUE THREAD

**Issue by chao921125** [alibaba/ice#1324]
## 环境信息

- 操作环境：windows 10  Microsoft Edge
- Iceworks 版本： 2.15.0

## 问题描述

React 物料模版 ICE Design Pro
表格页 - 通用表格 
筛选条件样式问题
输入框未自适应
 ##

**Comment by chenbin92** [comment]
@chao921125  可以提个 PR

**Comment by chenbin92** [comment]
新版本已修复
