### ISSUE TITLE
页面一直在加载中，项目、模板、区块等资源无法正常加载

### ISSUE THREAD

**Issue by zteBill** [alibaba/ice#1327]
## 环境信息

- 操作系统：windows7 64位
- Iceworks 版本： 2.15.0

## 问题描述

首次安装打开软件，页面一直在加载中，项目、模板、区块等资源无法正常加载，重启软件仍然无法加载

## 错误信息

index.js:2470 物料请求失败，地址: https://ice.alicdn.com/assets/react-materials.json，错误：Error: connect ETIMEDOUT 116.207.100.253:443
(anonymous) @ index.js:2470
2index.js:2470 物料请求失败，地址: https://ice.alicdn.com/assets/react-materials.json，错误：Error: connect ETIMEDOUT 119.147.156.254:443
(anonymous) @ index.js:2470
index.js:2470 物料请求失败，地址: https://ice.alicdn.com/assets/rax-materials.json，错误：Error: connect ETIMEDOUT 119.147.156.254:443
(anonymous) @ index.js:2470
index.js:2470 物料请求失败，地址: http://ice.alicdn.com/assets/vue-materials.json，错误：Error: connect ETIMEDOUT 119.147.156.254:80
(anonymous) @ index.js:2470
index.js:2470 物料请求失败，地址: https://ice.alicdn.com/assets/angular-materials.json，错误：Error: connect ETIMEDOUT 119.147.156.254:443
(anonymous) @ index.js:2470
index.js:2470 物料请求失败，地址: https://ice.alicdn.com/assets/react-materials.json，错误：Error: connect ETIMEDOUT 116.207.100.253:443

**Comment by chenbin92** [comment]
https://github.com/alibaba/ice/issues/1321

**Comment by imsobear** [comment]
重复问题 #1321
