### ISSUE TITLE
自动添加依赖时，verbose stack Error: write after end

### ISSUE THREAD

**Issue by banuidp** [alibaba/ice#1329]
## 环境信息

- 操作系统：Win10
- Iceworks 版本： 2.15.0

## 问题描述

verbose stack Error: write after end

## 错误信息
自动添加依赖时，verbose stack Error: write after end

**Comment by fenglai0802** [comment]
尝试
npm install -g npm@latest
npm cache verify
npm i

**Comment by imsobear** [comment]
#1008
