### ISSUE TITLE
这款桌面软件对windows用户似乎很不友好

### ISSUE THREAD

**Issue by zihaocao** [alibaba/ice#1330]
## 环境信息

- 操作系统：win10
- Iceworks 版本： 
2.15（最新）
## 问题描述
正常建立项目没问题，可以正常安装，但是跑不起来，用的是fusion的模板
![image](https://user-images.githubusercontent.com/42928735/51163859-1c659c80-18d6-11e9-92f8-9cc7bdfa8ad8.png)

![image](https://user-images.githubusercontent.com/42928735/51163788-d3ade380-18d5-11e9-9c5c-dc15e2fbf3fc.png)
## 错误信息
![image](https://user-images.githubusercontent.com/42928735/51163836-01932800-18d6-11e9-90a3-bdf2b8db2290.png)

**Comment by bindoon** [comment]
把 package.json 里面的 DEV=1 LIVELOAD=1 先删除

**Comment by chenbin92** [comment]
Fusion 模板已经下线和 ICE 官网模板进行合并
