### ISSUE TITLE
Input placeholder 在IE11中的显示问题

### ISSUE THREAD

**Issue by Symous** [alibaba/ice#1358]
## 环境信息

- 操作系统：Windows 10
- Iceworks 版本： 2.15.3

## 问题描述

在IE11中，Input的placeholder显示为黑色而不是灰色。
![image](https://user-images.githubusercontent.com/13534034/51372786-48348c80-1b39-11e9-97cb-ffad2255d432.png)

**Comment by chenbin92** [comment]
贴一下代码

**Comment by Symous** [comment]
[图片]
就是官方Input的示例代码。

**Comment by chenbin92** [comment]
下载最新版本的 @alifd/next 已处理
