### ISSUE TITLE
不支持手机版自适应吗

### ISSUE THREAD

**Issue by jiankian** [alibaba/ice#136]
创建的lite和pro模板都不支持自适应哦

**Comment by chenbin92** [comment]
@jiankian  目前在移动端的方案是等比缩放，确保页面可预览；整体的响应式方案计划在正式版后逐步迭代；

https://github.com/alibaba/ice/issues/126

<img src="https://img.alicdn.com/tfs/TB1ZoQSarGYBuNjy0FoXXciBFXa-720-1280.jpg" width="320" >  <img src="https://img.alicdn.com/tfs/TB1XvQSawmTBuNjy1XbXXaMrVXa-1242-2208.jpg" width="320" >
