### ISSUE TITLE
iceworks 下载的项目Menu，styleMenu 选择右侧小图标选中不会变

### ISSUE THREAD

**Issue by wqzgh** [alibaba/ice#1360]
这是官网的demo可以
![image](https://user-images.githubusercontent.com/8219427/51375826-ceed6780-1b41-11e9-8b9c-3650c7a1ab4d.png)
下面是iceworks上下载的项目好像不行
![image](https://user-images.githubusercontent.com/8219427/51375958-24297900-1b42-11e9-968c-5ba66895e782.png)
不知道是不是icedesign的版本不一样

**Comment by chenbin92** [comment]
检查是否有样式冲突
