### ISSUE TITLE
ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by Josie-ljw** [alibaba/ice#138]
安装完依赖，启动调试之后，报错：

ReferenceError: exports is not defined
(anonymous function)
http://192.168.18.72:4444/build/index.js:68857:23
./src/pages/Homepage/components/ProductCardList.jsx
http://192.168.18.72:4444/build/index.js:68988:30
__webpack_require__
webpack:/webpack/bootstrap 96767511015d3c417c62:678

**Comment by noyobo** [comment]
`ProductCardList.jsx` 文件的代码可以粘贴看看

**Comment by Josie-ljw** [comment]
import React, { Component } from 'react';
import { Card, Grid, Icon } from '@icedesign/base';
import IceTitle from '@icedesign/title';
import './ProductCardList.scss';
import ProductCard from './ProductCard';
import Img from '@icedesign/img';
import { Link } from 'react-router';

const { Row, Col } = Grid;

export default class ProductCardList extends Component {
    constructor(props) {
        super(props);
        this.state = {
            category: props.goodsList.category,
            goods: props.goodsList.goods
        }
    }

    render() {
        return (
            <div>
                <IceTitle style={{ padding: '0 15px' }}
                    text={this.state.category.category_name}
                    link="http://www.taobao.com"
                    decoration={false}
                />

                <Row className="demo-row">
                    <Col span="1p5">
                        <Img width={210}
                            height={312}
                            src={this.state.category.category_pic}
                            type="cover"
                        />
                    </Col>

                    {this.state.goods.map((good, index) =>
                        <Col span="1p5" key={index}>
                            <ProductCard good={good} />
                        </Col>
                    )}

                    <Col span="1p5">
                        <Card style={{ width: '100%', boxShadow: "none" }}>
                            <Link to={`/more?c=${this.state.category.category_id}`}>
                                <Icon type="arrow-right" size="xxxl" className="more" />
                                <p>浏览更多</p>
                            </Link>
                        </Card>
                    </Col>

                </Row>

            </div>
        );
    }
}

**Comment by Josie-ljw** [comment]
import React, { Component } from 'react';
import { Card, Grid, Icon } from '@icedesign/base';
import IceTitle from '@icedesign/title';
import './ProductCardList.scss';
import ProductCard from './ProductCard';
import Img from '@icedesign/img';
import { Link } from 'react-router';

const { Row, Col } = Grid;

export default class ProductCardList extends Component {
    constructor(props) {
        super(props);
        this.state = {
            category: props.goodsList.category,
            goods: props.goodsList.goods
        }
    }

    render() {
        return (
            <div>
                <IceTitle style={{ padding: '0 15px' }}
                    text={this.state.category.category_name}
                    link="http://www.taobao.com"
                    decoration={false}
                />

                <Row className="demo-row">
                    <Col span="1p5">
                        <Img width={210}
                            height={312}
                            src={this.state.category.category_pic}
                            type="cover"
                        />
                    </Col>

                    {this.state.goods.map((good, index) =>
                        <Col span="1p5" key={index}>
                            <ProductCard good={good} />
                        </Col>
                    )}

                    <Col span="1p5">
                        <Card style={{ width: '100%', boxShadow: "none" }}>
                            <Link to={`/more?c=${this.state.category.category_id}`}>
                                <Icon type="arrow-right" size="xxxl" className="more" />
                                <p>浏览更多</p>
                            </Link>
                        </Card>
                    </Col>

                </Row>

            </div>
        );
    }
}

**Comment by Josie-ljw** [comment]
@noyobo

**Comment by Josie-ljw** [comment]
@noyobo 好的，账号已发你邮箱，添加一下钉钉好友吧

**Comment by Josie-ljw** [comment]
解决了！原因是ProductCardList.jsx的第九行写法导致的编译不通过！
![image](https://user-images.githubusercontent.com/20377604/36627626-69cf2adc-1980-11e8-9c50-d508347111a7.png)
改成这样就可以了，谢谢 @noyobo 技术支持
