### ISSUE TITLE
新建项目启动 demo 的时候报错

### ISSUE THREAD

**Issue by wenqinruan** [alibaba/ice#141]
Failed to compile
./src/pages/EmptyContent/EmptyContent.jsx
Module build failed: Duplicate declaration "EmptyContent"

   7 | import './EmptyContent.scss';
   8 | 
>  9 | export default class EmptyContent extends Component {
     |                      ^
  10 |   static displayName = 'EmptyContent';
  11 | 
  12 |   constructor(props) {
This error occurred during the build time and cannot be dismissed.

**Comment by chenbin92** [comment]
@wenqinruan 已修复 https://github.com/alibaba/ice/pull/139
