### ISSUE TITLE
icework 挺不错的，大大减小了开发成本

### ISSUE THREAD

**Issue by wenqinruan** [alibaba/ice#142]
但是有几个问题想问一下

1. 怎么设置路径别名？现在都是用 '../.../../' 

2. 怎么切换皮肤和自定义皮肤？

**Comment by yujiangshui** [comment]
麻烦问下你之前设置路径别名的方式是什么样的？用的什么 loader 之类做的吗？目前我们保留的最原始的。

切换皮肤和自定义皮肤这块，你的具体需求是什么样的？是希望切换按钮等组件的主色调？还是自定义按钮圆角或者方角。或者是整个站点的风格变成深色、浅色？

**Comment by wenqinruan** [comment]
@yujiangshui loader都是用的 icework 默认的， 我只是想简单的设置一下 webpack（我不确定用的是不是webpack） 的 resolve.alias 参数，后面可能会设置其他参数。

切换皮肤 的意思是，icework 是否内置了一些不同主色调的皮肤，只需要更改配置即可达到切换皮肤。

自定义皮肤，就是说我是否可以 overwrite 整站主色调、栅格间距、按钮大小等，

**Comment by noyobo** [comment]
1. 是使用的  webpack  ， 设置别名这个是一种通用的能力，ice 会增加配置 webpack  的能力，目前暂未开放，后面设计好后再提供使用。 cc @wssgcg1213

**Comment by yujiangshui** [comment]
@wenqinruan 目前 lite 和 pro 两套模板已经支持 dark 和 light 两套主色调的切换了，修改配置即可实现黑、白风格切换。

自定义皮肤对于简单的按钮颜色等配置，我们正在开发配置项，可以配置主色调来修改相关组件的颜色。 cc @wssgcg1213 

但是调整栅格间距、按钮大小这种皮肤配置，我们基于 Fusion 的皮肤配置平台来实现（预计 8 月份开放使用），短时间如果需要定制，可以通过查看 class 在一个 scss 文件中覆盖来解决，可能会比较麻烦。

**Comment by yujiangshui** [comment]
- [ ] webpack 支持配置自定义的 config
- [ ] 主色调自定义配置功能

**Comment by yujiangshui** [comment]
新版已经支持，详情参见 https://zhuanlan.zhihu.com/p/34841259

**Comment by gclsoft** [comment]
dark 和 light 两套主色调的切换是在哪里切换?
