### ISSUE TITLE
应用监控系统模版下载后run就报错

### ISSUE THREAD

**Issue by wangiv2** [alibaba/ice#1430]
## 环境信息

- 操作系统：Mac
- Iceworks 版本： 2.15.5

## 问题描述

应用监控系统模版下载后run就报错

Failed to compile
./client/layouts/BasicLayout/components/Header/index.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):

undefined
             ^
      Undefined variable: "$nav-primary-bg-color".
      in /Users/ivanwang/Desktop/demo/client/layouts/BasicLayout/components/Header/index.scss (line 1414, column 15)

**Comment by chenbin92** [comment]
已修复。已下载的模板可手动先去掉 `$nav-primary-bg-color`  这个变量
