### ISSUE TITLE
有没横向的一二三级,不然一个树有几百个子子项目就展示不了

### ISSUE THREAD

**Issue by gclsoft** [alibaba/ice#1436]
https://alibaba.github.io/ice/component/treeselect#代码示例
有没横向的一二三级,不然一个树有几百个子子项目就展示不了

**Comment by chenbin92** [comment]
![image](https://user-images.githubusercontent.com/3995814/55369808-b11d8500-552a-11e9-8c34-559355099a85.png)

级联了解一下： https://alibaba.github.io/ice/component/cascader
