### ISSUE TITLE
1.x&0.x 混用 css-prefix 无法生效

### ISSUE THREAD

**Issue by Yanzengyong** [alibaba/ice#1456]
使用文档上【老项目 1.x&0.x 共存】的事例，但是无法生效，审查元素中1.x使用的组件自定义前缀是添加上去了，但是没有相应的css样式，应该就是package.json中的themeConfig: {"nextPrefix": "nextfd-"}没有生效，请问怎么解决，还是我忽略了什么其他步骤导致的？

**Comment by Yanzengyong** [comment]
已经解决，解决方案就是重新安装ice-scripts依赖，我猜的是themeConfig应该是在新的ice-scripts中加入的配置，所以需要重新安装（强行瞎猜一波，不过重新安装就好了，至于为什么如果有人知道可以解答一下）

**Comment by cpa0701** [comment]
> 已经解决，解决方案就是重新安装ice-scripts依赖，我猜的是themeConfig应该是在新的ice-scripts中加入的配置，所以需要重新安装（强行瞎猜一波，不过重新安装就好了，至于为什么如果有人知道可以解答一下）

问下你的依赖是全部重装还是只重装了ice-scripts？

**Comment by rilaohn** [comment]
为什么重装了，还是看不到样式呢？请问除了ice-scripts还有其他要配置的吗？

**Comment by imsobear** [comment]
@rilaohn 贴下 package.json 里的 themeConfig 以及入口代码使用 configProvider 的地方，然后描述下你遇到的问题。

@Yanzengyong 猜的没错，的确是因为新版本才支持

@cpa0701 重装 ice-scripts 然后按照文档操作即可 https://alibaba.github.io/ice/docs/upgrade-version
