### ISSUE TITLE
2.16.0  版本 OSS 插件失效

### ISSUE THREAD

**Issue by mr5** [alibaba/ice#1470]
## 环境信息

- 操作系统：Mojave 10.14.3
- Iceworks 版本： 2.16.0

## 问题描述
升级到 2.16.0 之后 OSS 插件失效

## 错误信息
![image](https://user-images.githubusercontent.com/3281595/53030431-be644000-34a5-11e9-99be-3770b7af73a6.png)

**Comment by imsobear** [comment]
2.17.0 已修复，请更新重试下，有问题的话辛苦再 reopen 下。
