### ISSUE TITLE
建议 支持 npm 自定义参数打包

### ISSUE THREAD

**Issue by gooddaddy** [alibaba/ice#1473]
开发的时候经常会区分3个环境，开发环境、测试环境、商用环境。虽然可以在.webpackrc.js中使用webpack.DefinePlugin来自定义全局变量来控制环境，但是感觉这样做够好，因为这样每次发不同环境布版本的时候都需要手动改这个文件，能否让 ice build 指令 支持自定义的参数，ice build --project-type=node --test，这样.webpackrc.js 中就可以通过 const test = process.argv.includes('--test');来判断是否为测试环境：
module.exports = (context) => {
  const { webpack } = context;
  const test = process.argv.includes('--test');
  let isDebug = process.argv.includes('--debug');
  // webpack config
  return {
    plugins: [
      new webpack.DefinePlugin({
        // 此处不能省略 JSON.stringify，否则构建过程会出现语法问题
        ASSETS_VERSION: JSON.stringify('0.0.2'),
        __TEST__: test,
        __DEV__: isDebug,
      }),
    ],
  };
};

**Comment by gooddaddy** [comment]
通过cross-env 已经解决了改问题

**Comment by liulingli** [comment]
@gooddaddy 你cross-env 怎么设置的呀， 我设置了获取到的undefined
