### ISSUE TITLE
使用其他server访问icework构建的资源时，热更新会失效

### ISSUE THREAD

**Issue by Orange-C** [alibaba/ice#1479]
## 环境信息

- 操作系统：macOS
- Iceworks 版本： 2.16.0

## 问题描述

使用自建的server程序访问iceworks构建的前端资源时，前端资源无法实现热更新，显示sockjs无法连接

## 错误信息
![image](https://user-images.githubusercontent.com/8469262/53084450-d4244480-353b-11e9-8952-dd5acd89053b.png)

**Comment by chenbin92** [comment]
自建的 server 是指什么？请描述清楚具体的问题

**Comment by Orange-C** [comment]
比如iceworks构建的页面资源在127.0.0.1:4444/js/index.js
我自己的server有个HTML是这样的，server的地址为127.0.0.1:6001
```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>testPage</title>
</head>

<body>
  <div id="ice-container"></div>
  <script src="127.0.0.1:4444/js/index.js"></script>
</body>

</html>
```
访问127.0.0.1:6001，页面和js可以正常运行，但是iceworks的热更新失效了，页面无法实时热更新并刷新，并出现下图的报错
![image](https://user-images.githubusercontent.com/8469262/53467444-3972bb00-3a91-11e9-9488-b9959f51c7ae.png)

**Comment by imsobear** [comment]
![image](https://user-images.githubusercontent.com/2505411/54801933-1ad49e00-4ca4-11e9-9235-994c40e026f5.png)

并且入口代码会执行多次……

**Comment by DoranYun** [comment]
原因在于创建 socket 链接取的是访问页面的 hostname 和 port 导致 socket 404 了。这段逻辑来自 

https://github.com/facebook/create-react-app/blob/master/packages/react-dev-utils/webpackHotDevClient.js#L62

create-react-app 有两个 issue 在讨论这个问题：

https://github.com/facebook/create-react-app/issues/3814
https://github.com/facebook/create-react-app/issues/4468

**Comment by imsobear** [comment]
一个社区的 MR: https://github.com/facebook/create-react-app/pull/6724

**Comment by Orange-C** [comment]
使用--disabled-reload关闭热更新功能之后报错减少了，但是仍然有sockjs的报错
![image](https://user-images.githubusercontent.com/8469262/57837820-251f9e00-77f6-11e9-8c0c-ee933d00facf.png)

**Comment by Orange-C** [comment]
### 报错原因

1. 项目启动时在js包插入了两段脚本发送socket请求
    * 第一段脚本是webpack-dev-server插入的，用于连接webpack-dev-server同步更新状态
    * 第二段脚本来自ice-scripts（react-dev-utils/webpackHotDevClient），用来连接热更新信息，进行热更新操作
2. 两段插入的脚本发送请求的origin都设定为了window.location，导致当在其他页面引用js包时，socket请求没有发送到编译js的服务器上，产生报错信息。

### 尝试源码方案修复
强制写死源码中两段脚本的路径，成功连接上WDS并且收到更新信息（update.JSON），但是JSON下载路径仍然不对，下载JSON的源码在webpack内核中。深入webpack内核发现路径信息有多个内部变量配置，大部分都是当前页面路径，很难修改，不再深入尝试。

修复后的WDS socket，成功返回
![image](https://user-images.githubusercontent.com/8469262/59320491-26fb5500-8d01-11e9-9574-d51ed79f98ca.png)

HMR update json，路径仍然不对
![image](https://user-images.githubusercontent.com/8469262/59320497-2a8edc00-8d01-11e9-99f9-c0e4aab90927.png)

### 调研旧工具对比
旧的builder-ice工具能实现不同服务器热更新，一部分是因为webpack的__resourceQuery包含了资源服务器的相关信息，热更新脚本中使用这段信息重写了路径，相比之下新webpack的__resourceQuery什么都没有，**猜测是用devServer的缘故，也可能是因为webpack升级**

新老__resourceQuery的区别，上为builder-ice，下为ice-scripts
￼![image](https://user-images.githubusercontent.com/8469262/59320527-3ed2d900-8d01-11e9-864d-d6a3b713aabf.png)
![image](https://user-images.githubusercontent.com/8469262/59320536-41353300-8d01-11e9-847b-184b5db610a5.png)

可能是以下原因：
1. builder-ice使用koa服务器接入webpack-dev-middleware，而ice-scripts使用webpack-dev-server
2. builder-ice使用webpack1，ice-scripts使用webpack4

### 结论
1. 源码修复方案不可行，即使使用上面的社区MR依然无法解决问题，社区MR只修复了第二段脚本，第一段脚本涉及到webpack内核代码修改。
2. 参考builder-ice的方案使用koa服务器接入webpack-dev-middleware，成本较大，而且如果是webpack升级导致，则该方案也无法修复。

**Comment by ClarkXia** [comment]
## 问题原因
react-dev-utils/webpackHotDevClient 中通过 window.location 获取来建立 socket 连接，因此通过其他 server 访问的时候会出现问题。
devServer 指定 hot 配置项后也会默认建立 socket 连接，默认域名端口逻辑同上。
详细分析可以参考上面讨论

## 解决方案
通过 `--disabled-reload` 关闭 ice-scripts 默认热加载能力，禁止加载 react-dev-utils/webpackHotDevClient 模块，修改 package.json 内容：
```json
{
  "scripts": {
     "start": "ice-scripts dev --disabled-reload",
  }
}
```
在 `ice.config.js` 文件中开启 HMR 能力：
```js
module.exports = {
  ...
  chainWebpack: (config, command) => {
    if (command === 'dev') {
      // 指定 4444 端口，保证在访问域名端口和资源域名端口不一致的情况下，能够正常建立 websocket 连接
      config.devServer.hot(true).port(4444);
    }
  },
};
```

> devServer 在 inline 模式下开启 hot 后 HotModuleReplacementPlugin 将会被自动添加

如果希望完整启用 HMR 能力，可以在入口文件中添加如下代码，否则 HMR 默认降级为自动刷新页面，添加代码如下：

```js
// src/index.js
...
if (module.hot) {
  module.hot.accept();
}
```

## 后续优化

调研其他方案替换目前 ice-scripts 中的 react-dev-utils/webpackHotDevClient
