### ISSUE TITLE
ICE 正式版发布计划

### ISSUE THREAD

**Issue by yujiangshui** [alibaba/ice#148]
ICE 将于3月5日左右发布正式版，正式版将包含下述内容：

## 全新的 iceworks

经过一段时间的公测，我们收集了大量的用户反馈并结合设计师重新设计的整个界面、交互和功能，对底层架构进行了重构使其更加稳定。

同时 iceworks 的开源计划将会提上日程，基于该版本的 iceworks 将会开启阿里内部开源流程。

## 稳定丰富的物料

所有物料我们进行了整体的翻新和优化处理，并保证了稳定性可以达到上线标准。此外每周仍然持续补充新的物料。针对模板我们将推出新的 CMS 模板等，适用于 CMS 类的业务。

同时，物料开发链路对外开放将会提上日程，届时将会将物料开发工具、模板等开放出来，支持自己开发、共建、集成等。

## 全新的站点

联合公测期间的反馈和实际使用体验，我们联合设计师重新设计、调整了新版的站点，使其更加美观、稳定、便于使用。

**Comment by dingyiming** [comment]
很赞！

**Comment by yujiangshui** [comment]
正式版已于昨日发布 https://zhuanlan.zhihu.com/p/34265596
