### ISSUE TITLE
分页器分页大小配置切换后，页面大小显示不吻合

### ISSUE THREAD

**Issue by zzysszzy** [alibaba/ice#1486]
## 环境信息

- 操作系统：mac
- Iceworks 版本： 0.x和1.x都有

## 问题描述

https://ice.alibaba-inc.com/ice/component/pagination#%E6%AF%8F%E9%A1%B5%E6%98%BE%E7%A4%BA

![image](https://user-images.githubusercontent.com/10130283/53148136-b1019f80-35e4-11e9-87f9-841e5b0e821c.png)
![image](https://user-images.githubusercontent.com/10130283/53148152-c1197f00-35e4-11e9-8fa4-1567b92c18c5.png)

**Comment by youluna** [comment]
demo没问题的，一共有100项，每页5个一共有20页；每页如果20个，一共有5页
