### ISSUE TITLE
plugins 元素不能是字符串？

### ISSUE THREAD

**Issue by gooddaddy** [alibaba/ice#1500]
## 环境信息

- 操作系统：mac
- Iceworks 版本： 2.16.0

## 问题描述
增加plugins编译不过

.webpackrc.js
module.exports = (context) => {
  return {
    plugins: [
      "react-hot-loader/babel"
    ],
  };
};

## 错误信息
Info: 注入 .webpackrc.js 的配置
(node:25712) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.plugins[8] should be one of these:
   object { apply, … } | function
   -> Plugin of type object or instanceof Function
   Details:
    * configuration.plugins[8] should be an object.
      -> Plugin instance
    * configuration.plugins[8] should be an instance of function
      -> Function acting as plugin
(node:25712) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by chenbin92** [comment]
插件配置示例如下：

```
module.exports = (context) => {
  const { webpack } = context;

  // webpack config
  return {
    plugins: [
      // here
      new webpack.DefinePlugin({
        ASSETS_VERSION: '0.0.1',
      }),
    ],
  };
};
```

插件配置与 webpack 文档配置方式一样，详见：https://webpack.js.org/concepts/plugins/
