### ISSUE TITLE
miniapp是怎样部署到小程序端？

### ISSUE THREAD

**Issue by flietospace** [alibaba/ice#1506]
## 环境信息

- 操作系统：win10
- Iceworks 版本： 2.15.0

## 问题描述

发现有小程序的物料，但是没有文档说明部署方式，需要调整的地方。

请问这方面现在有什么进展么？

**Comment by chenbin92** [comment]
目前这块是按照 h5 的方式在进行，可以按照 h5 的方式进行部署
