### ISSUE TITLE
页面适配问题renderOperator

### ISSUE THREAD

**Issue by Jeffery0** [alibaba/ice#1517]
## 环境信息

- 操作系统：macOS
- Iceworks 版本： 2.15.5

## 问题描述
![image](https://user-images.githubusercontent.com/39700990/53402750-476f0000-39ed-11e9-9241-7f3ec5644db5.png)
TabTable中renderOperator列和其他列没有对齐

**Comment by chenbin92** [comment]
@Jeffery0  提供一个可复现的 demo
