### ISSUE TITLE
自定义区块 暂不支持 生成vue代码吗

### ISSUE THREAD

**Issue by 672064406zerui** [alibaba/ice#1526]
## 环境信息

- 操作系统：
- Iceworks 版本：

**Comment by chenjun1011** [comment]
是的 三月初会支持

**Comment by imsobear** [comment]
支持了之后会通知，问题先关闭掉了

**Comment by imsobear** [comment]
https://github.com/alibaba/ice/issues/973#issuecomment-467737550 看起来这个问题指的是搭建部分，目前没有支持 vue 计划
