### ISSUE TITLE
ice-scripts 如何复制public文件夹下面的静态文件

### ISSUE THREAD

**Issue by QQCif** [alibaba/ice#1536]
## 环境信息

- 操作系统：Ubuntu 16.04
- ice-scripts: 1.8.9

## 问题描述

运行npm run build好像只会复制public文件夹下面的favicon.png和index.html?需要改webpack配置吗

**Comment by imsobear** [comment]
@chenbin92 看了下貌似的确不会，但我们文档说是有这个能力的

**Comment by chenbin92** [comment]
fixed https://github.com/alibaba/ice/pull/1753
