### ISSUE TITLE
预览物料时，出现“抱歉, 编译错误: @icedesign/tab-table-block/src/index.js”

### ISSUE THREAD

**Issue by spemoon** [alibaba/ice#154]
页面地址：https://alibaba.github.io/ice/#/block/tab-table/preview
PS：基本上每个预览页面，点击完预览按钮都会出现编译错误

**Comment by noyobo** [comment]
@spemoon 你使用的浏览器是？

目前已知问题是在 Firefox 下存在预览失败。可以使用 chrome 试试。

**Comment by wssgcg1213** [comment]
如果是 firefox 的问题, 会在月末的正式版修复

**Comment by spemoon** [comment]
@noyobo @wssgcg1213 chrome 63.xxx   win 7。mac底下不会。
下午有看了下log，是某段 https://unpkg.com/@icedesign/data-statistics-block/?meta 的请求超时
