### ISSUE TITLE
下载 tar 包失败（创建项目/新建页面或区块）

### ISSUE THREAD

**Issue by Louis-XIV** [alibaba/ice#1541]
## 环境信息

- 操作系统：win10
- Iceworks 版本： 2.16.0

## 问题描述
创建项目失败

## 错误信息

![image](https://user-images.githubusercontent.com/42088570/53612125-102a6a00-3c0c-11e9-99c0-608172ebf95a.png)

**Comment by chenbin92** [comment]
2.17.0 以上版本支持切换到 cnpm 源，推荐在设置面板将 npm 源设置成 cnpm，可以大幅降低下载 tar 包的失败率
