### ISSUE TITLE
关于win 10 下notification的问题

### ISSUE THREAD

**Issue by mowatermelon** [alibaba/ice#155]
系统
版次  window 10专业版
版本  1709
OS内部版本  162.99.64
node V8.9.1

> 问题描述

界面上原有设计创建项目成功，初始化依赖成功，和调试服务启动成功等等，都会有对应的notification进行状态提示，但是我这个系统版本下，一次都没有出现过notification。

**Comment by yujiangshui** [comment]
看起来是已知的兼容性问题，等我们想想办法 https://github.com/electron/electron/issues/10864
