### ISSUE TITLE
getBabelConfig.js 中并没有取 buildConfig，自定义 babelrc 无效。

### ISSUE THREAD

**Issue by xiongxiaoliang** [alibaba/ice#1557]
![20190304165808](https://user-images.githubusercontent.com/20310785/53724205-5c8fd700-3ea4-11e9-80f0-8941e94f4d73.png)
![20190304165924](https://user-images.githubusercontent.com/20310785/53724221-66193f00-3ea4-11e9-852f-4d3c844123cf.png)
改成这样：
![20190304173817](https://user-images.githubusercontent.com/20310785/53724253-73cec480-3ea4-11e9-9857-073c5b0a3db9.png)

**Comment by imsobear** [comment]
@chenjun1011 代码逻辑层面你看下有没有问题哈。然后原始需求是配置 antd 的按需加载 babel-plugin-import，我觉得这个逻辑可以内置掉。

另外未来如果是 React 体系非 Fusion 体系的业务组件开发，生成 style.js index.scss 之类的逻辑应该需要干掉，这块可以提前考虑下。

**Comment by imsobear** [comment]
ice-devtools@2.19.0 已经支持，antd 的按需和样式依赖已经默认内置，在模板/项目里使用 antd 的话可以通过配置支持：https://alibaba.github.io/ice/docs/advanced/webpackrc#babelPluginImportConfig
