### ISSUE TITLE
ICE Users

### ISSUE THREAD

**Issue by yujiangshui** [alibaba/ice#156]
如果你使用 ICE，欢迎提交信息。将有机会放到 ICE 官方首页的案例墙上。

提交范例：

项目：阿里V任务
logo：![logo](https://img.alicdn.com/tfs/TB1pTXTmr_I8KJjy1XaXXbsxpXa-498-116.png)
URL：https://v.taobao.com/ （如不方便提供则可不提供）

按照上面的格式回复就好。

我们将会选择性的更新到官方首页或者单独的案例墙页面，更新之后将会在这里删掉。

**Comment by yujiangshui** [comment]
项目：青团社
logo：
![image](https://user-images.githubusercontent.com/26426511/37019531-8092780c-2153-11e8-97a6-62f2e7d4b0e0.png)

https://github.com/alibaba/ice/issues/204

**Comment by duotai** [comment]
项目:  微软
logo: 
![microsoft](https://user-images.githubusercontent.com/8444073/45089780-e18d7400-b13f-11e8-8a19-d90bf6812a9b.png)
