### ISSUE TITLE
用户体验

### ISSUE THREAD

**Issue by ayixidelu** [alibaba/ice#1578]
## 问题描述
菜单栏，内容多的时候可以增加一个返回顶部，同时左侧菜单栏跟随

**Comment by imsobear** [comment]
@ayixidelu 麻烦规范下 issue 的格式，描述清晰一点，最好能给一些图片

**Comment by imsobear** [comment]
issue 格式不合格，先关掉，麻烦补全后再 reopen

**Comment by ayixidelu** [comment]
![qq 20190308153518](https://user-images.githubusercontent.com/37927198/54014799-bbad5e80-41b8-11e9-9b22-b5ebc8fe0f28.png)
一点小小的建议
