### ISSUE TITLE
Pro 模板如何去掉页面底部的滚动条

### ISSUE THREAD

**Issue by JingleZilch** [alibaba/ice#1619]
用了ICE Design Pro这个模板后,页面的底部老是出现滚动条 怎么解决呢？
![微信图片_20190315114122](https://user-images.githubusercontent.com/28947829/54406999-50fba600-4717-11e9-8bcd-ed19154f246d.png)
![微信图片_20190315114132](https://user-images.githubusercontent.com/28947829/54407013-5e189500-4717-11e9-8541-b7cfb307b46e.png)

**Comment by chenbin92** [comment]
https://github.com/alibaba/ice/pull/1634
