### ISSUE TITLE
iceworks 创建vue页面，生成的模板文件缺失最外层的.vue文件问题

### ISSUE THREAD

**Issue by james-cain** [alibaba/ice#1621]
实际安装版本号：Iceworks@2.16.0
系统环境：macOS
Node.js版本：8.10.0

## 问题描述
新建页面生成的代码结构存在问题
![iceworks-bug1](https://user-images.githubusercontent.com/18431775/54412956-4baa5580-472f-11e9-88a1-cfcdadf20d42.jpg)
缺少了最外层的xxx.vue文件，而index.js中的内容却是xxx.vue里应该写的内容
![iceworks-bug2](https://user-images.githubusercontent.com/18431775/54413078-9c21b300-472f-11e9-9ac8-855f61118bf4.jpg)

**Comment by chenbin92** [comment]
已修复 https://github.com/alibaba/ice/pull/1729
