### ISSUE TITLE
区块 Tab Head 样式不正确

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#1623]
## 问题描述

https://unpkg.com/@icedesign/flow-statistics-block@2.0.0/build/index.html

![image](https://user-images.githubusercontent.com/2505411/54416303-f7f13980-4739-11e9-91bb-2f16a5ae77ec.png)

升级模板时遇到过类似的问题，后来改了交互。

**Comment by chenbin92** [comment]
https://github.com/alibaba/ice/pull/1632
