### ISSUE TITLE
部分死链问题

### ISSUE THREAD

**Issue by alvinhui** [alibaba/ice#1625]
## 问题描述

1. https://alibaba.github.io/ice/ (1.x)

    出现了 2 个「设计」，其中第二个是死链。

    ![image](https://user-images.githubusercontent.com/4392234/54420010-db59ff00-4743-11e9-981f-0330ec39ef44.png)
 2. Iceworks 2.7.1 

    「自定义物料源使用文档」是死链。
    
    ![image](https://user-images.githubusercontent.com/4392234/54420120-1f4d0400-4744-11e9-8ff9-3b89e9b79c69.png)

**Comment by imsobear** [comment]
1. 已修复
2. 代码已修复，下个版本发布
