### ISSUE TITLE
ice-script devServer 不支持自定义 publicPath

### ISSUE THREAD

**Issue by battle-ooze** [alibaba/ice#1633]
## 问题描述

使用 ice-script 开发时，无法自定义 publicPath。

场景：
我们这边一个项目 index.html 是放在后端的，后端同学开发时会启一个后端服务（比如localhost:7001）和一个前端 devserver(127.0.0.1:4444)，开发的时候访问的是 localhost:7001，里面会引 127.0.0.1:4444/js/index.js 这样，如果我做了懒加载那么再去拉新的 js 的话，就会请求到 /js/1.js ，会拉不到，现在我们只能设一个代理来解决，如果这里的 publicPath 我可以自定义设置成 http://127.0.0.1:4444/  而不是 /  ，就没有这个问题了。

建议：
1.  dev 的 webpack 配置中，publicPath 也从 `.webpackrc.js` 中 merge，而不是写死。
2. 支持不传 publicPath，这样可以通过在运行时设置 __webpack_public_path__ 全局参数动态设置publicPath

**Comment by chenbin92** [comment]
@battle-ooze  支持在 `.webpackrc.js` 自定义配置 `devServer` 的，详见 https://github.com/alibaba/ice/blob/master/tools/ice-scripts/lib/dev.js#L105

### 示例
```
module.exports = (context) => {
  return {
    devServer: {
      publicPath: '/dist/',
    }
  };
};
```

### 输出：

![image](https://user-images.githubusercontent.com/3995814/55469048-39894c00-5637-11e9-9230-f020ca59fd29.png)
