### ISSUE TITLE
BallonConfirm

### ISSUE THREAD

**Issue by cpa0701** [alibaba/ice#1635]
BallonConfirm1.0业务组件点击取消无法关闭弹框，而且也没提供关闭api

**Comment by cpa0701** [comment]
BallonConfirm1.0业务组件点击取消无法关闭弹框，而且也没提供关闭api
![image](https://user-images.githubusercontent.com/24648209/54510008-a1c50600-4986-11e9-937f-8c6668ff025d.png)

**Comment by imsobear** [comment]
通过 visible 属性控制。
