### ISSUE TITLE
BalloonConfirm 1.x 点击取消/确认后没有隐藏

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#1640]
## 问题描述

BalloonConfirm 1.x 点击取消/确认后没有隐藏，0.x 是可以隐藏的：

- 0.x: https://alibaba.github.io/ice/0.x/component/balloonconfirm
- 1.x: https://alibaba.github.io/ice/component/balloonconfirm

**Comment by cpa0701** [comment]
同问

**Comment by Orange-C** [comment]
@imsobear `BallonConfirm`使用`refs`获取内部`Ballon`实例调用`Ballon`的`setState`来关闭Ballon。现在的问题是因为无法获取到内部`Ballon`实例。

`Fusion`1.0版本使用`ConfigProvider `包裹了所有基础组件，暴露了`_getInstance`方法和`_instance`属性用来获取被包裹的组件，这两个是通过`refs`实现的，但是React16的`refs`使用方法更新，导致这两个属性仍然是旧的用法，导致现在获取的实例都是`undefined`，外界无法再获取到内部的组件实例。目前修复此bug需要`Fusion`同学做出以下改动。

1. 修复`ConfigProvider `的`_getInstance`方法和`_instance`属性
2. （可选）在`Ballon`上增加`closePopup`方法避免直接调用`setState`

相关代码：
* [BallonConfirm](https://github.com/alibaba/ice/blob/master/react-materials/components/balloon-confirm/src/BalloonConfirm.jsx)
* [使用ConfigProvider包裹Ballon](https://github.com/alibaba-fusion/next/blob/master/src/balloon/index.jsx)
* [ConfigProvider](https://github.com/alibaba-fusion/next/blob/master/src/config-provider/config.jsx)
* [Ballon](https://github.com/alibaba-fusion/next/blob/master/src/balloon/balloon.jsx)

**Comment by Orange-C** [comment]
@imsobear fixed #1643
