### ISSUE TITLE
官方区块/模板样式方案统一迁移 css modules

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#1641]
工程上已经支持，目前官方物料里有内联、scss、css-modules 三种写法，对用户很不友好，需要择期统一迁移。

文档：https://alibaba.github.io/ice/docs/advanced/webpackrc#CSS%20Modules

**Comment by qivhou** [comment]
同意，目前感觉很多的物料并不是出自同一规范，样式方面可能体现的比较明显。
再有关于mock data的写法好像也不一致，是否直接通过data.js/json 进行纯的数据抽象，在物料中对data进行渲染更好。
当然这个可能超出了这个issue的讨论范围。

**Comment by yuanyan** [comment]
官方可以统一 scss + css-modules

**Comment by boiawang** [comment]
@qivhou 关于 mock 的讨论可以新开个 issue.
