### ISSUE TITLE
官方物料加载失败-VUE物料源

### ISSUE THREAD

**Issue by 13140130936** [alibaba/ice#1651]
VUE物料源加载失败：

chrome 浏览器能正常访问
https://cdn.jsdelivr.net/npm/@icedesign/materails-db@latest/lib/vue-materials.json

**Comment by imsobear** [comment]
#1321 重复问题

**Comment by agileago** [comment]
![image](https://user-images.githubusercontent.com/11799110/55202828-047a9500-5204-11e9-9868-1afc832af4f9.png)
不管自定义的还是官方的vue物料都下载失败，但是通过浏览器是可以下载的，和网络没关系
版本 `2.17.1`
