### ISSUE TITLE
select组件有最小宽度吗？配置width无法缩小宽度

### ISSUE THREAD

**Issue by xyl5k5k** [alibaba/ice#1654]
![image](https://user-images.githubusercontent.com/38687923/54672310-be05a600-4b32-11e9-89cf-bc2414e4be81.png)
![image](https://user-images.githubusercontent.com/38687923/54672384-de356500-4b32-11e9-8b48-223ffc26909a.png)
配置width无法缩小了

**Comment by imsobear** [comment]
@xyl5k5k 看下 issue 描述，组件问题按照文档给下 demo

**Comment by xyl5k5k** [comment]
https://codepen.io/anon/pen/BbqvJj?editors=0011
@imsobear 麻烦看一下，想把select宽度调小

**Comment by youluna** [comment]
组件默认最小宽度为100px，不建议更小。

想实现更小可以通过css hack
 `<Select style={{width: '50px', minWidth: '50px'}}>`

**Comment by xyl5k5k** [comment]
option好像不能通过minWidth更改宽度样式，只能用overlay定制吗？
