### ISSUE TITLE
物料源加载失败，请确认网络是否能直接访问此链接 https://cdn.jsdelivr.net/npm/@icedesign/materails-db@latest/lib/vue-materials.json，建议将此问题反馈给飞冰（ICE）团队，在菜单中点击: 帮助 => 反馈问题

### ISSUE THREAD

**Issue by vivioning** [alibaba/ice#1660]
物料源加载失败，请确认网络是否能直接访问此链接 https://cdn.jsdelivr.net/npm/@icedesign/materails-db@latest/lib/vue-materials.json，建议将此问题反馈给飞冰（ICE）团队，在菜单中点击: 帮助 => 反馈问题

**Comment by imsobear** [comment]
#1321 重复问题，这个问题下个版本会彻底修复

**Comment by olivia53135** [comment]
我也是遇到这个问题，现在还没有好
