### ISSUE TITLE
无法加载vue物料

### ISSUE THREAD

**Issue by sevendiod** [alibaba/ice#1663]
## 错误信息
icework无法加载vue物料
https://cdn.jsdelivr.net/npm/@icedesign/materails-db@latest/lib/vue-materials.json可以打开

**Comment by csdn182tcy** [comment]
我的也无法打开更新过后直接Vue直接炸了

**Comment by wangrocky** [comment]
同样的问题。

**Comment by imsobear** [comment]
现在的策略是先加载 oss 的文件，加载不到的话再加载 cdn.jsdelivr 的内容，你的这种情况是两个 url 都加载失败了。这个问题在下个版本会彻底解决。

#1321 跟进这个问题
