### ISSUE TITLE
无法上传到阿里云OSS

### ISSUE THREAD

**Issue by mtshen** [alibaba/ice#1664]
## 问题描述
构建完成后无法上传到阿里云OSS中
![image](https://user-images.githubusercontent.com/22271073/54742757-39cc2500-4bfd-11e9-905a-2b87e94e7b40.png)

## 错误信息
![image](https://user-images.githubusercontent.com/22271073/54742644-f4a7f300-4bfc-11e9-842c-5b901ac3b943.png)

**Comment by fenglai0802** [comment]
@mtshen OSS插件默认读build目录下的构建结果，vue-cli构建结果放在dist，下个版本会做兼容。目前需要上传请通过配置把构建结果目录从dist修改为build
