### ISSUE TITLE
ice-scripts publicPath 配置问题

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#1670]
## 错误信息

![image](https://user-images.githubusercontent.com/3995814/54808655-d6ed9300-4cbb-11e9-8da7-480eab95a612.png)

**Comment by chenbin92** [comment]
## Webpack `output.publicPath` 简述

![image](https://user-images.githubusercontent.com/3995814/54808350-ea4c2e80-4cba-11e9-8601-e8ccc8cd29ee.png)


总结一下意思就是说：可以通过配置 publicPath 来指定应用程序中 **所有资源** 的 **基础路径**。

* 所有资源： 构建之后的 css，js，img 等资源
* 基础路径：资源中引用 css，js，img 的路径，如 `background-image: url('./assets/img.png')`

```
静态资源访问路径 = output.publicPath + assets path
```

## 配置示例说明

使用 ice-scripts 默认的构建输出目录如下:

```
.
└── admin
    ├── assets
    │   └── xxx.png
    ├── css
    │   └── index.css
    ├── favicon.png
    ├── index.html
    └── js
        └── index.js
```

如果访问的地址是 `https://xxx.com`，并且 `js`、`css`、`assets` 文件存放地址与 `index.html` 一样，那么此时不需要做任何调整，这也是 ice-scripts 的默认配置。

#### 示例一：

为基础路径添加统一前缀，如过访问的地址是 `https://xxx.com/admin`，并且 `js`、`css`、`assets`  文件存放地址与 `index.html` 一样，但是我们的业务代码并没有写 `admin` 这个前缀，这个时候就可以按照以下方式配置：

资源引用
```
.app {
   background-image: url('./assets/img.png');
}
```

公共路径配置
```
output: {
  publicPath: '/admin/'
}
```

输出结果

```
// 加上了 publicPath 配置的 /admin/
background-image: url(/admin/assets/img.png);
```

#### 示例二

如果访问的地址是 `http://xxx.com/admin/index.html`，但 `js`、`css`、`assets`  文件存放地址与 `index.html` 不一样，比如：`http://cdn.com/index.js` 此时需要设置 publicPath 为 `http://xxx.com`

资源引用
```
.app {
   background-image: url('./assets/img.png');
}
```

公共路径配置
```
output: {
  publicPath: 'https://xxx.com/'
}
```

输出结果

```
// 加上了 publicPath 配置的 https://xxx.com
background-image: url(https://xxx.com/assets/img.png);
```

#### 示例三

如果配置相对路径，则会相对当前资源路径进行构建输出：

资源引用
```
.app {
   background-image: url('./assets/img.png');
}
```


公共路径配置
```
output: {
  publicPath: './'   // 这里 **只有一个点**
}
```

输出结果:

```
// 加上了 publicPath 配置的 ./ 
background-image: url(assets/img.png);
```

**注意**：这里只配置的是 `./` 所以会导致访问时直接访问的是 ```https://xxx.com/css/assets/img.png```，而 `/assets/img.png` 在根目录，这意味在生产环境则会直接挂掉。

**思考**：如果你看到这里，你可能知道已经如何避免这种错误，在想想如果 publicPath 配置成 `../`或者 `/` 会是什么样？

## 开发环境

ice-scripts 中开发环境 `output.publicPath` 固定为:

```
  // 配置合并
  // 开发环境下 publicPath 指定为 / 与 webpack server 一致
  return webpackMerge(baseConfig, {
    devtool: 'cheap-module-source-map',
    output: {
      publicPath: '/',
    },
    plugins,
  });
```

参考：[#L34](https://github.com/alibaba/ice/blob/master/tools/ice-scripts/lib/config/webpack.config.dev.js#L34)

## 生产环境 

ice-scripts 中生产环境 `output.publicPath` 默认值为:

```
{
  publicPath: '/'
}
```
参考： [#L36](https://github.com/alibaba/ice/blob/master/tools/ice-scripts/lib/config/paths.js#L36)


## 总结

* 因为在开发环境中 `output.publicPath` 固定为 `/`也即总是相对于根路径，所有不会存在上述错误，在生成环境中自定义配置 `output.publicPath` 为 `./`，所以会导致引用资源出错
* 大多数情况下 `output.publicPath` 配置为 `./` 即可，如果有特殊需求，可按照上述描述进行配置。

**Comment by Symous** [comment]
@chenbin92 我们一般的实际使用情况是，publicPath需要配置为''或者'./'以支持打包后的js和css的引入，但是针对资源文件，我们需要使用'../'，防止出现css/assets/img.png的情况，这种情况下应该怎么配置呢？
