### ISSUE TITLE
无法使用vue物料源

### ISSUE THREAD

**Issue by qq314216519** [alibaba/ice#1679]

**Comment by qq314216519** [comment]
加载失败

**Comment by chenbin92** [comment]
可以先在设置面板添加物料源： https://cdn.jsdelivr.net/npm/@icedesign/materails-db@latest/lib/vue-materials.json

相关 issue 讨论：https://github.com/alibaba/ice/issues/1321

**Comment by qq314216519** [comment]
![53C6 T(29(TG4WKIPM0A(~3](https://user-images.githubusercontent.com/38276132/54907396-5da2aa00-4f20-11e9-82ac-87550fdcb533.png)
![XJ@_B`} $AY Q~{%5R 3NZB](https://user-images.githubusercontent.com/38276132/54907397-5e3b4080-4f20-11e9-9fa5-03b9b1a8ddb4.png)

**Comment by imsobear** [comment]
问题已修复，请重置官方物料源然后重试
