### ISSUE TITLE
[Iceworks] electron 升级到稳定版本

### ISSUE THREAD

**Issue by alvinhui** [alibaba/ice#1680]
## 需求描述

当前 Iceworks 的 electron 版本：

```json
{
    "electron": "2.0.1",
    "electron-builder": "20.13.4"
}
```

1. electron 升级到 2.0.18：electron 从版本 2.0 开始已遵循 [semver 标准](https://semver.org/)，从 2.0.1 到 2.0.18 包含了[安全更新](https://electronjs.org/releases/stable?version=2)；
2. electron-builder 升级到 20.13.5：这是兼容的，仅包含了 [Bugfix](https://github.com/electron-userland/electron-builder/releases?after=v20.14.1)。

**Comment by chenbin92** [comment]
@alvinhui 这种直接提 MR 或者当做 TODO 去做就好了，应该不归类于 issue，先关闭了
