### ISSUE TITLE
初始化 ice design pro 项目后，运行时报错（Babel 依赖问题？）

### ISSUE THREAD

**Issue by Songkeys** [alibaba/ice#1689]
## 问题描述

类似问题：<https://github.com/creativetimofficial/ct-material-dashboard-pro-react/issues/62> <https://github.com/dvajs/dva/issues/1980>
问题来源：<https://github.com/babel/babel/pull/8266>

## 错误信息

```
Failed to compile
./node_modules/react-redux/es/components/connectAdvanced.js
Module not found: Can't resolve '@babel/runtime/helpers/esm/assertThisInitialized' in '/Users/songkeys/Github/uCourse-mp/node_modules/react-redux/es/components'
```

**Comment by imsobear** [comment]
@Songkeys 将 ice-scripts 升级到 1.9.0 试下，我这边试了是 OK 的

**Comment by WangJueStar** [comment]
![image](https://user-images.githubusercontent.com/38129014/55044772-92c11080-5076-11e9-903f-7fb6d55be771.png)
![image](https://user-images.githubusercontent.com/38129014/55044790-a0769600-5076-11e9-941f-aea1ee12326d.png)
我这边升级了1.9.0还是不行。

**Comment by imsobear** [comment]
https://github.com/alibaba/ice/pull/1687/files#diff-02c911d192c6fc87bf20c348f6b81028R40 可能是这个改动引起的，我排查下

**Comment by imsobear** [comment]
ice-scripts@1.9.1 大家试下

**Comment by WangJueStar** [comment]
> ice-scripts@1.9.1大家试下

可以了，谢谢。
