### ISSUE TITLE
ice-devtools 支持自定义npm 源

### ISSUE THREAD

**Issue by chenjun1011** [alibaba/ice#1691]
飞冰不能能使用非npm的私有源（比如 阿里云的）托管物料，在ice-devtools/utils/inner-net.js直接写死了阿里内网和npm源地址，我们想用阿里云的私有源来托管，这个能不能改进一下？

![image](https://user-images.githubusercontent.com/1303018/55045965-d61d7e00-507a-11e9-8101-e94e994d33a6.png)

**Comment by wssgcg1213** [comment]
feature request: 允许环境变量覆盖 registry url  

help wanted

**Comment by Gorden-Wang** [comment]
大致思路是修改 geNpmInfo这个方法https://github.com/alibaba/ice/blob/d570c8517759a186b51e0dc1bb1a0fc528be9434/tools/ice-devtools/utils/npm.js#L12 

利用```npm info```来获取npm的相关信息，组装```{versions,time}```

```javascript
const process = require('child_process');
const asset = require('assert');
const processPromise = (package,field) => {
  return new Promise((resolve,reject)=>{
    process.exec(`npm info ${package} ${field}`,(err, stdout, stderr) => {
      if (err) return reject(err)
      let res = String(stdout.replace(/\r\n/g,'')).trim();
      try {
        eval(`res=${res}`)
      }catch(_) {}
      resolve({ [field]:res })
    });
  })
}

async function test (package,fields) {
  asset(fields,"fields must be An array");
  asset(Array.isArray(fields),"fields must be An array")

  const promis = []
  fields.forEach((item)=>{
    promis.push(processPromise(package,item));
  });

  return await Promise.all(promis)
  
}

(async ()=>{
  const res = await test('@common/ajax',['time','versions'])
  console.log(res);
})()
```

**Comment by MickeyMouse-lh** [comment]
@Gorden-Wang 应该还需要```dist-tags```这个信息

**Comment by imsobear** [comment]
自定义 registry 是个通用需求，这块需要整体梳理看下，应该不只这一个地方

**Comment by Gorden-Wang** [comment]
> 自定义 registry 是个通用需求，这块需要整体梳理看下，应该不只这一个地方

这个不仅仅是个自定义registry，自定义registry如果是public的，也可以用Get到 npm info。

**Comment by chenjun1011** [comment]
是不是可以拆开两个功能点来看 
1. 自定义 registry 的能力
2. 跳过 npm 包检测的能力（类似上面提到的不能获取的情况，可以有跳过检测的能力）

**Comment by Gorden-Wang** [comment]
npm包的检测还是非常有意义的，有利于私有源托管物料生态健康吧。或者再加一个fallback

1. 自定义 registry 的能力
2. fallback机制
3. 跳过

**Comment by imsobear** [comment]
@Gorden-Wang @MickeyMouse-lh 这块涉及的改动点比较多，我这边来处理吧，到时候两位可以帮忙 review 代码

**Comment by imsobear** [comment]
https://github.com/alibaba/ice/pull/1705 @Gorden-Wang @MickeyMouse-lh 有空了看下，明天我发 beta 版本

**Comment by Gorden-Wang** [comment]
ping @hyj1991

**Comment by imsobear** [comment]
ice-scripts@1.9.3 ice-devtools@2.2.1 已支持

通过环境变量传递即可：https://www.npmjs.com/package/ice-npm-utils#custom

剩余的需要私有 npm 源支持对应接口：

- 通过 ${registry}/${npm} 返回 npm 包的信息，比如： registry.npm.taobao.org/koa
- 通过 ${registry}/${npm}/-/${npm}-${version}.tgz 可以下载 tar 包，比如：https://registry.npm.taobao.org/koa/-/koa-2.6.0.tgz
- 私有 npm 有对应的 unpkg 服务，不过这个主要是渲染构建的 html 用于预览模板等，不阻塞主链路

**Comment by MickeyMouse-lh** [comment]
![image](https://user-images.githubusercontent.com/29797274/55320299-51cb6080-54a9-11e9-8110-3a4657e88092.png)
![image](https://user-images.githubusercontent.com/29797274/55320313-55f77e00-54a9-11e9-919c-828958434cdd.png)
这个是没有改全吧！
