### ISSUE TITLE
iceworks 2.18.0 功能

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#1695]
|  功能说明 | 开发者  |  测试者 |  开发完成  | 测试完成  | MR   |
|---|---|---|---|---|---|
|  优先使用系统的 node/npm 环境 | 思忠   | 梧忌  |  是  |  是 | https://github.com/alibaba/ice/pull/1686 |
|  支持 npm/cnpm/tnpm client | 思忠   | 梧忌  |  是  |  是 | https://github.com/alibaba/ice/pull/1686  |
|  内置物料源 | 思忠   | 梧忌  |  是  | 是  | https://github.com/alibaba/ice/pull/1657  |
| 添加启动 npm 检查提示  | 思忠   | 梧忌  |  是  | 是  | https://github.com/alibaba/ice/pull/1562 |
|  windows 安装 iceworks 时支持安装路径选择  | 继尘   | 思忠 |  是  |   | https://github.com/alibaba/ice/pull/1662 |
|  生成页面时添加区块注释 | 迹尘   | 思忠 |  是  | 是   | https://github.com/alibaba/ice/pull/1684  |
|  下线新建页面的预览功能 | 迹尘   | 思忠 |  是  | 是   | https://github.com/alibaba/ice/pull/1684  |
|  点击页面路径支持在 vscode 和 sublime 中打开 | 迹尘   | 思忠 |  是  | 是  | https://github.com/alibaba/ice/pull/1661 |
|  代码优化和异常处理 | 梧忌   | 迹尘 | 是   |  是  | https://github.com/alibaba/ice/pull/1702   |

**Comment by chenbin92** [comment]
@fenglai0802  通过页面列表打开对应的项目文件不生效
![demo1](https://user-images.githubusercontent.com/3995814/55060177-d2eeb600-50ab-11e9-8072-c44f1fe6e6ba.gif)

**Comment by alvinhui** [comment]
建议功能点提供自测方法，优先自测，再交叉测试。

**Comment by chenbin92** [comment]
#### 优先使用系统的 node/npm 环境
测试方法：在运行日志中 `which node ` 和 `which npm/cnpm` 看看是否读的本地

#### 支持 npm/cnpm/tnpm client
测试方法：
1. 在运行日志中 `which npm/cnpm/tnpm`  看是否优先读的本地的环境
2. 在设置面板设置不同的 npm 源，重新安装以依赖，看是否启用了系统对应的 npm client
3. 为了验证更准确，可以干掉系统的 node 环境，看是否走兜底逻辑😆

#### 内置物料源

测试方法：断网环境，以及 4G 环境，内网环境，看物料源是否都能正常加载


#### 添加启动 npm 检查提示

测试方法：设置 npm 源，关闭重启看是否会提示并且只提示一次使用 cnpm 源

**Comment by chenbin92** [comment]
# iceworks  2.18.0 内置环境和稳定性优化

## 发布概览
* [功能] 优先使用系统的 node/npm 环境	
* [功能] 支持 npm/cnpm/tnpm client	
* [功能] 页面列表支持在 vscode 和 sublime 中打开
* [优化] 内置官方兜底物料源
* [优化] 添加启动 npm 检查提示	
* [优化] 生成页面时添加区块注释	
* [下线] 下线新建页面的预览功能	


## 更新说明

#### 优先使用系统的 node/npm 环境

* 因 iceworks 内置 node/npm/node-sass 环境，导致用户在命令行和 iceworks 两者间不能友好的切换出现各种问题，因 node-sass 强依赖 node 的版本
* 因 iceworks 内置 node/npm/node-sass 环境，用户使用时强依赖 iceworks 对基础环境的升级，不能自由切换 node/npm 等环境的版本

常见问题： [#1918](https://github.com/sass/node-sass/issues/1918)、[#2536](https://github.com/sass/node-sass/issues/2536)、[#1084](https://github.com/sass/node-sass/issues/1804)


**2.18.0 之前：**
![](https://img.alicdn.com/tfs/TB1ECUOOhjaK1RjSZKzXXXVwXXa-1632-1126.png)


基于以上两点考虑，在 iceworks 2.18.0 版本中，默认优先读取系统的 node/npm 等环境变量，确保在系统终端和 iceworks 的运行环境一致。但如果系统不存在 node/npm 环境，则会降级兜底使用 iceworks 提供的 node/npm 环境。

**2.18.0 之后：**
![](https://img.alicdn.com/tfs/TB1gYomObvpK1RjSZPiXXbmwXXa-1726-1178.png)


**使用系统环境可能部分用户会遇到一个非常常见的 node-sass 安装问题，这里给出问题原因和解决方案：**

安装 `node-sass` 时会在 [node scripts/install](https://github.com/sass/node-sass/blob/a2ac801e28/package.json#L31) 阶段从 github.com 上下载一个  [xxx-xx_binding.node](https://github.com/sass/node-sass/releases) 文件，因为 GitHub Releases 里的文件都托管在 `s3.amazonaws.com` 上面，而这个网址在国内网络不稳定，大部分安装不成功的原因都源自这里，所有通常的做法是通过国内的镜像进行下载。

[#L239](https://github.com/sass/node-sass/blob/a2ac801e28/lib/extensions.js#L239)

```js
// node-sass 获取 binary 代码
function getBinaryUrl() {
  var site = getArgument('--sass-binary-site') ||
             process.env.SASS_BINARY_SITE  ||
             process.env.npm_config_sass_binary_site ||
             (pkg.nodeSassConfig && pkg.nodeSassConfig.binarySite) ||
             'https://github.com/sass/node-sass/releases/download';

  return [site, 'v' + pkg.version, getBinaryName()].join('/');
}
```

由以上代码可见通常的做法如下：
```
$ npm i node-sass ---sass-binary-site=https://npm.taobao.org/mirrors/node-sass

// 或者

// linux、mac 下
$ SASS_BINARY_SITE=https://npm.taobao.org/mirrors/node-sass/ npm i node-sass

// window 下
set SASS_BINARY_SITE=https://npm.taobao.org/mirrors/node-sass/ && npm install node-sass

或者
npm config set sass_binary_site https://npm.taobao.org/mirrors/node-sass
```
  
或者读取系统的环境变量，也是 iceworks 最初的设计将 sass-binary 内置解决该类问题

 [iceworks sass binary](https://github.com/alibaba/ice/tree/master/tools/iceworks/binary)

```
// 通过内置 sass binary 环境变量解决网络下载的问题
const SASS_BINARY_PATH = isDev
  ? path.join(
      process.cwd(),
      'binary',
      process.platform,
      'sass',
      `${process.platform}-x64-57_binding.node`
    )
  : path.join(
      process.resourcesPath,
      'binary',
      'sass',
      `${process.platform}-x64-57_binding.node`
    );
```

* [功能] 支持 npm/cnpm/tnpm client	

2.18.0 版本之前下载依赖的方式是通过 `npm install --registry=xxx` 的方式进行安装，虽然支持了动态源的切换，但是只能通过 npm client  进行安装，而不能指定诸如 cnpm/tnpm 等 npm client，而 npm 和 cnpm 在依赖安装的策略不同，导致出现安装差异，出现各种问题。

在 2.18.0 版本因为默认读取系统的 node 以及 npm/cnpm/tnpm 等环境变量，因此只要确保你系统有安装对应的 npm 客户端，既可以使用该 npm 客户端安装依赖，而不强制使用 npm 客户端进行安装。


### 页面列表支持在 vscode 和 sublime 中打开

在列表页面支持快捷打开对应的代码文件，目前只支持 vscode 和 sublime 两种编辑器

![](https://img.alicdn.com/tfs/TB1J83pOirpK1RjSZFhXXXSdXXa-1425-814.gif)

### 内置官方兜底物料源

**iceworks 物料数据源问题**

目前官方物料源都托管在 `ice.alicdn.com` 下，很多用户反馈在特定网络会屏蔽导致物料源加载失败，因此整个 Iceworks 对用户不可用。

**数据同步 jsdelivr 方案**
在上一版本我们对官方物料源加了一个备份机制，将数据源同步到 jsdelivr， 然后访问 `https://cdn.jsdelivr.net/npm/@icedesign/materails-db@latest/lib/react-materials.json"`，但效果并不满意，结合日志发现部分用户这个地址还是无法访问。

**内置数据源兜底方案（最终方案）**
将所有官方维护的数据源内置到 Iceworks 软件中作为终极兜底方案，当网络环境不可用时降级到内置物料数据，这也意味着即使是在断网的情况下也能访问到物料数据。缺点是数据可能不是最新的，但一定能保证 Iceworks 的可用性。

### 添加启动 npm 检查提示	

对于大部分用户，强烈推荐使用 cnpm 代替 npm 进行下载，原因大家都知道。在 iceworks 启动时，新增了启动时的检查，如果检测到当前设置 npm 源，则会提示使用 cnpm。

### 下线新建页面的预览功能	

在 2.18.0 版本之前，在新建页面时可以实时预览当前的页面效果，当由于该过程会去动态下载代码和安装依赖，会导致整个过程较慢，且必须启动本地调试服务，基于用户反馈和使用体验，我们暂且下掉该功能。


### 其他
  * 生成页面时添加区块注释	
  * 代码稳定性优化
