### ISSUE TITLE
select组件外面有样式的话，首次点击下拉会有一次偏移的闪动

### ISSUE THREAD

**Issue by hjtgzh** [alibaba/ice#1701]
## select组件外面有样式的话，首次点击下拉会有一次偏移的闪动]

模板：飞冰官网模板和开放平台官网。

图片显示：
![image](https://user-images.githubusercontent.com/21164145/55062374-d9cbf780-50b0-11e9-828c-ec92f432c20a.png)

## 代码如下:
![微信截图_20190327165801](https://user-images.githubusercontent.com/21164145/55062729-86a67480-50b1-11e9-92b7-30ec3d548ff0.png)

**Comment by chenbin92** [comment]
![image](https://user-images.githubusercontent.com/3995814/55309284-e923ba00-548f-11e9-8c63-2e97451d3fb8.png)

@hjtgzh 
1. 飞冰官网模板和开放平台官网没有使用 `Select` 组件
2. 两个模板均做了测试，不能复现你说的问题，如上截图


综上：怀疑存在全局性的样式冲突问题，请自行检查或者提供可复现的 demo

**Comment by hjtgzh** [comment]
你加个默认值试下，应该会出现这个问题@chenbin92

**Comment by hjtgzh** [comment]
麻烦加个默认值试下，@imsobear
