### ISSUE TITLE
表单验证如何完毕如何阻止默认事件？

### ISSUE THREAD

**Issue by wangjue666** [alibaba/ice#1706]
## 问题描述

```
 this.refs.form.validateAll((errors, values) => {
      if (errors.length) {
        console.log({ errors });
        Message.error('请填写完整表单');
      }else(errors.length==1){
        //this.props.history.push('/media')  
       Axios.post('upload_video',values).then(()=>{
          this.props.history.push('/media')
        });
       
      }  
```

## 错误信息

验证表单成功后，页面就会直接跳转当前路径 报错，是因为form表单的没有诅咒默认事件吗？导致验证成功就直接跳转吗？（查阅了官方文档并没有这样的例子或解决方案）
但是 `this.props.history.push('/media')` 放到请求外面就没问题，该如何解决呢

**Comment by chenbin92** [comment]
* `form-binder` 内部只处理表单的数据逻辑，没有内置 Form 等 UI 元素。
* 验证成功的跳转是在外层控制的
* 看你提供的代码并不完整 `errors.length==1` 时也发送了请求然后跳转

综合以上问题，看起来是业务代码逻辑问题，请自行检查

**Comment by wangjue666** [comment]
恩恩 大佬原因找到了， 使用了Upload这个组件,但是数据类型是数组, 因为数据库图片类型是String,
没有考虑 values对象引用关系 直接转换图片的数据类型 组件就一直报错，，，，太沙雕了我，
react的报错信息真是得玄学debug
