### ISSUE TITLE
iceworks 安装依赖失败

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#1718]
## 问题描述
windows 使用 cnpm 源，安装依赖可能失败，使用 npm 可正常安装

## 错误信息

![image](https://user-images.githubusercontent.com/3995814/55277313-a6e86480-5339-11e9-88c6-80bbbcdaa400.png)

**Comment by chenbin92** [comment]
切换到 npm 源可以，切换到 cnpm 源会出现安装卡死的情况

**Comment by plxdhong** [comment]
我也是，然后手动在终端安装的

On Apr 1, 2019 11:48 AM, chenbin92 <notifications@github.com> wrote:

切换到 npm 源可以，切换到 cnpm 源会出现安装卡死的情况

**Comment by chenbin92** [comment]
@plxdhong 更新 2.18.2 版本
