### ISSUE TITLE
ICE Design Pro全新项目启动失败。Module parse failed: Unexpected token (22:9)

### ISSUE THREAD

**Issue by zzyyzz1992** [alibaba/ice#1721]
## 问题描述

使用Iceworks构建的全新项目启动失败。
环境：
Win 10
Iceworks 2.18.1
Node 10.15.3
![image](https://user-images.githubusercontent.com/3894825/55286424-5cfd8e00-53ce-11e9-9761-49a77fccdf1b.png)

## 错误信息

![image](https://user-images.githubusercontent.com/3894825/55286371-95e93300-53cd-11e9-89fc-344a6050f53d.png)

Console log:

> 
>  ERROR in ./src/pages/Dashboard/Dashboard.jsx 22:9
> Module parse failed: Unexpected token (22:9)
> You may need an appropriate loader to handle this file type.
> | import PageLoading from '../../components/PageLoading';
> | var Overivew = React.lazy(function () {
>    return import('./components/Overivew');
> | });
> | var TabChart = React.lazy(function () {

>  @ ./src/pages/Dashboard/index.js 1:0-36 2:15-24
>  @ ./src/routerConfig.js
>  @ ./src/layouts/UserLayout/UserLayout.jsx
>  @ ./src/layouts/UserLayout/index.js
>  @ ./src/router.js
>  @ ./src/index.js
>  @ multi ./node_modules/@babel/polyfill/lib/index.js ./node_modules/react-dev-u
> tils/webpackHotDevClient.js ./src/index.js
> ERR! Failed to compile.
> 
> ./src/pages/Dashboard/Dashboard.jsx 22:9
> Module parse failed: Unexpected token (22:9)
> You may need an appropriate loader to handle this file type.

> 
> | import PageLoading from '../../components/PageLoading';
> | var Overivew = React.lazy(function () {
> >   return import('./components/Overivew');
> | });
> | var TabChart = React.lazy(function () {
>

**Comment by zzyyzz1992** [comment]
补充一下：
使用了ICE Design Pro 模板。
如果不勾选添加Server端，则可以正常启动。

**Comment by zzyyzz1992** [comment]
补充完整日志：

> "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" run start --scripts-prepend-node-path=auto
> 
> > @icedesign/pro-scaffold@1.0.0 start C:\Users\zzyyz\iceworks-wor
> kspace\Test1\client
> > ice dev --project-type=nodejs
> 
> ice-scripts 1.9.2
> sassInfo node-sass      4.9.0   (Wrapper)       [JavaScript]
> libsass         3.5.4   (Sass Compiler) [C/C++]
> info package.json 存在 entry 配置
> info --inject-babel:  polyfill
> info 使用主题包 @icedesign/theme
>                                          71% basic dependencies o
>                                          72% dependencies optimiz
>                                          72% advanced dependencie
>                                          73% after dependencies o
>                                          74% basic module optimiz
>                                          75% advanced module opti
>                                          75% after module optimiz
>                                          76% basic chunk optimiza
>                                          77% advanced chunk optim
>                                          77% after chunk optimiza
>                                          78% module and chunk tre
>                                          78% after module and chu
>                                          79% basic chunk modules
>                                          79% chunk modules optimi
>                                          80% advanced chunk modul
>                                          80% after chunk modules
>                                          81% module order optimiz
>                                          82% advanced module orde
>                                          83% module id optimizati
>                                          84% module id optimizati
>                                          85% chunk order optimiza
>                                          86% chunk id optimizatio
>                                          86% after chunk id optim
>                                          90% module assets proces
>                                          90% chunk assets process
>                                          91% additional chunk ass
>                                          92% additional asset pro
>                                          92% chunk asset optimiza
>                                          93% after chunk asset op
>                                          94% after asset optimiza
>                                          95% emitting
> ----项目依赖健康检查-----
> WARN 项目依赖了 hoist-non-react-statics 的两个版本， [ '2.5.5', '
> 3.3.0' ]
> WARN 项目依赖了 path-to-regexp 的两个版本， [ '2.4.0', '1.7.0' ]
>                                          100%
> Starting the development server...
>     - Local:   http://localhost:4444/
>     - Network: http://192.168.31.99:4444/
> Hash: 2020d631b6362ca74f2a
> Version: webpack 4.29.6
> Time: 10099ms
> Built at: 2019-03-31 16:22:26
>             Asset       Size  Chunks             Chunk Names
>     css\index.css    563 KiB   index  [emitted]  index
> css\index.css.map   4.48 MiB   index  [emitted]  index
>       favicon.png   2.66 KiB          [emitted]
>        index.html  425 bytes          [emitted]
>       js\index.js   8.45 MiB   index  [emitted]  index
>   js\index.js.map   8.83 MiB   index  [emitted]  index
> Entrypoint index = css\index.css js\index.js css\index.css.map js
> \index.js.map
> 
> ERROR in ./src/pages/Dashboard/Dashboard.jsx 22:9
> Module parse failed: Unexpected token (22:9)
> You may need an appropriate loader to handle this file type.
> | import PageLoading from '../../components/PageLoading';
> | var Overivew = React.lazy(function () {
> >   return import('./components/Overivew');
> | });
> | var TabChart = React.lazy(function () {
>  @ ./src/pages/Dashboard/index.js 1:0-36 2:15-24
>  @ ./src/routerConfig.js
>  @ ./src/layouts/UserLayout/UserLayout.jsx
>  @ ./src/layouts/UserLayout/index.js
>  @ ./src/router.js
>  @ ./src/index.js
>  @ multi ./node_modules/@babel/polyfill/lib/index.js ./node_modul
> es/react-dev-utils/webpackHotDevClient.js ./src/index.js
> ERR! Failed to compile.
> 
> ./src/pages/Dashboard/Dashboard.jsx 22:9
> Module parse failed: Unexpected token (22:9)
> You may need an appropriate loader to handle this file type.
> | import PageLoading from '../../components/PageLoading';
> | var Overivew = React.lazy(function () {
> >   return import('./components/Overivew');
> | });
> | var TabChart = React.lazy(function () {
>

**Comment by zzyyzz1992** [comment]
经过测试，切换到Ubuntu也是报一样的错误。

**Comment by zzyyzz1992** [comment]
Solved！
[Inspired by this](https://github.com/webpack/webpack/issues/8656)
npm update acorn --depth 20
npm dedupe
npm install webpack

话说你们的package.json 里面为什么没有webpack?

**Comment by zzyyzz1992** [comment]
另外建议midway 的package.json中加入cross-env，[否则win平台根本构建不起来](https://blog.csdn.net/z69183787/article/details/54138818)。

**Comment by imsobear** [comment]
https://github.com/webpack/webpack/issues/8656

这是一个 npm 扁平化+webpack 的问题，可以参考这个 issue 处理，或者使用 cnpm 安装依赖。cross-env 这个我们在模板上加一下。

**Comment by gooddaddy** [comment]
我项目是从Iceworks 2.17.*生成的，目前升级到2.18.1,按照你的方法貌似不行.

**Comment by zzyyzz1992** [comment]
@gooddaddy 我发现win下node坑太多，现在使用wsl模拟linux环境，建议你尝试一下

**Comment by zixi0007** [comment]
怎么解决，我也是一样的问题。
Failed to compile
./src/pages/Dashboard/Dashboard.jsx 22:9
Module parse failed: Unexpected token (22:9)
You may need an appropriate loader to handle this file type.
| import PageLoading from '../../components/PageLoading';
| var Overivew = React.lazy(function () {
>   return import('./components/Overivew');
| });
| var TabChart = React.lazy(function () {

///////////////////////////////

解决方法是在项目根目录下执行这个命令，然后重启就可以了。
cnpm install webpack
