### ISSUE TITLE
Input 控件使用trim属性的错误逻辑

### ISSUE THREAD

**Issue by wangiv2** [alibaba/ice#1722]
## 问题描述

当Input控件使用trim属性的时候，当我输入空格时就会处罚onChange事件，然后把正常需要输入的空格给trim掉了，这样会导致需要正常输入空格不能输入空格。例如输入：“this is the good tool.”

**Comment by imsobear** [comment]
@wangiv2 请按照模板编写 issue，组件问题请在这里反馈：https://fusion.design/feedback
