### ISSUE TITLE
icework官网的组件的菜单太卡了，点开浏览器就挂了

### ISSUE THREAD

**Issue by guoqn** [alibaba/ice#1727]
## 问题描述
[ICE组件官网太卡了，一点开就挂了](https://alibaba.github.io/ice/component/menu)

**Comment by imsobear** [comment]
建议录屏给个 demo 然后再 reopen 下 issue，我这边看起来没有问题

**Comment by guoqn** [comment]
是打开之后,稍微滚动下页面的组件,很卡,不顺滑...
