### ISSUE TITLE
安装业务组件时增加版本检查机制

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#1733]
## 问题描述
业务组件安装依赖会默认添加最新的版本，导致 0.x 和 1.x 的兼容问题，在安装时增加版本检查确认机制

**Comment by imsobear** [comment]
不限于业务组件，任何 npm 包，只要最新版本跟 package.json 里的版本有 break change，都需要给用户二次确认下

**Comment by chenbin92** [comment]
fixed: https://github.com/alibaba/ice/pull/1780
