### ISSUE TITLE
ice-scripts的依赖如何升级

### ISSUE THREAD

**Issue by cpa0701** [alibaba/ice#1738]
npm install之后出现ice-scripts里面的依赖需要升级的提示
![image](https://user-images.githubusercontent.com/24648209/55388186-6705c500-5565-11e9-964a-3a9c85289c63.png)
请问如何进行升级

**Comment by chenbin92** [comment]
ice-scripts 本身的依赖升级需要 ice-scripts 开发者去进行升级，你那边在安装时忽略该提示
