### ISSUE TITLE
删除package.json下buildConfig.entry后，走多页打包模式运行出错

### ISSUE THREAD

**Issue by frontMoment** [alibaba/ice#1739]
https://github.com/alibaba/ice/blob/3e1fd61de420beec054d658ea737e9c8bd7ced87/tools/ice-scripts/lib/config/getEntryHtmlPlugins.js#L25

此处代码没有做变量保护，调整如下即可, @imsobear ：

```
const entriesNames = Object.keys(entries || {});
```

**Comment by chenbin92** [comment]
单页或者多页模板都需要指定对应的 `buildConfig.entry`，不然 ice-scripts 在运行时找不到对应的入口文件，故而这里没有兼容逻辑，也不需要有兼容逻辑吧

**Comment by frontMoment** [comment]
> @frontMoment 单页或者多页模板都需要指定对应的 `buildConfig.entry`，不然 ice-scripts 在运行时找不到对应的入口文件，故而这里没有写兼容逻辑。配置多页入口如下：
> 
> ```
> "buildConfig": {
>   "entry": {
>      "dashboard": "src/pages/dashboard/index.js",
>      "about": "src/pages/about/index.js"
>   }
> }
> ```

https://github.com/alibaba/ice/blob/master/tools/ice-scripts/lib/config/webpack.config.basic.js#L120

这里的逻辑是 entry不存在的情况下，才会走多页模式，所以多页下是不需要配置的，而且每次家页面都要手动配置是不人性化的

**Comment by frontMoment** [comment]
@chenbin92 https://github.com/alibaba/ice/blob/master/tools/ice-scripts/lib/config/webpack.config.basic.js#L120

这里的逻辑是 entry不存在的情况下，才会走多页模式，所以多页下是不需要配置的，而且每次家页面都要手动配置是不人性化的

**Comment by chenbin92** [comment]
@frontMoment 我这边处理下

**Comment by frontMoment** [comment]
@chenbin92 @imsobear https://github.com/alibaba/ice/blob/master/tools/ice-scripts/lib/config/webpack.config.basic.js#L88

这块的逻辑感觉也有点问题，getPlugin 的形参 entry 并不是最终的 `finalWebpackConfig.entry`。

**Comment by chenbin92** [comment]
@frontMoment   https://github.com/alibaba/ice/pull/1752
