### ISSUE TITLE
ICE Design Pro compile failed because of dynamic import

### ISSUE THREAD

**Issue by xiao-linxin** [alibaba/ice#1742]
使用Iceworks构建的全新项目启动失败。
环境：
macOS Mojave10.14.4
Iceworks 2.18.2
Node v11.11.0
![image](https://user-images.githubusercontent.com/20390177/55442880-07e69580-55e3-11e9-8f5c-916ce691ff3b.png)
![image](https://user-images.githubusercontent.com/20390177/55442919-29e01800-55e3-11e9-9c8e-496d2bf3ed66.png)
![image](https://user-images.githubusercontent.com/20390177/55442945-53993f00-55e3-11e9-9f91-1f0581918388.png)
![image](https://user-images.githubusercontent.com/20390177/55442956-5dbb3d80-55e3-11e9-811a-3c204026dabd.png)

**Comment by imsobear** [comment]
参考这个 issue https://github.com/alibaba/ice/issues/1721

**Comment by xiao-linxin** [comment]
嗯嗯，发现了。采取的步骤：
npm install webpack@4.28.4
npm install acorn-dynamic-import@4.0.0
npm update acorn --depth 20
npm dedupe
