### ISSUE TITLE
ice-模板 【项目管理系统】  启动报错

### ISSUE THREAD

**Issue by macmatilda** [alibaba/ice#1745]
## 问题描述

Iceworks 2.18.2
【模板】-【项目管理系统】-【使用该模板】
## 错误信息

./node_modules/react-trello/dist/styles/Base.js
Module not found: Can't resolve 'styled-components' in '/Users/hhydev/iceworks-workspace/test1/node_modules/react-trello/dist/styles'

**Comment by chenbin92** [comment]
安装依赖问题，注意看报错信息，安装下 `npm i styled-components -S`
