### ISSUE TITLE
建议FormBinder支持表单性能优化方案

### ISSUE THREAD

**Issue by frontMoment** [alibaba/ice#1750]
当使用FormBinder组件时，表单内容稍微多一点时，表单便会出现卡顿，因为 Input 是一种高频的state更新，会引起整个表单的重新render。

方案的解决思路：提供一个debounce高阶组件 或者 在 FormBinder 组件内部做 onChange 回调函数 debounce，

**Comment by boiawang** [comment]
@frontMoment 近期会推出新的 [form](https://github.com/ice-lab/react-materials/blob/master/components/form/README.md) 组件，对性能体验和可读性上做了优化，未来 FormBinder 不再维护.
