### ISSUE TITLE
业务组件开发未解析CSS

### ISSUE THREAD

**Issue by tao1991123** [alibaba/ice#1755]
在demo里面的markdown文件夹写样式 不解析 

例如:
![](https://img.alicdn.com/tfs/TB1eQRKPxjaK1RjSZFAXXbdLFXa-1646-1368.png)

解析出来是这个样子
p标签内的内容没有任何变化

![](https://img.alicdn.com/tfs/TB1sy0LPsfpK1RjSZFOXXa6nFXa-1902-1200.jpg)

**Comment by imsobear** [comment]
ice-scripts@1.10.0

**Comment by bindoon** [comment]
文档里面 ` ````css` 的样式应该自动解析，不应该要增加 importStyle: true 才解析
