### ISSUE TITLE
icon选择困难

### ISSUE THREAD

**Issue by zaoshang67dian** [alibaba/ice#1761]
有没有不同的icon type和图标的对应表，都不知道有哪些type可以用

**Comment by imsobear** [comment]
目前飞冰有两个 icon 组件，支持的 icon 类型文档里都可以看到：

- 基础组件 Icon: https://alibaba.github.io/ice/component/icon
- 业务组件 FoundationSymbol: https://alibaba.github.io/ice/component/foundationsymbol

如果这些 icon 还不能满足需求的话，可以选择使用 DynamicIcon(https://ice.alibaba-inc.com/ice/component/dynamicicon) 或者直接使用 iconfont

后续我们会补充文档。
