### ISSUE TITLE
Iceworks 后续会考虑支持基于Ant Design Pro 的添加页面、区块功能吗？

### ISSUE THREAD

**Issue by qianxuemin** [alibaba/ice#1762]
<!--
## 环境信息

- 操作系统：macOS
- Iceworks 版本： 2.15.0

## 问题描述

Iceworks 后续会考虑支持基于Ant Design Pro 的添加页面、区块功能吗？

**Comment by chenbin92** [comment]
@qianxuemin  iceworks 多物料层面是通用的协议，按照 [物料数据协议](https://alibaba.github.io/ice/docs/materials/devtools) 自建物料(区块/模板)，以及 [模板规范](https://alibaba.github.io/ice/docs/materials/add-templates) 即可接入使用

物料开发者工具 [ice-devtools](https://alibaba.github.io/ice/docs/materials/devtools)
