### ISSUE TITLE
构建组件 src 不支持 export default foo from 语法

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#1763]
https://github.com/alibaba/ice/blob/761ee806f5dfffb2f2d99a520b45829774b4f077/tools/ice-scripts/lib/config/getBabelConfig.js#L44

https://github.com/alibaba/ice/blob/761ee806f5dfffb2f2d99a520b45829774b4f077/tools/ice-scripts/lib/component/buildSrc.js#L21

配置了这个插件，但是看起来并没有生效，可能是跟其他配置冲突了

![image](https://user-images.githubusercontent.com/2505411/55682668-188f6680-5969-11e9-861a-70b29fc28f4a.png)

**Comment by ClarkXia** [comment]
插件本身是生效的，构建组件时需要通过babel额外对组件依赖样式进行分析，这部分babel插件缺少@babel/plugin-proposal-export-default-from导致构建出错

**Comment by imsobear** [comment]
我智障了。。。

**Comment by imsobear** [comment]
ice-scripts@1.10.0
