### ISSUE TITLE
ice-scripts 升级 gulp 依赖

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#1768]
![image](https://user-images.githubusercontent.com/2505411/55698533-e4638680-59f8-11e9-9b1c-cf5fcccddff3.png)

**Comment by ClarkXia** [comment]
目前gulp仅用来控制build流程中的输出目录清除和构建，建议删除gulp依赖

**Comment by imsobear** [comment]
嗯 没啥用就干掉吧
