### ISSUE TITLE
Ellipsis 多行文字控制组件考虑不周全

### ISSUE THREAD

**Issue by mosikoo** [alibaba/ice#177]
不支持「-webkit-line-clamp」的情况下
当我的content为中英文混合的时候，比如'一个两个三个个七个八个23231112九个十个十一个',
**大概显示效果如下**
```
一个两个三个个七个
八个232311...
```
**理论应该显示如下**
```
一个两个三个个七个
八个2323112九个...
```
并不是每个字体的宽度都是一样的。所以判断方法应该换一个

**Comment by yujiangshui** [comment]
是的，被发现了，我们看看怎么搞，目前唯一的就是读取当前字体的英文、数字的渲染宽度进行计算？你有什么好的思路没？

**Comment by wssgcg1213** [comment]
我倒有个思路, 在页面上创建一个看不到的元素, 计算宽度

**Comment by wssgcg1213** [comment]
对于英文这种非等宽字体处理比较麻烦

**Comment by wssgcg1213** [comment]
https://github.com/yuanqing/line-clamp  @yujiangshui

**Comment by mosikoo** [comment]
将设如下一个DOM

    <div>一个两个三个个七个八个212332311省略省略</div>

- 首先dom.cloneNode(true) 克隆得到cloneDOM，之后的任何操作都在cloneDOM上操作
- cloneDOM加上visibility、overflow、position:absolute、 z-index让其不显示
- 具体思路就是每次减少内容块一个字符，判断 cloneDOM 的高度是否符合要求



当然也不能每次都是一个字符一个字符的减少，这样性能较差，

所以假设原来5行，要减少到2行，则第一次一次性减少至3行，然后后面再一个字符一个字符的减少

[demo参考](https://github.com/mosikoo/clamp/blob/master/index.js)

**Comment by yujiangshui** [comment]
@mosikoo 你的思路挺好的。

我调研搜了下其他的，发现 https://github.com/xiaody/react-lines-ellipsis 这个做的算是比较完善的了，html 也支持。 @noyobo @wssgcg1213 @chenbin92   可以下掉我们的，使用这个社区组件吧。

**Comment by yujiangshui** [comment]
试用了下，有意外，不是很好用，代码写的太复杂了，我来重新封装一个吧

**Comment by chenbin92** [comment]
建议使用社区方案 [react-lines-ellipsis](https://www.npmjs.com/package/react-lines-ellipsis) 代替，或者自行封装。
