### ISSUE TITLE
物料请求及创建项目失败, 错误：SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert access denied

### ISSUE THREAD

**Issue by ariyuan** [alibaba/ice#1774]
打开之后，见控制台有错误

![image](https://user-images.githubusercontent.com/5848071/55710616-9614ae80-5a1d-11e9-91d2-9666b05247ca.png)

公司有proxy, IE代理已经设置，通过chrome可以正常访问https://ice.alicdn.com/assets/react-materials.json

尝试创建项目时，同样报SSL出错

![image](https://user-images.githubusercontent.com/5848071/55710830-0b807f00-5a1e-11e9-921e-c386842d06b5.png)

cmd information:

![image](https://user-images.githubusercontent.com/5848071/55710878-22bf6c80-5a1e-11e9-82f6-87f85efd2733.png)

**Comment by chenbin92** [comment]
更新到 2.18.1 版本已修复，如果还有类似问题可以重新打开该 issue

**Comment by ariyuan** [comment]
> 更新到 2.18.2 版本已修复，如果还有类似问题可以重新打开该 issue

我用的就是2.18.2, 4月1号发布的那个版本
