### ISSUE TITLE
想创建一个前后端分离的项目，但是GUI界面上没有勾选koa等后台服务这个select选项

### ISSUE THREAD

**Issue by kingwubin** [alibaba/ice#1778]

**Comment by chenbin92** [comment]
参考：https://alibaba.github.io/ice/docs/advanced/node-project

**Comment by kingwubin** [comment]
![image](https://user-images.githubusercontent.com/19777851/55768170-577b0480-5aae-11e9-8729-a15bfc9ae89f.png)
