### ISSUE TITLE
想搭建一个koa项目，没有koa这个select选项，我用户界面是这样子的

### ISSUE THREAD

**Issue by kingwubin** [alibaba/ice#1779]
![image](https://user-images.githubusercontent.com/19777851/55768272-d2dcb600-5aae-11e9-8f1e-c749dc2d8be6.png)

**Comment by chenbin92** [comment]
@kingwubin 你是内部用户？

**Comment by kingwubin** [comment]
@chenbin92 不是内部用户啊

**Comment by kingwubin** [comment]
@chenbin92 你给的链接跟我提的这个问题没有什么关系吧

**Comment by chenbin92** [comment]
@kingwubin  2.19.0 版本已修复，4月15号会发布版本
