### ISSUE TITLE
模板生成相关代码 eslint 规则不通过问题

### ISSUE THREAD

**Issue by noyobo** [alibaba/ice#178]
![image](https://user-images.githubusercontent.com/1292082/36936239-9b7cda76-1f3d-11e8-8ea3-dc09deb9ed32.png)

![image](https://user-images.githubusercontent.com/1292082/36936240-9f2a3efc-1f3d-11e8-8905-c8c2b3ced516.png)

**Comment by wssgcg1213** [comment]
ejs 不能控制空行, 需要成 handerbars 或者 xtemplate
