### ISSUE TITLE
Set up high quality materials for Vue

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#1783]
## Background

We have previously produced a set of [Vue materials](https://github.com/ice-lab/vue-materials) under the co-construction of the community. But it's not rich enough and not high quality compared to the current officially maintained [React materials](https://github.com/ice-lab/react-materials).So we hope to improve the Vue materials.

## Proposal

- Use Vue, Vue CLI, and a basic UI component(like Element, iView…)
- 3+ scaffolds, 20+ blocks, 5+ biz components
- Support international

## Skill Requirements

- Vue, Vue CLI, Element or others UI Components
- iceworks

**Comment by tanhengyeow** [comment]
Hi @imsobear 

I'm interested in this issue too! May I know what's the plan for this project? For example, should all the new Vue materials be the same as the current official React materials?

Also, are there plans to add new React materials?

**Comment by imsobear** [comment]
React materials is enough unless we have some better ideas. Next we will mainly build ice design pro(a scaffold).

Not require react and vue materials to be exactly the same. In addition, this issue may be a small thing. I don't want to use it as one of the Summer of code projects.
