### ISSUE TITLE
implement vue-cli adapter for iceworks

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#1784]
We hope to enhance the front-end development experience with the Iceworks GUI tool, which allows you to quickly add pages and configure build capabilities based.

But in fact, many of iceworks' features are coupled to directory structures and engineering tools. Such as add page, add block, start dev…

To solve these problems, we designed the Adapter architecture. Different tools or different directories can implement these capabilities through an adapter, which can be used smoothly in Iceworks. At the same time, our ICE team will implement an ice-scripts based adapter. We hope someone can implement a vue-cli adapter.

- [Adapter interface](https://github.com/alibaba/ice/blob/feat-project-interface/packages/iceworks-server/src/interface/project.ts)
- Adapter spec: TODO

**Comment by Kaushl2208** [comment]
@imsobear Hey, I am interested in solving this issue as my Soc2019 project. Can you guide me through where to start off? Or is there any platform you guys use to have discussions like gitter, slack?

**Comment by imsobear** [comment]
https://gitter.im/alibaba/ice @Kaushl2208

**Comment by chenbin92** [comment]
@imsobear  已实现 https://github.com/alibaba/ice/tree/iceworks/release-3.x/packages/iceworks-server/src/lib/adapter-vue-v1
