### ISSUE TITLE
Enhance  docs

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#1786]
### 目标

1. 文档驱动开发：我们开发的所有功能都应该在文档上有所体现，同时持续维护文档和代码的双向关系
2. 一站式的文档体验：文档尽量聚合

### 方案

1. 顶部导航「文档」入口，包含用户最核心的流程
2. ice-scrits/ice-devtools/iceworks/icedesign 文档目录各自独立，入口暂时放在「生态系统」下，后续看具体场景增强

#### 顶部导航「文档」目录

- 关于飞冰：what/why/how
- 使用 Iceworks 创建项目：支持创建 React/Vue/……；支持 GUI 和命令行两种；dev/build/publish 流程
- 开发：
	- 前端基础：HTML/js/css/React、npm 概念、包版本管理等
	- 官方 React 物料源：组件、模板
	- 前后端通信：axios, DataBinder, 跨域问题
	- 数据状态管理：icestore
	- 表单方案：暂无，组件 + Iceworks 场景搭建
	- 表格方案：暂无，组件 + Iceworks 场景搭建
	- 路由管理
	- 图表方案
	- 国际化方案
	- 菜单管理
	- 权限管理
- 测试：
	- 暂无，对标 CRA，工程能力需要补充
- 后端集成
	- Node.js Koa
	- Java SpringMVC
	- 类 Surge：内部 Air
- 发布资源
	- 资源发布：CDN，server，Nginx 三种方式
	- 版本号管理
- 产品监控
	- 数据埋点：暂无，cnzz
	- 异常监控：暂无，retcode
- 资源
	- 常用工具：编辑器、Fusion Cool 等
	- 常用社区组件

#### Iceworks

- 关于飞冰
- Iceworks
- 项目开发
- ice-scripts
- 自定义物料
- 中后台设计
- 前端知识

#### ice-scripts

* 介绍：是什么，特性，为什么不是 Create-React-App
* 命令行使用
* 工程配置
* 进阶
	* 使用TypeScript
	* 主题配置：主题配置方式和主题变量的使用
	* 数据 Mock
	* 接口代理
	* 业务组件开发：目录结构等
	* 自定义初始模板：业务组件、区块、项目
* 常见需求
	- 使用 monaco-editor
	- 调试本地资源
	- 加载本地图片
	- 减少图表资源大小
	- 本地开发使用 BrowserRouter

#### ice-devtools

- 关于物料
- 物料初始化与开发
- 物料托管与使用
- 物料数据协议
- 自定义物料模板：.template、npm 包
- React 物料开发指南：工程使用、不同基础组件（Antd）定制
- Vue 物料开发指南：不同基础组件（Element）定制
- Angular 物料开发指南

#### ice-design

保持现状

## 待补充文档

> 从 docs/enhance-2.0 分支切出新分支，完成后向 docs/enhance-2.0 提 MR 即可

### P0

- [x] 关于 Iceworks @梧忌
- [x] 前后端通信     @虚左
- [ ] 前端静态资源发布：内/外 @大果
- [ ] 版本号管理：内/外  @大果
- [ ] Node.js 集成  @夜宸
- [ ] Java 集成     @夜宸
- [ ] HTML 托管服务集成 @夜宸

### P1

- [x] 产品数据统计：内/外  @思忠 
- [x] 代码稳定性监控：内/外 @思忠
- [x] 常用工具推荐：@思忠
- [x] 物料相关文档：梳理、完善、优化、补充原先的模板规范 @泠铮
- [x] ice-scripts：梳理、完善、优化 @鲲尘
- [ ] 图表方案 @夜宸
- [x] 样式方案 @虚左

### P2

- [ ] 数据状态管理，需要完善 @梧忌
- [ ] 社区组件推荐，需要完善 @大果

### P3

> 因能力缺失，暂时无法完成

- 使用 Jest 写测试用例，需要工程支持  @鲲尘
- 表单方案，需要能力支持 @虚左

**Comment by chenbin92** [comment]
@imsobear `/advanced/webpackrc`  和 `/materials/devtools` 两个引导可以直接去掉，觉得意义不大

**Comment by imsobear** [comment]
@chenbin92 「建议保留物料的现有结构」这个点应该在我提 issue 的时候就给出反馈

然后说下我为什么把这个合并到「进阶->使用 ice-devtools 开发自定义物料」：

目前 Iceworks/pro/物料都各自包含 6 篇以上的文档，其实按照这个思路 ice-scripts 也可以拆除多篇文档，但是目前的信息架构方式这样做问题太大，导航太长，重要信息很可能被放在后面，因此这块我期望的是先重构文档的信息结构，再为每个部分建立自己的文档体系，每一块都独立的 owner，信息结构可以学习下微信小程序：

![image](https://user-images.githubusercontent.com/2505411/55859258-4a404180-5ba4-11e9-8f45-4bab2cfbf356.png)

**Comment by imsobear** [comment]
## 文档 2.0

### 目标

1. 文档驱动开发：我们开发的所有功能都应该在文档上有所体现，同时持续维护文档和代码的双向关系
2. 一站式的文档体验：交互跟微信小程序类似，顶部是一级导航，左边是二级导航，中间是文档内容，右边是当前文档的目录结构

### 整体目录

- 关于飞冰
  - 关于飞冰：Iceworks、ice-devtools 等
  - 基于 Iceworks + 官方 React 物料快速开发项目
  - 基于 Iceworks + 社区 Vue 物料快速开发项目
  - 常见问题
- 设计：跟目前设计文档目录保持一致
- ice-scripts
	- 介绍：是什么，特性，为什么不是 Create-React-App
	- 使用指南
	- 使用 TypeScript
	- 配置不同主题
	- 使用主题变量
	- Mock 能力
	- 业务组件规范：目录结构等
	- 资源发布 CDN（仅内部）：发布流程，abc.json, webapp 发布, 传入构建参数等
	- 常见需求：使用 monaco-editor、调试本地资源、加载本地图片、减少图表资源大小、本地开发使用 BrowserRouter
- 官方 React 物料
	- 介绍：Fusion 基础组件、模板区块、业务组件
	- 项目开发：Iceworks（模板/自定义，添加页面等）、ice-scripts init
	- 前后端通信方案
	- 表单方案
	- 国际化方案
	- 数据状态管理方案
	- 布局方案
	- 菜单方案
	- 路由方案
	- 权限方案
	- 图表方案
	- 资源按需加载方案
	- React-Router 使用指南：官方文档、如何跳转、HashRouter -> BrowserRouter 404 问题
	- 常用社区组件推荐
	- 基础组件 1.x 升级指南
	- 自定义 webpack 使用飞冰 React 物料
- 自定义物料
	- 物料理念介绍
	- 物料初始化与开发
	- 物料托管与使用
	- 物料数据协议
	- React 物料开发指南：工程使用、不同基础组件定制
	- Vue 物料开发指南
	- Angular 物料开发指南
- Iceworks
	- 介绍
	- 使用流程
	- 插件
	- 使用自定义物料
	- 设置功能
	- 常见问题：自定义编辑器、杀毒软件等
- 前端知识
	- 前端基础：HTML/js/css
	- 使用社区 npm 包：npm 概念、版本管理等
	- 常用工具推荐：Git 等

**Comment by alvinhui** [comment]
不知道上面这个从上到下是不是就是一级目录从左到右的顺序。如果是的话，我觉得不好。
我更倾向于：

- 关于飞冰
- Iceworks
- 项目开发
- ice-scripts
- 自定义物料
- 中后台设计
- 前端知识

我是从用户触达层次上考虑的。

**Comment by imsobear** [comment]
> 不知道上面这个从上到下是不是就是一级目录从左到右的顺序。如果是的话，我觉得不好。
> 我更倾向于：
> 
> * 关于飞冰
> * Iceworks
> * 项目开发
> * ice-scripts
> * 自定义物料
> * 中后台设计
> * 前端知识
> 
> 我是从用户触达层次上考虑的。

这块目前还没确定，下周确定掉，目前先梳理确定各个产品的目录

**Comment by chenbin92** [comment]
![image](https://user-images.githubusercontent.com/3995814/56728281-0133e400-6785-11e9-83fc-3790deee4c5f.png)

这块统一归为 `官方 React 物料` 感觉有点不搭，官方物料还是指组件，区块，模板比较好，基于物料快速构建中后台应用的介绍和使用，`通用方案` 可以独立一个类目，到时可以如下展示宣传：

![image](https://user-images.githubusercontent.com/3995814/56728681-f3cb2980-6785-11e9-82c3-3439e520fd35.png)

**Comment by imsobear** [comment]
分类名字改下就可以，比如 React 项目开发，不再单独加分类了 @chenbin92

**Comment by chenbin92** [comment]
> 分类名字改下就可以，比如 React 项目开发，不再单独加分类了 @chenbin92

改一下名字也可以

**Comment by DoranYun** [comment]
自定义物料目录结果不用调整，后期可以加一个优秀第三方开源物料的列表。

**Comment by alvinhui** [comment]
### Iceworks

- 简介
- 快速上手
- 项目管理
- 工程管理
- 使用物料
- 自定义物料
- 设置
- 常见问题

### 其他

在文档的其他部分中也包含有 Iceworks 相关的内容，这部分内容由 GUI 小组负责：

- 关于飞冰 - 简介 - Iceworks
- 关于飞冰 - 快速上手 - 使用 Iceworks
- 官方物料 - 项目开发 - Iceworks（模板/自定义，添加页面等）

**Comment by ClarkXia** [comment]
ice-scripts
* 介绍：是什么，特性，为什么不是 Create-React-App
* 快速开始
* 完整指南 
* 进阶
    * 使用TypeScript
    * 主题配置（主题配置方式和主题变量的使用）
    * 数据Mock
    * 接口代理
    * 自定义初始模板：业务组件、区块、项目
    * 业务组件开发：目录结构等
    * 区块：（初始化区块 添加区块）
* 部署
    * 资源发布 CDN（仅内部）：发布流程，abc.json, webapp 发布, 传入构建参数等
* 常见需求：使用 monaco-editor、调试本地资源、加载本地图片、减少图表资源大小、本地开发使用 BrowserRouter

---
快速开始，安装 -> 初始化项目 ->  dev -> build
复杂场景感觉可以整合到进阶里面

**Comment by imsobear** [comment]
主 issue 更新五一假期前跟 @yuanyan 讨论的结果
