### ISSUE TITLE
ice-scripts support add page & add block

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#1791]
## `ice add block ${npmName}`

两种模式

### 在项目根目录执行
  
- 询问加到哪个页面或者全局
- 添加到对应位置

### 在非项目根目录执行

- 直接添加到当前目录（来自 fie 的强需求）

## `ice add page`

> 比较轻量简单的功能

直接在 src/pages 里添加一个空白页面（index.jsx），不关心 routerConfig 和 menuConfig，需要用户自己手动引入

**Comment by chenbin92** [comment]
`ice add block ${npmName}` 赞成方式二，直接添加到当前目录

**Comment by imsobear** [comment]
@chenbin92 我的意思是两种方式都支持，支持方式一主要是为了跟 add page 的表现一致，可以看看有没有必要

**Comment by imsobear** [comment]
ice-scripts@1.10.0
