### ISSUE TITLE
小程序模板及Angular 模板预览一直在loading

### ISSUE THREAD

**Issue by NaughtBoy** [alibaba/ice#1792]
## 小程序模板及Angular 模板预览一直在loading

RT，在iceworks 里面打开小程序模板及Angular 模板预览，网页一直显示：加载中，请稍候。  
其他模板就不会。
## 错误信息

![loading](https://user-images.githubusercontent.com/8444080/55926207-07817680-5c43-11e9-9d20-4a46c2d0b82c.png)

**Comment by imsobear** [comment]
小程序和 Angular 两个链路目前支持不好，已在最新版本暂时下线，后续我们会重新整理这两个链路。

**Comment by vincentCheng** [comment]
请问小程序大概什么时候能够上线？
