### ISSUE TITLE
ice-scripts 不再锁死依赖版本

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#1794]
## 背景

因为一些历史原因（bael 7 初期不稳定），我们把很多依赖版本直接锁死了，但事实这种写死是没有意义的，用户安装时间接的依赖还是会自动用最新兼容版本。另一方面工具层面这样锁死依赖问题比较多，比如一些 bug 修复无法感知、用户端可能会安装重复版本引入问题，因此需要将这些写死的版本放开。

## 方案

- 将所有依赖放开 https://github.com/alibaba/ice/pull/1776
- 测试回归

**Comment by ClarkXia** [comment]
相关case回归

|模版 | ice init | ice dev | ice build |
| :--- | :----: | ----: | ----: |
| Lite | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| TS | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| Pro | :white_check_mark: | :white_check_mark: | :white_check_mark: |

**Comment by imsobear** [comment]
有个 corejs 的版本warning我记得

**Comment by imsobear** [comment]
ice-scripts@1.10.0
