### ISSUE TITLE
ts/tsx 文件支持自动引入 @alifd/next 组件样式

### ISSUE THREAD

**Issue by bindoon** [alibaba/ice#1800]
## 问题描述

.js 结尾文件支持自动引入style； .ts .tsx 结尾文件不支持

![image](https://user-images.githubusercontent.com/5189853/55945606-b478e500-5c7d-11e9-838a-11a7d73482d8.png)

![image](https://user-images.githubusercontent.com/5189853/55945669-d4100d80-5c7d-11e9-9845-1e1bb8ffe321.png)

**Comment by bindoon** [comment]
另外 npm run build 编译 lib 文件的时候报错

![image](https://user-images.githubusercontent.com/5189853/55947817-cf4d5880-5c81-11e9-82ec-6ccabddee13d.png)

**Comment by ClarkXia** [comment]
目前组件模版构建使用babel，考虑依赖@babel/preset-typescript支持ts编译，同时对构建产物进行依赖分析，自动引入@alifd/next相关组件样式

**Comment by imsobear** [comment]
@ClarkXia 我上次说的那个方案呢？基于编译后 lib 目录文件生成 lib/style.js

**Comment by ClarkXia** [comment]
嗯 就是基于构建产物来生成lib/style.js，目前组件模版编译lib是没有处理ts的，构建处理步骤如下：
1. 通过babel编译lib文件，包括js和ts
2.根据lib下构建产物，分析依赖来生成style.js，这里可以直接用正则处理require依赖
3.分析依赖生成对应lib/style.js

**Comment by imsobear** [comment]
ice-scripts@1.10.0
