### ISSUE TITLE
[windows]下载Iceworks2.18.2版本被报存在危险，无法下载

### ISSUE THREAD

**Issue by StarOfLife** [alibaba/ice#1803]
## 问题描述

下载Iceworks-setup-2.18.2.exe的时候，谷歌浏览器提示
![图片](https://user-images.githubusercontent.com/10042282/56010545-a5924100-5d16-11e9-8cb4-392265f59db8.png)

**Comment by alvinhui** [comment]
紧急解决，可以参考教程：https://jingyan.baidu.com/article/9faa7231b558bd473c28cbdd.html
具体原因我们再看一下。

**Comment by imsobear** [comment]
@alvinhui 我也遇到这个问题了

**Comment by imsobear** [comment]
![image](https://user-images.githubusercontent.com/2505411/56705378-37e90a80-6743-11e9-914d-4c5b1bf4313d.png)

**Comment by alvinhui** [comment]
今天尝试在一台 win10 电脑上安装 iceworks@2.19.1 时，报安全警告，禁止执行。

**Comment by alvinhui** [comment]
2.20.0 版本将解决该问题，请在 5.13 后更新到 2.20.0 版本。
