### ISSUE TITLE
最新版本2.18.2的vue所有模板构建总是失败，更换npm源也没有用

### ISSUE THREAD

**Issue by ylh23y** [alibaba/ice#1804]
最新版本2.18.2的vue所有模板构建总是失败，更换源cnpm和npm也没有用

**Comment by chenbin92** [comment]
贴一下错误日志，另外构建是一个本地执行的过程，正常情况下启动没问题构建一般也没问题的

**Comment by ylh23y** [comment]
![sdf](https://user-images.githubusercontent.com/13464610/56020465-d172ee00-5d39-11e9-9400-b4c3260fb2ac.png)
![dd8](https://user-images.githubusercontent.com/13464610/56020478-d637a200-5d39-11e9-8dc7-4c58f4e77cbf.png)

**Comment by ylh23y** [comment]
![image](https://user-images.githubusercontent.com/13464610/56020546-fb2c1500-5d39-11e9-8ac3-3a503338c115.png)

**Comment by ylh23y** [comment]
![image](https://user-images.githubusercontent.com/13464610/56020754-7261a900-5d3a-11e9-90c7-7ec7cdb4586d.png)
构建的模板

**Comment by ylh23y** [comment]
![image](https://user-images.githubusercontent.com/13464610/56021597-71317b80-5d3c-11e9-9826-688c30db86c5.png)

**Comment by ZhijianZhang** [comment]
遇到一样的问题。已经尝试跑了 vue 物料里面的两个模板了，都不能跑。 我clone 了 vue-materials 的仓库，经过测试在 scaffolds 文件夹中的 admin-lite 模板是可以跑的，但是通过 ice 客户端生成的不能跑， 生成的项目不能跑的原因是 少了一个 vue.config.js 文件。
![image](https://user-images.githubusercontent.com/11473889/56458836-117f4400-63be-11e9-98c5-4a40a21d5bf2.png)
左边是 scaffolds 下 admin-lite 模板的文件列表，右边是 ice 生成的， 生成代码报错跟上面的同学遇到的是一样的。手动复制 admin-lite 的 vue.config.js  文件到右边，npm start 才能正常跑。 猜测是客户端的问题。@chenbin92 @ylh23y

**Comment by chenbin92** [comment]
@yiliang114 我这边试着生成了几次，都是会生成 `vue.config.js` 文件的，你那边是必现不会生成 `vue.config.js`  ？

**Comment by chenbin92** [comment]
@yiliang114  fixed https://github.com/ice-lab/vue-materials/pull/3

**Comment by alvinhui** [comment]
将会在 2.20.0 版本发布
