### ISSUE TITLE
[windows] 最新版本2.18.2安装依赖出现错误。

### ISSUE THREAD

**Issue by llh1187** [alibaba/ice#1806]
## 问题描述

:smile:
windows10 64bit
第一次使用这个软件，创建项目后安装依赖，发现一直报错，错误信息如下图，再创建了一个项目后还是报错。

## 错误信息
![捕获](https://user-images.githubusercontent.com/40154001/56033013-2d4b7000-5d56-11e9-8b09-cd53a518dac5.PNG)

**Comment by chenbin92** [comment]
@alvinhui 这个问题看起来还是网络问题导致的安装依赖失败
