### ISSUE TITLE
升级到2.18.2版本OSS插件失效

### ISSUE THREAD

**Issue by XiaoCheng123** [alibaba/ice#1807]
## 环境

系统环境：win10
Iceworks 版本： 2.18.2

## 问题描述

OSS无法刷新bucket列表

## 错误信息

![](https://github.com/XiaoCheng123/markdownImg/blob/master/%E5%9B%BE%E7%89%87/ice%E8%BF%90%E8%A1%8C%E9%94%99%E8%AF%AF.jpg?raw=true)

**Comment by chenbin92** [comment]
@XiaoCheng123  已处理 https://github.com/alibaba/ice/pull/1730#issue-266478211
