### ISSUE TITLE
启动后标题显示为“index”,除了上面菜单，无任何内容

### ISSUE THREAD

**Issue by ehero77** [alibaba/ice#1808]
## 问题描述
iceworks 2.18.2
windows 10
node.js v8.9.0

启动后，停留在一个空白页面：
![QQ截图20190414114409](https://user-images.githubusercontent.com/46411415/56088036-ac51bd00-5eaa-11e9-86c1-18cc56872de9.png)

使用开发人员工具，显示如下：

![QQ截图20190414115650](https://user-images.githubusercontent.com/46411415/56088117-99d88300-5eac-11e9-9a55-b49742f2ab52.png)

重装软件后依然

## 错误信息

log.log中无任何信息

**Comment by alvinhui** [comment]
感谢反馈问题。

- 请点击 console 栏，截图给我们看看有没有报错？
- 你选择了哪个模板？

**Comment by ehero77** [comment]
已经解决了
是与老版本有冲突
需要将老版本彻底卸载后，再重新安装
即，卸载后，手动将所有残留文件删除

**Comment by GPWiOS** [comment]
遇到相同问题。
<img width="866" alt="ice_error" src="https://user-images.githubusercontent.com/15536539/56449974-6afe5900-6353-11e9-9b24-b18363c630f6.png">
提示dist文件找不到，工程已有dist文件

**Comment by zuiliushang** [comment]
![image](https://user-images.githubusercontent.com/16831435/56862310-3dad4d00-69dc-11e9-9b43-e0e48363248f.png)

项目写一半突然这样 更新重装都无济于事

**Comment by alvinhui** [comment]
备注：@zuiliushang 是打开项目的时候报错

**Comment by alvinhui** [comment]
将会在 2.20.0 版本发布
