### ISSUE TITLE
飞冰的物料缺少angular的物料，如何给飞冰贡献Angular的物料？

### ISSUE THREAD

**Issue by rdkmaster** [alibaba/ice#1811]
## 问题描述

飞冰的物料缺少angular的物料，如何给飞冰贡献Angular的物料？

![image](https://user-images.githubusercontent.com/16191626/56107146-38c9b180-5f77-11e9-9c57-fb0613ff15b6.png)

[Jigsaw](https://github.com/rdkmaster/jigsaw)是中兴大数据出品的一套基于Angular的组件集，功能完备，非常强大，非常适合用来开发PC端的带有复杂交互过程的页面，同时支持深浅色系皮肤，可一键换肤。我们有兴趣与飞冰合作。

github首页上有个贡献物料的超链，但是跳过去后没发现有指导性的文档，有没有具体的知道手册？

**Comment by imsobear** [comment]
@rdkmaster 我这边建了一个钉钉群沟通，方便的话可以加下钉钉群讨论

![IMG_5260](https://user-images.githubusercontent.com/2505411/56110485-3bcc9e00-5f87-11e9-8fe2-ff0ef83aa8ed.JPG)

**Comment by imsobear** [comment]
https://github.com/ice-lab/angular-jigsaw-materials
