### ISSUE TITLE
windows版本无法构建成功

### ISSUE THREAD

**Issue by gntyu** [alibaba/ice#1818]
## 问题描述
同一套代码在mac可以成功构建，windows不行。
但是windows另一个项目能成功构建。

## 错误信息

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\iceworks-desktop\\resources\\bin\\node.exe',
1 verbose cli   'C:\\Users\\Administrator\\AppData\\Local\\Programs\\iceworks-desktop\\resources\\app\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.10.0
3 info using node@v8.9.4
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle @icedesign/reviews-management-scaffold@1.0.0~prebuild: @icedesign/reviews-management-scaffold@1.0.0
6 info lifecycle @icedesign/reviews-management-scaffold@1.0.0~build: @icedesign/reviews-management-scaffold@1.0.0
7 warn lifecycle The node binary used for scripts is C:\Program Files\nodejs\node.exe but npm is using C:\Users\Administrator\AppData\Local\Programs\iceworks-desktop\resources\bin\node.exe itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
8 verbose lifecycle @icedesign/reviews-management-scaffold@1.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle @icedesign/reviews-management-scaffold@1.0.0~build: PATH: C:\Users\Administrator\AppData\Local\Programs\iceworks-desktop\resources\app\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\work\kpi-dashboard-ui\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\MySQL\MySQL Server 5.5\bin;D:\MySQL5.5\bin;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\Users\Administrator\AppData\Roaming\npm;C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Administrator\AppData\Local\Programs\iceworks-desktop\resources\bin
10 verbose lifecycle @icedesign/reviews-management-scaffold@1.0.0~build: CWD: D:\work\kpi-dashboard-ui
11 silly lifecycle @icedesign/reviews-management-scaffold@1.0.0~build: Args: [ '/d /s /c', 'ice build' ]
12 silly lifecycle @icedesign/reviews-management-scaffold@1.0.0~build: Returned: code: 1  signal: null
13 info lifecycle @icedesign/reviews-management-scaffold@1.0.0~build: Failed to exec build script
14 verbose stack Error: @icedesign/reviews-management-scaffold@1.0.0 build: `ice build`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Administrator\AppData\Local\Programs\iceworks-desktop\resources\app\node_modules\npm\node_modules\npm-lifecycle\index.js:283:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Administrator\AppData\Local\Programs\iceworks-desktop\resources\app\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid @icedesign/reviews-management-scaffold@1.0.0
16 verbose cwd D:\work\kpi-dashboard-ui
17 verbose Windows_NT 10.0.16299
18 verbose argv "C:\\Users\\Administrator\\AppData\\Local\\Programs\\iceworks-desktop\\resources\\bin\\node.exe" "C:\\Users\\Administrator\\AppData\\Local\\Programs\\iceworks-desktop\\resources\\app\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 verbose node v8.9.4
20 verbose npm  v5.10.0
21 error code ELIFECYCLE
22 error errno 1
23 error @icedesign/reviews-management-scaffold@1.0.0 build: `ice build`
23 error Exit status 1
24 error Failed at the @icedesign/reviews-management-scaffold@1.0.0 build script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by imsobear** [comment]
@gntyu 日志里看不出有效信息，麻烦补全下相关信息，日志采用正确的格式。另外系统间的差异一般主要是 Node.js 和 npm 差别，工具本身正常情况下是没有问题的。

issue 我先 close 掉，信息补充完全后可自行 reopen。

**Comment by gntyu** [comment]
> @gntyu 日志里看不出有效信息，麻烦补全下相关信息，日志采用正确的格式。另外系统间的差异一般主要是 Node.js 和 npm 差别，工具本身正常情况下是没有问题的。
> 
> issue 我先 close 掉，信息补充完全后可自行 reopen。
不太清楚日志需要什么格式，以前没提过。不好意思额。
这样可以了么？补全了node和npm版本信息

**Comment by gntyu** [comment]
不太清楚日志需要什么格式，以前没提过。不好意思额。
这样可以了么？补全了node和npm版本信息
