### ISSUE TITLE
无法打开编辑器

### ISSUE THREAD

**Issue by xiaonini** [alibaba/ice#182]
安装了Visual Studio Code 但是点击‘’编辑器中打开‘’报错，无法查找到Visual Studio Code
![tim 20180305113344](https://user-images.githubusercontent.com/22790394/36956426-4e21ef0a-2069-11e8-8121-156b60d90a8a.png)
![tim 20180305113420](https://user-images.githubusercontent.com/22790394/36956427-4e65b096-2069-11e8-86fb-877cc5ca16a8.png)
![tim 20180305113601](https://user-images.githubusercontent.com/22790394/36956452-6b8ab77a-2069-11e8-83ed-da614a8a6a05.png)

**Comment by noyobo** [comment]
@xiaonini 查找编辑器通过注册表信息

排查下是否存在 `HKEY_LOCAL_MACHINE/SOFTWARE/Microsoft/Windows/CurrentVersion/Uninstall/{EA457B21-F73E-494C-ACAB-524FDE069978}_is1`

例如：

![image](https://user-images.githubusercontent.com/1292082/36962364-3d4e2a7e-208a-11e8-8aa9-512b1c0a3b54.png)

**Comment by xiaonini** [comment]
有的
![tim 20180305161015](https://user-images.githubusercontent.com/22790394/36963834-bbcf966c-208f-11e8-9950-288a2d74b2bb.png)

**Comment by xiaonini** [comment]
解决了，Iceworks关闭重新启动就可以了

**Comment by kill33** [comment]
VS code 版本：
版本: 1.26.0
提交: 4e9361845dc28659923a300945f84731393e210d
日期: 2018-08-13T16:29:31.933Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
架构: x64
