### ISSUE TITLE
在ts下,开启Table的选择模式rowSelection

### ISSUE THREAD

**Issue by zjb19970804** [alibaba/ice#1853]
## 问题描述
启用了table的选择模式后，
官方的ts类型文件中rowSelection内的几个回调方法都是必选的？
d.ts中如下：
  rowSelection?: {
    getProps: () => void;
    onChange: () => void;
    onSelect: () => void;
    onSelectAll: () => void;
    selectedRowKeys: Array<any>;
    mode: string;
  };

现在我只想使用onChange的回调，但是类型检查会报错，必须要全部写上
我现在的：
        const rowSelection = {
            getProps: () => undefined,
            onChange: this.onRowChange.bind(this),
            onSelect: () => undefined,
            onSelectAll: () => undefined,
            selectedRowKeys: selectedRowKeys,
            mode: 'multiple'
        } 
        <Table 
            dataSource={dataSource}
            primaryKey={'Id'}
            rowSelection={rowSelection}
        >
请问该如何解决呢？

## 错误信息

Property 'getProps' is missing in type '{ onChange: any; onSelect: () => undefined; onSelectAll: () => undefined; selectedRowKeys: number[]; mode: string; }' but required in type '{ getProps: () => void; onChange: () => void; onSelect: () => void; onSelectAll: () => void; selectedRowKeys: any[]; mode: string; }'.ts(2741)

**Comment by youluna** [comment]
@zjb19970804 可以先通过@ts-ignore忽略此处报错，今年内会对next代码进行ts重构，修复各种ts问题

**Comment by imsobear** [comment]
issue 我先关闭了，未来用 ts 重构完成后会通知社区。
