### ISSUE TITLE
ice build 样式文件中的图片资源路径不对

### ISSUE THREAD

**Issue by HiCooper** [alibaba/ice#1856]
- 工具问题：ice-scripts 版本：1.10.0 ,
环境： node v8.15.0
操作系统：win10

## 问题描述
执行打包命令：ice build ，会将图片统一打包到  build/assets/下（包括样式文件里面引用的图片资源），然而对于样式文件中有用到图片的资源实际引用的地址是  /css/assets/xxx.jpg；

**Comment by ClarkXia** [comment]
对于样式文件中的图片资源，构建的逻辑会是publicPath（默认情况"/"）+ assets目录进行引用，方便的话提供下文件目录和对应package.json/.webpackrc.js(如果有)的信息

**Comment by HiCooper** [comment]
这是 `package.json` (默认没改)
![image](https://user-images.githubusercontent.com/22850207/56651735-50621200-66bc-11e9-976c-8aeaae957501.png)
没有` .webpackrc.js`
这是生成的样子：
![image](https://user-images.githubusercontent.com/22850207/56651784-67086900-66bc-11e9-8366-a349c42584b9.png)

其中一个样式文件中用到图片，实际引用的路径应该是（手动copy得到）
![image](https://user-images.githubusercontent.com/22850207/56651917-ac2c9b00-66bc-11e9-8fd7-0c730e1315b1.png)

这是引用细节：
![image](https://user-images.githubusercontent.com/22850207/56651978-d2ead180-66bc-11e9-8795-7e509c50e2d1.png)

谢谢解答

**Comment by ClarkXia** [comment]
ice-scripts@1.10.1版本已处理相对路径问题
