### ISSUE TITLE
notification组件关闭图标显示异常

### ISSUE THREAD

**Issue by HiCooper** [alibaba/ice#1860]
## 问题描述

问题类型：组件问题
组件名称：notification

官方示例：
![image](https://user-images.githubusercontent.com/22850207/56705011-dc6a4d00-6741-11e9-8e1d-22429a80c4aa.png)

实际使用：
![image](https://user-images.githubusercontent.com/22850207/56705042-f9068500-6741-11e9-813d-028a56f9b291.png)

## 错误信息
关闭按钮显示异常，可能是缺少字体？

**Comment by imsobear** [comment]
@HiCooper 看下控制台，是否有资源加载失败的情况

**Comment by HiCooper** [comment]
@imsobear 没有哦

**Comment by imsobear** [comment]
不太科学，可以试下这个配置：https://ice.work/docs/basis/ice-scripts#css%20%E4%B8%AD%E7%9A%84%E7%BD%91%E7%BB%9C%E8%B5%84%E6%BA%90%E6%9C%AC%E5%9C%B0%E5%8C%96 @HiCooper

**Comment by HiCooper** [comment]
试过，没效果 -.-

**Comment by imsobear** [comment]
![image](https://user-images.githubusercontent.com/2505411/56784095-85d44000-6821-11e9-929b-ca04a98e1259.png)

加钉钉群聊吧
