### ISSUE TITLE
idev add block中publish默认源的问题

### ISSUE THREAD

**Issue by shaojun427** [alibaba/ice#1866]
现在block init的时候package里面会设置默认的源为cnpm，这个和本地设置的源冲突，我觉得使用者每个人本地配置的源都是不一样，建议init的默认配置不要加源设置，每个人就用自己本地的也没关系，如果需要特定源，让使用者自己设置。要不然用户在用idev功能的时候，不知道的人肯定会踩到这个坑，因为不能保证使用者本地配置肯定会和设置的默认源相同。

**Comment by DoranYun** [comment]
https://github.com/alibaba/ice/blob/master/packages/ice-npm-utils/lib/index.js#L92-L103

**Comment by DoranYun** [comment]
@shaojun427  已有物料仓库可以先把 .template/block/_package.json 中的 registry 字段删掉，以后 idev add block 时候就不会在新创建的物料中添加 registry 了。

下个版本我们会将模版中的 registry 字段删除掉，用户发布时候按需设置。

**Comment by DoranYun** [comment]
ice-devtools@2.3.1 已修复此问题
