### ISSUE TITLE
新增页面或者区块时，package.json里面的配置错乱

### ISSUE THREAD

**Issue by LoLDragon** [alibaba/ice#1867]
"dependencies": {
    "0": "prop-types@^15.5.8",
    "1": "@alifd/ice-container@^0.1.0",
    "@alifd/next": "^1.10.1",
    "react": "^16.4.1",
    "react-dom": "^16.4.1",
    "react-router-dom": "^4.2.2"
  }

如上：新增页面 和区块后，dependencies中的 出现     "0": "prop-types@^15.5.8",
    "1": "@alifd/ice-container@^0.1.0",这种导致安装不成功；

**Comment by imsobear** [comment]
@LoLDragon 系统、版本、重现路径描述下，我刚才试了下是没有问题的

**Comment by chenbin92** [comment]
@LoLDragon  我这边试了下没能重现，确认一下是否必现，如果是选择的那个模板，然后怎么操作的描述一下可重现打开该 issue

**Comment by LoLDragon** [comment]
@imsobear @chenbin92 不是必现的，偶现的；系统：win10 Iceworks版本：2.19.0，就是简单的在已有页面添加区块、或者新建页面的时候添加区块就出现了；
