### ISSUE TITLE
ice-design-pro 模板识别mobile错误以及Aside菜单的问题

### ISSUE THREAD

**Issue by zhaofeng-shu33** [alibaba/ice#1869]
## 错误信息

1. 打开chrome console 后发现自动识别 mobile = True；
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/23316477/56821444-e9da2100-6880-11e9-990b-c0858a4f7cb9.png">
2. mobile 状态下点击下拉菜单 openDrawer =False 导致菜单自动隐藏，不清楚这个是bug还是设计成这样；
<img width="206" alt="image" src="https://user-images.githubusercontent.com/23316477/56821564-40475f80-6881-11e9-8d03-e1626434d8b9.png">

**Comment by temper357** [comment]
1. isMobile判断是现有响应式判断逻辑，窗口宽度小于1200px统一识别为mobile
2. 点击自动隐藏是设计缺陷

侧边栏后续计划用Fushion shell组件重构，响应式与自动隐藏的交互都遵循shell的规范，关联issue https://github.com/alibaba/ice/issues/2378
