### ISSUE TITLE
ice frame 怎么配置，可以自定义打包文件到指定的目录,谢谢！

### ISSUE THREAD

**Issue by ovarte** [alibaba/ice#1872]
## 问题描述
ice frame 怎么配置，可以自定义打包文件到指定的目录,谢谢！

**Comment by ovarte** [comment]
index.html和assets文件分别放在不同的文件夹

**Comment by imsobear** [comment]
因为 html 里引用 assets 资源，牵涉到路径问题，因此静态文件都是放在 build 目录下，支持把 build 改为其他目录

https://ice.work/docs/basis/ice-scripts#%E4%BF%AE%E6%94%B9%E6%9E%84%E5%BB%BA%E5%90%8E%E7%9A%84%E6%96%87%E4%BB%B6%E7%9B%AE%E5%BD%95
