### ISSUE TITLE
[Windows] Iceworks无法启动

### ISSUE THREAD

**Issue by wujunbiao1002** [alibaba/ice#1874]
Iceworks无法启动，
新安装的Windows 7 旗舰版 Service Pack 1，安装最新版2.19.1，双击没有任何反应，
试过安装旧版本，关闭杀毒软件、兼容性启动都无法解决。

**Comment by wujunbiao1002** [comment]
> Iceworks无法启动，
> 新安装的Windows 7 旗舰版 Service Pack 1，安装最新版2.19.1，双击没有任何反应，
> 试过安装旧版本，关闭杀毒软件、兼容性启动都无法解决。

**Comment by alvinhui** [comment]
今天尝试在一台 win10 电脑上安装 iceworks@2.19.1 时，报安全警告，禁止执行。

**Comment by alvinhui** [comment]
2.20.0 版本将解决该问题，请在 5.13 后更新到 2.20.0 版本。

**Comment by wujunbiao1002** [comment]
升级到2.20.1版本已经可以正常打开了！非常感谢。
