### ISSUE TITLE
1.0的表格组件可拖动的情况下拖动的标识不会随着被拖动表格移动

### ISSUE THREAD

**Issue by cpa0701** [alibaba/ice#1875]
1.0的表格组件可拖动的情况下拖动的标识不会随着被拖动表格移动
![image](https://user-images.githubusercontent.com/24648209/57081857-24800580-6d28-11e9-9e73-ee4540c18997.png)
麻烦看下这个问题，谢谢

**Comment by youluna** [comment]
没看懂问题，暴露出来的onResizeChange事件会告诉用户当前行移动的真实位移，再通过计算width实时改变列的宽度。demo里书包拖动和列位移不是1:1是因为只有第一行的width改变了
