### ISSUE TITLE
物料重复利用，不想引进冗余的物料

### ISSUE THREAD

**Issue by ReAlign** [alibaba/ice#1884]
## 物料重复利用，不想引进冗余的物料

![image/normal/2019-05-05/img-1557060598675-7705.png](https://public-bucket-realign.nos-eastchina1.126.net/image/normal/2019-05-05/img-1557060598675-7705.png)

**Comment by imsobear** [comment]
通用组件放到 src/components 下即可；两个 Demo 目录不需要的话可以删除掉。https://github.com/ice-lab/vue-materials/tree/master/scaffolds/d2-admin-ice/src/pages 模板代码在这里，欢迎 PR 优化。

**Comment by ReAlign** [comment]
@imsobear 

> 通用组件放到 src/components 下即可

上面这个是需要手动去做吗？
