### ISSUE TITLE
Iceworks vue项目无法添加自定义物料源区块

### ISSUE THREAD

**Issue by menghuan758** [alibaba/ice#1885]
vue项目生成后，点击新建页面无法看到自定义物料源，只能看到vue官方物料源。
官方回应暂不支持。

**Comment by imsobear** [comment]
@menghuan758 理论上是支持的，可以截图看下具体什么情况

**Comment by alvinhui** [comment]
用 Vue 模板创建的项目，然后添加一个自定义的 Vue 物料源，在页面里添加区块时没法使用自定义的 Vue 物料源

**Comment by menghuan758** [comment]
@imsobear 请问ice-devtools向fusion推送自定义物料的时候有办法推"type":"vue"的吗，我推完之后接口返回还是react的，我是用idev init的vue项目

**Comment by imsobear** [comment]
@menghuan758 fusion.design 只支持托管 React 的物料源，Vue 的需要托管在 unpkg 上，这块文档有描述 https://ice.work/docs/advanced/custom-materials#%E7%89%A9%E6%96%99%E6%95%B0%E6%8D%AE%E6%89%98%E7%AE%A1

**Comment by menghuan758** [comment]
@imsobear 不好意思专注fusion去了，没注意到这个unpkg。请问推到unpkg的话，生成materials.json文件后是需要在里面手动增加一行"type":"vue"吗？还是有什么办法在materials.json自动生成这个"type":"vue"，我试了在package.json里加入type，generate之后没有

**Comment by imsobear** [comment]
@menghuan758 type 这个是以前的一个设计，现在应该没什么作用。如果你有用到的话，可以在根目录的 package.json 里指定 materialConfig，这个对象的字段都会附加到 json 数据里。

![image](https://user-images.githubusercontent.com/2505411/57267528-07925c00-70b3-11e9-9bf9-4a311cea28fc.png)

**Comment by menghuan758** [comment]
@imsobear 好的，多谢。在我看来这个type在iceworks里使用物料的时候会被用到，type为vue的话添加页面的时候物料源才会被显示出来。
