### ISSUE TITLE
iceworks 客户端环境不一致问题

### ISSUE THREAD

**Issue by alvinhui** [alibaba/ice#1891]
## 问题描述

将源设置为 tnpm：

![image](https://user-images.githubusercontent.com/4392234/57232499-53131e80-704f-11e9-99e9-a9965a07d32a.png)

在客户端中无法使用 tnpm：

![image](https://user-images.githubusercontent.com/4392234/57232534-6920df00-704f-11e9-9cff-9b3dec97534e.png)

同时客户端的环境变量与 bash 不一致将会导致某些命令执行失败。

## 背景

目前在 iceworks 里执行命令有两处：

- [主进程内](https://github.com/alibaba/ice/blob/iceworks/2.19.1/tools/iceworks/app/main/services/sessions/Session.js#L41)；
- [渲染进程内](https://github.com/alibaba/ice/blob/iceworks/2.19.1/tools/iceworks/renderer/src/terms/index.js#L83)。

**Comment by imsobear** [comment]
![image](https://user-images.githubusercontent.com/2505411/57354563-5d8ffe00-719e-11e9-963a-37ef38451f3d.png)

**Comment by alvinhui** [comment]
今天有用户在 window 系统下，点击「重装依赖」后报如下错误：

![image](https://user-images.githubusercontent.com/4392234/57359503-6a1a5380-71aa-11e9-9b42-f9a87ed2c7d9.png)
![image](https://user-images.githubusercontent.com/4392234/57359547-81594100-71aa-11e9-9b53-a0ae9f709c70.png)

用户切换到命令行后，执行 `npm install` 能够安装成功。

**Comment by chenbin92** [comment]
[iceworks 3.0](https://ice.work/iceworks) 已发布，2.x 版本不在继续维护
