### ISSUE TITLE
create a website for custom materials showcase

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#1899]
## Background

Developers can use ice-devtools to create materials like block, component blocks, and scaffolds. These materials belong to their own team. At the same time, these materials can be used quickly in iceworks, but we lack a website to help developers display these materials. Through this website we can see all the materials, as well as the documentation for each material.

## Proposal

- Create a icematerials website
- Use Node.js(backend) and ICE(front)
- Support registered materials, show materials

**Comment by TG1999** [comment]
Hi @imsobear I will like to work on this project in this summer under Alibaba summer of code. Please can you tell me how can I show my pro efficiency for this project. I am currently doing my intern as a backend(Node.js).

**Comment by tanhengyeow** [comment]
Hi @imsobear 

I'm an avid open source contributor and my expertise lies in front-end engineering. I've also worked with Design Systems before. Looking forward to contributing for this project 😄

**Comment by imsobear** [comment]
We recommend building the page through materials. Each custom material is made up of scaffolds, blocks and components. Developer can use ice-devtools to build their own material. Single scffold/block/component need publish to npm or their private npm registry. For each custom material we can use `generate` cmd to create a json file. In this file, you can find all scaffold/block/component meta data.

And then we publish this json file to some one service:

- fusion.design: only support react materials
- npm: through unpkg read this json file

And then we can use this json file url in iceworks. See and use all scaffolds/blocks/components. If you want see others material, you need use iceworks and add the material json url. So I think we should create a website to do these things. And about this website We just have some general ideas at the moment. Maybe we can design and develop it together.

**Comment by lazycipher** [comment]
Hii @imsobear,
Please elaborate bit more about this project with some example if possible?
Thank You

**Comment by imsobear** [comment]
We are still in the discussion, next Tuesday confirm. @lazycipher

**Comment by DoranYun** [comment]
The material display website is a platform for collecting and displaying various materials of ICE. Developers can submit their own material in the  website for other developers to use.

## What do you need to do ?

The material display website needs to have the following functions:

- User System (based on GitHub OAuth)
- Submit material data (material meta data URL) 
- Materials list 
- Material details
- Component / Block / Bracket Preview
- Collect materials
- Regularly update material data 
- Manually update material data
- Backend based on NodeJS
- Frontend based on React + ICE

## skills you need have

- NodeJS
- React + ICE
- DevOps

----

物料展示平台是一个收集、展示 ICE 各种物料的平台，开发者可以在平台中提交自己的物料，以便其他开发者使用。

## 需要做什么

物料展示平台需要有以下功能：

- 用户系统（基于 GitHub OAuth）
- 提交物料数据（物料源数据 url）
- 物料列表
- 物料详情
- component/block/scaffolds 预览
- 收藏物料
- 定时更新物料数据
- 手动更新物料数据
- 后端基于 NodeJS
- 前端基于 React + ICE

## 你需要的能力

- NodeJS
- React + ICE
- devOps

**Comment by imsobear** [comment]
@TG1999 @tanhengyeow @lazycipher You can complete your proposal refer to the above reply.
