### ISSUE TITLE
optimize the user experience of ice-scripts

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#1900]
- improve webpack build speed：提升 webpack 的构建速度
- optimize stdout：优化构建日志输出
- add env check: node version, node-sass aviliable...：完善依赖环境的检测，比如 Nodejs 版本、依赖是否安装等

**Comment by UZIhuhuhu** [comment]
我对这个 issue 有点疑惑，如果可以答疑的话希望可以解答下。

在第一点中：这边的 config 是指注入的 webpackrc.js 中的 config 还是指 buildConfig
在第三点中：optimize stdout 是指优化 build 后的文件吗

**Comment by imsobear** [comment]
@UZIhuhuhu issue 完善了下，可以再看下

**Comment by UZIhuhuhu** [comment]
这个 issue 是对哪个分支上的代码进行研究？
是 `master` 还是 `ice-scripts/release-2.0.0` 分支

**Comment by imsobear** [comment]
ice-scripts/release-2.0.0 这个版本今天发布，发布后会合并到 master

**Comment by imsobear** [comment]
已发布，代码在 master 分支，文档：https://ice.work/docs/cli/about
