### ISSUE TITLE
2019 Alibaba Summer of Code

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#1901]
Welcome to the open source world!If you haven't planned how to spend this summer, come to the Alibaba Summer of Code and coding with us! 💻

Alibaba Summer of Code is a global program focused on engaging students directly into open source software development. Under the guidance of the mentor in the Alibaba open source project, students experience the software development in the real world.Alibaba Summer of code will begin between June 28th and September 20th. Students can use the summer time to participate in the open source project and work with the core members of the project.

## What you can get?

On this exclusive developer journey, students will have the opportunity to:

- Participate in the top projects of the International Open Source Foundation;
- Get a scholarship from Alibaba;
- Obtain an open source contributor certificate;
- Get a fast pass of Alibaba Internship/recruitment;
- Get your code adopted and used by the open source project！

## Our Mentor

Xiong Liu

GitHub ID：imsobear

ICE Project Manager, Alibaba front-end technical expert.

## Apply Now! 

You can click on this link to apply directly:

- optimize the user experience of ice-scripts #1900 
- create a website for custom materials showcase #1899
- support for english and other languages #921 
- automatically build and publish Iceworks #1920 
- implement vue-cli adapter for iceworks #1784 

full list of Alibaba Summer of Code Projects：

- 中文：https://developer.aliyun.com/summerofcode2019
- English: https://developer.aliyun.com/special/summerofcode2019en

## Timeline⏳

Reference https://developer.aliyun.com/special/summerofcode2019en

## Contact us!

- Gitter: https://gitter.im/alibaba/ice
- GitHub issue
- Email Address: aliopensource@alibabacloud.com

**Comment by sk9331657** [comment]
@imsobear Hi , I am interested in the project . Can you guide me how to start contributing in project ??

**Comment by sk9331657** [comment]
@imsobear  Is there any contact channel like gitter for project??

**Comment by imsobear** [comment]
@sk9331657 We use issue to communicate for the moment. And maybe you can describe your problem in detail.

**Comment by sk9331657** [comment]
@imsobear Do we need to contribute before submitting proposal in form of pr's or selection will be purely made on basis of proposal quality and past contributions?? Also what will be the expected intern's salary.

**Comment by luhc98** [comment]
Shall I provide my student identification?

**Comment by imsobear** [comment]
Don't quite understand your question. Maybe we can communicate in the gitter https://gitter.im/alibaba/ice

**Comment by luhc98** [comment]
@imsobear  Thanks for replying.

**Comment by maze-runnar** [comment]
@imsobear would ASoC would take place in 2020?

**Comment by Pihu1998** [comment]
> @imsobear would ASoC would take place in 2020?

+1

**Comment by a4aditya** [comment]
> @imsobear would ASoC take place in 2020?

+1
