### ISSUE TITLE
设置moment.locale('zh-cn')后, DatePicker仍然显示英文日期 

### ISSUE THREAD

**Issue by GPWiOS** [alibaba/ice#1902]
## 问题描述
使用的moment、alifd/next版本
    "@alifd/ice-container": "^0.1.0",
    "@alifd/ice-foundation-symbol": "^0.1.0",
    "@alifd/ice-layout": "^0.1.0",
    "@alifd/next": "^1.13.13",
    "moment": "^2.24.0",

[
![image](https://user-images.githubusercontent.com/15536539/57383042-ab2d5a80-71e0-11e9-9856-33b07465e0d2.png)
](url)

**Comment by cpa0701** [comment]
我也是，感觉是不是升级了ice-scripts导致的？现在的ice-scripts是1.10.1

**Comment by imsobear** [comment]
按照 @cpa0701 回复的文档操作即可，

**Comment by SunshineH2** [comment]
设置了<ConfigProvider locale={zhCN}></ConfigProvider>之后没起作用，弹层下还是英文呢
