### ISSUE TITLE
公司研发云不能上网，无法使用Iceworks，关于申请使用Iceworks网络权限的相关问题

### ISSUE THREAD

**Issue by LoLDragon** [alibaba/ice#1913]
问题描述：公司打算推广使用飞冰工具，但是在研发云内不能上网，只能申请对应的网络权限，目的是可以查看Iceworks上所有的模板并下载进行开发，目前的现状是我已经申请了一下域名的网络权限。可以查看Iceworks上模板、区块，但是下载的时候会出问题；里面好像涉及到**socket连接**，但是控制台只反应了连接**超时的ip**,而且这些ip是不固定的。每次重新打开这个工具，选择模板的时候。socket连接的ip都发生更改，类似于cdn的地址？？？

下面是我抓包的时候统计需要申请的网络域名以及控制台提示的那些会变的ip地址：；
![image](https://user-images.githubusercontent.com/19163371/57509477-e8a3fc00-7336-11e9-9a45-dfb08313ad35.png)

以下为模板下载过程中的错误的提示：
![image](https://user-images.githubusercontent.com/19163371/57507703-1c305780-7332-11e9-910d-8f2f546fafcc.png)

![image](https://user-images.githubusercontent.com/19163371/57508336-cf4d8080-7333-11e9-9f7e-6d83d4784f84.png)

![image](https://user-images.githubusercontent.com/19163371/57508353-dffdf680-7333-11e9-99cb-fa2994540544.png)

![image](https://user-images.githubusercontent.com/19163371/57508366-ea1ff500-7333-11e9-8a68-e285f5224448.png)

3.上面描述的问题，有以下问题想找各位大佬帮忙解答以下：

  3.1  上面的网络权限域名是否申请齐全了，在打开模板时，里面提示的socket连接ip变化。有没有具体的域名啊？这里面的具体是一个怎样的过程？为什么会有socket的连接；

  3.2 在设置里面，我设置了公司自定义的npm源，这个设置npm源是否就是指从模板下载后，安装的依赖会从自定义的npm源中下载？但是在下载模板的过程中，还是会从淘宝源下载。或者npmjs源。这个下载模板的过程中，应该Iceworks工具应该设置默认从淘宝源下载吧，没法更改吧！

  3.3Iceworks这个工具是否本身集成了node,npm？在点击下载模板的时候，为什么有时候我在vscode 打开使用相同的npm install安装依赖可以成功。但是在客户端上 就会提示错误呢？

**Comment by LoLDragon** [comment]
@imsobear @chenbin92 两位大佬，不好意思打扰。可否帮我解答一二，有没有开发Iceworks客服端的了解一下这个流程；在此先谢谢了

**Comment by chenbin92** [comment]
> 3.1 上面的网络权限域名是否申请齐全了，在打开模板时，里面提示的socket连接ip变化。有没有具体的域名啊？这里面的具体是一个怎样的过程？为什么会有socket的连接；

> 3.2 在设置里面，我设置了公司自定义的npm源，这个设置npm源是否就是指从模板下载后，安装的依赖会从自定义的npm源中下载？但是在下载模板的过程中，还是会从淘宝源下载。或者npmjs源。这个下载模板的过程中，应该Iceworks工具应该设置默认从淘宝源下载吧，没法更改吧！

iceworks 下载物料(模板/区块/组件)的流程是根据设置面板设置的 npm 源从对应的源上进行下载，目前支持 淘宝源，npm 官方源，以及自定义源，默认是从淘宝源进行下载的。另外下载过程是通过 HTTP 方式 ，出现 socket 错误是由于网络超时引起的。

为什么要从 npm/cnpm 源上下载物料？

目前物料的设计是以 npm 包的形式进行托管在 unpkg 上，iceworks 下载物料本质上是去 unpkg 上查找对应物料的 npm 包的 tar 地址进行解压，然后下载到本地项目中。当然，也可以是自定义的 npm 源进行托管和下载。

![image](https://user-images.githubusercontent.com/3995814/57510767-28201780-733a-11e9-82ed-0eeb26277e80.png)

> 3.3 Iceworks这个工具是否本身集成了node,npm？在点击下载模板的时候，为什么有时候我在vscode 打开使用相同的npm install安装依赖可以成功。但是在客户端上 就会提示错误呢？

iceworks 内置了 node 和 npm 作为兜底逻辑，当执行 npm install 时会优先读取系统的 node/ npm 环境，如果没有检测出系统的环境，则会降级使用 iceworks 依赖的环境。出现错误的可能原因是：iceworks 未正确解析到环境变量，同时 iceworks 内使用的是 node-pty 衍生子进程，这在 Electron 的 node 环境中会有一定的差异性。在下个大版本我们会彻底抛弃掉内置环境改为使用系统环境，避免此类问题。

综上， 建议优先使用 cnpm 源进行下载，减少网络超时的错误率或者私有源

**Comment by LoLDragon** [comment]
设置了npm私有的源。
![image](https://user-images.githubusercontent.com/19163371/57512615-b4343e00-733e-11e9-8754-02a26e6486d1.png)
创建项目下载的地址还是从淘宝源下载的；
![image](https://user-images.githubusercontent.com/19163371/57512547-851dcc80-733e-11e9-894e-42ba3c505c1c.png)

**Comment by chenbin92** [comment]
@LoLDragon  下载物料部分是根据 [物料协议](https://www.yuque.com/ice-team/wiki/ay2251) 的 source 字段定义的，看起来两者有冲突，目前下载的 ICE 官方物料都是走 cnpm 源。安装依赖是通过设置的 npm 源，物料下载是通过物料协议的 source 字段指定。

![image](https://user-images.githubusercontent.com/3995814/57513012-c6fb4280-733f-11e9-86ee-caa331a0eb64.png)


![image](https://user-images.githubusercontent.com/3995814/57512961-aa5f0a80-733f-11e9-97e3-27e61ced908b.png)

**Comment by LoLDragon** [comment]
总结：
1.本次Iceworks需要申请的网络域名地址如下：
```
    PS:以下网络请求均为https请求，443端口

    10.75.206.1 img.alicdn.com
    10.75.206.1 retcode.alicdn.com
    10.75.206.1 unpkg.com
    10.75.206.1 at.alicdn.com
    10.75.206.1 i.alicdn.com
    10.75.206.1 gw.alipayobjects.com
    10.75.206.1 arms-retcode.aliyuncs.com
    10.75.206.1 user-images.githubusercontent.com
    10.75.206.1 ice.alicdn.com
    10.75.206.1 iceworks.oss-cn-hangzhou.aliyuncs.com
    10.75.206.1 alifd.alibabausercontent.com
    10.75.206.1 fusion.design
    10.75.206.1 ice.alicdn.com
    10.75.206.1 alifd.alicdn.com
    10.75.206.1 cdn.npm.taobao.org
    10.75.206.1 registry.npm.taobao.org
    10.75.206.1 registry.npmjs.org
```
2.网络权限的申请，采用的是搭建了代理服务器，采用的`goproxy`代理.详情github上搜索goproxy有详细资料。
