### ISSUE TITLE
Automatically build and publish iceworks

### ISSUE THREAD

**Issue by alvinhui** [alibaba/ice#1920]
Now Iceworks build and push on development machine(macOS && Windows, to know more information please check [Iceworks README.md](https://github.com/alibaba/ice/tree/iceworks/release-2.20.0/tools/iceworks#%E6%89%93%E5%8C%85%E5%8F%91%E5%B8%83) ). This wastes machine resources and not enough automation. We suggest doing this in a more automated way, such as CI server.

We recommend the following effects:

- Push a Git tag, rule: iceworks/x.x.x;
- Run CI task to build and push Iceworks for macOS and Windows version.

Other solutions are welcome to achieve this automation process.

**Comment by alvinhui** [comment]
@imsobear I suggest adding this feature to [2019 Alibaba Summer of Code](https://github.com/alibaba/ice/issues/1901).

**Comment by chenbin92** [comment]
Just need to publish the npm package in iceworks 3.0, similar to dynamic updates.

iceworks 3.0

iceworks-server：

[/client.ts#L11](https://github.com/alibaba/ice/blob/iceworks%2Frelease-3.x/packages/iceworks-server/src/app/middleware/client.ts#L11)

```
ctx.clientConfig = {
      // TODO: 区分环境和端口检测
      // 默认使用 iceworks-client@latest 最新的版本
      clientPath: '//unpkg.com/iceworks-client@latest/build/',
      socketUrl: '//127.0.0.1:7001/',
      apiUrl: '//127.0.0.1:7001/api/',
    };
```

I don't think this is necessary.   @alvinhui

**Comment by alvinhui** [comment]
@chenbin92 
iceworks-app still need to load iceworks-server, if you do updated on iceworks-server, you still need to update iceworks-app, it is the same way for iceworks-cli.

Publishing process:

- iceworks-client
- iceworks-server
- iceworks-cli && iceworks-app

Actually, require an automated process for build and push should be more important in 3.x.

**Comment by zhaofeng-shu33** [comment]
I think this is a challenging but interesting work.

**Comment by zhaofeng-shu33** [comment]
Two problems exits currently:
1. Using Continuous deployment overseas to upload the zip files to aliyun oss is very slow. Timeout error is triggered.
2. The bundled app cannot run. Error message says `address module not found`.
