### ISSUE TITLE
打开ice works客户端,proxy的api请求会提示  no-referrer-when-downgrad

### ISSUE THREAD

**Issue by birdycn** [alibaba/ice#1924]
打开ice works客户端,proxy的api请求会提示  no-referrer-when-downgrad

关闭ICE，proxy请求可以正常获取数据

**Comment by imsobear** [comment]
- 使用 npm start 启动项目
- 访问页面一切正常
- 启动 iceworks 应用
- 刷新页面报错

**Comment by birdycn** [comment]
更尴尬的事。。我手写html访问ajax没使用proxy提示no-referrer-when-downgrade，于是我修改了服务端允许同源策略，已经可以正常获取了。

但是刚刚想打开ICE参考下模板的时候，又出现了no-referrer-when-downgrade，也就是说，即使服务端允许了跨域请求，但是只要打开ice还是出错，而且还是普通的html5页面，手写的，没用什么配置

> * 使用npm start启动项目
> * 访问页面一切正常
> * 启动冰淇淋应用
> * 刷新页面报错
