### ISSUE TITLE
企业私有化场景使用物料开发流程

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#1928]
## 背景

- 很多企业的 npm 包不能对外，需要发布到私有 npm 源上
- 飞冰的物料开发链路对 npm 是强依赖

## 方案

梳理飞冰对 npm 的依赖：

- ice-devtools:
  - 物料发布即 npm 包发布：按照标准自定义 package.json 里的 registry 字段即可
  - 生成物料数据时查询 npm 包信息：通过 REGISTRY 环境变量自定义
- iceworks:
  - 下载 tar 包（下载区块、根据模板初始化项目）：使用用户配置的 npm 源
    - 当前方案：**官方物料下载走 taobao 源，其他物料走物料 json 里生成的 registry（一般是 npm 官方 registry），计划修正为「官方物料下载走 taobao 源，其他物料走用户配置」**
  - 重装依赖功能：使用用户配置的 npm 源
- ice-scripts: 弱依赖
  - 根据模板初始化：通过 REGISTRY 环境变量自定义

根据上述依赖关系产出方案，企业需要搭建自己的私有 npm 服务并且符合以下规范：

1. 访问 ${registry}/${packageName} 返回正确格式的包信息，示例 http://registry.npmjs.com/react
2. 访问 ${registry}/${npm}/-/${npm}-${version}.tgz 可以下载 tar 包，示例 http://registry.npmjs.com/react/-/react-16.5.0.tgz
3. 通过上述接口可以查询到共有 npm 的信息，比如 ${registry}/react

## Actions

- 产出对应文档
- 补充私有 npm 服务的搭建文档，参考：https://zhuanlan.zhihu.com/p/35773211

## 结论

- 自定义物料的流转流程图：TODO
- 私有的需求核心是：每个物料的 npm 包需要私有化，发布到私有的 npm 源上。
- generate 生成的物料 json 数据：只包含描述信息，不包含实际代码，直接发布公共 npm 然后通过 unpkg 访问使用即可，如 https://unpkg.com/zl-materials@1.0.8/build/materials.json
- 私有物料需求的依赖：
  - 自建私有 npm 源：执行 `generate` 命令时需要传入环境变量 `REGISTRY=http://registry.xxx.com`；iceworks 中需要在设置里将 npm 源更改
  - 自建 unpkg 服务：目前每个物料的截图和预览依赖了 unpkg 能力，比如[截图地址](https://unpkg.com/@icedesign/user-landing-block@2.0.0/screenshot.png)、
[预览地址](https://unpkg.com/@icedesign/user-landing-block/build/index.html)，因此需要有自建 unpkg 来支持
- 关于截图和预览地址字段的生成：
  - 每个物料的 package.json prepublishOnly 字段会执行 `idev screenshot`，执行该命令后会在当前物料的 package.json 里补全两个字段 homepage 以及 config.screenshot，补全规则是 ·https://unpkg.com/${pkgName}@${version}/screenshot.png`，如果是私有的 unpkg，那么在执行单个物料的 npm 包时需要传入环境变量 UNPKG（每个物料 publish 都要添加不太合理，可以先加到 .template 里，后续看下怎么优化）
  - 在执行 `generate` 时会遍历每个物料的 package.json 然后取到需要的字段比如 screenshot 然后放到最终的 `materials.json` 里，iceworks 会根据该字段渲染物料的截图和预览地址等信息

**Comment by LoLDragon** [comment]
1.目前npm私有库已实现了上面所提的接口规范。同时npm run generate和npm run sync可以成功同步物料。但是Iceworks的界面显示的仍旧为上传到npm.js公共源的版本。查看ice-devtools sync的代码 应该是不支持该功能的。
@imsobear 不知道可否出一版根据用户自定义配置显示从私有npm库加载包信息和下载如您上面所说。

**Comment by imsobear** [comment]
https://ice.work/docs/materials/reference/env

**Comment by imsobear** [comment]
https://ice.work/docs/materials/reference/private
