### ISSUE TITLE
ice-scripts 2.0 方案

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#1929]
## 背景

ice-scripts 为 React 链路的工程工具，提供一套丰富的功能帮助开发者进行 React 项目的开发，但随着内部以及外部的一些业务定制和高级需求，越来越多的功能不断往上叠加，目前的架构体系已经无法应对日益增长的需求。因此将通过2.0的迭代提高工程工具的易用性和可拓展性。

## 核心目标

- 配置优化&统一
- 插件机制：提供拓展和自定义能力

## 配置方案

统一为 ice.config.js:

```javascript
// ice.config.js
const icePluginMonaco = require('ice-plugin-monaco');

module.exports = {
   entry: "",
   externals: {}, 
   outputDir: '',
   outputAssetsPath: {js, css},
   publicPath: '',
   devPublicPath: '',
   alias: {},
   define: {},
   hash: true,
   vendor: {}, 
   devServer: {},
   targets: {},  // babel targets
   injectBabel: '', 
   minify: true, // 是否压缩，原先的 debug
   // ice 插件
   plugins: [
     'ice-plugin-fusion',
     './plugins/custom-plugin',
     ['ice-plugin-fusion', {
       themePackages: []
     }],
     icePluginMonaco,
   ],
   // 自定义配置
   chainWebpack: (webpackChain) => {
      // 自定义 webpack 配置
   }
}
```

## 插件机制

借助插件化思路提供更加灵活的功能，如代码注入、复杂配置抽象等，各类定制方案均通过插件扩展。

### 插件定义

TODO

### 插件使用

参考上面的 `ice.config.js`

### 插件开发

```javascript
modules.exports = (api, opts) => {
  // 通过plugin api方法定制需求
	api.chainWebpackConfig((config) => {
  	config.output.publicPath('./');
  })
}
```

#### ice-plugin-fusion

支持 Fusion 主题；Fusion 组件按需加载；uniteBaseComponent 能力

#### ice-plugin-component

业务组件开发，支持标准的 React 组件、Fusion 业务组件甚至 Antd 业务组件

#### ice-plugin-wrap-entry

注入代码：自动加载 React、smartloader 能力

#### 其他插件

- ice-plugin-multi-entry：支持多页入口
- ice-plugin-block: 区块开发
- ice-plugin-typescript（内置实现）
- ice-plugin-css-source-local
- ice-plugin-import-config （babel import config）
- ice-plugin-pwa
- ice-plugin-antd: antd 组件按需加载；主题变量定制
- ice-plugin-router: 根据 pages 自动生成 router
- html 注入

## 时间点

- 5月底发布

**Comment by topwood** [comment]
mark

**Comment by imsobear** [comment]
关于 ice-scripts 里的 init/add block 等命令设计，感觉不是特别妥当，尤其是根社区同类产品对比，因此倾向于拆分为以下纬度：

- 全局 cli 工具
- 支持 React 项目的开发构建测试工具
- 支持自定义物料的数据生成、发布、截图工具

## create-ice or ice-cli

全局安装，提供命令：

- ice init project/block/scaffold/component/material
- ice add block: 添加默认空白区块、根据 npm 包添加区块、根据 .template 添加区块

目前有两种设计：

### 1. 关于 create-xxx

create-xxx 是 yarn 提出的一种简化方法，执行 `yarn create react-app` 等同于：

- yarn global add create-react-app
- create-react-app

在 npm@5 里通过 `npx create-react-app` 可以实现类似的效果，然后在 npm@6 里将其简化成执行 `npm init react-app`。

所以这种方式本质上就是简化了用户全局安装这个过程，通过一个命令即可初始化出一个项目。但是缺点是因为 create 的前缀限定不好支持其他命令。

### 2. 关于 xxx-cli

这种就没有任何约定了，类似 vue-cli angular-cli，命令完全由开发者设计，个人更倾向于这种。

## ice-scripts

项目安装，用户只需要执行 npm run xxx，提供命令：

- ice-scripts dev
- ice-scripts build
- ice-scripts test

## ice-devtools

项目安装，用户只需要执行 npm run xxx，提供命令：

- idev generate
- idev screenshot
- idev sync
- idev sync-unpkg
- idev clear

**Comment by chenbin92** [comment]
如果是基于上面的考虑，建议使用 `ice-cli`，但是 `ice-cli` 可以包含 `ice-devtools` 的几个命令，从现在看 ice-devtools 就只做了生成数据同步的工作，没必要单独存在了。如果并存 `ice-devtools`、`ice-cli`、`ice-scripts` 透出的工具有点多了，可能会懵逼，且没有太多收益。

**Comment by imsobear** [comment]
cli 更倾向于做文件相关的初始化等命令，如果要把 idev 的所有逻辑里内置进去感觉不妥，或者对比 vue-cli 可以这样理解这个事情：

- ice-cli
  - cli-react-service: react 构建等
  - cli-material-service: 物料的生成等

@chenbin92

**Comment by imsobear** [comment]
## ice-scripts

> React 工程工具，只做构建相关的事情

### 提供命令

- ice-scripts dev
- ice-scripts build
- ice-scripts test

### 插件

命名统一为 ice-scripts-plugin-foo

## ice-cli

> ICE 统一（应该也是唯一）的 CLI 工具，iceworks 的 CLI 版本是个例外

- ice init project/component/block/scaffold/materials
  - 支持根据自定义模板（npm 包）创建
- ice add：materials 根目录，从 .template 复制添加对应的内容
- ice add block：非 materials 根目录，下载区块并添加到当前目录
- ice generate：materials 根目录
- ice sync: materials 根目录（或者单个物料，仅 fusion.design 支持）
- ice clear: materials 根目录
- ice screentshot: 打开指定 URL -> 截图 -> 将 screenshot 字段（以及 homepage？）写入 package.json
- ice add adaptor：仅在组件开发有用

**Comment by chenbin92** [comment]
> ## ice-scripts
> > React 工程工具，只做构建相关的事情
> 
> ### 提供命令
> * ice-scripts dev
> * ice-scripts build
> * ice-scripts test
> 
> ### 插件
> 命名统一为 ice-scripts-plugin-foo
> 
> ## ice-cli
> > ICE 统一（应该也是唯一）的 CLI 工具，iceworks 的 CLI 版本是个例外
> 
> * ice init project/component/block/scaffold/materials
>   
>   * 支持根据自定义模板（npm 包）创建
> * ice add：materials 根目录，从 .template 复制添加对应的内容
> * ice add block：非 materials 根目录，下载区块并添加到当前目录
> * ice generate：materials 根目录
> * ice sync: materials 根目录（或者单个物料，仅 fusion.design 支持）
> * ice clear: materials 根目录
> * ice screentshot: 打开指定 URL -> 截图 -> 将 screenshot 字段（以及 homepage？）写入 package.json
> * ice add adaptor：仅在组件开发有用

+1

1. 以前项目的 `ice dev` 会有迁移的问题，模板又要批量改一遍了😆，不过本 2.0 本来是 breakchange，问题不大
2. `ice-scripts-plugin` 这个前缀的约束是出于什么考虑

**Comment by chenbin92** [comment]
这样看起来只是把以前 ice-devtools 换了个名字叫 ice-cli，其他的貌似都一样了

**Comment by imsobear** [comment]
@chenbin92 

- 将 ice-scripts init/add block 命令移到 ice-cli 里
- 将 ice-devtools 的所有能力移到 ice-cli 里

**Comment by imsobear** [comment]
已发布，文档：https://ice.work/docs/cli/about
