### ISSUE TITLE
iceworks 3.0 Roadmap

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#1930]
## 目录
* iceworks 3.0 定位
* iceworks 3.0 功能
   * 项目管理
   * 工程管理
   * 物料市场
   * 设置
* iceworks 3.0 发布时间
* 相关链接
    * [iceworks 3.0 进度安排](https://github.com/alibaba/ice/projects/5)
    * [iceworks 3.0 产品原型](https://org.modao.cc/app/1uBjWJK7q6EgZ3fBqkR9m71LvvJJ6In)

## iceworks 3.0 定位

> 开箱即用的『项目』和 『工程』可视化前端工作台

在现有的 iceworks 版本基础上区分 **项目** 和 **工程** 两大块：在实际开发中按照八二定律，即 80% 的时间是在项目开发上，20% 的时间在工程配置上。而 iceworks 3.0 定位为前端工作台，在产品设计上需要有明确的界定和产品引导，提升用户的使用体验，减少不必要的干扰和提升开发效率。

![产品定位](https://img.alicdn.com/tfs/TB1gBBfVSzqK1RjSZFHXXb3CpXa-1668-1022.png)

## 项目管理

将现有 iceworks 的 **项目** 面板功能进行细分，去除工程相关的功能，在现有的基础上新增以下项目管理功能：

新增功能：

- [菜单管理](https://free.modao.cc/app/design/pA1DEED102F1552536981171#screen=s6E43DE947F1552975743683)：可视化展示菜单，可以点击链接打开，支持编辑菜单名和对应的图标
- [路由管理](https://free.modao.cc/app/design/pA1DEED102F1552536981171#screen=s6E43DE947F1552975743683)：可视化展示路由，可以点击链接打开，支持编辑路由名
- [Mock 管理](https://free.modao.cc/app/design/pA1DEED102F1552536981171#screen=s6E43DE947F1552975743683)：基于目前的 Mock 功能，支持可视化编辑 Mock 数据（强需求）
- [物料信息](https://free.modao.cc/app/design/pA1DEED102F1552536981171#screen=s6E43DE947F1552975743683)：已下载物料记录用户选择过的区块、组件和模板，基于当前项目的物料管理
- [新建页面](https://free.modao.cc/app/design/pA1DEED102F1552536981171#screen=s6E43DE947F1552975743683)：优化现有的新建页面流程

现有功能：

- 页面列表
- 布局列表
- 依赖管理
- TODO
- Git
- DEF
- OSS

基于物料市场的项目管理和开发流程

![项目管理流程](https://img.alicdn.com/tfs/TB17B4rVIfpK1RjSZFOXXa6nFXa-970-633.png)

## 工程管理

新增 **工程** 管理面板，用于管理项目的工程配置部分，目前主要基于 ice-scripts 的可配置项进行可视化，降低工程配置的复杂度，不在需要写代码，了解各种配置的接口。

![image.png](https://img.alicdn.com/tfs/TB1jLk.VwTqK1RjSZPhXXXfOFXa-1558-990.png)

同时，制定 iceworks 工程可视化配置协议，支持多工程套件的接入

![image.png](https://img.alicdn.com/tfs/TB1tyxmVMHqK1RjSZJnXXbNLpXa-1422-908.png)

工程管理主要有以下功能：

- [dev](https://free.modao.cc/app/design/pA1DEED102F1552536981171?#screen=s7D747069F41552537002154)：启动本地开发模式，提供基础设置，日志，控制台和构建分析功能
- [build](https://free.modao.cc/app/design/pA1DEED102F1552536981171?#screen=s7D747069F41552537002154)：构建生产模式，提供基础设置，日志，控制台和构建分析功能
- [lint](https://free.modao.cc/app/design/pA1DEED102F1552536981171?#screen=s7D747069F41552537002154)：提供 Eslint 检查和可视化配置项目
- [configuration](https://free.modao.cc/app/design/pA1DEED102F1552536981171?#screen=s7D747069F41552537002154)：提供 webpack 的可视化配置项

## 物料市场

将原有的 **模板**、**区块**、**组件** 面板进行收敛，同一个物料源应该包含三者，形成单个物料品牌，而不是模板、区块、组件分别对应不同的物料源形式。改进后的效果图如下：

![image.png](https://img.alicdn.com/tfs/TB1uLJIVNjaK1RjSZKzXXXVwXXa-1532-986.png)

## 设置

在现有的设置基础上，对设置进行分类：

- 通用设置
  - 国际化
  - 主题
  - 消息提示
- 面板设置
  - 现有的插件管理
- 物料设置
  - 添加物料和说明
  - 删除物料源管理
- 高级设置
  - npm 源
  - 编辑器
  - 终端

![image.png](https://img.alicdn.com/tfs/TB1rwhEVOLaK1RjSZFxXXamPFXa-1552-918.png)

### 里程碑一

**发布版本**： 
- Beta 版本

**发布时间**：
- 六月底：功能完备
- 七月初：发布上线

**发布功能：**

- 产品功能对其现有 iceworks 2.x 的功能
- 全新的视觉体验
- 项目管理功能
    - 页面列表
    - 布局列表
    - 依赖管理
    - TODO
    - Git
    - DEF
    - OSS
- 工程管理的可视化配置
   - dev
   - build
   - lint
   - configuration
- 物料面板体验优化
- 支持 CLI 方式启动本地 Web 版本

### 里程碑二

> **这个阶段可以按照新增功能周迭代**

**发布版本**：
  - 正式版本

**发布时间**：
  - 九月初：功能完备
  - 九月中：发布上线

**发布功能**：

- 项目
  - 菜单管理
  - 路由管理
  - 物料信息
  - Mock 功能
- 工程
  - dev/build
    - 仪表盘
    - 构建分析
- 设置
  - 主题
  - 语言

![image](https://user-images.githubusercontent.com/3995814/58298149-fd8b8f80-7e0c-11e9-8498-942daa45bc01.png)

## 相关链接
* [iceworks 3.0 产品原型](https://org.modao.cc/app/1uBjWJK7q6EgZ3fBqkR9m71LvvJJ6In)
* [iceworks 3.0 进度安排](https://github.com/alibaba/ice/projects/5)

**Comment by FairyEver** [comment]
关于菜单配置中图标方面的建议

* 打通 https://www.iconfont.cn，svg 图标直接在设置界面设置 iconfont 上的 svg，选择后将图标下载到本地并将名称设置到菜单
* 加载项目中自带的 svg 图标
* 同时可选使用 FontAwesome 或者其它字体图标库
* 支持读取本地的字体图标并选择（比如 iconmoon 导出的图标包）

例如用户选择的是 FontAwesome 图标中的 fa-github，将会生成类似下面的数据：

``` js
{
  title: 'foo title',
  name: 'foo-name',
  icon: {
    type: 'font-awesome',
    name: 'fa-github'
  }
}
```

用户选择的 iconfont 上的一个左箭头图标，并起名为 left

``` js
{
  title: 'foo title',
  name: 'foo-name',
  icon: {
    type: 'svg',
    name: 'left'
  }
}
```

模板中根据 icon 的 type 属性判断应该使用何种渲染方式渲染图标

参考：

[http://kitchen.alipay.com/](http://kitchen.alipay.com/)

![image](https://user-images.githubusercontent.com/19357920/57665334-04a4e780-762e-11e9-9f2a-543f7b7c7a43.png)

**Comment by topwood** [comment]
对自定义区块搭建有重新上线的打算吗

**Comment by chenbin92** [comment]
@topwood  自定义区块这块暂时没有计划，但是会有针对具体业务场景类的搭建功能，如中后台常见的表单搭建

**Comment by boiawang** [comment]
@topwood 3.0 会上线表单场景化搭建和导航搭建，对于自定义区块你有什么样的诉求？

**Comment by topwood** [comment]
@chenbin92 @boiawang 我是觉得对于我们的需求方（通常是后端开发），或者其他开发同学（通常是外包）来说，有这么个可以让他们通过拖拽的方式参与到页面的设计并生成相应代码结构的工具是比较有用的。你们是怎么考虑的呢？

**Comment by boiawang** [comment]
@topwood 之前的自定义区块能力比较弱，只能实现静态的 UI(无数据绑定)，生成的代码也都是绝对定位的(维护性差)，如果单纯地实现静态的 UI 之前的方式没什么问题，但这种静态的业务需求很少，覆盖场景不全，所以近期我们还是会针对垂直领域场景(封装组件的方式)去做搭建，而元件级的搭建未来如果想出了更好的方案我们也会推出来的，短期内不会上。

**Comment by topwood** [comment]
@boiawang ok 3q

**Comment by james-cain** [comment]
![1558104492374](https://user-images.githubusercontent.com/18431775/57936160-e83ad080-78f5-11e9-8674-716d07547869.jpg)
关于菜单管理部分，希望红框内的内容可以自定义配置。
在之前版本中，有尝试在移动端模板中套用，但其实菜单项里的icon就是多余的，实际上我也需要多增加一些别的参数，希望这块可以以配置的形式呈现的更灵活。

**Comment by boiawang** [comment]
@james-cain 右上角的 + 就是增加一个菜单，“实际上我也需要多增加一些别的参数”，这里别的参数有具体的例子吗？

**Comment by james-cain** [comment]
@boiawang 我的模板在menuConfig.json里有增加一些参数，还有一些参数是不要的，比如图标我就是不需要的，具体的例子可能和官方的不一样，所以举例意义不太大。就是希望菜单项(位置、名称、路径、图标)这些可以配置，这样对于第三方的模板可以随意配置menuConfig

**Comment by YealZoy** [comment]
我想问一下  后续的icework 会有协同 开发的功能吗？  
比如说 
开发人员A在本地使用ice 初始化了项目p  
开发人员A的项目模板列表里 有项目p一些配置信息   
那开发人员B 使用Ice 可以通过某些操作 也可以获取项目p的一些配置信息吗？

**Comment by chenbin92** [comment]
> 开发人员A的项目模板列表里 有项目p一些配置信息

@YealZoy  这些配置信息是保存在开发人员A的本地？ 安装常规开发流程，如果 A，B 同时需要，那么这份配置信息应该是会被管理的，而不是依赖 A 的本地环境，比如存储在 GitLab/GitHub 的代码托管平台。后面会有项目研发流程的完整功能，目前还在规划中。

**Comment by chenbin92** [comment]
> @boiawang 我的模板在menuConfig.json里有增加一些参数，还有一些参数是不要的，比如图标我就是不需要的，具体的例子可能和官方的不一样，所以举例意义不太大。就是希望菜单项(位置、名称、路径、图标)这些可以配置，这样对于第三方的模板可以随意配置menuConfig

1. 如果图标不要，是否留空即可，不是一个必须的字段。
2. 目前的设计 `menuConfig` 这里是有一定的约定配置，这样才能确保 iceworks 按照一定的规则去添加
3. 对于第三方的模板可以随意配置 `menuConfig`，你目前的 menuConfig 是什么样的，方便的话贴一下代码

**Comment by lanyerzz** [comment]
> @chenbin92 @boiawang 我是觉得对于我们的需求方（通常是后端开发），或者其他开发同学（通常是外包）来说，有这么个可以让他们通过拖拽的方式参与到页面的设计并生成相应代码结构的工具是比较有用的。你们是怎么考虑的呢？

赞同，对于企业内部的应用和大部分对外的应用，前端布局、组件、交互   同质化非常严重，能实现拖拽，基本能节省80%体力劳动。

**Comment by imsobear** [comment]
已发布
