### ISSUE TITLE
快速上手打不开了呀

### ISSUE THREAD

**Issue by doubleHao2** [alibaba/ice#1938]
快速上手打不开呀，报错了。https://ice.work/docs/iceworks

**Comment by imsobear** [comment]
@doubleHao2 站点结构做了调整：https://ice.work/docs/guide/start ，上面那个链接入口在哪里？我修正下

**Comment by doubleHao2** [comment]
> @doubleHao2 文档结构做了调整：https://ice.work/docs/guide/start ，上面那个链接入口在哪里？我修正下

https://github.com/alibaba/ice  开始使用 快速上手指南。

**Comment by baixc1** [comment]
@ice/store，不兼容IE11，官网示例打不开（报错Proxy未定义。）
