### ISSUE TITLE
ice-scripts 兼容旧版本业务组件开发

### ISSUE THREAD

**Issue by tao1991123** [alibaba/ice#1957]
ice-scripts兼容旧规范业务组件。

## 1. 入口文件
旧规范文件为 src/index.jsx ,新规范为 src/index/js 。期望兼容结果`index.js`存在则用 index.js ,否则尝试使用 index.jsx 。

## 2. demo文档路径
旧规范文档存放在 /docs/*.md 目录下, 新规范存放在 /demo/*.md 目录下。期望兼容,优先使用 /demo ,不存在的话在使用 /docs/*.md 

## 3. demo文档内容
旧规范默认的Demo文件不会主动 import React和ReactDOM。把 React和ReactDOM挂载到 window上。

## 4. componentConfig字段依赖问题
ice-scripts 依赖一个`package.json`中的一个字段 componentConfig 来判定这个东西是组件/区块/模板。如果没有的话,运行`ice build`会报错。ice build名字支持 参数指定类型  例如 ice build component(具体命令待商榷) 那么就会把当前的代码作为组件编译。并且在`package.json`中加入 一个空字段。

**Comment by imsobear** [comment]
2.0 已支持
