### ISSUE TITLE
怎么实现登陆控制，只有在已经登陆的状态才可以访问主页面，否则跳回login页面

### ISSUE THREAD

**Issue by myyyy** [alibaba/ice#1958]
如题，多谢解答。
看了下authority
难道要在每一个menu 上面加 authority: 'admin' 才行吗？

顺便说一下官网页面 https://ice.work/docs/guide/dev/authority  Authorized 连接失效

**Comment by imsobear** [comment]
你可以在接口层面做统一鉴权，后端返回标志位，前端判断未登录则自动跳转。
