### ISSUE TITLE
ICE Design Pro    createBrowserHistory   使用时 报错 

### ISSUE THREAD

**Issue by wenJonSnow** [alibaba/ice#1975]
`import { createBrowserHistory} from 'history'; //  version 4.7.2
import { ConnectedRouter } from 'react-router-redux'; //version 5.0.0-alpha.8"
const history = createBrowserHistory(); <ConnectedRouter history={history}>{router()}</ConnectedRouter>
`

**Comment by imsobear** [comment]
请补充完整信息，补充后 reopen 下 issue.
