### ISSUE TITLE
Firefox浏览器布局显示不正确,Chrome显示正常

### ISSUE THREAD

**Issue by pengshaomin** [alibaba/ice#2000]
## 错误信息

![图片](https://user-images.githubusercontent.com/17870116/58234866-2c085c80-7d72-11e9-8343-1a56250cbdcd.png)

直接下载的订单管理 
Firefox浏览器布局显示不正确,Chrome显示正常

**Comment by imsobear** [comment]
@pengshaomin 欢迎 PR: https://github.com/ice-lab/react-materials
