### ISSUE TITLE
@icedesign/lite-scaffold@2.0.2 尚未发布在 https://registry.npm.taobao.org

### ISSUE THREAD

**Issue by ypchen-chjs** [alibaba/ice#2006]
## 问题描述

@icedesign/lite-scaffold@2.0.2 尚未发布在 https://registry.npm.taobao.org

**Comment by chenbin92** [comment]
npm 已发，淘宝源会自动同步，或者 cnpm sync 同步一下

![image](https://user-images.githubusercontent.com/3995814/58302072-bfe23300-7e1b-11e9-81ea-98c532170764.png)
