### ISSUE TITLE
window10调试模板项目失败

### ISSUE THREAD

**Issue by tangheng1995** [alibaba/ice#2010]
## 问题描述
用icework 2.20.0 里面的模板创建的项目，npm install 安装的依赖，调试报错
环境：
node:v10.15.3
icework:2.20.0
npm:6.4.1

## 错误信息

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Users\\Archer\\AppData\\Local\\Programs\\iceworks-desktop\\resources\\bin\\node.exe',
1 verbose cli   'C:\\Users\\Archer\\AppData\\Local\\Programs\\iceworks-desktop\\resources\\app\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.10.0
3 info using node@v8.9.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle @icedesign/creator-admin-scaffold@1.0.0~prestart: @icedesign/creator-admin-scaffold@1.0.0
6 info lifecycle @icedesign/creator-admin-scaffold@1.0.0~start: @icedesign/creator-admin-scaffold@1.0.0
7 warn lifecycle The node binary used for scripts is C:\Program Files\nodejs\node.exe but npm is using C:\Users\Archer\AppData\Local\Programs\iceworks-desktop\resources\bin\node.exe itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
8 verbose lifecycle @icedesign/creator-admin-scaffold@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle @icedesign/creator-admin-scaffold@1.0.0~start: PATH: C:\Users\Archer\AppData\Local\Programs\iceworks-desktop\resources\app\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;E:\Workspace\icework-workspace\blog-admin\node_modules\.bin;C:\Users\Archer\AppData\Local\Programs\iceworks-desktop\node_modules\.bin;C:\Users\Archer\AppData\Local\Programs\node_modules\.bin;C:\Users\Archer\AppData\Local\node_modules\.bin;C:\Users\Archer\AppData\node_modules\.bin;C:\Users\Archer\node_modules\.bin;C:\Users\node_modules\.bin;C:\node_modules\.bin;C:\Users\Archer\AppData\Local\Programs\iceworks-desktop;E:\devtool\xshell\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\Archer\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\Archer\AppData\Local\Programs\Python\Python37\;E:\devtool\Microsoft VS Code\bin;E:\devtool\flutter\flutter\bin;C:\Users\Archer\AppData\Roaming\npm;C:\Program Files\MySQL\MySQL Server 8.0\bin;C:\Users\Archer\AppData\Local\Programs\iceworks-desktop\resources\bin
10 verbose lifecycle @icedesign/creator-admin-scaffold@1.0.0~start: CWD: E:\Workspace\icework-workspace\blog-admin
11 silly lifecycle @icedesign/creator-admin-scaffold@1.0.0~start: Args: [ '/d /s /c', 'ice dev' ]
12 silly lifecycle @icedesign/creator-admin-scaffold@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle @icedesign/creator-admin-scaffold@1.0.0~start: Failed to exec start script
14 verbose stack Error: @icedesign/creator-admin-scaffold@1.0.0 start: `ice dev`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Archer\AppData\Local\Programs\iceworks-desktop\resources\app\node_modules\npm\node_modules\npm-lifecycle\index.js:283:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Archer\AppData\Local\Programs\iceworks-desktop\resources\app\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid @icedesign/creator-admin-scaffold@1.0.0
16 verbose cwd E:\Workspace\icework-workspace\blog-admin
17 verbose Windows_NT 10.0.10240
18 verbose argv "C:\\Users\\Archer\\AppData\\Local\\Programs\\iceworks-desktop\\resources\\bin\\node.exe" "C:\\Users\\Archer\\AppData\\Local\\Programs\\iceworks-desktop\\resources\\app\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 verbose node v8.9.4
20 verbose npm  v5.10.0
21 error code ELIFECYCLE
22 error errno 1
23 error @icedesign/creator-admin-scaffold@1.0.0 start: `ice dev`
23 error Exit status 1
24 error Failed at the @icedesign/creator-admin-scaffold@1.0.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by tangheng1995** [comment]
node:v10.15.3
icework:2.20.0

**Comment by tangheng1995** [comment]
"C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" run start --scripts-prepend-node-path=auto

> @icedesign/creator-admin-scaffold@1.0.0 start E:\Workspace\icework-workspace\blog-admin
> ice dev

internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'E:\Workspace\icework-workspace\blog-admin\node_modules\ice-scripts\bin\ice.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @icedesign/creator-admin-scaffold@1.0.0 start: `ice dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @icedesign/creator-admin-scaffold@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Archer\AppData\Roaming\npm-cache\_logs\2019-05-24T16_20_05_416Z-debug.log

Process finished with exit code 1

**Comment by chenbin92** [comment]
> throw err;
> ^

> Error: Cannot find module 'E:\Workspace\icework-workspace\blog-admin\node_modules\ice-scripts\bin\ice.js'

@tangheng1995  依赖没有安装，先按照依赖在启动调试
