### ISSUE TITLE
[框架] [前端] iceworks 功能使用情况统计

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#2026]
为了更好的促进 iceworks 的功能迭代、使用频率和发现问题，对 iceworks 的功能使用情况进行统计，只涉及功能操作的数据，不涉及任何用户的隐私数据统计，该 issue 仅用于讨论，最终方案需待定

- 行为数据
- 访问数据

**Comment by chenbin92** [comment]
目前 glodlog 数据采集不适合结构分类和观察，考虑将数据收集与 ice-scripts 的方式进行统一，采用通用的方案，与 Fusion 数据采集打通，具体待 @imsobear  确认

**Comment by chenbin92** [comment]
## 基本数据

* 日启动数、DAU、MAU
* 创建项目、新建页面、添加区块
* 有效项目数量以及项目简单的情况（当前项目信息发生变化时统计）

## 项目数据

* Git 操作次数
* 添加依赖次数
* OSS 发布次数
* Mock 操作次数
* 菜单操作次数
* 路由操作次数


## 工程数据

* 启动服务次数
* 启动配置次数
* 构建服务次数
* 构建配置次数
* 工程配置次数
* 依赖分析点击次数
* 控制台点击次数

##  物料数据
* 模板/区块/组件导航的点击量
* 统计物料源信息

## 设置数据
* 主题设置数据
* 编辑器设置数据
* Npm 源设置数据

**Comment by xiaoliang2233** [comment]
请问数据在哪里可以看到呢
