### ISSUE TITLE
iceworks 依赖 type 字段

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#2029]
## 问题描述

 在使用ice-devtools创建自定义物料时遇到一个问题：当我发布了物料并且生成了物料源地址， 添加到iceworks中， 无法正常显示， 组件、区块、模块均无法显示， 我可以确定在物料源中有组件和区块的存在

问题原因：

iceworks 依赖物料数据的 type 字段进行渲染

```json
{
  name: 'xxx',
  type: 'react' // or 'vue'
  blocks: [],
  scaffolds: []
}
```

**Comment by chenbin92** [comment]
- 根据 type 过滤功能需要
- 物料模板需要加回 type
- init 项目不能删除 scaffoldConfig

**Comment by imsobear** [comment]
- 物料源增加 type 字段
- 单个模板增加 iceworks.type 字段映射
