### ISSUE TITLE
ice-devtools 文档

### ISSUE THREAD

**Issue by DoranYun** [alibaba/ice#2039]
- 关于物料
- 快速开发物料
- 精品物料

- 开发指南
  - 物料初始化
  - 单个物料（？）开发：
    - add -> dev -> build -> screenshot -> publish
    - screenshot/homepage 两个特殊逻辑（？）
  - 物料数据生成：generate
  - 物料数据托管：fusion、npm(unpkg)
  - 物料数据使用：iceworks、物料站点

- 物料模板
  - 官方 React 物料模板：fusion/antd
  - 官方 Vue 物料模板：Element/iView
  - 自定义模板：.template 不是一个好的设计，考虑干掉（？）
  - 项目规范：menuConfig，routerConfig -> iceworks
  - 组件规范：React/Vue
  - 区块规范

- 参考
  - 物料数据协议
  - 物料私有化：单个物料私有，物料数据无需私有
  - 单独开发业务组件：React

**Comment by DoranYun** [comment]
- 关于物料
- 快速开发物料
- 精品物料

- 开发指南
  - 物料初始化
  - 单个物料（？）开发：
    - add -> dev -> build -> screenshot -> publish
    - screenshot/homepage 两个特殊逻辑（？）
  - 物料数据生成：generate
  - 物料数据托管：fusion、npm(unpkg)
  - 物料数据使用：iceworks、物料站点

- 物料模板
  - 官方 React 物料模板：fusion/antd
  - 官方 Vue 物料模板：Element/iView
  - 自定义模板：.template 不是一个好的设计，考虑干掉（？）
  - 项目规范：menuConfig，routerConfig -> iceworks
  - 组件规范：React/Vue
  - 区块规范

- 参考
  - 物料数据协议
  - 物料私有化：单个物料私有，物料数据无需私有
  - 单独开发业务组件：React

**Comment by imsobear** [comment]
@DoranYun 直接在主 issue 更新就可以
