### ISSUE TITLE
iceworks 下载的模板跟 npm 上模板内容不一致

### ISSUE THREAD

**Issue by LoLDragon** [alibaba/ice#2041]
## 问题描述
    搭建npm私有库后，从Iceworks下载的模板与上传到npm私有库模板内容不一致？
  
## 过程和错误信息
   1.将 `https://unpkg.com/zl-materials@latest/build/materials.json`执行npm sync-unpkg同步到unpkg。
   2.上传的内容如下：
上传的代码
![image](https://user-images.githubusercontent.com/19163371/58545542-0d083f80-8236-11e9-8fed-2a02414e8cf4.png)
通过`https://registry.npmjs.org/empty-single-page-scaffold/-/empty-single-page-scaffold-1.1.0.tgz`下载下来的代码如下：
![image](https://user-images.githubusercontent.com/19163371/58546320-ab48d500-8237-11e9-8251-be2d238f44e9.png)
  3.从Iceworks下载的模板内容为：
![image](https://user-images.githubusercontent.com/19163371/58545620-3628d000-8236-11e9-80af-4b783d28bb62.png)

总结：从Iceworks下载的模板与上传的模板内容不一致。目前发现为package.json 版本号不一致。

**Comment by chenbin92** [comment]
> 总结：从Iceworks下载的模板与上传的模板内容不一致。目前发现为package.json 版本号不一致。

 iceworks 在下载过程中将版本重置为 1.0.0 了，主要考虑是将版本重置，项目如果有需要自身维护这个版本，对于模板使用者不需要关系当前项目的版本和远程模板的版本建立联系

当然，这样设计会带来你现在的这种疑问 @imsobear 看下是否需要与模板的版本保持一致

**Comment by chenbin92** [comment]
结论：初始的项目版本与模板的版本保持一致不作修改
