### ISSUE TITLE
npm run build  Mac  报错  ice: command not found

### ISSUE THREAD

**Issue by WaveStill** [alibaba/ice#2048]
npm run build

> @icedesign/ice-koa-template@1.0.0 build /Users/didi/react/ice-react/ice-admin
> cd client && npm run build

> @icedesign/pro-scaffold@1.0.0 build /Users/didi/react/ice-react/ice-admin/client
> ice build --project-type=nodejs

sh: ice: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! @icedesign/pro-scaffold@1.0.0 build: `ice build --project-type=nodejs`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the @icedesign/pro-scaffold@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by Blankeer** [comment]
+1

**Comment by Blankeer** [comment]
使用新版 iceworks 新建模块已解决，查看 package.json,发现 start 改为 ice-scripts dev

**Comment by chenbin92** [comment]
> 使用新版 iceworks 新建模块已解决，查看 package.json,发现 start 改为 ice-scripts dev

ice-scripts 发布了 2.x 版本，命令改为了 `ice-scripts xxx`，需要统一修改下

**Comment by Blankeer** [comment]
> 使用新版 iceworks 新建模块已解决，查看 package.json,发现 start 改为 ice-scripts dev

又看了下，我这项目还是 ice 0.x 版本，见文档 https://ice.work/docs/guide/resource/upgrade-version，看实际情况选择是否升级吧

**Comment by WaveStill** [comment]
我的是用的新版的icework，自定义了一个项目，可以build，但是有些不行，ICE Design Pro 这个就不行，

**Comment by ClarkXia** [comment]
> 我的是用的新版的icework，自定义了一个项目，可以build，但是有些不行，ICE Design Pro 这个就不行，

给下具体的操作路径和错误输出

**Comment by WaveStill** [comment]
删除了老的，icework，下载了新的，build操作正常了
