### ISSUE TITLE
proxy没法代理静态资源

### ISSUE THREAD

**Issue by gooddaddy** [alibaba/ice#2049]
## 问题描述
**已经配置了代理服务器，但是静态链接的资源不会被代理到服务器上。**
![屏幕快照 2019-05-30 上午10 33 21](https://user-images.githubusercontent.com/14076373/58604782-3bcef600-82c8-11e9-87d7-f2941f35023c.png)

页面上引用：
`
<img src="/webapi/asset/qrcode" alt="" title="" style="display: block; max-width: none; height: auto; opacity: 0;">
`
查看network面板：
![屏幕快照 2019-05-30 上午10 24 26](https://user-images.githubusercontent.com/14076373/58604591-84d27a80-82c7-11e9-9fe7-bd4ed25083fd.png)
发现并没有发起代理。

### 对比普通的ajax请求：
![屏幕快照 2019-05-30 上午10 23 08](https://user-images.githubusercontent.com/14076373/58604662-c4996200-82c7-11e9-96f2-544b309e33a4.png)

普通ajax请求，能正常代理到指定的服务器上，但是dom 元素中引用的url没有代理到指定的服务器上。这样会造成我调试开发的时候和打包后运行不一致，是否有方法可以解决这问题。

**Comment by gooddaddy** [comment]
这问题使用插件xswitch解决了，原来官方文档2.0有说。

原文：
后端服务已部署（无论是测试环境还是生产环境），需要调试前端代码：直接访问后端服务的页面地址，然后将页面里加载的前端资源通过 chrome 插件 xswitch 代理成本地前端调试服务的资源，没有跨域问题，完全真实的数据，调试成本极低

同一个人同时开发前端和后端代码，直接访问后端的服务地址比如 http://127.0.0.1:6001，这个页面里加载本地的前端资源，实现前后端代码的同时调试

**Comment by imsobear** [comment]
@gooddaddy issue 我先关掉了哈
