### ISSUE TITLE
npm run bootstrap 初始化 Lerna报错

### ISSUE THREAD

**Issue by ren-liang** [alibaba/ice#205]
4317 silly @icedesign/application-progress-block
4318 error execute Error occured with '@icedesign/application-progress-block' while running 'npm run prepublish'
4319 error npm run prepublish [@icedesign/application-progress-block] Output from stdout:
4320 error npm run prepublish [@icedesign/application-progress-block] Output from stderr:
4321 error execute Error occured with '@icedesign/application-progress-block' while running 'npm run prepublish'

**Comment by noyobo** [comment]
@ren-liang 请问是点击上面操作后的错误提示？

**Comment by yujiangshui** [comment]
我试了下是 OK 的，要先 npm install 一下。如果有问题麻烦反馈更完整的报错信息。

**Comment by Mwuxiaoyu** [comment]
13 verbose stack Error: @0.1.13 bootstrap: `lerna bootstrap`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid @0.1.13
15 verbose cwd /home/wxy/BlockChain/remix
16 verbose Linux 4.15.0-52-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "bootstrap"
18 verbose node v10.16.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error @0.1.13 bootstrap: `lerna bootstrap`
22 error Exit status 1
23 error Failed at the @0.1.13 bootstrap script.
23 error This is probably not a problem with npm. There is likely additional logging output above.

**Comment by Mwuxiaoyu** [comment]
13 verbose stack Error: @0.1.13 bootstrap: `lerna bootstrap`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid @0.1.13
15 verbose cwd /home/wxy/BlockChain/remix
16 verbose Linux 4.15.0-52-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "bootstrap"
18 verbose node v10.16.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error @0.1.13 bootstrap: `lerna bootstrap`
22 error Exit status 1
23 error Failed at the @0.1.13 bootstrap script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
请问这个error怎么弄？
