### ISSUE TITLE
iceworks 选择中文名的文件夹不支持

### ISSUE THREAD

**Issue by noyobo** [alibaba/ice#206]

**Comment by Beritra** [comment]
同样出现了这个问题。选择中文文件夹之后选择框仍然是空白。

**Comment by yujiangshui** [comment]
![image](https://user-images.githubusercontent.com/2942913/37204898-9c26b020-23cd-11e8-813e-ace3a01bb2b7.png)

需要确认为什么会有这个逻辑

**Comment by yujiangshui** [comment]
@noyobo 应该支持中文目录和中文名，不限制。但是可以提示不推荐。

**Comment by noyobo** [comment]
路径中支持中文，项目文件夹不支持中文。

**Comment by yujiangshui** [comment]
项目文件夹不推荐用中文，已经给出提示。如后期需求比较多再 open 做修复吧。不推荐用中文
