### ISSUE TITLE
react项目打包为带hash值的css和js文件

### ISSUE THREAD

**Issue by ovarte** [alibaba/ice#2063]
## 问题描述

icework **React项目**，怎么**配置.webpackrc.js**，打包生成js或css的hash名字
**[name].js->[name][hash:6].js**
[name].css->[name][contenthash:6].css
比如 main.js -> main.ab12et.js
并且在index.html文件引入该带hash的文件

**Comment by ovarte** [comment]
https://github.com/alibaba/ice/issues/175
找到这个issue了，希望飞冰在打包的时候，默认打包成hash文件

**Comment by gooddaddy** [comment]
> #175
> 找到这个issue了，希望飞冰在打包的时候，默认打包成hash文件

但是这个貌似打出来的 不是contenthash的哦

**Comment by imsobear** [comment]
> > #175
> > 找到这个issue了，希望飞冰在打包的时候，默认打包成hash文件
> 
> 但是这个貌似打出来的 不是contenthash的哦

https://github.com/alibaba/ice/blob/master/tools/ice-scripts/lib/plugins/userConfig/configs/hash.js#L3 @ClarkXia @gooddaddy 我理解这里 hash 可以配字符串就可以满足了？
