### ISSUE TITLE
ice-scripts 2.0 如何配置 splitChunks

### ISSUE THREAD

**Issue by gooddaddy** [alibaba/ice#2065]
ice-scripts 2.0 如何配置 splitChunks

```
      config.optimization.splitChunks(
        {
          cacheGroups: {
            vendor: {
              test: /[\\/]node_modules[\\/]/,
              name: 'vendor',
              chunks: 'initial',
              minChunks: 2,
            },
          },
        }
      );
```
我这样写不起作用，没有打包出vendor.js 包来

**Comment by ClarkXia** [comment]
这个配置和ice-scripts 2.0内置配置一致，多入口的时候才会带出vendor，可以确认下ice.config.js的配置

**Comment by gooddaddy** [comment]
> 这个配置和ice-scripts 2.0内置配置一致，多入口的时候才会带出vendor，可以确认下ice.config.js的配置

刚刚看了源码,发现者的确是这样的，但是我还有一个问题，ice 为什么打包出来的名称使用hash，而不是contenthash，这样每次打包出来的东西都不一样，不管是否修改过文件，这样对浏览器缓存不太友好吧。

**Comment by imsobear** [comment]
hash 问题在另一个 issue 讨论哈
