### ISSUE TITLE
我还没有选择目录 就开始创建模板了

### ISSUE THREAD

**Issue by Bubblex** [alibaba/ice#207]

**Comment by Bubblex** [comment]
1.第一次点’以该模板创建项目‘后，我选了一个目录，发现目录选错了，就关闭了弹框。
2.第二次点‘以该模板创建项目’后，多次点击’浏览‘按钮后没有弹出目录选择。
3.目录为空的情况下，点击了创建项目 结果如上图。

**Comment by yujiangshui** [comment]
已经添加未选择目录的校验
