### ISSUE TITLE
ice-scripts 业务组件开发 adaptor 报错

### ISSUE THREAD

**Issue by luhc228** [alibaba/ice#2075]
按照官网React 物料开发指南搭建报错。<https://ice.work/docs/materials/react>
![error](https://i.loli.net/2019/06/03/5cf4933e5400629236.png)
去掉adaptor文件夹没有报错。

**Comment by luhc98** [comment]
![alifd/next](https://i.loli.net/2019/06/03/5cf497020db2716353.png) package.json中也没有默认带@alifd/next依赖

**Comment by imsobear** [comment]
adaptor 的问题我看下，next 这个设计上就是默认不引入，自已安装下依赖即可
