### ISSUE TITLE
Upload组件onChange事件参数问题

### ISSUE THREAD

**Issue by anan0825** [alibaba/ice#2076]
## 错误信息
第一次
![image](https://user-images.githubusercontent.com/38789599/58760473-e403e980-856a-11e9-8c81-d1810d5e9259.png)
第二次
![image](https://user-images.githubusercontent.com/38789599/58760478-f847e680-856a-11e9-916e-8badbbf4aabe.png)

**Comment by tao1991123** [comment]
什么浏览器？
