### ISSUE TITLE
物料协议增加对应的 npm 版本和作者信息

### ISSUE THREAD

**Issue by tao1991123** [alibaba/ice#2077]
RT

![](https://img.alicdn.com/tfs/TB1n0.VblOD3KVjSZFFXXcn9pXa-1704-962.png)

**Comment by imsobear** [comment]
组件感觉问题不大，区块（跟模板一样）构建出的 html 就是用户写的代码，不太好侵入

**Comment by bindoon** [comment]
再增加一个 issue 地址吧

**Comment by tao1991123** [comment]
先把组件做了也可以

**Comment by imsobear** [comment]
https://github.com/alibaba/ice/blob/master/packages/ice-plugin-component/lib/template/index.html.hbs @bindoon @tao1991123 来 PR 吧~~

**Comment by imsobear** [comment]
另外，通过物料协议数据自己渲染是不是更好一点？类似官网这样

![image](https://user-images.githubusercontent.com/2505411/58788394-67cade00-861e-11e9-97fd-f2a5cd5d5eab.png)

**Comment by imsobear** [comment]
![image](https://user-images.githubusercontent.com/2505411/59346862-d9eda200-8d45-11e9-9244-ab8735d151d6.png)
