### ISSUE TITLE
物料托管与使用文档

### ISSUE THREAD

**Issue by luhc228** [alibaba/ice#2078]
这个的 `npm run sync` 和 ·`npm run sync-unpkg`对应的在package.json中的script是什么？是我运行这个脚本的根目录下不对吗？物料托管与使用这个文档可以讲得具体些吗？
![sync](https://i.loli.net/2019/06/03/5cf4c48597be184141.png)

**Comment by imsobear** [comment]
idev sync 和 idev sync-unpkg

文档我 check 下，另外这周我们会重构一下这块的文档 https://github.com/alibaba/ice/issues/2039

**Comment by DoranYun** [comment]
使用 ice-devtools 初始化项目之后，根目录生成的 package.json 中包含这两个命令，对应的就是 idev sync 和 idev sync-unpkg

![image](https://user-images.githubusercontent.com/16359169/58782496-621acb80-8611-11e9-9164-8abde78a7b92.png)

**Comment by luhc98** [comment]
> idev sync 和 idev sync-unpkg
> 
> 文档我 check 下，另外这周我们会重构一下这块的文档 #2039

Thanks.
