### ISSUE TITLE
win64安装的时候能否支持下选目录了

### ISSUE THREAD

**Issue by Ezoio** [alibaba/ice#2079]
win64安装的时候能否支持下选目录了

**Comment by Ezoio** [comment]
win10-64机器下载安装包后，双击就直接安装了啊？好不习惯！！

**Comment by chenbin92** [comment]
现有 iceworks 2.x 版本不支持选择目录，在 iceworks 3.x 版本我们会主要提供 CLI + Web 的方式，不在强依赖 electron app 的形式

**Comment by Ezoio** [comment]
了解
