### ISSUE TITLE
ice hash 为什么默认情况不用contenthash

### ISSUE THREAD

**Issue by gooddaddy** [alibaba/ice#2091]
先问一下 ice-scripts2.0中：  hash: true,  为什么默认情况下使用hash 而非 用contenthash，感觉使用hash 每次打出来的包都不一样，即便没修改过，这样对浏览器缓存不太友好吧

**Comment by imsobear** [comment]
https://github.com/alibaba/ice/issues/2063 有类似问题就不要重复建 issue 了，事实上大部分场景都是直接用 hash 的，具体可以在 2063 这个 issue 讨论。

**Comment by zyhahaha** [comment]
> 先问一下 ice-scripts2.0中： hash: true, 为什么默认情况下使用hash 而非 用contenthash，感觉使用hash 每次打出来的包都不一样，即便没修改过，这样对浏览器缓存不太友好吧
> 
> ## 问题描述
> ## 错误信息

兄弟，这个问题找到答案了吗，我也很好奇为什么大多数的项目都是使用hash而不是contenthash
