### ISSUE TITLE
飞冰1.x Ellipsis组件样式问题

### ISSUE THREAD

**Issue by Loving-Vincent** [alibaba/ice#2106]
## 问题描述
飞冰1.x Ellipsis 组件的showTooltip样式问题。
鼠标悬浮Ellipsis元素时，showTooltip在元素上方显示并且三角形箭头也在上方：

![image](https://user-images.githubusercontent.com/36978364/58945324-3ab13380-87b6-11e9-8240-e444f8758053.png)
（截图来自飞冰官网： https://ice.work/component/ellipsis#%E7%94%A8%E5%9C%A8%E8%A1%A8%E6%A0%BC%E4%B8%AD ，滚动条拖动到某个位置可以复现bug。）

个人推测是因为元素距离屏幕下方距离小于弹出内容的高度，所以在上方显示。但是三角形箭头也应该跟着到弹出内容的下方吧。

**Comment by boiawang** [comment]
Ellipsis 里用的是 Next Tooltip，Tooltip 本身有这个 bug.  @youluna 

![image](https://user-images.githubusercontent.com/6340730/59005565-b8298200-8850-11e9-95fa-3a7a15377b9e.png)
