### ISSUE TITLE
目录部分和项目名的关系详细说明并提示

### ISSUE THREAD

**Issue by yujiangshui** [alibaba/ice#211]
![image](https://user-images.githubusercontent.com/2942913/37032378-45995368-217d-11e8-91bc-4f26aaee126c.png)

**Comment by noyobo** [comment]
创建项目流程需要有优化下

现在的是目录选择+项目名

改成： 目录选择 + 文件夹名(`/-_a-z0-9]/`) + 项目名（默认等于文件夹名）

生成路径  `path.join(目录，文件夹)`

**Comment by noyobo** [comment]
@yujiangshui @wssgcg1213  这样如何

**Comment by yuanyan** [comment]
选择的目录就是根目录，选择目录的时候检测该目录下是否有文件，有文件的时候提示用户该目录不是空目录

**Comment by wssgcg1213** [comment]
![image](https://user-images.githubusercontent.com/3922719/37076588-40dc5826-2212-11e8-869b-2311d8edcdea.png)
![image](https://user-images.githubusercontent.com/3922719/37076590-437401ce-2212-11e8-80de-a92e1258b994.png)

如截图所示, 这个选择的操作很容易引起误解

**Comment by wssgcg1213** [comment]
截图上用户期望的是选择 `mock` 目录, 但其实选中的是当前展示的这个目录

**Comment by wssgcg1213** [comment]
方案上最好的其实是把这个原生UI换成一个更友好的界面, 折中方案可以是强提示用户选择的完整路径

**Comment by noyobo** [comment]
![image](https://user-images.githubusercontent.com/1292082/37248818-d3f3eb00-2515-11e8-8bae-2937ba2eed52.png)

冲突的提示默认重新选择，

- [ ] 增加删除项目时把项目文件进入回收站

**Comment by yujiangshui** [comment]
![image](https://user-images.githubusercontent.com/2942913/37335788-6dc1e23e-26ea-11e8-9cce-3064c9602d8e.png)
