### ISSUE TITLE
menu Aside 收起展开模式 Bug

### ISSUE THREAD

**Issue by WaveStill** [alibaba/ice#2115]
操作环境   Mac  icework 2.0+

menu栏  进行 Aside 收起展开模式  

当收起的时候，会显示在content的位置 不消失，要再点击一下 面板才会消失 

![image](https://user-images.githubusercontent.com/22174061/59102018-66bae900-895d-11e9-9093-8438180c764a.png)

**Comment by WaveStill** [comment]
调了几下样式 还是不行，不知道具体哪里的问题，还望大佬 给解答一下，万分感谢

**Comment by imsobear** [comment]
https://github.com/ice-lab/react-materials/pull/30 @WaveStill 先按照这个修复下
