### ISSUE TITLE
win10系统中在系统状态栏中的ice图标显示不完整

### ISSUE THREAD

**Issue by mowatermelon** [alibaba/ice#212]
> 高兴的更新了1.0.0，结果新图标在系统状态栏显示不完整，有种风烛残年的味道

系统
版次 window 10专业版
版本 1709
OS内部版本 162.99.64
node V8.9.1
iceworks  1.0.0
网络环境  良好

![image](https://user-images.githubusercontent.com/18508817/37039365-3f282f08-2192-11e8-8005-200343fb4032.png)

**Comment by yujiangshui** [comment]
感谢反馈。。我们装个虚拟机排查下

**Comment by noyobo** [comment]
v1.0.2 更新了 ico 文件，问题如果还存在，请 reopen issue
