### ISSUE TITLE
[设置] 面板设置

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#2124]
- [x] 面板状态
    - [x] 开启或关闭
    - [x] 顺序
- [x] 面板拖拽

**Comment by alvinhui** [comment]
## 背景

项目的面板状态包含 3 个方面的内容：

- 有哪些面板？
- 哪些是用户开启的？
- 面板间的顺序如何？

不同的项目的类型有不同的面板状态。这体现为两个方面：

- 实现层面：导航面板目前只实现了 ICE 项目，对于 Angular 和 Vue 项目没有实现。如果此时上线，后两者应该怎样支持面板状态。在 Iceworks 产品的迭代过程中，会经常遇到这个问题：某个能力先支持哪些类型的项目，不支持的项目应该怎么处理；
- 类型层面： 不同的项目类型在能力的支持上就有不同。举个例子：即使是同一种脚手架工具（ice-scripts）也存在不同的版本对应不同的目录结构。

## 本质问题

- Adapter 应该按照怎样的一种维度进行划分；
- 服务端 Adapter 和前端面板如何进行关联。

**Comment by alvinhui** [comment]
## 初始问题

- Iceworks 3.x 怎么兼容以下的项目情况：
    - ice-scripts@2.0+新版目录结构（新项目）
    - ice-scripts@2.0+旧版目录结构（当前项目）
    - ice-scripts@1.0+旧版目录结构（老项目）
- 适配器和前端如何关联？

## 本质问题

- 怎么支持多种工程工具和目录结构；
- 不同的工程&目录在前端展现上有无差别，有哪些差别，如何处理差别。

## 分析问题

### 如何支持多种工程工具和目录结构

Iceowrks 需关注：工程工具 + 最佳实践（Pro）的组合（umijs 哭晕在厕所）。

> 我更倾向于将「目录结构」称为「最佳实践」。

我们支持的工程工具：

- react: ice-scripts
    - 1.0: .webpackrc.js
    - 2.0: ice.config.js
- vue: @vue/cli-service
    - 3.0: vue.config.js
- angular: @angular/cli
    - 6.0.0: angular.json

我们支持的 Pro：

- react:
    - 1.0
    - 2.0
- vue:
    - 1.0
- angular:
    - 1.0

能够产生的组合：

- react: 3 种（不存在 ice-scripts@1.0 + Pro@2.0 的情况）
- vue: 1 种
- angular: 1 种

总计 5 中。

### 前端展现差异性

工程工具包含哪些能力？

- 命令执行：dev/build/lint/test 

    - 无差异：都通过 pacakge.json 的 script 字段配置，前端操作方式上无差异；
    - 有差异：不同的工程工具包含的能力不一样，在「有无该功能」上有差异。
- 工程配置：config.js/lint.js

    - 无差异：都是配置项，在前端都以表单的方式展现；
    - 有差异：最终的实现的代码不一样，在最终操作产物上有差异。

项目管理包含哪些能力？

- 生成：通过模板生成，模板由 ice-devtool 生成；
- 开发：操作无差异，产物有差异。

    - 导航管理
    - 路由管理
    - 页面管理
- 发布：无差异

    - Git
    - OSS
    - DEF

## 怎么做？

- iceworks-adapter-interface：接口

    - iceworks-adapter-base：基础类

      - iceworks-adapter-react
      - iceworks-adapter-vue
      - iceworks-adapter-angular
