### ISSUE TITLE
[项目] 发布链路 - 静态资源发布

### ISSUE THREAD

**Issue by alvinhui** [alibaba/ice#2129]
### 发布链路

前端项目的发布，包含两个阶段的内容：

- 代码发布（Git）：代码版本管理的范畴；
- 静态资源发布（DEF），「云构建」的范畴 ，在云端服务器中将执行：

    「拉取代码仓库的源代码」=> 「执行构建打包」=> 「推送构建结果资源到 CDN 」

Iceworks 发布链路需通过 GUI 的方式完成这些内容。

### 2.x 的处理方式

2.x 中分三个面板来实现这两个阶段的内容：

- 代码发布：Git 面板
- 静态资源发布：

    - DEF 面板：通过将 @ali/def-pub-client 代码内置，调用该包进行发布（实际上 def-pub-client 的源代码是暴露的）；
    - OSS 面板：将本地的构建产物推送到 OSS。

## 问题

在 3.x 中将不改变产品方案（依然分三个面板）来处理。

在技术上，由于 @ali/def-pub-client 是内部包发布到了 tnpm，iceworks-cli 将发布到 npm。

**如何调用 DEF 客户端能力是一个问题。**

### 方案一：将 @ali/def-pub-client 代码内置到 iceworks-server

该方案与 2.x 的处理方式一致，在 iceworks-server 安装时下载 DEF 代码到根目录。

- 优点：处理方式简单有效
- 缺点：暴露了 DEF 源代码

### 方案二：直接调用 DEF 命令行工具

不再内置包，而是改为调用用户系统中的 DEF 客户端。

- 优点：Icework 弱依赖 DEF 客户端，处理方式更轻量
- 缺点：用户需手动安装 DEF 客户端（相当于把成本转嫁给了用户）

### 方案三：@ali/def-pub-client 发布到 npm

- 优点：开发和维护成本最低
- 缺点：把成本和风险转嫁给了 DEF 团队

### 方案四：划分为内外网 iceworks-cli 版本

对外输出 @ali/iceworks 和 iceworks 两个版本，前者依赖 @ali/def-pub-client  源码。

- 优点：满足需求又保障了源码的安全性
- 缺点：处理方式复杂，维护成本高

**Comment by chenbin92** [comment]
DEF 插件只在内网环境下才会展示， iceworks-server 依赖的代码也只会有 `@ali/def-pub-client` 这个包名，也就是暴露的只是这个包名，不会暴露源码。按照现在的面板设计只有内网的用户才会有机会下载这个包。

**Comment by alvinhui** [comment]
方案一虽然 DEF 插件只在内网环境下才会展示，但是 @ali/def-pub-client 这个包是需要在打包环节就需要的，而不是运行时加载。

**Comment by imsobear** [comment]
目前来看还是方案一可行点，可以考虑跟 DEF 的同学沟通下 @alvinhui

**Comment by chenbin92** [comment]
> 方案一虽然 DEF 插件只在内网环境下才会展示，但是 @ali/def-pub-client 这个包是 iceworks-server 打包环节就需要的，不是运行时加载。

@alvinhui iceworks-cli 拉取 iceworks-server 是在 postinstall 阶段做的，可以根据安装时是否内网环境去下载这个包，相当于你所说的运行时加载了

**Comment by alvinhui** [comment]
> > 方案一虽然 DEF 插件只在内网环境下才会展示，但是 @ali/def-pub-client 这个包是 iceworks-server 打包环节就需要的，不是运行时加载。
> 
> @alvinhui iceworks-cli 拉取 iceworks-server 是在 postinstall 阶段做的，不是默认就内置在 iceworks-cli 的代码里的，可以根据安装时是否内网环境去下载这个包，相当于你所说的运行时加载了

也是一个方法。那样的话用户得安装 tnpm。

**Comment by alvinhui** [comment]
方案五：

iceworks-server 安装时根据环境（是否内网）判断：

- 内网：拉取 @ali/def-pub-client 代码；
- 外网：无。

**Comment by alvinhui** [comment]
## 功能列表

- [x] DEF 面板

     - [x] 无关联仓库时提醒
     - [x] 日常发布和线上发布
     - [x] 未登录时发布提醒
- [x] 用户登录
