### ISSUE TITLE
更新了IceWork之后，打开GUI工具，左侧选项丢失

### ISSUE THREAD

**Issue by ArcherKay** [alibaba/ice#2132]
![image](https://user-images.githubusercontent.com/16865186/59259635-c3bfe300-8c6c-11e9-9f78-9aa0f19d8380.png)

**Comment by imsobear** [comment]
#2117 看下跟这个问题一样不

**Comment by chenbin92** [comment]
1. 提供版本
2. 提供错误信息（打开控制台）

**Comment by chenbin92** [comment]
https://github.com/alibaba/ice/issues/2117
