### ISSUE TITLE
[框架] iceworks-server多语言方案

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#2137]
# [框架] [服务端] 多语言方案

服务端返回的信息需以用户的设置的语言进行返回

## 目录结构
在 adapter 中维护一份中英文字典，具体如下：
```
- adapter
----- modules/
----- utils/
----- locales/
---------- en-US.ts
---------- zh-CN.ts
```

## 配置字典
```js
export default {
   [adapter.moduleName.action]: 'xxxx'
}
```

## 插件挂载 
将 locales 配置对象挂载到应用上

```json
{
  "eggPlugin": {
    "name": "locales"
  }
}
```

## Node 中使用

```js
ctx.socket.emit('adapter.dependency.reset.data',  ctx.locales.xxx);
```

## 前端使用
```
{data[locale]}
```

**Comment by chenbin92** [comment]
放在通用设置中实现

**Comment by chenbin92** [comment]
related: https://github.com/alibaba/ice/issues/2122

**Comment by alvinhui** [comment]
1. [egg-i18n](https://github.com/eggjs/egg-i18n)
2. 如果自己做插件，需要介绍一下如何设计，主要关注的点：

    - 怎么跟用户的设置保持一致；
    - 怎么做从 adapter 目录读取语言文件；
    - 看起来 adapter 里面不能用声明式字段了？比方说 https://github.com/alibaba/ice/pull/2181 里的 title&&description...

**Comment by chenbin92** [comment]
1. 看了下 egg-i18n，和上面的方案基本差不多，就是做了插件那一层
2. 怎么跟用户的设置保持一致
> 我上面想的是上面直接返回一个 `{zh: 'xxx', en: 'xx'}` 的形式给前端，然后前端是知道当前是什么语言的去匹配，当然这个匹配的流程也可以在后端做，只返回前端当前设置的数据

3. 怎么做从 adapter 目录读取语言文件
> 和上面的问题一样，不用获取，返回的就是一个对象，详见上面的 Node 的使用

4. 看起来 adapter 里面不能用声明式字段了？比方说 #2181 里的 title&&description...
> 是的，需要读配置的变量

**Comment by chenbin92** [comment]
@alvinhui 

> 1. 看了下 egg-i18n，和上面的方案基本差不多，就是做了插件那一层
> 2. 怎么跟用户的设置保持一致
> 
> > 我上面想的是上面直接返回一个 `{zh: 'xxx', en: 'xx'}` 的形式给前端，然后前端是知道当前是什么语言的去匹配，当然这个匹配的流程也可以在后端做，只返回前端当前设置的数据
> 
> 1. 怎么做从 adapter 目录读取语言文件
> 
> > 和上面的问题一样，不用获取，返回的就是一个对象，详见上面的 Node 的使用
> 
> 1. 看起来 adapter 里面不能用声明式字段了？比方说 #2181 里的 title&&description...
> 
> > 是的，需要读配置的变量

**Comment by Orange-C** [comment]
考虑扩展一下，把前端面板的国际化能力也包含进来，然后吧国际化的文案配置化放在阿里云ACM服务上管理，避免修改文案导致代码频繁发版的问题

**Comment by Orange-C** [comment]
> 1. [egg-i18n](https://github.com/eggjs/egg-i18n)

@alvinhui egg-i18n调研了下不合适，它的语言切换是基于http请求的cookie或者header的，但我们的通信是基于socket的，配置也是写在本地

**Comment by Orange-C** [comment]
# server多语言方案

## 目标
1. 服务端返回信息实现多语言
2. 多语言文案集中配置化

## 存储方案
1. 使用{语言名称}.json存储，例如zh-CN.json
2. 可以写模板

```json
{
  "server.dependency.install": "开始安装 %s 依赖"
}
```

## 使用方案
1. 使用midway plugin
2. 通过依赖注入与app对象解耦
3. plugin内根据配置的locale变量决定使用哪个语言的json
```js
class Dependency {
  @plugin('locale');
  locale;

  publich install() {
    console.log(this.locale.format('server.dependency.install', text)
  }
}
```

**Comment by alvinhui** [comment]
这里不应该使用依赖注入？Adapter 内是感知不到 midway 的，可以挂到 ctx 上。

- 返回的语言读 storage 内的 locale，这个是用户设置的；
- 命名空间明确一下，我提议用 `adapter.${module}.${method}.xxx`；

    ```javascript
    class Dependency {
      publich install(params, ctx) {
        console.log(ctx.locale.format('adapter.dependency.install.test'));
      }
    }
    ```
- 语言文件的地址明确一下，我的建议：

    ```
    --/adpater
    ----/modules/
    ------/page/
    ------/task/
    ----/locals/
    ------/en-US.json
    ------/zh-CN.json
    ```
- 模板语法希望和 react-intl 保持一致，减少 adapter 开发者的理解成本

**Comment by Orange-C** [comment]
@alvinhui 
* 配置，命名空间，模板语法没有异议。
* 语言文件不仅仅是adpater使用的，我们应用中其他地方（比如controller）也有文本，所以我们官方的locale文件放在全局比较好，可以放在config中。

* locale插件支持在运行时添加语言配置，adapter开发者可以在初始化的时候添加自己的多语言配置。如下
```js
ctx.locale.set('zh-CN',  {
  'adapter.someone.something': '你好'
});
ctx.locale.set('en-US',  {
  'adapter.someone.something': 'Hello'
});
```
1. 这个函数仅支持外部使用，我们自己应用内的文本还是使用统一的文件管理
2. 优先级高于原配置，字段同名情况下会覆盖

**Comment by alvinhui** [comment]
- iceworks-server 的放全局，adapter 的放 adapter 里面？
- 是初始化配置还是主动去读 adapter 文件夹后 merge ，还是让开发者调用方法去设置语言，哪一种更好呢？我觉得前者对开发者友好一些。如果是前者，则不存在你说的初始化配置问题。

**Comment by Orange-C** [comment]
> * iceworks-server 的放全局，adapter 的放 adapter 里面？
> * 是主动去读 adapter 文件夹后 merge ，还是让开发者调用方法去设置语言，哪一种更好呢？我觉得前者对开发者友好一些。如果是前者，则不存在你说的初始化配置问题。

同意。我调研下实现方案

**Comment by chenbin92** [comment]
1. adapter 是会单独抽离成 Npm 包的形式的，iceworks-server 会主动根据项目配置的 adapter 进行加载
2. iceworks-server 是核心的框架层，有自己的语言包，与 adapter 是隔离的，框架提供加载能力
