### ISSUE TITLE
[框架] [服务端] 存储层

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#2138]
- [x] 用户设置的存储；
- [x] 用户项目状态的存储；

**Comment by chenbin92** [comment]
## 可选库

- [conf](https://www.npmjs.com/package/conf): 
    -  支持通过配置 schema 的方式定义和校验应用需要存储的数据格式
    -  提供接口支持 set、get、delete 等配置操作

- [configstore](https://www.npmjs.com/package/configstore):
  - 与 conf 是同一个作者，可以理解 conf 是在 configstore 之后的重构版本

- [lowdb](https://www.npmjs.com/package/lowdb):
  - 基于 node 的纯 JSON 文件数据库，支持 Browser，Electron，node 
  - 能使用任何 lodash 方法来查询和操纵数据库
  - 针对 lowdb 自带的适配器：FileSync、FileAsync 和 LocalBrowser

**对比**
   * lowdb 功能非常完善，API 和链式操作比较方便，相比较 conf 就比较轻量，支持基本的操作。

## iceworks 存储
在  iceworks 中主要存储用户的设置配置，以及用户项目的信息，需要存储的数据相对较少，schema 如下：
```js
const schema = {
  workFolder: {
    type: 'string',
    default: userHome,
  },
  user: {
    type: 'object',
    default: {
      workId: '',
      name: '请登录',
      avatarUrl: 'https://img.alicdn.com/tfs/TB1hjBJXLxj_uVjSZFqXXaboFXa-147-150.jpg',
      isLogin: false,
    },
  },
  project: {
    type: 'string',
    default: '',
  },
  projects: {
    type: 'array',
    default: [],
  },
  editor: {
    type: 'string',
    default: 'code',
  },
  locale: {
    type: 'string',
    default: 'zh-CN',
  },
  theme: {
    type: 'string',
    default: '@alifd/theme-iceworks-dark',
  },
  material: {
    type: 'array',
    default: [
      {
        name: '',
        description: '',
        homepage: '',
        logo: '',
        source: '',
        tags: [ ],
        official: true
      }
    ],
  },
  oss: {
    type: 'array',
    default: [],
  },
};
```

## 方案
- 在 iceworks 使用 conf 库管理数据
- 在用户系统环境中创建 iceworks.json 文件持久化存储数据

**Comment by imsobear** [comment]
~/.iceworks/config.json 这样是不是更好一些

**Comment by chenbin92** [comment]
> `~/.iceworks/config.json` 这样是不是更好一些

<user-home>/.iceowrks/db.json

**Comment by Orange-C** [comment]
持久化储存的json需要放在npm包外（最好是用户目录），不然在npm包更新之后json会丢失
