### ISSUE TITLE
Window版安装时没让用户选择安装在哪个目录

### ISSUE THREAD

**Issue by chunyong1991** [alibaba/ice#214]
如题，没得选择安装在D盘很让人困扰

**Comment by noyobo** [comment]
目前是默认安装了。

后续提供选择的方式，敬请关注。

**Comment by yujiangshui** [comment]
@noyobo 查了下是不是配置下 allowToChangeInstallationDirectory 就可以了，看到之前这个 issue https://github.com/electron-userland/electron-builder/issues/596

**Comment by fenglai0802** [comment]
2.18.0 支持
