### ISSUE TITLE
ice-scripts 构建过程组件样式丢失

### ISSUE THREAD

**Issue by gooddaddy** [alibaba/ice#2144]
## 问题描述
npm run start 运行后发现页面缺失Layout控件的必要css（类似这样的问题，已经发现过很多次了，每次都感觉莫名其妙），原因有可能是因为拆包。
![屏幕快照 2019-06-12 下午2 02 17](https://user-images.githubusercontent.com/14076373/59327016-e7d9fd80-8d1a-11e9-9279-40222052db14.png)
查看发现 ice-layout ice-layout-fixable 缺失了。

项目依赖：
  "dependencies": {
    "@alifd/next": "^1.14.2",
    "@antv/data-set": "^0.9.5",
    "@icedesign/container": "^1.x",
    "@icedesign/data-binder": "^1.x",
    "@icedesign/dynamic-icon": "^0.1.8",
    "@icedesign/ellipsis": "^1.x",
    "@icedesign/form-binder": "^1.0.3",
    "@icedesign/foundation-symbol": "^1.0.0",
    "@icedesign/img": "^1.0.0",
    "@icedesign/label": "^1.x",
    "@icedesign/layout": "^1.x",
    "@icedesign/notification": "^1.0.3",
    "@icedesign/panel": "^1.0.0",
    "@icedesign/qrcode": "^1.0.3",
    "@icedesign/theme": "^1.0.0",
},
  "devDependencies": {
    "acorn-dynamic-import": "^4.0.0",
    "babel-eslint": "^8.0.3",
    "babel-plugin-syntax-dynamic-import": "^6.18.0",
    "eslint": "^4.13.1",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-plugin-babel": "^4.1.1",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-react": "^7.5.1",
    "ice-plugin-fusion": "^0.1.6",
    "ice-scripts": "^2.0.2",
    "webpack": "4.28.4"
  },

**Comment by imsobear** [comment]
@gooddaddy 是偶尔会出现还是？

**Comment by gooddaddy** [comment]
@imsobear 
如果出现了，无论如何打包都会出现，除非改成不拆包。
1.上次遇到过process控件样色丢失的，后来我是在没办法 我就自己把他控件的样色import 近来就好了。2.还有一次就是输入框样色丢失的。加载a页面的时候入框样没样色，加载b页面后再加载a页面就好了，查看css发现，本来a页面依赖的输入框组件样色，并没用被打包a页面所依赖的css包中，反而跑到了b页面的依赖的css中了。（a.js 异步加载的时候 会异步加载1.css,a.css 没有 输入框组件的样色，b.js异步加载的时候加载了2.css,3.css 样色，其中3.css包含了 输入框的样色）
1，2情况都是在 ice-scripts 1.8 版本的时候发现的。

**Comment by imsobear** [comment]
那感觉是 ice-scripts@1.x 在样式加载这块处理的有点问题

**Comment by gooddaddy** [comment]
@imsobear 
是的。目前我项目都升级到2.0了，之前Progress控件样色丢失的问题就好了，不需要主动
import '@alifd/next/lib/progress/style'
。在1.0中我还遇到一个奇怪的问题，npm run start 运行起来样色是好的，npm run build有些样色就丢失了（没有拆包的项目从来没出现过这些样色丢失的问题）。

**Comment by imsobear** [comment]
关联问题：https://github.com/alibaba/ice/issues/1921#issuecomment-494641018
