### ISSUE TITLE
Macpro打开飞冰，飞冰页面一片空白

### ISSUE THREAD

**Issue by guoxunbo** [alibaba/ice#2146]
1. 出现如下空白
![image](https://user-images.githubusercontent.com/14329149/59330954-62a81600-8d25-11e9-857f-48543cc07b28.png)
2. 查看了开发者日志发现是因为我吧一个项目的文件夹移动了地方，导致他找不到这个package.json。就会这样
3. 想问下有何办法可以避免这个问题。现在只能卸载重新下载。
4. 因为内部项目braches经过一次重大升级，client代码的路径不一样了。这就很恶心了。git上切一下branches就会出现如下这个问题。
render.log日志贴图如下：
![image](https://user-images.githubusercontent.com/14329149/59331221-f8dc3c00-8d25-11e9-8811-093b2f06ac7b.png)

**Comment by chenbin92** [comment]
有重复的 issue： https://github.com/alibaba/ice/issues/2117
