### ISSUE TITLE
编辑器打开出错

### ISSUE THREAD

**Issue by wzguo** [alibaba/ice#215]
如下图所示：

![snipaste_20180307_092951](https://user-images.githubusercontent.com/8574644/37068533-2c278db0-21ea-11e8-97a9-637da4cb615a.jpg)
![snipaste_20180307_092927](https://user-images.githubusercontent.com/8574644/37068534-2e110cb4-21ea-11e8-8cb7-1983b784b04d.jpg)

**Comment by noyobo** [comment]
windows 下根据注册表信息查询系统已安装的软件。

麻烦看下  `HKEY_CLASSES_ROOT/Applications/webstorm.exe/shell/open/command`   建是否存在

**Comment by wzguo** [comment]
找了，没发现，莫非我安装WebStorm的姿势不对？

**Comment by yujiangshui** [comment]
需要再查下。你这边 WebStorm 就是按照官网下载的安装的吗？什么系统和版本？

**Comment by wzguo** [comment]
@yujiangshui  WebStorm  版本是 2017.3.2，官网下载的，OS: win 7 专业版

**Comment by wzguo** [comment]
@yujiangshui 我一直用WebStorm，只要有新版本发布就升级，估计是升级的时候自动把注册表的键给删除了。

**Comment by yujiangshui** [comment]
@wzguo 收到，我们看下社区上有没有兼容方案之类的，感谢反馈

**Comment by noyobo** [comment]
@wzguo  可以在注册表 计算机 根节点上搜索  webstorm.exe 看看是不是有其他位置的注册表信息。

**Comment by wzguo** [comment]
@noyobo 搜了，没有，而且我装了Jetbrans 家的 IDEA，注册表也没有，但 GoLand 和 DataGrip有。
![snipaste_20180309_174818](https://user-images.githubusercontent.com/8574644/37201257-1de7a59e-23c2-11e8-8173-276c944ca73c.jpg)
![snipaste_20180309_174830](https://user-images.githubusercontent.com/8574644/37201258-1e26d534-23c2-11e8-8815-5306422ed789.jpg)

**Comment by kill33** [comment]
vs code 同样打不开
注册表没有这一项

**Comment by noyobo** [comment]
2.6.0 版本通过设置 编辑器启动脚本   例如 `subl ${cwd}`
