### ISSUE TITLE
[架构] PRO 目录结构

### ISSUE THREAD

**Issue by boiawang** [alibaba/ice#2164]

**Comment by temper357** [comment]
### 目录结构
```markdown
├── mock/                    # 本地模拟数据
├── public/                  # 静态文件，build时直接输出到根目录
│   ├── index.html           # HTML文件
│   └── favicon.png          # Favicon
├── src/
│   ├── components/          # 业务组件与区块
│   ├── layouts/             # 页面布局
│   ├── pages/               # 业务页面
│   │   ├── components/      # 模块
│   │   ├── index.js         # 入口文件
│   │   └── index.module.sass# css modules样式
│   ├── config/              # 配置信息  // iceworks 2.x先不改，平铺
│   │   ├── api.js           # 数据源配置
│   │   ├── router.js        # 路由配置
│   │   └── menu.js          # 导航菜单配置
│   ├── stores/              # 全局状态管理
│   ├── locales/             # 国际化资源
│   ├── utils/               # 工具库
│   │   └── request.js       # 通用的数据源请求方法
│   └── index.js             # 入口JS
├── tests/                   # 测试工具
├── ice.config.js            # 项目配置，包含插件配置及自定义webpack配置等
├── README.md
└── package.json
```

### 数据源请求逻辑
 1. 在config/api.js中全局定义所有用到的api接口，遵循的协议如下:
```javascript
// config/api.js
export default {
  "getList": {
    "type": "json",              // 异步请求类型(ajax、jsonp)
    "url": "/list/get",          // 线上url
    "method": "GET",             // http method
    "isCors": true,              // 是否支持跨域,对应credentials = 'include'
    "timeout": 5000,             // 超时时间单位ms
    ...                          // 其他同级参数
  }
}
```
2. utils中提供request方法，封装通用的接口请求方法
```javascript
// utils/request.js

// 本地调试时需要自定义域名时设置
// axios.baseUrl = '//xxxx.taobao.com';

export default function request(opts) {
  const {type, url, ...params} = opts;
  if (opts.type === 'ajax') {
    axios({
      url: opts.url, // 本地调试时默认走mock
      ...params
    });
  } else {
     ...
  }
}
```

**Comment by yuanyan** [comment]
数据源配置 config/api.js  -> config/data.js or source.js

**Comment by chenbin92** [comment]
index.module.sass# css modules样式  -> index.module.scss

**Comment by imsobear** [comment]
- 数据源配置名称可以再讨论下，我觉得这几个里面 api.js 更好一点
- 建议 router.js -> routes.js 
- 昨天试着写了下 router，逻辑还挺长的，可能还是需要搞个 src/router.jsx
- 建议 增加一个 src/global.scss 的文件

**Comment by boiawang** [comment]
@chenbin92 page 下的 components 是针对当前 page 独有的组件，src 的 components 是整个项目的组件，还是好理解没有歧义的

**Comment by chenbin92** [comment]
> @chenbin92 page 下的 components 是针对当前 page 独有的组件，src 的 components 是整个项目的组件，还是好理解没有歧义的

看下面的截图，组件和模块的概念应该不是对等的。还有区块和组件也不是对等的，各自的定位都不一样

![image](https://user-images.githubusercontent.com/3995814/59601637-316d8280-9137-11e9-80c7-59673915dd4f.png)

**Comment by boiawang** [comment]
> > @chenbin92 page 下的 components 是针对当前 page 独有的组件，src 的 components 是整个项目的组件，还是好理解没有歧义的
> 
> 看下面的截图，组件和模块的概念应该不是对等的。还有区块和组件也不是对等的，各自的定位都不一样
> 
> ![image](https://user-images.githubusercontent.com/3995814/59601637-316d8280-9137-11e9-80c7-59673915dd4f.png)

为啥上面 component 是业务组件与区块，下面 component 就是模块了？区块和模块有什么区别?

**Comment by imsobear** [comment]
项目目录里的 components 统一成自定义组件的概念？这里没必要引入区块，区块下载到项目里就变成自定义组件了我理解

**Comment by chenbin92** [comment]
> > > @chenbin92 page 下的 components 是针对当前 page 独有的组件，src 的 components 是整个项目的组件，还是好理解没有歧义的
> > 
> > 
> > 看下面的截图，组件和模块的概念应该不是对等的。还有区块和组件也不是对等的，各自的定位都不一样
> > ![image](https://user-images.githubusercontent.com/3995814/59601637-316d8280-9137-11e9-80c7-59673915dd4f.png)
> 
> 为啥上面 component 是业务组件与区块，下面 component 就是模块了？区块和模块有什么区别?

截图是最上面 @站稳 写的，所以我有歧义，看看上下文吧

**Comment by chenbin92** [comment]
> 项目目录里的 components 统一成自定义组件的概念？这里没必要引入区块，区块下载到项目里就变成自定义组件了我理解

+1  不建议在项目引出模块和区块的概念

* `src/components`:  项目级别的公共组件
* `src/pages/components`:  页面级别的公共组件
