### ISSUE TITLE
点击任意区块报编译错误

### ISSUE THREAD

**Issue by yydmss** [alibaba/ice#217]
点击任意区块，直接报编译错误
抱歉, 编译错误: @icedesign/real-time-statistics-block/src/index.js, 麻烦提交 issue 等待修复
----------
Console：
Unhandled promise rejection 
Object { __promise_pendings: [], __promise_progress_listeners: [], __promise_status: "Pending", defer: {…}, userConfig: {…}, responseData: null, config: {…}, timeoutTimer: null, responseText: "", responseXML: null, … }

**Comment by noyobo** [comment]
是点击区块的预览功能吗？

**Comment by yydmss** [comment]
对的亲~

**Comment by yujiangshui** [comment]
@wssgcg1213 关注下
