### ISSUE TITLE
RFC: 前端直接调用 Adapter

### ISSUE THREAD

**Issue by alvinhui** [alibaba/ice#2175]
## 问题

1. Adapter 事件的重复监听；
2. 前端调用 Adapter 链路过长。

下面是详细解释。

### 问题一

目前 Adapter 发送的事件会在 Controller 被监听，再由 Controller 通过 socket 转发到前端。

该中转环节不必要，且造成了重复监听。

示例代码：

```javascript
// 某个 Adapter 模块
class DependencyModule extends Event implements IModule {
  install(params) {
    this.emit('foo', foo);
  }
}

// 控制器
class DependencyController {
  async install({ args, socket }) {
    const { projectManager } = app;
    const project = projectManager.getCurrent();

    project.dependency.on('foo', (data) => { // 重复监听！！！
      socket.emit('project.dependency.foo', data); 
    });
    return await project.dependency.install(args);
  }
};
```

### 问题二

目前一个请求的调用从前端到 Adapter 要经历以下几个阶段：

|-----------------------------------------------------------|
|   view -> store -> socket -> router -> controller -> adapter   |
|-----------------------------------------------------------|

具体以依赖安装为例：

```javascript
// view
async onInstall() {
  await dependencyStore.install();
}

// store
export default {
  async install() {
    socket.emit('project.dependency.install');
  }
}

// router
['project.dependency.install', project.dependency.install]

// controller
class DependencyController {
  async install() {
    const { projectManager } = app;
    const project = projectManager.getCurrent();
    return await project.dependency.install();
  }
};

// adapter
class DependencyModule implements IModule {
  install() {
    // do something...
  }
}
```

**其中 router 和 controller 环节是不必要的，它的存在还会对未来拓展 Adapter 造成束缚。**
更好的方式是前端能够直接调用到 Adapter 的能力，即：

|------------------------------------|
| view -> store -> socket -> adapter |
|------------------------------------|

### 问题一

统一从 Adapter 直接发送 socket 事件。

Adapter.Module.Method 统一入参为：params, context，从 context 获取 socket 来发送消息。

```typescript
interface IContext {
  socket: ISocket;
}

interface Module {
  method: (params: any, context: IContext);
}
```

所有的 method 都会收到 content，在 method 内主动调用 socket.emit。

以问题一的示例代码为例，可改造为：

```javascript
// 某个模块
class DependencyModule implements IModule {
  install(params, context) {
    context.socket.emit('project.dependency.foo', data);
  }
}

// 控制器内
class DependencyController {
  async install(ctx) {
    const { args, socket } = ctx;
    const { projectManager } = app;
    const project = projectManager.getCurrent();
    return await project.dependency.install(args, ctx);
  }
};
```

### 问题二

通过 socket 的 middleware 进行拦截，根据事件名直接调用 Adapter。

```javascript
return async (ctx, next) => {
  const { packet } = ctx;
  const [ eventName, args, callback ] = packet;
  const [ namespace, moduleName, methodName ] = eventName.split('.');

  if (namespace === 'project') {
    const { projectManager } = app;
    const project = projectManager.getCurrent();
    callback(null, await project[moduleName][methodName](args, ctx));
  }

  await next();
};
```

**Comment by chenbin92** [comment]
方案没问题

1. 我理解问题一和问题二在本质上是一个问题：抛弃掉现在 Controller 层，通过 router 直接调用 adapter 的方法
2. 我觉得这个属于功能完成之后的代码重构优化部分，可以先保证现有功能的完成，然后在统一处理，包括之前提到 adapter 的目录改造，utils 问题

**Comment by Orange-C** [comment]
>``` js
>if (namespace === 'project') {
>    const { projectManager } = app;
>    const project = projectManager.getCurrent();
>    callback(null, await project[moduleName][methodName](args, ctx));
>  }
>```

这段代码每个namespace逻辑都一样吗？一样的话可以再抽象一下，不一样的话，不如每个namespace独自做一个router来的清晰，免得middleware里面有太多逻辑。

**Comment by alvinhui** [comment]
> > ```js
> > if (namespace === 'project') {
> >    const { projectManager } = app;
> >    const project = projectManager.getCurrent();
> >    callback(null, await project[moduleName][methodName](args, ctx));
> >  }
> > ```
> 
> 这段代码每个namespace逻辑都一样吗？一样的话可以再抽象一下，不一样的话，不如每个namespace独自做一个router来的清晰，免得middleware里面有太多逻辑。

这里只会有 `project` 这个 namespace，这个 middleware 只拦截 project

**Comment by alvinhui** [comment]
> 方案没问题
> 
> 1. 我理解问题一和问题二在本质上是一个问题：抛弃掉现在 Controller 层，通过 router 直接调用 adapter 的方法
> 2. 我觉得这个属于功能完成之后的代码重构优化部分，可以先保证现有功能的完成，然后在统一处理，包括之前提到 adapter 的目录改造，utils 问题

我觉得全局设置、导航、面板设置这三个 PR 合并后就可以做这个事情。
同时不包含目录改造，以免带来太多负担。

**Comment by imsobear** [comment]
> > > ```js
> > > if (namespace === 'project') {
> > >    const { projectManager } = app;
> > >    const project = projectManager.getCurrent();
> > >    callback(null, await project[moduleName][methodName](args, ctx));
> > >  }
> > > ```
> > 
> > 
> > 这段代码每个namespace逻辑都一样吗？一样的话可以再抽象一下，不一样的话，不如每个namespace独自做一个router来的清晰，免得middleware里面有太多逻辑。
> 
> 这里只会有 `project` 这个 namespace，这个 middleware 只拦截 project

我也觉得通过路由做更合理一些（中间件不适合做这个事情）。然后这块其实就是我刚开始说的类 rpc 方式，只有一个路由，前端通过 service 方式调用：

```js
// router
['adapter.service', adapterService.call]

// controller/adapterService.js
exports function call(ctx) {
  const {
    serviceName,
    params
  } = ctx.query;

  // get adapter
  const adapter = getCurrentAdaper();
  
  const result = await adapter[serviceName](params);
  
  this.body = {
    status: 'success',
    data: result,
  };
}
```

**Comment by chenbin92** [comment]
> > > > ```js
> > > > if (namespace === 'project') {
> > > >    const { projectManager } = app;
> > > >    const project = projectManager.getCurrent();
> > > >    callback(null, await project[moduleName][methodName](args, ctx));
> > > >  }
> > > > ```
> > > 
> > > 
> > > 这段代码每个namespace逻辑都一样吗？一样的话可以再抽象一下，不一样的话，不如每个namespace独自做一个router来的清晰，免得middleware里面有太多逻辑。
> > 
> > 
> > 这里只会有 `project` 这个 namespace，这个 middleware 只拦截 project
> 
> 我也觉得通过路由做更合理一些（中间件不适合做这个事情）。然后这块其实就是我刚开始说的类 rpc 方式，只有一个路由，前端通过 service 方式调用：
> 
> ```js
> // router
> ['adapter.service', adapterService.call]
> 
> // controller/adapterService.js
> exports function call(ctx) {
>   const {
>     serviceName,
>     params
>   } = ctx.query;
> 
>   // get adapter
>   const adapter = getCurrentAdaper();
>   
>   const result = await adapter[serviceName](params);
>   
>   this.body = {
>     status: 'success',
>     data: result,
>   };
> }
> ```

之前还有 Service 的概念，Service 那一层已经被干掉了，现在实际开发中发现 Controller 这一层基本是重复的代码很多余，确实可以通过一个 router 直接调用当前的 Adapter 类的方法。在想一个路由会不会太抽象，目前 iceworks 分了四大块：项目，工程，物料，设置，其中只有 「项目」和「工程」是需要在 adapter 实现的，以后也许会扩展，所以我觉得是不是以 namespace 的方式做路由会比较好，在调用和代码本身维护时也比较好区分

**Comment by imsobear** [comment]
service 只是一个概念，本质上就是分发下方法，这块 namespace 是指 `project/router` 这种吗？是的话我觉得每个 namespace 都要定义一个路由也挺繁琐的，要增加一个 namespace 都要改代码，不方便扩展，所以我建议直接把 adapter 作为 namespace 即可。 @chenbin92

**Comment by chenbin92** [comment]
@imsobear  伪代码如下：主要是想做下 namespace 的隔离和分层，在前端调用的时候 adapter 下不会直接挂载一堆的方法
```js
// router
['adapter.project.service', adapterService.project]
['adapter.task.service', adapterService.task]
['adapter.xxx.service', adapterService.xxx]

// controller/adapterService.js
// 与上面一样
```

> 是的话我觉得每个 namespace 都要定义一个路由也挺繁琐的，要增加一个 namespace 都要改代码，不方便扩展

目前来看也就 2 个 task 和 project，后面应该会扩展，但是扩展的前提也是需求前端先注册好顶级路由，就是那几个 左侧的 Tab 功能，所有也不会繁琐的

**Comment by Orange-C** [comment]
> > ```js
> > if (namespace === 'project') {
> >    const { projectManager } = app;
> >    const project = projectManager.getCurrent();
> >    callback(null, await project[moduleName][methodName](args, ctx));
> >  }
> > ```
> 
> 这段代码每个namespace逻辑都一样吗？一样的话可以再抽象一下，不一样的话，不如每个namespace独自做一个router来的清晰，免得middleware里面有太多逻辑。

我的看法是，如果在分发那一层每个namespace没有特殊逻辑的话，那就合并成一个分发的router，这样比较简洁，也好扩展。本身逻辑底层都是分开，不需要在分发的地方再做一次隔离。

如果要在分发层做特殊逻辑，路由的优势才比较明显。这也是我这个问题的初衷

**Comment by alvinhui** [comment]
现在的争议点：

- 用中间件还是用控制器；
- 怎样划分命名空间。

**Comment by alvinhui** [comment]
## 当前情况

Iceworks 中前后端通信包含 2 个方面内容：

- 调用全局的 API，如：
    - 获取全局设置：`home.setting.getLocale`
    - 保存全局设置：`home.setting.setLocale`
    - 获取物料信息：`material.index.resource`
- 调用适配器的 API：
    - 创建页面：`project.page.create`
    - 执行命令：`project.task.start`

当前前端请求后端 API 的方式：

`socket.emit('API')`

## 可行方案

@imsobear 

```javascript
// router
['adapter.service', adapterService.call]

// controller/adapterService.js
exports function call(ctx) {
  const {
    moduleName,
    methodName,
    params,
  } = ctx.query;

  const adapter = getCurrentAdaper();
  return await adapter[moduleName][methodName](params);
}
```
这样设计的话，前端请求需要怎么封装？

伪代码：

```javascript
// 调用 adapter
socket.emit('adapter.service', {moduleName: 'page', methodName: 'create', params});

// 调用其他
socket.emit('home.setting.setLocale',  params);
```

@alvinhui 

在中间件对 `adapter` 的命名空间进行拦截，然后调用 adapter。

前端调用方式不变。

**Comment by chenbin92** [comment]
## 结论

1.  根据模块保留 namespace 命名空间，在中间件对 adapter 的命名空间进行拦截，统一挂载到 adapter 模块下


**中间件核心实现**

```js
// https://github.com/alibaba/ice/pull/2192/files#diff-a9b3ae39187370f2ea02cb5ea5742854R1
await project.adapter[moduleName][methodName](args, ctx));
```

**前端调用方式**

```js
await socket.emit('adapter.page.getAll');
```

2. iceworks 内置通用逻辑保留之前的路由机制，代码如下

```
const routers: [string, () => {}][] = [
    ['home.project.list', home.project.list],
    ['home.project.create', home.project.create],
 
    ['material.index.add', material.index.add],
    ['material.index.delete', material.index.delete],

    ['home.setting.setLocale', home.setting.setLocale],
    ['home.setting.getLocale', home.setting.getLocale],
  ];
```
