### ISSUE TITLE
添加物料

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#2178]
- [x] 添加物料时名称是必填的，但是没有给输入框让用户填写名称

![screenshot](https://img.alicdn.com/tfs/TB1suf9afBj_uVjSZFpXXc0SXXa-1768-1290.png)

- [x] 物料数据截图没有做检验，前端也没有做容错
![image](https://user-images.githubusercontent.com/3995814/59579548-f13edd80-90ff-11e9-8297-4e0503e459bb.png)

- [x]  物料没有截图时，UI 需要兼容
![image](https://user-images.githubusercontent.com/3995814/59579579-1e8b8b80-9100-11e9-88b1-b6924f35fb0b.png)

- [x] 没有数据时也需要做兼容的处理
![image](https://user-images.githubusercontent.com/3995814/59579644-67434480-9100-11e9-8fec-8914e4f50622.png)

- [x] 物料省略了但是并没有其他地方能看到完整的信息，建议给出 Tooltip 的形式展示完全
![image](https://user-images.githubusercontent.com/3995814/59579654-76c28d80-9100-11e9-9815-c41bac05024e.png)

**Comment by DoranYun** [comment]
1. name 现在的逻辑是直接取物料 json 的 name 字段，这个报错是因为 物料数据缺少 name 字段导致；

5. tooltip 方式太重了，而且在切换物料时候非常容易误触，侧边栏不建议展示 description，或者可以移到右侧 panel 里

**Comment by DoranYun** [comment]
fixed.
