### ISSUE TITLE
[ice-devtools] 选择不接入设计系统时,仍然生成adaptor

### ISSUE THREAD

**Issue by tao1991123** [alibaba/ice#2184]
ice-devtools@2.3.3

![](https://img.alicdn.com/tfs/TB11gMmc.uF3KVjSZK9XXbVtXXa-1506-680.jpg)
![](https://img.alicdn.com/tfs/TB1pLonc7WE3KVjSZSyXXXocXXa-1802-884.jpg)

**Comment by tao1991123** [comment]
选择No的时候 应该不生成adaptor相关的文件

**Comment by ClarkXia** [comment]
ice-devtools@2.4.0 已修复
