### ISSUE TITLE
物料的工程依赖简化

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#2187]
## 背景

物料源里区块/业务组件每个包都要安装 ice-scripts 以及插件依赖，都要配置 ice.config.js，改起来很麻烦

## 方案

- ice-scripts 以及 plugin 依赖放到物料仓库根目录，同时新增 ice.block.config.js, ice.component.config.js
- 单个区块或者业务组件的 start 命令改为：`../../node_modules/.bin/ice-scripts dev --config ../../ice.block.config.js`

## 解释

- 模板的工程依赖和 ice.config.js 在生成项目时要用，因此不能这么玩，区块和业务组件不存在这个问题

## TODO

- ice-scripts 支持 --config 指定配置文件 #2188 
- 物料模板改造：
  - 单个物料初始化要做特殊处理，补全工程依赖和配置文件
  - vue-cli 应该也支持这种能力

**Comment by ClarkXia** [comment]
--config +1，命令的修改有点感觉像全局安装的变种...

**Comment by chenbin92** [comment]
单个区块或者业务组件的 start 命令改为：../../node_modules/.bin/ice-scripts dev --config ../../ice.block.config.js

这里的 「单个」是指不在物料仓库的当个区块吗？看后面的执行命令也不是？

#### 场景一
是指物料仓库跟目录下的 package.json 依赖一个 ice-scripts，然后在跟目录下配置一个 ice.block.config.js，然后在每个区块或者组件里面以相对路径的形式启动？

#### 场景二

当个组件开发呢，需要怎么配置？

#### 场景三

可以考虑支持 `ice-scripts dev --config <npmPackage>` 的形式

**Comment by imsobear** [comment]
- 场景一 是的，我说的就是这个
- 场景二 单个开发还是按照现在的自己依赖 ice-scripts 以及配置 ice.config
- 场景三 没必要这么彻底，两种方式：
  1. `ice-scripts dev --config <npmPackage>/index.js`
  2. ice.config.js 内容 `module.exports = require('<npmPackage>');`

**Comment by chenbin92** [comment]
> * 场景一 是的，我说的就是这个
> * 场景二 单个开发还是按照现在的自己依赖 ice-scripts 以及配置 ice.config
> * 场景三 没必要这么彻底，两种方式：
>   
>   1. `ice-scripts dev --config <npmPackage>/index.js`
>   2. ice.config.js 内容 `module.exports = require('<npmPackage>');`

没歧义，考虑到一个物料仓库的形式，比如官方仓库，每个区块和组件都依赖 ice-scripts，那是件多蛋疼的事情

**Comment by imsobear** [comment]
- react-materials 已按照这个思路改造，谢谢牛逼的 ice-scripts 🐮
- 物料模板就不改了（考虑到改了之后需要特殊处理单个物料的初始化逻辑），用户物料多了参考这个 issue 自己优化就可以
