### ISSUE TITLE
点击预览模板报错

### ISSUE THREAD

**Issue by daix6** [alibaba/ice#219]
![image](https://user-images.githubusercontent.com/8535971/37071110-e98218c0-21f5-11e8-808c-c3abf09db4f7.png)

系统：Windows 7
Ice：1.0.1

**Comment by wssgcg1213** [comment]
homepage 字段没有了吗 @chenbin92

**Comment by chenbin92** [comment]
@wssgcg1213  有 [homepage](https://github.com/alibaba/ice/blob/master/scaffolds/ice-design-pro/package.json#L5) 字段

**Comment by daix6** [comment]
@chenbin92 怎样重启？我关掉重开是还是报一样的错~

**Comment by wssgcg1213** [comment]
iceworks 做一下兼容, 不报错 

homepage 字段兜底拼接规则: 

`https://alibaba.github.io/ice/scaffold-preview/${name}.html`

**Comment by chenbin92** [comment]
@daix6   数据正常情况下模板界面应该类似下面这样的，截一下的 iceworks 模板界面的截图看看

![image](https://user-images.githubusercontent.com/3995814/37077457-0bb88e0e-2216-11e8-8f63-debdca2e5538.png)

**Comment by daix6** [comment]
![image](https://user-images.githubusercontent.com/8535971/37140247-08ecd884-22ec-11e8-9cbd-d3c94ff54d20.png)

重启无效

**Comment by yujiangshui** [comment]
fixed

**Comment by daix6** [comment]
恩恩，现在可以预览了~
