### ISSUE TITLE
Iceworks在新建页面时，提示get-tarball-info-error等错误信息

### ISSUE THREAD

**Issue by LoLDragon** [alibaba/ice#2204]
## 问题描述
在内网（研发网络中,但是下载模板工程是正常的）只有新建页面时出现以下截图错误。实际上区块代码已下载到工程中，就是依赖相关的路由等没有加入工程中。npm start由于依赖确实会失败。经验证，在家里网络是可以正常新建页面时正常的。故猜测是网络申请这边有缺失导致，但是目前不清楚具体的那些域名有问题。附上已经申请的网络域名：

![image](https://user-images.githubusercontent.com/19163371/59733877-f0ce5000-9281-11e9-9a5b-08f57888f237.png)

Iceworks版本：2.21.0
设置页面：
![image](https://user-images.githubusercontent.com/19163371/59734396-e1500680-9283-11e9-95a5-8e0bb997d57f.png)

设置npm源为淘宝，测试结果也是一样的。

## 错误信息
1.get-tarball-info-error 错误提示
![image](https://user-images.githubusercontent.com/19163371/59733637-27579b00-9281-11e9-9297-afe2a172a5a2.png)
![image](https://user-images.githubusercontent.com/19163371/59733658-3c342e80-9281-11e9-8ed7-d1e0cc1ee9a1.png)

2.获取当前区块的依赖失败
![image](https://user-images.githubusercontent.com/19163371/59733815-bd8bc100-9281-11e9-8c4b-31a807edefa8.png)
![image](https://user-images.githubusercontent.com/19163371/59733842-d4321800-9281-11e9-92c8-d1b1cf7bed9d.png)
![image](https://user-images.githubusercontent.com/19163371/59734301-88806e00-9283-11e9-8fb9-a254cec556b7.png)

3.在下载私有npm 区块时，提示的get-tarball-info-error错误时。
![image](https://user-images.githubusercontent.com/19163371/59734149-df397800-9282-11e9-8d1b-044d825ae3d1.png)

4.解压区块失败
![image](https://user-images.githubusercontent.com/19163371/59734687-042eea80-9285-11e9-9e69-2b4eef41e4dc.png)
偶现，目前未获取到有效log日志

**Comment by LoLDragon** [comment]
@imsobear

**Comment by chenbin92** [comment]
@LoLDragon 更新一下 2.22.0 版本
