### ISSUE TITLE
[工程] Task adapter 需提供一个 get dev api，路由面板可以拿这个 host+port 拼链接

### ISSUE THREAD

**Issue by boiawang** [alibaba/ice#2209]
路由面板的每一条路由支持跳转，需要从 Task 中获取到 host 和 port

![image](https://user-images.githubusercontent.com/6340730/59745128-af9c6700-92a6-11e9-84ea-1caef4ff94b4.png)

**Comment by chenbin92** [comment]
后续作为功能进行支持
