### ISSUE TITLE
mac下创建项目时部分情况下点击浏览无法打开文件选择框

### ISSUE THREAD

**Issue by BinShaw** [alibaba/ice#221]
mac下使用模板创建项目时部分情况下点击浏览无法打开文件选择框，必须重启才能打开。
复现方式：当选择一个非空目录创建项目时，会提示当前目录已存在文件的confirm，点击确认，然后再重新点击浏览选择目录时打不开文件选择框，目前我这里是100%复现

**Comment by noyobo** [comment]
收到，我这边排查下。

**Comment by noyobo** [comment]
v1.0.2 修复
