### ISSUE TITLE
[iceworks]RFC: 完善lint检查，接入开发流程

### ISSUE THREAD

**Issue by Orange-C** [alibaba/ice#2217]
主要是iceworks-server和iceworks-client两个包的代码检查

## 检查工具
1. 统一代码检查规则（社区方案+部分自定义配置）
2. 统一检查工具为eslint

## 开发流程接入
1. 在pre-commit阶段加入lint检查
2. 在GitHub PR的CI中加入lint检查

### 为什么不用tslint
tslint后续会被废弃，并入eslint，详见[tslint说明](https://github.com/palantir/tslint)
![image](https://user-images.githubusercontent.com/8469262/59760071-049aa600-92c4-11e9-8557-e5250c888f6e.png)

### 为什么是pre-commit而不是pre-push
1. pre-push阶段再做检查容易导致会有很多修正代码风格的多余commit
2. pre-commit阶段检查约束性更强容易形成统一的代码规范

## 总结
这个task并不影响3.0的开发，所以不与3.0的发布强关联，会多花点时间来得出统一的代码规则，以免未来频繁修改

**Comment by chenbin92** [comment]
> 在pre-commit阶段加入lint检查
> 在GitHub PR的CI中加入lint检查

1. iceworks-client 的 lint 规则是有的，现在是放在 CI 检查的，之前提议过在 pre-commit 阶段去做检查，当时讨论的结论 commit 检查比较费时间，所有没加，直接在 CI 上面加效果是一样的，CI 没过不会合并 MR
2. 根据昨天群里的讨论，后面这个 alibaba/ice 仓库之后包含 iceworks 的代码，可以等其他diam迁移出去在一起看下，pro-commit 还是 CI 阶段检查，应该是只要一处就可以了

**Comment by Orange-C** [comment]
> 1. iceworks-client 的 lint 规则是有的，现在是放在 CI 检查的，之前提议过在 pre-commit 阶段去做检查，当时讨论的结论 commit 检查比较费时间，所有没加，直接在 CI 上面加效果是一样的，CI 没过不会合并 MR
> 2. 根据昨天群里的讨论，后面这个 alibaba/ice 仓库之后包含 iceworks 的代码，可以等其他diam迁移出去在一起看下，pro-commit 还是 CI 阶段检查，应该是只要一处就可以了

@chenbin92 
pre-commit检查和云端CI检查不能同一而论，因为代码在本地是不可控，pre-commit检查在本地只需要一点改动就可以被用户禁用掉，所以在云端提交的时候必须有CI去进行第二次检查。这个规则并不只是给我们自己开发使用，要考虑到社区贡献时保证社区代码的质量。

举个类似的case，前端的表单需要做校验，但不意味着前端做了校验，后端接口就可以不再校验了。本地和云端校验都是有必要的。

再者每个commit都是**有具体意义的**，所以commit本来就不应该是个高频行为，所以在效率降低方面我认为不会有很大的影响。

**Comment by chenbin92** [comment]
> 再者每个commit都是有具体意义的，所以commit本来就不应该是个高频行为，所以在效率降低方面我认为不会有很大的影响。

1. 上面说了代码迁移出去之后，pre-commit 不会有影响了
2. commit 不应该是个高频行为，这个是基本规范，但是不是因为你加了 pre-commit 做 eslint 检查就能限制开发者的 commit 行为，这个前因后果不成立

你举例的 case +1

**Comment by Orange-C** [comment]
@chenbin92 
这两个东西我是这么理解的
1. CI用于强约束项目合并所有代码要求有个规范，是一个底线检查
2. pre-commit用于辅助我们形成更好的代码提交习惯，即每一个commit的代码都必须符合代码规范，这的确是一个附加的提议。
3. 如果不支持pre-commit，但至少pre-push阶段要有一次检查，如果每次都要等CI结果出来才意识到lint问题，这样是比较影响效率的，PR在提出的时候应该就是一个待review的状态。所以在提交PR前应该至少有一次lint检查。

**Comment by imsobear** [comment]
不赞成 pre-commit，因为比较影响效率，本质是为了卡口，我认为 CI 就够了。

**Comment by ChrisCindy** [comment]
1. 个人感觉 commit 应该是一个高频行为，应该尽可能把每处代码改动细粒度化，这样才有便于后期排查 bug 等。
2. 因为 eslint 相对耗时，如果 pre-commit 阶段进行检查，很容易让开发人员厌恶 commit，导致大把的代码改动浓缩在一个或某几个 commit 中，得不偿失。个人建议在 pre-push 阶段进行 eslint 检查，保证每个人提交上去的代码都是合乎规范的。用 CI 做检查流程对开发人员和执行代码合并的人员确实略有些繁琐。
