### ISSUE TITLE
新建页面 因缺少依赖抛异常

### ISSUE THREAD

**Issue by chenhongen** [alibaba/ice#223]
新建页面后报错如下：
ERROR in ./src/pages/VisualFileTable1/components/ComplexTabTable/ComplexTabTable.jsx
Module not found: Error: Can't resolve '@icedesign/data-binder' in 'E:\201803\ice-design-cms\src\pages\VisualFileTable1\components\ComplexTabTable'
 @ ./src/pages/VisualFileTable1/components/ComplexTabTable/ComplexTabTable.jsx 34:0-48
 @ ./src/pages/VisualFileTable1/components/ComplexTabTable/index.js
 @ ./src/pages/VisualFileTable1/VisualFileTable1.jsx
 @ ./src/pages/VisualFileTable1/index.js
 @ ./src/routes.jsx
 @ ./src/index.js
 @ multi ./node_modules/react-dev-utils/webpackHotDevClient.js ./src/index.js

ERROR in ./src/pages/VisualFileTable1/components/ComplexTabTable/ComplexTabTable.jsx
Module not found: Error: Can't resolve '@icedesign/label' in 'E:\201803\ice-design-cms\src\pages\VisualFileTable1\components\ComplexTabTable'
 @ ./src/pages/VisualFileTable1/components/ComplexTabTable/ComplexTabTable.jsx 35:0-40
 @ ./src/pages/VisualFileTable1/components/ComplexTabTable/index.js
 @ ./src/pages/VisualFileTable1/VisualFileTable1.jsx
 @ ./src/pages/VisualFileTable1/index.js
 @ ./src/routes.jsx
 @ ./src/index.js
 @ multi ./node_modules/react-dev-utils/webpackHotDevClient.js ./src/index.js
Failed to compile.

-----
需手动添加相关依赖：npm install @icedesign/label
希望改进为自动添加，且依赖安装过程中没有loading画面/进度条，希望添加[比心]

**Comment by wssgcg1213** [comment]
依赖自动安装其实是有的, 应该是bug, 我们排查下   

目前遇到的话麻烦你暂时手动处理下依赖, 有进展会在下面回复~

**Comment by yujiangshui** [comment]
麻烦升级 1.0.2 版本后再次尝试，安装依赖这块已经修复。如有问题再反馈。
