### ISSUE TITLE
同时使用飞冰和antd的组件会产生冲突

### ISSUE THREAD

**Issue by YuFF2018** [alibaba/ice#2236]
## 问题描述
同时使用飞冰和antd的组件会产生冲突

**Comment by boiawang** [comment]
@YuFF2018 指的是样式冲突吗？我们这边也不推荐 ice 和 antd 共用。

**Comment by YuFF2018** [comment]
> @YuFF2018 指的是样式冲突吗？我们这边也不推荐 ice 和 antd 共用。

是的，样式冲突，项目直接挂掉了。感谢回复

**Comment by imsobear** [comment]
请补全下信息，截图、日志、自己的工程配置等

**Comment by imsobear** [comment]
问题描述不全，先关掉了，补全后自行 reopen 下。
