### ISSUE TITLE
npm run deploy报错

### ISSUE THREAD

**Issue by Jack-rainbow** [alibaba/ice#2242]
## 问题描述(VUE区块)
npm run deploy构建区块失败

## 错误信息log
![image](https://user-images.githubusercontent.com/20368037/59975298-70914d00-95e9-11e9-96d2-7c35c9d71864.png)

## 版本信息
npm@6.4.1
node@v10.15.3
ice-devtools@2.2.3
win10  家庭版

#  根目录package.json
![image](https://user-images.githubusercontent.com/20368037/59975458-4c823b80-95ea-11e9-9088-376cead75cdf.png)

#  期望结果
解决问题，vue区块成功发布

**Comment by DoranYun** [comment]
vue 的物料不支持发布到 fusion，先执行 `npm run generate` 再执行 `npm run sync-unpkg` 发布到unpkg

**Comment by Jack-rainbow** [comment]
好的，已收到。目前已发布到unpkg。谢谢您的指导，期望在大版本更新时，可以支持vue物料到fusion。




------------------ 原始邮件 ------------------
发件人: "Dong Yun"<notifications@github.com>; 
发送时间: 2019年6月24日(星期一) 上午10:17
收件人: "alibaba/ice"<ice@noreply.github.com>; 
抄送: "987709173"<987709173@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [alibaba/ice] npm run deploy报错 (#2242)




vue 的物料不支持发布到 fusion，先执行 npm run generate 再执行 npm run sync-unpkg 发布到unpkg
