### ISSUE TITLE
[研发生态] 状态管理可视化

### ISSUE THREAD

**Issue by temper357** [alibaba/ice#2243]
## 背景
状态管理通常是一个应用中最复杂的部分，涉及状态、数据源、行为之间的各种交互，通过代码进行状态管理还是有不小的复杂度，因此我们希望通过可视化的方式提升状态管理的效率，减少重复代码的书写。

## 目标
打通数据源到状态初始化的链路，基于iceworks可视化管理数据源与状态，自动生成fetch与初始化代码，具体包含以下三个action:  

1. 数据源配置可视化，可自定义mock数据
2. 状态与数据源可关联，自动生成fetch代码
3. 可绑定状态初始化的页面或者组件，自动生成初始化代码插入

### 数据源管理
将数据源配置可视化，同时增加关联mock数据的能力，与本地的dataSourceConfig.js与mock目录实时同步。

#### 原型图
1. 数据源管理Table  
<img src="https://img.alicdn.com/tfs/TB1ZT8bd75E3KVjSZFCXXbuzXXa-1264-422.png" width="500"/>

2. 数据源编辑Dialog  
<img src="https://img.alicdn.com/tfs/TB1ziI9dRWD3KVjSZFsXXcqkpXa-720-848.png" width="300"/>

### 状态管理
基于icestore的多store方案，每个store中的状态可关联数据源及数据源中的data路径，并且可关联初始化的页面和组件。

1. 生成fetch代码
当关联数据源后，自动生成fetchXXXData(XXX为数据源名称)，如果多个状态关联了同一个数据源，合并到一个fetch方法，示例代码如下：

```javascript
// stores/store1.js
import request from '@/utils/request';
import { profile, login } from '@/dataSourceConfig';

export default {
  username: '',
  avatar: '',
  authority: 'guest',

  async fetchProfileData() {
    const { data } = await request(profile);
    this.username = data.name;
    this.avatar = data.avartar;
  }

  async fetchLoginData() {
    const { data } = await request(login);
    this.authority = data.authority;
  }
}
```

2. 生成初始化代码
关联初始化页面/组件后，生成初始化代码并插入到对应页面/组件中，示例代码如下：

```javascript
// layouts/BasicLayout/components/Header
function Header() {
  const store1 = stores.useStore('store1');
  useEffect(() => {
    store1.fetchProfileData();
  });

  ...
}
```
#### 原型图
1. 状态管理Table  
<img src="https://img.alicdn.com/tfs/TB1OLIYcAxz61VjSZFtXXaDSVXa-1356-678.png" width="550"/>

2. 状态编辑Dialog  
<img src="https://img.alicdn.com/tfs/TB1PUNad75E3KVjSZFCXXbuzXXa-706-1322.png" width="300"/>

**Comment by chenbin92** [comment]
1. 数据源可以关联组件吗？组件应该只接收 Props，另外要区分页面 Store 和全局 Store 吗？还是只有一个全局 Store 的概念，页面级别的 Store 都放在全局 Store 里。

![image](https://user-images.githubusercontent.com/3995814/59991276-50a96a00-9679-11e9-80ad-ea4019ce395b.png)

2. 生成的 Store 可以按照关联的页面进行命名
```js
const store1 = stores.useStore('store1'); 

=>

const PageNameStore = stores.useStore('PageNameStore'); 
```


3. 语法小问题
```js
function Header() {
  const store1 = stores.useStore('store1');
  useEffect(() => {
    fetchProfileData();
  });

  ...
}
```


=>

```js
store1.fetchProfileData();
```

**Comment by temper357** [comment]
@chenbin92 
1. 数据源不能关联组件，只与状态发生联系，状态可以关联组件。按照icestore的设计，store允许创建多个，多个store都是全局的，原型中也可以创建多个store的table。
2. store名用户在创建时可以定义
