### ISSUE TITLE
[icestore]useEffect中使用如何卸载？ 

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#2245]
示例代码：

```js
const users = stores.useStore('users');

const { dataSource } = users;

useEffect(() => {
//页面切换时，这里会报错：index.js:2178 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
users.listUsers();
}, []);
```

https://github.com/ice-lab/icestore/issues/11 @yattin

**Comment by boiawang** [comment]
```js
useEffect(() => {
  users.listUsers();
  return () => {
    // ?
    users.destory();
  };
}, []);
```

**Comment by temper357** [comment]
@imsobear 上面引用的这个issue访问不了，应该是很早提的吧，源码里面已经处理过unmount时卸载setState
https://github.com/ice-lab/icestore/blob/master/src/store.ts#L53

**Comment by yattin** [comment]
@temper357 我上周五提的喔，版本也是最新的版本了，一般是重复进入这个路由时，会触发这个 warn

**Comment by temper357** [comment]
@yattin OK，我本地重现一下这个问题

**Comment by yattin** [comment]
https://github.com/ice-lab/icestore/blob/master/src/store.ts#L53

貌似就是这段代码无法保证移除setState，我更换成

`    public useStore(): object {
        const [, setState] = useState();
        useEffect(() => {
            const uid = guid();
            this.map[uid] = setState;
            return () => {
                delete this.map[uid];
            };
        });

        return this.getBindings();
    }
`
这样做了简单测试，WARN就没有出现了

**Comment by temper357** [comment]
@yattin 0.1.4版本已修复此问题，可以验证下
