### ISSUE TITLE
React 物料模板统一升级 Kit 3.x

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#2250]
## 名词解释

icekit: 项目开发最佳实践，包括目录结构、路由配置方案、权限方案、样式方案等。

- icekit@1.0：Class Component, redux, routeConfig（路由扁平）, menuConfig
- icekit@2.0：过渡方案，Function Component + Hooks, icestore, routeConfig, menuConfig
- icekit@3.0：Function Component + Hooks, icestore, config/routes.js, config/menu.js

## 背景

针对模板的最佳实践这个月做了大量讨论，目前基本达成一致，接下来需要对官方 React 模板（ice-lab/react-materials）做统一升级，时间上最好能跟 iceworks 3.0 契合。

### 策略

两种策略：

1. 先把 1.0 -> 2.0 的改造掉，然后基于 2.0 再改造成 3.0（主要就 config 了），这样即便在 iceworks 2.0 里也能使用到近似于 3.0 的能力
2. 2.0 的只改造三个核心模板到 2.x，其他模板都不改，然后统一直接改造到 3.0，优点是工作量稍微少点，缺点是持续使用 iceworks 2.x 的开发者会持续产生增量的老版本项目（也可以在 2.x 的物料源里只透出三个改造的模板，其他模板不透出了）

选择策略 1，分两步：

1. 1.0 -> 2.0: https://github.com/ice-lab/react-materials/pull/49
2. 2.0 -> 3.0 

### 改动点

1.0 -> 2.0:

- 必选：class component -> function + hooks
- 必选：路由配置及渲染，不用 lazy，https://github.com/alibaba/ice/issues/2031#issuecomment-504885304
  - 沒 lazy 的情况用 Fragment 包一下
- 必选：lint 问题修复 https://github.com/alibaba/ice/issues/1852
  - 统一使用根目录的 eslint 规则，将当前目录的 eslint editorconfig 文件改为 _ 开头
  - .eslintignore 里注释掉自己的模板路径
- 必选：CSS Modules 文件命名错误、错误语法（分号）、Layout 的 CSS Modules
  - class 和 花括号的空格自己用编辑器统一替换
  - 引入 stylelint
- 必选：新建 src/global.scss，默认引入 next 的 reset 样式
- 必选：alias + jsconfig.json（如有精力）
- 可选：dataSourceConfig.js + mock/index.js（如有需求）
- 可选：状态管理 icestore（如有需求）
- 可选：权限方案（除了 pro 其他模板可以不用）
- 可选：Hooks 异步获取数据方案 
- 脚本：package.json 增加 adaptor
- 脚本：eslint 规则统一成 eslint-config-ice

2.0 -> 3.0

- config 收敛：比如 routeConfig 收敛到 config/routes

### 分工

见回复

**Comment by boiawang** [comment]
选策略一，全部改掉

**Comment by boiawang** [comment]
- [ ] ice-algorithm-model-admin 6 + 3
- [ ] ice-application-management-admin 5 + 2
- [ ] ice-asset-management-admin 8 + 2
- [ ] ice-build-platfrom 7 + 2
- [ ] ice-commodity-management-admin 10 + 2
- [ ] ice-contract-management-admin 5 + 2
- [ ] ice-creator-admin 8 + 2
- [ ] ice-creator-landingpage 1 + 1
- [ ] ice-customer-analysis-admin 5 + 2
- [ ] ice-design-analysis 1 + 1
- [ ] ice-design-cms 16 + 2
- [ ] ice-design-dashboard 1 + 1
- [ ] ice-design-ecommerce 9 + 2
- [ ] ice-design-iceworks 1 + 1
- [ ] ice-design-schools 8 + 2
- [ ] ice-finance-dashboard 1 + 1
- [ ] ice-government-management-admin 9 + 2
- [ ] ice-hr-management-admin 11 + 2
- [ ] ice-library-management-admin 7 + 2
- [ ] ice-monitor-dashboard 9 + 2
- [ ] ice-open-platform-landingpage 1 + 1
- [ ] ice-operation-admin 6 + 2
- [ ] ice-order-management-admin 10 + 2
- [ ] ice-project-management-admin 9 + 2
- [ ] ice-reviews-management 9 + 2
- [ ] ice-scroll-screen-homepage 1 + 1
- [ ] ice-task-management-admin 11 + 2
- [ ] ice-universal-homepage 12 + 2
- [ ] ice-voice-chat-admin 12 + 2
- [ ] ice-website-homepage 1 + 1
- [ ] ice-yunqi-homepage 3 + 1

模板名 + page 数 + layout 数

**Comment by boiawang** [comment]
#2249

**Comment by imsobear** [comment]
统一 check 黑名单:

- `{ Component }` `this.props` `this.state` `React.Component`
- xxx.scss 文件

**Comment by boiawang** [comment]
- `\{ Component.* \}` `React.Component` `this.`
- `TODO`
- `/\* eslint.*\n`
- `../../`

**Comment by boiawang** [comment]
package.json 里面的 files 修改
