### ISSUE TITLE
最新版GUI工具在mac os中无法展示内容

### ISSUE THREAD

**Issue by iphonexplus** [alibaba/ice#2257]
## 问题描述
今天下午15点10分下载的最新版飞冰GUI工具，安装完成后打开，界面一片空白，此处附上操作系统版本和飞冰版本截图
![image](https://user-images.githubusercontent.com/31926780/60078239-1cf44000-975e-11e9-94b1-f601588bfb89.png)

**Comment by chenbin92** [comment]
点击 「清空列表」清除一下缓存可以解决。已有相关 issue 跟进 https://github.com/alibaba/ice/issues/2117

![image](https://user-images.githubusercontent.com/3995814/60078464-8e33f300-975e-11e9-8864-f71b41419a33.png)

**Comment by iphonexplus** [comment]
感谢回复，已经好用了，多谢！响应速度极快，点个赞
