### ISSUE TITLE
模板缺少 .gitignore 文件

### ISSUE THREAD

**Issue by wssgcg1213** [alibaba/ice#226]

**Comment by chenbin92** [comment]
@wssgcg1213  三套模板下均有  `gitignore` 文件

**Comment by wssgcg1213** [comment]
生成出来没有, 创建链路我查一下
![image](https://user-images.githubusercontent.com/3922719/37078083-bab17522-2218-11e8-856b-f02f647d62ce.png)

**Comment by wssgcg1213** [comment]
http://unpkg.com/@icedesign/scafford-lite@0.1.27/   还真没有

**Comment by chenbin92** [comment]
代码里有 [.gitignore](https://github.com/alibaba/ice/blob/master/scaffolds/ice-design-lite/.gitignore)，发包没有了，我排查下

**Comment by wssgcg1213** [comment]
todo: 创建流程, 把 `_` 打头的文件改成 `.`

**Comment by chenbin92** [comment]
https://github.com/alibaba/ice/pull/235

**Comment by noyobo** [comment]
引起其他问题，例如 _header.scss  下划线类型文件也会被替换。

**Comment by noyobo** [comment]
修改为只对 

```js
if (parsedDestPath.base == '_gitignore') {
      parsedDestPath.base = parsedDestPath.base.replace(/^_/, '.');
 }
```

**Comment by yujiangshui** [comment]
@noyobo 之前这里是有一套模板约束语法的，指的是当 _ 开头时，换成 . 生成。所以应该避免 _hreader.scss 这样的文件？或者模板语法换成 __ 开头？

因为不只是 .gitignore 还会有 .babelrc .npmignore 等文件会可能存在类似的问题，而且这段逻辑记得是写在 SDK 还是生成器里面的，这样的判断条件会把业务文件目录带进去了，耦合了。

**Comment by noyobo** [comment]
@chenbin92  区块和模板里已经没有这样下划线的文件要做特殊替换的了，再次确认下，

@yujiangshui 之前这个逻辑只是对 .gitignore 文件。由于这个文件在发布 npm 的时候会忽略掉。

**Comment by chenbin92** [comment]
是的，目前只有  `.gitignore ` 使用的是下划线
