### ISSUE TITLE
[RFC] 物料国际化方案

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#2261]
## 背景

国际化

### 物料协议

协议层面牵涉到的文案不多，因此方案上尽量简单一些。单个物料层面不再增加字段，通过约定的方式来支持，以单个业务组件为例：

```json
{
  "description": "[zh-cn]描述呀[en-us]hello description",
  // "description": "[zh-cn]描述信息[en-us]",
  // "description": "[zh-cn][en-us]hello",
  "componentConfig": {
    "title": "[zh-cn]标题呀[en-us]hello title",
    "category": "form"
  }
}
```

生成物料协议时，会转换成如下格式，展示端根据需求切换文案即可：

```json
{
  "scaffolds": [],
  "blocks": [],
  "components": [{
    "name": "@ice/form",
    "title": "标题呀",
    "description": "描述呀",
    "en-us": {
      "title": "hello",
      "description": "hello description",
    }
  }]
}
```

### 物料自身代码 `src/`

- 模板：Pro 支持国际化、其他模板直接中文即可（或直接英文）
- 区块：写死文案的地方中英文选一个即可，支持属性透传的文案 follow 组件的多语言支持方案
- 组件：多语言支持方案，参考 fusion 基础组件，待补充

### 组件文档

主要用到构建生成文档的部分：

- ICE 站点需要对生成逻辑做处理
- ice-plugin-component 貌似需要构建出两个 index.html ??? index.html/index-en-us.html

整体 Follow Fusion 基础组件做法：

- README: README.md，README_en-us.md
- demo: demo/a.md
  - 描述部分：md 里使用特殊表示区分中英文描述，[示例](https://github.com/alibaba-fusion/next/edit/master/docs/badge/demo/change.md)
  - 代码部分：代码直接写成英文的

**Comment by chenbin92** [comment]
```
{
  "description": "[zh-cn]描述呀[en-us]hello description",
  // "description": "[zh-cn]描述信息[en-us]",
  // "description": "[zh-cn][en-us]hello",
  "componentConfig": {
    "title": "[zh-cn]标题呀[en-us]hello title",
    "category": "form"
  }
}
```

`[zh-cn]描述呀[en-us]hello description` 这个默认约定好顺序，初始的 `[zh-cn]` 就不用写，等开发者需要国际化的时候在去加后面的半截 `[en-us]`，这样是不是会友好一点

**Comment by tao1991123** [comment]
把元信息 从 package.json移到readme.md里面去
readme.md 本身就是对于组件的描述，而且通过后缀 Readme.en-us.md天生支持国际化 多语言 。

**Comment by tao1991123** [comment]
反而 现在提案这种 元数据写法很难看

**Comment by imsobear** [comment]
> 把元信息 从 package.json移到readme.md里面去
> readme.md 本身就是对于组件的描述，而且通过后缀 Readme.en-us.md天生支持国际化 多语言 。

这里我说下自己的想法：

1. 三个物料类型方案要统一，协议相关的元数据每个物料就只有 2-3 个，单独搞个 README.md 成本太高了，区块/模板的 README 实际上没有任何作用
2. 觉得这个写法难看是因为我没有扩充字段，因为我认为这个方案应该很轻量，甚至类似 github repo description 的做法都可以 `🚀Make Front-end development simple and friendly（让前端开发简单而友好 ）`
3. md 本身结构化比较差，对于 ice-devtools generate 以及 fusion.design 解析数据时多少都增加了一些成本

**Comment by DoranYun** [comment]
语言标识符字段和昨天讨论的保持一直吧。

`[zh_CN]` `[en_US]`

**Comment by imsobear** [comment]
[zh-CN] [en-US]
