### ISSUE TITLE
iceworks模板项目build后js文件超过1.8M

### ISSUE THREAD

**Issue by HC621311** [alibaba/ice#2263]
使用iceworks的CMS内容管理系统模板，build后js文件超过1.8M，在线预览确只有400k，需要做什么操作呢？

**Comment by imsobear** [comment]
参考这个文档：https://ice.work/docs/guide/dev/dynamic-load

**Comment by imsobear** [comment]
问题先关掉了，后续还有问题可以直接 reopen。
