### ISSUE TITLE
关于物料的疑问

### ISSUE THREAD

**Issue by xucongli1989** [alibaba/ice#227]
关于物料的问题：
- 初步来看仅仅只是一个样式组件模板。
- 真正的数据间的存储、交互、权限控制等还得自己写。
- 此框架的定位应该只是解决前端组件搭建的工作。
- 为何不直接复用Ant呢？直接生成Ant不更好？是否会与它有冲突？
- 还是仅仅为了样式更丰富一些？这样的话，有点像BootStrap生成器了。

不知道这样理解是否准确，官网预览总是报错。

Ad:https://github.com/xucongli1989/XCLCMS

**Comment by chenbin92** [comment]
## 物料体系

在 ICE 中，组件、区块、布局、模板等统称为物料，由 ICE 团队维护，在内部有一套完整的开发规范和工具，目前也正在逐步对外开放中；基于此，你可以参与共建 ICE，也可以自建私有的物料体系；并不局限于基础组件，可以是业务区块，或者是完成的模板
  * 组件：最基础的物料，目前 ICE 的基础组件达到 55+，具有高度可复用性

  * 区块：通过对大量的中后台系统常用的场景进行分类、对比和抽象，基于基础组件组合而成，目前 ICE 的区块达到 110+，可以通过 iceworks 进行快速组合搭建应用，减少重复的开发，提升效率

  * 布局：在中后台系统中布局通常较为统一，以`顶部-侧边布局-通栏`模式为主，为此我们提供了 4+ 常见的布局，支持 `light` 和 `dark` 两套主题

  * 模板：基于已有的区块搭建而成，目前提供了 4+ 的特定领域的模板，可以从零开始搭建应用，也可以选择特定类型的模板开始使用

**Comment by xucongli1989** [comment]
总体上来说，该框架还是非常不错的。至少让后台管理系统的开发有一个规范，也大大减少了前台重复的工作量。

**Comment by xucongli1989** [comment]
对UI设计的看法：该框架的设计与Ant设计类似，觉得比较适合作为【用户的个人中心】和【小型后台管理系统】，因为从设计上来看，元素之间占用了太大的空间，稍微复杂一些的后台系统，或内容比较丰富的后台系统，使用起来还是比较吃力的。

**Comment by chenbin92** [comment]
> 为从设计上来看，元素之间占用了太大的空间，稍微复杂一些的后台系统，或内容比较丰富的后台系统，使用起来还是比较吃力的

这个观点目前确实是这样，现在的物料中区块和模板还在持续的建设中，会针对不同的行业领域提供不同的模板。同时，这套机制是透明的，你是可以根据需求自建区块，形成私有的物料体系也是可以的。

有什么好的建议欢迎随时讨论

**Comment by yujiangshui** [comment]
设计上，传统的中后台信息密度非常高，信息量非常大，但其实看起来会比较累。目前的设计我们更倾向于显示核心信息、轻量简约的思路在做，希望可以提升一些质感重新定义后台。目前在淘宝的中后台业务中都是类似的设计思路。
