### ISSUE TITLE
[iceworks]工程面板增加 dev 报错信息

### ISSUE THREAD

**Issue by boiawang** [alibaba/ice#2274]
### 用户场景

1. 用户主动删除了 routerConfig、menuConfig 文件，dev 报错，路由、菜单面板解析错误
2. 用户主动删除了某个页面，routerConfig 引了这个页面，dev 报错，路由面板解析错误
3. 代码语法错误，dev 报错

综合以上信息，所有的异常都会导致工程 dev 报错，所以需要从根源上解决问题

### 解决方案

1. 如果 dev 起了，需要在项目工程面板中将报错信息打印出来
2. 工程面板点击 build 需要给出报错信息
3. 路由面板、菜单面板取不到文件需要给出“该文件不存在”的提示
4. 路由、菜单面板解析报错需要在面板中给出“解析报错”的提示

**Comment by chenbin92** [comment]
@boiawang  在错误处理异常中已经统一处理 https://github.com/alibaba/ice/pull/2349，如有问题可重现打开该 issue
