### ISSUE TITLE
[iceworks] RFC: 创建项目增加自定义模板能力

### ISSUE THREAD

**Issue by boiawang** [alibaba/ice#2283]
## 背景

目前 iceworks 可以从已有模板创建一个项目，但对于一个高级用户来说，他只需要创建一个 ICE 的目录以及工程配置(类似于 lite 模板)，基于模板创建项目的某些配置(布局、导航样式、是否需要 TS 等等)还是需要通过修改代码才能完成，所以需要可以通过可视化配置自定义模板的能力。

## 原型图(绘制原型图使用内部产品 ICELAND)

1. 首页增加创建项目按钮

![image](https://user-images.githubusercontent.com/6340730/60240685-30311800-98e4-11e9-9d92-c5a4a62e8aa4.png)

2. 选择创建一个新模板或者从原有已创建过的模板中选择，下面创建一个新模板

![image](https://user-images.githubusercontent.com/6340730/60240734-49d25f80-98e4-11e9-9fcb-ba6be697f4b2.png)

3. 从已有模板中选择

![image](https://user-images.githubusercontent.com/6340730/60240748-548cf480-98e4-11e9-98ea-86e77303c965.png)

## 方案

1. 需要通过不同的配置生成不同的模板
2. 可以实时预览配置的效果
3. 创建完需要截图将配置保存在本地
4. 将本地保存的数据展现

**Comment by chenbin92** [comment]
@boiawang 

1. 首页的两个模板是 「Quick Start」 的定位，是为了保证完成的流程的设计。
2. 自定义模板是一个比较复杂偏高级的功能，可以放在物料市场模板的 「第一个坑位」给用户进行自定义

综上：不建议在 「Quick Start」 增加自定义模板的流程。

**Comment by temper357** [comment]
为啥会有使用hooks开关？我们的模板已经切到hooks了，未来不维护class的写法

**Comment by boiawang** [comment]
@temper357 跟现在的官方模板没关系，高级配置里的都是可选的，优先级都比较低

**Comment by alvinhui** [comment]
> @boiawang
> 
> 1. 首页的两个模板是 「Quick Start」 的定位，是为了保证完成的流程的设计。
> 2. 自定义模板是一个比较复杂偏高级的功能，可以放在物料市场模板的 「第一个坑位」给用户进行自定义
> 
> 综上：不建议在 「Quick Start」 增加自定义模板的流程。

+1

**Comment by alvinhui** [comment]
> @temper357 跟现在的官方模板没关系，高级配置里的都是可选的，优先级都比较低

如非必要，就不需要实现 class？是否需要交给用户去选择呢，这里面实现也有成本。

**Comment by boiawang** [comment]
> > @temper357 跟现在的官方模板没关系，高级配置里的都是可选的，优先级都比较低
> 
> 如非必要，就不需要实现 class？是否需要交给用户去选择呢，这里面实现也有成本。

是否 hooks、是否 ts 这些选项优先级是会比较低，第一版不会实现，未来会根据用户需求实现

**Comment by boiawang** [comment]
> @boiawang
> 
> 1. 首页的两个模板是 「Quick Start」 的定位，是为了保证完成的流程的设计。
> 2. 自定义模板是一个比较复杂偏高级的功能，可以放在物料市场模板的 「第一个坑位」给用户进行自定义
> 
> 综上：不建议在 「Quick Start」 增加自定义模板的流程。

1. 首先我不认可自定义模板是「复杂偏高级」的，设置布局、导航样式、主题这些都属于基础能力，高级能力如 TS、hooks 等是要默认收起的。
2. 从用户路径来看，创建项目(自定义模板)是一个主流程(从专业前端分析，我们更喜欢创建一个自己配置的空模板，而不是从已有模板中复制)，如将自定义模板的能力放在物料面板里，用户的操作路径较长。

**Comment by chenbin92** [comment]
在 https://github.com/alibaba/ice/issues/2708 讨论
