### ISSUE TITLE
生成页面偶发出现安装区块报错

### ISSUE THREAD

**Issue by yujiangshui** [alibaba/ice#229]
![image](https://user-images.githubusercontent.com/2942913/37080195-58b0a16a-2220-11e8-9114-8659ceea4531.png)

**Comment by chenhongen** [comment]
跟#223一样的问题，我手动install了- -

**Comment by yujiangshui** [comment]
可能是官方默认的 cnpm 源不稳定导致。

尝试在『设置』面板里面将源设置为 npmjs 官方源。

**Comment by chenhongen** [comment]
如果是不稳定的原因的话，建议即使在安装模块失败情况下，多增加个“再试一次”按钮，方便用户一键安装未完成模块。: )

**Comment by yujiangshui** [comment]
排查出来了，不是网络问题，在 1.0.2 版本已经修复 @chenhongen 可以升级试试。
