### ISSUE TITLE
多主题配置 时出现错误或是官方文档错误

### ISSUE THREAD

**Issue by hhd85** [alibaba/ice#2292]
####报错截图
![11883400-8A51-4d9a-ADED-2E93AEA4242A](https://user-images.githubusercontent.com/11838178/60274326-714c1b00-992a-11e9-8b50-d7ca8b857e3b.png)

#### 问题描述
按照官方文档配置 多主题 时出现错误！
#### 相关版本，地址
ice-scripts  版本 2.1.2   之前使用的 2.0.2 也同样报错
官方文档地址 https://ice.work/docs/cli/plugin-list/fusion
#### ice.config.js 官方文档配置
```
module.exports = {
  plugins: [
    ['ice-plugin-fusion', {
      // 通过数组方式配置多主题包
      themePackage: [{
        name: '@icedesign/theme',
        // 设置默认加载主题，如果不进行设置，默认以最后添加主题包作为默认主题
        default: true,
        // 设置自定义主题颜色，可以在 scss 文件中直接使用该变量，比如： .bg-color { background: $custom-color; }
        themeConfig: {
          'custom-color': '#000',
        },
      }, {
        name: '@alifd/theme-ice-purple',
        themeConfig: {
          'custom-color': '#fff',
        },
      }],
    }]
  ]
}
```
#### 补充
配置中用的主题我是按照好的，使用单主题时没有问题！

**Comment by ClarkXia** [comment]
确认下 ice-plugin-fusion 的版本， 0.1.7 版本开始支持多主题设置

**Comment by hhd85** [comment]
非常抱歉，对ice的生态不了解。确实是这样的，我的ice-plugin-fusion是 0.1.6版本。我对比了代码，0.1.6确实没有判断数组的代码。
另外官方文档上也应该注明一下版本号。不然太费时间了！3Q

**Comment by imsobear** [comment]
@hhd85 感谢反馈，文档我们修复下
