### ISSUE TITLE
[icestore] icestore state同步方式讨论

### ISSUE THREAD

**Issue by temper357** [alibaba/ice#2299]
目前icestore的设计是action执行完并不会将最新的state更新到store实例中，而必须通过action的返回值来拿最新的state，store实例要等到页面rerender后再会将值更新进去。代码示例如下：

```javascript
// store.js
{
  foo: '',
  fetchData() {
    this.foo = 100;
  }
}

// view.jsx
const fooStore = stores.useStore('foo');
useEffect(() => {
  const newState = fooStore.fetchData();
  console.log(fooStore.foo); // 并不等于100，还是等于0
  console.log(newState.foo); // 等于100
});
```

该方式存在的问题如下：
1. action中并无返回值，用户并不知道通过这种方式可以拿到返回值，通过action拿最新值的方式更多像是弥补设计缺陷而用的一个隐藏的秘技，并不清楚这个设计的使用者很容易踩到坑使页面出现bug。
2. 调用action改变值之后却没有实时反映到store中，必须等setState rerender后再同步进去，这个设计有点反直觉，更符合操作习惯的是实时同步到store中。

因此我建议将state的同步方式改成action执行完立即同步到store中，这样使用方式上更符合通畅，具体的技术方案还需要重新梳理一下。大家有想法可以补充一下。

**Comment by alvinhui** [comment]
赞成将 state 的同步方式改成 action 执行完立即同步到 store 中，这样对开发者的认知比较友好。
