### ISSUE TITLE
remix  npm  run bootstrap  报错

### ISSUE THREAD

**Issue by Mwuxiaoyu** [alibaba/ice#2300]
##环境
ubuntu 16.04
npm 6.9.0
node v10.16.0
url：https://github.com/ethereum/remix.git

## 问题描述
<pre>
git clone  https://github.com/ethereum/remix.git
cd remix;
npm install
npm run bootstra
</pre>
## 错误信息
<pre>
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'bootstrap' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose run-script [ 'prebootstrap', 'bootstrap', 'postbootstrap' ]
5 info lifecycle @0.1.13~prebootstrap: @0.1.13
6 info lifecycle @0.1.13~bootstrap: @0.1.13
7 verbose lifecycle @0.1.13~bootstrap: unsafe-perm in lifecycle true
8 verbose lifecycle @0.1.13~bootstrap: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/wxy/BlockChain/remix/node_modules/.bin:/usr/bin:/usr/local/sbin:/
usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
9 verbose lifecycle @0.1.13~bootstrap: CWD: /home/wxy/BlockChain/remix
10 silly lifecycle @0.1.13~bootstrap: Args: [ '-c', 'lerna bootstrap' ]
11 silly lifecycle @0.1.13~bootstrap: Returned: code: 1  signal: null
12 info lifecycle @0.1.13~bootstrap: Failed to exec bootstrap script
13 verbose stack Error: @0.1.13 bootstrap: `lerna bootstrap`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid @0.1.13
15 verbose cwd /home/wxy/BlockChain/remix
16 verbose Linux 4.15.0-52-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "bootstrap"
18 verbose node v10.16.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error @0.1.13 bootstrap: `lerna bootstrap`
22 error Exit status 1
23 error Failed at the @0.1.13 bootstrap script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
</pre>

**Comment by imsobear** [comment]
看起来跟当前仓库无关

**Comment by Mwuxiaoyu** [comment]
> 看起来跟当前仓库无关



> 看起来跟当前仓库无关

嗯，我用的node v10版本出了问题，换成node v9版本就好了

**Comment by Mwuxiaoyu** [comment]
@imsobear 嗯，我用的node v10版本出了问题，换成node v9版本就好了
