### ISSUE TITLE
icescript2.1.2版本，多应用启动问题

### ISSUE THREAD

**Issue by jxwright** [alibaba/ice#2305]
## 问题描述

icescript 版本为2.1.2的应用，当启动多个应用时，第一个启动成功，第二个提示更改端口号后就一直卡在10%处，不往下加载了，关闭第一个后，启动第二个又可以成功，但再npm start 原来第一个又会卡在10%

## 错误信息
![5DD6879E-F59A-490d-89E0-177D72F6D148](https://user-images.githubusercontent.com/41815729/60404983-f3189e80-9bdf-11e9-9a39-585a21b3390b.png)
这个跟踪的情况，问题应该出在这里，但具体什么问题，不是很清楚。。
![F7620B8B-1EAE-45fe-8680-A6EA6616AE58](https://user-images.githubusercontent.com/41815729/60404988-f744bc00-9bdf-11e9-98b6-94fc99cb2cec.png)
![295715F9-40E0-467e-98E1-C07AF8824A4B](https://user-images.githubusercontent.com/41815729/60404989-f90e7f80-9bdf-11e9-98b7-8501fd3c1824.png)

**Comment by ClarkXia** [comment]
有相应的error信息吗？ 另外可以关注下内存占用的情况，两个 ice-scripts 应该是独立的

**Comment by jxwright** [comment]
> 另外可以关注下内存占用的情况

这两个都是官网模板，没有报任何错误。。内存占用正常。。icescript1.xxx版本没有这个问题。或者您那边同时启动两个icescript2.xxx应用没有这个问题吗。。

**Comment by jxwright** [comment]
补充信息，原问题实在VSCODE环境下直接在终端npm start,但在ICEWORKS下启动正常，我怀疑是端口选择的问题，在ICEWORKS下如果有端口占用会在启动前直接选择端口，但在VSCODE下是启动过程中选择端口。。具体原因还得麻烦你们看下

**Comment by imsobear** [comment]
不太好重现，issue 我先关掉了，猜测可能是同时启动瞬间内存不够引起的，目前没有特别好的解决方案。
