### ISSUE TITLE
请问如何在windows客户端中删除页面以及如何创建2级菜单

### ISSUE THREAD

**Issue by xyq145163** [alibaba/ice#231]
RT

**Comment by noyobo** [comment]
暂不支持删除，以及二级菜单，功能已加入需求，可关注进度。

**Comment by yujiangshui** [comment]
@xyq145163 希望可以了解下你对删除页面的详细需求。

是删除 pages/xxx 目录的文件？还是将其 routes.jsx、navs.js 等全部清除？

还是只删除 routes.js 路由和导航，而保留文件？

**Comment by xyq145163** [comment]
@yujiangshui 目前的话 觉得把routes.jsx和nav.js关联全部清除 保留页面文件更好一点。如果能有一个类似回收站的功能就更完美了  如果需要再用到原来的页面可以直接恢复并重建路由和导航

**Comment by noyobo** [comment]
react-route 升级支持删除页面功能

**Comment by noyobo** [comment]
路由操作以为 routerConfig.js 操作
