### ISSUE TITLE
RFC: 前端异步操作状态的同步到视图

### ISSUE THREAD

**Issue by alvinhui** [alibaba/ice#2313]
## 目标

前端在发出异步请求前后能同步状态到视图中。

## 背景

当前使用 icestore 进行异步数据请求，但没有在数据请求发起后：

- 显示等待效果
- 数据请求失败后显示错误信息。

### 示例

以请求依赖列表为例，下面的代码没有上面所描述的两种处理：

store:

```javascript
export default {
  dataSource: [],

  async refresh() {
    this.dataSource = await (await fetch(/* api */)).json();
  },

  async install(data) {
    await fetch(/* api */, data);
  },
};
```

view:

```javascript
import stores from '@src/stores';

const Component = () => {
  const dependenciesStore = stores.useStores('dependencies'); 

  useEffect(() => {
    dependenciesStore.refresh();
  }, []);

  function onInstall() {
    async function install() {
      await dependenciesStore.install();

      dependenciesStore.refresh();
    }

    install();
  }

  return 
    <div>
      <button onClick={onInstall}>
        安装新依赖
      </button>
      <div>
        {dependenciesStore.dataSource.map(({name, id}) => {
          return <div>
            {name}
          </div>;
        })}
      </div>
    </div>;
};
```

### 基于 icestore 业务层如果要处理

store:

```javascript
export default {
  dataSource: [],

  refreshError: undefined,

  refreshLoading: false,

  installError: undefined,

  installLoading: false,

  setRefreshLoading(value) {
    this.refreshLoading = value;
  }

  setInstallLoading(value) {
    this.installLoading = value;
  }

  async refresh() {
    try {
      this.dataSource = await (await fetch(/* api */)).json();
      this.refreshError = '';
    } catch (error) {
      this.refreshError = error;
    }
  },

  async install(data) {
    try {
      await fetch(/* api */, data);
      this.installError = '';
    } catch (error) {
      this.installError = error;
    }
  }
};
```

view:

```javascript
import stores from '@src/stores';

const Component = () => {
  const dependenciesStore = stores.useStores('dependencies'); 

  async function fetch() {
    await dependenciesStore.setRefreshLoading(true);
    await dependenciesStore.refresh();
    await dependenciesStore.setRefreshLoading(false);
  }
  useEffect(() => {
    fetch();
  }, []);

  function onInstall() {
    async function install() {
      await dependenciesStore.setInstallLoading(true);
      await dependenciesStore.install();
      await dependenciesStore.setInstallLoading(false);

      fetch();
    }

    install();
  }

  return 
    <div>
      {dependenciesStore.installError}
      <button onClick={onInstall} disable={dependenciesStore.installLoading}>
        安装新依赖
      </button>
      {
        dependenciesStore.refreshLoading ? 
          '加载中' :  
          !dependenciesStore.refreshError ? 
            <div>
              {dependenciesStore.dataSource.map(({name, id}) => {
                return <div>
                  {name}
                </div>;
              })}
            </div> : 
            null
      }
    </div>
};
```

## 问题

- 该逻辑的处理如果在业务层，则比较恶心；是否可以在 icestore 层面做，如果在业务层面做怎么做更好？
- 如果在 icestore 层面做，怎么做？

## 思路

通常一个异步方法有以下状态：

- 该方法未调用；
- 该方法在调用中；
- 该方法调用完成。

在我们的实际场景中，我们关心的是该方法是否在调用中，该方法调用是否成功，如果有错误，错误是什么。

## 方案

在每个异步方法后面挂载字段用于标识方法的执行状态，然后前端通过这些字段去进行状态判断及进行视图处理。

- 该方法在调用中: pending；
- 该方法调用完成后是否有错误：error。

示例代码

```javascript
// store
export default {
  dataSource: [],

  async refresh() {
    this.dataSource = await (await fetch(/* api */)).json();

    // 如果是根据接口的返回值确定成功与否状态：
    /*
    const result = await (await fetch()).json();

    if (result.error) {
      throw new Error(data.error);
    } else {
      this.dataSource = result.dataSource;
    }
    */
  },

  async install(data) {
    await fetch(/* api */, data);
  },
};

// view
import stores from '@src/stores';

const Component = () => {
  const dependenciesStore = stores.useStores('dependencies'); 

  useEffect(() => {
    dependenciesStore.refresh();
  }, []);

  function onInstall() {
    async function install() {
      await dependenciesStore.install();
      await dependenciesStore.refresh();
    }

    install();
  }

  return 
    <div>
      {dependenciesStore.install.error}
      <button onClick={onInstall} disable={dependenciesStore.install.pending}>
        安装新依赖
      </button>
      {
        dependenciesStore.refresh.pending ? 
          '加载中' :  
          !dependenciesStore.refresh.error ? 
            <div>
              {dependenciesStore.dataSource.map(({name, id}) => {
                return <div>
                  {name}
                </div>;
              })}
            </div> : 
            null
      }
    </div>
};
```

默认每个异步方法都会有该状态且触发*两次视图的刷新*：

- 第一次：异步方法执行前，将方法的 pending 属性赋值为 true；
- 第二次：异步方法执行后，将方法的 pending 属性赋值为 false，如果失败则将方法的 error 属性赋值为 Error。

可以在全局设置禁止异步状态的刷新：

```javascript
import Icestore from '@ice/store';

const icestore = new Icestore();
icestore.disableAsyncStatus = true;
```

也可以在方法调用前禁止该次调用的异步状态的刷新：

```javascript
import stores from '@src/stores';

const Component = () => {
  const dependenciesStore = stores.useStores('dependencies'); 

  useEffect(() => {
    dependenciesStore.refresh.disableAsyncStatus = true;
    dependenciesStore.refresh();
  }, []);

  return null;
};
```

**Comment by chenbin92** [comment]
1. 上述内容没有看到具体的实现方案，是在业务层面去做还是在 icestore 层面去做？
2. 在前端状态管理库中，一般状态会分为三种：`isLoading: true | false`  ||  `isError: true | false` 等，但通常不会用 `did`、`runing` 这样的字段来表示。

综上：

可以在 icestore 层面去统一考虑 loading 和 error 的处理，但不知道这个成本是多大；我个人建议现阶段在业务层面进行封装，包括上次说的 async 在 useEffect 中调用的问题。

个人比较倾向下面的这种封装形式：

![image](https://user-images.githubusercontent.com/3995814/60432933-15d5a200-9c36-11e9-8647-4d2db08adb30.png)

**Comment by alvinhui** [comment]
@chenbin92 icestore 层面去做，字段名可以再对焦一下

**Comment by temper357** [comment]
我对异步状态的分类有点疑问：
1. did：是否执行过的涵义有点模糊，因为一个action可以被执行多次，只要执行过一次这个标志位一直为true? 这个状态是否有必要
2. error: 有error，是否需要有sucess？

因为async函数返回的是Promise，我觉得可以参考Promise的状态去设计，Promise包含三种状态，pending, fulfilled, rejected

**Comment by alvinhui** [comment]
@temper357 

- 从业务场景来说，会有一种叫做「未初始化」的状态。从 API 设计来说，这个字段的含义确实含糊，有没有其他好的建议来实现这个场景呢？
- error 在我的设计当中，是一个错误对象。只要是有，则代表有错误，无则代表执行成功。

Promise 的提议很赞，怎么结合我们实际的业务场景，这方面我再考虑一下。

**Comment by chenbin92** [comment]
https://github.com/alibaba/ice/issues/2071

**Comment by chenbin92** [comment]
> 我对异步状态的分类有点疑问：
> 
> 1. did：是否执行过的涵义有点模糊，因为一个action可以被执行多次，只要执行过一次这个标志位一直为true? 这个状态是否有必要
> 2. error: 有error，是否需要有sucess？
> 
> 因为async函数返回的是Promise，我觉得可以参考Promise的状态去设计，Promise包含三种状态，pending, fulfilled, rejected

@temper357 
不赞成直接引入 Promise 这三个 `pending`, `fulfilled`, `rejected` 字段，这里要表达的是请求之后的状态，跟函数本身调用的状态应该是要区分开的，在本质上不是一个概念，我觉得 DataBinder 在这个设计上就挺好。试想一个场景，如果引入这三个字段，那么前端还需要拿着这三个字段分别去做处理，不如直接 loading: fasle || true 来的直接。

**Comment by alvinhui** [comment]
汇总了一下大家的意见

以下几点征集大家讨论一下：

1. 是否可以将状态挂载到方法中？
2. 状态有哪些？我认为有三种：

    - 方法是否曾经调用过；
    - 方法是否在调用中；
    - 方法是否调用完成且调用结果如何。
3. 状态字段如何命名，我的提案：

    - inited(boolean)：从未调用过则该字段为 false，调用过一次则该方法 true ；
    - loading(boolean)：如果方法在调用中则该字段为 true，否则为 false ；
    - error(Error)：方法未调用为 undefined，在调用中为 undefined，调用完有错误则为 Error，无错误则为 undefined 。

**Comment by chenbin92** [comment]
> 1. 是否可以将状态挂载到方法中？

我认为是将状态挂载到返回的结果中

>2. 状态有哪些？我认为有三种：
>
>方法是否曾经调用过；
>方法是否在调用中；
>方法是否调用完成且调用结果如何。

对状态管理需求来说，开发者不需要关系方法是否调用，只需要关心返回的数据状态结果，如 Loading  和 error，数据状态结果和方法状态是两个概念

> 3. 状态字段如何命名，我的提案：
> inited(boolean)：从未调用过则该字段为 false，调用过一次则该方法 true ；
> pending(boolean)：如果方法在调用中则该字段为 true，否则为 false ；
> error(Error)：方法未调用为 undefined，在调用中为 undefined，调用完有错误则为 Error，无错误则为 undefined 。

个人建议：

1. inited 不需要，状态管理不需要关心方法是否调用
2. pending => loading (参考 DataBinder 和社区常见的做法保持一致)

**Comment by alvinhui** [comment]
> > 1. 是否可以将状态挂载到方法中？
> 
> 我认为是将状态挂载到返回的结果中，跟方法没有任何关系
> 
> > 1. 状态有哪些？我认为有三种：
> > 
> > 方法是否曾经调用过；
> > 方法是否在调用中；
> > 方法是否调用完成且调用结果如何。
> 
> 对状态管理需求来说，开发者不需要关心方法是否调用，只需要关心返回的数据状态和结果，如 loading 、data ，数据状态结果和方法状态是两个概念
> 
> > 1. 状态字段如何命名，我的提案：
> >    inited(boolean)：从未调用过则该字段为 false，调用过一次则该方法 true ；
> >    pending(boolean)：如果方法在调用中则该字段为 true，否则为 false ；
> >    error(Error)：方法未调用为 undefined，在调用中为 undefined，调用完有错误则为 Error，无错误则为 undefined 。
> 
> 个人建议：
> 
> 1. inited 不需要，状态管理不需要关心方法是否调用
> 2. pending => loading (参考 DataBinder 和社区常见的做法保持一致)
> 3. 一般的做法是使用 success 字段，且应该是包含在 data 数据中，或者单独一个字段
> 
> **数据的流转过程**
> 
> * 请求中:
> 
> ```js
> {
>    loading: true 
>    data: []
> }
> ```
> 
> * 请求成功
> 
> ```js
> {
>    loading: false 
>    data: [
>       ...data,
>       success： true
>    ]
> }
> ```
> 
> * 请求失败
> 
> ```js
> {
>    loading: false 
>    data: [
>       ...data,
>       success： false
>    ]
> }
> ```

能否结合主贴中的具体场景写一个示例代码？

**Comment by alvinhui** [comment]
@chenbin92 你所描述的 数据的流转过程 是一个非常通用的 API 设计，我们能否就具体的场景来讨论呢？

**Comment by temper357** [comment]
1.  状态作为方法的属性挂载到方法中我认为没问题，作为返回结果会侵入方法自身的设计
2. 方法是否曾经调用过: 这个我认为可以在业务代码中增加flag来解决这个问题，是否值得在框架代码中加入这个功能来支持这个我有疑问，需要贴下具体的业务场景来评估下
3. 方法调用结果: 这个也可以直接在业务代码中支持，放在框架代码中没有带来更好的便利性

**Comment by chenbin92** [comment]
> @chenbin92 你所描述的 数据的流转过程 是一个非常通用的 API 设计，我们能否就**具体的场景**来讨论呢？

两个问题
1. 上面的回复是基于你的 [回复](https://github.com/alibaba/ice/issues/2313#issuecomment-507504043 )的回复，个人建议
2. 对应你的场景一示例代码

```js
import stores from '@src/stores';

const Component = () => {
  const [pagesStore] = stores.useStores(['page']); 

  useEffect(() => {
    pagesStore.refresh();
  }, []);

  // pagesStore 中包含 loading 和 data 字段，同时 data 字段包含具体的数据和 isSuccess(可选)
  return data.loading ? <Loading /> :  {data.isSuccess  ？ renderSuccessContent() : renderErrorContent()}
};
```

**Comment by chenbin92** [comment]
> 1. 状态作为方法的属性挂载到方法中我认为没问题，作为返回结果会侵入方法自身的设计
> 2. 方法是否曾经调用过: 这个我认为可以在业务代码中增加flag来解决这个问题，是否值得在框架代码中加入这个功能来支持这个我有疑问，需要贴下具体的业务场景来评估下
> 3. 方法调用结果: 这个也可以直接在业务代码中支持，放在框架代码中没有带来更好的便利性

> 状态作为方法的属性挂载到方法中我认为没问题，作为返回结果会侵入方法自身的设计

没理解这个概念是什么，求指点

**Comment by temper357** [comment]
@chenbin92 store.actionxxx.isInit，作为方法的属性

**Comment by chenbin92** [comment]
> @chenbin92 store.actionxxx.isInit，作为方法的属性

什么场景下需要关系方法是否调用过？而且是作为方法的属性而不是放在数据结果里

**Comment by temper357** [comment]
再总结下我的观点，从职责上划分的话，社区的状态管理框架其实都没有将这三种状态放入其中，我们如果要放进去的话，要有充足的理由，比如说场景很高频，加入后能便利得解决用户的问题，如果场景很少的话，我觉得没必要，如果没有给用户带来很大的便利，也不需要

**Comment by temper357** [comment]
> 什么场景下需要关心方法是否调用过？而且是作为方法的属性而不是放在数据结果里

inited这个状态也是我质疑的，我认为没有必要放入框架中

**Comment by chenbin92** [comment]
> 再总结下我的观点，从职责上划分的话，社区的状态管理框架其实都没有将这三种状态放入其中，我们如果要放进去的话，要有充足的理由，比如说场景很高频，加入后能便利得解决用户的问题，如果场景很少的话，我觉得没必要，如果没有给用户带来很大的便利，也不需要

+1  上面我有评论问你们是在 icestore 里面去处理还是在业务层面处理

![image](https://user-images.githubusercontent.com/3995814/60481845-d3f23d80-9cc1-11e9-8c4d-cac9ae63d83b.png)

**Comment by alvinhui** [comment]
> 1. 状态作为方法的属性挂载到方法中我认为没问题，作为返回结果会侵入方法自身的设计
> 2. 方法是否曾经调用过: 这个我认为可以在业务代码中增加flag来解决这个问题，是否值得在框架代码中加入这个功能来支持这个我有疑问，需要贴下具体的业务场景来评估下
> 3. 方法调用结果: 这个也可以直接在业务代码中支持，放在框架代码中没有带来更好的便利性


1. 是否曾经调用过确实不值得放到框架层面；
2. 调用结果直接在业务代码支持的话，会比较复杂，这里我列一个具体的场景，如果在业务代码中需要怎样处理以及放在框架中后是怎么处理的。

## 业务代码中处理

```javascript
export default {
  dataSource: [],

  refreshError: undefined,

  deleteError: undefined,

  async refresh() {
    try {
      this.dataSource = await (await fetch(/* api */)).json();
    } catch (error) {
      this.refreshError = error;
    }
  },

  async delete(id) {
    try {
      await fetch(/* api */, { id });
    } catch (error) {
      this.deleteError = error;
    }
  }
};
```

```javascript
import stores from '@src/stores';

const Component = () => {
  const [pagesStore] = stores.useStores(['page']); 

  useEffect(() => {
    pagesStore.refresh();
  }, []);

  function onDelete(id) {
    pagesStore.delete(id);
  }

  return 
    pagesStore.refreshError ? 
      'error!!!' :  
      <div>
        {pagesStore.dataSource.map(({name, id}) => {
          return <div>
            {name}
            <div>
              {pagesStore.deleteError}
              <button onClick={() => onDelete(id)}>
                删除
              </button>
            </div>
          </div>;
        })}
      </div>
};
```

## 框架处理

```javascript
export default {
  dataSource: [],

  async refresh() {
    this.dataSource = await (await fetch(/* api */)).json();
  },

  async delete(id) {
    await fetch(/* api */, { id });
  }
};
```

```javascript
import stores from '@src/stores';

const Component = () => {
  const [pagesStore] = stores.useStores(['page']); 

  useEffect(() => {
    pagesStore.refresh();
  }, []);

  function onDelete(id) {
    pagesStore.delete(id);
  }

  return 
    pagesStore.refresh.error ? 
      'error!!!' :  
      <div>
        {pagesStore.dataSource.map(({name, id}) => {
          return <div>
            {name}
            <div>
              {pagesStore.delete.error}
              <button onClick={() => onDelete(id)}>
                删除
              </button>
            </div>
          </div>;
        })}
      </div>
};
```

我认为这个场景是很高频，加入后能便利得解决用户的问题的。

**Comment by alvinhui** [comment]
几个点再拉大家线下讨论：

- 现在是什么场景？
- 是否需要在 icestore 层面做，还是在业务层面做？
- 如果在业务层面做，怎么做？
- 如果再 icestore 层面做，怎么做？

    - 是挂载到方法的属性，还是内置字段(@chenbin92 )；
    - 如果是方法的属性，则属性有哪些，怎么命名。

**Comment by alvinhui** [comment]
- 同步或异步是不一样的，同步不应该触发 loading / error；
- 异步时也应该是默认不触发 loading / error ，通过某种方式启动。

**Comment by alvinhui** [comment]
https://github.com/ice-lab/icestore/pull/16
