### ISSUE TITLE
预览好像有问题

### ISSUE THREAD

**Issue by Hongbo-Miao** [alibaba/ice#232]
这个页面

https://alibaba.github.io/ice/#/layout/header-aside-footer-responsive-layout/preview

预览好像有问题，基本是空白页面。
试了Chrome, Safari都是这样。

![image](https://user-images.githubusercontent.com/3375461/37083019-0444f18a-21a3-11e8-8fb4-c4241886fe41.png)

**Comment by chenbin92** [comment]
![](https://img.alicdn.com/tfs/TB14QHCcuuSBuNjy1XcXXcYjFXa-2148-1606.png)

**Comment by Hongbo-Miao** [comment]
一直卡在
![image](https://user-images.githubusercontent.com/3375461/37177195-96eebabc-22d3-11e8-9037-ab8032882504.png)
