### ISSUE TITLE
Git repository with full history size too large

### ISSUE THREAD

**Issue by zhaofeng-shu33** [alibaba/ice#2322]
## Problem Description
After cloning this repository with full history, I found the size of this git repository is too large. To be more specific,
```shell
git clone https://github.com/alibaba/ice
git checkout 4452d76
du -d 1 -h --exclude=./node_modules
```
![WechatIMG928](https://user-images.githubusercontent.com/23316477/60511136-d2e20000-9d03-11e9-8c09-d1aca0b85741.png)

The size of the repository at this specific commit is around 460MB with 2505 records of commit.

After checking `tools/iceworks`, it is found there are some binaries files. Also the size of this directory is around 80MB. One maintainer of this repository reports that once he pushed a large file to the remote
directory, and then he deletes this file in another commit. However, the deletion does not reduce the repository size.

A simple comparision can be done. We inspect [react](http://github.com/facebook/react/tree/5cb8f6f344a6f3e296f095b8d151157d1f05c835) at 5cb8f6. It has 11093 commits but has 158MB in total.
![WechatIMG927](https://user-images.githubusercontent.com/23316477/60511145-d70e1d80-9d03-11e9-9a65-dd0ac5039d16.png)

**Comment by chenbin92** [comment]
目前这个问题没有好的解决办法，除非是清除掉所有的历史记录，但这不是一个好的做法

**Comment by imsobear** [comment]
删除无用 tag 之后，体积缩小了一半：

![image](https://user-images.githubusercontent.com/2505411/63238345-9d27b500-c278-11e9-8c06-99dc2ac0b5e1.png)

**Comment by chenbin92** [comment]
> 删除无用 tag 之后，体积缩小了一半：
> 
> ![image](https://user-images.githubusercontent.com/2505411/63238345-9d27b500-c278-11e9-8c06-99dc2ac0b5e1.png)

666 怎么想到删除 tag 的

**Comment by imsobear** [comment]
因为仓库里有二进制文件，这些文件无法被 diff，版本变化等于完全替换，因此导致历史记录里很多大对象，看下能不能选择性删除一些：

![image](https://user-images.githubusercontent.com/2505411/63238550-a1a09d80-c279-11e9-893c-89df2f2f8b1e.png)

**Comment by imsobear** [comment]
- .git 太大的处理方案：https://www.zhihu.com/question/29769130
- 批量删除远程 tag 方案：https://sexywp.com/how-to-bulk-delete-tags-local-and-remote.htm
