### ISSUE TITLE
iceworks+create-react-app 生态建设

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#2325]
## 目标

使用 iceworks 可快速开发 create-react-app 的项目

## 描述

- 了解 iceworks Adapter 机制：[docs](https://github.com/alibaba/ice/blob/9f31584049c6301ec66463a4181c8212fb560d1a/docs/iceworks/advanced/adapter-about.md)
- 实现 Adapter: create-react-app
- 增加 creat-react-app 物料源：前期仅需一个 CRA 的模板即可
- 社区推广

**Comment by temper357** [comment]
cra模板需要实现的功能点：
* 适配 kit 3.0 [目录结构](https://github.com/alibaba/ice/issues/2164#issuecomment-501576394)，保证以下功能在iceworks中可用，数据源配置、状态管理、权限管理不用实现
  - [ ] 页面列表
  - [ ] 布局列表
  - [ ] 路由管理
  - [ ] 菜单管理
* 工程能力适配，包含dev, build, lint
