### ISSUE TITLE
初始化生成的区块代码package.json里面的name属性你们使用/隔开,npm命令运行会报错,只有把斜杠去掉或者改成其他的才可以.请问有其他解决办法吗

### ISSUE THREAD

**Issue by jeryqwq** [alibaba/ice#2335]
## 错误信息

![image](https://user-images.githubusercontent.com/25569373/60581425-61fd1f80-9db9-11e9-955b-f72c06061d20.png)

**Comment by imsobear** [comment]
- 按照正确格式描述，标题是标题，内容是内容
- 内容里描述清楚自己的操作路径
- 完善后自行 reopen 下 issue
