### ISSUE TITLE
Adapter 面板的语言配置刷新问题

### ISSUE THREAD

**Issue by alvinhui** [alibaba/ice#2337]
## 问题

- 当前的 getAdapter 只会执行一次，返回了面板相关的信息；
- 当切换语言后由于 getAdapter 不再执行，因此面板还是老的语言。

为了解决这个问题，Project 下引入了 updateAdapter 方法，在获取项目信息时（`getProject`）主动再次执行了该方法。

这样的做法有两个问题：

1. getProject 是个调用非常频繁的方法（每次请求 adapter 相关的 API 都会调用），导致无必要的调用；
2. 从职责上来说

    - 该方法名有问题，该方法实际上并非在 updateAdapter，而是在 updatePanels；
    - 不应该在 getProject 这个时机去做这个事情。

**Comment by chenbin92** [comment]
> 当前的 getAdapter 只会执行一次，返回了面板相关的信息； 

这个问题我准备在解，还是直接在这个一起解决？

**Comment by alvinhui** [comment]
> > 当前的 getAdapter 只会执行一次，返回了面板相关的信息；
> 
> 这个问题我准备在解，还是直接在这个一起解决？

一起解吧，我也是刚发现语言这里也有这个问题。

**Comment by Orange-C** [comment]
#2344
