### ISSUE TITLE
预览一个模板，窗口出现抖动

### ISSUE THREAD

**Issue by zancheng** [alibaba/ice#2342]
## 问题描述
进入下面的预览，出现窗口一直抖动
https://unpkg.com/@icedesign/reviews-management-scaffold@2.0.8/build/index.html#/dashboard

## 错误信息

进入数据概览，窗口一直抖动，窗口尺寸超过1457px时。
点击底部图表就会停止，可能是监听的窗口宽度变化出现图表一直重绘的问题。

**Comment by jasonintju** [comment]
@zancheng  你能再详细描述一下复现条件吗？我打开这个链接都是好的，没有发现页面抖动情况

**Comment by zancheng** [comment]
可能跟浏览器有关，我换火狐就没事。
windows系统    Google Chrome 版本 75.0.3770.100（正式版本） （64 位）

**Comment by jasonintju** [comment]
> 可能跟浏览器有关，我换火狐就没事。
> windows7系统 Google Chrome 版本 75.0.3770.100（正式版本） （64 位）

恩，建议升级一下浏览器版本。如果是普遍性bug，再reopen该issue

**Comment by C4o** [comment]
https://unpkg.com/@icedesign/project-management-admin@3.0.2/build/index.html#/dashboard
应该不是浏览器版本或者系统问题 chrome浏览器Version 75.0.3770.142 (Official Build) (64-bit)的版本 也是出现窗口抖动 似乎是自动匹配窗口尺寸有点问题
win10和mac的chrome都会有抖动

**Comment by imsobear** [comment]
@C4o 是否可以录一个 gif？

另外本地用这个模板初始化一个项目，然后开发项目时的预览窗口是否抖动？

**Comment by C4o** [comment]
gif有点大 https://s31.aconvert.com/convert/p3r68-cdx67/awrgs-o56nb.gif

**Comment by C4o** [comment]
![GIF](https://user-images.githubusercontent.com/17063085/62456945-3a301b80-b7ac-11e9-8620-943a27caf34d.gif)

**Comment by imsobear** [comment]
对模板进行了重新梳理，下线了一些无法持续维护的模板
