### ISSUE TITLE
iceworks vue-adapter 工程适配

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#2354]
## 需求梳理

了解 iceworks vue-dapter 开发的具体需求，产出方案

* 一个 Adapter 应该包含 「工程实践」和「项目实践」两部分，其中对应 vue Adapter 来说，主要是实现基于 vue-cli 3.x 目前已经有 vue-cli 4.x alpha.3 版本了，可以对比下。同时「项目实践」 主要是指项目中对 router 和 menu 的约束，能在 iceworks 上进行可视化展示和操作

* 目前已实现的是 adapter-vue-v1 是对老的工程和项目的适配，需要新增一个 adapter-vue-v2，对应 vue-cli 3.x 和 ice kit@3.x 的适配

## 相关链接
* 目录结构 & 讨论：https://github.com/alibaba/ice/issues/2164
* 路由和菜单约定 & 讨论 ：#2031
* Adapter 开发规范 & 讨论：https://github.com/alibaba/ice/issues/2249

**Comment by luhc228** [comment]
**adapter-vue-v1** 是基于vue-cli 3.x 和 kit@2.x 但在iceworks/release-3.x分支上 并没有加入与kit@2.x的相关Menu和Router。
```
import { checkAliInternal } from 'ice-npm-utils';
import getBaseAdapter from '../adapter';
import Configuration from './modules/configuration';
import Task from './modules/task';

export default async (i18n) => {
  const baseAdapter = await getBaseAdapter(i18n);
  const adapter = {
    Guide: baseAdapter.Guide,
    Layout: baseAdapter.Layout,
    Git: baseAdapter.Git,
    OSS: baseAdapter.OSS,
    Todo: baseAdapter.Todo,
    Dependency: baseAdapter.Dependency,
    Task: {
      ...baseAdapter.Task,
      module: Task
    },
    Configuration: {
      ...baseAdapter.Configuration,
      module: Configuration
    }
  };

  const isAliInternal = await checkAliInternal();
  const filteredPanels = isAliInternal ? ['OSS'] : ['DEF'];
  Object.keys(adapter).forEach((name) => {
    if (filteredPanels.indexOf(name) > -1) {
      delete adapter[name];
    }
  });
  return adapter;
};
```
这里是否需要修改吗？@chenbin92

**Comment by chenbin92** [comment]
> **adapter-vue-v1** 是基于vue-cli 3.x 和 [kit@2.x](mailto:kit@2.x) 但在iceworks/release-3.x分支上 并没有加入与[kit@2.x](mailto:kit@2.x)的相关Menu和Router。
> 
> ```
> import { checkAliInternal } from 'ice-npm-utils';
> import getBaseAdapter from '../adapter';
> import Configuration from './modules/configuration';
> import Task from './modules/task';
> 
> export default async (i18n) => {
>   const baseAdapter = await getBaseAdapter(i18n);
>   const adapter = {
>     Guide: baseAdapter.Guide,
>     Layout: baseAdapter.Layout,
>     Git: baseAdapter.Git,
>     OSS: baseAdapter.OSS,
>     Todo: baseAdapter.Todo,
>     Dependency: baseAdapter.Dependency,
>     Task: {
>       ...baseAdapter.Task,
>       module: Task
>     },
>     Configuration: {
>       ...baseAdapter.Configuration,
>       module: Configuration
>     }
>   };
> 
>   const isAliInternal = await checkAliInternal();
>   const filteredPanels = isAliInternal ? ['OSS'] : ['DEF'];
>   Object.keys(adapter).forEach((name) => {
>     if (filteredPanels.indexOf(name) > -1) {
>       delete adapter[name];
>     }
>   });
>   return adapter;
> };
> ```
> 
> 这里是否需要修改吗？@chenbin92

在 adapter-vue-v2 需要增加 router 和 menu 的管理

**Comment by luhc228** [comment]
> > **adapter-vue-v1** 是基于vue-cli 3.x 和 [kit@2.x](mailto:kit@2.x) 但在iceworks/release-3.x分支上 并没有加入与[kit@2.x](mailto:kit@2.x)的相关Menu和Router。
> > ```
> > import { checkAliInternal } from 'ice-npm-utils';
> > import getBaseAdapter from '../adapter';
> > import Configuration from './modules/configuration';
> > import Task from './modules/task';
> > 
> > export default async (i18n) => {
> >   const baseAdapter = await getBaseAdapter(i18n);
> >   const adapter = {
> >     Guide: baseAdapter.Guide,
> >     Layout: baseAdapter.Layout,
> >     Git: baseAdapter.Git,
> >     OSS: baseAdapter.OSS,
> >     Todo: baseAdapter.Todo,
> >     Dependency: baseAdapter.Dependency,
> >     Task: {
> >       ...baseAdapter.Task,
> >       module: Task
> >     },
> >     Configuration: {
> >       ...baseAdapter.Configuration,
> >       module: Configuration
> >     }
> >   };
> > 
> >   const isAliInternal = await checkAliInternal();
> >   const filteredPanels = isAliInternal ? ['OSS'] : ['DEF'];
> >   Object.keys(adapter).forEach((name) => {
> >     if (filteredPanels.indexOf(name) > -1) {
> >       delete adapter[name];
> >     }
> >   });
> >   return adapter;
> > };
> > ```
> > 
> > 
> > 这里是否需要修改吗？@chenbin92
> 
> @luhc228 在 adapter-vue-v2 需要增加对 router 和 menu 的管理

adapter-vue-v2针对的vue项目中的router和menu相关文件是统一放在config文件夹中还是在src根目录下？若统一放在config下，则不需要增加对 router 和 menu 的管理。

**Comment by luhc228** [comment]
### adapter-vue-v2 需求描述
iceworks adapter-vue-v2用于适配 vue-cli @3.x 和 ice kit @3.x。
### 具体方案描述
- 与adapter-react-v1/v2/v3读取的cliConfFilename应为 `ice.config.js`，而adapter-vue-v1/v2读取的cliConfFilename应为 `vue.config.js`。针对上述情况，需增加configuration和task的管理。
```
export default class Configuration extends baseModules.Configuration {
  public cliConfFilename: string = 'vue.config.js';
  public cliConfPath: string;

  constructor(params) {
    super(params);
    this.cliConfPath = path.join(this.project.path, this.cliConfFilename);
  }
}
```
```
export default class Task extends baseModules.Task {
  public cliConfFilename: string = 'vue.config.js';
  public cliConfPath: string;

  constructor(params) {
    super(params);
    this.cliConfPath = path.join(this.project.path, this.cliConfFilename);
  }
}
```
- 由于iceworks adapter-vue-v2面向的是 `ice kit @3.x`，menu.js和routes.js配置统一放在 src/config，可直接继承Adapter中的Menu和 Route配置（父类Adapter是基于ice kit@3.x的）。
- 需增加对npm lint支持，在开发环境下检查语法错误。
- 参考 [ice kit@3.x的讨论](https://github.com/alibaba/ice/projects/6)，产出符合ice kit@3.x的设计要求的Vue项目，对adapter-vue-v2进行测试。
-

**Comment by chenbin92** [comment]
@luhc228 需要对 vue 对应的模板 admin-lite 做一些调整

* 输出 3.x 的物料源地址 @chenbin92 
* 按照 kit@3.x 的规范调整目录结构 @luhc228 
   - [ ] 新增 src/config/menu.js
   - [ ] 新增 src/config/routes.js
   - [ ] menu 和 router 按照 kit@3.x 的协议进行调整
* 确保 admin-lite@3.x 和 adapter-vue-v2 能在 iceworks 中正常工作
   @chenbin92 
   - [ ] 添加 3.x vue 物料源

  @luhc228 
   - [ ] 创建项目
   - [ ] 新建页面，路由，菜单
   - [ ] 启动调试服务
   - [ ] 构建项目
   - [ ] 修改 vue.config.js 配置

**Comment by luhc228** [comment]
> @luhc228 需要对 vue 对应的模板 admin-lite 做一些调整
> 
> * 输出 3.x 的物料源地址 @chenbin92
> * 按照 [kit@3.x](mailto:kit@3.x) 的规范调整目录结构 @luhc228
>   
>   * [ ]  新增 src/config/menu.js
>   * [ ]  新增 src/config/routes.js
>   * [ ]  menu 和 router 按照 [kit@3.x](mailto:kit@3.x) 的协议进行调整
> * 确保 [admin-lite@3.x](mailto:admin-lite@3.x) 和 adapter-vue-v2 能在 iceworks 中正常工作 @luhc228
>   
>   * [ ]  添加 3.x vue 物料源  @chenbin92
>   * [ ]  创建项目
>   * [ ]  新建页面，路由，菜单
>   * [ ]  启动调试服务
>   * [ ]  构建项目
>   * [ ]  修改 vue.config.js 配置

是在原有的admin-lite基础上修改，还是再新建一个admin-lite（按照ice kit@3.x的协议规范）

**Comment by luhc228** [comment]
### adapter-vue-v2实现功能如下
- Task管理，主要用于获取或重写vue.config.js中的配置，包括构建目录，是否启用Hash等等。adapter-vue-v2主要是更改Task管理的cliConfFilename（在这里指vue.config.js），即更改cliConfPath。同时更改TaskConfig内容，因为vue.config.js有部分字段与ice.config.js不符合，所有字段的中文和英文已同步更新到en-US.json和zh-CN.json。其他继承父类Adapter。
- Configuration管理，用于用户自定义配置。更改Configuration管理的cliConfFilename（在这里指vue.config.js），同时更改ConfigSchema，因为vue.config.js有部分字段与ice.config.js不符合，所有字段的中文和英文已同步更新到en-US.json和zh-CN.json。他继承父类Adapter。
- 其他直接继承父类Adapter。

### 测试内容
 * [ ] Vue模板 Admin-Lite [admin-lite](https://github.com/ice-lab/vue-materials/pull/17)，按照 kit@3.x 的规范做出相应的调整。
 * [ ] 创建项目
 * [ ] 正确读取项目的页面，菜单，路由，git等信息。
 * [ ] 正确添加/删除/修改菜单和路由配置。
 * [ ] 新建页面
 * [ ] 启动本地调试，同时应测试修改部分设置（端口/host等）。
 * [ ] 构建项目，同时应测试修改部分设置（构建路径/开启 hash等）。
 * [ ] 修改用户自定义项目配置。
