### ISSUE TITLE
Implement iceworks create-react-app adapter

### ISSUE THREAD

**Issue by tanhengyeow** [alibaba/ice#2356]
## Problem Description

Adapters allow projects built by different tools for e.g. Create React App, Vue CLI to be imported inside [iceworks](https://ice.work/iceworks). 

Existing adapters e.g. `adapter-react-*` only support React projects built using [`ice-scripts`](https://github.com/ice-lab/ice-scripts). This means that only React projects built using `ice-scripts` can be imported inside iceworks.

This issue explores the possibility to implement the `adapter-cra-*` adapter so that React projects built using Create React App can be imported inside iceworks. Adapters should follow best practices specified in icekit@3.x(latest version as of now). 

These practices include directory structure, menu, routing, permissions etc, which decide how the project that is imported into iceworks would be displayed and configured. After the project is imported into iceworks, users can develop their project through the iceworks UI interface.

Sample directory structure suggested by @boiawang:
```
- mock
  - index.js
- src
  - components // 项目共用组件
    - xx
      - index.jsx
      - index.module.scss
  - layouts // 项目共用 layouts
  - pages // 项目页面
  - locales // 国际化
    - en-US
    - zh-CN
  - pages
    - PageA
      - components // 页面级组件
        - xx
          - index.jsx
          - index.module.scss
      - index.jsx
      - index.module.scss
  - utils
    - request.js
  - config
    - menu.js // 菜单配置
    - routes.js // 路由配置
  - index.jsx // 项目根入口
  - router.jsx // 解析 config/routes 渲染路由
- tests
- .editorconfig
_ .eslintignore
_ .eslintrc.js
_ .gitignore
_ .stylelintignore
_ .stylelintrc.js
_ jsconfig.json
_ package.json
_ README.md
_ webpack.config.js
```

## Relevant resources
- Discussion on directory structure specification: [#2164](https://github.com/alibaba/ice/issues/2164#issuecomment-501576394)
- Discussion on menu and routing specification: [#2031](https://github.com/alibaba/ice/issues/2031#issuecomment-504885304)
- Discussion on permissions specification: [#2174](https://github.com/alibaba/ice/issues/2174#issuecomment-504886208)
- Discussion on styles specification: [CSS Modules](https://ice.work/docs/guide/dev/style#CSS%20Modules)
- Documentation on `ice-scripts`: [ice-scripts](https://github.com/ice-lab/ice-scripts), [#1929](https://github.com/alibaba/ice/issues/1929)
- Documentation on Adapters: [resources](https://github.com/alibaba/ice/tree/iceworks/docs/docs/iceworks/advanced)
- Discussion on Adapters: [#2249](https://github.com/alibaba/ice/issues/2249), [relationship with ecosystem](https://github.com/alibaba/ice/issues/2249#issuecomment-508654134)

**Comment by tanhengyeow** [comment]
Analysis should be done to figure out how existing adapters such as `adapter-react-*` work to support React projects built using `ice-scripts`. This would help in identifying how to implement `adapter-cra-*`.

The strategy would be as follow:
1. Use `iceworks` to create a React project. (This project is built using `ice-scripts`)
2. Analyze how existing adapters such as `adapter-react-*` work to allow the project to be imported and used in iceworks
3. Use `create-react-app` to create a React project.
4. Implement the `adapter-cra-*` to allow the project to be imported and used in iceworks.

**Comment by boiawang** [comment]
No problem. That's it.

**Comment by boiawang** [comment]
[2325](2325)

**Comment by imsobear** [comment]
cra 模板需要实现的功能点：

* 适配 kit 3.0 [目录结构](https://github.com/alibaba/ice/issues/2164#issuecomment-501576394)，保证以下功能在iceworks中可用，数据源配置、状态管理、权限管理不用实现
  - [ ] 页面列表
  - [ ] 布局列表
  - [ ] 路由管理
  - [ ] 菜单管理
* 工程能力适配，包含dev, build, lint
