### ISSUE TITLE
多主题配置 __changeTheme__ 调用失败

### ISSUE THREAD

**Issue by JerryWoo** [alibaba/ice#2359]
## 问题描述

多主题配置后调用window.changeTheme('@alifd/theme-ice-green');后报错如下，是不是还要添加什么依赖：

## 错误信息
TypeError: window.__changeTheme__ is not a function
![image](https://user-images.githubusercontent.com/3063273/60719246-a3c4cc00-9f59-11e9-94d9-19170a7a3f1e.png)

## 相关代码
ice.config.js
`module.exports = {
  entry: 'src/index.js',
  publicPath: './',
  proxy: {
    '/**': {
      enable: true,
      target: 'http://localhost:8080',
    },
  },
  plugins: [
    ['ice-plugin-fusion', {
      themePackage: [{
        name: '@icedesign/theme',
        // 设置默认加载主题，如果不进行设置，默认以最后添加主题包作为默认主题
        default: true,
      }, {
        name: '@alifd/theme-green',
      }],
    }],
  
    ['ice-plugin-moment-locales', {
      locales: ['zh-cn'],
    }],
  ],
};`

SettingForm.jsx
`
export default class Footer extends PureComponent {
  render() {
    window.__changeTheme__('@alifd/theme-ice-green');
    return (
      <Layout.Footer className="ice-design-layout-footer" type={null}>
        <div className="ice-design-layout-footer-body">
          <div className="copyright">
            © 2019 版权
          </div>
        </div>
      </Layout.Footer>
    );
  }
}
`

**Comment by ClarkXia** [comment]
@JerryWoo `__changeTheme__`代码目前注入位置在相关 entry 入口文件之后，所以必须等入口文件执行完之后才会挂载到 window 对象上，建议通过操作触发，不要直接放在 render 函数中
下个版本将优化掉 `__changeTheme__`代码注入位置

**Comment by JerryWoo** [comment]
@ClarkXia 明白了，多谢！
