### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by chaochaohao** [alibaba/ice#236]
![pgsv4 kp fg88 2_ uw_j](https://user-images.githubusercontent.com/10116477/37087064-305297aa-2234-11e8-93a0-df2a8b04f04b.png)

**Comment by scglwsj** [comment]
![image](https://user-images.githubusercontent.com/9821801/37142943-8cc9e90a-22f4-11e8-8f74-5c9c1edef821.png)

系统为Win10 64位
项目页面数 -> 新建页面 -> 任意小眼睛会出现这个BUG。

**Comment by wssgcg1213** [comment]
fixed
