### ISSUE TITLE
 iceworks 3.0 beta 发布 - 基于物料的一站式可视化源码研发工作台 🚀

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#2369]
## 主要更新

- **CLI 使用链路**：无需下载，一步开启全新研发体验；
- **升级产品结构**：「项目管理」、「工程管理」、「物料市场」三大板块助力源码链路研发；
- **全新用户界面**：多主题和多语言，满足开发者的个性化诉求；
- **可定制化工作台**：任何前端项目，无论何种工程工具或项目规范，都可在 iceworks 中集成！

## 安装

在 iceworks 3.0 中， 我们提供了本地 CLI 的使用链路，安装 npm 的 iceworks 包，即可开始体验！

```
$ npm install iceworks -g # 或者 cnpm install iceworks -g
$ iceworks -V
```

## 启动

在命令行中执行以下命令，即可启用本地 Web 版本的 iceworks！

```
$ iceworks # open in browser： http://localhost:8000/
```

### 升级产品结构

在现有的 iceworks 2.0 版本基础上划分 「项目管理」、「工程管理」、「物料市场」三个核心版块，覆盖前端项目的生成、开发到发布的完整生命周期，提供一站式的源码研发管理。

#### 项目管理

- 覆盖项目研发的全流程，十多种面板定制使用，配置专属的 iceworks 界面；
- 基于物料的轻松拖拽，即可创建页面；
- 丰富多样的项目信息面板，为研发保驾护航：页面信息，路由信息，OSS 发布管理等；
- 新增 「路由」和「导航」的管理能力，告别复杂的代码配置。

![项目管理](https://img.alicdn.com/tfs/TB1Hgl3Xrj1gK0jSZFOXXc7GpXa-2888-1362.png)

#### 工程管理

- 可视化设置项目的工程配置，告别对复杂的工程体系的理解；
- 一键启动调试服务、构建服务、代码检测等；

![工程管理](https://img.alicdn.com/tfs/TB1Rvt0XrH1gK0jSZFwXXc7aXXa-2782-1222.png)

#### 物料市场

- 官方提供的海量高质量物料，丰富的垂直领域模板和区块；
- 基于目标一键快速创建项目，开启项目开发；
- 支持自定义物料接入，不断提高代码复用性。

![物料市场](https://img.alicdn.com/tfs/TB1kCXZXxD1gK0jSZFyXXciOVXa-2840-1456.png)

### 全新用户界面

- 支持多主题：提供「深色」和「浅色」两套主题，根据之前的用户调研，更多的用户更偏爱深色主题，这一功能在 iceworks 3.0 中得到了支持；
- 支持多语言：就是偏爱英文，我们满足你；
- 更大的项目面板，更清晰友好的用户体验！

![全新的用户界面](https://img.alicdn.com/tfs/TB1p3h2XBr0gK0jSZFnXXbRRXXa-1810-934.png)

### 可定制化工作台

为满足高级开发者的定制化诉求，iceworks 通过 adapter 的机制，支持开发者实现定制工作台的能力。

Adapter 本质上是某一类前端项目的最佳实践的抽象，通过 adapter 机制可以接入 iceworks 进行可视化的项目工程管理，定制专有的前端工作台。

![定制工作台](https://img.alicdn.com/tfs/TB1sh8ZXxD1gK0jSZFyXXciOVXa-2672-1526.png)

> 更多关于定制工作台的介绍将会在未来释出。
  
## 项目升级到 3.0

iceworks 之前的项目如需升级到 iceworks 3.0，只需要按需配置对应的 adapter 即可。

对于旧项目，要升级到 3.0 请在 package.json 中增加如下配置

```
{
  "iceworks": {
    "type": "react", 
    "adapter": "adapter-react-v1", // 或者 adapter-react-v2
  }
}
```

上面的 adapter-react 后面的版本号选择 v1 还是 v2 可以根据下面来判断： 

项目根目录是否存在 ice.config.js 文件：

- 如果存在，则使用 adapter-react-v2
- 否则使用 adapter-react-v1

> 注意：使用 iceworks 3.0 创建的新项目，adapter版本为 adapter-react-v3。

## 体验 & 反馈群

![image](https://user-images.githubusercontent.com/3995814/60947123-63cb6380-a322-11e9-9a4d-35774c85cf4b.png)

**Comment by alvinhui** [comment]
迁移方式我建议是不要外链，直接把内容贴过来（内容也不多哈）。

**Comment by chenbin92** [comment]
> 升级到 3.0 的迁移方式可以直接把内容贴过来吗？（内容也不多哈）

done

**Comment by chenbin92** [comment]
## 问题汇总

P0 主链路问题，P1 正式版前必须修复，P2 部分可以放到后续迭代版本

### P0

- [ ] 启动时进入页面报错 Message [object object]   https://github.com/alibaba/ice/issues/2386
- [ ] 沒安装依赖点击 dev iceworks-server 会退出
- [ ] iceworks electron 版本
- [ ] [项目]项目列表错乱 https://img.alicdn.com/tfs/TB1bXnWbQxz61VjSZFtXXaDSVXa-1756-1516.png

### P1

- [ ] 选择文件夹的地方需要过滤 . 文件
- [ ] 工程面板需要增加「安装依赖」操作按钮
- [ ] iceworks-cli 对 iceworks-server 的依赖动态化，启动时检测依赖版本是否有更新，参考 def-core 的做法
- [ ] 透出 Vue 物料源作为官方推荐物料源
- [ ] 执行命令后默认自动用浏览器打开页面
- [ ] 项目面板设置样式错乱 https://img.alicdn.com/tfs/TB1FsVSXUD1gK0jSZFGXXbd3FXa-1358-1580.png
- [ ] 推荐模板背景色优化 https://img.alicdn.com/tfs/TB14dw1XxD1gK0jSZFyXXciOVXa-1072-501.png
- [ ] iceworks 3.0 文档 Review和上线 https://github.com/alibaba/ice/pull/2247
- [ ] iceworks 3.0 新版官网介绍页更新 https://img.alicdn.com/tfs/TB1bURLeQ9E3KVjSZFGXXc19XXa-1915-4338.png

### P2

- [ ] 内置官方物料源数据兜底
- [ ] server 启动时间有点长：考虑多输出一些日志或者优化启动速度
- [ ] 底部切换主题的文案写反了
- [ ] 添加物料的 Dialog 太小
- [ ] [优化] 下载物料失败透出 URL 地址
-[ ] [优化] 日志台高度没撑满

### P3

- [ ] [优化] 全局日志分操作日志和进程日志
- [ ] [优化] 新建页面模态框优化
- [ ] [优化] 操作路径都写入 global 控制台

**Comment by chenbin92** [comment]
* windows 环境打开项目没有显示文件目录

![image](https://user-images.githubusercontent.com/3995814/60938862-307bdb00-a308-11e9-8997-bb190ef681dc.png)

**Comment by uv-w** [comment]
加油！

**Comment by imsobear** [comment]
![image](https://user-images.githubusercontent.com/2505411/60948319-3b913400-a325-11e9-8fc8-f249a8e5b249.png)

这个 loading 状态沒处理好

**Comment by imsobear** [comment]
安装依赖输出日志感觉像卡死了，建议：

- 持续输出日志，现在感觉不像 websocket，并且日志量很少感觉像加了 --silent
- 安装前打印出执行的命令 xnpm install 之类的，node 版本之类的也可以输出下

**Comment by imsobear** [comment]
- 依赖管理面板加载非常非常慢
- client 和 server 的日志都要补全，现在太少太少了
- 透出项目信息，比如路径
- 单个物料卡片，考虑透出版本信息

**Comment by imsobear** [comment]
![image](https://user-images.githubusercontent.com/2505411/60949337-8d3abe00-a327-11e9-885e-9f13b82591e4.png)

这个切换很卡，感觉像是代码问题

**Comment by chenbin92** [comment]
## 配置 npm 源和 client 问题

是否要提高 npm 源设置和 client 设置

- npm 源设置
- client 设置

目前 iceworks 3.0 中没有提供上述两种能力的设置，这样在内网的用户无法安装对应的内网包，解决方案是可以通过判断内网则直接使用 tnpm 进行安装。

如果提供上述两种配置，则需要根据用户环境去分析对应的 npm client 的安装路径，过程相对叫繁琐

**Comment by chenbin92** [comment]
安装依赖日志格式化问题

![image](https://user-images.githubusercontent.com/3995814/60956209-e8bf7880-a334-11e9-8fd2-6bf783e6dec0.png)

**Comment by luhc228** [comment]
#### 问题描述
- Node版本:  8.9.4
- 问题描述：停止项目调试服务后，会报下面的错。对应的页面也空白了。
![image](https://user-images.githubusercontent.com/44047106/61021001-42c24b80-a3d2-11e9-861b-65d19cf33a47.png)
![image](https://user-images.githubusercontent.com/44047106/61021006-4655d280-a3d2-11e9-81d7-1547e71b67d3.png)

**Comment by luhc228** [comment]
#### 问题描述
- node版本：8.9.4
- 系统：windows10
- 开始构建项目时，侧面会有错误提示，并一直卡在vue-cli-service build
![image](https://user-images.githubusercontent.com/44047106/61021988-553e8400-a3d6-11e9-8ee6-3780957bb1d3.png)
![image](https://user-images.githubusercontent.com/44047106/61022032-8e76f400-a3d6-11e9-91e0-ce65d16a73e2.png)

**Comment by chenbin92** [comment]
无项目时，切换语言报错

![image](https://user-images.githubusercontent.com/3995814/61025492-87a2ae00-a3e3-11e9-9784-c9ed948d0d9d.png)

**Comment by imsobear** [comment]
从 iceworks 中删除项目后 db.json 里的 panelSettings 内容还在

**Comment by imsobear** [comment]
从模板创建项目是个异步过程，界面上没有处理，网络慢的情况下就很明显

**Comment by imsobear** [comment]
入门指引面板建议跟其他面板保持一致，现在看起来有点奇怪：

![image](https://user-images.githubusercontent.com/2505411/61185976-3b30ca00-a692-11e9-84bf-a751971e77f7.png)

**Comment by chenbin92** [comment]
> 入门指引面板建议跟其他面板保持一致，现在看起来有点奇怪：
> 
> ![image](https://user-images.githubusercontent.com/2505411/61185976-3b30ca00-a692-11e9-84bf-a751971e77f7.png)

这个当时设计的时候讨论过，是特意这样设计的，「入门指引」不属于一个功能性的面板，与其他面板有所不同所有特别突出了，可以在设置面板关闭

**Comment by luhc228** [comment]
### 问题描述
react工程 创建页面时报错，进度条卡在40%，但实际上已经下载解压缩并移动到当前项目位置。debug时报错 **error: EISDIR: illegal operation on a directory.**
![image](https://user-images.githubusercontent.com/44047106/61197406-57228300-a707-11e9-980c-4b6a4b7e1187.png)
![image](https://user-images.githubusercontent.com/44047106/61197530-04959680-a708-11e9-99f8-af8558388c49.png)

**Comment by chenbin92** [comment]
- 进入物料模块，默认会定位官方物料，此时异步请求未返回结果，切换至自定义物料，显示自定义物料内容，当官方物料结果返回后，会覆盖自定义物料内容

![image](https://user-images.githubusercontent.com/3995814/61260127-a02e1200-a7af-11e9-946b-b7f8835ac02a.png)

**Comment by alvinhui** [comment]
## 桌面端软件 TODO List

### Bugs

- [ ] 在部分机器上无法启动应用，报 iceworks-server 启动失败，无读文件权限； @imsobear 
- [ ] 创建页面卡死；
- [ ] 退出时无等待效果 ；
- [ ] 窗口无法关闭。

### 功能

- [ ] changelog 的处理：需要明确 2.0 的 `changelog/changelog.json` 和 `changelog/${verison}.json` 的作用；
- [ ] 将安装包上传到 OSS；
- [ ] 生成 update.json：electron 自动更新需要读取；
- [ ] 上传 changelog.json 和 update.json 到 OSS。

**Comment by zhaofeng-shu33** [comment]
在部分机器(mac 10.13)上无法启动应用的问题是启动方式不对，mac 上 /Volume下的 iceworks 文件夹是只读的

**Comment by zhaofeng-shu33** [comment]
应该安装到 application 目录下运行。

**Comment by alvinhui** [comment]
## 桌面软件版本的维护及升级策略

(ing...)

### 2.0 维护及升级策略

2.0 发布最后一个 [2.23.0](https://github.com/alibaba/ice/pull/2529) 版本，后续将不投入维护。

- 区分 2.0 版本和 3.0 版本的升级检测地址，确保 2.0 不会收到 3.0 的更新信息；
- 代码层面在 2.23.0 上已不允许自动升级到 3.0；
- 在 2.23.0 版本上透出下载 iceworks 3.0 CLI 版本的提醒。

### 3.0 维护及升级策略

- 3.0 使用全新的升级检测地址；
- 3.0 升级：
    - 整体软件：有自动升级逻辑，与 2.0 版本一直；
    - iceworks-server: 启动时检查版本，有新版则自动更新。

**Comment by ChasLui** [comment]
使用 3.0 之后经常 socket 断开连接(电脑休眠后), 这时候就需要重启 iceworks, 并且还需要 lsof -i:8000 找到 pid 然后 kill, 很是不方便

**Comment by chenbin92** [comment]
> 使用 3.0 之后经常 socket 断开连接(电脑休眠后), 这时候就需要重启 iceworks, 并且还需要 lsof -i:8000 找到 pid 然后 kill, 很是不方便

https://github.com/alibaba/ice/issues/2650  这里有 issue 记录，会尽快解决掉

**Comment by niweiL** [comment]
GeneralTable domo如何请求api数据渲染
能否给个具体demo
const mockData = async () => {
  try {
    const result = await axios('https://mock-api.hupu.io/mock/205/eg/test');
    const data =[];
    for(var i=0;i<result.data.length;i++){
      data.fill(result.data[i]);
    }


    console.log("mockData:result:" + data);
    return data;
    // this.dataSource(result.data);
  } catch (err) {
    console.log(err)
  }
};
这样写不行
