### ISSUE TITLE
项目编译后存在css文件为空

### ISSUE THREAD

**Issue by TrumanDu** [alibaba/ice#2371]
## 基本规范
同样的版本，在window下没任何问题，在linux下即会出现该问题
## 问题描述

项目编译后存在css文件为空
## 错误信息
```
                                                                    css/3.css   8.22 KiB             3  [emitted]         
                                                                    css/4.css    0 bytes             4  [emitted]     
```
其他css和js文件都没问题，仅有4.css为空。
4.css内容
```
.next-sr-only{position:absolute;width:1px;height:1px;padding:0;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;-webkit-clip-path:inset(50%);clip-path:inset(50%);border:0}
```

查看所有css 文件，发现只有4.css文件最小，只有一个样式文件

**Comment by ClarkXia** [comment]
麻烦看下使用的 ice-scripts 版本是多少，两个css 差异仅仅是 .next-sr-only 的内容吗？

**Comment by TrumanDu** [comment]
`ice-scripts@1.10.1`
应该不是，我有看到别的css里也有这个样式，但是它还有其他的样式，感觉这个就是因为只有这一个样式才出问题的

**Comment by ClarkXia** [comment]
@TrumanDu 建议升级到 ice-scripts 2.x https://ice.work/docs/cli/migrate 
样式丢失关联问题 #2144

**Comment by TrumanDu** [comment]
升级以后还是同样问题，[模板](https://unpkg.com/@icedesign/usertrack-admin-scaffold@3.0.1/build/index.html#/user/login)登录页面改成懒加载，在linux 下build即可复现该问题

**Comment by ClarkXia** [comment]
@TrumanDu 麻烦贴下核心的修改代码 方便复现

**Comment by TrumanDu** [comment]
这个我抽时间给个最小demo

**Comment by imsobear** [comment]
先关掉了，需要的话再 reopen
