### ISSUE TITLE
WIN7每次停止调试服务，弹“启动失败”

### ISSUE THREAD

**Issue by chenhongen** [alibaba/ice#238]
家里和公司电脑都是这样：
![2018-03-07_215338](https://user-images.githubusercontent.com/16499303/37096011-6b3d9f90-2252-11e8-87b2-69479eedbb8e.png)

**Comment by noyobo** [comment]
收到， 下个版本修复

**Comment by YYEnglish** [comment]
我的也这样 重启电脑后可以了

**Comment by scglwsj** [comment]
win10同样的问题

**Comment by noyobo** [comment]
v1.0.2 修复
