### ISSUE TITLE
项目工程升级存在 es module 规范和 commonjs 规范混用问题

### ISSUE THREAD

**Issue by ClarkXia** [alibaba/ice#2381]
## 背景
一些历史项目中存在 es module 和 commonjs 混用的情况，比如会使用 `require` 去加载 es module 模块，这时候就需要处理成 `require('xx').default`
babel 6 可以使用 `add-module-export` 插件处理，但在 babel 7（目前 ice-scripts 使用版本） 中已经弃用 https://babeljs.io/docs/en/v7-migration-api#export-changes 
需要调研下有没有其它方式可以兼容

**Comment by Orange-C** [comment]
看了下babel7只是在babel相关包中弃用了add-module-export，我们依然可以使用add-module-export来处理自己的包

**Comment by imsobear** [comment]
> 看了下babel7只是在babel相关包中弃用了add-module-export，我们依然可以使用add-module-export来处理自己的包

可以试下，不过即便这样也是让用户自己去加，不要放到默认配置里，因为本身这不是正确的语法。

**Comment by Orange-C** [comment]
试了下需要@babel/preset-env同时配置modules: 'commonjs' 才会生效，的确不能放到默认配置里，推动模块更新或者再开一个插件做兼容比较好

**Comment by ClarkXia** [comment]
> 试了下需要@babel/preset-env同时配置modules: 'commonjs' 才会生效，的确不能放到默认配置里，推动模块更新或者再开一个插件做兼容比较好

不建议支持混用，历史项目可单独通过定制 babel 配置
