### ISSUE TITLE
[icestore] icestore架构设计与新feature讨论

### ISSUE THREAD

**Issue by temper357** [alibaba/ice#2382]
新版文档 [docs](https://github.com/ice-lab/icestore/blob/refactor-docs/README.zh-CN.md)

总结一下天马在使用icestore中遇到的一些问题，请补充具体的业务场景

1. 定义store方式 class vs object， class有何优点
2. 在一个store中调用到其他store的必要性

**Comment by demohi** [comment]
### 用 Class 的好处(TS 场景)

1. Class Store 字段可以定义类型，可以直接使用。 不然还得手写来维护类型定义
2. 父类 Store 可以统一提供一些全局定义，比如 loading

### 跨 store 调用
这个点主要还是开发的简单性

**Comment by temper357** [comment]
### 对于使用Class
1. 声明类型的确Class方便些，但是这个只是语法上的差异，单独定义interface增加的工作量并不多
2. icestore 0.2已经支持了loading和error状态的记录，在refresh上可以直接访问到loading，参考最新的icestore文档，还有没有其他需要类继承的场景?
3. websocket监听初始化放在store的constructor中做有个问题，由于store一旦初始化后就是全局的无法卸载，当使用这个store的view组件unmount时如何关闭socket？否则会面临内存泄露的问题。这个逻辑我觉得通过封装hooks，然后在view组件中引入更适合。

综上，使用Class与Object相比除了语法层面的差异之外，核心是Class使store具备了在constructor中定义初始化逻辑的能力，但是这个能力是否有必要开放我有疑问，一个constructor中用户可以写任意业务逻辑，在API设计角度来看会导致store的职责不清晰，另外一个如上面第3点所述类似websocket这种事件监听逻辑不适合放在store中处理。


### 跨 store 调用
从设计上层面来看，每个store应该都是逻辑独立的个体，不应该与其他store产生关系，否则就没必要设计成多store，因此从逻辑上对做store隔离我觉得是必要的。对于遇到一个store的action中要调用其他的action的场景，我觉得分两种情况处理，一种是这两个store是逻辑关联是强耦合的，此时适合将两个store中公共部分抽出来放到一个store中管理，另一种两个store没有关系，但是一个事件同时触发了两个store的action，这种情况推荐的做法是封装hooks，在其中分别调用两个store的action，例如以下:
```javascript
function useMultipleStore() {
  const [storeA, storeB] = stores.useStores(['a', 'b']);
  async function triggerActions() {
     await storeA.xxx(); 
     await storeB.yyy();
  };
  return triggerActions;
}
```

**Comment by demohi** [comment]
1.对于用 Object 写 store，我还是保留意见，手动维护类型我觉得还是不太合理。
2.其他几个点认可
