### ISSUE TITLE
[iceworks][ice-scripts] ice-plugin-multi-pages 插件支持启动指定的单个或多个页面

### ISSUE THREAD

**Issue by Wiolem** [alibaba/ice#2389]
## 场景描述

`ice-plugin-multi-pages` 插件希望可以支持命令行启动指定页面，因为每次迭代都是开发单个或少数页面，感觉没必要全部启动

例如: 

支持这样类似的命令

```js
iceworks dev pages/home,pages/list...
```
or

```js
ice-scripts dev pages/home,pages/list...
```

**Comment by ClarkXia** [comment]
@Wiolem 目前 ice-scripts 支持指定配置文件，建议开发单个页面的时候可以在 package.json 的 scripts 中增加一段类似 `"dev:single": "ice-scripts dev --config dev.config.js"`，然后 `dev.config.js` 里面的内容可以不使用 `ice-plugin-multi-pages`， 单独通过 `entry` 配置去指定本地迭代的入口页面
