### ISSUE TITLE
图标黑块

### ISSUE THREAD

**Issue by YYEnglish** [alibaba/ice#239]
我的win10系统打开应用软件打开后底部任务栏的iceworks上半部分有黑色块状挡住图标；yinyvcf@qq.com  我可以提供截图；

**Comment by wssgcg1213** [comment]
我们导出的 ICO 文件在win下有不识别的问题, 下一个版本会修复掉 感谢反馈

**Comment by YYEnglish** [comment]
嗯！git不太会用  不知道怎么上图

**Comment by wssgcg1213** [comment]
直接粘贴图片就可以

**Comment by yujiangshui** [comment]
@YYEnglish 目前我们发布了 1.0.2 版本，麻烦升级再看下，这个版本尝试修复 ico 文件。

**Comment by mowatermelon** [comment]
@yujiangshui   我更新了，1.0.2版本ice在win10系统任务栏中图标完整显示

**Comment by YYEnglish** [comment]
嗯嗯   我更新了1.1.1的版本  没有黑块了
