### ISSUE TITLE
Windows 上新建项目文件夹空白

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#2404]
## 操作流程

在 Windows 上新建项目，选择目录显示空白，无法继续操作

![image](https://user-images.githubusercontent.com/3995814/60952721-5b792580-a32e-11e9-8666-dbfe8e90846a.png)

![image](https://user-images.githubusercontent.com/3995814/60952725-5fa54300-a32e-11e9-8dfc-ade41f9df6db.png)

**Comment by chenbin92** [comment]
使用V8.9.4版本 

操作步骤：打开项目-->然后我点了返回上一级 C:\\Users 选择里面的Public，然后显示不出任何文件夹，点返回上一级也不能返回 

![image](https://user-images.githubusercontent.com/3995814/61019582-43a4ae80-a3cd-11e9-8a48-1be4bd704384.png)

![image](https://user-images.githubusercontent.com/3995814/61019584-47d0cc00-a3cd-11e9-9d49-a48a6847da96.png)

![image](https://user-images.githubusercontent.com/3995814/61019587-4b645300-a3cd-11e9-98c7-a73a2f263c6d.png)

**Comment by alvinhui** [comment]
https://github.com/alibaba/ice/pull/2520
