### ISSUE TITLE
npm run bootstrap 卡住了

### ISSUE THREAD

**Issue by Justforfei** [alibaba/ice#241]
$ npm run bootstrap

> ice-workspace@0.0.2 bootstrap E:\Test\ice
> lerna bootstrap

lerna info version 2.9.0
lerna info versioning independent
lerna info Bootstrapping 123 packages
lerna info lifecycle preinstall
lerna info Installing external dependencies
[         .........] \ install dependencies: verb installed leaf ice-scripts

一直卡在了这里

**Comment by Justforfei** [comment]
原因： 网络问题，包安装停止
解决方法： 配置 lerna.json

**Comment by wssgcg1213** [comment]
最近可能网络不稳定 先走个代理试下?

bootstarp 是一次性操作, 也可以你先改下配置
