### ISSUE TITLE
pro 模版样式细节问题

### ISSUE THREAD

**Issue by ClarkXia** [alibaba/ice#2418]
## 问题描述
ice-design-pro@3.0.2 在一些样式细节需要进行优化
e.g.  1440宽度下
![image](https://user-images.githubusercontent.com/4219965/61030416-e66e2480-a3ef-11e9-96e6-4c594a32855c.png)
![image](https://user-images.githubusercontent.com/4219965/61030454-fb4ab800-a3ef-11e9-8a59-eb51d6511543.png)
e.g. 响应式布局问题
![image](https://user-images.githubusercontent.com/4219965/61030563-3baa3600-a3f0-11e9-9fcc-b9e55e0f8c29.png)
![image](https://user-images.githubusercontent.com/4219965/61030590-4c5aac00-a3f0-11e9-98ee-f1d2c285ea95.png)

**Comment by temper357** [comment]
响应式的处理方案目前没有统一的标准，需要统一梳理一下方案
