### ISSUE TITLE
页面只能新增

### ISSUE THREAD

**Issue by scglwsj** [alibaba/ice#242]
在项目页面数里只能新增页面，希望可以有编辑，重命名，删除这些操作。谢谢！

**Comment by wssgcg1213** [comment]
恩, 在计划中, 我们会尽快支持

**Comment by yujiangshui** [comment]
@scglwsj 目前我们想要了解下需求详情。

你的编辑是想编辑什么信息？是之前创建页面时选择的模块信息？比如之前选择的模块集合、排序、编辑模块名。

重命名是想命名什么信息？页面的 title 还是在 navs.js 里面的页面信息？还是页面的文件路径名？

删除是想删除路由和侧边栏的信息？还是整个 page 的文件全部删掉？

**Comment by scglwsj** [comment]
编辑就是和创建的时候能做的事是一样的。
比如我创建一个页面之后，又想添加或者修改这个页面中的组建。
重命名指的是重命名页面名称。
比如我创建了page16页面，这个名字我觉得不好，我使用的时候需要进行重命名。
删除指的是整个page全部删除，包括创建page时生成的所有文件和代码。
比如我创建了一个页面，然后立即删除它，那么我这个时候的项目应该和创建前没有任何的diff。
谢谢

**Comment by noyobo** [comment]
1. 编辑，目前无法判断创建后用户是否已经修改了源码，如果再次编辑，有可能会冲掉编辑过的代码。修改组件的行为。
2. 重命名 这个功能可以有。
3. 删除与编辑同理，如果对已有页面删除（包括编辑过的）比较高风险。

整个流程目前已在规划中，需要更简单的路由管理方案。 cc @wssgcg1213

**Comment by noyobo** [comment]
路由页面关系， routerConfig.js 以及文件由开发者管理，工具暂不做支持。
