### ISSUE TITLE
点击运行日志弹出一个空白页面

### ISSUE THREAD

**Issue by a494836960** [alibaba/ice#2420]
## 问题描述
![image](https://user-images.githubusercontent.com/11493746/61034746-6b5d3c00-a3f8-11e9-9034-98320508b01b.png)

![image](https://user-images.githubusercontent.com/11493746/61034752-71531d00-a3f8-11e9-98fe-b66273365290.png)

## 错误信息
一片空白而且无法返回，只能关闭重进

**Comment by imsobear** [comment]
- 版本
- 是否有稳定的重现路径
- 可以尝试使用 3.x beta 版本 #2369
