### ISSUE TITLE
Don't need to start the server with multiple workers

### ISSUE THREAD

**Issue by zhaofeng-shu33** [alibaba/ice#2423]
## 问题描述
In current development version of `iceworks-3.0`, the server is started with 8 workers with the `midway` framework. However, it is not necessary since the server is used as a localhost and does not have much overload. I suggest using one process is enough.

**Comment by zhaofeng-shu33** [comment]
I wonder the subprocess can really be started?
<img width="560" alt="image" src="https://user-images.githubusercontent.com/23316477/61166817-b7c68a00-a566-11e9-915a-c037de363ceb.png">
After fixing all other startup errors, I have the above error. To reproduce this error, I prepare a standalone repository:  https://dev.azure.com/freewind201301/_git/iceworks. 
(I tested the following procedure on MacOS)
1. `cnpm install`.
1. `npm run start-electron` works.
1. `npm run electron-build` passes.
1.  Start the app (located at `dist_electron/mac/`)

**Comment by zhaofeng-shu33** [comment]
I change to start a subprocess using `express`. It works in the bundled app, see https://dev.azure.com/freewind201301/_git/iceworks?version=GBexpress

**Comment by zhaofeng-shu33** [comment]
It is found that assert error occurs in `eggcore loader`. I modify `proto === EggCore.prototype` to `proto.constructor.name = EggCore.name`.

**Comment by alvinhui** [comment]
https://github.com/alibaba/ice/pull/2519
