### ISSUE TITLE
Pro 模板丢失 mock 文件并且运行时报错

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#2442]
- package.json 的 files 字段少了 mock 目录导致初始化出来的项目接口都是挂的
- 本地手动 copy mock 文件之后，退出然后用 admin/admin 登录后报错 

![image](https://user-images.githubusercontent.com/2505411/61181526-86c78180-a65a-11e9-9385-f632dbcef7f6.png)

**Comment by imsobear** [comment]
两个版本理论上都要修复下

**Comment by temper357** [comment]
* 第2个报错问题是由于icestore的bug，升到到0.2.x可解决
