### ISSUE TITLE
“初始化预览编译器...”

### ISSUE THREAD

**Issue by Hongbo-Miao** [alibaba/ice#245]
https://alibaba.github.io/ice/#/layout/header-aside-footer-responsive-layout/preview

试了Chrome, Firefox, Safari，都显示“初始化预览编译器...”

![image](https://user-images.githubusercontent.com/3375461/37177195-96eebabc-22d3-11e8-9037-ab8032882504.png)

**Comment by yujiangshui** [comment]
将在下周重构掉并发布

**Comment by wssgcg1213** [comment]
layout 的 preview 功能因为意义不大, 先下掉了, layout 详情没有提供进入预览的按钮, 手动拼接可以进入这个URL, 我增加一个判断自动跳转逻辑  cc @yujiangshui 
![image](https://user-images.githubusercontent.com/3922719/37186892-af6ef16a-2382-11e8-8687-3502b9811793.png)
