### ISSUE TITLE
Improve ordering of entries in the Router panel

### ISSUE THREAD

**Issue by tanhengyeow** [alibaba/ice#2454]
## Steps to reproduce
1. Add new page(s):
![image](https://user-images.githubusercontent.com/25320782/61206621-98c22680-a725-11e9-881b-5e47458611ed.png)

2. Observe new route(s) added:
![image](https://user-images.githubusercontent.com/25320782/61206880-40d7ef80-a726-11e9-9513-562b4369320b.png)

3. Access one of the new route(s) and the error is shown:
![image](https://user-images.githubusercontent.com/25320782/61206940-66fd8f80-a726-11e9-944d-f3f36e745154.png)

## Problem Description
This happens because the `NotFound` component is placed before the new routes.

## Workaround

Users have to manually shift the entries in `src/config/routes.js` before the `NotFound` component entry so that the new route(s) work:
![image](https://user-images.githubusercontent.com/25320782/61207290-50a40380-a727-11e9-99e8-09d27f88862d.png)

![image](https://user-images.githubusercontent.com/25320782/61207093-c9569000-a726-11e9-95c7-872ba349c6d7.png)

## Suggestions

1. Always add new routes right before the last entry in `src/config/routes.js`.
2. Allow manual reordering of entries in the `Routes` panel of `iceworks` just like the `Menu` panel.

**Comment by alvinhui** [comment]
We have already sorted router: https://github.com/alibaba/ice/blob/iceworks/3.0.2/packages/iceworks-server/src/lib/adapter/modules/router/index.ts#L210 .
And I checked that the problem was fixed.

**Comment by tanhengyeow** [comment]
Yes, I think this #2559 fixed this issue.
