### ISSUE TITLE
关于mock热更新的问题

### ISSUE THREAD

**Issue by ch11ry** [alibaba/ice#2455]
## 问题描述
mock服务没有热更新，重现步骤：
1.启动服务
2.修改mock数据结构
3.没有得到修改后的mock数据

如果需要mock生效，只能停止服务，然后重新启动服务。才能得到修改后的mock数据。

希望能够加入热更新服务，让mock实时生效

**Comment by hfuuss** [comment]
https://www.yuque.com/mou/qs3yc0/ly6cfn

**Comment by ClarkXia** [comment]
ice-scripts@2.1.10 已支持
