### ISSUE TITLE
项目支持配置面板

### ISSUE THREAD

**Issue by yujiangshui** [alibaba/ice#246]
支持项目配置面板，修改项目名等功能。

![image](https://user-images.githubusercontent.com/2942913/37187531-b17094ca-2385-11e8-8b00-a04abc480506.png)

**Comment by yuanyan** [comment]
项目名是读区package.json里的信息，可以考虑支持，目录名不建议iceworks修改，修改后风险比较大

**Comment by imsobear** [comment]
优先级不高，暂时关闭。
