### ISSUE TITLE
mock拦截不了method为get的请求

### ISSUE THREAD

**Issue by ch11ry** [alibaba/ice#2462]
## 问题描述
1.mock -> index.js对get方法进行拦截：
<img width="1439" alt="1" src="https://user-images.githubusercontent.com/35297851/61260060-6826cf00-a7af-11e9-9521-cc11da0c85c0.png">

2.在chrome的console使用fetch进行请求：
![1](https://user-images.githubusercontent.com/35297851/61259970-10886380-a7af-11e9-826f-741bcaf78900.png)
![2](https://user-images.githubusercontent.com/35297851/61259975-154d1780-a7af-11e9-91fe-818a04b093f3.png)

3.没有得到预期的结果。

**Comment by ClarkXia** [comment]
看下proxy的相关配置

**Comment by ch11ry** [comment]
> 看下proxy的相关配置

项目中没有配置proxy

**Comment by ch11ry** [comment]
在ice.config.js中配置了以下信息，导致了get没有被正常拦截：

```
devServer: {
    historyApiFallback: {
      rewrites: [{
        from: /.*/,
        to: '/index.html',
      }],
    },
  },
```
