### ISSUE TITLE
win iceworks 帮助 menu 点击没反应

### ISSUE THREAD

**Issue by yujiangshui** [alibaba/ice#248]
![image](https://user-images.githubusercontent.com/2942913/37188172-ba71502a-2388-11e8-9ec9-603c9d2f8d62.png)

**Comment by noyobo** [comment]
qq 浏览器 测试

**Comment by chenhongen** [comment]
切换电脑上的IE、FF、CHROM为默认浏览器了也试了不行。应该与浏览器无关

**Comment by yujiangshui** [comment]
@chenhongen 发了很多版本了，现在是否还存在这个问题？如果还有再打开吧

**Comment by chenhongen** [comment]
刚试了还是不行。

**Comment by noyobo** [comment]
已升级 electron 版本，最新版本是否还有问题?  @chenhongen

**Comment by chenhongen** [comment]
刚试了下 还是不可以。
