### ISSUE TITLE
can we expect the ice work in English.

### ISSUE THREAD

**Issue by saifali40** [alibaba/ice#2480]

**Comment by imsobear** [comment]
iceworks@3.0 support english, and will publish 3.0 this week. But most of the docs is still Chinese, we will translate to english next month.

**Comment by imsobear** [comment]
You can try iceworks@3.0 now:

```bash
// install CLI
$ npm i -g iceworks

// start iceworks
$ iceworks
```

If you have any questions, please reply in this issue https://github.com/alibaba/ice/issues/2369
