### ISSUE TITLE
[iceworks] 不能直接拉取内网 npm

### ISSUE THREAD

**Issue by bindoon** [alibaba/ice#2487]
## 问题描述

直接拉取内网 tnpm 源报错

![image](https://user-images.githubusercontent.com/5189853/61437403-96eba380-a96f-11e9-99c4-75820a68d023.png)

版本：3.0.0-beta.6

## 期望

能够通过前缀自动识别内网 npm 源

**Comment by imsobear** [comment]
iceworks@3.0 已解决
