### ISSUE TITLE
新建页面支持区块搜索功能

### ISSUE THREAD

**Issue by yujiangshui** [alibaba/ice#249]

**Comment by chenhongen** [comment]
- 希望新建页面能和官网一样有去看对应英文。如：通用的基本设置表单 SettingsForm；
- ~~点击 新建页面 什么都没添加直接关闭/取消 的情况下，项目也重新热加载了；~~

**Comment by yujiangshui** [comment]
已经全部支持

**Comment by chenhongen** [comment]
现在是根据 区块名称搜索的吗？我发现了一件神奇的事。
![2018-03-14_175155](https://user-images.githubusercontent.com/16499303/37395159-7cffd1ec-276d-11e8-9fff-838c7b0e9285.png)

**Comment by noyobo** [comment]
包括模块的  description 信息也会匹配。

**Comment by chenhongen** [comment]
get
