### ISSUE TITLE
新建页面名称修改错别字 + 支持中文

### ISSUE THREAD

**Issue by yujiangshui** [alibaba/ice#250]
![image](https://user-images.githubusercontent.com/2942913/37197758-ea6453a8-23b6-11e8-815c-0535e0dbdfc8.png)

![image](https://user-images.githubusercontent.com/2942913/37197775-f5751a2a-23b6-11e8-9e87-8942eb90a1df.png)

**Comment by noyobo** [comment]
新增 导航名，对应 text 字段

**Comment by noyobo** [comment]
![image](https://user-images.githubusercontent.com/1292082/37970727-c1f5f850-3206-11e8-9e14-1238faa803a5.png)
