### ISSUE TITLE
使用ice-devtools新建vue物料模板失败

### ISSUE THREAD

**Issue by yin-shu** [alibaba/ice#2503]
系统：macOs 10.13.6
node:  v11.12.0
ice-devtools版本：2.4.0

## 问题描述
使用ice-devtools新建vue物料模板失败

## 错误信息

![image](https://user-images.githubusercontent.com/29432662/61530815-b4943800-aa57-11e9-9ef6-facbfea3c31c.png)

**Comment by imsobear** [comment]
模板忘记发版本了，已修复，重试下。
