### ISSUE TITLE
ice-scripts 为何运行需要联网

### ISSUE THREAD

**Issue by TrumanDu** [alibaba/ice#2517]
## 问题描述

ice-scripts 为何运行需要联网
## 错误信息
每次运行等待时间特别长

**Comment by ClarkXia** [comment]
目前运行前会有一个版本检测的逻辑

**Comment by TrumanDu** [comment]
@ClarkXia 有没有禁用机制？，每次运行程序都太慢了，只有网络超时才能运行起来

**Comment by imsobear** [comment]
@ClarkXia 评估下这个功能是否还需要

**Comment by ClarkXia** [comment]
> @ClarkXia 评估下这个功能是否还需要

提示更新的功能可以保留，可以通过社区的一些方案比如 `update-notifier` 优化成进程退出时进行更新提示

**Comment by imsobear** [comment]
@TrumanDu 你暂时先可以通过 `npm config set registry=https://registry.npm.taobao.org/` 换成淘宝源，这个步骤会快很多。

**Comment by TrumanDu** [comment]
嗯，因为特殊原因，本地源暂时不能修改，目前通过切换代理能快一点，等待你们最新解决办法，感谢

**Comment by imsobear** [comment]
> 嗯，因为特殊原因，本地源暂时不能修改，目前通过切换代理能快一点，等待你们最新解决办法，感谢

OK，了解，或者 `REGISTRY=https://registry.npm.taobao.org/ npm run start` 也可以哈

**Comment by ClarkXia** [comment]
ice-scripts 2.1.6 版本已移除版本检测
