### ISSUE TITLE
生成的路由配置放在了最顶端导致页面渲染为空

### ISSUE THREAD

**Issue by yujiangshui** [alibaba/ice#2521]
##  问题描述

首先创建一个页面，路由填写 `/test2`，之后生成的路由配置如下：

![image](https://user-images.githubusercontent.com/2942913/61704394-b6cbfe80-ad97-11e9-9dbf-e95ceaa5a620.png)

之后打开页面：`http://localhost:4445/#/test2` 页面为空：

![image](https://user-images.githubusercontent.com/2942913/61704534-03173e80-ad98-11e9-9eb1-4fcea9eeea4a.png)

将路由配置调整顺序或者位置后：

![image](https://user-images.githubusercontent.com/2942913/61704637-470a4380-ad98-11e9-8934-a3f1eb9fe628.png)

可以正常渲染：

![image](https://user-images.githubusercontent.com/2942913/61704595-2d68fc00-ad98-11e9-918e-548c3c0519c2.png)

**Comment by chenbin92** [comment]
@yujiangshui 这个是模板的路由渲染逻辑问题，改成如下形式就好，详见代码：https://github.com/ice-lab/react-materials/blob/master/scaffolds/ice-design-pro/src/router.jsx#L61

```jsx
<Suspense fallback={<PageLoading />}>
    {
       RouteItem({
          key: id,
           ...props,   // 这里改成 ... route
      })
    }
</Suspense>
```

**Comment by chenbin92** [comment]
@yujiangshui 在模板层已修复

**Comment by yujiangshui** [comment]
好的，我等再试试
