### ISSUE TITLE
 ice 组件体积过大

### ISSUE THREAD

**Issue by demohi** [alibaba/ice#2525]
## 基本规范
"@alifd/next": "^1.15.5",
"ice-scripts": "^2.1.2",

## 问题描述

![image](https://user-images.githubusercontent.com/1209159/61770304-85971100-ae1f-11e9-8c0e-ac2c962a188e.png)
![image](https://user-images.githubusercontent.com/1209159/61770319-8b8cf200-ae1f-11e9-9804-004f6a880d01.png)

另外 core.js 在中后台场景是否可选

## 错误信息

fusion 组件体积太多，是否有优化的可能

**Comment by ClarkXia** [comment]
> 另外 core.js 在中后台场景是否可选

可以在 ice.config.js 中指定 targets，比如：
```js
targets: {
    chrome: 75,
},
```
