### ISSUE TITLE
StyledMenu组件配合Link使用点击无法跳转问题

### ISSUE THREAD

**Issue by ylfeng250** [alibaba/ice#2538]
` import StyledMenu from '@icedesign/styled-menu'` 与 `import { Link } from 'react-router-dom'` 配合设计导航的时候，会出现点击无法跳转的问题。
![image](https://user-images.githubusercontent.com/26338012/61860144-0e837a80-aefc-11e9-8d67-e16668185a5f.png)
```jsx
 <MenuItem key={item.key}>
    <Link {...linkProps} className={styles['link']}>
    {item.name}
  </Link>
</MenuItem>
```
发现是默认设置了padding，这样就会在点击红色框的时候无法触发Link的点击事件，建议取消padding或者修改为margin，感觉在横向状态下设置为margin合理一些

**Comment by daysai** [comment]
> 状态下设置为margin合理一些
敬请关注
https://github.com/ice-lab/react-materials/pull/111
