### ISSUE TITLE
[RFC] 桌面软件版本的维护及升级策略

### ISSUE THREAD

**Issue by alvinhui** [alibaba/ice#2543]
### 维护策略

- 2.0 发布最后一个版本（[2.23.0](https://github.com/alibaba/ice/pull/2529)），后续将不投入维护；
- 如果有用户反馈问题，则让用户安装 iceworks 3.0 CLI 版本。

### 升级策略

- 区分 2.0 版本和 3.0 版本的自动升级检测地址，确保 2.0 不会收到 3.0 的更新信息；
- 代码层面在 2.23.0 上不允许自动升级到 3.0；
- 在 2.23.0 版本上透出下载 iceworks 3.0 CLI 版本的提醒。

### 维护策略

- 启动性问题
    - 确保正常情况下能够启动，有问题需要解决，优先级低；
    - 启动失败透出日志和使用 CLI 版本的提醒。
- 功能性问题
    - 通用、重要的 Bug 需要解决，优先级低；
    - 特殊系统版本的 Bug 不需要解决，直接让用户使用 CLI 版本；

### 升级策略

- 整体软件：有自动升级逻辑，与 2.0 版本一致；
- iceworks-server: 启动时检查版本，有新版则自动更新。

## 数据统计

需明确当前的 DAU 中的以下数据分布：

- 桌面版和 CLI 版本占比，目标 CLI 版本占比大于 90%；
- 桌面版不同的版本间的占比，目标 2.23.0 和 3.0.0 占比大于 80%。

**Comment by alvinhui** [comment]
@imsobear @chenbin92

**Comment by ilovejs** [comment]
aliyun 海外下载太慢了 https://iceworks.oss-cn-hangzhou.aliyuncs.com/3.0/win/iceworks-setup-3.0.0.exe  @alvinhui

**Comment by xiaoliang2233** [comment]
请问弃用 electron 的原因是什么呀

**Comment by imsobear** [comment]
@xiaoliang2233 因为我们后续要做云化的产品，Web 的方式未来更好迁移复用。
