### ISSUE TITLE
[RFC] iceworks cra 物料源添加方式

### ISSUE THREAD

**Issue by temper357** [alibaba/ice#2548]
问题：目前 iceworks 官方的物料源只提供飞冰和 vue 物料，讨论下 cra 物料源通过什么方式透出比较合适

方案：直接放在 [官方推荐物料] 下面，同时将 [官方推荐物料] 改名为 [官方物料]，以与[自定义物料]概念上有更好的对应

另外，对于内网用户由于中后台体系统一用的是飞冰，是否有必要透出 vue 和 cra 物料？

**Comment by chenbin92** [comment]
> 另外，对于内网用户由于中后台体系统一用的是飞冰，是否有必要透出 vue 和 cra 物料？

对内网不会透出 vue 和 cra 物料，这个是确定的

对外默认透出 vue 和 cra 物料，但是不会放在官方物料下面，考虑如下：
1. 官方没有足够的精力去维护 vue 和 cra 物料，很难保证优质
2. vue 和 cra 由社区去维护，作为推荐物料源内置

## 分层上：

* 推荐物料：（官方物料也属于推荐物料，不用刻意提官方物料）
   * ice material
   * vue material
* 自定义物料：
   * xxx

**Comment by imsobear** [comment]
cra 放文档里就可以，不用放推荐里
