### ISSUE TITLE
登录页完善

### ISSUE THREAD

**Issue by williamwang2015** [alibaba/ice#256]
能否在登录页增加登录失败的错误提示信息？

**Comment by chenbin92** [comment]
@williamwang2015  可以有，预计在下周二发布

**Comment by williamwang2015** [comment]
看了最新发布的版本，怎么没找到显示错误信息的地方，看到用户名和密码下面有显示错误的信息，但是显示一些通用信息的地方还是没找到。比如只想提示用户”用户名或密码错误“而不明确提示用户名错误还是密码错误

**Comment by chenbin92** [comment]
@williamwang2015 

错误提示自定义有两种方式：

1. 通过 `IceFormError`，参考：[FormBinder](https://alibaba.github.io/ice/#/component/formbinder)

```
<IceFormError name="" />
```

2. 在提交前统一处理

```
handleSubmit = (e) => {
    e.preventDefault();
    this.refs.form.validateAll((errors, values) => {
      if (errors) {
         //  
      }
      
    });
  };
```
