### ISSUE TITLE
iceworks 3.0 问题记录

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#2568]
1. 【Fixed】notfound project 提示

![image](https://user-images.githubusercontent.com/3995814/62094848-199a2a00-b2b1-11e9-9da2-e4b2b8b2b150.png)

2.  【Fixed】官网在 Safari 浏览器显示问题

![image](https://user-images.githubusercontent.com/3995814/62095552-5cf59800-b2b3-11e9-91f5-3e7d9be40222.png)

3.  【Fixed】 `adapter/modules/page/template.jsx.ejs` 不会被打包到 dist 目录

![image](https://user-images.githubusercontent.com/3995814/62098194-fd4fba80-b2bb-11e9-850a-9d7c5afe609a.png)

**Comment by we6288815** [comment]
Windows 10, node: v10.16.0
使用模板项目：pro-scaffold
初始安装依赖时出错，无法安装：
![image](https://user-images.githubusercontent.com/8169722/62095553-5d8e2e80-b2b3-11e9-9291-b6f7175e66eb.png)

切换cnpm源时，控制台显示如下错误：
![image](https://user-images.githubusercontent.com/8169722/62095578-6979f080-b2b3-11e9-8685-c55285bcf59f.png)

![image](https://user-images.githubusercontent.com/8169722/62095493-2d469000-b2b3-11e9-8f69-e5dd6f4be9a4.png)

**Comment by alvinhui** [comment]
自动升级 iceworks-server：
![image](https://user-images.githubusercontent.com/4392234/62106504-f59e0f00-b2d7-11e9-9dd3-3d7b6b1f8ed1.png)

系统信息：macOS

![image](https://user-images.githubusercontent.com/4392234/62106539-0d759300-b2d8-11e9-94a1-9379f0efe27f.png)

**Comment by huixisheng** [comment]
![image](https://user-images.githubusercontent.com/1518967/62264533-dbd50700-b452-11e9-91e8-0cd814d98740.png)
导入时候项目管理会出现2个。创建的时候也一样

**Comment by huixisheng** [comment]
创建项目的时候，不支持选择 koa. 2.x 的版本是可以的。

**Comment by huixisheng** [comment]
![image](https://user-images.githubusercontent.com/1518967/62264710-b1d01480-b453-11e9-8dc4-8eb5e4290e49.png)
启动服务出现乱码

**Comment by huixisheng** [comment]
![image](https://user-images.githubusercontent.com/1518967/62269807-c8339b80-b466-11e9-9b15-750c67337418.png)
创建页面报错

**Comment by chenbin92** [comment]
> ![image](https://user-images.githubusercontent.com/1518967/62269807-c8339b80-b466-11e9-9b15-750c67337418.png)
> 创建页面报错

已修复，更新一下 iceworks-core 到 3.0.2 版本

**Comment by chenbin92** [comment]
![image](https://user-images.githubusercontent.com/3995814/62278123-08504980-b47a-11e9-9371-38c83973eb19.png)

**Comment by huixisheng** [comment]
![image](https://user-images.githubusercontent.com/1518967/62287667-1196e180-b48d-11e9-80ca-e6fd760162bb.png)

**Comment by huixisheng** [comment]
> > ![image](https://user-images.githubusercontent.com/1518967/62269807-c8339b80-b466-11e9-9b15-750c67337418.png)
> > 创建页面报错
> 
> 已修复，更新一下 iceworks-core 到 3.0.2 版本

升级后还是存在

**Comment by gyh9457** [comment]
window 下只能选择 C盘, 且创建时无权限创建文件，手动创建文件后也会socket 连接失败，本地服务挂掉。

**Comment by chenbin92** [comment]
报错日志优化， UI 上报错信息应该稍微详细一点 @imsobear 

![image](https://user-images.githubusercontent.com/3995814/62437143-9d9e5700-b774-11e9-8211-3372068993fd.png)

**Comment by alvinhui** [comment]
删除项目 package.json 后启动 iceworks 异常

![image](https://user-images.githubusercontent.com/3995814/62188130-12047f00-b39e-11e9-9973-193b5130263c.png)

**Comment by alvinhui** [comment]
新建项目和导入项目在 windows 只能选择 C 盘

**Comment by alvinhui** [comment]
启动端口占用

![image](https://user-images.githubusercontent.com/3995814/62095096-ea37ed00-b2b1-11e9-845d-5b45f794fa08.png)

**Comment by alvinhui** [comment]
socket 自动断开连接

![image](https://user-images.githubusercontent.com/3995814/62095025-a5ac5180-b2b1-11e9-94f6-56a77761880c.png)

![image](https://user-images.githubusercontent.com/3995814/62095053-c83e6a80-b2b1-11e9-96d2-297eec9408cf.png)

**Comment by alvinhui** [comment]
> 创建项目的时候，不支持选择 koa。 2.x 的版本是可以的。

3.0 上不考虑支持了。
