### ISSUE TITLE
提供一套空白模版

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#257]
![image](https://user-images.githubusercontent.com/3995814/37240646-6cb2e996-2489-11e8-91b7-101ef27a53c0.png)

**Comment by mowatermelon** [comment]
小小建议
- 首先 默认模版选择中 应该有一个只有一个welcome页 的模版选择
- 项目模版除了默认的（welcome, lite.pro,cms），应该还有一个更多选择（感觉可以链接到新建页面功能页）
- 更多选择中，可以制定单页面（拼接了几个物料）作为项目的模版，也可以选择多个页面组合（比如login页和index页的组合）作为项目的模版
- 以上

**Comment by yujiangshui** [comment]
@mowatermelon 收到，感谢建议

**Comment by noyobo** [comment]
ice-design-lite 模板, 同时目前也可通过自定义模板创建。
