### ISSUE TITLE
新建页面选了区块后提示权限不够，保存不成功

### ISSUE THREAD

**Issue by nancyfrx** [alibaba/ice#2570]
## 
![图片](https://user-images.githubusercontent.com/38973280/62099465-b1534480-b2c0-11e9-8345-e75c56e034c0.png)

**Comment by nancyfrx** [comment]
windows 10 操作系统

**Comment by chenbin92** [comment]
@nancyfrx 麻烦详细描述一下操作路径，Node 版本，Windows 还是 Mac 设备等信息

**Comment by chenbin92** [comment]
@nancyfrx 麻烦详细描述一下操作路径，Node 版本，Windows 还是 Mac 设备等信息

**Comment by nancyfrx** [comment]
![图片](https://user-images.githubusercontent.com/38973280/62099564-1313ae80-b2c1-11e9-8c9d-d5ac694baf88.png)
![图片](https://user-images.githubusercontent.com/38973280/62099588-29ba0580-b2c1-11e9-9840-5410c04148da.png)

**Comment by nancyfrx** [comment]
![图片](https://user-images.githubusercontent.com/38973280/62099619-435b4d00-b2c1-11e9-820c-b789feca345b.png)

**Comment by nancyfrx** [comment]
node  :v10.16.0 
npm : 6.10.2

**Comment by Chinafree** [comment]
同样的问题，因为C盘没写入权限(猜测)，而飞冰只能选C盘空间作为项目路径，导致无法创建页面。
报错貌似是从临时目录拷贝到项目目录？
而且通常使用管理员权限就可以解决的此类问题，在Power Shell和cmd都使用管理权限也无法解决。
2019-08-01 02:59:20,889 ERROR 7360 nodejs.EPERMError: EPERM: operation not permitted, rename 'C:\Users\18610\AppData\Local\Temp\BoardList\src' -> 'C:\Users\18610\Documents\icepro\src\pages\todo\components\BoardList'
EPERMError: EPERM: operation not permitted, rename 'C:\Users\18610\AppData\Local\Temp\BoardList\src' -> 'C:\Users\18610\Documents\icepro\src\pages\todo\components\BoardList'
errno: -4048
code: "EPERM"
syscall: "rename"
path: "C:\\Users\\18610\\AppData\\Local\\Temp\\BoardList\\src"
dest: "C:\\Users\\18610\\Documents\\icepro\\src\\pages\\todo\\components\\BoardList"
name: "EPERMError"
pid: 7360
hostname: wang


npm -version
6.4.1
 node -v
v10.15.3


> @nancyfrx 麻烦详细描述一下操作路径，Node 版本

**Comment by alvinhui** [comment]
https://github.com/alibaba/ice/pull/2576
