### ISSUE TITLE
预览几个模板，在chrome下有抖动

### ISSUE THREAD

**Issue by C4o** [alibaba/ice#2572]
## 问题描述
预览https://unpkg.com/@icedesign/project-management-admin@latest/build/index.html
问题同#2342 
在win10和mac下的chrome最新版 都出现抖动 firefox正常

## 错误信息
不是做前端的 所以跟踪不出什么问题 不好意思

**Comment by imsobear** [comment]
@C4o 这个 issue 我关掉了，我们统一在 2342 这个 issue 里跟进哈
