### ISSUE TITLE
添加fusion物料失败

### ISSUE THREAD

**Issue by zy4726** [alibaba/ice#2577]
## 问题描述

从Fusion design的工具页面，拷贝的链接，在飞冰3.0里添加失败。
fusion design的说明写的是
![image](https://user-images.githubusercontent.com/52158058/62205956-3e7ec200-b3c3-11e9-87c7-b1be917f71ed.png)

**Comment by chenbin92** [comment]
Fixed https://github.com/alibaba/ice/pull/2567/commits/8b08b1de8b4296389f0dc1c5c51fa8d53b87c459
