### ISSUE TITLE
ice-devtools@2.4.2 新增物料无法引用本地模板

### ISSUE THREAD

**Issue by jndxzqc** [alibaba/ice#2580]
## 问题描述

安装最新版本ice-devtools，然后在根目录下执行
``` 
idev add
```

无法添加物料，控制台会报错

![image](https://user-images.githubusercontent.com/5928280/62268392-5b1e0700-b462-11e9-91a2-a184b2912cfb.png)

本地template目录：
![image](https://user-images.githubusercontent.com/5928280/62268511-a6d0b080-b462-11e9-984f-aa9bb9ff2e7b.png)

ps：2.3.3版本正常

## 错误信息

见上述截图

**Comment by imsobear** [comment]
本地模板遇到一个比较严重的问题：内置的工程目录规范等难以跟随官方版本升级，因此 2.4.0 里移除了这个能力，如有自定义模板需求我们希望能统一放到官方的代码仓库里。
