### ISSUE TITLE
[iceworks 3.0] iceworks-server unable to start if project directory is not present in local environment

### ISSUE THREAD

**Issue by tanhengyeow** [alibaba/ice#2585]
## Steps to reproduce
1. Start `iceworks`. Make sure that there is at least 1 project in `iceworks`:
![image](https://user-images.githubusercontent.com/25320782/62278175-24ec8180-b47a-11e9-9c5b-7809350a15f9.png)

2. Delete the project from your local environment.

3. Stop running `iceworks-server` e.g. running `Ctrl + C`.

4. Start `iceworks-server` again by running `npm run dev`.

5. A similar error message would be shown and `iceworks-server` can't be started anymore:
![image](https://user-images.githubusercontent.com/25320782/62278335-6f6dfe00-b47a-11e9-9e24-5781d69c0fb6.png)

## Suggestions
- Allow `iceworks-server` to still execute but indicate an error in the UI.

## Temporary workaround
- Delete your project entry in `~/.iceworks/db.json`.

**Comment by alvinhui** [comment]
also check package.json

**Comment by alvinhui** [comment]
@tanhengyeow cloud you please fix this problem in https://github.com/alibaba/ice/pull/2590 ?
