### ISSUE TITLE
手动删除项目目录会出现缓存问题。导致无法启动iceworks

### ISSUE THREAD

**Issue by renshunli** [alibaba/ice#2587]
iceworks@3.0.1
npm@6.9.0
node@v10.16.1
macOS@10.12.6

## 问题描述
报错后一直starting iceworks 必须重新在原目录地址新建iceDemo目录并且创建个package.json才能启动成功。重新安装iceworks删除iceworks 等都无法解决。

问题步骤
web页面中创建项目myIceDemo
手动去系统目录中把myIceDemo删除掉
重启iceworks

## 错误信息

![image](https://user-images.githubusercontent.com/20764151/62286497-6b49dc80-b48a-11e9-85fe-dd7b0211ac9b.png)
![image](https://user-images.githubusercontent.com/20764151/62286513-71d85400-b48a-11e9-88c2-47519f4c4d90.png)

**Comment by imsobear** [comment]
可以先手动修改 `~/.iceworks/db.json` 这个文件的内容，这个问题下个版本会解决。

重复问题 https://github.com/alibaba/ice/issues/2585
