### ISSUE TITLE
linux版具体发布时间

### ISSUE THREAD

**Issue by g770728y** [alibaba/ice#259]
刚开始做新产品，看能不能赶上^_^
#112

**Comment by noyobo** [comment]
3.15 提供预览版使用

**Comment by smileboywtu** [comment]
期待啊 明天发布是吧

**Comment by noyobo** [comment]
linux 系统遇到些问题 😭

**Comment by noyobo** [comment]
对不住呀各位，现在遇到点问题，打包要稍微晚几天。有进展我会回复在这里。

**Comment by yeeez** [comment]
期待中...

**Comment by smileboywtu** [comment]
等待中，如果需要协助，我可以贡献点时间，我对 python 比较熟悉

**Comment by kribeel** [comment]
我也是来期待Linux版的

**Comment by noyobo** [comment]
进展 linux 已可启动，部分功能还需要兼容。
第一次用  linux 还需要些时间。

![default](https://user-images.githubusercontent.com/1292082/37895970-528add56-3115-11e8-94bb-17fe34152bbd.png)

**Comment by smileboywtu** [comment]
thx 期待已久
