### ISSUE TITLE
Windows10自带的linux上无法安装iceworks

### ISSUE THREAD

**Issue by lip0091981** [alibaba/ice#2593]
## 问题描述

直接执行npm install iceworks -g

## 错误信息

2291 warn tar zlib: Cannot read property 'length' of null
2292 warn tar zlib: Cannot read property 'length' of null
2293 warn tar zlib: Cannot read property 'length' of null
2294 warn tar zlib: Cannot read property 'length' of null
2295 warn tar zlib: Cannot read property 'length' of null
2296 warn tar zlib: Cannot read property 'length' of null
2297 warn tar zlib: Cannot read property 'length' of null
2298 warn tar zlib: Cannot read property 'length' of null
2299 warn tar zlib: Cannot read property 'length' of null
2300 warn tar zlib: Cannot read property 'length' of null
2301 warn tar ENOENT: no such file or directory, open '/usr/local/lib/node_modules/.staging/async-1ee8f05b/LICENSE'
2302 warn tar ENOENT: no such file or directory, open '/usr/local/lib/node_modules/.staging/async-1ee8f05b/CHANGELOG.md'
2303 warn tar zlib: Cannot read property 'length' of null
2304 verbose unlock done using /root/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
2305 timing stage:rollbackFailedOptional Completed in 1ms
2306 timing stage:runTopLevelLifecycles Completed in 7855ms
2307 verbose stack ZlibError: zlib: Cannot read property 'length' of null
2307 verbose stack     at Unzip.Zlib.(anonymous function) (/usr/local/lib/node_modules/npm/node_modules/minizlib/index.js:126:21)
2307 verbose stack     at Unzip.write (/usr/local/lib/node_modules/npm/node_modules/minizlib/index.js:247:21)
2307 verbose stack     at Unzip.flush (/usr/local/lib/node_modules/npm/node_modules/minizlib/index.js:206:10)
2307 verbose stack     at Unzip.end (/usr/local/lib/node_modules/npm/node_modules/minizlib/index.js:213:10)
2307 verbose stack     at Unpack.end (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:416:21)
2307 verbose stack     at PassThrough.onend (_stream_readable.js:598:10)
2307 verbose stack     at Object.onceWrapper (events.js:254:19)
2307 verbose stack     at PassThrough.emit (events.js:164:20)
2307 verbose stack     at endReadableNT (_stream_readable.js:1054:12)
2307 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
2307 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
2308 verbose cwd /
2309 verbose Linux 4.4.0-17134-Microsoft
2310 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "iceworks" "-g"
2311 verbose node v9.2.0
2312 verbose npm  v6.10.2
2313 error zlib: Cannot read property 'length' of null
2314 verbose exit [ 1, true ]

**Comment by lip0091981** [comment]
一开始报没有权限，我把npm从5.5升级到6.10后就变成这个错了，请大佬帮忙解决下

**Comment by lip0091981** [comment]
5030 info lifecycle iceworks@3.0.1~postinstall: Failed to exec postinstall script
5031 timing action:postinstall Completed in 110ms
5032 verbose unlock done using /root/.npm/_locks/staging-81962f79a370deea.lock for /root/.nvm/versions/node/v10.16.1/lib/node_modules/.staging
5033 timing stage:rollbackFailedOptional Completed in 43008ms
5034 timing stage:runTopLevelLifecycles Completed in 75679ms
5035 verbose stack Error: iceworks@3.0.1 postinstall: `node ./lib/downloadServer.js`
5035 verbose stack spawn ENOENT
5035 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v10.16.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
5035 verbose stack     at ChildProcess.emit (events.js:198:13)
5035 verbose stack     at maybeClose (internal/child_process.js:982:16)
5035 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
5036 verbose pkgid iceworks@3.0.1
5037 verbose cwd /root
5038 verbose Linux 4.4.0-17134-Microsoft
5039 verbose argv "/root/.nvm/versions/node/v10.16.1/bin/node" "/root/.nvm/versions/node/v10.16.1/bin/npm" "install" "iceworks" "-g"
5040 verbose node v10.16.1
5041 verbose npm  v6.9.0
5042 error file sh
5043 error code ELIFECYCLE
5044 error errno ENOENT
5045 error syscall spawn
5046 error iceworks@3.0.1 postinstall: `node ./lib/downloadServer.js`
5046 error spawn ENOENT
5047 error Failed at the iceworks@3.0.1 postinstall script.
5047 error This is probably not a problem with npm. There is likely additional logging output above.
5048 verbose exit [ 1, true ]

**Comment by lip0091981** [comment]
卸载了nodejs， npm然后用nvm安装了nodejs，仍然报错
> iceworks@3.0.1 postinstall /root/.nvm/versions/node/v10.16.1/lib/node_modules/iceworks
> node ./lib/downloadServer.js

sh: 1: node: Permission denied
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! iceworks@3.0.1 postinstall: `node ./lib/downloadServer.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the iceworks@3.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-08-04T02_54_50_335Z-debug.log

**Comment by chenbin92** [comment]
参考下面文档进行解决
https://ice.work/docs/iceworks/Installation#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
