### ISSUE TITLE
希望增加抽屉式弹窗

### ISSUE THREAD

**Issue by iamcaochong** [alibaba/ice#2594]
## 问题描述

目前很多网站都使用了体验更好的抽屉式弹窗，比如隔壁的 (https://ant.design/components/drawer-cn/)  ,而我们ice的dialog弹窗仍然只有居中显示，希望大佬们后面可以加一个类似的组件，或者在dialog中加一个配置，跟乐高类似。

**Comment by youluna** [comment]
关注 https://github.com/alibaba-fusion/next/issues/955
