### ISSUE TITLE
 iceworks CLI 详细安装文档

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#2596]
## 背景
在 iceworks 3.0 中主要使用链路是 CLI 的方式，从用户反馈来看，很多卡在安装 CLI 的过程中，导致无法继续使用。

![image](https://user-images.githubusercontent.com/3995814/62433945-27e0be00-b769-11e9-9914-2d8551ba9df2.png)

![image](https://user-images.githubusercontent.com/3995814/62434063-b05f5e80-b769-11e9-8bce-23f395dd8b65.png)

## 解决

新增一篇 iceworks `安装教程`，包含 Node/Npm 基础环境以及安装常见问题，收集汇总更详细的相关安装问题和解决方案进行汇总，以便对号入座进行解决；

**Comment by ilovejs** [comment]
@alvinhui  https://gist.github.com/ilovejs/a9c444159999c6cfd3282423211c69a4 My notes for installation on windows 10

**Comment by GYDSB** [comment]
有解决么？ @chenbin92 sudo npm install -g iceworks --unsafe-perm=true --allow-root 通过这个安装成功，但是启动时候还是没有权限的错误

**Comment by chenbin92** [comment]
> 有解决么？ @chenbin92 sudo npm install -g iceworks --unsafe-perm=true --allow-root 通过这个安装成功，但是启动时候还是没有权限的错误

具体错误贴一下

**Comment by chenbin92** [comment]
## Npm 安装各种错误

![image](https://user-images.githubusercontent.com/3995814/62522524-732bc700-b864-11e9-9bed-96284977eec0.png)

![image](https://user-images.githubusercontent.com/3995814/62522541-79ba3e80-b864-11e9-913b-72e619fbc94b.png)

![image](https://user-images.githubusercontent.com/3995814/62522634-aa01dd00-b864-11e9-9934-7dc1262d7c91.png)

![image](https://user-images.githubusercontent.com/3995814/62524069-9146f680-b867-11e9-8022-f4b455107e7d.png)
