### ISSUE TITLE
Pro-scaffold's dependencies failed to install

### ISSUE THREAD

**Issue by alvinhui** [alibaba/ice#2607]
@we6288815 

## 信息

- Windows 10,
- node: v10.16.0
- 使用模板项目：pro-scaffold

## 现象

初始安装依赖时出错，无法安装：

![image](https://user-images.githubusercontent.com/8169722/62095553-5d8e2e80-b2b3-11e9-9291-b6f7175e66eb.png)

切换cnpm源时，控制台显示如下错误：

![image](https://user-images.githubusercontent.com/8169722/62095578-6979f080-b2b3-11e9-8685-c55285bcf59f.png)

![image](https://user-images.githubusercontent.com/8169722/62095493-2d469000-b2b3-11e9-8f69-e5dd6f4be9a4.png)

copy from: https://github.com/alibaba/ice/issues/2568#issuecomment-516232616

**Comment by chenbin92** [comment]
## 问题分析

在设置面板将包管理工具设置为 cnpm 源，但用户系统并没有安装 cnpm 源，如果项目在安装依赖时则会出现上述错误问题

## 解决方案
在设置面板切换包管理工具时，增加检查环境，即调用接口执行 `cnpm -V` 进行检查，如果有对应的版本则进行设置，如果没有则提示系统无 cnpm 工具，提示用户安装 cnpm 工具

目前只需要对 cnpm 进行检查，tnpm 会根据内网环境默认安装，npm 是使用 iceworks-cli 的基础条件不需要检查

## 讨论

- 提示 cnpm 不存在时是否需要给个选项 「点击安装」的功能，即 spawn 一个 npm install cnpm -g 的操作

**Comment by alvinhui** [comment]
这个问题我感觉跟 [ice-scripts 未安装](https://github.com/alibaba/ice/issues/2677#issuecomment-520330418)一样，解决完乱码问题是否就 OK 了？这类基础环境，可以自己安装。

**Comment by chenbin92** [comment]
> 这个问题我感觉跟 [ice-scripts 未安装](https://github.com/alibaba/ice/issues/2677#issuecomment-520330418)一样，解决完乱码问题是否就 OK 了？这类基础环境，可以自己安装。

这里是两个问题：
1. 乱码问题，在另外的 MR 已解
2. `Error spawn cnpm ENOENT`
上面讨论的是第二个问题，我认为这里至少需要给出弹出提示，不然就是功能的不完整性，用户的操作途径是 1）在设置面板设置为 cnpm，2）安装依赖后端报错 3）前端无任何反馈 4）懵了

**Comment by chenbin92** [comment]
## 结论

1. 解决乱码问题
2. 现在只在后台抛出了错误前端无任何反馈和错误提示，改为在 iceworks 终端日志流直接抛出 `Error spawn cnpm ENOENT`
