### ISSUE TITLE
Encode error for log

### ISSUE THREAD

**Issue by alvinhui** [alibaba/ice#2608]
@huixisheng 

![image](https://user-images.githubusercontent.com/1518967/62264710-b1d01480-b453-11e9-8dc4-8eb5e4290e49.png)

copy from: https://github.com/alibaba/ice/issues/2568#issuecomment-517109107

**Comment by alvinhui** [comment]
![image](https://user-images.githubusercontent.com/4392234/62506644-11ebff80-b834-11e9-8a75-fdc6cadec5b8.png)

**Comment by chenbin92** [comment]
问题原因：https://www.infoq.cn/article/nodejs-about-buffer
