### ISSUE TITLE
关于软件操作日志文件夹

### ISSUE THREAD

**Issue by mowatermelon** [alibaba/ice#261]
> 建议原因

- 使用ice一段时间后，在软件中新建项目，或者做其他操作的时候，出现问题，需要查看软件操作日志
- 可是在原有设计中所有日志都放在一个log.log文件中，这样我需要看很多其他的不需要的日志信息，我才查看操作当天错误记录，感觉体验有点不太好

> 具体描述

- 软件操作日志主要是记录在安装路径中的log文件夹中
- 操作日志以天为单位，来对软件操作进行记录，举个栗子，ice_log_2018_03_12.log
- 软件中提供一个清除日志的功能入口，提供清除最近七天，最近一个月，最近半年，或者自定义天数的操作日志，具体绑定事件是，清除log文件夹中对应天数的log文件
- 软件原有的查看操作日志功能入口，绑定的是每天对应的log文件

**Comment by noyobo** [comment]
非常好的建议 👍

**Comment by yuanyan** [comment]
@noyobo 可以看下社区是不是已经有实现这些功能
