### ISSUE TITLE
Differentiate "operation log" or "process log" in the GlobalLog Panel

### ISSUE THREAD

**Issue by alvinhui** [alibaba/ice#2611]
Now all logs show in GlobalLog Panel:

![image](https://user-images.githubusercontent.com/4392234/62452214-5038de80-b7a2-11e9-959a-b72de7e079b2.png)

We plan to differentiate "Operation log" or "Process log" in the GlobalLog Panel:

- Operation log, records of your operations in iceworks, such as:
    - Created a project;
    - Created a page;
    - Deleted a page;
    - ...
- Process log, program flow output caused by operation, such as:
    - Console output when installing dependencies;
    - Console output at debug service startup;
    - ...

**Comment by chenbin92** [comment]
https://github.com/alibaba/ice/pull/2599
