### ISSUE TITLE
推荐 CRA 和 Vue 物料未展示

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#2617]
## 默认推荐物料源
![image](https://user-images.githubusercontent.com/3995814/62506895-f9c8b000-b834-11e9-96c8-1ee6cb9397ed.png)

## 界面展示

![image](https://user-images.githubusercontent.com/3995814/62506967-37c5d400-b835-11e9-9322-9cbee3b87294.png)

## 解决方案

在物料菜单栏新增「刷新按钮」，将默认物料源强制更新一遍

![image](https://user-images.githubusercontent.com/3995814/62507435-f59d9200-b836-11e9-832e-18631ce7a10b.png)

**Comment by imsobear** [comment]
如果只是重置推荐物料的话，建议把按钮放在推荐物料的后面

**Comment by chenbin92** [comment]
内网不展示 vue 和 cra 的物料
