### ISSUE TITLE
组件库的代码不开源吗？

### ISSUE THREAD

**Issue by mosikoo** [alibaba/ice#262]
我找了半天没找到

**Comment by chenhongen** [comment]
icework创建对应的页面就能看到了。。。

**Comment by mosikoo** [comment]
@chenhongen https://alibaba.github.io/ice/#/component/form, 这个form所对应代码的github链接在哪

**Comment by wssgcg1213** [comment]
@mosikoo 组件部分的开源已经在路上了, 我们近期会逐步把组件代码开源出来, 最快这周
