### ISSUE TITLE
Permission denied when iceworks-server is started

### ISSUE THREAD

**Issue by alvinhui** [alibaba/ice#2624]
![image](https://user-images.githubusercontent.com/4392234/62520587-7755e580-b860-11e9-954e-cff8d7820244.png)

Commands for user operations:
```
$ npm install iceworks -g
$ iceworks
```

Try to use following commands can solve the problem:

```
$ npm install iceworks -g
$ sudo iceworks
```

**Comment by chenbin92** [comment]
![image](https://user-images.githubusercontent.com/3995814/62909722-62250d80-bdb0-11e9-93be-e1f84c5ae16d.png)

**Comment by chenbin92** [comment]
参照权限问题解决 https://ice.work/docs/iceworks/Installation
