### ISSUE TITLE
iceworks-cli 启动失败

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#2626]
* 安装 iceworks 时分为两个时机，下载 iceworks-cli 和 iceworks-core，当下载 iceworks-core 依赖失败时应该退出并给出提示，否则在启动 iceworks 时可能会出现以下报错

![image](https://user-images.githubusercontent.com/3995814/62526364-b0478780-b86b-11e9-8b4b-15438e3b81b7.png)

**Comment by chenbin92** [comment]
相关问题：https://github.com/alibaba/ice/issues/2633

**Comment by SeanKChan** [comment]
3.0.5版本 还是有和这个问题
