### ISSUE TITLE
打包后运行报错

### ISSUE THREAD

**Issue by zzh3319** [alibaba/ice#263]
You are currently using minified code outside of NODE_ENV === 'production'. This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) to ensure you have the correct code for your production build.

**Comment by noyobo** [comment]
是指打包后运行 build/index.html 文件吗？

**Comment by zzh3319** [comment]
@noyobo   是的

**Comment by noyobo** [comment]
你的模板是哪个？ cms 还是 pro ？

**Comment by zzh3319** [comment]
@noyobo  好像是lite

**Comment by noyobo** [comment]
尝试了使用 lite 打包后运行没有报错。

你能提供更详细的步骤和其他信息吗？

**Comment by zzh3319** [comment]
我在index.html引入了jquery.js  和一个3d轮播插件       其他都是正常流程 没什么特别的步骤 @noyobo

**Comment by noyobo** [comment]
飞冰的基于 React 开发的，不推荐使用 jQuery 组件，可能会引起其他副作用。可以用 https://alibaba.github.io/ice/#/component/slider 这个。

**Comment by wssgcg1213** [comment]
ice-scritps 增加 DefinePlugin NODE_ENV
