### ISSUE TITLE
填写页面信息时，填写目录名TableDemo，真实会新建两个目录：TableDemo、table-demo

### ISSUE THREAD

**Issue by daysai** [alibaba/ice#2630]
## 问题描述

填写页面信息时，填写目录名TableDemo，真实会新建两个目录：TableDemo、table-demo。

## 错误信息

![20190806181521](https://user-images.githubusercontent.com/18555391/62532070-3963bc00-b876-11e9-88ba-5a9cecbc873d.jpg)

![20190806181640](https://user-images.githubusercontent.com/18555391/62532154-5ef0c580-b876-11e9-8b22-7dc7688246cc.jpg)

**Comment by chenbin92** [comment]
新建页面的错误提示

![image](https://user-images.githubusercontent.com/3995814/62843297-73f0ad00-bceb-11e9-8ca0-58070152df1f.png)
