### ISSUE TITLE
如何离线化构建项目使得字体文件请求不再访问公网？

### ISSUE THREAD

**Issue by mrbian** [alibaba/ice#2632]
## 问题描述
**项目编译完成，部署到内网后，由于内网无法访问alicdn，故字体文件无法加载。**

如何设置才能让字体文件请求本地化？

相似问题中提到的wiki：
https://github.com/alibaba/ice/wiki/%E5%A6%82%E4%BD%95%E5%AD%97%E4%BD%93%E6%9C%AC%E5%9C%B0%E5%8C%96
链接无内容，新wiki中也无此文档。

**Comment by imsobear** [comment]
https://ice.work/docs/cli/plugin-list/local ice-scripts@2.0 的话试下这个插件
