### ISSUE TITLE
Can not find egg-scripts when iceworks-server is started

### ISSUE THREAD

**Issue by alvinhui** [alibaba/ice#2633]
## Problem

![image](https://user-images.githubusercontent.com/4392234/62586386-fba37980-b8ef-11e9-955a-a094f08f8963.png)

## Temporary fix

1. Find the local installation path for iceworks:

    - `$ which iceworks`
    - `$ ls -ls ${iceworks_bin_path}`
    - `$ cd ${iceworks_root_path}`

    ![image](https://user-images.githubusercontent.com/4392234/62586466-61900100-b8f0-11e9-8f3b-0c5e38e6fb43.png)
2. Find `server/package.json`
     - `$ pwd`
     - `$ ls`
     - `$ cd server/`

    ![image](https://user-images.githubusercontent.com/4392234/62586581-c6e3f200-b8f0-11e9-822b-81a253336a7e.png)
3. Update the`scripts` field in package.json:

    `$ vim package.json`:

    ```json
    {
      "scripts": {
        "start": "egg-scripts start --title=egg-server-iceworks-server --framework=midway-mirror --workers=1 --sticky",
      }
    }
    ```
    change to:
    ```json
    {
      "scripts": {
        "start": "node_modules/.bin/egg-scripts start --title=egg-server-iceworks-server --framework=midway-mirror --workers=1 --sticky",
      }
    }
    ```

    ![image](https://user-images.githubusercontent.com/4392234/62586629-f1ce4600-b8f0-11e9-8791-dffa34b79a69.png)

**Comment by chenbin92** [comment]
duplicate issues： https://github.com/alibaba/ice/issues/2626
