### ISSUE TITLE
反馈：ice控制台不会自动下载代码中的依赖库

### ISSUE THREAD

**Issue by Kura2017** [alibaba/ice#2634]
##反馈：ice控制台不会自动下载代码中的依赖库，导致我提交的代码同事无法运行，同事手动下载依赖库后才能运行。
###无法引入的依赖库如下：
import IceLabel from '@icedesign/label';
import DataBinder from '@icedesign/data-binder';

**Comment by imsobear** [comment]
前端工程里依赖信息都放在 package.json 里，其他人只要执行 `npm install` 就可以安装依赖。这两个组件你看下 package.json 里有没有，没有的话自己加一下，通过工具或者命令行安装的依赖应该都会自动写入到 package.json 里。
