### ISSUE TITLE
组件开发重新定义sass变量失效

### ISSUE THREAD

**Issue by ClarkXia** [alibaba/ice#2635]
## 问题描述

通过idev创建的业务组件，业务想基于原Fusion进行二次封装，封装成自己业务组件。在组件中定义sass变量，无法覆盖原Fusion组件变量，原组件的sass变量使用!default 改过优先级，在同名的sass下，被使用的优先级是最低的。

**Comment by imsobear** [comment]
这个应该是不允许的

**Comment by ClarkXia** [comment]
### 方案
业务组件对原组件进行二次封装时，指定对应的 sass 变量文件，工程将对应的变量文件注入到所有的 sass 文件前面，可以达到替换原先设置 !default 变量的参数。
但组件由于样式加载需要会生成style.js，内容如下：
```js
// 组件 sass 变量
require('./scss/variables.scss');
// 组件依赖样式
require('ts-idev-a-component/lib/style.js');
// 组件自身样式
require('./main.scss');
```
由于通过 require 的 sass 文件会单独编译，导致二次封装组件在被项目引用的相应的组件变量依旧会失效。

### 其他解决方式
工程上需要知道哪些 sass 变量需要进行替换，是否可以在项目中通过 ice-plugin-fusion 的 themeConfig 能力进行 sass 变量覆盖？

**Comment by imsobear** [comment]
目前的机制无法实现，先暂时关闭掉了
