### ISSUE TITLE
不想使用本地的mock数据

### ISSUE THREAD

**Issue by hyuanyuanlisiwei** [alibaba/ice#2637]
不想使用本地mock的数据,
想使用线上的数据, 本地的静态资源. 

这该如何设置呢

**Comment by imsobear** [comment]
默认访问的接口都是相对当前页面域名的，部署之后就会生效。

**Comment by hyuanyuanlisiwei** [comment]
> 默认访问的接口都是相对当前页面域名的，部署之后就会生效。
=====
那如何开发时 如何使用easy-mock网站的数据呢?

**Comment by imsobear** [comment]
axios.baseUrl 看一下

**Comment by hyuanyuanlisiwei** [comment]
\

**Comment by hyuanyuanlisiwei** [comment]
试过, 无效, 返回404

**Comment by imsobear** [comment]
@hyuanyuanlisiwei 你在飞冰群里吗，在的话直接在群里问，把你的代码配置错误啥的截图发下
