### ISSUE TITLE
Provide jumpable vscode plug-ins or configurations

### ISSUE THREAD

**Issue by alvinhui** [alibaba/ice#2638]
## Problem

Now icekit Pro using `@` as alias: https://github.com/ice-lab/react-materials/blob/master/scaffolds/ice-design-pro/ice.config.js#L15 :

```js
{
alias: {
    '@': path.resolve(__dirname, './src/'),
}
}
```
But in vscode(the common editor), the file path cannot be jumped::

![image](https://user-images.githubusercontent.com/4392234/62606623-3aa4ef80-b92f-11e9-9d32-4a1ce6955b75.png)

I suggest we should provide jumpable vscode plug-ins or configurations.

**Comment by imsobear** [comment]
#2584
