### ISSUE TITLE
ice-store 使用中的问题

### ISSUE THREAD

**Issue by ChenSimin0103** [alibaba/ice#2639]
## 问题描述

我有这样一个使用场景，定义了两个 store: storeA 和 storeB，在storeB中的定义的方法需要拿到storeA中保存的状态，应该怎么写呢？

其实完全可以在业务组件里调用storeB里的方法时，取得storeA的状态并传入，只是觉得这样做可以在业务组件里少写一些代码

**Comment by imsobear** [comment]
不推荐 store 互相调用，要么放在业务组件里多次调用，要么封装成一个 hooks

**Comment by temper357** [comment]
@ChenSimin0103 从设计上层面来看，每个store应该都是逻辑独立的个体，不应该与其他store产生关系，否则就没必要设计成多store，因此从逻辑上对做store隔离是必要的。

对于遇到一个store的action中要调用其他的action的场景，我觉得分两种情况处理，一种是这两个store是逻辑关联是强耦合的，此时适合将两个store中公共部分抽出来放到一个store中管理，另一种两个store没有关系，但是一个事件同时触发了两个store的action，这种情况推荐的做法是封装hooks，在其中分别调用两个store的action，例如以下伪代码:
```javascript
function useMultipleStore() {
  const [storeA, storeB] = stores.useStores(['a', 'b']);
  async function triggerActions() {
     await storeA.xxx(); 
     await storeB.yyy();
  };
  return triggerActions;
}
```

**Comment by ChenSimin0103** [comment]
我的目的仅是使用state而不是调用action修改state，这样并没有副作用，目前我的困惑是，因为取state这一步是设计为hooks的方式，所以在除了纯函数组件之外的其他地方都不能拿到store里的值，
例如，我希望将store中的值取出，并在封装请求方法时放进 http-header 中，没有办法做到
