### ISSUE TITLE
WIN7 icework->模板->模板市场->预览模板 点击没反应

### ISSUE THREAD

**Issue by chenhongen** [alibaba/ice#264]
![default](https://user-images.githubusercontent.com/16499303/37267760-2f2f4812-25ba-11e8-9223-fd6b6a740f9d.png)

**Comment by noyobo** [comment]
#219  cc @wssgcg1213  这个模板数据看起来是旧的，上面的截图

**Comment by wssgcg1213** [comment]
下个版本请求时带一个随机 query 试一下
