### ISSUE TITLE
screentshot 命令找不到 mountNode 的错误及临时解决方案

### ISSUE THREAD

**Issue by enboga** [alibaba/ice#2641]
## 问题描述
在win10环境下执行 区块模块发布 `npm publish` 时会报找不到 `mountNode`。

解决方案：

> package.json scripts 里 \\#mountNode 改成 #mountNode

建议团队在生成初始文件的时候能根据系统自动判断生成。

## 错误信息
![在win10环境下执行 区块模块发布 `npm publish` 时会报找不到 `mountNode`](https://user-images.githubusercontent.com/7981794/62612940-164f1000-b93b-11e9-80b4-ddaf968892d5.png)

**Comment by yang8866love** [comment]
已解决，感谢

**Comment by imsobear** [comment]
## 问题排查

类 unix 系统下 commander `-s #mountNode` 会直接报错找不到该参数

![image](https://user-images.githubusercontent.com/2505411/66803586-9654b000-ef52-11e9-8d36-68686f5b3dac.png)

可以通过 `-s '#mountNode'` 或者 `-s \\#mountNode` 的方式解决，但是这两种方式在 windows 下都不支持。

## 解决方案

- ice-screenshot 支持 `-s mountNode`，selector 没有 `.` 或者 `#` 的前缀则自动追加 `#`
- 将模板里的代码做如下改动：

```diff
"scripts": {
    "start": "ice-scripts dev",
    "build": "ice-scripts build",
-    "screenshot": "screenshot -l -s #mountNode",
+    "screenshot": "screenshot -l -s mountNode",
    "prepublishOnly": "npm run build && npm run screenshot"
},
```
