### ISSUE TITLE
iceworks are not reconnected after the computer is recalled

### ISSUE THREAD

**Issue by alvinhui** [alibaba/ice#2650]
![image](https://user-images.githubusercontent.com/4392234/62552988-24e8e900-b8a1-11e9-8bda-d4ece580529b.png)

1. Start iceworks;
2. Long time no operation, computer into dormancy;
3. When the computer wakes up again, find that iceworks has been disconnected many times without reconnection.

**Comment by chenbin92** [comment]
沉淀问题放到常见问题列表

**Comment by chenbin92** [comment]
![image](https://user-images.githubusercontent.com/3995814/64393852-f6b81e00-d085-11e9-8c4c-d6957d166d51.png)
