### ISSUE TITLE
git仓库面板加载错误-Git repository panel loading error

### ISSUE THREAD

**Issue by Wutong-wt** [alibaba/ice#2659]
## 问题描述
git仓库面板加载错误，没有错误提示
## 错误信息
![21_59_04__08_08_2019](https://user-images.githubusercontent.com/19224207/62709570-35779b80-ba28-11e9-9844-9dcd08fbc2b0.jpg)
短时间内重启无效，等一会重启恢复。
或者是仓库重新推送拉取后重启恢复。
## bug重现
通过terminal合并其他分支，并解决冲突，无须重启就会发生面板加载错误。

**Comment by K1rarin** [comment]
分支重新push后刷新恢复

**Comment by alvinhui** [comment]
这是一个前端渲染错误，麻烦能提供一下浏览器控制台的报错截图吗？
