### ISSUE TITLE
Dialog组件不兼容react 16.9.0

### ISSUE THREAD

**Issue by hyuanyuanlisiwei** [alibaba/ice#2667]
页面使用Dialog报错如下:
index.js:2178 Warning: A future version of React will block javascript: URLs as a security precaution. Use event handlers instead if you can. If you need to generate unsafe HTML try using dangerouslySetInnerHTML instead. React was passed "javascript:;".

react 16.9.0中有如下更新:
https://github.com/facebook/react/pull/15047

**Comment by imsobear** [comment]
https://github.com/alibaba-fusion/next/pull/998
