### ISSUE TITLE
无法创建新页面

### ISSUE THREAD

**Issue by zen0505** [alibaba/ice#2671]
## 问题描述
创建新页面后无法访问，猜想可能是路由的问题，于是为新的页面增加了一个路由，但也遇到问题，步骤如下：
1.创建新页面
![image](https://user-images.githubusercontent.com/53961562/62817855-374c7680-bb70-11e9-886b-973fc423a0aa.png)
![image](https://user-images.githubusercontent.com/53961562/62817871-81cdf300-bb70-11e9-9db4-9338ccbe3653.png)
2.访问该页面失败
![image](https://user-images.githubusercontent.com/53961562/62817861-5a772600-bb70-11e9-9fbd-d1a52d86aa8c.png)
3.创建一个路由
![image](https://user-images.githubusercontent.com/53961562/62817873-8f837880-bb70-11e9-8d3b-728c9ca2a63e.png)
![image](https://user-images.githubusercontent.com/53961562/62817878-9ca06780-bb70-11e9-9394-896d9cca673f.png)
![image](https://user-images.githubusercontent.com/53961562/62817934-83e48180-bb71-11e9-9c81-bce42c2f380c.png)

## 错误信息

Entrypoint index = css/index.css js/index.js css/index.css.map js/index.js.map

ERROR in ./src/config/routes.js
Module not found: Error: Can't resolve '@/pages/NewPage' in 'D:\project\iceWorker\src\config'
 @ ./src/config/routes.js 8:9-34
 @ ./src/router.jsx
 @ ./src/index.jsx
 @ multi ./node_modules/react-dev-utils/webpackHotDevClient.js ./src/index.jsx

 95% emitting HtmlWebpackPlugin./src/config/routes.js     
Module not found: Can't resolve '@/pages/NewPage' in 'D:\project\iceWorker\src\config'

 95% emitting CheckDepsPluginWARN 项目依赖了 core-js 的两个版本， [ '2.6.9', '3.2.0' ]

WARN 项目依赖了 hoist-non-react-statics 的两个版本， [ '2.5.5', '3.3.0' ]

WARN 项目依赖了 sockjs-client 的两个版本， [ '1.1.5', '1.3.0' ]

**Comment by imsobear** [comment]
`/pages/NewPage` 这个文件存在吗？

**Comment by zen0505** [comment]
文件存在，我想问题可能是出现在创建页面的时候。我在创建一个新的页面后点击确定后右上角会出现一个message提示文件已经存在不能覆盖。之后刷新页面列表，里面会有新创建的页面，项目中也会有相应的文件，但就是不能通过路由访问。

**Comment by alvinhui** [comment]
启动 iceworks 时显示的是哪个版本？

**Comment by alvinhui** [comment]
先前的处理逻辑中，如果下载区块失败，被创建的页面文件夹仍会「残留」。
在新逻辑中，如果创建页面流程中有失败，不会有副作用。

https://github.com/alibaba/ice/pull/2785
