### ISSUE TITLE
向已有页面中添加区块链路走不通

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#2673]
没有 loading，没有报错，一直提示文件已存在

![image](https://user-images.githubusercontent.com/2505411/62820611-557a9c80-bb99-11e9-99cf-c80a85382455.png)

**Comment by zen0505** [comment]
新建页面失败会出现以下的情况
![image](https://user-images.githubusercontent.com/53961562/62866695-0c1a8080-bd44-11e9-8ab0-3db1c98cad35.png)
新建页面的代码目录结构如下
![image](https://user-images.githubusercontent.com/53961562/62866756-3bc98880-bd44-11e9-8dbd-c5cd6d44119a.png)
使用的window 10系统，node版本v10.16.1

**Comment by chenbin92** [comment]
![image](https://user-images.githubusercontent.com/3995814/62921177-81d12b80-bdda-11e9-9a80-257b576e8f18.png)

**Comment by alvinhui** [comment]
![image](https://user-images.githubusercontent.com/4392234/62991488-6d486e00-be82-11e9-92b5-d97a25eba39b.png)
![image](https://user-images.githubusercontent.com/4392234/62991495-733e4f00-be82-11e9-85d0-dd6bc3b99bae.png)

**Comment by alvinhui** [comment]
## 背景

目前添加区块的实现方式：

1. 通过 npm tarballURL 将压缩包下载并解压到系统的临时目录（e.g. /var/temp/xxxx/${blockName}）；
2. 通过 [mv@2.1.1](https://github.com/andrewrk/node-mv/blob/2.1.1/index.js) 将 `${临时目录}/${blockName}/src` 移动到 `${project}/src/pages/${pageName}/components/${blockName}`

    ```javascript
    await mvAsync(path.join(blockTempPath, 'src'), blockSourcePath, {clobber: false});
    ```

为什么要设置 `{clobber: false}`？

https://github.com/alibaba/ice/issues/2570

## 问题

问题一：

在某些 macOS 下，执行 `fs.link(source, dest)`，当 dest 已存在的时候，报错：`EEXIST: file already exists` 

问题二：

在某些 windows 下，`fs.link(source, dest)`

**Comment by chenbin92** [comment]
> 将区块下载到项目的文件夹内，而不是系统临时文件夹内，避免一些硬盘间移动或文件夹读写权限问题；

最开始选择系统临时文件的原因是考虑在 iceworks 下载区块时，用户可以在编辑器看到 .tmp 临时文件的新增和删除，不过这个时间可能是比较短的，从现在面临的问题来看可以忽略不计

**Comment by alvinhui** [comment]
已向用户验证，问题二已解决。

**Comment by alvinhui** [comment]
将会在 https://github.com/alibaba/ice/milestone/17 中发布。
