### ISSUE TITLE
iceworks 中启动调试 bool 类型的参数传入 false 时 ice-scripts 也是当做 true 处理

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#2674]
参数永远是字符串，字符串 false 即为 true，两种方案解决这个问题：

1. iceworks 里配置为 false 的参数应该是删除该参数，而非把参数值置为 false
2. ice-scripts 里考虑字符串 false 的特殊情况

使用哪种方案取决于社区命令行 bool 参数对于这种情况是怎么约定的，按照社区规范选择方案。

**Comment by chenbin92** [comment]
![image](https://user-images.githubusercontent.com/3995814/62842976-e2803b80-bce8-11e9-817a-d0bd227541f6.png)

**Comment by chenbin92** [comment]
结论：iceworks 判断如果是 false 则删除掉对应的选项
