### ISSUE TITLE
Can not find "ice-scripts"

### ISSUE THREAD

**Issue by alvinhui** [alibaba/ice#2677]
![image](https://user-images.githubusercontent.com/4392234/62821999-03914100-bbb0-11e9-9647-fb810b02e9a9.png)

Check [getEnv](https://github.com/alibaba/ice/blob/master/packages/iceworks-server/src/lib/plugin/project-manager/app.ts#L88) function.

**Comment by alvinhui** [comment]
![image](https://user-images.githubusercontent.com/4392234/62843110-f7a99a00-bce9-11e9-843f-f4a22fe12196.png)

**Comment by chenbin92** [comment]
## 问题分析

iceworks 安装依赖时机：
1. 在初始化项目时进行安装
2. 在依赖面板进行重置安装
3. 在工程面板进行安装

分析发现还是安装依赖过程中存在失败的可能，在启动时并没有去检查依赖的完整性，只是检查了 node_modules 是否存在，因此导致启动时存在问题。

![image](https://user-images.githubusercontent.com/3995814/62851664-6fdb8400-bd19-11e9-877f-b3d5f526fa8f.png)


## 可能的方案

### 方案一：
 可以在启动调试前加个判断检查 node_modules/ice-scripts 是否存在，对应的 Adapter 各自实现，这样确保启动调试的可用性，虽然解决了工程依赖的问题，但如果有其他依赖没有安装依然会存在报错

### 方案二
可以在启动前执行一遍依赖安装，如果依赖没有安装这个过程是比较快的，`类似 npm install && npm run start`，可以比较完美的解决问题，但是有可能出现在次重装时依然出现问题，以此循环

### 方案三
不针对工程依赖丢失专门做逻辑处理，将现有的乱码问题解决透出提示，新增添加依赖功能到工程面板，当发现依赖没有安装完全时，重装一下依赖即可。

## 结论

选择方案三
