### ISSUE TITLE
datePicker不显示为中文语言

### ISSUE THREAD

**Issue by SunshineH2** [alibaba/ice#2687]
## 问题描述
在系统中设置了configProvider之后不起作用
![image](https://user-images.githubusercontent.com/31178307/62854637-7cb0a580-bd22-11e9-999a-4c92b4ad3e4d.png)
![image](https://user-images.githubusercontent.com/31178307/62854670-905c0c00-bd22-11e9-9d59-ed674d8bd4b4.png)
![image](https://user-images.githubusercontent.com/31178307/62854692-a36edc00-bd22-11e9-9681-af0af3e8f220.png)

**Comment by imsobear** [comment]
package.json 的完整内容发一下 @SunshineH2

**Comment by SunshineH2** [comment]
![image](https://user-images.githubusercontent.com/31178307/62924495-d082c380-bde2-11e9-9ab1-2468ea5c5931.png)
![image](https://user-images.githubusercontent.com/31178307/62924521-db3d5880-bde2-11e9-9867-f0c946fb35c8.png)

**Comment by imsobear** [comment]
https://ice.work/docs/cli-1.x/others/moment

同时有精力可以考虑将 ice-scripts 升级到 2.x：https://ice.work/docs/cli/migrate
