### ISSUE TITLE
 alert 类型的dialog样式冲突

### ISSUE THREAD

**Issue by wssgcg1213** [alibaba/ice#269]
![image](https://user-images.githubusercontent.com/3922719/37284156-7455ee02-2635-11e8-9e95-a928d6a0025a.png)

**Comment by wssgcg1213** [comment]
![image](https://user-images.githubusercontent.com/3922719/37284206-9f8c26a4-2635-11e8-8774-fa28ec12e33b.png)

**Comment by Symous** [comment]
@ClarkXia 我也遇到饿了一样的问题，请问该问题解决没有；
