### ISSUE TITLE
Table 过滤列 中 filters属性  对象数组中 的 value 不能为布尔值?

### ISSUE THREAD

**Issue by hyuanyuanlisiwei** [alibaba/ice#2694]
警告如下:

index.js:2178 Warning: Failed prop type: Invalid prop `filters[1].value` supplied to `Column`.

**Comment by imsobear** [comment]
https://codepen.io/sobear/pen/NeJmOG?editors=0011 麻烦给个重现 demo

**Comment by imsobear** [comment]
https://fusion.design/feedback 组件问题在这里反馈
