### ISSUE TITLE
关于使用DynamicIcon自定义组件时，使用ice-scripts 插件不会本地化打包css 字体文件。

### ISSUE THREAD

**Issue by LoLDragon** [alibaba/ice#2703]
## 问题描述
   再项目开发中使用DynamicIcon组件加载自定义的Icon.再工程文件打包本地化时。使用ice-scripts文档中插件化打包字体文件时无效。如下图 只是将Icon资源文件以link的方式插入到Dom中。对于很多内网环境中的项目工程很不友好。
![image](https://user-images.githubusercontent.com/19163371/63004001-ffb13780-beab-11e9-8ad8-5e749e17099e.png)

**Comment by imsobear** [comment]
@LoLDragon 除了 DynamicIcon 的场景，基础组件的字体文件 icon 啥的有离线化出来吗？离线化成功了的话在 build 目录可以看到一堆字体相关文件。

**Comment by LoLDragon** [comment]
@imsobear 基础组件有离线出来，后面自定义的Icon,   我自己下载字体下来。重新写了一个组件加载了。

**Comment by imsobear** [comment]
所以看起来主要是 DynamicIcon 这个场景的问题了

**Comment by imsobear** [comment]
@LoLDragon 问题解决了？
