### ISSUE TITLE
页面添加区块的时候，安装区块依赖的问题

### ISSUE THREAD

**Issue by enboga** [alibaba/ice#2705]
## 问题描述
页面添加区块的时候，期望下周区块代码的时候，同时安装相应依赖。一般区块开发的时候是会在package.json中定义依赖的，期望能自动安装这些依赖。不然自己还要手动去安装，手动安装步骤会比较繁琐。

**Comment by alvinhui** [comment]
https://github.com/alibaba/ice/pull/2711

**Comment by enboga** [comment]
我升级到3.1.0 这个问题好像还是没有解决，我使用了 官方某区块测试，该区块代码中，使用 import { Grid } from '@alifd/next'; 
证明需要使用到 @alifd/next ，我原本项目中是没有 @alifd/next 的，所以在区块下载的时候是不是应该在项目中自动添加这个依赖并安装？
我的试验结果是在 项目的 package.json 和 node_modules 都找不到该模块。

**Comment by enboga** [comment]
重新测试后发现刚才不行的原因是我们私库有问题，导致其中一个依赖包安装失败。这个时候下载区块是成功了，但是依赖是失败的，但是除了控制台有提示，其他地方都不清楚这个状态，如果不看控制台，或者控制台的信息刷没了，很容易就会不知道问题在哪里。
建议是不是在安装依赖失败的情况下，能有补救方式？依赖是否可以先添加到 package.json 再执行？

**Comment by enboga** [comment]
有时候如果我们下载错一个区块后，如何删除区块？并且在删除的时候能一并删除依赖（当然这个依赖需要没有被其他组件或区块引用）
