### ISSUE TITLE
[iceworks 3.0] RFC: Building custom projects through a standardized JSON structure

### ISSUE THREAD

**Issue by tanhengyeow** [alibaba/ice#2708]
## Background

1. To create a project from iceworks, materials from e.g. [react-materials](https://github.com/ice-lab/react-materials) are used as a base scaffold. These scaffolds are downloaded as npm packages and imported inside iceworks when the `iceworks init` command is executed. This process can be improved.

2. To create a custom project, users have to edit the code manually after the template is created. More flexibility can be provided to the users to customize the layout and functionalities of the scaffold to suit their needs. This functionality should be exposed to users through a visual interface.

3. There are ~30 scaffolds including scaffolds from [react-materials](https://github.com/ice-lab/react-materials), [vue-materials](https://github.com/ice-lab/vue-materials) and [cra-materials](https://github.com/ice-lab/cra-materials) etc. There is code duplication across all scaffolds, resulting in large maintenance cost. 

## Proposal

Scaffolds can be represented as a standardized JSON structure. The benefits include:
1. Generating projects in iceworks based on the scaffold's JSON structure 
   - This eliminates the need for downloading materials for e.g. [react-materials](https://github.com/ice-lab/react-materials) as npm packages and importing them inside iceworks, reducing network overhead.
2. Storing configuration of custom scaffolds using the same JSON structure in iceworks
   - Custom scaffolds can built in the same way as point 1.
3. Using a variety of materials for e.g. [react-materials](https://github.com/ice-lab/react-materials) as base scaffolds to build their custom projects. 
4. Reducing significant maintenance cost for [react-materials](https://github.com/ice-lab/react-materials), [vue-materials](https://github.com/ice-lab/vue-materials) and [cra-materials](https://github.com/ice-lab/cra-materials) etc.

Example [JSON](https://jsoneditoronline.org/?id=9fce7fbe45264e4bb119de6fadda4395) Structure:
```json
{
  "headerMenu": [
    {
      "name": "help",
      "path": "https://alibaba.github.io/ice",
      "external": true,
      "newWindow": true,
      "icon": "help"
    },
    {
      "name": "feedback",
      "path": "https://github.com/alibaba/ice",
      "external": true,
      "newWindow": true,
      "icon": "email"
    }
  ],
  "asideMenu": [
    { 
      "name": "test2~", 
      "path": "/test2" 
    },
    {
      "name": "Dashboard",
      "path": "/dashboard",
      "icon": "atm",
      "children": [
        { 
          "name": "监控页", 
          "path": "/dashboard/monitor"
        }
      ]
    }
  ],
  "layoutConfig": {
    "name": "",
    "enableName": false,
    "enableTheme": true, 
    "directory": "",
    "layout": "fluid-layout",
    "themePackge": "@alifd/xxx",
    "header": {
      "position": "static",
      "width": "full-width",
      "enabled": true,
      "styles": {
        "background": "none"
      }
    },
    "aside": {
      "position": "embed-fixed",
      "mode": "vertical",
      "width": 200,
      "collapsed": false,
      "enabled": true,
      "styles": {
        "background": "none"
      }
    },
    "footer": {
      "position": "fixed",
      "width": "full-width",
      "enabled": true
    },
    "logo": {
      "method": "upload",
      "width": "70px",
      "height": "70px",
      "url": ""
    },
    "iceConfig": {
      "internalization": false,
      "typeScript": false,
      "hooks": false,
      "register": false
    }
  },
  "router": [
    {
      "path": "/",
      "children": [
        {
          "path": "/dashboard",
          "page": {
            "name": "dashboard",
            "container": "containerA",
            "block": [
              "blockA",
              "blockB"
            ]
          }
        },
        {
          "path": "/test",
          "page": {
            "name": "test",
            "container": "containerB",
            "block": [
              "blockC"
            ]
          }
        }
      ]
    }
  ],
  "icestore": true,
  "mock": false
}
```
Details:
- `headerMenu`/`asideMenu`: Configuration for `/config/menu.js`
- `layoutConfig`: Configuration for `/layouts`
- `router`: Configuration for `/config/routes.js`. See below for example code generated.
```js
import React from 'react';
import ContainerA from './containerA';
import BlockA from './blockA';
import BlockB from './blockB';

const Dashboard = () => {
  <ContainerA>
    <BlockA />
    <BlockB />
  </ContainerA>
};

export default Dashboard;
```
### Core logic

The core logic uses [EJS](https://ejs.co/) to render files required for the project. 

This is an example project structure (example from [ice-design-pro](https://github.com/ice-lab/react-materials/tree/master/scaffolds/ice-design-pro/src)):

**`/components`**

Components that are shared across the app. Examples include `LocaleProvider` and `SelectLang`. They will be generated if the `iceConfig.internationlization` field is set to true.

**`/config`**

Configuration files that represent the header menu, aside menu and routes of the app. They will be generated from the `headerMenu`, `asideMenu` and `router` field.

**`/layouts`** 

A folder containing components like `Header`, `Aside`, `Footer`, `Logo` etc that make up the structure of the app. They will be generated from the `layoutConfig` field.

**`/locales`**

Configuration files that support internationalization. They will be generated if the `iceConfig.internationlization` field is set to true.

**`/pages`**

Pages are required to be built upon blocks. A block ([example](https://github.com/ice-lab/react-materials/tree/master/blocks)) is the smallest building block that makes up a template. We should create a set of template files whose content is similar to a block and use [EJS](https://ejs.co/) to represent dynamic content if necessary. 

Data from the standardized JSON structure would be used to determine the type of dynamic content to render in the new file. Generic files without dynamic content would be created as a new file with contents identical to the template file. These new files make up the generated project.

**`/stores`**

Configuration files that are generated if components/blocks use React Hooks. The matching functions/code will depend on which components/blocks depend on hooks. They will be generated if `icestore` is set to true.

### API

The API to generate the files will be broken up into functions that generate the respective folders. For e.g we would have a `pages` function and `config` function that generates pages and configuration files respectively. This ensures easier maintainability.

## Plan ahead
1. Setup template files with EJS if necessary
2. Implement the API to generate files based on the JSON structure
3. Implement a visual interface to allow users to change the configuration of the JSON structure
4. Save the JSON structure and/or build the custom project using logic built in point 2

## Others

This is a follow-up issue from #2283.

**Comment by chenbin92** [comment]
## Question 1
```json
 "icestore": {
    "enabled": true
  },
```
Should be：
```
"icestore":  Boolean
```

## Question 2
```json
"themeConfig": {
  "theme": "dark",
  "primaryColor": "#3080FE",
  "secondaryColor": "#FFC107"
}
```
I think it should be like this
```js
 "themePackge": "@alifd/xxx"
```

**Comment by chenbin92** [comment]
关联 issue https://github.com/alibaba/ice/issues/2283
