### ISSUE TITLE
设置Dialog组件的 closeable 为 true,  点击右上角的X, 对话框没有关闭

### ISSUE THREAD

**Issue by hyuanyuanlisiwei** [alibaba/ice#2709]
<img width="858" alt="屏幕快照 2019-08-14 下午8 18 24" src="https://user-images.githubusercontent.com/11502089/63020476-cfc85b00-bed0-11e9-987a-f363107d1d24.png">

**Comment by imsobear** [comment]
closeable 是控制 UI 状态的，关闭显示需要自己控制 visible 属性
