### ISSUE TITLE
icestore 在 TypeScript 中使用问题

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#2713]
## `useStore('xxx')` 返回的类型不对

![image](https://user-images.githubusercontent.com/2505411/63069345-15c10580-bf49-11e9-8cab-b620d31ce804.png)

```bash
Type '{}' is missing the following properties from type 'RoomStore': currentRoom, roomList, pagination, filters, and 5 more.
```

## action 不会提示组件额外追加的 .loading 属性

![image](https://user-images.githubusercontent.com/2505411/63069609-27ef7380-bf4a-11e9-8e19-23f5f3274bd1.png)

**Comment by chj-damon** [comment]
+1，typescript的类型推论目前只能用as的方式，不友好。

**Comment by temper357** [comment]
下个版本增加 ts 支持
