### ISSUE TITLE
如何去掉Dialog默认的确定取消按钮

### ISSUE THREAD

**Issue by hyuanyuanlisiwei** [alibaba/ice#2717]
因为我在Dialog中使用了Form,  Form的submit按钮进行了 自定义校验,

**Comment by hyuanyuanlisiwei** [comment]
或者, 如何更改 ice 组件的样式呢

**Comment by imsobear** [comment]
footer 属性设置为 null 即可。

**Comment by hyuanyuanlisiwei** [comment]
试过, 报错,  只能在全局样式文件中更改样式,  组件样式文件中更改样式无效

**Comment by imsobear** [comment]
说错了是 `footer={false}`，https://codepen.io/sobear/pen/jONqgdM?editors=0011
