### ISSUE TITLE
iceworks 新增 CLI 和 Core 更新文档

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#2718]
## 背景

目前 iceworks 分为 CLI 和 Core 更新两部分，当有新版本发布时，会在用户群发布更新说明，但是很多用户以为是更新 CLI 的版本，同时还有 Core 的更新，对两者理解会混淆

## 解决

新增一篇 iceworks 更新的文档说明，主要解释 iceworks-cli  和 iceworks-core 的更新说明，以及如何更新等内容

**Comment by imsobear** [comment]
放到架构设计那块

**Comment by chenbin92** [comment]
> 放到架构设计那块

架构设计的这边文章有讲到设计，我考虑的是主要面向使用者的，讲一下怎么更新，更新的是那部分就可以了？ https://ice.work/docs/iceworks/contributing/codebase-overview

![image](https://user-images.githubusercontent.com/3995814/63138876-a0b80380-c00e-11e9-9de1-d83b4678b2c2.png)
