### ISSUE TITLE
企业私有化部署需求收集讨论

### ISSUE THREAD

**Issue by yujiangshui** [alibaba/ice#272]
飞冰将在下个阶段重点支持企业、个人私有化部署，即物料私有化开发和部署。

届时 Iceworks 将支持导入自己的或者团队的私有物料和自定义的配置（插件、功能、部署逻辑等等）。

现征集下需求，有想法的朋友们可以在下面反馈下。

**Comment by yujiangshui** [comment]
@ltjin 你期望的是 Iceworks 可以配置全局数据源 API，然后可以在新建页面等地方显示接口对应的数据。

这个中间件是什么样的需求？希望对这个数据源 API 做访问权限控制？这个应该做在接口本身吧？

**Comment by ltjin** [comment]
@yujiangshui 
1. 其实就是把请求API这个事能够通过配置来完成，开发只关注后台逻辑，在UI上直接获取需要的数据
2. 中间件是为了解决配置不能完成的问题，比如API鉴权，签名等。前端请求接口，需要满足接口本身的规则，中间件是实现接口请求规则的

**Comment by yujiangshui** [comment]
@ltjin 那你这个本身其实是物料层面的需求，提供一些高度集成、动态化的配置的模板，在前端代码里配置 api 地址实现相关提交需求。

cc @chenbin92

**Comment by ltjin** [comment]
我设想的流程是这样的：
1、创建项目的时候选择模板、API定义文件（json/yml），生成基本的项目结构
2、新建页面的时候，可以选择区块，以及需要调用的API，比如商品列表：{products：products}，前边的products是页面里使用的API返回的数据，后边的products表示要调用的API接口名，新建完成之后在新页面里使用products来填充列表

其实就是物料+真实数据

**Comment by scglwsj** [comment]
项目的slogan既然是赋能中后台，所以真心希望能够在与后台api对接的时候能够通过简单配置的方式快速实现。
全局可以配置一个或多个接口的地址、端口。
每个页面或者组建可以配置接口的http request参数，然后如何从response中取出数据或者异常信息。

**Comment by yujiangshui** [comment]
@scglwsj 目前有 https://alibaba.github.io/ice/#/component/databinder 这个组件，就是类似你配置接口信息，然后再在下面调用 api 来实现，是否满足你的需求？

**Comment by scglwsj** [comment]
厉害！ @yujiangshui

**Comment by chenbin92** [comment]
已支持
