### ISSUE TITLE
启动项目增加 URL 信息

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#2723]
## 描述

在项目面板的 「启动项目」面板当任务启动时，只能通过工程面板的日志流信息找到当前启动项目的 URL 信息，且当信息输出较多时，很难在找到

![image](https://user-images.githubusercontent.com/3995814/63151494-37e78000-c03c-11e9-8b25-51096cc7badb.png)

## 解决

在启动面板透出当前项目的 URL 信息，可以点击打开

**Comment by imsobear** [comment]
我觉得可以把这个面板改为项目信息：把路径、URL以及其他相关信息都可以展示在这里
