### ISSUE TITLE
组件开发配置了 modular-import 插件不生效

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#2724]
编译后仍然直接引入了@ali/deep，可能跟 ice-plugin-component 冲突？

![image](https://user-images.githubusercontent.com/2505411/63151897-1cc94000-c03d-11e9-80ab-0ff5b5e24a6d.png)

![image](https://user-images.githubusercontent.com/2505411/63151906-22bf2100-c03d-11e9-918e-d28dcbbd2391.png)

**Comment by ClarkXia** [comment]
fixed in ice-plugin-component@0.1.5
