### ISSUE TITLE
创建路由优化

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#2726]
## 描述

创建路由面板有两个 ` + ` 可以创建路由，一个是一级路由，一个是子路由，但是对新用户来说，并没有给出任何提示，点击出来的弹窗也都是一样的，只能去代码看才知道，会让人摸不着头脑

![image](https://user-images.githubusercontent.com/3995814/63152288-1091b280-c03e-11e9-91d9-695fdc08c308.png)

![image](https://user-images.githubusercontent.com/3995814/63152408-551d4e00-c03e-11e9-8bc0-fadfb519557a.png)

## 解决

1. 弹窗的标题区分：`创建一级路由` 和 `创建子路由`
2. 在 `+` 上给出提示说明

**Comment by alvinhui** [comment]
https://github.com/alibaba/ice/milestone/19
