### ISSUE TITLE
Tree 组件 如何新建一个 节点  让其处于编辑状态 

### ISSUE THREAD

**Issue by hyuanyuanlisiwei** [alibaba/ice#2732]
<img width="730" alt="屏幕快照 2019-08-19 下午7 57 07" src="https://user-images.githubusercontent.com/11502089/63263594-a2f2ba00-c2bb-11e9-8ac3-899753e74e1b.png">

**Comment by imsobear** [comment]
基础组件 `@alifd/next` 问题请在这里反馈：https://fusion.design/feedback
