### ISSUE TITLE
🌈🌈🌈飞冰团队的“寻人启事”

### ISSUE THREAD

**Issue by alvinhui** [alibaba/ice#2738]
现在发布招聘贴，如果不起一个“语不惊人死不休”的标题，仿佛是很难博得眼球了。哗众取宠不适合技术场景，我们简单直白：招人！！！

## 我们是谁？

[飞冰](https://ice.work/)隶属于[淘系前端团队](https://fed.taobao.org/)的中后台架构小组。团队 16 年成立，3 年来我们持续在中后台领域耕耘，先后在内部孵化了可视化搭建平台(iceluna)、智能助手平台(iceman)、前端研发工作台(iceworks)等技术产品。在开源方面，我们主导的 [ice](https://github.com/alibaba/ice) 是阿里开源仓库中为数不多 star 数过万的前端项目。

## 我们在做什么？

过去几个月，飞冰团队做了这么几件事情：

- 发布了 [iceworks 3.0](https://github.com/alibaba/ice/issues/2369)，新增 CLI 使用链路，升级产品结构和用户界面，让「源码可视化研发」更简单友好；
- 发布了 [ice-scripts 2.0](https://ice.work/docs/cli/about)，开始通过丰富的插件体系涵盖不同场景，支持各种功能拓展和业务需求；
- 发布了 [icestore](https://github.com/ice-lab/icestore)，基于 React 最新 Hooks 特性实现的、轻量级的状态管理方案；
- 发布了 [icestark](https://github.com/ice-lab/icestore)，针对大型应用，我们在内部场景中孵化的微前端解决方案正式开源；
- 升级了 [ice-devtools](https://github.com/ice-lab/ice-devtools/releases)，不耦合任何前端框架或工程体系，这意味着基于 ice-devtools 可以开发 React/Vue/Angular 等各种前端体系的物料。

自此，面向中后台领域，飞冰形成了以研发生态、物料中心和研发链路为一体的技术矩阵，覆盖了前端项目从生成、开发到发布的全链路技术能力：

![](https://img.alicdn.com/tfs/TB157CQcpP7gK0jSZFjXXc5aXXa-1716-848.png)

业务上，我们将 icestark 应用到了小二工作台场景，并强参与到了工作台系统的构建中，期望通过创新业务模式，重塑新零售商业的生产关系。未来，我们还将横向支持部分重要的业务后台，完成小二操作系统的收口，技术架构的统一，提升小二的工作效率。

## 为什么我们还要招人？

我们的技术矩阵看起来很完备，但仔细去思考，里面问题和挑战依然很多，例如：

- 无线中后台与 PC 中后台之间的关系是什么，两者通过怎样的方式进行串联？
- 物料、方案和工具在各自领域精耕细作得不错，但面向中后台开发，怎么样才能做到开箱即用？
- 物料已经完成从无到有，未来怎么样做到既有「丰富度」又有「质量」？评价和筛选又应该怎么做，如何保障物料能够效益最大化？
- No Code 的理念和实践在业界越来越丰富，中后台领域迎来生产力突破的拐点，飞冰体系如何引领下一个时代的潮流？
- ...

业务上，淘系在高速发展的背后，成百上千的内部小二系统百花齐放百家争鸣，这些系统的管理成本、用户体验、质量和安全性方面都面临着巨大的挑战。大部门发起了“小二工作台战役”，「重新定义“人、货、场、商”商业能力，通过技术架构升级形成面向平台能力的研发模式」。在这样的大背景下，我们面临着新的问题和挑战：

- 在新的研发模式下，对于垂直业务后台如何进行研发支撑？@大果 提出了对统一的团队横向支持所有业务后台或垂直业务加人同时支持前后台的两种方案，这里没有最优解，值得思考和探讨；
- 大战役意味着要「统一指挥，高度协同」，技术如何贴着业务来打，做技术架构的同学应该怎样主导或参与业务的建设？这有赖于观念的转变，也需要能力的加持，甚至是生产关系的重塑。

这些问题，有些我们已经有了答案，还有一些我们也在思考和探索中。

因此，我们非常希望能够和对中后台领域有兴趣、在中后台领域有经验的同学，一起交流摩擦出思想的火花，甚至一起努力把想法变成现实。

我们已经看到，万众创业和产业互联网的蓬勃发展，ToB 市场大有可为；我们也看到，政企类网站和机构类后台的用户体验惨不忍睹，其管理者或使用者每天似乎还在 Web 旧时代的黑夜里度日如年；我们还看到，飞冰用户群里的开发者群体依然面临着研发门槛、研发效率、研发体验的困扰……

解决这些问题正是我们这一群人的价值所在。

这注定是一场风尘仆仆、跋山涉水的旅途。“如果要走得快，那就一个人走；如果要走得远，那就一群人走”。所以我们发布了这起“寻人启事”。

## 我们需要怎样的人？

常见的「职位要求」相信不少同学已经看过，在中后台领域和淘系的业务背景下，我们有自己的侧重点：

1. 我们希望你技术视野广阔，能够应用新技术或经典的方法解决业务中的痛点问题，并且有有大型网站前端架构、性能、可访问性、可维护性等方面的实践经验：淘系的中后台系统每天都在服务着大量的公司运营小二、外部商家和淘系创作者，它们无不是「大型网站」；
2. 至少熟练使用一门非前端脚本语言（如：NodeJS /Python/PHP 等），并有项目经验：淘系中后台系统的「大」，意味着需要多人协同，意味着我们需要与其他开发角色（服务端开发、测试开发）进行紧密的协作，这时候就需要具备「换位思考」的能力；
3. 对前端事件流、数据流有一定的理解：在大型中后台前端应用中，事件流和数据流的处理决定了整个架构的复杂度，我们期望你对此有自己的见解并在未来帮助飞冰体系沉淀出我们的最佳实践；
4. 理解 Babel/Webpack 的工作原理，对 AST 有一定的认识：要做「源码可视化」，这就需要打通 GUI to Code 的链路，这里面对 AST 能力的要求必不可少；
5. 了解 BaaS/FaaS，对 serverless 有一定的理解：面向未来的研发模式应该变成什么样子？ serverless 或许可以提供全新的思路。 

以下这些则是「加分项」：

1. 有复杂可视化搭建平台的研发经验：源码和可视化研发方式不应该是割裂的，如何将源码研发和可视化研发能力打通、打造一个产品和一致性用户体验，是接下来我们要去突破的新思路；
2. 对经典的深度学习模型(如CNN, LSTM)有一定的理解，使用深度学习模型完成过高质量的算法项目：「面向算法模型编程」在未来将会是程序员的标配，如果你已具备这种能力，我们认为你已手握通向未来的「船票」。

从技术人才层级来说，我们既需要专家（P7）也需要在中后台领域有丰富经验的高级工程师（P6）。

## 我们能为你提供什么？

我们知道，每一个求职应聘者都有自己的「人生诉求」，有自己对生活、工作的理解和追求。笔者结合自身的情况，总结了几下几点：

- 薪酬待遇：公司能为你开出怎样的薪酬，这既取决于岗位的行情，也取决于公司的盈利能力，在大公司里还取决于团队的竞争力情况。阿里近些年的发展情况大可通过财报、股价见端倪，淘系前端团队在阿里集团内也属于先头部队。我想，我们的 HR 肯定能开出让你满意的、有竞争力的薪酬。当然，关于涨薪、奖金、期权等情况，我也很愿意私下与你交流；
- 工作压力：「加班是对的，不加班也是对的，没有把工作完成，是不对的」。坦白讲，阿里的工作压力不小。但团队从不拔苗助长，也不鼓励过度自我消耗。有多大的能力承担多大的责任拿多少的报酬，过度的压力往往是因为你待在了不恰当的位置，适度的压力能让你保持清醒 —— 认清世界，认清自己；
- 上升空间：在阿里，每年集团都会组织一次晋升评审，这些年我看到了太多优秀又努力的同学连续晋升，也看到了不少沉着专研的同学涅槃成长。20 岁的阿里依然保持着活力，汰换制度正常，上升通道公平公开。

## 一些你还需要知道的事情

我们知道，中后台领域历史悠久、卧虎藏龙，但也正因为如此，所以技术人员能力参差不齐，鱼目混杂。「优秀的人总是希望和优秀的人一起合作」，所以阿里的招聘流程非常严格。如果你有兴趣加入我们，希望你能够放平心态，保持耐心，你将需要经历四到五场的面试，而面试流程越长，则说明我们对你越感兴趣。

2020 应届毕业生、前端开发工程师发送个人作品（Github 账号、个人博客、简历）至 wuji.xwt@alibaba-inc.com ，让我来主动找你，我将向你介绍更多关于我们团队的内容。

当然，也欢迎通过 WebChat(2009alvin) 直接联系我（请备注： 前端）。

我们在西溪园区等你。

**Comment by william-xue** [comment]
我感觉飞冰的东西比antd的好，😄

**Comment by forrestneo** [comment]
支持

**Comment by dylanzx** [comment]
支持。
