### ISSUE TITLE
发布物料后在Iceworks不能显示对应分类的物料

### ISSUE THREAD

**Issue by lidahuiSoftWare** [alibaba/ice#2742]
区块的物料描述，在新版ice-devtools 只会有category 字段有值。但是在iceworks 和 fusion-desing 中只能识别categories ，并不兼容 category。
1. 采用ice-devtools 发布的物料 只能在最新看到发布最新的表单区块
![image](https://user-images.githubusercontent.com/19846914/63526819-988e2580-c532-11e9-9005-45055d140ff4.png)

2.具体到表单分类的区块，在icewoks 并不展示
![image](https://user-images.githubusercontent.com/19846914/63526936-cb381e00-c532-11e9-9e71-1a78f8ff4b05.png)

3. 区块描述
 {
      "name": "feed-back-record-form",
      "title": "多图上传表单",
      "description": "多图上传表单",
      "homepage": "https://unpkg.alibaba-inc.com/@alife/fliggy-ice-material-feed-back-record-form@1.0.0/build/index.html",
      "categories": [],
      "category": "Form",
      "source": {
        "type": "npm",
        "npm": "@alife/fliggy-ice-material-feed-back-record-form",
        "version": "1.0.0",
        "registry": "https://registry.npm.alibaba-inc.com",
        "sourceCodeDirectory": "src/"
      },

**Comment by imsobear** [comment]
fusion 生成物料数据会兼容这个逻辑 @bindoon 跟进
