### ISSUE TITLE
Support HappyPack in ice-scripts

### ISSUE THREAD

**Issue by tanhengyeow** [alibaba/ice#2749]
HappyPack makes initial Webpack builds faster by transforming files in parallel, improving build-time performance. More on how it works is described [here](https://github.com/amireh/happypack#how-it-works). 

We should support HappyPack in `ice-scripts` so that users are able to enjoy improved build-time performance for applications built with `ice-scripts`.

**Comment by ClarkXia** [comment]
默认 loader 的结构被破坏，影响其他插件的使用，暂不考虑这种方案
