### ISSUE TITLE
icestore 管理next input框的value，输入中文异常

### ISSUE THREAD

**Issue by hellohy** [alibaba/ice#2758]
## 问题描述

使用icestore来管理next input框的value，无法输入中文。
使用普通的state，来设置input的value，是可以正常输入中文的。

## 复现地址

https://codesandbox.io/s/icestore-bug-npmzh

**Comment by temper357** [comment]
@hellohy 
参考 react 官方的 issue https://github.com/facebook/react/issues/3926, 该问题的现象是 onChange 中使用了异步 update 的方式（可以在 setState 时加上 setTimeout 来模拟）导致 UI 变化不连续，目前这个 issue 已经过了 3 年官方尚未给出解决方案。

icestore 出现问题的可能原因是为了支持异步 action 默认使用 async 方式触发，后续可以通过在内部实现上区分同步和异步的方式来解决，目前的 workaround 可参考这个社区贴子 https://segmentfault.com/a/1190000008023476 来实现。
