### ISSUE TITLE
ice官网文档 权限管理 文案错误

### ISSUE THREAD

**Issue by hyuanyuanlisiwei** [alibaba/ice#2761]
<img width="789" alt="屏幕快照 2019-08-28 下午2 58 01" src="https://user-images.githubusercontent.com/11502089/63832869-428f0700-c9a4-11e9-8851-64143c71e457.png">

对于组件 如果没有权限 这样会返回 403页面, 而不是不显示该组件

**Comment by imsobear** [comment]
https://github.com/alibaba/ice/issues/2767 在这里讨论
