### ISSUE TITLE
ice默认生成url中#锚点是否可以去掉

### ISSUE THREAD

**Issue by gluo1130** [alibaba/ice#2764]
## 问题描述

如题：ice默认生成url中#锚点是否可以去掉，未找到相应的配置项或代码修改项

## 错误信息

例如图中 # 的所示，是否支持去掉

![image](https://user-images.githubusercontent.com/16134023/63907897-bb976880-ca4f-11e9-90ae-c0e2ba74a705.png)

**Comment by imsobear** [comment]
> 文档正在补充，可以先看一下

## 常见问题

### 为什么浏览器里的地址都带着 `#`？

前端路由通常有两种实现方式：HashHistory 和 BrowserHistory，路由都带着 `#` 说明使用的是 HashHistory。这两种方式优缺点如下：

|特点\方案|     HashRouter    |   BrowserRouter  |
|--------|-------------------|-----------------|
|美观度   |   不好，有 # 号     |     好          |
|易用性   |   简单             |  中等，需要 server 配合 |
|依赖 server|    不依赖        | 依赖               |
|跟锚点功能冲突|   冲突         |  不冲突           |
|兼容性      |   IE8           |   IE10         |

开发者可以根据自己的实际情况选择对应方案。

### 如何使用 BrowserHistory？

首先在路由渲染部分将最外层由 HashRouter 替换为 BrowserRouter：

```diff
- import { HashRouter as Router, Switch, Route, Redirect } from 'react-router-dom';
+ import { BrowserRouter as Router, Switch, Route, Redirect } from 'react-router-dom';
```

本地调试支持，在 `ice.config.js` 中配置 webpack-dev-server 的配置：

```js
module.exports = {
  devServer: {
    historyApiFallback: true,
  }
}
```

线上运行时需要 server 端支持，否则会出现刷新 404 问题，具体方案请参考社区文档：

- [关于 react-router 的 browserHistory 模式](https://github.com/LoeiFy/Recordum/issues/15)
- [react-router 之 HashRouter & BrowserRouter](https://zzugbb.github.io/passages/react-router%E9%97%AE%E9%A2%98/)
