### ISSUE TITLE
Support inspection of webpack config files in ice-scripts

### ISSUE THREAD

**Issue by tanhengyeow** [alibaba/ice#2772]
`ice-scripts` uses [`webpack-chain`](https://github.com/neutrinojs/webpack-chain) to manage webpack config files. Using [`webpack-chain`](https://github.com/neutrinojs/webpack-chain) is beneficial to manage large webpack config files that are dynamic in nature. 

However, [`webpack-chain`](https://github.com/neutrinojs/webpack-chain) adds a layer of abstraction over the underlying webpack config files, causing developers to have difficulty in understanding what is included inside the config file. As a result, they face difficulties tweaking the config files when needed to.

We should allow developers to inspect the underlying webpack config files through `ice-scripts` to improve the developer experience, allowing developers to be more productive.

**Comment by ClarkXia** [comment]
命令的扩展尽量还是会控制在 dev build test，inspect 能力后续将通过文档透出

**Comment by ClarkXia** [comment]
具体能力将在文档中透出 https://github.com/alibaba/ice/pull/2903
