### ISSUE TITLE
icestark路由 AppRoute 增加 beforEach 钩子

### ISSUE THREAD

**Issue by ChasLui** [alibaba/ice#2774]
当先路由只在 AppRouter又一个 `onRouteChange` 钩子,  并且也没有formUrl 参数, 导致很多时候需要做路由拦截很不方便, 期望:
1. AppRouter 的 `onRouteChange`参数增加 `formUrl`
2. AppRoute 增加 `router.beforeEach` `router.beforeResolve``router.afterEach`

**Comment by daysai** [comment]
formUrl 指的是？ onRouteChange 有具体的pathname、query、hash的解析结果透出了。具体诉求是？   AppRoute 在考虑增加两个钩子，onEnter、onLeave，能对外透出更多能力。这两个钩子是否能满足以上router.beforeEach router.beforeResolve``router.afterEach的所有操作？

**Comment by daysai** [comment]
> 当先路由只在 AppRouter又一个 `onRouteChange` 钩子, 并且也没有formUrl 参数, 导致很多时候需要做路由拦截很不方便, 期望:
> 
> 1. AppRouter 的 `onRouteChange`参数增加 `formUrl`
> 2. AppRoute 增加 `router.beforeEach` `` router.beforeResolve``router.afterEach ``

formUrl 指的是？ onRouteChange 有具体的pathname、query、hash的解析结果透出了。具体诉求是？ AppRoute 在考虑增加两个钩子，onEnter、onLeave，能对外透出更多能力。这两个钩子是否能满足以上router.beforeEach router.beforeResolve``router.afterEach的所有操作？

**Comment by ChasLui** [comment]
> > 当先路由只在 AppRouter又一个 `onRouteChange` 钩子, 并且也没有formUrl 参数, 导致很多时候需要做路由拦截很不方便, 期望:
> > 
> > 1. AppRouter 的 `onRouteChange`参数增加 `formUrl`
> > 2. AppRoute 增加 `router.beforeEach` ` router.beforeResolve`router.afterEach ``
> 
> formUrl 指的是？ onRouteChange 有具体的pathname、query、hash的解析结果透出了。具体诉求是？ AppRoute 在考虑增加两个钩子，onEnter、onLeave，能对外透出更多能力。这两个钩子是否能满足以上router.beforeEach router.beforeResolve``router.afterEach的所有操作？

sorry, 敲错了, 是 fromUrl, 需要这个属性的场景是方便做登录拦截的时候重定向回到之前的地址
onEnter, onLeave基本能满足我的业务需求了, 我能做在路由层面的一些鉴权和预处理后处理工作

**Comment by daysai** [comment]
> > > 当先路由只在 AppRouter又一个 `onRouteChange` 钩子, 并且也没有formUrl 参数, 导致很多时候需要做路由拦截很不方便, 期望:
> > > 
> > > 1. AppRouter 的 `onRouteChange`参数增加 `formUrl`
> > > 2. AppRoute 增加 `router.beforeEach` ` router.beforeResolve`router.afterEach ``
> > 
> > 
> > formUrl 指的是？ onRouteChange 有具体的pathname、query、hash的解析结果透出了。具体诉求是？ AppRoute 在考虑增加两个钩子，onEnter、onLeave，能对外透出更多能力。这两个钩子是否能满足以上router.beforeEach router.beforeResolve``router.afterEach的所有操作？
> 
> sorry, 敲错了, 是 fromUrl, 需要这个属性的场景是方便做登录拦截的时候重定向回到之前的地址
> onEnter, onLeave基本能满足我的业务需求了, 我能做在路由层面的一些鉴权和预处理后处理工作

fromUrl ,icestark 这边需要再权衡一下。建议可以通过 onRouteChange 的钩子自行记录每一次变化，然后剔除 type 为 replaceState 的干扰项，自行记录 fromUrl。内部实现的话，差不多也是这个样子。

**Comment by daysai** [comment]
目前规划，在 AppRouter 层增加 onAppEnter: (appProps) => {} 以及 onAppLeave: (appProps) => {} 统一处理app切换的相关逻辑。以及 AppRoute 层增加 type=”hash | browser“（默认为官方建议的browser），按照react-router的解析规则区分hash和browser的配置。计划下周发布新版本。

**Comment by daysai** [comment]
敬请关注 [pr: 17](https://github.com/ice-lab/icestark/pull/17) ~
