### ISSUE TITLE
阿里云OSS  上传失败

### ISSUE THREAD

**Issue by mtshen** [alibaba/ice#2778]
VUE项目, 阿里云OSS 上传时提示  上传失败:Converting circular structure to JSON
![image](https://user-images.githubusercontent.com/22271073/64089865-bb160f00-cd7a-11e9-9794-62c0df93facc.png)

**Comment by alvinhui** [comment]
运行日志面板错误信息，错误截图，或者【帮助>切换开发者工具】日志，以及【帮助>查看运行日志】log.log 文件
