### ISSUE TITLE
table组件，使用fixedHeader和lock时报错

### ISSUE THREAD

**Issue by baixc1** [alibaba/ice#2779]
重现方法：
  官方示例：http://ice.work/component/table#锁列（示例导航-锁列），打开在线预览，上下滑动列表，报错：Unable to preventDefault inside passive event listener due to target being treated as passive。使用全局样式（* { touch-action: pan-y; } ）无法解决问题。

**Comment by imsobear** [comment]
基础组件问题在这里反馈：https://fusion.design/feedback

**Comment by baixc1** [comment]
ok
