### ISSUE TITLE
因为这个项目喜欢上react，感觉文档指引作用很好，期待更多的好文档出现

### ISSUE THREAD

**Issue by smileboywtu** [alibaba/ice#278]

**Comment by yujiangshui** [comment]
我们内部还有一个快速入门的学习平台，看来要排期放出去了 @wssgcg1213 @noyobo

**Comment by yujiangshui** [comment]
@smileboywtu 你觉得还缺少哪些文档？

**Comment by smileboywtu** [comment]
我目前是后端开发，前端了解的比较少，除了ice使用方面的东西，我也想了解一下工程化的设计思路，规范，另外我也看到react 的 redux，顺带问一下，你们这块有涉及吗

**Comment by yujiangshui** [comment]
了解了，工程化的设计思路会在 https://zhuanlan.zhihu.com/ice-design 知乎专栏陆续写文章放出来。

redux 这块我们没有默认内置，但是可以用户手动引入。

**Comment by smileboywtu** [comment]
好的 我已经关注了 期待你们的深度剖析
