### ISSUE TITLE
建议：“创建页面”页面的布局优化

### ISSUE THREAD

**Issue by Empireo** [alibaba/ice#2789]
![](https://img.alicdn.com/tfs/TB1CJ8CfkL0gK0jSZFtXXXQCXXa-2542-1058.jpg)

一句话总结痛点：一屏只能显示一个区块的缩略图，ICE 区块辣么多，我一个个看的好累好难受

现在的布局给我的感受是组装出来的目标页面更大更清晰，但是个人觉得 2.0 的布局对于用户选择区块的需求来说更友好些，我现在的操作流程被迫变成了：先上官网看好所有要用的区块，再上客户端去选，对我来说客户端的创建页面展示不展示区块好像没多大区别（建议体验一下，比如组装一个）

**Comment by chenbin92** [comment]
@alvinhui 这个你这边看下？
