### ISSUE TITLE
icestark 中 AppRouter 可否支持 hashHistory？

### ISSUE THREAD

**Issue by Wiolem** [alibaba/ice#2792]
## 问题描述
```js
<AppRouter>
  <AppRoute
    path={["/dash", "/dash/list", "/dash/detail"]}
    exact
    title="dashboard hash 应用"
    url={[
      '//localhost:4444/js/dashboard.js',
      '//localhost:4444/css/dashboard.css',
    ]}
  />
</AppRouter>
```
icestark AppRouter 可否支持设置成 hash 的方式 ？

现在 http://localhost:4444/dash#/dash/detail  这样的地址才能进入子 hash 应用

不能 http://localhost:4444/#/dash/detail 进入

子应用
```js
<HashRouter basename={getBasename()}>
    <Switch>
       <Route path="/" exact component={List} />
       <Route path="/detail" component={Detail} />
    </Switch>
</HashRouter>
```

**Comment by daysai** [comment]
hash改变路由的方式不会改变pathname，目前的版本推荐的hash路由配置

**Comment by daysai** [comment]
> ## 问题描述
> ```js
> <AppRouter>
>   <AppRoute
>     path={["/dash", "/dash/list", "/dash/detail"]}
>     exact
>     title="dashboard hash 应用"
>     url={[
>       '//localhost:4444/js/dashboard.js',
>       '//localhost:4444/css/dashboard.css',
>     ]}
>   />
> </AppRouter>
> ```
> 
> icestark AppRouter 可否支持设置成 hash 的方式 ？
> 
> 现在 http://localhost:4444/dash#/dash/detail 这样的地址才能进入子 hash 应用
> 
> 不能 http://localhost:4444/#/dash/detail 进入
> 
> 子应用
> 
> ```js
> <HashRouter basename={getBasename()}>
>     <Switch>
>        <Route path="/" exact component={List} />
>        <Route path="/detail" component={Detail} />
>     </Switch>
> </HashRouter>
> ```

hash的改变不会改变pathname，目前子应用支持 hash。但AppRouter 的配置层还是以Browser判断的。之前想的子应用配置方式为：
```js
<AppRouter>
  <AppRoute
    path=”/dash“
    exact
    title="dashboard hash 应用"
    url={[
      '//localhost:4444/js/dashboard.js',
      '//localhost:4444/css/dashboard.css',
    ]}
  />
  <AppRoute
    path=”/run“
    exact
    title="run hash 应用"
    url={[
      '//localhost:4445/js/run.js',
      '//localhost:4445/css/run.css',
    ]}
  />
</AppRouter>
```
然后子应用都不需要配置 basename={getBasename()}。访问地址为：http://localhost:4444/dash#/detail  -> 访问 dash 子应用
http://localhost:4444/run#/detail  -> 访问 run 子应用
目前版本规划的 hash 路由是这么玩的。考虑到配置效果还是不够丰富，计划下周会新增 matchFunciton，支持 AppRoute 自行配置路由生效规则，彻底解决此问题。

**Comment by daysai** [comment]
同步在：[https://github.com/ice-lab/icestark/pull/17](https://github.com/ice-lab/icestark/pull/17)
