### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by amateurlee** [alibaba/ice#2794]
第一个安装命令就报错了啊，目录不存在，用sudo执行

![image](https://user-images.githubusercontent.com/5285062/64467289-d6519780-d149-11e9-9f47-c114da01dda8.png)

**Comment by imsobear** [comment]
看文档，请不要随意使用 sudo 

https://ice.work/docs/iceworks/Installation#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by amateurlee** [comment]
赞👍🏻
