### ISSUE TITLE
icestark框架注册基于umi开发的子应用

### ISSUE THREAD

**Issue by littleDaniel** [alibaba/ice#2797]
## 问题描述

umi子应用已经独立部署
在icestark中通过AppRoute注册子应用，引入静态资源地址如下：

```
<AppRoute
        path={['/', '/sys', '/detail']}
        basename="/"
        exact
        title="商家平台"
        url={[
          'http://120.24.171.5/umi.js',
          'http://120.24.171.5/umi.css',
        ]}
        
      />
```
其中，/sys与/detail均为子应用的路由

## 错误信息

结果：注册失败，子应用无法成功内嵌到框架应用中
问题：是icestark框架无法注册基于umi开发的子应用？还是配置有误？

**Comment by daysai** [comment]
配置一下 rootId，icestark默认给子应用创建的dom节点是ice-container。两种方式适配：1.可以把子应用内的挂载节点改为通过@ice/stark内的getMountNode；2.在AppRoute上通过rootId配置默认生成的节点id（注意此时不要和框架应用的自身挂载节点重复）

**Comment by daysai** [comment]
> ## 问题描述
> umi子应用已经独立部署
> 在icestark中通过AppRoute注册子应用，引入静态资源地址如下：
> 
> ```
> <AppRoute
>         path={['/', '/sys', '/detail']}
>         basename="/"
>         exact
>         title="商家平台"
>         url={[
>           'http://120.24.171.5/umi.js',
>           'http://120.24.171.5/umi.css',
>         ]}
>         
>       />
> ```
> 
> 其中，/sys与/detail均为子应用的路由
> 
> ## 错误信息
> 结果：注册失败，子应用无法成功内嵌到框架应用中
> 问题：是icestark框架无法注册基于umi开发的子应用？还是配置有误？

配置一下 rootId，icestark默认给子应用创建的dom节点是ice-container。两种方式适配：1.可以把子应用内的挂载节点改为通过@ice/stark内的getMountNode；2.在AppRoute上通过rootId配置默认生成的节点id（注意此时不要和框架应用的自身挂载节点重复）
