### ISSUE TITLE
能否实现表格下载 输出格式为excle

### ISSUE THREAD

**Issue by aLIEzsss4** [alibaba/ice#280]

**Comment by noyobo** [comment]
表格展示只是  excel 的一种 web 展现方式。  excel 下载需要后台提供转换生成文件数据。

js 也有对应的实现，你可以看下 https://github.com/clarketm/TableExport

**Comment by yujiangshui** [comment]
此外，就开发经验，这种功能推荐后端提供接口生成下载。数据通常会比较私密，经过后端接口可以做到权限控制 + 访问日志记录。
