### ISSUE TITLE
icestark动态菜单、路由

### ISSUE THREAD

**Issue by littleDaniel** [alibaba/ice#2803]
## 问题描述

使用icestark，做动态菜单，路由，AppRoute配置如下：
```
<AppRoute
        rootId="root"
        path={['/','/list']}
        basename="/"
        exact
        title="系统管理"
        url={[
          '//localhost:8000/umi.js',
          '//localhost:8000/umi.css',
        ]}
      />
```
## 错误信息
无论动态菜单是否有显示，已配置的AppRoute都会默认将页面渲染
问：子应用注册组件AppRoute是否可以做到动态，即权限控制力度与动态菜单、路由一致？

**Comment by daysai** [comment]
AppRoute本身也是组件，
可以设置 
hasPermission ? 
<AppRoute
        rootId="root"
        path={['/','/list']}
        basename="/"
        exact
        title="系统管理"
        url={[
          '//localhost:8000/umi.js',
          '//localhost:8000/umi.css',
        ]}
/> : null
或者 内部的path配置也可以是动态的。

**Comment by daysai** [comment]
> ## 问题描述
> 使用icestark，做动态菜单，路由，AppRoute配置如下：
> 
> ```
> <AppRoute
>         rootId="root"
>         path={['/','/list']}
>         basename="/"
>         exact
>         title="系统管理"
>         url={[
>           '//localhost:8000/umi.js',
>           '//localhost:8000/umi.css',
>         ]}
>       />
> ```
> 
> ## 错误信息
> 无论动态菜单是否有显示，已配置的AppRoute都会默认将页面渲染
> 问：子应用注册组件AppRoute是否可以做到动态，即权限控制力度与动态菜单、路由一致？

AppRoute本身也是组件，
可以设置 
{hasPermission ? 
     <AppRoute
        rootId="root"
        path={['/','/list']}
        basename="/"
        exact
        title="系统管理"
        url={[
          '//localhost:8000/umi.js',
          '//localhost:8000/umi.css',
        ]}
     /> : null}
或者内部的path配置也可以是动态的。
