### ISSUE TITLE
物料模板规范中package.json内字段支持自定义~

### ISSUE THREAD

**Issue by xianzou** [alibaba/ice#2808]
## 问题描述

期望物料模板规范中package.json的字段可以自定义，并保存到物料库的npm  run generate命令生成的materials.json中；

## 示例
假设我们物料库下通过idev add生成组件ProgressBar，我想往组件的package.json新增自定义字段needDependencies:[],来描述我这个组件需要用到哪些外部的依赖(只是举例)，最后通过物料库的npm  run generate命令能添加到materials.json中，目前npm  run generate好像不识别自定义的packages.json字段。

**Comment by imsobear** [comment]
@xianzou materials.json 是 iceworks 消费的，加了自定义数据貌似也没意义，你这边的具体场景是什么？会自己消费 materials.json？

**Comment by xianzou** [comment]
是的，我们想自己添加一些数据进去，如果支持自定义，那我们可以自己开发预览平台，通过这些自定义的数据可以支持更多的信息展示




| |
李家其
邮箱：lijiaqijl@163.com
|

签名由 网易邮箱大师 定制

在2019年09月23日 18:36，大果 写道：

@xianzou materials.json 是 iceworks 消费的，加了自定义数据貌似也没意义，你这边的具体场景是什么？会自己消费 materials.json？

**Comment by imsobear** [comment]
嗯 我在重构的这个版本应该支持这个能力了 https://github.com/alibaba/ice/pull/2820/files#diff-4c2040dc1bde0b820e470cb48a66118eR36

**Comment by xianzou** [comment]
好的，谢谢你，我去关注一下




| |
李家其
邮箱：lijiaqijl@163.com
|

签名由 网易邮箱大师 定制

在2019年09月24日 09:48，大果 写道：

嗯 我在重构的这个版本应该支持这个能力了 https://github.com/alibaba/ice/pull/2820/files#diff-4c2040dc1bde0b820e470cb48a66118eR36
