### ISSUE TITLE
@ice/form 中的Field插件不重新渲染

### ISSUE THREAD

**Issue by tovei** [alibaba/ice#2809]
## 问题描述
封装了IceForm插件，外部调用该插件重新渲染整个form,所有的field直接用新的。但是发现Field中的内容不根据传参变化。用之前的Form.item是可以的。什么原因？

## 错误信息
无

**Comment by imsobear** [comment]
组件问题给个重现 demo： https://codepen.io/sobear/pen/NeJmOG?editors=0011

**Comment by imsobear** [comment]
出于性能考虑，`@ice/form` 是内部管理状态的，因此无法响应外部的 state 变化，需要通过 API 的方式来动态改变，比如动态改变 label 的一个例子：https://codepen.io/sobear/pen/wvwYMPa

对于一些复杂的动态场景，比如动态改变多个表单配置（通过数据驱动的表单），[demo](https://codepen.io/sobear/pen/bGbmVgm)，暂时先推荐重新渲染整个 form（form 上加个 key 属性），我们再看下这种场景怎么支持。
