### ISSUE TITLE
Vue 物料 d2admin 模板在 iceworks@3.0 未显示

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#2810]
升级路由相关写法

![image](https://user-images.githubusercontent.com/2505411/64964447-a898eb00-d8cd-11e9-9cb3-c3223dc23ae7.png)

**Comment by JyenZhou** [comment]
已订阅

**Comment by chenbin92** [comment]
@JyenZhou 已联系 d2-admin 负责的同学，已在跟进中

**Comment by chenbin92** [comment]
@imsobear  李杨那边因为时间问题之前计划的时间需要变更，目前暂时无法支持。如果不能稳定的维护，我的建议是 3.x 不在推荐，避免后续的维护和升级的成本问题

**Comment by chenbin92** [comment]
@JyenZhou  3.x 已支持

![image](https://user-images.githubusercontent.com/3995814/69228476-99c90000-0bbe-11ea-8f05-3bb68ad5016d.png)
