### ISSUE TITLE
菜单管理增加多菜单需求

### ISSUE THREAD

**Issue by meng-zhangmm** [alibaba/ice#2811]
## 问题描述
在 visual studio code里写了多个菜单，例如export { headerMenuConfig, asideMenuConfig,asideMenuConfig2 ，asideMenuConfig3}; 但是，在飞冰http://127.0.0.1:8000/project 项目管理中的菜单管理模块，默认显示的是headerMenuConfig，asideMenuConfig，新增的asideMenuConfig2 ，asideMenuConfig3菜单不能显示在菜单管理模块
（如若觉得描述的不清楚，请联系我：飞冰六群，姓名：zzz）

**Comment by imsobear** [comment]
对应修改下渲染菜单部分的代码逻辑即可，一般在 layouts 里
