### ISSUE TITLE
部分请求proxy不生效的问题

### ISSUE THREAD

**Issue by baldyellow** [alibaba/ice#2816]
# 部分请求proxy不生效的问题

（下面是对问题的描述和记录）

>## 碰到了什么问题？
>
>首先贴一下package.json中[Ice-scripts](https://ice.work/docs/cli/about)的版本和相关配置：
>
>*package.json*
>```
>{
>    ...
>    "devDependencies": {
>        ...
>        "ice-scripts": "^1.10.1",
>        ...
>    }
>    ...
>    "proxyConfig": {
>        "/api/": {
>            "enable": true,
>            "target": "http://some-api-path",
>            "changeOrigin": true
>        },
>        ...
>    }
>    ...
>}
>```
>
>而[devServer](https://webpack.js.org/configuration/dev-server)剩下的配置在.webpackrc.js里：
>
>*.webpackrc.js*
>```
>{
>    ...
>    "devServer": {
>        "historyApiFallback": true
>    }
>    ...
>}
>```
>
>在项目中，用到两种方式调用接口，一种是通过[Axios](https://www.npmjs.com/package/axios)调用，主要用在展示和更新数据；另一种是通过[Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API)请求，主要用在下载文件。
>
>问题出在，通过Axios获取JSON数据的方式，proxy代理配置可以生效，而通过Fetch调用接口获取文件流的方式，接口通通返回index.html。这表现可以推断出，代理配置没起作用，导致请求404，最终fallback到了index.html。
>
>## 排查问题原因
>
>一开始，是怀疑两种请求方式本身（XHR和Fetch）差异导致的，但捣腾了一会儿后发现这样一个情况：当尝试把package.json中的proxyConfig配置放到.webpackrc.js的devServer里之后，Fetch方式一样可以通过代理了。
>
>于是改变排查方向，从Ice入手。
>
>通过查看[Ice-scripts源码](https://github.com/ice-lab/ice-scripts)发现，在/lib/dev.js中有这样一段：
>
>*/lib/dev.js*
>```
>...
>const WebpackDevServer = require('webpack-dev-server');
>...
>const devMiddleware = require('./devMiddleware');
>...
>module.exports = async function (cliOptions, subprocess) {
>    ...
>    const devServer = new WebpackDevServer(compiler, devServerConfig);
>
>    devMiddleware(devServer.app, proxyConfig);
>    ...
>};
>```
>
>其中devMiddleware调用的是/lib/devMiddleware.js里的代码：
>
>*/lib/devMiddleware.js*
>```
>const httpProxyMiddleware = require('http-proxy-middleware');
>...
>module.exports = (app, proxyConfig) => {
>    ...
>    const exampleProxy = httpProxyMiddleware(match, proxyOptions);
>    app.use(exampleProxy);
>    ...
>};
>```
>
>Ice先用不包含proxy的配置生成[Webpack-dev-server](https://www.npmjs.com/package/webpack-dev-server)实例，然后再在实例上加载[Http-proxy-middleware](https://www.npmjs.com/package/http-proxy-middleware)处理过的proxy配置。
>
>如果，我们把/lib/dev.js里的那两行代码修改一下，在生成Webpack-dev-server实例之前，把proxy配置也加入到config里，一次性生成实例：
>
>*/lib/dev.js*
>```
>...
>// 把proxy配置加入devServerConfig，一次性生成实例
>devServerConfig.proxy = proxyConfig;
>
>const devServer = new WebpackDevServer(compiler, devServerConfig);
>
>// 取消作为中间件加载proxy
>// devMiddleware(devServer.app, proxyConfig);
>...
>```
>
>结果代理配置可以对Fetch方式起效，正常获取文件流。
>
>于是怀疑问题出在这里：一次性把所有配置全交给Webpack-dev-server实例化，代理表现正常；先实例化，再加载代理配置，代理表现异常。继续查看[Webpack-dev-server源码](https://github.com/webpack/webpack-dev-server)，在/lib/server.js中：
>
>*/lib/server.js*
>```
>...
>class Server {
>    constructor(compiler, options = {}, _log) {
>        ...
>        this.setupFeatures();
>        ...
>    }
>    ...
>    setupFeatures() {
>        const features = {
>            ...
>            proxy: () => {
>                if (this.options.proxy) {
>                    this.setupProxyFeature();
>                }
>            },
>            historyApiFallback: () => {
>                if (this.options.historyApiFallback) {
>                    this.setupHistoryApiFallbackFeature();
>                }
>            },
>            ...
>        };
>
>        const runnableFeatures = [];
>        ...
>        if (this.options.proxy) {
>            runnableFeatures.push('proxy', 'middleware');
>        }
>        ...
>        if (this.options.historyApiFallback) {
>            runnableFeatures.push('historyApiFallback', 'middleware');
>            ...
>        }
>        ...
>        (this.options.features || runnableFeatures).forEach((feature) => {
>            features[feature]();
>        });
>    }
>    ...
>}
>...
>```
>
>这段体现出了这样一个先后顺序：先根据是否有proxy配置，执行setupProxyFeature，再根据是否有historyApiFallback配置，执行setupHistoryApiFallbackFeature。
>
>那么问题就来了，如果按照Ice的做法，把proxy配置后置，先historyApiFallback后proxy，会有什么问题？我们看一下setupHistoryApiFallbackFeature做了些什么：
>
>*/lib/server.js*
>```
>...
>const historyApiFallback = require('connect-history-api-fallback');
>...
>class Server {
>    ...
>    setupHistoryApiFallbackFeature() {
>        ...
>        this.app.use(historyApiFallback(fallback));
>    }
>    ...
>}
>...
>```
>
>调用了[Connect-history-api-fallback](https://www.npmjs.com/package/connect-history-api-fallback)，来看一下它的[源码](https://github.com/bripkens/connect-history-api-fallback)：
>
>*/lib/index.js*
>```
>...
>exports = module.exports = function historyApiFallback(options) {
>    options = options || {};
>    var logger = getLogger(options);
>
>    return function(req, res, next) {
>        var headers = req.headers;
>        if (req.method !== 'GET') {
>            logger(
>                ...
>            );
>            return next();
>        } else if (!headers || typeof headers.accept !== 'string') {
>            logger(
>                ...
>            );
>            return next();
>        } else if (headers.accept.indexOf('application/json') === 0) {
>            logger(
>                ...
>            );
>            return next();
>        } else if (!acceptsHtml(headers.accept, options)) {
>            logger(
>                ...
>            );
>            return next();
>        }
>
>        var parsedUrl = url.parse(req.url);
>        var rewriteTarget;
>        options.rewrites = options.rewrites || [];
>        for (var i = 0; i < options.rewrites.length; i++) {
>            var rewrite = options.rewrites[i];
>            var match = parsedUrl.pathname.match(rewrite.from);
>            if (match !== null) {
>                ...
>                req.url = rewriteTarget;
>                return next();
>            }
>        }
>
>        var pathname = parsedUrl.pathname;
>        if (pathname.lastIndexOf('.') > pathname.lastIndexOf('/') &&
>            options.disableDotRule !== true) {
>            logger(
>                ...
>            );
>            return next();
>        }
>
>        rewriteTarget = options.index || '/index.html';
>        logger('Rewriting', req.method, req.url, 'to', rewriteTarget);
>        req.url = rewriteTarget;
>        next();
>    };
>};
>...
>function acceptsHtml(header, options) {
>    ...
>}
>
>function getLogger(options) {
>    ...
>}
>```
>
>可以看出，当不满足：
>
>- 请求类型非GET
>- 请求头中没有Accept
>- Accept以“application/json”开头
>- Accept不接受HTML
>- 未匹配到rewrite规则，且disableDotRule为false情况下“.”出现在“/”之后
>
>以上条件时（总之是为了确认是否可以重定向返回HTML内容），req.url将被改写成rewriteTarget，然后再调用next，进入后续流程。于是我们就可以解答刚才的问题：**如果先historyApiFallback后proxy，那么proxy接收的req可能已经被historyApiFallback改写了。**
>
>到这里，我们回头看看最初，问题的表现：Axios方式代理有效，Fetch方式代理无效。问题关键点渐渐浮现了，可以做如下猜测：项目中Axios方式主要是操作一些业务数据，交互的数据格式都是JSON；而Fetch方式用于下载，接收的都是数据流。这两者之间，和接口约定的数据类型不同。
>
>验证一下这两者的请求头：
>
>- Axios：
>
>  *Axios*
>  ```
>  ...
>  Accept: application/json, text/plain, */*
>  ...
>  ```
>- Fetch：
>
>  *Fetch*
>  ```
>  ...
>  Accept: */*
>  ...
>  ```

**Comment by ClarkXia** [comment]
ice-scripts 2.x 中的代理方式已优化为添加 devServer

**Comment by imsobear** [comment]
@baldyellow 可以升级到 ice-scripts@2.x https://ice.work/docs/cli/migrate ，如果还有问题麻烦再 reopen 下
