### ISSUE TITLE
icestark路由

### ISSUE THREAD

**Issue by littleDaniel** [alibaba/ice#2817]
## 问题描述

icestark是否只能配置子应用的路由，如果想在框架应用里使用登录页，登录页的路由配置入口是在哪里？或者有其他解决方案？

## 错误信息
通过iceworks工作台的路由管理针对icestark框架应用进行路由配置 ，一直配置失败，显示暂无路由

**Comment by daysai** [comment]
icestark 对框架应用是否引用 react-router 没有限制。但推荐将框架应用只作为资源配置、控制渲染的容器存在，因此我们建议将 登录页、403等公共页面抽离成一个单独的子应用，作为子应用引入。
