### ISSUE TITLE
能把ICEDesignBase.css这里面所有文件里调的字库文件本地化吗？

### ISSUE THREAD

**Issue by 775174143** [alibaba/ice#2819]
![image](https://user-images.githubusercontent.com/29495296/65371325-26297600-dc95-11e9-868c-8701d9a09889.png)
![image](https://user-images.githubusercontent.com/29495296/65371331-36415580-dc95-11e9-9e2d-f320549d4acc.png)

**Comment by imsobear** [comment]
https://ice.work/docs/cli/plugin-list/local
