### ISSUE TITLE
meteor 框架结合飞冰

### ISSUE THREAD

**Issue by saxihuangxing** [alibaba/ice#2822]
飞冰能够用在meteor框架上吗，用飞冰开发UI。

**Comment by imsobear** [comment]
基本上所有的后端应用都可以通过这种方式集成：https://ice.work/docs/guide/backend/nodejs

**Comment by saxihuangxing** [comment]
@imsobear  meteor 是全栈框架，前端是可以支持react的，但是要使用 ice的话就不知道怎么搞了，折腾了很久。因为meteor 有自己的工具去编译启动工程，meteor run 。 而ice也要用自己的自己工具去编译启动工程 ice-script 。 而如果 用meteor的工具去编ice 会有scss编译错误(尚未知是否有其他错误）.我是想在meteor的工具里面改成使用ice-script去编前端代码，折腾很久，感觉比较难搞。

**Comment by imsobear** [comment]
你想用 ICE 核心能力是哪块？

**Comment by saxihuangxing** [comment]
我就想用ICE做UI，我是直接用ICE客户端生成了模版，主要是要用到iceDesign  和  alifd 里面的组件。

**Comment by imsobear** [comment]
这个我们先研究下 meteor 看看，具体问题要再明确下

**Comment by saxihuangxing** [comment]
好的，非常感谢，因为我对scss,jsx这个编译过程不太了解，不确定是否能与meteor结合使用，之前又用飞冰开发了一些UI了，不想放弃。

**Comment by imsobear** [comment]
@saxihuangxing 可否提供一个完整的项目然后把问题再具体点，我们看一下
