### ISSUE TITLE
icework 3.0 升级问题

### ISSUE THREAD

**Issue by guoxunbo** [alibaba/ice#2825]

**Comment by guoxunbo** [comment]
1. 2.2.4版本升级到3。发现换了文件之后config/router等等都不行。启动的时候都报错了。
ice 不是启动命令。。。如下是package.json的部分截图
![image](https://user-images.githubusercontent.com/14329149/65496708-8c0f3b00-deeb-11e9-8f17-07dd12415bad.png)
2. 去看了一个新的构建项目。换成了ice-scripts.我去install了一个也不行。。。求助。

**Comment by imsobear** [comment]
- iceworks 是辅助工具，你这个问题参考这篇文档：https://ice.work/docs/iceworks/migrate
- ice-scripts 是工程构建工具，跟你这个问题不相关，不过你想升级的话也可以升级（推荐分开升级）：https://ice.work/docs/cli/migrate

搞不定的话，钉钉加下这个群：

![](https://ice.alicdn.com/assets/images/qrcode.png)
