### ISSUE TITLE
我使用的webpack3.8 使用的_@icedesign_base@0.2.8@@icedesign，可以本地化资源吗ice-plugin-css-assets-local依赖要webpack>=4.0

### ISSUE THREAD

**Issue by 775174143** [alibaba/ice#2826]
![image](https://user-images.githubusercontent.com/29495296/65495536-7dc01f80-dee9-11e9-8310-137bc0e7baf8.png)
字体文件

**Comment by imsobear** [comment]
工程推荐使用 ice-scripts，自建的 webpack 配置需要自己看下怎么解决，这块我们不太好支持，还望理解。
