### ISSUE TITLE
ICE 业务组件支持 typescript

### ISSUE THREAD

**Issue by gooddaddy** [alibaba/ice#2827]
能否为组件添加一下typescript的类型声明文件，这样typescript的工程也能很好地使用。

**Comment by imsobear** [comment]
指业务组件吗？

**Comment by daysai** [comment]
> 能否为组件添加一下typescript的类型声明文件，这样typescript的工程也能很好地使用。

确认一下是针对模板？区块？还是业务组件？

**Comment by gooddaddy** [comment]
React-materials/components

这些组件,因为icework的生成的模板中经常会使用到这些组件，并且在实际开发中也经常会使用到，如果能支持 typescript开发那更好不了，不然使用者得自己编写并维护t.ds





------------------ 原始邮件 ------------------
发件人: "daysai"<notifications@github.com>;
发送时间: 2019年9月25日(星期三) 上午10:33
收件人: "alibaba/ice"<ice@noreply.github.com>;
抄送: "小波"<272499344@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [alibaba/ice] react-materials 组件 支持typescript (#2827)



 
能否为组件添加一下typescript的类型声明文件，这样typescript的工程也能很好地使用。
  
确认一下是针对模板？区块？还是业务组件？

**Comment by imsobear** [comment]
@gooddaddy 这个可以搞，我们跟进一下

**Comment by gooddaddy** [comment]
@imsobear  typescript支持的问题，你们有没有开发计划。

**Comment by imsobear** [comment]
有的，如果着急的话可以先提 PR：https://github.com/ice-lab/react-materials/tree/master/components

**Comment by gooddaddy** [comment]
@imsobear 我想知道大概什么时候能实行，我要说服公司的人使用飞冰框架，有人纠结ice对typescript不友好

**Comment by imsobear** [comment]
@gooddaddy 那我觉得可以尽可能详细的梳理下哪一块都有问题，我们可以发起一个专门的项目做针对性优化，比如：

- 业务组件没有 ts 声明
- ts 模板不完善？
- icestore 对 ts 支持不够好（具体点？）

比如这些，你可以梳理下，然后我们整体来给个时间点

**Comment by gooddaddy** [comment]
@imsobear 就组件，react-materials 的component，能否提供 @types/**  这包，这样ts上就能够直接使用了，否则 我的 一个个去补这些 声明文件哦

**Comment by imsobear** [comment]
@gooddaddy 最晚 10 月底发布

**Comment by chenbin92** [comment]
@gooddaddy  可以加一下飞冰钉钉群，然后联系群主进行沟通 https://ice.alicdn.com/assets/images/qrcode.png

**Comment by imsobear** [comment]
done
