### ISSUE TITLE
Windows 启动 iceworks 报错 egg-scripts 不存在

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#2835]
![image](https://user-images.githubusercontent.com/3995814/65769359-fa5f3200-e165-11e9-9a75-bf6878cf3ed0.png)

**Comment by Ghostliming** [comment]
同样的错。
![image](https://user-images.githubusercontent.com/11506222/65814508-53d26a00-e215-11e9-99f6-fdaa3782f415.png)

**Comment by ipfans** [comment]
The same.

**Comment by imsobear** [comment]
同类问题，合并掉了：https://github.com/alibaba/ice/issues/2847

**Comment by imsobear** [comment]
https://github.com/alibaba/ice/pull/2853
