### ISSUE TITLE
ice-scripts@1.x 版本部署后 js 文件缓存问题

### ISSUE THREAD

**Issue by guoxunbo** [alibaba/ice#2838]
## 问题描述
在2+版本上要想打包后部署不从缓存获取的话，有什么办法。我看了下3+版本是设置了hash:true。
2+版本是在哪边加呢？package.json里？
![image](https://user-images.githubusercontent.com/14329149/65828994-72973600-e2d3-11e9-815f-e25d740462d0.png)
这样？

**Comment by imsobear** [comment]
ice-scripts 从 1.x 升级到 2.x  https://ice.work/docs/cli/migrate
