### ISSUE TITLE
iceworks客户端版本2.24.0 选择移动端模板提示请求模板包失败

### ISSUE THREAD

**Issue by wuxiangyu0126** [alibaba/ice#2839]
## 问题描述
在iceworks（客户端版本2.24.0中）添加移动端物料（地址：https://fusion.alibaba-inc.com/api/v1/sites/491/materials ）后引用模板，提示请求模板包失败

## 错误信息
![IMAGE](https://img.alicdn.com/tfs/TB1AEeQhHH1gK0jSZFwXXc7aXXa-1964-1424.png)
模板包地址:https://registry.npm.alibaba-inc.com/@alife/mobile-materials-mobile-scaffolds

**Comment by chenbin92** [comment]
设置面板 npm 源修改为内网源即可
