### ISSUE TITLE
iceworks 3.1.0版本使用模板创建项目失败

### ISSUE THREAD

**Issue by xiaosuoWu** [alibaba/ice#2842]
## 问题描述
iceworks 3.1.0版本使用模板常见项目失败，回退到3.0.0版本后可以正常创建项目，使用node版本8.9.1
## 错误信息
![IMAGE](https://img.alicdn.com/tfs/TB1rPlJiEH1gK0jSZSyXXXtlpXa-1420-1414.png)

**Comment by alvinhui** [comment]
## 临时解决

使用命令行创建项目：

0. `mkdir ice-test && cd ice-test` 
0. ` iceworks init @icedesign/pro-scaffold`

再启动 iceworks 导入项目。
