### ISSUE TITLE
iceworks3.1.0GUI面板启动项目部分状态显示不正确

### ISSUE THREAD

**Issue by zhaochenjun** [alibaba/ice#2843]
## 错误信息

iceworks3.1.0网页管理端的项目模块中的启动项目功能,如果有多个项目,运行和停止的状态会不正确(感觉像是受最后一次点的项目的状态影响),不同的项目还会显示相同的访问地址

**Comment by alvinhui** [comment]
问题确实存在，将会在 3.4.1 版本里解决
