### ISSUE TITLE
ice-scripts 增加run dev的时候输出编译后到资源到lib目录

### ISSUE THREAD

**Issue by bojoyzhou** [alibaba/ice#2844]
ice-scripts在dev的时候不会编译输出到lib目录，在需要npm link 联调的场景很不方便，而每次run build 需要大量的时间。 希望支持。

**Comment by ClarkXia** [comment]
一般场景下在开发组件的时候借助 demo 的能力进行联调，如果要在 dev 的时候输出到 lib，本质上是走watch 文件变更 然后 run build。
可以具体看下是不是有通过 demo 能力调试不能解决的场景。

**Comment by imsobear** [comment]
link 的场景需要 watch (src -> lib)，应该是这个需求

**Comment by bojoyzhou** [comment]
> link 的场景需要 watch (src -> lib)，应该是这个需求

是这个意思

**Comment by ClarkXia** [comment]
已支持，ice-plugin-component 支持 watch 参数开启监听:
```js
module.exports = {
  injectBabel: 'runtime',
  publicPath: './',
  plugins: [
    'ice-plugin-fusion',
    ['ice-plugin-component', {
      watch: true,
    }],
    ['ice-plugin-moment-locales', {
      locales: ['zh-cn'],
    }],
  ],
};
```
