### ISSUE TITLE
egg-scripts:command not found

### ISSUE THREAD

**Issue by luojinghui** [alibaba/ice#2847]
node: 10.15.0
系统：mac os ，10.14
iceworks: 最新版

## 问题描述

安装了全局的iceworks后，执行：
```bash
$ iceworks
```
命令报错：
 
<img width="849" alt="WechatIMG411" src="https://user-images.githubusercontent.com/12367406/66559806-a18d9180-eb88-11e9-98b1-16d9547b5f0e.png">

卸载整个iceworks，重新安装也是一样的错误。估计是cli工具的问题。

**Comment by luojinghui** [comment]
> 先手动删除打印出来的那个目录 /Users/xxx/.iceworks-server，然后重新启动试下，这个问题我们在跟进中。

不行，尝试过，我们删除了home目录的.iceworks-server文件，重新启动，还是一样在安装完依赖后，报egg-script not found的错误。

**Comment by imsobear** [comment]
@luojinghui 那在 .iceworks-server 目录下执行下 npm install 再启动呢

**Comment by ChenJiaojiao123** [comment]
我试试

**Comment by ChenJiaojiao123** [comment]
> @luojinghui 那在 .iceworks-server 目录下执行下 npm install 再启动呢

在.iceworks-server目录下执行npm intsall出现了这样的错误：
![1570706257345](https://user-images.githubusercontent.com/32218517/66564484-abb48d80-eb92-11e9-9362-716ad46b5cec.jpg)

**Comment by ChenJiaojiao123** [comment]
好的


 
---Original---

**Comment by ChenJiaojiao123** [comment]
> ![image](https://user-images.githubusercontent.com/2505411/66570195-b295cd00-eb9f-11e9-9fff-4191e83990fe.png)
> 
> 加下这个钉钉群吧

现在好啦，npm install前要加sudo

**Comment by chenbin92** [comment]
https://github.com/alibaba/ice/pull/2853
