### ISSUE TITLE
如何在 IMG 中使用本地图片

### ISSUE THREAD

**Issue by songhuagao** [alibaba/ice#285]
`
 <Img
          enableAliCDNSuffix={true}
          width={300}
          height={200}
          src="//img.alicdn.com/tfs/TB1oPNcPFXXXXXQXpXXXXXXXXXX-341-202.png"
          type="cover"
          shape="sharp"
          style={{border: '1px solid #ccc', margin: '10px'}}
        />
`
示例中都是使用外链的, 如何使用本地的图片?

**Comment by wssgcg1213** [comment]
docs + 如何使用本地图片

**Comment by noyobo** [comment]
```
<Img enableAliCDNSuffix={true} width={300} height={200} src={require('../local/img.jpg')} type="cover" shape="sharp" style={{border: '1px solid #ccc', margin: '10px'}} />
```
