### ISSUE TITLE
无法打开编辑器webstorm

### ISSUE THREAD

**Issue by lroyzz** [alibaba/ice#2855]
## 错误信息

![image](https://user-images.githubusercontent.com/29371605/66643441-48d5fb80-ec51-11e9-8b70-d919906baa39.png)

**Comment by alvinhui** [comment]
如果 webstorm 已经启动，那么在 iceworks 点击编辑器时是可以启动 webstorm 的。

如果 webstorm 没有启动，需要尝试在终端中输入 `$ webstorm.ext`，确保在命令行中可以执行该命令。

如果不能，则参考 https://www.jetbrains.com/help/webstorm/working-with-the-ide-features-from-command-line.html 进行配置。
