### ISSUE TITLE
[icekit] pro 模板侧边菜单从收缩状态切换到展开状态时，二级菜单 padding 丢失

### ISSUE THREAD

**Issue by temper357** [alibaba/ice#2860]
## 问题描述

pro 模板先点击顶部菜单收缩按钮，再点击一次展开菜单，二级菜单 padding 丢失
侧边菜单从收缩状态切换到展开状态时，二级菜单 padding 丢失

出错状态：二级菜单 Monitor 的左侧 padding 丢失
<img width="198" alt="DC776C19-4847-45A8-8830-15A4CE809687" src="https://user-images.githubusercontent.com/5419233/66737904-c2632900-ee9f-11e9-8ce6-519898e8ee8a.png">

正常状态：
<img width="209" alt="F54A31E1-75C3-425C-B2D0-5CE300D28FA2" src="https://user-images.githubusercontent.com/5419233/66737877-b6776700-ee9f-11e9-8e0d-5ff516709f3f.png">

**Comment by xiaozhendong** [comment]
我出现过类似状况。不知道能不能解决你的问题，我是把NAV style的width设置成和侧边栏Aside一样的宽度，收缩打开之后就不会出现这种情况

**Comment by raohuiyong** [comment]
希望官方早点出解决方案吧

**Comment by raohuiyong** [comment]
最近试了下，是在没啥办法解决，直接给.next-nav .next-menu-sub-menu .next-menu-item的样式添加了一个padding-left:40px;然后就暂时好了。

**Comment by temper357** [comment]
该问题属于 Nav 组件实现上的 bug，定位问题后提给 next 团队

**Comment by imsobear** [comment]
已发布新版本的 Fusion Design Pro，视觉上做了大量优化，可以尝试下：[预览地址](https://unpkg.com/@alifd/fusion-design-pro@0.1.22/build/index.html)

执行 `npm init ice ice-app` 即可
