### ISSUE TITLE
iceworks中阿里云OSS上传配置针对项目

### ISSUE THREAD

**Issue by YunGouOS** [alibaba/ice#2863]
目前iceworks阿里云OSS上传配置是针对全局的，这将导致多个项目时候上传时候需要重复配置上传目录，有时候点快了还有可能传错目录吧其他项目的目录给覆盖，故希望OSS的配置能够针对项目，这样上传则不需要重复配置目录

**Comment by alvinhui** [comment]
iceworks 3.0 已经不是全局而是针对项目的了，参考 https://ice.work/docs/iceworks/migrate 进行升级。
