### ISSUE TITLE
icestore 中的setState 是否应改为异步设置

### ISSUE THREAD

**Issue by xluos** [alibaba/ice#2866]
目前icestore中setState的调用是在 action执行完成后立即调用的，当我要连续设置多个值的时候就会多次的调用setState造成页面多次渲染。是否应该设置一个队列机制，将一段时间内的修改收集统一进行渲染？

**Comment by temper357** [comment]
@xluos icestore 目前还没有设计 batchUpdate 的机制，你当前可以对要连续执行的 action 做一层封装，放进一个新的 action，在 component 中执行封装后的 action

**Comment by xluos** [comment]
@temper357 我最开始是这样做的, 因为A的值对于B、C存在约束，所以设置B、C的时候需要进行一些判断，在A的值变化后需要重新计算B、C的值。为了复用代码 我直接使用this调用B、C对应的action。发现组件渲染了多次。为了解决这个问题我不得不把相关的代码拷贝多次，对于这样的场景有什么更优的解决方案吗？
```js
{
  stateA: '',
  setStateA (val) {
    this.stateA = val
    // ... 一些判断操作
    this.setStateB(val)
    this.setStateC(val)
  },
  stateB: '',
  setStateB (val) {
    // ...一些判断操作 A的值会对B、C存在约束 
    this.stateB = val
  },
  stateC: '',
  setStateC (val) {
    // ...一些判断操作 A的值会对B、C存在约束 
    this.stateC = val
  }
}
```

**Comment by temper357** [comment]
@xluos 你可以将 setStateB 和 setStateC 中的逻辑通过纯函数方式定义在 store 对象的外部，然后分别在 action 中调用这些函数，也可以达到复用目的，例如以下：

```javascript
 
function mutateB(val) {
   ......
   return ....;
}

const store = {
  stateA: '',
  setStateA(val) {
     this.stateA = val;
     this.stateB = mutateB(val);
     this.stateC = mutateC(val);
  },
  stateB: '',
  setStateB(val) {
    this.stateB = mutateB(val);
 }
 ......
}
