### ISSUE TITLE
loader 的配置 如何控制顺序

### ISSUE THREAD

**Issue by gooddaddy** [alibaba/ice#2870]
## 问题描述

 // 增加svg文件的解析
    config.module
      .rule('svg')
      .use('svg')
      .loader('@svgr/webpack')

这样写会覆盖之前svg的配置不，还是只是在后面增加了loader？ 如果想调整顺序如何弄

**Comment by ClarkXia** [comment]
如果想覆盖 svg 的规则可以先确认是否有svg 规则，有的话可以进行覆盖，关于顺序问题 webpack-chain 提供类似 before / after 的 API 可以进行调整 https://github.com/neutrinojs/webpack-chain
