### ISSUE TITLE
启动项目报 maximum call stack size exceeded

### ISSUE THREAD

**Issue by alvinhui** [alibaba/ice#2873]
## 版本信息

- iceworks: 3.1.2
- node: 8.16

## 问题描述

在界面中点击「启动」。

界面显示：

![image](https://user-images.githubusercontent.com/4392234/67061083-b7efaa80-f191-11e9-9ef4-fd94f5c2ab2c.png)

Bash 中报错：

![image](https://user-images.githubusercontent.com/4392234/67061064-a0182680-f191-11e9-9c4b-69d641b77747.png)
![image](https://user-images.githubusercontent.com/4392234/67061068-a3abad80-f191-11e9-98f7-31123ed6f346.png)

**Comment by chenbin92** [comment]
排查中
