### ISSUE TITLE
增加命令行参数禁止每次自动打开localhost:4444页面

### ISSUE THREAD

**Issue by orangeyyy** [alibaba/ice#2875]
## 问题描述

现在ice-script执行dev命令时默认会校验public/index.html文件，并且自动打开localhost:4444页面，在有些场景下，dev只是希望起一个资源服务，并代理到本地node服务或者是线上环境，每次都弹测试页的体验不太好，希望能够增加一个命令行参数来禁用掉两面两个功能。
## 错误信息
![image](https://user-images.githubusercontent.com/19667299/67074074-f8afe980-f1ba-11e9-846d-5137eb2c4875.png)
![image](https://user-images.githubusercontent.com/19667299/67074195-2dbc3c00-f1bb-11e9-8bdc-a8355649fa83.png)

**Comment by imsobear** [comment]
`--disabled-reload`
