### ISSUE TITLE
业务组件对接FusionCool的时候，build/index.scss 文件里面没换行

### ISSUE THREAD

**Issue by bindoon** [alibaba/ice#2876]
## 问题描述

![image](https://user-images.githubusercontent.com/5189853/67080665-497a0f00-f1c8-11e9-9808-3037ad3f77e7.png)
![image](https://user-images.githubusercontent.com/5189853/67080675-4da62c80-f1c8-11e9-9c32-79e4cf3e38eb.png)

https://unpkg.com/@alifd/biz-anchor@1.1.1/build/index.scss

**Comment by imsobear** [comment]
@bindoon 这个你来提个 PR？相关代码在这里：https://github.com/ice-lab/ice-scripts/tree/master/packages/ice-plugin-component

**Comment by ClarkXia** [comment]
ice-plugin-component@0.1.7 已修复
