### ISSUE TITLE
寻找文档

### ISSUE THREAD

**Issue by wital** [alibaba/ice#2881]
有没有一个给后端的文档呀，带着做一遍的。感觉飞冰文档太少了

**Comment by wital** [comment]
我是一个纯后端，学了2天前端，想用飞冰做一个管理平台，现在的文档对了我这样的情况还是难了一点。比如现在登陆以后，所有的请求都要加上token。我看现在的文档就不知道怎么加上这一步。可能我描述的有问题，我需要的应该是一个教程。不是文档。

**Comment by imsobear** [comment]
春节前后会出视频教程，这个 issue 先关掉了
