### ISSUE TITLE
iceworks服务经常断开连接

### ISSUE THREAD

**Issue by raohuiyong** [alibaba/ice#2883]
目前使用iceworks版本3.1.1

全局安装依赖项如下
+-- create-react-app@2.1.3
+-- eslint@6.5.1
+-- iceworks@3.1.3
+-- live-server@1.2.1
+-- npm@6.5.0
+-- nrm@1.0.2
+-- typings@2.1.1
+-- vue-cli@2.9.6
`-- yarn@1.12.3

**Comment by imsobear** [comment]
@raohuiyong 请多提供一些信息，日志、描述、截图
