### ISSUE TITLE
菜单配置，没有子菜单的时候，配置icon图表无效

### ISSUE THREAD

**Issue by 18660738669** [alibaba/ice#2884]
菜单配置，没有子菜单的时候，配置icon图表无效
![image](https://user-images.githubusercontent.com/20150911/67444843-4efaad80-f63d-11e9-9164-3b0d461b326d.png)
layouts/BasicLayout/Aside/index.jsx 第36行 缺少icon={item.icon ? item.icon : null}

**Comment by temper357** [comment]
该问题需要所有的模板都回归一下

**Comment by imsobear** [comment]
已发布新版本的 Fusion Design Pro，视觉上做了大量优化，可以尝试下：[预览地址](https://unpkg.com/@alifd/fusion-design-pro@0.1.22/build/index.html)

执行 `npm init ice ice-app` 即可
