### ISSUE TITLE
飞冰OSS发布上传是否可以区分开发或生产坏境

### ISSUE THREAD

**Issue by ChenJiaojiao123** [alibaba/ice#2885]
描述：
       在项目构建完成后，上传至阿里云OSS，是否可以或如何区分开发、生产坏境。

**Comment by alvinhui** [comment]
我们在 4.0 的产品设计上可以考虑一下让上传 OSS 可以自定义环境 cc @chenbin92

**Comment by luojinghui** [comment]
@alvinhui @chenbin92 4.0的版本大概会在什么时候出来呢？

现在的模式无法确认环境，一股脑的上传到oss一个目录上，其实真实的使用价值不大，还是需要依赖CI做自动化部署。
