### ISSUE TITLE
 "ice-scripts": "^1.6.0-next.3" npm install 报错

### ISSUE THREAD

**Issue by fengqitudd01** [alibaba/ice#2890]
(node:80) UnhandledPromiseRejectionWarning: Error: postcss-svgo: TypeError: Cannot set property 'multipassCount' of undefined
    at promises.push.getSvgo.optimize.then.catch.error (/srv/node_modules/postcss-svgo/dist/index.js:95:19)
(node:80) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 16)
(node:80) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ClarkXia** [comment]
检查下项目中是不是依赖到 svgo， https://github.com/svg/svgo/issues/1174

**Comment by imsobear** [comment]
应该就是这个问题，svgo 已经修复了，重新安装下依赖就可以
