### ISSUE TITLE
之前模板无法找到

### ISSUE THREAD

**Issue by TrumanDu** [alibaba/ice#2891]
## 问题描述
在官网无法找到之前大量的模板，请问这个是永久会去掉吗？
我有看到PRO,但是至少目前我觉得还做不到取代之前大量模板

**Comment by imsobear** [comment]
@TrumanDu 目前的模板维护成本太高导致部分模板代码质量不达标，因此我们暂时先下线掉了，接下来会通过自定义模板的能力支持模板丰富度。

**Comment by TrumanDu** [comment]
听到这个信息，很遗憾!
