### ISSUE TITLE
单个区块或者业务组件的 start 命令执行报错

### ISSUE THREAD

**Issue by zhaiqiang1987** [alibaba/ice#2892]
单个区块或者业务组件的 start 命令改为：../../node_modules/.bin/ice-scripts dev --config ../../ice.block.config.js

执行npm run start 报.'..' 不是内部或外部命令，也不是可运行的程序

**Comment by imsobear** [comment]
react-materials 吗？项目根目录下安装下依赖

**Comment by zhaiqiang1987** [comment]
> react-materials 吗？项目根目录下安装下依赖

根目录依赖都安装了的，react-materials-master跟区块目录下都安装过的。

是我这边node没法识别"../../"这种形式吧？要安装什么插件才能解析这个路径吗？

**Comment by imsobear** [comment]
@zhaiqiang1987 windows 吧，你在命令行直接执行 `../../node_modules/.bin/ice-scripts dev --config ../../ice.block.config.js` 试试呢，或者把路径换成 windows 的写法再试试

**Comment by zhaiqiang1987** [comment]
这样写就可以了..\\..\\node_modules\\.bin\\ice-scripts dev --config ..\\..\\ice.block.config.js
多谢指导~！
