### ISSUE TITLE
react-materials中的区块发布到私有库出现临时目录权限问题

### ISSUE THREAD

**Issue by zhaiqiang1987** [alibaba/ice#2893]
为了熟悉物料的发布，我在win10系统在blocks/..目录执行npm publish命令将区块发布到私有npm库，报temp目录文件unlink权限错误
npm ERR! path C:\Users\LENOVO1\AppData\Local\Temp\npm-18044-ecfa802a\tmp\fromDir-d149913f\package.tgz
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\Users\LENOVO1\AppData\Local\Temp\npm-18044-ecfa802a\tmp\fromDir-d149913f\package.tgz'
npm ERR!  { [Error: EPERM: operation not permitted, unlink 'C:\Users\LENOVO1\AppData\Local\Temp\npm-18044-ecfa802a\tmp\fromDir-d149913f\package.tgz']
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, unlink 'C:\Users\LENOVO1\AppData\Local\Temp\npm-18044-ecfa802a\tmp\fromDir-d149913f\package.tgz'

查阅过往issue发现iceworks创建页面也出现过类似的问题并在新版本解决了。
我这个是在cmd窗口执行的 该如何解决呢？

**Comment by imsobear** [comment]
谷歌下看看？看起来是 npm 的问题
