### ISSUE TITLE
目录结果什么意思

### ISSUE THREAD

**Issue by alex2wong** [alibaba/ice#2898]
## 问题描述
请问README 里面的这行：

>最佳实践：结合丰富的经验沉淀出的项目开发最佳实践，包括目录结果、开发调试、路由配置、状态管理等

`目录结果`是什么意思？是指的目录结构吗还是其他特定含义， 英文readme 里面也是 directory result，貌似是直译过来的。

**Comment by imsobear** [comment]
目录结构，笔误，我修正下，感谢反馈
