### ISSUE TITLE
ice-script 2.0升级的困扰

### ISSUE THREAD

**Issue by fengqitudd01** [alibaba/ice#2902]
之前的 .webpackrc.js 
 config.entry = {"block":"src/Block/index.js"};
  config.output = {
    library: 'LIBRARY_BLOCKS',
    path: path.resolve(__dirname, 'build/library'),
  };
升级到2.0一直找不到解决方案 实现相同功能

**Comment by ClarkXia** [comment]
entry 字段在 2.0 中会作为基础配置，进行类似配置就行 https://ice.work/docs/cli/config/config#entry
output 字段内容可以通过自定义webpack 配置的方式添加 https://ice.work/docs/cli/config/custom-webpack，比如：
```js
cont path = require('path');
module.exports = {
  chainWebpack: (config) => {
    // 修改 webpack output.path
    config.output.path(path.resolve(__dirname, 'build/library'));
  }
}
```
