### ISSUE TITLE
推荐的表单组件为什么总是变来变去？

### ISSUE THREAD

**Issue by Lisuhan** [alibaba/ice#2904]
你们飞冰组件文档上面 之前推荐使用 Form 和 FormBinder，当你们 @ice/form 出来以后又把 Formbinder 放在不推荐组件里。那好既然不推荐Formbinder 那我们就把用 Formbinder 的重构成 @ice/form吧 。今天再看文档 @ice/form 成了不推荐组件？Formbinder 成了推荐组件了，是不是耍人玩？

**Comment by imsobear** [comment]
@Lisuhan 表单这块的确是我们团队没有做好，先说声抱歉。然后同步一些信息：

- Form/Field 以及 FormBinder 的确都有一些小的缺陷（比如上手成本，布局能力），不过如果已经使用习惯了没必要再改
- 我们原本想通过 `@ice/form` 解决上述的一系列问题，后来在使用过程中发现一些底层的设计导致一些使用上的问题，比如 https://github.com/alibaba/ice/issues/2809，因为涉及到底层架构目前还不太好改，因此决定先不推荐开发者再使用，防止对业务产生历史包袱
- Form/Field 以及 FormBinder 很稳定，我们也会持续维护，如果 `@ice/form` 使用还不多建议迁移下，迁移遇到的问题我们可以帮助解决

再次表示歉意，如果有任何需要协助的地方欢迎在钉钉群反馈。

**Comment by chenbin92** [comment]
首先很抱歉，因为表单组件的变动带来的困扰，这里稍微解释一下。

目前 ICE 体系有多套表单组件的方案，分别是 Form 、Field、FormBinder、@ice/form 这四个，不同的表单方案最初要解决的问题也是不一样的。比如 Form 和 Filed 属于基础组件 @alifd/next，作为基础组件的表单方案。而 FormBinder 的背景则是考虑到 Form 和 Filed 的复杂和上手成本等问题，推出的一个类似双向数据绑定的表单数据管理方案，API 和使用也非常简单，但相比 Form 和 Filed 少了 UI 的封装，以及在大型表单场景的情况下可能出现的性能问题，比如 500 个 checkbox 下会卡顿之类的。基于此考虑，在原有的方案上继续探索，就有了后面的 @ice/form 方案来解决前面说的问题。

至于推荐的表单组件总是变来变去，这里主要是从使用率和维护的成本去考虑的，目前来看，使用最多的还是 Form 和 FormBinder。当然，如果项目里面有使用 @ice/form 遇到问题可以通过 issue 进行反馈，我们依旧会进行维护的，只是新的项目不推荐在使用。

最后，这确实是我们考虑不当的地方，再次表示歉意，也非常感谢反馈。
