### ISSUE TITLE
在线编辑器和对外授权访问

### ISSUE THREAD

**Issue by CrazyBoyM** [alibaba/ice#2908]
你好，我在手机上安装了iceworks。
但发现以下两点头疼的问题：
1.web面板没有提供在线编辑器，必须自己安装图形化界面和图形化文本编辑器。
2.只能通过127.0.0.1:8000访问web面板，而不能电脑通过192.168.2.150:8000访问。

场景：我电脑不方便装这个，所以在手机上用termux装了ubuntu系统，安装了nodejs，成功运行iceworks，测试发现web面板提供的功能都没有问题，新建项目时依赖安装，启动项目等等都可以用，速度也很快，运行流畅。但是我发现自己没法在线修改文件，因为iceworks的web面板没有像其他面板那样提供一个内置的在线文本编辑器，我必须再另外安装桌面和图形化文本编辑器，更重要的是，我目前还没找到arm版的vscode，atom，sublime text等等。所以目前我只有在命令行里通过vim慢慢修改文件……
希望iceworks尽快加入内置的轻量版本web在线文本编辑器，其次可以在设置中设置是否对外访问，以及密码鉴权，因为我做这个的目的是为了打造一个可移动化随身携带的环境，大屏设备通过内网访问我的手机进行一些工作，而无须每到一个地方就得重新装一次要用的东西。

**Comment by CrazyBoyM** [comment]
顺便我起初测试的是把iceworks装到服务器上，通过域名加端口访问，然后发现无法加载出内容……

**Comment by CrazyBoyM** [comment]
可以参考宝塔面板的在线文本编辑器

**Comment by alvinhui** [comment]
在手机上安装，大屏设备通过内网访问我的手机进行一些工作这个脑洞开得很大。。。

安装我的理解，就你的需求来说，部署 iceworks 3.0 到服务器上会比较合理一些。如果是无法加载出内容，可以看看浏览器控制台的报错，看看是不是网络访问问题。

你的两个问题：

1. web 版本的在线编辑器：我们在 4.0 版本中会做桌面集成软件，里面会有编辑器。我们会考虑在 4.0 中做 Web 版本，就 3.0 版本来说，我们不会做一个在线编辑器，因为我们没有这样的精力来开发和维护；
2. 不能电脑通过192.168.2.150:8000：如果是同一台电脑应该是 OK 的，如果是跨设备访问，需要看看当前局域网的网络环境配置。

**Comment by CrazyBoyM** [comment]
当前局域网的网络环境配置，这个怎么说？我目前内网设备之间是可以相互访问的。但当我在电脑上用Chrome浏览器访问手机时就无法打开，只加载出了网页的logo和title，内容为空白。（在服务器上部署问题同样，可以访问的通，但没有页面内容）

**Comment by CrazyBoyM** [comment]
还有如果下一个版本仍无法开发一个在线文本编辑器的话，可否在设置中开启某一相关选项，然后点击编辑后会自动下载该文件到本地，用户可在本地的文本编辑器进行编辑后在页面相应位置点击上传并自动覆盖。

**Comment by CrazyBoyM** [comment]
如果是我操作不当导致不能远程访问飞冰的话，这就说明飞冰是可以由另一台设备访问的？那么飞冰怎么确保面板和工程的安全，是不是应该加一个鉴权页面。

**Comment by alvinhui** [comment]
> 当前局域网的网络环境配置，这个怎么说？我目前内网设备之间是可以相互访问的。但当我在电脑上用Chrome浏览器访问手机时就无法打开，只加载出了网页的logo和title，内容为空白。（在服务器上部署问题同样，可以访问的通，但没有页面内容）

服务端部署，没有页面内容可以打开 Chrome 控制台来看看错误。我这边也试一下。

**Comment by alvinhui** [comment]
> 如果是我操作不当导致不能远程访问飞冰的话，这就说明飞冰是可以由另一台设备访问的？那么飞冰怎么确保面板和工程的安全，是不是应该加一个鉴权页面。

我的建议是，你的场景如果确实有这个需求，这类鉴权应该在网络层做，不在应用级别做。

**Comment by alvinhui** [comment]
> 还有如果下一个版本仍无法开发一个在线文本编辑器的话，可否在设置中开启某一相关选项，然后点击编辑后会自动下载该文件到本地，用户可在本地的文本编辑器进行编辑后在页面相应位置点击上传并自动覆盖。

3.0 如果是在电脑端我们是支持打开编辑器进行编辑的，手机端的话我们没有支持的计划。
