### ISSUE TITLE
如何在业务代码中区分环境

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#2916]
## 场景

- 业务代码里需要知道当前是什么环境
- 需要根据构建环境向前端代码注入一些变量

### 通过页面 url 动态区分

这是一个万能方案，域名特征以及需要哪些环境业务都可以自定义：
```js
// utils/env.js

let env = 'production';
const host = location.host;

if (/127.0.0.1/.test(host) || /localhost/.test(host)/) {
  env = 'local';
} else if (/daily.taobao.net/.test(host)) {
  env = 'daily';
} else if (/pre.taobao.com/.test(host)) {
  env = 'prepub';
}

export default env;

// src/pages/Home/index.js
import env from '@/utils/env';
console.log(env);
```

### 通过构建注入环境变量

正常情况下，我们可以为 `start` 和 `build` 两个命令指定不同的环境变量，比如在 `package.json` 中：

```json
{
  "scripts": {
    "start": "CMD_TYPE=start ice-scripts dev",
    "build": "CMD_TYPE=build ice-scripts build"
  } 
}
```

如果有专门的发布脚本，也可以在发布脚本中指定其他环境变量，默认情况下 ice-scripts 有一个环境变量是 `NODE_ENV`，这个环境变量无法被覆盖，start 命令对应的值是 `development`，build 对应的是 
`production`。完成环境变量的定义后接下来通过 webpack DefinePlugin 将变量注入到前端代码里：

```js
// ice.config.js
module.exports = {
  define: {
    // 根据当前环境变量注入一个动态值
    'process.env.CMD_TYPE': JSON.stringify(process.env.CMD_TYPE),
    // 注入一个静态值
    'process.env.XXX_API': JSON.stringify('http://taobao.com'),
  }
}
```

在前端代码中使用：

```js
// src/pages/Home/index.js

console.log(process.env.CMD_TYPE, process.env.XXX_API);
```

> 对于阿里内部的同学，如果 ice.config.js 里有 `ice-plugin-def` 这个插件，那会自动注入几个环境变量，直接在前端代码里使用即可：process.env.BUILD_GIT_GROUP, process.env.BUILD_GIT_PROJECT, process.env.CDN_VERSION, process.env.CDN_PATH, process.env.CDN_ENV

### 不同环境的请求 url 地址不一样

1. **优先推荐前端代码写相对地址，这样当前页面域名是什么，最终发请求的域名就是什么**
2. 如果 1 满足不了（比如接口域名跟页面域名不一致），那就按照上面的方式设置 env，然后在 `utils/request.js` 里加一段如下的逻辑：

```js
// utils/request.js
import env from './env';

// 改了这个属性之后，用 axios 发请求相对路径都会使用这个 baseURL
axios.defaults.baseURL = env === 'local' ? '//127.0.0.1:6001/' : '//taobao.com';
```

**Comment by yuanweisuannai** [comment]
通过构建注入环境变量 这种方式启动的时候会报错

**Comment by imsobear** [comment]
@yuanweisuannai 报什么错，日志或者截图看下
