### ISSUE TITLE
请问有有没有提供拖拽的组件？

### ISSUE THREAD

**Issue by zhouyao1994** [alibaba/ice#2921]
我在ice的官网上看了文档，似乎没有发现拖拽相关的组件 ，请问，ice 有没有组件拖拽相关的建议？或者相关的实践？ 我在GOOGLE 中搜索的有一些推荐 react-dnd 不知道 ice 有没有更好的建议？或者，ice 有没有拖拽拓建开发的排期，谢谢！

**Comment by imsobear** [comment]
推荐用 react dnd 哈
