### ISSUE TITLE
怎么官网模板类目 展示的模板少了很多？

### ISSUE THREAD

**Issue by wangjue666** [alibaba/ice#2922]
但是iceworks上创建项目展示的 模板是正常的

**Comment by imsobear** [comment]
目前的方案模板维护成本很高，导致很多模板质量偏低，存在一些 bug，因此经过权衡我们将一些使用率不高的模板下线掉了，未来会通过工具降低这块的成本，同时能够提高丰富度。

iceworks@2.0 是老版本，用的是老的数据源，因此数据还在。
