### ISSUE TITLE
ice store能否支持计算属性？

### ISSUE THREAD

**Issue by luojinghui** [alibaba/ice#2927]
# 需求描述
ice中默认使用icestore作为数据状态管理，但是在使用时，发现ice sotre的基本数据管理无法满足需求，在一些需要计算数据的地方，只能手动去做更新操作。比较繁琐。

通过Object的getter和setter测试了发现无法实现自响应。

希望支持对数据及其数据依赖发生变动时的计算属性能力。

**Comment by temper357** [comment]
> 通过Object的getter和setter测试了发现无法实现自响应。

这个没太明白是什么场景，贴段实际的代码示例看下

**Comment by temper357** [comment]
如果你指的是 mobx 的 @computed 的能力，那么 icestore 暂时没有计划支持这种响应式能力，icestore 的定位与 Redux 更接近，希望所有的状态变化都是由用户控制的，以达到状态变化的链路可追踪

**Comment by luojinghui** [comment]
其实就是类似mobx/vue的computed能力。其实可以通过状态自行控制解决，也没有问题，但是可能在某些情况下，自定义控制处理数据稍微麻烦一点。如果有计算能力，那么能够统一管理对数据的转换，会更方便一点。
