### ISSUE TITLE
飞冰 iceworks环境搭建配置完成之后，在无网络的情况下无法启动工作台

### ISSUE THREAD

**Issue by guananny2** [alibaba/ice#2929]
问题：
根据飞冰官网搭建完iceworks之后，在无网络情况下，在终端启动 iceworks ,终端报错无法运行工作台。公司目前的需求是 能用飞冰开发企业定制化私有的模板、物料、模块。并期望可以不依赖网络环境去开发。

期望:
在无网络环境下，可以使用飞冰管理项目，可发布私有模板、物料、模块。

**Comment by imsobear** [comment]
![image](https://user-images.githubusercontent.com/2505411/69776540-a6a9ad00-11d7-11ea-9b56-ef61adebf14d.png)
