### ISSUE TITLE
飞冰（ICE）企业级用户群

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#2935]
## 背景说明
感谢大家选择并使用飞冰（ICE）相关的技术产品，在接下来我们将深入线下和大家进行沟通交流，以及提供宣讲培训服务，帮助大家搭建企业级的中后台解决方案。

同时为了提供更好的使用体验和及时解大家在使用过程中遇到的相关问题，飞冰团队建立了一个企业级用户群，欢迎大家加入👏👏👏

## 入群福利

- 提供专职人员为群成员提供快速答疑服务(节假日除外)
- 加强沟通建立更加快速的反馈渠道
- 优先使用飞冰相关技术产品的内测版
- 成为飞冰企业级用户，提供线下培训服务

## 入群条件

- 使用飞冰（ICE）开发过实际的项目
- 使用飞冰团队成员在 10 人左右可申请线下培训和分享交流

## 入群方式

请使用钉钉扫描以下二维码添加群主为好友，并备注 「公司名称 - 职位 - 姓名 」的格式

![image](https://user-images.githubusercontent.com/3995814/69299799-73ea3c80-0c4c-11ea-8254-ec1ec0df3aaf.png)

**Comment by a97077088** [comment]
添加不了啊

**Comment by imsobear** [comment]
> 添加不了啊

不再提供该服务，有需求建议直接加用户群，官网有钉钉二维码。

**Comment by a97077088** [comment]
加了半个月没加进去，大哥批准下啊，外卖小张

**Comment by a97077088** [comment]
umijs转icejs后体验很好，就是碰到问题无解，bug无解啊

**Comment by imsobear** [comment]
![image](https://user-images.githubusercontent.com/2505411/158097485-160cfba9-4c1f-4b37-9e4c-fe75e5bec481.png)

@a97077088 没看到申请，你试下上面的二维码呢？

**Comment by imsobear** [comment]
或者先加下我个人的钉钉号：imsobear

**Comment by a97077088** [comment]
收到，谢谢老板，已加入
