### ISSUE TITLE
业务组件使用 ts 开发生成 d.ts 文件

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#2942]
现在没有生成这个文件

**Comment by imsobear** [comment]
![image](https://user-images.githubusercontent.com/2505411/69776738-5717b100-11d8-11ea-9ed2-62bd21c3ae3f.png)

**Comment by imsobear** [comment]
ice-scripts 和 build-scripts 都有这个问题

**Comment by ClarkXia** [comment]
ice-plugin-component0.1.10 已支持
