### ISSUE TITLE
iceworks项目运行中点关闭

### ISSUE THREAD

**Issue by chenhongen** [alibaba/ice#295]
此时，弹出提示框，然后关闭提示框居然iceworks直接关了。。
（本意关闭提示框，然后手动去停止项目的）
![11](https://user-images.githubusercontent.com/16499303/37471946-dab9ece4-28a5-11e8-8159-37f1b49de305.png)

**Comment by noyobo** [comment]
关闭提示框可以点击  右上角的关闭按钮，或者取消。

**Comment by chenhongen** [comment]
我的意思是，点击 右上角的关闭按钮。iceworks就退出了。而此时 应该是要 只关闭提示框才对。

**Comment by noyobo** [comment]
不好意思，我理解错了。这个问题我查下

**Comment by noyobo** [comment]
待 1.3.0 发布
