### ISSUE TITLE
[icestore]未来有计划实现类似 hox 中 withModel 这样的功能吗？

### ISSUE THREAD

**Issue by niqingyang** [alibaba/ice#2953]
## 需求描述

项目中确实还存在不少遗留的类组件（虽然也能转换为函数组件，但是有些组件是第三方获取的，转换函数组件后不便于后期升级），如果 icestore 能提供类似 hox 中 withModel 这种在将 hooks 状态注入到类组件中那就太好了，能省去不少的工作。所以想了解一下未来有没有类似的计划

**Comment by imsobear** [comment]
https://github.com/ice-lab/icestore/pull/39

**Comment by imsobear** [comment]
https://github.com/ice-lab/icestore#class-component-support 已支持 v0.4.1
