### ISSUE TITLE
ICE Pro模板展开收起bug

### ISSUE THREAD

**Issue by Nilets** [alibaba/ice#2954]
## 错误信息

ICE Pro模板点击收起，然后再点击展开时，二级目录左边的的空格消失，需要点击一下菜单栏才能恢复正常
![image](https://user-images.githubusercontent.com/20531176/70144860-cbbb8580-16d9-11ea-901a-00ca6bf501be.png)
![image](https://user-images.githubusercontent.com/20531176/70144895-d9710b00-16d9-11ea-97f0-e657175054f7.png)

**Comment by imsobear** [comment]
已发布新版本的 Fusion Design Pro，视觉上做了大量优化，可以尝试下：https://unpkg.com/@alifd/fusion-design-pro@0.1.22/build/index.html

执行 `npm init ice ice-app` 即可
