### ISSUE TITLE
Iceworks 布局添加预览功能

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#297]
用户现在在选择的时候还是会模糊，建议布局提示框里加个预览，跳到站点上看实际的效果图

![](https://static.dingtalk.com/media/lALPBY0V4xAJzz3NAfjNAxg_792_504.png_620x10000q90g.jpg)

**Comment by noyobo** [comment]
@chenbin92  布局的预览地址放在与 缩略图 的同级字段上

**Comment by noyobo** [comment]
https://g.alicdn.com/ice-assets/ice-design/databases/layouts.db.json 目前没有预览地址的字段
