### ISSUE TITLE
[ice-scripts]支持只编译输出 lib 目录的命令

### ISSUE THREAD

**Issue by Leslie2014** [alibaba/ice#2976]
有两个场景会用到这个功能：

1.业务组件很多的时候，如果需要做大包方案，每个子组件都构建生成 build 目录，会很慢。
2.当 link 开发调试的时候，每次都要 rebuild，会挺久的，不方便。

所以希望能有个命令，只做轻量级的 compile to lib.

**Comment by ClarkXia** [comment]
ice-scripts@2.1.15 支持 `ice-scripts build --skip-compile` 跳过 build 构建
