### ISSUE TITLE
使用命令iceworks add 添加区块的时候，期望能安装区块依赖

### ISSUE THREAD

**Issue by enboga** [alibaba/ice#2979]
## 问题描述

使用命令`iceworks add` 添加区块的时候，期望下载区块代码的时候，同时安装相应依赖。一般区块开发的时候是会在package.json中定义依赖的，期望能自动安装这些依赖。不然自己还要手动去安装，手动安装步骤会比较繁琐。

**Comment by imsobear** [comment]
仓库迁移：https://github.com/ice-lab/iceworks/issues/8
