### ISSUE TITLE
block 的demo展示期望能够配置成组件的demo展示模式

### ISSUE THREAD

**Issue by Leannechn** [alibaba/ice#2984]
主要解决的问题：业务多变的跨项目 跨团队情况下的业务组件复用。
1. 业务组件看起来很像，又不一样。
2. 组件拓展性越强 越需要专人维护，时间一长根本找不到人，不如拉下来自己维护。
3. 能力增加或者修改沟通成本高。
4. 业务特性修改，不能确定影响面。

所以选择了block，以block的模式开发了基础能力，项目开发通过add到项目中，如果有业务特性的能力用户自行增加和维护。但对于block（即业务组件）的基础能力希望可以有像组件那样的demo展示效果。

附加（以下这个诉求暂时只是YY，上诉能力真实需要）
block基础功能满足业务诉求的时候，也能npm包使用。既然都发npm包了，能不能编译一下使用。

酌情考虑是否增加以上能力

**Comment by imsobear** [comment]
@ClarkXia 评估下，合理的话可以迁移到 build-scripts 的 issue 里。
