### ISSUE TITLE
浏览器中ice安装依赖，源与npm registry不一致

### ISSUE THREAD

**Issue by Call-Me-Uncle** [alibaba/ice#2986]
npm config get registry 
![image](https://user-images.githubusercontent.com/8119899/71391668-22b0dc80-2640-11ea-9a19-3b37deb55b10.png)

ice安装依赖时取到的源配置
![image](https://user-images.githubusercontent.com/8119899/71391703-42480500-2640-11ea-8e34-5462b3765ed8.png)

**Comment by imsobear** [comment]
这里的 registry 取的是 「设置->包管理工具」的值

**Comment by Call-Me-Uncle** [comment]
谢谢，已解决
