### ISSUE TITLE
iceworks 在非空目录执行init会抛异常，建议友好提示或者默认按照项目名称生成新目录

### ISSUE THREAD

**Issue by hipoyang** [alibaba/ice#2989]
![image](https://user-images.githubusercontent.com/3152059/71505868-c822b500-28b9-11ea-8e48-508381c2cd0a.png)

习惯上，直观感受是执行创建项目会以输入项目名称，生成目录。建议这种出错能够错误提示，不要抛异常。因为新用户并不清楚这个工具的约定

**Comment by imsobear** [comment]
仓库迁移：https://github.com/ice-lab/iceworks/issues/7
