### ISSUE TITLE
组件的icon失效

### ISSUE THREAD

**Issue by ityao** [alibaba/ice#2992]
https://ice.work/component/icon

里面的一堆icon都显示不出来, eye, lock那些, 都在组件里面有用的, 弄得组件的UI也渲染不正确

**Comment by imsobear** [comment]
这个应该是站点里组件版本太低导致的，你在项目里使用应该没问题吧？

**Comment by ityao** [comment]
我的项目就是有问题才去查, 发现官网文档也是有问题

**Comment by imsobear** [comment]
看下你项目里用的 `@alifd/next` 是什么版本

**Comment by ityao** [comment]
^1.19.5

**Comment by imsobear** [comment]
@ityao 能不能给个重现的项目放 GitHub 上，我们排查下

**Comment by imsobear** [comment]
+ @icedesign/theme@1.2.0 @ityao 升级下这个包的版本
