### ISSUE TITLE
缩小了浏览器会自动弹出所有菜单

### ISSUE THREAD

**Issue by wssgcg1213** [alibaba/ice#300]
![image](https://user-images.githubusercontent.com/3922719/37515225-165196cc-2945-11e8-8d88-3ac5e69241e9.png)

![image](https://user-images.githubusercontent.com/3922719/37515252-275ff7ce-2945-11e8-8e60-d6d369e57e20.png)

![image](https://user-images.githubusercontent.com/3922719/37515247-245a1c12-2945-11e8-877b-ef5d00f315a3.png)

**Comment by chenbin92** [comment]
这个是这样设计的，菜单在没有折叠的时候二级菜单如果是打开的，那么在折叠之后也是会打开的，如果不需要这种UI交互，可以判断在折叠之后隐藏即可
