### ISSUE TITLE
iceworks IDE 发布：极速构建企业级中后台前端应用

### ISSUE THREAD

**Issue by alvinhui** [alibaba/ice#3005]
如果您是在企业环境中构建中后台应用，那么您应该已经遇到了要开发的应用数量与团队交付能力之间日渐扩大的鸿沟。一些团队有多达 20~30 个应用需要开发。

ICE 已经提供了组件、物料、构建工具和常用的前端方案帮助您更好地构建中后台应用。但是，这里面依然有不低的学习成本和使用成本。

不管您有多熟练，您仍然会觉得花了一半的时间在代码编辑器和开发人员文档之间来回切换：我应该使用哪个组件？正确的语法是什么？为什么这个样式没有生效？等等……更不用说管理工程环境或者弄清楚如何与新的后端服务集成之类的事情了。

iceworks 就是在这样的背景下产生的，面向企业级中后台领域的 IDE（Integrated Development Environment，集成开发环境），目标是让构建企业级中后台应用更轻松更快速。

![iceworks](https://img.alicdn.com/tfs/TB1lMLdtXY7gK0jSZKzXXaikpXa-2763-1449.png)

### 从创建到发布的完整项目开发流程

iceworks 内置了 ICE 官方模板帮助您快速创建一个中后台应用，并提供了 SCM 的支持（强大的 Git 集成）以加速发布操作。iceworks 还支持对接应用发布平台，在阿里内部，我们集成了对 DEF 发布的支持。

### 使用物料进行应用开发

iceworks 内置了 ICE 官方物料，在 IDE 中已经包含了物料的查找、预览、文档和示例。您在物料面板中滚动列表即可轻松浏览，然后通过点击组件就可以将物料添加到您的应用，iceworks 会自动生成您需要的代码。在未来，我们还会支持在右侧活动栏中进行物料的属性设置。

如果这些物料还不能满足您的诉求，您可以在欢迎界面中通过物料设置添加自定义物料，又或者通过可视化搭建的方式搭建您的本地物料。

### 通过可视化搭建加速界面开发

iceworks 中提供了基于可视化搭建生成本地区块的能力。大部分开发者并不擅长布局和样式的编写，而且这部分的工作量十分繁重。通过可视化搭建的方式，您可以很快地完成界面部分的开发工作，生成区块。然后再通过物料面板再将已生成的区块添加到页面中，您可以反复搭建您的区块以适应不同的场景。

您还可以使用创建页面的功能，通过区块快速地组合出新的页面。经过验证，这对于有大量页面需要开发的场景来说非常有用。

## 发行策略

iceworks IDE 从 iceworks GUI 工具演进而来，版本代号 4.x 。自 4.x 版本发布后，我们将参考 [Node.js Release](https://nodejs.org/en/about/releases/)，规范发行策略：

| 版本  | 状态       | 发布时间    | 活跃 LTS 开始 | 维护 LTS 开始 | 终止维护时间  |
| :--: | :---:      | :---:      | :---:       | :---:     | :---:       |
| 2.x | **维护 LTS** | 2018-05-04 | 2019-06-01 | 2019-10-01 | 2020-01-31  |
| 3.x | **活跃 LTS** | 2019-07-08 | 2019-10-01 | 2020-01-01 | 2020-04-31  |
| 4.x | **当前版本**  | 2020-01-01 | 2020-04-31 | 2020-10-31 |             |

### 你们会不会支持 Linux 平台？

短期内不会。这是一个比较小众的需求，我们暂时没有精力进行支持。

### iceworks 未来会不会支持网页版本？

对外部不会，在内部我们将通过 DEF 平台支持 WebIDE。

### 会不会提供插件开发，插件市场等功能？

针对于企业定制研发流程，将以类似 [Extension Packs](https://code.visualstudio.com/blogs/2017/03/07/extension-pack-roundup) 的方式进行支持。

### 你们会不会把一些功能做成 VS Code 插件？

不会。我们对于研发流程、工程环境的定制、集成程度未来会越来越高。但我们将会保障与 VS Code 一致的代码编辑体验及部分插件的兼容。

### iceworks 未来会不会内置开发环境？

会。我们期望开发者只需要下载一个 IDE，在 IDE 中完成整个开发链路的流转。

### 你们的更新策略是怎样的？

每个月初会制定一次迭代计划，在月末进行更新，iceworks 将会自动升级，不需要开发者进行额外的操作。

### 代码什么时候开源？
   
预计是在 2020 年中旬。

### 如何反馈问题或意见？

请提交 [issue](https://github.com/alibaba/ice/issues/new?labels=iceworks%204.0) 或扫描[二维码](https://ice.alicdn.com/assets/images/qrcode.png)加入飞冰社区钉钉群。

## 最后

iceworks 从 4.0 开始刚刚走上 IDE 的这条路，总体来说还很稚嫩。一方面我们将完善周边，持续定义企业级中后台产品的研发模式，打造面向企业级中后台产品的一体化开发工具；另一方面，我们也在寻找企业级中后台产品研发提效的「银弹」，真正做到「提效十倍」。

请保持关注，更多内容请移步 [iceworks 站点文档](https://ice.work/docs/iceworks/about)。

**Comment by Pines-Cheng** [comment]
2020 年中旬过了哦，貌似还没开源？
