### ISSUE TITLE
目前我们的代码中有用到less，想讲代码移到飞冰框架中，如何添加less-loader到webpack配置中？

### ISSUE THREAD

**Issue by wangyuks** [alibaba/ice#3009]

**Comment by imsobear** [comment]
less 默认支持的

**Comment by wangyuks** [comment]
> less 默认支持的

不需要改什么吗？我把原来代码放进来，直接报错了
![image](https://user-images.githubusercontent.com/26295888/71959094-d8794f00-322c-11ea-8eb9-cb56c44a7bf5.png)

**Comment by imsobear** [comment]
确定下是不是文件路径不对。。

**Comment by wangyuks** [comment]
> 确定下是不是文件路径不对。。
antd组件库主题如何配置呢？

**Comment by wangyuks** [comment]
> 确定下是不是文件路径不对。。

确实是路径不对
