### ISSUE TITLE
less文件无法开启热更新

### ISSUE THREAD

**Issue by Lcj-space** [alibaba/ice#3013]
在setWebpackLoaders.js 文件中发现只需要把文件改成这样就能实现

![image](https://user-images.githubusercontent.com/22415092/72124345-5cebdf00-339f-11ea-8455-b91e84fba60f.png)
之前的代码是这样的如下图
![image](https://user-images.githubusercontent.com/22415092/72124449-c370fd00-339f-11ea-9c2c-cf3a30f6e39d.png)

请问下这样的话如何解决

**Comment by ClarkXia** [comment]
css-hot-loader 热更新能力可以被 MiniCssExtractPlugin 的 hmr 属性替代，有兴趣可以 PR

**Comment by Lcj-space** [comment]
用法如下 less当成一个对象引入
![image](https://user-images.githubusercontent.com/22415092/72125810-f7025600-33a4-11ea-8087-e4b5cce09180.png)
![image](https://user-images.githubusercontent.com/22415092/72125841-06819f00-33a5-11ea-8a72-3372f78f2f9e.png)
![image](https://user-images.githubusercontent.com/22415092/72125861-17321500-33a5-11ea-81a7-440560904704.png)

**Comment by Lcj-space** [comment]
查看浏览器的时候发现那个css文件不是跟新后的，但是手动F5一下有好用了，后来跟换到我先前的那种方式就不会出现这样的问题
