### ISSUE TITLE
点击启动报 node-sass 无法运行

### ISSUE THREAD

**Issue by alvinhui** [alibaba/ice#3015]
## 问题描述

点击导航栏上的启动按钮，终端上报错：

![image](https://user-images.githubusercontent.com/4392234/72129733-4bf89900-33b2-11ea-9347-2357f01fcd8b.png)

![image](https://user-images.githubusercontent.com/4392234/72129411-13a48b00-33b1-11ea-93c4-c752d5d5cc94.png)

**Comment by alvinhui** [comment]
## 问题分析

终端上使用的 node 与安装 node-sass 时的 node 不是同一个示例。

## 临时解决

**在 iceworks 终端上执行**（）：

```bash
$ rm -rf node_modules/
$ npm install
```

**Comment by imsobear** [comment]
不是一个 node 不太符合预期，这个问题应该需要解决吧

**Comment by QZscott** [comment]
我的同事遇到同一个问题
