### ISSUE TITLE
是否可以考虑通过 vuera 实现对 vue 使用 ICE的支持？

### ISSUE THREAD

**Issue by dingyiming** [alibaba/ice#302]
目前使用 [vuera ](https://github.com/akxcv/vuera)是可以直接在 vue 的构建中，使用 react 组件，并实现 props 的组件通信的，是否可以在 ICE 模板中添加基于 vue-cli 的脚本模板支持，就可以支持起ICE的工作流了,比如下载区块？

**Comment by wssgcg1213** [comment]
感谢建议, 我们会考虑一下这个方案. 

 iceworks 工具我们不希望跟某一种特定的渲染层(React vue or ect..)耦合, 所以对 vue 的支持不是适配而是提供基础能力(编译)和物料池开放建设的思路

粗略看了一下 vuera 的 api, 可以确认的是我们首先会默认启用 vueloader 支持 .vue 文件的构建

**Comment by dingyiming** [comment]
好的，挺棒的，我目前已经基于 vue-cli 模板把 ice 四套模板引入实现了使用，也尝试了antd 等，初步使用生产过程没有问题，

**Comment by yujiangshui** [comment]
这种问题其实我们有讨论过。对于一个偏向 vue 或者偏向 React 的开发者来说，一个项目里遇到两种 DSL 的写法可能是一种比较恐怖的问题。虽然可以通过 loader 复用，但是我们更倾向于一致的 DSL 这样用户体验会更好一点。

**Comment by waynehu2014** [comment]
大佬，我最近也想通过vuera在react中使用vue，但是配置文件不知为何，修改后一直报错，能否帮我看看指点一下我～
