### ISSUE TITLE
更新页面时不能删除物料块

### ISSUE THREAD

**Issue by JackeBluthH** [alibaba/ice#3024]
## 问题描述
创建一个项目后进入页面更新模态框，添加一些物料。新添加的物料上有一个删除图标，点击后不能删除。修改名称有同样的问题

**浏览器信息**：Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36

## 错误信息
删除和修改都不成功

## 问题定位
SelectedBlock组件使用了index属性，该属性可能与SortableElement有冲突，不能正确传递到回调函数中，导致点击删除图标时使用的index值为undefined
涉及文件：packages\iceworks-client\src\pages\Project\components\PagePanel\BuildPageModal.js

**Comment by imsobear** [comment]
@JackeBluthH 是 iceworks@3.0 吗？
