### ISSUE TITLE
icestark子应用调试问题

### ISSUE THREAD

**Issue by blitheinsz** [alibaba/ice#3025]
关于微前端子应用调试，我看文档是这样写的：

**单独子应用开发时只能看到自身的内容，无法关注到在框架应用下的表现，这时候本地如果需要再启动一个框架应用，开发起来就很繁琐。针对这种情况，我们推荐通过框架应用的日常/线上环境调试本地子应用。在框架应用中注册子应用时，如果 url 里携带了类似 ?env=local 的 query，则将子应用的 url 转换为对应的本地服务地址，这样就可以方便调试子应用了**

1、框架应用的线上环境访问子应用本地服务调试，是不是指框架应用必须部署到**本地局域网**的线上环境？
2、如果公司的测试环境是部署在外网的，是不是就没法采用这种方式调试了？必须在本地启动框架应用？

**Comment by daysai** [comment]
> 关于微前端子应用调试，我看文档是这样写的：
> 
> **单独子应用开发时只能看到自身的内容，无法关注到在框架应用下的表现，这时候本地如果需要再启动一个框架应用，开发起来就很繁琐。针对这种情况，我们推荐通过框架应用的日常/线上环境调试本地子应用。在框架应用中注册子应用时，如果 url 里携带了类似 ?env=local 的 query，则将子应用的 url 转换为对应的本地服务地址，这样就可以方便调试子应用了**
> 
> 1、框架应用的线上环境访问子应用本地服务调试，是不是指框架应用必须部署到**本地局域网**的线上环境？
> 2、如果公司的测试环境是部署在外网的，是不是就没法采用这种方式调试了？必须在本地启动框架应用？

icestark 的相关问题可以直接在icestark 仓库下进行: [issue](https://github.com/ice-lab/icestark/issues)
1. 不需要部署到**本地局域网**环境，因为 icestark 通过 url 拉取资源的方式是原生 script/link 标签形式，天然支持跨域。 
2. 建议 urlQuery.env 的配置只在测试环境下生效，但不对测试环境的网络状况有要求。只要本地浏览器端能访问就可以。

**Comment by blitheinsz** [comment]
多谢解答
