### ISSUE TITLE
在 Windows 下终端功能不可用

### ISSUE THREAD

**Issue by alvinhui** [alibaba/ice#3028]
## 问题描述

打开工作台，点击终端，显示功能不可用：

![image](https://user-images.githubusercontent.com/4392234/72587332-da7b9600-392f-11ea-9b6e-42a5d77127fb.png)

**Comment by ElliottNing** [comment]
same issue

**Comment by QZscott** [comment]
same issue

**Comment by bioinformatist** [comment]
@alvinhui 有合适的解决办法吗，我在两台电脑上都是这样的问题...
