### ISSUE TITLE
升级到1.1.1结果项目运行出错了

### ISSUE THREAD

**Issue by yiyi99** [alibaba/ice#303]
Failed to compile
./src/layouts/HeaderAsideFooterLayout/Layout.jsx
Module not found: Can't resolve 'enquire-js' in 'E:\test1\src\layouts\HeaderAsideFooterLayout'
This error occurred during the build time and cannot be dismissed.

**Comment by wssgcg1213** [comment]
有区块使用了 `enquire-js` 模块, 可以在这里安装此模块  
![image](https://user-images.githubusercontent.com/3922719/37565608-2d65a3a0-2ae7-11e8-84d7-dbbd87235435.png)  

我们确认一下区块下载时对应模块未安装成功的问题

**Comment by noyobo** [comment]
closed by iceworks v2.0
