### ISSUE TITLE
[Feature] ice-scripts 不支持加载.env配置

### ISSUE THREAD

**Issue by fengxinming** [alibaba/ice#3032]
期望支持加载 `.env` 配置到 `process.env` 中

**Comment by imsobear** [comment]
建议升级到 icejs，通过 --mode 支持：https://ice.work/docs/guide/basic/build#%E6%A0%B9%E6%8D%AE%E7%8E%AF%E5%A2%83%E5%8C%BA%E5%88%86%E5%B7%A5%E7%A8%8B%E9%85%8D%E7%BD%AE

.env 的方式太重了，目前不计划支持。
