### ISSUE TITLE
icestore 优化点汇总

### ISSUE THREAD

**Issue by alvinhui** [alibaba/ice#3037]
## 来自社区

由 @Lucifier129 指出，感谢。

### 能力

1. SSR：在一个独立模块里直接初始化的单例 Store，如何处理 Per Request 的 SSR 场景？第一次 SSR 和第二次 SSR 公用同一个 Store 里的数据，会带来数据污染问题。如果要支持 SSR，则需要有 **Provider**，从 `props` 和 `context` 里获取，目前 icestore 直接从另一个模块里 `import store` 的简便用法就不成立了。如果要成立，则不能在模块里直接 `new store` 实例，需要像 create-react-store 一样，Store 只是 API 对象，而不是 Instance，Store 内部没有可变状态和监听器。
2. ~~向前兼容~~：外部 Store 在 **Concurrent-Mode** 下，会因为 Suspense/异步，产生数据不一致，两次 `store.getState()` 的间隙中，可能存在 dispatch，而已 getState 的没机会得到通知（suspend 状态下 render 没执行完，useEffect 更没机会执行）
3. 缺乏数据变更追踪的精确性：当前触发更新的方式，是对函数做一层 wrapper，不管 action 是否更新了状态，都执行 setState，如果一个 action 是根据条件去决定是否更新状态，没命中的情况下，也可能引起冗余渲染。要更精确的追踪变化，可以通过像 immer/vue/bistate 这种基于 defineProperty/Proxy 的途径。

    ![数据变更追踪的精确性](https://img.alicdn.com/tfs/TB1bfDBu.T1gK0jSZFrXXcNCXXa-563-719.png)

### 缺陷

1. ~~数据不一致~~：useStore 里是在 useEffect 时才监听了 setState/state-change，而 useEffect 是有父子组件的执行顺序的。这意味着，如果子组件也用了同一个 `store.useStore`，它在 useEffect 时立即触发了更新，父组件的 useEffect 还未执行，它无法被通知到。此时子组件的 useStore 拿到了最新的 state，而父组件里拿到的是旧的。

    ![数据不一致](https://img.alicdn.com/tfs/TB1tQbBuYr1gK0jSZFDXXb9yVXa-410-327.png)
2.  **mutable** 的问题：Store 定义时没有用 **immer** 之类的库，但又直接 mutate 了对象，只在一个组件里 useStore 消费和响应数据变化时，问题不会暴露，将数据作为 props 传递时，就会产生问题。数据变化了，但还是同一个引用，React 会认为数据没有变化。

    ![mutable](https://img.alicdn.com/tfs/TB1x4HzuVY7gK0jSZKzXXaikpXa-425-353.png)

### 性能

useStore 实现的一些问题：

- 性能优化点：每次 useStore 都会调用 getState ，getState 都会对 bindings 去执行一次循环。useStore 时应该用 `useState(() => this.getState())` 的 **lazy 模式**；
  
  ![](https://img.alicdn.com/tfs/TB1JWzBu4z1gK0jSZSgXXavwpXa-478-798.png)
  ![](https://img.alicdn.com/tfs/TB1DbzAu.z1gK0jSZLeXXb9kVXa-453-379.png)
- 隐患：当在一个组件里多次使用 useStore 时，它会把同一个 setState push 到 queue 里，状态变化时，则会触发超过 1 次，产生冗余更新，一般场景下，没有开发者会直接 useStore 两次，但在封装可复用的 custom hooks 时，则很可能使用多次。应该做一个 protect；
- 返回值每次都浅拷贝一下，意味着把 state 当作子组件的 props.state 时，子组件无法通过 PureComponent 和 React.lazy 得到优化，`useMemo(() => {}, [state])` 也无法得到缓存。

  ![](https://img.alicdn.com/tfs/TB1VYvCu.T1gK0jSZFhXXaAtVXa-455-333.png)

## 来自业务

1. 基于 hooks 的状态管理方案的成熟度；
2. 中大型的前端仓库，代码量比较大，面临的迁移成本；
3. icestore API 的稳定性；
4. 优化点：资源过多需要懒加载，组件动态加载的同时如何让 store 也做动态注册（参考 [Dva](https://dvajs.com/guide/develop-complex-spa.html#%E5%8A%A8%E6%80%81%E5%8A%A0%E8%BD%BDmodel)）。

**Comment by alvinhui** [comment]
另有开发者（方舟方舟）反映：

1. 基于 hooks 的状态管理方案的成熟度；
2. 中大型的前端仓库，代码量比较大，面临的迁移成本；
3. icestore API 的稳定性；
4. 优化点：资源过多需要懒加载，组件动态加载的同时如何让 store 也做动态注册。

**Comment by alvinhui** [comment]
## 新的 API 设计

_Work In Process_

Use a model to define your store:

```tsx
import { dispatch } from '@ice/store';

const productsModel = {
  items: {
    1: { id: 1, name: 'Peas', price: 10 }
  },
  updateItem: async (state, payload) => {
    const updated = await productService.update(payload.id, payload);
    state.items[payload.id] = payload;
  },
  setItems: (state, payload) => {
    state.items[payload.id] = payload;

    // Call other model
    dispatch.basket.setProducts(state.items.map(({ id } => id)));
  },
};

const basketModel = {
  productIds: [1],
  setProducts: (state, payload) => {
    state.productIds = payload;
  },
};

const storeModel = {
  products: productsModel,
  basket: basketModel
};
```

Create the store

```tsx
import { createStore } from '@ice/store';

const store = createStore(storeModel);
```

Wrap your application

```tsx
import { StoreProvider } from '@ice/store';

ReactDOM.render(
  <StoreProvider store={store}>
    <App />
  </StoreProvider>,
  rootElement
);
```

 Consume model

```tsx
import { useStore } from '@ice/store';

function ProductsInBasket() {
  const { items, updateItem } = useStore('products');
  return (
    <div>
      <h2>count: {Object.keys(items).length}</h2>
      <button onClick={() => updateItem(updatedValues)}>
        Submit
      </button>
    </div>
  ) 
}
```

**Comment by chenbin92** [comment]
@alvinhui 

![image](https://user-images.githubusercontent.com/3995814/73996136-c27abd80-4995-11ea-892d-9db256c2c8c0.png)

**Comment by alvinhui** [comment]
> @alvinhui
> 
> ![image](https://user-images.githubusercontent.com/3995814/73996136-c27abd80-4995-11ea-892d-9db256c2c8c0.png)

1. state 总是默认第一个参数，这个出发点是和 setState 的 API 保持一致；
2. payload 是参数；
3. 想法是 state 是不可变的，所以可以返回全新的 state 也可以直接修改（draft）；
4. 示例有点问题，最后一行应该是 `state.items[payload.id] = updated`；

**Comment by alvinhui** [comment]
## 来自社区

### 能力

1. [ ] SSR：WIP
2. [x] ~~向前兼容~~：当前实现无法支持；
3. [x] 缺乏数据变更追踪的精确性：
4. [ ] 懒加载模型：

### 缺陷

1. [x] ~~数据不一致~~：在 Concurrent-Mode 模式下可能会遇到这个问题；
2. [ ]  **mutable** 的问题：

### 性能

useStore 实现的一些问题：

- [x] 性能优化点：每次 useStore 都会调用 getState ，getState 都会对 bindings 去执行一次循环。useStore 时应该用 `useState(() => this.getState())` 的 **lazy 模式**；
- [ ] 隐患：当在一个组件里多次使用 useStore 时，它会把同一个 setState push 到 queue 里，状态变化时，则会触发超过 1 次，产生冗余更新，一般场景下，没有开发者会直接 useStore 两次，但在封装可复用的 custom hooks 时，则很可能使用多次。应该做一个 protect；
- [x] 返回值每次都浅拷贝一下，意味着把 state 当作子组件的 props.state 时，子组件无法通过 PureComponent 和 React.lazy 得到优化，`useMemo(() => {}, [state])` 也无法得到缓存。

**Comment by alvinhui** [comment]
将直接发布 1.0 版本：https://github.com/ice-lab/icestore/pull/57

**Comment by alvinhui** [comment]
可以参考指南从 0.x 升级到 1.x ：https://github.com/ice-lab/icestore/blob/master/docs/upgrade-guidelines.md#0xx-to-1xx
