### ISSUE TITLE
Feature request: 请求IDE支持远程项目

### ISSUE THREAD

**Issue by bioinformatist** [alibaba/ice#3038]
## 问题描述

emmm，我是一个bioinformatics开发人员，因为组学数据计算需要高性能软件在Linux下运行，所以好多protocol等等只能部署在服务器上，本地是Windows下开发的话，可能不是很好调试，所以希望Iceworks这个优秀的框架可以支持远程项目。

repo地址：https://github.com/kingzhuky/meripseqpipe/
现在正在用Ice撸web：https://github.com/bioinformatist/m6APipe-web

## 错误信息

无

**Comment by imsobear** [comment]
@bioinformatist 你现在用的是 iceworks 哪个版本？

**Comment by bioinformatist** [comment]
@imsobear 最新的，最新的~
icework 4.0开始都是退出所有进程之后后台自动更新的了~
所以我这边一直都是最新的
感觉直接支持Linux的各种x11倒是没什么必要，但是如果可以支持远程项目就已经很方便了

**Comment by imsobear** [comment]
@bioinformatist 远程的话你设想的工作流程是怎样的？在 windows 上用 iceworks IDE 写代码，但是项目的 `npm run start` 调试服务是启动在 linux 上的？

**Comment by bioinformatist** [comment]
@imsobear 其实我觉得只要把类似VS code的remote: SSH模块差不多合并过来就好
我现在基本上就是这样操作，主要是有目录结构比较方便
因为还要写后端，icework里面的前端代码原样迁移到Linux下没有任何问题的，只是在这个体系里写后端就很不方便了，我现在的做法是放弃使用Ice的IDE，直接用VS code + npm cli了，但是回头再想改前端（直接搞物料）也有点麻烦

**Comment by imsobear** [comment]
@bioinformatist 我们近期会做一些 VS Code 的插件，到时候欢迎使用哈~

**Comment by bioinformatist** [comment]
@imsobear 好的鸭好的鸭，到时候你们和我说一下hhh，多谢~~~
