### ISSUE TITLE
项目依赖安装失败

### ISSUE THREAD

**Issue by joyuce** [alibaba/ice#304]
模板市场
ICE Design Analytical
ICE Design CMS
ICE Design Lite
ICE Design Pro
选择项目地址：

点击选择/新建文件夹
项目文件生成到：
F:\webproject/
项目名称：

tupian
 
同时安装项目依赖
开始创建项目
项目依赖安装失败
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated @types/commander@2.12.2: This is a stub types definition for commander (https://github.com/tj/commander.js). commander provides its own type definitions, so you don't need @types/commander installed!
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\d3-selection-a96cd0b1\package.json'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\d3-sankey-c9389ad5\package.json'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\d3-shape-c291ceba\package.json'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\d3-selection-a96cd0b1\.eslintrc'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\d3-sankey-c9389ad5\.npmignore'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\d3-shape-c291ceba\.npmignore'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\damerau-levenshtein-6b299bb5\test\test.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\d3-selection-a96cd0b1\index.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\d3-sankey-c9389ad5\README.md'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\d3-voronoi-9d53695e\build\d3-voronoi.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\d3-shape-c291ceba\README.md'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\d3-selection-a96cd0b1\LICENSE'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\d3-sankey-c9389ad5\LICENSE'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\d3-voronoi-9d53695e\build\d3-voronoi.min.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\d3-selection-a96cd0b1\README.md'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\d3-sankey-c9389ad5\index.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\d3-voronoi-9d53695e\.eslintrc'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\d3-voronoi-9d53695e\graph.png'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\clean-css-90f37c81\lib\utils\clone-array.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\clean-css-90f37c81\lib\utils\has-protocol.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\clean-css-90f37c81\lib\utils\is-data-uri-resource.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\clean-css-90f37c81\lib\utils\is-http-resource.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\clean-css-90f37c81\lib\utils\format-position.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\clean-css-90f37c81\lib\utils\is-import.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\clean-css-90f37c81\lib\utils\is-remote-resource.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\clean-css-90f37c81\lib\utils\natural-compare.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\clean-css-90f37c81\lib\utils\override.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\clean-css-90f37c81\lib\utils\split.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\clean-css-90f37c81\lib\utils\is-https-resource.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-bac883c7\lib\_components\@alife\next-config-provider\lib\index.js'
npm WARN tar ENOENT: no such file or directory, lstat 'F:\webproject\node_modules\.staging\clean-css-90f37c81\lib\writer'
npm WARN tar ENOENT: no such file or directory, lstat 'F:\webproject\node_modules\.staging\@icedesign\base-a9266b2a\lib\_components\@alife\next-cascader-select'
npm WARN tar ENOENT: no such file or directory, lstat 'F:\webproject\node_modules\.staging\@icedesign\base-a1a71843\lib\_components\@alife\next-cascader-select\lib'
npm WARN tar ENOENT: no such file or directory, lstat 'F:\webproject\node_modules\.staging\@icedesign\base-b414e5f0\lib\_components\@alife\next-cascader-select\lib'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\fsevents-e30d3e9e\node_modules\aws4\package.json'
npm WARN tar ENOENT: no such file or directory, lstat 'F:\webproject\node_modules\.staging\@icedesign\base-017bf75e\lib\_components\@alife\next-cascader-select\lib'
npm WARN tar ENOENT: no such file or directory, lstat 'F:\webproject\node_modules\.staging\@icedesign\base-8cf5efe0\lib\_components\@alife\next-cascader-select\lib'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\fsevents-e30d3e9e\node_modules\aws4\.npmignore'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\fsevents-e30d3e9e\node_modules\aws4\README.md'
npm WARN tar ENOENT: no such file or directory, lstat 'F:\webproject\node_modules\.staging\@icedesign\base-57c3b0ee\lib\_components\@alife\next-cascader-select\lib'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\fsevents-e30d3e9e\node_modules\aws4\LICENSE'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\d3-sankey-c9389ad5\img\align-center.png'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\dateformat-28168ca6\lib\dateformat.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\fsevents-e30d3e9e\node_modules\aws4\aws4.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\fsevents-e30d3e9e\node_modules\aws4\lru.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\fsevents-e30d3e9e\node_modules\aws4\.tern-port'
npm WARN tar ENOENT: no such file or directory, lstat 'F:\webproject\node_modules\.staging\@icedesign\base-017bf75e\lib\_components\@alife'
npm WARN tar ENOENT: no such file or directory, lstat 'F:\webproject\node_modules\.staging\@icedesign\base-8cf5efe0\lib\_components\@alife'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\fsevents-e30d3e9e\node_modules\aws4\.travis.yml'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-017bf75e\lib\_components\@alife\next-cascader-select\lib\style.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-8cf5efe0\lib\_components\@alife\next-cascader-select\lib\style.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\utila-356f4afc\scripts\js\test\array.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\es5-ext-bc20695b\array\#\fill\implement.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\es5-ext-bc20695b\array\#\fill\index.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\utila-356f4afc\scripts\js\test\object.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\es5-ext-bc20695b\array\#\fill\is-implemented.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\es5-ext-bc20695b\array\#\fill\shim.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\utila-356f4afc\scripts\js\test\_prepare.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\core-js-70813f34\fn\_.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\core-js-70813f34\fn\weak-map.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\core-js-70813f34\fn\get-iterator-method.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\core-js-70813f34\fn\get-iterator.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\core-js-70813f34\fn\dict.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\core-js-70813f34\fn\is-iterable.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\core-js-70813f34\fn\set-timeout.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\core-js-70813f34\fn\log.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\core-js-70813f34\fn\map.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-57c3b0ee\lib\_components\@alife\next-cascader-select\lib\scss\variable.scss'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\core-js-70813f34\fn\set-interval.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-57c3b0ee\lib\_components\@alife\next-cascader-select\lib\style.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\core-js-70813f34\fn\delay.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\core-js-70813f34\fn\set-immediate.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\core-js-70813f34\fn\clear-immediate.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\core-js-70813f34\fn\promise.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\core-js-70813f34\fn\set.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\core-js-70813f34\fn\weak-set.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\fsevents-e30d3e9e\node_modules\block-stream\package.json'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\fsevents-e30d3e9e\node_modules\block-stream\README.md'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\fsevents-e30d3e9e\node_modules\block-stream\LICENCE'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\fsevents-e30d3e9e\node_modules\block-stream\LICENSE'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\fsevents-e30d3e9e\node_modules\block-stream\block-stream.js'
npm WARN tar ENOENT: no such file or directory, lstat 'F:\webproject\node_modules\.staging\@icedesign\base-6c994827\lib\_components\@alife\next-cascader\lib'
npm WARN tar ENOENT: no such file or directory, lstat 'F:\webproject\node_modules\.staging\@icedesign\base-cd355584\lib\_components\@alife\next-cascader\lib'
npm WARN tar ENOENT: no such file or directory, lstat 'F:\webproject\node_modules\.staging\@icedesign\base-6c994827\lib'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-6c994827\lib\_components\@alife\next-cascader\lib\style.js'
npm WARN tar ENOENT: no such file or directory, lstat 'F:\webproject\node_modules\.staging\@icedesign\base-cd355584\lib\_components'
npm WARN tar ENOENT: no such file or directory, lstat 'F:\webproject\node_modules\.staging\@icedesign\base-a1a71843\lib\_components\@alife\next-cascader'
npm WARN tar ENOENT: no such file or directory, lstat 'F:\webproject\node_modules\.staging\@icedesign\base-a9266b2a\lib\_components\@alife\next-cascader\lib'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-7ced889a\lib\_components\@alife\next-cascader\lib\scss\mixin.scss'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-7ced889a\lib\_components\@alife\next-cascader\lib\scss\variable.scss'
npm WARN tar ENOENT: no such file or directory, lstat 'F:\webproject\node_modules\.staging\@icedesign\base-a9266b2a\lib'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-7ced889a\lib\_components\@alife\next-cascader\lib\style.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-cd355584\lib\_components\@alife\next-cascader\lib\style.js'
npm WARN tar ENOENT: no such file or directory, lstat 'F:\webproject\node_modules\.staging\@icedesign\base-a1a71843\lib\_components'
npm WARN tar ENOENT: no such file or directory, lstat 'F:\webproject\node_modules\.staging\@icedesign\base-b414e5f0\lib\_components\@alife\next-cascader\lib\scss'
npm WARN tar ENOENT: no such file or directory, lstat 'F:\webproject\node_modules\.staging\@icedesign\base-7ced889a\lib'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-a9266b2a\lib\_components\@alife\next-cascader\lib\style.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-a1a71843\lib\_components\@alife\next-cascader\lib\style.js'
npm WARN tar ENOENT: no such file or directory, lstat 'F:\webproject\node_modules\.staging\@icedesign\base-b414e5f0\lib\_components'
npm WARN tar ENOENT: no such file or directory, lstat 'F:\webproject\node_modules\.staging\@icedesign\base-bac883c7\lib\_components\@alife\next-core\lib\variables'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-b414e5f0\lib\_components\@alife\next-cascader\lib\style.js'
npm WARN tar ENOENT: no such file or directory, lstat 'F:\webproject\node_modules\.staging\@icedesign\base-57c3b0ee\lib\_components\@alife\next-cascader'
npm WARN tar ENOENT: no such file or directory, lstat 'F:\webproject\node_modules\.staging\@icedesign\base-57c3b0ee\lib\_components'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\less-0e689da9\test\less\plugin\plugin-global.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-57c3b0ee\lib\_components\@alife\next-cascader\lib\style.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\less-0e689da9\test\less\plugin\plugin-local.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\less-0e689da9\test\less\plugin\plugin-transitive.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\less-0e689da9\test\less\plugin\plugin-tree-nodes.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\less-0e689da9\test\less\plugin\plugin-transitive.less'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\less-0e689da9\test\less\plugin.less'
npm WARN tar ENOENT: no such file or directory, lstat 'F:\webproject\node_modules\.staging\@icedesign\base-1abc29fb\lib\_components\@alife\next-checkbox\lib'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-bac883c7\lib\_components\@alife\next-core\lib\variables\_corner.scss'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-1abc29fb\lib\_components\@alife\next-checkbox\lib\style.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-bac883c7\lib\_components\@alife\next-core\lib\variables\_font.scss'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-bac883c7\lib\_components\@alife\next-core\lib\variables\_global.scss'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-bac883c7\lib\_components\@alife\next-core\lib\variables\_icon.scss'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-bac883c7\lib\_components\@alife\next-core\lib\variables\_line.scss'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-bac883c7\lib\_components\@alife\next-core\lib\variables\_shadow.scss'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-bac883c7\lib\_components\@alife\next-core\lib\variables\_size.scss'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-1abc29fb\lib\_components\@alife\next-config-provider\lib\index.js'
npm WARN tar ENOENT: no such file or directory, lstat 'F:\webproject\node_modules\.staging\@icedesign\base-1abc29fb\lib\_components'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\fsevents-e30d3e9e\node_modules\co\package.json'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\fsevents-e30d3e9e\node_modules\co\LICENSE'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\fsevents-e30d3e9e\node_modules\co\index.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-e0c6d39d\lib\_components\@alife\next-core\lib\base\_normalize.scss'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\fsevents-e30d3e9e\node_modules\co\History.md'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\fsevents-e30d3e9e\node_modules\co\Readme.md'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-e0c6d39d\lib\_components\@alife\next-core\lib\base\_typography.scss'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\fsevents-e30d3e9e\node_modules\code-point-at\package.json'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\fsevents-e30d3e9e\node_modules\code-point-at\index.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\fsevents-e30d3e9e\node_modules\code-point-at\license'
npm WARN tar ENOENT: no such file or directory, lstat 'F:\webproject\node_modules\.staging\@icedesign\base-e0c6d39d\lib\_components\@alife\next-core\lib'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\fsevents-e30d3e9e\node_modules\code-point-at\readme.md'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-e0c6d39d\lib\_components\@alife\next-core\lib\main.scss'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-e0c6d39d\lib\_components\@alife\next-core\lib\next.scss'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-e0c6d39d\lib\_components\@alife\next-core\lib\style.js'
npm WARN pure-render-decorator@1.2.1 requires a peer of react@^15.0.0 || ^0.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN @icedesign/scaffold-pro@1.0.0 No repository field.
npm WARN @icedesign/scaffold-pro@1.0.0 No license field.

npm ERR! code EINTEGRITY
npm ERR! sha1-LWFaHvSu5PV0Qlzf9wJu34GRmDY= integrity checksum failed when using sha1: wanted sha1-LWFaHvSu5PV0Qlzf9wJu34GRmDY= but got sha1-zHtNO9IUfFJSWLHn7Q+IRHSDafQ=. (1331006 bytes)
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-1abc29fb\lib\_components\@alife\next-nav\lib\group.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-1abc29fb\lib\_components\@alife\next-nav\lib\index.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-1abc29fb\lib\_components\@alife\next-nav\lib\index.scss'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-1abc29fb\lib\_components\@alife\next-nav\lib\item.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-1abc29fb\lib\_components\@alife\next-nav\lib\main.scss'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-1abc29fb\lib\_components\@alife\next-nav\lib\nav.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-1abc29fb\lib\_components\@alife\next-nav\lib\popup-item.js'
npm WARN tar ENOENT: no such file or directory, lstat 'F:\webproject\node_modules\.staging\@icedesign\base-1abc29fb\lib\_components\@alife'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-e0c6d39d\lib\_components\@alife\next-animate\lib\scss\_expand-entrances\_expandInDown.scss'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-017bf75e\lib\_components\@alife\next-affix\lib\index.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-017bf75e\lib\_components\@alife\next-affix\lib\index.scss'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-017bf75e\lib\_components\@alife\next-affix\lib\main.scss'
npm WARN tar ENOENT: no such file or directory, lstat 'F:\webproject\node_modules\.staging\@icedesign\base-017bf75e\lib\_components\@alife\next-animate\lib\scss'
npm WARN tar ENOENT: no such file or directory, lstat 'F:\webproject\node_modules\.staging\@icedesign\base-017bf75e\lib\_components\@alife\next-animate\lib\scss\_other-entrances'
npm WARN tar ENOENT: no such file or directory, lstat 'F:\webproject\node_modules\.staging\@icedesign\base-017bf75e\lib\_components'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-bac883c7\lib\_components\@alife\next-animate\lib\scss\_fading-exits\_fadeOut.scss'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-bac883c7\lib\_components\@alife\next-animate\lib\scss\_fading-exits\_fadeOutDown.scss'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-bac883c7\lib\_components\@alife\next-animate\lib\scss\_fading-exits\_fadeOutDownBig.scss'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-bac883c7\lib\_components\@alife\next-animate\lib\scss\_fading-exits\_fadeOutLeft.scss'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-bac883c7\lib\_components\@alife\next-animate\lib\scss\_fading-exits\_fadeOutLeftBig.scss'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-bac883c7\lib\_components\@alife\next-animate\lib\scss\_fading-exits\_fadeOutRight.scss'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-bac883c7\lib\_components\@alife\next-animate\lib\scss\_fading-exits\_fadeOutRightBig.scss'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-bac883c7\lib\_components\@alife\next-animate\lib\scss\_fading-exits\_fadeOutUp.scss'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-bac883c7\lib\_components\@alife\next-animate\lib\scss\_fading-exits\_fadeOutUpBig.scss'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-bac883c7\lib\_components\@alife\next-animate\lib\scss\_fading-exits\fading-exits.scss'
npm WARN tar ENOENT: no such file or directory, lstat 'F:\webproject\node_modules\.staging\@icedesign\base-bac883c7\lib\_components'
npm WARN tar ENOENT: no such file or directory, lstat 'F:\webproject\node_modules\.staging\@icedesign\base-e0c6d39d\lib\_components\@alife\next-card\lib'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-e0c6d39d\lib\_components\@alife\next-card\lib\main.scss'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-e0c6d39d\lib\_components\@alife\next-core\lib\base\_normalize.scss'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-e0c6d39d\lib\_components\@alife\next-core\lib\base\_typography.scss'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-e0c6d39d\lib\_components\@alife\next-date-picker\lib\view\date-picker.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-e0c6d39d\lib\_components\@alife\next-date-picker\lib\view\month-picker.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-e0c6d39d\lib\_components\@alife\next-date-picker\lib\view\quick-tool.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-e0c6d39d\lib\_components\@alife\next-date-picker\lib\view\range-picker.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-e0c6d39d\lib\_components\@alife\next-date-picker\lib\view\utils.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\webproject\node_modules\.staging\@icedesign\base-e0c6d39d\lib\_components\@alife\next-date-picker\lib\view\year-picker.js'
npm WARN tar ENOENT: no such file or directory, lstat 'F:\webproject\node_modules\.staging\@icedesign\base-e0c6d39d\lib'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-03-17T11_05_28_815Z-debug.log
确认

**Comment by wssgcg1213** [comment]
考虑权限问题? 换一个逻辑分区安装可以成功吗

**Comment by noyobo** [comment]
closed by iceworks 2.0.0
