### ISSUE TITLE
ice-scripts@1.x 在 centos7 上构建错误

### ISSUE THREAD

**Issue by fangjishuai** [alibaba/ice#3071]
构建失败：
[root@master gm_web]# npm run build

> @icedesign/usertrack-admin-scaffold@1.0.0 build /root/gm_deploy/gm/gm_web
> ice build

ice-scripts 1.8.7
sassInfo node-sass      4.13.1  (Wrapper)       [JavaScript]
libsass         3.5.4   (Sass Compiler) [C/C++]
ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/root/gm_deploy/gm/gm_web/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/root/gm_deploy/gm/gm_web/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/root/gm_deploy/gm/gm_web/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
ice-scripts exited unexpectedly.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @icedesign/usertrack-admin-scaffold@1.0.0 build: `ice build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @icedesign/usertrack-admin-scaffold@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-20T03_49_55_513Z-debug.log

package.json
`{
  "name": "@icedesign/usertrack-admin-scaffold",
  "version": "1.0.0",
  "description": "该模板内置了丰富的区块，适用于埋点治理的管理系统，使用时需要根据需求进行删除和添加",
  "files": [
    "src/",
    "build/",
    "public/",
    "tests/",
    "_gitignore",
    ".editorconfig",
    ".eslintignore",
    ".eslintrc"
  ],
  "dependencies": {
    "@alifd/next": "^1.13.2",
    "@alifd/theme-1": "^0.0.6",
    "@antv/data-set": "^0.8.9",
    "@icedesign/container": "^1.x",
    "@icedesign/data-binder": "^1.0.0",
    "@icedesign/dynamic-icon": "^0.1.6",
    "@icedesign/form-binder": "^1.x",
    "@icedesign/foundation-symbol": "^1.x",
    "@icedesign/img": "^1.x",
    "@icedesign/layout": "^1.x",
    "@icedesign/theme": "^0.1.2",
    "axios": "^0.18.0",
    "bizcharts": "^3.2.2",
    "classnames": "^2.2.5",
    "echarts": "^4.6.0",
    "echarts-for-react": "^2.0.14",
    "enquire-js": "^0.1.2",
    "immutable": "^3.8.2",
    "install": "^0.12.2",
    "intl": "^1.2.5",
    "is-hotkey": "^0.1.1",
    "jquery": "^3.3.1",
    "js-md5": "^0.7.3",
    "json": "^9.0.6",
    "moment": "^2.23.0",
    "npm": "^6.8.0",
    "prop-types": "^15.5.8",
    "react": "^16.4.1",
    "react-dom": "^16.4.1",
    "react-router-dom": "^4.2.2",
    "slate": "^0.32.1",
    "slate-plain-serializer": "^0.5.1",
    "slate-react": "^0.21.18"
  },
  "devDependencies": {
    "babel-eslint": "^8.0.3",
    "eslint": "^4.13.1",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-plugin-babel": "^4.1.1",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-react": "^7.5.1",
    "ice-scripts": "^1.7.1"
  },
  "scripts": {
    "start": "ice dev",
    "build": "ice build",
    "lint": "eslint . --ext '.js,.jsx' --fix"
  },
  "publishConfig": {
    "registry": "http://registry.npmjs.com",
    "access": "public"
  },
  "buildConfig": {
    "theme": "@icedesign/theme",
    "entry": "src/index.js",
    "localization": false,
    "output": {
      "publicPath": "./"
    }
  },
  "scaffoldConfig": {
    "builder": "ice-scripts",
    "name": "ice-usertrack-admin",
    "title": "应用监控系统",
    "categories": [
      "行业领域"
    ],
    "screenshot": "https://img.alicdn.com/tfs/TB1LkGRDH2pK1RjSZFsXXaNlXXa-2860-1580.png",
    "screenshots": [
      "https://img.alicdn.com/tfs/TB1LkGRDH2pK1RjSZFsXXaNlXXa-2860-1580.png"
    ]
  },
  "engines": {
    "node": ">=8.0.0"
  },
  "title": "gm_web",
  "proxyConfig": {
    "/**": {
      "enable": true,
      "target": "http://127.0.0.1:8888/"
    },
    "https://open.work.weixin.qq.com/wwopen/sso/qrConnect": {
      "enable": true,
      "target": "https://open.work.weixin.qq.com/wwopen/sso/qrConnect"
    }
  },
  "iceworks": {
    "type": "react",
    "adapter": "adapter-react-v0"
  }
}
`

**Comment by imsobear** [comment]
ice-scripts@1.x 依赖的是 gulp 3，gulp 3 不支持在 node 12 里使用了https://github.com/gulpjs/gulp/issues/2324

建议参考官方文档升级到 icejs
