### ISSUE TITLE
win10 控制台报错的时候路径丢失了 /

### ISSUE THREAD

**Issue by shibxz** [alibaba/ice#3076]
info WEBPACK             df3fa8cf949fe5c0a15a.hot-update.json   47 bytes          [emitted] [immutable] [hmr]
info WEBPACK                                      favicon.png   4.83 KiB          [emitted]
info WEBPACK                                        index.css   13.5 KiB   index  [emitted]                    index
info WEBPACK                                    index.css.map    125 KiB   index  [emitted] [dev]              index
info WEBPACK         index.df3fa8cf949fe5c0a15a.hot-update.js   1.43 KiB   index  [emitted] [immutable] [hmr]  index
info WEBPACK     index.df3fa8cf949fe5c0a15a.hot-update.js.map  974 bytes   index  [emitted] [dev]              index
info WEBPACK                                       index.html  446 bytes          [emitted]
info WEBPACK                                         index.js   3.04 MiB   index  [emitted]                    index
info WEBPACK                                     index.js.map   2.99 MiB   index  [emitted] [dev]              index
info WEBPACK
info WEBPACK     ERROR in ./.ice/createApp.tsx
info WEBPACK     Module not found: Error: Can't resolve '`D:workjsicework1study11`
info WEBPACK     ode_moduleuild-plugin-ice-corelibmodule.js' in 'D:\work\js\ice\work1\study11\.ice'
info WEBPACK      @ ./.ice/createApp.tsx 18:23-111
info WEBPACK      @ ./.ice/index.ts
info WEBPACK      @ ./src/app.jsx
info WEBPACK      @ multi ./src/app

![image](https://dmall-cdn.devaqk.com/file/8/202002/20/20200220211724052231846.png)
<img src="https://dmall-cdn.devaqk.com/file/8/202002/20/20200220211724052231846.png"/>
截图被屏蔽了
路径是  https://dmall-cdn.devaqk.com/file/8/202002/20/20200220211724052231846.png

**Comment by imsobear** [comment]
issue 迁移到 icejs 仓库下了，这个先关闭了
