### ISSUE TITLE
Cannot find module '@alib/build-scripts/dist/utils/checkNodeVersion'

### ISSUE THREAD

**Issue by cmdparkour** [alibaba/ice#3081]
刚开始安装iceworks
初始化框架应用时在执行完npm install 命令之后，npm start 命令报错。
**报错信息如下：**
Cannot find module '@alib/build-scripts/dist/utils/checkNodeVersion'

**Comment by cmdparkour** [comment]
**具体命令行报错信息如下所示：**

F:\网站项目\飞冰\微前端\icestark>npm start

> @icedesign/stark-layout-scaffold@3.0.7 start F:\网站项目\飞冰\微前端\icestark
> icejs start


F:\网站项目\飞冰\微前端\icestark>"node"  "F:\网站项目\飞冰\微前端\icestark\node_
modules\.bin\\..\_ice.js@1.0.7@ice.js\bin\ice-cli.js" start
internal/modules/cjs/loader.js:984
  throw err;
  ^

Error: Cannot find module '@alib/build-scripts/dist/utils/checkNodeVersion'
Require stack:
- F:\网站项目\飞冰\微前端\icestark\node_modules\_ice.js@1.0.7@ice.js\bin\ice-cli
.js
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:981
:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:863:27)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:1043:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:77:18)[39m
    at Object.<anonymous> (F:\网站项目\飞冰\微前端\icestark\node_modules\[4m_ic
e.js@1.0.7@ice.js[24m\bin\ice-cli.js:3:26)
[90m    at Module._compile (internal/modules/cjs/loader.js:1157:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:1
0)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:1001:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:900:14)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_ma
in.js:74:12)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [
    [32m'F:\\网站项目\\飞冰\\微前端\\icestark\\node_modules\\_ice.js@1.0.7@ice.
js\\bin\\ice-cli.js'[39m
  ]
}

**Comment by imsobear** [comment]
周末的版本已经修复了，忘记回复了。
