### ISSUE TITLE
自定义 public 解析目录

### ISSUE THREAD

**Issue by zoffyzhang** [alibaba/ice#3088]
## 问题描述
"我们约定 public 目录下的文件会在 dev 和 build 时被自动 copy 到输出目录（默认是 ./build）下。所以可以在这里存放 favicon, index.html 等静态文件。"

关于文档里的这句，可不可以自定义 public 解析路径？比如 "./src/static"

## 错误信息
无

**Comment by imsobear** [comment]
@zoffyzhang 这个感觉需求不大，public 更符合社区规范，暂时不计划支持自定义。
