### ISSUE TITLE
打包后运行build中的代码，react-dom报错，提示 Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead.

### ISSUE THREAD

**Issue by flylee2011** [alibaba/ice#309]
![image](https://user-images.githubusercontent.com/1164223/37588740-206b666e-2b9e-11e8-9609-cf35454ee21c.png)

打包后运行build中的代码，react-dom报错，提示 Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead.

这个是什么原因？

**Comment by wssgcg1213** [comment]
底层依赖了一些老规范的组件, 把 react-dom 切换成 production.min.js 就可以了

**Comment by noyobo** [comment]
- iceworks 增加修改构建后的模板内容

**Comment by flylee2011** [comment]
好的。了解了。
目前模板里，我看react，react-dom都是外链，还有字体文件也是外链，这些不能本地化吗，比如react放到package里安装到项目node_modules，字体文件也打包到项目一个目录。
这块文档里好像没有提到？是现在只能外链，还是后期有打算这块做一些调整？

**Comment by yujiangshui** [comment]
@flylee2011 外链主要考虑到缓存、CDN 等的能力，打包在一起会变得比较大，而且其他页面用到了 React 都在自己 bundle 里面没法缓存。

**Comment by wssgcg1213** [comment]
@yujiangshui 确实是 16 版本的  可能是别的组件 需要排查

**Comment by noyobo** [comment]
```html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <meta http-equiv="x-ua-compatible" content="ie=edge,chrome=1">
  <link rel="icon" type="image/png" href="https://img.alicdn.com/tps/TB1kBU7NpXXXXXLXXXXXXXXXXXX-160-160.png">
  <meta name="viewport" content="width=device-width">
  <title>ICE Design Lite</title>
</head>

<body>
  <div id="ice-container"></div>
<% if (NODE_ENV === 'production') { %>
<script src="https://g.alicdn.com/code/npm/??react/16.2.0/umd/react.production.min.js,react-dom/16.2.0/umd/react-dom.production.min.js"></script>
<% } else { %>
<script src="https://g.alicdn.com/code/npm/??react/16.2.0/umd/react.development.js,react-dom/16.2.0/umd/react-dom.development.js"></script>
<% } %>
</body>
</html>
```

增加判断条件，ice-scripts 1.2.0 后支持，待发布。 cc @chenbin92 模板需要对应的修改

**Comment by yujiangshui** [comment]
@wssgcg1213 https://github.com/react-component/menu/blob/master/src/Menu.jsx#L8 可以联系下那边有没有兴趣干掉这个。
