### ISSUE TITLE
关于权限管理的一些问题咨询

### ISSUE THREAD

**Issue by raohuiyong** [alibaba/ice#3090]
想做一个路由的权限管理，在路由每次跳转之前进行路由的权限验证，只有通过验证的路由才可以继续访问，否则重定向到指定页面，请问有什么全局的方法可以设置。
大概实现的效果类似`vue-router`的`beforeEach`方法

**Comment by imsobear** [comment]
你现在用的是 ice-scripts 还是 icejs？或者截图看下根目录结构

**Comment by raohuiyong** [comment]
> 你现在用的是 ice-scripts 还是 icejs？或者截图看下根目录结构

用的icejs，下载的官网的模板Fusion Design Pro（TypeScript）构建的项目。

**Comment by imsobear** [comment]
恩 这块着急的话可以先用以前的方案，类似给每个页面包个 withAuth：https://ice.work/docs/guide-0.x/dev/authority

这个需求在 icejs 里可以做到更简单，这块我这两天整理下方案，下周应该可以支持，先关注下这个 issue：https://github.com/ice-lab/icejs/issues/70 。

当前这个 issue 我先关闭了，后面 icejs 的问题可以反馈到 ice-lab/icejs 这个仓库，alibaba/ice 主要是 iceworks 相关哈。
