### ISSUE TITLE
项目启动不了，在3.x的版本可以启动，用4.x的就不可以了

### ISSUE THREAD

**Issue by XiaoZhangQAQ1** [alibaba/ice#3099]
## 问题描述
点击启动项目后卡在这里运行不了

开始运行任务...
> @icedesign/pro-scaffold@3.0.10 start e:\workspace(vs)\test
> ice-scripts dev
ice-scripts 2.1.11
sassInfo node-sass	4.12.0	(Wrapper)	[JavaScript]
libsass 3.5.4	(Sass Compiler)	[C/C++]
到这里就不动了
切换到开发人员模式
有一个这个错误
Failed to load resource: the server responded with a status of 404 ()

## 错误信息
没报错误，项目起不来

![AON 7UL~V@5D3N5K7AO5$OA](https://user-images.githubusercontent.com/43202906/75752106-f9f54380-5d62-11ea-8816-31789962cdfc.png)

**Comment by imsobear** [comment]
建议先使用终端的方式启动，iceworks IDE 目前存在一些问题，我们正在跟进修复中。
