### ISSUE TITLE
iceworks桌面版安装依赖时间超长

### ISSUE THREAD

**Issue by wu482525** [alibaba/ice#3103]
iceworks桌面版安装依赖时间超长，我的电脑是win10系统，安装了iceworks Windows版本，新建项目icestark框架应用后，安装依赖时间超过天也未完成安装，电脑网络正常，npm也是使用了阿里镜像！

**Comment by imsobear** [comment]
@wu482525 先使用终端的方式来安装，iceworks IDE 目前存在一些问题，我们正在修复中。

**Comment by niaoshuai** [comment]
团队内部一直用的ice， 前天晚上作4.0 技术交流会，大型翻车现场
