### ISSUE TITLE
input组件trim属性不好用

### ISSUE THREAD

**Issue by sunguangjin** [alibaba/ice#3106]
问题类型：组件
具体组件：input
问题描述：input输入类组件的 trim 属性不满足需求，现在的效果相当于禁用了空格输入。期望是能输入空格，只是在失焦的时候去除首尾空格。很多时候，字符串中间是需要输入空格的。

**Comment by imsobear** [comment]
组件问题在这里反馈哈：https://fusion.design/feedback

**Comment by sunguangjin** [comment]
收到，已反馈，感谢。

发自我的iPhone
