### ISSUE TITLE
download iceworks windows version blocked by ESET antivirus

### ISSUE THREAD

**Issue by masterclock** [alibaba/ice#312]
时间;扫描程序;对象类型;对象;威胁;操作;用户;信息;哈希;此处首次所见
2018/3/19 20:01:55;HTTP 过滤器;文件;http://iceworks.oss-cn-hangzhou.aliyuncs.com/win/Iceworks-setup-1.1.1.exe;Blocked Object;连接中断;******\*****;通过应用程序访问 web 时检测到威胁: C:\Program Files (x86)\Google\Chrome\Application\chrome.exe (87A567F54537E5D2335FC226F44E4FB35067ED03).;ACDF1A926792BDABD021D66D75017474D5B71055;2018/3/19 19:57:51

windows 10
eset antivirus 17080(20180319)

**Comment by yujiangshui** [comment]
![image](https://user-images.githubusercontent.com/2942913/37596138-2f1978e6-2bb6-11e8-80de-0375952f4226.png)

已经添加说明。

只要是可执行文件都有几率被误判。 @noyobo @wssgcg1213 后面 win 版本用 zip 压缩下在流程上是否方便？

**Comment by noyobo** [comment]
嗯， 增加一个 zip 的下载类型。

**Comment by noyobo** [comment]
讨论后决定，没必要增加其他下载方式， exe 运行前的为电脑的保护提醒机制。
