### ISSUE TITLE
tab下的table边框在火狐浏览器丢失

### ISSUE THREAD

**Issue by DylinZhang** [alibaba/ice#3124]
谷歌浏览器：
![image](https://user-images.githubusercontent.com/33078688/76920393-58dfbe80-6906-11ea-908e-378252bbf60c.png)
火狐浏览器：
![image](https://user-images.githubusercontent.com/33078688/76920416-69903480-6906-11ea-80c6-d2d608452121.png)

**Comment by youluna** [comment]
在table的body上增加了position: relative 撞上了一个火狐的“特性”，解决方案考虑中
https://stackoverflow.com/question/7517127/borders-not-shown-in-firefox-with-border-collapse-on-table-position-relative-o
