### ISSUE TITLE
期待Table组件支持类似scrollToRow 滚动到指定行一样，可以滚动到指定列

### ISSUE THREAD

**Issue by POTERYUNG** [alibaba/ice#3132]
需求问题：table存在很多列，无法快速预览关注的部分重要信息，滚动条无法快速达到效果。
期待解决：期待Table组件支持类似scrollToRow 滚动到指定行一样，可以滚动到指定列。

**Comment by imsobear** [comment]
基础组件问题反馈到这里：https://fusion.design/feedback
