### ISSUE TITLE
使用 build-plugin-fusion 设置多主题时icon报错。

### ISSUE THREAD

**Issue by a188658587** [alibaba/ice#3136]
`{
  "entry": "src/index",
  "alias": {
    "@": "./src"
  },
  "publicPath": "./",
  "vendor": false,
  "plugins": [
    "build-plugin-ice-app",
    [
      "build-plugin-fusion",
      {
        "themePackage": [
          {
            "name": "@alifd/theme-design-pro",
            "default": true
          },
          {
            "name": "@alifd/theme-12074"
          }
        ],
        "uniteBaseComponent": "@alife/next",
        "themeConfig": {
          "nextPrefix": "next-"
        }
      }
    ],
    "build-plugin-fusion-material",
    ["build-plugin-css-assets-local", {
      "outputPath": "assets",
      "relativeCssPath": "./"
    }],
    "./build.plugin.js"
  ]
}
`
在设置 多主题的时候 编译时icon报错。看源码发现 多主题处理哪里有点问题。主题处理了，icon没有处理。 希望可以解决一下。
也不知道是谁在哪维护，我就提到这里了

## 错误信息
info 已启用 themePackage 多主题功能 
info uniteBaseComponent 开启，基础包统一到： @alife/next
                                         10% buildingℹ ｢wds｣: Project is running at http://0.0.0.0:3333/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /Users/wanglin/project/react-iceDesignTs

info WEBPACK Starting the development server at:
info    - Local  :  http://localhost:3333/
info    - Network:  http://192.168.31.17:3333/

  92% chunk asset optimization[WARNING]: 编译 Icon 出错，构建继续。错误详细信息： Error: Undefined variable: "$css-prefix".

**Comment by imsobear** [comment]
icejs 的问题请提到 https://github.com/ice-lab/icejs ，这个仓库是 iceworks
