### ISSUE TITLE
ice-scripts 怎么分配更多的内存？

### ISSUE THREAD

**Issue by jacktang** [alibaba/ice#3142]
`yarn build`的时候出现内存不足的错误，尝试添加 `max_old_space_size`，结果不认识这个选项

```
ice-scripts --max_old_space_size=6096 build
ice-scripts 2.1.11
sassInfo node-sass	4.12.0	(Wrapper)	[JavaScript]
libsass  	3.5.4	(Sass Compiler)	[C/C++]
error: unknown option `--max_old_space_size'
error Command failed with exit code 1.
```

**Comment by ClarkXia** [comment]
max_old_space_size 是 node 的配置，可以通过修改 package.json 中的 build 命令进行处理

1. cross-env NODE_OPTIONS=--max_old_space_size=8192 ice-scripts build
2. node --max_old_space_size=8192 node_modules/.bin/ice-scripts build
