### ISSUE TITLE
如何处理微前端中各个子应用和基座应用之间的登录授权关系？

### ISSUE THREAD

**Issue by bigbigbo** [alibaba/ice#3148]
子应用允许独立运行，并且又允许运行在基座应用中，请问：
1. 如何处理子应用独立运行时的登录授权问题？
2. 运行在基座应用的时候，登录授权又是怎么样的呢？

分别讨论子应用和基座应用的两种关系：
1. 运行在同域下
2. 运行在不同域下

**Comment by imsobear** [comment]
@bigbigbo issue 移到 icestark 仓库里面吧 https://github.com/ice-lab/icestark/issues

**Comment by bigbigbo** [comment]
@imsobear 好的
