### ISSUE TITLE
mac版本无法选择目录

### ISSUE THREAD

**Issue by lijie19871108** [alibaba/ice#315]
选择浏览，选中目录后，目录并没有填入输入框中，开始创建项目按钮一直处于不可点击的状态

**Comment by lijie19871108** [comment]
再精确点：最后一级目录，目录名是中文的情况下，无法选中目录。

**Comment by lijie19871108** [comment]
![image](https://user-images.githubusercontent.com/5638950/37808071-995a9774-2e83-11e8-95c7-c494f25ea02f.png)
创建项目阶段，没有看到提示

**Comment by noyobo** [comment]
@lijie19871108  升级下 iceworks 版本
