### ISSUE TITLE
iceworks初始化的物料库，多包场景希望增加lerna支持

### ISSUE THREAD

**Issue by hipoyang** [alibaba/ice#3153]
## 问题描述

目前使用iceworks生成物料库及component的模板代码生成，基于build-scripts做工程构建。多数场景物料库是一个多组件的场景（多npm包），其中不乏多包依赖的问题。目前的这个工程套件没有支持lerna，在做包管理比较低效，希望增加lerna多包管理能力。

**Comment by imsobear** [comment]
@hipoyang 可以先手动接一下，接好了发现仓库地址，我们参考下看看怎么接入到模板里。

**Comment by imsobear** [comment]
仓库迁移：https://github.com/ice-lab/iceworks/issues/4
