### ISSUE TITLE
ice文档有些链接无法访问

### ISSUE THREAD

**Issue by lewis-li** [alibaba/ice#3156]
## 文档里有些链接应该是你们内部链接，如：[目录结构/config.ts](https://ice.work/docs/guide/basic/structure#config.ts) 的链接是 <https://ice.alibaba-inc.com/docs/guide/basic/config#%E6%A0%B9%E6%8D%AE%E7%8E%AF%E5%A2%83%E9%85%8D%E7%BD%AE> ，我们无法打开。

**Comment by imsobear** [comment]
已修复
