### ISSUE TITLE
使用icejs 1.x构建build.json配置文件冲突

### ISSUE THREAD

**Issue by zhangyuliangzyl** [alibaba/ice#3157]
飞冰大佬们好
       我们使用icejs 1.x做构建，接入我们公司内部的编译系统时，发现build.json这个文件是冲突的。请问下飞冰有没有什么办法可以自定义配置文件的名称或者路径。比如可以在package.json里配置个"iceConfig": "ice.build.json"，来指定飞冰系统的构建配置。

**Comment by ClarkXia** [comment]
通过 cli 参数 `--config` 可以指定工程配置文件
