### ISSUE TITLE
执行icesworks add block命令后，让填写block name，不管输入什么区块名都报名字已存在

### ISSUE THREAD

**Issue by 1YOYO** [alibaba/ice#3159]
## 简述
执行icesworks add block命令时，让填写block name，不管输入什么区块名字都报名字已存在

## 问题描述

按照 飞冰 文档-快速开发物料的步骤进行开发

**1.** $ npm install iceworks -g

**2.** $ iceworks -V
=> 3.2.0

**3.** $ iceworks init
填写信息

**4.** 在根目录下执行：
$ iceworks add block
block name EastEggLogin(试了无数名字)
=> this block name(@eastCentury/east-egg-login) has already exist. please retry

## 错误信息

this block name(@eastCentury/east-egg-login) has already exist. please retry

**Comment by imsobear** [comment]
仓库迁移：https://github.com/ice-lab/iceworks/issues/5
