### ISSUE TITLE
打包出来的文件没有去除注释，亦未找到配置去除注释的地方

### ISSUE THREAD

**Issue by pimkle** [alibaba/ice#3161]
## 错误信息

用 ice 脚手架开发了个组件，node_modules 里查看打包出来的文件，里面的注释一点没删，全在，翻了老半天文档，也没找到配置的地方，minify 默认就开了哇。

![image](https://user-images.githubusercontent.com/3403548/79957022-90b4c580-84b3-11ea-9c44-1f05eb056be0.png)

**Comment by imsobear** [comment]
组件构建到 lib 一般只走 babel（不会压缩代码），不走 webpack。
