### ISSUE TITLE
iceworks-cli

### ISSUE THREAD

**Issue by gitzhuhe** [alibaba/ice#3166]
## 问题描述

我在用 iceworks add 区块名的时候，发现不读取项目配置的materialConfig。

在这个addBlockToProject文件的 45 行第二个参数是 null。

在执行 downloadMaterialTemplate 之前 读取了项目的 package.json（command/add.js 22行）
` if (!materialType && npmName) {
    await addBlockToProject(options, destDir);
    return;
  }

  const materialPkg = await fse.readJson(path.join(destDir, 'package.json'));
  const { materialConfig, name = '' } = materialPkg;`

我觉得应该把这两段反过来，把materialConfig传入到addBlockToProject。

或者 在 addBlockToProject文件的 45行之前接入
`
  const materialPkg = await fse.readJson(path.join(destDir, 'package.json'));
  const { materialConfig, name = '' } = materialPkg;
`
再把materialConfig写到第二个参数

**Comment by imsobear** [comment]
已线下沟通
