### ISSUE TITLE
[RFC] 权限方案设计

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#3169]
>  关联 issue https://github.com/ice-lab/icejs/issues/70

整体能力决定实现到 `plugin-ice-auth` 里，插件默认不内置。对比实现到 plugin-router 里：

优点：

- 不影响 bundle 大小
- 逻辑分离好维护

缺点：

- 多包一层 HOC

## 初始化用户角色

在 `src/app.ts` 中设置当前用户的角色：

```js
import { createApp, helpers, IAppConfig } from 'ice';
import NoAuthComponent from '@/components/NoAuthComponent';
const { cookie } = helpers;

const appConfig: IAppConfig = {
  app: {},
  auth: {
    setRole: () => {
      // 服务端将当前用户角色 role 保存在 cookie 中，或者通过全局变量等方式输出
      const { role } = cookie.parse(document.cookie);
      return role;
    },
    // 可选，配置无权限时的视图组件，默认有一个
    NoAuthComponent,
  }
};

createApp(appConfig);
```

### 异步获取角色

外部很多公司的 html 是托管在 nginx 这一层的，同步访问 html 时没有任何鉴权，鉴权/登录逻辑是在前端代码里调用的，通过 `app.getInitalData` 实现，`app.getInitalData` 有点像应用级别的支持同步/异步的 setup，可以考虑作为通用能力而不仅是服务于 SSR。大概的用法：

```js
import { createApp, helpers, IAppConfig } from 'ice';
import NoAuthComponent from '@/components/NoAuthComponent';
const { cookie } = helpers;

const appConfig: IAppConfig = {
  app: {
    getInitialData: async () => {
      const role = await request('/api/getRole');
      return { role };
    }
  },
  auth: {
    setRole: (initialData) => {
      return initialData.role;
    },
  }
};
```

## 页面/路由权限

通过 `pageConfig.roles` 声明当前页面允许哪些角色访问：

```js
import React from 'react';

const Home = () => {
  return <>Home Page</>;
};

Home.pageConfig = {
  // 允许的角色，若不配置则代表所有角色都可以访问
  roles: ['guest', 'admin'],

  // 对 roles 的补充，控制能力更强
  hasAuth: () => { return true; }
};

export default Home;
```

## 组件级权限

提供 `getRole()` API 获取当前用户的角色：

```js
import { getRole } from 'ice';

function CustomComponent() {
  const role = getRole();
  return (
    <>
        <div>当前用户角色：{role}</div>
        { role === 'admin' ? <span>确定</span> : null }
        { ['guest', 'admin' ].indexOf(role) !== -1 ? <span>更新</span> : <span>无权限</span> }
    </>
  );
}
```

## 菜单权限

业务代码结合 API `getRole()` 自己消化

## 操作权限抽象

> 不需要框架做什么事情，一个最佳实践

@TODO

## 相关链接

- 之前版本的权限方案：https://ice.work/docs/guide-0.x/dev/authority

**Comment by cqcmdwym** [comment]
👀

**Comment by busyfree** [comment]
OK

**Comment by chenbin92** [comment]
@raohuiyong  @cqcmdwym 已发布 beta 版本 icejs@1.4.0-alpha.0，使用文档 https://github.com/alibaba/ice/blob/release-next/docs/guide/advance/auth.md

**Comment by chenbin92** [comment]
已发布 icejs@1.4.0 正式版本

**Comment by cqcmdwym** [comment]
@chenbin92 棒棒棒！

**Comment by cqcmdwym** [comment]
@chenbin92 有一个问题，getInitialData何时调用，如果未登录前调用呢？触发时机是？谢谢

**Comment by TrumanDu** [comment]
@chenbin92 ` const role = getRole()` 报错，×
TypeError: Object(...) is not a function

ice版本：1.6.3

**Comment by cqcmdwym** [comment]
@chenbin92 @imsobear 在思考一个问题，如果一个系统的role也是动态配置的，比如可以新增role1，role2，怎么实现比较好？谢谢
