### ISSUE TITLE
支持 prerender 即构建时渲染

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#3176]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

only ssr, no pre-render

**What is the expected behavior?**

> 需求来自躺平 #孝行

To C业务场景下，我们时常会遇到需要 seo 的场景，但是有些活动使用 ssr 又比较重，体验上可能也没有预渲染那么快。

简单总结一下业务中场景：

1. 相对比较静态、场景简单的页面 - prerender
2. 数据较为静态，并且需要识别用户态 - ssr

实现方案，大概有两种思路：

1. 基于 ssr 场景(以umi举例)：https://web.npm.alibaba-inc.com/package/@umijs/plugin-prerender
2. 基于 spa 场景：https://www.npmjs.com/package/prerender-spa-plugin

这块是否可以看可以考虑一下，哪种场景更适合。

优缺点：

- prerender: 成本低很多，seo 效果比较局限（只能输出 SPA 中单一路由的 html 内容），不考虑动态数据获取
- ssr: 成本高，seo 效果更完善，考虑并支持动态数据获取

prerender 使用场景：

- 静态站点类应用
- 静态营销类页面

**Comment by chenbin92** [comment]
# icejs 支持 prerender 方案

## 什么是 Prerender（预渲染）

在进行打包构建的时候就预先渲染页面。当客户端请求到的 `index.html` 就已经是渲染过的内容。如果页面上面有数据实时更新，需要等到 JavaScript 代码下载完毕才能更新数据。

Prerender 需要预先指定需要渲染的页面（路由）。如果页面数量很多，每个页面都需要进行预渲染成本很高，打包时间很长。因此，在这种情况下，Prerender 不是一个最佳选择。

当页面无数据，或者是只有几个页面小型的SPA应用，可使用 `Prerender`，这是一种通过预览打包的方式构建页面，不需要进行二次渲染，也不会增加服务端的成本。

## 方案

基于 [prerender-spa-plugin](https://www.npmjs.com/package/prerender-spa-plugin) 插件（3.x），在 icejs 中提供 Prerender 的能力。

prerender-spa-plugin 插件对外提供的选项：https://www.npmjs.com/package/prerender-spa-plugin#documentation。

### 方案一

在 build.json 中提供 `prerender` 字段供用户配置, 以在 build-script 支持 prerender。



prerender-spa-plugin 插件的三个字段`staticDir` 、 `ouputDir`、 `indexPath` 在 `build.json` 中不需要配置。具体的值对应如下。

| Option    | Type   | In icejs                            |
| --------- | ------ | ----------------------------------- |
| staticDir | String | 默认与 icejs 中构建产物目录保持一致 |
| ouputDir  | String | 默认与 icejs 中构建产物目录保持一致 |
| indexPath | String | 默认为 staticDir/index.html         |

prerender

- 类型：string[] | object
- 默认值：[]

1. 当传入的参数类型为 string[]，即传入需要配置 prerender 的页面（路由）列表。

   ```json
   // build.json
   {
     "prerender": ["/", "/home"]
   }
   ```

2. 当传入的参数类型为 object，可支持配置更多参数。（必须传入 `routes` 字段，其他字段均为可选。若用户不传入 `routes` 字段，可考虑容错，`routes`为 []。）
   `renderer` 支持 `pupperteer` 和 `jsdom` 。 *https://github.com/Tribex/prerenderer/tree/master/renderers*
   
   ```json
   // build.json
   {
     "prerender": {
         "routes": ["/", "/home"],
         "minify": {
           "collapseBooleanAttributes": true,
           "collapseWhitespace": true,
           "decodeEntities": true,
         },
         "renderer":  ["jsdom", {
             "maxConcurrentRoutes": "4",
             "renderAfterTime": "5000",
         }]
     }
   }
   ```
   

缺点：

- 对于 `ouputDir` 和 `indexPath` ，不能自定义配置，（在 json 文件中无法引入 path 模块进行自定义路径），只能使用默认方案。


### 方案二

开发插件 `build-plugin-prerender`

1. 在 `build.json` 里引入了插件 `build-plugin-prerender`

```json
{
  "plugins": {
    "build-plugin-prerender"
  }
}
```

2. 在应用入口 `src/app.ts` 中配置。（prerender-spa-plugin 中的必须字段`staticDir` 与 icejs 中构建产物目录保持一致。）
`renderer` 支持 `pupperteer` 和 `jsdom` 。 *https://github.com/Tribex/prerenderer/tree/master/renderers*
```js
import { createApp } from 'ice'
const path = require('path')

const appConfig = {
  // other configs...
   prerender: {
      routes: ["/", "/home"],   // 页面（路由） 必填
      minify: {					// html 压缩  可选
        "collapseBooleanAttributes": true,
        "collapseWhitespace": true,
        "decodeEntities": true,
      },
      outputDir: path.join(__dirname, 'prerendered'), // 预渲染的页面输出路径 可选
      indexPath: path.join(__dirname, 'dist', 'index.html'), // 可选
      postProcess (renderedRoute) {  // 可选
       	// configs...
        return renderedRoute
      },
      renderer: ["jsdom", {  // 可使用 jsdom or pupperteer 默认是pupperteer  可选 
       	  // renderer 对应的配置   
          "maxConcurrentRoutes": "4",
          "renderAfterTime": "5000",
      }]
   }
}
createApp(appConfig)
```

优点：

- 对于 `ouputDir` 和 `indexPath` ，可以自定义配置。

### 附我在CRA中使用 prerender-spa-plugin 的 Demo

```js
const PrerenderSPAPlugin = require('prerender-spa-plugin')
const Renderer = PrerenderSPAPlugin.PuppeteerRenderer

// webpack 配置
new PrerenderSPAPlugin({
    routes: ["/", "/about", "/contact"], // 必须参数 可支持多个路由
    staticDir: path.join(__dirname, "build"), // 必须参数 构建产物的路径
    renderer: new Renderer({   // 可选参数 选择不同的renderer: puppeteer & jsdom 
        inject: {
            foo: 'bar'
        },
        headless: true,
        renderAfterDocumentEvent: 'render-event'
    })
})
```

build 目录

```
├── about				// /about 路由
|  └── index.html
├── asset-manifest.json
├── contact				// /contact 路由
|  └── index.html
├── index.html			// / 路由
├── precache-manifest.c9c68600b386a9e76d35e19153737234.js
├── service-worker.js
└── static
   └── js
```

使用  [prerender-spa-plugin](https://www.npmjs.com/package/prerender-spa-plugin)  后的效果
![image-20200508125915384](https://user-images.githubusercontent.com/44047106/81389090-db893b00-914b-11ea-9374-aee4d30c521b.png)

**Comment by chenbin92** [comment]
方案里没有看到 `prerender-spa-plugin` 的优缺点，比如它依赖 puppeteer 会下载 chromium，这个在国内很难下载完成。

**Comment by luhc228** [comment]
## prerender-spa-plugin

link: https://www.npmjs.com/package/prerender-spa-plugin

优点

- 配置简单。正常使用 prerender-spa-plugin 插件，只需要配置 routes & staticDir
- 支持配置 puppeteer 和 jsdom 作为 render

缺点

- 默认 render 为 puppeteer。依赖 puppeteer 会下载 chromium, 在国内下载较慢。在下面附解决办法
- 部分用户部署前端项目时可能会使用 docker，这需要在 `Dockerfile` 文件中做一些额外[配置](https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker)，不过只需在服务器中配置一次即可。

## react-snap 

link: https://www.npmjs.com/package/react-snap

优点

- 官方宣称 zero-configuration，配置上手很快。

![image-20200514114048619](https://user-images.githubusercontent.com/44047106/81891657-934e9a80-95db-11ea-913f-b5af7f1afea2.png)

缺点

- 默认 render 为 puppeteer，会下载chromium，在国内下载比较慢
- 默认所有路由都配置 puppeteer， 不能自由选择哪些路由配置 prerender，哪些路由需要 prerender。当页面数量过多的时候，可能在构建的过程会很慢。
- 部署前端项目使用 docker，同上。

## static-site-generator-webpack-plugin

link: https://www.npmjs.com/package/static-site-generator-webpack-plugin

优点

- 不需要依赖 puppeteer，也就不用下载 chromium

缺点

- 需要额外的配置成本

  需要在 index.js(webpack 打包入口文件) 中配置 render 的 html 模板

![image-20200514105806739](https://user-images.githubusercontent.com/44047106/81891593-65695600-95db-11ea-8edb-7257f865c48b.png)

使用 React-Router 需要额外的配置
  ```js
    var React = require('react')
    var Router = require('react-router')
    var Routes = require('./Routes.jsx')
    module.exports = function render(locals, callback) {
      Router.run(Routes, locals.path, function (Handler) {
      var html = React.renderToStaticMarkup(React.createElement(Handler, locals))
      callback(null, '<!DOCTYPE html>' + html)
    })
  }
  ```
## 依赖的 puppeteer 下载过慢解决方法

通过修改`puppeteer_download_host`的方式，加速下载`chromium`的下载，具体方法如下

```bash
npm config set puppeteer_download_host=https://npm.taobao.org/mirrors
```

总结：

1. 基本上 prerender 插件都会依赖 puppeteer，可以通过配置 `puppeteer_download_host` 为淘宝镜像源解决下载 chromium 过慢的情况。
2. 插件推荐指数： `prerender-spa-plugin` >  `react-snap` > `static-site-generator-webpack-plugin`

**Comment by chenbin92** [comment]
已发布 icejs@1.6.0 支持
