### ISSUE TITLE
GUI工具使用内置模板创建不了项目

### ISSUE THREAD

**Issue by Suntgr** [alibaba/ice#318]
Windows 10 系统，用GUI工具创建不了项目。
![error](https://user-images.githubusercontent.com/15276065/37648177-362f2460-2c69-11e8-8acf-f012e15c1b71.png)
错误提示框，点都点不掉！

**Comment by noyobo** [comment]
尝试使用管理员模式打开 GUI 工具，这样可以吗？

**Comment by Suntgr** [comment]
嗯，管理员模式打开GUI，可以创建项目。不过这有十分钟了，还是99%，我就当他假死，继续等待。然而还是依赖安装失败！
![error-1](https://user-images.githubusercontent.com/15276065/37649057-b4418fa8-2c6b-11e8-8743-4b9c2ce9359c.png)
@noyobo

**Comment by Suntgr** [comment]
我代理开着的，PAC模式 @noyobo

**Comment by noyobo** [comment]
1. 创建失败这个需要看下完整的日志，滚动到最底部可以看到一个 log 文件。
2. 如果安装失败，可以线创建项目，再通过命令行安装依赖，用 GUI 启动项目也是可以的。先这么绕过。

**Comment by Suntgr** [comment]
嗯。多谢。按你说的绕过，现在都ok了。
