### ISSUE TITLE
CompressionWebpackPlugin gzip 不起作用

### ISSUE THREAD

**Issue by RodgerLai** [alibaba/ice#3191]
ice.config.js plugin中加入CompressionWebpackPlugin：
new CompressionWebpackPlugin({ //这里对大于10k的js和css文件进行压缩，其它配置参考官方文档
  filename: '[path].gz[query]',
  algorithm: 'gzip',
  test: new RegExp(
    '\\.(' +
    ['js', 'css'].join('|') +
    ')$'
  ),
  threshold: 10240,
  minRatio: 0.8
})

npm run build 后的结果js css文件并没有生成压缩问题

**Comment by ClarkXia** [comment]
工程上需要以 `webpack-chain` 的方式定义，看具体如何配置的？

**Comment by RodgerLai** [comment]
@ClarkXia C 以下是完整配置：

#ice.config.js
const path = require('path');

module.exports = {
  entry: 'src/index.js',
  publicPath: './',
  plugins: [
    ['ice-plugin-fusion', {
      themePackage: '@icedesign/skin',
    }],
    ['ice-plugin-moment-locales', {
      locales: ['zh-cn'],
    }],
    'ice-plugin-css-assets-local',
    "./build.plugin.js"
  ],
  alias: {
    '@': path.resolve(__dirname, './src/'),
  },
  minify: true,
};


#build.plugin.js

const CompressionWebpackPlugin = require('compression-webpack-plugin')

module.exports = () => new CompressionWebpackPlugin({ //这里对大于10k的js和css文件进行压缩，其它配置参考官方文档
  filename: '[path].gz[query]',
  algorithm: 'gzip',
  test: new RegExp(
    '\\.(' +
    ['js', 'css'].join('|') +
    ')$'
  ),
  threshold: 10240,
  minRatio: 0.8
})

**Comment by ClarkXia** [comment]
@RodgerLai 看实现并没有以 webpack-chain 的方式定义，参考下文档  https://ice.work/docs/guide-0.x/builder/plugin-dev#%E6%96%B0%E5%A2%9E%20webpack%20%E6%8F%92%E4%BB%B6
