### ISSUE TITLE
插件的chain webpack 覆盖了 devServer的https配置

### ISSUE THREAD

**Issue by chenhebing** [alibaba/ice#3194]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
插件的chain webpack 覆盖了 devServer的https配置

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

* icejs version：latest
* Node verson：10
* Platform：macos
* `build.json`：使用的ice-script
* `src/app.(ts|js)`：

**What is the expected behavior?**

期望去除默认false的逻辑

https://github.com/ice-lab/ice-scripts/blob/ice-scripts/2.1.16/packages/ice-scripts/lib/plugins/cliOptions/index.js#L42

![image](https://user-images.githubusercontent.com/12512045/81631881-7da26f00-943b-11ea-8dfc-90c56b7f8503.png)

**Comment by chenbin92** [comment]
@chenhebing  ice-scripts 问题请提交到对应的仓库下：https://github.com/ice-lab/ice-scripts/issues

**Comment by ClarkXia** [comment]
devServer 的 https 被覆盖的问题提供以下两种思路：
1. 工程建议迁移到 [icejs](https://ice.work/docs/guide/migrate)，底层工程 `build-scripts` 已修复这个覆盖问题
2. 新增本地插件的形式去修改 https
