### ISSUE TITLE
📢  2020 Alibaba Summer of Code

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#3197]
Welcome to the open-source world! If you haven't planned how to spend this summer, come to the Alibaba Summer of Code and coding with us! 💻

Alibaba Summer of Code is a global program focused on engaging students directly into open source software development. Under the guidance of the mentor in the Alibaba open source project, students experience software development in the real world. Alibaba Summer of code will begin between May 25th and September 5th. Students can use the summertime to participate in the open-source project and work with the core members of the project.

## What you can get?

On this exclusive developer journey, students will have the opportunity to:

- Participate in the top projects of the International Open Source Foundation;
- Get a scholarship from Alibaba;
- Obtain an open-source contributor certificate;
- Get a fast pass of Alibaba Internship/recruitment;
- Get your code adopted and used by the open-source project!

## Apply Now! 

Step 1. You can click on following project idea links to apply directly
* [Improving build/compilation performance](https://github.com/alibaba/ice/issues/3225)
* [Front-end project quality scoring](https://github.com/alibaba/ice/issues/3227)
* [Building difference analysis](https://github.com/alibaba/ice/issues/3228)
* [Building plugin ecosystem with icejs](https://github.com/alibaba/ice/issues/3226)

Step 2. Full list of Alibaba Summer of Code Projects

- Chinese: https://developer.aliyun.com/topic/summerofcode2020
- English: https://www.alibabacloud.com/campaign/summerofcode2020
![image](https://user-images.githubusercontent.com/3995814/82559849-e360ca80-9ba2-11ea-8d4f-499a33c6bae2.png)

## Timeline⏳

![image](https://user-images.githubusercontent.com/3995814/82559867-ec519c00-9ba2-11ea-9f3e-9a33e5a7beef.png)

## Contact us!

- Email Address: chenbinbin.cb@alibaba-inc.com

**Comment by rpjayasekara** [comment]
Hello, can Sri Lankan undergraduates participate Alibaba summer of code program or is it only open to chineese?

**Comment by chenbin92** [comment]
@rpjayasekara Alibaba Summer of Code is a global program focused on engaging students directly into open source software development, will begin between May 25th and September 5th. welcome you to join us!

**Comment by rpjayasekara** [comment]
Thank you, I am really excited to be a part of this year! Is there any getting started guideline?

**Comment by arteevraina** [comment]
@chenbin92 Are there any guidelines that we as a participant must follow and idea list that we will be working upon this summer?

**Comment by arteevraina** [comment]
@chenbin92 Are there any guidelines that we as a participant must follow and idea list that we will be working upon this summer?

**Comment by anascann** [comment]
Where is the apply now link? will It become active later?

**Comment by chenbin92** [comment]
@rpjayasekara @arteevraina @anascann  Thank you all, we will release the website link and getting started guide on May 25, please wait

**Comment by Zpadger** [comment]
您好，我看到Step1中有4个项目idea链接，请问参与2020ASoC提交的proposal是只需要选择其中一个idea吗？

**Comment by chenbin92** [comment]
> 您好，我看到Step1中有4个项目idea链接，请问参与2020ASoC提交的proposal是只需要选择其中一个idea吗？

是的，可以根据自己的实际情况选择一个适合的，然后在这里提交申请  https://developer.aliyun.com/topic/summerofcode2020

**Comment by anje123** [comment]
Hi @chenbin92  Am Olufemi from Nigeria I found project ice projects really interesting and I am looking forward to work on one of them during the ASoC 2020. please is there a slack or gitter channel  for this project
