### ISSUE TITLE
iceworks开发组件如果引用了alifd/next，在项目中引用了alifd/next主题，会造成主题被覆盖

### ISSUE THREAD

**Issue by inier** [alibaba/ice#3198]
ice的组件开发包，能否提供非cra项目支持。
目前ice打包组件时会把alifd/next组件会的样式打包到style.js中
对于非CRA项目，要使用这类组件，build-plugin-component能否提供个参数，在打包组件时自定义部分组件的样式不打包到style.js中。

提供了个demo
https://codesandbox.io/s/confident-jones-4vhqn
引入组件地址：
新版iceworks组件工程： https://github.com/inier/packages/tree/master/components/Test
旧版iceworks组件工程：https://github.com/inier/packages/tree/master/components/Test2

**Comment by imsobear** [comment]
业务组件开发目前 style.js 是我们总结出来最合理的方案，因为你没考虑到业务组件的相互依赖问题，所以感知可能不深。

如果觉得 style.js 不符合你的诉求，项目里不要引 style.js，引对应组件的 index.scss 即可。
