### ISSUE TITLE
TypeError: Cannot assign to read only property loading of object '#<Object>'

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#3200]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

![image](https://user-images.githubusercontent.com/3995814/81884517-b4f35600-95ca-11ea-9308-84443b8e902c.png)

![image](https://user-images.githubusercontent.com/3995814/81884572-cf2d3400-95ca-11ea-8f24-87d9089a09e9.png)

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

* icejs version：1.2.1
* Node verson：
* Platform：
* `build.json`：
* `src/app.(ts|js)`：

**What is the expected behavior?**

**Comment by imsobear** [comment]
这个问题我们自己重现了吗？ @chenbin92

**Comment by chenbin92** [comment]
可以重现，@alvinhui 在跟进

**Comment by chenbin92** [comment]
已发布 @ice/store@1.4.1 版本修复该问题
