### ISSUE TITLE
关于ice-script 升级到 icejs, 希望icejs能保留像 ice-script 那样简单的构建功能

### ISSUE THREAD

**Issue by gooddaddy** [alibaba/ice#3202]
我希望icejs 保留 只作为一个构建工具的简单功能，开不开起 其他约束，应由用户而定。ice-scripts 比 create-react-app 好的地方是，它把我们常用的很多react web开发的配置都集成在一起了。我们只需要简单修改或者添加一些自己想要的东西就能很好地运行。
   升级的兼容性问题，以及个人不考虑升级到icejs的原因：
   1.由于公司的架构决定了目录的结构，如果icejs要求用户修改目录，那就是破坏了原有项目架构的定义的某些抽象概念。
   2.个人感觉通过目录规范去掉上层代码引编写明确import引用不一定带来方便，因为这隐含的方式会导致我缺少了某些能力，之前我可以通过注释import就能不引用某个模块，现在得改文件夹名称？这种动态的方式，我觉得用户如果需要，完全可以自己通过require.context来实现这样的功能。
 3.ice.config.js 分离到不同的两个配置文件build.json、build.plugin.js，感觉没必要。因为在某些场景下，打包配置是需要额外的控制变量来控制的，build.json和build.plugin.js，都可能引用到这些控制变量，那么这样就需要在两个文件中都写对应的代码比如：
```
let Version = process.env.Version || 'last'
const ENV = process.env.ENV || 'Production' // 环境
```
或者把类似这样的定义再放到另外一个独立的文件中，然后导出来给build.json和build.plugin.js 使用

**Comment by imsobear** [comment]
1. icejs 提供松散模式，使用场景：外部不需要约束的场景 + 内部存量项目的升级，这个认为是需要支持的。
2. build.json + build.plugin.js 合并，原因：分开没必要。这个核心是需要支持 `.js` 结尾的配置文件，暂时不考虑支持，关于为什么用 `.json` 我们内部做过一些讨论，同步出来：

> 1. json 的结构化数据，在一些可视化和配置动态修改的场景下可操作性更好 2. 在工程设计原则上，也尽量希望配置能够足够简单，通过 json 的配置能够覆盖到大多数场景

**Comment by gooddaddy** [comment]
@imsobear 我是否可以把全部东西都写在build.plugin.js 里面，用这样的方式来适配原来的配置？

**Comment by chenbin92** [comment]
> @imsobear 我是否可以把全部东西都写在build.plugin.js 里面，用这样的方式来适配原来的配置？

1. 内部通过 webpack-chain 实现的，所有你可以基于 plugin 修改任何配置来实现你原来的配置。

2. 但这里核心问题在于这样是否有必要，可以看看你原来配置了什么，现在没有覆盖到的 case，现在支持的[配置](https://ice.work/docs/guide/basic/build)。

3. 上面讲到了 JSON 化配置本质是尽可能的简化工程配置，同时支持绝大部分的场景，对于一些非通用的场景使用自定义插件的形式支持，能力也是完备对等的。

**Comment by gooddaddy** [comment]
@chenbin92 
```
  outputDir: `build/${Version}/`,
  publicPath: `/${Version}/`,
```

**Comment by imsobear** [comment]
关于第二个问题单独记录了一个 issue：https://github.com/alibaba/ice/issues/3204 ，这里重点讨论第一个问题。

**Comment by chenbin92** [comment]
@gooddaddy 

> ```
>   outputDir: `build/${Version}/`,
>   publicPath: `/${Version}/`,
> ```
> 
> 主要还是上面说到的问题，某些配置中我需要动态的变量。

工程的问题 #3204 单独 issue 会跟进。

> 1.由于公司的架构决定了目录的结构，如果icejs要求用户修改目录，那就是破坏了原有项目架构的定义的某些抽象概念。
> 2.个人感觉通过目录规范去掉上层代码引编写明确import引用不一定带来方便，因为这隐含的方式会导致我缺少了某些能力，之前我可以通过注释import就能不引用某个模块，现在得改文件夹名称？这种动态的方式，我觉得用户如果需要，完全可以自己通过require.context来实现这样的功能。

这也是我们做 icejs 的背景之一，希望通过 icejs 将我们在日常开发中的最佳实践进行沉淀，并且是强约束的，包括你这里描述的目录，import 引用问题，以及状态管理，数据请求等等功能。在淘系有很多不同的团队有开发中后台的项目，但是如果这些团队没有一个统一的强约束和开发的规范，那么沟通和跨团队协作成本，以及长期的维护成本是非常高的。所以我们希望通过 icejs 强约束和提供标准化的 React 应用开发模式。旨在收敛技术栈、屏蔽底层差异和统一开发体验，从而降低开发和维护成本。

那么回到你这里的问题，因为 icejs 本身的一些约定和你们公司的架构有差异，不希望有这些强约束的能力，希望是更自由松散的，其实 icejs 也提供了比如关闭内置状态管理的能力，只需要配置 `store: false` 即可，但这个不是我们推荐的。另外一方面 icejs 有提供了 `运行时` 和 `工程扩展` 的插件机制，你可以基于这些能力去定制符合公司的架构设计。你也可以梳理下具体的差异点是什么，是否 icejs 可以更合理的开放这些能力，可以讨论下。

**Comment by gooddaddy** [comment]
@chenbin92 规范是好，但是有时候只是不想使用你们定下来的规范（并非说你们定的规范不合理，这出于很多历史代码或者自身架构的原因）。我们没看到相关文档描述： 如果关闭规范目录的配置。我希望有相关的说明，能告诉我如何使用icejs 实现 ice-script那样纯粹（只是个打包工具，不加运行时）的功能。如果 icejs 强约束是不可关闭的，我相信之前使用飞冰构建的人都难以接受这一点，因为这可以说是不兼容。

**Comment by chenbin92** [comment]
@gooddaddy 理解你的诉求了，我们评估了下这个在下个版本可以支持，「icejs 运行能力是可选的，在某些场景只用 icejs 的工程能力」

**Comment by chenbin92** [comment]
## 方案
>目标： 单独使用 icejs 的工程方案

* 不限定入口文件（app.ts、index.ts）
* 不规范目录结构（pages、models、etc）
* 不注入任何运行时能力（store、request、logger）
* 不生成 `.ice` 目录

```ts
// 提供 disableRuntime: false 关闭运行时能力
const getBuiltInPlugins = (userConfig) => {
  if (userConfig.disableRuntime === false) {
    return ['build-plugin-react-app'];
  };
}
```

**Comment by chenbin92** [comment]
@gooddaddy 已支持支持通过 `--disableRuntime` 关闭运行的能力，即只使用工程的能力
