### ISSUE TITLE
工程配置文件能否自持 js 类型

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#3204]
## 背景

目前的配置文件即 build.json，仅支持 json 格式，原因：

1. json 的结构化数据，在一些可视化和配置动态修改的场景下可操作性更好
2. 在工程设计原则上，也尽量希望配置能够足够简单，通过 json 的配置能够覆盖到大多数场景

但是这样也有一些缺陷，比如无法支持动态配置能力，之前用 `ice.config.js` 的写法：

```js
module.exports = {
  define: {
    env: process.env.xxx, // 可以使用变量
  },
  plugins: [
    ["build-plugin-fusion", {
      themePackage: '', // 可以使用变量
    }]
  ]
}
```

## 方案

这里整理两个方案，大家可以针对性讨论下。

### 1. 通过本地插件 build.plugin.js + 扩展 API 支持

build.json:

```json
{
  "plugins": [
    "./build.plugin.js"
  ]
}
```

build.plugin.js:

```js
module.exports = (api) => {
  // 新增 API registerPlugin
  api.registerPlugin('build-plugin-fusion', {
    themePackage: 'xxx'
  });

  // 已有 API modifyUserConfig
  api.modifyUserConfig('define', {
    env: process.env.xxx
  });
}
```

- 缺点：需要两个配置文件
- 优点：不打破原先的设计

### 2. 支持 js 类型的配置文件

默认依然是 `build.json`，需要通过参数指定，在 npm scripts 中指定配置文件：

```json
{
  "scripts": {
    "start": "icejs start --config build.config.js",
    "build": "icejs build --config build.config.js"
  }
}
```

build.config.js 的内容：

```js
module.exports = {
  define: {
    env: process.env.xxx
  },
  plugins: [
    ['build-plugin-fusion', {
      themePackage: xxx
    }],
    (api) => {
      api.onGetWebpackConfig((config) => {
        config.xxx
      });
    }
  ]
}
```

- 优点：具备动态能力、只需要一个配置文件
- 缺点：开发者的配置文件不可控（当然原本的 build.plugin.js 也不可控）

**Comment by gooddaddy** [comment]
@imsobear 
1. 通过本地插件 build.plugin.js + 扩展 API 支持
假如是这种，那么build.plugin.js名字也得改一下，因为需要实现动态配置都需要在这个文件中进行，但是我修改的不一定是plugin，所以名称不能叫build.plugin.js，会误导别人

**Comment by imsobear** [comment]
修改 userConfig 本身也是 plugin 的一种能力，这个我感觉倒还好 @gooddaddy

**Comment by tao1991123** [comment]
## 奥卡姆剃刀定律: 如无必要，勿增实体


插件修改其他插件参数的能力  以后感觉就完全不可控了  有点略恐怖
特别是 以后用插件的时候 要小心翼翼的。说不定我配的好好的东西被别的插件改了我都不知道 。排查起问题来,困难重重

第二种 基本上是目前通用的解决方案    无论是 umijs 还是cra 也都是使用的 js文件作为配置文件。

**Comment by gooddaddy** [comment]
我也赞同第二种做法

**Comment by ClarkXia** [comment]
配置文件将通过指定配置文件的方式拓展支持 JS 配置，插件写法新增插件函数写法：

```js
module.exports = {
  plugins: [
    'build-plugin-react-app',
    (api) => {
      api.onGetWebpackConfig(() => {});
    },
  ]
}
```

计划下周的版本支持

**Comment by chenbin92** [comment]
build-scripts 已支持，补充文档

**Comment by chenbin92** [comment]
已支持，详见文档https://ice.work/docs/guide/basic/build#%E5%B7%A5%E7%A8%8B%E6%9E%84%E5%BB%BA%E9%85%8D%E7%BD%AE
