### ISSUE TITLE
IDE support not working properly

### ISSUE THREAD

**Issue by tushar22-tg** [alibaba/ice#3207]
I wanted to know basic functioning of The playground utilized because 

some times `import ReactDOM from 'react-dom';` appears

![Screenshot 2020-05-14 at 11 53 15 PM](https://user-images.githubusercontent.com/52567960/81971035-16a0d800-963e-11ea-989d-a1e61eab98c6.png)

whereas in this example it doesn't work well when i import `ReactDOM` the site crashes

![Screenshot 2020-05-14 at 11 52 50 PM](https://user-images.githubusercontent.com/52567960/81970996-0688f880-963e-11ea-93d3-5236aa383d0c.png)

**I am highly interested in working over this issue**

**Comment by chenbin92** [comment]
@tushar22-tg 
It is a code debugging environment similar to [CodePen](https://codepen.io/srebalaji/pen/MVbWdB?__cf_chl_jschl_tk__=f5fc7682786c709b76eadf161c88c10ab1508f16-1589765734-0-AdxFJnpMNdfpjis7ayQrN0BlXtlgUaUPQkHVIFOrvft6UO46QKYXyeMXWV_YOk_qlVFbTSsxiQPLN4WUgV7XgGkgUkR6CWFScpFnqYrDzMb0k5erNRKElReCugTYPWspIRO4_f5tTU7R8CktPJZBOVirLefxvC3CQnhGLWqHEBab0nEDxeRIek8d_KJvi6RLwkZ9Qa1bVLK-puqJYapeJAQerqdkcnS7PIiFYEQDM2xdQQd8gdizbvsUUwfp9whdtHbrN-V_W_7NbenE85dQoZXygdAU31Vu0TWDQboJ7uJEfOBe-Bq_K7LQfZjN6nXWEUM5xNs_iJWPzmmBB6jSYUI8e2p57344dHCsQk4gmlhG) which has built-in React dependencies, so there is no need to `import ReactDOM from 'react-dom'`.
