### ISSUE TITLE
是否考虑过将react-router升级到4版本以上呢？

### ISSUE THREAD

**Issue by nick-ma** [alibaba/ice#321]
由于react-router的4版本以上做了breaking changes，导致无法升级了。
而且，官方也不建议在后面继续使用hash的方式。
请问ICE这边有计划升级到react-router 4以上的版本么？

**Comment by yujiangshui** [comment]
在计划中，将在后续的版本中升级

**Comment by yujiangshui** [comment]
cc @wssgcg1213

**Comment by nick-ma** [comment]
@yujiangshui  谢谢回答，如果官方有计划，我就不自己折腾了。 :-D

**Comment by zerofront** [comment]
感觉升级到router4是比较重要的，很有可能挺多开发者看到模板都是router3就放弃飞冰了。。。。。毕竟router3到4变化挺大的。

**Comment by nick-ma** [comment]
确实要快一点实现了。现在程序里还只能用hashHistory.push来做页面的跳转，但这显然不是官方推荐的了。后面再改也是个麻烦事。

**Comment by mike623** [comment]
加1，這是我不推薦給朋友及不使用的最重要原因

**Comment by yujiangshui** [comment]
官方模板已经升级，可以参照迁移文档 https://github.com/alibaba/ice/blob/master/docs/others/migration-to-react-router-v4.md
详细发布日志：https://zhuanlan.zhihu.com/p/36437999

**Comment by nick-ma** [comment]
Great job you guys have done!
