### ISSUE TITLE
在 icejs 中使用 webpack@5

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#3217]

**Comment by chenbin92** [comment]
补充文档

**Comment by chenbin92** [comment]
已支持，详见文档 https://ice.work/docs/guide/develop/plugin-list#build-plugin-webpack5%EF%BC%88%E5%AE%9E%E9%AA%8C%E6%80%A7%EF%BC%89

**Comment by imsobear** [comment]
webpack5 已发布，正式版本是否直接支持掉？

**Comment by imsobear** [comment]
https://github.com/alibaba/ice/issues/4171
