### ISSUE TITLE
ErrorBoundaryFallback错误边界备用UI无效的问题

### ISSUE THREAD

**Issue by raohuiyong** [alibaba/ice#3218]
通过官网提供的Fusion Design Pro - TS模板进行测试icejs功能，在使用错误边界的时候发现ErrorBoundaryFallback设置无效的问题[演示地址](https://codesandbox.io/s/exmaple-basic-spa-fe1gb?file=/src/app.tsx)

## 复现方式
1. 在/pages/Dashboard页面执行了一个错误的方法
2. 在appConfig设置ErrorBoundaryFallback无法生效，如果不设置那么会显示默认UI

**Comment by chenbin92** [comment]
@raohuiyong  文档示例的类型不对，改成 `ErrorBoundaryFallback: () => <div>渲染错误</div>` 即可，我这边更新下文档

![image](https://user-images.githubusercontent.com/3995814/82397548-43604f80-9a83-11ea-8938-b29270050a8a.png)
