### ISSUE TITLE
[ASoC2020]  Improving build/compilation performance

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#3225]
## 项目名称/Project Title

提高构建/编译性能

Improving build/compilation performance

## 项目描述/Project Description

目前 icejs 基于 webpack 作为工程构建工具，但在构建体验上仍然存在很大程度的提升空间，主要包括构建速度和构建产物的大小两部分，基于此我们希望进一步的对工程体验进行优化，实现编译提速，更小的构建产物等，如可通过 DllPlugin、webpack5/Module Federation 等技术方案进行落地。

At present, icejs is based on webpack as an engineering construction tool, but there is still a lot of room for improvement in the construction experience, mainly including the construction speed and the size of the construction product. Based on this, we hope to further optimize the engineering experience to achieve faster compilation and smaller build products, etc, such as DllPlugin, webpack5 / Module Federation and other technical solutions for landing.

## 预期成果/Expected Outcomes

• 针对特定场景构建速度提升 50%
• 支持构建 esm 的方式

• 50% faster build speed for specific scenarios
• Support the way to build the esm

## 需要的技能/Required Skills

* webpack
* TypeScript

**Comment by zhmushan** [comment]
我想要做这个, 想问下申请书上的 Part 2 是直接复制这里的描述吗?

**Comment by chenbin92** [comment]
> 我想要做这个, 想问下申请书上的 Part 2 是直接复制这里的描述吗?

不是，这里只是需求，你需要根据需求提交你的提案，然后在这里提交申请 https://developer.aliyun.com/topic/summerofcode2020

**Comment by aryamanpuri** [comment]
Hi @chenbin92 
I am a student from India looking forward to contributing to this idea under Alibaba's summer of code.
Can you help me get started?
Is there any communication medium to discuss the ideas which students can access?

**Comment by aryamanpuri** [comment]
Improving the build/compilation performance can be done by making the webpack version to the latest. Making the total size of the compilation smaller to increase build performance. Removing unused code.
Your views @chenbin92
