### ISSUE TITLE
[ASoC2020] Building plugin ecosystem with icejs

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#3226]
## 项目名称/Project Title

构建 icejs 插件生态

Build plugin ecosystem with icejs

## 项目描述/Project Description

icejs 框架提供了强大的插件机制，除了通过插件定制工程能力以外，还为插件扩展了运行时定制的能力，这让插件拥有更多的想象空间。基于此，我们希望为 icejs 建设一个完整的插件生态，覆盖应用开发的绝大部分场景。开发者在这个插件生态可以快速找到需要的插件，以及开发贡献自己的插件到插件生态。

The icejs framework provides a powerful plugin mechanism. In addition to the ability to customize the project through the plugin, it also extends the ability of the plugin to customize at runtime, which gives the plugin more imagination. Based on this, we hope to build a complete plugin ecosystem for icejs, covering most of the application development scenarios. Developers can quickly find the required plugins in this plugin ecology, and develop and contribute their own plugins to the plugin ecology.

## 预期成果/Expected Outcomes

- 规范和简化插件的开发流程（包括插件模板生成以及目录组织、类型导出、module/webpack/jest 的编写规范）
- 插件生态建设，结合现有插件列表、社区生态、以及开发者诉求编写至少 3 个以上插件

- Standardize and simplify the development process of plugins (including plugin template generation and directory organization, type export, module / webpack / jest writing specifications)
- Build plugin ecology and rite at least 3 plugins based on the list of existing plugins, community ecology, and developers' demands

## 需要的技能/Required Skills

- React
- Webpack
- Typescript
- Jest

**Comment by LanceZhu** [comment]
Hi, this project looks interesting. I would like to work on this in this summer. :hand:

**Comment by chenbin92** [comment]
> Hi, this project looks interesting. I would like to work on this in this summer. ✋

@LanceZhu  Great, You can click on following project idea links to apply directly

- Chinese: https://developer.aliyun.com/topic/summerofcode2020
- English: https://www.alibabacloud.com/campaign/summerofcode2020
