### ISSUE TITLE
[ASoC2020] Front-end Project Quality Scoring

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#3227]
## 项目名称/Project Title

前端项目质量评分

Front-end Project Quality Scoring

## 项目描述/Project Description

前端项目的数量一路飙升，开发者的能力参差不齐，前端应用的质量需得到保障且上升一个台阶。为了达到此目标，需提供针对前端应用的代码质量有评分标准和改进能力。

Now, the number of front-end projects has soared all the time, the capabilities of developers are uneven, and the quality of front-end applications needs to be guaranteed and rise to a new level. In order to achieve this goal, it is necessary to provide scoring standards and improvement capabilities for front-end application code quality.

## 预期成果/Expected Outcomes

- 产出前端项目质量评分标准
- 产出 VSCode 插件，扫描项目代码并给出质量分和意见
- Develop front-end project quality scoring standards.
- Write a VSCode plugin, which can scan the project code and give quality scores and suggestions.

## 需要的技能/Required Skills

- AST
- Node.js

**Comment by hastagAB** [comment]
Hi @chenbin92 , This issue seems interesting to me, I would like to work on this feature during ASoC 2020.
I've a question that I would like to ask.
The Quality Scoring Standards can be set taking references from the maintainer's code or the code that is merged. But can you please explain what opinions means here? Is it the pre-defined suggestions or the references?

**Comment by luhc228** [comment]
> Hi @chenbin92 , This issue seems interesting to me, I would like to work on this feature during ASoC 2020.
> I've a question that I would like to ask.
> The Quality Scoring Standards can be set taking references from the maintainer's code or the code that is merged. But can you please explain what opinions means here? Is it the pre-defined suggestions or the references?

Thank you, hastagAB. Your understanding is correct.

**Comment by alvinhui** [comment]
> Hi @chenbin92 , This issue seems interesting to me, I would like to work on this feature during ASoC 2020.
> I've a question that I would like to ask.
> The Quality Scoring Standards can be set taking references from the maintainer's code or the code that is merged. But can you please explain what opinions means here? Is it the pre-defined suggestions or the references?

This is a strategic issue. I suggest that we use a predefined scoring model first.

**Comment by alvinhui** [comment]
I think the quality score will be of great significance for front-end projects. In Alibaba, we have developers from various backgrounds, Some of them are not professional front-end developers. We need to make sure that the code they write is accurate and can stand the test of time. Welcome interested students to explore this direction together.

**Comment by rpjayasekara** [comment]
I found this project interesting and it would be a great experience if I could work on this issue during ASoC 2020. I have a question regarding the project.
When it comes to measuring the quality score, first there has to be some well-defined quality metrics and benchmarks, Are there any well-defined quality metrics already or defining quality metrics and benchmarks also included to the project scope?

**Comment by anje123** [comment]
Hi, @chenbin92 Am Olufemi from Nigeria I found this project interesting and I am looking forward to work on it during the ASoC 2020, is there any communication medium to discuss the idea which i can access?

**Comment by chenbin92** [comment]
> Hi, @chenbin92 Am Olufemi from Nigeria I found this project interesting and I am looking forward to work on it during the ASoC 2020, is there any communication medium to discuss the idea which i can access?

@anje123  Any questions can be discussed in this issue

**Comment by alvinhui** [comment]
> I found this project interesting and it would be a great experience if I could work on this issue during ASoC 2020. I have a question regarding the project.
> When it comes to measuring the quality score, first there has to be some well-defined quality metrics and benchmarks, Are there any well-defined quality metrics already or defining quality metrics and benchmarks also included to the project scope?

We are still having some internal discussions, but I think this should be included in the application proposal.

**Comment by anje123** [comment]
Are we going to be extending eslint, tslint with new Custom Rules or scoring standards, or are we building a new linter, or am I getting it wrong?

**Comment by anje123** [comment]
@chenbin92 I noticed ice.js uses Eslint ,@typescript-eslint/parser , is it ok if custom rules or scoring standards are built on eslint as plugins, then later converted to vscode plugin
