### ISSUE TITLE
[ASoC2020] Building difference analysis with icejs

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#3228]
## 项目名称/Project Title

构建差异分析

Buiding Difference Analysis with icejs

## 项目描述/Project Description

目前项目打包后对比上一次构建发生的变化无法感知，希望工程上能够能力来显示对比构建差异，比如构建的资产大小、依赖变化等等。

After the project is packaged, the changes from the previous build are not perceptible now. we hope that the project will be able to show the differences between the builds, for example, build asset size, dependency changes, etc.

## 预期成果/Expected Outcomes

- 产出插件，能力上能够分析构建打包差异并友好展示
- 提供差异对比的能力，包括 bundleSize、打包模块、模块版本的变化、优化提示等
- 提供接口支持远程服务接入存储构建数据
- Write plugins which can analyze the build differences and display friendly.
- Provide the ability to compare differences, including the bundle size, packaging modules, module version changes, optimization tips, etc.
- Provide interface to support remote service access to store construction data.

## 需要的技能/Required Skills
- webpack
- typescript

**Comment by Kaushl2208** [comment]
Hey @chenbin92 , This project seems quite interesting and challenging and I would love to work on it this summer. This project will take proper planning and discussions so, Is there any community platform/mailing list where we can discuss it further?

**Comment by hastagAB** [comment]
> Hey @chenbin92 , This project seems quite interesting and challenging and I would love to work on it this summer. This project will take proper planning and discussions so, Is there any community platform/mailing list where we can discuss it further?

Hi @Kaushl2208 , Please have a look at https://github.com/alibaba/ice#community

**Comment by chenbin92** [comment]
@Kaushl2208 @hastagAB  can discuss it in this issue, we will release the website link and getting started guide on May 25
