### ISSUE TITLE
iceworks IDE编译几次就很卡的问题啥时候能解决下

### ISSUE THREAD

**Issue by chenjinli** [alibaba/ice#3229]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

* icejs version：
* Node verson：
* Platform：
* `build.json`：
* `src/app.(ts|js)`：

**What is the expected behavior?**

**Comment by chenbin92** [comment]
@alvinhui iceworks 相关处理一下。

**Comment by alvinhui** [comment]
iceworks 未来以 vscode 套件的释放，IDE 相关的问题需要 hold 一下。
