### ISSUE TITLE
@icedesign 不开源吗？没有找到源码在github上的repo

### ISSUE THREAD

**Issue by CrisLi** [alibaba/ice#323]
用npm下来后看到的代码，有一个_components文件夹，里面的样式和官网文档上不一致。至少默认的主题颜色是橙色(#FFAC75)的，不是蓝色。

**Comment by wssgcg1213** [comment]
组件的开源计划进行中, 预计年中之后可以开源  

如果单独使用组件, 需要使用 `ice-skin-loader` 加载 `@icedesign/skin`, 具体可以参考 https://github.com/alibaba/ice/blob/master/tools/ice-scripts/lib/config/getRules.js#L51

**Comment by CrisLi** [comment]
@wssgcg1213 
多谢 了解了
