### ISSUE TITLE
vim 临时文件导致ice编译出错

### ISSUE THREAD

**Issue by lihongxun945** [alibaba/ice#3241]
**Do you want to request a *feature* or report a *bug*?**
报告bug

**What is the current behavior?**
VIM临时文件导致ice编译出了语法错误的代码

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
* icejs version：1.2.1
* Node verson：10.10.0
* Platform：Mac 10.14.6
* `build.json`：
```json
{
  "plugins": [
    [
      "build-plugin-fusion",
      {
        "themePackage": "@alifd/theme-design-pro"
      }
    ],
    "@ali/build-plugin-faas",
    [
      "build-plugin-moment-locales",
      {
        "locales": ["zh-cn"]
      }
    ],
    [
      "build-plugin-antd",
      {
        "themeConfig": {
          "primary-color": "#1DA57A"
        }
      }
    ],
    "@ali/build-plugin-ice-def",
    "@ali/build-plugin-midway-hooks",
    "./build.plugin.js"
  ]
}
```
* `src/app.(ts|js)`：略

文件目录结构如下：
![image](https://user-images.githubusercontent.com/1144765/83002795-0aeee180-a040-11ea-8c43-7dbea787e755.png)

编辑`global.ts` 会生成一个 临时文件 `.global.ts.swp`
![image](https://user-images.githubusercontent.com/1144765/83002842-1c37ee00-a040-11ea-9eca-73feecf5c001.png)

ice 由于编译了vim临时文件，会生成如下错误代码
![image](https://user-images.githubusercontent.com/1144765/83002904-2c4fcd80-a040-11ea-9072-9b47a6717c92.png)

**What is the expected behavior?**
忽略vim临时文件，一般文件名都是是 `.*.sw*`

**Comment by chenbin92** [comment]
已发布 icejs@1.5.0 版本
