### ISSUE TITLE
自动刷新功能失效

### ISSUE THREAD

**Issue by wangxiaojuan** [alibaba/ice#3244]
用官方推荐的代理工具xswitch开启代理，就会导致自动刷新失效
报错截图：
![image](https://user-images.githubusercontent.com/1762334/83107736-58775700-a0f1-11ea-838e-678008159fba.png)
代理工具截图:
![image](https://user-images.githubusercontent.com/1762334/83107793-6e851780-a0f1-11ea-88e1-6f79c821fd51.png)

**Comment by chenbin92** [comment]
cc @ClarkXia  无法重现
