### ISSUE TITLE
ice.work 网站 文档页面样式问题

### ISSUE THREAD

**Issue by LanceZhu** [alibaba/ice#3246]
该页面 [ice.work - 文档 - 基础指南 - 框架 API](https://ice.work/docs/guide/basic/api#IRootState) 右侧目录过长，超过视图可见范围，无法上下滑动。缩放页面后可以看全。

**基本信息：**
浏览器：Chrome
分辨率：1080p
**具体效果见下图：**
![bug](https://user-images.githubusercontent.com/26158863/83126786-e829ff00-a10b-11ea-8bc8-ac9081e94d27.jpg)

**Comment by chenbin92** [comment]
感谢反馈，我们这边处理下

**Comment by chenbin92** [comment]
已与 @luhc228 沟通
