### ISSUE TITLE
details about GUI tools

### ISSUE THREAD

**Issue by anymost** [alibaba/ice#325]
thanks for your contributions。I want to know how to develop the ice GUI tools ,as I see the Github source code doesn't contain the source code about GUI tools. I try to implement the GUI tools with election while found it difficultly.

**Comment by yujiangshui** [comment]
Iceworks 的开源流程在计划中，只是时间周期可能会有点长。涉及到代码脱敏、开源审批、集团敏感代码扫描、安全等等。可以关注知乎专栏或者加入我们的钉钉群，最新消息会随时公布。
