### ISSUE TITLE
新增页面需要重新npm start (JS)

### ISSUE THREAD

**Issue by dyyliao123** [alibaba/ice#3251]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
新增完页面需要重新npm start 才会生效。
If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
https://user-images.githubusercontent.com/25788204/83380890-be295300-a411-11ea-8282-ba5ab7b905d3.png
这个页面有的
https://user-images.githubusercontent.com/25788204/83380904-c8e3e800-a411-11ea-90b6-bc3c67815586.png
* icejs version："1.0.0"
* Node verson："10.16.0"
* Platform：
* `build.json`：
* `src/app.(ts|js)`：js

**What is the expected behavior?**
希望新增完页面不需要重新npm start

**Comment by chenbin92** [comment]
@dyyliao123 可以录个 GIF 吗

**Comment by dyyliao123** [comment]
![demo](https://user-images.githubusercontent.com/25788204/83469892-6e02cd00-a4b3-11ea-811d-7911c2991f5b.gif)

**Comment by chenbin92** [comment]
已发布 icejs@1.6.3 修复

**Comment by dyyliao123** [comment]
ok，感谢
