### ISSUE TITLE
css加载顺序告警怎么处理

### ISSUE THREAD

**Issue by mopsky** [alibaba/ice#3258]
![image](https://user-images.githubusercontent.com/18085384/83607397-bef6ec00-a5ad-11ea-8115-974e0783a6f7.png)

WARN (web) chunk vendor [mini-css-extract-plugin]
WARN Conflicting order. Following module has been added:
WARN  * css ./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/postcss-loader/src??ref--6-2!./node_modules/sass-loader/dist/cjs.js??ref--6-3!./node_modules/ice-skin-loader/lib??ref--6-4!./node_modules/@alifd/next/es/responsive-grid/main.scss
WARN despite it was not able to fulfill desired ordering with these modules:
WARN  * css ./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/postcss-loader/src??ref--6-2!./node_modules/sass-loader/dist/cjs.js??ref--6-3!./node_modules/ice-skin-loader/lib??ref--6-4!./node_modules/@alifd/next/es/button/main.scss
WARN    - couldn't fulfill desired order of chunk group(s) user
WARN    - while fulfilling desired order of chunk group(s) buyer, seller

vscode已经用sort-import插件格式化过了，还是很多，这个要怎么处理，或者如何屏蔽，在哪里配置ignoreOrder: true?

**Comment by ClarkXia** [comment]
一般为组件先后引入顺序引起，如果需要关闭提示，可以通过自定义插件的方式处理

```js
module.exports = ({ onGetWebpackConfig }) => {
  onGetWebpackConfig(config => {
    // ignore mini-css-extract-plugin warning
    config.plugin('MiniCssExtractPlugin').tap(args => [
      Object.assign(...args, {
        ignoreOrder: true,
      }),
    ]);
  });
};
```
