### ISSUE TITLE
build-plugin-ice-auth 插件pageConfig.auth问题

### ISSUE THREAD

**Issue by mopsky** [alibaba/ice#3260]
![image](https://user-images.githubusercontent.com/18085384/83738789-5419e380-a687-11ea-8dab-35fe6e6e22cd.png)
这边写页面的pageConfig.auth不配置的情况下，应该所有人都可以访问的，但是实际上好像不行，我去看了下源代码：

![image](https://user-images.githubusercontent.com/18085384/83738871-6e53c180-a687-11ea-86e2-b045183267d8.png)
确定这样可以吗，还是我理解或者使用有问题？

**Comment by chenbin92** [comment]
@mopsky  已修复

**Comment by mopsky** [comment]
OK，3KS

**Comment by chenbin92** [comment]
@mopsky 已发布 icejs@1.5.0 版本
