### ISSUE TITLE
使用ice store管理页面状态 做列表的增删操作， 当删除 列表中某行数据 时出现 死循环。

### ISSUE THREAD

**Issue by guozeliang** [alibaba/ice#3261]
- 使用ice store 页面级状态管理 删除操作 Table 的dataSource列表数据时
- 出现死循环 调用model.ts中 effects--》remove方法。
demo代码地址：
[https://github.com/guozeliang/ice-test](url)

**Comment by luhc228** [comment]
```js
import { IRootDispatch } from 'ice';

export default {
  state: result,
  effects: (dispatch: IRootDispatch) => ({
    async add(item) {
      dispatch.default.update([item]);
    },
    async remove(index) {
      dispatch.default.remove(index);
    },
  }),
  reducers: {
    update(prevState, payload) {
      return [...prevState, ...payload];
    },
    remove(prevState, index) {
    //   debugger;
      console.log('remove');
      const tmpSource = [...prevState];
      tmpSource.splice(index, 1);
      return result;
    },
  },
}
```

Hello，上面是你写的代码，因为你在 effects 和 reducers 中都写了 相同的方法名 --> *remove*。icestore 处理同名方法的逻辑是先执行 reducers 中的 *remove*，再执行 effects 中的 *remove*。

你上面代码的执行顺序是这样的
1. reducers 中的 remove 执行
2. effects 中的 remove 执行
3. 遇到了 dispatcher.default.remove 重复上面两个步骤...
所以你会遇到死循环的现象

**Comment by luhc228** [comment]
https://github.com/ice-lab/icestore/blob/master/docs/api.zh-CN.md#%E5%90%8C%E5%90%8D%E5%A4%84%E7%90%86
