### ISSUE TITLE
eslint 规则优化

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#3266]
- 优化 `@ice/spec` 规则 https://github.com/ice-lab/spec/issues/12
- 模板里的 eslint 参数改为 true

**Comment by chenbin92** [comment]
结论：作为框架中台的插件沉淀，包含 rax 和 ice 的两部分。

**Comment by chenbin92** [comment]
进度同步：eslint 规则 @chenhebing 基于 @ice/spec 提供完整的 RFC 进行讨论 https://github.com/ice-lab/spec/issues/created_by/chenhebing
