### ISSUE TITLE
IE 无法使用

### ISSUE THREAD

**Issue by ihwf** [alibaba/ice#3268]
复现步骤:
1. 使用` yarn create ice <projectName>`创建项目,
2.`npm i`
3.`npm start`
用IE打开报语法错误, 定位报错行为箭头函数, 无论怎么修改 build.json内的target都一样

使用icework选择用模板创建也一样在IE下无法使用

**Comment by imsobear** [comment]
@luhc228 看下这个问题：

- 给出 `npm start` 在 IE 下可用的方案（估计要配置一堆 compileDependencies）
- 明确 `npm run build` 产物默认支持的 IE 版本
- 上面两点汇总到文档里

**Comment by ihwf** [comment]
即使在build.json内配置target为支持IE11, `npm run build` 后也无法在IE下使用, target配置似乎无用?

**Comment by imsobear** [comment]
start 模式不可用是符合预期的，build IE11 应该是没问题的，出问题的是 IE 多少，具体问题是什么？ @ihwf

**Comment by ihwf** [comment]
start 模式下报的语法错误, 定位为箭头函数, build 后的报错一样, 依然是箭头函数, 并没有进行转换

- start 模式下的报错位置
![image](https://user-images.githubusercontent.com/17941662/84222580-85bcff80-ab0a-11ea-8b35-52183ada7f95.png)

- build 后的报错位置
![image](https://user-images.githubusercontent.com/17941662/84222730-e0eef200-ab0a-11ea-9b43-a67ec2bfcac0.png)
build 后箭头函数依然是箭头函数

整个项目是通过`yarn create ice <projectName>`选择模版创建的, 还没有进行任何修改, 我提交到了这里, [iceDemo]("https://github.com/ihwf/iceDemo.git")
@imsobear

**Comment by imsobear** [comment]
@ihwf IE 版本是？

**Comment by ihwf** [comment]
IE11的默认设置,
![image](https://user-images.githubusercontent.com/17941662/84225379-8dcc6d80-ab11-11ea-9bc9-2d3915ec0a2a.png)

**Comment by luhc228** [comment]
测试浏览器： IE 11

在 build.json 设置 compileDependencies 增加如下内容：

```json
{

  "compileDependencies": [
    "ansi-regex",
    "ansi-styles",
    "chalk",
    "query-string",
    "react-dev-utils",
    "split-on-first",
    "strict-uri-encode",
    "strip-ansi"
  ]
}
```

在 dev 和 prod 环境下测试过，没有问题
@ihwf

**Comment by ihwf** [comment]
> 测试浏览器： IE 11
> 
> 在 build.json 设置 compileDependencies 增加如下内容：
> 
> ```json
> {
> 
>   "compileDependencies": [
>     "ansi-regex",
>     "ansi-styles",
>     "chalk",
>     "query-string",
>     "react-dev-utils",
>     "split-on-first",
>     "strict-uri-encode",
>     "strip-ansi"
>   ]
> }
> ```
> 
> 在 dev 和 prod 环境下测试过，没有问题
> @ihwf


换了另外两个错误, 截图如下
![image](https://user-images.githubusercontent.com/17941662/85358332-00900c80-b546-11ea-8875-a34980e26e0d.png)
1. 似乎 `babel` 没有转换 `Promise`, 
2. 定位"引发异常但未捕获"的位置, 为`internal-state.js`文件内报的, 截图如下
![image](https://user-images.githubusercontent.com/17941662/85358716-0803e580-b547-11ea-94d8-59a45bb2b4c4.png)

**Comment by luhc228** [comment]
1. 看一下 `Promise 未定义` 的错误是哪个依赖包里的错误？
2. `internal-state.js` 是哪个依赖包的？
@ihwf

**Comment by ihwf** [comment]
感觉是babel编译没有生效，因为我根据文档`"compileDependencies":[""] 等同于不忽略 node_modules`，设置了，但是问题依旧

**Comment by luhc228** [comment]
> compileDependencies

可以提供一下你的 demo 吗? 我这里没法复现。

**Comment by luhc228** [comment]
> 感觉是babel编译没有生效，因为我根据文档`"compileDependencies":[""] 等同于不忽略 node_modules`，设置了，但是问题依旧

可以提供一下你的 demo 吗? 我这里没法复现。

**Comment by ihwf** [comment]
[iceDemo](https://github.com/ihwf/iceDemo.git) @luhc228

**Comment by luhc228** [comment]
> [iceDemo](https://github.com/ihwf/iceDemo.git) @luhc228

https://github.com/alibaba/ice/pull/3305

**Comment by chenbin92** [comment]
已发布 ice.js@1.6.1 版本修复
