### ISSUE TITLE
子工程中引入小图可以显示，子工程引入大图在父工程中找不到路径

### ISSUE THREAD

**Issue by tdyyyy** [alibaba/ice#3269]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

* icejs version：
* Node verson：
* Platform：
* `build.json`：
* `src/app.(ts|js)`：

**What is the expected behavior?**

**Comment by chenbin92** [comment]
@tdyyyy 详细描述一下，就只一个标题无法定位问题
