### ISSUE TITLE
icestark打包后找不到资源问题

### ISSUE THREAD

**Issue by xiaoyaosheng-yu** [alibaba/ice#3270]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
icestark子应用打包后找不到资源文件

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
我用官方vue模板修改的一个子应用，模板地址：https://github.com/ice-lab/vue-materials/tree/master/scaffolds/icestark-child-app

框架主应用(端口3333)也是官方仓库的，地址：https://github.com/alibaba-fusion/materials/tree/master/scaffolds/ice-stark-layout

本地联调都是正常的，可以在主框架中访问到子应用，但是我将子应用build后，放到nginx指定端口(9001)时，主框架显示资源不存在，子应用单独打开没问题。

报错内容：
`
http://localhost:3333/css/app.css:404 Not Found
http://localhost:3333/js/app.js:404 Not Found
Remote Address: 127.0.0.1:3333
`
另外，我想请问一下，为什么会显示是3333端口的资源找不到，而不显示是9001的端口找不到呢，我的子应用静态资源在9001端口？

vue.config.js中的publicPath: '/' 已尝试将此修改为publicPath: './'
build.json中的publicPath: '/' 已尝试将此修改为publicPath: './'
以上两步皆已经尝试修改过了，但是未能解决问题，望相关技术支持，为感！

* icejs version：^1.0.0
* Node verson：v10.15.3
* Platform：window10_64
* `build.json`：
`
{
  "publicPath": "./",
  "plugins": [
    "build-plugin-icestark",
    ["build-plugin-fusion", {
      "themePackage": "@alifd/theme-design-pro",
      "themeConfig": {
        "nextPrefix": "next-icestark-"
      }
    }],
    ["build-plugin-moment-locales", {
      "locales": ["zh-cn"]
    }]
  ]
}
`
* `src/app.(ts|js)`：ts
* "@ice/stark-app": "^1.0.1",

**What is the expected behavior?**

**Comment by imsobear** [comment]
子应用要把 publicPath 配置成自己的域名

**Comment by xiaoyaosheng-yu** [comment]
> 子应用要把 publicPath 配置成自己的域名

我已经找到了方法，这里可以设置为:publicPath: '/'
但是主框架中必须用url，而不应该用entry，谢谢你
`
{
        path: '/report',
        title: '报表系统',
        // entry: 'http://localhost:9003',
        url: [
          'http://localhost:9003/js/app.js',
          'http://localhost:9003/css/app.css'
        ]
      }
`

**Comment by xiaoyaosheng-yu** [comment]
> 子应用要把 publicPath 配置成自己的域名

vue的子应用路由采用异步加载的方式引入会报错，是因为主框架不支持异步引入么？
代码如下：

`
const routerConfig = [
  {
    path: '/',
    component: isInIcestark() ? BasicLayout : CommenLayout,
    children: [
      { path: '/home', component: Home },
      { path: '/order', component: BasicLayout, exact: true, children: [
        { path: '/order/add', component: () => import('@/pages/orderManage/add') },
        { path: '/order/list', component: () => import('@/pages/orderManage/list') },
        { path: '/order/detail', component: () => import('@/pages/orderManage/detail') }
      ]},
      {
        path: '*',
        component: () => renderNotFound(),
      },
    ],
  },
];
`

**Comment by imsobear** [comment]
了解下 webpack 里的 publicPath，有助于你更深刻的理解这个问题。

**Comment by mizi-lin** [comment]
> > 子应用要把 publicPath 配置成自己的域名
> 
> vue的子应用路由采用异步加载的方式引入会报错，是因为主框架不支持异步引入么？
> 代码如下：
> 
> `const routerConfig = [ { path: '/', component: isInIcestark() ? BasicLayout : CommenLayout, children: [ { path: '/home', component: Home }, { path: '/order', component: BasicLayout, exact: true, children: [ { path: '/order/add', component: () => import('@/pages/orderManage/add') }, { path: '/order/list', component: () => import('@/pages/orderManage/list') }, { path: '/order/detail', component: () => import('@/pages/orderManage/detail') } ]}, { path: '*', component: () => renderNotFound(), }, ], }, ];`

异步加载的问题解决了么?
