### ISSUE TITLE
ice的微前端的子应用可以运用到ant design pro

### ISSUE THREAD

**Issue by rodchen-king** [alibaba/ice#3271]
看到ice关于微前端的文档，子应用需要对路由进行处理，可是ant designp pro的目前没有这种入口，可能是我不知道。请问antdesign pro想使用ice的微前端，可以做吗？可以做的话，应该怎么处理？

**Comment by ClarkXia** [comment]
ant design pro 基于 umi，路由均为内置，子应用如果需要修改 basename 来引入到框架应用中可以修改 base 配置 https://umijs.org/config#base
