### ISSUE TITLE
状态管理页面状态model目录组织

### ISSUE THREAD

**Issue by daiikaku** [alibaba/ice#3273]
状态管理页面状态model目录组织如src/pages/\*/\*/model.ts

报错提示store is null。

**Comment by chenbin92** [comment]
状态管理对目录结构有一定的约定，看看是不是按照文档写的。

![image](https://user-images.githubusercontent.com/3995814/84336657-5372d700-abca-11ea-834e-dea729ba0b0f.png)

另外，如果是给出可复现的 demo 或者详细步骤

**Comment by daiikaku** [comment]
@chenbin92 

src/pages/A/models/department.ts
src/pages/A/index.tsx，可以按照期望得到数据
src/pages/A/AA/index.tsx，提示错误如下

TypeError: Cannot read property 'store' of null
useSelector
./node_modules/react-redux/es/hooks/useSelector.js:100

**Comment by chenbin92** [comment]
@daiikaku 上面的信息无法排查，基于这个 [codesandbox](https://codesandbox.io/s/github/ice-lab/icejs/tree/master/examples/basic-store) 给出可复现的 demo 

或者参考这个示例：https://github.com/alibaba/ice/tree/master/examples/basic-store

**Comment by daiikaku** [comment]
> @daiikaku 上面的信息无法排查，基于这个 [codesandbox](https://codesandbox.io/s/github/ice-lab/icejs/tree/master/examples/basic-store) 给出可复现的 demo
> 
> 或者参考这个示例：https://github.com/alibaba/ice/tree/master/examples/basic-store

codesandbox 试了下，一直提示有依赖下不下来

我把工程传上来了，文件不多，请帮忙看下问题，感谢

https://github.com/daiikaku/ice_model

**Comment by chenbin92** [comment]
@daiikaku  看了下你的仓库代码，问题在于你在 `pages/Home/*` 页面下有多个页面。

- `pages/Home/index.tsx` 这个页面对应的路由也即 `/home` 可以正常访问
- `pages/Home/Page1/index.tsx` 这个页面对应的路由也即 `/home/page1` 访问报错，原因在于 icejs 约定了 model 和 page 之间的文件关系，需要遵循这里的约定 https://ice.work/docs/guide/basic/request#%E7%9B%AE%E5%BD%95%E7%BA%A6%E5%AE%9A
