### ISSUE TITLE
auth含参数初始化/模型联动

### ISSUE THREAD

**Issue by JimAmuro** [alibaba/ice#3280]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
如果我没有理解错的话，现在如果我想初始化 auth 应该找 app.ts 中的 gettInitialData 去向服务器请求 role，但是app初始化的时候用户并没有登录，我也没办法初始化有意义的auth。然后我希望利用状态管理的模型联动达到登录后向服务器请求role以后设到 auth 里面，但是我发现 dispatch 里面没有 auth，这样我做不到模型联动，只能在 hook 中 setAuth，这样我觉得不如模型联动。请问有什么初始化用户 auth 的好办法么？谢谢。

**What is the expected behavior?**

**Comment by imsobear** [comment]
在 gettInitialData 里先登录是不是就可以了？

**Comment by JimAmuro** [comment]
> 在 gettInitialData 里先登录是不是就可以了？

呃，我理解是这个app启动的时候 getInitialData 就执行了，那login页在app启动之后才有吧，怎么在 getInitialData中login呢？

**Comment by imsobear** [comment]
getInitialData 执行完才会调用 createApp

**Comment by JimAmuro** [comment]
> getInitialData 执行完才会调用 createApp

对我就是这个意思，app启动以后才有登录页面才能登录啊，怎么在getInitialData里登录呢

**Comment by mopsky** [comment]
我目前是开mpa，两个入口，user一个入口，用来登录，注册之类，然后剩下的业务一个入口，这样先登录，然在getInitialData获取权限

**Comment by imsobear** [comment]
@JimAmuro 你的登录逻辑是怎么实现的？前端发起一个 ajax 请求？

**Comment by JimAmuro** [comment]
@imsobear 就有个login页面发登录请求，后端通过了就返回jwt

**Comment by imsobear** [comment]
```js
import { request, createApp } from 'ice';

createApp({
  app: {
    getInitialData: async () => {
       // 发起登录请求
       const userInfo = await request('/user/login');
    }
  }
});
```

这样不行吗？

**Comment by JimAmuro** [comment]
@imsobear 这样 username 和 password 怎么传给 request 呢

**Comment by imsobear** [comment]
@JimAmuro 要不你再清晰描述下你的问题，感觉有点绕晕了

**Comment by JimAmuro** [comment]
@imsobear 就是说用户有权限，但要登录以后才能从后端拿到权限，他需要在登录页面输入账号密码，但是登录页面也是app的一部分，而 getInitialData 在 app 之前就执行了，所以没法用它初始化auth，然后我想在登录返回的时候用模型联动的方式 在 user model 的 effects 中 set auth，但是 dispatch 里面没有 auth，所以现在不方便初始化 auth。 
@mopsky 说的mpa也算是一种办法，相当于登录app执行了以后再 create 业务app 这样可以用 getInitialData 初始化业务的 auth，我觉得有点麻烦了

**Comment by imsobear** [comment]
@JimAmuro 钉钉答疑群里说，我们私聊看下。

**Comment by imsobear** [comment]
https://github.com/alibaba/ice/issues/3310 这个应该可以解决你们的问题，通过 SPA 来实现。 @JimAmuro @mopsky

**Comment by JimAmuro** [comment]
> #3310 这个应该可以解决你们的问题，通过 SPA 来实现。 @JimAmuro @mopsky

最近有点忙，你们先弄，有空了我再研究下😂谢谢了，效率很高
