### ISSUE TITLE
BUG: CSS 热更新失效问题

### ISSUE THREAD

**Issue by lihongxun945** [alibaba/ice#3283]
**Do you want to request a *feature* or report a *bug*?**
*BUG*

**What is the current behavior?**
如果先在JS中加入了classname，再写SCSS，样式不生效，需要手动刷新。
原因是在JS中加入classname的时候由于css不存在，导致编译的时候去掉了class，再写scss的时候只更新了css，而没有在DOM上把class加上，导致无法生效

* icejs version：1.5.0
* Node verson：10.10.0
* Platform：Mac
* `build.json`：
```json
{
  "plugins": [
    "build-plugin-icestark",
    [
      "build-plugin-moment-locales",
      {
        "locales": [
          "zh-cn"
        ]
      }
    ],
    "@ali/build-plugin-ice-def"
  ],
  "sassLoaderOptions": {
    "prependData": "@import '~@txdfe/at-theme/teambition/scss/index.scss';\n"
  }
}
```
* `src/app.(ts|js)`：无

**What is the expected behavior?**
希望能热更新生效

**Comment by ClarkXia** [comment]
dev 阶段通过开启 css-hot-loader  cssModule 配置

**Comment by ClarkXia** [comment]
已修复
