### ISSUE TITLE
BUG：使用d.ts 中声明的全局enum会导致运行时错误

### ISSUE THREAD

**Issue by lihongxun945** [alibaba/ice#3284]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
`d.ts` 中声明全局 `enum` 会运行时报错，如果在其他文件中使用会导致运行时报错。声明代码如下：
```js
declare enum MessageTypes {
  Success = 'success',
  Warning = 'warning',
  Error = 'error',
  Notice = 'notice'
}

declare interface MessageProps {
  type?: MessageTypes,
  title: string,
  children: JSX.Element | string,
  actions: JSX.Element | string
}

```
如果在其他文件中用 `MessageProps` 不会报错，但是用 `MessageTypes` 就会运行时报错，编译不会报错。似乎是对 `enum` 类型的处理有问题

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

* icejs version：1.5.0
* Node verson：10.10.0
* Platform：mac
* `build.json`：
```json
{
  "plugins": [
    "build-plugin-icestark",
    [
      "build-plugin-moment-locales",
      {
        "locales": [
          "zh-cn"
        ]
      }
    ],
    "@ali/build-plugin-ice-def"
  ],
  "sassLoaderOptions": {
    "prependData": "@import '~@txdfe/at-theme/teambition/scss/index.scss';\n"
  }
}
```
* `src/app.(ts|js)`：

**What is the expected behavior?**
希望能正常使用全局 `enum` 类型

**Comment by chenbin92** [comment]
## 问题

目录结构如下：

```markdown
.
├── components
│   ├── MiniMessage
│   │   ├── index.tsx
│   │   ├── styles.module.scss
│   │   └── typing.d.ts
├── pages
│   └── Publish
│       ├── components
│       │   └── CheckPoint
│       │       ├── index.tsx
│       │       └── styles.module.scss

```

`components/typing.d.ts` 定义如下

```ts
declare enum MessageTypes {
  Success = 'success',
  Warning = 'warning',
  Error = 'error',
  Notice = 'notice',
}
```

`在 pages/publish/index.tsx` 引用 `components/typing.d.ts`定义的类型

```
const FC: React.FC = () => {
  return (
    <>
      {/* 使用枚举类型 */}
      <MiniMessage type={MessageTypes.Warning}
    </>
  );
}; 
```

![image](https://user-images.githubusercontent.com/3995814/85143886-ea9bf680-b27c-11ea-8cd9-72295432817a.png)

问题原因：在页面中直接使用组件的 `xx.d.ts` 里的枚举类型（PS：没有这种用法）

## 解决

1. 将 `components/typing.d.ts` 的类型维护在 `src/typings` 下并改为 `common.ts` ，然后导出类型

```ts
// src/typing/common.ts
export enum MessageTypes {
  Success = 'success',
  Warning = 'warning',
  Error = 'error',
  Notice = 'notice',
}
```
2. 在使用时需要导入类型使用

```ts
import { MessageTypes } from '@/typing/common';

const FC: React.FC = () => {
  return (
    <>
      {/* 使用枚举类型 */}
      <MiniMessage type={MessageTypes.Warning}
    </>
  );
}; 
```

关于使用 `xx.d.ts` 全局声明方式可以参考：

* https://ts.xcatliu.com/basics/declaration-files
* https://stackoverflow.com/questions/38335668/how-to-refer-to-typescript-enum-in-d-ts-file-when-using-amd
