### ISSUE TITLE
物料脚手架—组件支持缩略图

### ISSUE THREAD

**Issue by suprise** [alibaba/ice#3285]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**

目前只有区块支持缩略图，但组件不支持

iceworks: 3.2.1

**What is the expected behavior?**

组件和区块一样支持缩略图，然后输入到fusion 物料中心

**Comment by imsobear** [comment]
```js
const materialItemConfig = pkg[`${materialType}Config`] || {};
const screenshot = materialItemConfig.screenshot
    || (hasScreenshot(path.dirname(pkgPath)) ? `${unpkgHost}/${npmName}@${pkg.version}/screenshot.png` : '');
```

支持的，逻辑是：先获取 package.json 里的 componentConfig.screenshot，没有的话会根据当前目录下是否有 `screenshot.png` 进行动态拼接。满足这个条件的话执行 `iceworks generate` 生成的 json 文件里应该会有对应字段。
