### ISSUE TITLE
插件里负责 runtime 定制的文件从 model.ts 改为 runtime.ts

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#3286]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

model.ts

**What is the expected behavior?**

model.ts 改为 runtime.ts，语义上更准确，老的 model.ts 可以兼容着。

**Comment by chenbin92** [comment]
已发布 ice.js@1.6.3 支持
