### ISSUE TITLE
支持本地个性化编译的配置

### ISSUE THREAD

**Issue by chenhebing** [alibaba/ice#3287]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
只有一个build.json，对于本地个性化的配置只能通过命令行来支持

**What is the expected behavior?**
希望提供一个local.build.js(on)?的配置，可以将本地的一个个性化的配置放进去

比如本地服务启动，希望直接打开自定义的host，或者多页项目指定打开的页面配置等

**Comment by chenbin92** [comment]
`local.build.json` 的配置不会太多，目前想到的只有`host` 和 `--mpa-entry` 这种。单独开一个 `local.build.json` 有点太重。在一般 node 的框架里会区分 local/prod/test 这样的配置文件，但你会发现他们三者的配置都是对等的，而在前端的工程环境下我理解不会对等。

其次，类似 `host` 和 `--mpa-entry` 这种推荐的是使用命令行的方式使用。

综上，不建议使用 `local.build.json` 的方式。

@ClarkXia

**Comment by imsobear** [comment]
支持 build.json + `build.plugin.js` 呀 https://ice.work/docs/guide/basic/build#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%85%8D%E7%BD%AE

另外我没有特别理解原始诉求是什么。

**Comment by chenhebing** [comment]
> 支持 build.json + `build.plugin.js` 呀 https://ice.work/docs/guide/basic/build#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%85%8D%E7%BD%AE
> 
> 另外我没有特别理解原始诉求是什么。

有些config 我这边期望有个性化的配置，这个配置是gitignore的，我可以将一些运行中差异化的配置只在我本地配置。

比如我本地配置的是 x.xx.com 域名指向localhost，别的同学配置的是y.yy.com，如果没有这个配置 那么我需要每次在命令行加上这个参数。

目前我这边会有一些配置，比如host，port，mpa-entry等配置，config-console 插件（用来打印webpack config，不常用）

如果能有一个local的配置能力，这个只有我本地话的配置 可以更便捷的运行

**Comment by imsobear** [comment]
线下讨论汇总：

## 需求

同一个项目多人开发，每个人的 build.json 可能有不一样的配置，希望这个差异化的配置能放在本地而不跟随 Git 提交。

## 方案

支持 `.tmp.build.json` 的配置文件，添加到 `.gitignore` 里，配置字段跟 `build.json` 保持一致，build-scripts 读取配置时将两个文件进行合并。

## 结论

不支持。诉求比较特殊，并且会引入新的问题，比如本地和预发不一致、更换电脑重新 clone 仓库配置文件丢失等，建议同一个项目配置统一，不应该因人而已。
