### ISSUE TITLE
retcode log report error ETIMEDOUT 203.119.169.39:443

### ISSUE THREAD

**Issue by Miantang** [alibaba/ice#3293]
**Do you want to request a *feature* or report a *bug*?**

为什么每次启动都有接口请求要访问淘宝 (203.119.169.39)

想问一下，这个每次上报(log report)我们项目中的什么信息到淘宝？

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/3156907/85494377-229f9280-b60b-11ea-9c9f-20de8040d3bb.png)

* icejs version：
1.5.0

**Comment by seanmpthx** [comment]
可怕

**Comment by imsobear** [comment]
`DISABLE_COLLECT=true icejs start` 可以关闭，主要用来统计命令行基础的使用量以及基础组件的使用量，不会收集开发者源码的信息。

**Comment by Miantang** [comment]
> `DISABLE_COLLECT=true icejs start` 可以关闭，主要用来统计命令行基础的使用量以及基础组件的使用量，不会收集开发者源码的信息。

好的，了解了。谢谢
