### ISSUE TITLE
权限配置在build.json配置完出现Invalid hook call的error并且白屏

### ISSUE THREAD

**Issue by DiiiligentBeeees** [alibaba/ice#3298]
按照ice官方文档的教程，我在build.json里设置了"build-plugin-ice-auth"后npm run start项目，发现出现白屏并且报错：Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component.请问该怎么解决呢？

**Comment by chenbin92** [comment]
@DiiiligentBeeees  贴一下代码看看怎么配置的，然后补充一下 `package.json ` 的依赖信息。

**Comment by DiiiligentBeeees** [comment]
**build.json配置如下：**
{
  "plugins": [
    [
      "build-plugin-fusion",
      {
        "themePackage": "@alifd/theme-design-pro"
      }
    ],
    [
      "build-plugin-moment-locales",
      {
        "locales": [
          "zh-cn"
        ]
      }
    ],
    [
      "build-plugin-ice-auth"
    ]
  ]
}

---------------------------------------
**package.json的配置如下：**
{
  "name": "xxx",
  "version": "0.0.1",
  "description": "xxx",
  "dependencies": {
    "@alifd/next": "1.20.12",
    "@alifd/theme-design-pro": "0.6.2",
    "@antv/data-set": "0.10.2",
    "@icedesign/qrcode": "^1.0.5",
    "@types/react": "16.9.36",
    "@types/react-dom": "16.9.4",
    "ahooks": "^2.0.1",
    "bizcharts": "3.5.9",
    "moment": "2.26.0",
    "prop-types": "15.7.2",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-intl": "2.9.0"
  },
  "devDependencies": {
    "@ice/spec": "1.0.1",
    "build-plugin-fusion": "0.1.3",
    "build-plugin-ice-auth": "^1.6.0",
    "build-plugin-moment-locales": "0.1.0",
    "eslint": "7.2.0",
    "ice.js": "1.5.0",
    "stylelint": "13.6.1"
  },
  "scripts": {
    "start": "icejs start",
    "build": "icejs build",
    "lint": "npm run eslint && npm run stylelint",
    "eslint": "eslint --cache --ext .js,.jsx ./",
    "stylelint": "stylelint ./**/*.scss",
    "design": "icejs build --design"
  },
  "ideMode": {
    "name": "ice-react"
  },
  "iceworks": {
    "type": "react",
    "adapter": "adapter-react-v3"
  },
  "engines": {
    "node": ">=8.0.0"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/alibaba-fusion/materials/tree/master/scaffolds/fusion-design-pro-js"
  },
  "private": true,
  "originTemplate": "@alifd/fusion-design-pro-js"
}

**Comment by chenbin92** [comment]
> Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component

@DiiiligentBeeees  看这个日志是调用 hook 错误，Hooks 只能在函数里调用。权限方案提供了 `useAuth` 和 `withAuth` 两个 API：

1. useAuth 适用于函数组件
2. withAuth 适用于 Class 组件

文档：https://ice.work/docs/guide/advance/auth#useAuth
示例：https://github.com/alibaba/ice/blob/master/examples/basic-auth/src/pages/Home/index.tsx#L6

**Comment by myshanshan** [comment]
您好，这里 并未调用任何的Hook，只要在build.json中添加相关配置就立即报错，如果将配置删除即恢复正常，请问是什么原因导致的呢？
![73c6e7470bae9df7243cb9921a04b9b](https://user-images.githubusercontent.com/34647621/85940712-a5e51f00-b950-11ea-993f-c91fe63f72ec.png)

**Comment by chenbin92** [comment]
@myshanshan  提供一个最小可复现的 demo ，我这边看下

**Comment by myshanshan** [comment]
好的，但我是编程新人，不懂如何改造最小可复现，就发个项目给您看看吧，就是基于模板项目修改了一些简单的页面而已，没有包引入或者复杂逻辑编写。
[dxc_web (1).zip](https://github.com/alibaba/ice/files/4841838/dxc_web.1.zip)

**Comment by chenbin92** [comment]
上面提供的 DEMO 代码太多，基于 [fusion-design-pro-js@0.1.18](https://unpkg.com/@alifd/fusion-design-pro-js@0.1.18/build/index.html#/dashboard/analysis) 模板 + 权限插件测了下正常使用，步骤如下：

## 初始化项目

```ts
$ npm init ice ice-app @alifd/fusion-design-pro
```

## 安装权限插件

```ts
$ cd ice-app && npm install build-plugin-ice-auth -D
```

## 配置权限插件

```diff
{
  "plugins": [
    [
      "build-plugin-fusion",
      {
        "themePackage": "@alifd/theme-design-pro"
      }
    ],
    [
      "build-plugin-moment-locales",
      {
        "locales": [
          "zh-cn"
        ]
      }
    ],
    "@ali/build-plugin-ice-def",
+   "build-plugin-ice-auth"
  ]
}
```

## 伪造权限数据

```diff
import React from 'react';

const locale = getLocale();
const appConfig = {
  app: {
    rootId: 'ice-container',
    addProvider: ({ children }) => <LocaleProvider locale={locale}>{children}</LocaleProvider>,
+    getInitialData: async () => {
+     return {
+        auth: {
+          readAnalysis: false,
+       }
+      }
    },
  },
+  auth: {
+    NoAuthFallback: <div>没有权限...</div>,
+  }
};
createApp(appConfig);
```

## 配置页面权限

如 `src/pages/Analysis` 页面

```diff
import React from 'react';

const Analysis = () => (
  
);

+Analysis.pageConfig = {
+  auth: ['readAnalysis'],
+};

export default Analysis;
```

## 启动调试预览

可在 `app.js` 通过设置 `readAnalysis: true | false` 查看页面的权限状态

![image](https://user-images.githubusercontent.com/3995814/85947487-98925980-b97d-11ea-9ff6-c875394df8c2.png)

**Comment by xiaozhendong** [comment]
我这里也出现了同样 的情况，只要在build.json里面配置这个build-plugin-ice-auth插件就会报错。
`Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app`
我尝试了使用1.5.0版本也一样报错

**Comment by chenbin92** [comment]
@DiiiligentBeeees @myshanshan @xiaozhendong 

排查到问题了，相关修复 MR https://github.com/alibaba/ice/pull/3307

**Comment by chenbin92** [comment]
已发布 ice.js@1.6.1 版本修复
