### ISSUE TITLE
支持 MPA 可选路由配置

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#3302]
## 问题

当前 MPA 模式下需要用户配置路由，但大多数情况下 MPA 单个页面无需配置路由直接渲染即可。

```ts
import { createApp, IAppConfig } from 'ice';
import Home from './index';

const appConfig: IAppConfig = {
  router: {
    routes: [{ path: '/', component: Home }],
  },
};

createApp(appConfig);
```

## 预期
- MPA 模式下路由配置是可选的

**Comment by imsobear** [comment]
另外这个问题看下怎么规避？比如打个日志出来？

**Comment by chenbin92** [comment]
与 rax-app 的 MPA 逻辑保持一致。

**Comment by ClarkXia** [comment]
### 方案
开启 mpa 模式后，默认以 app / index 为应用 entry：
1. 如果希望使用 icejs 运行时能力，在入口手动添加 runApp 逻辑及路由设置（同目前保持一致）
2. 对于单个页面无需配置路由的情况下，默认以组件导出的方式即可启动（以 index 为入口），工程上默认通过 loader 增加 ReactDOM.render 等逻辑

> 兼容逻辑：如果入口已添加 runApp / ReactDOM.render 的代码，默认不在做自动代码注入逻辑
