### ISSUE TITLE
在配置了使用了build-plugin-ice-auth，页面报Invalid hook call错误

### ISSUE THREAD

**Issue by xiaozhendong** [alibaba/ice#3304]
我查看的issue里的和我情况一模一样的问题：[权限配置在build.json配置完出现Invalid hook call的error并且白屏](https://github.com/alibaba/ice/issues/3298#)

跑了一下给的DEMO，这个里面的DEMO跑了没问题能正常使用，但我自己的项目却无法使用

**Comment by chenbin92** [comment]
@xiaozhendong  提供一个最小可复现的 DEMO

**Comment by xiaozhendong** [comment]
@chenbin92 不好意思刚刚一直在穿最小的代码复现demo，代码传不上来，我放弃挣扎了，我直接飞冰群里说吧

**Comment by xiaozhendong** [comment]
[ManagementIterfaceDemo-master.zip](https://github.com/alibaba/ice/files/4844540/ManagementIterfaceDemo-master.zip)
终于传上来了，这是最小的代码复现DEMO

**Comment by chenbin92** [comment]
@xiaozhendong  排查到问题了，修复 MR https://github.com/alibaba/ice/pull/3307

**Comment by xiaozhendong** [comment]
更新了build-plugin-ice-auth@1.6.1-alpha.0已经可以使用
