### ISSUE TITLE
使用iceworks IDE 添加区块时，区块依赖没有添加到项目依赖中

### ISSUE THREAD

**Issue by 97Ronal** [alibaba/ice#3309]
**Do you want to request a *feature* or report a *bug*?**

使用iceworks ide添加区块的时候，无法将区块的依赖自动添加到`package.json`中

**What is the current behavior?**

无法自动将区块依赖添加到项目`package.json`中，导致每次添加区块时需要手动添加依赖，过于麻烦

**What is the expected behavior?**

期望的是，添加了区块之后，会在项目`package.json`中添加对应区块的依赖

**Comment by chenbin92** [comment]
@97Ronal 推荐使用新版的 iceworks VSCode 插件 https://marketplace.visualstudio.com/items?itemName=iceworks-team.iceworks
