### ISSUE TITLE
通过 circular-dependency-plugin 插件检测存在循环依赖

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#3319]
## 问题

如下配置

```ts
const CircularDependencyPlugin = require('circular-dependency-plugin')

module.exports = ({ onGetWebpackConfig }) => {
    onGetWebpackConfig((config) => {
        config.plugin('CircularDependencyPlugin')
          .use(CircularDependencyPlugin, [{
              // exclude detection of files based on a RegExp
              exclude: /node_modules/,
              // include specific files based on a RegExp
              // include: /src/,
              // add errors to webpack instead of warnings
              failOnError: false,
              // allow import cycles that include an asyncronous import,
              // e.g. via import(/* webpackMode: "weak" */ './file.js')
              // allowAsyncCycles: false,
              // set the current working directory for displaying module paths
              cwd: process.cwd(),
          }]);
    });
}
```

路由使用

```ts
import { lazy } from 'ice';
import BasicLayout from '@/layouts/BasicLayout';

import Home from '@/pages/Home';

const routerConfig = [
  {
    path: '/',
    component: BasicLayout,
    children: [
      { path: '/channels', component: Home }
    ],
  },
];
export default routerConfig;

```

通过 `circular-dependency-plugin` 插件检测存在循环问题

![image](https://user-images.githubusercontent.com/3995814/86442986-25a02e80-bd41-11ea-9df4-f9e9e85061c1.png)

## 预期

解决循环依赖问题

**Comment by LanceZhu** [comment]
问题定位：
`plugin-router` 中引用 `src/routes.ts` 文件。
产生循环依赖：`src/app.tsx` -> **`.ice/index.ts`** -> `plugin-router` -> *`src/routes.ts`* -> **`.ice/index.ts`**

相关代码：
https://github.com/alibaba/ice/blob/2787cbfe269cfa0845499f7222aab51490fcca53/packages/plugin-router/src/runtime.tsx#L2
https://github.com/alibaba/ice/blob/2787cbfe269cfa0845499f7222aab51490fcca53/packages/plugin-router/src/index.ts#L57

解决方案：
1. 将 `routes.ts` 提升至 `app.tsx`
示例代码：

```diff
// src/app.tsx
import routes from '$ice/routes';

const appConfig: IAppConfig = {
	router: {
+		routes
	}
}
```

2. 路由相关组件，`lazy`、`Link` 等与 `createApp` 分离。

   原有:

   ```typescript
   import { createApp, lazy, Link } from 'ice';
   ```
   
   
   
   示例：
   
   ``` typescript
   import { createApp } from 'ice';
   
   import { Link } from 'ice/Router';
   import { lazy } from 'ice/lazy';

**Comment by LanceZhu** [comment]
针对解决方案2：
想法：通过 `babel` 更换 `src/pages/*` 及 `src/routes` 中引入的 路由 相关组件，如 `Link`, `lazy` 的原有导入方式。

*原有导入：*
`import { Link } from 'ice';`
![](http://latex.codecogs.com/gif.latex?\downarrow)
*修改后：*
`import { Link } from 'ice/routes/index.ts';`

实现参考：[plugin-store babelPluginReplacePath](https://github.com/alibaba/ice/blob/master/packages/plugin-store/src/babelPluginReplacePath.ts)

**Comment by chenbin92** [comment]
已处理
