### ISSUE TITLE
icejs 禁用运行时能力后使用约定式路由能力

### ISSUE THREAD

**Issue by ClarkXia** [alibaba/ice#3322]
## 背景

icejs 的运行时能力屏蔽了应用入口相关的执行逻辑，历史项目可以通过 `disableRuntime` 快速升级到 icejs。
但历史项目类型中存在使用基础插件搭配约定式路由能力的场景。期望 icejs 在关闭运行时能力的同时，可以提供约定式路由开启使用的方式。

**Comment by chenbin92** [comment]
## 目标

1. 在 `build.json` 中配置 disableRuntime 之后，使用约定式路由项目能正常构建 & 运行。

```json
{
  "disableRuntime": true 
}
```

2. 可以用 basic-spa 为示例，删除 `src/routes.ts` 然后启动项目正常运行。

## 方案

1. 约定式路由即默认不需要配置路由，在 icejs 中的规则是如果 `src/routes.js` 不存在，即当做约定式路由处理。

2. 配置 disableRuntime 之后，在[内置插件](https://github.com/alibaba/ice/blob/master/packages/icejs/src/index.ts#L5)配置中需要添加 build-plugin-ice-router 插件即支持约定式路由功能。

```ts
if (userConfig.disableRuntime) {
    return [
      'build-plugin-react-app',
      'build-plugin-ice-mpa',
      'build-plugin-ice-router'
    ];
  }
```

3. 禁用 disableRuntime 逻辑之后，build-plugin-ice-core 插件不在生效即[相关路由配置](https://ice.work/docs/guide/basic/router#%E8%BF%90%E8%A1%8C%E6%97%B6%E9%85%8D%E7%BD%AE)也不再生效，需要文档给出说明。

## 其他

- [路由文档](https://ice.work/docs/guide/basic/router)
- [路由实现](https://github.com/alibaba/ice/blob/master/packages/plugin-router)

**Comment by LanceZhu** [comment]
disableRuntime 后 `import { logger } from 'ice'` 等内置能力同样不生效。

**Comment by chenbin92** [comment]
结论：不单独开放这个能力，直接使用最新版 icejs。
