### ISSUE TITLE
Table组件的sortIcon显示不正常

### ISSUE THREAD

**Issue by we6288815** [alibaba/ice#3326]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
使用Table组件的排序功能，发现sortIcon过小，无论怎么设置Icon的大小都不生效。

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
复现步骤：
1、使用@alifd/scaffold-lite-js模板创建一个新项目；
2、添加一个Table组件，并且启用排序；
3、sortIcon未正常显示。
![image](https://user-images.githubusercontent.com/8169722/86886695-f6ffca80-c129-11ea-93b5-4e27213d3aab.png)
[test-table-sort.zip](https://github.com/alibaba/ice/files/4888951/test-table-sort.zip)

* icejs version：1.6.2
* Node verson：v10.16.0
* Platform：windows 10
* `build.json`：
* `src/app.(ts|js)`：js

**What is the expected behavior?**
sortIcon正常显示
![image](https://user-images.githubusercontent.com/8169722/86886819-29a9c300-c12a-11ea-8177-235bef6faa4e.png)

**Comment by youluna** [comment]
看了下是@alifd/theme-design-pro  这个主题包特地把icon改成这样的，算设计上的偏好吧
https://fusion.design/72791/component/basic/table#%E6%8E%92%E5%BA%8F%E4%B8%8E%E8%BF%87%E6%BB%A4
![image](https://user-images.githubusercontent.com/10049465/86887892-df294600-c12b-11ea-87d0-df8b23dadef1.png)

**Comment by we6288815** [comment]
更换主题后显示正常
