### ISSUE TITLE
页面 404 引用变量不合法

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#3328]
## 问题

如下图所示，对 `pages/404` 进行了转换，根据页面名称将导入的变量名命名为 `404`，该变量不符合规范

![image](https://user-images.githubusercontent.com/3995814/86899039-0982ff80-c13c-11ea-8bbb-60bcc747499e.png)

## 预期

- 变量名规范化

## 建议

- 在引用时添加 Page 前缀如 `Page404`

**Comment by chenbin92** [comment]
已发布 ice.js@1.6.3 修复

**Comment by usercao** [comment]
@chenbin92 文档还没有对应修改

**Comment by chenbin92** [comment]
> @chenbin92 文档还没有对应修改

这个是内部实现，你指的文档是那一块 ？

**Comment by usercao** [comment]
文档约定式路由那里，不清楚是否也应该改为/page404

**Comment by usercao** [comment]
[约定式路由404](https://ice.work/docs/guide/basic/router#404%20%E8%B7%AF%E7%94%B1)

**Comment by usercao** [comment]
@chenbin92 [helpers](https://ice.work/docs/guide/basic/api#helpers)的文档也没有

**Comment by sspku-yqLiu** [comment]
> @chenbin92 [helpers](https://ice.work/docs/guide/basic/api#helpers)的文档也没有

文件上仍然使用404.tsx,只是对引用进行修改，即import Page404 from ...404.tsx  文件并没有更改，改变的是引用。
因此仍然使用404.tsx进行判断搜索。
