### ISSUE TITLE
自定义模块名的校验和生成规则有问题

### ISSUE THREAD

**Issue by yujiangshui** [alibaba/ice#333]
![image](https://user-images.githubusercontent.com/2942913/37772628-2faf7f8c-2e16-11e8-9aaa-075f044a99c6.png)

设置这样的三个名字，可以预览，点击直接挂。可以点击生成页面，但生成之后页面也是挂的，因为少了文件

![image](https://user-images.githubusercontent.com/2942913/37772677-53817c08-2e16-11e8-84aa-e786872f56ba.png)

**Comment by noyobo** [comment]
大小写检测，需要略掉大小写的。

**Comment by noyobo** [comment]
![image](https://user-images.githubusercontent.com/1292082/37971212-f6e84490-3207-11e8-8152-53eb05a2f65c.png)
