### ISSUE TITLE
Upgrade from ice-scripts 2.x 

### ISSUE THREAD

**Issue by TrumanDu** [alibaba/ice#3341]
**Do you want to request a *feature* or report a *bug*?**
按[文档](https://ice.work/docs/guide/migrate#%E4%BB%8E%20ice-scripts%202.x%20%E8%BF%81%E7%A7%BB)迁移，
**What is the current behavior?**
项目可以启动，只是无法看到页面，空页面
If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
目测原因是未迁移布局，例如MainRoutes.jsx

项目地址：https://github.com/xaecbd/KafkaCenter/blob/master/KafkaCenter-Frontend/src/layouts/BasicLayout/MainRoutes.jsx
* icejs version：
1.6.3
* Node verson：
v10.15.2
* Platform：
window10
* `build.json`：
```
{
    "alias": {
        "@utils": "./src/utils/",
        "@components": "./src/components",
        "@images": "./public/images"
    },
    "outputDir": "../KafkaCenter-Core/src/main/resources/static",
    "proxy": {
        "/**": {
            "enable": true,
            "target": "http://127.0.0.1:8080"
        }
    },
    "plugins": [
        [
            "build-plugin-moment-locales",
            {
                "locales": [
                    "zh-cn"
                ]
            }
        ],
        [
            "build-plugin-fusion",
            {
                "themePackage": "@icedesign/theme"
            }
        ],
        [
            "build-plugin-css-assets-local",
            {
                "outputPath": "assets",
                "relativeCssPath": "/"
            }
        ]
    ]
}
```
* `src/app.(ts|js)`：
```
import { createApp } from 'ice';

const appConfig = {
  router: {
    type: 'browser', // 配置 browser 路由
  },
};

createApp(appConfig);
```
**What is the expected behavior?**
正确迁移项目

**Comment by 1533424140** [comment]
项目是仅迁移项目的工程能力吗？如果是的话 可以在build.json里面设置"disableRuntime": true后再尝试下（在此条件下src/index可以不用迁移）

**Comment by chenbin92** [comment]
> 项目是仅迁移项目的工程能力吗？如果是的话 可以在build.json里面设置"disableRuntime": true后再尝试下（在此条件下src/index可以不用迁移）

@1533424140 先排查具体问题，看看是否可以在开启 disableRuntime

**Comment by TrumanDu** [comment]
@chenbin92 @1533424140 不仅仅是工程能力，最后我采用了重新整理项目，也就是重新搭建一个pro项目，然后把页面迁移过去。不过代码有点大。迁移不太友好。预计需要花费3天代价。

pro 模板项目，icejs的版本竟然还是1.0，建议保持模板工程的版本。迁移后存在多个版本共存，这周我把迁移过程写篇文章，还有遇到的问题也反馈一下。

**Comment by 1533424140** [comment]
> @ chenbin92 @ 1533424140两个工程能力，最后我采用了重新整理项目，也就是重新建造一个pro项目，然后把页面迁移过去。不过修改代码量有点大。迁移不太友好。预计需要花费3天代价。
> 
> pro模板项目，icejs的版本竟然还是1.0，建议及时更新模板工程的版本。迁移后存在多个版本共存，这周我把迁移过程写文章，还有遇到的问题也反馈一下。
“项目可以启动，只是无法看到页面，空页面”  这个问题 请问你的问题分支在哪里，我没有看到，无法拉取bug代码

**Comment by TrumanDu** [comment]
@1533424140 那个没有建分支哦。就 是把我连接的那个项目按照官网文档迁移，操作完成，打开就是空白页面、没有任何错误。

**Comment by chenbin92** [comment]
> pro 模板项目，icejs的版本竟然还是1.0，建议及时更新模板工程的版本。

@TrumanDu  pro 模板里写的是 `"ice.js": "^1.0.0"`，这个在依赖安装时会下载 1.x 最新版本的

**Comment by chenbin92** [comment]
> @1533424140 那个没有建分支哦。就 是把我连接的那个项目按照官网文档迁移，操作完成，打开就是空白页面、没有任何错误。

具体什么错误可以贴出来看下

**Comment by TrumanDu** [comment]
[ice-scripts到ice.js实战迁移之路](https://trumandu.github.io/2020/07/15/ice-scripts%E5%88%B0ice-js%E5%AE%9E%E6%88%98%E8%BF%81%E7%A7%BB%E4%B9%8B%E8%B7%AF/)

**Comment by imsobear** [comment]
@TrumanDu 赞总结。文章中提到的图标和菜单权限我们后续会产出方案，感谢反馈。

**Comment by TrumanDu** [comment]
@imsobear 希望方案是持续演进的（能考虑到旧系统的升级），还有希望能把一些推荐的用法多在pro项目中落地。如果文档不能及时更新的话，模板项目及时更新也是个不错的办法。感谢你们的付出，加油，看到你们。

**Comment by TrumanDu** [comment]
@chenbin92 这个问题该如何解决
```
----项目依赖健康检查-----
WARN 项目依赖了 core-js 的两个版本， [ '3.6.5', '2.6.11' ]
WARN 项目依赖了 @alifd/next 的两个版本， [ '1.21.0-beta.4', '1.20.18' ]
WARN 项目依赖了 hoist-non-react-statics 的两个版本， [ '3.3.2', '2.5.5' ]
WARN 项目依赖了 regenerator-runtime 的两个版本， [ '0.11.1', '0.13.5' ]
```

package.json
```
  "dependencies": {
    "@alifd/next": "^1.21.0-beta.4",
    "@alifd/theme-design-pro": "^0.6.2",
    "@antv/data-set": "^0.10.2",
    "@icedesign/container": "^1.0.3",
    "@icedesign/form-binder": "^1.x",
    "@icedesign/foundation-symbol": "^1.x",
    "@icedesign/img": "^1.x",
    "@icedesign/layout": "^1.x",
    "@icedesign/panel": "^1.0.4",
    "@icedesign/theme": "^0.1.2",
    "@types/react": "^16.9.13",
    "@types/react-dom": "^16.9.4",
    "ahooks": "^2.0.0",
    "axios": "^0.19.0",
    "bizcharts": "^3.5.6",
    "bootstrap-daterangepicker": "^3.0.4",
    "brace": "^0.11.1",
    "dayjs": "^1.8.15",
    "deepmerge": "^4.2.2",
    "js-cookie": "^2.2.0",
    "lodash.debounce": "^4.0.8",
    "moment": "^2.24.0",
    "numeral": "^2.0.6",
    "prop-types": "^15.5.8",
    "react": "^16.4.1",
    "react-ace": "^8.0.0",
    "react-bootstrap-daterangepicker": "^4.1.0",
    "react-cookie": "^4.0.0",
    "react-dom": "^16.4.1",
    "react-intl": "^2.8.0",
    "react-json-pretty": "^2.2.0",
    "react-json-tree": "^0.11.2",
    "react-sortablejs": "^2.0.11"
  },
  "devDependencies": {
    "@ice/spec": "^1.0.0",
    "bootstrap": "^4.3.1",
    "build-plugin-css-assets-local": "^0.1.0",
    "build-plugin-fusion": "^0.1.0",
    "build-plugin-ice-auth": "^1.6.3",
    "build-plugin-moment-locales": "^0.1.0",
    "enquire-js": "^0.1.2",
    "eslint": "^6.0.1",
    "ice.js": "^1.6.3",
    "stylelint": "^13.2.0"
  },
```

**Comment by chenbin92** [comment]
> @chenbin92 这个问题该如何解决
> 
> ```
> ----项目依赖健康检查-----
> WARN 项目依赖了 core-js 的两个版本， [ '3.6.5', '2.6.11' ]
> WARN 项目依赖了 @alifd/next 的两个版本， [ '1.21.0-beta.4', '1.20.18' ]
> WARN 项目依赖了 hoist-non-react-statics 的两个版本， [ '3.3.2', '2.5.5' ]
> WARN 项目依赖了 regenerator-runtime 的两个版本， [ '0.11.1', '0.13.5' ]
> ```

这里的逻辑是扫描 node_modules 下的依赖，有些是项目间接依赖的，可以运行 npm list core-js 看下依赖关系要不要升级，这个是 WARN 可以忽略。

![image](https://user-images.githubusercontent.com/3995814/87623048-12388e80-c757-11ea-8997-22609d8aceac.png)
