### ISSUE TITLE
菜单配置文档缺失

### ISSUE THREAD

**Issue by TrumanDu** [alibaba/ice#3342]
**Do you want to request a *feature* or report a *bug*?**
官网未找到关于菜单配置文档
**What is the current behavior?**

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

* icejs version：
* Node verson：
* Platform：
* `build.json`：
* `src/app.(ts|js)`：

**What is the expected behavior?**
关于菜单中，目前仅支持icon,图标集合太少，可否icon 内置更多图标，自定义扩展有点繁杂，还有菜单图标扩展的用法

**Comment by TrumanDu** [comment]
@chenbin92 菜单权限是怎么配置的，自己鉴权吗？

**Comment by TrumanDu** [comment]
[ice-scripts到ice.js实战迁移之路](https://trumandu.github.io/2020/07/15/ice-scripts%E5%88%B0ice-js%E5%AE%9E%E6%88%98%E8%BF%81%E7%A7%BB%E4%B9%8B%E8%B7%AF/)

**Comment by chenbin92** [comment]
> @chenbin92 菜单权限是怎么配置的，自己鉴权吗？

可以参考下 [权限管理](https://ice.work/docs/guide/advance/auth#%E5%88%9D%E5%A7%8B%E5%8C%96%E6%9D%83%E9%99%90%E6%95%B0%E6%8D%AE)，拿到权限列表后，在渲染菜单的位置判断下是否有权限即可

**Comment by TrumanDu** [comment]
@chenbin92 [场景 2：构建部署和网站运行时都请求不到 CDN 文件](https://ice.work/docs/guide/advance/assets-local#%E5%9C%BA%E6%99%AF%202%EF%BC%9A%E6%9E%84%E5%BB%BA%E9%83%A8%E7%BD%B2%E5%92%8C%E7%BD%91%E7%AB%99%E8%BF%90%E8%A1%8C%E6%97%B6%E9%83%BD%E8%AF%B7%E6%B1%82%E4%B8%8D%E5%88%B0%20CDN%20%E6%96%87%E4%BB%B6)

按这种操作方式，发现图标不同
在线
![image](https://user-images.githubusercontent.com/16727775/87622976-e74e3a80-c756-11ea-8088-369daf65ad2c.png)
lixi
离线
![image](https://user-images.githubusercontent.com/16727775/87623007-f503c000-c756-11ea-8d95-02af39368493.png)

**Comment by cqcmdwym** [comment]
> > @chenbin92 菜单权限是怎么配置的，自己鉴权吗？
> 
> 可以参考下 [权限管理](https://ice.work/docs/guide/advance/auth#%E5%88%9D%E5%A7%8B%E5%8C%96%E6%9D%83%E9%99%90%E6%95%B0%E6%8D%AE)，拿到权限列表后，在渲染菜单的位置判断下是否有权限即可，我这边补充下文档和示例。

请问文档有否更新发布？谢谢

**Comment by nick-ma** [comment]
> @chenbin92 [场景 2：构建部署和网站运行时都请求不到 CDN 文件](https://ice.work/docs/guide/advance/assets-local#%E5%9C%BA%E6%99%AF%202%EF%BC%9A%E6%9E%84%E5%BB%BA%E9%83%A8%E7%BD%B2%E5%92%8C%E7%BD%91%E7%AB%99%E8%BF%90%E8%A1%8C%E6%97%B6%E9%83%BD%E8%AF%B7%E6%B1%82%E4%B8%8D%E5%88%B0%20CDN%20%E6%96%87%E4%BB%B6)
> 
> 按这种操作方式，发现图标不同
> 在线
> ![image](https://user-images.githubusercontent.com/16727775/87622976-e74e3a80-c756-11ea-8088-369daf65ad2c.png)
> lixi
> 离线
> ![image](https://user-images.githubusercontent.com/16727775/87623007-f503c000-c756-11ea-8d95-02af39368493.png)

我也遇到这个问题了，估计是图标的字体文件不一样。

**Comment by luhc228** [comment]
已新增文档：https://ice.work/docs/guide/basic/menu
