### ISSUE TITLE
icejs如何动态配置entry

### ISSUE THREAD

**Issue by shaniu00** [alibaba/ice#3346]
build.json中的 "entry"如何动态设置，
我在build.plugin.js中尝试
```js
module.exports = ({ onGetWebpackConfig }) => {
    onGetWebpackConfig((config) => {
        console.log(entry);
        config.entry(entry);
```
始终都是报错的entry格式为字符串"src/index.js"或者数组["src/index.js"]都不行
 configuration[0].entry['src/Block/index.js'] should be an non-empty array
 A non-empty array of non-empty strings

**Comment by chenbin92** [comment]
onGetWebpackConfig 里支持通过 webpack chain 修改，格式如下：

```ts
module.exports = ({ onGetWebpackConfig }) => {
  onGetWebpackConfig((config) => {

    config.entryPoints.clear();

    config.entry('index')
      .add('src/index.js')
      .end()
  })
})
```
