### ISSUE TITLE
components物料build时生成的homepage没有使用私有unpkg地址

### ISSUE THREAD

**Issue by rootsli** [alibaba/ice#3347]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
已设置iceworks config set unpkgHost，但是components物料build时生成的homepage并没有使用私有unpkg地址，而是https://unpkg.com/

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

* icejs version：
* Node verson：
* Platform：
* `build.json`：
* `src/app.(ts|js)`：

**What is the expected behavior?**

**Comment by imsobear** [comment]
https://github.com/ice-lab/iceworks/blob/master/packages/iceworks-cli/src/command/generate/generateMaterialData.ts#L27-L28

**Comment by imsobear** [comment]
提供一个物料源仓库看下，看代码是没有问题的

![image](https://user-images.githubusercontent.com/2505411/87514835-71da5f80-c6ad-11ea-86ba-d5ae63199d3c.png)

![image](https://user-images.githubusercontent.com/2505411/87514857-7dc62180-c6ad-11ea-867e-319483cbd871.png)

**Comment by rootsli** [comment]
是指package.json里的homepage字段哦
![image](https://user-images.githubusercontent.com/4099803/87622770-6131f400-c756-11ea-9344-98326b84fd81.png)

**Comment by imsobear** [comment]
哦哦 这里的确有这个问题，我看一下

**Comment by rootsli** [comment]
![image](https://user-images.githubusercontent.com/4099803/87653100-a1f63100-c787-11ea-9c20-45a5b579f05a.png)

补充：物料数据homepage字段也不是私有地址，screenshot字段是OK的

**Comment by ImPigerla** [comment]
同样遇到这个问题，配置了`materialConfig.unpkgHost` 和 全局 iceworks config set unpkgHost xxx 也没用

**Comment by imsobear** [comment]
业务组件下的 build-plugin-component 升级到 0.2.21
