### ISSUE TITLE
自动将  ````jsx 转换为```jsx时，生成的demo文档有问题

### ISSUE THREAD

**Issue by rootsli** [alibaba/ice#3348]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**

开发业务组件的时候 demo文件夹里的md文件格式化时会自动将  ````jsx 转换为```jsx  导致生成的demo有问题，能否兼容```jsx。
格式化的时候是自动转换，有时候很难发现是这里引起的问题

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

* icejs version：
* Node verson：
* Platform：
* `build.json`：
* `src/app.(ts|js)`：

**What is the expected behavior?**

**Comment by ImPigerla** [comment]
![image](https://user-images.githubusercontent.com/26539446/87758784-ae3dc500-c83f-11ea-92fa-87d25497a39e.png)

**Comment by chenbin92** [comment]
@ClarkXia 这个看下

**Comment by ClarkXia** [comment]
https://github.com/ice-lab/iceworks-cli/pull/24 md 内容将支持标准语法

**Comment by ClarkXia** [comment]
build-plugin-component 已支持标准 md 语法
