### ISSUE TITLE
构建产物大小&编译速度优化

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#3354]
## 背景

目前 icejs 基于 webpack 作为工程构建工具，但在构建体验上仍然存在很大程度的提升空间，主要包括 **构建产物大小** 和 **构建速度** 两部分，基于此我们希望进一步的对工程体验进行优化，提高编译速度，更小的构建产物。

## 需求

- [ ] **构建产物分析和优化方案**：对构建产物进行分析，使用 icejs 最小化场景的构建依赖分析，基于依赖关系制定方案删除无用代码，减少体积。需要有具体的数字如优化前后的体积大小的对比。
- [ ] **构建速度分析和优化方案**：在了解构建产物关系依赖后，对构建速度进行分析，首次编译速度、二次编译速度等数据指标。

数据指标

|      |  产物体积(优化前)  | 产物体积(优化后)  |
|  ----  | ----  |----  |
| examples/hello-world  | - |
| fusion-design-lite  | - |
| fusion-design-pro  | - |

|      |  构建速度(优化前)  | 构建速度(优化后)  |
|  ----  | ----  |----  |
| examples/hello-world  | - |
| fusion-design-lite  | - |
| fusion-design-pro  | - |

## 相关参考

- [构建依赖分析](https://www.npmjs.com/package/webpack-bundle-analyzer)
- [Webpack 打包太慢？来试试 Bundleless 吧](https://mp.weixin.qq.com/s/Wr9d6yrNWjrmP8_Sxbmzfw)
- [三十分钟掌握Webpack性能优化](https://juejin.im/post/5b652b036fb9a04fa01d616b)
- [性能优化篇---Webpack构建速度优化](https://segmentfault.com/a/1190000018493260)

**Comment by LanceZhu** [comment]
进度：
1. 根据`相关参考`，在 `example/hello-world` 测试 webpack 打包构建速度优化方案。发现 优化方案 在现有 webpack 配置中均有体现。
2. 使用 `happypack` 多进程构建，`example/hello-world` 构建速度下降。
3. 使用 `webpack-bundle-analyzer` 初步查看构建产物组成。

**Comment by LanceZhu** [comment]
### 进度：
1. 总结现有示例 `hello-world`、`fusion-design-pro-ts`、`fusion-design-lite-ts` 构建速度 及 构建包相关数据。

![示例构建速度及构建包相关数据](https://user-images.githubusercontent.com/26158863/88047974-10bafc00-cb85-11ea-8321-0b5f31a8c2d0.png)

2. 优化方案：

	**构建产物大小：**
	
	1. 压缩 JS, CSS：如移除空格，comment 等。
	   现状：JS 使用 terser-webpack-plugin，CSS 使用 optimize-css-assets-webpack-plugin。
	   方案：无需处理。
	
	2. tree shaking：移除未使用代码，如 examples/hello-world 中未使用 store，logger helpers 可移除。
	   现状：未启用。
	   方案：启用 [tree shaking](https://webpack.js.org/guides/tree-shaking/#root)。
	   内置功能依赖包统计：
       
       ![2](https://user-images.githubusercontent.com/26158863/88048371-c8e8a480-cb85-11ea-8638-c422b14ad42c.png)

	
	**构建速度：**
	
	1. 缩小文件处理范围。webpack 只处理需要处理的内容。如 ts-loader 只需处理 ts、tsx 文件，node_modules 无需处理。
	   现状：符合要求。
	   方案：尝试配置 resolveLoaders 及 resolve 加快模块解析速度。
	
	2. 多进程构建：对于耗时较长的操作如 babel-loader ts-loader sass 进行多进程构建。
	   现状：未使用多进程构建。
	   方案：引入 [happypack](https://github.com/amireh/happypack) 进行多进程构建。
	3. 缓存构建产物：对于不常变动的基础代码/库，如 react、react-dom 进行缓存。babel-loader 构建产物进行缓存。
	   现状：react、react-dom 通过 alias 处理，babel-loader 存在缓存。
	   方案：尝试使用 DllPlugin 与 现行方案对比。

**Comment by chenbin92** [comment]
**结论：**

1.  从数据表来看构建产物 .ice 只有 26k 左右，在中后台场景下这个 size 可以忽略不计
2.  构建速度在 hello-world 示例下还是比较慢的，需要优化。

**TODO：**

1. 通过 speed-measure-webpack-plugin 插件分析出具体构建时间的组成，整理成一张数据表
2. 优化手段
   - DLL
   - happypack 
   - esbuild

**Comment by LanceZhu** [comment]
#### 构建时间组成，通过 speed-measure-webpack-plugin 分析：
1. hello-world
	
	![image](https://user-images.githubusercontent.com/26158863/88247493-7cf64680-ccd0-11ea-878c-badd31b1898e.png)

2. fusion-design-pro-ts

	**start**

	![start](https://user-images.githubusercontent.com/26158863/88247546-b16a0280-ccd0-11ea-9ee1-63d18560bb81.png)

	**build**

	
	![build](https://user-images.githubusercontent.com/26158863/88247583-d52d4880-ccd0-11ea-89be-a2c89019003f.png)

3. fusion-design-lite-ts

	**start**
	
	![start](https://user-images.githubusercontent.com/26158863/88248794-f8f28d80-ccd4-11ea-96c8-9a745f3a3b7c.png)

	**build**

	![build](https://user-images.githubusercontent.com/26158863/88248859-31926700-ccd5-11ea-8128-c36368466ac3.png)

**Comment by LanceZhu** [comment]
# icejs 工程构建的优化探索

## 前言

ice.js 工程构建基于 webpack，通过插件对其进行定制和扩展。内置了 typescript、样式方案(Scss, Less, Css Modules)、热更新、代码混淆压缩等工程能力的支持。开发者开箱即用，无需考虑内部实现，从而专注于业务逻辑，提高研发效率。

然而，各种工程能力的支持往往意味着额外代码的引入及处理步骤的增加，与之对应的是构建产物体积的增大及构建时间的增长。随着业务逻辑的复杂化，需要处理的资源越来越多，构建产物体积和构建时间的增长越来越明显。构建时间从最初的几秒中到几分钟、十几分钟，构建产物体积从几十KB到十几MB、上百MB，严重影响研发效率。

为了将工程能力带来的副作用尽可能的减少，本文对 icejs 构建优化进行了探索和尝试。

## 构建质量衡量指标及分析对象

### 衡量指标

**构建速度** 及 **构建产物大小** 分别对应构建过程和构建结果，且较为直观，选为构建质量衡量指标。

### 分析对象

分析对象选择 icejs 最小化场景下的官方示例。

1. [hello-world](https://github.com/alibaba/ice/tree/master/examples/hello-world)

    icejs 最简示例，演示 icejs 基础能力。

2. [Fusion Design Pro TS](https://fusion.design/mc/detail/728?spm=fusion-design.mc-design-fusion.0.0.56c933e6KX9Jpw)

    icejs 结合 fusion design 组件库中的 fusion design pro ts 模板，包含大量 UI 区块，如图表、表单等。

3. [Fusion Design Lite TS](https://fusion.design/mc/detail/740?spm=fusion-design.mc-design-fusion.0.0.4cd233e6qxjZxz)

    icejs 结合 fusion design 组件库中的 fusion design lite ts 模板，仅包含基础布局组件 Layout。

> PS: 在 [飞冰官方模板库](https://ice.work/scaffold/)可找到更多模板 。

## 现状

### 构建分析

对选取的示例进行 **构建产物大小** 和 **构建速度** 进行分析。

分析设备： `Windows10 - wsl ubuntu 18.04`。

#### 构建产物大小

- 构建产物大小表

![构建产物大小表](https://uploader.shimo.im/f/kZVky5tFSnY9t5dc!thumbnail)

#### 构建速度

- 构建速度表

  - hello-world 构建时间组成表：

  ![hello-world 构建时间组成表](https://uploader.shimo.im/f/1AZbGk6oL4hHO81s.png!thumbnail)

  - fusion-design-pro-ts 构建时间组成表：

  ![fusion-design-pro-ts 构建时间组成表](https://uploader.shimo.im/f/crvuqnMm1xaSBbpB.png!thumbnail)

  - fusion-design-lite-ts 构建时间组成表：

  ![fusion-design-lite-ts 构建时间组成表](https://uploader.shimo.im/f/yTzHLUIjjxz5a9W6.png!thumbnail)

### icejs 工程构建现状

#### webpack

版本：`webpack@^4.27.1`

##### 内置 loader

**javascript 相关：**

- `ts-loader` 转译 `typescript`
- `babel-loader` 转译 `javascript` 语言新标准，以兼容不同浏览器

**样式相关：**

- `css-loader`

- `postcss-loader`

- `sass-loader` 处理 `scss` 、 `sass`

- `less-loader` 处理 `less`

- `mini-css-extract-plugin`

##### 内置minimizers: （当构建生产环境下产物时使用）

- `terser-webpack-plugin` 压缩、混淆 `javascript` 代码

- `optimize-css-assets-plugin`

#### 已有优化

- 区分 `开发` 和 `生产环境`

  - 根据 `开发` 和 `生产环境` 设置 `webpack` `mode` 和 `devtool`
  
  - `terser-webpack-plugin` 及 `optimize-css-assets-plugin` 仅在生产环境下使用。

- 限定文件类型，排除 `node_modules` 等无需处理内容。

  ```javascript
  // webpack module rules 处理 tsx 文件
  {
      test: /\.tsx?$/, // 限定文件后缀
      exclude: [ 'node_modules', ...] // 排除处理文件范围
  ],
  ```

- 为 `react` 及 `react-dom` 设置 `alias` 以加速 `webpack` 依赖构建。

  ```javascript
  // webpack resolve alias
  {
      react: 'react_path',
      'react-dom': 'react-dom_path',
      ...
  }
  ```

- `babel-loader` 启用 `cache` 以加速 `webpack` 二次编译。

  ```javascript
  {
      loader: 'babel-loader',
      options: {
          cacheDirectory: true // 对产物启用缓存
      }
  }
  ```

- `terser-webpack-plugin` 启用缓存 + 并行

  ```javascript
  new TerserPlugin({
          cache: true, // 启用缓存
          parallel: true, // 启用并行构建
          ...
      })
  ```

## 优化

### webpack

要对 `webpack` 构建进行优化，首先要理解 webpack 工作原理。

`webpack` 以 `entry` 作为打包入口，构建依赖图，最终输入浏览器可运行的代码。对于 `javascript` 以外的类型如 `ts` ， `tsx` ， `css` 等，可通过 `loader` 进行处理。同时可通过 `plugin` 处理 `loader` 之外的其他任务，如 `html-webpack-plugin` 可生成入口 `html` 文件，并加载 `webpack` 输出文件。

webpack 构建耗时主要产生于 loader 及 plugin 中。

### 构建优化方案

优化方向：使用 **尽可能多的资源**  **更好的** 去处理 **尽可能少的事** 。

>以下方案针对 `icejs` 制定。

1. 缓存构建产物

- [`DllPlugin`](https://webpack.js.org/plugins/dll-plugin/)

  对于不常变动的基础库，使用 `DllPlugin` 预先编译，如 `react` 、 `react-dom` 等。 之后只需构建变动频繁的业务代码，从而减少构建时间。
  
  其作用原理为通过 `DllPlugin` 预先编译，构建 `DLL` 即 动态链接库，`DLL` 内容包括 `react`、`react-dom` 的依赖关系，当需要编译业务代码时，无需再次编译 `react`、`react-dom`，使用 `DllReferencePlugin` 直接加载 `DLL` 以提高编译速度。

- [`hard-source-webpack-plugin`](https://github.com/mzgoddard/hard-source-webpack-plugin)

  `hard-source-webpack-plugin` 将 `webpack` 首次编译时的产物缓存到本地，此后编译时，通过哈希函数验证代码是否有修改，对于无变动的代码，可直接从缓存中读取，无需再次编译，从而减少构建时间。

2. 多进程构建

- [`happypack`](https://github.com/amireh/happypack)

   `webpack` 打包受限于 `node.js` 的单进程模型，无法利用多核的 `CPU` 资源。 `happypack` 的出现则为了解决这一问题。对于耗时较长的 `webpack`  `Loader` 可使用 `happypack` 多进程加速编译。

  > 可根据 `speed-measure-webpack-plugin` 可以得到 `webpack` 中各 `loader` 的时间花费，可对花费时间较长的 `loader` 选择性使用 `happypack` 。

3. 选择更快的 minimizer

- [`esbuild`](https://github.com/evanw/esbuild)

   `esbuild` 基于 `go` ，对 `javascript` 打包时并行处理，保证构建速度。与其他构建工具的对比数据可查看 [esbuild: benchmark](https://github.com/evanw/esbuild#benchmarks)。

4. 移除产物中多余代码

- [webpack tree-shaking](https://webpack.js.org/guides/tree-shaking/)

  对于 `icejs` 中内置的众多能力如 `logger` 、 `request` 、 `helpers` 等，开发者可能并未使用到，但 `icejs` 将能力对应的代码及相应的依赖包含到构建产物中。对于这种情况可通过 `webpack`  `tree-shaking` 在构建阶段移除掉。

  > 本步尚未完成，后续更新可见： [alibaba/ice Issue: 构建产物大小&编译速度优化]([https://github.com/alibaba/ice/issues/3354](https://github.com/alibaba/ice/issues/3354))

### 具体实践

1. `DllPlugin`

    由 *构建产物大小表* 看出：

    - hello-world：总体积(396K)中 `react-dom` (134.29K)、 `core-js` (112.15K)所占比例较大。
    - fusion-design-pro：总体积(2.7M)中 `bizcharts` (672.51K)、 `react-dom` (134.29K)、 `core-js` (112.7K)、 `moment` (61.64K)所占比例较大。
    - fusion-design-lite-ts：总体积(776K)中 `react-dom` (134.29K)、 `core-js` (112.44K)、 `moment` (61.64K)占比较大。

    对于占比较大的产物通过 `DllPlugin` 预先构建，测量再次构建时，构建时间变化。

    **实验**

    对每个示例 start、build、restart 均做3次实验，得到下表：

    ![图片](https://uploader.shimo.im/f/h9SEpQCUsvggD3EW.png!thumbnail)

    使用 `DllPlugin` 后构建速度变化为：

    ![图片](https://uploader.shimo.im/f/zZ3aqwhnX4B6wRH8.png!thumbnail)

    **结论**

    由表中数据可以得出 `DllPlugin` 对于构建开发环境代码包稍有提升，构建生产环境代码包构建时间不减反增。 **`DllPlugin`** **对于构建速度提升不明显。**

    原因分析： `DllPlugin` 对于旧版本 `webpack` 提升较为明显，而 `webpack 4` 本身做了足够的优化， `DllPlugin` 效果不明显。

2. `hard-source-webpack-plugin`

    **实验**

    将 `hard-source-webpack-plugin` 添加进 `webpack` `plugins`。

    构建速度表如下：

    ![图片](https://uploader.shimo.im/f/izjhbx4DjAnTATeL.png!thumbnail)

    速度变化为：

    ![图片](https://uploader.shimo.im/f/A5SRaxX3rK2ynpdm.png!thumbnail)

    **结论**

    由速度变化图看出，对于 `hello-world` 及 `fusion-design-lite-ts`，`hard-source-webpack-plugin` 有小幅提升，而对于 `fusion-design-pro-ts` 速度却有较大下降，原因可能是 `hard-source-webpack-plugin` 缓存内容较多，导致对于缓存的读取耗费较多时间。综合来看，`hard-source-webpack-plugin` 对于构建速度有小幅提升。

3. `happypack`

    由 *构建速度表* 看出

    示例中耗时较长的 `loader` 主要为 `ts-loader` 和 `babel-loader`

    fusion-design-pro-ts 和 fusion-design-lite-ts中耗时较长的还有样式相关的 `loader` : `ice-skin-loader` 、 `sass-loader` 、 `mini-css-extract-loader` 和 `css-loader` 。

    **实验**

    对于 `ts-loader` 使用 `happypack` 进行多进程构建，构建速度数据为：

    > `happypack` 对于其他 `loader` 在测试过程中存在众多问题，尚未完全解决，仅以 `ts-loader` 作为实验说明。

    ![图片](https://uploader.shimo.im/f/xrQNCtuue60X2HqW.png!thumbnail)

    速度变化为：

    ![图片](https://uploader.shimo.im/f/ND7oRemzwBLl10FX.png!thumbnail)

    **结论**

    由图可以看出，对于 fusion-design-lite-ts，使用 `happypack` 后，构建速度均稍有提升。hello-world 及 fusion-design-pro-ts，构建速度未见明显提升。而且由于测量数据存在波动，波动幅度可达5s， `happypack` 对于构建速度提升基本无效。

    原因分析： `happypack` 提供多进程充分利用计算资源加速构建的同时，增加了进程间通信，增加时间消耗，且 `happypack` 当前不再继续优化，仅修复现有 bug。

3. `esbuild`

    **实验**

    使用 `esbuild-webpack-plugin` 替换 `icejs` 中 `terser-webpack-plugin` 。记录构建时间数据，见下表：

    ![图片](https://uploader.shimo.im/f/0IwAoLwM8Ud5lGw7.png!thumbnail)

    速度变化为：

    ![图片](https://uploader.shimo.im/f/GRgHXqyft89yLnk3.png!thumbnail)

    **结论**

    根据速度变化数据得出，使用 `esbuild` 后，各示例 `build` 时间均稍有增加。 `esbuild` 未对构建速度有提升。

    原因分析： `esbuild` 尚处于实验阶段，对于实际生产中的项目还需测试。

## 产品对比

与社区中较为成熟的 `create-next-app` 、 `next.js` 相比较，由下图可以看到 开发环境构建 `start` 及生产环境构建 `build` ，花费时间均为 10s 左右，基本一致。

![产品对比](https://uploader.shimo.im/f/CPma8BF6mQh9eMAh.png!thumbnail)

## 总结

本次对于 icejs 构建优化的探索，选取 hello-world、fusion-design-pro-ts 和 fusion-design-lite-ts 为示例，构建时间及构建产物大小为构建质量标准，尝试使用 `DllPlugin`、`hard-source-webpack-plugin`、`happypack` 及 `esbuild` 进行构建优化，结果对于构建速度的提升均不太明显。原因在于，webpack 4本身做了足够的优化，`DllPlugin` 和 `happypack` 效果不明显，esbuild 仍需测试以在实际项目中取得真正的优化效果。

虽然本文尝试的构建优化方法对于选取示例的构建优化提升均不明显，但也从侧面反映出 webpack 本身的改进。产品对比小节可以看出 icejs 与 next.js 和 create-react-app 在构建速度上持平，反映当前 icejs 的工程构建也做了足够的优化。期待 webpack 进一步的优化和社区中其他优秀方案的产出。

后续进展可见：[alibaba/ice Issue: 构建产物大小&编译速度优化]([https://github.com/alibaba/ice/issues/3354](https://github.com/alibaba/ice/issues/3354))

## 参考及推荐阅读

- [三十分钟掌握Webpack性能优化](https://juejin.im/post/5b652b036fb9a04fa01d616b)

- [Webpack 打包太慢？来试试 Bundleless 吧](https://mp.weixin.qq.com/s/Wr9d6yrNWjrmP8_Sxbmzfw)

- [esbuild](https://github.com/evanw/esbuild)

**Comment by LanceZhu** [comment]
详细优化实践可见：[icejs 工程构建的优化探索](https://www.yuque.com/f00bar/bsa44q/tfsp39)

**Comment by chenbin92** [comment]
已发布 icejs@1.7.0 版本

**Comment by jacktang** [comment]
最终包有什么优化的方案吗？资料 icejs 工程构建的优化探索：https://www.yuque.com/f00bar/bsa44q/tfsp39 需要登录才能访问

**Comment by LanceZhu** [comment]
> 最终包有什么优化的方案吗？比如ice默认是否启用 tree-shaking？
> 
> 资料 icejs 工程构建的优化探索：[yuque.com/f00bar/bsa44q/tfsp39](https://www.yuque.com/f00bar/bsa44q/tfsp39) 需要登录才能访问

更新了文章链接：[icejs 工程构建的优化探索](https://www.yuque.com/docs/share/37e815e9-ba39-44bc-b517-6d0201d9c405)
