### ISSUE TITLE
重新 render 导致 upload 组件显示的已上传图片消失

### ISSUE THREAD

**Issue by Crayon-ShinChan** [alibaba/ice#3365]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

upload 组件在表单中使用时，上传文件后，别的 Form.Item 更新了 useState 的 postData 里面的信息，导致页面重新 render 了一遍，然后 upload 组件下面显示的已上传图片，就消失了。这个要怎么解决呢？

表单信息存在这个里面，`setValue` 一触发就会重新 render 导致 upload 组件显示的已上传图片消失：
```
  const [postData, setValue] = useState({
    title: '',
    detail: '',
    cover: '',
    proposeStart: '',
    voteStart: '',
    voteEnd: '',
    privacyOption: 'realName',
    showProposer: 'false',
  });
```

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

* icejs version：1.6.3
* Node verson：
* Platform：Mac
* `build.json`：
```json
{
  "plugins": [
    [
      "build-plugin-fusion",
      {
        "themePackage": "@alifd/theme-elezoo1"
      }
    ],
    [
      "build-plugin-moment-locales",
      {
        "locales": ["zh-cn"]
      }
    ]
  ]
}

```
* `src/app.(ts|js)`：
```javascript
import { createApp, history } from 'ice';

const appConfig = {
  app: {
    rootId: 'ice-container',
  },
  request: [
    {
      baseURL: 'http://127.0.0.1:7001/api/',
      headers: { Authorization: `Bearer ${localStorage.getItem('jwt-token')}` },
      interceptors: {
        request: {
          onConfig: (config) => {
            // console.log('config', config);
            if (
              localStorage.hasOwnProperty('jwt-token') === false &&
              config.url !== '/user/create'
            ) {
              history.push('/user/login');
            }
            config.headers = {
              Authorization: `Bearer ${localStorage.getItem('jwt-token')}`,
            };
            return config;
          },
        },
        response: {
          onConfig: (response) => {
            // 请求成功：可以做全局的 toast 展示，或者对 response 做一些格式化
            return response.data;
          },
        },
      },
    },
  ],
};
createApp(appConfig);

```

**What is the expected behavior?**

更新表单的 data 之后，upload 组件显示的已上传图片依然存在

**Comment by chenbin92** [comment]
> upload 组件在表单中使用时，上传文件后，别的 Form.Item 更新了 useState 的 postData 里面的信息，导致页面重新 render 了一遍，然后 upload 组件下面显示的已上传图片，就消失了。这个要怎么解决呢？

@Crayon-ShinChan  方便提供一下完整可复现的 DEMO，上面的代码无法排查

**Comment by Crayon-ShinChan** [comment]
> > upload 组件在表单中使用时，上传文件后，别的 Form.Item 更新了 useState 的 postData 里面的信息，导致页面重新 render 了一遍，然后 upload 组件下面显示的已上传图片，就消失了。这个要怎么解决呢？
> 
> @Crayon-ShinChan 方便提供一下完整可复现的 DEMO，上面的代码无法排查

我创建了一个 demo，https://github.com/Crayon-ShinChan/uploadDemo

在这个 demo 里面，upload 上传好之后会触发下面的函数

[https://github.com/Crayon-ShinChan/uploadDemo/blob/ae43cebf6d221ff9f6a6bc3b5732d95175745ac5/src/pages/Dashboard/components/Guide/index.jsx#L26](url)

```javascript
  const uploadSuccess = (value) => {
    const url = value.response.url;
    // console.log(value);
    // console.log(url);
    setValue({ ...postData, cover: url });
  };
```

然后导致 postData 改变，进一步导致 render，然后会发现 upload 下面的已上传图片列表一闪而过，因为重新 render 消失了。

**Comment by bindoon** [comment]
一闪而过，说明受控情况下给upload传递的 value 还是旧的吧！

**Comment by Crayon-ShinChan** [comment]
> 一闪而过，说明受控情况下给upload传递的 value 还是旧的吧！

我没有给 upload 组件设置 value，所以可能是每次 render 之后，导致 upload 组件的 value 被刷新了。

我暂时的解决方案是，给 upload 设置一个 value，然后上传成功之后，把返回的信息存到这个 value 里面，另外还需要定义一下 onRemove 的函数，让用户点击删除的时候，删除 value 中的数据。

但是我个人觉得这种方式非常麻烦很绕，不知道有没有更好的写法。

**Comment by bindoon** [comment]
@行遠 跟进

**Comment by cqcmdwym** [comment]
> > 一闪而过，说明受控情况下给upload传递的 value 还是旧的吧！
> 
> 我没有给 upload 组件设置 value，所以可能是每次 render 之后，导致 upload 组件的 value 被刷新了。
> 
> 我暂时的解决方案是，给 upload 设置一个 value，然后上传成功之后，把返回的信息存到这个 value 里面，另外还需要定义一下 onRemove 的函数，让用户点击删除的时候，删除 value 中的数据。
> 
> 但是我个人觉得这种方式非常麻烦很绕，不知道有没有更好的写法。

貌似只能这样，我也遇到类似的场景
