### ISSUE TITLE
icejs createApp增加初始化生命周期

### ISSUE THREAD

**Issue by Aerojin** [alibaba/ice#3368]
createApp可否增加类似于React的componentDidMount这样的生命周期，用于在主应用启动的时候做一些全局配置或者初始化

```
import { createApp, IAppConfig } from 'ice'

const appConfig: IAppConfig = {
  app: {
    rootId: '__content__',
    onInit: () => {
       // todo 这里可以做一些全局的初始化或者配置
    }
  }
};

createApp(appConfig)
```

**Comment by imsobear** [comment]
现在的 app.getIinitialData 是可以满足你的需求的，可以试一下

**Comment by chenbin92** [comment]
> 在主应用启动的时候做一些全局配置

@Aerojin 具体是想做哪些全局配置

**Comment by chenbin92** [comment]
@Aerojin 目前可以通过具体 app.getIinitialData 做初始化的全局配置，如果有其他诉求和者不满足的可以回复 issue 在重新打开。
