### ISSUE TITLE
物料收集 

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#339]
## 物料定义
在飞冰中，组件、区块、布局、模板等统称为物料，由飞冰团队维护，在内部有一套完整的开发规范和工具，目前也正在逐步对外开放中；基于此，你可以参与共建 ICE，也可以自建私有的物料体系。

* 组件：最基础的物料，目前飞冰的基础组件达到 55+，具有高度可复用性。
* 区块：通过对大量的中后台系统常用的场景进行分类、对比和抽象，基于基础组件组合而成，目前飞冰的区块达到 126+，可以通过 iceworks 进行快速组合搭建应用，减少重复的开发，提升效率。
* 布局：在中后台系统中布局通常较为统一，以 顶部-侧边布局-通栏 模式为主，为此我们提供了 4+ 常见的布局，支持 light 和 dark 两套主题。
* 模板：基于已有的区块搭建而成，目前提供了 4+ 的特定领域的模板，可以从零开始搭建应用，也可以选择特定类型的模板开始使用。

## 物料收集

目前物料部分的迭代主要是区块和模板，会针对不同行业领域设计不同类型的模板，基于不同的模板沉淀出不同的区块，提升物料的可复用效率。

如果你觉得某个区块或者模板我们还没有提供，在实际中又是很常见的场景，你可以在下面回复你的需求，最好是以一段相关的描述和截图说明，我们会进行评估，交由设计师设计，然后产出供大家使用。

**Comment by chenbin92** [comment]
## 提交示例：

**类型**：区块

**标题**：视频列表

**说明**：可以考虑支持视频区块吗，左边是一个视频播放器，右边是视频播放列表，可以点击循环播放，类似 youtube 播放的那种，如下截图所示

![](https://img.alicdn.com/tfs/TB1SlthfwmTBuNjy1XbXXaMrVXa-2350-918.png)

**Comment by yewenxiang23** [comment]
类型：组件

标题：标签

说明：可以删除的那种标签，悬浮显示一个删除按钮。
![2](https://user-images.githubusercontent.com/20874994/37814102-25142c84-2ea3-11e8-9c81-b1d3fa2a3798.gif)

**Comment by chenhongen** [comment]
类型：区块

标题：文档展示

说明：pdf/doc/ppt文档展示。类似http://mozilla.github.io/pdf.js/web/viewer.html。可参考https://github.com/wojtekmaj/react-pdf等。

**Comment by chenbin92** [comment]
@yewenxiang23  已支持

**Comment by chenbin92** [comment]
类型： 区块
标题： Markdown

说明：支持 markdown https://github.com/rexxars/react-markdown

**Comment by Ablegang** [comment]
@chenbin92 支持一下

**Comment by chenbin92** [comment]
类型：区块
标题：表格
说明：支持表头可输入和筛选的表格


![image](https://user-images.githubusercontent.com/3995814/38127995-297b8bcc-342b-11e8-975c-c391788c9e0a.png)

**Comment by yujiangshui** [comment]
@chenbin92 已经支持过的可以把楼删掉，减少信息量

**Comment by v3u3i87** [comment]
现在有没有类似todo的区块，有些中台需要分配任务之类，如果有todo区块可以方便很多。

**Comment by joeyFuck** [comment]
> @v3u3i87 https://alibaba.github.io/ice/#/block/sort-card-list 有类似的 UI

你进去拖一个看看？？？
