### ISSUE TITLE
将 src 改为其他目录名之后页面无法正常渲染

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#3402]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

改动点：

- src -> client
- build.json 里增加 entry: "client/app"
- tsconfig.json 里将 src 改为 client

可以正常 start，但是页面无法渲染（不报错）

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

* icejs version：
* Node verson：
* Platform：
* `build.json`：
* `src/app.(ts|js)`：

**What is the expected behavior?**

**Comment by chenbin92** [comment]
icjes@1.7.2 已支持，该功能不推荐使用，因此没在文档上进行透出
