### ISSUE TITLE
集成formily后，主题变为了深色

### ISSUE THREAD

**Issue by Gamehu** [alibaba/ice#3407]
Do you want to request a feature or report a bug?
feature
What is the current behavior?
基于iceworks创建的项目，**使用的是@alifd/theme-11907主题**，现集成formily表单，npm i styled-components后，页面的主题自动变成深色

 [codesandbox](https://codesandbox.io/s/thirsty-stallman-26zxq?file=/src/App.js)

icejs version：1.6.4-alpha
Node verson：12.18.2
What is the expected behavior?

不影响现有的功能

Test suite failed to run
 
导航栏等变为深色。

![image](https://user-images.githubusercontent.com/10043320/89750741-dac3c480-daff-11ea-9572-a3c0ad98a05c.png)

**Comment by imsobear** [comment]
@Gamehu 因为直接引用了 next 的 css 文件，导致 sass 变量无法生效，改为引用 sass 样式文件即可。

**Comment by Gamehu** [comment]
> @Gamehu 因为直接引用了 next 的 css 文件，导致 sass 变量无法生效，改为引用 sass 样式文件即可。

请问是 改为这样是吗
`import '@alifd/next/index.scss';`

**Comment by imsobear** [comment]
对
