### ISSUE TITLE
私有化部署 Actions

### ISSUE THREAD

**Issue by yujiangshui** [alibaba/ice#341]
## 物料

* [x] 产出物料规范
  * [x] 物料目录结构、类型定义（组件、区块、布局、模板）
  * [x] meta 数据规范、推荐代码规范
  * [x] 物料模板的规范（目录文件和功能、模板字符串等）
  * [x] 物料源 db.json 规范
* [ ] 物料相关文档
  * [x] 私有化物料部署文档教程
  * [ ] npm 私有化部署或者 npm 企业私有服务文档
* [x] 物料开发工具 ice-dev-tools
  * [x] ice-dev init repo 支持选择 react、vue 等
  * [x] ice-dev add [template type] 从上面物料仓库里读取物料模板并进行个性化生成
  * [x] ice-dev start 开启物料源开发界面（类似 def light、storybook）
  * [x] ice-dev publish 目前将物料用 lerna 发布到 npm，未来将发送到 物料 hub 中
  * [x] ice-dev build 基于当前物料信息构建产生标准的物料数据库 db.json 并结合 lite 站点代码构建产生静态物料站点
* [x] Vue 基础物料模板，从 Vue 官方站点拿下最佳实践

## 站点

* [ ] 产出与物料结合的 lite 版本，用于在线预览和简单文档介绍
  * [ ] 支持业务组件透出和托管

## Iceworks

* [x] 支持自定义物料源和物料合并逻辑、界面交互
  - [x] 物料设置项
  - [x] 模板物料展示
	- [x] db.json 文件格式解析
  - [x] 区块选择面板物料源切换
	- [x] 区块选择面板物料合并
  - [x] 模板特征检测，识别 react vue 
* [x] 梳理与物料的耦合点并拆分解耦
  - [x] 创建项目 createProject
  - [x] 新建页面 addPage
	- [x] 路由创建 addRoute
	- 路由操作标准
	- 构建器路由操作（写入 route）
  - [x] 区块下载 addBlocks
	- [x] NPM 依赖安装
  - [x] 创建预览页面  addPreviewPage
  - [x] 移除预览页面 removePreviewPage

====

项目将拆分两期，第一期为最精简接入 Vue 物料路径，将于4月10日开始内测，4月12日正式发布，届时社区可以开始共建 Vue 物料。

第二期则为全量功能，将会提供绝佳的开发体验。

**Comment by lgfinfo** [comment]
迫不及待

**Comment by chenhongen** [comment]
目前对区块涉及的字体图标，如何在离线环境运行的需求比较迫切。。

**Comment by mcuking** [comment]
期待中

**Comment by yujiangshui** [comment]
基础开发链路已经打通并进入公测阶段。如需测试请钉钉联系 浩睿。
