### ISSUE TITLE
NumberPicker 小数点能无限输入, 应该控制只能输入一个, 且不能再开头位置

### ISSUE THREAD

**Issue by j787701730** [alibaba/ice#3419]
![image](https://user-images.githubusercontent.com/23625690/89854219-e974af00-dbc5-11ea-9b60-3456bee5355e.png)
![image](https://user-images.githubusercontent.com/23625690/89854260-09a46e00-dbc6-11ea-8966-b9886f0e9a08.png)
![image](https://user-images.githubusercontent.com/23625690/89854277-15903000-dbc6-11ea-9b57-0f90efc21eac.png)

**Comment by chenbin92** [comment]
@j787701730 已经有 MR 在处理了，预计下周发布 https://github.com/alibaba-fusion/next/pull/2055
