### ISSUE TITLE
Select 组件在mode=tag或者multiple, maxTagCount={1}和tagInline 一起用时无效. 样式也难用

### ISSUE THREAD

**Issue by j787701730** [alibaba/ice#3435]
"@alifd/next": {  "version": "1.20.24",

在配合Form.item 使用时会出现各种问题. select在配置不同属性时宽度和高度会超出form. 
![image](https://user-images.githubusercontent.com/23625690/90113256-a8c29480-dd83-11ea-8c27-3aaced82a3e7.png)
![image](https://user-images.githubusercontent.com/23625690/90113347-ca238080-dd83-11ea-9821-71e33f699140.png)
`<Select defaultValue={['1','2']} dataSource={state} mode="multiple" maxTagCount={1}
              maxTagPlaceholder={maxTagPlaceholder}
              onChange={(val)=>{
                param.state = val
              }}
            />`

在配置maxTagCount={1}和 tagInline无效.
![image](https://user-images.githubusercontent.com/23625690/90113466-f808c500-dd83-11ea-88d5-a6fe91a3e97a.png)
`<Select defaultValue={['1','2']} dataSource={state} mode="multiple" maxTagCount={1} tagInline
              maxTagPlaceholder={maxTagPlaceholder}
              onChange={(val)=>{
                param.state = val
              }}
            />`

**Comment by youluna** [comment]
这个场景下不使用maxTagCount就可以了。另外maxTagCount这个API会在什么场景下使用？使用场景不多的话考虑废弃掉

**Comment by chenbin92** [comment]
与 @youluna 讨论，maxTagCount 属于废弃 API，不推荐使用。
