### ISSUE TITLE
关于配置路由的高阶组件wrappers用法

### ISSUE THREAD

**Issue by RaphielAinsworth** [alibaba/ice#3437]
### 说明
在ice.work官网文档 -> 路由方案 -> 配置式路由 中有描述了一个配置路由协议的高阶组件wrappers，但文档中没具体展示怎么使用或补充说明，请问可否在官网文档补充或者提供下示例demo

**Comment by chenbin92** [comment]
@RaphielAinsworth 已补充文档 https://ice.work/docs/guide/basic/router#wrappers%20%E9%85%8D%E7%BD%AE

**Comment by wildfire810** [comment]
Duplicate of #3518
