### ISSUE TITLE
icejs升级到1.7.0 IAppConfig接口问题

### ISSUE THREAD

**Issue by mopsky** [alibaba/ice#3438]
不知道是不是我哪里操作有问题，升级到1.7.0之后，IAppConfig.auth没了？看文档还是旧的
![image](https://user-images.githubusercontent.com/18085384/90228920-a460af00-de49-11ea-9074-c2cc2d589183.png)

看接口里已经没有auth了
![image](https://user-images.githubusercontent.com/18085384/90228960-b2aecb00-de49-11ea-9ca6-fd948ffe1bb5.png)

而且感觉request?: IRequest; 也有变更？

有没有最新的文档地址发我看下啊，项目都全错了。。。

**Comment by mopsky** [comment]
IAppConfig.request 也不起作用了，以前版本是可以的，现在拦截器进不来，不知道哪里问题；
![image](https://user-images.githubusercontent.com/18085384/90230561-4e413b00-de4c-11ea-9948-193ae0587b7e.png)

**Comment by LanceZhu** [comment]
`build-plugin-ice-auth` 版本是是 `1.7.0` 吗？
可以通过在项目根目录通过 `npm ls` 查看。
```shell
npm ls build-plugin-ice-auth
```

**Comment by mopsky** [comment]
> `build-plugin-ice-auth` 版本是是 `1.7.0` 吗？
> 可以通过在项目根目录通过 `npm ls` 查看。
> 
> ```shell
> npm ls build-plugin-ice-auth
> ```

build-plugin-ice-auth@1.6.3

**Comment by LanceZhu** [comment]
> > `build-plugin-ice-auth` 版本是是 `1.7.0` 吗？
> > 可以通过在项目根目录通过 `npm ls` 查看。
> > ```shell
> > npm ls build-plugin-ice-auth
> > ```
> 
> build-plugin-ice-auth@1.6.3

`build-plugin-ice-auth` 可能忘发布新版本了，稍等下，马上更新。`1.7.0` 为正常版本。

**Comment by LanceZhu** [comment]
`request interceptors` 不起作用吗？能再描述详细些吗？
[examples/basic-request](https://github.com/alibaba/ice/tree/release-next/examples/basic-request) 测试正常。

**Comment by mopsky** [comment]
> `request interceptors` 不起作用吗？能再描述详细些吗？
> [examples/basic-request](https://github.com/alibaba/ice/tree/release-next/examples/basic-request) 测试正常。

app.js
![image](https://user-images.githubusercontent.com/18085384/90237757-6074a680-de57-11ea-94a1-44977d878bc3.png)

![image](https://user-images.githubusercontent.com/18085384/90237830-7f733880-de57-11ea-91a7-89bb975da3b5.png)

request的时候，拦截器没有进入,log没出来，以前1.6.3版本是可以的
![image](https://user-images.githubusercontent.com/18085384/90237881-91ed7200-de57-11ea-89ef-9c82fa649e1a.png)

**Comment by chenbin92** [comment]
@mopsky  auth 类型问题更新下依赖即可。

**Comment by chenbin92** [comment]
@mopsky  request 问题给个可复现的 demo，这边测试没问题。

**Comment by mopsky** [comment]
@chenbin92 试了下request在其他页面是可以的，就是在app.ts入口里调用不生效
![image](https://user-images.githubusercontent.com/18085384/90349255-c46fb880-e06b-11ea-94a0-9b02c3be8b24.png)

以前1.6.3没问题

**Comment by mopsky** [comment]
[test-request.zip](https://github.com/alibaba/ice/files/5081940/test-request.zip)

**Comment by chenbin92** [comment]
> [test-request.zip](https://github.com/alibaba/ice/files/5081940/test-request.zip)
> 
> 入口里的request好像用不到请求配置
> ![image](https://user-images.githubusercontent.com/18085384/90353432-c2602680-e078-11ea-8345-1b9d02da8267.png)

OK

**Comment by mopsky** [comment]
@chenbin92 是的，你可以测试下

**Comment by chenbin92** [comment]
> @chenbin92 已处理，试下 ice.js@1.7.3-0 版本

**Comment by mopsky** [comment]
@chenbin92 1.7.3-0版本测试可以了，感谢

**Comment by chenbin92** [comment]
已发布 1.7.3.0 正式版本
