### ISSUE TITLE
ice.js升级到1.7.1后，使用auth模块js报错

### ISSUE THREAD

**Issue by pingguotailang** [alibaba/ice#3440]
**Do you want to request a *feature* or report a *bug*?**
是
**What is the current behavior?**
ice.js升级到1.7.1后，使用auth模块js报错
![image](https://user-images.githubusercontent.com/41989206/90240617-28bc2d80-de5c-11ea-8ab6-d2d376a23f01.png)
import { useAuth, store } from 'ice';
const [auth, setAuth] = useAuth();//去掉此行代码，报错消失
If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

* icejs version：1.7.1
* Node verson：12
* Platform：windows 谷歌浏览器
* `build.json`：
* `src/app.(ts|js)`：

**What is the expected behavior?**

**Comment by chenbin92** [comment]
结论：用户版本未更新导致。
