### ISSUE TITLE
启动项目，遇到Cannot read property 'map' of undefined问题

### ISSUE THREAD

**Issue by HateTomatoes** [alibaba/ice#3441]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
项目运行icejs start完成后，报错
If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

* icejs version：1.7.1
* Node verson：v12.18.3
* Platform：macbook pro,  chrome 84.0.4147.125
* `build.json`：
```
{
  "plugins": [
    "./build.plugin.js",
    ["build-plugin-antd", {
      "themeConfig": {
        "brand-primary": "#1DA57A"
      },
      "importOptions": {
        "libraryName": "antd-mobile",
        "libraryDirectory": "es",
        "style": true
      }
    }]
  ],
  "proxy": {
    "/file": {
      "enable": true,
      "target": "http://localhost:3200"
    },
    "/api": {
      "enable": true,
      "target": "http://localhost:3200"
    },
    "/webapi": {
      "enable": true,
      "target": "http://localhost:3200"
    },
    "/test": {
      "enable": true,
      "target": "http://localhost:3200"
    }
  },
  "alias": {
    "@utils": "./src/utils/",
    "@components": "./src/components/",
    "@src": "./src/"
  },
  "router": {
    "configPath": "src/routes.js"
  }
}

```
* `src/app.(ts|js)`：
```
app.js

import React from "react";
import {createApp, config} from 'ice';
import VConsole from 'vconsole';
import PageLoading from './components/PageLoading';

require('./config/netConfig');
import './global.css';
// import 'antd-mobile/dist/antd-mobile.css'; // or 'antd-mobile/dist/antd-mobile.less'

console.log('dddd=>', IS_DEBUG);
if(IS_DEBUG){
    var vconsole = new VConsole();
}

// 注意事件冲突
document.body.addEventListener('touchstart', function () { });

// rem适配
const idealViewWidth = window.screen.width;
const BASICVALUE = 1080;
document.documentElement.style.fontSize = `${(idealViewWidth / BASICVALUE) * 100}px`;

Date.prototype.Format = function (fmt) {
    let o = {
        "M+": this.getMonth() + 1, //月份
        "d+": this.getDate(), //日
        "h+": this.getHours(), //小时
        "m+": this.getMinutes(), //分
        "s+": this.getSeconds(), //秒
        "q+": Math.floor((this.getMonth() + 3) / 3), //季度
        "S": this.getMilliseconds() //毫秒
    };
    if (/(y+)/.test(fmt))
        fmt = fmt.replace(RegExp.$1, (this.getFullYear() + "").substr(4 - RegExp.$1.length));
    for (let k in o){
        if (new RegExp("(" + k + ")").test(fmt)) {
            fmt = fmt.replace(RegExp.$1, (RegExp.$1.length == 1) ? (o[k]) : (("00" + o[k]).substr(("" + o[k]).length)));
        }
    }
    return fmt;
};


const appConfig = {
    app: {
        // 可选，是否解析路由组件的查询参数
        parseSearchParams: true,
    },
    router: {
        type: 'browser', // 配置 browser 路由
        fallback: <PageLoading />,
    },
};

createApp(appConfig);

```

**What is the expected behavior?**
正常。

问题描述：
1、由于之前一直在台式mac上开发，没有出现问题；转到另一台Macbook上开发，同一份代码就直接报错；
2、生成.ice文件不一样如下图：

出现问题的.ice目录
![image](https://github.com/HateTomatoes/resources/blob/master/%E6%9C%89%E9%97%AE%E9%A2%98%E7%9A%84Ice.jpg)

未出现问题的.ice目录
![image](https://github.com/HateTomatoes/resources/blob/master/%E6%B2%A1%E9%97%AE%E9%A2%98%E7%9A%84ice.JPG)

3、web报错如下：
```
Uncaught TypeError: Cannot read property 'map' of undefined
    at __updateRouterMap (router.js:143)
    at new MiniAppHistory (History.js:25)
    at Object.createMiniAppHistory (index.js:14)
    at createHistory (history.js:22)
    at miniappRenderer (miniappRenderer.js:41)
    at runApp (runApp.ts:56)
    at Module../src/app.js (app.js:58)
    at __webpack_require__ (bootstrap:837)
    at fn (bootstrap:129)
    at Object.1 (utils.js:87)
    at __webpack_require__ (bootstrap:837)
    at bootstrap:1016
    at bootstrap:1016
```
像是没有读取到路由目录

routes.js 
```
import Entry from "./pages/Entry";

const routerConfig = [
    {
        path: '/entry',
        component: Entry,
    },
];

console.log('123!@#!@#!@#!@#!@#!@#!@#!@#');

export default routerConfig;
```

**Comment by chenbin92** [comment]
@HateTomatoes 麻烦一个一个最小可复现的 demo 。 生成的 .ice 文件在 1.6.3 和 1.6.7 是有变化的，但是功能都是完全兼容的

**Comment by HateTomatoes** [comment]
> @HateTomatoes 麻烦提供一个最小可复现的 demo 。 生成的 .ice 文件在 1.6.3 和 1.6.7 是有变化的，但是功能都是完全兼容的

https://github.com/HateTomatoes/TestForIce
demo代码已上传

**Comment by LanceZhu** [comment]
@HateTomatoes 排查了下。

**原因**

[`icejs@1.7.0`](https://github.com/alibaba/ice/releases/tag/1.7.0) 版本引入对小程序开发的支持。复现 demo 中引入的 [https://res.wx.qq.com/open/js/jweixin-1.6.0.js](https://github.com/HateTomatoes/TestForIce/blob/master/public/index.html#L11) 导致 `icejs` 判断当前代码运行环境为微信小程序。

**解决方案**

1. 如果未使用引入的 [https://res.wx.qq.com/open/js/jweixin-1.6.0.js](https://github.com/HateTomatoes/TestForIce/blob/master/public/index.html#L11) ，可删除。
2. 如果该项目是进行微信小程序开发，可直接通过 `icejs` 直接[开发小程序](https://ice.work/docs/miniprogram/start)

**问题**

引入的 [https://res.wx.qq.com/open/js/jweixin-1.6.0.js](https://github.com/HateTomatoes/TestForIce/blob/master/public/index.html#L11) 作用是什么。

**Comment by HateTomatoes** [comment]
@LanceZhu
目前并不是开发微信小程序，而是微信H5页面。
 
https://res.wx.qq.com/open/js/jweixin-1.6.0.js 该链接是支持开通微信支付分必须的引用，由于功能需要并无法删除。

请问有没有其他解决方案呢？

**Comment by chenbin92** [comment]
> 复现 demo 中引入的 https://res.wx.qq.com/open/js/jweixin-1.6.0.js 导致 icejs 判断当前代码运行环境为微信小程序

@LanceZhu 具体是那个环境变量引起的 ？

**Comment by LanceZhu** [comment]
环境变量：`wx` `wx.` 具体判断逻辑在 [`universal-env`](https://unpkg.com/browse/universal-env@3.2.0/src/index.ts)。

`icejs` 相关代码：[plugin-app-core runApp.ts.ejs](https://github.com/alibaba/ice/blob/master/packages/plugin-app-core/src/generator/templates/common/runApp.ts.ejs#L2)

**Comment by chenbin92** [comment]
@HateTomatoes ice.js@1.8.1 已修复
