### ISSUE TITLE
使用 icejs 开发一套小程序模板和后台管理系统

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#3443]
## 背景

目前 GitHub 上小程序类模板大多数都还是在使用原生的小程序语法进行编写，其后台管理则使用 React 或者 Vue 进行开发，这对于同时有小程序和后台管理系统开发的团队来说，意味着多端技术的不一致性和学习成本，有没有可能我们只使用 Vue 或者 React 类技术就能同时开发，答案肯定是有的。

对于使用过 icejs 的大多数人而言，大部分场景是用来开发中后台管理类的系统，但在 icejs 1.7.0 版本中，已经支持使用 icejs + React 开发小程序，目前支持的小程序平台包括微信小程序和支付宝小程序。**这意味着你如果想开发小程序和一套后台管理系统，那么你只需使用 icejs 就够了。**  这在一定程度上能极大的提升开发效率、以及多端一致的开发体验。

使用 icejs 开发小程序，可以一次编码多端(微信、支付宝、Web)投放，更重要的是，可以无需学习各个平台的小程序语法，只要你会使用 React、即可开发小程序。

## 目标

使用 icejs 开发一套小程序模板和后台管理系统

## 技术栈

- 前端
   - 框架：React.js
   - 应用框架：icejs
   - UI 组件：Fusion Design、小程序组件库
- 服务端
   - Node 框架：Midway/egg
   - ORM 框架：Sequelize
   - 数据库：MongoDB/MySQL

## 相关参考

- [litemall](https://github.com/linlinjava/litemall)
- [nideshop-mini-program](https://github.com/tumobi/nideshop-mini-program)
- [mall-admin-web](https://github.com/macrozheng/mall-admin-web)
- [wechat-app-mall](https://github.com/EastWorld/wechat-app-mall)

**Comment by chenbin92** [comment]
@LanceZhu  看下上面的需求

**Comment by LanceZhu** [comment]
## 功能列表

### 电商小程序

- 首页（搜索功能、分类展示）
- 商品详情页
- 购物车
- 个人页（订单、收藏、地址、账户）

### 后台管理系统

- 商品管理（列表、添加、删除、编辑、分类）

- 会员管理（权限）

- 订单管理

- 首页（统计报表）


## 开发排期

**2周（2020/8/17-2020/8/31）**

---

- [ ] 2天（8/17-8/18)：小程序首页、商品详情页

- [ ] 2天（8/19-8/20)：小程序购物车、个人页

- [ ] 1天（8/21）：小程序整体梳理

---

- [ ] 2天（8/24-8/25)：后台首页、商品管理

- [ ] 2天（8/26-8/27)：会员管理、订单管理

- [ ] 1天（8/28）：后台整体梳理

---

- [ ] 1天（8/31）：项目整体梳理

**Comment by jacktang** [comment]
能否给出一个使用飞冰开发chrome extension的模板或者例子?

**Comment by usercao** [comment]
路由拦截功能能否跟进👍

**Comment by chenbin92** [comment]
> 能否给出一个使用飞冰开发chrome extension的模板或者例子?

暂时没这块的计划，你可以试着贡献一个，在开发过程中如果有 icejs 相关的技术支持，可以保持沟通。

**Comment by chenbin92** [comment]
> 路由拦截/导航守卫能否跟进👍

可以先用 [wrappers 的方式](https://ice.work/docs/guide/basic/router#wrappers%20%E9%85%8D%E7%BD%AE) 实现路由拦截。

完整的路由拦截方案在下个版本迭代实现。

@usercao 在 issue https://github.com/alibaba/ice/issues/3199 讨论。

**Comment by Tenodec** [comment]
去年那时候 remaxjs就已经出来了啊
