### ISSUE TITLE
create-ice 部分依赖已经停止维护

### ISSUE THREAD

**Issue by usercao** [alibaba/ice#3457]
![image](https://user-images.githubusercontent.com/13760476/90586514-f61e8600-e209-11ea-997a-29ad62fd5357.png)
![image](https://user-images.githubusercontent.com/13760476/90586537-0171b180-e20a-11ea-90ae-d6d27160659f.png)
是否会对项目构建造成影响？

**Comment by imsobear** [comment]
- create-ice 是创建项目用的，跟开发构建没关系
- 这个依赖过期不影响正常使用，我们后面排期升级掉

**Comment by usercao** [comment]
@imsobear 还有GitHub与npm版本不一致，一个是1.7.2一个是1.7.3

**Comment by imsobear** [comment]
@usercao GitHub 哪个版本？没懂

**Comment by usercao** [comment]
![image](https://user-images.githubusercontent.com/13760476/90601718-35110380-e22b-11ea-982c-39d0d826b0fc.png)
![image](https://user-images.githubusercontent.com/13760476/90601812-596ce000-e22b-11ea-8b98-45346e6a38f2.png)
@imsobear 这个

**Comment by imsobear** [comment]
GitHub 上 release 的是 ice.js 这个主包，不是 create-ice 这个包，create-ice 只是创建项目的一个小包。

**Comment by usercao** [comment]
哦哦，了解了thanks

**Comment by chenbin92** [comment]
非核心链路，基础依赖不影响功能使用，暂时不考虑升级
