### ISSUE TITLE
支持工程配置调试日志

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#3458]
## 需求

在某些场景下用户在 `build.json` 中配置相应的配置项后，工程构建时配置不生效。导致排查问题时无法感知配置的规则是否符合预期，以及不易排查问题。

## 方案

支持通过 `icejs start --debug` 时输出用户的配置合并的日志信息

**Comment by jacktang** [comment]
希望可以加上route 匹配的日志

**Comment by chenbin92** [comment]
> 希望可以加上route 匹配的日志

@jacktang   怎样的形式 ？ 我理解 route 匹配是运行时的逻辑，无法在控制台输出的吧

**Comment by jacktang** [comment]
@chenbin92 我的理解是 `icejs start --debug` 运行后，那么就覆盖了 `app.jsx` 中的 logger.level 配置项，这时候可以往 logger里面输出 `routes.js` 匹配到的url的日志信息？或许我误解了你提的feature。

**Comment by chenbin92** [comment]
> @chenbin92 我的理解是 `icejs start --debug` 运行后，那么就覆盖了 `app.jsx` 中的 logger.level 配置项，这时候可以往 logger里面输出 `routes.js` 匹配到的url的日志信息？或许我误解了你提的feature。

不太一样，这个 issue 是希望在终端里输出  webpack 的配置。你这个是在 chrome devtools 里输出运行时的日志

**Comment by chenbin92** [comment]
已发布 ice.js@1.9.1 版本支持
