### ISSUE TITLE
dll 构建失败

### ISSUE THREAD

**Issue by LanceZhu** [alibaba/ice#3459]
## 问题及方案

1. `dllEntry` `key` 需符合 `JavaScript` 变量要求，不包含特殊字符 `- @ /`。
	原因为 `key` 作为 `library` 名称：[plugin-react-app](https://github.com/alibaba/ice/blob/master/packages/plugin-react-app/src/userConfig/dll.js#L61)

	```json
	{
	  "dll": true,
	  "dllEntry": {
		"vendor-a": ["react", "react-dom"]
	  }
	}
	```
	
	上面 `vendor-a` 不符合要求，可改为 `vendor_a`
	
	解决方案：对 `dllEntry` `key` 进行转义。

2. dll 构建错误信息输出

	现有只包含 `Webpack` 配置错误。相关代码：[plugin-react-app](https://github.com/alibaba/ice/blob/master/packages/plugin-react-app/src/userConfig/dll.js#L78)
	错误输出逻辑参考：[Webpack#error-handling](https://webpack.js.org/api/node/#error-handling)

**Comment by chenbin92** [comment]
@LanceZhu `.library('_dll_[name]')` 这里的 library 命名为 `_dll_[name]` 是有什么考虑吗

**Comment by LanceZhu** [comment]
只是为了将不同 `entry` 进行区分。

`react` -> `_dll_react`

`antd` -> `_dll_antd`

**Comment by chenbin92** [comment]
已发布
