### ISSUE TITLE
启动项目报错

### ISSUE THREAD

**Issue by trivialmonster** [alibaba/ice#3461]
![image](https://user-images.githubusercontent.com/27729745/90721962-79180d00-e2ec-11ea-8536-d20a34d2618e.png)

不管是vscode的Iceworks创建项目还是npm init ice <projectName>都会报错，啥都没改...

![image](https://user-images.githubusercontent.com/27729745/90722131-cb592e00-e2ec-11ea-961d-0f6b018ef809.png)

不知道怎么解决？

**Comment by chenbin92** [comment]
@trivialmonster  执行 `npm ls ice.js` 看下，确认使用的是 ice.js@1.7.3 的版本。

建议操作：

1. 手动删除 node_modules 文件夹
2. 重新安装 node_modules

**Comment by trivialmonster** [comment]
ice.js 1.7.2 有影响么 
删除node_modules文件夹重装 结果还是报错的，没啥用。
不知道对node，npm版本有要求么，我就看到npm起码 6.x
* node 10.15.3
* npm 6.4.1

**Comment by imsobear** [comment]
1.7.2 是个有 bug 的版本，我们前天发了 1.7.3 的版本，`npm view ice.js` 看下有没有同步到 1.7.3 版本。

**Comment by trivialmonster** [comment]
谢谢，切换到1.7.3就没问题了。
