### ISSUE TITLE
状态管理文档优化

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#3473]
## 需求

[状态管理](https://ice.work/docs/guide/basic/store) 作为 icejs 使用较多的能力之一，因为在实现时通过文件约束为用户简化了使用 store 的流程，其中有一些黑魔法，导致用户在使用时会产生困惑。同时在复杂场景下不支持多个页面配置单独的 store 等问题。

## 预期

- 对状态文档进行优化，一步一步引导用户使用全局状态、页面状态的完整示例。（复制粘贴即可跑通）
- 通过文档降低答疑成本

**Comment by cqcmdwym** [comment]
👀

**Comment by chenbin92** [comment]
@cqcmdwym  可以看下 https://github.com/alibaba/ice/pull/3484

**Comment by chenbin92** [comment]
done
