### ISSUE TITLE
Module '"../../../.ice"' has no exported member 'useAuth'.

### ISSUE THREAD

**Issue by cqcmdwym** [alibaba/ice#3478]
**Do you want to request a *feature* or report a *bug*?**
bug?
**What is the current behavior?**

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

* icejs version：1.4.0
* Node verson：
* Platform：
* `build.json`：
* `src/app.(ts|js)`：

**What is the expected behavior?**

似乎生成的.ice 文件夹没有把auth给export出来

**Comment by chenbin92** [comment]
@cqcmdwym  ice.js 升级到最新版本 1.8.0

**Comment by cqcmdwym** [comment]
@chenbin92 嗯，升级到1.8.0的确好了，1.4的bug？谢谢
