### ISSUE TITLE
ice.work 访问不了  index.window.min.js 文件加载不到

### ISSUE THREAD

**Issue by aqrun** [alibaba/ice#3479]
如题。 https://g.alicdn.com/code/npm/@ali/icedesign-base-site/0.2.4/dist//index.window.min.js  这个文件404

**Comment by chenbin92** [comment]
@aqrun  检查下是否设置了代理什么的。

![image](https://user-images.githubusercontent.com/3995814/91247555-1e1b6580-e785-11ea-87da-611534f07cdc.png)
