### ISSUE TITLE
basic-ssr project can't find module: basic-ssr\build\server\index.js 

### ISSUE THREAD

**Issue by aqrun** [alibaba/ice#3483]
求助
win10 node 12.16

![图片](https://user-images.githubusercontent.com/4224867/91373255-7f583d00-e848-11ea-945f-6ec4e53cbcce.png)
![图片](https://user-images.githubusercontent.com/4224867/91373283-94cd6700-e848-11ea-81ee-0dcd87250bb1.png)
![图片](https://user-images.githubusercontent.com/4224867/91373313-a44cb000-e848-11ea-8966-2edfcd95ab76.png)

**Comment by aqrun** [comment]
build 就好了

**Comment by chenbin92** [comment]
@aqrun  看下是否有正常生成 build 文件

![image](https://user-images.githubusercontent.com/3995814/91374138-27223a80-e84a-11ea-8d39-772f70053b26.png)

**Comment by aqrun** [comment]
有的都正常
