### ISSUE TITLE
页面的 Model 在单页应用中路由切换后回到初始化状态

### ISSUE THREAD

**Issue by alvinhui** [alibaba/ice#3491]
## 问题描述

在单页面应用中，

- Pa 页面有 Store - Sa，Sa 内有 Model - Ma，Ma 内有 todos 状态，会在用户触发某些交互后，填充数据
- 用户从 Pa 页面点击某个链接，跳到 Pb 页面
- 用户从 Pb 页面点击某个链接，跳到 Pa 页面
- 这时候 Pa 页面的 Sa 内的 Ma 的 todos 里仍有老数据

**Comment by chenbin92** [comment]
@alvinhui  具体是什么问题，详细描述下场景 ？

**Comment by ClarkXia** [comment]
支持通过配置 `store.resetPageState` 恢复到初始状态
