### ISSUE TITLE
[RELEASE] rax-app & icejs 9月计划

### ISSUE THREAD

**Issue by SoloJiang** [alibaba/ice#3495]
## 状态管理
- [x] icejs@1.9.0 发布支持 -  9/3

### app

- [x] ErrorBoundary
- [x] parseSearchParams
   rax 不支持该配置项，直接默认支持，并支持 `getSearchParams`
- [x] addProvider
- [ ] 配置 rootId
- [ ] 配置 mountNode

### router

- [x] type
- [x] basename
- [x] fallback
- [x] history
- [x] withRouter

### request

- [ ] 待方案

### 环境配置

- [ ] 待方案

### 其他
- [x] 2.x tabbar navigation 迁移

## itrace

- [ ] 待方案 @思忠

## 工程优化

- [ ] Explore Bundless

## 构建产物

- [ ] SSR，MPA，SPA 方案和策略 @思忠 @弗申

## Web App Framework

- [ ] 页面自动保活销毁机制

**Comment by usercao** [comment]
路由拦截/导航守卫没有计划吗？
