### ISSUE TITLE
Store 支持页面多级目录嵌套

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#3502]
## 全局状态

1. 目录结构

```md
src
├── models               // 全局 store
|   ├── a.ts
│   └── b.ts
```

2. model 定义

```ts
export default {
  state: { },
};
```

3.  model 消费

对于全局状态的情况，框架会默认在应用最外层包裹一层 Provider，因此只需要直接调用 store 即可，使用方式如下：

```tsx
// 从 ice 中引入 store
import { store as appStore } from 'ice'

export default () => {
  const [ state, dispatchers ] = appStore.useModel('xxx')
}
```

## 非嵌套页面

1. 目录结构

```md
src
├── pages
|   ├── Home              // 非嵌套页面
|   │   ├── models/
|   |   │   ├── modelA.ts
|   |   │   └── modelB.ts
|   │   ├── index.tsx
|   │   └── store.ts
```

2. store 定义

```ts
import { createStore } from 'ice';
import modelA from './models/modelA';
import modelB from './models/modelB';

const store = createStore({ a: modelA, b: modelB });

export default store;
```

3.  model 消费

对于简单非嵌套的情况，框架会默认为页面包裹一层 Provider，因此只需要直接调用 store 即可，使用方式如下：

```tsx
// 从 ice 中引入 store
import { store as pageStore } from '@/pages/Home/store'

export default () => {
  const [ state, dispatchers ] = pageStore.useModel('a')
}
```

## 嵌套页面

* 目录结构

```md
src
└── pages
│   ├── Home      // 嵌套页面状态
│   │   ├── A        
│   │   ├── B
│   │   ├── Layout
│   │   ├── models
│   │   │   ├── modelA.ts
│   │   │   └── modelB.ts
│   │   └── store.ts
```

* 使用状态

1. model 定义

```ts
export default {
  state: { },
};
```

2. store 定义

```tsx
import { createStore } from 'ice';
import modelA from './modelA';
import modelB from './modelB';

const store = createStore({ a: modelA, b: modelB });

export default store;
```

3. model 消费

```tsx
import React from 'react';

// 引用自定义的 store
import pageStore from '@/pages/Home/store';

export default () => {
  const [state, dispatchers] = appStore.useModel('xxx');
};
```

## 兼容

* 目录结构

```md
src
├── pages
|   ├── Home
|   │   ├── index.tsx
|   │   └── models
|   |   │   ├── a.ts
|   |   │   └── b.ts
```

*  model 消费

对于老的从 `ice/PageName` 的引用方式需要兼容

```diff
// 从 ice 中引入 store
+import { store as pageStore } from 'ice/Home'

export default () => {
  const [ state, dispatchers ] = pageStore.useModel('xxx')
}
```

**Comment by chenbin92** [comment]
@SoloJiang  看下上述方案

**Comment by ClarkXia** [comment]
目录结构中建议不要默认将 `pages` 目录和 routes.ts 作为规范约束，`pages` 下的目录结构相对比较直观清晰，没必要再引入一层 `pages` 进行嵌套，规范上所有的组件文件夹名首字母大写 layout -> Layout

```
src
├── models               // 全局 store
|   ├── counter.ts
│   └── user.ts
└── pages
│   ├── Home 
│   │   ├── A        
│   │   ├── B
│   │   ├── Layout
│   │   └── models
```

**Comment by chenbin92** [comment]
> 目录结构中建议不要默认将 `pages` 目录和 routes.ts 作为规范约束，`pages` 下的目录结构相对比较直观清晰，没必要再引入一层 `pages` 进行嵌套，规范上所有的组件文件夹名首字母大写 layout -> Layout
> 
> ```
> src
> ├── models               // 全局 store
> |   ├── counter.ts
> │   └── user.ts
> └── pages
> │   ├── Home 
> │   │   ├── A        
> │   │   ├── B
> │   │   ├── Layout
> │   │   └── models
> ```

1. 目录规范 +1
2. 二级页面新增 routes.ts 的意义上面已经说了，如果不新增则用户的代码如下：

```ts
import Layout from '@/layouts/index';

// 其中一组
import PageHomeLayout from '@/pages/Home'
import A from '@/pages/Home/A';
import B from '@/pages/Home/B';
import C from '@/pages/Home/C';

export default [
  // 此处实际省略 4 * 5 = 20 行代码
]
```

新增 routes.ts

```ts
import Layout from '@/layouts';
import homePageRoutes from '@/pages/Home/routes';

export default [
  {
    path: '/',
    component: Layout,
    children: [
      // 二级路由合并
      ...homePageRoutes,  // 执行一行代码
    ]
  }
];
```

这里的想法是通过二级路由提升 `src/routes.ts` 的可维护性，如果去掉这个问题怎么解，还是忽略不管。

**Comment by SoloJiang** [comment]
### 目前
现有页面级状态管理方案的能力：
```bash
src
├── models               // 全局 store
|   ├── counter.ts
│   └── user.ts
└── pages
│   ├── Home 
│   │   ├── index       
│   │   ├── store.ts
```
用户可以在 `store.ts` 里返回一个 `store`，然后研发框架会将用户 `Home/index` 这个页面的代码拷贝到 `.ice` 临时目录下，然后在页面组件外层套一个 `<Provider></Provider>`

### 存在的问题
当存在多级嵌套页面的时候，研发框架无法解析到二级页面的路径，从而无法将二级页面的代码复制到 `.ice` 目录下，导致自动包裹 `Provider` 这一步无法实现

### 方案
现有 `routes.ts` 的设计并不是完全没办法通过 `app.json` 的形式静态化掉，如果能够将页面配置静态化掉，可以给用户在创建页面的时候更大的自由度（也可以推荐目录结构的最佳实践）。并且带来的收益是，可以明确知道每一个页面源码来源，从而降低并且通过 AST 解析 `routes.ts` 带来的负担。

#### 二级页面
```bash
src
├── models               // 全局 store
|   ├── counter.ts
│   └── user.ts
└── pages
│   ├── Home 
│   │   ├── A        
│   │   ├── B
│   │   ├── Layout
│   │   └── store.ts
```

**app.json:**
```json
{
  "routes": [
    {
      "path": "/home/a",
      "source": "pages/Home/A"
    },
    {
      "path": "/home/b",
      "source": "pages/Home/B"
    }
  ],
}
```

由于可以解析到每个二级页面的地址，就可以在将二级页面拷贝到 `.ice` 之后，每个页面引入 `pages/Home` 一级目录下的 `store.ts`然后就可以实现自动包裹 `Provider` 的能力

**Comment by SoloJiang** [comment]
以上方案是针对，「规范约束」的角度思考的，研发框架可以提供一些规范约束，但是如果过于繁琐的话，可能会导致学习成本上升

**Comment by SoloJiang** [comment]
以上方案是针对，「规范约束」的角度思考的，研发框架可以提供一些规范约束，但是如果过于繁琐的话，可能会导致学习成本上升

**Comment by chenbin92** [comment]
综上：

1. 目录结构达成一致意见最终如下：

```md
src
├── models               // 全局 store
|   ├── counter.ts
│   └── user.ts
└── pages
│   ├── Home 
│   │   ├── A        
│   │   ├── B
│   │   ├── Layout
│   │   └── models
```

2. 对于路由是否按照页面划分是用户可选择的能力，框架上推荐使用集中式管理，保持现状。
3. 对于 @SoloJiang 的方案本质是通过 app.json 静态化解决了 AST 解析路由的成本，但是改变了现有路由管理模式，和现有方案开发习惯偏差较大，个人不建议在 icejs 中采用。

**Comment by imsobear** [comment]
从最佳实践的角度看，嵌套和非嵌套是不是一致？主要几个点：

1. model 是否需要开发者自行在 `models/index.ts` 里注册？是，这个应该没疑问
2. Provider 是否需要开发者在 `index.ts` or `Layout/index.ts` 里包裹？这里貌似还没完全一致

**Comment by chenbin92** [comment]
## 完整的 Store 方案

## 全局状态

```md
src
├── models               // 全局 store
|   ├── counter.ts
│   └── user.ts
```

*  model 消费

对于全局状态的情况，框架会默认在应用最外层包裹一层 Provider，因此只需要直接调用 store 即可，使用方式如下：

```tsx
// 从 ice 中引入 store
import { store as appStore } from 'ice'

export default () => {
  const [ state, dispatchers ] = appStore
}
```


## 非嵌套页面

* 目录结构

```md
src
├── pages
|   ├── Home
|   │   ├── index.tsx
|   │   └── model.ts     // 非嵌套页面
```

*  model 消费

对于简单非嵌套的情况，框架会默认为页面包裹一层 Provider，因此只需要直接调用 store 即可，使用方式如下：

```tsx
// 从 ice 中引入 store
import { store as pageStore } from 'ice/Home'

export default () => {
  const [ state, dispatchers ] = pageStore
}
```

## 嵌套页面

* 目录结构

```md
src
└── pages
│   ├── Home 
│   │   ├── A        
│   │   ├── B
│   │   ├── Layout
│   │   └── models  // 嵌套页面状态
```

* 使用状态

对于复杂嵌套的情况，需要开发者自行为页面包裹一层 Provider，调用 store 的使用方式如下：

1. model 定义

export default {
  state: { },
};

2. store 定义

```tsx
import { createStore } from 'ice';
import modelA from './modelA';
import modelB from './modelB';

const store = createStore({ a: modelA, b: modelB });

export default store;
```

3. model 消费

```tsx
import React from 'react';

// 引用自定义的 store
import pageStore from '@/pages/Home/models';

export default () => {
  const [state, dispatchers] = appStore.useModel('xxx');
};
```

**Comment by SoloJiang** [comment]
1. 上面的 demo 代码好像没有看到开发者自行包裹 `Provider` 的示例，从开发直觉来看，如果使用上存在嵌套和非嵌套的差异可能难以理解
2. icejs 本身就提供了 `app.json` 和 `routes.ts` 两种用法，前者是给无线开发使用，后者是给中后台开发使用，那这个使用差异本身是不是合理的？
3. 如果按照上面的设计方案，rax-app 和 icejs 应该需要区分两个插件来做，因为 rax-app 基于上述 `app.json` 的方式，可以比较容易实现无感的嵌套路由状态管理

**Comment by chenbin92** [comment]
> 从最佳实践的角度看，嵌套和非嵌套是不是一致？主要几个点：
> 
> 1. model 是否需要开发者自行在 `models/index.ts` 里注册？是，这个应该没疑问
> 2. Provider 是否需要开发者在 `index.ts` or `Layout/index.ts` 里包裹？这里貌似还没完全一致


1.  是
2. 最好的方式是 Layout 的 Provider 也能由框架包裹，这样保证了嵌套和非嵌套的使用方式的一致性

**Comment by chenbin92** [comment]
> 1. 上面的 demo 代码好像没有看到开发者自行包裹 `Provider` 的示例，从开发直觉来看，如果使用上存在嵌套和非嵌套的差异可能难以理解
> 2. icejs 本身就提供了 `app.json` 和 `routes.ts` 两种用法，前者是给无线开发使用，后者是给中后台开发使用，那这个使用差异本身是不是合理的？
> 3. 如果按照上面的设计方案，rax-app 和 icejs 应该需要区分两个插件来做，因为 rax-app 基于上述 `app.json` 的方式，可以比较容易实现无感的嵌套路由状态管理

1. 嵌套和非嵌套的主要差异在于是否包 Provider，初步判断可以实现，需要具体代码验证下
2. 3 对于 `routes.ts` 和 `app.json` 是两种模式，目前中后台还是保持兼容 `routes.ts` 的方式，然后分开两个插件实现：
  * build-plugin-ice-store：支持现有 `routes.ts` 和 store 的使用和解析
  * build-plugin-xx-store：支持 `app.json` 和 store 的使用和解析

**Comment by chenbin92** [comment]
ice.js@1.9.7 已发布
