### ISSUE TITLE
css网络资源本地化配置后，还会有一个字体的js外部请求

### ISSUE THREAD

**Issue by pingguotailang** [alibaba/ice#3508]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
css网络资源本地化配置后，还会有一个字体的js外部请求
If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
1 安装"build-plugin-css-assets-local": "^0.1.0",
2 build.json增加配置项
[
			"build-plugin-css-assets-local",
			{
				"outputPath": "assets",
				"relativeCssPath": "../",
				"activeInDev":true
			}
		]
3 npm start
4 访问站点，发现network请求中发送了一条Request URL: http://at.alicdn.com/t/font_1432938_rde8zgqgx4l.js

* icejs version：1.9.0
* Node verson：v12.18.3
* Platform：
* `build.json`：
* `src/app.(ts|js)`：

**What is the expected behavior?**
希望本地化css配置后，没有外网请求

**Comment by ClarkXia** [comment]
这个 js 请求并不是 css 中发起的，fusion 的 Icon 组件会默认加载 svg 相关的脚本，这个脚本可以自定义路径，详见 https://ice.work/component/icon#%E4%BD%BF%E7%94%A8%E5%85%B6%E4%BB%96%E6%BA%90%E7%9A%84%E5%9B%BE%E6%A0%87
