### ISSUE TITLE
dynamic-icon create 出来的 CustomIcon 组件是 stateless 组件，在部分组件下可能会产生报错

### ISSUE THREAD

**Issue by yujiangshui** [alibaba/ice#351]
![image](https://user-images.githubusercontent.com/2942913/37894090-9a0eef06-310f-11e8-94a6-baa4202596e4.png)
![image](https://user-images.githubusercontent.com/2942913/37894097-a42ca9d8-310f-11e8-8fa6-1f821ea42390.png)

原因：balloon 对 trigger 会通过 ref 的方式获取 DOM 或者绑定事件。

**Comment by wssgcg1213** [comment]
我修复一个版本改成正常组件好了

**Comment by chenbin92** [comment]
dynamic-icon 1.x 版本已不推荐使用，旧版本已修复
