### ISSUE TITLE
Tree组件dataSource使用models中的state数据初始化失败

### ISSUE THREAD

**Issue by we6288815** [alibaba/ice#3510]
**Do you want to request a *feature* or report a *bug*?**
这是一个bug

**What is the current behavior?**
Tree组件dataSource使用models中的state数据初始化失败，控制台报错：
Uncaught TypeError: Cannot add property pos, object is not extensible

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
在models中定义的state，在Tree组件提供给dataSource时，无法渲染，而同样的数据，在非store中的数据可以正常渲染
![image](https://user-images.githubusercontent.com/8169722/92427349-d225e300-f1be-11ea-93f8-0655e3e38645.png)
![image](https://user-images.githubusercontent.com/8169722/92427350-d225e300-f1be-11ea-9247-5eae130a9f58.png)

* icejs version：^1.9.0
* Node verson：^1.9.0
* Platform：Windows 10 x64
* `build.json`：

```json
{
  "proxy": {
    "/**": {
      "enable": true,
      "target": "http://127.0.0.1:8888"
    }
  },
  "plugins": [
    [
      "build-plugin-fusion",
      {
        "themePackage": "@alifd/theme-ice"
      }
    ],
    [
      "build-plugin-moment-locales",
      {
        "locales": [
          "zh-cn"
        ]
      }
    ]
  ]
}
```

* `src/app.(ts|js)`：ts
"@alifd/next": "^1.20.28",
**What is the expected behavior?**
Tree组件正常显示dataSource的内容

**Comment by chenbin92** [comment]
已处理 https://github.com/alibaba-fusion/next/pull/2131
