### ISSUE TITLE
MPA应用需要手动更改浏览器地址加载界面，否则显示“Cannot Get /”问题

### ISSUE THREAD

**Issue by LoLDragon** [alibaba/ice#3511]
问题描述：
   当使用MPA应用时，存在多个页面时，浏览器open url默认为“http://localhost:3333/”,此时浏览器会显示“Cannot Get /”问题，需要手动更改地址为“http://localhost:3333/xxx.html”才会显示具体的界面，这样开发体验很不好，希望可以优化当多页面时，默认打开某一个页面，而且可以根据build.json中字段设置打开某个页面，最好可以指定浏览器open的url地址。

开发环境：
  ice.js: 1.8.1
 nodejs: 10.16.0

**Comment by chenbin92** [comment]
https://github.com/alibaba/ice/issues/3512

**Comment by chenbin92** [comment]
@LoLDragon  ice.js@1.9.1-0 版本已经支持，欢迎试用。详见 https://github.com/alibaba/ice/pull/3513#issue-482114861

**Comment by chenbin92** [comment]
已发布 ice.js@1.9.1 版本支持
