### ISSUE TITLE
我搭建的平台使用了react-snap，想要实现ssr功能

### ISSUE THREAD

**Issue by Dilmoon2016** [alibaba/ice#3514]
我对ssr不太了解build之后需要做什么操作呢，我现在是直接用iis启动的网站seo效果并不好，请问一下如果用ice，启用ssr功能之后该如何启动网站

**Comment by chenbin92** [comment]
@Dilmoon2016 ICE 的 SSR 方案参考这个文档 https://ice.work/docs/guide/advance/ssr，只需要在 `build.json` 配置是否开启 SSR 即可，其他与 SPA 的开发方式差不多。

**Comment by Dilmoon2016** [comment]
> @Dilmoon2016 ICE 的 SSR 方案参考这个文档 https://ice.work/docs/guide/advance/ssr ，只需要在 `build.json` 配置是否开启 SSR 即可，其他与 SPA 的开发方式差不多。

那build之后用iis部署网站是否已经打开了ssr

**Comment by chenbin92** [comment]
可以看下这里与服务端集成的示例 https://ice.work/docs/guide/advance/ssr#%E6%9C%8D%E5%8A%A1%E7%AB%AF%E9%9B%86%E6%88%90

对 iis 部署不了解，具体可以自行搜索尝试下
