### ISSUE TITLE
官方文档中（路由方案》wrappers 配置》实现路由高阶组件）文档不健全

### ISSUE THREAD

**Issue by MichaelFly** [alibaba/ice#3518]
官方文档：import { useAuth, Redirect } from 'ice';
没有告诉遇到引入auth插件，最后发现是因为auth插件没有，找到问题，但是发现官方文档（插件开发》官方插件列表）里面就没有auth这个插件，往官方问题更加明确的添加该插件的使用

**Comment by chenbin92** [comment]
@MichaelFly 权限管理文档有写如何使用。https://ice.work/docs/guide/advance/auth#%E5%AE%89%E8%A3%85

![image](https://user-images.githubusercontent.com/3995814/92674518-17c5e580-f350-11ea-9139-08e0c6b718aa.png)

**Comment by MichaelFly** [comment]
找到了，谢谢

**Comment by wildfire810** [comment]
这个例子代码确实有问题啊

首先，需要引入
import React from 'react';

然后安装和配置plugin-ice-auth插件肯定是没问题了

auth.isLogin ? <WrappedComponent {...props} /> : <Redirect to="/login" />;
这行代码，最后的分号需要删除，否则报错，然后里面的props变量也找不到。

这个例子不知道该怎么改才能通过。删除了分号和{...props}之后，引入到routes.ts中，会导致崩溃。
Unhandled Rejection (TypeError): Cannot read property 'concat' of undefined
