### ISSUE TITLE
可否考虑提供CDN之类的

### ISSUE THREAD

**Issue by BearXiongLaoXiong** [alibaba/ice#352]
目前看到的都是React 或者 即将支持的vue的。对于我这种非专业人士，感觉使用无比困难啊。可否考虑直接提供CDN这样的。。

**Comment by yujiangshui** [comment]
@BearXiongLaoXiong 你说的困难是写前端代码困难？直接提供 CDN 是希望什么样的？

**Comment by chenhongen** [comment]
LZ的意思应该是 直接通过CDN引入就可以使用 类似传统的jq。。

**Comment by BearXiongLaoXiong** [comment]
对对，如楼上说的， 我这种前端弱鸡，什么webpack cli统统不会啊。。。但是又想用这个东西，感觉学习压力很大。。。悲剧了

**Comment by yujiangshui** [comment]
@BearXiongLaoXiong 使用 iceworks 根本不会接触到 webpack、cli 的概念。你可以下载一下，GUI 操作就可以生成项目，点击构建按钮就可以生成打包好的 js、css 文件，往服务器上一丢就可以了。至于 react 之类的都会自动加载的不需要你去手动引入。
