### ISSUE TITLE
配置式路由应用 lazy 报 Suspense 相关错误

### ISSUE THREAD

**Issue by q1255490** [alibaba/ice#3523]
** bug **
**版本**
![image](https://user-images.githubusercontent.com/20785828/92842745-84a3b300-f416-11ea-8860-8bfa1cbbdb50.png)

**描述**
文档中说明 配置式路由 只需要添加 lazy即可
![image](https://user-images.githubusercontent.com/20785828/92842554-48705280-f416-11ea-85bf-b33f9070b58e.png)

**路由配置**
![image](https://user-images.githubusercontent.com/20785828/92842411-1bbc3b00-f416-11ea-9c89-8960fb61583f.png)
**错误**
![image](https://user-images.githubusercontent.com/20785828/92842600-5cb44f80-f416-11ea-90c4-f615853e8c72.png)

**Comment by chenbin92** [comment]
![image](https://user-images.githubusercontent.com/3995814/92845184-45c32c80-f419-11ea-8af5-eb242b6b0f50.png)


Layout 不需要添加 lazy，以路由作为切割点
