### ISSUE TITLE
[BUG] TS2305: Module '"./store"' has no exported member 'createStore'.

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [alibaba/ice#3529]
.ice/index.ts :

![image](https://user-images.githubusercontent.com/69426460/92978858-aa25d080-f499-11ea-9461-b5e8528dc3ec.png)

.ice/store/index.ts :

![image](https://user-images.githubusercontent.com/69426460/92978944-e5c09a80-f499-11ea-9e83-e80a713e6711.png)
```

**Comment by SoloJiang** [comment]
你在页面下使用到了 `store.ts` 吗？比如 `/pages/Home/store.ts`

**Comment by MaxmaxmaximusAWS** [comment]
@SoloJiang no, this is where is bug.

if there is no such file `store.ts`, then there should be a "stub" inside `.ice/store/index.ts` with valid TypeScript code.

**Comment by SoloJiang** [comment]
我好像不能复现这个问题，可用提供一个简单复现的 demo 吗
