### ISSUE TITLE
模块中使用代码分割 Code Splitting，会将公用的js单独打包在每个模块的js里面 

### ISSUE THREAD

**Issue by ModestQian** [alibaba/ice#3547]
![image](https://user-images.githubusercontent.com/39544880/93289578-45f46b00-f811-11ea-90b3-67723805d92d.png)
![image](https://user-images.githubusercontent.com/39544880/93289584-4856c500-f811-11ea-8731-b4fb6efc76ce.png)

**Comment by alvinhui** [comment]
@sspku-yqLiu 可以看看

**Comment by sspku-yqLiu** [comment]
> @sspku-yqLiu 可以看看

ok  我了解一下

**Comment by chenbin92** [comment]
@sspku-yqLiu 有结论了在这里回复一下。

**Comment by imsobear** [comment]
@ModestQian 一个临时的解决方案是：

- 在 `src/utils` 新加一个 `lodash.js` 的问题，通过 lazy import lodash，同时把 lodash export 出来
- 业务里所有用到 lodash 的地方都从 `src/utils/lodash.js` 里引入

**Comment by sspku-yqLiu** [comment]
贡献一些解决思路：

- 关于按路由进行打包，没有成功复现问题。 如果两个包同时引用了 lodash, 那么他们在打包时会生成公有包 venders~...:
    ``` js
    // Person/index.tsx
    import { deepClone } from 'lodash';
    ...

    // Monitor/index.tsx
    import { forIn } from 'lodash';
    ...

    //router.ts
    const Person = lazy(() => import(/* webpackChunkName: 'person' */'@/pages/Person'));
    const Monitor = lazy(() => import(/* webpackChunkName: 'monitor' */'@/pages/Monitor'));
    ```
    生成代码如下：
    ![image-20200923211614343](https://user-images.githubusercontent.com/56879942/94017965-9a37b600-fde2-11ea-9179-349fbcac7f17.png)
    包 venders~person~monitor 里面的内容为 完整的 lodash 打包，另两个 index.js 中无 lodash 内容
- 关于如何减小 lodash 打包后的体积: 
    

建议在打包插件中添加 webpack 插件 lodash-webpack-plugin： https://github.com/lodash/lodash-webpack-plugin, 可以实现按需加载

**Comment by imsobear** [comment]
@sspku-yqLiu 这个问题跟 lodash 本身无关。当应用托管在 java/node 上时，vendor 的问题是需要开发者在 html 里主动引，会有一些成本，因此还是希望能走 chunk 这种自动加载的方式，类似自动生成一个 CommonChunk。

**Comment by luhc228** [comment]
@ModestQian 能否提供可复现的 demo ?
