### ISSUE TITLE
在table 组件中 无法使用自定义权限组件的问题

### ISSUE THREAD

**Issue by q1255490** [alibaba/ice#3548]
###  参考
![image](https://user-images.githubusercontent.com/20785828/93311541-b662b280-f838-11ea-9154-8c01c2df3261.png)
### 实现
![image](https://user-images.githubusercontent.com/20785828/93311638-d2665400-f838-11ea-9d51-9939fd6fe516.png)
### 在非table 中正常使用
![image](https://user-images.githubusercontent.com/20785828/93311733-f1fd7c80-f838-11ea-920e-591dfa16dfd3.png)
### 在table 组件中出现
![image](https://user-images.githubusercontent.com/20785828/93311878-1c4f3a00-f839-11ea-871d-bcbb3ca70ad7.png)
![image](https://user-images.githubusercontent.com/20785828/93311960-38eb7200-f839-11ea-866d-54b55cbcd109.png)

**Comment by imsobear** [comment]
@q1255490 在 codesandbox 上搞个 demo 吧 https://codesandbox.io/s/github/ice-lab/icejs/tree/master/examples/hello-world

**Comment by chenbin92** [comment]
@@q1255490 看错误信息和实现代码是你的 `WithAclIamG` 组件的实现问题，该组件返回类型不是一个 Table.Column，也就错误中的提示。

![image](https://user-images.githubusercontent.com/3995814/93707363-64839a80-fb60-11ea-92b6-bb60b5e35cbd.png)

![image](https://user-images.githubusercontent.com/3995814/93707373-8b41d100-fb60-11ea-9e0b-33cfbb62938f.png)

**Comment by imsobear** [comment]
WithAclIamG 应该包到 renderOps 上，而不是包到 Tabel.Column 上。
