### ISSUE TITLE
icejs 中不支持 icestore disableImmer 的配置项

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#3551]
其他选项同理，icejs 中不应该是阉割版的 icestore.

**Comment by luhc228** [comment]
### 方案1
把 disableImmer、disableError、disableLoading 配置写在 build.json 当中，可以在 template generator render 时读取到配置参数

优点：解决简单
缺点：运行时的配置写在构建时的配置文件中不合适

### 方案2 
icestore 支持在 Provider 传入 disableImmer、disableError、disableLoading 配置参数 

优点：运行时可以注入配置参数给 createElement
缺点：icestore 支持此功能需要一定的成本，而且在 Provider 传入这些配置参数不太合理

### 方案3
setAppConfig 完成之后，使用 babel 解析 `.ice/store/index.ts` 和 `pages/About/store.ts ` 文件，写入 disableImmer、disableError、disableLoading 配置参数

缺点：实现太重了，有点复杂

**Comment by imsobear** [comment]
不能写在 app.js 的 app.store 里？

**Comment by luhc228** [comment]
> 不能写在 app.js 的 app.store 里？

目前不能。生成 .ice/ 目录代码并且编译代码时，拿不到 appConfig 的内容

**Comment by farrrr** [comment]
有鑒於這三個配置都是屬於不會頻繁修改（通常在專案一開始就會確立的，又或者是特殊情形下才會更動），建議可以走方案一，只是需要在文件中註明更動該配置需重新構建。

順便提供另一種方案可能性
若用戶目錄下 src/store/index.ts (or src/models/index.ts) 存在，直接以用戶目錄下的 store 為主。
優點：彈性可以到非常高，高度客製化。
缺點：但這樣似乎就不好做到新增 model 時，同步更動 .ice/store/index.[js|ts] 了

**Comment by chenbin92** [comment]
@luhc228 @farrrr 

这个  MR https://github.com/alibaba/ice/pull/3555 支持了用户自定义 store 的功能，但目前只支持 pages 目录下的 store。其实也可进一步支持全局自定义 store，这样的话 createStore 的参数就都可以自定义了。

因此在类似 disableImmer 这种方案下，建议使用自定义 store 的方式。

**Comment by chenbin92** [comment]
ice.js@1.9.7 版本已支持
