### ISSUE TITLE
Input.TextArea组件使用isPreview报错

### ISSUE THREAD

**Issue by we6288815** [alibaba/ice#3553]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Input.TextArea组件使用预览时报错
![image](https://user-images.githubusercontent.com/8169722/93452705-4ffa9480-f90b-11ea-8fa0-213cafeafb32.png)

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
复现demo：https://codesandbox.io/s/wizardly-water-gsx8c?file=/src/pages/Home/index.tsx

* icejs version：^1.6.3
* Node verson：v10.16.0
* Platform：Windows 10 x62
* `build.json`：
* `src/app.(ts|js)`：js

**What is the expected behavior?**
多行文本正常使用预览能力

**Comment by chenbin92** [comment]
@we6288815  感谢反馈，具体进展在 https://github.com/alibaba-fusion/next/issues/2189 跟进。
