### ISSUE TITLE
怎么覆盖默认样式？

### ISSUE THREAD

**Issue by kechen123** [alibaba/ice#3556]
就是类似于less中的:global这种的

**Comment by chenbin92** [comment]
1. 要覆盖的「默认样式」是指什么，问题描述清楚。
2. 如果是想模板内置基础组件的样式，有两种做法：
  *  定制主题变量，或者主题。[参考](https://ice.work/docs/guide/advance/fusion#%E4%BD%BF%E7%94%A8%E4%B8%BB%E9%A2%98%E5%8F%98%E9%87%8F)
  * CSS 层级覆盖
