### ISSUE TITLE
useAuth 遇到 React.lazy 导入 无效

### ISSUE THREAD

**Issue by zt1820057934** [alibaba/ice#3557]
* icejs version： 1.9.3
* Node verson：12.18.2
* Platform：mac
* `build.json`： "plugins": [ "build-plugin-ice-auth"  ]
* `src/app.(ts|js)`：
```
const appConfig = {
  app: {
    getInitialData: async () => {
      const data = await authService.getUserTree()
      console.log('authData is ', data)     // data: {  xxx : true, yyy: false   }
      return {
        auth: data
      }
    },
  },
```
然后再某组件下设置code, 
```
const Area = () => {
  const [ auth ] = useAuth()
  console.log('auth is ', auth)  // auth 输出正常  {  xxx : true, yyy: false   }
  return (
    <div><h1>AAA</h1></div>
  )
}
Area.pageConfig = {
  auth: ['yyy']
}

export default Area
```
但无效， 依然可进入，  经测试， 在routes.js 中， 
const Area = React.lazy(() => import('@/pages/xxxx/AreaManagement'));  这样导入就是无效的
而直接import 可以

**Comment by chenbin92** [comment]
@zt1820057934 可以参考下 [examples/basic-auth](https://github.com/alibaba/ice/blob/master/examples/basic-auth/src/routes.ts#L3) 这个示例，使用了 useAuth 和 lazy 配合正常使用。
