### ISSUE TITLE
在页面级状态下有多个 model 时，引入 store 为 undefined

### ISSUE THREAD

**Issue by luhc228** [alibaba/ice#3559]
ICE 社区群 #曹津杰 #六弦 反馈问题如下：

如下图，在 Discovery 页面下有多个 model，放在 `pages/Discovery/models/` 目录下。引入的 store 为 `undefined` 

![image](https://user-images.githubusercontent.com/44047106/93730391-f344f580-fbfa-11ea-8c16-636ad1e744c9.png)

**Comment by luhc228** [comment]
按照上面的图片的代码在本地尝试复现，打印的 model 没出现 `undefined` 的情况，详见下面的代码：

![image](https://user-images.githubusercontent.com/44047106/93735433-7112fc00-fc0f-11ea-8997-d8a157012353.png)

打印的结果如下：

![image](https://user-images.githubusercontent.com/44047106/93735450-7cfebe00-fc0f-11ea-9657-be32d68165be.png)

**Comment by luhc228** [comment]
检查一下在 pages/Discovery/models/ 下是不是有 settings 这个 store

**Comment by caojinjie** [comment]
settings这个model肯定有的，在使用Function的方式运行时一切正常，切换成Class并使用withModel时出现该问题。

**Comment by caojinjie** [comment]
经过在本地使用官方ice-pro模板实践，发现可能跟ice.js版本有关，1.6.0版本不会报undefined，我的工程代码中ice.js版本是1.9.3，在我将基于1.6.0的ice-pro模板升级到1.9.3时，也出现了undefined

**Comment by caojinjie** [comment]
[ice-demo.zip](https://github.com/alibaba/ice/files/5258949/ice-demo.zip)
可使用上述压缩工程进行复线，我基于ice-pro模板，升级了ice.js版本为1.9.3，将其中Advanced目录下的Function组件改成了Class组件并调用页面级store.withModel，出现了undefined错误，请尝试一下。
