### ISSUE TITLE
createApp 需要提供init函数 来控制前置的注册

### ISSUE THREAD

**Issue by younyzhu** [alibaba/ice#3567]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

* icejs version：
* Node verson：
* Platform：
* `build.json`：
* `src/app.(ts|js)`：

**What is the expected behavior?**

createApp 需要提供init函数 来控制前置的注册，
比如我的所有接口需要先注册过才能用，现在model里面直接从注册完的结果拿，比如const {xxxApi}  = context;
如果init没预先注册，xxxApi 是拿不到的
由于目前 全局 store 的生成机制比较靠前，导致这类场景直接挂掉，但是页面级别store就没问题

**Comment by imsobear** [comment]
@younyzhu 可否描述再详细点，没太理解这个场景，比如这里的 context 是哪里来的？

**Comment by imsobear** [comment]
问题描述不清楚，暂时先关掉，有需要自行打开。
