### ISSUE TITLE
create-func-wrap 代码健壮性

### ISSUE THREAD

**Issue by wssgcg1213** [alibaba/ice#357]
![image](https://user-images.githubusercontent.com/3922719/38023982-425bbb88-32b6-11e8-8ea5-37e4a9b248f7.png)

**Comment by wssgcg1213** [comment]
代码里面怎么要setTimeout去销毁？

**Comment by chenbin92** [comment]
之前讨论的结果是：去掉这种写法 @yujiangshui

**Comment by yujiangshui** [comment]
@chenbin92 这个你不是都去掉了么？还有什么 block 有？

**Comment by noyobo** [comment]
已废弃的方法。
