### ISSUE TITLE
主包更稳定的版本管理方案

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#3570]
## 背景

ice.js 目前锁定了一级依赖的版本，但一级依赖的依赖版本并未锁定，如果业务锁定了 ice.js 的版本，这时候如果一级依赖的依赖版本发生变化，重新安装后就有可能运行不起来，因此需要提供一个更稳定的版本管理方案。

## 方案

ice.js  发版本前将所有层级的依赖都打包成一个 bundle，这样这个版本就是「完全」稳定的。

## 优缺点

优点：

- 版本更加稳定
- 安装速度变快、运行速度理论上也会变快

缺点：

- 丧失部分灵活性，比如依赖的依赖发版后不需要重新发布 ice.js，但结合实践来看我们貌似不怎么依赖这种灵活性
- 发版前的回归成本会有一些增加

**Comment by imsobear** [comment]
node-sass 这种依赖 nodejs 版本和系统环境的要单独看下

**Comment by ClarkXia** [comment]
ice.js 2.0 采用底层依赖预编译的方案
