### ISSUE TITLE
运行npm start命令报错 icejs: command not found

### ISSUE THREAD

**Issue by huazijiang** [alibaba/ice#3576]
sh: icejs: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! @alifd/fusion-design-pro@0.1.0 start: `icejs start`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the @alifd/fusion-design-pro@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

log报错
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error @alifd/fusion-design-pro@0.1.0 start: `icejs start`
23 error spawn ENOENT
24 error Failed at the @alifd/fusion-design-pro@0.1.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by chenbin92** [comment]
确认下是否有安装依赖

**Comment by huazijiang** [comment]
tnpm update
更新过程中报错
gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/tnpm/node_modules/_node-gyp@3.8.0@node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/Users/quzhen.gjj/.nvm/versions/node/v8.9.0/bin/node" "/usr/local/lib/node_modules/tnpm/node_modules/_npminstall@3.14.0@npminstall/node-gyp-bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/quzhen.gjj/Documents/itemTools/code/tropos/item-preun-front/node_modules/_fsevents@1.2.13@fsevents
gyp ERR! node -v v8.9.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 


执行start后报错
ERR! CONFIG Fail to load plugin /Users/quzhen.gjj/Documents/itemTools/code/tropos/item-preun-front/node_modules/_build-plugin-app-core@0.1.18@build-plugin-app-core/lib/index.js
ERR! CONFIG /Users/quzhen.gjj/Documents/itemTools/code/tropos/item-preun-front/node_modules/_prettier@2.1.2@prettier/third-party.js:9871
ERR! CONFIG       for await (const place of this.config.searchPlaces) {
ERR! CONFIG           ^^^^^
ERR! CONFIG 
ERR! CONFIG SyntaxError: Unexpected reserved word
ERR! CONFIG     at createScript (vm.js:80:10)
ERR! CONFIG     at Object.runInThisContext (vm.js:139:10)
ERR! CONFIG     at Module._compile (module.js:599:28)
ERR! CONFIG     at Object.Module._extensions..js (module.js:646:10)
ERR! CONFIG     at Module.load (module.js:554:32)
ERR! CONFIG     at tryModuleLoad (module.js:497:12)
ERR! CONFIG     at Function.Module._load (module.js:489:3)
ERR! CONFIG     at Module.require (module.js:579:17)
ERR! CONFIG     at require (internal/module.js:11:18)
ERR! CONFIG     at Object.<anonymous> (/Users/quzhen.gjj/Documents/itemTools/code/tropos/item-preun-front/node_modules/_prettier@2.1.2@prettier/index.js:16561:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @alifd/fusion-design-pro@0.1.0 start: `icejs start "--port" "4444"`
npm ERR! Exit status 1

**Comment by huazijiang** [comment]
> @huazijiang 确认下是否有安装依赖

tnpm update
更新过程中报错
gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: gyp failed with exit code: 1
gyp ERR! stack at ChildProcess.onCpExit (/usr/local/lib/node_modules/tnpm/node_modules/_node-gyp@3.8.0@node-gyp/lib/configure.js:345:16)
gyp ERR! stack at emitTwo (events.js:126:13)
gyp ERR! stack at ChildProcess.emit (events.js:214:7)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/Users/quzhen.gjj/.nvm/versions/node/v8.9.0/bin/node" "/usr/local/lib/node_modules/tnpm/node_modules/_npminstall@3.14.0@npminstall/node-gyp-bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/quzhen.gjj/Documents/itemTools/code/tropos/item-preun-front/node_modules/_fsevents@1.2.13@fsevents
gyp ERR! node -v v8.9.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

执行start后报错
ERR! CONFIG Fail to load plugin /Users/quzhen.gjj/Documents/itemTools/code/tropos/item-preun-front/node_modules/_build-plugin-app-core@0.1.18@build-plugin-app-core/lib/index.js
ERR! CONFIG /Users/quzhen.gjj/Documents/itemTools/code/tropos/item-preun-front/node_modules/_prettier@2.1.2@prettier/third-party.js:9871
ERR! CONFIG for await (const place of this.config.searchPlaces) {
ERR! CONFIG ^^^^^
ERR! CONFIG
ERR! CONFIG SyntaxError: Unexpected reserved word
ERR! CONFIG at createScript (vm.js:80:10)
ERR! CONFIG at Object.runInThisContext (vm.js:139:10)
ERR! CONFIG at Module._compile (module.js:599:28)
ERR! CONFIG at Object.Module._extensions..js (module.js:646:10)
ERR! CONFIG at Module.load (module.js:554:32)
ERR! CONFIG at tryModuleLoad (module.js:497:12)
ERR! CONFIG at Function.Module._load (module.js:489:3)
ERR! CONFIG at Module.require (module.js:579:17)
ERR! CONFIG at require (internal/module.js:11:18)
ERR! CONFIG at Object. (/Users/quzhen.gjj/Documents/itemTools/code/tropos/item-preun-front/node_modules/_prettier@2.1.2@prettier/index.js:16561:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @alifd/fusion-design-pro@0.1.0 start: icejs start "--port" "4444"
npm ERR! Exit status 1

**Comment by huazijiang** [comment]
1.安装xcode
2.升级node高版本

解决了
