### ISSUE TITLE
子应用vue，相同页面a，配置不同路由/raa,rab；使用appHistory.push切换时，页面不刷新

### ISSUE THREAD

**Issue by rootsli** [alibaba/ice#3580]
**Do you want to request a *feature* or report a *bug*?**
子应用vue，相同页面a，配置不同路由/raa,rab；使用appHistory.push切换时，页面不刷新
**What is the current behavior?**
子应用vue，相同页面a，配置不同路由/raa,rab；使用appHistory.push切换时，页面不刷新
If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

* icejs version：
* Node verson：
* Platform：
* `build.json`：
* `src/app.(ts|js)`：

**What is the expected behavior?**
相同页面，配置不同路由时，能重新触发页面的生命周期逻辑

**Comment by imsobear** [comment]
这个问题应该跟 icestark 没关系，React/Vue 里都是一样的表现，比较常见的例子：

- 路由配置：`/project/:id` 对应页面组件 ProjectDetail
- 当从 /project/1 跳转到 /project/2 时，只会触发 ProjectDetail 的 update 逻辑

**Comment by rootsli** [comment]
> 这个问题应该跟 icestark 没关系，React/Vue 里都是一样的表现，比较常见的例子：
> 
> * 路由配置：`/project/:id` 对应页面组件 ProjectDetail
> * 当从 /project/1 跳转到 /project/2 时，只会触发 ProjectDetail 的 update 逻辑

如果相同页面ProjectDetail路由配置分别是/projectA和/projectB，也只触发update逻辑吗？

**Comment by imsobear** [comment]
@rootsli 你说的这个 case，可以搞个单页面应用先测试下，先排查清楚跟 icestark 有没有关系。
