### ISSUE TITLE
主应用中使用lazy加载页面，报Uncaught ChunkLoadError: Loading chunk xxxx failed.

### ISSUE THREAD

**Issue by darkmice** [alibaba/ice#3581]
主应用中使用lazy加载页面，报Uncaught ChunkLoadError: Loading chunk xxxx failed.  
 
![image](https://user-images.githubusercontent.com/1502088/94220079-c9514300-ff1a-11ea-8903-73af02dad941.png)

* icejs version：1.8.1
* Node verson：v12.17.0
* Platform：window
* `build.json`：
```
{
  "router": {
    "lazy": true
  }
```
* `src/app.(ts|js)`：
```
{
router: {
    type: 'browser',
    fallback: <div className='g-loading'><Spin delay={1000} size="large"/></div>,
  },
  icestark: {
    type: 'framework',
    Layout: FrameworkLayout,
    getApps: async () => {
        // 省略
       return [];
    },
    appRouter: {
      NotFoundComponent: NotFound,
      LoadingComponent: PageLoading,
    }
  },
}

**Comment by ClarkXia** [comment]
先判断下，是否主子应用均开启了  lazy 而导致的 webpackJsonp 变量的冲突覆盖。
如果是，可以通过在主应用工程中通过定制插件的方式执行 webpackJsonp 的变量：https://ice.work/docs/guide/develop/plugin-build

```js
module.exports = ({onGetWebpackConfig}) => {
  onGetWebpackConfig((config) => {
    config.output.jsonpFunction('FrameworkWebpackJsonp');
  });
}
```

**Comment by darkmice** [comment]
非常感谢解答
