### ISSUE TITLE
主应用和子应用都使用了styled-components时，子应用切换回主应用，开发环境会丢失styled-compoents的样式

### ISSUE THREAD

**Issue by darkmice** [alibaba/ice#3583]
主应用和子应用都使用了styled-components时，子应用切换回主应用，开发环境会丢失styled-compoents的样式
 
* icejs version：1.8.1
* Node verson：v12.17.0
* Platform：window
* `build.json`：
* `src/app.(ts|js)`：

 主应用正常时的head
![image](https://user-images.githubusercontent.com/1502088/94220868-898b5b00-ff1c-11ea-9f2e-fa652db26723.png)

子应用的head
![image](https://user-images.githubusercontent.com/1502088/94220897-9b6cfe00-ff1c-11ea-829d-6d8f21805cc3.png)

从子应用切换回主应用后的head
![image](https://user-images.githubusercontent.com/1502088/94220938-b8093600-ff1c-11ea-8bed-fd652cc6412d.png)

**Comment by ClarkXia** [comment]
icestark 通过标识资源的 `icestark="static"` 来防止主应用资源被移除，目前看来主子应用同时使用 styled-components 时，会覆盖 style 标签上的属性，可以通过 https://ice.work/docs/icestark/reference/api#AppRouter 上 shouldAssetsRemove 的属性判断在开发阶段暴露 data-styled 等属性的标签
