### ISSUE TITLE
子应用跳转路由问题

### ISSUE THREAD

**Issue by rootsli** [alibaba/ice#3586]
**Do you want to request a *feature* or report a *bug*?**
微框架使用browser路由，子应用基于iceworks react子应用模板创建，使用hash路由
**What is the current behavior?**
子应用跳转地址hash路由冗余，正确应该是：/gpx-ice/gpx-subapp/#/subBackend => 实际是/gpx-ice/gpx-subapp/#/gpx-ice/gpx-subapp/subBackend
If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
虽然可以正常路由到子应用，但是会导致浏览器前进后退导航会失效，
* icejs version：
* Node verson：
* Platform：
* `build.json`：
* `src/app.(ts|js)`：

**What is the expected behavior?**
url地址正常，浏览器前进后退导航正常

**Comment by rootsli** [comment]
> **Do you want to request a _feature_ or report a _bug_?**
> 微框架使用browser路由，子应用基于iceworks react子应用模板创建，使用hash路由
> **What is the current behavior?**
> 子应用跳转地址hash路由冗余，正确应该是：/gpx-ice/gpx-subapp/#/subBackend => 实际是/gpx-ice/gpx-subapp/#/gpx-ice/gpx-subapp/subBackend
> If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
> 虽然可以正常路由到子应用，但是会导致浏览器前进后退导航会失效，
> 
> * icejs version：
> * Node verson：
> * Platform：
> * `build.json`：
> * `src/app.(ts|js)`：
> 
> **What is the expected behavior?**
> url地址正常，浏览器前进后退导航正常
通过打印日志，子应用取到的basename是：getBasename() => /gpx-ice/gpx-subapp

有什么办法可以将其改为""，在子应用createApp这边配置basename:"",不生效

**Comment by ClarkXia** [comment]
首先不推荐主应用采用 browser，子应用采用 hash 混合路由模式。
如果子应用以 hash 类型接入，需要在子应用参数上设置 `hashType: true`，如果path 设置为 `/gpx-ice/gpx-subapp` ，一般情况下 `/#/gpx-ice/gpx-subapp` 就可以激活子应用，应用间跳转使用 appHistory。
前后路由失效问题，请提供复现的 demo

**Comment by rootsli** [comment]
> 首先不推荐主应用采用 browser，子应用采用 hash 混合路由模式。
> 如果子应用以 hash 类型接入，需要在子应用参数上设置 `hashType: true`，如果path 设置为 `/gpx-ice/gpx-subapp` ，一般情况下 `/#/gpx-ice/gpx-subapp` 就可以激活子应用，应用间跳转使用 appHistory。
> 前后路由失效问题，请提供复现的 demo

路由失效问题是这样的：进入subBackend页面，url变为/gpx-ice/gpx-subapp/#/gpx-ice/gpx-subapp/subBackend，能正常进入，然后按浏览器后退，能正常后退，按浏览器前进按钮，再次想进入subBackend，页面没刷新还是停留在当前页，没有进入subBackend

**Comment by rootsli** [comment]
> > 首先不推荐主应用采用 browser，子应用采用 hash 混合路由模式。
> > 如果子应用以 hash 类型接入，需要在子应用参数上设置 `hashType: true`，如果path 设置为 `/gpx-ice/gpx-subapp` ，一般情况下 `/#/gpx-ice/gpx-subapp` 就可以激活子应用，应用间跳转使用 appHistory。
> > 前后路由失效问题，请提供复现的 demo
> 
> 路由失效问题是这样的：进入subBackend页面，url变为/gpx-ice/gpx-subapp/#/gpx-ice/gpx-subapp/subBackend，能正常进入，然后按浏览器后退，能正常后退，按浏览器前进按钮，再次想进入subBackend，页面没刷新还是停留在当前页，没有进入subBackend

设置 hashType: true问题：注册子路由我们是通过FrameworkLayout里的updateApps进行动态注册的，配置如下：

![image](https://user-images.githubusercontent.com/4099803/94356482-c04ea600-00c1-11eb-8116-6924a0537d61.png)

设置上hashType: true后，页面跳转失效了，跳转不了了。也不知道是bug还是什么原因，配置cache: true也无法跳转了。

**Comment by ClarkXia** [comment]
提供下复现的 demo，按上述步骤无法复现

**Comment by ClarkXia** [comment]
相关 issue：https://github.com/alibaba/ice/issues/3656

**Comment by LoLDragon** [comment]
同样遇到相同的情况，设置hashType为true后，子应用的hash路由无法跳转

**Comment by LoLDragon** [comment]
@ClarkXia 就用的官方demo, 启动子应用后改成hash路由跳转就不行了。 如果都推荐使用browser路由的，需要对ng配置。。那么每次新增一个子系统都要配置一次？ 这块有什么好的建议？

**Comment by LoLDragon** [comment]
@ChrisCindy 为什么不推荐子应用使用hash路由啊？如果使用browser路由的话，需要配置ng type_files, 每次新增一个子系统都需要配置一次，这种有什么好的方法解决嘛？
