### ISSUE TITLE
fusion-design-pro 模板项目菜单不会根据当前路由自动展开高亮

### ISSUE THREAD

**Issue by we6288815** [alibaba/ice#3595]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
切换路由，但是菜单并未根据当前路由自动展开高亮
If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
![image](https://user-images.githubusercontent.com/8169722/94380520-77056180-0168-11eb-82ef-4d3705559c0b.png)
官方演示模板：
https://unpkg.com/@alifd/fusion-design-pro@0.1.36/build/index.html#/form/two

* icejs version：
* Node verson：
* Platform：
* `build.json`：
* `src/app.(ts|js)`：

**What is the expected behavior?**
菜单能够根据当前路由自动展开高亮

**Comment by luhc228** [comment]
参考：
- https://unpkg.com/@alifd/fusion-design-pro@0.2.1/build/index.html#/dashboard/analysis
- https://github.com/alibaba-fusion/materials/blob/0032213d0b78642e15c94b5767bfcff85511b996/scaffolds/fusion-design-pro/src/layouts/BasicLayout/components/PageNav/index.tsx#L81
