### ISSUE TITLE
如何实现history的pop功能

### ISSUE THREAD

**Issue by rootsli** [alibaba/ice#3596]
**Do you want to request a *feature* or report a *bug*?**
使用微框架后，子应用间或子应用内部切换，如何实现pop后退功能？
**What is the current behavior?**
appHistory不支持类似history的后退功能
If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
pr
* icejs version：
* Node verson：
* Platform：
* `build.json`：
* `src/app.(ts|js)`：

**What is the expected behavior?**
框架应用为browser路由，当前子应用为hash路由。
方案1.通过监听pathname变化，自己保持路由栈来实现，实际发现，子应用内部切换时，pathname根本不会变化，该方案pass

`
  useEffect(() => {
    console.log("== app onRouteChange ==", pathname);
  }, [pathname]);
`

方案2.通过注册hashchange事件实现，但是发现路由切换时，事件回调没有执行

`
window.addEventListener("hashchange", onHashChange, false);
`

是否有其他可行方案，实现路由pop功能？

**Comment by ClarkXia** [comment]
实现回退直接使用 `windows.history.back()`，应用跳转问题在 https://github.com/alibaba/ice/issues/3586 中补充完整的 demo
