### ISSUE TITLE
新建的区块项目，执行 npm install 报错

### ISSUE THREAD

**Issue by dohkoxiaozu** [alibaba/ice#3605]
https://ice.work/docs/materials/guide/block
根据这里的提示，执行如下两个步骤（没有更改任何文件）

1、iceworks add block
![image](https://user-images.githubusercontent.com/48460761/94509971-2e24da00-0248-11eb-9209-f288e908c970.png)

2、npm install
![image](https://user-images.githubusercontent.com/48460761/94510239-dc308400-0248-11eb-8b29-699cec8f21ed.png)
![image](https://user-images.githubusercontent.com/48460761/94510247-e2befb80-0248-11eb-9e48-0364b6c0914d.png)

npm install 安装依赖库报错信息：
“ Command failed: C:\WINDOWS\system32\cmd.exe /s /c "autoreconf -fiv"
'autoreconf' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���”
“ pngquant failed to build, make sure that libpng-dev is installed”

相关环境信息：
操作系统：win10
node版本：12.18.3
iceworks版本：3.4.1

**Comment by ClarkXia** [comment]
看错误信息是 raw.githubusercontent.com 访问的问题，可以尝试切换 npm 镜像源或者修改 raw.githubusercontent.com host 设置

**Comment by dohkoxiaozu** [comment]
> 看错误信息是 raw.githubusercontent.com 访问的问题，可以尝试切换 npm 镜像源或者修改 raw.githubusercontent.com host 设置

是说找不到  libpng-dev 这个库吧？

**Comment by dohkoxiaozu** [comment]
windows 和 mac 下都会存在这个问题，实力劝退的感觉。。。

**Comment by dohkoxiaozu** [comment]
mac 下也会存在这个问题，一样的提示

**Comment by imsobear** [comment]
@dohkoxiaozu 实在不行可以去除 screenshot 的依赖以及对应的命令，我们这边没法重现。
