### ISSUE TITLE
文档补充环境准备

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#3613]

**Comment by chenbin92** [comment]
这是什么 😆

**Comment by imsobear** [comment]
https://github.com/imsobear/blog/blob/gh-pages/_posts/2014-04-10-nodejs-prepare.md 跟这个差不多

**Comment by chenbin92** [comment]
@luhc228 

在 「快速开始」章节的 「使用 CLI」部分新增环境准备章节。可以包含以下几部分环境：

- Node.js： 要求在 10.0.0 或者以上版本
- 管理工具：NVM、NPM、Yarn（可以介绍下安装步骤）

**Comment by chenbin92** [comment]
ice.js@1.9.9 版本已支持
