### ISSUE TITLE
路由查询参数的使用

### ISSUE THREAD

**Issue by zzwMay** [alibaba/ice#3619]
请问ice里面如何在没有使用动态路由的情况下，使用查询参数

**Comment by imsobear** [comment]
@zzwMay 尽量把问题描述清楚点，多补充点信息

**Comment by zzwMay** [comment]
页面中有查询条件。我用history.push把参数拼到url上，然后用useParams()获取url，用querystring.parse()解析参数。现在问题是，没有':name'，只有'?key=xxx'的情况下，怎么获取这些查询参数呢？

**Comment by chenbin92** [comment]
只有'?key=xxx'的情况下，怎么获取这些查询参数呢？

useParams 的用法：

```ts
// url 如下
const currentUrl = http://localhost:3333/#/ice/dashboard?a=1&b=2;

// 在函数组件中调用 
const params = useParams();
console.log(params); // 输出 { a: 1, b: 2 }
```
