### ISSUE TITLE
常见问题汇总

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#362]
## 问题一：
问题：Warning getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead

![](https://img.alicdn.com/tfs/TB18ZVchwmTBuNjy1XbXXaMrVXa-1662-410.png)

原因：基础 Menu 组件使用了  getDefaultProps 属性，getDefaultProps只能用在React.createClass形式声明的组件中，而项目模板默认使用的是 React 16 版本，导致出现警告提示。

解法：下个版本的基础包会修复该问题；

建议在生成环境中使用  react production 版本，即不会出现警告提示
```
//  in development
http://g.alicdn.com/code/npm/??react/16.2.0/umd/react.development.js,react-dom/16.2.0/umd/react-dom.development.js

// in production
https://g.alicdn.com/code/npm/??react/16.2.0/umd/react.production.min.js,react-dom/16.2.0/umd/react-dom.production.min.js
```

## 问题二：

问题：怎么添加反向代理服务

解法：详见文档 https://alibaba.github.io/ice/#/docs/advanced/webpackrc

**Comment by akiko123456** [comment]
666

**Comment by sxcooler** [comment]
@chenbin92 抱歉打扰下，替换js文件只能在public/index.html里，这样我就不能实现同一份代码在不同环境打包出不同的结果（我想到几种实现方式，但是在webpack config不可控的情况下都做不到）。
类似的，比方说我想修改一下webpack config增加一个alias之类的……反正所有涉及到webpack的需求，由于你们把webpack的配置都隐藏在了ice-scripts里，都无法实现。
个人建议能否考虑像create-react-app一样增加一个“eject”操作，把ice-scripts里面隐含的东西解出来，供有较强定制需求的用户使用。
感谢您的时间。

**Comment by noyobo** [comment]
迁移到  Wiki https://github.com/alibaba/ice/wiki
