### ISSUE TITLE
自定义npm包问题

### ISSUE THREAD

**Issue by zhangsixue-1992** [alibaba/ice#3626]
项目使用飞冰 icejs，自定义了Layouts 和 基于飞冰组件封装了项目内便于使用的组件。 遇到的问题有多个系统如何便捷使用呢

可以在发布npm包 npm i 进行使用么？ 也要把用到的组件写里么？ 想请教一下有没有好的方式

**Comment by imsobear** [comment]
参考这个文档开发业务组件：https://ice.work/docs/materials/guide/component
