### ISSUE TITLE
how to use typescript & tsx in ice?

### ISSUE THREAD

**Issue by 2903710916** [alibaba/ice#363]
How to use typescript & tsx in ice?  Could you give some tips of how to use typescript in ice?

**Comment by noyobo** [comment]
Now don't support, coming some.

**Comment by sjy** [comment]
添加关联issue https://github.com/alibaba/ice/issues/433

**Comment by noyobo** [comment]
https://github.com/alibaba/ice/issues/267

**Comment by imsobear** [comment]
https://alibaba.github.io/ice/docs/advanced/how-to-use-typescript 已支持
