### ISSUE TITLE
不使用vsCode 要如何使用物料

### ISSUE THREAD

**Issue by zhangsixue-1992** [alibaba/ice#3631]
看了官网文档，如物料开发以后不使用vsCode 要如何使用物料呢？
可以npm i 下载包么？ 还是需要有什么样的配置

**Comment by imsobear** [comment]
推荐通过 VS Code 使用，当然也支持 CLI 使用，提前安装下 iceworks CLI `npm i -g iceworks`

- 模板：`npm init ice ice-app --template 模板包名`
- 区块：`iceworks add @alifd/fusion-action-table`
- 业务组件：`npm i --save 组件包名`
