### ISSUE TITLE
开发业务组件时，将d.ts打包成d.js

### ISSUE THREAD

**Issue by JbSun** [alibaba/ice#3638]
## 发生了什么?

使用iceworks搭建业务组件，src下声明的d.ts文件，如何不被转换成d.js文件。
如下：
![问题](https://img.alicdn.com/tfs/TB1YDWjpj39YK4jSZPcXXXrUFXa-482-810.jpg)

**Comment by imsobear** [comment]
1. 为什么会有 d.ts 的文件？很奇怪
2. 如果不可避免的话，可以将这些文件放到根目录，然后加到 package.json 的 files 字段

**Comment by ClarkXia** [comment]
组件 ts 类型建议跟源码一起开发，构建时默认会生成对应的 d.ts
如果存在自定义类型文件 *.d.ts 建议在根目录在 package.json 的 file 字段中指定
