### ISSUE TITLE
我在一个页面修改全局状态的数据，引用全局状态数据的页面，如何自动刷新

### ISSUE THREAD

**Issue by jitaguizhao** [alibaba/ice#3652]
const storeUser={
      username: values.username,
      dept_id: userState.dept_id,
      avatar: values.avatar,
      user_id: userState.user_id,
      access_token: userState.access_token,
      refresh_token: userState.refresh_token,
     }
     userDispatchers.update(storeUser);
![image](https://user-images.githubusercontent.com/19563190/95935388-b76e0c00-0e05-11eb-9b28-2ce9eb3b3b81.png)

**Comment by imsobear** [comment]
默认就会更新的，建议代码给全一点，或者给个完整的 demo

**Comment by jitaguizhao** [comment]
import React, { useState,useEffect } from 'react';
import { Box, ResponsiveGrid, Divider, Card, Avatar, Upload, Button, Form, Input, Message } from '@alifd/next';
import {store,useRequest} from 'ice';
import userService from '@/pages/Person/services/user';
import styles from './index.module.scss';

const { Cell } = ResponsiveGrid;
const FormItem = Form.Item;
export interface userInfo {
  username: string;
  user_id: string;
  phone: string;
  avatar: string;
  password: String,
  newpassword1: String,
  newpassword2: String,
}

const SettingPersonBlock: React.SFC<userInfo> = (props): JSX.Element => {
 
  const [userState , userDispatchers ] = store.useModel('user');
  const { request } = useRequest(userService.getUser,{
    manual: true,
    onSuccess: (result, params) => {
      setValue(result.data)
    }, 
  });
  const [postData, setValue] = useState(props);
  const { request: updateUser } = useRequest(userService.updateUser,);

  const DEFAULT_ON_SUBMIT = (values:userInfo, errors: []): void => {
    if (errors) {
      console.log('errors', errors);
      return;
    }
    const DEFAULT_DATA: userInfo = {
      username: values.username,
      user_id: values.user_id,
      phone: values.phone,
      avatar: values.avatar,
      password: '',
      newpassword1: "",
      newpassword2: "",
    };
    updateUser(DEFAULT_DATA);
    const storeUser={
      username: values.username,
      dept_id: userState.dept_id,
      avatar: values.avatar,
      user_id: userState.user_id,
      access_token: userState.access_token,
      refresh_token: userState.refresh_token,
     }
     userDispatchers.update(storeUser);
    //
    Message.success('更新成功');
  };
  useEffect(() => {
    // 调用 user 模型中的 fetchUserInfo 方法
   request(userState.user_id);
   
  }, []);
  const headers = {
    Authorization: 'Bearer ' +userState.access_token,
  };
  
  const formChange = (values): void => {
    
  };
  return (
    <Card free>
      <Card.Content 
        className={styles.SettingPersonBlock}
      >
        <Form
          value={postData}
          labelAlign="top"
          onChange={formChange}
          responsive
        >
          <FormItem label='' colSpan={12}>
            <ResponsiveGrid gap={10}>
              <Cell colSpan={2}><Avatar shape="circle" size={64} icon="account" src={postData?.avatar} /></Cell>
              <Cell colSpan={10} className={styles.changeLogo}>
                <Box spacing={12}>
                  <FormItem>
                    <Upload 
                    action="/admin/user/file"
                    headers={headers}
                    
                    **onSuccess={onSuccess}
                    name='pic'>
                      <Button className={styles.uploadButton} type="normal">更新头像</Button>
                    </Upload>**
                  </FormItem>
                  <Box>
                    <p>* 头像尽量上传超过 80px*80px, 但不要太大了。</p>
                    <p>* 请上传两倍图保证清晰度</p>
                  </Box>
                </Box>
              </Cell>
            </ResponsiveGrid>
          </FormItem>
          <FormItem colSpan={12}>
            <Divider />
          </FormItem>
          <FormItem label="用戶名"   colSpan={12}>
            <Input name="username" defaultValue={postData?.username} disabled/>
          </FormItem>

          <FormItem label="手机：" required  requiredMessage="请输入手机号" pattern="^1[3456789]\d{9}$" colSpan={12} defaultValue={postData?.phone}>
          <Input name="phone"  />
          </FormItem>

          <FormItem colSpan={12} >
            <Box spacing={8} direction="row">
              <Form.Submit
                type="primary"
                validate
                onClick={DEFAULT_ON_SUBMIT}
               
              
              >更新信息</Form.Submit>
            </Box>
          </FormItem>
        </Form>
      </Card.Content>
    </Card>
  );
  function onSuccess(info) {
    setValue(info.response.data);
    
  }
  
};

export default SettingPersonBlock;

**Comment by jitaguizhao** [comment]
我在用户信息修改页面，更改了头像，用户提交修改时，更新了全局的user信息，但右上角的头像没有变

**Comment by jitaguizhao** [comment]
需要手动刷新才会变

**Comment by imsobear** [comment]
把你的代码排版好

正确的 markdown 格式：

````markdown
下面是代码

```js
console.log(123)
```
````

**Comment by chenbin92** [comment]
@jitaguizhao 上面的代码无法重现问题，建议给出一个最小可复现的 DEMO。 可以基于这个示例 https://github.com/alibaba/ice/tree/master/examples/basic-store

**Comment by chenbin92** [comment]
@jitaguizhao 提供复现 DEMO 可重新打开该 issue
