### ISSUE TITLE
使用 windows.history.back()实现回退问题

### ISSUE THREAD

**Issue by rootsli** [alibaba/ice#3656]
从react子应用，例如：/gpx-ice/gpx-react/#/routera 跳转到/gpx-ice/gpx-vue/#/routerb，使用windows.history.back()时，需要返回2次（浏览器后退也需要点2次）

其中：gpx-ice为icestark微框架，gpx-react为react子应用，routera为react子应用某一路由；gpx-vue为vue子应用，routerb为vue子应用某一路由

## 发生了什么?
从/gpx-ice/gpx-react/#/routera 跳转到/gpx-ice/gpx-vue/#/routerb，执行windows.history.back()，不能返回routera页面，除非执行2次windows.history.back()

## 复现步骤，错误日志以及相关配置

> 建议并上传到你的 GitHub 仓库，请使用 `yarn init ice <project-name>` 选择 Lite 模板，这样您的问题我们会更高优先级的进行解决。

## 期望的结果是什么
使用windows.history.back()时，和pop一样，直接返回gpx-react/#/routera页面，不需要执行windows.history.back()2次。

## 相关环境信息

- **ice.js 版本**：
- **build.json 配置**：
- **Node 版本**：
- **操作系统**：

**Comment by ClarkXia** [comment]
提供下复现 demo

**Comment by rootsli** [comment]
> 提供下复现 demo

这个demo需要一个框架，2个子应用，不太好提供啊

**Comment by ClarkXia** [comment]
> > 提供下复现 demo
> 
> 这个demo需要一个框架，2个子应用，不太好提供啊

可以简单用官方的模版复现下，方便判断

**Comment by rootsli** [comment]
已诊断为子应用内部问题，与框架无关。

**Comment by rootsli** [comment]
已诊断为子应用内部问题，与框架无关。
