### ISSUE TITLE
我是通过iceWorks创建的项目，如何升级ice.js 1.9.7版本

### ISSUE THREAD

**Issue by jitaguizhao** [alibaba/ice#3657]
## 复现步骤，错误日志以及相关配置

> 建议并上传到你的 GitHub 仓库，请使用 `yarn init ice <project-name>` 选择 Lite 模板，这样您的问题我们会更高优先级的进行解决。

## 相关环境信息

- **ice.js 版本**：
- **build.json 配置**：
- **Node 版本**：
- **操作系统**：

**Comment by imsobear** [comment]
看下你 package.json 里 ice.js 的版本号

**Comment by imsobear** [comment]
如果 ice.js 本身就是 1.0.0 的版本，那么重新安装下依赖就可以。
