### ISSUE TITLE
Linux beta 版本试用说明

### ISSUE THREAD

**Issue by noyobo** [alibaba/ice#366]
- 1.4.0-beta 版本：
    - deb: https://iceworks-beta.oss-cn-hangzhou.aliyuncs.com/linux/Iceworks-amd64-1.4.0-beta.deb
    - AppImage: https://iceworks-beta.oss-cn-hangzhou.aliyuncs.com/linux/Iceworks-x86_64-1.4.0-beta.AppImage

Linux 版本首次发布，提供 beta 版本试用，可能存在未知问题，各位请多多包涵，如果遇到问题可向我反馈问题，跟帖或者提交 Issue 都可以。

Linux 版本尚未支持自动更新，如需要新版本，请重新下载安装。

> 更新问题在寻求办法解决中。

**Comment by noyobo** [comment]
Close #259 #112

**Comment by inuxor** [comment]
弄个appimage吧，或者snap发布？这样只打包deb不大合适。更新只要提供一个新版本提示，给个链接就行，不用多费心。

**Comment by noyobo** [comment]
@inuxor AppImage 有打包了。一般 Linux 主流是什么格式的？

**Comment by inuxor** [comment]
linux哪有什么主流，就算是deb还分debian的和ubuntu的，rpm还分redhat的opensuse的。顾不过来。
还不如就维护两条，一个snap，一个flatpak，再给个appimage通用包。这就基本通吃了。

**Comment by noyobo** [comment]
@inuxor 那只提供 AppImage 是否就足够了？

我看其他 VScode atom 基本都是 deb, rpm, 和 tar 可执行程序的包。

**Comment by lu592674374** [comment]
![image](https://user-images.githubusercontent.com/15523855/38294282-ef65db90-381c-11e8-90a6-2be08b194e2c.png)
ubuntu16.04
用的appImage的方式

**Comment by inuxor** [comment]
win版都出2.0了，linux版依旧没动静啊

**Comment by probonopd** [comment]
The AppImage runs well for me on Xubuntu 18.04. Thank you for making it.

![screenshot_2018-05-10_11-15-17](https://user-images.githubusercontent.com/2480569/39862273-d0bef6d6-5432-11e8-9993-cee6f046c80f.png)

**Comment by yan-xz** [comment]
看了上面的评论，deb 还是需要重视的，毕竟用户群体大

**Comment by levinit** [comment]
@noyobo 给源码包就行

**Comment by levinit** [comment]
@FontEndArt 木有发现  1.x就没几个功能  感觉没什么用

**Comment by noyobo** [comment]
维护更新在： https://github.com/alibaba/ice/wiki/Linux
