### ISSUE TITLE
iceworks命令行工具执行时候报404

### ISSUE THREAD

**Issue by nigulasikk** [alibaba/ice#3665]
第一步： npm install -g iceworks
第二步：运行 iceworks init 或 在物料项目中执行  iceworks add

## 发生了什么?
报错 404 （可参照截图）
<img width="1137" alt="截屏2020-10-17 下午9 49 08" src="https://user-images.githubusercontent.com/5045972/96338723-9ab22c80-10c2-11eb-8cf6-6caba00ee359.png">

能正常运行  iceworks add 功能

## 相关环境信息

- **ice.js 版本**：
- **build.json 配置**：
- **Node 版本**：
- **操作系统**：

**Comment by imsobear** [comment]
没有 `iceworks add component` 这个命令，你是想做什么？

**Comment by nigulasikk** [comment]
> 没有 `iceworks add component` 这个命令，你是想做什么？

https://ice.work/docs/materials/guide/component 这个文档里有呀，想要进行物料开发，上周五还能执行的。

**Comment by imsobear** [comment]
嗯  应该是有的，`LOG_LEVEL=verbose iceworks add component` 试下，看看输出。 @nigulasikk

**Comment by nigulasikk** [comment]
感谢 ，找到问题了 ，是我 全局设置了私有源问题
