### ISSUE TITLE
组件开发构建提供升级文档（ice-scripts -> build-scripts）

### ISSUE THREAD

**Issue by inier** [alibaba/ice#3667]
目前，旧版iceworks项目采用的是ice-scripts， 新版采用的@alib/build-scripts，由于版本上的不兼容（项目文件，目录结构都有调整），导致部分bug无法得到快速修复。部分bug：
1. 旧版本上 执行npm run build 时会将package.json中的homepage 修改为  "https://unpkg.com/xxx/build/index.html"（异常行为），而新版本不会（正常行为）

如果要升级组件开发项目，目前只能通过手动新建一个新项目，然后手动拷贝代码的方式来处理。

**iceworks能否出一个可兼容的升级工具，便于老版本的升级。**

**Comment by imsobear** [comment]
- 升级这块我晚点整理下文档
- homepage 新老板本都会改，自由 unpkg 的情况老版本没法通过 [iceworks config](https://ice.work/docs/materials/reference/private#%E9%85%8D%E7%BD%AE%E5%AD%97%E6%AE%B5) 定制，只能通过环境变量定制，修改组件 package.json 的 scripts.build 字段 `UNPKG=https://unpkg.xxxx.com ice-scripts build` 。

**Comment by imsobear** [comment]
升级文档：https://ice.work/docs/materials/reference/upgrade
