### ISSUE TITLE
项目初始刷后， npm install 不成功。

### ISSUE THREAD

**Issue by lz7878** [alibaba/ice#3669]
![image](https://user-images.githubusercontent.com/31120405/96411171-a0228a80-121a-11eb-875d-48c3fd65957e.png)

![image](https://user-images.githubusercontent.com/31120405/96411263-c21c0d00-121a-11eb-9e07-b91cb19e39c3.png)

npm 装不上这个

**Comment by imsobear** [comment]
内部请用 tnpm。
