### ISSUE TITLE
linux版未能识别code-insiders

### ISSUE THREAD

**Issue by inuxor** [alibaba/ice#367]
如下提示，然而确实安装有vscode,只不过是code-insiders版本。

![default](https://user-images.githubusercontent.com/1345457/38227999-8d720254-3733-11e8-9dee-23638b56fc32.png)

如果不想把设置弄得琐碎，可以给留个自定义的口吗？用户自己填写编辑器地址。上边终端设置也可以照此办理。

**Comment by noyobo** [comment]
感谢反馈，这个我优化下。

**Comment by noyobo** [comment]
## 2.6.0-beta
  - [Iceworks-x86_64-2.6.0-beta.AppImage](https://iceworks-beta.oss-cn-hangzhou.aliyuncs.com/linux/Iceworks-x86_64-2.6.0-beta.AppImage)
  - [Iceworks-amd64-2.6.0-beta.deb](https://iceworks-beta.oss-cn-hangzhou.aliyuncs.com/linux/Iceworks-amd64-2.6.0-beta.deb)


2.6.0 版本支持自定义编辑器启动脚本
