### ISSUE TITLE
SubNav自定义Icon缺少样式?

### ISSUE THREAD

**Issue by jacktang** [alibaba/ice#3675]
# 问题

* 代码
```
<NavItem key={path} icon='warning' >
<NavItem key={path} icon={<CustomIcon type="icon-alert" />} >
```

* 使用内嵌icon, 对应的样式有: `next-icon next-icon-warning next-medium next-nav-icon`
* 如果使用外部 icon, 对应的样式有: `next-icon  next-medium`

所以导致
<img width="68" alt="截屏2020-10-20 下午2 44 59" src="https://user-images.githubusercontent.com/44341/96550490-85681880-12e3-11eb-8456-73a6155cfc2a.png">

# 解决

有什么办法可以把 `next-nav-icon` 样式设置进去?

**Comment by youluna** [comment]
<NavItem key={path} icon={<CustomIcon type="icon-alert"  className="next-nav-icon"/>} />

**Comment by jacktang** [comment]
@youluna 你的建议没有解决问题，icon的className是加到 `<svg>` 上，没有加到 `<i>` 上
<img width="438" alt="截屏2020-11-09 上午11 27 17" src="https://user-images.githubusercontent.com/44341/98497364-bc946e80-227e-11eb-8ea8-3934630b3f61.png">

**Comment by jacktang** [comment]
@youluna 请问这个有包含到哪个版本发布吗？

**Comment by jacktang** [comment]
@youluna 有发布计划吗？
