### ISSUE TITLE
子应用发生脚本错误时，icestark框架能否统一捕获错误并提示？

### ISSUE THREAD

**Issue by rootsli** [alibaba/ice#3678]
## 发生了什么?

项目基于icestark微前端架构，子应用脚本错误时，页面会空白，是否可以统一在icestark框架上捕获错误并提示

## 复现步骤，错误日志以及相关配置

> 建议并上传到你的 GitHub 仓库，请使用 `yarn init ice <project-name>` 选择 Lite 模板，这样您的问题我们会更高优先级的进行解决。

## 期望的结果是什么

如题，当子应用脚本错误时，页面空白时，能在icestark框架上捕获错误并提示。

## 相关环境信息

- **ice.js 版本**：
- **build.json 配置**：
- **Node 版本**：
- **操作系统**：

**Comment by imsobear** [comment]
不太好搞，主应用里通过 window.onerror 可以监听错误事件，但是没法区分清楚哪些是白屏的错误。

**Comment by rootsli** [comment]
> 不太好搞，主应用里通过 window.onerror 可以监听错误事件，但是没法区分清楚哪些是白屏的错误。

了解了 那我们在每个子应用里使用错误边界捕获试试
