### ISSUE TITLE
[ Model interaction ] Unhandled Rejection (TypeError): Cannot read property 'actions' of undefined

### ISSUE THREAD

**Issue by somnus-L** [alibaba/ice#3679]
## Any additional comments?

- **ice.js Version**："^1.0.0"
- **build.json Configuration**：
{
  "plugins": [
    [
      "build-plugin-fusion",
      {
        "themePackage": "@alifd/theme-design-pro"
      }
    ],
    [
      "build-plugin-moment-locales",
      {
        "locales": [
          "zh-cn"
        ]
      }
    ],
    "build-plugin-ice-auth"
  ],
  "proxy": {
    "/api": {
      "enable": true,
      "target": "http://localhost:7001"
    }
  }
}
- **Node Version**:  "node": ">=8.0.0"  version :v14.8.0
- **Platform**: drawin mac os

参考这个 
[https://github.com/ice-lab/icestore/blob/master/docs/recipes.md#example](url)

`import { createStore } from '@ice/store'`
`import { upload } from '@/pages/UploadKnowledge/models/upload'`
`import { user } from '@/models/user'`

`const store =  createStore({
    upload,
    user,
})`
`export default store`
`
报这个错误：
![image](https://user-images.githubusercontent.com/18191162/96666479-cc104e00-1389-11eb-83a7-457963e821ec.png)

在 pages 目录下这样使用的

`import { store  } from '@/store/store'`
`const dispatchers = store.useModelDispatchers('user')`
`dispatchers.updateUser(res.user_session)`

**Comment by luhc228** [comment]
icestore 的
`import { user } from '@/models/user'` 看下这里是怎么写的

**Comment by somnus-L** [comment]
这样写的 ：
![image](https://user-images.githubusercontent.com/18191162/96682676-c0ce1a00-13ab-11eb-8c86-539fb0953435.png)

**Comment by luhc228** [comment]
> 这样写的 ：
> ![image](https://user-images.githubusercontent.com/18191162/96682676-c0ce1a00-13ab-11eb-8c86-539fb0953435.png)

导入模块写错了，你上面的是 `export default` 
 
`import { user } from '@/models/user'`  -> `import user  from '@/models/user'`

**Comment by somnus-L** [comment]
我按照你说的，改了导入，但是 现在报这个错，我打印出了store ，如图：
![image](https://user-images.githubusercontent.com/18191162/96716594-d2c5b200-13d7-11eb-8629-722dcb4bfbb4.png)
我是这样用的：
`import store from '@/store/store'`
` const dispatchers = store.useModelDispatchers('user')`
` dispatchers.updateUser(res.user_session).then(()=>{})`

**Comment by somnus-L** [comment]
我的store.js是这样写的 ：

![image](https://user-images.githubusercontent.com/18191162/96717042-7a42e480-13d8-11eb-9a12-5f40a074c935.png)

**Comment by luhc228** [comment]
store.js 的目录错了，目录应该为 src/store.js
