### ISSUE TITLE
icestark切换子应用的时候偶现脚本错误

### ISSUE THREAD

**Issue by rootsli** [alibaba/ice#3689]
## 发生了什么?
![image](https://user-images.githubusercontent.com/4099803/96806727-7601e000-1447-11eb-9c73-2ea0e0b21f88.png)

![image](https://user-images.githubusercontent.com/4099803/96806843-b5c8c780-1447-11eb-8621-1b08b63d461b.png)

## 复现步骤，错误日志以及相关配置
Step1.浏览器设置Disable cache（每次强制加载资源）
Step2.来回切换子应用

当子应用资源较多，加载较慢时，出现截图脚本错误，页面空白。

> 建议并上传到你的 GitHub 仓库，请使用 `yarn init ice <project-name>` 选择 Lite 模板，这样您的问题我们会更高优先级的进行解决。

## 期望的结果是什么

应用切换，加载资源过多时，不出现脚本错误

## 相关环境信息

- **ice.js 版本**：
- **build.json 配置**：
- **Node 版本**：
- **操作系统**：

**Comment by rootsli** [comment]
![image](https://user-images.githubusercontent.com/4099803/96807436-22909180-1449-11eb-8336-2603877075c4.png)

**Comment by ClarkXia** [comment]
webpackJsonp 中的错误，确认下子应用来回切换的时候是否做了 webpackJsonp 的隔离，比如开启 sandbox 或者应用切换后的清空 webpackJsonp。
目前的错误截图无法判断什么原因，可以提供复现 case

**Comment by rootsli** [comment]
> webpackJsonp 中的错误，确认下子应用来回切换的时候是否做了 webpackJsonp 的隔离，比如开启 sandbox 或者应用切换后的清空 webpackJsonp。
> 目前的错误截图无法判断什么原因，可以提供复现 case

没有开启sandbox，但是有清空webpackJsonp。清空逻辑如下：

`
  useEffect(() => {
    console.log("== app leave ==", appLeave);

    if (window.webpackJsonp) {
      delete window.webpackJsonp;
    }

    if (appLeave.path === "/sub" && window.CKEDITOR) {
      window.CKEDITOR = null;
    }
  }, [appLeave]);
`

**Comment by rootsli** [comment]
这个问题目前是偶现，当浏览器设置Disable cache时，出现的概率会变大。

**Comment by ClarkXia** [comment]
截图中 webpackJsonp 被重新封装过，常规 webpackJsonp 是一个数组，内部存储了按需加载信息 ，这种情况建议开启 sandbox 隔离，而不是单纯将 window.webpackJsonp 删除（导出截图中 undefined 报错）。
如果可以提供复现 demo 可以重新开启 issue 协助排查
