### ISSUE TITLE
icestark子应用 页面组件按需加载 主框架不支持？？

### ISSUE THREAD

**Issue by LoLDragon** [alibaba/ice#3690]
#2729  发生了什么?

如题， 子应用页面组件采用按需加载，主框架配置子应用url地址后，切换到相应子应用报错。具体信息如下：
主框架注册：
![image](https://user-images.githubusercontent.com/19163371/96818297-ca12c180-1453-11eb-848b-c3b5bf0a7b47.png)
主框架加载子应用报错提示：
![image](https://user-images.githubusercontent.com/19163371/96817878-d8141280-1452-11eb-8e69-c054ca122197.png)

## 期望的结果是什么
子应用采用按需加载时， 主框架正常展示页面

## 相关环境信息

- **ice.js 版本**：1.0.14
- **build.json 配置**：
- **Node 版本**：
- **操作系统**：

**Comment by ClarkXia** [comment]
子应用按需加载的情况下只需要配置入口脚本，比如 index.js，其他 bundle 将根据 webpackJsonp 中内容按需加载，按需加载是注意子应用打包时候的 [publicPath 设置](https://ice.work/docs/icestark/guide/child-app#%E5%AD%90%E5%BA%94%E7%94%A8%20bundle%20%E5%8A%A0%E8%BD%BD%E5%A4%B1%E8%B4%A5%EF%BC%9F)

**Comment by LoLDragon** [comment]
@ClarkXia 子应用已经配置了publicPath了，你现在是按当前域名加载分割后的文件块，会报404错误啊，具体应该怎么处理？你这里描述不是很清楚

**Comment by imsobear** [comment]
本地环境要配置 devPublicPath

**Comment by LoLDragon** [comment]
子应用配置的devPublicPath或者publicPath如果与主框架不是同一个域名，必须要带上当前的**子应用的域名和端口**，不能仅仅配置常规的相对路径。

**Comment by liqupan** [comment]
> 子应用配置的devPublicPath或者publicPath如果与主框架不是同一个域名，必须要带上当前的**子应用的域名和端口**，不能仅仅配置常规的相对路径。

请问可以来一个demo嘛，publicPath和devpublicPath配置信息和主应用主子应用入口地址如何配置的

**Comment by liqupan** [comment]
> 子应用按需加载的情况下只需要配置入口脚本，比如 index.js，其他 bundle 将根据 webpackJsonp 中内容按需加载，按需加载是注意子应用打包时候的 [publicPath 设置](https://ice.work/docs/icestark/guide/child-app#%E5%AD%90%E5%BA%94%E7%94%A8%20bundle%20%E5%8A%A0%E8%BD%BD%E5%A4%B1%E8%B4%A5%EF%BC%9F)

@ClarkXia
链接失效了 请问可以来一个demo嘛，publicPath和devpublicPath配置信息和主应用主子应用入口地址如何配置的

**Comment by liqupan** [comment]
类似的错误 请问webpack的pubilcpath 和 devpublicpath应该如何配置
![image](https://user-images.githubusercontent.com/21078925/120954998-01d03e80-c783-11eb-8904-ef2b98094a6c.png)

**Comment by imsobear** [comment]
https://micro-frontends.ice.work/faq#%E5%BE%AE%E5%BA%94%E7%94%A8-bundle-%E5%8A%A0%E8%BD%BD%E5%A4%B1%E8%B4%A5%EF%BC%9F @liqupan

**Comment by liqupan** [comment]
> https://micro-frontends.ice.work/faq#%E5%BE%AE%E5%BA%94%E7%94%A8-bundle-%E5%8A%A0%E8%BD%BD%E5%A4%B1%E8%B4%A5%EF%BC%9F @liqupan

感谢 配置pubilcpath、devpublicpath解决问题了
