### ISSUE TITLE
嵌套路由报错

### ISSUE THREAD

**Issue by koryuoh123** [alibaba/ice#3701]
ice:1.9.0
routes.js配置

const XXX = lazy(()=>import ('@/pages/XXX')
const YYY= lazy(()=>import ('@/pages/YYY')

` {
    path: '/',
    component: BasicLayout,
    children: [
      { path: '/xxx',
        component: XXX,
        children: [
          {
            pathname: '/yyy',
            component: YYY,
          }
        ]
       },
       ......
`
报错：
![image](https://user-images.githubusercontent.com/60175264/96997042-90c97700-1563-11eb-95f1-36c81c7510a3.png)
![image](https://user-images.githubusercontent.com/60175264/96997081-a343b080-1563-11eb-888b-c47c34666981.png)

想要在一个页面里面再渲染另个页面组件并用路由控制

**Comment by chenbin92** [comment]
@koryuoh123 给出完整的重现 DEMO

**Comment by chenbin92** [comment]
无法复现，提供可复现 DEMO 后可重新打开改 issue
