### ISSUE TITLE
iceworks中新增页面父级路由必选问题

### ISSUE THREAD

**Issue by whit15** [alibaba/ice#3702]
## 发生了什么?

使用最新版本的iceworks，在vscode扩展商店中显示的版本是v0.12.0，所有依赖都为最新版本。
当用使用区块组装页面或使用模板生成页面时，新增页面的弹出框中要求必须选择父级路由，但是我添加的是一个不需要框架界面的登录页面，默认选择BasicLayout的话，生成出来的页面是这样
![image](https://user-images.githubusercontent.com/9914116/97102629-0f4c2300-16e2-11eb-9a01-c1e36b58affd.png)

是不是可以提供一个选择是无父级路由，或者非必选呢？
![image](https://user-images.githubusercontent.com/9914116/97102522-2b9b9000-16e1-11eb-8293-f8876a91cdfe.png)

## 复现步骤，错误日志以及相关配置

> 建议并上传到你的 GitHub 仓库，请使用 `yarn init ice <project-name>` 选择 Lite 模板，这样您的问题我们会更高优先级的进行解决。

## 期望的结果是什么

让新增页面脱离基础框架，提供一个选择是无父级路由，或者非必选。

## 相关环境信息

- **ice.js 版本**：^1.0.0
- **build.json 配置**：{
  "plugins": [
    [
      "build-plugin-fusion",
      {
        "themePackage": "@alifd/theme-design-pro"
      }
    ],
    [
      "build-plugin-moment-locales",
      {
        "locales": [
          "zh-cn"
        ]
      }
    ]
  ]
}

- **Node 版本**：v12.18.3
- **操作系统**：MacOS 10.15.7

**Comment by chenbin92** [comment]
@alvinhui  看下这个

**Comment by luhc228** [comment]
Iceworks 发布新版本已解决
