### ISSUE TITLE
通过可视化搭建的组件form里有个初始化数据设置问题

### ISSUE THREAD

**Issue by xulin56** [alibaba/ice#3707]
初始化设置里是export default一个对象，对象里的key值应该是对应的下面的FormItem的字段名，可是设置了没什么变化，组件没有被返填

**Comment by imsobear** [comment]
多给点信息，比如可视化搭建的截图

**Comment by xulin56** [comment]
![Uploading image.png…]()

**Comment by imsobear** [comment]
补充了信息再 reopen 下

**Comment by xulin56** [comment]
这个issues怎么放截图啊？

**Comment by imsobear** [comment]
快捷键复制粘贴

**Comment by xulin56** [comment]
这就是截图![Uploading image.png…]()
