### ISSUE TITLE
ice.js 支持 webIDE 下输出 dev 地址

### ISSUE THREAD

**Issue by ClarkXia** [alibaba/ice#3708]
目前 ice.js 在 webIDE 下输出的 dev 地址不准确，希望可以正确输出泛域名地址

**Comment by imsobear** [comment]
DEF WebIDE 那边怎么说的

**Comment by ClarkXia** [comment]
> DEF WebIDE 那边怎么说的

目前仅支持 process.env.RequestedIP 这个真实 IP 地址
alipay ide 貌似通过 process.env.HOST 注入了域名信息

**Comment by imsobear** [comment]
嗯 可以推进下，最好是保持一致

**Comment by imsobear** [comment]
- CLOUDIDE_ENV 表示 WebIDE 环境
- WORKSPACE_UUID 表示当前空间 uuid
- WORKSPACE_HOST 表示当前所用域名
- WORKSPACE_IP    当前空间容器的 ip，使用 ip 地址预览的情况下

拼接规则： `https://${UUID}-${port}.${WORKSPACE_HOST}`
