### ISSUE TITLE
本地开发模式主应用开启sandbox,通过url连接子应用提示跨域？

### ISSUE THREAD

**Issue by WeiZe-Yaooh** [alibaba/ice#3716]
<img width="581" alt="截屏2020-10-26 下午6 05 13" src="https://user-images.githubusercontent.com/27259858/97249438-c958a180-183e-11eb-9e68-e569545c0462.png">
<img width="425" alt="截屏2020-10-26 下午6 05 44" src="https://user-images.githubusercontent.com/27259858/97249440-c9f13800-183e-11eb-9961-0c5557ff7a41.png">
<img width="425" alt="截屏2020-10-26 下午6 05 44" src="https://user-images.githubusercontent.com/27259858/97249552-10469700-183f-11eb-98ee-1d66ce6ee33a.png">

沙盒模式应该怎样在开发模式下使用？生产环境需要使用nginx配置？

**Comment by imsobear** [comment]
子应用的 wwebpack devServer 配置下 cors
