### ISSUE TITLE
webpack配置的子应用和主应用，连接时提示error occurs when execute script in sandbox: ReferenceError: __webpack_require__ is not defined

### ISSUE THREAD

**Issue by WeiZe-Yaooh** [alibaba/ice#3717]
<img width="1054" alt="截屏2020-10-27 上午11 24 41" src="https://user-images.githubusercontent.com/27259858/97253312-0f196800-1847-11eb-89c5-951d3eb9068a.png">

**Comment by imsobear** [comment]
截图后面全一点，错误是执行 app.js 报的错还是执行 chunk 时报的错？

**Comment by WeiZe-Yaooh** [comment]
执行app.js报的错

**Comment by WeiZe-Yaooh** [comment]
执行app.js报的错

**Comment by WeiZe-Yaooh** [comment]
<img width="1427" alt="截屏2020-10-27 上午11 39 44" src="https://user-images.githubusercontent.com/27259858/97254354-248f9180-1849-11eb-9904-e6ce22dbe891.png">
但是子应用的文件是加载成果的

**Comment by WeiZe-Yaooh** [comment]
应该是主应用开启沙盒后没有匹配的到子应用的文件资源

**Comment by imsobear** [comment]
![image](https://user-images.githubusercontent.com/2505411/97256639-8acae300-184e-11eb-8176-d97487858c85.png)

这一行截图全一点，看下是哪个文件抛出来的错误

**Comment by WeiZe-Yaooh** [comment]
很奇怪  现在又不报错了～～

**Comment by qingwenje2008** [comment]
我也出现了这种情况 ，子应用做了改造 ，在父应用通过menu跳转到对应子应用页面的时候，第一次正常，切到别的页面，再回来就报这个错 index.js:1 error occurs when execute script in sandbox: Error: only one instance of babel-polyfill is allowed

**Comment by yuxiuj** [comment]
@qingwenje2008 @wzyaooh 请问具体是怎么解决这个问题的呢？

**Comment by markexin** [comment]
![image](https://user-images.githubusercontent.com/18322323/129204453-29cd118c-c361-4080-9d8a-621216593332.png)
@imsobear 你好，本地启动访问是没有问题的。但是微应用接入之后就报这个错误

**Comment by maoxiaoke** [comment]
[@ice/sandbox 1.3.1](https://github.com/alibaba/ice/issues/3717?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDEyNzU1NDUwOTk6MTM0MTcwMDY%3D&notifications_query=repo%3Aalibaba%2Fice#issuecomment-897637569) 应该修复了这个问题
