### ISSUE TITLE
脚手架默认默认开启 eslint 配置

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#3722]
## 问题

eslint 作为项目开发的基础规范之一，我们非常建议并推荐在开发时遵循同一套 eslint 规范，同时 ICE 也提供一套最佳实践的 @ice/spec 规则，在开发项目过程中只需要在 build.json 中开启即可。

```json
"eslint": true
```

## 预期

模板默认开启 eslint 规则。

**Comment by imsobear** [comment]
官方相关的几个地方：

- ice-lab/material-templates
- alibaba-fusion/materials
- ice-inside

**Comment by imsobear** [comment]
这个可以考虑 @fyangstudio 来做，顺便把 spec 更新掉。

**Comment by imsobear** [comment]
改动点增加：去除 tsconfig 和 jsconfig 里的 `"ice/*": [".ice/pages/*"]`

**Comment by fyangstudio** [comment]
* [x] raxjs/rax-materials 
* [ ] ice-lab/material-templates
* [ ] ice-inside
* [ ] alibaba-fusion/materials

**Comment by fyangstudio** [comment]
> 改动点增加：去除 tsconfig 和 jsconfig 里的 `"ice/*": [".ice/pages/*"]`

@chenbin92 ice-inside 和 alibaba-fusion/materials 这2个仓库的 ice/store 的用法 能更新下吗？

**Comment by imsobear** [comment]
同步下昨天跟 @fyangstudio 沟通的结论：

- 暂时先不开启 eslint，原因：eslint 规则当下还是偏严格的，很多写法不符合 eslint 规范但其实是能正常运行的；目前 eslint-loader 是阻塞式的，有 lint 错误就不能正常预览开发，对开发者影响较大；我们的文档以及 demo 很多地方的代码片段都不符合 eslint 规范，开发者直接 copy 过去会比较痛苦；开发者整体素养没那么高。
- 后续的 Actions：
  - 新开发一个 eslint-loader，不阻塞正常预览，比如页面上有个气泡显示对应的错误
  - 文档/demo 等代码逐渐推进符合规范
  - 上面两个做完之后在默认开启脚手架的  eslint

**Comment by chenbin92** [comment]
> > 改动点增加：去除 tsconfig 和 jsconfig 里的 `"ice/*": [".ice/pages/*"]`
> 
> @chenbin92 ice-inside 和 alibaba-fusion/materials 这2个仓库的 ice/store 的用法 能更新下吗？

done

**Comment by chenbin92** [comment]
结论：与 @fyangstudio  确认沟通已完成。
