### ISSUE TITLE
ice-plugin-css-assets-local的CSS 网络资源本地化失败

### ISSUE THREAD

**Issue by wujunbiao1002** [alibaba/ice#3724]
## 发生了什么?

ice-scripts 2.1.17中
使用ice-plugin-css-assets-local的CSS 网络资源本地化发现字体资源没有被下载下来
之前一直使用着没有问题，最近发现无法成功下载离线资源
![image](https://user-images.githubusercontent.com/22448122/97283778-3b4edc00-187b-11eb-80e5-79da74504f27.png)

![image](https://user-images.githubusercontent.com/22448122/97284383-f0819400-187b-11eb-9d3a-f76525039710.png)

## 复现步骤，错误日志以及相关配置

> 建议并上传到你的 GitHub 仓库，请使用 `yarn init ice <project-name>` 选择 Lite 模板，这样您的问题我们会更高优先级的进行解决。
[复现demo.zip](https://github.com/alibaba/ice/files/5444290/demo.zip)

## 期望的结果是什么
怎么解决这样的问题

## 相关环境信息

- **ice-scripts 版本**：ice-scripts 2.1.17
- **Node 版本**：v12.18.3
- **操作系统**：windows10

**Comment by luhc228** [comment]
你现在提供的 demo 项目中，依赖的组件库没有需要离线下载的资源

**Comment by wujunbiao1002** [comment]
增加fusion组件使用demo
[增加组件使用demo.zip](https://github.com/alibaba/ice/files/5445803/demo.zip)

**Comment by luhc228** [comment]
应该是 extract-css-assets-webpack-plugin@0.2.7 的版本有问题，我们修复一下

**Comment by luhc228** [comment]
已发布 extract-css-assets-webpack-plugin@0.2.8 解决
