### ISSUE TITLE
文件狀態管理部分事例錯誤

### ISSUE THREAD

**Issue by farrrr** [alibaba/ice#3725]
照著文件示例去做發現有錯誤，應該是原本是從 1.9.7 的自動產生 store 轉變成自定義創建 Store 實例沒更改到的原因。

文件中所有 `import { store } from '@/store';` 都應該改成 `import store from '@/store';`
這樣才能跟示例中的 `自定義創建 Store 實例` 能夠搭配上。

另外頁面狀態的部分 `import { store as pageStore } from '@/pages/Home/store';` 也必須改成 `import pageStore from '@/pages/Home/store';` 才對。

原本是要發 PR.. 但看文件到最後 `設置初始狀態` 裏的 `import { runApp } from '@/store';` 是不是也錯了？

**Comment by farrrr** [comment]
另外 `import { createStore, IStoreModels, IStoreDispatch, IStoreRootState } from 'ice';` 在 ice 裡沒看到 IStoreModels, ISToreDispatch, IStoreRootState 的 export...

**Comment by luhc228** [comment]
> 另外 `import { createStore, IStoreModels, IStoreDispatch, IStoreRootState } from 'ice';` 在 ice 裡沒看到 IStoreModels, ISToreDispatch, IStoreRootState 的 export...

如果是自定义创建 store 时，上面所提到的 IStoreModels, ISToreDispatch, IStoreRootState，框架不会导出，需要自己导出

**Comment by luhc228** [comment]
> 照著文件示例去做發現有錯誤，應該是原本是從 1.9.7 的自動產生 store 轉變成自定義創建 Store 實例沒更改到的原因。
> 
> 文件中所有 `import { store } from '@/store';` 都應該改成 `import store from '@/store';`
> 這樣才能跟示例中的 `自定義創建 Store 實例` 能夠搭配上。
> 
> 另外頁面狀態的部分 `import { store as pageStore } from '@/pages/Home/store';` 也必須改成 `import pageStore from '@/pages/Home/store';` 才對。
> 
> 原本是要發 PR.. 但看文件到最後 `設置初始狀態` 裏的 `import { runApp } from '@/store';` 是不是也錯了？

文档是有问题的，我们对应修改一下

**Comment by luhc228** [comment]
文档已更新
