### ISSUE TITLE
工程底层依赖包从 ice-scripts 仓库迁移

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#3728]
比如 https://github.com/ice-lab/ice-scripts/tree/master/packages/extract-css-assets-webpack-plugin

**Comment by ClarkXia** [comment]
### 迁移策略
#### 方案一
独立的 webpack plugin/loader 单独在 ice-lab 下新建仓库管理，icejs 仓库下仅维护 builder-*、plugin-*、create-*

#### 方案二
独立的 webpack plugin/loader 迁移到 icejs 仓库下，通过统一目录前缀 webpack-* 进行管理

> 从维护性的角度考虑更加倾向 方案二 进行统一维护

**Comment by ClarkXia** [comment]
已迁移
