### ISSUE TITLE
injectBabel配置runtime后build报错

### ISSUE THREAD

**Issue by chenhebing** [alibaba/ice#3733]
## What is the current behavior?
injectBabel配置runtime在build时候报下面错
![image](https://user-images.githubusercontent.com/12512045/97410069-8deecd80-1939-11eb-9788-bbec83079470.png)

## What is the expected behavior?**
正常构建
## Any additional comments?

- **ice.js Version**：1.9.9
- **build.json Configuration**：
{
  "alias": {
    "@": "./src",
    "@components": "./src/components",
    "@utils": "./src/utils"
  },
  "disableRuntime": true,
  "devServer": {
    "host": "local.wapa.taobao.com",
    "port": 4444,
    "https": true,
    "compress": false
  },
  "mpa": true,
  "injectBabel": "runtime",
  "plugins": [
    "@ali/build-plugin-ice-def"
  ]
}
- **Node Version**: 12
- **Platform**: macos

**Comment by chenbin92** [comment]
项目开发不推荐使用 `injectBabel: runtime`，如果是组件开发请使用 iceworks-cli。另外对于项目开发按需 polyfill 的能力详见 https://github.com/raxjs/rax-scripts/issues/468#issuecomment-719425852
