### ISSUE TITLE
npm init rax 生成的 Kraken 工程项目开发访问地址 404

### ISSUE THREAD

**Issue by andycall** [alibaba/ice#3734]
![image](https://user-images.githubusercontent.com/4409743/97436107-6a894a00-195c-11eb-93ee-0b83c537ad2f.png)

![image](https://user-images.githubusercontent.com/4409743/97436128-6fe69480-195c-11eb-8cd3-b3a6d213f38d.png)

## What is the current behavior?

![image](https://user-images.githubusercontent.com/4409743/97435931-2138fa80-195c-11eb-944a-d8e20f8fab86.png)

**Comment by SoloJiang** [comment]
build.json 配置一下 devServer:{writeToDisk:true}就好了

**Comment by andycall** [comment]
![image](https://user-images.githubusercontent.com/4409743/97436555-28acd380-195d-11eb-9ab3-2e39265c84c9.png)

**Comment by SoloJiang** [comment]
已经修复，更新依赖即可
