### ISSUE TITLE
插件 runtime 代码提升可调试性

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#3742]
## What is the current behavior?

项目本地开发时，两个问题：

- 插件 runtime 代码分布在 node_modules 里，无论是编辑器还是 chrome source 面板里，找起来比较困难
- 这部分代码都是 babel 编译后的，本质跟 npm 依赖一样

## What is the expected behavior?**

我的建议：

- 插件 src 发到 npm
- icejs 将插件 src/runtime 代码 copy 到 .ice 下使用（需要确认下依赖之类的有没有问题）

> 如果 src 不行的话，兜底方案是把 lib 目录搞过去

## Any additional comments?

- **ice.js Version**：
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by ClarkXia** [comment]
## 方案

dev 阶段支持调试 runtime 能力：
```bash
$ icejs start --debug-runtime
```

1. 开启调试后，临时默认生成 plugins 目录，依赖插件 runtime 的包内容将会被复制到目录中
2. 通过 loadRuntimeModules 加载的路径引用将指向  `${TEMP_PATE}/plugins/${plugin-name}`
3. npm 发包时，同时发布 src 目录，debug 模式开始后优先指向 src 目录，如果不存在则以原先引用目录为准

**Comment by imsobear** [comment]
不用通过参数开启吧，默认支持就行了

**Comment by ClarkXia** [comment]
建议通过参数开启，目前没有单独对 src 下内容判断是否是 runtime，因此直接拷贝过去的内容相对比较杂乱。
虽然开发者不关心临时目录内容，日常开发过程中还是希望保证目录内容的规范。仅在排查和调试过程中开启这项能力。

**Comment by imsobear** [comment]
加参数的话我感觉意义不大~~

**Comment by ClarkXia** [comment]
目前以参数的形式开启，默认开启的情况下直接拷贝到用户目录下 并不是特别友好
后续优化通过指定运行时文件的方式，精细化拷贝内容，再考虑默认开启

**Comment by ClarkXia** [comment]
参见 #4119 优化逻辑
