### ISSUE TITLE
飞冰如何和Freemarker模板进行通讯？

### ISSUE THREAD

**Issue by sunruinian** [alibaba/ice#3744]
## 复现步骤，错误日志以及相关配置

> 建议并上传到你的 GitHub 仓库，请使用 `yarn init ice <project-name>` 选择 Lite 模板，这样您的问题我们会更高优先级的进行解决。

## 相关环境信息

- **ice.js 版本**：
- **build.json 配置**：
- **Node 版本**：
- **操作系统**：

**Comment by chenbin92** [comment]
不支持如题所述的 Freemarker 进行通讯的解决方案。建议了解下前后端分离的开发模式 。
