### ISSUE TITLE
部署 html 到非根目录时，对应路由的base配置缺失

### ISSUE THREAD

**Issue by Mario34** [alibaba/ice#3745]
## 发生了什么?
项目需要部署在非根目录，但没有找到相关可配置项或文档未体现，相似配置参考 [umi](https://umijs.org/zh-CN/config#base) [vue-router](https://router.vuejs.org/zh/api/#base)

## 相关环境信息

- **ice.js 版本**：1.0.1
- **build.json 配置**：
- **Node 版本**：
- **操作系统**：

**Comment by imsobear** [comment]
src/app.ts：

```js
const appConfig = {
  router: {
    basename: '/seller'
  }
};
runApp(appConfig);
```

文档遗漏了，我们补充下。

**Comment by imsobear** [comment]
https://ice.work/docs/guide/basic/router#%E8%BF%90%E8%A1%8C%E6%97%B6%E9%85%8D%E7%BD%AE 文档已补充
