### ISSUE TITLE
新项目选型，icejs和umijs v3，两者都是阿里系出品，都支持插件机制、区块、模板等，路由菜单权限Mock什么的也都挺像，粗略看下来也就是数据流上的区别，能从作者角度对两者做下更细致的对比以及给出开发者选型的建议吗？

### ISSUE THREAD

**Issue by futurexiong** [alibaba/ice#3746]
如题。

**Comment by engru** [comment]
如题

**Comment by chenbin92** [comment]
## 从时间维度看：

#### 2017

ICE 提出物料体系概念，包括基础组件、业务组件、区块、模板四个概念，主要目的是基于基础组件沉淀上层的物料提升研发效率。这一阶段的核心为：
- 物料（区块、业务组件、模板）
- 开放物料开发工具 ice-devtools（同时支持 Vue ）
- 工程 ice-scripts 0.x（黑盒逻辑较多，支持简单的配置）

#### 2018
ICE 体系下基于物料的 GUI 研发工具 [发布 1.0 版本](https://zhuanlan.zhihu.com/p/34265596)，Slogan 为「海量可复用物料，通过 GUI 工具极速构建中后台应用」。主要目的是基于物料的模式与 GUI 进行融合，降低前端工程门槛，降低物料的使用成本，进一步提升研发效率。这一阶段的核心为：
- GUI 工具 iceworks （可视化研发工具）
- 工程 ice-scripts 1.x 版本（增强版本的工程）
- 物料的不断沉淀和优化

#### 2019

通过与 Fusion Design 合作，在物料方面进行大幅度的优化，其中主要表现在对模板的再设计，对工程能力的再升级。这一阶段的核心为：

- iceworks 升级为集成式研发工作发布 4.0 版本
- 工程 ice-scripts 2.x 版本（插件化的工程设计）
- 物料开发工具升级 iceworks-cli
- 全新物料（Fusion Design Pro 等模板）
- 自研数据流方案 icestore
- 自研微前端方案 icestark

#### 2020

通过对工程能力和业务开发的最佳实践进行再整合，即对应用开发时进行规范和标准化，如目录规范、ESLint 规则、样式、权限管理、状态管理等。同时对于不同场景下的技术方案如 微前端 icestark、SSR、MPA、Prerender 等也进一步进行收敛，届时我们推出了 ICE 的研发框架 ice.js 1.0 版本。这一阶段的核心为：

- 工程和模板能力进行再整合升级为「企业级的研发框架」ice.js
- iceworks 通过 VSCode 进行打通升级为「可视化智能研发助手」
- 一些还在规范但不方便写的

## 从技术发展看：

这里先不展开讨论 iceworks 的发展，单从题主的标题来看应该主要是想了解 icejs 相关。下面是一张简陋的 icejs 发展图，结合上面的时间线发展来看，icejs 只是我们在技术演进上很自然而然的一个衍生物，当然在未来的某个时间点上也可能被替换掉。

![image](https://user-images.githubusercontent.com/3995814/97824877-1b466f00-1cf8-11eb-8ac5-7da287dad03f.png)

## 小结

至于标题提到的插件机制、区块、路由权限、Mock 之类的功能，这个就不展开细节讨论了。icejs 的主要命题是为解决淘系（淘宝、天猫）的中后台业务而存在，但解决自身业务的同时，ICE 也基本是阿里绝大部分的中后台业务方的选择。最后在贴一张 ICE 整体的大图：

![image](https://user-images.githubusercontent.com/3995814/97825580-0f5bac80-1cfa-11eb-9429-4849d24f3da0.png)

**Comment by futurexiong** [comment]
感谢回复，但这只是ice的发展简述，还是希望有一些icejs和umijs的对比，毕竟看文档，api和采坑都是要花不少时间的，这样开发较少的技术团队可以更快的达成选型方案。

**Comment by chenbin92** [comment]
@futurexiong 

> 感谢回复，但这只是ice的发展简述。

知过去，晓未来。

> 还是希望有一些icejs和umijs的对比，毕竟看文档，api和采坑都是要花不少时间的，这样开发较少的技术团队可以更快的达成选型方案。

上面其实提到一些，除了大而全的基础能力外。icejs 在工程化上支持 JSON 化配置，通过插件机制除了扩展功能能力外还支持通过扩展运行时能力，以及框架的框架进行自定义等。

不过我觉得你是想要一份更细致的对比，从各个功能维度进行横纵向的对比表格。如果是这样更希望是作为开发者进行自调研来对比。其实就是把大家的各自能力进行梳理，看看谁支持了什么不支持什么，扩展性、稳定性、维护团队等方面考虑。
