### ISSUE TITLE
mac系统的官方物料库启动失败

### ISSUE THREAD

**Issue by jadestarzuo** [alibaba/ice#3749]
## 本地物料库区块物料启动失败，我就尝试使用官方提供的，也失败

![image](https://user-images.githubusercontent.com/25679725/97828450-15ee2200-1d02-11eb-87e3-59962b5d726a.png)

## 复现步骤，错误日志以及相关配置

官方的物料仓库报错复现步骤：
1、根目录下，执行npm i
2、区块物料  cd blocks/ActionTable
3、npm i
4、npm start

启动失败

尝试过删除node_module包，重新通过cnpm安装，也失败

## 期望的结果是什么

区块物料启动正常

## 相关环境信息
项目就是咱们官方提供的物料仓库项目：
 https://github.com/alibaba-fusion/materials

- **ice.js 版本**：ice.js 1.10.0
- **build.json 配置**：配置没动过
- **Node 版本**：v14.3.0
- **操作系统**：mac系统   10.15.7

**Comment by imsobear** [comment]
主动安装 core-js 之后可以了，比较奇怪。

按道理 plugin-block -> build-scripts-config -> core-js，是不需要开发者手动引入的，后面能稳定重现了再看。
