### ISSUE TITLE
windows10 安装报错

### ISSUE THREAD

**Issue by wanglong167** [alibaba/ice#375]
![image](https://user-images.githubusercontent.com/456516/38370536-ead8d2d4-391c-11e8-9a4a-11a87c3719be.png)

**Comment by noyobo** [comment]
32位系统吗？

**Comment by nmxiaowei** [comment]
@wanglong167 关闭杀毒软件试试，可能杀毒软件把exe程序删除了

**Comment by wanglong167** [comment]
64系统

**Comment by wanglong167** [comment]
可能安装后自动启动有问题，  我手动启动是好的
