### ISSUE TITLE
使用cli创建antd的基础脚手架并且安装了build-plugin-antd，VSCode的iceworks插件也没法选择antd的区块和模板来创建Page吗？

### ISSUE THREAD

**Issue by futurexiong** [alibaba/ice#3755]
如题。

**Comment by futurexiong** [comment]
通过https://github.com/ice-lab/antd-materials里的readme说明添加了antd物料源，但vscode iceworks插件的antd物料源搜索不出任何物料
<img width="1024" alt="QQ20201103-093328@2x" src="https://user-images.githubusercontent.com/1567478/97936813-b3eff400-1db7-11eb-8254-3c0a613009bc.png">

**Comment by luhc228** [comment]
这个 antd 物料源没有 pages 相关物料(见下图)。因此你用这个 「Generate Page by Configuration」的功能时，显示没有 antd 相关的物料源
![image](https://user-images.githubusercontent.com/44047106/97938360-34b0ef00-1dbc-11eb-8bbf-6d9da259f1eb.png)

**Comment by futurexiong** [comment]
嗯，看过里面的配置，区块，组件，页面都没有，就单纯一个脚手架了，那官方这个物料源实际用处不大了。

**Comment by imsobear** [comment]
@futurexiong 目前还没有太多精力建设 antd 的物料源，有精力的话可以共建，或者建设你们业务自己的物料源也可以。
