### ISSUE TITLE
IE11下子应用使用entry模式不能正常加载，fetch已经polyfill 过

### ISSUE THREAD

**Issue by darkmice** [alibaba/ice#3762]
IE11下子应用使用entry模式不能正常加载，fetch已经polyfill 过

![image](https://user-images.githubusercontent.com/1502088/98080642-b4b88100-1eb0-11eb-8627-4b5cc8ee7ce4.png)

![image](https://user-images.githubusercontent.com/1502088/98080618-a9fdec00-1eb0-11eb-846a-161c05018c4b.png)

## 相关环境信息

- **ice.js 版本**：1.10.0
  "build-plugin-icestark": "^1.7.2-2",
- **build.json 配置**：
- **Node 版本**：
- **操作系统**：window10

**Comment by darkmice** [comment]
解决了，需要把 `import 'whatwg-fetch';` 放到最前面，

**Comment by rootsli** [comment]
> 解决了，需要把 `import 'whatwg-fetch';` 放到最前面，

为啥我放到最前面也不行，每次需要强制刷新才能加载。 @darkmice 你们子应用是broswer路由还是hash路由？
