### ISSUE TITLE
使用飞冰构建的项目怎么解决跨域的问题?

### ISSUE THREAD

**Issue by ZhouWHao** [alibaba/ice#377]
![7_ ht yno bx vee a](https://user-images.githubusercontent.com/18208612/38461968-7d6b244a-3b10-11e8-8188-3c83a6e12ffd.png)

**Comment by noyobo** [comment]
1. 可以通过反向代理的方式参考： https://alibaba.github.io/ice/#/docs/advanced/webpackrc 
2. 如果后端服务方便的话也可以修改 CORS 策略（https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Access_control_CORS）

**Comment by nick-ma** [comment]
@ZhouWHao 如果用eggjs做后端的话，可以用一个cors的插件，配置一下就好了，不用改现有的中间件的程序和接口。

**Comment by nmxiaowei** [comment]
@ZhouWHao  可以后台设置请求头origin 为*

**Comment by yujiangshui** [comment]
@nmxiaowei 不推荐这样，会产生一定的隐患，建议还是走域名白名单的方式。虽然这样省事一些。
