### ISSUE TITLE
router wrappers 配置报错

### ISSUE THREAD

**Issue by henanlzt** [alibaba/ice#3770]
问题现象：
![image](https://user-images.githubusercontent.com/466811/98248110-7655bb80-1faf-11eb-8871-7ea657792e10.png)
![image](https://user-images.githubusercontent.com/466811/98248146-82da1400-1faf-11eb-9572-999aa1887054.png)
![image](https://user-images.githubusercontent.com/466811/98248171-8a012200-1faf-11eb-8864-f4a8f276d210.png)
![image](https://user-images.githubusercontent.com/466811/98248192-908f9980-1faf-11eb-99d6-c9ccf94af809.png)
router配置
...
{
        path:'/api/setting',
        component: DsApi,
        // 配置路由的高阶组件
        wrappers: [WrapperPage]
      },

wrapper组件:
`import { useAuth, history } from 'ice';
import React from 'react';

const WrapperPage = (PageComponent) => {
  return (props) => {
    // eslint-disable-next-line react-hooks/rules-of-hooks
    const [auth] = useAuth();
    if (!auth.login) {
      history.push('/403');
    }
    return <PageComponent {...props} />;
  };
};
export default WrapperPage;
`
错误信息：
`Uncaught TypeError: curr is not a function
    at http://localhost:3333/js/index.js:128694:23
    at Array.reduce (native)
    at wrapperRoute (http://localhost:3333/js/index.js:128693:35)
    at http://localhost:3333/js/index.js:128708:57`

代码：
`Object.defineProperty(exports, "__esModule", { value: true });
exports.IceRouter = void 0;
/* eslint @typescript-eslint/explicit-function-return-type:0, react/jsx-filename-extension: 0, no-shadow: 0, @typescript-eslint/no-explicit-any:0 */
var React = require("react");
var react_router_dom_1 = require("react-router-dom");
function wrapperRoute(component, routerWrappers) {
    return (routerWrappers || []).reduce(function (acc, curr) {
        var compose = curr(acc);
        if (acc.pageConfig) {
            compose.pageConfig = acc.pageConfig;
        }
        if (acc.getInitialProps) {
            compose.getInitialProps = acc.getInitialProps;
        }
        return compose;
    }, component);
}`

package.json
{
  "name": "@alifd/fusion-design-pro-js",
  "version": "0.1.24",
  "description": "使用 JavaScript，包含大量 UI 区块，比如图表、表单等。",
  "dependencies": {
    "@alifd/next": "^1.19.4",
    "@alifd/theme-design-pro": "^0.6.2",
    "@antv/data-set": "^0.10.2",
    "@types/qs": "^6.9.5",
    "@types/react": "^16.9.55",
    "@types/react-dom": "^16.9.9",
    "@types/webpack": "^4.41.22",
    "anymatch": "^3.1.1",
    "bizcharts": "^3.5.6",
    "braces": "^3.0.2",
    "build-plugin-ice-auth": "^1.7.0",
    "is-glob": "^4.0.1",
    "jsonp": "^0.2.1",
    "md5": "^2.3.0",
    "md5-node": "^1.0.1",
    "moment": "^2.18.1",
    "prop-types": "^15.7.2",
    "qs": "^6.9.4",
    "react": "^16.4.1",
    "react-dom": "^16.4.2",
    "react-intl": "^2.8.0",
    "react-router-dom": "^5.0.0"
  },

**Comment by henanlzt** [comment]
今天跟了下代码，发现是因为配置了懒加载导致
const WrapperPage = lazy(()=>import('@/components/WrapperPage'));
改成
import WrapperPage from '@/components/WrapperPage';

问题消失。

**Comment by imsobear** [comment]
@chenbin92 确认下这个逻辑，懒加载的不支持吗？确定不支持的话文档标注下。

**Comment by chenbin92** [comment]
@henanlzt 用这个示例试下，lazy + wrappers https://github.com/alibaba/ice/blob/master/examples/basic-spa/src/routes.ts#L19
