### ISSUE TITLE
ice 的 electron 版本代码找不到了

### ISSUE THREAD

**Issue by mtrucc** [alibaba/ice#3773]
## 发生了什么?

我看到ice 以前是有 electron 的代码的，我想看一下。
https://github.com/alibaba/ice/projects/9

## 复现步骤，错误日志以及相关配置

> 建议并上传到你的 GitHub 仓库，请使用 `yarn init ice <project-name>` 选择 Lite 模板，这样您的问题我们会更高优先级的进行解决。

在仓库中我找不到electron相关的代码了

## 期望的结果是什么

能够找到electron相关的代码

## 相关环境信息

- **ice.js 版本**：
- **build.json 配置**：
- **Node 版本**：
- **操作系统**：

**Comment by imsobear** [comment]
已停止维护，仅供参考：https://github.com/ice-lab/iceworks-backup/tree/stable/iceworks-2.x/packages
