### ISSUE TITLE
[Bug] Icejs 1.10.0 找不到全局的store 

### ISSUE THREAD

**Issue by myronliu347** [alibaba/ice#3774]
## Any additional comments?

- Icejs 1.10.0

```json
{
  "alias": {
    "@": "./src/",
    "@projectList": "./src/pages/ProjectList/"
  },
  "plugins": [
    "build-plugin-icestark",
    [
      "build-plugin-fusion",
      {
        "themePackage": "@alife/theme-5358"
      }
    ],
    "build-plugin-fusion-unicode",
    [
      "build-plugin-moment-locales",
      {
        "locales": [
          "zh-cn"
        ]
      }
    ],
    "@ali/build-plugin-ice-def"
  ]
}
```
- node 12.14.1
- chrome, all

![image](https://user-images.githubusercontent.com/7897937/98322976-b22a6880-2023-11eb-9f73-9e7abdaf6ad7.png)
![image](https://user-images.githubusercontent.com/7897937/98322983-b9ea0d00-2023-11eb-9693-14fecea98342.png)
![image](https://user-images.githubusercontent.com/7897937/98323015-ca01ec80-2023-11eb-9637-6024a497d107.png)

**Comment by ClarkXia** [comment]
推荐使用 src/store.ts 的方式维护全局 store https://ice.work/docs/guide/basic/store

**Comment by imsobear** [comment]
https://ice.work/docs/guide/basic/store#%E7%89%88%E6%9C%AC%E5%8F%98%E6%9B%B4%E8%AF%B4%E6%98%8E 补充了下文档
