### ISSUE TITLE
icejs&rax-app SSR 方案统一

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#3778]
- 支持有无 app.json 两种路由情况 @ClarkXia 
- 支持 Document & public/index.html 两种主文档模式 @ClarkXia 
- SPA & MPA @luhc228

**Comment by ClarkXia** [comment]
## app.json 支持

icejs 支持 routes 文件和 app.json 两种路由，优先读取 routes 文件。

```json
{
  "routes": [                    
    {
      "path": "/",
      "source": "pages/Home/index"
    },
    {
      "path": "/about",
      "source": "pages/About/index"
    }
  ]
}
```

### SPA

SPA 应用下，app.json 替代 routes 文件作为路由配置文件。

相关能力：
- Layout：默认以 layouts/index 为全局 Layout，路由配置
- lazy：build.json 中配置 `router: { lazy: true }`
- 嵌套路由：SPA 下支持 chidren 配置，如果切换其他模式，默认忽略

### MPA

以 app.json 指定 routes 作为 MPA 入口

### 小程序

目前已支持

## 配置式文档模式

结合 SSR 场景支持配置文档默认，默认启用优先级最低，但是作为推荐方式

新增配置 `htmlInjection`，支持自定义 html 内容包含：

- meta
- title
- link
- style
- script
- htmlAttrs
- headAttrs
- bodyAttrs

配置结构上经历以 `{[htmlTag: string]: {[attribute]: string;}[]}` 的形式，比如：

```json
{
  "htmlInjection": {
    "script": [
      {
        "src": "/index.js",
        "async": true,
      },
      {
        "innerHTML": "console.log()"
      }
    ]
  }
}
```

除了配置属性之外，像 style、script 等增加 `position` 字段标识插入位置。

html 占位内容：

```html
<!doctype html>
<html ${htmlAttrs}>
  <head ${headAttrs}>
    ${meta}
    ${title}
    ${link}
    ${style}
    ${script}
    ${noscript}
  </head>
  <body ${bodyAttrs}>
    <!-- prepended content-->
    ${style}
    ${script}
    ${noscript}

    <!-- html 内容 -->
    ${html}

    <!-- webpack assets 资源，默认注入，需要结合webpack 插件生成 -->
    <script src="/js/index.js"></script>

    <!-- appended content -->
    ${style}
    ${script}
    ${noscript}
  </body>
</html>
```

## SSR 方案统一

1. html 文档模式统一
- icejs 下文档类型支持 index.html 和 配置式文档模式
- rax-app 下文档类型支持 document 和 配置式文档模式

2. 支持 SPA 和 MPA 下的 SSR
- SPA 和 MPA 下均实现 SSR（icejs 目前仅支持 SPA）

**Comment by ClarkXia** [comment]
分别在 #3894 和 #3895 中跟进
