### ISSUE TITLE
取消axios请求的统一处理

### ISSUE THREAD

**Issue by jacktang** [alibaba/ice#3779]
ice对axios简单封装了一层，请问对axios请求有统一处理的方案吗? (或者以后会有吗?)
有遇到相同问题的也想请教下大家的最佳实践是怎样的

**Comment by imsobear** [comment]
https://ice.work/docs/guide/basic/request#%E8%AF%B7%E6%B1%82%E9%85%8D%E7%BD%AE 这个满足你得需求吗？

**Comment by jacktang** [comment]
@imsobear 我指的是AbortController 或者 CancelToken: https://medium.com/datadriveninvestor/aborting-cancelling-requests-with-fetch-or-axios-db2e93825a36

**Comment by imsobear** [comment]
https://github.com/axios/axios#cancellation 直接用这个？

**Comment by jacktang** [comment]
@imsobear 直接用是可以的，那就是每个api都要添加一下。所以问下有没有统一处理的机制 :)

**Comment by imsobear** [comment]
icejs 跟 axios 保持一致，以 axios 能力为准，axios 支持那就支持，不支持的话 icejs 里也不支持。
