### ISSUE TITLE
ice框架配置nextPrefix后，自定义重写next组件样式时，使用变量#{$css-prefix}的方式覆盖，覆盖失败。

### ISSUE THREAD

**Issue by pingguotailang** [alibaba/ice#3782]
ice框架配置nextPrefix后，自定义重写next组件样式时，使用变量#{$css-prefix}的方式覆盖，覆盖失败。

## 复现步骤，错误日志以及相关配置
![image](https://user-images.githubusercontent.com/41989206/98515226-b2399b00-22a5-11eb-8879-c3eb1a50ac2e.png)
![image](https://user-images.githubusercontent.com/41989206/98515278-c9788880-22a5-11eb-8fdc-fabac5118323.png)

> 建议并上传到你的 GitHub 仓库，请使用 `yarn init ice <project-name>` 选择 Lite 模板，这样您的问题我们会更高优先级的进行解决。

## 期望的结果是什么
期望能生成修改后的变量

## 相关环境信息

- **ice.js 版本**：
- **build.json 配置**：
- **Node 版本**：
- **操作系统**：

**Comment by imsobear** [comment]
```diff
{
  "themeConfig": {
-    "nextPrefix": "next-icestark-"
+    "css-prefix": "next-icestark-"
  }
}

```
