### ISSUE TITLE
app.tsx配置全局response处理，onConfig根据业务错误返回Promise.reject，组件中的useRequest返回的error没有值

### ISSUE THREAD

**Issue by futurexiong** [alibaba/ice#3787]
<img width="796" alt="QQ20201109-213511@2x" src="https://user-images.githubusercontent.com/1567478/98547873-c1cfd880-22d3-11eb-90d9-e2b14fcab065.png">
<img width="705" alt="QQ20201109-213638@2x" src="https://user-images.githubusercontent.com/1567478/98547880-c4cac900-22d3-11eb-92b7-9bb3c77751b3.png">
<img width="482" alt="QQ20201109-213659@2x" src="https://user-images.githubusercontent.com/1567478/98547884-c5635f80-22d3-11eb-818a-1da1d163dadb.png">

**Comment by imsobear** [comment]
在 useRequest 下面也就是第九行打印 error 看下

**Comment by imsobear** [comment]
```js
function UserLogin() {
  const { data, error, loading, request } = useRequest(request.login);
  
  useEffect(() => {
    request();
  }, []);

  if (error) {
      // error
  } else if (data.success) {
     // 登录成功
  }

  return <>xxx</>;
}
```
