### ISSUE TITLE
路由配置里有 children 的元素（Layout）则 wrappers 不生效

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#3789]
https://github.com/alibaba/ice/blob/74d0cf4cb527994d3fd94bb379038ddefcdf3896/packages/plugin-router/src/runtime/Router.tsx#L48

感觉这个设计不太合理

**Comment by ClarkXia** [comment]
routeWrappers 除了自定义的 wrappers 之外还有针对一些路由页面相关的处理（比如 pageConfig），所以都是添加在具体路由页面上，带有 children 的 Layout 一般情况下是不需要对应runtime 添加的 wrapper 的

可优化方向：Layout 路由支持 wrappers 属性，但 wrapperRouteComponent 为页面级别添加包裹的内容不生效
