### ISSUE TITLE
如何使用speed-measure-webpack-plugin查看项目构建时间

### ISSUE THREAD

**Issue by lusoftware** [alibaba/ice#3796]
## 发生了什么?
项目构建时间长达40s，想要使用speed-measure-webpack-plugin查看各loader、plugin耗时情况，不知道在飞冰中怎么使用这个plugin
## 相关环境信息

- **ice.js 版本**：ice-scripts 2.1.17
- **build.json 配置**：
- **Node 版本**：10.16.2
- **操作系统**：ubuntu 16.04

**Comment by ClarkXia** [comment]
smp 需要对 webpack 配置整体做一次处理，目前还未提供响应的钩子，后续通过 build-scripts 进行支持

**Comment by lyj1994** [comment]
@ClarkXia 你好，这个有进展了吗？项目打包超过10分钟，急需分析一下
