### ISSUE TITLE
@alifd/next的List只有一条数据的时候显示暂无数据

### ISSUE THREAD

**Issue by rootsli** [alibaba/ice#3799]
## 复现步骤，错误日志以及相关配置

![image](https://user-images.githubusercontent.com/4099803/98770663-b25ca680-241d-11eb-839b-b2a57bcfe448.png)

https://codepen.io/pen/?editors=0010

> 建议并上传到你的 GitHub 仓库，请使用 `yarn init ice <project-name>` 选择 Lite 模板，这样您的问题我们会更高优先级的进行解决。

## 期望的结果是什么
正确显示一条数据

正确显示一条数据

## 相关环境信息

- **ice.js 版本**：
- **build.json 配置**：
- **Node 版本**：
- **操作系统**：

**Comment by luhc228** [comment]
配置 renderItem 属性后可以吗？

**Comment by fangqi5** [comment]
List的源码里有对dataSource长度的判断，判断条件是dataSource.length > 1，可以暂时先在业务中处理
![image](https://user-images.githubusercontent.com/48438816/98791869-a0402f80-2440-11eb-8aa8-43abc1b3ebe5.png)

**Comment by fangqi5** [comment]
源码里判断源数据长度部分：`{!(dSValid && dataSource.length > 1) && !children ? (
                    <div className={`${prefix}list-empty`}>{emptyContent || locale.empty}</div>
                ) : (
                    <ul key="list-body" className={`${prefix}list-items`}>
                        {customContent}
                        {children}
                    </ul>
                )}`
