### ISSUE TITLE
自定义区块/业务组件/模板完成后npm publish

### ISSUE THREAD

**Issue by GracefulTing** [alibaba/ice#3800]
自定义区块开发完成后npm publish，最后是发布到npm的资源管理网站，供每个人可使用吗？还是一个团队内的人共享？如果是供每个人可使用，有办法做到团队内部使用吗？

**Comment by imsobear** [comment]
如果发布到官方 npm 源，就是所有人都可以看到。如果只是希望自己公司内用，建议自己搭私有的 npm 源，具体怎么搭可以谷歌下。

**Comment by GracefulTing** [comment]
Thanks
