### ISSUE TITLE
组件 dist 构建搭配通用插件问题

### ISSUE THREAD

**Issue by ClarkXia** [alibaba/ice#3803]
#### build-plugin-fusion
build-plugin-fusion 插件内置了 next 组件的按需加载，导致构建 dist 配置 externals 是 next 配置复杂，如果开启 externalNext，则导致 demo 页面缺少 next 组件依赖 

> next 按需加载逻辑需要在组件 dist 构建场景下无效

#### build-plugin-load-assets
build-plugin-load-assets 在组件开发下常用于全局依赖/样式的加载，如果构建 dist 会将 load-assets 代码打包进去，产物不可用

> load-assets 代码注入逻辑需要在组件 dist 构建场景下无效

**Comment by zuoqi705** [comment]
而且 build-plugin-load-assets 里面的资源是 async 加载的，导致 external 的依赖不能按正常顺序加载

**Comment by ClarkXia** [comment]
目前已兼容组件 umd 构建场景

> build-plugin-load-assets 使用 0.1.2 + 版本
