### ISSUE TITLE
[Discussion] 关于 lint 配置相关的提议

### ISSUE THREAD

**Issue by SoloJiang** [alibaba/ice#3830]
# 开发规范相关的配置项

## 当前的方案
目前存在两个用户可配的字段进行构建时校验 -- `eslint`/ `tschecker`，分别针对的是普通场景下的规范化提示和 TypeScript 的开发规范提示。
在此基础上，还默认开启提供了 `eslint-reporting-webpack-plugin` 插件进行 `warning` 提示。

### `tschecker` 的生效问题
默认为 `false`，开启的时候目前的校验是否符合预期待确认。

### `eslint-reporting-webpack-plugin` 和 `eslint` 配置的冲突性
目前 `eslint` 为布尔值，并且默认值为 `false`，当用户代码存在不规范写法的时候，前面这个插件会报 `warning` 提示，导致老项目在升级过程中可能会存在大量不友好的日志提示，并且改动可能会影响业务逻辑。当 `eslint` 为 `true` 时，直接报错阻塞构建符合预期。

## 建议

- `tschecker` 确认表现符合预期，如果是鸡肋配置，进行弱化移除
- `eslint` 向下兼容，并且支持通过字符串配置，分别为：`off`/`warning`/`error`，面向用户使用而言，用户只需要感知这个配置即可控制所有构建时关于 `eslint` 相关的表现，`off` 时彻底关闭 `eslint` 提示，`warning` 时不阻塞构建但日志输出，`error` 时阻塞构建并且日志输出，默认值为 `warning`

**Comment by ClarkXia** [comment]
eslint 的执行应该可以覆盖到 tschecker 的能力，目前 tschecker 使用的是 [fork-ts-checker-webpack-plugin
](https://www.npmjs.com/package/fork-ts-checker-webpack-plugin) 插件的能力上相对比较完备，可以调研下是不是可以满足 eslint 的需求

**Comment by fyangstudio** [comment]
eslint 错误提示插件当前默认开启，是增量扫描，第一次会扫描全部eslint指定文件，后续仅扫描用户编辑的文件。
如果一直有大量 eslint 错误被打印，可以说明 用户的 lint 错误应该被修复。

当前打印在控制台中，有几点好处：
* 遵循 eslint 日志格式，用户有连贯和熟悉的体验
* 可点击控制台中的文件地址，打开 VS Code 编辑等
* 覆盖所有平台，小程序 kraken weex 等

feature：
用户手动设置了 eslint: false 应该给予关闭，能让用户有选择的控制。（当然我是倡导用户注意 lint 问题）

## 关于 tschecker

个人倾向关闭，当前 eslint 配置 和 ts 构建默认的类型校验 足以覆盖当前能力
