### ISSUE TITLE
在子应用的路由中配置了众多参数，无法在框架应用或子应用中获取

### ISSUE THREAD

**Issue by baikaishui01** [alibaba/ice#3831]
<img width="418" alt="2D8CD1F0-CE71-4C52-9888-76827E3288E5" src="https://user-images.githubusercontent.com/48601669/99473930-93fb2b80-2986-11eb-940d-57056daedd7d.png">

如图，在zi ying yon子应用路由中配置了一些参数，但是却无法在子应用或者框架应用中获取到这些参数

**Comment by ClarkXia** [comment]
`routerConfig` 的配置作为应用独立渲染的路由信息（name 应该属于无效字段），没太理解框架应用中为什么需要获取这份配置。
如果是为了动态的设置子应用的 `path` 信息，建议还是将子应用配置信息单独维护在框架应用

**Comment by baikaishui01** [comment]
子应用下有众多路由，那么如何实现例如页面的document.title跟随每个路由动态去改变

如图：
      
<img width="343" alt="9B0A781B-56EE-4CC7-A4E3-B4D7B028CDC3" src="https://user-images.githubusercontent.com/48601669/99475623-e853da80-2989-11eb-95f9-acb673f48097.png">
在框架应用中给某个子应用分配了“/demand”路由并配置title为“需求研发”，那么该子应用下所有路由的页面title只会显示“需求研发”，无法根据路由动态改变

**Comment by ClarkXia** [comment]
icestark 会在加载子应用的时候将 document.title 修改成配置的 `title` 信息，如果子应用下属的页面有其他 title 定制需求，可以由子应用自己实现。可以参考 icejs 的页面配置，可以快速应用标题切换能力 https://ice.work/docs/guide/basic/page
