### ISSUE TITLE
Table 组件如何实现点击按钮拖拽排序

### ISSUE THREAD

**Issue by zhangsixue-1992** [alibaba/ice#3832]
Table要实现点击按钮拖拽排序， 想到 react-sortable-hoc 组件，但是结合飞冰Table组件的时候没太弄明白，不知道有没有类似的例子供参考。
![image](https://user-images.githubusercontent.com/68992967/99479858-f1e14080-2991-11eb-888a-5ec962ef606c.png)

**Comment by zhangsixue-1992** [comment]
请问有解么？

**Comment by youluna** [comment]
这个需要调研下，11月月底之前可以给个能不能支持的结论

**Comment by imsobear** [comment]
如还未解决，建议通过 https://fusion.design/feedback 反馈
