### ISSUE TITLE
Pagination 无法选择每页展示条数

### ISSUE THREAD

**Issue by lihuajiede** [alibaba/ice#3836]
1.0 版本的 分页器的 pageSizeSelector 设置后无法正常回显选择的展示条数

**Comment by youluna** [comment]
需要给可复现demo

**Comment by lihuajiede** [comment]
> 需要给可复现demo

demo你直接在飞冰或者 fusion 的分页器组件上看吧，官网上的案例都是不能用的
https://ice.alibaba-inc.com/component/pagination  飞冰官网的案例上你点击下每页显示你看下能不能用吧

**Comment by imsobear** [comment]
@youluna 我看了下，好像的确没找到控制 pageSizeList 选择哪个的属性

**Comment by youluna** [comment]
- 可以通过设置 pageSizeList 属性来指定 「每页显示数量」 可选的值，默认是[5, 10, 20]。
- 可以通过设置 pageSizeSelector 属性来指定是否显示 「每页数量选择」 的部件以及部件形状，默认是false不展示，可以设置为dropdown展开或者平铺到页面上（filter）

![image](https://user-images.githubusercontent.com/10049465/134840308-f56c757e-5ad2-4223-ad25-0d5ed6ea00ec.png)

demo没有问题可以正常用
