### ISSUE TITLE
使用 useRequest 时，多次请求，返回的内容会出现 undefined 

### ISSUE THREAD

**Issue by luhc228** [alibaba/ice#3840]
示例代码如下，当 text 不断更新，log 的 data 会出现 undefined 

```tsx
import React, { useEffect, useState } from 'react';
import { useRequest } from 'teamix';
import { Input, Loading } from 'teamix/ui';
import tableServices from './services';

const Home = () => {
  const { loading, request: getTableData } = useRequest(tableServices.getTableData);
  const [text, setText] = useState<string>('');
  useEffect(() => {
    async function getData() {
      const data = await getTableData();
      // 快速输入时，data会变成 undefined
      console.log('====', data);
    }
    getData()
  }, [text]);

  return (
    <Loading visible={loading} inline={false}>
      <Input value={text} onChange={setText} />
    </Loading>
  );
};

Home.pageConfig = {
  title: '首页',
};

export default Home;
```

```ts
// ./services/index.ts
import { request } from 'teamix';
import { Message } from 'teamix/ui';

export default {
  async getTableData(): Promise<any> {
    const res = await request.get('xxx');
    if (res?.successResponse) {
      Message.success('获取数据成功');
      return res.data;
    }
    Message.error('获取数据失败');
    return [];
  },
};
```

**Comment by purple-force** [comment]
另外，useRequest传入throttleInterval或者debounceInterval，会全部返回null

**Comment by imsobear** [comment]
demo: https://codesandbox.io/s/dreamy-cherry-6x48e?file=/src/App.js

**Comment by ttys026** [comment]
需要加上：
fetchKey: (params) => params['some unique id']

没有 fetchKey 默认是同一个请求，后一个会取消前一个

配上之后, 打印的 await 里的一定有值，render 里的为 undefined 是因为处于 loading

demo：https://codesandbox.io/s/inspiring-meadow-0lj6h?file=/src/App.js

**Comment by brickspert** [comment]
> 另外，useRequest传入throttleInterval或者debounceInterval配置，会全部返回null

throttleInterval 和 debounceInterval 的 run 是不会返回 promise 数据的，你可以用 onSuccess 代替，这个文档上有说明。

不过后面确实可以优化下这个。

**Comment by brickspert** [comment]
> 需要加上：
> fetchKey: (params) => params['some unique id']
> 
> 没有 fetchKey 默认是同一个请求，后一个会取消前一个
> 
> 配上之后, 打印的 await 里的一定有值，render 里的为 undefined 是因为处于 loading
> 
> demo：https://codesandbox.io/s/inspiring-meadow-0lj6h?file=/src/App.js

确实如 @ttys026 所说，useRequest 新请求会取消掉旧请求。

并不是一次发出去 10 个请求，10 个请求都存活。

而是只有最后一个请求存活。所以会出现丢掉响应的情况。

不知道你们具体的需求是什么？可以描述下原始需求吗？我们帮忙看看是否有更好的办法处理。

**Comment by brickspert** [comment]
用 onSuccess 来处理响应结果，就不会出现这个问题啦。

**Comment by purple-force** [comment]
> > 另外，useRequest传入throttleInterval或者debounceInterval配置，会全部返回null
> 
> throttleInterval 和 debounceInterval 的 run 是不会返回 promise 数据的，你可以用 onSuccess 代替，这个文档上有说明。
> 
> 不过后面确实可以优化下这个。

onSuccess 回调方式在如今一通await走天下确实不太合适。这种返回null或者undefined的是否可以返回上一次请求的数据？这样从感官上来说和service的返回逻辑一致。我现在的做法是对await返回值做了次非空判断。

**Comment by brickspert** [comment]
> > > 另外，useRequest传入throttleInterval或者debounceInterval配置，会全部返回null
> > 
> > 
> > throttleInterval 和 debounceInterval 的 run 是不会返回 promise 数据的，你可以用 onSuccess 代替，这个文档上有说明。
> > 不过后面确实可以优化下这个。
> 
> onSuccess 回调方式在如今一通await走天下确实不太合适。这种返回null或者undefined的是否可以返回上一次请求的数据？这样从感官上来说和service的返回逻辑一致。我现在的做法是对await返回值做了次非空判断。

取消上一次请求的机制我这边会统一考虑~

**Comment by Maconzhang** [comment]
@imsobear  3.0 fetchkey 无效, 问题复现 https://codesandbox.io/s/focused-lake-9eq35?file=/src/App.js 选ahook 3.0
