### ISSUE TITLE
useHistory问题

### ISSUE THREAD

**Issue by s4hyhzi** [alibaba/ice#3843]
我导入了useHistory后
const history=useHistory()

history.push("url",{data:111})
跳转到的页面直接console   props
然后里面thislocation.state是undefind
不知道是不是写的不对
ice.js
api文档里面写的不是很清楚

**Comment by ClarkXia** [comment]
可以提供下相关使用的代码

**Comment by imsobear** [comment]
```js
<Button onClick={() => {
  history.push({
    pathname: '/',
    state: {a : 1}
  });
}}>Home</Button>
```
