### ISSUE TITLE
ice框架切换子应用时附加在body外层的模态框dom节点没有被卸载，当使用浏览器后退按钮时，导致UI异常

### ISSUE THREAD

**Issue by rootsli** [alibaba/ice#3845]
Step1.打开一个append到body的模态框
Step2.点击浏览器后退按钮切换到上一个子应用
Step3.前一子应用资源被卸载，但是append到body的模态框dom节点还在，导致UI异常。

## 复现步骤，错误日志以及相关配置

> 建议并上传到你的 GitHub 仓库，请使用 `yarn init ice <project-name>` 选择 Lite 模板，这样您的问题我们会更高优先级的进行解决。

## 期望的结果是什么
切换子应用时，append到body的模态框dom节点被删除

## 相关环境信息

- **ice.js 版本**：
- **build.json 配置**：
- **Node 版本**：
- **操作系统**：

**Comment by ClarkXia** [comment]
对于框架应用的副作用逻辑，建议在 子应用卸载的生命周期里进行处理。
append 到 body 的 dom 结构也是类似，需要在 unmount 组件的生命周期中执行对应的 destroy 操作
