### ISSUE TITLE
安装react-dnd@9.3.4后项目无法运行

### ISSUE THREAD

**Issue by zzwMay** [alibaba/ice#3846]
现在要实现拖拽列表排序，安装了react-dnd和react-dnd-html5-backend，版本都是9.3.4，ice版本为1.10.0，react-dom为16.9.8，然后执行npm start，报错信息：'icejs' 不是内部或外部命令,也不是可运行的程序 或批处理文件。卸载react-dnd后又能正常运行

**Comment by luhc228** [comment]
安装好 react-dnd和 react-dnd-html5-backend 依赖后，重新 npm install。看起来和 icejs 没有关系

**Comment by imsobear** [comment]
@zzwMay 重装下依赖即可，框架跟运行时的包没有耦合的。
