### ISSUE TITLE
希望 updateBindingData  请求数据  支持数组

### ISSUE THREAD

**Issue by yili1992** [alibaba/ice#385]
### 问题描述
我们这后台暴露的服务接口是  JsonRpc的接口 入参格式如下： 其中 params为数组
```js
data: {
      method: 'XXXXX',
      id: '1',
      jsonrpc: '2.0',
      params: [{
        requestData: {
          name: '',
          projectName: '',
        },
        page: {
          currentPage: 1,
          pageSize: 10,
        },
      }],
    },
```
当前  我调用 updateBindingData时候，无法对 params 中的参数 进行修改，直接给params 赋值，却发生了数组的append 操作

### 期望
希望 updateBindingData  请求数据  支持数组，当我给 数组赋值时候 是覆盖 而不是 append

**Comment by yujiangshui** [comment]
你 updateBindingData 是怎么调用的？

**Comment by noyobo** [comment]
https://github.com/alibaba/ice/pull/559

**Comment by noyobo** [comment]
提交复杂格式可以使用  `this.props.updateBindingData('tableData', { params: { params: this.queryCache, }, });`
