### ISSUE TITLE
plugin-react-app 插件的config.js  ignoreHtmlTemplate defaultValue 拼写错误

### ISSUE THREAD

**Issue by Mr-ZhaoRui** [alibaba/ice#3855]
## plugin-react-app 插件的config.js  ignoreHtmlTemplate defaultValue 拼写错误
![image](https://user-images.githubusercontent.com/30251448/100090775-ad244080-2e8e-11eb-8b41-4de84f527775.png)

https://github.com/alibaba/ice/blob/master/packages/plugin-react-app/src/config.js#L22

**Comment by SoloJiang** [comment]
可以 pr 修复一下，预计这周版本修复
