### ISSUE TITLE
dllEntry 生成文件名称能不能自定义

### ISSUE THREAD

**Issue by 790859022** [alibaba/ice#3858]
`
    dllEntry: {
        'vendor' : [
            '@ant-design/icons', 
            'react',
            'react-dom',
            'prop-types',
            'immutable',
            'antd',
        ]
    }
`
![image](https://user-images.githubusercontent.com/19199867/100178650-472bcd80-2f0f-11eb-906e-01cee4644b1f.png)
希望生成的文件名称 跟定义key一致，不需要 _dll_76656e646f72 中的 _dll_和转码

**Comment by ClarkXia** [comment]
dllEntry 方案已废弃，推荐使用 ice.js 2.0 默认提供了预编译的调试能力
