### ISSUE TITLE
[BUG] TypeError: Cannot read property 'location' of undefined

### ISSUE THREAD

**Issue by smileboywtu** [alibaba/ice#386]
``` shell
  28 |   }
  29 | 
  30 |   return _ret = (_temp = (_this = _possibleConstructorReturn(this, _React$Component.call.apply(_React$Component, [this].concat(args))), _this), _this.state = {
> 31 |     match: _this.computeMatch(_this.props.history.location.pathname)
  32 |   }, _temp), _possibleConstructorReturn(_this, _ret);
  33 | }
  34 |
```

https://stackoverflow.com/questions/42892488/react-router-v4-0-0-uncaught-typeerror-cannot-read-property-location-of-unde

I don't know how to fix, is a version general bug?

linux version

**Comment by noyobo** [comment]
https://github.com/alibaba/ice/blob/master/docs/others/migration-to-react-router-v4.md 参考文档升级到 react-router 4
