### ISSUE TITLE
框架代码没法通过 tsChecker

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#3861]
build.json 里开启 `tsChecker: true` 之后的表现，大量 .ice 目录的报错：

![image](https://user-images.githubusercontent.com/2505411/100209466-e1f2cf00-2f44-11eb-88f3-7c2a836a98ac.png)

**Comment by luhc228** [comment]
PR #3910 #3899 调整了 `.ice/index.ts` 文件中模块引入的顺序后，框架代码（`.ice/` 目录）仅剩下 node 相关的代码报错，如下图：

![image](https://user-images.githubusercontent.com/44047106/102078292-a7929880-3e45-11eb-8707-05102d22056a.png)

![image](https://user-images.githubusercontent.com/44047106/102078309-b24d2d80-3e45-11eb-99da-0d12133cd95d.png)

解决办法：
在项目中的 `tsconfig.json` 中增加以下的内容：

```diff
{
  "compilerOptions": {
+   "types": ["node"],  
  }
}
```

**Comment by imsobear** [comment]
那要改下脚手架？

**Comment by luhc228** [comment]
> 那要改下脚手架？

恩。脚手架和 icejs & rax-app 的 examples 统一修改一下

**Comment by luhc228** [comment]
脚手架和框架里的 examples 已改造完成
