### ISSUE TITLE
飞冰table组件不能锁定列

### ISSUE THREAD

**Issue by yanzulee** [alibaba/ice#3864]
table每一列设置了宽度，然后设置了左右两列分别左锁定和右锁定，锁定没用，反而直接把页面撑开了

**Comment by luhc228** [comment]
看下代码怎么写的

**Comment by yanzulee** [comment]
![image](https://user-images.githubusercontent.com/49908097/100350074-4f296180-3024-11eb-8791-b7cddd88dcfa.png)
![image](https://user-images.githubusercontent.com/49908097/100350148-6bc59980-3024-11eb-82c5-5631c9a6c230.png)

**Comment by yanzulee** [comment]
中间的每一个都设置了宽度的，然后效果就是每一个宽度保证了，但是lock没生效，就直接把浏览器撑开出现浏览器的滑动条了

**Comment by a426855a5a5** [comment]
我遇到过这个问题，可以看下tabel 元素的父元素（section 这样的），是否有overflow: “initial” || “revert” || “unset” || ”visible“ 这样的值存在，是会影响锁定列的，可以一级一级看下。

**Comment by yanzulee** [comment]
一级一级的看了，就是包着table的class写一个固定宽度就可以了，但是我又不能写固定宽度 0.0

**Comment by a426855a5a5** [comment]
可以在往上级找找，应该就是影响盒子计算的某些属性导致的。
笨办法：逐级设置overflow: auto; 进行覆盖验证。

**Comment by yanzulee** [comment]
一级一级的找了，只有设置固定宽度，哎，这啥问题啊

**Comment by imsobear** [comment]
https://codesandbox.io/s/kmy7zjr7l3 搞个 demo

**Comment by youluna** [comment]
https://fusion.design/help.html#/faq
![Uploading image.png…]()

**Comment by youluna** [comment]
长时间不回复，先关掉了
