### ISSUE TITLE
官方文档中（路由方案《wrappers 配置》实现路由高阶组件）文档不健全

### ISSUE THREAD

**Issue by wildfire810** [alibaba/ice#3865]
尊敬的开发者，不好意思打扰了，下面这个例子感觉确实有问题的。
https://ice.work/docs/guide/basic/router

首先，需要引入（这个可能需要增补一下）
import React from 'react';

然后安装和配置plugin-ice-auth插件肯定是没问题了
上述两步我都确认实现了

auth.isLogin ? <WrappedComponent {...props} /> : ;
这行代码，最后的分号需要删除，否则报错，然后里面的props变量也找不到。

这个例子不知道该怎么改才能通过。删除了分号和{...props}之后，引入到routes.ts中，会导致崩溃。
Unhandled Rejection (TypeError): Cannot read property 'concat' of undefined

实现高阶组件
```
// src/components/LoginWrapper
import { useAuth, Redirect } from 'ice';

const LoginWrapper = (WrappedComponent) => {
  const Wrapped = () => {
    const [auth] = useAuth();
    return (
      <>
        {
          auth.isLogin ? <WrappedComponent {...props} /> : <Redirect to="/login" />;
        }
      </>
    )
  };

  return Wrapped;
}

export default LoginWrapper;
```

![](https://user-images.githubusercontent.com/17704611/100305903-10bc8400-2fdd-11eb-9a2c-ccef57ed0459.png)
![image](https://user-images.githubusercontent.com/17704611/100306790-2df25200-2fdf-11eb-9c9c-6228d1784da0.png)
```
const routerConfig = [
  {
    path: '/User',
    component: UserLayout,
    children: [
      {
        path: '/Login',
        component: Login,
      }
    ]
  },
  {
    path: '/',
    component: BasicLayout,
    children: [
      {
        path: '/DashBoard',
        // wrappers: [LoginWrapper]
      }
    ],
  },
]
```

核心是只要在routes里面加wrappers: [LoginWrapper]，就会出错

**Comment by wildfire810** [comment]
![image](https://user-images.githubusercontent.com/17704611/100305903-10bc8400-2fdd-11eb-9a2c-ccef57ed0459.png)

**Comment by wildfire810** [comment]
![image](https://user-images.githubusercontent.com/17704611/100306770-203ccc80-2fdf-11eb-9d11-eb74a045b96e.png)

**Comment by ClarkXia** [comment]
感谢反馈，文档我们修复下，可以试下以下代码：

```js
import * as React from 'react';
import { useAuth, Redirect } from 'ice';

const LoginWrapper = (WrappedComponent) => {
  const Wrapped = (props) => {
    const [auth] = useAuth();
    console.log('[auth]', auth);
    return (
      <>
        {
          auth.isLogin ? <WrappedComponent {...props} /> : <Redirect to="/login" />
        }
      </>
    );
  };

  return Wrapped;
};

export default LoginWrapper;
```

**Comment by wildfire810** [comment]
@ClarkXia 谢谢。你们的及时调整。

我这边在进行你给出的修改方案后，还继续有问题。
![image](https://user-images.githubusercontent.com/17704611/100309776-97299380-2fe6-11eb-8ad2-f376f5cc98fa.png)

**Comment by ClarkXia** [comment]
复现代码提供下

**Comment by huhansome** [comment]
阿里云服务器低至96/年，学生价9.5/年
https://www.aliyun.com/minisite/goods?source=5176.11533457&userCode=j6bryttg

阿里云数据库限时折扣，低至188/年
https://www.aliyun.com/activity/ambassador/database?source=5176.11533457&userCode=j6bryttg

阿里云企业级服务器1折限时特惠
https://promotion.aliyun.com/ntms/act/enterprise-discount.html?source=5176.11533457&userCode=j6bryttg

阿里云建站 速成美站 - 千套模板，价格低至500元
https://ac.aliyun.com/application/webdesign/sumei?source=5176.11533457&userCode=j6bryttg

CDN爆款产品低至5.5折
https://yqh.aliyun.com/live/cdncarnival?userCode=j6bryttg&source=5176.11533457&userCode=j6bryttg

**Comment by wildfire810** [comment]
import * as React from 'react';
import { useAuth, Redirect } from 'ice';

const LoginWrapper = (WrappedComponent) => {
    const Wrapped = (props) => {
        const [auth] = useAuth();
        console.log('[auth]', auth);
        return (
            <>
                {
                    auth.isLogin ? <WrappedComponent {...props} /> : <Redirect to="/login" />
                }
            </>
        );
    };

    return Wrapped;
};

export default LoginWrapper;

**Comment by wildfire810** [comment]
```
const routerConfig = [
  {
    path: '/User',
    component: UserLayout,
    children: [
      {
        path: '/Login',
        component: Login,
      }
    ]
  },
  {
    path: '/',
    component: BasicLayout,
    children: [
      {
        path: '/DashBoard',
        wrappers: [LoginWrapper]
      }
    ],
  },
]
```

**Comment by wildfire810** [comment]
就只是这样。
wrappers: [LoginWrapper]
这一行，打开就出错

**Comment by ClarkXia** [comment]
验证了并没有错误，确认下 ice.js 版本，可以重装下依赖。
如果还有问题可以用官方 sample 模版创建一个复现 demo https://github.com/alibaba-fusion/materials/tree/master/scaffolds/scaffold-lite

**Comment by ClarkXia** [comment]
>     children: [
>       {
>         path: '/DashBoard',
>         wrappers: [LoginWrapper]
>       }

需要配置基础的 component

**Comment by wildfire810** [comment]
懂了。你说得对，不能光验证和跳转。

  {
    path: '/',
    component: BasicLayout,
    children: [
      {
        path: '/DashBoard',
        component: Solution,
        wrappers: [LoginWrapper]
      }
    ],
  },
改成这样就可以了。
谢谢，我关闭了
