### ISSUE TITLE
icejs 是否支持编译到小程序

### ISSUE THREAD

**Issue by Mr-ZhaoRui** [alibaba/ice#3870]
## 发生了什么?
https://ice.alibaba-inc.com/docs/miniprogram/start
按此文档操作初始化`npm init ice demo`，无对应miniapp模板可选择

## 期望的结果是什么
如果现在未支持，希望去掉文档入口（目前通过搜索能搜到，如搜索 「miniapp」关键字）

**Comment by imsobear** [comment]
![image](https://user-images.githubusercontent.com/2505411/100819416-1a376780-3487-11eb-81d9-57c6eba5887f.png)

是有的哈，另外这个链路我们近期准备重新设计下。
