### ISSUE TITLE
fusion上传组件是否有分片上传 秒传及断点续传的示例

### ISSUE THREAD

**Issue by rootsli** [alibaba/ice#3879]
## 复现步骤，错误日志以及相关配置

> 建议并上传到你的 GitHub 仓库，请使用 `yarn init ice <project-name>` 选择 Lite 模板，这样您的问题我们会更高优先级的进行解决。

## 期望的结果是什么
如题

能提供分片上传 秒传及断点续传的示例，或方案
## 相关环境信息

- **ice.js 版本**：
- **build.json 配置**：
- **Node 版本**：
- **操作系统**：

**Comment by rootsli** [comment]
因为很多ToB业务涉及到大文件上传，所以都需要用到秒传和断点续传功能。

**Comment by bindoon** [comment]
秒传和断点续传一般需要控件级别的支持，并且需要服务端配合，纯web能力暂时无法做到。
