### ISSUE TITLE
tree组件，选中节点后如何获取包括子节点及所有上级父节点的key

### ISSUE THREAD

**Issue by jitaguizhao** [alibaba/ice#3885]
![image](https://user-images.githubusercontent.com/19563190/100958717-ce082800-3557-11eb-8340-ca414884d9fa.png)

**Comment by bindoon** [comment]
![image](https://user-images.githubusercontent.com/5189853/105677876-64891200-5f27-11eb-9ab1-694a0140e149.png)
api 参数第二个是可以获取 path 路径的，可以拿到当前节点到root的路径
