### ISSUE TITLE
SSR 开启按需加载后服务端 bundle publicPath 错误

### ISSUE THREAD

**Issue by Mr-ZhaoRui** [alibaba/ice#3888]
## 发生了什么?
SSR开启后，使用路由按需加载出错
![image](https://user-images.githubusercontent.com/30251448/100972840-6b715500-3574-11eb-9a0f-e2a2e455376a.png)

## 复现步骤，错误日志以及相关配置

1. `npm init ice ice-demo`
2. 修改build.json配置为`{
  "plugins": [
    "@ali/build-plugin-ice-def"
  ],
  "ssr": true
}`
3. 修改routes.ts为 
`
import { lazy } from 'react';
const routerConfig = [
  {
    path: '/',
    component: lazy(() => import('@/pages/Home'))
  },
];
export default routerConfig;`
3. `npm i`
4. `npm start`

## 相关环境信息

- **ice.js 版本**：
1.11.4
- **build.json 配置**：
`{
  "plugins": [
    "@ali/build-plugin-ice-def"
  ],
  "ssr": true
}`

**Comment by imsobear** [comment]
@luhc228 看下这个问题

**Comment by luhc228** [comment]
SSR 场景下，目前在 SPA 应用没法获取到按需加载页面的 bundle，在服务端渲染时，拿到的是路由对应的组件外层包裹了动态渲染的组件。

**Comment by luhc228** [comment]
ice.js@1.15.0 已发布支持
