### ISSUE TITLE
基于ICE的构建如何在构建时，配置移除console.log

### ISSUE THREAD

**Issue by rootsli** [alibaba/ice#3892]
## 复现步骤，错误日志以及相关配置

> 建议并上传到你的 GitHub 仓库，请使用 `yarn init ice <project-name>` 选择 Lite 模板，这样您的问题我们会更高优先级的进行解决。

## 期望的结果是什么
构建时，移除console.log

## 相关环境信息

- **ice.js 版本**：
- **build.json 配置**：
- **Node 版本**：
- **操作系统**：

**Comment by ClarkXia** [comment]
参考 terser 配置 https://ice.work/docs/guide/basic/build#terserOptions
