### ISSUE TITLE
SSR Server 端调用方式统一

### ISSUE THREAD

**Issue by ClarkXia** [alibaba/ice#3894]
## 背景
目前 icejs 和 rax-app 的 SSR 方案在数据请求，初始的入参以及最终 server 端调用的逻辑并不一致。
期望server 端调用的方式一致，并且对于数据请求时的入参也能够统一

**Comment by luhc228** [comment]
## initialContext

- req(server)

- res(server)

- pathname
- query
- path
- location
- ssrError(client)

## SSR

- getInitialData(ctx)

  icejs 和 rax-app `ctx` 对象对齐，均为 initialContext

- getInitialProps(ctx)

  icejs 和 rax-app `ctx` 对象对齐，均为 initialContext

- 服务端 render()

  icejs 支持的入参：

  ```js
  render({ ctx, pathname, initialData })
  ```

  rax-app 支持的入参：

  ```js
  // 推荐
  render({ ctx, initialData })
  // 兼容旧的用法
  render(req, res)
  ```

- 页面组件 props
  - icejs
    - history
    - location
    - match
    - staticContext
    - searchParams
    - other props...
  - rax-app
    - other props...

## CSR

- 页面组件 props
  - icejs
    - history
    - location
    - match
    - searchParams
    - staticContext
    - other props
  - rax-app
    - history
    - location
    - routes
    - InitialComponent
    - other props
- initialContext
  - icejs
    - pathname
    - query
    - path
    - ssrError
  - rax-app 
    - 缺少 ssrError
