### ISSUE TITLE
Upload.Card 上传组件失败，如何删除显示数量的队列

### ISSUE THREAD

**Issue by zhangsixue-1992** [alibaba/ice#3896]
上传组件失败，如何删除显示数量的队列

**Comment by bindoon** [comment]
没看明白啥意思，至少放个截图吧

**Comment by bindoon** [comment]
https://fusion.design/feedback 

请在这里提问吧

**Comment by bindoon** [comment]
可以自己  onChange 的时候过滤掉失败的组件list，然后再赋值给 value
