### ISSUE TITLE
打包之后图标显示不出来怎么回事？还一直warning：getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead.

### ISSUE THREAD

**Issue by akiko123456** [alibaba/ice#390]
打包之后图标显示不出来怎么回事？还一直warning：getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead.

**Comment by zhangshichun** [comment]
我也遇到了同样的问题。很奇怪，用ice-works就没有这种问题，自己用路径访问时就会出现
