### ISSUE TITLE
fusion组件form表单校验，默认提示信息应该是label而非name

### ISSUE THREAD

**Issue by rootsli** [alibaba/ice#3902]
## 复现步骤，错误日志以及相关配置

https://ice.work/playground/new

> 建议并上传到你的 GitHub 仓库，请使用 `yarn init ice <project-name>` 选择 Lite 模板，这样您的问题我们会更高优先级的进行解决。

## 期望的结果是什么

![image](https://user-images.githubusercontent.com/4099803/101608181-5dbe4280-3a40-11eb-97e6-5b7f7282adb4.png)

正确应该提示：Email （使用from的labe而非input的name）是必填字段
## 相关环境信息

- **ice.js 版本**：
- **build.json 配置**：
- **Node 版本**：
- **操作系统**：

**Comment by bindoon** [comment]
最新版本已经支持 useLabelForErrorMessage

**Comment by rootsli** [comment]
> 最新版本已经支持 useLabelForErrorMessage

文档没搜索到这个关键字，怎么使用呢？

**Comment by bindoon** [comment]
组件不够新吧

**Comment by rootsli** [comment]
> 组件不够新吧

@alifd/next目前使用的是这个版本："version": "1.21.13"，应该是最新的了。

**Comment by rootsli** [comment]
> > 组件不够新吧
> 
> @alifd/next目前使用的是这个版本："version": "1.21.13"，应该是最新的了。

@bindoon 麻烦确认下是否最新版本，ice文档确实没看到useLabelForErrorMessage怎么使用~
