### ISSUE TITLE
field方式校验只有错误提示input边框没有变红

### ISSUE THREAD

**Issue by rootsli** [alibaba/ice#3903]
https://ice.work/playground/new

上面demo点“validate”只有错误提示，input边框没有变成红色

## 复现步骤，错误日志以及相关配置

> 建议并上传到你的 GitHub 仓库，请使用 `yarn init ice <project-name>` 选择 Lite 模板，这样您的问题我们会更高优先级的进行解决。

## 期望的结果是什么
有提示，input边框变红，如下截图：

![image](https://user-images.githubusercontent.com/4099803/101609100-8430ad80-3a41-11eb-8f2f-db3b5bb5ff40.png)

## 相关环境信息

- **ice.js 版本**：
- **build.json 配置**：
- **Node 版本**：
- **操作系统**：

**Comment by imsobear** [comment]
@rootsli https://codesandbox.io/s/kmy7zjr7l3  在这里补个 demo，补完了自己再打开确认下

**Comment by rootsli** [comment]
> @rootsli https://codesandbox.io/s/kmy7zjr7l3 在这里补个 demo，补完了自己再打开确认下

https://codesandbox.io/s/fusion-next-template-forked-3950y

**Comment by rootsli** [comment]
@imsobear

**Comment by bindoon** [comment]
@rootsli 看下 Form 的demo吧，已经把校验错误展示都做好了。

**Comment by rootsli** [comment]
> @rootsli 看下 Form 的demo吧，已经把校验错误展示都做好了。

两种校验方式不同，没有用form，只用field.init定义校验规则的时候，使用field.validator校验错误，是不是也应该支持input边框变红？

**Comment by rootsli** [comment]
@bindoon

**Comment by imsobear** [comment]
红框是 FormItem 提供的能力，因此需要结合 Form 一起使用。

**Comment by rootsli** [comment]
> 红框是 FormItem 提供的能力，因此需要结合 Form 一起使用。

👌
