### ISSUE TITLE
public/index.html ejs 语法应该怎么写

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#3920]
- 可以访问哪些变量
- 基本的文档

**Comment by ClarkXia** [comment]
### SPA 场景

可用变量：
- NODE_ENV： 值为 `development | production` 用来区分 start / build

> SPA 场景下大部分 html 定制需求可以直接修改 html 内容即可，通过环境变量可以针对调试开发过程中渲染额外内容

### MPA 场景

可用变量：
- NODE_ENV （同上）
- pageName 但前渲染页面的页面名称（默认为 src/pages 目录下的一级目录名）

> MPA 场景下通过 `pageName` 参数结合 ejs 语法可以进行 html 差异化渲染。如果差异内容较多，建议通过 MPA template 能力单独指定渲染的 html 模版 

### html 中使用 ejs 语法

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge,chrome=1" />
    <meta name="viewport" content="width=device-width" />
    <title>icejs · spa example</title>
  </head>

  <body>
    <div>current env: <%= NODE_ENV %></div>
<% if (pageName === 'Home') { %>
  <h2>Home page</h2>
<% } %>
    <div id="ice-container"></div>
  </body>
</html>
```

**Comment by daemonchen** [comment]
1、希望能支持自定义模版语法：
```
{
    blockStart: '{{',
    blockEnd: '}}',
  }
```
因为在bff架构里，希望复用这个html入口。
2、希望能够在配置里自定义变量，比如插入一个`user`变量，方便在纯前端开发的时候使用:
```
window.g_config = {
        user: '{{ user | safe }}',
        env: '{{ env }}',
        versions: '{{ versions | safe }}',
      };
```

**Comment by imsobear** [comment]
@daemonchen 怎么用的描述具体点，我感觉你这个有点特殊。

**Comment by ClarkXia** [comment]
@daemonchen 目前模版语法采用 ejs，如果其他类似 hbs 的模版语法可以额外设置
自定义变量注入的方式，可以描述下具体的使用场景 单独开一个 issue 进行讨论
