### ISSUE TITLE
简化 postcss 的插件配置

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#3922]
## What is the current behavior?

- 在 build.json 中关闭 postcssrc
- 新建 postcss.config.js 并写入自己的配置，**此时会丢失框架默认的配置，必须 copy 一下**

## What is the expected behavior?**

https://nuxtjs.org/faq/postcss-plugins

## Any additional comments?

- **ice.js Version**：
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by ClarkXia** [comment]
配置方式

```json
{
  "postcssOptions": {
    "plugins": {
      "postcss-import": false,  // 移除 postcss-import 插件
      "postcss-short": { "prefix": "x" } // 不存在 postcss-short 的情况下添加，存在的情况下修改
    },
    "syntax": "sugarss",
    "parser": "sugarss",
    "stringifier": "sugarss"
  }
}

```
