### ISSUE TITLE
关于飞冰官网显示问题

### ISSUE THREAD

**Issue by J-DuYa** [alibaba/ice#3923]
现在飞冰官网显示，是不是基于gitbook来写的呢？--。--

**Comment by J-DuYa** [comment]
那官网所有的都是手写的吗？还是有什么公用的？[有内部人员想了解 --。--]

**Comment by imsobear** [comment]
文档是手写的，发布时打包成 json 文件推到 oss，站点拉取 oss 然后渲染。

**Comment by J-DuYa** [comment]
那大体知道了，谢啦
