### ISSUE TITLE
icestark：entry方式加载，子应用html存在script脚本时，框架解析脚本错误

### ISSUE THREAD

**Issue by rootsli** [alibaba/ice#3936]
## 发生了什么?
子应用的脚本在框架加载时，被截取掉了

## 复现步骤，错误日志以及相关配置
1.子应用存在如下脚本：
`
<script type="text/javascript">
  document.write('<script type="text/javascript" src="/static/config.js?_t=' + new Date().getTime() + '"><\/script>')
</script>
`
请求参数加入随机值，保证每次加载最新配置。

2.通过icestark加载子应用，实际加载的连接为：
https://host:port/static/config.js?_t
等号及后面的随机参数没掉了

> 建议并上传到你的 GitHub 仓库，请使用 `yarn init ice <project-name>` 选择 Lite 模板，这样您的问题我们会更高优先级的进行解决。

## 期望的结果是什么

请求的随机参数正确

## 相关环境信息

- **ice.js 版本**：
- **build.json 配置**：
- **Node 版本**：
- **操作系统**：

**Comment by maoxiaoke** [comment]
@rootsli 具体的例子吗

**Comment by rootsli** [comment]
@maoxiaoke 直接在html文件的头部加入如下代码段，然后通过框架加载子应用即可。例子不好给啊！
<script type="text/javascript"> 
document.write('<script type="text/javascript" src="/static/config.js?_t=' + new Date().getTime() + '"><\/script>') 
</script>

**Comment by maoxiaoke** [comment]
@rootsli 问题已经定位到，下周发布修复

**Comment by ClarkXia** [comment]
fixed in `@ice/stark@2.1.0`

**Comment by rootsli** [comment]
> fixed in `@ice/stark@2.1.0`

@ClarkXia @ice/stark@1.x有更新么？需要升级到2.x是么？

**Comment by maoxiaoke** [comment]
更新 @ice/stark 到 2.1.0，版本，并根据这个 https://stackoverflow.com/a/18832826 修改改动。更多信息 https://github.com/ice-lab/icestark/releases/tag/v2.1.0
