### ISSUE TITLE
select 不支持无限滚动，但是官方文档上却说有，有bug吗

### ISSUE THREAD

**Issue by wang3852** [alibaba/ice#3942]
https://ice.work/component/select#%E6%97%A0%E9%99%90%E6%BB%9A%E5%8A%A8 滚动到底部并没有继续滚动

**Comment by bindoon** [comment]
我看官网demo正常 item 一直是固定个数，不需修复

![image](https://user-images.githubusercontent.com/5189853/105677734-33a8dd00-5f27-11eb-900b-383964999922.png)
