### ISSUE TITLE
runApp 支持没有路由的情况

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#3945]
- 不要进入约定式路由的逻辑
- url 上不要自动加 # ，跟上面的问题可能有关系
- runApp 需要提供一个渲染组件的地方
- 可能失效的功能需要列举出来，不一定非得兼容，比如 store 的 Provider 需要手动包裹、pageConfig 应该失效了等
- 优先级不高：不引入 history 之类的包，减少体积

**Comment by imsobear** [comment]
临时 hack 的方案，还是走了约定事路由，所以 # 问题没解决：

```jsx
import React from 'react';
import { runApp } from 'ice';
import store from './store';
import Dashboard from './index';

const { Provider } = store;

const appConfig = {
  app: {
    addProvider: ({ children }) => {
      return <Provider><Dashboard>{children}</Dashboard></Provider>;
    },
  },
  icestark: {
    type: 'child',
  },
};
runApp(appConfig);
```

**Comment by ClarkXia** [comment]
## 方案

### build.json 开启方式

目前 build-plugin-ice-router 插件支持路由模式为优先匹配配置式（src/routes.ts），兜底走到约定式，需要提供一个配置项禁用路由能力

```json
{
  "router": false
}
```

设置之后将不会通过 runtime 包裹 react-router，并默认读取 `src/index.(j|t)sx` 作为渲染入口

> build-plugin-ice-router runtime 耦合 ErrorBoundary 能力，期望该部分能力可用

### runApp 逻辑改造

获取 staticConfig（工程配置）禁用 router 能力后，不再执行 createHistory 相关逻辑，以及 router 相关 API 导出均不可用
涉及不再从 ice 中导出的 API 列表：
- withRouter
- history
- getHistory
- getSearchParams

**Comment by SoloJiang** [comment]
从 Rax 无线端的视角来看，`runApp` 支持无路由情况收益应该不太大，原因如下：
1. 路由应该是应用(`runApp` 顾名思义是启动一个应用)的一部分，可以支持只有一个路由且 path 为 '/' 的时候，不引入 history 从而缩小体积
2. 开发者手动调用 `render` 就可以满足轻量模式
3. 目前对于 Rax 而言，`runApp` 接收两个主要参数 `runApp( { app: {}, router: {} } )`，app 里的生命周期其实和路由就是有很大关系的，在没有路由的情况下，例如 `onShow` 其实只需要 `compnentDidMount` 就够了

**Comment by SoloJiang** [comment]
接上面第一条，没有路由的话，`runApp` 和 App 关系就不大了，在无路由场景下，依然需要运行时增益功能的场景还多吗？

**Comment by ClarkXia** [comment]
rax-app 无路由模式相关设计讨论在 https://github.com/raxjs/rax-app/issues/543 跟进
