### ISSUE TITLE
ice自带的useRequest未导出run方法

### ISSUE THREAD

**Issue by whit15** [alibaba/ice#3954]
## What is the current behavior? 发生了什么？

在使用中遇到一个组件中多个useRequest的需求
参照ahooks文档中的写法
`const firstRequest = useRequest(service,{manual: true});`
但是在调用
`firstRequest.run()`
时提示run方法不存在，手动切换到最新版ahook使用正常，应该是ice这边没有导出这个方法，请修复。

## What is the expected behavior? 期望的结果是什么？

firstRequest.run()方法可正常调用。

## Any additional comments? 相关环境信息？

- **ice.js Version**：^1.12.2
- **build.json Configuration**：
`{
  "plugins": [
    [
      "build-plugin-fusion",
      {
        "themePackage": "@alifd/theme-design-pro"
      }
    ],
    [
      "build-plugin-moment-locales",
      {
        "locales": [
          "zh-cn"
        ]
      }
    ],
    "build-plugin-ice-auth"
  ]
}
`
- **Node Version**:v12.18.3
- **Platform**:MacOS 11.1

**Comment by imsobear** [comment]
为了兼容之前的版本，ice 里这个方法叫 request 不叫 run
