### ISSUE TITLE
请问可以提供一个微模块的简易demo吗？

### ISSUE THREAD

**Issue by BigGaoYep** [alibaba/ice#3958]
import React from 'react';
import ReactDOM from 'react-dom';
import App from "./model";
import { MicroModule, registerModules } from '@ice/stark-module';

registerModules([
  {
    // render: () => <App />,
    // name: 'module-demo1',
    name: 'module-demo1',
    url: 'http://localhost:3002/helloApp.js',
    mount: (ModuleComponent, mountNode) => {
      ReactDOM.render(<App />, mountNode);
    },
  },
]);

ReactDOM.render(
  <React.StrictMode>
    <MicroModule moduleName="module-demo1" />
  </React.StrictMode>,
  document.getElementById('root')
);
这个是微模块的单独项目

import { MicroModule, registerModules } from '@ice/stark-module';
import React from 'react'

export default class App extends React.Component {

  componentDidMount() {
    registerModules([
      {
        url: '/api2/helloApp.js',
        name: 'module-demo1',
      }
    ]);
  }

  render() {
    return <MicroModule moduleName="module-demo1" />
  }
}

微模块想挂载在这个页面上  有没有大佬给提供个方案呀  我是做移动端的小白 谢谢各位大佬🙏

**Comment by ClarkXia** [comment]
@maoxiaoke

**Comment by maoxiaoke** [comment]
你可以使用 
```shell
$ iceworks init component @icedesign/template-icestark-module
```

更多内容可参考官方文档 https://ice-lab.github.io/icestark/guide/micro-module
