### ISSUE TITLE
app.jsx 里面能访问全局的store吗?

### ISSUE THREAD

**Issue by jacktang** [alibaba/ice#3966]
# 问题

app.jsx中只有 `createApp(appConfig)` 方法，并且里面有request的配置。如果request存在某些场景，需要将全局的store做数据更新，一般是建议怎么做？

**Comment by whit15** [comment]
是说脱离hooks，在组件外可以使用吗？
```
const a = store.getModelState(model_name);
console.log(a.field);
```

**Comment by jacktang** [comment]
@whit15 谢谢 问题解决了

**Comment by ochive** [comment]
谢谢, 也解决了我的问题😁😁😁
