### ISSUE TITLE
动态切换主题时，只支持颜色切换，不支持边角，高度等样式切换

### ISSUE THREAD

**Issue by robin2017** [alibaba/ice#3967]
ice-script2.x的ice-fusion-plugin插件中，在提取主题变量的时候，只提取了颜色变量，其他变量都去掉，导致只能切换颜色
相关代码如下：ice-fusion-plugin/lib/getThemeVars.js
```
  // 过滤颜色相关内容
  Object.keys(themeVars).forEach((themeKey) => {
    originTheme[themeKey.slice(1)] = themeVars[themeKey];
    const themeValue = themeVars[themeKey];
    if (themeValue && (themeValue.indexOf('#') !== 0 || ['$color-white', '$color-black'].indexOf(themeKey) > -1)) {
      delete themeVars[themeKey];
    }
  });
```

**Comment by robin2017** [comment]
icejs的build-plugin-fusion插件也存在这个问题

**Comment by ClarkXia** [comment]
依赖 next 组件中非颜色参数会基于 sass 能力进行复杂计算，而这部分能力 css variable 的方案无法完全覆盖。
目前 next 组件已内置 css variable 变量，后续考虑支持一种模式移除对 sass 样式的依赖

relate to #3526

**Comment by ClarkXia** [comment]
目前 fusion 站点主题支持生成 css variables 样式文件，结合 build-plugin-fusion 方案，可以支持除颜色之外的样式切换，参考[使用 css variables 样式](https://github.com/alibaba/ice/blob/acc681f06abd0330cd0af503bf285a0b627d3c3f/docs/guide/advance/fusion.md#%E4%BD%BF%E7%94%A8-css-variables-%E6%A0%B7%E5%BC%8F)
