### ISSUE TITLE
设置多主题情况下，除了window.__changeTheme__可以更改主题，有没有根据条件在初始化时选择主题的方法？

### ISSUE THREAD

**Issue by newsmallyu** [alibaba/ice#3968]

**Comment by ClarkXia** [comment]
目前只能通过 `window.__changeTheme__` 去修改，看下具体什么场景下需要

**Comment by rootsli** [comment]
@ClarkXia 例如基于微框架集成应用，主题切换到了主题A，但切换子应用时，子应用初始化都会默认运行一遍changeTheme('主题B')，如果业务代码再手动运行changeTheme('主题A')会出现主题闪现切换效果。

**Comment by rootsli** [comment]
@ClarkXia 例如基于微框架集成应用，主题切换到了主题A，但切换子应用时，子应用初始化都会默认运行一遍changeTheme('主题B')，如果业务代码再手动运行changeTheme('主题A')会出现主题闪现切换效果。
