### ISSUE TITLE
icejs不可以配置缓存路由吗？

### ISSUE THREAD

**Issue by xqt888** [alibaba/ice#3969]
icejs不可以配置缓存路由吗？react-router-cache-route

**Comment by ClarkXia** [comment]
默认没有使用 react-router-cache-route，你是想知道配合 react-router-cache-route 的使用方式？

**Comment by xqt888** [comment]
> 默认没有使用 react-router-cache-route，你是想知道配合 react-router-cache-route 的使用方式？

是的，怎么配合使用react-router-cache-route啊

**Comment by ClarkXia** [comment]
参见 [build-plugin-keep-alive 用法](https://ice.work/docs/guide/develop/plugin-list#plugin-keep-alive)

**Comment by wh1teYu** [comment]
@ClarkXia  开启了ice的keep-alive ，但是路由切换，再回退后，滚动位置会回到顶部。

**Comment by wh1teYu** [comment]
版本是ice2
