### ISSUE TITLE
Vue项目的doctor检测只有1个文件

### ISSUE THREAD

**Issue by MHcute** [alibaba/ice#3972]
![image](https://user-images.githubusercontent.com/29968512/103200327-fea96a80-4927-11eb-9478-31baf855804b.png)

**Comment by fyangstudio** [comment]
能提供下 示例项目吗

**Comment by MHcute** [comment]
> 能提供下 示例项目吗

直接用的公司的项目，稍后我试试创建一个Demo会不会有问题

**Comment by fyangstudio** [comment]
这个问题 应该确实存在。 没有检查 .vue 的文件。  这个我尽快修复

**Comment by fyangstudio** [comment]
https://github.com/ice-lab/iceworks/pull/715

**Comment by fyangstudio** [comment]
使用 Doctor v 0.2.2 版本
