### ISSUE TITLE
icejs可以使用webpack的chunks打包文件吗

### ISSUE THREAD

**Issue by xqt888** [alibaba/ice#3973]
icejs可以使用webpack的chunks打包文件吗？怎么使用

**Comment by ClarkXia** [comment]
使用 lazy 或者 dynamic import 默认会生成 chunks
你的需求场景是什么样的

**Comment by xqt888** [comment]
> 使用 lazy 或者 dynamic import 默认会生成 chunks
> 你的需求场景是什么样的

我想node_modules包也chunks打包

**Comment by ClarkXia** [comment]
具体分包策略参考 webpack 配置即可，在 icejs 下可以参考[自定义工程配置](https://ice.work/docs/guide/develop/plugin-build#onGetWebpackConfig) 和 [webpack-chain 文档](https://github.com/neutrinojs/webpack-chain#configuring-optimizations-shorthand-methods) 进行配置
