### ISSUE TITLE
ice 中引用文件的 mock 方式，不支持 number  数据类型

### ISSUE THREAD

**Issue by SevenHDU** [alibaba/ice#3978]
以引用 mock 文件的方式，若 mock 文件带 number 数据类型，则启动会报错
复现步骤如下
1.  在 mock 文件夹下创建一个 mock 文件 /get/hello/index.js
![1](https://user-images.githubusercontent.com/2370446/103264982-62df3380-49e7-11eb-869d-d956e39dffbc.png)

2. 在 mock/index.js 引入该 /get/hello/index.js mock 文件
![2](https://user-images.githubusercontent.com/2370446/103264990-696dab00-49e7-11eb-8dc1-dd3d95e1f5a9.png)

3. 启动，查看控制台信息
![3](https://user-images.githubusercontent.com/2370446/103264998-6ffc2280-49e7-11eb-814c-3992947199a1.png)

通过源码排查到 **webpack-dev-mock** 插件对 mock 数据有类型限制。
源码详情查看 https://github.com/ice-lab/ice-scripts/blob/master/packages/webpack-dev-mock/index.js#L94

疑问点：
1. **为什么有数据类型限制，是处于什么考虑?**
2. **能否支持 number 数据类型吗?**

**Comment by ClarkXia** [comment]
目前的 mock 功能是将 mock 目录下所有的单文件导出都作为 mock 数据的规则，即每个文件导出都应该符合：

```js
module.exports = {
  "/api/test": mockData
}
```

上述 `/get/hello/index.js` 的导出直接作为一个 mock 文件是不符合规范的

> 推荐每个文件管理导出各自相关的 API 的 mock 数据，不需要在入口文件中导入再导出

**Comment by ClarkXia** [comment]
数据类型限制，是从一个接口 api 返回数据格式的维度考虑的，设计上参考上一条回复
如果有更好的设计想法 欢迎 pr
