### ISSUE TITLE
Select组件文档预览错误

### ISSUE THREAD

**Issue by sxcooler** [alibaba/ice#398]
https://alibaba.github.io/ice/component/select 这个页面，从“多选受控”往下的几个combobox的例子，点击都没有反应。
Mac，OSX 10.13.4，Chrome 65.0.3325.181

**Comment by yujiangshui** [comment]
应该的应该的。

**Comment by wssgcg1213** [comment]
sorry, forget to handle. 
修复完成, 会在明天进行发布
