### ISSUE TITLE
You should not use <Route> or withRouter() outside a <Router>

### ISSUE THREAD

**Issue by huifeidepaozi** [alibaba/ice#3980]
![image](https://user-images.githubusercontent.com/58034748/103277942-2e7a7000-4a05-11eb-9f24-03bbfaa48f6e.png)
![image](https://user-images.githubusercontent.com/58034748/103277952-376b4180-4a05-11eb-9a56-dd46ff402edc.png)

**Comment by huifeidepaozi** [comment]
![lALPD2sQt8bNf_LNA8_NBRA_1296_975](https://user-images.githubusercontent.com/58034748/103278040-77cabf80-4a05-11eb-83a8-158829569e97.png)
![lALPD26eNmuPhRfNAvPNA-c_999_755](https://user-images.githubusercontent.com/58034748/103278044-7c8f7380-4a05-11eb-8566-0716d10f7064.png)

**Comment by luhc228** [comment]
哪里用到了 `withRouter()` or `<Route>`，想要实现什么功能?

**Comment by imsobear** [comment]
https://github.com/alibaba/ice/blob/docs-fusion/docs/icestark/guide/framework-app.md#%E4%B8%BB%E5%BA%94%E7%94%A8%E4%B8%AD%E8%B7%AF%E7%94%B1%E8%B7%B3%E8%BD%AC @huifeidepaozi 看下是不是这个问题

**Comment by imsobear** [comment]
长时间未回复，先关掉了，有问题再 reopen。
