### ISSUE TITLE
build.json配置，polyfill值改成usage，启动项目报错

### ISSUE THREAD

**Issue by rootsli** [alibaba/ice#3985]
polyfill:"usage",重新安装依赖包，运行npm start("start": "icejs start --mode local --https")启动项目，报如下错误：

`
 ERROR  Failed to compile with 4551 errors                                                                                                                                                      9:45:28 AM

These dependencies were not found:

* core-js/modules/es.array-buffer.constructor.js in ./node_modules/axios/lib/utils.js, ./node_modules/lodash.clonedeep/index.js and 3 others
* core-js/modules/es.array.concat.js in ./.ice/ErrorBoundary/ErrorBoundaryFallback.tsx, ./node_modules/@ahooksjs/use-request/es/index.js and 169 others
* core-js/modules/es.array.every.js in ./node_modules/@alifd/next/es/cascader/cascader.js, ./node_modules/@alifd/next/es/cascader/utils.js and 8 others
* core-js/modules/es.array.fill.js in ./node_modules/echarts/lib/chart/custom.js, ./node_modules/echarts/lib/chart/bar/BarView.js and 28 others
* core-js/modules/es.array.filter.js in ./node_modules/@alifd/field/lib/index.js, ./node_modules/@alifd/next/es/cascader/cascader.js and 87 others
* core-js/modules/es.array.find-index.js in ./node_modules/@alifd/next/es/calendar/head/menu.js, ./node_modules/@alifd/next/es/cascader/menu.js and 1 other
* core-js/modules/es.array.find.js in ./node_modules/@alifd/next/es/menu/view/util.js, ./node_modules/@alifd/next/es/select/auto-complete.js and 17 others
* core-js/modules/es.array.for-each.js in ./node_modules/@ahooksjs/use-request/es/useLoadMore.js, ./node_modules/@ahooksjs/use-request/es/useAsync.js and 145 others
* core-js/modules/es.array.from.js in ./.ice/auth/index.tsx, ./node_modules/@babel/runtime/helpers/unsupportedIterableToArray.js and 79 others
* core-js/modules/es.array.includes.js in ./node_modules/@alifd/next/es/balloon/balloon.js, ./node_modules/@alifd/next/es/overlay/popup.js and 12 others
* core-js/modules/es.array.index-of.js in ./node_modules/@ahooksjs/use-request/es/index.js, ./node_modules/@ahooksjs/use-request/es/useLoadMore.js and 182 others
* core-js/modules/es.array.iterator.js in ./.ice/ErrorBoundary/index.tsx, ./.ice/auth/index.tsx and 194 others
* core-js/modules/es.array.join.js in ./node_modules/@alifd/next/es/balloon/balloon.js, ./node_modules/@alifd/next/es/cascader/cascader.js and 71 others
* core-js/modules/es.array.last-index-of.js in ./node_modules/echarts/lib/echarts.js, ./node_modules/echarts/lib/chart/bar/PictorialBarView.js and 5 others
* core-js/modules/es.array.map.js in ./node_modules/@alifd/field/lib/index.js, ./node_modules/@alifd/field/lib/utils.js and 210 others
* core-js/modules/es.array.reduce.js in ./node_modules/@alifd/next/es/cascader/cascader.js, ./node_modules/@alifd/next/es/cascader-select/cascader-select.js and 28 others
* core-js/modules/es.array.slice.js in ./.ice/auth/index.tsx, ./node_modules/@ahooksjs/use-request/es/useLoadMore.js and 218 others
* core-js/modules/es.array.some.js in ./node_modules/@alifd/next/es/cascader/cascader.js, ./node_modules/@alifd/next/es/cascader-select/cascader-select.js and 12 others
* core-js/modules/es.array.sort.js in ./node_modules/@alifd/field/lib/index.js, ./node_modules/@alifd/next/es/cascader/cascader.js and 26 others
* core-js/modules/es.array.splice.js in ./node_modules/@ahooksjs/use-request/es/utils/windowFocus.js, ./node_modules/@ahooksjs/use-request/es/utils/windowVisible.js and 60 others
* core-js/modules/es.function.name.js in ./.ice/auth/index.tsx, ./node_modules/@alifd/next/es/checkbox/checkbox.js and 211 others
* core-js/modules/es.json.to-string-tag.js in ./node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js, ./node_modules/react-dom/cjs/react-dom.development.js and 3 others
* core-js/modules/es.map.js in ./node_modules/@ahooksjs/use-request/es/utils/cache.js, ./node_modules/@alifd/next/es/config-provider/cache.js and 5 others
* core-js/modules/es.math.sign.js in ./node_modules/react-error-overlay/lib/index.js
* core-js/modules/es.math.to-string-tag.js in ./node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js, ./node_modules/react-dom/cjs/react-dom.development.js and 3 others
* core-js/modules/es.number.constructor.js in ./node_modules/@alifd/field/lib/index.js, ./node_modules/@alifd/next/es/calendar/head/menu.js and 31 others
* core-js/modules/es.number.is-nan.js in ./node_modules/events/events.js, ./node_modules/query-string/index.js
* core-js/modules/es.number.max-safe-integer.js in ./node_modules/@alifd/next/es/number-picker/number-picker.js
* core-js/modules/es.number.min-safe-integer.js in ./node_modules/@alifd/next/es/number-picker/number-picker.js
* core-js/modules/es.number.to-fixed.js in ./node_modules/@alifd/next/es/dialog/dialog.js, ./node_modules/@alifd/next/es/menu/view/util.js and 19 others
* core-js/modules/es.object.assign.js in ./.ice/config.ts, ./.ice/genWithSearchParams.ts and 57 others
* core-js/modules/es.object.entries.js in ./src/services/bidcore.js
* core-js/modules/es.object.freeze.js in ./node_modules/@ice/store/node_modules/immer/dist/immer.esm.js, ./node_modules/react-dom/cjs/react-dom.development.js and 1 other
* core-js/modules/es.object.get-own-property-descriptor.js in ./node_modules/@alifd/validate/lib/index.js, ./node_modules/@babel/runtime/helpers/interopRequireWildcard.js and 37 others
* core-js/modules/es.object.get-own-property-descriptors.js in ./node_modules/@alifd/validate/lib/index.js, ./node_modules/redux/es/redux.js and 25 others
* core-js/modules/es.object.get-own-property-names.js in ./node_modules/@ice/sandbox/lib/index.js, ./node_modules/@ice/store/node_modules/immer/dist/immer.esm.js and 7 others
* core-js/modules/es.object.get-prototype-of.js in ./.ice/ErrorBoundary/index.tsx, ./node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js and 16 others
* core-js/modules/es.object.is-frozen.js in ./node_modules/@ice/store/node_modules/immer/dist/immer.esm.js, ./node_modules/moment/moment.js
* core-js/modules/es.object.is.js in ./node_modules/react-dom/cjs/react-dom.development.js
* core-js/modules/es.object.keys.js in ./node_modules/@ahooksjs/use-request/es/useAsync.js, ./node_modules/@alifd/field/lib/index.js and 137 others
* core-js/modules/es.object.prevent-extensions.js in ./node_modules/react-dom/cjs/react-dom.development.js
* core-js/modules/es.object.seal.js in ./node_modules/react-dom/cjs/react-dom.development.js, ./node_modules/react/cjs/react.development.js
* core-js/modules/es.object.to-string.js in ./.ice/ErrorBoundary/index.tsx, ./.ice/ErrorBoundary/ErrorBoundaryFallback.tsx and 238 others
* core-js/modules/es.object.values.js in ./node_modules/@ahooksjs/use-request/es/useLoadMore.js, ./node_modules/@ahooksjs/use-request/es/useAsync.js and 3 others
* core-js/modules/es.promise.finally.js in ./node_modules/@ahooksjs/use-request/es/useAsync.js, ./src/pages/Procurer/PurchaseOrderDetail/index.jsx and 1 other
* core-js/modules/es.promise.js in ./node_modules/@ahooksjs/use-request/es/index.js, ./node_modules/@ahooksjs/use-request/es/useAsync.js and 36 others
* core-js/modules/es.reflect.apply.js in ./node_modules/events/events.js
* core-js/modules/es.reflect.construct.js in ./.ice/ErrorBoundary/index.tsx, ./node_modules/react-countdown/dist/index.es.js and 3 others
* core-js/modules/es.reflect.get-own-property-descriptor.js in ./node_modules/@ice/store/node_modules/immer/dist/immer.esm.js
* core-js/modules/es.reflect.own-keys.js in ./node_modules/@ice/store/node_modules/immer/dist/immer.esm.js, ./node_modules/events/events.js
* core-js/modules/es.regexp.constructor.js in ./node_modules/@alifd/field/lib/index.js, ./node_modules/@alifd/next/es/cascader-select/cascader-select.js and 25 others
* core-js/modules/es.regexp.exec.js in ./node_modules/@alifd/field/lib/index.js, ./node_modules/@alifd/field/lib/utils.js and 171 others
* core-js/modules/es.regexp.flags.js in ./node_modules/react-fast-compare/index.js
* core-js/modules/es.regexp.to-string.js in ./.ice/ErrorBoundary/index.tsx, ./.ice/ErrorBoundary/ErrorBoundaryFallback.tsx and 150 others
* core-js/modules/es.set.js in ./node_modules/@alifd/next/es/icon/icon-font.js, ./node_modules/@ice/store/node_modules/immer/dist/immer.esm.js and 6 others
* core-js/modules/es.string.bold.js in ./src/pages/FoundProject/Components/CardItem/index.jsx
* core-js/modules/es.string.code-point-at.js in ./node_modules/html-entities/lib/surrogate-pairs.js
* core-js/modules/es.string.ends-with.js in ./node_modules/create-use-router/node_modules/path-to-regexp/dist.es2015/index.js
* core-js/modules/es.string.fixed.js in ./node_modules/@alifd/next/es/grid/row.js, ./node_modules/@alifd/next/es/table/index.js and 2 others
* core-js/modules/es.string.from-code-point.js in ./node_modules/html-entities/lib/surrogate-pairs.js
* core-js/modules/es.string.includes.js in ./node_modules/@alifd/next/es/overlay/popup.js, ./node_modules/@alifd/next/es/tree/view/tree.js and 9 others
* core-js/modules/es.string.iterator.js in ./.ice/ErrorBoundary/index.tsx, ./.ice/auth/index.tsx and 176 others
* core-js/modules/es.string.link.js in ./node_modules/@alifd/next/es/pagination/pagination.js, ./node_modules/echarts/lib/component/axisPointer.js
* core-js/modules/es.string.match.js in ./node_modules/@alifd/field/lib/index.js, ./node_modules/@alifd/next/es/cascader-select/cascader-select.js and 40 others
* core-js/modules/es.string.repeat.js in ./node_modules/create-use-router/lib/index.js, ./node_modules/path-to-regexp/index.js and 1 other
* core-js/modules/es.string.replace.js in ./node_modules/@alifd/field/lib/index.js, ./node_modules/@alifd/field/lib/utils.js and 88 others
* core-js/modules/es.string.search.js in ./node_modules/@alifd/next/es/search/Search.js, ./node_modules/axios/lib/helpers/isURLSameOrigin.js and 32 others
* core-js/modules/es.string.split.js in ./node_modules/@alifd/field/lib/utils.js, ./node_modules/@alifd/next/es/badge/sup.js and 62 others
* core-js/modules/es.string.sub.js in ./node_modules/echarts/lib/echarts.js, ./node_modules/echarts/lib/chart/graph/forceHelper.js and 6 others
* core-js/modules/es.string.trim-start.js in ./node_modules/url-parse/index.js
* core-js/modules/es.string.trim.js in ./node_modules/@alifd/next/es/input/base.js, ./node_modules/@alifd/next/es/number-picker/number-picker.js and 14 others
* core-js/modules/es.symbol.async-iterator.js in ./node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js, ./node_modules/react-error-overlay/lib/index.js and 3 others
* core-js/modules/es.symbol.description.js in ./.ice/ErrorBoundary/index.tsx, ./.ice/auth/index.tsx and 171 others
* core-js/modules/es.symbol.iterator.js in ./.ice/ErrorBoundary/index.tsx, ./.ice/auth/index.tsx and 166 others
* core-js/modules/es.symbol.js in ./.ice/ErrorBoundary/index.tsx, ./.ice/auth/index.tsx and 197 others
* core-js/modules/es.symbol.to-string-tag.js in ./node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js, ./node_modules/react-dom/cjs/react-dom.development.js and 3 others
* core-js/modules/es.symbol.unscopables.js in ./node_modules/@ice/sandbox/lib/index.js
* core-js/modules/es.typed-array.copy-within.js in ./node_modules/echarts/lib/chart/candlestick/candlestickLayout.js, ./node_modules/echarts/lib/chart/heatmap/HeatmapLayer.js and 13 others
* core-js/modules/es.typed-array.every.js in ./node_modules/echarts/lib/chart/candlestick/candlestickLayout.js, ./node_modules/echarts/lib/chart/heatmap/HeatmapLayer.js and 13 others
* core-js/modules/es.typed-array.fill.js in ./node_modules/echarts/lib/chart/candlestick/candlestickLayout.js, ./node_modules/echarts/lib/chart/heatmap/HeatmapLayer.js and 13 others
* core-js/modules/es.typed-array.filter.js in ./node_modules/echarts/lib/chart/candlestick/candlestickLayout.js, ./node_modules/echarts/lib/chart/heatmap/HeatmapLayer.js and 13 others
* core-js/modules/es.typed-array.find-index.js in ./node_modules/echarts/lib/chart/candlestick/candlestickLayout.js, ./node_modules/echarts/lib/chart/heatmap/HeatmapLayer.js and 13 others
* core-js/modules/es.typed-array.find.js in ./node_modules/echarts/lib/chart/candlestick/candlestickLayout.js, ./node_modules/echarts/lib/chart/heatmap/HeatmapLayer.js and 13 others
* core-js/modules/es.typed-array.float32-array.js in ./node_modules/echarts/lib/chart/candlestick/candlestickLayout.js, ./node_modules/echarts/lib/chart/helper/LargeSymbolDraw.js and 7 others
* core-js/modules/es.typed-array.float64-array.js in ./node_modules/echarts/lib/chart/lines/LinesSeries.js, ./node_modules/echarts/lib/data/List.js
* core-js/modules/es.typed-array.for-each.js in ./node_modules/echarts/lib/chart/candlestick/candlestickLayout.js, ./node_modules/echarts/lib/chart/heatmap/HeatmapLayer.js and 13 others
`

**Comment by ClarkXia** [comment]
通过配置 [fusion-design-pro](https://github.com/alibaba-fusion/materials/tree/master/scaffolds/fusion-design-pro) 项目未复现，可以提供下简单的 demo

**Comment by rootsli** [comment]
> 通过配置 [fusion-design-pro](https://github.com/alibaba-fusion/materials/tree/master/scaffolds/fusion-design-pro) 项目未复现，可以提供下简单的 demo
> 表现上有点像 core-js 2.x 版本依赖被提升到顶层，可以尝试在项目 dependencies 中依赖 core-js 3.x 版本

确实项目里core-js有依赖2.x也有3.x的。我试试改3.x

**Comment by rootsli** [comment]
@ClarkXia 错误本身是由于css语法引起：
-@ ==>这里换行了
--webkit-keyframes progress-bar-stripes {
+@-webkit-keyframes progress-bar-stripes { ==>修改成这样，构建就过了
 	from {background-position: 40px 0
 }


但是，构建的时候public内容会提示语法错误，有点奇怪。
