### ISSUE TITLE
CSS 网络资源本地化 请求路径问题

### ISSUE THREAD

**Issue by roginluo** [alibaba/ice#3986]
我们使用了`build-plugin-fusion`插件将css资源本地化配置文件如下：
```json
{
  "plugins": [

    [
      "build-plugin-moment-locales",
      {
        "locales": [
          "zh-cn"
        ]
      }
    ],
    [
      "build-plugin-fusion", {
      "themeConfig": {
        "icon-font-path": "'/icon-font/icon'",
        "font-custom-path": "'/font/'"
      }
    }
  ]
  ],
  "modeConfig": {
    "local": {
      "define": {},
      "vendor": false
    },
    "pro": {
      "define": {},
      "vendor": true
    }
  },
  "publicPath": "./",
  "outputDir": "dist",
  "minify": false,
  "proxy": {
	  "/phbip_application_data": {
      "enable": true,
      "target": "http://127.0.0.1:6001"
    }
  }
}
```

但是在请求资源时访问站点：http://localhost:63343/dataApplication/dist/index.html
页面却是去请求：http://localhost:63343/icon-font/icon.woff2
正常应该请求：http://localhost:63343/dataApplication/dist/icon-font/icon.woff2才对啊
请解答

**Comment by ClarkXia** [comment]
首先明确业务场景：参考 https://ice.work/docs/guide/advance/assets-local

上述表现上是符合预期的，icon-font-path 设置为  /icon-font/icon 的情况下，将 icon 资源添加在 public 目录下，网络请求时是  window.location.origin + 该路径
建议 /icon-font/ 下相关资源部署在根目录，或者在配置 icon-font-path 的时候直接以 cdn 地址规则进行配置（提前将 icon 资源部署到可访问 cdn）

> 如果以相对路径配置，需要将 icon-font 相关资源以相对  node_modules 下 @alifd/next 的位置存放，可操作性较差
