### ISSUE TITLE
ice框架build时，public文件夹的css也会被构建，导致报错

### ISSUE THREAD

**Issue by rootsli** [alibaba/ice#3989]
报错信息如下：（期望：忽略public下的文件）
`
> icejs build --mode dev
ice.js 1.12.0
info 离线化构建项目，自动下载网络资源，请耐心等待 
info 使用 Fusion 组件主题包： @alifd/theme-design-pro
info 自定义 Fusion 组件主题变量： { nextPrefix: 'next-icestark-' }
                                         95% emitting(node:10088) UnhandledPromiseRejectionWarning: CssSyntaxError: /Users/lichbin/Desktop/bss-project/web-gpx-ice-framework/pdfjs2/UiWeb/css/bootstrap-3.3.7-dist/css/bootstrap.min.css:5558:1: At-rule without name
(node:10088) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:10088) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
lichbin@roots web-gpx-ice-framework % 

`

**Comment by rootsli** [comment]
错误源码位置如下：

![image](https://user-images.githubusercontent.com/4099803/103517249-cd431880-4eac-11eb-8345-e3b58421a144.png)

**Comment by rootsli** [comment]
错误文件在项目中的位置：

![image](https://user-images.githubusercontent.com/4099803/103518536-e351d880-4eae-11eb-8f39-0d40462dd4ec.png)

**Comment by ClarkXia** [comment]
是不是引用了 css 文件，合理的方式是在 index.html 通过 link 标签的形式加入

**Comment by rootsli** [comment]
> 是不是引用了 css 文件，合理的方式是在 index.html 通过 link 标签的形式加入

这里只是静态内容，src内没有任何引用。相当于cdn了

**Comment by rootsli** [comment]
> 是不是引用了 css 文件，合理的方式是在 index.html 通过 link 标签的形式加入

构建应该是先执行的编译，最后才拷贝吧？

**Comment by rootsli** [comment]
> > 是不是引用了 css 文件，合理的方式是在 index.html 通过 link 标签的形式加入
> 
> 构建应该是先执行的编译，最后才拷贝吧？

build.json有配置：  "compileDependencies": [""],
按道理不会去编译public内容啊

**Comment by ClarkXia** [comment]
提供下有问题的 demo，没被源码引入的内容不会进行编译

**Comment by ClarkXia** [comment]
public 目录下未被引用源码不会进行编译，如确定问题，提供下 demo 并重开 issue
