### ISSUE TITLE
.webpackrc.js 可以区分开发和生产环境吗？

### ISSUE THREAD

**Issue by flylee2011** [alibaba/ice#399]
RT，webpack自定义配置文件 支持分开发和生产2份配置文件吗？

**Comment by yujiangshui** [comment]
@noyobo 关注下

**Comment by flylee2011** [comment]
@noyobo  ，比如我想开发的时候走一个配置文件，正式打包的时候走一个配置文件，而不是全都走一个 .webpackrc.js 文件。

**Comment by noyobo** [comment]
```js
if (process.env.NODE_ENV === 'production') {
  module.exports = require('./webpackrc.prod.js')
} else {
  module.exports = require('./webpackrc.dev.js')
}
```

@flylee2011  这样可以么？

**Comment by flylee2011** [comment]
@noyobo  可以的。现在就是这么搞的，谢谢

**Comment by HaveF** [comment]
@noyobo 麻烦问下, 如果我想在dev的时候, 使用一个restful api路径, 在production时使用另外一个路径, 应该怎么做? 看上去好像是使用NODE_ENV? 

package.json:
```
    "build": "cross-env NODE_ENV=dev && ice build",
```

代码中用:
```
if(process.ENV.NODE_ENV === 'env'){
...
}
```

这样吗?

**Comment by noyobo** [comment]
@HaveFm  可以，但是  NODE_ENV 不能修改的。 dev 下是 development，  build 时是  production。

**Comment by HaveF** [comment]
谢谢, 看了下, 似乎还挺麻烦的

生产和开发, env这种事情, 似乎内置到ice的整体逻辑中比较好

**Comment by noyobo** [comment]
这个是工程构建方便的  NODE_ENV 这个和 webpack 构建有强依赖关系。 一般不建议改这个

建议的方式是： https://alibaba.github.io/ice/docs/developers/how-to-define-global-var

**Comment by HaveF** [comment]
@noyobo 感谢感谢! 刷文档时居然没看到! 正是我需要的🤝

**Comment by shuaidiao** [comment]
引入webpack就会构建失败

**Comment by noyobo** [comment]
@shuaidiao  麻烦请提供错误信息，新开个 issue 反馈。

**Comment by shuaidiao** [comment]
已经开了，麻烦帮我看下 @noyobo
