### ISSUE TITLE
初始化项目的时候出问题

### ISSUE THREAD

**Issue by 626008797** [alibaba/ice#3993]
从github上拉下ice项目  执行npm i 的时候报错

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nsfw@1.2.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nsfw@1.2.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lenovo\AppData\Roaming\npm-cache\_logs\2021-01-05T06_54_17_385Z-debug.log

然后执行不了npm start

**Comment by ClarkXia** [comment]
npm 安装问题，建议指定淘宝源，重新执行 npm install 或者使用 cnpm 进行安装
