### ISSUE TITLE
首先明确业务场景：参考 https://ice.work/docs/guide/advance/assets-local

### ISSUE THREAD

**Issue by roginluo** [alibaba/ice#3994]
我就是参考的https://ice.work/docs/guide/advance/assets-local进行配置的，但是受到运维要求的限制，我不可以把我的应用部署到根目录，仅仅可以部署到某个context路径下，所以我会遭遇到这样尴尬的场景。所以我这边急切的期待如何通过访问/contextPath/icon-font/icon.woff2而不是/icon-font/icon-woff2

首先明确业务场景：参考 https://ice.work/docs/guide/advance/assets-local

上述表现上是符合预期的，icon-font-path 设置为  /icon-font/icon 的情况下，将 icon 资源添加在 public 目录下，网络请求时是  window.location.origin + 该路径
建议 /icon-font/ 下相关资源部署在根目录，或者在配置 icon-font-path 的时候直接以 cdn 地址规则进行配置（提前将 icon 资源部署到可访问 cdn）

> 如果以相对路径配置，需要将 icon-font 相关资源以相对  node_modules 下 @alifd/next 的位置存放，可操作性较差

_Originally posted by @ClarkXia in https://github.com/alibaba/ice/issues/3986#issuecomment-752825228_

**Comment by ClarkXia** [comment]
如果受部署问题影响，开发阶段和部署阶段的配置是不一样的可以通过不同的区分不同环境构建出不同的资源地址：
参考[工程配置](https://ice.work/docs/guide/basic/build#%E5%B7%A5%E7%A8%8B%E6%9E%84%E5%BB%BA%E9%85%8D%E7%BD%AE)

```js
module.exports = {
  plugins: [
    ['build-plugin-fusion', {
      themeConfig: {
        'icon-font-path': process.env.NODE_ENV === 'development' ? '\'/icon-font/icon\'' : '\'/contextPath/icon-font/icon\'' ,
        'font-custom-path': '\'/font/\''
      }
    }],
  ],
}
```

**Comment by roginluo** [comment]
很感谢您的回答，但是我们项目上测试，uat，生产的context路径都是不一样的。所以这个方法貌似不太可行。

**Comment by roginluo** [comment]
> 如果受部署问题影响，开发阶段和部署阶段的配置是不一样的可以通过不同的区分不同环境构建出不同的资源地址：
> 参考[工程配置](https://ice.work/docs/guide/basic/build#%E5%B7%A5%E7%A8%8B%E6%9E%84%E5%BB%BA%E9%85%8D%E7%BD%AE)
> 
> ```js
> module.exports = {
>   plugins: [
>     ['build-plugin-fusion', {
>       themeConfig: {
>         'icon-font-path': process.env.NODE_ENV === 'development' ? '\'/icon-font/icon\'' : '\'/contextPath/icon-font/icon\'' ,
>         'font-custom-path': '\'/font/\''
>       }
>     }],
>   ],
> }
> ```



> 如果受部署问题影响，开发阶段和部署阶段的配置是不一样的可以通过不同的区分不同环境构建出不同的资源地址：
> 参考[工程配置](https://ice.work/docs/guide/basic/build#%E5%B7%A5%E7%A8%8B%E6%9E%84%E5%BB%BA%E9%85%8D%E7%BD%AE)
> 
> ```js
> module.exports = {
>   plugins: [
>     ['build-plugin-fusion', {
>       themeConfig: {
>         'icon-font-path': process.env.NODE_ENV === 'development' ? '\'/icon-font/icon\'' : '\'/contextPath/icon-font/icon\'' ,
>         'font-custom-path': '\'/font/\''
>       }
>     }],
>   ],
> }
> ```


很感谢您的回答，但是我们项目上测试，uat，生产的context路径都是不一样的。所以这个方法貌似不太可行。为什么不能直接配置相对路径呢。
