### ISSUE TITLE
change layout name

### ISSUE THREAD

**Issue by wssgcg1213** [alibaba/ice#4]
AsideLayout 侧边布局  
BasicLayout 居中布局  
LandingLayout 通栏布局   
ScalableAsideLayout 通栏侧边布局  

布局类通用的特征: 一定有内容区域, 是否有顶栏(Header), 侧边(Aside)栏, 侧边栏位置(左右), 是否有(Footer)底栏, 是否固定页宽(通栏)

建议的命名规则, 对于可选择部分, 出现表示有, 用`-`分隔, 每一个可选部分之前可以有相关修饰词, 如固定(Fixed)

`顶栏-侧栏-底栏-通栏布局`  

`HeaderAsideFooterResponsiveLayout`

~~AsideLayout 侧边布局~~    HeaderAsideFooterLayout 顶栏-侧栏-底栏-布局
~~HeaderLayout 居中布局~~   HeaderFooterLayout 顶栏-底栏-布局
~~LandingLayout 通栏布局~~  FixedHeaderFooterLayout 固定顶栏-底栏布局
~~ScalableAsideLayout 通栏侧边布局~~  HeaderAsideFooterResponsiveLayout 顶栏-侧栏-底栏-通栏布局

cc @noyobo @yujiangshui

**Comment by yujiangshui** [comment]
HeaderAsideScalableFooterLayout ? 我觉得也可以，通过其他中文扩展描述，来表示这个 layout 的适用场景。

**Comment by wssgcg1213** [comment]
Scalable 通栏的描述, 会比固定存在部分(Header, Aside, Footer...) 在后面

**Comment by wssgcg1213** [comment]
通栏这个词  换成自适应如何  对应的英文  responsive
