### ISSUE TITLE
新建页面后无法打开页面

### ISSUE THREAD

**Issue by LanceXZH** [alibaba/ice#400]
![image](https://user-images.githubusercontent.com/13652913/39043181-4d154f9c-44bf-11e8-9631-01ef077440ef.png)
![image](https://user-images.githubusercontent.com/13652913/39043217-65291f82-44bf-11e8-9bec-1d70415420b5.png)
新建页面，添加区块，无法预览，新建后， 无法打开页面！报错如图，这是咋回事啊？

**Comment by LanceXZH** [comment]
貌似应该是新增加的模板的问题！！使用旧的模板没有出现这样的问题了！

**Comment by noyobo** [comment]
`@icedesign/icon`  依赖缺失了。

**Comment by noyobo** [comment]
看下 package.json dependencies 里是否有,  

如果已存在，可以重装依赖后试下。
