### ISSUE TITLE
如果受部署问题影响，开发阶段和部署阶段的配置是不一样的可以通过不同的区分不同环境构建出不同的资源地址：

### ISSUE THREAD

**Issue by roginluo** [alibaba/ice#4001]
很感谢您的回答，但是我们项目上测试，uat，生产的context路径都是不一样的。所以这个方法貌似不太可行。是不是能直接配置相对路径呢？

如果受部署问题影响，开发阶段和部署阶段的配置是不一样的可以通过不同的区分不同环境构建出不同的资源地址：
参考[工程配置](https://ice.work/docs/guide/basic/build#%E5%B7%A5%E7%A8%8B%E6%9E%84%E5%BB%BA%E9%85%8D%E7%BD%AE)

```js
module.exports = {
  plugins: [
    ['build-plugin-fusion', {
      themeConfig: {
        'icon-font-path': process.env.NODE_ENV === 'development' ? '\'/icon-font/icon\'' : '\'/contextPath/icon-font/icon\'' ,
        'font-custom-path': '\'/font/\''
      }
    }],
  ],
}
```

_Originally posted by @ClarkXia in https://github.com/alibaba/ice/issues/3994#issuecomment-754468125_

**Comment by ClarkXia** [comment]
相对路径配置问题已经说明过了，有问题可以在原有 issue 下重开并回复
多个环境可以配置不同的环境变量，`process.env.NODE_ENV` 只是一个例子

**Comment by ClarkXia** [comment]
可以尝试通过环境变量解决
```json
"scripts": {
  "start": "icejs start --mode dev",
  "build": "icejs build --mode prod",
  "test": "icejs build --mode test"
}
```

`process.env.APP_MODE` 根据 mode 的指定可以将会有 `dev | prod | test` 三种情况
