### ISSUE TITLE
希望可以加大对vue的支持力度，提高对vue的重视程度

### ISSUE THREAD

**Issue by 330595524** [alibaba/ice#4005]
在iceworks add scaffold 添加的vue模板
模板 存在<%=xxx%>发布不了问题，
希望可以对vue项目给与一定的支持，
1. 一般的项目都会有初始化模板，添加页面，修改路由，这是一个通行
2. 那么是不是可以通过配置+询问式解决不同项目问题
3. 有个设想，如果可以通过package.json 中通过配置要添加的模板类型指定输出目录，这样就可以实现对react、vue、angular对应项目目录，达到添加修改的目的

**Comment by imsobear** [comment]
最好是有一些具体的诉求

**Comment by imsobear** [comment]
长时间未回复，先关闭了。
