### ISSUE TITLE
Field组件的resetToDefault无效

### ISSUE THREAD

**Issue by we6288815** [alibaba/ice#4013]
问题描述：
Field组件的resetToDefault无效，无法重置一组输入控件的值为默认值

组件版本："@alifd/next": "^1.21.0-beta.4",

复现demo如下：
https://codepen.io/we6288815/pen/GRjYdzV?editors=0011

**Comment by bindoon** [comment]
```
<Form.Item>
          <Input name="name" defaultValue="abcd"/>
 </Form.Item>
```

defaultValue 这么写的

**Comment by we6288815** [comment]
> ```
> <Form.Item>
>           <Input name="name" defaultValue="abcd"/>
>  </Form.Item>
> ```
> 
> defaultValue 这么写的

不能结合Field组件用吗？

**Comment by imsobear** [comment]
如还未解决，建议通过 https://fusion.design/feedback 反馈
