### ISSUE TITLE
sandbox启用报错，子应用显示空白

### ISSUE THREAD

**Issue by 178558956245** [alibaba/ice#4021]
使用飞冰文档中的命令行新建一个项目，start后打开子应用页面空白，注释掉子应用配置的sandbox：true，子应用可以正常显示，
换成文档常见问题中的window.webpackJsonp = [];懒加载模块报错

**Comment by ClarkXia** [comment]
提供下具体的子应用模版信息和报错信息

**Comment by 178558956245** [comment]
> 提供下具体的子应用模版信息和报错信息


[demo.zip](https://github.com/alibaba/ice/files/5829050/demo.zip)

一开始报错Access to fetch at 'http://localhost:8080/app.js' from origin 'http://localhost:3333' has been block，
修改了子应用配置文件：添加devServer: {
    before(app) {
      app.use((req, res, next) => {
        res.set('Access-Control-Allow-Origin', '*');
        next()
      })
    }
  },
报错信息变更，变成error occurs when execute script in sandbox: ReferenceError: __webpack_require__ is not defined

**Comment by yuxiuj** [comment]
@178558956245 请问 ReferenceError: webpack_require is not defined 这个问题怎么解决的呢？

**Comment by maoxiaoke** [comment]
same as #4294
