### ISSUE TITLE
使用 import * as xxx from '@alifd/next'; 报错

### ISSUE THREAD

**Issue by luhc228** [alibaba/ice#4028]
来自用户 @静沫
在项目中使用 ` import * as nextComponent from '@alifd/next';` 会报错，如下图：

![image](https://user-images.githubusercontent.com/44047106/104881358-22e2ef00-599c-11eb-8c9f-583944f6a059.png)

![image](https://user-images.githubusercontent.com/44047106/104881396-31c9a180-599c-11eb-987e-8a6681cad60a.png)

build-plugin-fusion 插件做了分包处理，webpack 打包的时候，没有把模块打进来。

**Comment by ClarkXia** [comment]
build-plugin-fusion 默认做了分包逻辑，`import * as nextComponent from '@alifd/next';` 的写法和 `babel-plugin-import` 逻辑是冲突的，转化后会出现对应错误

**Comment by ClarkXia** [comment]
分包和 `import * ` 应该是二选一关系
