### ISSUE TITLE
ice集成数据管理方案

### ISSUE THREAD

**Issue by zerofront** [alibaba/ice#403]
**问题描述**
通过iceworker的模板ice design lite等，如何添加dva等数据管理方案？
问题主要是因为这些插件继承了router。而iceworker生成的布局区块又是有一套router的模式。导致两者相互冲突

**期望**
希望能基于icework与ice design给出一套数据管理方案

**Comment by chenbin92** [comment]
类似问题： https://github.com/alibaba/ice/issues/508

**Comment by chenbin92** [comment]
https://github.com/alibaba/ice/issues/537

**Comment by lijing666** [comment]
@chenbin92 刚刚下载了飞冰2.1.1，试用了一下，有以下心得：
1：目前的版本更像是一个模板库管理平台，离一套成熟的中后端应用构建平台还有很长的一段距离，一套成熟的应用构建平台必须解决后端数据的自动生成，以及无需手工代码的前后端交互，否则拼凑出来的也只是一堆html、css、js的盒子而已，并没有多大实际用处
2：第二个问题就是组件本身的重用问题，每一个添加到页面的块都产生复制的一份组件定义，组件重用的意义没有了，只是一堆重复的代码，希望能够你们能够思考一下这一块的实现方式
3：阿里开源了很多各种框架ant design、weex等，weex也入坑很久，问题多到头疼，哈哈，总感觉阿里人精神很好，但总是在一开始，慢慢就疲惫了，维护始终跟不上，希望你们这个团队能够制定一个比较完善的发展计划，反正我从你们当前的版本看，感觉很快就瓶颈了，希望不会是我想的那样

**Comment by noyobo** [comment]
@lijing666  感谢你的反馈

1.  关于数据管理部分，模板上目前是没有的。做复杂容易，做简单难，如何让开发者更简单的使用，是我们一直考虑的。数据绑定交互存在一定业务逻辑性，无法保证区块不内修改，接口完全一致。类似  bootstrap 时期搭建好 UI 后，再绑定数据。
2. 区块的共用，目前区块以偏 UI 为主，并且需要一定的数据配合。需要重用，那么就等于他们都是相同的，包括数据部分。但是往往同样的结构，展示不同的数据。 都是需要开发者决定的，工具上还无法判断。 区块与往常使用的 react-xxx 组件不同，组件是内部实现了逻辑，提供 props 进行定制，而区块是需要二次开发来完成后续工作。
3. 开源的同时也是希望能吸取社区宝贵的意见建议，提供更好的服务大家。如果你有遇到问题可以在 issue 反馈给我们，或者入群都可以。

**Comment by chenbin92** [comment]
redux 集成 https://github.com/alibaba/ice/pull/700

**Comment by xoptimal** [comment]
能否出一个基于dva 的数据化管理  ,  我相信这会让开发者更简单的使用 ~  降低 redux 这么繁琐的使用方式~

@chenbin92

**Comment by perany** [comment]
同求 dva的集成方案

**Comment by mozillo** [comment]
dva + 1
