### ISSUE TITLE
主应用子应用切换页头title未及时变更，需要刷新

### ISSUE THREAD

**Issue by 178558956245** [alibaba/ice#4031]
主应用子应用切换页头title未及时变更，需要刷新

1.开启应用：
![image](https://user-images.githubusercontent.com/18350417/104895958-7b70b700-59b1-11eb-9fc4-0073c94a925d.png)
开启时title为icestark framework
2.跳转到商家平台：
![image](https://user-images.githubusercontent.com/18350417/104896147-b541bd80-59b1-11eb-9413-66d446dea2b3.png)
title显示商家平台
3.切换回主应用Home页面
![image](https://user-images.githubusercontent.com/18350417/104896210-ce4a6e80-59b1-11eb-86d2-0cc604696b4b.png)
title显示商家平台

## What is the expected behavior? 期望的结果是什么？
title显示icestark framework
## Any additional comments? 相关环境信息？

- **ice.js Version**："ice.js": "^1.0.0",
- **build.json Configuration**：
![image](https://user-images.githubusercontent.com/18350417/104896714-77916480-59b2-11eb-8836-3bf7b5512fa2.png)

- **Node Version**: v14.4.0
- **Platform**:

**Comment by maoxiaoke** [comment]
@178558956245 https://ice.work/docs/guide/basic/page 需要在主应用页面添加 title 的渲染

**Comment by 178558956245** [comment]
1
