### ISSUE TITLE
tab Icon替换失败

### ISSUE THREAD

**Issue by LanceXZH** [alibaba/ice#404]
无法替换Icon，正确的打开方式是啥？

![image](https://user-images.githubusercontent.com/13652913/39169433-5f4c6bec-47ca-11e8-8829-06ae0aeca0d9.png)

![image](https://user-images.githubusercontent.com/13652913/39169346-0c971e7e-47ca-11e8-9aaf-cab49a94a166.png)

**Comment by noyobo** [comment]
PUBLIC_URL 目前没有这个变量注入。

**Comment by LanceXZH** [comment]
href="./favicon.ico" 我用相对路径也不行吗？图片放在根目录然后直接用href="favicon.ico"也不行呢？？是必须要用网络图片吗？

**Comment by noyobo** [comment]
favicon.ico  是你后面添加的吗？

**Comment by noyobo** [comment]
ice-scripts@beta 版本已支持，在 public/ 目录下的文件会 copy 到 build 中。 

index.html 

```html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <meta http-equiv="x-ua-compatible" content="ie=edge,chrome=1">
  <meta name="viewport" content="width=device-width">
  <title>网站标题</title>
</head>

<body>
  <div id="ice-container"></div>
</body>

</html>
```
![image](https://user-images.githubusercontent.com/1292082/42143495-e4b51c86-7de7-11e8-83a7-eec0ec45c54f.png)

存在 favicon.png favicon.ico 即可， 编译后会自动设置
