### ISSUE TITLE
在iceworks标签里直接点击npm脚本只能激活一个

### ISSUE THREAD

**Issue by AoaoMH** [alibaba/ice#4045]
目前这边发现的是2个脚本运行的地方
一个是编辑器顶部右侧的debug和build
![image](https://user-images.githubusercontent.com/29968512/105469168-d0bf0800-5cd2-11eb-8969-6deca693f9c3.png)

这里点击之后会开启`Run Debug`和`Run Build`名称的终端
![image](https://user-images.githubusercontent.com/29968512/105469173-d3216200-5cd2-11eb-9b97-6f631f1da842.png)
也就是说这里可以同时在debug的时候进行build

但是如果在npm脚本栏里点击运行，那么只会激活一个名为`Run Script`的终端
![image](https://user-images.githubusercontent.com/29968512/105469382-1a0f5780-5cd3-11eb-83fe-ab912279fb8c.png)

想要进行其他命令必须停止正在运行的script终端，无法在start的时候进行build或其他脚本操作，体验较差
![image](https://user-images.githubusercontent.com/29968512/105469399-21366580-5cd3-11eb-95e1-defa0b4bbb6d.png)

**Comment by luhc228** [comment]
Will fix it in next version
