### ISSUE TITLE
希望可以引入ahooks中更多的hooks

### ISSUE THREAD

**Issue by whit15** [alibaba/ice#4049]
如useFusionTable、useCookieState等，当然如果是能完整引入适配会更好。
尝试过单独在项目中引入ahooks来替代ice自带的useRequest，在全局设置时ahooks需要在根节点嵌套，感觉这种方式不太友好，最后还是去掉ahooks回到了ice自带的useRequest中来，但是ahooks中很多其他优秀的hooks也就没法使用，建议官方是不是可以考虑将更多的hooks引入进来，并通过入口文件或单独的配置文件来修改全局配置。

**Comment by imsobear** [comment]
useRequest 因为涉及到框架的定制，所以建议使用 ice 导出的。

其他 hooks 直接依赖 ahooks 就可以，ahooks 飞冰团队本身也有参与，文档也有推荐：https://ice.work/docs/guide/basic/component#React%20Hooks

**Comment by whit15** [comment]
好的，打算新项目拿ahooks来做二次封装，用完整ahooks的话其实也就不需要useRequest了

**Comment by imsobear** [comment]
「在全局设置时ahooks需要在根节点嵌套，感觉这种方式不太友好」没看懂这句话，理论上直接用也没问题

**Comment by whit15** [comment]
@imsobear ahooks的useRequest，官方给出的全局配置方案，是要用UseRequestProvider来实现全局配置
[https://ahooks.js.org/zh-CN/hooks/async#%E5%85%A8%E5%B1%80%E9%85%8D%E7%BD%AE](url)

**Comment by imsobear** [comment]
这个应该可以直接用 icejs 的 request，其实跟 icejs 内置的 useRequest 作用差不多。

**Comment by whit15** [comment]
对，从配置方式和跟框架的结合度来说，肯定是ice的useRequest更好，但是我想用ahooks中其他的hooks的同时不想两种混用，哈哈哈

**Comment by imsobear** [comment]
嗯，那就在 app.ts 里配置下 `useRequestProvider`

**Comment by whit15** [comment]
@imsobear 非常感谢，通过app.ts中使用addProvider插入useRequestProvider解决了ahooks全局配置的问题
