### ISSUE TITLE
app.js中添加了icestark配置后，主工程切换动态路由时对应组件触发卸载，而不配置icestark时不会触发卸载

### ISSUE THREAD

**Issue by caojinjie** [alibaba/ice#4053]
**场景描述：**

我这边工程使用了icestark微服务，结构为主工程套子工程，子工程主要是详情页面，路由根据id动态配置，即/xxx/:id；

主工程中可以用tab页签导航打开多个详情页面，当详情页面切换时，会触发子工程路由切换，如/xxx/1 -> /xxx/2；

由于react-router机制，此时子工程路由对应组件不会重新安装（重走生命周期），当前我的解决方式是在子工程路由处添加组件的key为props.match.params.id；

在追溯该问题过程中，发现主工程中也会有动态路由场景，如资源的编辑页面/res/edit/:id（组件是主工程不是子工程），展示方式同上（使用tab页签导航切换），发现路由切换时，如/res/edit/1 -> /res/edit/2，会自动重新安装组件（重走生命周期），产生了疑惑；

**测试效果：**

app.js加入了icestark配置后切换动态路由会重新安装组件，未做icestark配置时切换动态路由不会重新安装组件；

**复现demo：**

使用官方icestark模版（https://fusion.design/mc/detail/745?spm=fusion-design.template-design-fusion.0.0.230b38035oXtuL），修改about路由为动态路由，在对应组件中加入useEffect打印日志，在layout中添加按钮切换动态路由，观察控制台输出；源码见zip；

**Comment by caojinjie** [comment]
[src.zip](https://github.com/alibaba/ice/files/5871048/src.zip)

**Comment by maoxiaoke** [comment]
duplicate for https://github.com/ice-lab/icestark/issues/239
