### ISSUE TITLE
sass-loader&less-loader 升级最新版本

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#4060]
## sass-loader 8.0.0 -> 10.0.0

[Changelog](https://github.com/webpack-contrib/sass-loader/blob/master/CHANGELOG.md)

### prependData -> additionalData

- prependData [detail](https://github.com/webpack-contrib/sass-loader/tree/v8.0.0#prependdata)
- additionalData [detail](https://github.com/webpack-contrib/sass-loader#additionaldata) 

功能应该一样，兼容下 prependData 选项就可以，走 sassLoaderOptions 的方式应该没问题，但是如果是走 webpack-chain 改的 sass-loader 好像就没办法了？

## less-loader 5.0.0 -> 7.0.0

[Changelog](https://github.com/webpack-contrib/less-loader/blob/master/CHANGELOG.md)

**Comment by ClarkXia** [comment]
sass-loader 已升级至 10.0.0，默认使用 sass（dart-sass）

**Comment by ClarkXia** [comment]
less-loader 已升级至 7.3.0，less 升级至 4.0.0

sass 和 less 均升级至 webpack 4 相关最高版本
