### ISSUE TITLE
如何配置路由返回一个 json

### ISSUE THREAD

**Issue by DDDrop** [alibaba/ice#4062]
在对应iOS的universal links时，需要已json的形式返回 /.well-known/apple-app-site-association文件。

> 例如：twitter.com/.well-known/apple-app-site-association

想请问如何配置路由。

**Comment by ClarkXia** [comment]
这块路由由网关服务决定，以 nginx 为例可以配置不同 localtion 到不同目录，比如：
```
// 输出前端资源页面
location / {
  root html;
  index index.html index.htm;
}
// 输出想要的今天资源
location /.well-known/ {
  root /home/source/www/;
  autoindex on;
}
```
具体配置形式可以参考社区 nginx 配置

**Comment by DDDrop** [comment]
哦哦。谢谢提点。搞定啦。
