### ISSUE TITLE
updateApps方法使用

### ISSUE THREAD

**Issue by 178558956245** [alibaba/ice#4063]
## What is the current behavior? 发生了什么？
在layout里面使用useEffect调用updateApps方法在调用了接口的情况下报错apps.map is not a function怎么处理，使用写死的数据是可以的

![image](https://user-images.githubusercontent.com/18350417/105971969-13fbeb00-60c6-11eb-9fc0-3bafd4a7b238.png)
![image](https://user-images.githubusercontent.com/18350417/105971991-1c542600-60c6-11eb-9a6f-57a72678d0c3.png)

## Any additional comments? 相关环境信息？

- **ice.js Version**：1.6.3
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by ClarkXia** [comment]
`updateApps` 接收一个数组，`getChild()` 返回是一个 Promise，参考以下伪代码

```js
useEffect(() => {
  (async() => {
    const apps = await getChild();
    updateApps(apps);
  })();
}, []);

```
