### ISSUE TITLE
 createStore 共享state未更新

### ISSUE THREAD

**Issue by Gamehu** [alibaba/ice#4068]
## What is the current behavior? 发生了什么？
store里的数据没有更新

场景：B逻辑上时A的子组件，但是因为需求要求B在系统里另开tab页签，所以物理上A、B时独立的，现想要B能拿到A的state。

**通过createStore 使A的models state，在B能访问，但是A加载数据成功后，B获取的state 还是为 {}，未更新。**

**组件A models:**

`state: {
    singleStrategy: {},
    ...
}`

**组件B 包装Provider:**
```javascript
import React from 'react';

import { createStore } from '@ice/store';

import singleResourceStrategy from '../SingleResourceStrategy/models/singleResourceStrategy';

import SingleResourceStrategyEdit from './container';



export default function SingleResourceStrategyEditProvider() {

 const { Provider, ...props } = createStore({

  singleResourceStrategy,

 });

 return (

  <Provider>

   <SingleResourceStrategyEdit {...props} />

  </Provider>

 );

}
```

**组件B，引用：**

```javascript
const singleResourceStrategy = props.useModelState('singleResourceStrategy');
const { singleStrategy } = singleResourceStrategy;
```

## What is the expected behavior? 期望的结果是什么？

页面B能拿到最新的A的state

## Any additional comments? 相关环境信息？

- **ice.js Version**：1.9.9
- **build.json Configuration**：
- **Node Version**:12.18.3
- **Platform**:

**Comment by luhc228** [comment]
提供最小复现的 demo

**Comment by imsobear** [comment]
给的信息不足以排查问题，先关闭了。
