### ISSUE TITLE
期望使用icestark做3层嵌套来搭建服务

### ISSUE THREAD

**Issue by caojinjie** [alibaba/ice#4073]
## What is the current behavior? 发生了什么？

A为主应用，其包含多个功能，其中一个功能会由子应用B统一管理，子应用B自身会集成多个子应用用于控制其的权限，
即【A -【B -【 C、D、E...】】】，由于A、B之前需要做物理隔离，目前来看icestark需要嵌套多层；

## What is the expected behavior? 期望的结果是什么？

使用icestark隔离各个页面，官方例子都是两层嵌套使用，即【framework - child】，期望能够嵌套为上述场景所述，
【framework - framework - child】或【framework - child - child】或 手动加载子服务；

## Any additional comments? 相关环境信息？

- **ice.js Version**：1.14.1
- **build-plugin-icestark Version**：2.0.4
- **build.json Configuration**：
- **Node Version**:10.16.0
- **Platform**:

**Comment by caojinjie** [comment]
### 目前实践过程

1. 【framework - framework - child】路由方式或手动加载方式均无法实现，加载页面时报错；
2. 【framework - child - child】路由方式或手动加载方式可以正常加载出页面；

### 当前遇到的问题

1. 当第二层的child做路由切换时，会造成主应用对应路由组件的重新加载（可见issue：https://github.com/alibaba/ice/issues/4053），造成切换后页面无法正常展示；
2. 由于问题1，我换了个思路，在第二层的child切换页面（其实是切换导航，加载不同的第三层child展示）时，不切换路由，通过状态来处理，切换页面时改变对应的state，当state变化时，当前路由组件（组件内手动加载第三层child）监听变化，卸载已加载的child，创建新的child，达到页面切换的效果；
问题时，手动调用卸载方法时，主应用的样式丢失（可见issue：https://github.com/alibaba/ice/issues/4074）

**Comment by maoxiaoke** [comment]
duplicate for https://github.com/ice-lab/icestark/issues/239
