### ISSUE TITLE
手动卸载子应用时，shouldAssetsRemove无响应

### ISSUE THREAD

**Issue by caojinjie** [alibaba/ice#4074]
【场景介绍】

子应用（A）中手动创建子应用（B）时，无法给A加入icestark=static的标记，导致手动卸载子应用B时，A的样式丢失（link被删除）；

【期望】

1. 子应用A的资源标签中能够加入表识；
2. 子应用B当调用unmountMicroApp进行卸载时，可以响应shouldAssetsRemove方法，在该方法中根据表识判断不对A的资源进行删除；

【Demo】
可见zip

**Comment by caojinjie** [comment]
[projectName.zip](https://github.com/alibaba/ice/files/5892160/projectName.zip)

**Comment by maoxiaoke** [comment]
@caojinjie 通过手动方式加载子应用，showAssetsRemove 需要手动指定
```tsx
  createMicroApp({
    name: `stark-micro-${activeKey}`,
    container: appContainer.current,
    umd: true,
    sandbox: true,
    url: [`/${activeKey}/js/index.js`, `/${activeKey}/css/index.css`],
  },
  {
    beforeMount: () => { console.log('beforeMount!') }
  },
  {
    shouldAssetsRemove: (assetUrl) => return !!assetUrl;
  }
);
```

**Comment by ClarkXia** [comment]
嵌套需求在 https://github.com/ice-lab/icestark/issues/239 跟进
