### ISSUE TITLE
从ice-scripts升级到icejs后, npm run build报错

### ISSUE THREAD

**Issue by missweetcxx** [alibaba/ice#4080]
按文档升级icejs后，npm start可正常运行，但是npm run build就报错;

具体报错log如下：
"""
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle @icedesign/cms-scaffold@3.0.5~prebuild: @icedesign/cms-scaffold@3.0.5
6 info lifecycle @icedesign/cms-scaffold@3.0.5~build: @icedesign/cms-scaffold@3.0.5
7 verbose lifecycle @icedesign/cms-scaffold@3.0.5~build: unsafe-perm in lifecycle true
9 verbose lifecycle @icedesign/cms-scaffold@3.0.5~build: CWD: D:\Users\xx.cai\projects-fe\posidon
10 silly lifecycle @icedesign/cms-scaffold@3.0.5~build: Args: [ '/d /s /c', 'icejs build' ]
11 silly lifecycle @icedesign/cms-scaffold@3.0.5~build: Returned: code: 1  signal: null
12 info lifecycle @icedesign/cms-scaffold@3.0.5~build: Failed to exec build script
13 verbose stack Error: @icedesign/cms-scaffold@3.0.5 build: `icejs build`
13 verbose stack Exit status 1

13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid @icedesign/cms-scaffold@3.0.5

18 verbose node v12.18.3
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error @icedesign/cms-scaffold@3.0.5 build: `icejs build`
22 error Exit status 1
23 error Failed at the @icedesign/cms-scaffold@3.0.5 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
"""

**Comment by ClarkXia** [comment]
@missweetcxx 使用官方的 demo 是否也存在 start 通过，build 报错的问题？

**Comment by missweetcxx** [comment]
> @missweetcxx 使用官方的 demo 是否也存在 start 通过，build 报错的问题？

暂未使用官方demo, 但是是完全按照 https://ice.work/docs/guide/migrate 这篇文档进行升级的

**Comment by missweetcxx** [comment]
> @missweetcxx 使用官方的 demo 是否也存在 start 通过，build 报错的问题？

具体报错截图
![屏幕截图_20210204105712](https://user-images.githubusercontent.com/30889036/106838772-defc2380-66d7-11eb-978b-98aa37fc1df1.png)

**Comment by imsobear** [comment]
@missweetcxx 重装依赖试一下，如果还不行的话最好能提供一个 demo 项目，我们跑一下看看。
