### ISSUE TITLE
创建项目一直name is defined

### ISSUE THREAD

**Issue by ycfcando** [alibaba/ice#4084]
不管怎么创建都会出现name is not defined，不能成功创建项目
demo：
应用名称：fusion-design-demo
路径：桌面
报错：name is not defined
![9EEDD915-D390-40bf-B375-FA1A5A21B5AA](https://user-images.githubusercontent.com/66405072/107136263-b6289800-693c-11eb-85a4-1428e724383e.png)

**Comment by imsobear** [comment]
截图看下

**Comment by alvinhui** [comment]
试一下：

- 应用名称不要有中划线
- 本地路径的文件夹不要又中划线
- 本地路径是一个空目录

创建的时候通过 `ctrl+shift+I` 打开调试控制台看看有没有错误。

**Comment by alvinhui** [comment]
我在我的 windows 电脑上无法复现该问题。 @ycfcando 也许可以尝试更新插件到最新版本，并且参考我上面所说的步骤提供更多的信息。

**Comment by alvinhui** [comment]
![image](https://user-images.githubusercontent.com/4392234/108456456-54a4e980-72ab-11eb-9a8a-fbe47e831b09.png)

我成功复现了这个问题，并且正在定位解决，预计会在下周释放的版本中修复。

**Comment by alvinhui** [comment]
出现这个报错的原因是因为你使用的源里面没有从 npm 同步版本，我已经手动同步了最新版本：

https://web.npm.alibaba-inc.com/sync/@alifd/scaffold-lite-js#logid=17248853

报 name is not defined 的原因是因为我们的某个包有 bug，有个变量未声明就被使用了，我已经在这个 PR 修复了这个问题：

https://github.com/ice-lab/iceworks-cli/pull/130

针对这种场景，在错误信息中抛出了源信息，让开发者更好地理解这个错误：

https://github.com/ice-lab/iceworks-cli/pull/131

或者我们还可以提供一个同步按钮，让开发者可以一键执行类似 `xnpm sync`的命令。 @luhc228
