### ISSUE TITLE
Install fail! Error: GET https://r.npm.taobao.org/@ali%2Fbuild-plugin-ice-def response 404 status

### ISSUE THREAD

**Issue by tosmq008** [alibaba/ice#4086]
![image](https://user-images.githubusercontent.com/1542804/107171796-9e194d00-69fe-11eb-808e-d321787250a2.png)

新建一个demo

按照官方手册操作

npm init ice   

选择：
## Lightweight TypeScript template with fusion design components

 npm install 

 sudo npm install -g cnpm --registry=https://registry.npm.taobao.org        

 cnpm -v    

 cnpm install  

错误日志如下：

`✖ Install fail! Error: GET https://r.npm.taobao.org/@ali%2Fbuild-plugin-ice-def response 404 status
Error: GET https://r.npm.taobao.org/@ali%2Fbuild-plugin-ice-def response 404 status
    at get (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/get.js:68:17)
    at get.next (<anonymous>)
    at onFulfilled (/usr/local/lib/node_modules/cnpm/node_modules/co/index.js:65:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
npminstall version: 3.28.0
npminstall args: /usr/local/bin/node /usr/local/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --fix-bug-versions --china --userconfig=/Users/zhuoruo/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://r.npm.taobao.org

`

**Comment by ClarkXia** [comment]
@ali/build-plugin-ice-def 是私有源依赖，外部用户不需要关心 可以删除该依赖，如果是阿里内部用户使用内部源即可
