### ISSUE TITLE
编译器使用代码分割和引入字体 实时更新很慢

### ISSUE THREAD

**Issue by 371280604** [alibaba/ice#4087]
vscode编译器,运行项目很慢,实时更新实时编译时改一个代码需要10来秒才能更新到浏览器
上图两个项目的对比 
第一个项目是没有使用代码分割功能和引用字体
![11](https://user-images.githubusercontent.com/70129933/107181000-f1969580-6a14-11eb-86ef-747398b3a71a.png)
图片好像没显示出来 运行时加载出来的是这样的↓
 DONE  Compiled successfully in 58599ms                                                                                                                                                                             下午1:38:29
Hash: 2de1acdcdca73e125b34
Version: webpack 4.46.0
Child
    Hash: 2de1acdcdca73e125b34
    Built at: 2021/02/08 下午1:38:29
                Asset       Size  Chunks                          Chunk Names
        css/index.css    520 KiB   index  [emitted]               index
    css/index.css.map   1.21 MiB   index  [emitted] [dev]         index
          favicon.png   4.83 KiB          [emitted]
           index.html  454 bytes          [emitted]
          js/index.js   6.08 MiB   index  [emitted]        [big]  index
      js/index.js.map   5.24 MiB   index  [emitted] [dev]         index
    Child html-webpack-plugin for "index.html":
             Asset     Size  Chunks  Chunk Names
        index.html  536 KiB       0

 Starting the development server at:
   - Local  :  http://localhost:3334/
   - Network:  http://10.10.111.32:3334/

第二个项目是使用了路由懒加载功能和引入ttf字体, 运行时加载了多余的好几个文件,导致很慢,请问有什么办法可以解决
![12](https://user-images.githubusercontent.com/70129933/107181081-13901800-6a15-11eb-8b2e-cf8d33d0d7b3.png)
图片好像没显示出来 运行时加载出来的是这样的↓ 多出来几个文件

Hash: 1723b9f4ef9ee92e4582    
Version: webpack 4.44.2       
Child
    Hash: 1723b9f4ef9ee92e4582
    Built at: 2021/02/08 下午1:39:19
                                           Asset       Size  Chunks                                      Chunk Names
            24f73c691532fdffe4fa.hot-update.json   47 bytes          [emitted] [immutable] [hmr]
     assets/456f6968af7fdbde28970967bfdc4d12.ttf   11.1 MiB                                       [big]
     assets/f80465e9d8cea2b48da01f5aba236b59.ttf   14.3 MiB                                       [big]
                                   css/index.css    579 KiB   index  [emitted]                           index
                               css/index.css.map   1.67 MiB   index  [emitted] [dev]                     index
                                     favicon.png  724 bytes          [emitted]
        index.24f73c691532fdffe4fa.hot-update.js   10.5 KiB   index  [emitted] [immutable] [hmr]         index
    index.24f73c691532fdffe4fa.hot-update.js.map   1.48 KiB   index  [emitted] [dev]                     index
                                      index.html  554 bytes          [emitted]
                                         js/0.js  821 bytes       0
                                     js/0.js.map  333 bytes       0  [dev]
                                         js/1.js  797 bytes       1
                                     js/1.js.map  321 bytes       1  [dev]
                                         js/2.js  837 bytes       2
                                     js/2.js.map  341 bytes       2  [dev]
                                         js/3.js  869 bytes       3
                                     js/3.js.map  357 bytes       3  [dev]
                                         js/4.js  829 bytes       4
                                     js/4.js.map  337 bytes       4  [dev]
                                         js/5.js  845 bytes       5
                                     js/5.js.map  345 bytes       5  [dev]
                                     js/index.js   8.26 MiB   index  [emitted]                    [big]  index
                                 js/index.js.map   7.66 MiB   index  [emitted] [dev]                     index
    Child html-webpack-plugin for "index.html":
             Asset     Size  Chunks  Chunk Names
        index.html  536 KiB       1

**Comment by 371280604** [comment]
#

- [ ] 
![11](https://user-images.githubusercontent.com/70129933/107181154-37535e00-6a15-11eb-8753-21b8789d6711.png)

**Comment by ClarkXia** [comment]
提供下 build.json 等项目配置，另外 ttf 文件达到了 十几 MB 有点不合理

**Comment by 371280604** [comment]
> 提供下build.json等项目配置，另外ttf文件达到了几MB有点不合理

{
  "plugins": [
    [
      "build-plugin-fusion",
      {
        "themePackage": "@alifd/theme-design-pro"
      }
    ],
    [
      "build-plugin-moment-locales",
      {
        "locales": [
          "zh-cn"
        ]
      }
    ]
  ],
  "proxy": {
    "/mainApi": {
      "enable": true,
      "target": "http://omp-fulfillment.test.i4px.com",
      "pathRewrite": {
        "^/mainApi": ""
      }
    }
  },
  "modeConfig": {
    "branch": {
      "outputDir": "E:/FB4/fpx-fb4-womp/fpx-fb4-womp-web/src/main/resources/static/build/"
    },
    "trunk": {
      "outputDir": "E:/FB4_trunk/fpx-fb4-womp-web/src/main/resources/static/build/"
    }
  }
}
![13](https://user-images.githubusercontent.com/70129933/107184257-30c7e500-6a1b-11eb-9a43-42aa07cc74e9.png)

**Comment by 371280604** [comment]
@ClarkXia 你好,能帮忙解决解答下吗

**Comment by ClarkXia** [comment]
配置上没什么问题，最好能有一个比较能复现二次编译慢的项目，比如 十几M 的字体文件如何引入

**Comment by imsobear** [comment]
给的信息不足以排查问题，先关闭了。
