### ISSUE TITLE
icejs 应用接入 qiankun 主应用

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#4093]

**Comment by ClarkXia** [comment]
icejs 项目接入qiankun 主应用：
1. 在 app.js 入口补充导出 bootstrap 周期
2. 使用 build-plugin-icestark 导出标准 umd 微应用

**Comment by ClarkXia** [comment]
@maoxiaoke 评估下 bootstap 的逻辑在 icestark 的架构下是否需要

**Comment by imsobear** [comment]
@ClarkXia 建议插件里先加下，什么都不做（或者打个日志）就可以。
