### ISSUE TITLE
table数据异常

### ISSUE THREAD

**Issue by LanceXZH** [alibaba/ice#410]
![image](https://user-images.githubusercontent.com/13652913/39246620-aef7a8c8-48c9-11e8-8f33-755ba671d483.png)
table的数据源写死，发现只要数组数目大于等于三，不断点击左侧边栏的“其他”item，右侧的数组就会不断的叠加！！点击三次后：
![image](https://user-images.githubusercontent.com/13652913/39246684-ddb78e58-48c9-11e8-9898-fa2ff24ba47a.png)

**Comment by LanceXZH** [comment]
我发现数据源中如果key是id的话，那么value必须是数字，如果设置成字符串，在数据源条数大于2时就会出现上述的问题！！不知道这个算不算bug。还是你们底层有对应的控制？？？

**Comment by chenbin92** [comment]
单独写了个demo测试验证没问题，作者未能提供可测试的环境和示例代码，先暂时关闭
