### ISSUE TITLE
Vue 物料支持计划

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#411]
飞冰物料目前只提供了 React 版本，但我们收到很多用户的反馈，希望提供 Vue 版本的物料。为此，我们提供了物料开发者工具 ice-devtools(目前还在beta版本)，可以通过 ice-devtools 自定义 React、Vue 物料。在官方仓库 [vue-materials](https://github.com/alibaba/ice/tree/master/vue-materials) 目录下，我们已经提供了基础的 Vue 物料，包含组件，区块，布局，脚手架。但这对于 Vue 物料体系来说远远不够，因此，在 Vue 物料上的计划是希望通过社区共建的方式来扩充 Vue 物料，主要有以下两种方式：

 * 通过认领的方式对现有 React 物料进行 Vue 转换共建
 * 自由贡献(基于业务场景的高质量区块)

## 认领列表

| 区块名 | 描述 | 认领状态 | 认领人 | 完成情况 | 
| ------   | ---- | ----         |  ---      |-------     |
| [ChartBar](https://alibaba.github.io/ice/block/chart-bar) | 柱状图 | 已认领 | [chenbin92](https://github.com/chenbin92)  | 已完成 |
| [UserLogin](https://alibaba.github.io/ice/block/user-login) | 登录页  | 已认领 | [nmxiaowei](https://github.com/nmxiaowei) |  已完成|
| [LandingIntroBanner](https://alibaba.github.io/ice/block/landing-intro-banner?type=react) | 首页介绍  | 已认领 | [1xuanyuan1](https://github.com/1xuanyuan1) | 开发中 |
| [ProgressDataList](https://alibaba.github.io/ice/block/progress-data-list) | 进度条数据列表  | 已认领 | [1xuanyuan1](https://github.com/1xuanyuan1) | 开发中  |
| [TagMessageList](https://alibaba.github.io/ice/block/tag-message-list) | 标签消息列表  | 已认领 | [sjy](https://github.com/sjy)  |  已完成 |
| [TabTable](https://alibaba.github.io/ice/block/tab-table) | 标签页表格组合  | 已认领 | [james-cain](https://github.com/james-cain)  | 开发中  |
| [TagTable](https://alibaba.github.io/ice/block/tag-table) | 标签表格组合  | 已认领 | [bybiuhappy](https://github.com/bybiuhappy)  | 开发中  |
| [DetailTable](https://alibaba.github.io/ice/block/detail-table) | 详情信息表格  | 已认领 |  [bybiuhappy](https://github.com/bybiuhappy)   |  开发中 |
| [RealTimeOverview](https://alibaba.github.io/ice/block/real-time-overview) | 实时概况  | 已认领 |  [bybiuhappy](https://github.com/bybiuhappy)   | 开发中  |
| [DataStatistics](https://alibaba.github.io/ice/block/real-time-overview) | 数据统计展示  | 已认领 |  [bybiuhappy](https://github.com/bybiuhappy)   |  开发中 |
| [DataDisplay](https://alibaba.github.io/ice/block/data-statistics?type=react) | 数据展示  | 已认领 | [nmxiaowei](https://github.com/nmxiaowei)  | 已完成  |

注：未列出全部，根据使用率和认领情况按需增加，[区块列表](https://alibaba.github.io/ice/block)

## 开发文档
  * [物料简介](https://alibaba.github.io/ice/docs/materials/intro-materials)
  * [开发者工具 ice-devtools ](https://alibaba.github.io/ice/docs/materials/ice-devtools)
  * [如何贡献](https://alibaba.github.io/ice/docs/materials/how-to-contribute)

## 认领方式

大家可以在下面的 issue 评论认领，有任何疑问可以通过飞冰钉钉群联系我们

![](https://camo.githubusercontent.com/340ac1a3e004f03a29d991a4ba820ac2698a1c93/68747470733a2f2f67772e616c6963646e2e636f6d2f7466732f544231695666626531535342754e6a7930466c58586242705658612d3634302d3838302e6a7067)

**Comment by nmxiaowei** [comment]
@chenbin92 
UserLogin登陆页 和 DataDisplay 数据展示

**Comment by 1xuanyuan1** [comment]
@chenbin92 
LandingIntroBanner 首页介绍
ProgressDataList 进度条数据列表

**Comment by dingyiming** [comment]
为什么我环境跑不起来？

![](https://images-cdn.shimo.im/0S74Nxqzdj4L0oQi/image.png!thumbnail)
![](https://images-cdn.shimo.im/8fEoiqpWSqwxiJ6X/image.png!thumbnail)

**Comment by chenbin92** [comment]
@dingyiming 试试 `ice-devtools-init`

**Comment by dingyiming** [comment]
@chenbin92 哦哦，文档写错了吗？可以更新下，第一步就被阻挡在了门外

**Comment by yi-ge** [comment]
非常期待！

**Comment by easycrew** [comment]
@chenbin92  改为 ice-devtools-init ice-materials-template app  报错
![image](https://user-images.githubusercontent.com/20573490/39354612-7c4faa18-4a3d-11e8-95c3-258915f6bb72.png)

**Comment by chenbin92** [comment]
@easycrew  看起来是 Object.values 兼容问题，你可以升级下 node 版本试试，我这边兼容性

**Comment by sjy** [comment]
@chenbin92  TagMessageList

**Comment by Jiiiiiin** [comment]
👍

**Comment by creanme** [comment]
我照着文档使用下面的命令，cpu使用率就飙升到100%，我等待了30秒左右，关掉了，windows系统。
$ git clone git@github.com:alibaba/ice.git
$ npm run bootstrap
![Alt text](http://wx3.sinaimg.cn/large/6dd11bf2gy1frln7aqclqj21k70ia0x9.jpg)

**Comment by yoohhal** [comment]
![image](https://user-images.githubusercontent.com/26109591/51521421-8e535e00-1e61-11e9-8880-4ef1d0326c7a.png)
构建区块的时候一直在报这个错，不知道怎么解...

**Comment by Eagle407** [comment]
各位大神，如何建立 基于Vue的物料库， ice-devtools init  建立的是基于React的物料库

**Comment by chenbin92** [comment]
@Eagle407   参考文档： https://alibaba.github.io/ice/docs/materials/custom-template
