### ISSUE TITLE
ant design pro v5 怎样改造成ice child？

### ISSUE THREAD

**Issue by ruofeng086** [alibaba/ice#4110]

**Comment by ClarkXia** [comment]
如果是基于 UmiJS 可以参考 https://ice.work/docs/icestark/guide/faq#UmiJS%20%E5%BA%94%E7%94%A8%E5%A6%82%E4%BD%95%E6%94%B9%E9%80%A0%E4%B8%BA%E5%BE%AE%E5%BA%94%E7%94%A8

**Comment by ruofeng086** [comment]
qiankun和icejs是同一个东西吗？

**Comment by ruofeng086** [comment]
接入后，没有渲染成功
![image](https://user-images.githubusercontent.com/14192308/109249311-6db91780-7822-11eb-946b-946fbbc0a5ff.png)
![image](https://user-images.githubusercontent.com/14192308/109249342-7ad60680-7822-11eb-87ca-9ae607122f59.png)

**Comment by ruofeng086** [comment]
![image](https://user-images.githubusercontent.com/14192308/109271211-2a729f00-784a-11eb-8cf6-074f866c5b6f.png)

**Comment by ClarkXia** [comment]
看下 umi 项目的入口文件，需要获取对应的 rootId 进行渲染，或者使用 entry 的模式

**Comment by ruofeng086** [comment]
> 看下 umi 项目的入口文件，需要获取对应的 rootId 进行渲染，或者使用 entry 的模式

文档中没有写rootid该怎么配置？

**Comment by maoxiaoke** [comment]
@ruofeng086 umi 应用接入 icestark 微应用请参考  https://github.com/maoxiaoke/icestark-demos/blob/master/child/umi-3.x/README.md
