### ISSUE TITLE
ice应用启动时报错globalThis is not defined

### ISSUE THREAD

**Issue by cassiewang01** [alibaba/ice#4113]
ice应用安装依赖，tnpm run start后，报错：ReferenceError: globalThis is not defined

具体报错如下：
![image](https://user-images.githubusercontent.com/22312427/109416183-9a725800-79f7-11eb-9976-21452ab9dd39.png)

查看了node_modules/_build-plugin-app-core@1.3.1中的确没有globalThis

帮忙看下是什么原因，感谢～

**Comment by ClarkXia** [comment]
项目中依赖的 queue-microtask 升级导致，可以升级 node 版本或者暂时先锁定低版本
