### ISSUE TITLE
路由嵌套3层或以上有bug

### ISSUE THREAD

**Issue by yantaolu** [alibaba/ice#4118]
## What is the current behavior? 发生了什么？

正常配置路由嵌套三层或三层以上时，则结果超出预期，

![image](https://user-images.githubusercontent.com/38716634/109746693-c583c400-7c10-11eb-9fbd-1dabdcc812d5.png)

按照这种配置理论上子路由会拼接父路由的路径，但是超过三层时，则不拼接路径了

![image](https://user-images.githubusercontent.com/38716634/109746837-01b72480-7c11-11eb-8cbe-e22b2e1de7bc.png)

## Any additional comments? 相关环境信息？

- **ice.js Version**：
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by yantaolu** [comment]
![image](https://user-images.githubusercontent.com/38716634/109747440-16e08300-7c12-11eb-8d13-5a085a8b0a6a.png)

**Comment by yantaolu** [comment]
正常配置一个四层路由需要这样配置
![image](https://user-images.githubusercontent.com/38716634/109747866-dc2b1a80-7c12-11eb-8251-9261064c46d4.png)

**Comment by ClarkXia** [comment]
提供下复现 demo，嵌套会自动拼接 path

**Comment by ClarkXia** [comment]
ice.js 1.17.2 已修复
