### ISSUE TITLE
Module build failed: Duplicate plugin/preset detected

### ISSUE THREAD

**Issue by seanxlliu** [alibaba/ice#4126]
## What is the current behavior? 发生了什么？

步骤：
1. 项目更新ice 从1.0.0 到1.16.0
2. 删除node_modules, yarn.lock
3. 清理缓存 npm clean cache -f
4. npm install
5. npm run start

错误：

_./.ice/index.ts
Error: Duplicate plugin/preset detected.
If you'd like to use two separate instances of a plugin,
they need separate names, e.g.

  plugins: [
    ['some-plugin', {}],
    ['some-plugin', {}, 'some unique name'],
  ]

Duplicates detected are:
[
  {
    "alias": "E:\\xxx\\node_modules\\@babel\\preset-react\\lib\\index.js",
    "options": {},
    "dirname": "E:\\xxx",
    "ownPass": false,
    "file": {
      "request": "E:\\xxx\\node_modules\\@babel\\preset-react\\lib\\index.js",
      "resolved": "E:\\xxx\\node_modules\\@babel\\preset-react\\lib\\index.js"
    }
  },
  {
    "alias": "E:\\xxx\\node_modules\\@babel\\preset-react\\lib\\index.js",
    "options": {
      "runtime": "automatic"
    },
    "dirname": "E:\\xxx",
    "ownPass": false,
    "file": {
      "request": "E:\\xxx\\node_modules\\@babel\\preset-react\\lib\\index.js",
      "resolved": "E:\\xxx\\node_modules\\@babel\\preset-react\\lib\\index.js"
    }
  }
]
    at createDescriptors.next (<anonymous>)
    at createPresetDescriptors.next (<anonymous>)
    at Generator.next (<anonymous>)
    at Generator.next (<anonymous>)
    at Generator.next (<anonymous>)
    at cachedFunction.next (<anonymous>)
    at mergeChainOpts.next (<anonymous>)
    at Generator.next (<anonymous>)_

## What is the expected behavior? 期望的结果是什么？
正常的打包和运行

## Any additional comments? 相关环境信息？

环境：

- **ice.js Version**：1.16.0
- **build.json Configuration**：
```
const config = require('./project.config');

module.exports = {
  mpa: true,
  devPublicPath: config.devPublicPath,
  publicPath: config.proPublicPath,
  plugins: [
    [
      "build-plugin-moment-locales",
      {
        "locales": [
          "zh-cn"
        ]
      }
    ]
  ],
  sassLoaderOptions: {
    prependData: `
      @import "./src/global/theme.scss";
    `
  }
}
```

- **Node Version**: v14.16.0
- **Platform**: Windows 10
- **yarn**: 1.22.5
- **npm**: 6.14.11
- **package.json**:

```
{
  "name": "xxx",
  "version": "3.0.0",
  "description": "banber v3",
  "dependencies": {
    "antd": "^4.13.0",
    "i18next": "^19.8.4",
    "moment": "^2.24.0",
    "react": "17.0.1",
    "react-dom": "^16.4.1",
    "react-i18next": "^11.8.5",
    "react-router": "^5.2.0",
    "swiper": "^6.4.15"
  },
  "devDependencies": {
    "build-plugin-moment-locales": "^0.1.0",
    "enzyme": "^3.11.0",
    "enzyme-adapter-react-16": "^1.15.6",
    "eslint": "^6.8.0",
    "ice.js": "^1.16.0",
    "react-test-renderer": "^17.0.1",
    "stylelint": "^13.2.0"
  },
  "scripts": {
    "start": "icejs start --config build.config.js",
    "build": "icejs build --config build.config.js",
    "test": "icejs test",
    "lint": "npm run eslint && npm run stylelint",
    "eslint": "eslint --cache --ext .js,.jsx,.ts,.tsx ./",
    "eslint:fix": "npm run eslint -- --fix",
    "stylelint": "stylelint \"**/*.{css,scss,less}\""
  },
  "engines": {
    "node": ">=8.0.0"
  },
  "private": true
}
```

**Comment by ClarkXia** [comment]
重复 issue 在 https://github.com/alibaba/ice/issues/4125 跟进

**Comment by seanxlliu** [comment]
@ClarkXia Thanks. The PR #4125 works in my enviroment.
