### ISSUE TITLE
项目运行ERR! Cannot find module 'react-dom' 

### ISSUE THREAD

**Issue by vision-yip** [alibaba/ice#4130]
## 近两天升级ice到1.16.0之后已经出现三次这种情况, 一次打包后再运行项目出现, 两次在电脑休眠状态唤醒了之后编译代码一直卡在50%的进度条, 然后重启项目出现.

![image](https://user-images.githubusercontent.com/18309167/110084069-7aadac00-7dca-11eb-946b-a87bdb88bb73.png)

- **ice.js Version**：1.16.0
- **Node Version**: 14.16.0
- **Platform**: macOS Catalina

![image](https://user-images.githubusercontent.com/18309167/110084322-ca8c7300-7dca-11eb-8b95-833912281c3a.png)
![image](https://user-images.githubusercontent.com/18309167/110084351-d11aea80-7dca-11eb-8bda-042feba87d77.png)

**Comment by imsobear** [comment]
@vision-yip 需要你提供各重现的项目放在 GitHub 上。

**Comment by imsobear** [comment]
长时间未回复先关闭掉了，有重现 demo 了再 reopen 下。
