### ISSUE TITLE
history的回调和React的没有对齐

### ISSUE THREAD

**Issue by xmsz** [alibaba/ice#4140]
## What is the current behavior? 发生了什么？

例如history.listen和history.block 理论上第一个参数应该是history，但是在ice里确是location

然后ice里的history为什么没有也没有类型

没对齐带来的问题是

```
// Block navigation and register a callback that
// fires when a navigation attempt is blocked.
let unblock = history.block(tx => {
  // Navigation was blocked! Let's show a confirmation dialog
  // so the user can decide if they actually want to navigate
  // away and discard changes they've made in the current page.
  let url = tx.location.pathname;
  if (window.confirm(`Are you sure you want to go to ${url}?`)) {
    // Unblock the navigation.
    unblock();

    // Retry the transition.
    tx.retry();
  }
});

```

没有tx.retry这个函数

还有一个场景是我，微应用服务里怎么互通block
例如我的子应用A里做了block，但是用户直接点击父应用进行了跳转，这时候就没办法触发block

## What is the expected behavior? 期望的结果是什么？

1. 希望对齐history
2. 希望有类型提示
3. 希望子应用的block也能拦截主应用或者其他方式解决需求

## Any additional comments? 相关环境信息？

- **ice.js Version**：
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by ClarkXia** [comment]
history.block 这个 API 已经被移除详见： https://github.com/ReactTraining/history/issues/690#issuecomment-477248369

关于子应用拦截主应用的需求可以具体描述下业务需求

**Comment by xmsz** [comment]
> history.block 这个 API 已经被移除详见： [ReactTraining/history#690 (comment)](https://github.com/ReactTraining/history/issues/690#issuecomment-477248369)
> 
> 关于子应用拦截主应用的需求可以具体描述下业务需求

居然被移出了

那我的问题变成
1. 希望对齐history.listen
```
// React

let unlisten = history.listen(({ location, action }) => {
  console.log(action, location.pathname, location.state);
});

// Ice
let unlisten = history.listen(( location, action ) => {
  console.log(action, location.pathname, location.state);
});
```


2. history有类型提示，因为现在是any不好检查问题


3. 子应用拦截父组件的场景

有
主应用A
子应用B 带有表单
子应用C

我们想要
用户跳转出子应用B的时候，提示用户未保存


实际
用户在子应用B的表单进行输入，然后不小心通过主应用A跳转到了子应用C

这时候既不会触发子应用的block和页面的unload(因为不是关闭页面)，也就无法显示需求



4. 那prompt组件可以使用吗

**Comment by ClarkXia** [comment]
1,2 看了下类型提示 block 还是在的，ice 导出的 histroy 使用应该没问题，具体的类型参考下 https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/history/index.d.ts#L46，类型提示我们处理下

3,4 多个主子应用的 history 都是独立创建的，而 history.block 等操作能对同一个 history 实例生效，而针对微前端模式下会出现多个 history 的场景，icestark 后续出个方案看如何支持 history block 的场景

**Comment by ClarkXia** [comment]
相关需求可以分别在 #4145 和 https://github.com/ice-lab/icestark/issues/263 跟踪
