### ISSUE TITLE
有没有可以控制构建时的资源消耗

### ISSUE THREAD

**Issue by xmsz** [alibaba/ice#4141]
## What is the current behavior? 发生了什么？
在jenkins上构建 基本每次都要搞挂掉 jenkins服务器是2核4G

除了构建ice项目，其他都是没问题的

![image](https://user-images.githubusercontent.com/5879146/110315132-c9b24600-8043-11eb-9719-38be46d7c7f7.png)

而且最少也要2分多钟，以前的非ice项目都是
![image](https://user-images.githubusercontent.com/5879146/110315257-f9614e00-8043-11eb-8194-d5d467c253be.png)
特别大的项目也才1分钟，而且不会把jenkins搞挂掉

所以理论上速度没有更快，性能倒是耗得更多

## What is the expected behavior? 期望的结果是什么？

1. 我要升级到什么配置构建ice才不会挂掉
2. ice能否可以设置，例如牺牲一些优化和时间但是至少能构建起来

## Any additional comments? 相关环境信息？

- **ice.js Version**：
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by ClarkXia** [comment]
先试下本地构建的具体输出 看下整体项目大小，以及会不会出现 OOM

**Comment by ClarkXia** [comment]
可以多试几次，看是否稳定复现，如果能够复现，可以提供下打包机相关的环境信息

**Comment by xmsz** [comment]
> 可以多试几次，看是否稳定复现，如果能够复现，可以提供下打包机相关的环境信息

2核4G centos7.2 2个项目就会挂

**Comment by xmsz** [comment]
我暂时关闭问题好了 

因为我们后台同学不是很愿意帮忙，他直接把每次同时构建次数变成1个来应付情况了，哎
