### ISSUE TITLE
DatePicker 设置初始值为时间戳的问题

### ISSUE THREAD

**Issue by terryZz** [alibaba/ice#415]
使用 DatePicker 时设置初始值为时间戳，这时候通过表单项获取的结果是时间戳；但是当手动设置过日期之后，获取到的表单值是 date 类型；期待不管是否重新设置，DatePicker 的返回值类型都是一致的

**Comment by wssgcg1213** [comment]
DatePicker 的  onChange 第一个值返回是 Date 类型, 设置初始值为时间戳实际并没有触发DatePicker的onChange 回调, 得看你是怎么获取的了

**Comment by wssgcg1213** [comment]
建议展示之前使用moment之类的库格式化一次
