### ISSUE TITLE
https启动项目CA证书无效

### ISSUE THREAD

**Issue by rootsli** [alibaba/ice#4155]
使用icejs start --mode local --https启动项目，浏览自动打开访问地址后，提示CA证书无效（参见截图），证书是否能支持基于host和port动态生成？

![ca](https://user-images.githubusercontent.com/4099803/110780395-9bc93d80-829f-11eb-8f56-377111b96d34.jpg)

**Comment by ClarkXia** [comment]
默认已添加 localhost 域名
打开钥匙串，选择系统，将终端输出的证书导入，并设置信任

**Comment by luhc228** [comment]
1. 在 终端 输入 `open /Users/xx/build-user-config/lib/ICE_CA/rootCa.crt` 
![image](https://user-images.githubusercontent.com/44047106/110781110-738e0e80-82a0-11eb-9f66-71fbf9c8a847.png)

2. 然后选择始终信任：
![image](https://user-images.githubusercontent.com/44047106/110781246-a0422600-82a0-11eb-8ef5-0b8172f28c77.png)
