### ISSUE TITLE
2.x迁移至icejs, import 得到的值是 undefined

### ISSUE THREAD

**Issue by Hicbik** [alibaba/ice#4160]
## What is the current behavior? 发生了什么？
2.x迁移至icejs, 在2.x里面import能获取到正确的值,icejs却是undefined

> 2.x
![image](https://user-images.githubusercontent.com/47243758/110923358-caa4e980-835b-11eb-8c8c-59e6bd1bc7a5.png)

> icejs
![image](https://user-images.githubusercontent.com/47243758/110923488-ead4a880-835b-11eb-887d-774d9f259667.png)

## Any additional comments? 相关环境信息？

- **ice.js Version**：1.17.1
- **build.json Configuration**：
- **Node Version**: v12.16.3
- **Platform**: window10

**Comment by ClarkXia** [comment]
提供下 import 相关代码以及工程配置
