### ISSUE TITLE
区块截图报错

### ISSUE THREAD

**Issue by maoye610** [alibaba/ice#4162]
![image](https://user-images.githubusercontent.com/54488615/111027999-aa922a80-842e-11eb-94f0-28d9f453c38a.png)

**Comment by maoye610** [comment]
按照指示来的啊，直接在iceworks init 的ExampleBlock模板里用 npm publish然后出这个错误，自己添加了一个也是这个错误

**Comment by ClarkXia** [comment]
错误原因是启动截图服务的时候找不到 mountNode，可以提供下相关的复现 demo

**Comment by maoye610** [comment]
> 错误原因是启动截图服务的时候找不到 mountNode，可以提供下相关的复现 demo

没有demo 就是建一个文件夹，然后
iceworks init
cd blocks/ExampleBlock
npm install
npm publish
失败

**Comment by maoye610** [comment]
iceworks add 之前我用这个创建了一个发布也是一样的错 是我少了什么操作吗

**Comment by ClarkXia** [comment]
确认下以下几点：
npm run build 是否可以成功构建出产物
npm run screenshot 最终执行的应该是 `screenshot -l -s mountNode` 看截图的命令少了 -s，各参数作用参考 [npm](https://www.npmjs.com/package/@ice/screenshot)

**Comment by maoye610** [comment]
虽然不知道为什么会这样，但是我去pngquant官网下载了pngquant.exe,然后放到node_modules里那个文件夹里，再发布就成功咯

**Comment by ClarkXia** [comment]
pngquant-bin 在 postinstall 阶段会根据环境进行编译，可能存在安装过程中错误的请求。
