### ISSUE TITLE
🚀  通过 webpack5 提升本地调试效率

### ISSUE THREAD

**Issue by ClarkXia** [alibaba/ice#4171]
icejs 基于 webpack 5 提供了一个提升本地开发调试性能的方案，让本地调试效率得到大幅提升。

优化前：
![图片2](https://user-images.githubusercontent.com/4219965/111414525-1b7d5f00-871b-11eb-8312-361a5ddf75f1.gif)

优化后：
![图片1](https://user-images.githubusercontent.com/4219965/111414512-14eee780-871b-11eb-96b6-5f49cb1c1d53.gif)

## 体验方式

1. 添加依赖：

```bash
$ npm i --save-dev build-plugin-webpack5 webpack
```

> 为了保证 webpack 版本引用正确，建议添加依赖后，重新安装所有依赖

2. 修改工程配置：

```diff
{
+  "customWebpack": true,
  "plugins": [
+    ["build-plugin-webpack5", { "remoteRuntime": true }]
  ]
}
```

remoteRuntime 参数支持配置 include 、exclude：

```json
{
   "customWebpack": true,
  "plugins": [
    [
      "build-plugin-webpack5",
      // 内置规则会默认过滤出需要预编译的包，如果有定制需求，可以通过参数进行指定
      { "remoteRuntime": {"include": "moment"}}
    ]
  ]
}
```

> 如开启过程中遇到问题，欢迎在此 issue 下进行反馈，我们将持续改进和优化本地构建提速的方案

**Comment by mopsky** [comment]
会报错，不知道是不是姿势不对：
```
Failed to compile with 1 errors 下午2:18:07

 error  in ./.ice/bootstrap.ts

Module not found: Error: Can't resolve '../src/app' in 'C:\Users\ChenFeng\VSCode\pfws.ice.erp\.ice' 
```

**Comment by ClarkXia** [comment]
项目是不是做过定制，是否存在 `src/app` ？

**Comment by mopsky** [comment]
![image](https://user-images.githubusercontent.com/18085384/113668757-4b4dd000-96e5-11eb-95c6-dcbe67e1d4bb.png)

没有src/app，是map多页模式

**Comment by ClarkXia** [comment]
多页暂未支持，这个需要我们看下

**Comment by mopsky** [comment]
哦，好的没事，我后期再关注，谢谢

**Comment by zhangtda** [comment]
构建的时候提示
Can't resolve 'os/crypto/stream/https' in  xxxx
webpack 5不再支持自动对Node引用的包进行polyfill，需要设置webpack的resolve.fallback 选项，在Ice 框架内怎么修改这项webpack配置

**Comment by lyyh** [comment]
请问现在MPA模式支持webpack5了吗？

**Comment by june2315** [comment]
不支持build-plugin-antd吗？使用以后样式没了

**Comment by phshy0607** [comment]
customWebpack 这个的作用是? 有文档吗？

**Comment by ClarkXia** [comment]
推荐直接使用 2.0 版本，默认集成基于 webpack5 的优化
