### ISSUE TITLE
怎么区分input组件输入中文时确认状态和输入待确认状态

### ISSUE THREAD

**Issue by wx727886178** [alibaba/ice#4174]
我们要定制这个长度限制 需要区分输入中文状态下 确认状态和输入中待确认 这两种状态，因为我们有特殊字符，用默认的字符长度限制不符合要求
思路是cutString属性为false，手动截取字符串，封装
但现在无法区分

**Comment by ClarkXia** [comment]
参考 https://developer.mozilla.org/zh-CN/docs/Web/API/Element/compositionstart_event
