### ISSUE TITLE
使用build-plugin-fast-refresh插件 css/scss不能热加载

### ISSUE THREAD

**Issue by slightc** [alibaba/ice#4180]
使用build-plugin-fast-refresh插件，css/scss更新后，页面样式不变化，刷新页面以后才有效果

期望：
css/scss更新后，页面样式立即变化，不用刷新页面

- **ice.js Version**：1.17.2

**Comment by ClarkXia** [comment]
![image](https://user-images.githubusercontent.com/4219965/112291654-45122980-8ccb-11eb-834e-b56ed623559c.png)
关注下 控制台是否有类似日志输出，目前无法复现，可以提供下简单的 demo

**Comment by slightc** [comment]
![image](https://user-images.githubusercontent.com/17919546/112293699-5eb47080-8ccd-11eb-9683-7f1114399c5d.png)
我这里具体操作如上

**Comment by slightc** [comment]
附上demo
https://github.com/slightc/css_test

**Comment by ClarkXia** [comment]
已重现，将在本周版本修复
