### ISSUE TITLE
ice@1.17.2版本升级了less-loader版本到7以上，导致less文件解析失败

### ISSUE THREAD

**Issue by nanfengd** [alibaba/ice#4187]
如题，报错截图如下：
![image](https://user-images.githubusercontent.com/13551694/112717175-e7c5e480-8f25-11eb-9b8a-e77a6beaf448.png)
可能是ice组织less-loader参数的时候有点问题：
![image](https://user-images.githubusercontent.com/13551694/112717213-193eb000-8f26-11eb-9b10-7327bef2dc68.png)

**Comment by imsobear** [comment]
我这边是好的唉，删除重装下依赖再试试？

![](https://img.alicdn.com/imgextra/i1/O1CN011XxzHf1jkR1id1sIp_!!6000000004586-2-tps-1586-736.png)

**Comment by ClarkXia** [comment]
内置 less-loader 已 升级，modifyVars 等参数被归到 lessOptions 下，ice 工程对[快捷工程配置](https://ice.work/docs/guide/basic/build#lessLoaderOptions)做了适配，如果是自定义插件，需要处理下：

```js
config.module
  .rule(rule)
  .use('less-loader')
  .tap((options) => ({
    ...options,
    // merge less options
    lessOptions: {
      ...(options.lessOptions || {}),
      modifyVars: {...},
    }
  }));

```
源码参考：https://github.com/alibaba/ice/blob/master/packages/build-user-config/src/userConfig/lessLoaderOptions.js#L49

**Comment by nanfengd** [comment]
截图报错通过升级build-plugin-antd到0.1.1版本解决，该版本对less-loader做了适配，谢谢大佬

**Comment by nanfengd** [comment]
升级ice@1.17.2版本后，内置less-loader升级到7.0版本以上，less升级到4.0，相应build-plugin-antd版本应升级到0.1.1版本，antd应升级到4.10.0版本以上，该版本对less@4.0做了兼容
