### ISSUE TITLE
[RFC] 路由页面配置优化

### ISSUE THREAD

**Issue by ClarkXia** [alibaba/ice#4188]
### 目前方案

目前框架为页面级组件提供了一些特殊配置，让页面级别组件可以一键开启一些能力，约定组件的静态能力统一收敛到 `pageConfg` 中，并跟随组件进行配置，同时 `pageConfig` 上的配置可以被其他运行时插件消费： 

```jsx
const HomePage = () => {
  return (
    // jsx code...
  )
}

HomePage.pageConfig = {
  scrollToTop: true,
  spm: 'adxsx'
  ...
}
```

### 期望方式

基于页面级别的配置可以跟随路由配置文件 `routes.ts` 中心化进行配置：

```js
const routerConfig = [
  {
    path: '/user',
    component: UserLayout,
    pageConfig: {
      scrollToTop: true,
      spm: 'adxsx',
    },
    children: [
      {
        // 路由路径
        path: '/login',
        // 精确匹配
        exact: true,
        // 路由组件
        component: UserLogin,
        // 配置路由的高阶组件
        wrappers: [wrapperPage]
      },
  ]
];

export default routerConfig;
```

### 其他配置

除默认约定 `pageConfig` 之外，页面属性上还存在 `getInitialProps` 用于 ssr 场景下页面级初始数据获取

### 两者优缺

|  配置方式  | 优势 | 缺点 |
|  ----  | ----  | ----  |
| 页面组件配置 | 就近配置原则，所有逻辑内聚到组件 | 配置相对零散，不同页面差异化配置不直观 |
| 中心化路由配置  | 中心化配置有利于配置统一处理和集中管控 | 大量逻辑可能导致 routes 膨胀不可控 |

**Comment by ClarkXia** [comment]
结论：
- 中心化配置（2.0 实现）
- pageConfig 不同层级配置问题

**Comment by FuzzyFade** [comment]
为了方便其他插件的版本迁移，考虑将中心化路由配置自动转为页面组件配置，最后再去消费。
