### ISSUE TITLE
mpa情况下 懒加载的组件路由权限不生效问题

### ISSUE THREAD

**Issue by mopsky** [alibaba/ice#4196]
我参考了这个issue #3706，也看了这个案例https://github.com/alibaba/ice/tree/master/examples/basic-auth，
SPA的情况下没什么问题，MPA就有bug了，不知道是什么问题，麻烦帮忙看看，谢谢：

附件：
[basic-auth.zip](https://github.com/alibaba/ice/files/6257202/basic-auth.zip)

**Comment by ClarkXia** [comment]
看了下 demo 版本锁死了，使用 ice.js 最新版即可，老版本没有内置权限插件

**Comment by mopsky** [comment]
@ClarkXia 升级到ice1.7.2之后还是不行
http://localhost:3333/home2.html#/
这个可以，因为没有lazy
http://localhost:3334/home.html#/
这个不行，还是可以进入路由

[basic-auth.zip](https://github.com/alibaba/ice/files/6263398/basic-auth.zip)

**Comment by mopsky** [comment]
@ClarkXia 帮忙看看啊，谢谢
