### ISSUE TITLE
开启ssr后，npm start 报错

### ISSUE THREAD

**Issue by darkmice** [alibaba/ice#4203]
![image](https://user-images.githubusercontent.com/1502088/113958355-8837d500-9853-11eb-8f33-f285f81441b0.png)
![image](https://user-images.githubusercontent.com/1502088/113958850-5a9f5b80-9854-11eb-8505-f333132cdc5d.png)

复现步骤：

1、`yarn create ice ssr`

根据模板选择: ts antd

2、`yarn install`

3、`yarn start`

- **ice.js Version**：1.17.2
- **build.json Configuration**：{ ssr: true}
- **Node Version**: v12.17.0
- **Platform**: win10

**Comment by luhc228** [comment]
发布 ice.js@1.17.4 已解决
