### ISSUE TITLE
基于vue源和自定义源下载的模板无法使用自定义源来下载区块

### ISSUE THREAD

**Issue by eterXing** [alibaba/ice#4207]
vscode版本: 1.52.1
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.10586

iceworks已经配置了自定义源
![图片](https://user-images.githubusercontent.com/41899952/113982412-4f135b00-987b-11eb-8226-5045ec843535.png)

下载项目时发现，如果是基于vue源或者是自定义源下载的模板项目添加区块的时候，没有出现自定义源的tab

![图片](https://user-images.githubusercontent.com/41899952/113982796-c517c200-987b-11eb-9f73-5fa4a7c3de8b.png)
![图片](https://user-images.githubusercontent.com/41899952/113982912-ea0c3500-987b-11eb-8e86-bee5b337b915.png)

当下载的是基于pcweb的模块的时候，添加区块就会有自定义源的tab项
![图片](https://user-images.githubusercontent.com/41899952/113983173-35bede80-987c-11eb-8577-61bb71d8d3f8.png)
![图片](https://user-images.githubusercontent.com/41899952/113983311-5b4be800-987c-11eb-8241-dad605cf7d50.png)

**Comment by imsobear** [comment]
还是因为 type 不对应的问题，项目的 type 是 vue，但是物料源因为 fusion 的原因 type 是 React，这里会做一层过滤，建议你把 json 放在其他地方（比如 unpkg）先托管下，把流程走通。
