### ISSUE TITLE
Mock数据过大，初次启动很慢

### ISSUE THREAD

**Issue by hi-liuyj** [alibaba/ice#4215]
https://github.com/alibaba/ice/issues/4088 从这个issue过来的，看了下只加了防抖。
我们还有一个场景，在做图展示的时候，有的mock文件是非常大的json，现在是一次性编译，导致启动时会非常慢，有没有可能搞成访问到才加载，改成一种路由注册机制。

比如：mock/index.js中如果使用了mock.registeRoutes这种方法，就不会编译全部文件，而是访问到才加载。
注册方式可能形如
`
mock.registeRoutes([
    '/collectionA/getA',
    '/collectionA/setA',
])
`
之后去寻找mock/collectionA/getA这样的文件加载进来
或者
`
mock.registeRoutes({
    '/collectionA/getA':  ‘/collectionA/getA’,
    '/collectionA/setA': '/collectionA/setA'
})
`

**Comment by ClarkXia** [comment]
这个诉求我们先评估下，如果访问时进行编译，针对数据量过大的场景网络返回将会非常慢，另外 json 文件时不参与编译的 可以再精准定位下启动速度影响的原因

**Comment by hi-liuyj** [comment]
> 这个诉求我们先评估下，如果访问时进行编译，针对数据量过大的场景网络返回将会非常慢，另外 json 文件时不参与编译的 可以再精准定位下启动速度影响的原因

现在是这么写的：
`
export default {
  '/api/users/1': { data: {} } // 很大的json
};
`
如果json不参与到编译，我们是不是可以通过把json单独写一个文件，然后import进来绕开？

**Comment by ClarkXia** [comment]
> 如果json不参与到编译，我们是不是可以通过把json单独写一个文件，然后import进来绕开？

嗯 可以的，目前只会编辑 js 和 ts 文件，json 默认使用导入的数据

**Comment by ClarkXia** [comment]
mock 采用运行时编译，大量静态 mock 数据建议独立成 json 文件
