### ISSUE TITLE
keepAlive 方案配合 build-plugin-icestark 使用问题

### ISSUE THREAD

**Issue by ClarkXia** [alibaba/ice#4224]
build-plugin-keep-alive 和 build-plugin-icestark 配合使用，在微前端容器下，页面报错

**Comment by caojinjie** [comment]
这个 issues是否能够解决在ice +icestark的场景下当切换不同的icestark支持子应用的keep-alive @ClarkXia

**Comment by ClarkXia** [comment]
应用级别的 Keep-Alive 可以在 https://github.com/alibaba/ice/issues/3875 进行讨论
