### ISSUE TITLE
主应用页面中的微应用调用接口，接口响应无返回

### ISSUE THREAD

**Issue by springot** [alibaba/ice#4229]
![image](https://user-images.githubusercontent.com/26103913/114692658-648cf700-9d4b-11eb-98d8-8df6dc23f5eb.png)
微应用单独运行的时候，返回接口响应正常。在主应用中加载，接口响应为空

**Comment by maoxiaoke** [comment]
看上去有点像跨域问题导致，可否排查一下跨域设置是否正常

**Comment by springot** [comment]
> 看上去有点像跨域问题导致，可否排查一下跨域设置是否正常

嗯 原来本地开发，主应用和微应用都要配置代理

**Comment by maoxiaoke** [comment]
@springot response header 可以贴一下，看下服务端跨域配置是否正确

**Comment by springot** [comment]
> @springot response header 可以贴一下，看下服务端跨域配置是否正确

嗯 已解决，在主应用也加了跨域代理配置
