### ISSUE TITLE
[RFC] 渐进式的 webpack5 能力

### ISSUE THREAD

**Issue by ClarkXia** [alibaba/ice#4233]
## 背景

目前在 icejs 研发框架中使用 webpack 5 能力相对比较繁琐，需要在项目目录下依赖 webpack 5，并且在 build.json 中[配置](https://ice.work/docs/guide/develop/plugin-list#build-plugin-webpack5)。
上述的方式对于期望体验 webpack 5 能力的项目并不友好，并且一旦希望降级也存在比较繁琐的删除步骤

## 期望方式

`build.json` 中直接开启  `webpack5` 即可体验 webpack 5 相关能力，不需要额外安装依赖：

```json
{
  "webpack5": true
}
```

一旦希望降级回 webpack 4，直接移除该配置即可

## 实现方案

1. 工程底层移除 webpack 4 的依赖
2. icejs 研发框架预打包 webpack 4 和 webpack 5 两个版本 webpack，实现动态切换

> 开启 webpack 5 后将动态修改基础链路上基于 webpack 5 的适配

**Comment by mopsky** [comment]
厉害了，期待

**Comment by imsobear** [comment]
开箱即用，默认开启，灰常需要
