### ISSUE TITLE
[RFC] MPA 多页应用下 browser 路由调试方案

### ISSUE THREAD

**Issue by ClarkXia** [alibaba/ice#4235]
## 现状

目前 MPA 项目启动后会输出对应 mpa 目录名称的 html 地址作为调试地址，比如：

```bash
http://localhost/dashboard.html
http://localhost/home.html
```

对于只存在一个组件或 hash 路由的情况下，可以正常进行调试，但是如果是 browser 路由，开发者期望访问 `http://localhost/dashboard/a` 的方式进行调试

## 优化方案

MPA 服务启动后，开发者可以通过 `http://localhost/dashboard.html` 和 `http://localhost/dashboard/` 两种方式访问。
如果 MPA 下的一个页面开启了  browser 路由则可以通过 `http://localhost/dashboard/` 的方式进行调试

### 实现方案

借助 devServer 能力对指定路径进行重定向处理：

```js
{
  devServer: {
    historyApiFallback: {
      rewrites: [
        // 具体实现需要考虑根路径匹配问题
        { from: /^\/dashboard\/*/, to: '/dashboard.html' },
      ]
    }
  }
}
```

上述逻辑根据 mpa 分析规则默认进行配置

### 自定义情况

存在一种情况：本地开发路径约定为 dashboard（目录名），而服务端部署时有统一前缀最终 basename 为 `site/dashboard`。
为了保障本地开发和最终部署代码的一致性，考虑开放自定义配置

```json
// build.json
{
  "mpa": {
    // 暂未实现
    "rewrites": {
      "dashboard": "site/dashboard"
    }
  }
}
```

**Comment by imsobear** [comment]
补充：无论是 SPA 还是 MPA 里某个页面是 SPA，BrowserHistory 都需要服务端做配合（rewrite）https://zzugbb.github.io/passages/react-router%E9%97%AE%E9%A2%98/

**Comment by ClarkXia** [comment]
结论：
- 默认开启 rewrite
