### ISSUE TITLE
 约定式路由生成结果错误

### ISSUE THREAD

**Issue by hyunsu-git** [alibaba/ice#4236]
## 按照约定路由目录，会有部分路由生成错误

这是我的Pages目录结构
<img width="332" alt="image" src="https://user-images.githubusercontent.com/51943152/114831846-682e8580-9e00-11eb-8a87-2f833709e140.png">

这是生成出来的路由结果
<img width="495" alt="image" src="https://user-images.githubusercontent.com/51943152/114831889-754b7480-9e00-11eb-87ca-6691129aaad0.png">

导致无法访问 /rabc/user/update/123456 这样路由

生成的通用路由应该在最后面

##  相关环境信息

- **ice.js ^1.0.0**：
- **"react": "^16.4.1",
- **"react-dom": "^16.4.1",
- **Node v15.12.0**:
- **mac os 10.15**:

**Comment by ClarkXia** [comment]
我们修复下，官方更推荐[配置式的路由](https://ice.work/docs/guide/basic/router#%E9%85%8D%E7%BD%AE%E8%B7%AF%E7%94%B1%E4%BF%A1%E6%81%AF)

**Comment by hyunsu-git** [comment]
好的 ，麻烦问答大概多久修复 ？  因为某些特别的需求 ，约定式路由 更适合我们

**Comment by hyunsu-git** [comment]
刚才我在 Pages 目录下 新增了 index.jsx 文件后，生成的路由产生了很大的差异
这是我的pages目录
<img width="332" alt="image" src="https://user-images.githubusercontent.com/51943152/114834698-6914e680-9e03-11eb-8cef-7f5c19ae6433.png">
这是生成的文件
<img width="450" alt="image" src="https://user-images.githubusercontent.com/51943152/114834849-8ba6ff80-9e03-11eb-9117-506f84b4e663.png">
<img width="492" alt="image" src="https://user-images.githubusercontent.com/51943152/114834894-9792c180-9e03-11eb-8ae2-e7ef3d85b2f7.png">
<img width="397" alt="image" src="https://user-images.githubusercontent.com/51943152/114834922-9feafc80-9e03-11eb-912e-0508e2051890.png">

这导致了排在 '/' 目录内部的路由都无法访问。
比如:
 /login
/qgc/activerecord
/qgc/crud
这些

**Comment by hyunsu-git** [comment]
刚才我在Pages目录下新增了 index.jsx 文件后，生成的路由产生了很大差异
这是我的目录
<img width="331" alt="image" src="https://user-images.githubusercontent.com/51943152/114835940-afb71080-9e04-11eb-94ce-a6ea0c4eece4.png">
这是我生成的文件,部分路由被包含到了  `/` 的跟路由中
<img width="533" alt="image" src="https://user-images.githubusercontent.com/51943152/114836006-c65d6780-9e04-11eb-93cd-72f25497f56a.png">
<img width="547" alt="image" src="https://user-images.githubusercontent.com/51943152/114836044-d07f6600-9e04-11eb-8617-ce97ac6f04cb.png">
<img width="569" alt="image" src="https://user-images.githubusercontent.com/51943152/114836067-d83f0a80-9e04-11eb-8d83-7abbc44248f7.png">
这导致排在  `/` 路由后的都无法访问
比如 
/login
/qgc/activerecord
/rabc/user/create

**Comment by ClarkXia** [comment]
预计下周修复，如果感兴趣也可以给我们提 PR
