### ISSUE TITLE
项目打包完成，访问index出现白空，页面出现报错信息Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by sosojie** [alibaba/ice#4249]
项目打包完成，访问index出现白空，页面出现报错信息Cannot read property 'call' of undefined
![image](https://user-images.githubusercontent.com/25785909/115505946-ce0d8800-a2ac-11eb-9636-58bbf96aa44d.png)

**Comment by luhc228** [comment]
提供最小复现demo

**Comment by sosojie** [comment]
项目dome地址:https://gitee.com/sosojie0124/icedome.git
上面提供的demo就是打包后，会重现我的问题，

我们定位到问题是echarts地图问题，但是不知道是webpack配置问题，还是什么原因打包之后使页面报错，

**Comment by luhc228** [comment]
![image](https://user-images.githubusercontent.com/44047106/116024329-8d34bb00-a680-11eb-99c7-6a1e84a9341e.png)

提供的 demo 中使用的antv/l7 默认开启了 `sideEffects: true`，但 demo 中没有用到从 antv/l7 中引入的模块（Scene, PointLayer, Marker），打包时候没有把它们打进去 bundle 中，导致出现找不到模块的错误。

![image](https://user-images.githubusercontent.com/44047106/116024580-13510180-a681-11eb-9bd2-34bc4cb4773f.png)

后面框架需要提供解法让这种情况不报错。@clarkXia
