### ISSUE TITLE
husky相关的配置无效

### ISSUE THREAD

**Issue by ananiy** [alibaba/ice#4255]
按照文档给的提示, 安装了最新的husky没生效

查阅相关文档后发现, husky@6之后改变了写法, 需要到.husky下面增加相关的hooks

参考: https://typicode.github.io/husky/#/?id=automatic-recommended

另外建议, 在pre-commit用lint-staged对修改的文件做lint检查

**Comment by ClarkXia** [comment]
是指官方物料？

**Comment by ananiy** [comment]
> 是指官方物料？

代码规范: https://github.com/ice-lab/spec

**Comment by ClarkXia** [comment]
可以根据最新的 husky 写法给 spec 仓库提一个 pr

**Comment by imsobear** [comment]
我理解上面说的是要改脚手架吧？

**Comment by ClarkXia** [comment]
可以都升级，按文档指引的方式配置，目前最新 husky 配置已经不是这种方式了（官方物料的 husky 版本相对比较老）。
![image](https://user-images.githubusercontent.com/4219965/115979181-0bc52600-a5b7-11eb-9475-7f4b718d0a8e.png)

**Comment by ananiy** [comment]
提供一个作者的文章作为参考:

https://blog.typicode.com/husky-git-hooks-javascript-config/

**Comment by ClarkXia** [comment]
husky 的配置和版本对应问题，暂时关闭，后续逐步升级官方仓库及模版的 husky 版本

**Comment by imsobear** [comment]
husky 升级最新版本的计划单独开 issue 讨论。
