### ISSUE TITLE
使用微前端的配置后，每次路由变化时Layout渲染的 路由组件（children）都改变了。导致路由下的所有组件都rerender

### ISSUE THREAD

**Issue by lzsheng** [alibaba/ice#4256]
[微前端配置的demo](https://github.com/lzsheng/materials/tree/master/scaffolds/ice-stark-layout) 官网demo，加了点log
[相关文件](https://github.com/lzsheng/materials/commit/05492f1bf457bf3db244607afbff5663ff857c34#diff-d424265590be23d11bda2ba0f574d6c45d6a23eb1158d9a32da8374ca37f0f55)

每次切换路由，无论是子应用还是主应用的路由，children都改变了，导致整体rerender。
![image](https://user-images.githubusercontent.com/8055289/115675205-f961a700-a380-11eb-81b5-4a329a225e87.png)

[没有配置微前端的demo](https://github.com/lzsheng/materials/tree/master/scaffolds/fusion-design-pro) 官网demo，加了点log
[相关文件](https://github.com/lzsheng/materials/commit/85e408edbf683706a9bc37d986fedabc1509dfd8)

每次切换路由，children都不会改变。
![image](https://user-images.githubusercontent.com/8055289/115675392-201fdd80-a381-11eb-8e8d-0d56b4df5545.png)

【期望】在配置了微前端时，是否可以做到跟没有配置微前端时一致，路由变化时只更新对应路由对应Route，而不是全部更新。

【具体实现】公司需要实现一个多页签（多tab）的功能，原打算使用 动态路由 + 动态加载组件 实现，无奈在配置微前端后，每次都会重新构造一个路由（上述所说的children）导致路由下的所有组件都重新刷新了

[动态路由实现多tab的demo](https://github.com/lzsheng/lzs/tree/master/react-multiTabs-demo)

**Comment by maoxiaoke** [comment]
可以考虑通过 api 的方式接入 https://ice-lab.github.io/icestark/api/core#createmicroapp

**Comment by lzsheng** [comment]
@maoxiaoke 感谢提供实现思路。
现在通过去除 ice脚手架初始化 runApp 方法的icestark相关配置，自己搭建一个基于 icestark 的微前端加载方案。大概思路：判断相关的路由匹配时，使用createmicroapp方法手动挂载微前端应用到特定的dom节点，可以实现多页签的功能。
希望官方能出一个相关的demo供有这样产品需求的同学参考

**Comment by lzsheng** [comment]
@maoxiaoke 感谢提供实现思路。
现在通过去除 ice脚手架初始化 runApp 方法的icestark相关配置，自己搭建一个基于 icestark 的微前端加载方案。大概思路：判断相关的路由匹配时，使用createmicroapp方法手动挂载微前端应用到特定的dom节点，可以实现多页签的功能。
希望官方能出一个相关的demo供有这样产品需求的同学参考

**Comment by maoxiaoke** [comment]
@lzsheng 欢迎提供 demo，我们会考虑输出到官网上~

**Comment by ClarkXia** [comment]
官方实现了一版多 tab 欢迎讨论 https://dev.g.alicdn.com/nazha/ice-multi-tabs/0.0.1/index.html?spm=defwork.iteration_detail.0.0.3f0c3119WpS33i

**Comment by lzsheng** [comment]
> 官方实现了一版多 tab 欢迎讨论 https://dev.g.alicdn.com/nazha/ice-multi-tabs/0.0.1/index.html?spm=defwork.iteration_detail.0.0.3f0c3119WpS33i

@ClarkXia 请问这个是内网地址吗？ 打不开~
