### ISSUE TITLE
是不是每个 DataBinder 都只能去判断 response 的值

### ISSUE THREAD

**Issue by cjm61177** [alibaba/ice#426]
我的场景是这样的，我每次请求接口都会在http的header里面带一个token，然后去请求，根据这个请求拿到对应的response，response里面的data会有一个code 这个code是服务器端给我的业务码，如果code:123 的话，我就得跳转对应的页面。比如code:123代表token无效。此时我得跳转登录页面，那么，是不是我每写一个@DataBinder 的时候都需要单独去处理，如果我有很多页面，很多请求，是否要写很多个判断response{data:{code:123}} 去做这个逻辑。我之前是用axios的interceptors.response去做的。(第一次提问。可能描述不清晰。～～

**Comment by noyobo** [comment]
可以通过  `responseFormatter`  做处理
