### ISSUE TITLE
微前端的2个vue子应用，切换时提示Cannot redefine property: $router vue

### ISSUE THREAD

**Issue by rootsli** [alibaba/ice#4261]
1.子应用A：在index.html中引入vue-router.js，在webpack的externals中排除
2.子应用B：webpack的externals中没有排除，将vue-router.js打包到vendor中

在子应用A切换到子应用B时，会报如下脚本错误：
vendor.4d1d6faf159ddb08d42b.js:1 Uncaught TypeError: Cannot redefine property: $router
at Function.defineProperty (<anonymous>)

是不是子应用卸载时，没有卸载掉$router对象，要如何解决该问题？

**Comment by maoxiaoke** [comment]
icestark 不会主动清除 external 挂载到全局的变量，需要手动清除

**Comment by ClarkXia** [comment]
可以先确认下 B 在主应用下独立是否可以运行，最好能给到 demo 方便定位

**Comment by maoxiaoke** [comment]
https://github.com/vuejs/vue-router/blob/v3.0.1/dist/vue-router.esm.js#L2619 感觉是这里导致如果 全局 Vue 没有清除的话，会被执行两次

**Comment by rootsli** [comment]
> 可以先确认下 B 在主应用下独立是否可以运行，最好能给到 demo 方便定位

独立可以运行，或者出错后，重新刷新页面，就正常了。

**Comment by rootsli** [comment]
> icestark 不会主动清除 external 挂载到全局的变量，需要手动清除

已通过如下方式解决。
useEffect(() => {
    console.log("== app leave ==", appLeave);

    // 删除externals外挂的Vue对象
    if (window.Vue) {
      delete window.Vue;
      delete window.VueRouter;
      delete window.Vuex;
    }
  }, [appLeave]);

**Comment by imsobear** [comment]
sandbox 也可以吧？

**Comment by maoxiaoke** [comment]
@rootsli 可以开启下沙箱执行

**Comment by chencs-19950208** [comment]
开启沙箱没有用
