### ISSUE TITLE
ssr error

### ISSUE THREAD

**Issue by diandiandidi519** [alibaba/ice#4268]
![image](https://user-images.githubusercontent.com/31098442/116028913-c2460b00-a68a-11eb-91a7-0aee9f9360e5.png)

[SSR] start server render
[HMR] Waiting for update signal from WDS...
[SSR] generating html content
ERR! [SSR] generate html template error
ERR! [SSR] Server side rendering error, downgraded to client side rendering 
ERR! TypeError: Cannot set property 'type' of undefined 
[SSR] output html content
<!DOCTYPE html><html><head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge,chrome=1">
    <meta name="viewport" content="width=device-width">
    <title>icejs simple app</title>
  
    <script>
      window.__ICE_SSR_ERROR__ = "Cannot set property 'type' of undefined";
    </script></head>

  <body>
    <div id="ice-container"></div>
  

</body></html>

**Comment by luhc228** [comment]
Could you provide a demo?

**Comment by luhc228** [comment]
Does your project use the HashRouter?

**Comment by luhc228** [comment]
I found that when use BrowserRouter, it will not throw any errors. I will fix this bug in next version.
