### ISSUE TITLE
找不到 isWeChatMiniProgram

### ISSUE THREAD

**Issue by guoyunhe** [alibaba/ice#4274]
## What is the current behavior? 发生了什么？

在代码中加入 `import { EventEmitter } from 'events';` 之后，便开始报错。一开始提示 core-js 依赖缺失，手动 import core-js 之后仍然提示下面的错误，无法解决：

![image](https://user-images.githubusercontent.com/5836790/116197444-5be2ea80-a767-11eb-96b8-b54879b2a8de.png)

## Any additional comments? 相关环境信息？

- **ice.js Version**：
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by ClarkXia** [comment]
提供下 复现 demo，以及版本信息。特别关注下 universal-env 的版本

**Comment by guoyunhe** [comment]
改为 `eventemitter3` 之后就没有这个问题了，eventemitter3是纯 js 的，不依赖 polyfill
