### ISSUE TITLE
addProvider 在 ie11 下报错

### ISSUE THREAD

**Issue by maoxiaoke** [alibaba/ice#4276]
## What is the current behavior? 发生了什么？
添加 appProvider 如下：

```js
import { ConfigProvider } from '@alifd/next';
const appConfig: IAppConfig = {
  app: {
    rootId: 'ice-container',
    addProvider: ({ children }) => (
      <ConfigProvider prefix="next-icestark-">{children}</ConfigProvider>
    ),
  }
};

runApp(appConfig)
```

构建产物 ConfigProvider 的引入顺序在 polyfill 之前，导致 ie11 下运行失败

![image](https://user-images.githubusercontent.com/13417006/116337492-c7cb5e80-a80c-11eb-886e-f3d67589307e.png)

**Comment by maoxiaoke** [comment]
更多细节：移除 build-plugin-fusion（即 babel-plugin-import）引入顺序是正确的

![image](https://user-images.githubusercontent.com/13417006/116340577-f992f400-a811-11eb-9479-330ca5850cf3.png)

**Comment by ClarkXia** [comment]
## 问题分析

build-plugin-fusion 插件中的 babel-plugin-import 后按需加载 next 组件，babel-plugin-import 中将通过 `@babel/helper-module-imports` 重新注入解析后的 import 语句，[参考代码](https://github.com/ant-design/babel-plugin-import/blob/master/src/Plugin.js#L76)，从而导致 next 组件加载先于 core-js 加载

## 修复方案

基于上述错误可以有两种方案修复：
- 方案一：单独增加 entry 入口，用于 core-js 加载
- 方案二：通过 babel 插件确保 core-js 加载顺序

方案一修改由于修改了默认 entry 逻辑，对于现有逻辑影响面相对较大，因此采用方案二的方式确保加载顺序更加合理

**Comment by maoxiaoke** [comment]
> ## 问题分析
> build-plugin-fusion 插件中的 babel-plugin-import 后按需加载 next 组件，babel-plugin-import 中将通过 `@babel/helper-module-imports` 重新注入解析后的 import 语句，[参考代码](https://github.com/ant-design/babel-plugin-import/blob/master/src/Plugin.js#L76)，注入代码在文件头部，从而导致 next 组件加载先于 core-js 加载
> 
> ## 修复方案
> 基于上述错误可以有两种方案修复：
> 
> * 方案一：单独增加 entry 入口，用于 core-js 加载
> * 方案二：通过 babel 插件确保 core-js 加载顺序
> 
> 方案一修改由于修改了默认 entry 逻辑，对于现有逻辑影响面相对较大，因此采用方案二的方式确保加载顺序更加合理

方案三：修复 babel-plugin-import 的 bug ?
