### ISSUE TITLE
ice.js升级报错

### ISSUE THREAD

**Issue by crawler-django** [alibaba/ice#4278]
![image](https://user-images.githubusercontent.com/37062307/116357142-bbf09400-a82e-11eb-8221-514707660b76.png)

我现在使用的ice是1.14.0, 想升级到1.17.6。 但是运行就报错了

**Comment by crawler-django** [comment]
一开始直接升级是报错Error: Cannot find module 'node-sass'.
然后我装上与我node12对应的node-sass@4.12.0版本. 就报了上面的错误.

**Comment by ClarkXia** [comment]
升级不要仅执行 npm install ice.js，建议删除 node_modules 所有依赖重装下

**Comment by crawler-django** [comment]
清掉了node_modules, 再重新yarn install了还是一样报上面的错误.

**Comment by crawler-django** [comment]
可以了, 清掉node_modules 和 对应的lock, 然后重装就可以了
