### ISSUE TITLE
shouldAssetsRemove 配置不生效

### ISSUE THREAD

**Issue by joshualzb** [alibaba/ice#4281]
const appConfig = {
  app: {
    rootId: 'icestark-container',
    addProvider: ({children}) => (
      <ConfigProvider prefix="next-icestark-">{children}</ConfigProvider>
    ),
  },
  router: {
    type: 'browser',
  },
  // 引入在service/index.ts里面的请求config
  request: requestConfig,
  icestark: {
    // 指定此为框架程序
    type: 'framework',
    // 指定框架程序的layout
    Layout: FrameworkLayout,
    // 获取子工程的配置信息
    getApps: AppManager.getApps,
    appRouter: {
      LoadingComponent: PageLoading,
      shouldAssetsRemove: () => {
        console.log('判断资源是否卸载,走不到这里');
        return false;
      },
    },
  },
};

// @ts-ignore
runApp(appConfig);

**Comment by maoxiaoke** [comment]
build-plugin-icestark 的版本是多少？

**Comment by joshualzb** [comment]
> build-plugin-icestark 的版本是多少？

  "dependencies": {
    "@alifd/next": "^1.22.11",
    "@alifd/theme-design-pro": "^0.6.3",
    "@icedesign/container": "^1.0.5",
    "@antv/data-set": "^0.11.8",
    "@types/react": "^16.9.20",
    "@types/react-dom": "^16.9.5",
    "bizcharts": "^4.1.7",
    "classnames": "^2.2.5",
    "moment": "^2.24.0",
    "prop-types": "^15.5.8",
    "react": "^16.8.0",
    "react-dom": "^16.8.0"
  },
  "devDependencies": {
    "@ice/spec": "^1.0.1",
    "@ice/stark": "^2.2.1",
    "@ice/stark-data": "^0.1.2",
    "build-plugin-fusion": "^0.1.0",
    **"build-plugin-icestark": "^2.0.6",**
    "build-plugin-moment-locales": "^0.1.0",
    "eslint": "^6.0.1",
    "ice.js": "^1.16.1",
    "node-sass": "^4.14.1",
    "stylelint": "^13.1.0"
  },

**Comment by maoxiaoke** [comment]
@joshualzb  提供下可复现的 demo，官方 demo 无法复现

**Comment by joshualzb** [comment]
> @joshualzb 提供下可复现的 demo，官方 demo 无法复现

我现在去准备demo，顺便说一下，我要解决的问题是，主应用开了按需加载，刷新后样式丢失（在页面级别index.module.scss中定义的:global样式丢失了）。

我看官网说是用 shouldAssetsRemove 解决，才引发这个问题。如果样式丢失可以有其他解决方案，我这个问题就不会管了。

**Comment by joshualzb** [comment]
放弃shouldAssetsRemove了

**Comment by imsobear** [comment]
> 问题。如果样式丢失可以

你说的问题跟 shouldAssetsRemove 没有关系，你这个问题无解，属于不合理的写法。
