### ISSUE TITLE
[讨论]如何解决Message组件在切换子应用时不会自己消失

### ISSUE THREAD

**Issue by xmsz** [alibaba/ice#4282]
步骤
- 子应用A，调用Message显示，然后倒计时时间是2s(无所谓)
- 2s以内马上切换到子应用B

表现
- Message组件不会消失

期望
- Messsage还是会自行消失

**Comment by ClarkXia** [comment]
Message组件渲染的位置默认在 body 的阶段，子应用切换后删除结构不会移除，推荐在组件销毁阶段 通过 `Message.destory()` 的方式销毁

**Comment by xmsz** [comment]
> 推荐在组件销毁阶段 通过 `Message.destory()` 的方式销毁

这个是什么意思哈

我现在有两个思路

1. 子应用卸载时，直接调用 `Message.destory()` 。但是缺点就是倒计时相当于没用了（一切页面就消失，用户可能内容都看不到）
2. 子应用调用父应用的Message，可以解决问题，但是太麻烦了

**Comment by ClarkXia** [comment]
推荐第一种思路，子应用卸载的时候本来就应该销毁应该产生的副作用

**Comment by maoxiaoke** [comment]
@xmsz 你这边使用的是 fusion 的 message，还是 antd 的 message ?

**Comment by ClarkXia** [comment]
如果是 fusion 组件，可以控制 Message.hide 调用；如果是 antd 组件，调用 message.destroy()
子应用的副作用建议由子应用中处理，如果主应用需要根据子应用切换来控制 message 逻辑，建议实现在对应的生命周期中（比如 onAppEnter / onAppLeave）
