### ISSUE TITLE
build-plugin-fusion组件使用css-variable时时使用next-prefix不生效

### ISSUE THREAD

**Issue by fengxs269** [alibaba/ice#4284]
## What is the current behavior? 发生了什么？

项目中使用build-plugin-fusion组件时使用css-variable功能后next-prefix不生效

## What is the expected behavior? 期望的结果是什么？

使用css-variable时，也能使用next-prefix, ps: next-prefix最好能替换工程中的next-前缀&且提供单行忽略的语法

## Any additional comments? 相关环境信息？

- **ice.js Version**：无
- **build.json Configuration**：
``` json
{
  "entry": "src/index.js",
  "publicPath": "./",
  "alias": { 
    "@": "./src/" 
  },
  "devServer": {
    "allowedHosts": [
      "test.import.tmall.com",
      "test.import.tmall.net"
    ],
    "historyApiFallback": true,
    "https": true,
    "http2": true,
    "open": true,
    "openPage": "https://test.import.tmall.com:3333",
    "public": "test.import.tmall.com:3333",
    "port": "3333"
  },
  "plugins": [
    "build-plugin-react-app",
    "@ali/build-plugin-ice-def",
    ["build-plugin-fusion", {
      "themeConfig": {
        "css-prefix": "next-"
      },
      "nextPrefix": "next-",
      "cssVariable": true
    }]
  ]
}
```
- **Node Version**: v10.20.1
- **Platform**: mac
ps: 已在内部研发小蜜中沟通

**Comment by ClarkXia** [comment]
开启 `cssVariable` 配置后，fusion 组件的默认样式引入将会变成 css 文件，即缺少 sass 等预编译工具的变量逻辑来处理 `css-prefix`，[css 文件](https://unpkg.alibaba-inc.com/browse/@alifd/next@1.22.24/es/button/index.css)  vs [sass 文件](https://unpkg.alibaba-inc.com/browse/@alifd/next@1.22.24/es/button/main.scss)

> `cssVariable` 主要用于多主题场景，相比于原先基于 sass 多主题能力，处理可以定制主题颜色同时一些尺寸和文字大小均支持。

可以描述下修改 `css-prefix` 的业务场景
