### ISSUE TITLE
iceworks npm or yarn 出现错误，pngquant failed to build, make sure that libpng-dev is installed

### ISSUE THREAD

**Issue by liqupan** [alibaba/ice#4293]
## What is the current behavior? 发生了什么？

iceworks npm or yarn 出现错误，pngquant failed to build, make sure that libpng-dev is installed

![image](https://user-images.githubusercontent.com/21078925/117601863-e113c980-b181-11eb-9950-ebb53c125b8f.png)

## What is the expected behavior? 期望的结果是什么？

正常install 

## Any additional comments? 相关环境信息？

- **ice.js Version**：3.4.3
- **Node Version**:v14.16.0
- **npm Version**:7.6.3

**Comment by ClarkXia** [comment]
具体执行的什么命令？

**Comment by imsobear** [comment]
长时间未回复先关闭了，有问题自行 reopen 下。
