### ISSUE TITLE
iceworks物料开发，物料下载超时，需要手动下载物料问题

### ISSUE THREAD

**Issue by liqupan** [alibaba/ice#4296]
## What is the current behavior? 发生了什么？

问题描述： 现在在尝试自己开发物料，物料大小是1.06MB，提示我物料下载超时，需要手动下载物料，请问是因为物料包太大了吗？

![image](https://user-images.githubusercontent.com/21078925/117745139-825f5600-b23c-11eb-8574-0d502352cca0.png)

## What is the expected behavior? 期望的结果是什么？
成功下载物料配置页面

**Comment by liqupan** [comment]
昨天发现的问题，今天莫名其妙解决了，可能是网络的原因

**Comment by imsobear** [comment]
可以检查下 npm 源设置的是什么。

@luhc228 这种情况哪里能看到日志？
