### ISSUE TITLE
iceworks add component初始化的组件npm start报错

### ISSUE THREAD

**Issue by rootsli** [alibaba/ice#4297]
1.node -v    
v14.15.4

iceworks -V
3.4.3

2.初始化物料：
$ cd my-materials
$ iceworks add component

3.设置npm源为taobao源，npm install 然后npm start,报如下错误：

![image](https://user-images.githubusercontent.com/4099803/117754532-1802e180-b24d-11eb-993a-5636d743d4be.png)

**Comment by ClarkXia** [comment]
社区 caniuse-lite 发包问题，npm update 下
