### ISSUE TITLE
build-plugin-antd如何配置多主题

### ISSUE THREAD

**Issue by curry-wxj** [alibaba/ice#4301]
如何向fusion一样可以配置多主题

**Comment by ClarkXia** [comment]
方案目前在设计，参见 https://github.com/alibaba/ice/issues/4223

**Comment by imsobear** [comment]
受限于 antd 的设计问题目前还不支持，最近在开发 icejs 2.0 版本，梳理了通用的多主题方案：https://github.com/alibaba/ice/issues/4223#issuecomment-838102445

**Comment by curry-wxj** [comment]
icejs 2.0 预计什么时候发布呢～ 发布后 就可以支持 多主题了对吧。
 现在有没有其他方案切换不同主题呢～ 比如 ice-scripts 2.0 通过环境变量判断， 在ice.config.js 进行不同的配置。

**Comment by haoxiaoshu6** [comment]
你的单主题能生效？我的被覆盖了

**Comment by imsobear** [comment]
> 你的单主题能生效？我的被覆盖了

被谁覆盖了？看下你是不是哪里直接引了 antd 相关的 css。
