### ISSUE TITLE
generate materials data progress: 0/4time 字段不存在

### ISSUE THREAD

**Issue by frontHu** [alibaba/ice#4304]
iceworks CLI: 3.4.3

wn-title的package.json字段如下：
{
  "name": "@winexmaterial-components/tag",
  "version": "1.0.4",
  "description": "",
  "main": "./lib/index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "componentConfig": {
    "name": "wn-tag",
    "title": "标签组件"
  }
}

**Comment by imsobear** [comment]
执行 `LOG_LEVEL=verbose iceworks generate` 看下输出

![image](https://user-images.githubusercontent.com/2505411/118089124-99e43d80-b3fa-11eb-857c-e15b89a18828.png)

**Comment by frontHu** [comment]
> LOG_LEVEL=verbose iceworks generate

图片发不上去，不好意思，就直接复制过来了。

huzhiwei@huzhiweideMacBook-Pro winning-webblock-common % LOG_LEVEL=verbose iceworks generate
iceworks CLI: 3.4.3
info Generate: generating materials data，total: 4，concurrency: 30
⠋ generate materials data progress: 0/4verb getNpmRegistry http://172.16.9.242:8081/#browse/browse:npm-group
verb getNpmPublishTime http://172.16.9.242:8081#browse/browse:npm-group/@winexmaterial-components/title
verb getNpmRegistry http://172.16.9.242:8081/#browse/browse:npm-group
verb getNpmPublishTime http://172.16.9.242:8081#browse/browse:npm-group/@winexmaterial-scaffolds/vue3.x-html
verb getNpmRegistry http://172.16.9.242:8081/#browse/browse:npm-group
verb getNpmPublishTime http://172.16.9.242:8081#browse/browse:npm-group/@winexmaterial-components/tag
verb getNpmRegistry http://172.16.9.242:8081/#browse/browse:npm-group
verb getNpmPublishTime http://172.16.9.242:8081#browse/browse:npm-group/@winexmaterial-scaffolds/vue2.x-html
⠙ generate materials data progress: 0/4time 字段不存在
✖ materials data generate failed!
ERR! iceworks generate error @winexmaterial-components/title@1.0.5 time 字段不存在
Error: @winexmaterial-components/title@1.0.5 time 字段不存在
    at /usr/local/lib/node_modules/iceworks/lib/command/generate/generateMaterialData.js:141:35
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
huzhiwei@huzhiweideMacBook-Pro winning-webblock-common %

**Comment by imsobear** [comment]
私有 npm 源，看起来是你们这个源返回的信息不全导致的，可以对比下官方的源：http://registry.npmjs.org/ice.js

![image](https://user-images.githubusercontent.com/2505411/118092206-60adcc80-b3fe-11eb-842d-7c5511521e31.png)

**Comment by frontHu** [comment]
> 私有 npm 源，看起来是你们这个源返回的信息不全导致的，可以对比下官方的源：http://registry.npmjs.org/ice.js
> 
> ![image](https://user-images.githubusercontent.com/2505411/118092206-60adcc80-b3fe-11eb-842d-7c5511521e31.png)

好的，谢谢大佬

**Comment by frontHu** [comment]
找到问题
