### ISSUE TITLE
Fusion主题配置，Dialog对话会“确定按钮位置”项修改后保存不生效

### ISSUE THREAD

**Issue by rootsli** [alibaba/ice#4310]
如下图：

![image](https://user-images.githubusercontent.com/4099803/118210978-e765b680-b49d-11eb-9dab-da44fb5564ae.png)

**Comment by ClarkXia** [comment]
@youluna 帮忙看下

**Comment by rootsli** [comment]
@imsobear @youluna 主题配置那边好像看不到：Notification 通知 这个组件的配置项啊

**Comment by youluna** [comment]
这里只是配置时的状态预览，不会保存的。

Notification底层依赖Message的样式，配置Message就可以
