### ISSUE TITLE
状态管理 createStore undefined

### ISSUE THREAD

**Issue by liqupan** [alibaba/ice#4317]
我引入createStore 发现报错了，然后打印了一下ice，发现里面没有createStore

**Comment by luhc228** [comment]
有可复现的 demo 或者代码吗？

**Comment by liqupan** [comment]
> 有可复现的 demo 或者代码吗？

// src/store.ts
import { createStore } from 'ice';
import user from './models/user';
console.log(createStore);
const store = createStore({
  user,
}, {
  // options
});

export default store;
我就按照官方的状态管理去引入，这个console的内容是undefined,然后页面就报错了

**Comment by liqupan** [comment]
> 有可复现的 demo 或者代码吗？

TypeError: Object(...) is not a function
Module../src/store.ts
.@icedesign/stark-child-scaffold/src/store.ts:5
  2 | import { createStore } from 'ice';
  3 | import user from './models/user';
  4 | console.log(createStore);
> 5 | const store = createStore({
  6 |   user,
  7 | }, {
  8 |   // options
