### ISSUE TITLE
CSS 构建时静态资源本地化兼容 url 中无协议类型

### ISSUE THREAD

**Issue by luhc228** [alibaba/ice#4321]
### 背景

使用 DynamicIcon 编写自定义 Icon 组件：
```js
import DynamicIcon from '@icedesign/dynamic-icon';

const Icon = DynamicIcon.create({
  fontFamily: 'toolkit',
  prefix: 'toolkit',
  // 这里没有写 http/ https 协议类型
  css: '//at.alicdn.com/t/font_2523538_197e6ww3p0bh.css',
});

export default Icon;
```

打包构建时使用 `build-plugin-css-assets-local` 将 CSS 资源本地化，运行的时候报错找不到对应网络资源，同时对应的 CSS 资源也没有打包到本地。

![image](https://user-images.githubusercontent.com/44047106/118590403-f5d10c80-b7d4-11eb-8132-4b7478347028.png)

### 期望
兼容 CDN url 中没有写协议类型，或者打包构建时直接抛出错误。

**Comment by ClarkXia** [comment]
build-plugin-css-assets-local 目前应该只做了针对 css 文件的解析
