### ISSUE TITLE
Pro 模板启动失败

### ISSUE THREAD

**Issue by zh-D** [alibaba/ice#4327]
## What is the current behavior? 发生了什么？
npm init ice my-app
select “Pro TypeScript template”
cd my-app
npm install
npm start

**启动信息：**
![image](https://user-images.githubusercontent.com/61453507/118777417-9d286f00-b8bb-11eb-8d09-452c0796583a.png)

![image](https://user-images.githubusercontent.com/61453507/118777611-d3fe8500-b8bb-11eb-867a-ca7ba7fbaa71.png)

lite 模板可以跑

## Any additional comments? 相关环境信息？

- **ice.js Version**：1.17.8
- **build.json Configuration**：
- **Node Version**:12.16.3
- **Platform**:win10

**Comment by ClarkXia** [comment]
mac 下暂时无法复现

试下 build.json 中移除  remoteRuntime，项目是否可以正常执行
```diff
[
  "build-plugin-webpack5",
-  {
-    "remoteRuntime": true
-  }
]
```

**Comment by zh-D** [comment]
不行
![image](https://user-images.githubusercontent.com/61453507/118782075-4cffdb80-b8c0-11eb-8830-3d96bd2f3584.png)

**Comment by ClarkXia** [comment]
清空下 node_modules/.cache 目录

**Comment by zh-D** [comment]
清空之后可以跑了

**Comment by ClarkXia** [comment]
> 清空之后可以跑了

已定位 window 下问题，我们修复下

**Comment by zh-D** [comment]
感谢~

**Comment by ClarkXia** [comment]
build-plugin-webpack5 更新 1.2.5 版本
