### ISSUE TITLE
什么时候可以支持 TypeScript ？

### ISSUE THREAD

**Issue by nick-ma** [alibaba/ice#433]
团地作战还是强类型的比较靠谱，请问ice的组件什么时候可以出一版 d.ts 文件，然后我们可以在typescript项目里用上呢？

**Comment by noyobo** [comment]
近期暂无计划, 后续有进度再同步出来

**Comment by imsobear** [comment]
https://alibaba.github.io/ice/docs/advanced/how-to-use-typescript 已支持

**Comment by cca313** [comment]
> https://alibaba.github.io/ice/docs/advanced/how-to-use-typescript 已支持

页面打不开啊 @imsobear

**Comment by imsobear** [comment]
https://ice.work/docs/cli/basic/typescript @cca313 文档结构做了一些调整
