### ISSUE TITLE
Module '"universal-env"' has no exported member "XXX"

### ISSUE THREAD

**Issue by caoyi5225** [alibaba/ice#4333]
## What is the current behavior? 发生了什么？

升级ice.js到1.18.0后，启动应用报错
![image](https://user-images.githubusercontent.com/21326015/119083122-f61a1380-ba31-11eb-8dd4-aaf9d25d5524.png)

## What is the expected behavior? 期望的结果是什么？
正常启动
## Any additional comments? 相关环境信息？

- **ice.js Version**：1.18.0
- **build.json Configuration**：
```json
{
  "tsChecker": true,
  "hash": true,
  "plugins": [
    [
      "build-plugin-fusion",
      {
        "themePackage": "@alifd/theme-16139"
      }
    ],
    [
      "build-plugin-moment-locales",
      {
        "locales": [
          "zh-cn"
        ]
      }
    ]
  ]
}
```
- **Node Version**: v14.15.0
- **Platform**: macos

**Comment by ClarkXia** [comment]
删除依赖重新安装，独立 npm install ice.js  会导致部分依赖没更新
