### ISSUE TITLE
iceworks插件页面不显示

### ISSUE THREAD

**Issue by 15036658799** [alibaba/ice#4335]
显示快速入口、页面列表、组件列表三个下拉菜单。点开都是显示未找到。请问遇到这种情况该怎么解决？

**Comment by luhc228** [comment]
如果是打开 rax 项目或者 ice 项目会有显示相应的内容吗？

**Comment by 15036658799** [comment]
> 如果是打开rax项目或者ice项目会有显示相应的内容吗？

资源管理器打开了，Rax App[https://github.com/raxjs/rax-app](url)没有运行，iceworks没有相应内容显示。

**Comment by luhc228** [comment]
![image](https://user-images.githubusercontent.com/44047106/119326821-e6f6c800-bcb4-11eb-8542-80dccb31b387.png)

我这边都是 OK 的。尝试下把插件更新到最新版本。

**Comment by 15036658799** [comment]
> ![图像](https://user-images.githubusercontent.com/44047106/119326821-e6f6c800-bcb4-11eb-8542-80dccb31b387.png)
> 
> 我这边都是OK的。尝试下把插件更新到最新版本。

版本号是：0.19.0  可以通过CLI命令创建项目，iceworks没有显示相应的东西。我的另一台windows系统的电脑可以正常使用。

**Comment by 15036658799** [comment]
> ![图像](https://user-images.githubusercontent.com/44047106/119326821-e6f6c800-bcb4-11eb-8542-80dccb31b387.png)
> 
> 我这边都是OK的。尝试下把插件更新到最新版本。

版本号是：0.19.0  可以通过CLI命令创建项目，iceworks没有显示相应的东西。我的另一台windows系统的电脑可以正常使用。

**Comment by 15036658799** [comment]
> > ![图像](https://user-images.githubusercontent.com/44047106/119326821-e6f6c800-bcb4-11eb-8542-80dccb31b387.png)
> > 我这边都是OK的。尝试下把插件更新到最新版本。
> 
> 版本号是：0.19.0 可以通过CLI命令创建项目，iceworks没有显示相应的东西。我的另一台windows系统的电脑可以正常使用。

macOS Catalina 版本 10.15.7  Vscode 版本 1.56

**Comment by luhc228** [comment]
> macOS Catalina 版本 10.15.7 Vscode 版本 1.56

提供下项目 demo 和现在的 Iceworks 插件的截图
