### ISSUE TITLE
使用lazy分包路由后，使用formilyjs 配置形式加载number picker 组件出现样式问题

### ISSUE THREAD

**Issue by MarshalShan** [alibaba/ice#4337]
## What is the current behavior? 发生了什么？
工程使用了 Ice 提供的lazy的加载机制同时将不同的路由分开打包，系统中其中一个路由使用了formilyjs 配置并展示number picker
此时页面渲染后出现样式丢失的情况。

### 正常的情况下 ”.next-number-picker“是能够看到对应的样式表的
![image](https://user-images.githubusercontent.com/10287829/119453929-84f89a00-bd6a-11eb-8cee-4c4d1e206ac0.png)
### 异常的情况下”.next-number-picker"的样式从样式表中无法找到
![image](https://user-images.githubusercontent.com/10287829/119454313-00f2e200-bd6b-11eb-97ac-d232f29ebcac.png)

## What is the expected behavior? 期望的结果是什么？
1. 期望官方看一下是否为分包加载的一个缺陷，或者是其他的原因导致的。
2. 当前识别出来的formilyjs 中的number picker 是有问题的是否其他组件也会出现同类问题。
## Any additional comments? 相关环境信息？

- **ice.js Version**：1.14.1
- ** formilyjs**：1.3.17
- **build.json Configuration**：
- **Node Version**: v10.16.0
- **Platform**:

**Comment by imsobear** [comment]
补充下代码怎么写的

**Comment by MarshalShan** [comment]
通过官方给出https://ice.work/docs/guide/develop/plugin-list#plugin-modular-import的插件进行尝试当前来看如果使用了formlly提供的setup方法的情况下会出现编译报错，主要原因是因为插件是在查找使用的组件上面增加style的样式引用，当调用到了setup方法时它本身没有对应的样式stylejs所以引发了报错

**Comment by imsobear** [comment]
不建议从 components 里导出 setup 使用。

![image](https://user-images.githubusercontent.com/2505411/119595020-70221200-be0f-11eb-8ddc-351cb785f983.png)

**Comment by MarshalShan** [comment]
经过这几天的尝试发现新的问题：
![image](https://user-images.githubusercontent.com/10287829/119759382-bc865400-beda-11eb-81d5-f8ebec196b30.png)
在build配置这段代码后可以将对应的样式引入到工程中，同时发现自己在站点定义的样式被pages级别的样式覆盖了这样主题包中的样式则不再生效。不知道这是不是一个缺陷
