### ISSUE TITLE
切换菜单，离开微应用路由，再切换回来，样式未加载。

### ISSUE THREAD

**Issue by springot** [alibaba/ice#4341]
主应用路由离开微应用页面，进去其他路由，再切换回微应用路由，微应用样式未加载

**Comment by ClarkXia** [comment]
提供下简单的 demo 和代码

**Comment by springot** [comment]
首次进入微应用路由，样式正常
![image](https://user-images.githubusercontent.com/26103913/119772944-86ed6500-bef2-11eb-83be-0e6802fa9345.png)
离开路由，再次进入，onAppEnter函数中，status是UNMOUNTED，样式未加载。
![image](https://user-images.githubusercontent.com/26103913/119773346-12ff8c80-bef3-11eb-8fcf-5a76dd3c9d22.png)
![image](https://user-images.githubusercontent.com/26103913/119773345-12ff8c80-bef3-11eb-8d44-e43c55438f99.png)

**Comment by maoxiaoke** [comment]
@springbot 贴一下主应用配置微应用的代码，或提供一个 demo

**Comment by springot** [comment]
demo, stark-demo-main是主应用，stark-demo-child是微应用。链接: https://pan.baidu.com/s/1NEyYCHg94e15V_z1dKDDCQ  密码: el96

**Comment by maoxiaoke** [comment]
@springot 可否提供上传至 github

**Comment by springot** [comment]
问题已解决，是微应用使用的ant design 样式覆盖了主应用的，已经好了
