### ISSUE TITLE
开启SSR，build失败，找不到core-js

### ISSUE THREAD

**Issue by kchjxxgh** [alibaba/ice#4342]
## What is the current behavior? 发生了什么？
在build.json里面开启了SSR之后，构建失败

![image](https://user-images.githubusercontent.com/19234718/119759994-cf4d5880-bedb-11eb-8a9a-0693c7a254fa.png)

## Any additional comments? 相关环境信息？

- **ice.js Version**：1.18
- **build.json Configuration**：
`{
  "plugins": [
    [
      "build-plugin-fusion",
      {
        "themePackage": "@alifd/theme-design-pro"
      }
    ],
    [
      "build-plugin-moment-locales",
      {
        "locales": [
          "zh-cn"
        ]
      }
    ]
  ],
  "ssr": true
}`
- **Node Version**: 14.15.4
- **Platform**: Windows 10

**Comment by ClarkXia** [comment]
icejs 针对 csr 渲染会锁定 core-js 的加载版本，目前 ssr 链路上并没有生效，下个版本将修复。
临时解决方案：在项目 package.json 中增加 core-js 3.x 版本的依赖即可

**Comment by kchjxxgh** [comment]
> icejs 针对 csr 渲染会锁定 core-js 的加载版本，目前 ssr 链路上并没有生效，下个版本将修复。
> 临时解决方案：在项目 package.json 中增加 core-js 3.x 版本的依赖即可

加上 core-js 3.x 解决了，多谢！

**Comment by mopsky** [comment]
mpa是不是不能开启ssr，有报错：
ERR! (ssr) ./.ice/server.ts
ERR! Module not found: Can't resolve '@/app'

**Comment by mopsky** [comment]
@ClarkXia 
mpa是不是不能开启ssr，有报错：
ERR! (ssr) ./.ice/server.ts
ERR! Module not found: Can't resolve '@/app'

**Comment by imsobear** [comment]
@mopsky MPA 的确没支持 SSR，有需求的话可以单独提一个 issue 哈
