### ISSUE TITLE
[RFC] SPA 应用支持 pwa 能力

### ISSUE THREAD

**Issue by maoxiaoke** [alibaba/ice#4343]
# 背景

为了突破 Web 应用的体验瓶颈，Google 提出 PWA 应用架构，其核心为
+ Web App Manifest  - 用于生成桌面图标
+ Service Worker - 提供预缓存、动态缓存，可用于离线访问
+ Push API & Notification API - 用于离线通知
+ App Shell - 骨架屏

其中 Service Worker 可用于提升应用的加载性能。[这篇文章](https://unused-css.com/blog/are-service-workers-faster-than-the-browser-cache/) 对比了 HTTP cache 和 Service worker。相比较而言，使用了 Service Worker 的 time-to-first-byte 的时间更长，页面的整体加载时间反而有所改善。

在使用 Service Worker 的应用中，浏览器会按照如下的顺序获取缓存：

1. Service worker cache：通过 Service worker 的 caching strategies 来决定是否使用缓存或请求新资源。
2. HTTP cache 
3. Server-Side

![image](https://user-images.githubusercontent.com/13417006/121131782-d6bd1c00-c862-11eb-9dfd-3e82b82301d9.png)

下面是 Service  Worker 一些的背景：

### 作用域

Service Worker 的作用域是 Service Worker 可控的页面范围。比如某一 Service Worker 的作用域为 https://xxx/a 则该目录下的所有页面的资源请求和网络请求，都可以通过该 Service Worker 来处理。

由于 Service Worker 存在作用域的情况，就会导致 **存在多个 Service Worker 控制一个页面的情况，这就称为作用域污染**。

#### SPA

SPA 架构通常只有一个 index.html 的入口，一般维护单个 Service Workder, 将 `sw.js` 直接放在站点的根目录，保证整个作用域可控制。

#### MPA

可以根据业务形态来选择注册单个还是多个 Service Worker。比如小型的业务，每个页面之间的公共的资源或请求较多，或许就适合在所有页面注册一个 Service Worker。如果是针对大型的中后台项目，各独立业务通过 path 来进行拆分，或许就可以拆分多个 Service Worker，每个 path 维护各自的 Service Worker。

维护多个 ServiceWorker 会增加复杂性，主要表现在：

- 需要严格管理自己域的 `sw.js` 和作用域，防止对其他域的页面造成影响

#### 更新

当网站资源被缓存后（AppShell 的静态资源被缓存，也就是入口 `index.html`、js 资源），应用进行了功能升级，如何将最新的页面展示给用户呢。

在通过 `navigator.serviceWorker.register()` 注册 Service Worker 的时候，浏览器会 **异步** 检测 sw.js 的更新。算法如下：

- Service Worker 文件 URL 的更新
- Service Worker 文件内容的更新

因此有两种常见的应用更新策略：

1. 每次构建出不同路径的产物，比如携带版本号、添加 hash 后缀的方式

在这种设计中，由于入口 `index.html` 被缓存，因此 index.html 需要采用 Network First 的策略，保证可以获取到最新的。

2. 每次构建修改 `sw.js` 的内容，比如添加一个唯一的版本号

```jsx
// sw.js
self.version = 'xxxxx'
```

这种设计通常针对覆盖式资源发布。当检测到新的 Service Worker 时，由新的 Service Worker 接管页面。

与前者比较，有以下几点需要考虑：

1. 前者由于入口 `index.html` 采用 Network First 策略，在页面的加载速度上略输于后者；
2. 后者由于缓存了入口文件，页面无法得到及时更新，需要关闭页面或刷新页面才可以获取最新内容；
3. 由于同一页面被不同 Service Worker 接管，可能会产生不一致问题。

###  缓存策略

常见的缓存策略有以下几种：

1. Cache First

该策略会优先从本地缓存读取资源，读取失败或资源过期则发起网络请求。对于实时性要求不太高的资源，使用该策略可以大幅提高加载速度。

2. Network First

该策略优先尝试通过网络请求获取资源，并进行缓存。当请求失败时，再尝试从本地缓存中读取缓存资源。一般适用于对请求的实时性有一定要求的场景。

3. Network Only

发送正常请求，直接将结果返回。适用于实时性非常高的资源。

4. Cache Only

仅从缓存中读取资源。

5. Stale While Revalidate

该策略会优先返回本地缓存资源，不同 Cache First 策略的地方在于，Stale While Revalidate 策略无论在缓存是否读取成功的时候都会发送请求，并更新缓存。

### 预缓存方案

根据资源的动态性，可将应用所依赖的资源笼统地分为：

- 静态资源：比如 js、css、字体文件、静态加载的图片等
- 动态资源：比如接口返回的数据，动态加载的图片等

因此，针对应用静态资源，在项目构建阶段就可以确定下来。这些资源不会频繁变化，内容和数量是可控的。这些资源可以进行预缓存，并通过 Cache First 策略进行缓存。

#### 资源的加载和缓存

为了让静态资源在 Service Worker 安装完成时已缓存完毕，可以将资源加载和缓存的过程放在 `install` 事件中进行。

由于 install 阶段，旧的 Service Worker 还在工作，因此对于同名文件的加载，避免覆盖具有相同路径的旧资源。通常解决方案有以下两种：

1. 使用不同 cacheName 进行存储

这个方法可以完美地解决重名问题，新旧的资源相互隔离，全部资源都需要进行加载和缓存。

缺点：没有发生变化的资源，这部分资源的加载其实是没有必要的。

2. 确保资源部重名

借助工程构建，可以保证资源不同名。另外是可以通过增加 revision 参数来标识文件是否发生变化。

### workbox 介绍

Workbox 是一套管理 Service Worker 的解决方案。主要能力有：

- 封装的预缓存能力
- 封装的动态缓存能力
- 提供多种缓存策略

### 预缓存能力

`work.precaching` 提供了常用的预缓存能力，将传入的资源列表进行缓存。

```jsx
workbox.routing.precacheAndRoute([
 { url: '/index.html', revision: '20110608' }
])
```

### 动态缓存能力

workbox 对资源请求匹配和对应的缓存策略执行进行了统一管理，采用路由注册的组织形式，并依此规范化动态缓存。例如：

```jsx
workbox.routing.registerRoute(/\.(jep?g|png)/, new workbox.strategies.NetworkFirst(
	plugins: [
    new workbox.expiration.Plugin({
     // 缓存时间
     maxAgeSeconds: 7 * 24 * 60 * 60,
     
     // 最多的缓存数量
     maxEntries: 10
   })
  ]
))
```

workbox 提供一些功能强大的插件来强化缓存策略，上面就是使用了 expiration 插件来实现对图片资源的过期管理。

对于 webpack 用户，提供了 [GenerateSW Plugin](https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin#generatesw_plugin) 和 [InjectManifest]() 两个插件来实现预缓存和动态缓存能力。两者的区别如下：

| 对比项   |  GenerateSW | InjectManifest |
|  ----  | ----  | ---- |
| Prechaing | ✅   | ✅   |
| Runtime caching  |  ✅  |  ✅  |
| 自定义 Service Worker（更多的自由权）|  ❌  | ✅ |
| Web Push | ❌  | ✅ |

# 概述

本方案使用 workbox 提供的动态缓存和预缓存能力，结合官方提供的 [work-webpack-plugin](https://developers.google.com/web/tools/workbox/guides/generate-service-worker/webpack) 支持 ice SPA 应用的资源缓存能力。

### 内置缓存策略

- document：Network First
- fonts: Cache First
- CSS/JS 资源： Stale While Revalidate
- 图片资源：Cache First
- 其他：Network First

### Service Worker 更新策略

默认行为：当检测到 Service Worker 更新时，立即调用 `skipWaiting` 进行 sw 的控制权转换。并 `skipWaiting` 配置项切换为用户手动更新。

### 整体默认加载示意图

![image](https://user-images.githubusercontent.com/13417006/119764232-9d3ff480-bee3-11eb-9976-79645afe607d.png)

### 使用

pwa 能力封装成 build-plugin-pwa 插件开启 pwa 能力（还包括封装 sw 注册 + 策略方案）。

```scss
// build.json
{
	"plugins": [
		["build-plugin-pwa", {
			...
		}]
	]
}
```

配置参数：

- dev - boolean，默认为 false
本地开发时是否启用 PWA 能力。

- scope -  string
Service Worker 生效的 scope，默认读取 basename

- sw - 默认生成的 sw 文件名

- runtimeCaching - array

自定义动态缓存配置，配置同 [workbox](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-build#.RuntimeCachingEntry)，示例如下：

```js
runtimeCaching: [
 {
   urlPattern: /\.jpg/,
   handler: 'CacheFirst',
   options: {
      cacheName: 'xxx',
      expiration: {
        maxAgeSecond: xxxx
   }
  }
 }
...
]
```

- additionalManifestEntries - Array

指定额外需要预缓存的内容和资源，配置同 [workbox](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-build#.ManifestEntry)

<del> - manifest - web app manifest 配置 </del>
放在 public 文件下，命名为 manifest.json

- skipWaiting - boolean

当检测到 Service Worker 更新时，立即调用 `skipWaiting` 进行 sw 的控制权转换。默认为 true，在 false 的情况下，需要主动 emit 一个 `SKIP_WAITING` 来主动触发新 Service Worker 激活。

### 构建产物

```text
├── css
 │   └── index.css
├── manifest.json
├── favicon.png
├── index.html
├── js
 │   └── index.js
└── sw.js
```

<del> ### 微应用相关设计 </del>

#### 支持资源预缓存
预缓存微应用资源主要的难点在于 **动态配置预缓存**。在单 Service Worker 的设计下，通过监听 `RUNTIME_ADDITIONAL_MANIFEST` 追加预缓存内容。

```js
// 主应用
window.MicroAssets = ['app1/index.js', 'app1/index.css', 'app2/index.js']
navigator.serviceWorker.controller.postMessage({
  type: 'RUNTIME_ADDITIONAL_MANIFEST',
});
```

#### 支持接口的缓存
单 Service Worker 的设计下，通过监听 `RUNTIME_CACHING` 事件，动态添加缓存接口策略。

```js
// 微应用
const goodsApiCacheStrategy =  {
   urlPattern: /mtop/,
   handler: 'CacheFirst',
   method: 'GET',    // 匹配 HTTP 的 GET 方法
   options: {
      expiration: {
        maxAgeSecond: xxxx
   }
  }
 }

navigator.serviceWorker.controller.postMessage({
  type: 'RUNTIME_CACHING',
});
```

#### 微应用多  Service Worker 的问题
对于微应用，如果采用多 Service Worker，会出现一些比较难可控的问题：

+ 作用域问题。场景是主应用 Service Worker 会影响到子应用，子应用无法摆脱主应用 Service Worker 的影响。
+ Service Worker 膨胀问题。随着 Service Worker 的数量越多，Service Worker 的管控会愈加复杂。

### 一些问题

1. 覆盖式发布的一致性问题
2. 本地开发需要 127.0.0.1、localhost、https 协议的地址才可以访问。

**Comment by imsobear** [comment]
都提供了哪些能力？这些能力简要说明下作用和原理？

**Comment by FuzzyFade** [comment]
![image](https://user-images.githubusercontent.com/25416941/124565500-b2118f80-de74-11eb-9d28-d454d5d1efcf.png)
typo: 冬天 -> 动态

**Comment by maoxiaoke** [comment]
+ 能力默认内置
+ 能力默认开启

**Comment by maoxiaoke** [comment]
1. 本地开发开启的参数需要统一考虑
2. manifest 详细的内容，明确基于 PC 端可能需要哪些内容
3. sw 默认逻辑应该由插件处理，自定义的场景如何拓展
4. 生成的 sw 文件的引入方式（独立文件/打包进 bundle），需要考虑后端的集成
5. 接口缓存的场景需要细化

**Comment by maoxiaoke** [comment]
2. 所有 manifest 的所有的内容包括 https://developer.mozilla.org/en-US/docs/Web/Manifest，似乎不存在单独 mobile 提供的参数
3. sw.js 的逻辑由插件生成，暂不支持自定义 service worker。自定义场景可以通过插件参数 runtimeConfig / additionalManifestEntries 等配置进行定义。
4. service worker 注册跟入口文件打包在一起，减少一个资源的请求

**Comment by maoxiaoke** [comment]
内容更新：
+  移除 manifest 配置，在 public 下新增 manifest.json 文件夹
