### ISSUE TITLE
使用TS，即使类型传入错误的，却仍然可以编译通过？

### ISSUE THREAD

**Issue by edc-hui** [alibaba/ice#4347]
我用的是webstorm，使用ice创建的TS模板，当我在使用自己定义的组件的时候，故意把类型传错，正常来说编辑器应该要报错的，但是现在并不报错，webpack直接编译通过。该如何解决？目的是当类型错误的时候，代码编译不能通过，直接报错

**Comment by imsobear** [comment]
https://ice.work/docs/guide/basic/build#tsChecker

**Comment by edc-hui** [comment]
好的  感谢  这个配置项没看到
