### ISSUE TITLE
ice-scripts@1.x版本迁移到icejs，webpack插件配置无具体模版

### ISSUE THREAD

**Issue by yanzulee** [alibaba/ice#4348]
想知道项目的webpack配置移植到build.plugin.js中怎么配置

**Comment by ClarkXia** [comment]
先参考迁移文档 https://ice.work/docs/guide/migrate#%E4%BB%8E%20ice-scripts%201.x%20%E8%BF%81%E7%A7%BB
具体迁移问题可以提供简单的代码

**Comment by yanzulee** [comment]
看了，这个针对我们项目没用，具体不知道怎么迁移![image](https://user-images.githubusercontent.com/49908097/119961771-ffc6ec80-bfd8-11eb-9027-d62ce2f11550.png)

**Comment by ClarkXia** [comment]
参考[配置迁移](https://ice.work/docs/guide/migrate#3.%20%E7%A6%81%E7%94%A8%E8%BF%90%E8%A1%8C%E6%97%B6%E8%83%BD%E5%8A%9B) 中的说明，涉及 webpack 插件的配置可以参考 [issue](https://github.com/alibaba/ice/issues/3179#issuecomment-722226295) 

对于上述的配置，基本上只需要配置 DefinePlugin 以及修改文件的输出

**Comment by yanzulee** [comment]
嗯，但是查看了模版不知道具体DefinePlugin和output应该怎么写，webpack就是一个js文件，但是build.json需要写为json，所以想要确定下怎么写这个json

**Comment by yanzulee** [comment]
修改好了但是报了mini-css-extract-plugin的![image](https://user-images.githubusercontent.com/49908097/120150898-3477b580-c21e-11eb-8b9a-7f0541118640.png)

**Comment by ClarkXia** [comment]
样式规则都不需要配置，内置的规则是能够满足 ice-scripts 下工程能力的。
另外可以将上述配置提供个代码 demo，方便快速定位问题。

**Comment by yanzulee** [comment]
其实就很小一个webpack配置文件，我这边可以直接复制代码给你吗，也不用去弄一个仓库了

**Comment by imsobear** [comment]
用户提供的 demo: https://github.com/yanzulee/icedemo

**Comment by yanzulee** [comment]
@FuzzyFade 我这边build.plugin.js配置改好了，但是没有见build.json文件，我看build.json文件里面就多配置了一个飞冰主题包，可能你没有看到，在package.json我们项目里面用了飞冰主题包，然后我现在项目启动不起来，可能是这个问题，麻烦再帮忙看一下吧，还有就是看能不能麻烦下装包用npm，别yarn，谢谢了

**Comment by yanzulee** [comment]
![Uploading image.png…]()

**Comment by yanzulee** [comment]
![image](https://user-images.githubusercontent.com/49908097/120456783-82302180-c3c8-11eb-89ff-1e26a4b95aec.png)

**Comment by yanzulee** [comment]
@imsobear 这个关掉了不会看了吗，是不是要重新开一个

**Comment by imsobear** [comment]
@FuzzyFade 再看一下

**Comment by FuzzyFade** [comment]
@yanzulee 
```typescript
config.output
  .path('./'))
```
改为
```typescript
config.output
  .path(path.resolve(__dirname))
```

这里要写相对路径呀...

细节可以再看一下我发的那个仓库 https://github.com/FuzzyFade/icedemo

**Comment by yanzulee** [comment]
@FuzzyFade 请问一下用yarn安装了哪些包啊，给的demo里面只有package.jason，现在yarn.lock也在，安装包混乱，虽然demo是能运行了，但是移植到项目很多错误

**Comment by FuzzyFade** [comment]
@yanzulee yarn 和 npm 的效果是一样的，直接删掉 yarn.lock 用 npm 完全没问题...

**Comment by yanzulee** [comment]
@FuzzyFade 按理是这样，但是我先npm i 完了启动项目一直启不来,但是yarn过后就能启起来了，只是启起来报错

**Comment by FuzzyFade** [comment]
@yanzulee npm 缓存清一下？

**Comment by FuzzyFade** [comment]
@yanzulee 现在怎么样了呀？😇
