### ISSUE TITLE
使用构建方式: 构建部署和网站运行时都请求不到 CDN 文件   构建出的字体图标太大

### ISSUE THREAD

**Issue by hyuanyuanlisiwei** [alibaba/ice#4351]
[](url)
<img width="734" alt="截屏2021-05-27 上午10 24 46" src="https://user-images.githubusercontent.com/11502089/120135056-01272d80-c202-11eb-912c-17df23c54582.png">
<img width="1313" alt="截屏2021-05-27 上午10 25 04" src="https://user-images.githubusercontent.com/11502089/120135063-05534b00-c202-11eb-99bc-ddbaf05f7648.png">

**Comment by ClarkXia** [comment]
提供下 demo，并确认下样式上是否正确

**Comment by leoyoung07** [comment]
遇到同样的问题，只能靠覆盖css样式暂时解决

**Comment by ClarkXia** [comment]
需要复现提供 demo
