### ISSUE TITLE
加载微应用静态资源的图片时加载失败

### ISSUE THREAD

**Issue by springot** [alibaba/ice#4353]
![image](https://user-images.githubusercontent.com/26103913/120206316-a58a8d80-c25d-11eb-9c92-5173467998c8.png)

**Comment by maoxiaoke** [comment]
是不是使用 `<script />` 标签来加载图片了？

**Comment by springot** [comment]
![image](https://user-images.githubusercontent.com/26103913/120287204-a1a84b00-c2f1-11eb-8daf-9cc15dfaf30e.png)
打包的图片应该在哪里加载的？

**Comment by maoxiaoke** [comment]
url 字段里面只处理 js/css 文件。
png 可在 webpack 配置好 url-loader 和 file-loader，参考 https://webpack.js.org/guides/asset-modules/#root，即参考下面的方式在代码中引入：

```html
<template>
  <div>
    <img :src="require('../../图片地址.png')" />
  </div>
</template>
```

**Comment by maoxiaoke** [comment]
Pleased to reopen if you're still in trouble @springot
