### ISSUE TITLE
externalNext 设置后构建失败

### ISSUE THREAD

**Issue by ccs520** [alibaba/ice#4361]
场景：

   基于umi 的主框架。子应用是基于ice 的。需要到处umd 的格式。
        config.output.library(`${packjson.name}-[name]`);
        config.output.libraryTarget('umd');
        config.output.jsonpFunction(`webpackJsonp_${packjson.name}`);
externalNext 开启并且设置了 umd 导出之后，构建将会报错：
  ERR! js/index.js
ERR! Missing external configuration for type:commonjs2

希望做出支持。

**Comment by maoxiaoke** [comment]
这个跟你的  externals 的配置有关，检查 externals 是否配置 commonjs2，和 output.libraryTarget 的配置无关

**Comment by MarshalShan** [comment]
遇到同样问题，使用的ice体系的子应用+UMD模式，同时子应用中还使用了formily 作为集成，同样遇到打包时提示
ERR! js/index.js
ERR! Missing external configuration for type:commonjs2
的错误，这个问题已经修复了吗？

**Comment by ClarkXia** [comment]
## 问题原因
目前 externalNext 默认配置的 extrenals 规则不适配 umd 配置，如果需要 适配 libraryTarget: 'umd' 的导出必须配置为：

```
{
  "externals": {
     "@alifd/next": {
        "root": "Next",
        "amd": "@alifd/next",
        "commonjs": "@alifd/next",
        "commonjs2": "@alifd/next",
     }
   }
}
```

## 解决方案

需要根据用户 `@alifd/next` 的 externals 配置，自定判定是否需要适配 umd 导出的 externals 规则

**Comment by ClarkXia** [comment]
参考 webpack [源码逻辑](https://github.com/webpack/webpack/blob/f4c04d8f98c023f1ff7e06642133ea5ee6f107f3/lib/WebpackOptionsApply.js#L192-L195)，@maoxiaoke umd 导出的应该多数是子应用的场景，可以整理个推荐配置

**Comment by ClarkXia** [comment]
增加指定 externalNext 为 umd 的配置方式：
```json
{
  "plugins": [
    ["build-plugin-fusion", {
       "externalNext": "umd"
    }]
  ]
}
```
