### ISSUE TITLE
为什么没有图标，是不是vscode原因啊。。。

### ISSUE THREAD

**Issue by heiyangk** [alibaba/ice#4362]
![image](https://user-images.githubusercontent.com/33884924/120578961-41ccb400-c459-11eb-8ccb-f50f243b4846.png)

**Comment by luhc228** [comment]
系统信息、VSCode 版本发一下，同时保持 AppWorks （以前是 Iceworks）插件是最新的。

**Comment by heiyangk** [comment]
系统信息：win10；VSCode版本：1.56.2 最新； AppWorks刚装的应该是最新的

**Comment by luhc228** [comment]
> 系统信息：win10；VSCode版本：1.56.2 最新； AppWorks刚装的应该是最新的

恩。VS Code 1.56.2 版本存在这个问题，1.56.1 没有。等待 VS Code 官方修复吧

**Comment by imsobear** [comment]
重复问题：https://github.com/appworks-lab/pack/issues/858
