### ISSUE TITLE
代码分割微前端子应用不能和主应用对接

### ISSUE THREAD

**Issue by liqupan** [alibaba/ice#4365]
## What is the current behavior? 发生了什么？
使用代码分割后，微前端路由失败。

## What is the expected behavior? 期望的结果是什么？

子应用使用代码分割，可以正常和主应用对接
## Any additional comments? 相关环境信息？

**Comment by maoxiaoke** [comment]
若子应用开启 [splitChunk](https://webpack.js.org/plugins/split-chunks-plugin/#optimizationsplitchunks)，假设打包后的产物为 main.js、common.chunk.js，则配置时需要将所有 chunk 都添加到 url 中（并保证执行顺讯）：

```js
url: [
  'common.chunk.js',
  'main.js'
]
```

或通过 [entry](https://micro-frontends.ice.work/guide/concept/child#2-entry) 的方式接入。

**Comment by liqupan** [comment]
> 若子应用开启 [splitChunk](https://webpack.js.org/plugins/split-chunks-plugin/#optimizationsplitchunks)，假设打包后的产物为 main.js、common.chunk.js，则配置时需要将所有 chunk 都添加到 url 中（并保证执行顺讯）：
> 
> ```js
> url: [
>   'common.chunk.js',
>   'main.js'
> ]
> ```
> 
> 或通过 [entry](https://micro-frontends.ice.work/guide/concept/child#2-entry) 的方式接入。

请问打包出来是这样的产物
![image](https://user-images.githubusercontent.com/21078925/120956801-f1ba5e00-c786-11eb-8865-31a9fdf64d68.png)
我引用是这样吗？
![Uploading image.png…]()

**Comment by liqupan** [comment]
已经解决，需要配置子应用publicPath使主应用可以正确访问子应用地址
