### ISSUE TITLE
使用的npm init ice 并不支持webp格式的图片，并报错

### ISSUE THREAD

**Issue by cl510804194** [alibaba/ice#4369]
我该如何在项目中配置以便支持webp格式，配置的loader好像并没有生效
1. 图1 是报的错误信息
![image](https://user-images.githubusercontent.com/42998038/120980272-0871ac80-c7a9-11eb-89fd-680ec468810e.png)

2.图2 是我配置的build.json
![image](https://user-images.githubusercontent.com/42998038/120980405-2b9c5c00-c7a9-11eb-8d49-56ed2b5924be.png)

**Comment by ClarkXia** [comment]
参考下文档 https://ice.work/docs/config/about#webpackloaders  loaders 配置是个 key-value 结构

**Comment by cl510804194** [comment]
我试过了，上面那个图2 就是配置的webp，但是似乎没有生效？，我使用以下两种的配置都是失效了

**Comment by cl510804194** [comment]
图1

**Comment by imsobear** [comment]
> 参考下文档 https://ice.work/docs/config/about#webpackloaders loaders 配置是个 key-value 结构

PS：是不是应该默认支持？

**Comment by cl510804194** [comment]
{
  "plugins": [],
  "webpackLoaders": {
    "webp": {
      "test": ".(webp)$",
      "loaders": [
        "file-loader",
        "webp-loader"
      ]
    }
  },
  "webpackPlugins": {

  }
}
配置2
 {
  "plugins": [],
  "webpackLoaders": {
    "webp": {
      "test":".(jpe?g|png)$",
      "loaders": [
        "file-loader",
        "webp-loader"
      ]
    }
  }
}

**Comment by ClarkXia** [comment]
```json
{
  "plugins": [],
  "webpackLoaders": {
    "webp": {
      "test":".(jpe?g|png)$",
      "loaders": {
        // 配置 options 如果有的话
        "file-loader": {},
        "webp-loader":{}
      }
   }
  }
}
```

**Comment by cl510804194** [comment]
okk 已经解决了这个问题，希望官方在脚手架中能默认支持webp,h5挺常用的，配置如下
{
  "plugins": [],
  "webpackLoaders": {
    "image": {
      "test": ".webp$",
      "loaders": {
        "file-loader": {
        }
      }
    }
  }
}

**Comment by ClarkXia** [comment]
需求在 https://github.com/alibaba/ice/issues/4370 中跟进
