### ISSUE TITLE
子应用路由加hash返回问题

### ISSUE THREAD

**Issue by 178558956245** [alibaba/ice#4376]
子应用内部从列表页面跳转到详情页面时用hash记录搜索条件，先使用window.location.hash = XXX记录hash值，然后使用window.location.href做跳转，在此操作情景下需要点击两次返回按钮，才能返回初始页面，第一次返回把路由上的hash清除，用户体验不好，做出以下修改：使用history.replaceState()做处理，这种操作在子应用单独使用的时候正常，但是放在主应用打开的时候点击详情按钮会把当前页面重新加载一遍，然后再打开详情页面，有没有好的解决方案

**Comment by maoxiaoke** [comment]
如果只是需要从详情页 -> 详情页携带参数，可以通过 query 参数的方式实现，这或许是一个比较好的方式。
