### ISSUE TITLE
[RFC] MPA 复用 runApp 能力

### ISSUE THREAD

**Issue by SoloJiang** [alibaba/ice#4384]
## 概述

MPA 默认导出的形式可以复用 runApp 加载 runtime 的能力，同时通过架构设计满足大部分自定义渲染场景。

### 现在是什么样的

目前 MPA 应用，导出的页面组件会被框架包裹一层 `render` 方法渲染，以 `src/pages/Home/index.js` 为例：

```jsx
export default () => {
  return <div>这是 Home 页面</div>
};
```

在构建时，框架会在 `.ice` 目录下创建对应页面**真正的** webpack 入口 `.ice/mpaEntry/home.tsx`：

```jsx
// 以下代码为最简展示
import React from 'react';
import ReactDOM from 'react-dom';

import Component from '/Users/fushen/Documents/workplace/ice2.x/examples/basic-mpa/src/pages/Home/index';

ReactDOM.render(
  <Component />,
  document.getElementById('ice-container')
);
```

### 满足不了什么样的需求

即使上述方法非常轻量的渲染了页面组件，但是依然不够好用，满足不了以下诉求：

- MPA 场景下能够让页面的共用逻辑统一维护
  - 从代码设计上，虽然可以用高阶函数或者公共文件来达成目标，但是对业务使用者而言，依然存在一定的认知、使用成本，不利于提供最佳实践
- 研发框架插件的能力增强，面向多数 MPA 开发者，运行时和构建能力缺少通过**一个插件**就能统一注入的能力
- 如果需要让 MPA 中的某一个页面是 SPA，开发者必须主动调用 runApp 并且传入 routes 信息
- 开发者一旦需要自定义 `render` ，框架就失去了对项目运行时能力的控制，比如渲染 TabBar

### 多页应用临时目录规范：

```bash
├──.ice/        # 约定临时目录
│   ├── core/        # 用于存放运行时核心代码，比如 runtime 机制，runApp 执行流程，主要有 plugin-app-core 生成
│   ├── plugins/        # 插件运行时
│   ├── entries/        # mpa 多入口目录
│   │   ├── home        # home 页面
│   │   │   ├── index.tsx        # 引入页面组件并执行 runApp
│   │   │   └── runApp.ts        # 该页面按需生成的 runApp 方法
│   ├── types/        # 类型文件
│   └── index.ts        # ice 入口，用于导出运行时 API
```

按照上述结构设计之后，可以实现以下能力：

- 多页应用默认使用 `runApp` 加载插件 runtime 的能力
- runApp 的入参可以根据每个页面自身的情况通过 ejs 生成
- runApp 方法本身也可以根据不同的页面有不同的实现，核心是为了解决路由等依赖引入之后造成的体积膨胀问题

### 插件 runtime API

在多页应用中，运行时**可能**会不存在一些在单页应用中存在的方法：`modifyRoutes/setRenderRouter` ，需要插件开发者自行兼容。

#### appConfig

对应 `runApp` 传入的的 appConfig。

#### context

应用运行上下文。包含页面级数据 `pageInitialProps`。

#### addDOMRender

自定义渲染，开发者自行渲染最终的 App 组件实例。

```jsx
import ReactDOM from 'react-dom';

export default ({ addDOMRender }) => {
  // App: React 组件
  // appMountNode: App 挂载点
  const DOMRender = ({ App, appMountNode }) => {
    ReactDOM.render(<App />, appMountNode);
  };
  addDOMRender(DOMRender);
};
```

#### addProvider

为页面包裹 Provider：

```jsx
export default ({ addProvider }) => {
  const StoreProvider = ({ children }) => {
    return <Provider store={store}>{children}</Provider>;
  };
  addProvider(StoreProvider);
};
```

#### wrapperPageComponent

为所有页面级组件做一层包裹：

```jsx
import { useEffect } from 'react';

export default ({ wrapperRouteComponent }) => {
  wrapperRouteComponent((PageComponent) => {
    const { title } = 'Hello icejs';
    if (!title) {
      return PageComponent;
    }

    const TitleWrapperedComponent = () => {
      useEffect(() => {
        document.title = title;
      }, []);

      return <PageComponent />;
    };
    return TitleWrapperedComponent;
  });
};
```

**备注：** SPA 现有的 `wrapperRouteComponent` 也对应更名为 `wrapperPageComponent`

#### 推荐

脚手架创建的页面都是 `export default` 导出：

```jsx
export default () => {
  return <div>这是 Home 页面</div>
};
```

#### 对 runApp 入参有定制化需求

自行创建 `pages/Home/app.ts`，执行 `runApp()`，此时会根据同目录下是否存在 `routes.ts` 决定是使用 `.ice/entries/home/runApp.ts` 还是 `.ice/runApp.ts`，两者的区别是后者会引入路由相关的依赖。

```jsx
// pages/Home/app.ts

runApp({
  request: {
    baseURL: '/api',
  }
});
```

### 方案最终解决了什么问题

- 多页应用可以低成本的使用 runApp 带来的插件 runtime 的能力
- 每个页面共用的逻辑可以通过插件的形式统一注入
- 通过该项能力可以提供哪些最佳实践：无痕埋点、vscode 调试代码快速定位到源码....
- 多页应用每个页面的 runApp 可以是不同的实现，从而保障了体积不会互相影响
- 多页应用中某一个页面是 SPA 的场景，面向开发者的步骤简化到只需要在 `pages/Home` 下创建 routes.ts （Rax App 里是 app.json）
- Rax App 小程序分包场景，也可以简化开发者的操作，即只需要每个分包创建 `app.json` 即可
- 多页应用中，开发者如果有自定义 render 的诉求，也可以通过插件提供的 `addDomRender` 来进行自定义，这样一来不仅能保留插件 runtime 的能力还可以满足自定义渲染的诉求，针对的场景：SSR 并行渲染，服务端需要 `export default` 导出，客户端需要自定义 `render`

### 实现中需要注意的一些点

- 改为默认执行 `runApp` ，需要关注对原有 MPA 造成的 break change
  - build-plugin-router
- react-app-renderer 里的逻辑需要和 history 解耦
- SSR 需要考虑怎么串起来整个逻辑
- 代码体积需要保障做到不膨胀
  - router 这类插件需要改造，把 runtime 做的尽可能薄，较重的逻辑通过模板生成组装到 runApp 里

**Comment by ClarkXia** [comment]
2.0 版本中支持
