### ISSUE TITLE
unable to resolve dependency tree when add dependencies

### ISSUE THREAD

**Issue by dangolbeeker** [alibaba/ice#4385]
无法让冰与手动构建或 Appworks 一起工作。 NPM 安装 ice.js，react 和 react-dom
"name": "项目",
  “脚本”：{
    "start": "icejs 开始",
    "build": "icejs 构建"
  },
  “依赖关系”：{
    "@ice/store": "^1.4.2",
    "ice.js": "^1.18.1",
    “反应”：“^ 17.0.2”，
    “反应域”：“^ 17.0.2”
  },
  “开发依赖”：{
    “打字稿”：“^4.3.2”
  }
}

 ```
npm install --save @alifd/next ahooks bizcharts 类名 react-intl react-sortablejs
npm 错误！代码 ERESOLVE
npm 错误！ ERESOLVE 无法解析依赖树
npm 错误！
npm 错误！解析时：Project@undefined
npm 错误！发现：react@17.0.2
npm 错误！节点模块/反应
npm 错误！ react@"^17.0.2" 来自根项目
npm 错误！
npm 错误！无法解决依赖：
npm 错误！同行反应@“^ 16.13.1”来自@alifd/meet-react@2.3.6
npm 错误！ node_modules/@alifd/meet-react
npm 错误！来自@alifd/next@1.23.6 的同行@alifd/meet-react@"^2.0.0"
npm 错误！ node_modules/@alifd/下一个
npm 错误！ @alifd/next@"*" 来自根项目
npm 错误！
npm 错误！修复上游依赖冲突，或者重试
npm 错误！此命令带有 --force 或 --legacy-peer-deps
npm 错误！接受不正确（并且可能已损坏）的依赖项解析。
npm 错误！
npm 错误！请参阅 C:\Users\Scott\AppData\Local\npm-cache\eresolve-report.txt 了解更多信息
会报告。

npm 错误！可以在以下位置找到此运行的完整日志：
npm 错误！ C:\Users\Scott\AppData\Local\npm-cache\_logs\2021-06-15T15_26_58_38
4Z-debug.log
```

是否有简单的安装或 CLI？我喜欢使用 React 并添加一堆 NPM 包进行自定义。

我可以单独使用 Fusion Component 吗？

抱歉语境不好我说英语。

**Comment by FuzzyFade** [comment]
@dangolbeeker Please speak English, we have understood enough 😄

**Comment by dangolbeeker** [comment]
Unable to get ice to work with Manual build or Appworks. NPM install ice.js, react and react-dom
"name": "Project",
  "scripts": {
    "start": "icejs start",
    "build": "icejs build"
  },
  "dependencies": {
    "@ice/store": "^1.4.2",
    "ice.js": "^1.18.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  },
  "devDependencies": {
    "typescript": "^4.3.2"
  }
}

 npm install --save @alifd/next ahooks bizcharts classnames react-intl react-sortablejs
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: Project@undefined
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.13.1" from @alifd/meet-react@2.3.6
npm ERR! node_modules/@alifd/meet-react
npm ERR!   peer @alifd/meet-react@"^2.0.0" from @alifd/next@1.23.6
npm ERR!   node_modules/@alifd/next
npm ERR!     @alifd/next@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Scott\AppData\Local\npm-cache\eresolve-report.txt for a fu
ll report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Scott\AppData\Local\npm-cache\_logs\2021-06-15T15_26_58_38
4Z-debug.log



Is there a simple installation or CLI? I feel like using React and just adding a bunch of NPM Packages for customization.


Can I use the Fusion Component Standalone in my React Project?

**Comment by FuzzyFade** [comment]
I try according to the configuration, didn't repeat the same error.
Please try to clean up the .lock file first or use `npm i -f` for install these dependencise.

**Comment by FuzzyFade** [comment]
Closed
