### ISSUE TITLE
为什么将环境配置分为工程配置和运行时配置

### ISSUE THREAD

**Issue by hetchzhao** [alibaba/ice#4390]
飞冰将环境配置划分为工程配置和运行时配置，这是基于怎样的考虑来设计的？

**Comment by imsobear** [comment]
因为实际业务场景里两种需求都有：

- 工程配置：多个环境会有差异，比如 publicPath、sourceMap 这种
- 运行时配置：比如页面运行时要从某个服务端请求接口，不同环境这个服务端的域名是不一样的

**Comment by hetchzhao** [comment]
懂了
