### ISSUE TITLE
https://fusion.design/上，自定义主题看不到了

### ISSUE THREAD

**Issue by rootsli** [alibaba/ice#4391]
![image](https://user-images.githubusercontent.com/4099803/122696963-eda63a00-d276-11eb-90eb-f1f690d1d62e.png)
d

点击“配置主题”进入后，找不到自定义主题，只看到下面几个主题：
![image](https://user-images.githubusercontent.com/4099803/122696917-d23b2f00-d276-11eb-97bf-3a41ecc66c9d.png)

**Comment by imsobear** [comment]
建议前往 fusion 仓库反馈：https://github.com/alibaba-fusion/next
