### ISSUE TITLE
飞冰 部署到GitHub page后js和css出现404 not found。

### ISSUE THREAD

**Issue by StrayCamel247** [alibaba/ice#4392]
飞冰 部署到GitHub page后js和css出现404 not found。
使用的是 gh-pages

项目关联地址
https://github.com/OHSY247/BotWeb/tree/dev

本地build是可以正常run起来的

部分配置信息
....
  "homepage": "./",
....
    "predeploy":"icejs build",
    "deploy":"gh-pages -d build",
...

搭建后的预览图
![image](https://user-images.githubusercontent.com/26707191/122861148-87421a00-d351-11eb-91a7-5cc1227c9420.png)

**Comment by ClarkXia** [comment]
看下访问的地址，默认 publicPath 是 `/`，这种情况配置成 `./` 会更合理

**Comment by StrayCamel247** [comment]
https://github.com/OHSY247/BotWeb/blob/dev/webpack.config.js
```
import { resolve } from 'path';

export const entry = './src/index.js';
export const output = {
  publicPath: './',
  path: resolve(__dirname, 'build'),
};
```

配置后依旧无法访问到js css文件

尝试将https://github.com/OHSY247/BotWeb/blob/dev/package.json。中homepage 更换为 ‘/’ ‘./' 都不行
```

**Comment by imsobear** [comment]
publicPath 是配置在 build.json 里的。
