### ISSUE TITLE
请问官网现在不提供mac客户端的下载了吗？

### ISSUE THREAD

**Issue by trusause** [alibaba/ice#4394]
请问官网现在不提供mac客户端的下载了吗？

**Comment by ClarkXia** [comment]
具体是指什么客户端，目前支持 vscode 插件以及前端开发工具箱的下载 https://appworks.site/

**Comment by imsobear** [comment]
可以在这里了解下：https://appworks.site/pack/about.html#%E6%BC%94%E8%BF%9B%E5%8E%86%E7%A8%8B
