### ISSUE TITLE
node.getIterator is not a function

### ISSUE THREAD

**Issue by maskTAQ** [alibaba/ice#4395]
## node.getIterator is not a function

`$ yarn build `
提示报错，翻阅了issue大致定位到是postcss-less 与postcss版本不兼容导致

## What is the expected behavior? 期望的结果是什么？

顺利编译

## Any additional comments? 相关环境信息？

- **ice.js Version ^1.0.0
- **build.json Configuration**：
- **Node Version**: v14.16.0
- **Platform**:mac

**Comment by imsobear** [comment]
ice.js 依赖的 optimize-css-assets-webpack-plugin^5.0.3 昨天晚上发布了 5.0.7 版本，相比 5.0.6，其中一个变化是 postcss 从传递依赖的 7.x 变为了直接依赖 8.x，导致构建报错，相关 issue：https://github.com/NMFR/optimize-css-assets-webpack-plugin/issues/167

建议使用 cnpm 安装依赖，cnpm 临时解决了这个问题：https://github.com/cnpm/bug-versions/pull/140
