### ISSUE TITLE
路由跳转useHistory 传递对象

### ISSUE THREAD

**Issue by zoewrenlcw** [alibaba/ice#4399]
是否可以传递整个对象？还是只能传递在url中？传递对象的话该如何配置？
目前使用的是如下配置（貌似只能传递单个对象，不能传递复杂对象，例如[test:{'a':'b'}]）
{
        path: '/test/:testId/',
        exact: true,
        component: Test
      }

**Comment by imsobear** [comment]
声明路由的时候什么场景需要动态传入对象？这个对象是哪里来的？一般是调用 `history.push` 的时候可以传入一个 state，而不在声明路由的地方。

**Comment by zoewrenlcw** [comment]
> 声明路由的时候什么场景需要动态传入对象？这个对象是哪里来的？一般是调用 `history.push` 的时候可以传入一个 state，而不在声明路由的地方。
history.push（）的state对象在也是通过useParams()方法获取么？state对象是否命名必须为state？
push可以传入类似这样的参数么？
const testData={
                  'Id':idtest,
                  'name':testname,
                  'config':config
                }

**Comment by imsobear** [comment]
https://ice.work/docs/api/about#link history.push 拥有同样的参数

**Comment by zoewrenlcw** [comment]
const state={
   id:'123',
   name:'name1'
}
尝试根据文档中的示例，使用history.push('/test',{State:state})或者history.push('/test',state);
然后在其他页面通过useLocation().state或者useHistory().location.state获取state对象，获取到是未定义

**Comment by maoxiaoke** [comment]
@zoewrenlcw hashRouter 吗？

**Comment by zoewrenlcw** [comment]
> @zoewrenlcw hashRouter 吗？

创建history的方式么？使用的是useHistory()

**Comment by imsobear** [comment]
@zoewrenlcw 搞个重现 demo 放到 GitHub 上，我看下

**Comment by maoxiaoke** [comment]
@zoewrenlcw 如果是 router 是 hash 的话，react-router-dom 不支持 state，参考 https://reactrouter.com/web/api/history

> state - (object) location-specific state that was provided to e.g. push(path, state) when this location was pushed onto the stack. <b>Only available in browser and memory history.</b>

ice 默认是 HashRouter

**Comment by imsobear** [comment]
https://ice.work/docs/guide/basic/router#%E8%B7%AF%E7%94%B1%E8%B7%B3%E8%BD%AC 已补充更详尽的文档。
