### ISSUE TITLE
飞冰1.10问题

### ISSUE THREAD

**Issue by chyj19961101** [alibaba/ice#4400]
我们使用的是阿里系的阿里云管理项目，项目中使用的是飞冰的ui，在使用流水线部署的时候，到92%左右校验阶段会报postcss的问题导致无法部署成功，猜测原因是ice的1.10与postcss 7.0.36之间的问题，能否帮忙解决一下，项目有需求和线上bug待处理

**Comment by ClarkXia** [comment]
参考下 https://github.com/alibaba/ice/issues/4395

**Comment by ClarkXia** [comment]
optimize-css-assets-webpack-plugin 已发版本修复，可以重新构建下，如果还有问题可以提供项目信息重开 issue
