### ISSUE TITLE
[SSR] Expected server HTML to contain a matching <div> in <div>.

### ISSUE THREAD

**Issue by maskTAQ** [alibaba/ice#4402]
## react警告
在ssr模式下。会出现如下警告
`Expected server HTML to contain a matching <div> in <div>.`
```js
// Fix: Expected server HTML to contain a matching <a> in
const renderMethod = module.hot ? ReactDOM.render : ReactDOM.hydrate;
renderMethod(
  <BrowserRouter>
    <RoutersController data={data} routes={routes} />
  </BrowserRouter>,
  document.getElementById('root')
);
```
## What is the expected behavior? 期望的结果是什么？
解决此警告

## Any additional comments? 相关环境信息？

- **ice.js Version N/*：
- **build.json Configuration N/*：
- **Node Version N/*:
- **Platform mac:

**Comment by imsobear** [comment]
终端日志截图发一个

**Comment by maskTAQ** [comment]
经测试，此警告引用的原因是由于修改容器的id引起的[#4405]。(https://github.com/alibaba/ice/issues/4405)
