### ISSUE TITLE
【ssr】当修改容器的id时，输出的html中没有xml文档

### ISSUE THREAD

**Issue by maskTAQ** [alibaba/ice#4405]
## 【ssr】当修改容器的id时，输出的html中没有xml文档
在 public/index src/app.ts俩个文件中
将rootId ice-container 改为 其他比如app时 服务直出的html中会丢掉xml内容
![image](https://user-images.githubusercontent.com/19301145/123381021-bf9c5f00-d5c2-11eb-9ea3-84f04cdc20cb.png)
![image](https://user-images.githubusercontent.com/19301145/123381053-ca56f400-d5c2-11eb-8b3f-8ce850919902.png)

## What is the expected behavior? 期望的结果是什么？
可以自定义容器id

## Any additional comments? 相关环境信息？

- **ice.js Version 1.18.1：
- **build.json Configuration**：
```json
{
  "ssr": true,
  "router": {
    "lazy": true
  },
  "plugins": [
    [
      "build-plugin-antd",
      {
        "themeConfig": {
          "primary-color": "#54a984"
        }
      }
    ],
    [
      "build-plugin-moment-locales",
      {
        "locales": [
          "zh-cn"
        ]
      }
    ]
  ]
}

```
- **Node Version N/*:
- **Platform mac:

**Comment by imsobear** [comment]
@luhc228 @ClarkXia 这个貌似是已知问题？

**Comment by imsobear** [comment]
ice.js:1.18.2-beta.1 @maskTAQ 这个版本修复了这个问题，可以试一下

**Comment by maskTAQ** [comment]
> ice.js:1.18.2-beta.1 @maskTAQ 这个版本修复了这个问题，可以试一下

![image](https://user-images.githubusercontent.com/19301145/123755721-c7c00b80-d8ee-11eb-9085-b684f37341fc.png)
![image](https://user-images.githubusercontent.com/19301145/123755775-d5759100-d8ee-11eb-9fba-c325c075b812.png)

> cnpm i ice.js@1.18.2-beta.1 --save 

我通过cnpm升级了ice.js到指定版本,并重新运行 `yarn start`,问题没有得到解决

**Comment by imsobear** [comment]
改下 package.json 的版本号，然后 `cnpm update` 完全重装下试试

**Comment by maskTAQ** [comment]
我重新装了依赖是可以的,现在没有html日志输出。
