### ISSUE TITLE
[SSR]开启SSR时不论是开发环境亦或是生成环境控制台都会输出html文档等日志信息，可以关闭吗？

### ISSUE THREAD

**Issue by maskTAQ** [alibaba/ice#4410]
## 在生产环境或开发环境关闭输出的日志信息

![image](https://user-images.githubusercontent.com/19301145/123753556-92b2b980-d8ec-11eb-8ef1-294f3e53e3a1.png)

## What is the expected behavior? 期望的结果是什么？
提供关闭输出日志的方法

## Any additional comments? 相关环境信息？

- **ice.js Version**：
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by imsobear** [comment]
https://github.com/alibaba/ice/issues/4405#issuecomment-870284465 这个版本一起修复了哈

**Comment by maskTAQ** [comment]
> [#4405 (comment)](https://github.com/alibaba/ice/issues/4405#issuecomment-870284465) 这个版本一起修复了哈

> cnpm i ice.js@1.18.2-beta.1 --save 

我升级到了指定版本，终端还是输出html日志信息，是需要通过配置关闭吗?
![image](https://user-images.githubusercontent.com/19301145/123756272-56348d00-d8ef-11eb-827a-1194569fa402.png)

**Comment by imsobear** [comment]
@maskTAQ 不需要配置，你先试下纯前端的调试是不是 OK 的

**Comment by imsobear** [comment]
@maskTAQ 项目依赖整体重装下试试，看了下发布后的代码应该没问题
