### ISSUE TITLE
[SSR]打包后引用资源的路径未更改

### ISSUE THREAD

**Issue by maskTAQ** [alibaba/ice#4411]
## [SSR]打包后引用资源的路径未更改
当使用 `<img src="./demo.png" />` 时，开发环境可以正确引用文件,打包后配置的publicPath不生效，线上渲染依然为 `./demo.png`,而不是`publicPath+'./demo.png'`

不知道是否可以通过`require`来引入文件解决img引入问题,即使可以,
`<link crossorigin="" rel="shortcut icon" type="image/x-icon" href="/src/assets/icon/logo.png">`
link引入的图标之类在html中引用的资源改怎么解决

## What is the expected behavior? 期望的结果是什么？
可以再生产环境引入正确的资源地址

## 配置信息
前端 build.josn
```json
{
 "publicPath": "http://localhost:8887/public/web/"
}
```
服务端

```js
const path = require('path');
const render = require('../render/server/index').default;
const webStatsPath = path.resolve(__dirname, '../render', 'loadable-stats.json');

'use strict';

const Controller = require('egg').Controller;

class WebController extends Controller {
    async index() {
        const pathname = '/';
        const result = await render({
            req: { url: pathname },
            pathname,
            path: pathname,
        }, {
            loadableStatsPath: webStatsPath,
            publicPath: 'http://localhost:8887/public/web/',
        });

        this.ctx.body = result.html;
    }
}

module.exports = WebController;

```
## Any additional comments? 相关环境信息？
- **ice.js Version**：
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by ClarkXia** [comment]
`<img src="./demo.png" />` 这种形式的写法是直接将 src 的链接当成具体的图片地址，推荐写法如下：

```js
import img from './demo.png';

<img src={img} />
```

如果 图片地址已经是 cdn 地址，可以直接通过 `<img src="https://cdn.com/pic.png" />` 的形式设置

**Comment by maskTAQ** [comment]
> `<img src="./demo.png" />` 这种形式的写法是直接将 src 的链接当成具体的图片地址，推荐写法如下：
> 
> ```js
> import img from './demo.png';
> 
> <img src={img} />
> ```
> 
> 如果 图片地址已经是 cdn 地址，可以直接通过 `<img src="https://cdn.com/pic.png" />` 的形式设置

那其实没有框架没有对public/html里的资源地址做处理，只能声明为绝对路径或者直接放在根目录索引?

**Comment by ClarkXia** [comment]
框架默认做的是往 `public/index.html` 里注入执行的资源（js 和 css），构建后带 publicPath，其他 html 内容并不会去处理
html 中的其他资源，推荐用 cdn 地址；如果资源在 public 目录下可以用 `/` 索引到根域名，但这种方式对具体部署位置有要求，即资源需要部署在域名跟目录下

**Comment by imsobear** [comment]
cdn 地址是另一种用法，这里可以不讨论，主要还是针对资源放在 public 然后一起部署到 server 端的情况，路径应该怎么写，上面的例子是 js，那么 css 里应该怎么写？html 里应该怎么写？
