### ISSUE TITLE
[SSR][CSR] 开启SSR时,支持一键降级至CSR吗?

### ISSUE THREAD

**Issue by maskTAQ** [alibaba/ice#4412]
## 想实现当UA为百度蜘蛛类的爬虫时输出html,正常用户访问时为[CSR]
```js
 const result = await render({
        req: { url: pathname },
        pathname,
        path: pathname,
    }, {
        loadableStatsPath: webStatsPath,
        publicPath: 'http://localhost:8887/public/web/',
       csr:true// 此render函数为ssr:true 打包产出 可否支持类似配置 一键降级至csr
    });
```

## What is the expected behavior? 期望的结果是什么？
支持在服务端[SSR][CSR]之间自由切换
## Any additional comments? 相关环境信息？

- **ice.js Version**：
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by imsobear** [comment]
现在的逻辑是 SSR 出错后会自动降级，你这种需求需要加个参数，这块我看下。

**Comment by ClarkXia** [comment]
行为上更像是期望直接输出 html template 的内容，如果在内置逻辑中写 `if (forceCSR) { return htmlContent }` 的话，感觉提供获取 default html 的 api 会更合理，职责上也更明确

```js
import serverRender, { getHtmlTemplate } from './server';
```

> ps 感觉这类前置就判断出是否 ssr/csr 的场景应该不多

**Comment by luhc228** [comment]
这个场景感觉有点少~
要加的话，上面 @ClarkXia 的方案好点
