### ISSUE TITLE
如何获取axios.CancelToken来abort数据请求

### ISSUE THREAD

**Issue by caojinjie** [alibaba/ice#4413]
## What is the current behavior? 发生了什么？

1. 我使用Upload组件来做上传，业务场景中需要上传大于1G的文件，期望做分片处理；

2. 查阅ice文档后使用customRequest来自定义请求做分片，按照官档介绍需要返回abort方法来取消请求，由于request是基于axios封装的，查询axios官档（https://github.com/axios/axios#request-config）发现可以通过axios.CancelToken来实现abort；

3. 但从ice导入的request未见获取CancelToken的方法，参考axios直接使用request.CancelToken获取为undefined；

## What is the expected behavior? 期望的结果是什么？

1. 期望了解Upload组件是否提供了分片、断点续传等支持或样例；

2. 能够获取到CancelToken来abort，或提供其他方式；

## Any additional comments? 相关环境信息？

- **ice.js Version**：1.17.6
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by imsobear** [comment]
https://github.com/alibaba/ice/pull/4415/files 支持了下，明天发布 beta 版本，可以看下使用方式是否符合预期。

**Comment by imsobear** [comment]
ice.js@1.18.2，已支持
