### ISSUE TITLE
request 的类型缺陷问题

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#4417]
1. 导出 `IRequestConfig` 的类型，供开发者使用
2. `request(options)` 不支持 `instanceName | withFullResponse` 等自定义属性

![image](https://user-images.githubusercontent.com/2505411/123816660-12ab4480-d92a-11eb-998c-2db098aeca65.png)

3. `useRequest()` 缺少基础的类型提示和校验

![image](https://user-images.githubusercontent.com/2505411/123816829-38384e00-d92a-11eb-8d1d-2a60877becd6.png)

@maoxiaoke 看一下

**Comment by maoxiaoke** [comment]
导出 IRequestConfig 的目的是什么？在哪种场景下消费呢？是否有必要？
