### ISSUE TITLE
SSR 时为什么需要服务端自行传入 publicPath

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#4418]
按道理工程上注入到运行时里不就可以了吗？ @luhc228 

![image](https://user-images.githubusercontent.com/2505411/123817898-1db2a480-d92b-11eb-8510-1c791e96306b.png)

**Comment by luhc228** [comment]
可以的，实现的方案，是在渲染 `server.ts.ejs` 模板时，把 publicPath 注入进去。

不过这里需要区分 build 和 dev 两种情况，build 用 publicPath，dev 用 devPublicPath

**Comment by luhc228** [comment]
可以的，实现的方案，是在渲染 `server.ts.ejs` 模板时，把 publicPath 注入进去。

不过做的更好一点，需要区分 build 和 dev 两种情况，build 用 publicPath，dev 用 devPublicPath

**Comment by luhc228** [comment]
icejs 2.x 已支持

**Comment by imsobear** [comment]
> icejs 2.x 已支持

文档可以更新下
