### ISSUE TITLE
微模块和npm的一个组件 有什么区别

### ISSUE THREAD

**Issue by haoxiaoshu6** [alibaba/ice#4423]
微模块和npm的一个组件 有什么区别

**Comment by maoxiaoke** [comment]
npm 包的劣势：
1. 不支持动态下发，npm 包更新后，主应用也需要重新部署
2. 会影响都主应用的编译速度和打包体积

icestark 微模块的优势：
1. 跨技术栈，支持 React、Vue 的开发
2. 资源支持动态下发，天然的分包加载、错误隔离等优势

**Comment by webMasterMrBin** [comment]
当主子应用都是统一技术栈时, 比如react,
微模块的优势就不是很明显了吧, 直接把子应用通过npm组件引入进来的方案 只是单一会增加包体积和编译速度了,
这块有统计当组件有多重时引入 微模块方案 才比较有意义呢
