### ISSUE TITLE
如何嵌入angular的子应用？

### ISSUE THREAD

**Issue by 178558956245** [alibaba/ice#4424]
飞冰微前端怎么嵌入angular的子应用，需要对angular的项目做一些什么配置？文档没有说明，按照命令生成的微前端项目angular的项目地址有index.html,实际本地的angular项目并没有生成html,是不是需要什么配置？

**Comment by maoxiaoke** [comment]
Angular 我们推荐使用 [entry](https://micro-frontends.ice.work/docs/guide/concept/child#2-entry) 的方式接入。比如 Angular 项目可以通过 xxx.abc.com 访问，则主应用配置：

```js
entry:  ’xxx.abc.com‘
```

**Comment by 178558956245** [comment]
子应用不需要做什么设置吗，我看示例里的angular是用了XXX/index.html,然而我们实际的项目里面没有找到index.html,entry直接配置域名拿不到资源

**Comment by maoxiaoke** [comment]
@178558956245 会不会 html 是由服务器端下发的呢？

**Comment by 178558956245** [comment]
我这个 angular是已有项目改造的，不用像vue那样的在main.js里面配置引入主框架的东西吗

**Comment by 178558956245** [comment]
[Uploading demo0709.zip…]()

**Comment by 178558956245** [comment]
[demo0709.zip](https://github.com/alibaba/ice/files/6788301/demo0709.zip)

**Comment by maoxiaoke** [comment]
1. 升级下 Ice.js 的版本
2. 升级 build-plugin-stark 至最新版本
3. create-react-app 接入参考 https://micro-frontends.ice.work/docs/guide/use-child/others#create-react-app-%E5%BA%94%E7%94%A8 和 demo https://github.com/maoxiaoke/icestark-demos/tree/master/cra-api-umd/react16-child
