### ISSUE TITLE
[build error] yarn build时esbuild报错

### ISSUE THREAD

**Issue by maskTAQ** [alibaba/ice#4426]
##  `yarn build`时esbuild报错

于7月1日安装依赖,不知道是不是由于依赖包版本变更导致的此问题
已尝试使用yarn npm cnpm 写死项目package.json版本号并重新安装依赖，未能解决问题

![image](https://user-images.githubusercontent.com/19301145/124080709-40ed6900-da7d-11eb-99b5-4b0eccd29b23.png)

## Any additional comments? 相关环境信息？

- **ice.js Version 1.18.2-beta.1：
- **build.json Configuration **：
```json
{
  "ssr": true,
  "router": {
    "lazy": true
  },
  "plugins": [
    [
      "build-plugin-antd",
      {
        "themeConfig": {
         
        }
      }
    ],
    [
      "build-plugin-moment-locales",
      {
        "locales": [
          "zh-cn"
        ]
      }
    ]
  ],
  "outputDir": "render",
  "esbuild": {
    "target": "es2015",
    "minify": true,
    "minifyWhitespace": true,
    "minifyIdentifiers": true,
    "minifySyntax": true,
    "css": true
  },
  "publicPath": "http://localhost:8887/public/web/"
}
```
- **Node Version :v14.16.0
- **Platform: mac

**Comment by ClarkXia** [comment]
提供下简单的 demo，目前无法简单通过官方 demo 复现

**Comment by maskTAQ** [comment]
> 提供下简单的 demo，目前无法简单通过官方 demo 复现

在esbuild报错的代码中我打印了详细的错误,定位到由于我自身的代码导致的编译失败
```js
//const _IS_DEV = process.env.NODE_ENV = 'development';
const _IS_DEV = typeof process === 'object' && process.env.NODE_ENV === 'development'
```
