### ISSUE TITLE
怎么在tsx中使用jsxplus

### ISSUE THREAD

**Issue by mcc-stack** [alibaba/ice#4427]
按照官方文档添加了build-plugin-jsx-plus,但是在tsx文件中使用jsxplus,项目直接报错,该怎么解决(在jsx里是好的)

运行结果:
![image](https://user-images.githubusercontent.com/54461051/124093440-751b5680-da8a-11eb-9e85-cc0a3d69f9e0.png)

**Comment by FuzzyFade** [comment]
fixed
