### ISSUE TITLE
import导入的资源打包后publicPath未生效

### ISSUE THREAD

**Issue by maskTAQ** [alibaba/ice#4428]
## import或require导入的资源打包后publicPath未生效

> 导入图片

![image](https://user-images.githubusercontent.com/19301145/124101915-705aa080-da92-11eb-85dd-ee61e116d9fa.png)

>publicPath配置

![image](https://user-images.githubusercontent.com/19301145/124101997-86686100-da92-11eb-9eba-9ba1b260ce85.png)
![image](https://user-images.githubusercontent.com/19301145/124102081-9bdd8b00-da92-11eb-8f82-5313bc321c7a.png)

>打包后的资源地址

![image](https://user-images.githubusercontent.com/19301145/124102133-ab5cd400-da92-11eb-84a7-351f39a07d66.png)
![image](https://user-images.githubusercontent.com/19301145/124102189-b879c300-da92-11eb-9f2d-9c8bd7f6018b.png)

## What is the expected behavior? 期望的结果是什么？
打包后可以正确索引地址。

## 可以描述一下俩个地方配置的publicPath的差异性吗?
仅测试好像：
css中如果引用了背景图片publicPath由build.json配置确定,
生成的js文件由后端渲染时传入的publicPath确定
## Any additional comments? 相关环境信息？

- **ice.js Version**：
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by maskTAQ** [comment]
## 临时解决方案
```js
//dev.js
export const IS_DEV = typeof process === 'object' && process.env.NODE_ENV === 'development'

const publicPath = 'static';
export function path(v) {
    return IS_DEV || v.includes('base64') ? v : `${publicPath}${v}`
}
//组件
import a from './a.png';
<img src={path(a)} />
```

**Comment by ClarkXia** [comment]
https://ice.work/docs/config/about#publicpath

**Comment by maskTAQ** [comment]
> https://ice.work/docs/config/about#publicpath
> https://ice.work/docs/config/about#devpublicpath
> 两个配置用来区分构建和 dev，看你的表现应该是在 dev 下调试，添加下 devPublicPath

不是的在开发环境下`publicPath `工作正常，但是在打包时不生效

**Comment by imsobear** [comment]
`render()` 传入 publicPath 是个冗余的设计：https://github.com/alibaba/ice/issues/4418 ，我们把这个选项移除掉，都统一用 build.json 里的 devPublicPath/publicPath，是不是可以满足你的诉求？ @maskTAQ

**Comment by imsobear** [comment]
@maskTAQ 这个问题现在解决了吗？

**Comment by maskTAQ** [comment]
> @maskTAQ 这个问题现在解决了吗？

可以的，但是我还未更新版本。
