### ISSUE TITLE
升级到 1.18.2 后单元测试，不可以发现ice相关模块，还是报Cannot find module 'ice' from 'src/services/model.js',已提供dmo

### ISSUE THREAD

**Issue by linshaoye12345** [alibaba/ice#4433]
## Any additional comments? 相关环境信息？

- **ice.js Version**：
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by ClarkXia** [comment]
提供下复现 demo

**Comment by linshaoye12345** [comment]
Cannot find module 'ice/DataStore' from 'test/pages/DataStore/index.test.js'

      1 | import React from 'react';
    > 2 | import { store as pageStore } from 'ice/DataStore';
        | ^
      3 |
      4 | // 测试组件中存在store时，需要用provider包裹
      5 | const PageProvider = pageStore.Provider;

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (test/pages/DataStore/index.test.js:2:1)

**Comment by linshaoye12345** [comment]
[dmo.zip](https://github.com/alibaba/ice/files/6763528/dmo.zip)
@ClarkXia  问题dmo

**Comment by linshaoye12345** [comment]
![image](https://user-images.githubusercontent.com/61184465/124457990-0b1eec00-ddbf-11eb-9b90-f6ec00c67a1e.png)

**Comment by linshaoye12345** [comment]
问题1：点击上图run 按钮会报 Cannot find module 'ice' 。
问题2：运行npm run ice:coverage  不可以使用store。（ice版本为1.18.2）
问题dmo：
[dmo.zip](https://github.com/alibaba/ice/files/6766746/dmo.zip)

**Comment by ClarkXia** [comment]
测试代码里依赖了 `ice/DataStore` 不建议 测试依赖，这些内容都是依赖 npm start/build 之后生成在临时目录中的
store 使用方式推荐：https://ice.work/docs/guide/basic/store#%E9%A1%B5%E9%9D%A2%E7%BA%A7%E7%8A%B6%E6%80%81

**Comment by linshaoye12345** [comment]
之前你们给的建议是“测试内容中需要处理store时，需要用provider包裹”，所以测试代码中引用ice/DataStore，这种页面中含store 如何测试可以给我个建议吗？

**Comment by ClarkXia** [comment]
建议可以独立对组件进行 UI 测试，不要耦合过重的逻辑，上述 store 可以参考使用推荐方式，目前 jest 配置的 moduleNameMapper 有点问题，如果需要引入 ice 下内容建议添加如下配置：

```js
moduleNameMapper: {
    '^ice/(.*)$': '<rootDir>/.ice/pages/$1',
    '^ice': '<rootDir>/.ice',
},
```

后续我们也将优化到内置的 jest 配置中

**Comment by linshaoye12345** [comment]
> ```js
> '^ice/(.*)$': '<rootDir>/.ice/pages/$1',
>     '^ice': '<rootDir>/.ice',
> ```

好滴，感谢
