### ISSUE TITLE
前端接口代理无法命中

### ISSUE THREAD

**Issue by baikaishui01** [alibaba/ice#4449]
问题场景：本地分别启动后端与前端工程，由于端口不同导致的跨域场景。
前端两种proxy配置如下：
    配置一：
     
![image](https://user-images.githubusercontent.com/48601669/124916089-dc09b400-e024-11eb-9a51-4ffb810fc913.png)
    配置二：
![image](https://user-images.githubusercontent.com/48601669/124916196-f9d71900-e024-11eb-8564-23ec237819d4.png)
在采用配置二的情况下，代理无法命中。而在ice的官方文档中的说明是采用配置二，该项目也是通过ice的脚手架初始化的

**Comment by ClarkXia** [comment]
![image](https://user-images.githubusercontent.com/4219965/125444227-4de7a237-9b0f-43d0-8377-97123c6367e8.png)
添加配置二的 proxy 无法复现代理的问题，上图显示被正常代理，可以提供下相关的 demo 供复现

**Comment by imsobear** [comment]
@baikaishui01 是否可以提供个重现 demo？

**Comment by baikaishui01** [comment]
由于权限问题我目前也无法访问项目，不过项目是通过def平台进行初始化的

**Comment by baikaishui01** [comment]
> @baikaishui01 是否可以提供个重现 demo？

由于权限问题我目前也无法访问项目，不过项目是通过def平台进行初始化的

**Comment by imsobear** [comment]
@baikaishui01 通过命令行重新初始化一个能重现吗？不能重现的话这个 issue 先关闭了。

**Comment by baikaishui01** [comment]
> @baikaishui01 通过命令行重新初始化一个能重现吗？不能重现的话这个 issue 先关闭了。

暂时未能重现，先关闭了，日后再次出现该情况提供demo
