### ISSUE TITLE
[Question]如何动态加载远程组件

### ISSUE THREAD

**Issue by xmsz** [alibaba/ice#4450]
背景
- 我们系统有个应用中心，每个应用有自己的设置页
- 但是我们不想把设置页的代码放到系统代码里，因为应用有很多，且后续会开发给第三方
- 然后我们也不希望使用iframe
- 不希望使用第三方动态加载远程组件
- 因为我看见Ice可以动态修改微应用列表，那理论上支持动态加载组件也是一样的原因
-

需求
- 如何优雅的解决动态加载远程组件
- 希望可以动态加载远程组件

**Comment by maoxiaoke** [comment]
icestark 有一套动态组件方案，看下可以满足要求吗 https://micro-frontends.ice.work/docs/guide/micro-module

**Comment by xmsz** [comment]
感谢 感觉就是我想要的 我在ice.work文档上没找到
