### ISSUE TITLE
ice store替换

### ISSUE THREAD

**Issue by hioak** [alibaba/ice#4454]
你好，现在想使用redux的store来替换ice自带的store，但是在app.jxs中加入addProvider后出现异常。我用的ice版本为：
我的做法是：
1、停用ice库自带的store组件；
<img width="326" alt="图片" src="https://user-images.githubusercontent.com/3831083/125097513-ca99d800-e108-11eb-96d6-7fb20f8d8dc3.png">

2、在app.jsx中的appConfig对象中添加addProvide；
<img width="795" alt="图片" src="https://user-images.githubusercontent.com/3831083/125097645-eb622d80-e108-11eb-8302-beaa4048bf7a.png">

3、添加store后编译正常，但是运行时出现异常。
<img width="663" alt="图片" src="https://user-images.githubusercontent.com/3831083/125097901-26fcf780-e109-11eb-895a-5a7edae7cf64.png">

**Comment by luhc228** [comment]
项目是用 React@16.x 的吗？如果是，app.jsx 中要引入 React。
