### ISSUE TITLE
ESBuild 插件无法正常使用

### ISSUE THREAD

**Issue by FuzzyFade** [alibaba/ice#4455]
## 环境

**icejs** version: 1.18.1
**build-plugin-esbuild** version: 1.6.2

build.json 配置
```json
{
  "plugins": [
    "build-plugin-esbuild"
  ],
  "router": { "lazy": true }
}

```

## 现象
在 Command Build 时，Terminal 输出
```bash
WEBPACK Error: Invalid option: "optimize"
```

## 其他

关于 esbuild 插件使用的 ice 文档地址：https://ice.work/docs/plugin/list/esbuild

**Comment by ClarkXia** [comment]
build-plugin-esbuild 后面输出下 deprecate 信息，功能已经内置到 icejs 了
