### ISSUE TITLE
pdf引入，显示未找到

### ISSUE THREAD

**Issue by zjw4328217** [alibaba/ice#4463]
## What is the current behavior? 发生了什么？
在项目中引入pdf之后，报错
* @/assets/zkTube_Whitepaper.pdf in ./src/pages/WhitePaper/index.tsx

![image](https://user-images.githubusercontent.com/62387737/125419015-67ec037a-aae6-4d73-8bfd-6721bed3be8d.png)

To install it, you can run: npm install --save @/assets/zkTube_Whitepaper.pdf
## What is the expected behavior? 期望的结果是什么？
引入正确，页面可以展示
## Any additional comments? 相关环境信息？

- **ice.js Version**：1.0.0
- **build.json Configuration**：
"webpackLoaders": {
    "file": {
      "test": ".pdf$",
      "loaders": "file-loader"
    }
  }
- **Node Version**:14.17.3
- **Platform**:

**Comment by ClarkXia** [comment]
配置方式有点问题，参考如下配置

```json
{
  "plugins": [],
  "webpackLoaders": {
    "pdf": {
      "test":".pdf$",
      "loaders": {
        // 配置 options 如果有的话
        "file-loader": {},
      }
   }
  }
}

```

**Comment by zjw4328217** [comment]
谢谢啦
