### ISSUE TITLE
父应用访问子应用资源跨域

### ISSUE THREAD

**Issue by transitiongo** [alibaba/ice#4464]
![image](https://user-images.githubusercontent.com/26265969/125432918-257fcb00-ecf2-45c7-bb55-e9af3cf9836d.png)

之前也出现过这个问题，强刷一下就好了，
今天子应用部署线上 又出现了这个问题，回滚掉依然未解决

**Comment by ClarkXia** [comment]
跨域的网络请求跟框架本身关系不大，需要验证下 ppt.pelitem.com 域名接口的 access-control-allow-origin 的设置

**Comment by transitiongo** [comment]
好的，联系运维看下，其他之前也找过运维，他那边反馈配的* 我再找他看下
