### ISSUE TITLE
获取不到上一个tab的url

### ISSUE THREAD

**Issue by Gamehu** [alibaba/ice#4471]
## What is the current behavior? 发生了什么？

获取不到上一个tab的url

## What is the expected behavior? 期望的结果是什么？
![image](https://user-images.githubusercontent.com/10043320/125758349-d4da4032-fbbd-4c62-8d6e-68f39007f001.png)
如图，点击红色箭头时期望获取前一个tab页签的url，尝试解析history对象不过没发现历史有效的信息。

## Any additional comments? 相关环境信息？

- **ice.js Version**：1.18.0
- **build.json Configuration**：
- **Node Version**:v12.22.1
- **Platform**: Windows Chrome

**Comment by ClarkXia** [comment]
可以具体讲下使用场景，router 相关信息都会通过 props 传递，如果有类似诉求可以主动记录

**Comment by Gamehu** [comment]
> 可以具体讲下使用场景，router 相关信息都会通过 props 传递，如果有类似诉求可以主动记录

好的谢谢，就问问看有没有方式获取，我主动记录吧。
