### ISSUE TITLE
如何能够去掉 .ice的文件

### ISSUE THREAD

**Issue by wangzyeeeeee** [alibaba/ice#4473]
## What is the current behavior? 发生了什么？
目前使用ice Simple  想做一个轻量脚手架 ，请问.ice文件夹如何删除 

## What is the expected behavior? 期望的结果是什么？
能够将.ice文件夹删除

**Comment by ClarkXia** [comment]
.ice 目前下有项目开发所需的运行时依赖，如果不希望生成，工程层面提供了配置能力 https://ice.work/docs/config/about/#disableruntime 进行关闭，关闭后则需要自己处理项目入口的渲染，请谨慎选择
