### ISSUE TITLE
项目中自带的icon 都不显示了，应该如何排查问题

### ISSUE THREAD

**Issue by a426855a5a5** [alibaba/ice#4474]
![image](https://user-images.githubusercontent.com/28923151/125905128-4f6f2d3b-0511-4a2f-89ed-6509e009bc5b.png)
![image](https://user-images.githubusercontent.com/28923151/125905197-bbd6959a-3d58-4274-b944-5dc6276770c9.png)

**Comment by imsobear** [comment]
看下用的哪个主题包，主题包版本是多少

**Comment by a426855a5a5** [comment]
1.19.4

**Comment by a426855a5a5** [comment]
已经找到问题，我是代理了线上资源导致的，不是包的问题。
