### ISSUE TITLE
脚手架如何接入 build-scripts

### ISSUE THREAD

**Issue by wangzyeeeeee** [alibaba/ice#4475]
想请教一下 ，自己的脚手架如何能接入build-scripts 有没有相关文档 
## What is the expected behavior? 期望的结果是什么？
脚手架可以接入 build-scripts

**Comment by imsobear** [comment]
直接接 icejs 就行了，build-scripts 更底层。

**Comment by wangzyeeeeee** [comment]
我们想做一个更轻量的脚手架 基于build-scripts 
老板给的任务。。翻了一圈语雀 没有找到相关文档

**Comment by imsobear** [comment]
那研究下 ice-lab/build-scripts 的文档吧，这种不是我们推荐的链路，我们还是推荐项目直接用 icejs。

**Comment by wangzyeeeeee** [comment]
好的 谢谢 然后再请教一下 tnpm上的 
 @alib/build-scripts  和 build-scripts 是一个东西吗 
 我看作者都有  clarkxia 使用的话 我用哪个
