### ISSUE TITLE
@alib/build-scripts 和 build-scripts 有什么区别 

### ISSUE THREAD

**Issue by wangzyeeeeee** [alibaba/ice#4476]
## What is the current behavior? 发生了什么？

@alib/build-scripts 和 build-scripts 有什么区别 
 两个作者都有 clarkxia 在自己脚手架配置 应该用哪个
@alib/build-scripts  的源码链接方便发一下吗

**Comment by ClarkXia** [comment]
@alib/build-scripts 和 build-scripts 本质上是一个，借 build-scripts 1.x 升级的时机，启用更加简洁的包名 `build-scripts`。
代码和相关说明可以参考 https://github.com/ice-lab/build-scripts
