### ISSUE TITLE
工程接入build-scripts 显示 Config key 'entry' is not supported 

### ISSUE THREAD

**Issue by wangzyeeeeee** [alibaba/ice#4477]
## What is the current behavior? 发生了什么？
已有的脚手架接入 build-scripts ，start 之后 报错 
[Config File] Config key 'entry' is not supported 

![image](https://user-images.githubusercontent.com/67303799/126098034-92a2b647-e791-4fbe-91a4-53386dcd978b.png)
![image](https://user-images.githubusercontent.com/67303799/126098043-d07a8733-b4e7-4836-bacc-d58140c18b3e.png)

## What is the expected behavior? 期望的结果是什么？
能够通过build-scripts 搭建出来一个脚手架

**Comment by ClarkXia** [comment]
参考这部分说明 https://github.com/ice-lab/build-scripts#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6 

build-scripts 本身是解耦了工程流程，如果希望项目中使用需要通过插件定制项目 webpack 配置，推荐直接使用 icejs 的插件集
