### ISSUE TITLE
build-scripts 搭配 create react app 出现key不支持

### ISSUE THREAD

**Issue by wangzyeeeeee** [alibaba/ice#4482]
## What is the current behavior? 发生了什么？
 npm start的时候报出如下的错误
![image](https://user-images.githubusercontent.com/67303799/126153502-d1bff924-2558-4e13-ae99-59c2637be099.png)

![image](https://user-images.githubusercontent.com/67303799/126153519-31cc4f7e-576e-43c5-8544-cf138d35671d.png)

## What is the expected behavior? 期望的结果是什么？
能够不在报错 顺利打开项目

**Comment by ClarkXia** [comment]
参考 https://github.com/alibaba/ice/issues/4477#issuecomment-882205101
推荐用 icejs，如果非要自定义需要结合 build-scripts 提供的 API 定制基础配置和 webpack 配置
