### ISSUE TITLE
icestark 是否支持子应用路由按需加载？

### ISSUE THREAD

**Issue by fedorjia** [alibaba/ice#4487]
"主应用"通过 url 中放置：.js, .css 路径方式去加载"子应用"，如果"子应用"的路由是按需加载（可能会有多个js, css），这种情况该如何处理? 是否需要改为通过 entry 的配置加载“子应用” URL 入口（如 .html）实现吗？

例如 icestark “主应用” 通过如下配置加载“子应用”：

```
icestark: {
    type: 'framework',
    Layout: FrameworkLayout,
    getApps: async () => {
      const apps = [{
        path: '/waiter',
        title: '小二平台',
        sandbox: true,
        url: [
          'https://iceworks.oss-cn-hangzhou.aliyuncs.com/icestark/child-waiter-vue/dist/js/app.js',
          'https://iceworks.oss-cn-hangzhou.aliyuncs.com/icestark/child-waiter-vue/dist/css/app.css',
        ],
      }];
      return apps;
    },
  },
```

**Comment by maoxiaoke** [comment]
@fedorjia icestark url 方式支持 dynamic import，具体可参考 https://micro-frontends.ice.work/docs/faq#%E5%BA%94%E7%94%A8%E5%90%AF%E7%94%A8-lazy-%E5%90%8E%EF%BC%8Cchunk-%E5%8A%A0%E8%BD%BD%E5%A4%B1%E8%B4%A5
