### ISSUE TITLE
[SSR]<Head><title>title</title></Head>在服务端不生效

### ISSUE THREAD

**Issue by maskTAQ** [alibaba/ice#4491]
## [SSR]<Head><title>title</title></Head>在服务端不生效
服务端输出的title不是<Head><title>title</title></Head>声明的，代码只会在客户端运行的时候修改title

## What is the expected behavior? 期望的结果是什么？
<Head><title>title</title></Head>可以再服务端生效
## Any additional comments? 相关环境信息？

- **ice.js Version**：
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by luhc228** [comment]
https://ice.work/docs/guide/advanced/ssr#%E9%A1%B5%E9%9D%A2-meta-%E6%A0%87%E7%AD%BE
目前这样使用的话，有问题吗？

**Comment by imsobear** [comment]
> > https://ice.work/docs/guide/advanced/ssr#%E9%A1%B5%E9%9D%A2-meta-%E6%A0%87%E7%AD%BE
> > 目前这样使用的话，有问题吗？
> 
> 写法是一样的，但是不生效，吐出的html的title是public/index.html中声明的值

能提供个 demo 仓库吗？或者多给点代码看下。

**Comment by maskTAQ** [comment]
在`ice.js`版本为`1.18.2-beta.1`会出现此bug。当版本升级至`^1.18.3`得以解决。
