### ISSUE TITLE
[RFC] 可区分环境移除 log 语句

### ISSUE THREAD

**Issue by SoloJiang** [alibaba/ice#4493]
## 概述

希望开发者可以控制是否移除不必要的日志信息

## 背景

当前 icejs 提供的 Logger 方案，可以通过给 `runApp` 传递参数配置 `loglevel` 来控制日志输出级别，使用方式如下：

```jsx
import { runApp, APP_MODE, logger } from 'ice';

runApp({
  logger: {
    level: APP_MODE === 'build' ? 'error' : 'warn',
  }
});
```

当未传入 `level` 字段并且开启 `smartLoglevel` 可根据 url 参数中的 `__loglevel__` 动态控制日志输出级别。

**存在的问题：** 面向部分场景开发者希望能够在生产环境移除冗余 Log 代码，基于上述方案无法达到目标。

## 解决方案

**在当前 logger 运行时的配置基础上**支持在 build.json 进行如下配置：

```json
// 默认全部保留
{
  "dropLogLevel": "error"
}
```

上述配置仅在 npm run build 生效，生效时所有 error 以下的日志输出将会被移除。

### 配置

logLevel 和现有方案完全相同分为：
- trace
- debug
- info (alias log)
- warn
- error
- slient

可以通过 `modeConfig` 在不同环境下进行不同的移除操作，在移除相关 log 语句后，`smartLoglevel` 将会对这些级别的日志失效。

使用上不再通过 `import { logger } from 'ice'` 暴露，而是 **直接使用 `console.*`** 来进行日志输出。

## 方案设计

运行时不再依赖 loglevel，日志输出级别控制通过复写 `console.*` ，开发者也是直接使用 `console.*` 进行日志打印，`build` 阶段通过 Terser Plugin  的 `drop_console` 和 `pure_funcs` 移除和保留对应代码。

## 如何引导开发者使用

- 老方案直接移除替换为新方案
- 升级文档和配套的 codemod 工具

**Comment by imsobear** [comment]
- 解决方案是解决什么问题的？背景里完全没有说明问题是什么
- 新方案开发者除了配置项以外怎么调用？logLevel 有哪些选择？
- 老的方案后面是完全移除还是保留两套？

**Comment by SoloJiang** [comment]
> * 解决方案是解决什么问题的？背景里完全没有说明问题是什么
> * 新方案开发者除了配置项以外怎么调用？logLevel 有哪些选择？
> * 老的方案后面是完全移除还是保留两套？

已补充
