### ISSUE TITLE
支持开启/关闭 React StrictMode

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#4494]
## What is the current behavior? 发生了什么？

不支持开启 StrictMode

## What is the expected behavior? 期望的结果是什么？

支持开启 StrictMode

```js
import { runApp } from 'ice';

runApp({
  app: {
    strict: true,  // default: false
  }
})
```

## Any additional comments? 相关环境信息？

- **ice.js Version**：
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by ClarkXia** [comment]
已在 2.0 中支持
