### ISSUE TITLE
icejs X vite

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#4495]
## 开启 vite 模式

package.json

```diff
{
-   "ice.js": "^1.0.0",
+  "ice.js": "next"
}
```

build.json

```diff
{
+  "vite": true
}
```

## 整体进展

- [x] 基础工程能力适配
- [x] runApp: 渲染
- [x] SPA 场景 - pro 模版
- [x] MPA
- [x] 路由 @ClarkXia 
- [ ] SSR
- [x] Store @ClarkXia 
- [x] 微前端 icestark @ClarkXia 
- ……

**Comment by ClarkXia** [comment]
vite 模式配置能力对齐：
- [ ] publicPath & devPublicPath
- [ ] sourceMap
- [ ] externals
- [ ] hash
- [ ] polyfill
- [ ] minify
- [ ] outputAssetsPath (js/css)
- [ ] outputDir
- [ ] proxy
- [ ] vendor
- [ ] cssLoaderOptions
- [ ] lessLoaderOptions
- [ ] postcssOptions
- [ ] terserOptions
- [ ] ignoreHtmlTemplate
- [ ] ~eslint~
- [ ] ~tsChecker~
- [ ] esbuild
- [ ] webpack-plugin-import 注入组件样式的能力

**Comment by ClarkXia** [comment]
预编译阶段报错问题 
![image](https://user-images.githubusercontent.com/4219965/127828708-f2ed51dd-1c5a-401c-8ebb-888dde93cb7c.png)

**Comment by FuzzyFade** [comment]
SPA Pro 模版相关问题
- ven.js（fusion 引的某个依赖）内部存在 ../node_moudles/xxx.js 的引用现象，esbuild 默认报错
- scss 波浪线前缀问题（由于是新版模板，直接在模板中全部修复对应写法即可）
- 启动后没有样式，需要适配 webpack-plugin-import

**Comment by FuzzyFade** [comment]
minify / polyfill 配置 warning 提示

**Comment by ClarkXia** [comment]
icejs 在 vite 和 webpack v5 两种模式下目前遗留问题：

vite 模式：

- [ ] SSR 场景支持，目前已评估结合 vite SSR 的适配成本不高 @FuzzyFade 
- [ ] 业务上非标准的用法，比如 @import 样式出现 ~。（支持通过默认的 alias 设置解决）
- [ ] 对于 fusion 组件体系的支持 （组件按需✅，主题配置支持❌）
- [ ] 对齐一些特殊 babel-loader 的逻辑（raw-loader、url-loader 等）

webpack v5 模式：

- [ ] 非内置插件中 webpack 插件的 Deprecated Waring（优先级不高，主要为 plugin-wrap-code 等插件）
