### ISSUE TITLE
[Discussion] 插件运行时部分是否需要强制同步模式

### ISSUE THREAD

**Issue by SoloJiang** [alibaba/ice#4496]
### 背景

目前插件运行时部分的代码是在判断 `appConfig.app.getInitialData` 是否存在后 `await appConfig.app.getInitialData` 后执行，即流程图为：

![image](https://user-images.githubusercontent.com/14757289/126928812-ce10237a-f0b4-458c-a677-09fd9160ad9b.png)

此时，以 Logger 插件为例，是否存在 `appConfig.app.getInitialData` 会导致用户代码行为不一致，即同步模式 `runApp()` 执行完 Logger 的 `setLevel` 就生效了，异步模式时 `setLevel` 未生效。

由于路由和权限等插件需要依赖 `appConfig.app.getInitialData` 的返回结果，所以不能将插件一刀切成同步执行，可能需要划分成同步和异步两种？

**Comment by ClarkXia** [comment]
运行时插件设计上有 staticModule，比如 request 模块，在执行 runApp 的具体逻辑之前已经完成初始化

**Comment by SoloJiang** [comment]
ok，那 Logger 也应该移入到 staticModule 吧？

**Comment by SoloJiang** [comment]
在 Logger 新方案中已将该插件移入 staticModule
