### ISSUE TITLE
qiankun 主应用 集成 ice 子应用 使用  build-plugin-icestark 

### ISSUE THREAD

**Issue by qqqdu** [alibaba/ice#4504]
## What is the current behavior? 发生了什么？
qiankun 主应用 集成 ice 子应用中，开发环境正常，生产环境出错
  

在主应用中，使用 `npm run start`  的 `localhost/*`  作为入口，表现正常。可以看到 bootstrap 钩子函数打印出 `bootstrap` 信息，并且成功渲染到主应用中。 
 
而使用 `npm run build` 打包出静态资源部署之后的链接作为入口，子应用成功渲染到主应用中，但控制台打印报错如下（并且bootstrap 钩子未回调）：
![image](https://user-images.githubusercontent.com/19419834/127138583-134f418c-1213-4329-a0d2-62b1257c0e45.png)

## What is the expected behavior? 期望的结果是什么？
控制台不应该有这个报错
## Any additional comments? 相关环境信息？

- **ice.js Version**：1.0.1
- **build-plugin-icestark**： 2.1.0
- **build.json Configuration**：和官方文档一致
- **Node Version**:最新版本
- **Platform**: MAC OS

**Comment by maoxiaoke** [comment]
@qqqdu  dev 和 build 的构建配置有何不同吗？

**Comment by qqqdu** [comment]
> @qqqdu dev 和 build 的构建配置有何不同吗？

没有不同，同一套配置文件：
```javascript
module.exports = {
  publicPath: process.env.BUILD_PUBLIC_PATH || '/',
  minify: false, // 代表是否压缩代码
  plugins: [
    [
      'build-plugin-fusion',
      {
        themePackage: '@alifd/theme-design-pro',
      },
    ],
    [
      'build-plugin-antd',
      {
        importOptions: {
          libraryName: 'antd',
          libraryDirectory: 'es',
          style: true,
        },
      },
    ],
    [
      'build-plugin-moment-locales',
      {
        locales: [
          'zh-cn',
        ],
      },
    ],
    [
      "build-plugin-icestark",
      {
        "umd": true
      }
    ],
  ],
  proxy: {
    '/': {
      enable: true,
      target: 'http://xxx.xxx:8080'
    },
  },
};

```

**Comment by maoxiaoke** [comment]
@qqqdu 尝试在控制台执行打包后的代码，查看下 window 是否挂载了变量（默认为  window['npm 的包名']）。查看是否正确导出生命中周期函数。

**Comment by qqqdu** [comment]
> @qqqdu 尝试在控制台执行打包后的代码，查看下 window 是否挂载了变量（默认为 window['npm 的包名']）。查看是否正确导出生命中周期函数。  

![image](https://user-images.githubusercontent.com/19419834/127159199-a5301dcc-1c48-432b-b579-71949bae7455.png)  
控制台尝试执行打包文件后

**Comment by maoxiaoke** [comment]
@qqqdu 从这里看来，ice 这边打包出来的产物大概上没有什么问题的

**Comment by qqqdu** [comment]
> @qqqdu 从这里看来，ice 这边打包出来的产物大概上没有什么问题的。可以在 qiankun 咨询下问题

排查到问题了，我们子项目使用构建 script 标签的方式来加载入口脚本，在 `qiankun` 执行检测逻辑的时候入口脚本还未执行，改成 script cdn 引入就可以了
ice 工程
```html
 <script>
    (function(){ 
         var time=new Date().getTime();
         var e = document.getElementsByTagName("script")[0];
         var d = document.createElement("script");
         d.src = "******";
         d.type = "text/javascript";
         e.parentNode.insertBefore(d,e);
     })();
  </script>
```

**Comment by lbarakidouji** [comment]
> > @qqqdu 从这里看来，ice 这边打包出来的产物大概上没有什么问题的。可以在 qiankun 咨询下问题
> 
> 排查到问题了，我们子项目使用构建 script 标签的方式来加载入口脚本，在 `qiankun` 执行检测逻辑的时候入口脚本还未执行，改成 script cdn 引入就可以了 ice 工程
> 
> ```
>  <script>
>     (function(){ 
>          var time=new Date().getTime();
>          var e = document.getElementsByTagName("script")[0];
>          var d = document.createElement("script");
>          d.src = "******";
>          d.type = "text/javascript";
>          e.parentNode.insertBefore(d,e);
>      })();
>   </script>
> ```

想请问下，这个入口脚本是指子应用自定义的生命周期吗？
我们暂时也遇到了这个问题
