### ISSUE TITLE
TypeError: Cannot read property 'store' of null

### ISSUE THREAD

**Issue by Oroy188** [alibaba/ice#4513]
## What is the current behavior? 发生了什么？
在 View 中使用模型状态报错了 

![image](https://user-images.githubusercontent.com/49527956/127761931-101c6061-3c0b-42d4-8208-39c29590d3a8.png)
![image](https://user-images.githubusercontent.com/49527956/127761957-890afbfb-7cd9-477d-b7cc-23b99f1e4a15.png)
![image](https://user-images.githubusercontent.com/49527956/127761980-ddda882d-f45d-41a9-adfb-f41d839cd98a.png)
![image](https://user-images.githubusercontent.com/49527956/127762011-2ae713ac-2ebf-433e-a70e-bede73f8aaff.png)
引用时异常了，不知道为啥 ，官网上好像没啥别的配置
## Any additional comments? 相关环境信息？

- **ice.js Version**：
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by zhgt-shaozi** [comment]
你好，我碰到了和你一样的问题，请问你最后如何解决的呢？
