### ISSUE TITLE
build打包后，页面运行报regeneratorRuntime is not defined错误

### ISSUE THREAD

**Issue by zhongerdeng** [alibaba/ice#4518]
build.json文件默认配置为以下，用的官方模板，没动过
{
  "publicPath": "./",
  "eslint":false,
  "plugins": [
    [
      "build-plugin-fusion",
      {
        "themePackage": "@alifd/theme-design-pro"
      }
    ],
    [
      "build-plugin-moment-locales",
      {
        "locales": [
          "zh-cn"
        ]
      }
    ]
  ]
}

**Comment by zhongerdeng** [comment]
>  

- [ ] [@[](url)](url)

**Comment by zhongerdeng** [comment]
https://github.com/alibaba-fusion/materials/tree/master/scaffolds/scaffold-lite-js

**Comment by Oroy188** [comment]
兄弟 你怎么解决的
