### ISSUE TITLE
ice组件表单的colon属性传入colon，控制台会输出如下警告

### ISSUE THREAD

**Issue by rootsli** [alibaba/ice#4530]
组件文档说明该属性为bool类型，如下：
![image](https://user-images.githubusercontent.com/4099803/128678611-67d748d2-02f6-42cc-a830-ae06edef5609.png)

于是，在代码做如下引用：

![image](https://user-images.githubusercontent.com/4099803/128678708-304cb474-e820-4f15-94e4-bf72057f2243.png)

但控制台会报如下错误：

`
Warning: Received `true` for a non-boolean attribute `colon`.

If you want to write it to the DOM, pass a string instead: colon="true" or colon={value.toString()}.
    in form (created by Form)
    in Form (created by Config(Form))
    in Config(Form) (created by ForwardRef)
    in ScGpxReactFusionComponentPortal (created by ForwardRef)
    in div (created by ForwardRef)
    in ForwardRef (created by Tenders)
    in div (created by SaasLayout)
    in SaasLayout (created by ScGpxReactFusionComponentSubpageLayout)
    in ScGpxReactFusionComponentSubpageLayout (created by Tenders)
    in Tenders (created by WrapperedPageComponent)
    in WrapperedPageComponent (created by RouterWrapperedPage)
    in RouterWrapperedPage (created by WrapperedPageErrorBoundary)
    in WrapperedPageErrorBoundary (created by AuthWrapperedComponent)
    in AuthWrapperedComponent
    in Unknown (created by Context.Consumer)
    in Suspense (created by Context.Consumer)
    in Route (created by Routes)
    in Switch (created by Routes)
    in Routes (created by Context.Consumer)
    in div (created by Shell)
    in div (created by Shell)
    in Shell (created by Config(Shell))
    in Config(Shell) (created by BasicLayout)
    in section (created by Shell)
    in section (created by Shell)
    in section (created by Shell)
    in Shell (created by Config(Shell))
    in Config(Shell) (created by BasicLayout)
    in BasicLayout (created by Context.Consumer)
    in Route (created by Routes)
    in Switch (created by Routes)
    in Routes (created by IceRouter)
    in Router (created by IceRouter)
    in IceRouter
    in Unknown (created by App)
    in Provider (created by Provider)
    in Provider (created by AuthStoreProvider)
    in AuthStoreProvider
    in Provider (created by Provider)
    in Provider (created by StoreProvider)
    in StoreProvider
    in Unknown (created by App)
    in App
`

期望不输出警告。

**Comment by imsobear** [comment]
如还未解决，建议通过 https://fusion.design/feedback 反馈
