### ISSUE TITLE
支持关闭 request/logger 等运行时能力

### ISSUE THREAD

**Issue by YouHan26** [alibaba/ice#4536]
## What is the current behavior? 发生了什么？
ice.js默认就引入比较多的运行时插件，这些插件部分是业务不需要的，但是都会被打包进入，譬如：
auth-> store -> react-redux & immer

一个auth就能增加大概60～70kb的大小
类似的还有request、logger、helper、miniapp、helmet

## What is the expected behavior? 期望的结果是什么？
build.json增加自定义plugin列表配置，业务根据自己的诉求配置插件能力，当然，core这些插件还是不允许参数更改的。

**Comment by imsobear** [comment]
auth 和 store 支持在 build.json 关闭：

```
// 不需要 store&auth 的话建议一起关闭，auth 本身很小，只是因为依赖了 store 所以变大
{
  "auth": false,
  "store": false,
}
```

下面这几个理论上是 import 了才会引入。

**Comment by YouHan26** [comment]
@imsobear 是的，看源码是有相应的flag标识，但是业务基本都是mtop，强迫症表示request、logger这些也想干掉

**Comment by imsobear** [comment]
> @imsobear 是的，看源码是有相应的flag标识，但是业务基本都是mtop，强迫症表示request、logger这些也想干掉

嗯 其他几个我们先看下

**Comment by YouHan26** [comment]
另外如果可以的话，希望考虑下多环境判断能处理的更干净一些，pc页面现在打包也会有一部分其他环境的依赖，譬如mini-render等。
相较于universal的接口一致性，希望同时也提供最基础灵活的能力。封装总归会碰到泄漏。

**Comment by ClarkXia** [comment]
目前通过动态分析默认在 build 阶段优化
