### ISSUE TITLE
build-plugin-esbuild 问题

### ISSUE THREAD

**Issue by zzx0106** [alibaba/ice#4554]
### 环境
icejs version: 1.18.3
build-plugin-esbuild version: 1.6.2

build.json 配置
```

{
  "plugins": [
    "build-plugin-esbuild"
  ]
}
```
### 现象
在 Command Build 时，Terminal 输出
```
HookWebpackError: Invalid option: "optimize"
```
### 类似问题
https://github.com/alibaba/ice/issues/4455#issue-941184819
### 发现问题
初步判断，是build-plugin-esbuild/lib/index.js中的line:14的optimize: true这个配置的问题
![image](https://user-images.githubusercontent.com/23009081/129839153-9f68b6ce-6845-4002-b78d-afd304d5fd26.png)
因为esbuild-webpack-plugin/dist.index和esbuild/lib/main.js中均没有optimize这个属性
![image](https://user-images.githubusercontent.com/23009081/129839120-b8237207-aa8b-4f32-9cc8-d8cf3f142581.png)
### 测试问题
注释掉optimize:true属性后，发现程序能正常打包
![image](https://user-images.githubusercontent.com/23009081/129839450-3a139b5b-8e17-456e-84aa-7c54f1bd4e67.png)
![image](https://user-images.githubusercontent.com/23009081/129839451-b44a3f74-29e0-4d69-9c69-9477a07cf814.png)
### 解决问题
仿照build-plugin-esbuild重写一个插件，并去掉optimize字段

**Comment by ClarkXia** [comment]
https://ice.work/docs/config/about#esbuild esbuild 能力已内置，可以参考文档配置。
对于 esbuild 使用的优化，欢迎 PR 👏 贡献代码
