### ISSUE TITLE
微应用激活之后，切换非微应用的页面，index.html里head的css样式发生丢失

### ISSUE THREAD

**Issue by springot** [alibaba/ice#4561]
1、未激活微应用，进入非微应用页面：split的css在head里，style标签没有被处理为 icestark="static"。
![image](https://user-images.githubusercontent.com/26103913/130031912-69415ba6-fd3e-43de-a702-abd927cf987d.png)

2、激活微应用后，再次进去非微应用页面：split的css style标签被处理为 icestark="static"，此页面 style 样式丢失。
![image](https://user-images.githubusercontent.com/26103913/130032559-0e01d817-f950-412c-bb17-8911a16b96ab.png)

不清楚stark框架对于主应用的split css和微应用的 css是如何处理的，微应用激活之后，微应用挂载的dom节点之外的其他节点的css会丢失且不会对服务器请求这个css。

**Comment by maoxiaoke** [comment]
主应用 split css 指的是？icestark 框架不会对标记为 static 的资源进行移除，在切换微应用时，会对没有标记为 static 的js、css 资源进行移除。可通过 https://micro-frontends.ice.work/docs/api/ice-stark/#shouldassetsremove 这个字段来修改默认行为。

**Comment by springot** [comment]
这个问题已解决，产生的原因是主应用的部分页面使用了路由懒加载，在切换至微应用页面时，回到路由懒加载的页面，不会请求样式文件。这个问题在qiankun 也有出现，建议飞冰对这种情况优化一下。https://github.com/umijs/qiankun/issues/517

**Comment by yyyyffqqqq** [comment]
ice3.0 怎么解决的切换？
