### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by Oroy188** [alibaba/ice#4564]
![image](https://user-images.githubusercontent.com/49527956/130163556-999caead-a7f1-4bf4-9081-1e2a3e20aa4e.png)
打包后访问报错

**Comment by ClarkXia** [comment]
提供下 icejs 安装的版本以及系统环境等信息

**Comment by Oroy188** [comment]
> 确认下 icejs 安装的版本，最新版依赖已修复 window 系统下的兼容

![image](https://user-images.githubusercontent.com/49527956/130171572-a46d431a-9597-4062-b897-f657451c809e.png)
是这个版本吗

**Comment by ClarkXia** [comment]
嗯 这个版本没问题，@builder/user-config 的依赖版本也确认下，可以直接查看 node_modules 下的信息

**Comment by Oroy188** [comment]
> 嗯 这个版本没问题，@builder/user-config 的依赖版本也确认下，可以直接查看 node_modules 下的信息

![image](https://user-images.githubusercontent.com/49527956/130172184-38dbd085-71e7-4b59-a0c4-0840f33b258e.png)
是这个吧

**Comment by ClarkXia** [comment]
这个包修复了 regeneratorRuntime 的问题，版本应该是 0.3.9，你可以删除下依赖重新安装

**Comment by Oroy188** [comment]
> 这个包修复了 regeneratorRuntime 的问题，版本应该是 0.3.9，你可以删除下依赖重新安装

**Comment by Oroy188** [comment]
> > 这个包修复了 regeneratorRuntime 的问题，版本应该是 0.3.9，你可以删除下依赖重新安装

好  我试下   单独删除这个包 是吧

**Comment by ClarkXia** [comment]
嗯 都可以  简单操作可以全部重装

**Comment by Oroy188** [comment]
好了   谢谢了  社区现在进去了吗

**Comment by ClarkXia** [comment]
ok https://github.com/alibaba/ice readme 中有 钉钉群 管理员会定期审核
