### ISSUE TITLE
微前端 icestarkdemo进入angular菜单报错

### ISSUE THREAD

**Issue by livershi** [alibaba/ice#4566]
## What is the current behavior? 发生了什么？
https://ice.work/docs/guide/advanced/icestark/
按照此文档通过模板快速创建一个微前端的框架应用后，点击左侧angular菜单报错：index.js:1 [@ice/stark] microapp should export mount/unmout or register registerAppEnter/registerAppLeave.

   `{
  "name": "@icedesign/stark-layout-scaffold",
  "version": "0.1.0",
  "description": "微前端方案 icestark 的主应用模板，用于快速初始化主应用",
  "dependencies": {
    "@alifd/next": "^1.x",
    "@alifd/theme-design-pro": "^0.x",
    "@icedesign/container": "^1.x",
    "classnames": "^2.2.5",
    "moment": "^2.24.0",
    "prop-types": "^15.5.8",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  },
  "devDependencies": {
    "@iceworks/spec": "^1.0.0",
    "@types/react": "^17.0.2",
    "@types/react-dom": "^17.0.2",
    "build-plugin-fusion": "^0.1.0",
    "build-plugin-icestark": "^2.0.0",
    "build-plugin-moment-locales": "^0.1.0",
    "eslint": "^7.30.0",
    "ice.js": "^1.0.0",
    "stylelint": "^13.7.2"
  },
  "scripts": {
    "start": "icejs start",
    "build": "icejs build",
    "lint": "npm run eslint && npm run stylelint",
    "eslint": "eslint --cache --ext .js,.jsx,.ts,.tsx ./",
    "eslint:fix": "npm run eslint -- --fix",
    "stylelint": "stylelint \"**/*.{css,scss,less}\""
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/ice-lab/react-materials/tree/master/scaffolds/icestark-layout"
  },
  "private": true,
  "originTemplate": "@icedesign/stark-layout-scaffold"
}
`

## What is the expected behavior? 期望的结果是什么？
     点击菜单不报错
## Any additional comments? 相关环境信息？

- **ice.js Version**：^1.0.0
- **build.json Configuration**：{
  "plugins": [
    [
      "build-plugin-icestark",
      {
        "uniqueName": "frameworkJsonp"
      }
    ],
    [
      "build-plugin-fusion",
      {
        "themePackage": "@alifd/theme-design-pro",
        "themeConfig": {
          "nextPrefix": "next-icestark-"
        }
      }
    ],
    [
      "build-plugin-moment-locales",
      {
        "locales": [
          "zh-cn"
        ]
      }
    ]
  ]
}
- **Node Version**：14.0
- **Platform**:windows

**Comment by maoxiaoke** [comment]
近期，我们会更新 angluar 应用的接入指导 https://github.com/ice-lab/icestark/pull/368#issuecomment-903205291，从目前 entry 接入的方式转成官方推荐的接入方式

**Comment by livershi** [comment]
谢谢
