### ISSUE TITLE
使用 yarn 进行包管理后启动项目提示缺少 react-router

### ISSUE THREAD

**Issue by FuzzyFade** [alibaba/ice#4569]
## What is the current behavior? 发生了什么？

使用 yarn 进行安装之后，使用 yarn start（icejs start）启动，在 webpack 编译到一半时报错，提示缺少 react-router
![image](https://user-images.githubusercontent.com/25416941/130383018-6f143907-1051-4435-8030-0315eb8033d8.png)

## Any additional comments? 相关环境信息？

- **ice.js Version**：1.8.3
- **build.json Configuration**: 
```json
{
  "esbuild": {
    "target": ["es2015"]
  },
  "hash": true,
  "modularImportRuntime": true,
  "plugins": [
    [
      "build-plugin-antd",
      {
        "importOptions": {
          "libraryName": "antd-mobile",
          "libraryDirectory": "es",
          "style": true
        }
      }
    ]
  ]
}

```
- **Node Version**: 14.16.1
- **Platform**: MacOS

**Comment by FuzzyFade** [comment]
存量的[脚手架](https://github.com/ice-lab/react-materials/tree/master/scaffolds/simple) 也同样透出相同错误

**Comment by FuzzyFade** [comment]
yarn version 1.10

**Comment by FuzzyFade** [comment]
解决进度：可能和 yarn 版本有关

**Comment by ClarkXia** [comment]
2.0 模版已修复，需要针对 1.x 进行修复

**Comment by ClarkXia** [comment]
2.x 模版已修复，存量 1.x 项目推荐升级到 2.x
