### ISSUE TITLE
ice 脚手架 icejs builder 在 css 文件带有中文时打包出来会乱码

### ISSUE THREAD

**Issue by ibeizhu** [alibaba/ice#4581]
css 代码
`   
 .title {
      font-weight: bold;
      font-family: '阿里巴巴普惠体';
    }
`

构建打包结果：
font-family:é˜¿é‡Œå·´å·´æ™®æƒ ä½“}

**Comment by ClarkXia** [comment]
暂时无法简单复现，可以先按上述回复排查，如果还是有问题再重开 issue
