### ISSUE TITLE
地图marker点击事件中的变量一直不更新

### ISSUE THREAD

**Issue by God-gill** [alibaba/ice#4583]
function initMarker(data) {
    let markers = new L.MarkerClusterGroup()
    data.forEach((item) => {
      let marker = L.marker([item.lat, item.lng], {
        icon,
      })
      marker.on('click', () => {
        console.log(globalState.isShowBinDetail) // 这块这个值一直是初始值，即使我一直在改变他
        globalDispatchers.update({
          isShowBinDetail: true,
          detailType: item.type,
          selectId: item.id
        })
      })
      markerMap.set(item.id, item)
      markers.addLayer(marker)
    })
    mapInstance.addLayer(markers)
  }

**Comment by ClarkXia** [comment]
仅通过上述的代码片段，无法确定问题，可以考虑提供完整 demo

**Comment by ClarkXia** [comment]
提供 demo 后重开 issue

**Comment by God-gill** [comment]
等我再遇到的时候提
