### ISSUE TITLE
状态管理引入createStore，显示没有依赖

### ISSUE THREAD

**Issue by is-cool** [alibaba/ice#4589]
在ice引入createStore，显示有这个function，

<img width="576" alt="截屏2021-08-31 16 32 45" src="https://user-images.githubusercontent.com/78067806/131470048-1e7985fe-25e6-416a-bc9b-13850842c48c.png">
![截屏2021-08-31 16 33 53](https://user-images.githubusercontent.com/78067806/131470246-7b2efcab-3dc1-463f-af30-b596b47ee9a5.png)

状态管理使用有问题，完全按照文档操作。可以看一下嘛

**Comment by is-cool** [comment]
打印结果为undefined

**Comment by FuzzyFade** [comment]
See https://github.com/alibaba/ice/issues/4510#issuecomment-889181860

**Comment by is-cool** [comment]
> @is-cool See [#4510 (comment)](https://github.com/alibaba/ice/issues/4510#issuecomment-889181860)

Yes, thanks
