### ISSUE TITLE
themeConfig被覆盖导致不生效

### ISSUE THREAD

**Issue by haoxiaoshu6** [alibaba/ice#4594]
![image](https://user-images.githubusercontent.com/23648457/131813822-826fbf79-0c5e-462a-ba55-db25fce5a872.png)
![image](https://user-images.githubusercontent.com/23648457/131813909-55b05a90-ad81-4bb7-8072-68aa3e74a6fd.png)
![image](https://user-images.githubusercontent.com/23648457/131814016-d9b3be78-aed9-49f4-bc0e-0f7c81d4515e.png)

**Comment by ClarkXia** [comment]
确认下 index.css 中的 ant-btn-primary 是什么地方引入的

**Comment by haoxiaoshu6** [comment]
node-modules/antd/es/button/style/index.css.  是说这个吗

**Comment by ClarkXia** [comment]
提供的截图看着像是同时引入了 css 和 less 文件，导致覆盖，如果自己无法定位可以提供下复现的 demo

**Comment by haoxiaoshu6** [comment]
找到原因了，是因为我们有自己的业务组件库，是基于antd封装的，引入了自己业务组价库的css文件导致的 ，这个要怎么处理呢

**Comment by ClarkXia** [comment]
样式根据引入的顺序会存在一定的覆盖关系，如果期望使用 less 的样式定制能力，自己的业务组件在引入的时候需要引入 less，而不是 css
