### ISSUE TITLE
首页的适配问题

### ISSUE THREAD

**Issue by JJYing** [alibaba/ice#461]
提在这里不知道是不是合适……

![img_1776](https://user-images.githubusercontent.com/494562/39669232-459dc770-5118-11e8-8f25-d883e3d3cd95.png)

![img_1777](https://user-images.githubusercontent.com/494562/39669234-493c6198-5118-11e8-9c5c-0ed5986fdeb3.png)

**Comment by noyobo** [comment]
@yujiangshui 看看？

**Comment by yujiangshui** [comment]
感谢反馈，我处理下

**Comment by yujiangshui** [comment]
已发布，感谢反馈。
