### ISSUE TITLE
error in rxjs dependencies resolving

### ISSUE THREAD

**Issue by tarnishablec** [alibaba/ice#4613]
## What is the current behavior? 发生了什么？

![image](https://user-images.githubusercontent.com/42984497/132635031-0b8e0ff5-f1ef-4765-ab8b-17bb6c11ce08.png)

## Any additional comments? 相关环境信息？

- **ice.js Version**：latest
- **build.json Configuration**：default
- **Node Version**: v14
- **Platform**:  macoc

**Comment by ClarkXia** [comment]
提供一个复现的 demo

**Comment by tarnishablec** [comment]
只要项目引入了rxjs v7 版本就会出现问题，降级到6.6.7之后就没问题了
