### ISSUE TITLE
在 ICE下使用 Formily ，如何引入样式

### ISSUE THREAD

**Issue by Z8264** [alibaba/ice#4615]
如果不单独引入 @import '@alifd/next/dist/next.css'；则没有Fusion组件的样式，Formily组件无法正常显示。

如果手动引入，在同时使用Fusion组件时，会造成样式重复加载。

怎么解？

**Comment by ClarkXia** [comment]
使用的是 @formily/next ？ 类似 @alifd/next 进行按需加载配置即可，参考 https://ice.work/docs/plugin/list/modular-import

**Comment by Z8264** [comment]
能提供一个在ICE下面，正确使用 Formily 2.0 的 例子吗 ？如何引入样式才不和 @alifd/next  按需加载 导致重复引入样式。

**Comment by imsobear** [comment]
我来看下这个问题

**Comment by Z8264** [comment]
@imsobear formily 如何引入样式？这个有进展吗～～

**Comment by imsobear** [comment]
> @imsobear formily 如何引入样式？这个有进展吗～～

明天

**Comment by imsobear** [comment]
@Z8264 确认两个问题：

1. 你是否有主题定制诉求？
2. 我建议全量引入 fusion 的样式，按需意义不大，你觉得这个有问题没？

**Comment by Z8264** [comment]
@imsobear
1  主题定制这个是有诉求的
2.可以全量引入。主要如何全量引入呢？是指不使用build-plugin-fusion插件，手动引入fusion吗？如何在ICE下实施。

**Comment by imsobear** [comment]
@Z8264 https://github.com/imsobear/icejs-formily-v2 看这里，README 里写的比较详细了，应该可以解决你的问题。

**Comment by imsobear** [comment]
后面插件会做一个大版本升级，重新设计下这块，在这之前可以直接用上面 README.md 里写的方案，对工程什么的没依赖。
