### ISSUE TITLE
axios 版本过低

### ISSUE THREAD

**Issue by guoyunhe** [alibaba/ice#4636]
## What is the current behavior? 发生了什么？

```
npm WARN deprecated axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
```

```
$ tnpm list axios
└─┬ ice.js@1.18.5
  └─┬ build-plugin-ice-request@1.7.8
    └── axios@0.19.2
```

## What is the expected behavior? 期望的结果是什么？

更新到 0.21.4

## Any additional comments? 相关环境信息？

- **ice.js Version**：1.18.5
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by imsobear** [comment]
@ClarkXia 看下，icejs 2.0 也是 0.19，感觉版本问题还是没 check 全。

**Comment by imsobear** [comment]
@guoyunhe icejs 2.0 已升级到 axios 最新版本，有需求的话建议按照文档升级到 icejs 2.0：https://ice.work/docs/guide/upgrade#%E4%BB%8E-icejs-1x-%E5%8D%87%E7%BA%A7

因为这个升级可能会产生 break change，因此 icejs 1.0 不计划升级这个版本。

**Comment by xmsz-stu** [comment]
为啥我的是版本锁定在了    "ice.js": "^2.6.6",
dependencies:
axios 1.4.0
