### ISSUE TITLE
主应用路由没问题，子应用的自身路由里没展开的导航点击却没有反应

### ISSUE THREAD

**Issue by xiazefeng** [alibaba/ice#4638]
利用自身模版建了个主应用，  分别用icestark-child 和 fusion pro 建了两个子应用。  两个子应用分别打包放到本地nginx上，然后启动主应用。调试了一天，差不多处理好了。但是突然发现 fusion pro的子应用 自身的路由好像有点问题。

![11111111](https://user-images.githubusercontent.com/47770130/133585776-34a20212-a1b9-4005-b3ad-cbecaf7f8efc.gif)
如图，首次进来，在主应用home 导航下   
点击进入fusion导航（fusion pro子应用）  子应用自身路由正常，没问题。
点击商家平台（icestark-child 子应用），正常
再次点击fusion导航，
### **就发现子应用自身的路由，没展开的就点击不了。 展开了的，点击有效果，但是会自动刷新整个主应用，**
然后刷新完自身子应用路由也全部可以了。
请问这种情况子应用自身的路由失效是什么情况。
有热心大哥解答一下吗？

### 下面是主应用入口配置图，
![1A16DB97-4BD5-43c3-8CCB-8A9F2B8A7562](https://user-images.githubusercontent.com/47770130/133587565-0ad0aff6-9719-4dbf-82ba-3ab67af1e3d9.png)

### fusion-pro 子应用接入的配置
![D37F22FA-3D16-4843-91EF-07DC0DB3DA73](https://user-images.githubusercontent.com/47770130/133587741-209b6d5f-a62b-41f2-9552-a6affb43d0d7.png)

**Comment by maoxiaoke** [comment]
我看控制台也没啥错误，方便上次 demo 给我排查一下吗

**Comment by xiazefeng** [comment]
> 我看控制台也没啥错误，方便上次 demo 给我排查一下吗

可以的，明天我整理下明天原封不动放上去。可能设计几个项目，看看有问题你再给我指点指点，才自学入坑。

**Comment by xiazefeng** [comment]
> 我看控制台也没啥错误，方便上传 demo 给我排查一下吗

主应用  https://github.com/xiazefeng/xzf-center
子应用  https://github.com/xiazefeng/xzf-fusion-pro
install 后分别 启动一下就出来了。
多下别的子应用，再回到fusion-pro子应用，就会发现没展开的菜单点击无效。

**Comment by xiazefeng** [comment]
我之前是用的自定义的mount 和unmount 的子应用的接入主应用的。      刚才试了下用build-plugin-icestark 插件的方式，发现可以，**### 没有问题了。** 打扰了
