### ISSUE TITLE
mac上第一次启动飞冰闪退，打不开

### ISSUE THREAD

**Issue by deimo** [alibaba/ice#464]
系统版本如下
![image](https://user-images.githubusercontent.com/17610142/39748483-c35851b4-52e2-11e8-8327-d4c0567aabf3.png)
报错信息如下

![image](https://user-images.githubusercontent.com/17610142/39748667-3b4ab7de-52e3-11e8-9484-c3fb8b9ab9c6.png)

**Comment by noyobo** [comment]
看起来像是文件缺失了。 重装后能好么？

**Comment by davecat** [comment]
同上。

**Comment by oukan** [comment]
第一次打开会出现这样情况，第二次打开就好了。

**Comment by qbmiller** [comment]
楼上正确, 我原先某个软件也是这情况,不过是升级nodejs 好的. 可做以后参考

**Comment by noyobo** [comment]
@deimo 2.0.3 版本修复了改问题 https://iceworks.oss-cn-hangzhou.aliyuncs.com/mac/Iceworks-2.0.3.dmg ， 麻烦你再看看。

**Comment by deimo** [comment]
@noyobo 谢谢大佬，新下载你指定的版本后，没问题了
