### ISSUE TITLE
模块 "ice" 没有导出的成员 "createStore"

### ISSUE THREAD

**Issue by ClarkXia** [alibaba/ice#4646]
## 现状

由于框架的导出 API 默认通过工程启动时动态生成，导致项目在未运行 `npm start / build` 的情况下，默认无法获取任何 API 的提升

![image](https://user-images.githubusercontent.com/4219965/133869935-63320908-ceaa-43a8-93a9-74fa0aa1a9d1.png)

期望初始化的时候能够获取良好的类型提示

## 方案

框架安装时默认生成针对 ice 模块的 `d.ts` 类型声明

### 具体设计

TODO

**Comment by usercao** [comment]
![image](https://user-images.githubusercontent.com/13760476/148902537-c8311163-cedd-4740-8fc8-a78f2633afe7.png)
@imsobear 创建不包含任何UI库的纯净项目，此问题依然存在。

**Comment by imsobear** [comment]
https://github.com/alibaba/ice/issues/5018#issuecomment-987771972 @usercao

**Comment by WuDuShanCheng** [comment]
我也是初始化之后 就这样了 找不到createStore
