### ISSUE TITLE
vite模式下无法显示fusion主题扩展图标

### ISSUE THREAD

**Issue by Ryokai96** [alibaba/ice#4648]
## What is the current behavior? 发生了什么？
开启vite模式后，无法显示主题中的扩展图标

开启vite模式后，引入Icon组件\<Icon type="alibaba" /\>无法显示主题中的扩展图标alibaba，而\<Icon type="smile" /\>这些自带图标可以正常显示，关闭vite模式后\<Icon type="alibaba" /\>可以正常显示

## What is the expected behavior? 期望的结果是什么？
开启vite模式后，扩展图标可以正常显示

## Any additional comments? 相关环境信息？

- **ice.js Version**：2.0.0
- **build.json Configuration**：
  ```json
  {
    "vite": true,
    "plugins": [
      [
        "build-plugin-fusion",
        {
          "themePackage": "@alifd/theme-design-pro"
        }
      ]
    ]
  }
  ```
- **Node Version**: v14.15.4
- **Platform**:

**Comment by ClarkXia** [comment]
问题已修复可以先通过 beta 版提前尝试  build-plugin-fusion@0.1.19-beta.1
