### ISSUE TITLE
如何在service中更新model的state

### ISSUE THREAD

**Issue by HengzheLi** [alibaba/ice#4649]
调用service获取服务端的之后想更新本地store中的mode的state，使用dispatcher来调用model的reducer来更新，但是一致报错说
···
Invalid hook call. Hooks can only be called inside of the body of a function component
···

有什么别的办法在不使用hooks的情况下从model的外部更新model的state吗？

**Comment by luhc228** [comment]
@HengzheLi 是按照这里的使用方式？
https://ice.work/docs/guide/basic/request/#%E5%9C%A8%E6%A8%A1%E5%9E%8B%E4%B8%AD%E8%B0%83%E7%94%A8-service

**Comment by imsobear** [comment]
@HengzheLi 提供下关键代码，看看你怎么写的。

**Comment by HengzheLi** [comment]
@imsobear

这个是我的实例代码
···
import { request } from 'ice';
import appConfig from '@/models/appConfig';
import store from '@/store';

export default {
  async openIdLogin(username: string, password: string) {
    const res = await request({
      url: '/connect/token',
      data: {
        grant_type: 'password',
        client_id: appConfig.state.appId,
        username,
        password,
      },
    });
    const [userState, userDispatcher] = store.useModel('user');
    userDispatcher.update({ state: res.data });
    return res;
  },
};
···

**Comment by imsobear** [comment]
在非 React 组件里是没法使用 React Hooks(useModel) 的，因此也没法更新状态，我的建议是：service 职责应该清晰，就是获取&处理服务端接口数据的，如果要操作 UI 状态（包含 model），要么直接在 React 组件里做，要么就封装成一个自定义 hooks。

另外上面直接用 appConfig.state.appId 也不是正确的用法，因为丢失了监听变化的能力，通过参数传递进来更合理。
