### ISSUE TITLE
2.0 版本问题记录

### ISSUE THREAD

**Issue by ClarkXia** [alibaba/ice#4652]
- [x] swc 预编译 #4602 
- [x] icestark 2.6.0 版本发布，支持 esm 模式的开发模版 https://github.com/ice-lab/icestark/pull/369
- [x] 模版依赖从 rc 切换支持正式版本
- [ ] vite 模式下高优先级能力对齐（eslint、tsChecker、moment-locals、css-assets-locals）#4647

**Comment by imsobear** [comment]
- [ ] faas 模板切换 2.0 发布
