### ISSUE TITLE
webpack 5 不再自动 polyfill Node.js 的核心模块，在build.plugin.js 如何配置

### ISSUE THREAD

**Issue by hugo1o1** [alibaba/ice#4654]
![image](https://user-images.githubusercontent.com/30338290/134313399-da7ed667-c36d-45fd-8614-e2a99bf3afcd.png)

**Comment by ClarkXia** [comment]
build-plugin-ice-app 已不再维护，并且使用 icejs 的情况下不需要这个插件

**Comment by hugo1o1** [comment]
应该怎么添加wepack 配置呢

**Comment by ClarkXia** [comment]
可以直接通过类似 alias 的设置，比如：

```js
config.resolve.alias.set('path', 'path-browserify');
```

**Comment by vision-yip** [comment]
从1.7.2升级到2.0.0, 也有类似报错;
node: 14.16.0;
npm: 6.14.11;
build.js:
`
mpa: {
    openPage: 'auth',
  },
  devPublicPath: config.devPublicPath,
  publicPath: config.proPublicPath,
  alias: {
    '@public': './public',
    '@config': './project.config.js',
  },
  plugins: [
    [
      'build-plugin-moment-locales',
      {
        locales: ['zh-cn'],
      },
    ],
  ],
  sassLoaderOptions: {
    prependData: `
      @import "./src/assets/sass/theme.scss";
    `,
  },
  proxy: proxys,
`

**Comment by vision-yip** [comment]
从1.7.2升级到2.0.0, 也有类似报错;
node: 14.16.0;
npm: 6.14.11;
build.js:
`
mpa: {
    openPage: 'auth',
  },
  devPublicPath: config.devPublicPath,
  publicPath: config.proPublicPath,
  alias: {
    '@public': './public',
    '@config': './project.config.js',
  },
  plugins: [
    [
      'build-plugin-moment-locales',
      {
        locales: ['zh-cn'],
      },
    ],
  ],
  sassLoaderOptions: {
    prependData: `
      @import "./src/assets/sass/theme.scss";
    `,
  },
  proxy: proxys,
`

**Comment by ClarkXia** [comment]
@vision-yip 类似问题具体指什么，大部分场景下 node 模块的代码都不应该出现在浏览器端。可以给出具体需要 fallback 的错误信息

**Comment by vision-yip** [comment]
> @vision-yip 类似问题具体指什么，大部分场景下 node 模块的代码都不应该出现在浏览器端。可以给出具体需要 fallback 的错误信息

@ClarkXia https://github.com/alibaba/ice/issues/4689

**Comment by lilithyang2018** [comment]
请问在ice3里如何配置webpack的fallback？
