### ISSUE TITLE
【咨询】icework能不能设置HTTP代理

### ISSUE THREAD

**Issue by xzhnick** [alibaba/ice#467]
icework能不能设置HTTP代理，在公司内网无法连接市场

**Comment by noyobo** [comment]
@xzhnick  没有网络代理功能，你可以配置电脑的代理。

**Comment by yuanyan** [comment]
@noyobo 存在用户只想配置某个软件的网络代理吗？ 比如配了全局所有网络都走了公网反而有问题

**Comment by noyobo** [comment]
嗯，用户希望的场景应该是 iceworks 单独配置网络代理功能，公司内网屏蔽了 alicdn.com，导致物料请求失败。

**Comment by xzhnick** [comment]
@noyobo  是的，就像npm一样，可以单独配置代理服务器

**Comment by shellbark** [comment]
很需要这个功能，希望能加进来

**Comment by dingyiming** [comment]
很需要这个功能，希望能加进来

**Comment by imsobear** [comment]
@xzhnick npm 这个功能具体是怎么使用的？我们考虑借鉴下

**Comment by imsobear** [comment]
> 使用浏览器访问 http://ice.alicdn.com/assets/vue-materials.json 是可以的，因为浏览器走了代理。但是在飞冰上无法设置代理，导致请求不到。
控制台报错信息：物料请求失败，地址: http://ice.alicdn.com/assets/vue-materials.json ，错误：Error: connect ETIMEDOUT 180.97.245.253:80

**Comment by ycp424c** [comment]
求代理配置 +1

**Comment by imsobear** [comment]
确认方案是剥离这块网络依赖，issue 统一到 #1321
