### ISSUE TITLE
model 状态单元测试，createStore 报错

### ISSUE THREAD

**Issue by linshaoye12345** [alibaba/ice#4684]
错误截图：
![image](https://user-images.githubusercontent.com/61184465/134608293-13981889-484b-4dc7-ba69-5025b73b41f0.png)

jest配置：
module.exports = {
  // 测试环境设置
  testEnvironment: 'jsdom',
  verbose: true,
  preset: 'ts-jest',
  transform: {
    // 将.js后缀的文件使用babel-jest处理
    '^.+\\.js$': 'babel-jest',
    '^.+\\.jsx?$': 'babel-jest',
    '^.+\\.ts$': 'ts-jest',
    '^.+\\.tsx?$': 'ts-jest',
  },
  transformIgnorePatterns: [
    'node_modules/(?!(@alifd|react-dnd|dnd-core|jsdom|react-dnd-html5-backend|@riil-frontend)/)',
  ],
  collectCoverage: true,
  collectCoverageFrom: ['src/**/*.{js,jsx,ts,tsx}', '!**/node_modules/**'],
  roots: ['<rootDir>/test/'],
  // 设置单元测试的范围：文件、目录，可多个
  testMatch: ['<rootDir>/test/**/*.test.{js,jsx}'],
  setupFilesAfterEnv: ['<rootDir>/test/setup/rtl.js'],
  setupFiles: ['<rootDir>/test/setup/setupTests.js'],
  testPathIgnorePatterns: ['<rootDir>/.ice/', '<rootDir>/node_modules/'],
  coveragePathIgnorePatterns: ['<rootDir>/.ice/', '<rootDir>/node_modules/'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^ice/(.*)$': '<rootDir>/.ice/pages/$1',
    '^ice': '<rootDir>/.ice',
    // ice: '<rootDir>/.ice/index.ts',
    // '^ice/(.*)$': '<rootDir>/.ice/pages/$1',
  },
  snapshotSerializers: ['enzyme-to-json/serializer'],
  //  typeAcquisition: {
  //    include: ['jest'],
  //  },
};

**Comment by linshaoye12345** [comment]
[dmo.zip](https://github.com/alibaba/ice/files/7221863/dmo.zip)

**Comment by linshaoye12345** [comment]
dmo目录：
![image](https://user-images.githubusercontent.com/61184465/134608794-c4ded9b9-5bed-44ff-a4f9-65eebe4d0eef.png)

**Comment by linshaoye12345** [comment]
[dmo2.zip](https://github.com/alibaba/ice/files/7222185/dmo2.zip)

**Comment by linshaoye12345** [comment]
[dmo2.zip](https://github.com/alibaba/ice/files/7222185/dmo2.zip)

**Comment by imsobear** [comment]
@linshaoye12345 你是怎么跑单测命令的

**Comment by linshaoye12345** [comment]
![image](https://user-images.githubusercontent.com/61184465/134623268-99f86c9a-8923-402f-8879-6980e1cdec44.png)

**Comment by linshaoye12345** [comment]
@imsobear  点击run

**Comment by imsobear** [comment]
这个 run 调的是什么命令，不太懂，按道理应该走 `icejs test` https://ice.work/docs/guide/advanced/test

**Comment by imsobear** [comment]
我这两天弄个 demo 你直接参考下吧

**Comment by imsobear** [comment]
@linshaoye12345 transformIgnorePatterns 加一个 `@ice` 以使用 babel 编译里面的 esmodule 语法：

```
transformIgnorePatterns: [
  'node_modules/(?!(@alifd|react-dnd|dnd-core|jsdom|react-dnd-html5-backend|@riil-frontend|@ice)/)',
],
```

**Comment by imsobear** [comment]
https://github.com/alibaba/ice/issues/4697 这个问题的分析。

另外推荐用 `icejs test`，而不是直接用 jest，icejs test 会内置一些必要的工程配置。
