### ISSUE TITLE
jest 与 babel-jest 版本匹配问题

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#4686]
问题：

- babel-jest 目前是内置依赖，版本是 25.x，最新版本是 27.x
- jest 需要开发者自己安装，最新是 27.x，27.x 的 jest 和 25.x 的 babel-jest 一起使用会报错

目标：

- 保证两个版本的一致性

方案（二选一）：

1. jest 本身也依赖了 babel-jest，所以是不是不需要内置？
2. 内置的 babel-jest 升到最新 27 版本，jest 也告知开发者用 27 版本

**Comment by ClarkXia** [comment]
推荐项目自身依赖 jest 和 babel-jest
