### ISSUE TITLE
why set publish registry as registry.npmjs.com rather than registry.npm.org in auto-generated package.json?

### ISSUE THREAD

**Issue by sjy** [alibaba/ice#469]

**Comment by noyobo** [comment]
没太理解， 你指 iceworks 还是 物料 ? @sjy

**Comment by sjy** [comment]
物料 
![image](https://user-images.githubusercontent.com/1523060/39859569-d3667ca8-546c-11e8-98e2-888ade6fb8aa.png)

**Comment by yuanyan** [comment]
没差别，同一个地址别名
