### ISSUE TITLE
内置 jest 配置支持某些依赖包的 esmodule 格式

### ISSUE THREAD

**Issue by imsobear** [alibaba/ice#4697]
## 背景

icejs 内置的 jest 配置里 babel-jest 默认 ignore 了 node_modules 依赖（社区推荐做法）：

https://github.com/alibaba/ice/blob/e003e4888f74567d76681c47c88bf44d379a1e46/packages/build-jest-config/src/index.ts#L6-L13

因此如果依赖包里如果使用了 esmodule 语法（比如 @ice/store 2.0 版本），jest 则会直接报错：

```bash
> icejs test

ice.js 2.0.0
 FAIL  test/index.test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/guoda/work/ice-biz/ice-jest/node_modules/_@ice_store@2.0.0-4@@ice/store/lib/index.js:12
    import React from 'react';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      1 | import sum from '@/sum';
    > 2 | import { createStore } from '@ice/store';
```

## 思路

两个思路

### 1. babel-jest 不再忽略 `node_modules`

新建 `jest.config.js` 覆盖内置配置：

```diff
module.exports = {
  transformIgnorePatterns: [
-    '[/\\\\]node_modules[/\\\\].+\\.(js|jsx|ts|tsx)$', 
+    '^.+\\.module\\.(css|sass|scss|less)$', 
  ],
}
```

这个方案的缺陷：webpack start/build 时我们推荐的做法都是 babel-loader 默认忽略 node_modules（webpack 支持处理 esmodule 语法因此大多数情况都没有问题），这样的话 test 跟 start/build 的逻辑会不一致。

### 2. jest 默认支持 esmodule 语法

类似上述 webpack + babel-loader 的处理方式，忽略逻辑不变，让 jest 默认能支持 esmodule 语法，[相关文档](https://jestjs.io/docs/ecmascript-modules)，但是这个方案目前使用成本比较高：

- 需要添加 experimental 参数：`NODE_OPTIONS=--experimental-vm-modules npx icejs test`
- 对应的 npm 包需要在 package.json 里添加 `type: module` 的字段

这个方案使用成本比较高，**我在 `icejs test` 的场景里没有跑成功，但是在最简单的 jest demo 里有跑成功**。

## 方案

推荐使用方案 1，并且 icejs 直接将内置的这个规则改掉。

**Comment by ClarkXia** [comment]
方案一存在的风险，部分 node_modules 依赖参与编译后会导致问题，目前已知 core-js、@swc/helpers、@babel/runtime，已内置忽略
大部分测试场景为功能模块测试，一般不存在类似依赖，特殊情况下推荐用户自定义 transformIgnorePatterns
