### ISSUE TITLE
feature request for ice-script

### ISSUE THREAD

**Issue by wssgcg1213** [alibaba/ice#47]
- [x] configurable (pr #38)
- [ ]  support hot module replacement (config to enable)
- [x] dist dir default to `/build/` 调研了下, 遵循社区习惯
- [ ] compiling speed optimization: 尽可能的开启缓存
  - happypack?
  - babel-loader. cacheDirectory 
- [ ] webpack define plugin support for `process.env`
- [ ] enable tree shaking (config resolve.mainFields)
- [ ] support css modules
- [x] visualized module analyzer: webpack-bundle-analyzer #49 

> 自动刷新 vs 模块热更新：
> 实时预览反应更快，等待时间更短
> 不刷新浏览器能保留当前网页的运行状态

**Comment by wssgcg1213** [comment]
https://en.wikipedia.org/wiki/0.0.0.0  
`0.0.0.0` is not a valid ip address,

**Comment by chenbin92** [comment]
@wssgcg1213  [webpack  v4.0.0-beta.0](https://github.com/webpack/webpack/releases) 的默认配置

![](https://img.alicdn.com/tfs/TB1v_ynXbGYBuNjy0FoXXciBFXa-1488-400.png)

**Comment by wssgcg1213** [comment]
based on information followed, we decided to change default output path from `dist` to `build`

- we use `build` as default output path in `def` workflow
- `create-react-app` use `build` as their default output path  

@chenbin92

**Comment by yujiangshui** [comment]
是否已经完成或需要继续跟进？
