### ISSUE TITLE
是否考虑支持ng啊

### ISSUE THREAD

**Issue by smile2014** [alibaba/ice#470]

**Comment by chenbin92** [comment]
@smile2014  angular 会提供文档接入，有人贡献的话就会在 iceworks 里放出来。对 Iceworks 来说，主要是物料数据源，不管是 angular，react ，vue 还是其他类型的物料，只要符合定义好的物料数据协议，就都可以在 Iceworks 里使用。

**Comment by smile2014** [comment]
明白，谢谢了。

**Comment by chenbin92** [comment]
@smile2014  接入文档： https://github.com/alibaba/ice/blob/add-material-data-specification/docs/materials/data-specification.md
