### ISSUE TITLE
关于内置的@iceworks/spec 相关规范文档

### ISSUE THREAD

**Issue by iamlhh** [alibaba/ice#4720]
使用相对黑盒的脚手架工具也意味着要遵循相同的代码规范和工程实践模式，但是阿里的前端规约文档貌似并没有开源，只能从f2e-spec窥其一角，虽然注释还是写得不错的，但是要整理成文就需要做一定逆向工程。所以是否存在开源阿里前端规约的计划。

**Comment by imsobear** [comment]
- 框架 icejs 本身跟 lint 规范不耦合，我们模式内置了 `@iceworks/spec`，你可以替换成其他任意 lint 规范（比如 airbnb）
- `@iceworks/spec` （仓库在 ice-lab/spec）是基于 `alibaba/f2e-spec` 里的规则的，有一部分规则做了修改，无论是 f2e-spec 还是 iceworks/spec 完整的规则文档说明目前的确是缺失的，后面会补充（优先级不高），如果诉求强烈建议替换成 airbnb 之类的规则
