### ISSUE TITLE
[QUESTION]升级webpack5以后，有些webpack的依赖引用不到，怎么优雅解决？

### ISSUE THREAD

**Issue by yiescc** [alibaba/ice#4725]
背景
- 我们项目用到一个插件woker-loader
- 它需要用到webpack/lib/ExternalsPlugin这个文件
- 原来ice1.x版本正常
- 升级到ice2.x的时候就失败，说没有加载webpack/lib/ExternalsPlugin这个问题
- 发现并没有安装webpack导致
- 但理论上ice应该内置了webpack，2.x是不是改了？

然后我是自己安装了webpack解决了找不到的问题，但是感觉不太对，因为webpack应该其他依赖也有安装

需求
- 优雅解决需求

**Comment by ClarkXia** [comment]
2.x 中 webpack 5 相关的依赖都进行了预编译，下个版本将会将内置的插件开放出来
