### ISSUE TITLE
升级2.0后，微应用拿到的history不是自己的而是父级的

### ISSUE THREAD

**Issue by yiescc** [alibaba/ice#4727]
背景
- 我们通过`import { history } from 'ice';`拿history
- 1.x版本微应用拿到的是自己的history，所以跳转是自己的路径
- 2.x版本我们再跳转的时候变成了父应用跳转，不符合我们的预期
```
import { history } from 'ice';

history.push("/test") => /微应用/test

但现在变成
/test

```
然后我们用useHistory Api就是正常的

所以这个行为都会这样吗？

**Comment by maoxiaoke** [comment]
@yiescc 暂时请使用 [useHistory](https://ice.work/docs/api/about/#usehistory)，目前 ice 2.x 导出的 history 存在一些问题。

```jsx
import { useHistory } from 'ice'

function App () {
 const history = useHistory();
 ...
}
```
