### ISSUE TITLE
自定义区块，启动报错，麻烦看下

### ISSUE THREAD

**Issue by somebody-2** [alibaba/ice#4730]
![image](https://user-images.githubusercontent.com/23648457/136652934-5cf2a3e1-7536-4a1a-af95-dbb169888ac0.png)

**Comment by haoxiaoshu6** [comment]
就是按官网的一步一步来   然后启动报这个的，选type选的第一个，选component就可以

**Comment by haoxiaoshu6** [comment]
怎么提供demo

**Comment by haoxiaoshu6** [comment]
![image](https://user-images.githubusercontent.com/23648457/136695759-42f4311f-b106-49c1-a7d6-49ff7b81d602.png)
官网alibaba-fusion/materials  克隆下来下载依赖也报一样的错

**Comment by luhc228** [comment]
> 就是按官网的一步一步来 然后启动报这个的，选type选的第一个，选component就可以

按照上面的步骤，我这里复现不了
