### ISSUE TITLE
升级到icejs2.x之后，项目名称中含有.ice，修改源码不会自动编译

### ISSUE THREAD

**Issue by mopsky** [alibaba/ice#4731]
我们的项目名称正好是xxx.ice.erp，发现只要含有.ice，修改源码就不会自动编译，换个名称就可以，猜测是ice自己本身会生成.ice目录，不知道是不是这个问题

**Comment by ClarkXia** [comment]
对于项目名刚好为 xxx.ice.erp 的情况 我们修复下
