### ISSUE TITLE
[QUESTION]如何不自动引入fusion/next的组件的样式

### ISSUE THREAD

**Issue by xmsz** [alibaba/ice#4735]
背景
- 我引入了fusion的组件，然后发现同时有引入样式
- 不过我有定制主题的需求，所以这就导致了样式的冲突，且自己的写的样式层级比自动的引入的低
- 导致需求无法实现

需求
- 不自动引入fusion样式
- 有没有什么办法优先级高于自动引入的样式

**Comment by xmsz** [comment]
> ```json
>  "externals": {
>      "@alifd/next/**/*/style": ""
>   }
> ```

牛逼 这个理论上确实可以

不过实际测试还是会加到style.js里进去 不确定运营

**Comment by imsobear** [comment]
> > ```json
> >  "externals": {
> >      "@alifd/next/**/*/style": ""
> >   }
> > ```
> 
> 牛逼 这个理论上确实可以
> 
> 不过实际测试还是会加到style.js里进去 不确定运营

方便的话提供个重现项目，我试下

**Comment by imsobear** [comment]
@xmsz 我意思是在项目级别配置这个 externals，不是单个组件。

**Comment by xmsz** [comment]
> @xmsz 我意思是在项目级别配置这个 externals，不是单个组件。

嗯  主项目就是普通ice模板 然后我插件和项目都加了 但是没有效果

然后这个行为怎么在插件里实现

**Comment by xmsz** [comment]
> > > @xmsz 我意思是在项目级别配置这个 externals，不是单个组件。
> > 
> > 
> > 嗯 主项目就是普通ice模板 然后我插件和项目都加了 但是没有效果
> > 然后这个行为怎么在插件里实现
> 
> 你给我一个项目的 demo 吧，组件不建议配这个

我新建一个ice项目测试，也是一样，所以没有上传
```
{
  "vite": false,
  "externals": {
    "@alifd/next/**/*/style": ""
  }
}
```
+ 插件(@cool/cool-ui)
```
import React from 'react';

import { Button } from '@cool/cool-ui';

export default () => {
  return (
    <>
      <Button>asd</Button>
    </>
  );
};
```


然后大致是
- 插件，会生成style.js，并把用到的next样式引用到添加进去
- 项目引用会自动加载style.js，所以带上了样式
- 项目和插件都使用externals，没有效果

**Comment by imsobear** [comment]
@xmsz 可以先回到你初始的问题，提高下你自定义样式的优先级，比如加一些前缀之类的，类似下面这样：

```css
body {
  .next-btn {
      color: red;
  }
}
```

**Comment by xmsz** [comment]
> @xmsz 可以先回到你初始的问题，提高下你自定义样式的优先级，比如加一些前缀之类的，类似下面这样：
> 
> ```css
> body {
>   .next-btn {
>       color: red;
>   }
> }
> ```

对 我现在就是
- 加前缀或者手动再加className 但是一方面觉得有点麻烦 一方面有时候会产生更奇怪的冲突 例如几个css共有一个，然后这个层级太高了，会直接影响覆盖其他


-------------------------
然后回到最开始我的项目的需求是
- 有个插件，基于fusion/next进行业务封装
- 使用css变量模式，为了后续可以动态修改
- 需要定制一些样式，然后不想用fusion的定制功能


遇到的问题
- 插件会自动构造出fusion/next的样式，导致样式优先级太高，定制的样式失效


然后临时的解决方法
- 用脚本将fusion/next的sideEffects删除，可行但做法太烂
- 插件构建时将相关依赖引用去除，可行但行为副作用可能更大，这种行为正确应该交由调用者去选择才对

**Comment by imsobear** [comment]
@xmsz 你看这样如何：

- build-plugin-component 我们发个版本，样式依赖这块做一些改动
- 你这边相关的包（目前看就有个 cool-ui）按照说明升级下插件，然后发布新版本
- 项目里使用手动引入 fusion 组件样式 + 新版本的 cool-ui

**Comment by xmsz** [comment]
> @xmsz 你看这样如何：
> 
> * build-plugin-component 我们发个版本，样式依赖这块做一些改动
> * 你这边相关的包（目前看就有个 cool-ui）按照说明升级下插件，然后发布新版本
> * 项目里使用手动引入 fusion 组件样式 + 新版本的 cool-ui

我觉得可以 感恩

**Comment by xmsz** [comment]
> * build-plugin-component@1.8.0-0
> * build.json 加一个 `"disableGenerateStyle": true` 的选项
> 
> @xmsz

ok 可用
