### ISSUE TITLE
ice2.0.1在mpa模式中errorBoundary 报错, vite渲染空白

### ISSUE THREAD

**Issue by vision-yip** [alibaba/ice#4755]
## What is the current behavior? 发生了什么？

1. 在webpack5 mpa模式下使用errorBoundary会报错
![image](https://user-images.githubusercontent.com/18309167/137578582-16dda99e-7bc7-43db-ba59-4580223872fd.png)

2. vite mpa模式下会不渲染(页面空白)
![image](https://user-images.githubusercontent.com/18309167/137578597-1baafc5d-222f-437b-82bd-f8f137fe9dbf.png)

## What is the expected behavior? 期望的结果是什么？
1. 在webpack5 mpa模式下正常使用errorBoundary
2. 在vite mpa模式下正常渲染

## Any additional comments? 相关环境信息？

- **ice.js Version**：2.0.1
- **build.json Configuration**：
```
{
  "mpa": true,
  "vite": true,
  "plugins": [
    [
      "build-plugin-antd"
    ]
  ]
}
```
- **Node Version**: 16.10

**Comment by ClarkXia** [comment]
文档中的 onErrorBoundaryHander 有点问题，应该是

```js
import { runApp, IAppConfig } from 'ice';

const appConfig: IAppConfig = {
  app: {
    // 是否开启 ErrorBoundary，默认为 false
    errorBoundary: true
    // 自定义错误边界的 fallback UI
    ErrorBoundaryFallback: () => <div>渲染错误</div>,
    // 自定义错误的处理事件
    onErrorBoundaryHandler: (error: Error, componentStack: string) => {
      // Do something with the error
    },
  }
};

runApp(appConfig);
```

上述问题我们看下，另外最好再提供下 app.ts 的内容

**Comment by vision-yip** [comment]
import { runApp, IAppConfig } from 'ice';
import Route from './routes'

const appConfig: IAppConfig = {
  app: {
    rootId: 'ice-container',
    // 是否开启 ErrorBoundary，默认为 false
    errorBoundary: true,
    // 自定义错误边界的 fallback UI
    ErrorBoundaryFallback: () => <div>渲染错误</div>,
    // 自定义错误的处理事件
    onErrorBoundaryHander: (error: Error, componentStack: string) => {
      // Do something with the error
    },
  },
  router: {
    type: 'hash',
    routes: Route
  },
};

runApp(appConfig);

**Comment by vision-yip** [comment]
@imsobear @ClarkXia let me know you haven't forgotten this😄
