### ISSUE TITLE
如何加载远程模块？

### ISSUE THREAD

**Issue by woaizimmy** [alibaba/ice#4759]
我们知道，antd有个cdn线上版本，地址是：https://cdn.bootcss.com/antd/4.15.0/antd.js
在飞冰的项目模板中，如果不想`npm i antd` 和 `import { Table } from 'antd' `，而是直接使用`import { Table } from 'https://cdn.bootcss.com/antd/4.15.0/antd.js'`，应该如何实现？

尝试过 import 和 require，都不支持加载远程模块。

**Comment by imsobear** [comment]
为什么需要 `import url`？直接用 externals 不行么？

**Comment by woaizimmy** [comment]
> 为什么需要 `import url`？直接用 externals 不行么？

嗯，后来用了 externals ，行得通。
