### ISSUE TITLE
创建store文件后，原有的嵌套路由效果失效

### ISSUE THREAD

**Issue by jshuhao** [alibaba/ice#4772]
###  **1.没创建store文件，正常情况如下** 
![view1](https://user-images.githubusercontent.com/43402557/138050393-07920f6c-7afb-48da-9e5f-38523e55d249.jpg)
![ye](https://user-images.githubusercontent.com/43402557/138050605-074b9f0e-f1f5-4c23-8fda-aa8ccdf5d784.jpg)
![6666](https://user-images.githubusercontent.com/43402557/138051589-6ac2e2f1-8ebc-4df1-ad74-05e3d1325825.jpg)
 ![router1](https://user-images.githubusercontent.com/43402557/138049656-b9926874-419c-4073-8d6e-0814ebbf90d1.jpg)

###  **2.创建store后**
  ![985](https://user-images.githubusercontent.com/43402557/138051270-ef72a362-fb8d-4d46-9454-ecd8205d17b2.jpg)
  ![store1](https://user-images.githubusercontent.com/43402557/138051317-c632beac-905c-457a-a805-1ebc0ff7e5b8.jpg)

## What is the expected behavior? 期望的结果是什么？
**1.我创建了store后，其余代码均没用改动，组件内部也并没有引用他，我重启了一下项目，发现了这个情况**
**2.因为刚转react没多久，不知道是不是我的原因，希望您帮忙看看，是否是我哪里操作有误呢？**

## Any additional comments? 相关环境信息？
![22323](https://user-images.githubusercontent.com/43402557/138052256-78bb91a6-56e0-48e3-b32f-eb60079b6e79.jpg)
{
  "name": "@icedesign/ice-antd-scaffold",
  "version": "0.1.0",
  "description": "Ant Design and icejs scaffold, use TypeScript.",
  "dependencies": {
    "@ant-design/icons": "^4.0.2",
    "@ant-design/pro-layout": "^6.5.1",
    "antd": "^4.0.0",
    "moment": "^2.24.0",
    "prop-types": "^15.5.8",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  },
  "devDependencies": {
    "@iceworks/spec": "^1.0.1",
    "@types/react": "^17.0.14",
    "@types/react-dom": "^17.0.9",
    "build-plugin-antd": "^0.1.2",
    "eslint": "^7.30.0",
    "ice.js": "^2.0.0",
    "stylelint": "^13.1.0"
  },
  "scripts": {
    "start": "icejs start",
    "build": "icejs build",
    "lint": "npm run eslint && npm run stylelint",
    "eslint": "eslint --cache --ext .js,.jsx ./",
    "stylelint": "stylelint ./**/*.scss"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/ice-lab/react-materials/tree/master/scaffolds/antd-lite"
  },
  "private": true,
  "originTemplate": "@icedesign/ice-antd-scaffold"
}

**Comment by luhc228** [comment]
> > @jshuhao 可以提供下复现的代码
> 
> 可以，您提供一下邮箱，我发给您，具体复现步骤，只需要删除和创建store文件，重启即可

可以提供仓库地址或者压缩包

**Comment by imsobear** [comment]
@luhc228 非 Vite 模式下貌似是好的

**Comment by imsobear** [comment]
默认是 vite 模式，build.json 有个 vite: true 的选项。

**Comment by jshuhao** [comment]
> 默认是 vite 模式，build.json 有个 vite: true 的选项。

好像是的，我改了之后就好了，感谢
