### ISSUE TITLE
表单解决方案

### ISSUE THREAD

**Issue by tyua07** [alibaba/ice#479]
ice 会出类似于 [react-jsonschema-form](https://github.com/mozilla-services/react-jsonschema-form) 的解决方案么？因为后台管理系统表单还是一个比较大的痛点，在知乎上面看到了 @yujiangshui  的回答，但是遗憾的是没有开源。

还有，最近有持续关注你们产品的动态，看你们在 issues 或者 知乎上面也回答了一些反馈，比如说 @yuanyan 说的“ iceland”，还用很多人关心的允许新增后编辑页面等， 希望能出一个 “下个版本计划” 类似的东西。毕竟能看得到等待的东西还是会很开心的。

**Comment by yujiangshui** [comment]
动态表单这类的方案是非常偏业务的，通用的不好用，好用的不通用。所以应该是不会开源了。

ICELAND 这个将会在下半年开放使用，但是目前还不能确定，所以没能列到计划中。大型项目或者计划我们会放在 https://github.com/alibaba/ice/milestones 这里，知乎上的发布日志也会包含一些对未来的规划，可以关注。
