### ISSUE TITLE
Windows 版本 iceworks 打开终端设置无效

### ISSUE THREAD

**Issue by TaroXin** [alibaba/ice#480]
设置 `iceworks ` 终端打开方案为 `Git bash`，打开后终端为 `Cmd`

`Windows` 版本: `8.1`
`iceworks` 版本: `2.0.2`

**Comment by noyobo** [comment]
查找不到 `git bash` 后默认会以 `cmd` 启动。 麻烦检查下 `HKEY_LOCAL_MACHINE\\SOFTWARE\\GitForWindows` 注册表键是否存在。

**Comment by TaroXin** [comment]
确实是不存在的，这个我自己搞定好了
