### ISSUE TITLE
[Feature Request] build-plugin-component 支持 scss 和 js 分离导出

### ISSUE THREAD

**Issue by guoyunhe** [alibaba/ice#4815]
在构建复杂组件的时候，我们常常为了方便在 jsx/tsx 组件中直接导入 scss：

```js
import './Foobar.scss';

export function Foobar() {}
```

```js
import { Foobar } from './Foobar';
import './HelloWorld.scss';

export function HelloWorld() {}
```

目前 build-scripts 会原样输出到 lib 文件夹。但是一旦这样的 npm 包被引入到 Jest 单元测试中，就会报错。

希望能够支持 lib 导出 index.scss 自动合并所有 *.scss :

```scss
@import "Foobar.scss";
@import "HelloWorld.scss";
```

并且从 jsx/tsx 中去除 scss 导入。这样产出的包就能够直接运行于 Jest 环境中。

**Comment by maoxiaoke** [comment]
https://github.com/ice-lab/icepkg/issues/258 参考下这里的设计
