### ISSUE TITLE
禁用 ice 的 router 插件

### ISSUE THREAD

**Issue by StarHosea** [alibaba/ice#4827]
## What is the current behavior? 发生了什么？

router plugin 限制死了路由机制，能否禁用切换到 react-router 。看到 examples 中有一个 without-react-router 项目，有一个配置项
```
{
   "router": false,
}
```
官方配置文档没有提到，这个有效吗，会带来异常吗？

## What is the expected behavior? 期望的结果是什么？
可以禁用内置的 router 机制，完全使用 react-router
## Any additional comments? 相关环境信息？

- **ice.js Version**：2.1.1
- **build.json Configuration**：
- **Node Version**: 16
- **Platform**: win10

**Comment by imsobear** [comment]
https://github.com/alibaba/ice/issues/4813 这是个 bug，这周版本会修复

**Comment by StarHosea** [comment]
现在有计划安排吗？还比较喜欢 ice 的base，新的项目在技术验证选型，我们对 router 灵活要求高，需要自己实现 router ，auth 机制

**Comment by imsobear** [comment]
最晚下周会修复，不过如果不用 router 的话，很多运行时的能力就没法用，主要就是用工程构建相关的能力。

**Comment by StarHosea** [comment]
MPA，SSR 等应用形态方便接入，插件扩展能力会是考虑的点

**Comment by imsobear** [comment]
MPA 还好，SSR 感觉会有问题，SSR 需要对路由组件强劫持的
