### ISSUE TITLE
[RFC] vite 模式下 babel 插件应用优化

### ISSUE THREAD

**Issue by ClarkXia** [alibaba/ice#4829]
vite 模式下不推荐使用 babel 进行语法的转化，但受限于 vite 内置编译工具 esbuild 的开放 API 能力影响，一些强依赖 babel 的功能无法快速的进行应用，比如 fast-refresh、jsx-runtime、jsx+ 语法等。
因此在 esbuild 处理之前，针对上述功能会应用 babel 插件完成一次转化，在多个能力同时开启的情况下，造成 ast 结构重复转化的性能损耗，需要提供统一的转化逻辑

## 方案

提供统一添加 babel 插件的机制，支持复用 webpack 模式下的 babelPlugins、babelPreset 字段，所有依赖 babel 能力在完成插件收集后完成转化，推荐复用社区生态 [plugin-react](https://www.npmjs.com/package/@vitejs/plugin-react)

目前框架内置功能依赖 babel 能力如下：
- fast-refresh
- jsx-runtime：考虑迁移至 babel 转化，依赖 esbuild 追加代码的 jsx-runtime 并没有真正应用 `react/jsx-runtime`
- jsx+
- icestark 插件入口默认生命周期导出：仅入口进行转换
- lazy 重定向逻辑：仅 routes.(ts|js) 进行转换

对于单文件依赖 babel 转化，由于能力仅转化单文件，性能成本可控，可以不进行统一处理

**Comment by imsobear** [comment]
如果效果显著的话，考不考虑直接用 swc
