### ISSUE TITLE
[QUESTION]如何解决vite下引用第三方插件jsx提示'React is not defined'

### ISSUE THREAD

**Issue by xmsz** [alibaba/ice#4831]
背景
- 第三方插件文件内容
```
// test.jsx

import { render } from 'react-dom';

export default function test(Comp) {
    render(<Comp />, div);
}

```
- 将vite设为false则没有问题
- 第三方插件源内容
```
/* eslint-disable @typescript-eslint/indent */
import {
  createElement,
} from 'react';
import { render } from 'react-dom';

export default function test(Comp) {
  render(createElement(Comp), div);
}
```
- 提示
```
Uncaught (in promise) ReferenceError: React is not defined
```

需求
- 如何解决这种情况
-

**Comment by xmsz** [comment]
然后我看https://github.com/vitejs/vite/issues/1286 可以用额外的插件解决

那推荐的方案是什么样?
- 每个ice项目，自己添加vite jsx插件
- 第三方插件要求需要加入 imoport React from 'react'

**Comment by ClarkXia** [comment]
@xmsz 目前的 jsx-runtime 使用的是 esbuild 注入代码的能力，ice 中通过 tsConfig.json 的 `"jsx": "react-jsx"` 开启https://ice.work/docs/guide/basic/vite/#uncaught-syntaxerror-identifier-react-has-already-been-declared
下个版本将会利用 babel 的能力进行转化

相关的方案 issue #4829 中已提及

**Comment by imsobear** [comment]
已支持
