### ISSUE TITLE
[REQUEST].ice/types/index.ts下types/icestark引用目录不正确

### ISSUE THREAD

**Issue by xmsz** [alibaba/ice#4833]
背景
```
// .ice/types/index.ts
...
import { IIceStark } from './types/icestark';
...
```
![image](https://user-images.githubusercontent.com/5879146/139634338-9cc69ac4-3ae6-4885-9fc0-545f4d16e9ff.png)

**Comment by maoxiaoke** [comment]
#4800 
我待会修复一下~

**Comment by maoxiaoke** [comment]
Solved. 更新下 build-plugin-icestark 的版本
