### ISSUE TITLE
[QUESTION]请问什么时候history会可能是null

### ISSUE THREAD

**Issue by xmsz** [alibaba/ice#4838]
背景
- 我在程序中使用 import {history} from 'ice'
- 然后type提示我可能是null

需求
- 请问什么情况下会是null
- 怎么才能保证不是null，我们可以接受history配置完成后再加载页面
- 还有我通过useHistory获取的history反而是undefined

**Comment by ClarkXia** [comment]
> 还有我通过useHistory获取的history反而是undefined

这个是什么场景下，history 初始化（应用渲染后）再去获取的时候就不会是 null 了

**Comment by ClarkXia** [comment]
框架层面支持以下两种方式获取：

```js
import { history, getHistory } from 'ice';
```

**Comment by xmsz** [comment]
> 框架层面支持以下两种方式获取：
> 
> ```js
> import { history, getHistory } from 'ice';
> ```

我现在有点点混乱了，是不是

通用情况
- 需要等应用加载后才能获取得到history对象

主应用
- 只能通过history, getHistory，useHistory获取不到


子应用
- history, getHistory, useHistory都可以

**Comment by ClarkXia** [comment]
> > 框架层面支持以下两种方式获取：
> > ```js
> > import { history, getHistory } from 'ice';
> > ```
> 
> 我现在有点点混乱了，是不是
> 
> 通用情况
> 
> * 需要等应用加载后才能获取得到history对象
> 
> 主应用
> 
> * 只能通过history, getHistory，useHistory获取不到
> 
> 子应用
> 
> * history, getHistory, useHistory都可以

微前端架构是另外一个话题，微前端架构下 主应用跟子应用的不是同一个 history，主应用的跳转参考 https://micro-frontends.ice.work/docs/api/ice-stark-app/#apphistory

**Comment by xmsz** [comment]
> > > 框架层面支持以下两种方式获取：
> > > ```js
> > > import { history, getHistory } from 'ice';
> > > ```
> > 
> > 
> > 我现在有点点混乱了，是不是
> > 通用情况
> > 
> > * 需要等应用加载后才能获取得到history对象
> > 
> > 主应用
> > 
> > * 只能通过history, getHistory，useHistory获取不到
> > 
> > 子应用
> > 
> > * history, getHistory, useHistory都可以
> 
> 微前端架构是另外一个话题，微前端架构下 主应用跟子应用的不是同一个 history，主应用的跳转参考 https://micro-frontends.ice.work/docs/api/ice-stark-app/#apphistory

嗯 我的需求是『获取当前路由的pathname』

然后刚好是在主应用获取（在子应用没有发现问题所以没注意），但是用useHistory发现拿到是undefined
然后直接history虽然可以，但发现类型提示有可能是null

想象中
1. 主应用能否使用useHistory和是否是微前端架构应该没关系

然后
1. 由于现在history拿到的可能是null，导致之前的代码检查都不通过（之前都是直接拿history使用）

**Comment by ClarkXia** [comment]
> 然后刚好是在主应用获取（在子应用没有发现问题所以没注意），但是用useHistory发现拿到是undefined
然后直接history虽然可以，但发现类型提示有可能是null

useHistory 的问题最好提供下 demo，如果是用 pnpm 安装可能跟 #4822 问题类似

**Comment by xmsz** [comment]
https://github.com/xmsz/demo-20211103

我大概又试了一下
1. 在页面使用没有问题
2. 在icestark.Layout的组件会是undefined
3. layouts.index.tsx没有测试成功不知道结果

**Comment by ClarkXia** [comment]
微前端这个场景是比较特殊，你可以理解为他的结构是

```jsx
<FrameworkLayout>  // 整体 Layout
  <AppRouter>
    <AppRoute />  // 子应用
    <AppRoute render={() => {
      // 主应用路由
      return (
        <ReactRouter>
          <Switch>
            <Route component=Home />
          </Switch>
        </ReactRouter>
      );}}
    />
  <AppRouter>
</FrameworkLayout>
```

因此在 FrameworkLayout 中是无法使用 useHistory 的，因为没有 ReactRouter 初始化的 Context 信息

**Comment by xmsz** [comment]
> 微前端这个场景是比较特殊，你可以理解为他的结构是
> 因此在 FrameworkLayout 中是无法使用 useHistory 的，因为没有 ReactRouter 初始化的 Context 信息

ok 明白了
