### ISSUE TITLE
建议proxy配置从build.json中分离

### ISSUE THREAD

**Issue by inier** [alibaba/ice#4848]
## What is the current behavior? 发生了什么？
jcejs2.0中，proxy配置是通过build.json配置的，使用非常不便。
porxy配置更贴合开发需求，不适合防止在工程文件中：
1. 需要频繁更改；
2. json格式不好加注释，维护不便；
3. 大项目中，代理配置很多，不便于维护；

## What is the expected behavior? 期望的结果是什么？
推荐参考create-react-app的模式，将proxy配置单独一个js文件，放置目录和文件名及处理方式都可以一致。这样即可以保证与CRA项目同步，也更方便已有的CRA项目迁移到icejs。

## Any additional comments? 相关环境信息？

- **ice.js Version**：2.0

icejs 2.0 更加成熟，工程化和开发文件更好的分离，将能更好的替代CRA，加油！

**Comment by imsobear** [comment]
看了下 CRA 是有个 `src/setupProxy.js` 的文件然后写中间件。

对于你这个诉求，build.json 是支持写成 `build.config.[j|t]s`，[文档](https://ice.work/docs/guide/basic/build#%E5%B7%A5%E7%A8%8B%E6%9E%84%E5%BB%BA%E9%85%8D%E7%BD%AE)，你可以单独弄个 `proxy.config.js`，然后在 `build.config.[j|t]s` 里 `import` 过来，不知道是否满足诉求？

**Comment by inier** [comment]
按照以下配置导出，无法正确代理

module.exports = {
  '/api/mock': {
    // mock api地址
    target: '//localhost:3000/mock/12',
    enable: true,
    changeOrigin: true,
    pathRewrite: {
      '^/api/mock': '',
    },
  },
  '/api': {
    target: '//ip-api.com/',
    enable: true,
    changeOrigin: true,
    pathRewrite: {
      '^/api': '',
    },
  },
};

**Comment by inier** [comment]
vite 下不报错，但无法正常代理； webpack模式下，报错
![image](https://user-images.githubusercontent.com/7600897/141812767-d8753644-4bd1-4fe7-8b36-d9a526d2276c.png)

**Comment by inier** [comment]
独立的文件引入，可行：
module.exports = {
  '/api/mock': {
    // mock api地址
    target: 'http://localhost:3000/mock/12',
    enable: true,
    changeOrigin: true,
    pathRewrite: {
      '^/api/mock': '',
    },
  },
  '/api': {
    target: 'http://ip-api.com/',
    enable: true,
    changeOrigin: true,
    pathRewrite: {
      '^/api': '',
    },
  },
};
