### ISSUE TITLE
build.json 配置项里面的 plugins 是什么

### ISSUE THREAD

**Issue by xiaohp** [alibaba/ice#4860]
使用的不带组件库的模板

## What is the current behavior? 发生了什么？

build.json 的内容是

```json
{
  "vite": true,
  "plugins": []
}
```

在配置页面没有看到相关选项 https://ice.work/docs/config/about 只有 vitePlugins
## What is the expected behavior? 期望的结果是什么？

补充文档 or 更新模板

## Any additional comments? 相关环境信息？

- **ice.js Version**：2.0.0
- **build.json Configuration**：
- **Node Version**:  v16.13.0
- **Platform**: macOS

**Comment by imsobear** [comment]
https://ice.work/docs/plugin/develop/start 这里有介绍，文档我们完善下

**Comment by imsobear** [comment]
https://ice.work/docs/config/about/#plugins 文档已补充。
