### ISSUE TITLE
使用remoteRuntimes构建报错

### ISSUE THREAD

**Issue by JackLLLLL** [alibaba/ice#4862]
## What is the current behavior? 发生了什么？
当build.json中开启remoteRuntime = true时, 多次构建后会出现require not defined的报错
![image](https://user-images.githubusercontent.com/37646584/140443885-efcfd732-257e-4ee6-9699-e11b63ebcfa3.png)
如果把remoteRuntime设置为false, 就一切正常
或者tnpm update重新安装后tnpm start, 都可以恢复正常, 但是tnpm start多次开发以后, 多次热更新以后, 下一次再tnpm start就会报错

## What is the expected behavior? 期望的结果是什么？
remoteRuntime可以一直正常使用

## Any additional comments? 相关环境信息？

- **ice.js Version**：2.1.2
- **build.json Configuration**：

```json
{
  "remoteRuntime": true,
  "externals": {
    "react": "React",
    "react-dom": "ReactDOM",
    "react-router": "ReactRouter",
    "react-router-dom": "ReactRouterDOM"
  },
  "plugins": [
    [
      "build-plugin-fusion",
      {
        "themePackage": "@alife/theme-maox",
        "cssVariable": true
      }
    ],
    [
      "build-plugin-moment-locales",
      {
        "locales": [
          "zh-cn"
        ]
      }
    ],
    "@ali/build-plugin-ice-def",
    "build-plugin-keep-alive"
  ]
}
```

- **Node Version**: 14.17.0
- **Platform**: macos 10.15.7 (19H15)

**Comment by ClarkXia** [comment]
看下编译过程的终端信息，最好提供 demo，如果是内部业务可以直接通过答疑渠道提供 demo

**Comment by JackLLLLL** [comment]
ok, 那我复现一下

**Comment by ClarkXia** [comment]
2.2.0 版本已修复
