### ISSUE TITLE
Vite 模式如何使用 unocss

### ISSUE THREAD

**Issue by chenar-x** [alibaba/ice#4864]
## Any additional comments? 相关环境信息？

- **ice.js Version**：
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by imsobear** [comment]
删除 build.json，新增 build.config.ts：

```js
import Unocss from 'unocss/vite';
import { presetIcons, presetUno } from 'unocss';

export default {
  vite: true,
  vitePlugins: [
    Unocss({
      presets: [
        presetUno(),
        presetIcons({}),
      ],
    }),
  ],
}
```

这样就可以，我昨天刚跑过 demo ~~

**Comment by chenar-x** [comment]
i try add unocss on build.js on vite

> 删除 build.json，新增 build.config.ts：
> 
> ```js
> import Unocss from 'unocss/vite';
> import { presetIcons, presetUno } from 'unocss';
> 
> export default {
>   vite: true,
>   vitePlugins: [
>     Unocss({
>       presets: [
>         presetUno(),
>         presetIcons({}),
>       ],
>     }),
>   ],
> }
> ```
> 
> 这样就可以，我昨天刚跑过 demo ~~

刚改掉build.config试了一下，在main页面import 'uno.css'会报错

**Comment by imsobear** [comment]
看下 ice.js 的版本是多少

**Comment by chenar-x** [comment]
> 看下 ice.js 的版本是多少

2.0.0

**Comment by imsobear** [comment]
要看实际安装的版本，start 的时候会输出在终端。确保是 2.1.2 版本。

**Comment by imsobear** [comment]
global.css： `@import 'uno.css'` ，也可以写在 app.js 里：`import 'uno.css';`，写法不一样

**Comment by chenar-x** [comment]
> 要看实际安装的版本，start 的时候会输出在终端。确保是 2.1.2 版本。

可以啦~~非常感谢！

**Comment by xmsz** [comment]
我的图标没有显示 其他正常
```
<i className="ic-baseline-add" />
<div className="i-twemoji-grinning-face-with-smiling-eyes hover:i-twemoji-face-with-tears-of-joy" />
```

怎么正确使用presetIcons
```
    Unocss({
      presets: [presetUno(), presetIcons({})],
    }),

```

**Comment by imsobear** [comment]
@xmsz 你提交个项目，我来给你看下

**Comment by xmsz** [comment]
> @xmsz 你提交个项目，我来给你看下

https://github.com/xmsz/demo-20220301

只做了
- build.config.js
- import 'uno.css'
- npm i uno.css -D

然后还有 如果我在global.css里添加 '@import 'uno.css'' 会提示
```
Failed to find 'uno.css'
```

**Comment by xmsz** [comment]
@imsobear 还有一个情况
import transformerDirective from '@unocss/transformer-directives';

```
    Unocss({
      transformers: [transformerDirective()],
    }),
```

提示
```
下午2:59:55 [vite] Internal server error: Cannot read property 'includes' of undefined
  Plugin: unocss:transformers:pre
  File: /__uno.css
      at transformDirectives (/node_modules/.pnpm/@unocss+transformer-directives@0.27.0/node_modules/@unocss/transformer-directives/dist/index.cjs:21:22)
```

**Comment by imsobear** [comment]
> > @xmsz 你提交个项目，我来给你看下
> 
> https://github.com/xmsz/demo-20220301
> 
> 只做了
> 
> * build.config.js
> * import 'uno.css'
> * npm i uno.css -D
> 
> 然后还有 如果我在global.css里添加 '@import 'uno.css'' 会提示
> 
> ```
> Failed to find 'uno.css'
> ```

仓库地址打开是 404

**Comment by imsobear** [comment]
@xmsz 你漏了一步：https://github.com/unocss/unocss/tree/main/packages/preset-icons#install ，要安装下这个依赖 `@iconify-json/[the-collection-you-want]`

**Comment by imsobear** [comment]
把 unocss 升级到 0.27.x 试下，我测了没问题

**Comment by xmsz** [comment]
> 把 unocss 升级到 0.27.x 试下，我测了没问题

感谢 第一个问题确实是版本问题... 更新太快了 （又犯一个傻错误）


然后第二个问题，我还是会报错

**Comment by imsobear** [comment]
@xmsz 我试了也不行，还是在 app.js 中引入吧，我看 unocss 的文档也是让在 js 里引入。

**Comment by xmsz** [comment]
> @xmsz 我试了也不行，还是在 app.js 中引入吧，我看 unocss 的文档也是让在 js 里引入。

ok

**Comment by xmsz** [comment]
@imsobear 不好意思能否再帮我看个情况
```
// global.scss
.first {
  @apply text-blue-500;
  .second {
    @apply text-red-500;
  }
}
```
这里`@apply text-red-500;`没有生效
<img width="351" alt="image" src="https://user-images.githubusercontent.com/5879146/156980429-0a316d00-81df-4f9b-a5b0-2604aa295c3a.png">


要这么写才行
```
.first  .second {
    @apply text-red-500;
  }

```

**Comment by xmsz** [comment]
> @imsobear 不好意思能否再帮我看个情况
> 
> ```
> // global.scss
> .first {
>   @apply text-blue-500;
>   .second {
>     @apply text-red-500;
>   }
> }
> ```
> 
> 这里`@apply text-red-500;`没有生效 <img alt="image" width="351" src="https://user-images.githubusercontent.com/5879146/156980429-0a316d00-81df-4f9b-a5b0-2604aa295c3a.png">
> 
> 要这么写才行
> 
> ```
> .first  .second {
>     @apply text-red-500;
>   }
> ```

好吧 这是unocss bug

**Comment by ChenLeoXX** [comment]
unocss presetAttributify无效，用了JSX插件也不行，貌似只能使用classname

**Comment by ChenLeoXX** [comment]
> unocss presetAttributify无效，用了JSX插件也不行，貌似只能使用classname

@imsobear 有办法解决嘛

**Comment by ChenLeoXX** [comment]
![image](https://user-images.githubusercontent.com/27530887/206150731-7f023696-4d5a-4c98-b74e-3d013f223752.png)
