### ISSUE TITLE
ICE v2: 在 dev server 中禁用 eslint 且在 build 中启用 eslint

### ISSUE THREAD

**Issue by guoyunhe** [alibaba/ice#4865]
平常用 ICE 做开发，感觉修改代码之后，hot-reload 的时间偏长。只修改一个小文件一行内容，也要四五秒左右。其他构建工具只需要1s不到。

观察发现，eslint 默认是开启的。hot-reload 之后，ice 又花了很多时间去跑 eslint。

在 dev 模式下，前端开发经常频繁保存，实时的跑 eslint 就很影响效率。另外，我们用 VS Code，本身在 IDE 里就提供了很好的 ESLint 支持。不是很需要 ice 再跑一遍。

但是在 build 模式下，我们又需要跑 eslint，以防止大家代码合并后出了问题，或者有人越过了 eslint 提交部署。

矛盾的是，ice 的 eslint 选项，是同时控制 dev server 和 build 模式的。但是我们对这两种模式又有不同的需求。

**Comment by ClarkXia** [comment]
偏慢的情况 我们再排查下，eslint 问题可以参考[文档](https://ice.work/docs/guide/basic/config#%E5%8C%BA%E5%88%86%E5%B7%A5%E7%A8%8B%E9%85%8D%E7%BD%AE) 区分环境，或者直接使用 js 配置，目前 icejs 会默认加载 build.config.js

**Comment by inier** [comment]
对的，ice的hot-load对比cra 真的忙很多

**Comment by imsobear** [comment]
@inier 这个问题里主要是 2.x + vite 引入 eslint 检测导致的，你这边是什么版本什么场景，最好能单独提个 issue 我们分析下。

**Comment by ClarkXia** [comment]
2.2.0 默认已关闭 eslint 检测，按需开启，其他性能相关问题可以在 https://github.com/alibaba/ice/issues/4866 回复，近期会针对构建性能的耗时点进行梳理优化
