### ISSUE TITLE
新建项目 Vite HMR 只能 reload 而 没有 updated...

### ISSUE THREAD

**Issue by csd998aaa** [alibaba/ice#4870]
试过了两台电脑 都是只能reload...

**Comment by csd998aaa** [comment]
下午3:55:12 [vite] page reload src/pages/Dashboard/index.tsx (x4)

**Comment by csd998aaa** [comment]
![image](https://user-images.githubusercontent.com/25193345/140478008-e11d3708-759c-46ae-b7e5-acc7d43d6a16.png)

**Comment by ClarkXia** [comment]
![image](https://user-images.githubusercontent.com/4219965/140479203-c7e0696a-cadc-4b97-8c34-e2c86b7cf43b.png)
直接用官方 template 创建出来的 antd 模版并不能复现，看下你在模版的基础上有没有什么变动，最好提供个复现的 demo

**Comment by csd998aaa** [comment]
我这边复制了同事可以热更新的代码， 安装node_modules后 可以正常updated...
