### ISSUE TITLE
ice是否支持类似umijs的运行时动态修改路由patchRoutes？

### ISSUE THREAD

**Issue by wittech** [alibaba/ice#4872]
ice是否支持类似umijs的运行时动态修改路由patchRoutes？
export function patchRoutes({ routes }) {
  routes.unshift({
    path: '/foo',
    exact: true,
    component: require('@/extraRoutes/foo').default,
  });
}

**Comment by imsobear** [comment]
https://ice.work/docs/guide/basic/router#%E8%BF%90%E8%A1%8C%E6%97%B6%E9%85%8D%E7%BD%AE modifyRoutes

**Comment by rootsli** [comment]
> https://ice.work/docs/guide/basic/router#%E8%BF%90%E8%A1%8C%E6%97%B6%E9%85%8D%E7%BD%AE modifyRoutes

这种方案不支持异步请求拉取数据吧？是否可以支持下。例如：从服务端拉取权限数据再注册路由

**Comment by imsobear** [comment]
试下这样：

```js
import { runApp, getInitialData } from 'ice';

runApp({
  app: {
    getInitialData: async () => {
      return Promise.resolve({ routes: [] });
    }
  },
  router: {
    modifyRoutes: () => {
      return getInitialData().routes;
    }
  }
})
```

**Comment by rootsli** [comment]
> 试下这样：
> 
> ```js
> import { runApp, getInitialData } from 'ice';
> 
> runApp({
>   app: {
>     getInitialData: async () => {
>       return Promise.resolve({ routes: [] });
>     }
>   },
>   router: {
>     modifyRoutes: () => {
>       const { routes } = getInitialData();
>       return routes;
>     }
>   }
> })
> ```

@imsobear 可以。但是我们的场景是：登录以后，才去拉取权限，动态注册路由。不能在登录页就注册。而上面这个回调，首次访问就执行了（还在登录页的时候）。所以，没法用。是否还有其他方法？

**Comment by imsobear** [comment]
@rootsli  你现在登录是怎么做的？可以放个大概的代码逻辑

**Comment by rootsli** [comment]
> @rootsli 你现在登录是怎么做的？可以放个大概的代码逻辑

@imsobear 就是正常登录逻辑。
访问域名=>跳转登录页（modifyRoutes和getInitialData在这里执行了）=>输入用户名密码=>登录成功，拉取权限菜单=>注册路由（这步需要注册路由，在哪里做？modifyRoutes和getInitialData不会再执行）=>渲染菜单

**Comment by imsobear** [comment]
所以你登录成功后不是一个刷新行为，只是 history 路由的跳转？ @rootsli

**Comment by rootsli** [comment]
> 所以你登录成功后不是一个刷新行为，只是 history 路由的跳转？ @rootsli

@imsobear 是的

**Comment by imsobear** [comment]
@rootsli 那 modifyRoutes 支持异步也解决不了你这个问题，因为 modifyRoutes 也只会在 runApp 的时候执行一次，你需要的是类似 updateRoutes 的能力，建议单独提个 issue。

**Comment by rootsli** [comment]
> @rootsli 那 modifyRoutes 支持异步也解决不了你这个问题，因为 modifyRoutes 也只会在 runApp 的时候执行一次，你需要的是类似 updateRoutes 的能力，建议单独提个 issue。

👌 。我们获取菜单路由后，重新执行一遍runApp，好像也行。目前测试中。。。
