### ISSUE TITLE
飞冰这个表格排序点击之后如何恢复默认呢

### ISSUE THREAD

**Issue by TangDekun1990** [alibaba/ice#4880]
![1636358914789_65849AAF-248B-4a63-A6B6-1B1ED790C18B](https://user-images.githubusercontent.com/33854900/140707638-2e7bb8a8-9a63-483e-99b0-36de5fd1bd8a.png)

**Comment by youluna** [comment]
参考下文档 https://fusion.design/pc/component/table?themeid=2#filterSort-container
![image](https://user-images.githubusercontent.com/10049465/141972645-d4777c83-188c-4e71-95cd-dcb366772a36.png)
