### ISSUE TITLE
[QUESTION] icestark.layout 里面的pathname 

### ISSUE THREAD

**Issue by yiescc** [alibaba/ice#4885]
背景：
- 在访问路径没有匹配到路由的时候，pathname的值是空的

需求：
- 为什么是空的？

**Comment by maoxiaoke** [comment]
在刷新操作下，先会得到一个空的 pathname，并立马获得有路由的 pathname。若是 hash 路由，将会获得一个 `/` 的结果。

可以通过 https://stackblitz.com/edit/github-rogx3k 提供一个我们可复现的链接

**Comment by yiescc** [comment]
希望在主应用的laypout拿到pathname做权限判断，但是现在拿不到
- 必须匹配到路由才拿的到，但是还没进去就肯定匹配不到路由

有没有其他方法可以获取pathname

**Comment by maoxiaoke** [comment]
@yiescc 请先复现下访问无匹配路由时，拿不到 pathname 的情况

**Comment by yiescc** [comment]
https://github.com/yiescc/demo-2021-11-10.git

**Comment by maoxiaoke** [comment]
@yiescc 额嗯，确实会存在一些疑惑~ 虽然我们推荐尽早渲染 `AppRouter`，避免重复渲染

**Comment by yiescc** [comment]
> @yiescc 额嗯，确实会存在一些疑惑~ 虽然我们推荐尽早渲染 `AppRouter`，避免重复渲染

那有没有其他的办法可以在不渲染AppRouter的情况下拿到实时的pathname，我们想要做权限判断

**Comment by maoxiaoke** [comment]
@yiescc 具体的权限判断形式是？另外，这个问题我们会修复下的~

**Comment by yiescc** [comment]
> @yiescc 具体的权限判断形式是？另外，这个问题我们会修复下的~

在FrameworkLayout拿到pathname，与权限列表进行匹配，如果不在权限列表，返回指定页面，如果在，则正常渲染布局
现在的问题就是不进入子应用就拿不到pathname，如果进去子应用在拿到pathname，页面会先渲染再跳转，不符合预期

**Comment by maoxiaoke** [comment]
@yiescc 已发布，可以更新下依赖
