### ISSUE TITLE
[QUESTION] 项目使用物料的业务组件会报Identifier 'React' has already been declared

### ISSUE THREAD

**Issue by yiescc** [alibaba/ice#4891]
背景：
- 项目使用jsx为"react-jsx"，引入业务组件报错
```
Uncaught SyntaxError: Identifier 'React' has already been declared
```
- 想把业务组件的jsx修改一样，但是发现业务组件的只支持
```
Argument for '--jsx' option must be: 'preserve', 'react-native', 'react'.
```

需求：
- 解决项目引用业务组件报错的问题

**Comment by ClarkXia** [comment]
参考文档 https://ice.work/docs/guide/basic/vite#uncaught-syntaxerror-identifier-react-has-already-been-declared
近期会优化这个逻辑 #4892

**Comment by ClarkXia** [comment]
已优化 react-jsx 的应用
