### ISSUE TITLE
[QUESTION] npm build 之后 第三方的样式丢失

### ISSUE THREAD

**Issue by yiescc** [alibaba/ice#4901]
背景：
- 第三方插件构建文件是这样
```
{
  "disableGenerateStyle": true,
  "plugins": [
    "build-plugin-component"
  ]
}

```
- 文件是这样
```
import React, { createElement, PropsWithChildren } from 'react';

import style from './Footer.module.scss';



```
- 我们在项目中引入了这个插件
- 在开发模式下没有问题
- 然后我们构建后，发现这个插件的样式没有被构建进来
- vite:false下build不会丢失

**Comment by imsobear** [comment]
是不是 npm 包的 sideEffects 没配对，被 treeshaking 了

**Comment by yiescc** [comment]
> 是不是 npm 包的 sideEffects 没配对，被 treeshaking 了

```
  "sideEffects": [
    "dist/*",
    "*.scss",
    "*.less",
    "*.css"
  ],
```
然后vite:true实际上生成了2个文件
index.css
vendor.css

发现丢失的样式在vendor里

**Comment by imsobear** [comment]
能提供个 demo 放 GitHub 上吗

**Comment by ClarkXia** [comment]
分包的文件理论上会动态引入，如果还有问题可以重开 issue
