### ISSUE TITLE
icejs 1.X 升级 2.X启动碰到的问题

### ISSUE THREAD

**Issue by zhangsixue-1992** [alibaba/ice#4903]
![image](https://user-images.githubusercontent.com/68992967/141429228-2e8eab5c-5aa6-468d-9efe-f6523bf79753.png)

**Comment by ClarkXia** [comment]
最好提供下复现的 demo

**Comment by zhangsixue-1992** [comment]
这个不方便啊，公司项目我切分支想搞一波升级看看。   你大概给一个思路么？问题错在那。

"ice.js": "^2.0.0",
node: v12.22.0,

**Comment by ClarkXia** [comment]
错误日志 可以看下具体报错的代码

**Comment by imsobear** [comment]
build.json 可以发一下

**Comment by zhangsixue-1992** [comment]
module.exports = {
  hash: false,
  minify: true,
  eslint: true,
  publicPath: '/base/',
  dropLogLevel: 'log',
  devServer: {
    historyApiFallback: true,
  },
  define: {
    env: process.env.NODE_ENV,
  },
  plugins: [
    [
      'build-plugin-fusion',
      {
        themePackage: '@alifd/theme-15584',
      },
    ],
  ],
  outputAssetsPath: {
    js: 'js[hash]',
    css: 'css[hash]',
  },
};

**Comment by imsobear** [comment]
实际安装的 build-plugin-fusion 版本是多少？升级到最新版本试下

**Comment by zhangsixue-1992** [comment]
应该可以了！谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月12日(星期五) 下午4:21
收件人: ***@***.***&gt;; 
抄送: "| zˊ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/ice] icejs 1.X 升级 2.X启动碰到的问题 (Issue #4903)





 
实际安装的 build-plugin-fusion 版本是多少？升级到最新版本试下
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
