### ISSUE TITLE
@builder/app-helpers 版本依赖问题

### ISSUE THREAD

**Issue by guoyunhe** [alibaba/ice#4904]
vite-service 依赖了  @builder/app-helpers ^2.0.0

https://github.com/alibaba/ice/blob/master/packages/vite-service/package.json#L25

但是代码里引用了 redirectImport

https://github.com/alibaba/ice/blob/master/packages/vite-service/src/plugins/import.ts#L2

我本地依赖装的 @builder/app-helpers 2.3.5 并没有这个导出，旧项目迁移 ICE v2 的时候就会报错(没有用 tnpm 模式)。

**Comment by ClarkXia** [comment]
迁移的项目依赖多个版本 @builder/app-helpers ？

**Comment by guoyunhe** [comment]
没有，旧项目本地开发，将 ice.js 改为 ^2.0.0 然后 tnpm install，依赖的 @builder/app-helpers 并没有升级。npm 的模式应该是在满足依赖的情况下，就不升级二级三级依赖。

**Comment by imsobear** [comment]
用 tnpm update

**Comment by guoyunhe** [comment]
我们团队这边统一配的 tnpm 使用 npm 模式，tnpm update 不会删除 node_modules 也不会更新已存在且满足依赖关系的旧包。

**Comment by imsobear** [comment]
那你就手动删除 node_modules 然后重装依赖。

**Comment by guoyunhe** [comment]
这个我当然知道。但是从软件开发的角度看，既然引用了 @builder/app-helpers 高版本才有的函数/类，那么对应的依赖版本号就应该提升到实际需要的最低版本。

**Comment by ClarkXia** [comment]
@guoyunhe OK 这个版本依赖关系 框架中重新梳理下

**Comment by ClarkXia** [comment]
2.3.0 中已修正依赖
