### ISSUE TITLE
Vite下proxy.pathRewrite是不是无效

### ISSUE THREAD

**Issue by xmsz** [alibaba/ice#4908]
背景
```
  "proxy": {
    "/api": {
      "enable": true,
      "target": "http://127.0.0.1:7010",
      "pathRewrite": { "^/api": "" }
    }
  },
```
- vite: true下 pathRewrite无效
- vite: false下正常

**Comment by inier** [comment]
proxy: {
    '/api/mock': {
      // mock api地址
      target: 'http://localhost:3000/mock/12',
      changeOrigin: true,
      pathRewrite: {
        '^/api/mock': '',
      },
    },
    '/api': {
      target: 'http://ip-api.com/',
      changeOrigin: true,
      pathRewrite: {
        '^/api': '',
      },
    },
  },

**Comment by inier** [comment]
而且命名配置的是http，自动给转成HTTPS了，表现很奇怪
![image](https://user-images.githubusercontent.com/7600897/142090581-a397e3b8-147a-4b04-9903-3b8c31ec95d5.png)

**Comment by ClarkXia** [comment]
2.2.0 版本已支持 proyx.pathRewrite

**Comment by DreamLee1997** [comment]
> 2.2.0 版本已支持 proxy.pathRewrite
3.x.x又不支持了
