### ISSUE TITLE
由icejs2.0.1升级2.1.3之后构建报错

### ISSUE THREAD

**Issue by BrettCao** [alibaba/ice#4909]
## What is the current behavior? 发生了什么？
![image](https://user-images.githubusercontent.com/17780089/141716628-d46df777-8d10-4545-857f-edc782d95120.png)

由icejs2.0.1升级2.1.3之后构建报错，提示缺少配置文件
## What is the expected behavior? 期望的结果是什么？
成功构建 并且运行
## Any additional comments? 相关环境信息？

- **ice.js Version**：2.1.3
- **build.json Configuration**：
{
  "router": {
    "lazy": true
  },
  "plugins": [
    [
      "build-plugin-antd",
      {
        "themeConfig": {
          "primary-color": "#000c17",
          "layout-sider-background": "#2f2929",
          "pro-layout-header-bg": "#2f2929"
        }
      }
    ],
    [
      "build-plugin-moment-locales",
      {
        "locales": [
          "zh-cn"
        ]
      }
    ]
  ],
  "proxy": {
    "/v4/": {
      "enable": true,
      "target": "http://127.0.0.1:4040"
    }
  }
}

- **Node Version**: v14.17.5
- **Platform**:
package.json
  "dependencies": {
    "@ant-design/icons": "^4.0.2",
    "@ant-design/pro-card": "^1.15.3",
    "@ant-design/pro-form": "^1.43.2",
    "@ant-design/pro-layout": "^6.5.1",
    "@ant-design/pro-table": "^2.56.0",
    "@multiavatar/multiavatar": "^1.0.7",
    "antd": "^4.0.0",
    "moment": "^2.24.0",
    "prop-types": "^15.5.8",
    "react": "^17.0.2",
    "react-dev-inspector": "^1.7.1",
    "react-dom": "^17.0.2",
    "react-helmet-async": "^1.1.2",
    "react-inlinesvg": "^2.3.0"
  },
  "devDependencies": {
    "@iceworks/spec": "^1.4.2",
    "@types/react": "^17.0.14",
    "@types/react-dom": "^17.0.9",
    "build-plugin-antd": "^0.1.2",
    "build-plugin-moment-locales": "^0.1.0",
    "eslint": "^7.30.0",
    "ice.js": "2.1.3",
    "stylelint": "^13.1.0"
  },

**Comment by ClarkXia** [comment]
确保原 node_modules 清空后再安装依赖

**Comment by BrettCao** [comment]
> 确保原 node_modules 清空后再安装
已经确认清空了

**Comment by ClarkXia** [comment]
删除 node_modules 后重新安装还是有问题？ 可以提供下复现的 demo
