### ISSUE TITLE
[REQUEST]vite下构建会出现「warning: "@charset" must be the first rule in the file」

### ISSUE THREAD

**Issue by xmsz** [alibaba/ice#4916]
背景
```
@charset "UTF-8"
```
- vite下构建，出现
```
 > <stdin>:39474:1: warning: "@charset" must be the first rule in the file
    39474 │ }@charset "UTF-8";
          ╵  ~~~~~~~~
   <stdin>:39472:0: note: This rule cannot come before a "@charset" rule
    39472 │ .c-cap {
          ╵ ^

```
- webpack下不会出现

**Comment by ClarkXia** [comment]
标准的 css 中 `@charset "UTF-8";`  应该只出现在头部，某个样式文件中中间出现了 charset，可以具体看下是哪个文件 针对性优化下

**Comment by xmsz** [comment]
> 标准的 css 中 `@charset "UTF-8";` 应该只出现在头部，某个样式文件中中间出现了 charset，可以具体看下是哪个文件 针对性优化下

next.min.scss
![image](https://user-images.githubusercontent.com/5879146/141891073-b9735328-d103-487e-9702-6eb692d73340.png)

**Comment by ClarkXia** [comment]
这个后续我们给 next 组件库提一个建议，打包 css 时移除
