### ISSUE TITLE
TS + ant design 的模板首屏样式有问题，页面错位

### ISSUE THREAD

**Issue by zaleGZL** [alibaba/ice#4918]
## 刷新页面的一瞬间会出现这个错误的样式
![image](https://user-images.githubusercontent.com/20339327/141936002-c9514642-170c-403b-98fe-2a87b24330bc.png)

初步定位是 ant-layout div 的样式问题，flex-direction 为 column 导致的
![image](https://user-images.githubusercontent.com/20339327/141936117-23a3f693-4730-4110-b661-adc55d97859e.png)

## 相关环境信息

- **ice.js Version**： 2.1.3
- **build.json Configuration**：
`{
  "vite": true,
  "plugins": [
    [
      "build-plugin-ignore-style",
      {
        "libraryName": "antd"
      }
    ]
  ]
}
`
- **Node Version**: v14.17.3
- **Platform**:  macos big sur version 11.6

**Comment by zaleGZL** [comment]
大佬们有什么好的解决方法嘛？

**Comment by imsobear** [comment]
@zaleGZL 固定到 6.27.1 这个版本试下呢

**Comment by imsobear** [comment]
我本地是 @ant-design/pro-layout@6.29.0 ，没法重现你这个问题。
