### ISSUE TITLE
微应用切换后访问二级路由白屏

### ISSUE THREAD

**Issue by yiescc** [alibaba/ice#4922]
背景：
[示例demo](https://github.com/yiescc/ice-demo-2021-11-17.git)
- main为主应用，配置了两个微应用child1，child2，均vite模式
- child1与child2配置了一级路由/test,二级路由/plan/test
- 在child1与child2切换过程中，访问一级路由没有问题，访问二级路由会出现白屏
- 示例操作：
- ①进入main的根目录
- ②点击child1，访问child1的/plan/test
- ③点击child2，什么都不做
- ④点击child1，访问child1的/plan/test，白屏

需求：
- 如何解决白屏问题？

**Comment by maoxiaoke** [comment]
@yiescc 问题已修复，可以关注下这个 pr 的变更

**Comment by yiescc** [comment]
大概什么时候会发版？

**Comment by maoxiaoke** [comment]
@yiescc 今天

**Comment by maoxiaoke** [comment]
已发布，请升级 ice.js 至最新版本

```bash
$ npm i ice.js@latest -S
```
