### ISSUE TITLE
ice 2.0 如何配置 postcss-pxtorem

### ISSUE THREAD

**Issue by edc-hui** [alibaba/ice#4926]
## What is the current behavior? 发生了什么？
配置postcss-pxtorem不成功

在build.json中配置了poscss-loader postcss-rxtorem 打包之后px没有转化成rem

## What is the expected behavior? 期望的结果是什么？
期望px成功转化为rem
## Any additional comments? 相关环境信息？

- **ice.js Version**： 
^2.0.0
- **build.json Configuration**：
![image](https://user-images.githubusercontent.com/33356467/142171581-83bc89fd-4ad6-4f74-8711-2a32d2af70b4.png)

- **Node Version**:
v14.15.3
- **Platform**:
mac os

**Comment by ClarkXia** [comment]
配置 postcssOptions 即可，参考 https://github.com/alibaba/ice/issues/4902  目前存在的问题明天会发版修复，临时方案，将 build.json 修改为 build.config.js 并配置 vite.css.postcss，参考

```js
module.exports = {
  vite: {
    css: {
      postcss: {
        plugins: [require('postcss-pxtorem')()], // 配置自己需要的 postcss 插件 参考 https://vitejs.dev/config/#css-postcss
      },
    },
  }
};

```

**Comment by edc-hui** [comment]
![image](https://user-images.githubusercontent.com/33356467/142179953-171b61c5-85cb-4b42-bc75-81272768733d.png)
按照您指导的已经生效，但是会报图中的一个警告，这个警告并没有啥用，因为vite.css.postcss 这种配置是有效的

**Comment by edc-hui** [comment]
@ClarkXia

**Comment by PiscesWD** [comment]
@edc-hui 
<img width="770" alt="企业微信截图_de30ffeb-c039-4c0a-b268-0c9f1fc1d2cf" src="https://user-images.githubusercontent.com/42125817/142297073-ace0f765-ce49-4675-9142-4fd5c9d8628d.png">



同样的情况下 ,postcss-pxtorem不起作用,页面白屏,报Uncaught SyntaxError: Identifier 'React' has already been declared

**Comment by imsobear** [comment]
> ![image](https://user-images.githubusercontent.com/33356467/142179953-171b61c5-85cb-4b42-bc75-81272768733d.png) 按照您指导的已经生效，但是会报图中的一个警告，这个警告并没有啥用，因为vite.css.postcss 这种配置是有效的

这是一个 hack 用法，不是框架推荐的用法，所以会有警告。正常是推荐通过 [postcssOptions](https://ice.work/docs/config/about#postcssoptions) 来配置，这块现在有一个小 bug 参考 https://github.com/alibaba/ice/issues/4902 ，今天发布的版本会修复。

**Comment by edc-hui** [comment]
@imsobear 已经更新至2.2.1版本，配置postcssOptions仍然是不起作用的。
![image](https://user-images.githubusercontent.com/33356467/142725934-0b083466-e4c0-4afd-8da6-7b018c27d036.png)

**Comment by ClarkXia** [comment]
@edc-hui 依赖已更新 删除下 node_modules 重新安装下依赖，确保 @builder/user-config 版本在 1.1.7 以上

**Comment by edc-hui** [comment]
@ClarkXia 我这边使用npm init ice icestark-framework @icedesign/stark-layout-scaffold命令创建了一个新的项目，我看了下 @builder/user-config 版本是 1.1.7 ，但是配置postcssOptions还是不起作用

**Comment by edc-hui** [comment]
@ClarkXia 好的  感谢  配置已经生效

**Comment by edc-hui** [comment]
![image](https://user-images.githubusercontent.com/33356467/142985459-697d44c6-4dcb-4375-abba-c5da62337bc8.png)
为了防止误导，正确的配置如图所示
