### ISSUE TITLE
pages下创建嵌套文件夹无法识别

### ISSUE THREAD

**Issue by iLikeStar** [alibaba/ice#4940]
src：
![image](https://user-images.githubusercontent.com/49977041/142398321-ddbe6348-3c8f-4376-bfb4-dba411207701.png)

.ice
![image](https://user-images.githubusercontent.com/49977041/142398387-016a823d-ea35-4c25-a11e-7c30130f717b.png)

![image](https://user-images.githubusercontent.com/49977041/142398635-5862f587-3ccc-48e2-b6ab-987f0947c2cb.png)

无论是lazy加载路由，还是非lazy，路由一直报错找不到/Manage/index.tsx

**Comment by ClarkXia** [comment]
提供下 build.json 信息

**Comment by iLikeStar** [comment]
@ClarkXia 
{
  "vite": true,
  "plugins": [
    [
      "build-plugin-antd"
    ]
  ],
    "lessLoaderOptions": {
        "modifyVars": {
            "primary-color": "#F53851"
        }
    }
}

**Comment by imsobear** [comment]
@iLikeStar 这个貌似是编辑器的报错吧？调试构建有问题吗？

**Comment by iLikeStar** [comment]
除了不能识别嵌套文件夹 其他没问题。。

**Comment by imsobear** [comment]
@iLikeStar 编辑器是什么？提供下 tsconfig.json / jsconfig.json 的内容。
