### ISSUE TITLE
build-scripts 会把 import { ConfigProvider } from '@alifd/next' 吃掉

### ISSUE THREAD

**Issue by guoyunhe** [alibaba/ice#4951]
## What is the current behavior? 发生了什么？

在 build-scripts 配置的组件库项目中，源码中 import { ConfigProvider } from '@alifd/next';

![image](https://user-images.githubusercontent.com/5836790/142579459-22d0eae1-a189-4725-a715-c904d8345170.png)

然后构建，在 lib 和 es 输出中，ConfigProvider 的导入都丢失了，其他导入正常。在应用中引用这个包报错。

## What is the expected behavior? 期望的结果是什么？

ConfigProvider 编译后能被正常导入

## Any additional comments? 相关环境信息？

- **ice.js Version**：build-scripts 0.1.32
- **build.json Configuration**：
```json
{
  "plugins": [
    "build-plugin-component",
    [
      "build-plugin-moment-locales",
      {
        "locales": ["zh-cn"]
      }
    ]
  ],
  "library": "BcOtFetch",
  "libraryTarget": "umd",
  "filename": "index",
  "minify": true,
  "externals": {
    "react": "React",
    "react-dom": "ReactDOM",
    "@alifd/next": "Next",
    "moment": "moment"
  }
}
```
- **Node Version**:
- **Platform**:

**Comment by guoyunhe** [comment]
这个 ConfigProvider 我们并没有当 React 组件来使用，而是当作类来使用它的一些静态方法/变量。我尝试手动加了一行 JSX 

![image](https://user-images.githubusercontent.com/5836790/142582804-c619b2d7-a67c-4ece-b100-4ceeba0c0d01.png)

import 就回来了。看来是 build-scripts 用了什么算法，只导入 JSX？

**Comment by maoxiaoke** [comment]
经分析，代码中 ConfigProvider 的用法如下：

```ts
import { ConfigProvider } from '@alifd/next';

(ConfigProvider as any).getLanguage();
```

`babel-plugin-import` [不会处理](https://github.com/umijs/babel-plugin-import/blob/master/src/index.js#L86) typescript `as` 语法，从而无法未能正确处理 `ConfigProvider` 的按需逻辑。[相关 issue](https://github.com/umijs/babel-plugin-import/pull/588)

### 解决方案

1. 不使用 `as` 语法
2. 未来组件开发不推荐使用 `babel-plugin-import` 来按需加载组件（直接使用 tree-shaking 能力），因此建议开启 `disableGenerateStyle: true` 相关讨论 #4705 

这个问题暂时不再跟进。
