### ISSUE TITLE
升级最新版本2.2.1报错React is not defined

### ISSUE THREAD

**Issue by wittech** [alibaba/ice#4952]
runtime.tsx:44 Uncaught ReferenceError: React is not defined
    at AuthStoreProvider (runtime.tsx:44)

**Comment by wittech** [comment]
关闭vite能正常访问

**Comment by ClarkXia** [comment]
确保依赖升级，特别是 @builder/vite-service 版本在 1.1.4，最好删除 node_modules 重新安装

**Comment by wittech** [comment]
@ClarkXia 已经更新了@builder/vite-service，并且删除了 node_modules 重新安装，还是报错。
![image](https://user-images.githubusercontent.com/48845269/142713096-2e483fb7-97e4-4748-94cf-caa367dd9f4f.png)

**Comment by ClarkXia** [comment]
能否提供个复现 demo

**Comment by weiaohan** [comment]
一样的问题，只有先关闭vite

**Comment by weiaohan** [comment]
使用yarn upgrade更新所有依赖解决问题
