### ISSUE TITLE
[RFC] icejs 国际化方案

### ISSUE THREAD

**Issue by luhc228** [alibaba/ice#4969]
# locale

支持在 icejs 应用中快速开启国际化功能。

### 安装插件

```shell
$ npm i build-plugin-ice-i18n -D
```

### 使用

在 `build.json` 中使用插件：

```json
{
  "plugins": [
    [
      "build-plugin-ice-i18n", {
        "locales": ["en-US", "zh-CN"],
        "defaultLocale": "zh-CN"
      }
    ]
  ]
}
```

上面的 `en-US` 和 `zh-CN` 是国际化语言的缩写，它们均遵循标准的[UTS 语言标识符](https://www.unicode.org/reports/tr35/tr35-59/tr35.html#Identifiers)。比如：

- `zh-CN`：中文（中国）
- `zh-HK`：中文（香港）
- `en-US`：英文（美国）
- `de`: 德文

**插件选项**

- `locales`: 必填，该应用支持的国际化语言；
- `defaultLocale`: 必填，该应用默认的国际化语言；
- `i18nRouting`: 选填，默认值是 `true`。设置为 `false` 后，则将关闭国际化路由；
- `redirect`: 选填，默认值是 `false`。设置为 `true` 后，则将重定向到偏好语言对应的页面。

## 国际化路由

国际化路由是指在页面路由中包含当前页面的国际化语言。开启该插件后，ice.js 会自动处理路由。

举个例子，假如在 `src/routes.ts` 有以下的路由配置：

```js
const routerConfig = [
  {
    path: '/home',
    exact: true,
    component: Home,
  },
]
```

同时在 `build.json` 中有以下配置：

```json
{
  "plugins": [
    [
      "build-plugin-ice-i18n", {
        "locales": ["en-US", "zh-CN", "nl-NL"],
        "defaultLocale": "zh-CN"
      }
    ]
  ]
}
```

则以下路由是可访问的：

- `/home`：显示 `zh-CN` 语言，默认语言没有前缀路由；
- `/en-US/home`：显示 `en-US` 语言；
- `/nl-NL/home`：显示 `nl-NL` 语言。

### 关闭国际化路由

插件默认开启国际化路由。如需关闭，则需要在 build.json 中增加以下配置：

```diff
{
  "plugins": [
    [
      "build-plugin-ice-i18n", {
        "locales": ["en-US", "zh-CN"],
        "defaultLocale": "zh-CN",
+       "i18nRouting": false 
      }
    ]
  ]
}
```

### useLocale

`useLocale` hook 用于在组件中获取和修改语言信息。

```jsx
import { useLocale } from 'ice';

function Home() {
  const [locale, setLocale] = useLocale();
  
  console.log('locale: ', locale);  // 'en-US'
  return (
    {/* 切换语言为 zh-CN */}
    <div onClick={() => setLocale('zh-CN')}>Set zh-CN</div>
  )
}
```

调用 `setLocale` 方法时，将更新 cookie 中的 `ice_locale` 的值。

### getLocale

`getLocale` 用于获取当前页面的语言。
```jsx
import { getLocale } from 'ice';

console.log(getLocale()); // 'zh-CN'
```

### getAllLocales

`getAllLocales` 用于获取当前配置的所有语言。

```jsx
import { getAllLocales } from 'ice';

console.log(getAllLocales()); // ['zh-CN', 'en-US']
```

### getDefaultLocale

`getDefaultLocale` 用于获取默认配置的语言。

```jsx
import { getDefaultLocale } from 'ice';

console.log(getDefaultLocale()); // 'zh-CN'
```

## 使用 i18n 库

插件不耦合任何 i18n 库，用户可以自行选择。目前社区比较流行的 i18n 库有 [react-intl](https://formatjs.io/docs/getting-started/installation/), [react-i18next](https://react.i18next.com/) 等等。

在 icejs 中使用 i18n 库很简单，以 react-intl 为例：

```jsx
// src/app.ts
import { IntlProvider } from 'react-intl';
import { useLocale } from 'ice';
import { messages } from './locales';

function LocaleProvider({ children }) {
  const [locale] = useLocale();
  const defaultLocale = getDefaultLocale();

  return (
    <IntlProvider 
      messages={messages[locale]} 
      locale={locale}
      defaultLocale={defaultLocale}
    >
      {children}
    </IntlProvider>
  );
}

const appConfig = {
  app: {
    addProvider: ({ children }) => {
      return (
        {/* 添加 Provider */}
      	<LocaleProvider>{children}</LocaleProvider>
      )
    }
  }
}

// src/locales/index.ts
import { LOCALES } from './locales';

const LOCALES = {
  ENGLISH: 'en-US',
  ZH_CN: 'zh-CN'
};

const messages = {
  [LOCALES.ENGLISH]: {
    homeTitle: 'Home',
    aboutTitle: 'About',
  },
  [LOCALES.ZH_CN]: {
    homeTitle: '首页',
    aboutTitle: '关于',
  },
};
```

## 切换路由

我们可以使用 `<Link>` 组件或者 `history.push/replace` 进行路由切换：

```jsx
import { useLocale, getAllLocales, Link, useLocation } from 'ice';

export default function LocaleSwitcher() {
  const location = useLocation();
  const [activeLocale, setLocale] = useLocale();
  const allLocales = getAllLocales();
  const otherLocales = allLocales.filter((locale) => activeLocale !== locale);

  function switchAboutZHCNPage () {
    history.push('/about');
    setLocale('zh-CN');
  }
  return (
    <div>
      <div onClick={() => switchAboutZHCNPage()}>
        切换到中文
     </div>
     <ul>
        {
          otherLocales.map((locale: string) => {
            return (
              <li key={locale}>
                <Link 
                  to={location.pathname}
                  onClick={() => setLocale(locale)}>
                  {locale}
                </Link>
              </li>
            );
          })
        }
      </ul>
    </div>
  );
}

```

## 自动重定向

根据当前语言环境自动跳转到对应的国际化路由。其中，语言环境的识别顺序的规则如下：

- CSR：cookie 中 `ice_locale` 的值 > `window.navigator.language` > `defaultLocale`
- SSR：cookie 中 `ice_locale` 的值 > `res` 的 Header 中的 `Accept-Language` > `defaultLocale`

在 `build.json` 开启方式如下：

```diff
{
  "plugins": [
    [
      "build-plugin-ice-i18n", {
        "locales": ["en-US", "zh-CN"],
        "defaultLocale": "zh-CN",
+       "redirect": true 
      }
    ]
  ]
}
```

## SSG

在 [SSG](/docs/guide/advanced/ssg) 场景下，将根据在 `build.json` 中配置的 `locales` 字段，在 `build` 阶段会生成不同国际化语言对应的 html：

```markdown
├── build
|  ├── 404.html
|  ├── about
|  |  └── index.html
|  ├── en-US
|  |  ├── about
|  |  |  └── index.html
|  |  └── index.html
|  ├── index.html
```

## 参考链接

- nextjs i18n-routing：https://nextjs.org/docs/advanced-features/i18n-routing
- umi locale 文档：https://umijs.org/zh-CN/plugins/plugin-locale
- umi locale RFC：https://github.com/umijs/umi-next/issues/7
- nextjs-i18n-example：https://github.com/luhc228/nextjs-i18n-app

**Comment by ZhongMingKun** [comment]
期待，什么时候发布

**Comment by usercao** [comment]
最新版本使用`lingui`生态未按预期工作,[这是一个最小实例](https://github.com/usercao/ice-test)
![image](https://user-images.githubusercontent.com/13760476/149081417-5d380d8f-d545-408f-882b-69ae065a9a6a.png)
使用`lingui extract`也会报错

**Comment by usercao** [comment]
希望兼容`LinguiJS`的cli命令 #5132

**Comment by luhc228** [comment]
已发布 build-plugin-ice-i18n 插件支持

**Comment by usercao** [comment]
![image](https://user-images.githubusercontent.com/13760476/149740134-a3dc01d4-29af-4a00-bf70-b0dae5699258.png)
![image](https://user-images.githubusercontent.com/13760476/149740189-c3ba9113-b67c-42dd-9761-b6173173b432.png)
按照文档配置报错

**Comment by usercao** [comment]
@luhc228 icejs 2.4.3 和 2.5.0版本均无法使用，是还需要升级什么依赖吗？

**Comment by luhc228** [comment]
> @luhc228 icejs 2.4.3 和 2.5.0版本均无法使用，是还需要升级什么依赖吗？ 重新yarn create ice也不行，npm主版本还是2.4.3

能提供下具体的 demo ？

**Comment by usercao** [comment]
@luhc228 仓库地址[https://github.com/usercao/ice-test](https://github.com/usercao/ice-test)，还有个问题icejs在使用LinguiJS这个国际化方案的时候，build里面配置的不能使用cli命令，希望可以集成到一个配置文件里，这是问题地址 #5132

**Comment by luhc228** [comment]
> @luhc228 仓库地址https://github.com/usercao/ice-test，还有个问题icejs在使用LinguiJS这个国际化方案的时候，build里面配置的不能使用cli命令，希望可以集成到一个配置文件里，这是问题地址 #5132

恩。我修一下

**Comment by usercao** [comment]
@luhc228 希望能兼容下`LinguiJS`的开发和CLI的统一配置，这个库比react-intl, react-i18next 好用很多🙏

**Comment by luhc228** [comment]
> @luhc228 希望能兼容下`LinguiJS`的开发和CLI的统一配置，这个库比react-intl, react-i18next 好用很多🙏

具体需要怎样兼容呢？我简单看了下 issue 是目前在 icejs 下使用需要增加 babel 的配置。

从 icejs 国际化方案设计来说，不想耦合太多其他 i18n 库的兼容逻辑。

**Comment by usercao** [comment]
@luhc228 希望能把`babel.config.js`和`build.json`中的
```js
plugins: ['macros'],
presets: ['@babel/preset-typescript'],
```
内置icejs中，`yarn start`与`yarn lingui extract`是统一走`icejs`的`build.json`配置，配置不统一让人很迷茫

**Comment by usercao** [comment]
@luhc228 react-intl和react-i18next都长期使用过，LinguiJS与之相比有如下优点
1. LinguiJS的语法与其他两位完全相同，API几乎完全一样可以无任何难度上手
2. LinguiJS提供完整的i18n工作流方案，在API使用上比竞品简洁清晰，搭配vscode的`i18n Ally`插件做i18n不能更爽
3. LinguiJS的社区非常健康积极活跃，都是以分钟计的回复速度

[Lingui.js—React 前端国际化工作流解决方案](https://zhuanlan.zhihu.com/p/291202582)

> 从 icejs 国际化方案设计来说，不想耦合太多其他 i18n 库的兼容逻辑。

`icejs`的理念是**基于 React 的渐进式应用框架**，是否可以做成插件形式的例如`store`这样的开关方式？这样用户使用其他i18n库也不会有任何冲突，当然如果能使用最方便开发者使用的i18n库、集成开箱即用的i18n方案必然是锦上添花了

如果没有想法希望能统一`icejs`的开发与打包`build.json`配置

**Comment by luhc228** [comment]
@usercao 我建议是，针对 LinguiJS 单独搞一个插件，欢迎 PR。

**Comment by usercao** [comment]
> @usercao 我建议是，针对 LinguiJS 单独搞一个插件，欢迎 PR。

业务需求都忙不过来了=。=

**Comment by luhc228** [comment]
> @luhc228 仓库地址https://github.com/usercao/ice-test，还有个问题icejs在使用LinguiJS这个国际化方案的时候，`build.json`里面配置的不能使用cli命令，希望可以集成到一个配置文件`build.json`里，这是问题地址 #5132

已发布 build-plugin-ice-i18n@0.1.1 版本修复

**Comment by usercao** [comment]
> 已发布 build-plugin-ice-i18n@0.1.1 版本修复 @usercao

测试OK👍

**Comment by usercao** [comment]
![image](https://user-images.githubusercontent.com/13760476/150080905-a33a215d-8557-4b43-88f0-3b0fccdfe2c6.png)
@luhc228 不同path会出现多个相同cookie

**Comment by usercao** [comment]
![image](https://user-images.githubusercontent.com/13760476/150081450-4058385c-a223-4a5a-a5c4-0c8aa5550346.png)
切换路由后静态资源地址也找不到了
