### ISSUE TITLE
动态加载产物命名全是 index1 index2 index3

### ISSUE THREAD

**Issue by guoyunhe** [alibaba/ice#4970]
## What is the current behavior? 发生了什么？

页面组件定义如下，文件名都是 index.tsx

![image](https://user-images.githubusercontent.com/5836790/143375873-8367a489-4284-4460-be4f-b7596a75f961.png)

在使用动态加载之后，构建产物是

![image](https://user-images.githubusercontent.com/5836790/143375794-3645d8dc-8b92-4e20-a255-81b3ee9d2a24.png)

## What is the expected behavior? 期望的结果是什么？

希望在文件名是 index.tsx 的时候，能够按照文件夹的名字来命名产物，生成 dashboard.js, settings.js 等，比较容易在第三方应用中动态加载

## Any additional comments? 相关环境信息？

- **ice.js Version**：2.2.2
- **build.json Configuration**：
```json
{
  "alias": {
    "@": "./src/"
  },
  "browserslist": {
    "chrome": "49",
    "ie": "11"
  },
  "eslint": false,
  "devPublicPath": "/customs/",
  "plugins": [
    [
      "build-plugin-fusion",
      {
        "themePackage": "@alife/theme-blue"
      }
    ],
    [
      "build-plugin-moment-locales",
      {
        "locales": ["zh-cn"]
      }
    ]
  ],
  "publicPath": "/customs/",
  "tsChecker": true,
  "vite": true
}
```
- **Node Version**: 16
- **Platform**: macOS

**Comment by imsobear** [comment]
https://github.com/alibaba/ice/issues/4818 相同的问题，这个先关掉了
