### ISSUE TITLE
ice.js1.x支持类似 updateRoutes 的能力

### ISSUE THREAD

**Issue by rootsli** [alibaba/ice#4973]
## What is the current behavior? 发生了什么？
系统是一个SPA应用，希望支持路由的动态注册。
用户首先进入登录页，登录成功后从服务器拉取菜单列表，然后根据菜单列表注册路由并渲染菜单。目前通过modifyRoutes和getInitialData实现不了。

访问域名=>跳转登录页（modifyRoutes和getInitialData在这里执行了）=>输入用户名密码=>登录成功，拉取权限菜单=>注册路由（这步需要注册路由，在哪里做？modifyRoutes和getInitialData不会再执行）=>渲染菜单

相应issue连接：https://github.com/alibaba/ice/issues/4872

## What is the expected behavior? 期望的结果是什么？
ice.js1.x支持类似 updateRoutes 的能力

## Any additional comments? 相关环境信息？

- **ice.js Version**：1.12.0
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by imsobear** [comment]
重复 runApp 测试了怎么样？

**Comment by ClarkXia** [comment]
方案设计
1. 路由配置上全量配置，通过下发的权限决定哪些路由有访问权限
2. runApp 支持重复调用
3. 业务逻辑上去支持，比如设计 /:auth 动态匹配路径，根据返回的路由结果决定渲染的组件

**Comment by rootsli** [comment]
> 方案设计
> 
> 1. 路由配置上全量配置，通过下发的权限决定哪些路由有访问权限
> 2. runApp 支持重复调用
> 3. 业务逻辑上去支持，比如设计 /:auth 动态匹配路径，根据返回的路由结果决定渲染的组件

@ClarkXia 路由跳转的时候能支持全局拦截吗？，在拦截的时候，判断是否有权限，没有权限，则跳转没权限页面。

**Comment by imsobear** [comment]
需要通过 wrapper 来实现 https://ice.work/docs/guide/basic/router#%E8%B7%AF%E7%94%B1%E9%AB%98%E9%98%B6%E7%BB%84%E4%BB%B6
