### ISSUE TITLE
Cannot find module 'create-cli-utils/lib/cli'

### ISSUE THREAD

**Issue by Yongle-Fu** [alibaba/ice#4976]

**Comment by Yongle-Fu** [comment]
not found ice/node_modules/create-cli-utils folder

**Comment by ClarkXia** [comment]
提供下复现 demo

**Comment by Yongle-Fu** [comment]
master分支clone之后  npm i  or  yarn install  完成后
create-cli-utils没有lib文件夹

**Comment by ClarkXia** [comment]
@Yongle-Fu 通过 `npm init ice ice-demo`  尝试复现下，create-cli-utils 的发包应该是包含 lib 目录的

**Comment by Yongle-Fu** [comment]
通过 npm init ice ice-demo 是正常的
