### ISSUE TITLE
icejs 1.x 下 useRequest 的使用问题咨询

### ISSUE THREAD

**Issue by as0026** [alibaba/ice#4978]
接手以前的项目，useRequest的请求方式如下：
```
const {data, loading, error, request} = useRequest({
      url: '/login',
      method: 'POST'
  });
await request({
    data: {
        name: 'admin',
        pwd: '123456'
    }
})
```
现在官网2.x的使用方式已有改变，请问应该使用ice.js的版本号

**Comment by ClarkXia** [comment]
request 的使用方式没有变化，看下具体遇到什么问题

**Comment by as0026** [comment]
是这样的， 现在使用如上请求会Required request body is missing错误。
我按照现有的官方文档，是可以请求成功的。代码如下
```
const {loading, request} = useRequest(paramsObj => ({
    url: login_url,
    method: 'POST',
    data: paramsObj
}));
const objData = {
    username: values.name,
    password: values.password,
    validateCode: values.validateCode
};
await request(objData);
```
所以我觉得是ice.js的版本不同， 使用useRequest的方式不一样。
ps: 接手的项目有好几十个不同的请求， 所以都去修改的话工作量有点大。

**Comment by ClarkXia** [comment]
useRequest 依赖 "@ahooksjs/use-request": "^2.0.0"，1.x 到 2.x 没有发生过 breakchange 版本

**Comment by as0026** [comment]
会不会是低版本的ice.js没有用到ahooksjs，是不是用到了umijs/use-request。因为我在1.0.6版本的ice.js，package-lock.json中是没有ahooksjs的依赖。

**Comment by ClarkXia** [comment]
@as0026 1.0.6 版本的确比较老了，@ahooksjs/use-request 在 ice.js 1.4.0 版本中引入

**Comment by as0026** [comment]
@ClarkXia 提问的请求代码的确是报Required request body is missing错误。
那能确定提问的请求代码大概是哪个ice.js版本吗

**Comment by ClarkXia** [comment]
我们验证确定下  上面方式是在哪个版本支持的

**Comment by imsobear** [comment]
@as0026 为啥不直接升级到 1.x 的最新版本 1.18.3？

- icejs 低于 1.5.0 里的 useRequest 是自行实现的，没有依赖任何三方库：[代码](https://unpkg.alibaba-inc.com/browse/build-plugin-ice-request@1.4.2/request/useRequest.ts)
- icejs@1.5.0 开始切到 ahoohs/useRequest，能力增强同时兼容之前的实现：[代码](https://unpkg.alibaba-inc.com/browse/build-plugin-ice-request@1.5.0/template/useRequest.ts)

**Comment by imsobear** [comment]
看了下你们的讨论，我还没清楚 @as0026 的问题/需求是什么？建议描述清楚点。

**Comment by as0026** [comment]
改回1.4.2版本，问题解决了。非常感谢
