### ISSUE TITLE
打包好的文件发布到服务之后路由失效

### ISSUE THREAD

**Issue by WaveStill** [alibaba/ice#498]
registerServiceWorker.js:80 Error during service worker registration: DOMException: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).

不知道是路由的问题，还是service worker 的问题， 求大佬指点

**Comment by yuanyan** [comment]
@WaveStill 参考报错信息，serviceworker 必须是`https`：`Only secure origins are allowed`
