### ISSUE TITLE
微前端icestark，使用官网创建子应用命令，创建出来的子应用，在主应用中加载报错

### ISSUE THREAD

**Issue by edc-hui** [alibaba/ice#4980]
## What is the current behavior? 发生了什么？
通过npm init ice icestark-child @icedesign/stark-child-scaffold创建出来的子应用，build.json中vite设置为true，打包出来的子应用，在主应用中加载正常，build.json中vite设置为false，打包出来的子应用，在主应用中加载报错，错误如图所示:

![image](https://user-images.githubusercontent.com/33356467/144024183-dcf5542e-8624-46b6-bacf-29d69e0ab936.png)

## What is the expected behavior? 期望的结果是什么？
webpack模式下打包，子应用也能正常加载
## Any additional comments? 相关环境信息？

- **ice.js Version**：
- 2.2.3
- **build.json Configuration**：
- {
  "vite": false,
  "plugins": [
    [
      "build-plugin-icestark",
      {
        "type": "child"
      }
    ],
    [
      "build-plugin-moment-locales",
      {
        "locales": [
          "zh-cn"
        ]
      }
    ],
    [
      "build-plugin-ignore-style",
      {
        "libraryName": "@alifd/next"
      }
    ]
  ],
  "postcssOptions": {
    "plugins": {
      "@huisiyu/ptr": {
        "rootValue": 100,
        "propList": [
          "*"
        ]
      }
    }
  },
  "tsChecker": true,
  "outputDir": "dist"
}

- **Node Version**:
- v14.15.3
- **Platform**:
- mac os

**Comment by edc-hui** [comment]
补充：图中错误是主应用使用vite打包，子应用使用webpack打包，子应用不能正常加载。

**Comment by maoxiaoke** [comment]
移除 loadScriptMode 配置试下，设置为  import 会默认以 esm 微应用进行加载，而你的微应用不是 esm 应用

**Comment by edc-hui** [comment]
补充：主应用和子应用同时使用webpack模式打包也是会报错。
刚刚测试移除 loadScriptMode 配置，仍然是报错。
![image](https://user-images.githubusercontent.com/33356467/144028363-a1446c73-f807-4c20-a27b-587875abb3ff.png)
这张图中的错误是出现在： 主应用和子应用都是使用webpack模式打包
@maoxiaoke

**Comment by maoxiaoke** [comment]
看错误是 404，确认下资源地址呢

**Comment by edc-hui** [comment]
这个资源 地址怎么确定？我测试过程是这样的，主应用中配置 如图所示
![image](https://user-images.githubusercontent.com/33356467/144029798-59908d00-4654-42d2-886a-900c3cf91a9d.png)
子应用使用yarn build打包之后(子应用的端口号配置是8102)，主应用yarn start启动，然后从主应用中使用history.push进行跳转，然后就报图中的错误了

**Comment by maoxiaoke** [comment]
@edc-hui ice 应用 dev 下资源的地址是 `//127.0.0.1:host/js/index.js` 和 `//127.0.0.1:host/css/index.css`

**Comment by edc-hui** [comment]
@maoxiaoke ice应用dev下资源地址应该是//127.0.0.1:host/dist/js/index.js 和 //127.0.0.1:host/dist/css/index.css吧？
我看官网案例我的理解是，子应用需要先yarn build打包出来一个dist文件夹之后，才可以从主应用中加载子应用。大佬，我的理解对么？

**Comment by maoxiaoke** [comment]
@edc-hui 访问一下就知道了，ice 应用 build 的产物在 build 文件夹呀~
