### ISSUE TITLE
ice的项目，改成成微前端的子应用，是通用的吗？兼容阿里的qiankun、字节的garfish吗？

### ISSUE THREAD

**Issue by SKHon** [alibaba/ice#4983]
这个文档中，改正微前端子应用，兼容阿里的qiankun、字节的garfish吗？
https://ice.work/docs/guide/advanced/icestark#%E5%BE%AE%E5%BA%94%E7%94%A8%E5%AD%90%E5%BA%94%E7%94%A8

**Comment by maoxiaoke** [comment]
qiankun 是兼容的，字节的不确定

**Comment by lbarakidouji** [comment]
> qiankun 是兼容的，字节的不确定

直接修改为 ice-stark 的子应用就可以兼容 qiankun 吗？
