### ISSUE TITLE
ice 启动报错

### ISSUE THREAD

**Issue by hyuanyuanlisiwei** [alibaba/ice#4996]
## What is the current behavior? 发生了什么？
npm run start 报错

<img width="932" alt="截屏2021-12-02 下午4 26 32" src="https://user-images.githubusercontent.com/11502089/144385308-b2c343c5-e47a-445f-95ef-350c6dbc88b3.png">

## Any additional comments? 相关环境信息？

- **ice.js Version**：ice -V 显示3.1.0.  但是生成的项目中package.json 显示 ice.js": "^2.0.0"
- **build.json Configuration**：
- **Node Version**: v16.13.1
- **Platform**:  8.1.2

**Comment by ClarkXia** [comment]
使用 ice.js 2.3.0

**Comment by hyuanyuanlisiwei** [comment]
> 

怎么升级 ice.js

**Comment by ClarkXia** [comment]
npm install ice.js@2.3.0 或者删除 node_modules 后重新安装，ice.js 的最新版本为 2.3.0

**Comment by hyuanyuanlisiwei** [comment]
> npm install ice.js@2.3.0 或者删除 node_modules 后重新安装，ice.js 的最新版本为 2.3.0
这两个方法都试了 报错
<img width="852" alt="截屏2021-12-02 下午4 44 39" src="https://user-images.githubusercontent.com/11502089/144388098-9338eb5b-1f0a-4b1c-a51f-20b1d61e5144.png">

<img width="953" alt="截屏2021-12-02 下午4 45 38" src="https://user-images.githubusercontent.com/11502089/144388111-c7b4b741-36db-4d84-b18b-6680fd03f772.png">

**Comment by maoxiaoke** [comment]
@hyuanyuanlisiwei  用的什么源安装的，可能没有同步过来 https://www.npmjs.com/package/ice.js/v/2.3.0

npm 这个包已经发布了

**Comment by hyuanyuanlisiwei** [comment]
> 
➜  test npm config get registry

https://registry.npm.taobao.org/
用的淘宝的

**Comment by maoxiaoke** [comment]
https://registry.npm.taobao.org/ice.js 淘宝 npm 已经同步了

**Comment by hyuanyuanlisiwei** [comment]
> https://registry.npm.taobao.org/ice.js 淘宝 npm 已经同步了，现在更新下呢

还是不行:
➜  test npm install
npm ERR! code ETARGET
npm ERR! notarget No matching version found for ice.js@^2.3.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lisiwei/nodeModules/node_cache/_logs/2021-12-02T09_15_25_134Z-debug.log
➜  test

**Comment by maoxiaoke** [comment]
@hyuanyuanlisiwei https://npmmirror.com/ 是不是应为淘宝换源造成的，换成这个源试下 https://registry.npmmirror.com

**Comment by hyuanyuanlisiwei** [comment]
> @hyuanyuanlisiwei https://npmmirror.com/ 是不是应为淘宝换源造成的，换成这个源试下 https://registry.npmmirror.com

还是报同样的错,  我只是想正常启动项目,  那就必须安装2.3.0吗,  我安装2.3.0以下可以吗

**Comment by hyuanyuanlisiwei** [comment]
> @hyuanyuanlisiwei https://npmmirror.com/ 是不是应为淘宝换源造成的，换成这个源试下 https://registry.npmmirror.com
在iterm2终端下 一直失败,  在webstorm终端中  重新install  start 成功了.  好奇怪

**Comment by hyuanyuanlisiwei** [comment]
我知道原因了, 跟node版本有关系,  16太高了,  换成14就好了
