### ISSUE TITLE
Cursor out of focus when modify the block filename

### ISSUE THREAD

**Issue by phobal** [alibaba/ice#5]
### 问题
在修改 block 文件名的时候，每删除一个字母鼠标光标就是去了焦点，如图：
![ice_bug](https://user-images.githubusercontent.com/9244211/34672189-7f44d692-f4b8-11e7-811a-3914cc8a46ab.jpg)
### 环境
系统版本：macOS 10.13.2 (17C88)
node 版本：v8.9.3

**Comment by yujiangshui** [comment]
@noyobo 是不是拦截事件导致的？

**Comment by noyobo** [comment]
Iceworks v0.1.2 fixed it.
