### ISSUE TITLE
版本1.0升级到2.0 使用vite编译报错的问题 does not provide an export named 'withRouter'

### ISSUE THREAD

**Issue by liqupan** [alibaba/ice#5003]
## What is the current behavior? 发生了什么？
版本1.0升级到2.0 使用vite编译报错的问题
Uncaught SyntaxError: The requested module '/node_modules/.vite/react-router.js?v=f58f2b22' does not provide an export named 'withRouter'
![image](https://user-images.githubusercontent.com/21078925/144551997-7fa72340-514f-4515-9251-c0d004ac5a79.png)

- **ice.js Version**：2.0
- **build.json Configuration**：
- {
  "plugins": [
    [
      "build-plugin-antd",
      {
        "themeConfig": {
          "primary-color": "#2A64EB"
        }
      }
    ],
    [
      "build-plugin-moment-locales",
      {
        "locales": [
          "zh-cn"
        ]
      }
    ],
    [
      "build-plugin-icestark",
      {
        "uniqueName": "frameworkJsonp"
      }
    ]
  ],
  "vite": true
}

- **Node Version**:v14.16.0

**Comment by ClarkXia** [comment]
提供下具体的复现 demo

**Comment by ClarkXia** [comment]
提供复现 demo 后重开，目前没遇到类似问题
