### ISSUE TITLE
依照官方教程下载安装后，执行npm start 无法正常启动

### ISSUE THREAD

**Issue by theecn** [alibaba/ice#5004]
## What is the current behavior? 发生了什么？
按照官方提供的脚本
 ```
npm init ice icestark-child @icedesign/stark-child-scaffold
npm install
npm start
```
无法正常运行

![image](https://user-images.githubusercontent.com/22100544/144552074-5400b74c-2df7-42bc-8a2f-7c9d783c1fd1.png)

## What is the expected behavior? 期望的结果是什么？
能够正常启动，看到效果
## Any additional comments? 相关环境信息？

- **ice.js Version**：2.2.3
- **build.json Configuration**：
```
- {
  "vite": true,
  "plugins": [
    [
      "build-plugin-icestark",
      {
        "type": "child"
      }
    ],
    [
      "build-plugin-moment-locales",
      {
        "locales": [
          "zh-cn"
        ]
      }
    ],
    [
      "build-plugin-ignore-style",
      {
        "libraryName": "@alifd/next"
      }
    ]
  ]
}
```
- **Node Version**:v14.17.3
- **Platform**:macos

**Comment by ClarkXia** [comment]
安装 ice.js 2.3.0 版本

**Comment by theecn** [comment]
还没发版吧 还是淘宝镜像有延迟？
![image](https://user-images.githubusercontent.com/22100544/144555990-bc834041-a597-4742-8f4d-af68852b891e.png)

**Comment by theecn** [comment]
镜像源换了就可以了

**Comment by ClarkXia** [comment]
@theecn 哪个镜像 我们去同步下
