### ISSUE TITLE
将一个react15 的项目改造成一个微应用 使用@ice/stark-app  可以改造吗

### ISSUE THREAD

**Issue by hyuanyuanlisiwei** [alibaba/ice#5005]
## Any additional comments? 相关环境信息？

- **ice.js Version**：
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by maoxiaoke** [comment]
完全可以。微前端的常见的业务场景就是面向「旧系统迁移」，参照 [已有 React 项目改造为微应用](https://micro-frontends.ice.work/docs/guide/use-child/react#%E5%B7%B2%E6%9C%89-react-%E9%A1%B9%E7%9B%AE%E6%94%B9%E9%80%A0%E4%B8%BA%E5%BE%AE%E5%BA%94%E7%94%A8) 的方式记性迁移即可
