### ISSUE TITLE
vite模式下 配置hash = "contenthash" ，执行打包报错

### ISSUE THREAD

**Issue by theecn** [alibaba/ice#5007]
## What is the current behavior? 发生了什么？
vite模式下 配置hash = "contenthash" ，执行打包报错

![image](https://user-images.githubusercontent.com/22100544/144559514-f6050c13-80b5-4934-860c-673ae52a0356.png)

## What is the expected behavior? 期望的结果是什么？
能够执行正常打包
## Any additional comments? 相关环境信息？

- **ice.js Version**：2.3.0
- **build.json Configuration**：
```
{
  "vite": true,
  "plugins": [
    [
      "build-plugin-icestark",
      {
        "type": "child"
      }
    ],
    [
      "build-plugin-moment-locales",
      {
        "locales": [
          "zh-cn"
        ]
      }
    ],
    [
      "build-plugin-ignore-style",
      {
        "libraryName": "@alifd/next"
      }
    ]
  ],
  "hash": "contenthash"
}

```
- **Node Version**:  v14.17.3
- **Platform**: macos

**Comment by ClarkXia** [comment]
https://github.com/alibaba/ice/issues/4915 参考这个 issue，vite 模式下暂时不支持
