### ISSUE TITLE
 store.useModel('userStore')  报错

### ISSUE THREAD

**Issue by dmyz** [alibaba/ice#5008]
## 问题

Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.

![image](https://user-images.githubusercontent.com/15307200/144559938-4b1b7866-1bd2-4a71-be1f-be6a0211ed44.png)

![image](https://user-images.githubusercontent.com/15307200/144560369-7368f8ba-77fe-4757-9494-b52dbda7a9c8.png)

## Any additional comments? 相关环境信息？

- **ice.js Version**：2.3.0
- **build.json Configuration**：
- **Node Version**: v16.13.0
- **Platform**: windwos

**Comment by luhc228** [comment]
这个和 icejs 内置的状态管理没有关系，可以看下是否需要在组件卸载时取消订阅状态
