### ISSUE TITLE
咱们的路由支持多级嵌套么，我写了两级嵌套就不好使

### ISSUE THREAD

**Issue by 8708798** [alibaba/ice#5014]
![image](https://user-images.githubusercontent.com/42125669/144792754-aec09c16-e1c8-4201-9d81-c6052bfdad94.png)

**Comment by 8708798** [comment]
![image](https://user-images.githubusercontent.com/42125669/144793078-76954ee7-a82f-4484-b2e7-65e77f05836d.png)
这样的情况下是读不到页面的，能否告知一下原因

**Comment by 8708798** [comment]
> /finance 那层的`exact: true`去除

去掉以后就会显示了finance的页面信息，而不是edit的信息

**Comment by ClarkXia** [comment]
Finance 组件怎么写的

**Comment by 8708798** [comment]
> Finance 组件怎么写的

![image](https://user-images.githubusercontent.com/42125669/144803943-b36233d8-f79e-4cb1-b8a2-4c2f2cda9624.png)
就是最平常的表格

**Comment by 8708798** [comment]
![image](https://user-images.githubusercontent.com/42125669/144804059-52d3c70e-ca42-4660-9532-25876934b195.png)
这么写就ok的，如果是嵌套在children里面就不行

**Comment by ClarkXia** [comment]
如果你希望 /finance/edit 显示具体的 edit 内容，那 Finance 组件应该作为 layout 渲染，即带有 `children`，比如：

```js
const Finance = ({ children }) => <><h1>Finance</h1>{children}</>
```

**Comment by 8708798** [comment]
> 如果你希望 /finance/edit 显示具体的 edit 内容，那 Finance 组件应该作为 layout 渲染，即带有 `children`，比如：
> 
> ```js
> const Finance = ({ children }) => <><h1>Finance</h1>{children}</>
> ``

父元素只能当做layout使用是吧，懂了

**Comment by imsobear** [comment]
父元素只能当做layout使用是吧，懂了

Yes~
