### ISSUE TITLE
启用vite，编译部署到GitHub pages 访问出现 404 not found

### ISSUE THREAD

**Issue by niexq** [alibaba/ice#5016]
## What is the current behavior? 发生了什么？
使用icejs，部署编译到Github pages访问出现404
复现地址：https://github.com/niexq/appworks-github-pages

![](https://raw.githubusercontent.com/niexq/picbed/main/picgo/icevitebasefix.png)

![](https://raw.githubusercontent.com/niexq/picbed/main/picgo/icevitebasebuildfix.jpg)

## What is the expected behavior? 期望的结果是什么？

期望build.json启动vite时，支持[配置base](https://cn.vitejs.dev/config/#base)

build.json
```json
{
  "vite": true,
  "base": "./"
}
```

关闭vite，启动 Webpack 的 publicPath 部署到Github pages 访问正常

build.json
```json
{
  "vite": false,
  "plugins": [
    [
      "build-plugin-moment-locales",
      {
        "locales": [
          "zh-cn"
        ]
      }
    ],
    [
      "build-plugin-ignore-style",
      {
        "libraryName": "@alifd/next"
      }
    ]
  ],
  "publicPath": "./"
}

```

## Any additional comments? 相关环境信息？

- **ice.js Version**：^2.0.0
- **build.json Configuration**：
```json
{
  "vite": true,
  "plugins": [
    [
      "build-plugin-moment-locales",
      {
        "locales": [
          "zh-cn"
        ]
      }
    ],
    [
      "build-plugin-ignore-style",
      {
        "libraryName": "@alifd/next"
      }
    ]
  ],
  "base": "./"
}
```
- **Node Version**: v14.15.1
- **Platform**: macOS Big Sur

**Comment by ClarkXia** [comment]
vite 模式下同样配置 publicPath 即可

**Comment by niexq** [comment]
> ClarkXia

感谢大佬
