### ISSUE TITLE
createStore找不到，ice2.3.1，已经重启重新下载多次

### ISSUE THREAD

**Issue by TingtingXuYilongWang** [alibaba/ice#5018]
![image](https://user-images.githubusercontent.com/37179536/144988639-edff0c6f-1f95-4d0c-a203-fe36ed2b7240.png)

**Comment by ClarkXia** [comment]
麻烦提供下复现简单 demo

**Comment by TingtingXuYilongWang** [comment]
[react-send-data-platform.zip](https://github.com/alibaba/ice/files/7666920/react-send-data-platform.zip)

**Comment by ClarkXia** [comment]
@TingtingXuYilongWang store 采用自动检测的方式加载，全局 store 的文件需要在 src  目录下，目前在 src/models/ 下，参考 文档 https://ice.work/docs/guide/basic/store#%E5%AE%9A%E4%B9%89-model
