### ISSUE TITLE
ice1.0.0版本使用build-plugin-keep-alive缓存能力,再点击跳转其他页面后,如何手动销毁组件缓存,不然其他未缓存页面会重复调用已缓存页面接口

### ISSUE THREAD

**Issue by yangvue** [alibaba/ice#5021]
## What is the current behavior? 发生了什么？
ice1.0.0版本使用build-plugin-keep-alive缓存能力,再点击跳转其他页面后,如何手动销毁组件缓存,不然其他未缓存页面会重复调用已缓存页面接口

## What is the expected behavior? 期望的结果是什么？

>

## Any additional comments? 相关环境信息？

- **ice.js Version**：1.0.0
- **build.json Configuration**：
- **Node Version**:V12.18.1
- **Platform**:

**Comment by ClarkXia** [comment]
重复 issue 在 #5020 补充信息即可
