### ISSUE TITLE
如何拿到root组件吖

### ISSUE THREAD

**Issue by SKHon** [alibaba/ice#5026]
## What is the current behavior? 发生了什么？
我想在app.tsx中，拿到react的root组件。

## What is the expected behavior? 期望的结果是什么？
期望能够在app.tsx入口文件中，获取到react 根组件实例
## Any additional comments? 相关环境信息？

- **ice.js Version**：
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by imsobear** [comment]
拿到 root 组件想做什么？原始诉求可以描述下~

**Comment by imsobear** [comment]
长时间未回复，先关闭了，有诉求再 reopen
