### ISSUE TITLE
调试服务与预览报错

### ISSUE THREAD

**Issue by TrumanDu** [alibaba/ice#503]
500 Internal Privoxy Error
Privoxy encountered an error while processing your request:

Could not load template file no-server-data or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).

**Comment by yuanyan** [comment]
这个报错信息是在哪里提示的？

**Comment by TrumanDu** [comment]
GUI 预览页面

**Comment by TrumanDu** [comment]
还有2.0.4 下来依赖失败，强制关闭，需要admin权限才能删除下载的依赖。

**Comment by chenbin92** [comment]
@noyobo  看看这个问题

**Comment by noyobo** [comment]
@TrumanDu 最新版本是否还存在该问题？ 2.1.0 后对预览的方式做了重构

**Comment by TrumanDu** [comment]
@noyobo 我稍后测试几天

**Comment by TrumanDu** [comment]
@noyobo 暂未发现问题
