### ISSUE TITLE
可以支持runtimePublicPath吗？

### ISSUE THREAD

**Issue by komaedaXnagito** [alibaba/ice#5030]
类似umi的runtimePublicPath
![image](https://user-images.githubusercontent.com/26919146/145547443-57117fc4-28d2-4e8e-969c-7ef46e7fd9f3.png)

**Comment by imsobear** [comment]
直接把这行代码写在 src/app.ts 的最上面就可以了，感觉不太需要框架内置？

**Comment by komaedaXnagito** [comment]
试了一下可行，感觉可以加到文档里

**Comment by imsobear** [comment]
> 试了一下可行，感觉可以加到文档里

嗯嗯 我来加下

**Comment by imsobear** [comment]
https://ice.work/docs/guide/advanced/code-splitting#%E5%8A%A8%E6%80%81%E4%BF%AE%E6%94%B9%E5%BC%82%E6%AD%A5%E8%B5%84%E6%BA%90%E5%8A%A0%E8%BD%BD%E5%9C%B0%E5%9D%80 文档已添加
