### ISSUE TITLE
项目启动报错

### ISSUE THREAD

**Issue by 52myu** [alibaba/ice#5032]
npm create ice --template @alifd/fusion-design-pro-js
![image](https://user-images.githubusercontent.com/11611897/145549620-4308719f-0404-4ff5-8e16-c9184b230ea1.png)
![image](https://user-images.githubusercontent.com/11611897/145549672-6f39830c-3b6d-455c-9257-49c2e3c137f3.png)
src/pages/PageSift/components/EditableTable/columns.const.js:13:13: error: Unexpected "<"
    13 │       return <span>{index + 1}</span>;

**Comment by ClarkXia** [comment]
包含 jsx 语法的内容需要以 `.jsx` 作为后缀

**Comment by ClarkXia** [comment]
后缀修改后如果还有类似问题可以重开 issue @52myu
