### ISSUE TITLE
windows 10 下 build 出错

### ISSUE THREAD

**Issue by fireloong** [alibaba/ice#5034]
## What is the current behavior? 发生了什么？
新创建的项目，执行 build 报错：

![uTools_1639276927678](https://user-images.githubusercontent.com/10606957/145701650-8e3ee9dc-f34b-4f79-9118-9437595c2697.png)

## Any additional comments? 相关环境信息？
windows10 vscode AppWorks 创建项目

- **ice.js Version**：2.4.0
- **Node Version**:  v14.15.0

**Comment by ClarkXia** [comment]
通过官方的 demo 暂时无法复现，可以尝试通过 npm init ice 出来的基础模版，给我们提供下复现 demo。例外如果项目下有 lock 文件比如（yarn.lock / package-lock.json）可以尝试删除后重装依赖

**Comment by jaysg** [comment]
同问，window10下npm init ice

**Comment by jaysg** [comment]
同问，window10
1.npm init ice
2.npm i
3.npm run build
以上三步出现上面图示bug

**Comment by fireloong** [comment]
> 通过官方的 demo 暂时无法复现，可以尝试通过 npm init ice 出来的基础模版，给我们提供下复现 demo。例外如果项目下有 lock 文件比如（yarn.lock / package-lock.json）可以尝试删除后重装依赖

没有修改任何代码，也尝试了 npm init ice 出来的基础模版；start 正常，build 不行。

**Comment by ClarkXia** [comment]
@fireloong 提供下具体基础模版的名称

**Comment by ClarkXia** [comment]
2.4.1 版本已修复
