### ISSUE TITLE
build显示TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by xiaobc1234** [alibaba/ice#5039]
和 [4754](https://github.com/alibaba/ice/issues/4754) 一样的问题，项目没有使用cssnano，node_modules中没有cssnano包。

npm run start 一切正常，npm run build就报下面的错。

![image](https://user-images.githubusercontent.com/4045741/145999974-5925f8bc-c886-4fac-ac92-44c18182c601.png)

**Comment by ClarkXia** [comment]
cssnano 是依赖的依赖，可以提供下复现 demo

**Comment by xiaobc1234** [comment]
> 
找到问题了，项目里面插件引入了 fast-sass-loader，这个包有问题在webpack5下面build失败。 关闭这个loader就好。

**Comment by ClarkXia** [comment]
OK fast-sass-loader 配合使用问题，我们尝试复现下
