### ISSUE TITLE
自定义物料中组件开发， 不同组件之间本地相对路径引入报错。

### ISSUE THREAD

**Issue by baimifan2017** [alibaba/ice#5050]
使用自定义物料iceworks开发组件， 因为不同组件之间存在引用关系，如果在一个组件中通过本地相对路径引入另一个组件将会报如下错误：

**1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app**

所试用reactb版本：  
 > "react": "^17.0.2",
 > "react-dom": "^17.0.2",

如果将被引用的组件先发布到npm中，再通过npm install 按照方式引入就不存在错误。

问题：
1、请问iceworks物料开发， 上诉场景是推荐我们每个组件都上传npm 然后在引入吗？
2、如果采用本地相对路径引入另外一个组件 遇见上诉问题应该怎么修改呢？

**Comment by baimifan2017** [comment]
![image](https://user-images.githubusercontent.com/29325266/146325174-6f71abb9-6c97-4441-a366-19d849fbb8b6.png)

**Comment by maoxiaoke** [comment]
这种方式应该走 [monorepo](https://en.wikipedia.org/wiki/Monorepo) 吧，试一试用 [lerna](https://github.com/lerna/lerna) 或 [pnpm workspace](https://pnpm.io/zh/pnpm-workspace_yaml) 这一类工具

**Comment by imsobear** [comment]
用 npm link 的方式更规范点，然后需要配置下 externals https://appworks.site/materials/guide/component.html#%E7%BB%84%E4%BB%B6%E5%B7%A5%E7%A8%8B%E9%85%8D%E7%BD%AE

```
{
  "externals": {
    "react": "./node_modules/react"
  }
}
```

**Comment by Dodd2013** [comment]
> 用 npm link 的方式更规范点，然后需要配置下 externals https://appworks.site/materials/guide/component.html#%E7%BB%84%E4%BB%B6%E5%B7%A5%E7%A8%8B%E9%85%8D%E7%BD%AE
> 
> ```
> {
>   "externals": {
>     "react": "./node_modules/react"
>   }
> }
> ```

这里应该不是配置externals而是alias 吧
