### ISSUE TITLE
AppWorks新建 Fusion Design Pro项目启动的时候报错

### ISSUE THREAD

**Issue by sumbyKB** [alibaba/ice#5054]
步骤：
通过vsCode新建Fusion Design Pro，
yarn依赖以后，yarn start报错
报错截图
![image](https://user-images.githubusercontent.com/23375251/146482158-f52330cb-8e6e-40d9-a68f-b43119cc2ff6.png)

**Comment by ClarkXia** [comment]
参考 https://github.com/alibaba-fusion/materials/issues/134 近期模版会再优化一版
