### ISSUE TITLE
配置config.devServer.proxy时项目启动报错

### ISSUE THREAD

**Issue by AliyaLiu** [alibaba/ice#5058]
业务场景需要根据启动命令配置不同的跨域target，在build.plugin.js中添加如下配置

`
config.devServer.proxy({
  '/api': {
    target: targetUrl,  //  根据启动命令不同 target不同
    changeOrigin: true,
    secure: true,
    ws: false,
  },
 });
`
npm run start 报如下错误
![image](https://user-images.githubusercontent.com/39554660/146858739-63ddfe6a-89b8-4e35-8d38-bce36709a2ca.png)
后改成
`
  config.devServer.proxy([{
      context: '/api',
      target: targetUrl,  //  根据启动命令不同 target不同
      changeOrigin: true,
      secure: true,
      ws: false,
   }]);
`
后启动又报错
![image](https://user-images.githubusercontent.com/39554660/146859079-698a52c3-265a-44c3-aad2-8a7a83dea875.png)
使用的node npm ice.js版本如下：
`
node : v14.18.1
npm : 6.14.15
icejs: 2.4.0
`
请问这是怎么回事，有没有解决方案~

**Comment by ClarkXia** [comment]
通过 build.json 中配置，默认会为 proxy 添加 onProxyRes 和 onError，转换到 vite 配置的时候默认会监听

https://github.com/alibaba/ice/blob/69bf5516fda0cca9f3332431ccd3bb1fe40b6671/packages/build-user-config/src/userConfig/proxy.js#L14-L35

https://github.com/alibaba/ice/blob/69bf5516fda0cca9f3332431ccd3bb1fe40b6671/packages/vite-service/src/wp2vite/config.ts#L218-L219

后续会进行容错处理，暂时可以同步增加下这两个方法
