### ISSUE TITLE
新建项目无法启动报错日志

### ISSUE THREAD

**Issue by sunjian19920716** [alibaba/ice#506]
ERROR in ./node_modules/react-trello/dist/styles/Base.js
Module not found: Error: Can't resolve 'styled-components' in 'E:\iceSpace\demo\node_modules\react-trello\dist\styles'
 @ ./node_modules/react-trello/dist/styles/Base.js 31:24-52
 @ ./node_modules/react-trello/dist/components/Tag.js
 @ ./node_modules/react-trello/dist/index.js
 @ ./src/pages/Home/components/BoardList/BoardList.jsx
 @ ./src/pages/Home/components/BoardList/index.js
 @ ./src/pages/Home/Home.jsx
 @ ./src/pages/Home/index.js
 @ ./src/routerConfig.js
 @ ./src/router.jsx
 @ ./src/index.js
 @ multi ./node_modules/react-dev-utils/webpackHotDevClient.js ./src/index.js

ERROR in ./node_modules/react-trello/dist/styles/Elements.js
Module not found: Error: Can't resolve 'styled-components' in 'E:\iceSpace\demo\node_modules\react-trello\dist\styles'
 @ ./node_modules/react-trello/dist/styles/Elements.js 20:24-52
 @ ./node_modules/react-trello/dist/components/Lane.js
 @ ./node_modules/react-trello/dist/index.js
 @ ./src/pages/Home/components/BoardList/BoardList.jsx
 @ ./src/pages/Home/components/BoardList/index.js
 @ ./src/pages/Home/Home.jsx
 @ ./src/pages/Home/index.js
 @ ./src/routerConfig.js
 @ ./src/router.jsx
 @ ./src/index.js
 @ multi ./node_modules/react-dev-utils/webpackHotDevClient.js ./src/index.js

ERROR in ./node_modules/react-trello/dist/styles/Loader.js
Module not found: Error: Can't resolve 'styled-components' in 'E:\iceSpace\demo\node_modules\react-trello\dist\styles'
 @ ./node_modules/react-trello/dist/styles/Loader.js 16:24-52
 @ ./node_modules/react-trello/dist/components/Loader.js
 @ ./node_modules/react-trello/dist/components/Lane.js
 @ ./node_modules/react-trello/dist/index.js
 @ ./src/pages/Home/components/BoardList/BoardList.jsx
 @ ./src/pages/Home/components/BoardList/index.js
 @ ./src/pages/Home/Home.jsx
 @ ./src/pages/Home/index.js
 @ ./src/routerConfig.js
 @ ./src/router.jsx
 @ ./src/index.js
 @ multi ./node_modules/react-dev-utils/webpackHotDevClient.js ./src/index.js
Failed to compile.

**Comment by chenbin92** [comment]
**问题原因**：项目依赖的包 [react-trello](https://github.com/rcdexta/react-trello) 在最近进行了更新，导致依赖的 `styled-components` 安装失败，详见 [MR ](https://github.com/rcdexta/react-trello/commit/1ed59a137235e5a0579cdff4d1cd31c72550eb54)

**解决方案**： 手动安装 `styled-components` 依赖
