### ISSUE TITLE
从icejs 2.2.3升级到icejs2.4.1之后，fusion design 的Dialog组件配合Form、Select组件有问题，升级之前是正常的。

### ISSUE THREAD

**Issue by edc-hui** [alibaba/ice#5065]
## What is the current behavior? 发生了什么？
Dialog组件包裹Form，FormItem包裹Select组件，当Select组件的下拉框显示出来之后，除非选中Select的选项，否则Select组件的下拉框不会消失。（此问题同样出现在DatePicker2组件上面，估计是同一类问题）
这个现象是从icejs 2.2.3升级到icejs2.4.1之后出现的。
经过我这边测试，使用官方脚手架命令 npm init ice icestark-child @icedesign/stark-child-scaffold 创建出来的新项目也会有此问题。

![image](https://user-images.githubusercontent.com/33356467/147047394-95944951-8515-4b2c-a389-cb51528f6446.png)

## What is the expected behavior? 期望的结果是什么？
恢复和icejs v2.2.3的效果
## Any additional comments? 相关环境信息？

- **ice.js Version**：
-2.4.1
- **build.json Configuration**：
{
  "vite": false,
  "plugins": [
    [
      "build-plugin-icestark",
      {
        "type": "child"
      }
    ],
    [
      "build-plugin-moment-locales",
      {
        "locales": [
          "zh-cn"
        ]
      }
    ],
    [
      "build-plugin-ignore-style",
      {
        "libraryName": "@alifd/next"
      }
    ]
  ]
}

- **Node Version**:
v16.13.1
- **Platform**:
Mac os

**Comment by imsobear** [comment]
icejs 版本理论上不影响这个，看看前后 @alifd/next 的版本号是不是有变化。

**Comment by edc-hui** [comment]
@imsobear  @alifd/next 的版本号发生了变化，  额  我刚刚用 npm init ice icestark-child @icedesign/stark-child-scaffold 创建出来的新项目也会出现这个问题，那意思是这是fusion design 的问题？刚刚创建出来新项目  我看@alifd/next版本是1.25.9

**Comment by edc-hui** [comment]
@imsobear 我刚刚测试了下  把fusion design版本退回到1.24.18版本，结果正常了。那不是ice的问题  我去fusion design提个issue，谢谢了

**Comment by edc-hui** [comment]
已解决  此问题是fusion design的问题  不是icejs的问题
