### ISSUE TITLE
[vite:css] @charset must precede all other statements

### ISSUE THREAD

**Issue by wooooooooc** [alibaba/ice#5074]
## 复现
```
npm init ice ice-fusion
create-ice version: 1.7.5
create-ice args ice-fusion undefined
? Please select a template TypeScript + Fusion Design
download tarballURL https://registry.npmmirror.com/@alifd/scaffold-lite/download/@alifd/scaffold-lite-0.4.1.tgz
√ download npm tarball successfully.
clean package.json...

Initialize project successfully.

Starts the development server.

    cd ice-fusion
    npm install
    npm start


We have prepared develop toolkit for you.
See: https://marketplace.visualstudio.com/items?itemName=iceworks-team.iceworks
```
```
npm install
```
```
npm start

> @alifd/scaffold-lite@0.1.0 start
> icejs start

ice.js 2.4.2
  > Network:  http://10.136.8.3:3333/
  > Local:    http://localhost:3333/
[vite:css] @charset must precede all other statements
5  |    -webkit-font-smoothing: antialiased;
6  |  }
7  |
   |   ^
```

### 定位到 global.css 发现@import已经置顶了，怎么消除 [vite:css] @charset must precede all other statements 提示呢
```
@import '@alifd/theme-design-pro/variables.css';
@import '@alifd/theme-design-pro/dist/next.var.css';

body {
  -webkit-font-smoothing: antialiased;
}

```

**Comment by wooooooooc** [comment]
```
node -v
v14.17.6
```
```
npm -v
8.3.0
```

```
npm config list
; "builtin" config from C:\Users\wangc\AppData\Roaming\npm\node_modules\npm\npmrc

prefix = "C:\\Users\\wangc\\AppData\\Roaming\\npm"

; "user" config from C:\Users\wangc\.npmrc

registry = "https://registry.npm.taobao.org/"

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\Users\wangc\Desktop\ice-fusion
; HOME = C:\Users\wangc
; Run `npm config ls -l` to show all defaults.
```

**Comment by ClarkXia** [comment]
本质上还是 esbuild 和 postcss 配合的问题，解法可以参考 issue：https://github.com/vitejs/vite/issues/5833
后续 vite 跟进 esbuild 版本后这个问题应该会解决

**Comment by guoyunhe** [comment]
@ClarkXia 根据 https://github.com/vitejs/vite/issues/5833 的讨论，升级 esbuild 到 0.14 可以解决这个问题。但是现在 ICE 的 esbuild 版本是 0.13。

**Comment by guoyunhe** [comment]
@ClarkXia 还是不行，插件依赖的 esbuild 没有升级到 0.14，需要更新

```
├─┬ build-plugin-fusion@0.1.22
│ └─┬ @builder/app-helpers@2.5.1
│   └── esbuild@0.13.15 
└─┬ ice.js@2.5.1
  ├─┬ build-plugin-ice-ssr@3.1.0
  │ └─┬ vite@2.8.4
  │   └── esbuild@0.14.22 
  ├─┬ build-plugin-react-app@2.2.0
  │ └── esbuild@0.13.15  deduped
  └─┬ build-scripts@1.2.1
    └── esbuild@0.13.15  deduped
```

**Comment by zangguojun** [comment]
我讲每个npm包都升级到最新版本了
```json
{
  "name": "@icedesign/stark-layout-scaffold",
  "version": "0.1.0",
  "description": "微前端方案 icestark 的主应用模板，用于快速初始化主应用",
  "dependencies": {
    "@alifd/next": "^1.25.49",
    "@alifd/theme-design-pro": "^0.8.0",
    "classnames": "^2.3.1",
    "moment": "^2.29.4",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@iceworks/spec": "^1.6.0",
    "@types/react": "^18.0.15",
    "@types/react-dom": "^18.0.6",
    "build-plugin-dev-inspector": "^0.1.2",
    "build-plugin-fusion": "^0.1.22",
    "build-plugin-icestark": "^2.5.3",
    "build-plugin-ignore-style": "^0.1.2",
    "build-plugin-moment-locales": "^0.1.3",
    "eslint": "^8.21.0",
    "ice.js": "^2.6.4",
    "stylelint": "^14.9.1"
  },
  "scripts": {
    "start": "icejs start",
    "build": "icejs build",
    "lint": "npm run eslint && npm run stylelint",
    "eslint": "eslint --cache --ext .js,.jsx,.ts,.tsx ./",
    "eslint:fix": "npm run eslint -- --fix",
    "stylelint": "stylelint \"**/*.{css,scss,less}\"",
    "prettier": "prettier **/* --write"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/ice-lab/react-materials/tree/master/scaffolds/icestark-layout"
  }
}
```
按照fusion自定义主题的配置，我在`global.css`中
```css
@import '@alifd/theme-design-pro/variables.css';
@import '@alifd/theme-design-pro/dist/next.var.css';

body {
  -webkit-font-smoothing: antialiased;
}
```
然后start启动时，就报错
<img width="487" alt="image" src="https://user-images.githubusercontent.com/49148972/183232271-1b5a66ca-55ab-4d14-b113-9415db25537c.png">

**Comment by theLongYi** [comment]
> 已经有解决方案了吗

**Comment by theLongYi** [comment]
> 我每个npm包都升级到最新版本了
> 
> ```json
> {
>   "name": "@icedesign/stark-layout-scaffold",
>   "version": "0.1.0",
>   "description": "微前端方案 icestark 的主应用模板，用于快速初始化主应用",
>   "dependencies": {
>     "@alifd/next": "^1.25.49",
>     "@alifd/theme-design-pro": "^0.8.0",
>     "classnames": "^2.3.1",
>     "moment": "^2.29.4",
>     "prop-types": "^15.8.1",
>     "react": "^18.2.0",
>     "react-dom": "^18.2.0"
>   },
>   "devDependencies": {
>     "@iceworks/spec": "^1.6.0",
>     "@types/react": "^18.0.15",
>     "@types/react-dom": "^18.0.6",
>     "build-plugin-dev-inspector": "^0.1.2",
>     "build-plugin-fusion": "^0.1.22",
>     "build-plugin-icestark": "^2.5.3",
>     "build-plugin-ignore-style": "^0.1.2",
>     "build-plugin-moment-locales": "^0.1.3",
>     "eslint": "^8.21.0",
>     "ice.js": "^2.6.4",
>     "stylelint": "^14.9.1"
>   },
>   "scripts": {
>     "start": "icejs start",
>     "build": "icejs build",
>     "lint": "npm run eslint && npm run stylelint",
>     "eslint": "eslint --cache --ext .js,.jsx,.ts,.tsx ./",
>     "eslint:fix": "npm run eslint -- --fix",
>     "stylelint": "stylelint \"**/*.{css,scss,less}\"",
>     "prettier": "prettier **/* --write"
>   },
>   "repository": {
>     "type": "git",
>     "url": "https://github.com/ice-lab/react-materials/tree/master/scaffolds/icestark-layout"
>   }
> }
> ```
> 
> 按照定制主题的配置，我在`global.css`中集成定制
> 
> ```css
> @import '@alifd/theme-design-pro/variables.css';
> @import '@alifd/theme-design-pro/dist/next.var.css';
> 
> body {
>   -webkit-font-smoothing: antialiased;
> }
> ```
> 
> 然后start启动时，就报错 <img alt="图片" width="487" src="https://user-images.githubusercontent.com/49148972/183232271-1b5a66ca-55ab-4d14-b113-9415db25537c.png">

@zangguojun 已经有解决方案了吗
