### ISSUE TITLE
vite模式 页面不会热更新

### ISSUE THREAD

**Issue by hyuanyuanlisiwei** [alibaba/ice#5076]
## Any additional comments? 相关环境信息？

- **ice.js Version**：
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by ClarkXia** [comment]
提供下具体的 demo 和复现步骤

**Comment by ClarkXia** [comment]
官方 demo 暂时无法复现，提供 demo 后重开 issue
