### ISSUE TITLE
如何复制npm中的文件？

### ISSUE THREAD

**Issue by luqin** [alibaba/ice#5078]
## What is the current behavior? 发生了什么？

如何复制npm中的文件？尝试了webpack的copy插件失败

## What is the expected behavior? 期望的结果是什么？

- `icejs start` 后，node_modules里npm包里的图片文件可在http://localhost:3333/访问到
- `icejs build`构建后npm包里的图片文件复制到build目录

## Any additional comments? 相关环境信息？

- **ice.js Version**：1.18.0

**Comment by ClarkXia** [comment]
具体是什么需求，如果仅仅只是构建后的复制，直接通过 fs.copy 完成即可

**Comment by luqin** [comment]
@ClarkXia 
我的需求是：
- `icejs start` 后，node_modules里npm包里的图片文件可在http://localhost:3333/访问到
- `icejs build`构建后发布到build目录

**Comment by ClarkXia** [comment]
直接报这个图片拷贝到 public 目录就好了？ 需要实时从 node_modules 依赖中拷贝吗
