### ISSUE TITLE
vscode中 index.module.css 总是报格式错

### ISSUE THREAD

**Issue by hyuanyuanlisiwei** [alibaba/ice#5080]
<img width="578" alt="截屏2021-12-28 下午5 59 50" src="https://user-images.githubusercontent.com/11502089/147554583-3da4548d-78c5-415d-aa77-4d96686b2a98.png">

**Comment by ClarkXia** [comment]
css 本身不支持嵌套写法，如果期望不报错可以安装 postcss 的 vscode 插件
