### ISSUE TITLE
webpack模式下, 使用插件react-refresh报错

### ISSUE THREAD

**Issue by vision-yip** [alibaba/ice#5081]
## What is the current behavior? 发生了什么？
> webpack模式下, 使用插件react-refresh报错

![image](https://user-images.githubusercontent.com/18309167/147554385-2e52257f-b558-43e7-bd2c-bfcce159b373.png)

## What is the expected behavior? 期望的结果是什么？
> 使用vite模式的时候正常, 希望也能正常
## Any additional comments? 相关环境信息？
> ice.js 2.4.2

- **ice.js Version**：ice.js 2.4.2
- **build.js Configuration**：
```
const ReactRefreshPlugin = require('@pmmmwh/react-refresh-webpack-plugin');
module.exports = {
  "plugins": [
    [
      "build-plugin-ignore-style",
      {
        "libraryName": "antd"
      }
    ],
    (api) => {
      api.onGetWebpackConfig((config) => {
        config.plugin('ReactRefreshPlugin').use(ReactRefreshPlugin);
        ['jsx', 'tsx'].forEach((rule) => {
          config.module.rule(rule).use('babel-loader').tap((options) => {
            options.plugins.push(require.resolve('react-refresh/babel'));
          });
        });
      });
    }
  ]
}
```
- **package.json**:

```
// npm init ice <xxx> 的基础上添加以下两行
"@pmmmwh/react-refresh-webpack-plugin": "^0.5.4",
"react-refresh": "^0.11.0"
```

**Comment by vision-yip** [comment]
目的: 使用react-refresh达到热更新的效果
参考文档: https://segmentfault.com/a/1190000023534941

**Comment by ClarkXia** [comment]
2.x 版本默认内置

**Comment by imsobear** [comment]
对的，默认就有这个能力，不需要额外做任何事。
