### ISSUE TITLE
初次启动 vite 项目，先是跳转到 about:blank 空页面，然后跳转到实际页面

### ISSUE THREAD

**Issue by luhc228** [alibaba/ice#5084]
## What is the current behavior? 发生了什么？

RT

## What is the expected behavior? 期望的结果是什么？
直接跳转到 dev 调试页面（比如：localhost:3333），不打开 about:blank 空白页面
## Any additional comments? 相关环境信息？

- **ice.js Version**：2
- **build.json Configuration**：
- **Node Version**: 14
- **Platform**: macOS

**Comment by ClarkXia** [comment]
复现步骤是什么
