### ISSUE TITLE
Iceworks不支持下载git+https或git+http方式

### ISSUE THREAD

**Issue by james-cain** [alibaba/ice#509]
目前有一类需求，公司需要创建一些业务组件物料，这些物料是放在公司搭建的gitlab上，我们是通过git+https或git+http的方式下载私服的包。
iceworks目前只支持下载npm的tar包方式，不支持http的形式。
希望iceworks可以解决这方面的需求

**Comment by yuanyan** [comment]
这块是计划里的，最快这个月底版本可以支持

**Comment by james-cain** [comment]
感谢啦




| |
15960192140
邮箱：m15960192140@163.com
|

签名由 网易邮箱大师 定制

在2018年05月16日 23:09，元彦 写道：

这块是计划里的，最快这个月底版本可以支持
