### ISSUE TITLE
icejs构建缓存问题

### ISSUE THREAD

**Issue by wangchongwei** [alibaba/ice#5091]
icejs版本：1.17.3
build.json文件内容
`{
  "plugins": [
    [
      "build-plugin-fusion",
      {
        "themePackage": "@alifd/theme-design-pro"
      }
    ],
    [
      "build-plugin-moment-locales",
      {
        "locales": [
          "zh-cn"
        ]
      }
    ]
  ],
  "hash": true
}`
hash也生效了，引用的js、css文件名都带有hash值，
但是构建后仍然存在缓存问题，当清除浏览器缓存后才显示出期望的效果

请问有何解决办法？

**Comment by ClarkXia** [comment]
确认下 html 输出的 js 和 css 地址是不是最新的地址

**Comment by wangchongwei** [comment]
> 确认下 html 输出的 js 和 css 地址是不是最新的地址

相对路径的话，不存在最不最新吧。

**Comment by ClarkXia** [comment]
js 和 css 带 hash，但是 html 访问的时候如果返回的内容还是上一次的内容的话 会出现你的问题，html 内容也可能被缓存
