### ISSUE TITLE
icejs: command not found

### ISSUE THREAD

**Issue by FrominXu** [alibaba/ice#5093]
subprocess:/usr/local/lib/node_modules/tnpm/node_modules/_npm@6.11.3@npm/bin/npm-cli.js exit code: 1, signal: null
[tnpm] mainprocess exit code: 1

当有两个ice项目，都执行了npm i 和 npm start，然后都结束进程，然后将一个项目的node_modules删除重新npm i 和 npm start，另一个项目再 npm start 就会报上面的错，提示 icejs: command not found，也要删除 node_modules 再 npm i 后才能 npm start

**Comment by ClarkXia** [comment]
两个项目结构，以及执行的命令步骤均提供下，我们看下是否能够复现
