### ISSUE TITLE
vite 模式下如何指定 localhost:3333 响应的 content-type

### ISSUE THREAD

**Issue by dashdotdawn** [alibaba/ice#5108]
![image](https://user-images.githubusercontent.com/15552215/148332302-c94262d7-ff68-4077-b27b-7b82c2a1e4c7.png)

vite 模式下预览链接得到的响应未指定 content-type，请问如何自定义？

需要指定是因为本地通过 nginx 转发了这个请求，不希望命中 nginx 的 default_type。测试了 webpack 模式，和单独使用 vite，预览端口其实都有返回 content-type

**Comment by dashdotdawn** [comment]
或者可以在这里 https://github.com/alibaba/ice/blob/master/packages/vite-service/src/plugins/html.ts#L87 加上 setHeader ？
```
res.setHeader{ 'Content-Type': 'text/html' }.end(await server.transformIndexHtml(req.url, html));
```

**Comment by ClarkXia** [comment]
可以给我们提个 PR 修正下这个 Content-Type
