### ISSUE TITLE
升级react-router v6

### ISSUE THREAD

**Issue by usercao** [alibaba/ice#5116]
react-router v6已经出来有段时间了，请问是否短期内有计划升级？

**Comment by ClarkXia** [comment]
会考虑这个方案 https://github.com/alibaba/ice/issues/4917

**Comment by usercao** [comment]
> 会考虑这个方案 #4917

请问有计划上线日期吗？

**Comment by ClarkXia** [comment]
我们先评估下 v6 的变化，后续可以直接关注 #4917 这两天会将上线计划更新上去
