### ISSUE TITLE
静态资源使用路径别名未生效

### ISSUE THREAD

**Issue by usercao** [alibaba/ice#5124]
![image](https://user-images.githubusercontent.com/13760476/148918724-42ca77cb-b05f-4d6f-b1f6-6c06d014efdc.png)
![image](https://user-images.githubusercontent.com/13760476/148918828-e3707175-4b49-41a7-b585-7204094e652f.png)
项目默认配置的`"@/*"`在加载图片等静态资源时没过滤

**Comment by imsobear** [comment]
上下两个截图是两种用法，具体想问哪个用法的问题？

**Comment by imsobear** [comment]
上面这种没法用 alias，写相对路径；下面这个是 ts 提示的问题，在 src/typings.d.ts 里加下 declare。

**Comment by usercao** [comment]
> 上面这种没法用 alias，写相对路径；下面这个是 ts 提示的问题，在 src/typings.d.ts 里加下 declare。

如何才能使用alias导入呢？

**Comment by imsobear** [comment]
![image](https://user-images.githubusercontent.com/2505411/148946887-671bfe83-abc5-4719-a386-30d9bff12d11.png)
 
文档写了
