### ISSUE TITLE
routes跟menuConfig 配置不到重定向问题

### ISSUE THREAD

**Issue by DavidWuJay** [alibaba/ice#5125]
routes配置
![image](https://user-images.githubusercontent.com/24268244/148944671-c6c2944a-bb44-41ad-9d09-61c3be4828f9.png)

menuConfig配置
![image](https://user-images.githubusercontent.com/24268244/148944821-9a0acd11-52c4-44ae-bad5-15cb81abe56e.png)
![image](https://user-images.githubusercontent.com/24268244/148944945-ef3a7b27-1903-412f-9d2d-f861613d8643.png)
配置了重定向后展开子菜单无法默认选中第一个
想要达成
![image](https://user-images.githubusercontent.com/24268244/148945126-495878d9-02e0-4768-91e6-4dabb7357f72.png)
根据重定向配置展开后默认配置成重定向配置的路由

**Comment by imsobear** [comment]
![image](https://user-images.githubusercontent.com/2505411/149059901-924a36b4-1151-4662-9ddc-2c6e036cd4c5.png)

**Comment by DavidWuJay** [comment]
这样做依然不生效，我的解决方案是

**Comment by DavidWuJay** [comment]
这样做的方案依然不生效的，我的解决方案是配置menuConfig
把父类的path直接指向子类的path路径

**Comment by DavidWuJay** [comment]
![image](https://user-images.githubusercontent.com/24268244/149070778-7e28bd09-42b3-4af4-ac9f-2f0d0f515ed9.png)
