### ISSUE TITLE
 icejs vite 模式没有支持 ejs 变量

### ISSUE THREAD

**Issue by 77629296** [alibaba/ice#5130]
## What is the current behavior? 发生了什么？

![image](https://user-images.githubusercontent.com/22374488/149097566-41606318-5326-4744-a3b0-9fba12d244b5.png)
ejs环境变量 vite模式下没有支持

## What is the expected behavior? 期望的结果是什么？
希望支持

## Any additional comments? 相关环境信息？

- **ice.js Version**：2.4.3
- **build.json Configuration**：
- **Node Version**: 16.13.0
- **Platform**: MacOS

**Comment by ClarkXia** [comment]
最新版本已支持
