### ISSUE TITLE
Appworks 怎样配置私有物料地址？？

### ISSUE THREAD

**Issue by baimifan2017** [alibaba/ice#5138]
背景描述：
       公司现在是内网开发和外网之间是物料隔离， 系统利用iceworks + Appworks 搭建一个私有物料市场。

现在我的操作步骤是：

第一步： 利用verdaccio 搭建本地npm 仓库
第二部： 搭建本地unpkg 服务
第三步： 配置unpkg中的私用库地址 privateNpmRegistryURL
第四步： 新建组件 npm publish 到私有npm库中

目前实现了 unpkg 中关联到私有npm 库
![image](https://user-images.githubusercontent.com/29325266/149292080-d086598f-0684-4ed6-b0f7-fd46eff6a8d9.png)

但是我发现预览截图无反应
![image](https://user-images.githubusercontent.com/29325266/149292228-fdf2f486-89e4-49cd-a3bc-8d507cfc1a30.png)

含有就是我应该怎样配置Appworks中的物料地址呢？
我这样配置了下， 发现要报403的错误

![image](https://user-images.githubusercontent.com/29325266/149292615-e29db88d-b5e4-4daa-b6c1-a0a537ff35fe.png)

有没有朋友搭建过？？
或者指出下我过程中有哪些错误？
私有物料怎样配置物料地址？

**Comment by imsobear** [comment]
先说 403 的问题，你这个地址在浏览器里直接访问返回的是什么内容？
