### ISSUE TITLE
无法获取store

### ISSUE THREAD

**Issue by OShuxin** [alibaba/ice#5148]
无法获取store
正常添加页面级路由
![截屏2022-01-17 下午3 01 49](https://user-images.githubusercontent.com/88992305/149722618-2c8fff2f-cb93-489a-afb4-ca9e9ce38322.png)
e

**Comment by luhc228** [comment]
提供下最小复现 demo 和 icejs 版本

**Comment by OShuxin** [comment]
这个主要还是项目中碰到的唯独一个其他的项目都是好的没有 icejs为1.0.0

**Comment by luhc228** [comment]
> 这个主要还是项目中碰到的唯独一个其他的项目都是好的没有 icejs为1.0.0

提供下最小复现 demo，可以发 GitHub 项目地址或者上传压缩包
