### ISSUE TITLE
安装使用FusionDesignPro 报错

### ISSUE THREAD

**Issue by sgfily** [alibaba/ice#5155]
> node_modules/venn.js/src/layout.js:2:20: error: Could not resolve "../node_modules/fmin/index.js"
    2 │         scale} from '../node_modules/fmin/index.js';
      ╵                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 > node_modules/venn.js/src/diagram.js:6:25: error: Could not resolve "../node_modules/fmin/index.js"
    6 │ import {nelderMead} from "../node_modules/fmin/index.js";
      ╵                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

CONFIG Failed to load vite config.
ERR! Build failed with 2 errors:
node_modules/venn.js/src/diagram.js:6:25: error: Could not resolve "../node_modules/fmin/index.js"
node_modules/venn.js/src/layout.js:2:20: error: Could not resolve "../node_modules/fmin/index.js"
      detail: undefined,
      location: [Object],
      notes: [],
      pluginName: '',
      text: 'Could not resolve "../node_modules/fmin/index.js"'
    }
  ],
  warnings: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@0.1.0 start: `icejs start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sgf\AppData\Roaming\npm-cache\_logs\2022-01-18T06_23_38_433Z-debug.log

**Comment by ClarkXia** [comment]
参考 https://github.com/alibaba-fusion/materials/issues/134
