### ISSUE TITLE
npm start启动调试 webpack日志乱码

### ISSUE THREAD

**Issue by LoLDragon** [alibaba/ice#5156]
## What is the current behavior? 发生了什么？
![image](https://user-images.githubusercontent.com/19163371/149928824-686909c2-9ecf-4e3c-a743-c16c0a29569f.png)

执行npm start, 终端输出的日志一直乱码，而且不会停止

## Any additional comments? 相关环境信息？

- **ice.js Version**：1.9.6
- **build.json Configuration**：常规配置
- **Node Version**: 12.22.7
- **Platform**: windows 10专业版

**Comment by ClarkXia** [comment]
看下 colors 版本

**Comment by LoLDragon** [comment]
![image](https://user-images.githubusercontent.com/19163371/150053446-92b00ddd-caf3-4ea1-9bb0-4017af8d3641.png)

@ClarkXia  确定了colors的版本就是1.4.0的

**Comment by LoLDragon** [comment]
@ClarkXia 感谢大神，使用1.4.0版本之后可以了
