### ISSUE TITLE
[Vue warn]: Error in nextTick: "RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by mowatermelon** [alibaba/ice#516]
系统  win7
node V8.10.0

操作步骤
- 选择vue版本，生成vue项目
- 在页面列表选择，点击add按钮，新增页面。
- 新页面生成成功，点击`http://localhost:4444/`，进行预览
- 选择刚刚生成的页面入口，页面控制台报错`vue.runtime.esm.js:588 [Vue warn]: Error in nextTick: "RangeError: Maximum call stack size exceeded" RangeError: Maximum call stack size exceeded`
- 整个页面完全崩溃，点击其他路由也没有反应

![image](https://user-images.githubusercontent.com/18508817/40155886-9e9941e8-59c8-11e8-8d1c-a2536671c5c9.png)

> 尝试一

- 关掉页面，重新打开，只点击默认的路由入口，页面一切正常====>只有点击新增的页面路由才有问题

![image](https://user-images.githubusercontent.com/18508817/40155938-02dbe250-59c9-11e8-9154-e2c6de5604d9.png)

> 尝试二

- 在新增页面弹窗中， 选择预览效果，页面预览正常====>新页面本身应该是没有问题

![image](https://user-images.githubusercontent.com/18508817/40156003-6f7ec6b6-59c9-11e8-9c09-02769c6ab7ab.png)

> 尝试三

- 在新增页面弹窗中， 选择login模版，点击`http://localhost:4444/`，进行预览，点击新增的`nav4`，预览正常====>vue模版本身新增页面这块逻辑没有问题

![image](https://user-images.githubusercontent.com/18508817/40156065-cb691a94-59c9-11e8-97a5-0debfb1ed592.png)

> 尝试四

- 在新增页面弹窗中， 选择login模版，修改相关页面信息

![image](https://user-images.githubusercontent.com/18508817/40156122-19107c24-59ca-11e8-9c7d-09b6cd551b95.png)

- 点击`http://localhost:4444/`，点击新增的navLogin，预览正常。====>vue模版本身新增页面，修改名称这块逻辑没有问题

![image](https://user-images.githubusercontent.com/18508817/40156134-2e429852-59ca-11e8-8223-60b513b48e75.png)

> 尝试五

- 在新增页面弹窗中， 选择login模版，修改相关页面信息，将页面名称和组件名称写成一致

![image](https://user-images.githubusercontent.com/18508817/40156217-a45b556a-59ca-11e8-9795-051a5fedce9c.png)

- 点击`http://localhost:4444/`，点击新增的nav1Login，预览失败，页面控制台报错`vue.runtime.esm.js:588 [Vue warn]: Error in nextTick: "RangeError: Maximum call stack size exceeded" RangeError: Maximum call stack size exceeded`
- 整个页面完全崩溃，点击其他路由也没有反应。====>问题在于新增的页面名称不能和组件名称一样，如果一致，这边就会报错

![image](https://user-images.githubusercontent.com/18508817/40156239-cc923238-59ca-11e8-99c0-7a3aecf364f4.png)

### 总结

综上问题在于新增的页面名称不能和组件名称一样，如果一致，这边就会报错，所以在新页面生成的时候需要检查新页面的名称和组件名称是否一致，如果一致，则需要进行提醒，要不然这个新页面预览的时候就会出错。

**Comment by chenbin92** [comment]
https://github.com/alibaba/ice/issues/487

**Comment by yunhongyao** [comment]
useful issue,thank!
