### ISSUE TITLE
初始化数据无法重新获取嘛

### ISSUE THREAD

**Issue by XuJin186** [alibaba/ice#5163]
如umi  
` 
import { useModel } from 'umi';

export default () => {
  const { initialState, loading, error, refresh, setInitialState } = useModel('@@initialState');
  return <>{initialState}</>
}; 
`

**Comment by imsobear** [comment]
如果说的是通过 `app.getInitialData` 返回的数据，那么用这个 API 就可以：https://ice.work/docs/guide/basic/app#appgetinitialdata

**Comment by XuJin186** [comment]
你好  如你所说  这样是可以实现第一次打开的时候获取   比如第一次获取之后数据为未授权需要登录  登录完成之后这个数据肯定需要更新的  比如当前用户信息 后端的一个主题信息（根据用户设置）

**Comment by imsobear** [comment]
- 如果是权限数据，提供了 [useAuth](https://ice.work/docs/guide/advanced/auth#%E8%AE%BE%E7%BD%AE%E6%9D%83%E9%99%90%E6%95%B0%E6%8D%AE) 的 API
- 如果是其他数据，需要自己新建一个 model，然后结合 initialStates 实现 https://ice.work/docs/guide/basic/store#%E8%AE%BE%E7%BD%AE%E5%88%9D%E5%A7%8B%E7%8A%B6%E6%80%81

**Comment by imsobear** [comment]
针对上述第二点，umi 里有一个隐式的 model 叫 `@@initialState`，ice 里没有，如有必要可以创建一个 `models/initialStates.ts` 的文件。

**Comment by imsobear** [comment]
针对上述第二点，umi 里有一个隐式的 model 叫 `@@initialState`，ice 里没有，如有必要可以创建一个 `models/initialStates.ts` 的文件。

**Comment by XuJin186** [comment]
新建之后就可以覆盖了initialStates状态嘛 我尝试一下

**Comment by imsobear** [comment]
不是覆盖关系，是包含关系，就是一个特殊命名的 model 而已：

```
models/
  - user.ts
  - initialState.ts
```

```
runApp({
  app: {
     getInitialData: () => {
        return {
          initialStates: {
             user: {},
             initialState: {}
          }
       }
     }
  }
})
```

但我觉得 `models/initialState.ts` 并不是一个好的实践，最好还是通过有意义的多个 model 来实现，比如 user/auth/menu/...

**Comment by XuJin186** [comment]
是的  我也觉得这不是最佳实践   因为我们是个聚合接口   主题 多语言 设置啥的都在一个接口返回   所以多个model有可能会发出多个请求   这很不合理  我再想想办法吧

**Comment by imsobear** [comment]
那我觉得按照 https://github.com/alibaba/ice/issues/5163#issuecomment-1019663116 就可以，只是 model 命名上最好不要用 `models/initialState.ts`，这种语义是有问题的，最好是自己抽象一下：

```
models/
  - user.ts
  - auth.ts
  - ... // 实在不行就来个 common.ts
```

runApp：

```
runApp({
  app: {
     getInitialData: () => {
        return {
          initialStates: {
             user: {name: 'jack'},
          }
       }
     }
  }
})

定义一个简单的 model：

```
// models/user
const user = {
  state: {name: ''}
};
export default user;
```

然后通过 useModel 就可以用了：

```js
import store from '@/store';

const HomePage = () => {
  const [userState, userDispatchers] = store.useModel('user');
  return (
    <>
      {userState.name}
      <div onClick={() => {  userDispatchers.setState({ name: '哈哈' }) }}>update</div>
   </> 
  );
};
```

**Comment by XuJin186** [comment]
感谢你的回复  这个能解决嘛？是的 能解决  就是多调用几次dispatchers

**Comment by imsobear** [comment]
> 感谢你的回复 这个能解决嘛？是的 能解决 就是多调用几次dispatchers

那你就弄一个 `models/common.ts`，把这些信息都放在 common 里。（虽然我觉得这样不是很合理）

**Comment by XuJin186** [comment]
极其的不合理   还请你们认真考虑

**Comment by XuJin186** [comment]
极其的不合理   还请你们认真考虑

**Comment by imsobear** [comment]
> 极其的不合理 还请你们认真考虑

不合理是因为你的要求呀 「多调用几次dispatchers」，并不是方案本身不合理。或者你有什么建议的方案吗？

**Comment by strongyc** [comment]
getInitialData是否支持运行时调用，一般来说，都需要登录成功后再去拉取用户权限数据
