### ISSUE TITLE
ice从1.x升级到2.x后,build-plugin-fusion配置了themeConfig.icon-font-path和 font-custom-path报错

### ISSUE THREAD

**Issue by smat0096** [alibaba/ice#5167]
## What is the current behavior? 发生了什么？
ice.js 1.x能正常启动, 升级到2.5.1后, 发现build-plugin-fusion配置了themeConfig的 icon-font-path和 font-custom-path就报错,
`
build.config.js
[
      'build-plugin-fusion',
      {
        themePackage: '@alifd/theme-18842',
        themeConfig: {
          'css-prefix': 'next-icestark-',
          'icon-font-path': "'/icon-font/icon'",
          'font-custom-path': "'/font/'",
        }
      },
    ],
`
报错如下:
![企业微信截图_16430996183121](https://user-images.githubusercontent.com/20716152/150940795-511e9621-3bb4-43c6-a31c-ade5ad63957a.png)

## Any additional comments? 相关环境信息？

- **ice.js Version**：2.5.1
- **build.json Configuration**：`
const proxyApi = 'http://192.168.1.147';
module.exports = {
  define: {
    env: process.env.NODE_ENV,
  },
  plugins: [
    [
      'build-plugin-icestark',
      {
        type: 'child',
        umd: true,
        uniqueName: 'frameworkJsonp',
      },
    ],
    [
      'build-plugin-fusion',
      {
        themePackage: '@alifd/theme-18842',
        themeConfig: {
          'css-prefix': 'next-icestark-',
          'icon-font-path': "'/icon-font/icon'",
          'font-custom-path': "'/font/'",
        },
      },
    ],
    [
      'build-plugin-moment-locales',
      {
        locales: ['zh-cn'],
      },
    ],
  ],
  mock: {
    exclude: ['/api/**'],
  },
  proxy: {
    '/api': {
      enable: true,
      target: proxyApi,
      changeOrigin: true,
    },
  },
  hash: 'contenthash',
};

- `
- **Node Version**:
- **Platform**:

**Comment by ClarkXia** [comment]
提供下复现的 demo

**Comment by smat0096** [comment]
[ice-demo.zip](https://github.com/alibaba/ice/files/8095072/ice-demo.zip)

![企业微信截图_16451703937679](https://user-images.githubusercontent.com/20716152/154640001-875d1951-fb26-4884-8a64-353b56667678.png)

@ClarkXia 推测是因为ice2.x默认使用webpack5,webpack5的svg   ##loader更改导致;  #5115

**Comment by smat0096** [comment]
@ClarkXia 
   已解决, 路径格式改为scss的别名绝对路径; '~@/...'
   **另外,经调试发现, 加入自定义plugin, 在webpack-chain中加入 noParse, rules中加入exclue, IgnorePlugin 排除模块都不起作用, 依然会报错找不到图标模块** 
![企业微信截图_16454303646457](https://user-images.githubusercontent.com/20716152/154912432-64b4503e-6fe5-4fce-bf61-ae356308de33.png)
