### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'Graph')     at vendor.js:73

### ISSUE THREAD

**Issue by wenliu255** [alibaba/ice#5170]
新建一个ice的项目，js+fusiondesign，build使用iis托管发布，就显示这个错误，如果只是npm start不存在任何问题。

**Comment by ClarkXia** [comment]
提供下复现的 demo，默认模版构建结果 目前没有对应问题，参考 unpkg 的构建内容 https://unpkg.com/@alifd/fusion-design-pro@0.5.0/build/index.html

**Comment by likepearl** [comment]
遇到相同报错，不清楚什么原因引起的

**Comment by loadchange** [comment]
同样遇到这个问题，我的情况是使用了 `@antv/data-set` 可以先用这个方法临时处理下

> 这不是ice的问题

```javascript
import DataSet from '@antv/data-set/build/data-set';
````
