### ISSUE TITLE
默认 minify 选项 terser 速度过慢

### ISSUE THREAD

**Issue by guoyunhe** [alibaba/ice#5173]
## What is the current behavior? 发生了什么？

在迁移一个 JUST 项目的过程中发现，从 JUST 迁移到 ICE Vite，无缓存 build 的速度反而变慢了。经过尝试不同的选项发现，minify 选项对构建时间的影响非常大（无缓存）：

- minify: terser --> 29s
- minify: esbuild --> 20s

## What is the expected behavior? 期望的结果是什么？

minify 选项默认值改为更快的 esbuild

## Any additional comments? 相关环境信息？

- **ice.js Version**：
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by ClarkXia** [comment]
默认压缩由 terser 转变为 esbuild  对于开发者属于 breakchange 了，会在后续的大版本中考虑
