### ISSUE TITLE
icejs现在不支持小程序开发了么？

### ISSUE THREAD

**Issue by HarryLue** [alibaba/ice#5176]
icejs现在不支持小程序开发了么？
创建项目的时候没有小程序模板的选择提示，直接就是UI模板提示。
yarn build编译之后，build目录下只有web项目，没有小程序项目，最新官方文档翻烂了也没有提小程序的事情。
icejs还支持小程序开发么？

**Comment by ClarkXia** [comment]
不支持小程序，现阶段有小程序诉求的可以参考下 https://rax.js.org/docs/guide/about-miniapp
