### ISSUE TITLE
vite模式配置router:false 启动报错CONFIG Failed to load vite config.

### ISSUE THREAD

**Issue by lipten** [alibaba/ice#5180]
## What is the current behavior? 发生了什么？
vite模式设置router:false 启动报错

![image](https://user-images.githubusercontent.com/8328548/153551876-5df1bc0c-2b2c-4179-b8f0-ad452ef296a7.png)

### 作过哪些尝试：
* 把vite设为false使用webpack可以正常启动
* ice.js@2.5.1和2.0.0都有这个问题

## What is the expected behavior? 期望的结果是什么？
期望可以正常启动，正常访问
## Any additional comments? 相关环境信息？

- **ice.js Version**：2.5.1
- **build.json Configuration**：
```json
{
  "vite": true,
  "router": false,
  "plugins": [
    [
      "build-plugin-ignore-style",
      {
        "libraryName": "antd"
      }
    ]
  ]
}

```
- **Node Version**:v16.13.0
- **Platform**: mac os 12.3

## 复现步骤：
使用官方快速开始：
```
yarn create ice <projectName>

# 选择Typescript + Ant Design模板
```
build.json配置：
```
{
  "vite": true,
  "router": false,
  "plugins": [
    [
      "build-plugin-ignore-style",
      {
        "libraryName": "antd"
      }
    ]
  ]
}

```
src/app.jsx配置：
```
import { runApp, IAppConfig } from 'ice';

const appConfig: IAppConfig = {
  app: {
    // rootId: 'ice-container',
    renderComponent() {
      return <div>整个应用就一个简单组件</div>
    },
  },
};

runApp(appConfig);

```

**Comment by maoxiaoke** [comment]
@lipten 关注下 https://github.com/alibaba/ice/pull/5181 这个修复分支
