### ISSUE TITLE
打包时发生错误optimize runtime failed when analyze

### ISSUE THREAD

**Issue by vision-yip** [alibaba/ice#5184]
## What is the current behavior? 发生了什么？

npm start 没问题, 打包时发生错误

 {"auth":"/src/pages/Auth/app.ts","example":"/src/pages/Example/app.ts","report":"/src/pages/Report/app.ts","user":"/src/pages/User/app.ts"}
[ERROR] optimize runtime failed when analyze /public/images/auth-bg.png
[ERROR] optimize runtime failed when analyze /public/images/logo-nav.png
[ERROR] optimize runtime failed when analyze /public/images/tip-success.png
[ERROR] optimize runtime failed when analyze /public/images/tip-success.png
[ERROR] optimize runtime failed when analyze /public/images/logo-nav.png
[ERROR] optimize runtime failed when analyze /public/images/banner1.jpeg
[ERROR] optimize runtime failed when analyze /src/pages/Example/index.tsx
...

## What is the expected behavior? 期望的结果是什么？

打包正常

## Any additional comments? 相关环境信息？

- **ice.js Version**：2.5.1
- **build.json Configuration**：
```
mpa: {
  openPage: 'auth',
},
```
- **Node Version**: v16.14.0
- **Platform**: TencentOS Server 3.2

**Comment by ClarkXia** [comment]
提供下完整的错误信息及 build.json，最好有复现的 demo

**Comment by vision-yip** [comment]
``` javascript
const webpackConfig = ({ onGetWebpackConfig }) => {
  onGetWebpackConfig((config) => {
    config.resolve.alias.set('buffer', 'buffer');
    config.resolve.alias.set('crypto', 'crypto-browserify');
    config.resolve.alias.set('stream', 'stream-browserify');
  });
};

module.exports = {
  mpa: { openPage: 'auth' },
  devPublicPath: './',
  publicPath: './',
  hash: undefined,
  plugins: [
    [
      'build-plugin-moment-locales',
      {
        locales: ['zh-cn'],
      },
    ],
    webpackConfig,
  ],
  sassLoaderOptions: {
    prependData: '@import "./src/assets/sass/theme.scss"; '
  },
  proxy: {}
}
```

**Comment by ClarkXia** [comment]
升级 2.6.1 版本，确保 @builder/app-helpers 版本升级为 2.5.3
