### ISSUE TITLE
different component (`Provider2`)

### ISSUE THREAD

**Issue by preedomly** [alibaba/ice#5188]
Link 重新进入当前页面时，页面会提出如下报错，产生数据源获取失败.
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/22881032/154904841-8f487b38-bbe4-443d-a53a-d9286d8c1dc9.png">

**Comment by preedomly** [comment]
<img width="346" alt="image" src="https://user-images.githubusercontent.com/22881032/154910332-4d007f9b-3855-4a7f-b4b1-411c58685b92.png">
<img width="902" alt="image" src="https://user-images.githubusercontent.com/22881032/154910683-302aeae0-a1f9-46fe-822d-7872211fc83f.png">
<img width="641" alt="image" src="https://user-images.githubusercontent.com/22881032/154910801-54d42035-8300-49be-9941-237d98261a9c.png">

**Comment by imsobear** [comment]
@preedomly 问题是否已解决，没解决的话麻烦提供下重现 demo。
