### ISSUE TITLE
ICE 2.x Webpack 模式 如何修改  watchOptions

### ISSUE THREAD

**Issue by weilaiqishi** [alibaba/ice#5192]
## What is the current behavior? 发生了什么？
ICE 2.x Webpack 模式 如何修改  watchOptions
## What is the expected behavior? 期望的结果是什么？
build.json 是否有相关配置
## Any additional comments? 相关环境信息？

- **ice.js Version**：2.x

**Comment by ClarkXia** [comment]
https://ice.work/docs/guide/basic/build#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%B7%A5%E7%A8%8B%E9%85%8D%E7%BD%AE  通过自定义的方式修改，另外什么场景需要修改 watchOptions

**Comment by weilaiqishi** [comment]
> https://ice.work/docs/guide/basic/build#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%B7%A5%E7%A8%8B%E9%85%8D%E7%BD%AE  通过自定义的方式修改，另外什么场景需要修改 watchOptions

node_modules有公共组件，本地联调时修改需要触发打包
