### ISSUE TITLE
icestark在切换子应用的时候，不会执行生命周期的组件销毁函数，需要调用@ice/stark-app的registerAppLeave方法销毁，带来额外改造的工作量

### ISSUE THREAD

**Issue by rootsli** [alibaba/ice#5196]
icestark在切换子应用的时候，不会执行生命周期的组件销毁函数，需要调用@ice/stark-app的registerAppLeave方法销毁，带来额外改造的工作量：

Vue:对应destroy(){
   // 切换子应用，当前组件不会执行
}方法
React：
1.componentWillUnmount(){
   // 切换子应用，当前组件不会执行
}
2.useEffect(()=>{
   return () =>{
      // 切换子应用，当前组件不会执行
   };
},[])

期望：在执行子应用切换时，先执行当前组件生命周期的卸载方法。

**Comment by rootsli** [comment]
> 正常来说，销毁工作应该在 unmount 生命周期处理，er unmount 函数会在触发应用卸载后执行

好像并没有执行

**Comment by maoxiaoke** [comment]
@rootsli 可以用官方的 case 验证下，应该是会执行的
