### ISSUE TITLE
建议多行 Input 支持自动尺寸

### ISSUE THREAD

**Issue by coderfox** [alibaba/ice#520]
建议多行 Input 支持根据文本长度自动调整大小。

**Comment by wssgcg1213** [comment]
建议收到, 我们内部讨论一下

**Comment by bindoon** [comment]
1.x 里面的支持的。 https://fusion.design/component/basic/input 里面查找自动高度！

```
<Input.TextArea autoHeight />
```

0.x 不会再新增这个功能！
