### ISSUE TITLE
vite模式下favicon丢失

### ISSUE THREAD

**Issue by is-cool** [alibaba/ice#5201]
## What is the current behavior? 发生了什么？
vite模式下favicon丢失问题

vite模式：
![截屏2022-02-28 14 48 16](https://user-images.githubusercontent.com/78067806/155937356-1dc5301e-d9cb-46ab-9934-c64086b1db98.png)

webpack模式下:
![截屏2022-02-28 14 47 37](https://user-images.githubusercontent.com/78067806/155937416-4358638b-2925-414d-8787-8280318f4619.png)

## What is the expected behavior? 期望的结果是什么？
vite模式favicon展示正常

## Any additional comments? 相关环境信息？

- **ice.js Version**：
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by ClarkXia** [comment]
看下 html 的输出上的区别，默认 webpack 模式下会注入 favicon 的标签

**Comment by is-cool** [comment]
谢谢，手动注入有效🥳
