### ISSUE TITLE
× Unhandled Rejection (Error): [Immer] 

### ISSUE THREAD

**Issue by Gamehu** [alibaba/ice#5202]
## What is the current behavior? 发生了什么？

tab页关闭和打开偶发，错误 Unhandled Rejection (Error): [Immer] 

<img width="904" alt="image" src="https://user-images.githubusercontent.com/10043320/156194972-652863be-1597-4f80-8cc8-51abeabed8f2.png">

## Any additional comments? 相关环境信息？

- **ice.js Version**：1.18
- **build.json Configuration**：
{
  "externals": {
    "echarts": "echarts"
  },
  "webpackLoaders": {
    "file": {
      "test": ".ico$",
      "loaders": {
        "url-loader": {}
      }
    }
  },
  "plugins": [
    "build-plugin-icestark",
    [
      "build-plugin-fusion",
      {
        "themePackage": [
          {
            "name": "@alifd/theme-19926",
            "default": true
          }
        ]
      }
    ],
    [
      "build-plugin-moment-locales",
      {
        "locales": ["zh-cn"]
      }
    ],
    [
      "build-plugin-load-assets",
      {
        "assets": ["/uicbb/echart/echarts.min.js"]
      }
    ],
    [
      "build-plugin-css-assets-local",
      {
        "outputPath": "assets",
        "relativeCssPath": "../"
      }
    ]
  ],

  "proxy": {
    ...
  }
}

- **Node Version**: 12.12
- **Platform**: mac

**Comment by ClarkXia** [comment]
提供下简单的复现 demo，最好能够明确复现路径

**Comment by ClarkXia** [comment]
提供复现 demo 后，重开 issue
