### ISSUE TITLE
引用代码库中使用了 top-level-await 特性，在飞冰配置中添加特性支持后，启动项目仍报错

### ISSUE THREAD

**Issue by zhangpeng178** [alibaba/ice#5207]
### 问题：配置后无法在项目中使用top-level-await特性

<img width="1020" alt="企业微信截图_341a6b10-ae8a-4f50-81d3-cbcc265a20c9" src="https://user-images.githubusercontent.com/83490054/156543519-53b85713-9208-49f6-8af7-5a36256e1a8d.png">

### 希望得到的结果：配置后可以使用top-level-await特性
- **ice.js Version**：^2.0.0
- **build.json Configuration**：
- **Node Version**:16.13.1
- **Platform**:MacOS

**Comment by ClarkXia** [comment]
可以暂时通过插件方式开启，https://ice.work/docs/guide/basic/build/#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%B7%A5%E7%A8%8B%E9%85%8D%E7%BD%AE

```js
module.exports = ({ onGetWebpackConfig }) => {
  onGetWebpackConfig((config) => { config.merge({ experiments: { topLevelAwait: true }}) })
}
```
