### ISSUE TITLE
生产环境特殊情况下 Auth 插件无效

### ISSUE THREAD

**Issue by luhc228** [alibaba/ice#5208]
### 问题描述

项目源码中没有使用到 `useAuth` 和 `withAuth` 时候，在 dev 环境下，Auth 能正常使用，生产环境下，Auth 失效了。

### 原因

在生产环境下，会把 auth 插件的 runtime 移除掉，导致 Auth 失效了。应该需要判断是有使用 pageConfig.auth，如果有，不需要移除。

另外 dev 环境和生产环境应该效果保持一致，生产环境下打包时应该把移除 runtime 的信息打印出来，方便调试。

**Comment by xmsz** [comment]
我也遇到，不过我的情况奇葩点，我的auth信息是父应用传递下来的。
所以app.tsx的app.getInitialData并没有设置。
导致[#5209](https://github.com/alibaba/ice/pull/5209)这个也无法打包进来

解决办法就是，设置一个
```
    getInitialData: async () => {
      return { auth: {} };
    },
```

**Comment by yiescc** [comment]
我也遇到了，代码里面没有使用到useAuth，线上的路有权限就不生效了
