### ISSUE TITLE
container missing error while using "remoteRuntime" config with preBuilt bundles 使用remoteRuntime时，第二次启动页面报错

### ISSUE THREAD

**Issue by SaltyFish6952** [alibaba/ice#5210]
## What is the current behavior? 发生了什么？

while using  “remoteRuntime: true” in build.json, in the first time it could run successfully, but in the second time ioccured error “Container Missing”.
使用 “remoteRuntime: true” 配置时，第一次可以成功运行，第二次（使用预构建bundles）报错 “Container Missing”
![image](https://user-images.githubusercontent.com/41666009/157152555-ba9eb823-359f-4933-be06-5bc754a86066.png)

## What is the expected behavior? 期望的结果是什么？

could use preBuilt bundles
可以使用预构建bundles

## Any additional comments? 相关环境信息？

only using icejs init templates
使用icejs初始化模板

- **ice.js Version**：2.5.1
- **build.json Configuration**：
```json
{
  "remoteRuntime": true,
  "plugins": [
    [
      "build-plugin-moment-locales",
      {
        "locales": ["zh-cn"]
      }
    ],
    [
      "build-plugin-ignore-style",
      {
        "libraryName": "@alifd/next"
      }
    ]
  ]
}
```

- **Node Version**: v14.18.1
- **Platform**: Windows10 2004

**Comment by ClarkXia** [comment]
具体使用的是哪个模版？

**Comment by SaltyFish6952** [comment]
> 具体使用的是哪个模版？

TS + fusion-design

**Comment by ClarkXia** [comment]
在 2.x 下推荐使用 vite 模式 https://ice.work/docs/guide/basic/vite/ 来提升 HMR 体验
