### ISSUE TITLE
getInitialProps 首次打开不会触发，在页面二次切换后才会触发

### ISSUE THREAD

**Issue by aadog** [alibaba/ice#5212]
## What is the current behavior? 发生了什么？ getInitialProps 首次打开不会触发

getInitialProps 首次打开不会触发，在页面二次切换后才会触发

## Any additional comments? 相关环境信息？

- **ice.js Version**：2.5.1
- **build.json Configuration**：
{
  "ssr": "static",
  "vite": false,
  "plugins": [
    [
      "build-plugin-ignore-style",
      {
        "libraryName": "antd"
      }
    ]
  ]
}

- **Node Version**:
- **Platform**: windows

**Comment by ClarkXia** [comment]
最新版本（2.6.3）无法复现，如果还有问题可以提供复现 demo
