### ISSUE TITLE
怎么样实现跟umijs的exportStatic: true 生成所有html,而不启动server

### ISSUE THREAD

**Issue by aadog** [alibaba/ice#5213]
## What is the expected behavior? 期望的结果是什么？

怎么样实现跟umijs的exportStatic: true 生成所有html,而不启动server，启动server太卡了，我们都是golang直接对着就干了

## Any additional comments? 相关环境信息？

- **ice.js Version**：
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by ClarkXia** [comment]
默认可以直接 build，类似 exportStatic 的能力后续考虑在 ice 3.0 版本中实现 https://github.com/ice-lab/ice-next/issues/255
