### ISSUE TITLE
如何打包出入口index.js和入口index.css，用于其他html可以指定名称引入

### ISSUE THREAD

**Issue by antstudio-git** [alibaba/ice#5220]
目前如果有多个css文件，打包出来后，无法只引入index.js 和 index.css 来实现加载所有资源。
如何配置能实现？

**Comment by ClarkXia** [comment]
是这个 https://github.com/alibaba/ice/issues/4818 诉求吗

**Comment by antstudio-git** [comment]
> 是这个 #4818 诉求吗

这个我试了下，不知道是不是我用的不对，下面是build.json的配置，打包出来还是多个css


`{
  "vite": {
    "build": {
      "chunkSizeWarningLimit": 500,
    }
  },
  "publicPath": "http://localhost/0.0.1/",
  "cssChunkNames": [
    "index-main.css"
  ],
  "lessLoaderOptions": {
    
  },
  "plugins": [
    [
      "build-plugin-ignore-style",
      {
        "libraryName": "antd"
      }
    ]
  ]
}
`

**Comment by ClarkXia** [comment]
打出多个 css 是分包的原因，其他引入的 css 是通过脚本动态引入的

**Comment by antstudio-git** [comment]
> 打出多个 css 是分包的原因，其他引入的 css 是通过脚本动态引入的，只要确保入口样式正确就行，如果还有问题最好提供下复现的 demo 和步骤

其实问题是这样的：

1. 我在web工程build出来4个css， index1,index2,index3,vendor
2. build出来的html中，引入的是index3和vendor的css （如果工程新增了样式，index4会被引入）
3. 发布这些build到了cdn并按版本号隔离
4. 我有个springmvc的工程中，index.html中的js和css会通过服务端指定版本加载

所以index.html中是这样的
`
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    <script defer src="//localhost/${version}/js/index.js"></script>
    <link href="//localhost/${version}/css/index.css" rel="stylesheet">
</head>
<body>
<div id="ice-container"></div>
</body>
</html>
`

**Comment by komaedaXnagito** [comment]
> cssChunkNames

老哥，我试了一下，你配置里面不要用数组，直接写名字就行。我翻了一下他的源码，接受的类型是string 或者 record<string,string>

**Comment by komaedaXnagito** [comment]
> > 打出多个 css 是分包的原因，其他引入的 css 是通过脚本动态引入的，只要确保入口样式正确就行，如果还有问题最好提供下复现的 demo 和步骤
> 
> 其实问题是这样的：
> 
> 1. 我在web工程build出来4个css， index1, index2, index3, vendor
> 2. build出来的html中，引入的是index3和vendor的css （如果工程新增了样式，index4会被引入）
> 3. 发布这些build到了cdn并按版本号隔离
> 4. 我有个spring mvc的工程中，index.html中的js和css会通过服务端指定版本加载
> 
> 所以index.html中是这样的
> 
> ```
> <!DOCTYPE html>
> <html lang="en">
> <head>
>     <meta charset="UTF-8">
>     <title>Index</title>
>     <script defer src="//localhost/${version}/js/index.js"></script>
>     <link href="//localhost/${version}/css/index.css" rel="stylesheet">
> </head>
> <body>
> <div id="ice-container"></div>
> </body>
> </html>
> ```

老哥，我试了一下，你配置里面不要用数组，直接写名字就行。我翻了一下他的源码，接受的类型是string 或者 record<string,string>

**Comment by antstudio-git** [comment]
> > > 打出多个 css 是分包的原因，其他引入的 css 是通过脚本动态引入的，只要确保入口样式正确就行，如果还有问题最好提供下复现的 demo 和步骤
> > 
> > 
> > 其实问题是这样的：
> > 
> > 1. 我在web工程build出来4个css， index1, index2, index3, vendor
> > 2. build出来的html中，引入的是index3和vendor的css （如果工程新增了样式，index4会被引入）
> > 3. 发布这些build到了cdn并按版本号隔离
> > 4. 我有个spring mvc的工程中，index.html中的js和css会通过服务端指定版本加载
> > 
> > 所以index.html中是这样的
> > ```
> > <!DOCTYPE html>
> > <html lang="en">
> > <head>
> >     <meta charset="UTF-8">
> >     <title>Index</title>
> >     <script defer src="//localhost/${version}/js/index.js"></script>
> >     <link href="//localhost/${version}/css/index.css" rel="stylesheet">
> > </head>
> > <body>
> > <div id="ice-container"></div>
> > </body>
> > </html>
> > ```
> 
> 老哥，我试了一下，你配置里面不要用数组，直接写名字就行。我翻了一下他的源码，接受的类型是string 或者 record<string,string>

嗯。。我之前也是直接用的string，也没生效，所以才来求助 。。。

**Comment by komaedaXnagito** [comment]
> > > > 打出多个 css 是分包的原因，其他引入的 css 是通过脚本动态引入的，只要确保入口样式正确就行，如果还有问题最好提供下复现的 demo 和步骤
> > > 
> > > 
> > > 其实问题是这样的：
> > > 
> > > 1. 我在web工程build出来4个css， index1, index2, index3, vendor
> > > 2. build出来的html中，引入的是index3和vendor的css （如果工程新增了样式，index4会被引入）
> > > 3. 发布这些build到了cdn并按版本号隔离
> > > 4. 我有个spring mvc的工程中，index.html中的js和css会通过服务端指定版本加载
> > > 
> > > 所以index.html中是这样的
> > > ```
> > > <!DOCTYPE html>
> > > <html lang="en">
> > > <head>
> > >     <meta charset="UTF-8">
> > >     <title>Index</title>
> > >     <script defer src="//localhost/${version}/js/index.js"></script>
> > >     <link href="//localhost/${version}/css/index.css" rel="stylesheet">
> > > </head>
> > > <body>
> > > <div id="ice-container"></div>
> > > </body>
> > > </html>
> > > ```
> > 
> > 
> > 老哥，我试了一下，你配置里面不要用数组，直接写名字就行。我翻了一下他的源码，接受的类型是string 或者 record<string,string>
> 
> 嗯。。我之前也是直接用的string，也没生效，所以才来求助 。。。

用的是2.6.0版本吗？

**Comment by antstudio-git** [comment]
> > > > > 打出多个 css 是分包的原因，其他引入的 css 是通过脚本动态引入的，只要确保入口样式正确就行，如果还有问题最好提供下复现的 demo 和步骤
> > > > 
> > > > 
> > > > 其实问题是这样的：
> > > > 
> > > > 1. 我在web工程build出来4个css， index1, index2, index3, vendor
> > > > 2. build出来的html中，引入的是index3和vendor的css （如果工程新增了样式，index4会被引入）
> > > > 3. 发布这些build到了cdn并按版本号隔离
> > > > 4. 我有个spring mvc的工程中，index.html中的js和css会通过服务端指定版本加载
> > > > 
> > > > 所以index.html中是这样的
> > > > ```
> > > > <!DOCTYPE html>
> > > > <html lang="en">
> > > > <head>
> > > >     <meta charset="UTF-8">
> > > >     <title>Index</title>
> > > >     <script defer src="//localhost/${version}/js/index.js"></script>
> > > >     <link href="//localhost/${version}/css/index.css" rel="stylesheet">
> > > > </head>
> > > > <body>
> > > > <div id="ice-container"></div>
> > > > </body>
> > > > </html>
> > > > ```
> > > 
> > > 
> > > 老哥，我试了一下，你配置里面不要用数组，直接写名字就行。我翻了一下他的源码，接受的类型是string 或者 record<string,string>
> > 
> > 
> > 嗯。。我之前也是直接用的string，也没生效，所以才来求助 。。。
> 
> 用的是2.6.0版本吗？

是的，我就是看了那个issue，特意升级过去的。低版本这个config是报错的

**Comment by ClarkXia** [comment]
@antstudio-git 这个配置是为了让入口的 css 名称固定，分出多个 css 是 dynamic import 引起。如果还是有问题可以提供复现 demo 重开 issue
