### ISSUE TITLE
使用IDEA运行 npm安装了icework依赖包，运行ice dev 提示：Unknown command dev

### ISSUE THREAD

**Issue by Oyilin** [alibaba/ice#5221]
![image](https://user-images.githubusercontent.com/32355286/157796420-5e0832af-6cc0-4131-8402-4a2ba2462257.png)

**Comment by ClarkXia** [comment]
https://github.com/ice-lab/iceworks-cli 启动 cli 是 iceworks，另外如果是为了开发项目 请直接使用 ice.js
