### ISSUE TITLE
权限管理不支持children子路由,或者说不支持没有component的路径，有解决方法帮忙处理下啊

### ISSUE THREAD

**Issue by aadog** [alibaba/ice#5223]
## What is the current behavior? 发生了什么？权限管理不支持children子路由,或者说不支持没有component的路径

    path: '/admin',
    component: AdminLayout,
    pageConfig:{
          auth:['admin']
        },
    children: [
      {
        path: '/test',
        component: lazy(() => import('@/pages/Admin/Test')),
      },
    ]

/admin/test和/admin auth无效

## What is the expected behavior? 期望的结果是什么？ 

/admin
/admin/test
/admin/*下数据都需要权限

## Any additional comments? 相关环境信息？

- **ice.js Version**："ice.js": "^2.5.1",
- **build.json Configuration**：

{
  "vite": true,
  "plugins": [
    ["build-plugin-ignore-style", {
      "libraryName": "antd"
    }]
  ],
  "proxy": {
    "/api": {
      "enable": true,
      "target": "http://127.0.0.1:8080"
    }
  }
}

- **Node Version**:
- **Platform**: windows

**Comment by a97077088** [comment]
**在这里改一下代码引入路由递归下顶层路由应该就可以了，但是...愣是没找到怎么获取全部路由的方法...**

`
//build-plugin-ice-auth/src/runtime.tsx


const wrapperComponentFn = (authConfig: IAuth) => (PageComponent) => {
  const { pageConfig = {} } = PageComponent;

  const AuthWrappedComponent = (props) => {
    const [ auth ] = useAuth();
    const pageConfigAuth = pageConfig.auth;
    //这里开始递归顶层路由,false为顶优,没有权限跳过继续递归,直到顶层,但是怎么引入路由方法呢
    if (pageConfigAuth && !Array.isArray(pageConfigAuth)) {
      throw new Error('pageConfig.auth must be an array');
    }

    const hasAuth =
      Array.isArray(pageConfigAuth) && pageConfigAuth.length
        ? Object.keys(auth).filter((item) =>
          pageConfigAuth.includes(item) ? auth[item] : false
        ).length
        : true;

    if (!hasAuth) {
      if (authConfig.NoAuthFallback) {
        if (typeof authConfig.NoAuthFallback === 'function') {
          return <authConfig.NoAuthFallback {...Object.assign({}, props, {pageConfig})} />;
        }
        return authConfig.NoAuthFallback;
      }
      return <>No Auth</>;
    }
    return <PageComponent {...props} />;
  };
  return AuthWrappedComponent;
};



`

**Comment by imsobear** [comment]
@aadog 问题解决了吗？

**Comment by aadog** [comment]
解决了，官方说不支持找个功能，只能又转umi了

**Comment by xmsz** [comment]
这个功能还是蛮想要的 希望支持

**Comment by imsobear** [comment]
> 这个功能还是蛮想要的 希望支持

@xmsz 用的哪个版本？ @wssgcg1213 可以关注下

**Comment by xmsz** [comment]
> > 这个功能还是蛮想要的 希望支持
> 
> @xmsz 用的哪个版本？ @wssgcg1213 可以关注下

我还是v2
