### ISSUE TITLE
webpack5 entry 支持了import dependOn 等属性，希望icejs 2.0的entry属性支持Object的配置

### ISSUE THREAD

**Issue by chenhebing** [alibaba/ice#5227]
webpack5  entry 支持了 「描述入口的对象」，但是现在icejs 2.0 只支持 string | string[] | record<string, string|string[]>  希望可以支持Object的配置方式

https://webpack.docschina.org/concepts/entry-points/#entry-description-object

**Comment by ClarkXia** [comment]
本质原因是 webpack-chain 未能完善支持 webpack 5 的相关配置，导致指导 entry 内容在转化后变为数组形式，目前可以通过以下手段支持 import dependOn 等属性：

```js
// 新增自定义插件，在执行具体的 webpack 任务之前修改 webpack 配置

module.exports = ({ onHook, context }) => {
  const { command } = context;
  onHook(`before.${command}.run`, ({ config }) => {
    console.log(config);
    config[0].entry = {
      index: {
        import: './src/app.tsx',
        runtime: 'runtime',
      },
    };
  });
};
```
