### ISSUE TITLE
awesome-materials

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#523]
物料源汇总：

* React
   * [react-materials](https://g.alicdn.com/ice-assets/ice-design/databases/react-materials.json)
* Vue
   * [vue-materials](https://g.alicdn.com/ice-assets/ice-design/databases/vue-materials.json)

**Comment by yujiangshui** [comment]
最好可以有站点等看到实际效果

**Comment by chenbin92** [comment]
@yujiangshui  后续有优质物料源可以介入到官方站点展示

**Comment by yujiangshui** [comment]
@chenbin92 不是官方站点展示，原本计划有一个轻量的站点，可以在构建物料的时候，一起构建出来用来做静态展示。

**Comment by james-cain** [comment]
vue-materials.json中的scaffolds中增加下面的源，可以使用新的模板
{
      "name": "cain-ice-template-lite",
      "title": "Cain Ice Lite",
      "source": {
        "type": "npm",
        "npm": "@coracain/cain-ice-template",
        "version": "1.0.1",
        "registry": "http://registry.npmjs.com"
      },
      "dependencies": {
        "axios": "^0.18.0",
        "babel-polyfill": "^6.26.0",
        "echarts": "^4.0.4",
        "element-ui": "^2.3.2",
        "mockjs": "^1.0.1-beta3",
        "normalize.css": "^8.0.0",
        "nprogress": "^0.2.0",
        "vue": "^2.5.2",
        "vue-router": "^3.0.1",
        "vuex": "^3.0.1"
      },
      "devDependencies": {
        "autoprefixer": "^7.1.2",
        "babel-core": "^6.22.1",
        "babel-eslint": "^8.2.1",
        "babel-helper-vue-jsx-merge-props": "^2.0.3",
        "babel-loader": "^7.1.1",
        "babel-plugin-component": "^1.1.0",
        "babel-plugin-syntax-jsx": "^6.18.0",
        "babel-plugin-transform-runtime": "^6.22.0",
        "babel-plugin-transform-vue-jsx": "^3.5.0",
        "babel-preset-env": "^1.3.2",
        "babel-preset-stage-2": "^6.22.0",
        "chalk": "^2.0.1",
        "chokidar": "^2.0.3",
        "copy-webpack-plugin": "^4.0.1",
        "css-loader": "^0.28.0",
        "eslint": "^4.15.0",
        "eslint-config-airbnb-base": "^11.3.0",
        "eslint-friendly-formatter": "^3.0.0",
        "eslint-import-resolver-webpack": "^0.8.3",
        "eslint-loader": "^1.7.1",
        "eslint-plugin-import": "^2.7.0",
        "eslint-plugin-vue": "^4.0.0",
        "extract-text-webpack-plugin": "^3.0.0",
        "file-loader": "^1.1.4",
        "friendly-errors-webpack-plugin": "^1.6.1",
        "html-webpack-plugin": "^2.30.1",
        "less": "^3.0.1",
        "less-loader": "^4.1.0",
        "node-notifier": "^5.1.2",
        "optimize-css-assets-webpack-plugin": "^3.2.0",
        "ora": "^1.2.0",
        "portfinder": "^1.0.13",
        "postcss-import": "^11.0.0",
        "postcss-loader": "^2.0.8",
        "postcss-url": "^7.2.1",
        "rimraf": "^2.6.0",
        "semver": "^5.3.0",
        "shelljs": "^0.7.6",
        "svg-sprite-loader": "^3.7.3",
        "uglifyjs-webpack-plugin": "^1.1.1",
        "url-loader": "^0.5.8",
        "vue-loader": "^13.3.0",
        "vue-style-loader": "^3.0.1",
        "vue-template-compiler": "^2.5.2",
        "webpack": "^3.6.0",
        "webpack-bundle-analyzer": "^2.11.1",
        "webpack-dev-server": "^2.9.1",
        "webpack-merge": "^4.1.0"
      },
      "screenshot": "https://img.alicdn.com/tfs/TB1SqrjontYBeNjy1XdXXXXyVXa-2842-1596.png",
      "categories": [
        
      ],
      "features": {
        
      },
      "repository": "https://github.com/james-cain/cain-ice-template",
      "description": "该模板适用于从 0 到 1 开始搭建项目，内置基础的页面，路由和菜单展示。",
      "publishTime": "2018-05-24T08:09:16.315Z",
      "updateTime": "2018-05-24T08:09:20.486Z"
}

附上源码地址：https://github.com/james-cain/cain-ice-template

**Comment by chenbin92** [comment]
已移动到 wiki 中
