### ISSUE TITLE
request 类型问题

### ISSUE THREAD

**Issue by theonell** [alibaba/ice#5232]
![1647322625746_25101216-17F2-4ff6-90C6-39F3F42E91A7](https://user-images.githubusercontent.com/33079405/158315195-b1b607e1-9995-4f3b-9b5a-e8fd18d603d8.png)
 request baseURL ts报语法错误， 程序可以正常运行

**Comment by ClarkXia** [comment]
![image](https://user-images.githubusercontent.com/4219965/158315790-12edecf4-8430-475b-9cf3-0f25947c48a4.png)
默认情况下无法复现，可以提供下 demo

**Comment by theonell** [comment]
需要手动安装axios依赖么？？

**Comment by ClarkXia** [comment]
> 需要手动安装axios依赖么？？

不需要 ice 框架内置锁定了依赖，可以看下你用的是什么版本的 ice.js
