### ISSUE TITLE
Vite模式下如何自定义css module配置？

### ISSUE THREAD

**Issue by galaxynova1999** [alibaba/ice#5239]
## What is the current behavior? 发生了什么？
在Vite模式下需要配置module less导出的变量名为驼峰形式，根据Vite官方文档需要配置如下：
![image](https://user-images.githubusercontent.com/45778220/158771708-82794b99-01b4-466f-87f3-ff8d8e8e9923.png)

ice不会读取在根目录下新建的vite.config.js文件 

切换到Webpack模式，可以通过CssLoader选项来配置：
```js
cssLoaderOptions: {
    modules: {
      localIdentName: '[local]_[hash:base64:5]',
      exportLocalsConvention: 'camelCase',
    },
  },
```

## What is the expected behavior? 期望的结果是什么？
能够通过某种配置来修改Vite Css Module配置

**Comment by ClarkXia** [comment]
暂时可以通过配置 vite 字段，后续将支持直接读取 cssLoaderOptions 的配置

```js
{
  vite: {
    css: {
      module: {...}
    }
  }
}

```
