### ISSUE TITLE
项目占用内存过大，重编译1-2次就增加很大内存占用且不会被释放

### ISSUE THREAD

**Issue by lbarakidouji** [alibaba/ice#5241]
## What is the current behavior? 发生了什么？
近期，我们将使用 ice-scripts的项目升级到了 ice.js 最新版本
但是升级之后发现项目占用的内存变得很大，并且会存在 dev 下内存泄漏问题

更有小伙伴启动项目都起不来，CPU飙升100%....
build 时也一样

感到奇怪的是
dev 下，就算没有任何代码的改动，只是单纯的保存一下，都会进行重新编译，内存占用也会随之提高
有时候放着不动，什么操纵都不做，内存占用也会莫名其妙的增大

![image](https://user-images.githubusercontent.com/83287204/159167640-f45fc0fc-4f8c-4590-b4d3-7ca498a71f97.png)

## What is the expected behavior? 期望的结果是什么？
优化内存占用
## Any additional comments? 相关环境信息？

- **ice.js Version**：2.6.1
- **build.json Configuration**：
```
const proxyMap = require('./config/proxy');
const themeMap = require('./config/antdTheme');
const { PROXY_KEY, THEME } = process.env;

module.exports = {
  publicPath: './',
  alias: {
    '@': './src/',
  },
  hash: 'contenthash',
  vendor: true,
  outputDir: 'dist',
  define: {
    TSIETHEME: THEME.split('-')[1] === '浅色' ? 'light' : 'dark',
    THEMENAME: THEME,
  },
  proxy: PROXY_KEY
    ? proxyMap[PROXY_KEY]
    : {
        '/web': {
          target: 'https://xxxxx',
          pathRewrite: {
            '/web': '/web',
          },
          enable: true,
        },
      },
  lessLoaderOptions: {
    modifyVars: {
      ...themeMap[THEME]['modify-vars'],
    },
    math: 0,
  },
  plugins: [
    [
      'build-plugin-moment-locales',
      {
        locales: ['zh-cn'],
      },
    ],
    [
      'build-plugin-antd',
      {
        disableModularImport: true,
        themeConfig: THEME
          ? {
              ...themeMap[THEME]['build-plugin-antd-theme'],
            }
          : {
              'primary-color': '#295EF3',
              'link-color': 'rgb(0, 0, 0, 0.65)',
              'text-color': 'rgb(0, 0, 0, 0.65)',
              'table-header-bg': '#242c3b',
            },
      },
    ],
  ],
};
```

- **Node Version**: 15.2.0
- **Platform**:

**Comment by lbarakidouji** [comment]
$ npm list @builder/app-helpers：
![image](https://user-images.githubusercontent.com/83287204/159168146-69a8a815-317f-4454-8531-21e1b79f250b.png)

**Comment by ClarkXia** [comment]
没有复现的 demo 比较难以判断，可以在 dev 阶段尝试通过 `icejs start --build-speed` 定位下 构建耗时较长的编译任务

**Comment by imsobear** [comment]
建议提供个能重现的项目放到 GitHub 上。

**Comment by lbarakidouji** [comment]
操作：
随便进入一个文件，然后不断的保存，每次保存都会增加内存占用，并且慢慢的内存也不会被释放出来

**Comment by lbarakidouji** [comment]
录屏有点大，上传到了阿里云盘了，地址：https://www.aliyundrive.com/s/js3k1K6Pk3B

**Comment by lbarakidouji** [comment]
T T  想了解一下有什么进展吗

是我们项目的问题还是？

我尝试回到老版本，但是对应的 @builder/app-helpers 装的一直都是2.5.3最新版本... 导致启动不来

**Comment by imsobear** [comment]
等等，我在看，这两天会回复

**Comment by lbarakidouji** [comment]
更新： 因为配置中开启了 `hash: true` 所导致了，关闭该项配置后恢复正常

**Comment by imsobear** [comment]
> 更新： 因为配置中开启了 `hash: true` 所导致了，关闭该项配置后恢复正常

可以现在 dev 环境下关闭 hash，`hash: process.env.NODE_ENV === 'production' ? 'contenthash' : false`
