### ISSUE TITLE
build-plugin-ice-i18n 使用非hooks方式设置语言

### ISSUE THREAD

**Issue by we6288815** [alibaba/ice#5243]
## What is the current behavior? 发生了什么？
我需要在app.tsx的getInitialData方法中根据后台返回的多语言环境设置语言，但是插件提供的useLocale是个hooks，无法在app.tsx中直接使用，期望能提供非hooks方式设置语言。

![image](https://user-images.githubusercontent.com/8169722/159832329-37ef6cb3-ef3c-4911-a480-4229b4dc8c8a.png)

## Any additional comments? 相关环境信息？

- **ice.js Version**：^2.0.0
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by we6288815** [comment]
希望能提供非hooks的set和get方法，我还需要在request的响应拦截里提示多语言文本。

**Comment by luhc228** [comment]
> 希望能提供非hooks的set和get方法，我还需要在request的响应拦截里提示多语言文本。

getLocale 已经有了的：https://ice.work/docs/guide/advanced/i18n#getlocale

setLocale 的提供：https://github.com/alibaba/ice/pull/5253

**Comment by we6288815** [comment]
> getLocale 已经有了的：https://ice.work/docs/guide/advanced/i18n#getlocale
> setLocale 的 PR：https://github.com/alibaba/ice/pull/5253

非常感谢

**Comment by we6288815** [comment]
> getLocale 已经有了的：https://ice.work/docs/guide/advanced/i18n#getlocale
> setLocale 的 PR：https://github.com/alibaba/ice/pull/5253

非常感谢

**Comment by we6288815** [comment]
> getLocale 已经有了的：https://ice.work/docs/guide/advanced/i18n#getlocale
> setLocale 的 PR：https://github.com/alibaba/ice/pull/5253

非常感谢
