### ISSUE TITLE
icejs test的时候如何指定测试用例文件

### ISSUE THREAD

**Issue by HengzheLi** [alibaba/ice#5248]
jest下可以使用 --runTestsByPath xxxxxxx 来指定要运行的测试文件，也能发现测试文件中的测试用例

icejs test下使用该参数  --jest-runTestsByPath xxxxxxx后报的是没有找到匹配的测试用例
```
testMatch: xxxxxxx - 0 matches
  testPathIgnorePatterns: \\node_modules\\ - 126 matches
  testRegex:  - 0 matches
```

如果我只想运行某个用例或某个文件下的用例需要怎么操作呢

**Comment by ClarkXia** [comment]
icejs test 之后后面跟 testMatch，`icejs test "testPattern"` 的形式

**Comment by HengzheLi** [comment]
> icejs test 之后后面可以直接跟 testMatch，`icejs test "testPattern"` 的形式

testPattern是匹配的哪个地方的内容，尝试了文件名，describe和it的内容都没成功，返回的都是
```
testMatch:  [testPattern]- 0 matches
  testPathIgnorePatterns: \\node_modules\\ - 126 matches
  testRegex:  - 0 matches
```

**Comment by ClarkXia** [comment]
testPattern 匹配的是测试文件名，可以提供下简单的 demo 供复现

**Comment by HengzheLi** [comment]
直接配置jest.config.js绕开了  随便问一下大家平时 
```
icejs test "文件名"
```
是可以的吗

**Comment by ClarkXia** [comment]
是的，比如执行，可以指定对应的测试用例
![image](https://user-images.githubusercontent.com/4219965/164965385-ed6e6656-7f60-4f49-961a-b1342ffd4922.png)
![image](https://user-images.githubusercontent.com/4219965/164965398-e96bce4e-84bb-4852-b89b-c782d162d4af.png)
