### ISSUE TITLE
如何保留已加载页面 不重复加载

### ISSUE THREAD

**Issue by jie-L** [alibaba/ice#5250]
做一个tab页的功能   默认加载A页面   从A页面 appHistory.push() 到B页面 再返回A会重新加载

/BasicLayout/index.tsx
![image](https://user-images.githubusercontent.com/53324040/160043088-ab52f354-e184-4166-a23f-c8337c69c12e.png)

**Comment by maoxiaoke** [comment]
@jie-L 参考下 https://github.com/maoxiaoke/icestark-multi-tabs 这个能否满足？

**Comment by jie-L** [comment]
> 

 https://github.com/maoxiaoke/icestark-multi-tabs 
默认browser模式没有问题    但是 修改为hash模式后    微应用还是不会保留   每次都重新加载   主应用页面可以保留

**Comment by maoxiaoke** [comment]
@jie-L 在上面的例子中，用的是 path 作为缓存的标识，不论其是不是 hash 模式。

**Comment by jie-L** [comment]
> > 
> 
> https://github.com/maoxiaoke/icestark-multi-tabs 默认browser模式没有问题 但是 修改为hash模式后 微应用还是不会保留 每次都重新加载 主应用页面可以保留

@maoxiaoke   用了您给提供的这个多tab的demo   发现hash模式    使用微应用链接的tab还是会重新加载

**Comment by maoxiaoke** [comment]
@jie-L 如何确定的不会缓存？除非不同的 tab 使用使用了相同的 name ?

**Comment by jie-L** [comment]
> 

感谢回复   我马上提供一个demo出来

**Comment by jie-L** [comment]
> @jie-L 如何确定的不会缓存？除非不同的 tab 使用使用了相同的 name ?

https://github.com/jie-L/icestark-multi-tabs.git

**Comment by maoxiaoke** [comment]
@jie-L 给个完整点的例子，微应用地址无法访问

**Comment by jie-L** [comment]
> @jie-L 给个完整点的例子，微应用地址无法访问

可以访问   本地启动应用访问微应用会有跨域问题     参考下 https://blog.csdn.net/u011293970/article/details/108483638

**Comment by maoxiaoke** [comment]
@jie-L 我用的 macOs 我看下怎么操作

**Comment by jie-L** [comment]
> @jie-L 我用的 macOs 我看下怎么操作
好的  感谢

**Comment by maoxiaoke** [comment]
@jie-L 微应用直接用官方的 demo 生成的吗？可否直接上传一个微应用的 demo

**Comment by jie-L** [comment]
是的  用的vscode模板   稍等我上传一下

**Comment by maoxiaoke** [comment]
@jie-L 

根因：微应用会响应路由变化，导致微应用路由卸载，复重复加载导致
修复办法：微应用使用 memory 路由，以 ice 应用为例


```js
const appConfig: IAppConfig = {
  router: {
    type: 'memory',
    initialEntries: ['/list', '/'],
    initialIndex: 0,
    // type: 'browser',
  },
};

```
