### ISSUE TITLE
Cannot find module '@ice/store' from '.ice/index.ts'

### ISSUE THREAD

**Issue by HengzheLi** [alibaba/ice#5252]
## What is the current behavior? 发生了什么？
测试启动的时候报
```
Cannot find module '@ice/store' from '.ice/index.ts'
```

## Any additional comments? 相关环境信息？

- **ice.js Version**：2.6.1
- **build.json Configuration**：
- **Node Version**: 16.13.1
- **Platform**: windows/linux

查了一下node_modules下的@ice/store包，发现下面只有esm格式的文件，没有commonjs格式的文件。前面有commonjs格式文件的时候(有lib文件)可以正常启动，最近一次yarn install后发现只有esm文件夹，没有lib文件夹了，然后就一直失败
@ice/store版本为2.0.0

![Uploading image.png…]()

**Comment by HengzheLi** [comment]
把@ice/store的版本降级到1.*后问题解决，查看了文档https://github.com/ice-lab/icestore/blob/stable/1.x/docs/upgrade-guidelines.zh-CN.md  好像没有提到这个迁移操作，是有什么breaking change吗

**Comment by imsobear** [comment]
@HengzheLi 是不是在 `@ice/store` package.json 里加一个 `"main": "esm/index.js"` 就可以了？上个版本 2.0.0-4 就是这样的，你可以本地试下，没问题的话我来加下这个字段。

**Comment by HengzheLi** [comment]
> @HengzheLi 是不是在 `@ice/store` package.json 里加一个 `"main": "esm/index.js"` 就可以了？上个版本 2.0.0-4 就是这样的，你可以本地试下，没问题的话我来加下这个字段。

是的  加了
```
"main": "esm/index.js"
```
就好了

**Comment by imsobear** [comment]
已发布 @ice/store@2.0.1
