### ISSUE TITLE
error overlay is not working anymore

### ISSUE THREAD

**Issue by maoxiaoke** [alibaba/ice#5254]
## How to reproduce

1. Init a new project: `pnpm ice init xxx`
2. Toss in a random error:

```jsx
const Home = () => {
 // `error` isn't declared or intialized
  console.log('error', error);
  return <Guide />;
};
```

**Comment by imsobear** [comment]
听说是 react-error-overlay 版本问题，现在有解决吗，更新下进度？

**Comment by maoxiaoke** [comment]
目前 ice.js 会通过 [webpack.devServer](https://webpack.js.org/configuration/dev-server/#overlay) 提供 **编译时 overlay**。

> Shows a full-screen overlay in the browser when there are compiler errors or warnings.

**Comment by maoxiaoke** [comment]
It‘s more likely a feature request instead of a bug. Just close it.
