### ISSUE TITLE
打包成docker镜像报错 未找到icejs

### ISSUE THREAD

**Issue by ChenLeoXX** [alibaba/ice#5260]
## What is the current behavior? 发生了什么？
打包docker镜像build 提示未找到icejs
![image](https://user-images.githubusercontent.com/27530887/161028273-608cc798-eee1-4f79-a452-983c6b8a52e8.png)

## What is the expected behavior? 期望的结果是什么？
完成docker镜像打包
## Any additional comments? 相关环境信息？

- **ice.js Version**：
- ^2.0.0
- **build.json Configuration**：
- 
![image](https://user-images.githubusercontent.com/27530887/161028139-bcc5689d-4a3e-4016-9669-9c9d589086fc.png)

- **Node Version**:
- 16.14.2
- **Platform**:
- macOS

**Comment by imsobear** [comment]
yarn run build 的内容是什么？

**Comment by onlyacat** [comment]
刚刚也遇到了

如果用的也是 VSC 的教程的话， 你看看是不是在 dockerfile 里头指定了 node 的环境

把两个都去掉就可以了

提供一个 debug 的 dockerfile 参考
```dockerfile
FROM node:18-alpine3.14

WORKDIR /usr/src/app

COPY ["package.json", "build.json", "./"]

RUN npm install --silent --registry=https://registry.npmmirror.com && mv node_modules ../

EXPOSE 3333

CMD npm run start

**Comment by ClarkXia** [comment]
如果还有问题 请提供详细的 docker 配置

**Comment by ChenLeoXX** [comment]
> 是在 dockerfile 里头指定了 node 的环境

FROM node:alpine as builder
ENV NODE_ENV production

WORKDIR /code
ADD package.json yarn.lock /code/

RUN yarn config set registry https://registry.npmmirror.com \
&& yarn

ADD . /code

RUN npm run build


RUN ls node_modules/ice.js/bin


FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/
COPY --from=builder code/build /usr/share/nginx/html/
EXPOSE 80
