### ISSUE TITLE
配置 hash:'contenthash'不生效

### ISSUE THREAD

**Issue by theonell** [alibaba/ice#5261]
// build.config.js 文件内容
![lQLPDhtJ2QHaaPBGzQQysAZ0leSuRxDYAkmqTU8AEwA_1074_70](https://user-images.githubusercontent.com/33079405/161181322-5d329e8d-48a7-4f33-90c5-7c9a5b82499a.png)
export default {
  hash: 'contenthash',
  vendor: true,
  plugins: [
    [
      'build-plugin-fusion',
      {
        themePackage: [
          {
            name: '@icedesign/theme',
            default: true,
            themeConfig: {
              'btn-pure-primary-bg': '#27a5e0',
            },
          },
          {
            name: '@alifd/theme-dark-pro',
          },
        ],
      },
    ],
    [
      'build-plugin-css-assets-local',
      {
        outputPath: 'assets',
        relativeCssPath: '../',
      },
    ],
  ],
  proxy: {
    '/api': {
      enable: true,
      changeOrigin: true,
      target: 'http://10.0.0.100:13306',
      pathRewrite: { '^/api': '' },
    },
    '/esApi': {
      enable: true,
      changeOrigin: true,
      target: 'http://10.0.0.20:9200',
      pathRewrite: { '^/esApi': '' },
    },
  },
  alias: {
    '@': './src/',
    '@comp': './src/components/',
    '@store': './src/store/',
    '@utils': './src/utils/',
    '@api': './src/api/',
    '@assets': './src/assets/',
    '@pages': './src/pages/',
    buffer: require.resolve('buffer/'),
    zlib: false,
    stream: require.resolve('stream-browserify/'),
  },
  webpackPlugins: {
    'webpack.ProvidePlugin': {
      options: {
        Buffer: ['buffer', 'Buffer'],
      },
    },
  },
  eslint: false,
}

**Comment by ClarkXia** [comment]
![image](https://user-images.githubusercontent.com/4219965/161181722-dcf681f4-d8f6-4092-8406-c08294c819ee.png)
配置之后 build 产物上会带上 hash，确认下不生效的表现，如果还有问题 提供下复现 demo

**Comment by theonell** [comment]
![Uploading image.png…]()

**Comment by theonell** [comment]
![image](https://user-images.githubusercontent.com/33079405/161184425-0775d373-07de-4d84-b074-7ea7cccc431a.png)

**Comment by luhc228** [comment]
> ![image](https://user-images.githubusercontent.com/33079405/161184425-0775d373-07de-4d84-b074-7ea7cccc431a.png)

要一个可复现的 demo

**Comment by ClarkXia** [comment]
无法复现，暂时关闭，可以带复现 demo 重开 issue
