### ISSUE TITLE
升级React 18

### ISSUE THREAD

**Issue by usercao** [alibaba/ice#5264]
React 18正式版已经发布了，请问有计划升级安排吗？

**Comment by imsobear** [comment]
估计项目里直接把 react 升级到 18 就可以，有兴趣可以验证下。

**Comment by usercao** [comment]
@imsobear 好的我试试，但还是希望ice官方模板和相关生态也同步升级一下

**Comment by usercao** [comment]
```js
// After
import { createRoot } from 'react-dom/client';
const container = document.getElementById('app');
const root = createRoot(container);
root.render(<App tab="home" />);
```

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/13760476/161481014-e5a5217d-8fbd-43ae-949a-40ea7854dfe0.png">

试了下按照官方升级指南使用都报错，还是等icejs升级完再使用吧

**Comment by imsobear** [comment]
> @imsobear 好的我试试，但还是希望ice官方模板和相关生态也同步升级一下

嗯 这个我来跟进下

**Comment by imsobear** [comment]
@usercao 我试了下貌似除了几个 warning 没有其他问题，你上面报错这个 demo 可以往 GitHub 上提交下。

**Comment by usercao** [comment]
@imsobear demo地址 [ice-test](https://github.com/usercao/ice-test) 中的`StackManager.tsx`
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/13760476/164619300-66e80737-e0bb-4cd4-93c4-e119d895ae38.png">

**Comment by feitian124** [comment]
期待升级
