### ISSUE TITLE
如何异步更新 initialData 

### ISSUE THREAD

**Issue by strongyc** [alibaba/ice#5265]
在权限设计体系中，前端页面几乎都是需要登录后才能获取用户的权限和角色，是否应该将getInitialData在app.tsx中定义导出不调用，然后再登录时成功后调用该函数再去拉取用户权限和角色，并且需要像umi一样支持在页面里支持重新设置setInitialData

**Comment by strongyc** [comment]
按照isse里的回复
import React, { useEffect } from 'react';
import { createApp, history } from 'ice';

const NoAuth = () => {
  useEffect(() => {
    history.push('/login');
  }, []);
  return null;
};

const appConfig: IAppConfig = {
  app: {
    getInitialData: async () => {
      // 获取权限数据
      const data = await request('/api/auth');
      return {
        auth: {
          // 表明用户具有 admin 权限
          admin: true,
        }
      };
    }
  },
  auth: {
    NoAuthFallback: <NoAuth />
  }
};

createApp(appConfig);
这样会导致没权限就会调到登录，对用户非常不友好

**Comment by strongyc** [comment]
getInitialData: async (ctx) => {
      const { username, count } = await request.get('/api/data');
      return {
        // initialStates 是约定好的字段，会透传给 store 的初始状态
        initialStates: {
          user: { name: username },
          counter: { count }
        }
      }
还没登录他就已经执行了，连token都没有是无法请求成功的呀，大佬是如何解决的？

**Comment by usercao** [comment]
先判断下没token直接 return `无权限角色`，有token再执行这套逻辑

**Comment by strongyc** [comment]
文档中没有主动调用该方法，有token如何主动去调用呢？大佬怎么用的呀

**Comment by imsobear** [comment]
getInitialData 内部判断是否登录：

- 如果没登录，跳转到登录页面，登录成功后刷新页面
- 如果已登录，拉取权限数据，进入正常渲染逻辑

这样有什么问题么？

**Comment by strongyc** [comment]
import { runApp, IAppConfig, request, history, config, APP_MODE } from 'ice';
import { useEffect } from 'react';
import { isEmpty } from 'lodash';

console.log('config.baseURL', config.baseURL);
console.log('APP_MODE', APP_MODE);
const NoAuth = () => {
  useEffect(() => {
    history?.push('/login');
  }, []);
  return null;
};
const token = `${localStorage.getItem('token')}`;
// console.log('token----', token);
const appConfig: IAppConfig = {
  app: {
    rootId: 'ice-container',
    getInitialData: async () => {
      // 获取权限数据
      console.log('token-----------', token);
      if (token == null) {
        console.log('进入了----token');
        return undefined;
      } else {
        const res = await request('/api/getLoginUser');
        console.log('获取到的权限-----', res);
        if (res.success) {
          return {
            auth: {
              // 表明用户具有 admin 权限
              admin: true,
            },

          };
        } else {
          // alert('清先登录');
          history?.push('/login');
          return null;
        }
      }
    },
    auth: {
      NoAuthFallback: <NoAuth />,
    },
    request: {
    // 可选的，全局设置 request 是否返回 response 对象，默认为 false
      withFullResponse: false,
      baseURL: '/api',
      headers: {},
      // ...RequestConfig 其他参数

      // 拦截器
      interceptors: {
        request: {
          onConfig: (config) => {
            const authHeader = { Authorization: `Bearer ${token}` };
            // 发送请求前：可以对 RequestConfig 做一些统一处理
            config.headers = authHeader;
            return config;
          },
          onError: (error) => {
            return Promise.reject(error);
          },
        },
        response: {
          onConfig: (response) => {
          // 请求成功：可以做全局的 toast 展示，或者对 response 做一些格式化
            if (response?.data?.status !== 200) {
              alert('请求失败');
            }
            return response;
          },
          onError: (error) => {
          // 请求出错：服务端返回错误状态码
            console.log(error?.response?.data);
            console.log(error?.response?.status);
            console.log(error?.response?.headers);
            return Promise.reject(error);
          },
        },
      },
    },
  } };

runApp(appConfig);

app..tsx只会在运行时执行一次，登录成功后不会再次执行  getInitialData，怎么调用去执行呢，怎么去刷新权限呢，大佬

**Comment by strongyc** [comment]
是否应该像umi一样，用户id发生变化，主动调用 getInitialData，这样可以解决不

**Comment by imsobear** [comment]
我的建议是登录成功直接做一次页面刷新，因为登录本身就要涉及很多状态的重置，刷新应该是比较正常的操作。

**Comment by strongyc** [comment]
大佬，request是否支持定义返回类型，比如这样export async function currentUser(options?: { [key: string]: any }) {
  return request<API.CurrentUser>('/api/getLoginUser', {
    method: 'GET',
    ...(options || {}),
  });
}****
你是怎么定义返回的ts的呀

**Comment by imsobear** [comment]
一个 issue 解决一个问题，有其他问题建议单独再开 issue。

**Comment by strongyc** [comment]
好的

**Comment by strongyc** [comment]
刷新确实可以解决，谢谢大佬

**Comment by strongyc** [comment]
刷新可以解决，但是用户体验不好，页面会强制闪一次，期待有更好的解决方案

**Comment by imsobear** [comment]
> 刷新可以解决，但是用户体验不好，页面会强制闪一次，期待有更好的解决方案

你们一般情况下登录成功后不刷新页面么？

**Comment by strongyc** [comment]
不刷新啊，antd pro 就不用刷新，最好就是提供setInitvalues，或者监听用户id变化重新拉取一次用户权限，这样就避免了页面刷新一直发请求去拉权限，监听用户id变化就只用拉一次，个人觉得用户体验更好。

**Comment by usercao** [comment]
> 你们一般情况下登录成功后不刷新页面么？

一般登录后都不会刷新页面，SPA感觉就应该只加载一次，我觉得主要问题是appConfig里面没法写hooks，我开始试过用全局数据来管理这个的，发现没法写hooks就很麻烦

**Comment by strongyc** [comment]
有的用户他就喜欢按F5或者点浏览器的刷新

**Comment by usercao** [comment]
因为`appConfig`下面的配置项没法写任何hooks，现在我是用sessionStorage来同步一些加载前必要的数据的，然后再监听sessionStorage再注入到[Recoil](https://recoiljs.org/) store里面

**Comment by strongyc** [comment]
> 因为`appConfig`下面的配置项没法写任何hooks，现在我是用sessionStorage来同步一些加载前必要的数据的，然后再监听sessionStorage再注入到[Recoil](https://recoiljs.org/) store里面

这样太麻烦了，感觉借用umi的思想就比较好

**Comment by usercao** [comment]
> > 因为`appConfig`下面的配置项没法写任何hooks，现在我是用sessionStorage来同步一些加载前必要的数据的，然后再监听sessionStorage再注入到[Recoil](https://recoiljs.org/) store里面
> 
> 这样太麻烦了，感觉借用umi的思想就比较好

没办法现在ice不支持只能先这样搞了，能写hooks一切都好说，你那个问题也能直接全局数据来控制

**Comment by strongyc** [comment]
> > > 因为`appConfig`下面的配置项没法写任何hooks，现在我是用sessionStorage来同步一些加载前必要的数据的，然后再监听sessionStorage再注入到[Recoil](https://recoiljs.org/) store里面
> > 
> > 
> > 这样太麻烦了，感觉借用umi的思想就比较好
> 
> 没办法现在ice不支持只能先这样搞了，能写hooks一切都好说，你那个问题也能直接全局数据来控制
嗯嗯，但是全局数据感觉又丢失了ice提供的权限管理能力，总的来说，出一个新的方案比较好，强制刷新用户体验非常不好

**Comment by usercao** [comment]
> > > > 因为`appConfig`下面的配置项没法写任何hooks，现在我是用sessionStorage来同步一些加载前必要的数据的，然后再监听sessionStorage再注入到[Recoil](https://recoiljs.org/) store里面
> > > 
> > > 
> > > 这样太麻烦了，感觉借用umi的思想就比较好
> > 
> > 
> > 没办法现在ice不支持只能先这样搞了，能写hooks一切都好说，你那个问题也能直接全局数据来控制
> > 嗯嗯，但是全局数据感觉又丢失了ice提供的权限管理能力，总的来说，出一个新的方案比较好，强制刷新用户体验非常不好

其实全局数据没问题啊，我全局数据只是想覆写return的这堆权限配置而已，权限管理还是用ice的这一套，只是不用刷新页面和保存userinfo等数据方便点

**Comment by strongyc** [comment]
这个isse应该还不用关闭，可以在看看其他人有没有好的想法或解决方案

**Comment by imsobear** [comment]
initialData 更新是可以考虑支持的，弄成一个 React.Context 就好了，比较麻烦的问题是非 UI 组件里消费 initialData 是无法响应到数据更新的，这块需要看下怎么约束。

**Comment by imsobear** [comment]
@strongyc 话说你现在需要异步更新的是 initialData 的哪部分数据？如果是权限数据的话我们有提供 setAuth 的 API

**Comment by usercao** [comment]
> @strongyc 话说你现在需要异步更新的是 initialData 的哪部分数据？如果是权限数据的话我们有提供 setAuth 的 API

项目基础配置数据，想拉到接口数据后hooks到[Recoil](https://recoiljs.org/)里面

**Comment by imsobear** [comment]
> > @strongyc 话说你现在需要异步更新的是 initialData 的哪部分数据？如果是权限数据的话我们有提供 setAuth 的 API
> 
> 项目基础配置数据，想拉到接口数据后hooks到[Recoil](https://recoiljs.org/)里面

通过 addProvider 包裹一个 initialData 的 Provider，Provider 里面提供 `const [initialData, setInitialData] = useInitialData()` 能力，这样是不是就可以了？我们的 auth 插件就是这样做的。

**Comment by usercao** [comment]
👍我试试

**Comment by strongyc** [comment]
iniitData主要就是用户的数据，比如用户名组织之类的，权限有setAuth 的 Api应该可以解决的，我也试一试

**Comment by strongyc** [comment]
按照ice的文档，目前这样可行，用户登录成功拿到token后（因权限数据需要token，登录成功token保存到本地），在调用查询用户初始化数据和权限数据，用户初始化数据保存到全局state，权限数据调用 setAuth 的 API刷新权限。

**Comment by usercao** [comment]
@strongyc 试试[Recoil](https://recoiljs.org/)用起来爽飞了

**Comment by strongyc** [comment]
好的，我试一下

**Comment by lhb2631225005** [comment]
getInitialData获取用户权限这些对服务端来说都是相对耗时的   这个没有请求结束  页面是不会渲染的   想要做一些加载的loading都做不了
想知道有没有啥好的办法
