### ISSUE TITLE
build.config.js中报错

### ISSUE THREAD

**Issue by kq1314** [alibaba/ice#5274]
<img width="712" alt="image" src="https://user-images.githubusercontent.com/24579143/162685048-b31966a8-576c-4d76-8831-a6d4ab815728.png">
<img width="388" alt="image" src="https://user-images.githubusercontent.com/24579143/162685105-7898eae1-37e0-442b-9e7f-7ad7002d2cc4.png">
<img width="1348" alt="image" src="https://user-images.githubusercontent.com/24579143/162685174-179a8bf1-18a6-4857-848e-17a190e3aa06.png">

**Comment by kq1314** [comment]
icejs版本为"ice.js": "^1.0.0"

**Comment by usercao** [comment]
升级 `^2.0.0` 版本后再试试

**Comment by ClarkXia** [comment]
1.x 支持解析 js 配置，推荐升级到 2.x
