### ISSUE TITLE
less 无法忽略对url的处理

### ISSUE THREAD

**Issue by gooddaddy** [alibaba/ice#5283]
![lALPGRAzniUApF_NAcnNBH8_1151_457](https://user-images.githubusercontent.com/14076373/163370788-1f97239b-96e0-4672-8966-51c99d87fb5d.png)

## What is the expected behavior? 期望的结果是什么？
期望可以忽略掉针对url的处理，因为我希望绝对路径的 在运行时会在public里面找
## Any additional comments? 相关环境信息？

- **ice.js Version**：2.6.2
- **build.json Configuration**：
- **Node Version**: v16.14.2
- **Platform**: web

**Comment by gooddaddy** [comment]
找到个其他方法：
```    
config.module
      .rule('less-module')
      .use('css-loader')
      .tap(_options => {
        return {
          ..._options,
          url: (url) => {
            console.log('url:', url)
            if (url.startsWith('/')) {
              return false
            }

            return true
          },
        }
      })
```

**Comment by ClarkXia** [comment]
这个应该要配合 commonjsMagicComments 启用 https://webpack.docschina.org/configuration/module/#moduleparserjavascriptcommonjsmagiccomments

**Comment by gooddaddy** [comment]
> 这个应该要配合 [commonjsMagicComments](https://webpack.docschina.org/configuration/module/#moduleparserjavascriptcommonjsmagiccomments) 启用

你这个是针对 js来设置的吧，我这里希望 要针对less 文件的url 魔法注释哦

**Comment by ClarkXia** [comment]
目前通过 `.css` 文件可以正常使用 `webpackIgnore` 能力，需要排除 less-loader 对于该注释是否特殊化处理
