### ISSUE TITLE
子应用间来回跳转报错（第一次跳转正常），报export mount/unmount or register registerAppEnter/registerAppLeaver....

### ISSUE THREAD

**Issue by wenqizou** [alibaba/ice#5284]
## What is the current behavior? 发生了什么？
主应用React , 微应用Vue-A,Vue-B，A 调用appHistory API 跳转B成功，但是B 应用调用appHistory 跳转回A失败。报如题错误，后面虽然通过window.localtion.href 去处理可以，但是页面会刷新肯定效果不好

## Any additional comments? 相关环境信息？

- **ice.js Version**：2.0
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by maoxiaoke** [comment]
@wenqizou 用的是哪个模板，@ice/stark 似乎也是低版本的？

**Comment by wenqizou** [comment]
内部系统，无法提供代码，@ice/stark 是1.4.2
import appHistory from '@ice/stark-app/lib/appHistory' 
appHistory.push('xxx')

**Comment by wenqizou** [comment]
![image](https://user-images.githubusercontent.com/23254439/163806366-24a8793b-66b4-42a0-b1bb-a66d19d1c0e2.png)

**Comment by wenqizou** [comment]
接入子应用是采用官网的方式....有没有哪些点可以提醒我去确认的。。

**Comment by haiqding** [comment]
下面为问题的代码：

**Comment by wenqizou** [comment]
![1650443368(1)](https://user-images.githubusercontent.com/23254439/164185697-a628e145-e864-489b-8be9-33d103f120a9.png)
![image](https://user-images.githubusercontent.com/23254439/164185747-1bbe57a2-ea05-4056-8858-f1c439e58c14.png)

**Comment by imsobear** [comment]
@wenqizou @haiqding 可否想办法提供一个重现 demo，把代码提交到 GitHub 上

**Comment by maoxiaoke** [comment]
@wenqizou 你们这个版本有点低呀
