### ISSUE TITLE
在项目文件夹名字中含有(1)这种类型的数据的时候，报错

### ISSUE THREAD

**Issue by ajieying** [alibaba/ice#5285]
报错如下图：
<img width="890" alt="image" src="https://user-images.githubusercontent.com/9877509/163750891-0025ccca-9dfd-4ddb-b383-ce66ba13c6a1.png">

当去掉文件夹名字中的(1)类型的名字的时候，就能正常编译成功

**Comment by ClarkXia** [comment]
Fixed in ice.js@2.6.4
