### ISSUE TITLE
ice应用引用的组件中有scss导致无法运行

### ISSUE THREAD

**Issue by by-passed** [alibaba/ice#5286]
![image](https://user-images.githubusercontent.com/85748129/163751709-e889146f-a767-4b9a-9b40-9027bf38cdfb.png)

在def上创建了一个ice应用，在应用的tsx代码中import了一个npm组件，然后页面就报编译错误，看起来和子组件的lib代码打包成scss有关

#  assets应用
https://assets.def.alibaba-inc.com/iteration/1668468/basic#env=daily

**Comment by ClarkXia** [comment]
内部问题走答疑  初步判断是 vite 模式下不支持 require 的语法
