### ISSUE TITLE
basic-vite示例中的.env变量无法在index.html中使用

### ISSUE THREAD

**Issue by conorzhong** [alibaba/ice#5287]
## What is the current behavior? 发生了什么？
basic-vite示例中的.env变量无法在index.html中使用
```
VITE_STR=vite
ICE_STR=ice
DB=test
```
```html
<div>current env: <%= NODE_ENV %></div>
<div>current env: <%= VITE_STR %></div>
<div id="ice-container"></div>
```
<img width="258" alt="image" src="https://user-images.githubusercontent.com/39456642/163764117-2306bf56-0016-48a6-aaad-a0a3e22300ef.png">

## What is the expected behavior? 期望的结果是什么？
vite支持自定义变量的<%=...%>
## Any additional comments? 相关环境信息？
- **ice.js Version**：2.6.3
- **build.json Configuration**：
- **Node Version**: 14.18.2
- **Platform**: macOS Big Sur

**Comment by ClarkXia** [comment]
在 ice 框架下默认注入到 client 端的参数前缀为 `ICE_`，通过如下方式输出即可
```html
<div>current env: <%= NODE_ENV %></div>
<div>html parse: <%= ICE_STR %></div>
```
