### ISSUE TITLE
Browserslist: caniuse-lite is outdated.

### ISSUE THREAD

**Issue by usercao** [alibaba/ice#5288]
<img width="733" alt="image" src="https://user-images.githubusercontent.com/13760476/163775100-af12acdc-0477-4828-b3ce-ef649cbfa0b6.png">

本地运行`npx browserslist@latest --update-db`没有效果，推测是否ice需要更新？

**Comment by ClarkXia** [comment]
Fixed in ice.js@2.6.4

**Comment by usercao** [comment]
@ClarkXia `2.6.7`再次报警该问题

**Comment by usercao** [comment]
@ClarkXia 下个版本有预发布时间吗？

**Comment by usercao** [comment]
@luhc228 下个版本有预计发布时间吗？
