### ISSUE TITLE
React Router layout 配置导致 menu 切换，layout 会进行刷新的问题

### ISSUE THREAD

**Issue by yujiangshui** [alibaba/ice#529]
会导致部分情况下 openkeys 出现问题，以及全局信息如果通过 ajax 请求，每次切换页面都会请求一次的问题。

**Comment by yujiangshui** [comment]
切换命中路由之后，整个 layout 会进行冲渲染。

**Comment by noyobo** [comment]
没有问题，需要注意的在 Layout 里需要响应路由变化的就关联 `withRouter`

**Comment by guoxunbo** [comment]
我想知道这个怎么解决。每次都加载一下挺烦的。因为菜单这个东西一次加载就够了。
@chenbin92 我项目里没有看到router.js。只看到了router.jsx。是在这里改么还是在哪里？求助。
@noyobo @yujiangshui 大佬解决了么。求助

**Comment by guoxunbo** [comment]
因为我的菜单也是后台请求回来的。现在每次都会新请求一次。。。迷之尴尬。

**Comment by guoxunbo** [comment]
![image](https://user-images.githubusercontent.com/14329149/45097341-2a9bf300-b155-11e8-8606-b47f3ef00a9b.png)
是在这里改下？router.jsx。这里的layout如果有就不重新创建了？

**Comment by freedomzj** [comment]
问一下这个问题解决了吗？

**Comment by chenbin92** [comment]
新的路由方式解决了，参考 [router.jsx](https://github.com/alibaba/ice/blob/master/react-materials/scaffolds/ice-design-lite/src/router.jsx#L10)
