### ISSUE TITLE
build-plugin-fusion插件enableColorNames参数默认值建议改为true

### ISSUE THREAD

**Issue by JohnGao818** [alibaba/ice#5294]
## What is the current behavior? 发生了什么？
在通过build-plugin-fusion插件配置多主题动态切换时，因为其中一个主题有些色值变量设置为colorName，编译时被忽略，导致切换主题时该样式的颜色无法切换，后来发现这种情况需要配置enableColorNames为true，是否可以将此配置默认为true，或者在文档中特意标注一下。

![image](https://user-images.githubusercontent.com/50511900/164169853-27ecc31a-3870-4885-b0e8-3ec622d4f195.png)

## Any additional comments? 相关环境信息？

- **ice.js Version**：
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by ClarkXia** [comment]
enableColorNames 为新增逻辑，默认为 true 会有一定的风险
