### ISSUE TITLE
webpack模式下 less 文件热更新失效

### ISSUE THREAD

**Issue by cuiaiguanggh** [alibaba/ice#5297]
## Any additional comments? 相关环境信息？

- **ice.js Version**：2.6.3
- **build.json Configuration**：
- 
![image](https://user-images.githubusercontent.com/23047484/164454485-c1c7c965-ffd9-45bb-be45-cd57c542f8db.png)

export default {
  hash: true,
  plugins: [
    [
      'build-plugin-antd',
      {
        disableModularImport: true,
        themeConfig,
      },
    ],
  ],

  modeConfig: {
    vite: {
      vite: true,
      vitePlugins: [],
      outputDir: 'dist',
    },
    webpack: {
      outputDir: 'dist_webpack',
      devServer: { port: 8080 },
    },
  }
};
- **Node Version**:v16.14.2
- **Platform**:mac

**Comment by ClarkXia** [comment]
是以 css module 方式引入的场景下会出问题吗

**Comment by cuiaiguanggh** [comment]
> 是 css 模块的方式暴露的场景下会出问题吗

是的呢

**Comment by cuiaiguanggh** [comment]
> 是 css 模块的方式暴露问题吗？
我的结构是这样的
![image](https://user-images.githubusercontent.com/23047484/164464049-a86853b9-b791-4c15-8104-3933b2ed94c6.png)

**Comment by imsobear** [comment]
我试了下是可以的呀

**Comment by luhc228** [comment]
可以提供下 最小 demo

**Comment by cuiaiguanggh** [comment]
> 我试了下是可以的呀

设置hash：false 能解决，
![image](https://user-images.githubusercontent.com/23047484/164611273-cc53297e-36e1-4707-9b70-30d09989e5ec.png)

**Comment by imsobear** [comment]
建议初始化一个最简单的项目，然后一步一步看能不能复现，复现了可以把仓库提交到 GitHub。

**Comment by cuiaiguanggh** [comment]
> 建议初始化一个最简单的项目，然后一步一步看能不能复现，复现了可以把仓库提交到 GitHub。

好的呢 我稍后建一个，现阶段我正在公司项目试水，稍后提交简化的demo

**Comment by ClarkXia** [comment]
提供 demo 后重新开启
