### ISSUE TITLE
ice1.x 升级ice2.x遇到的问题

### ISSUE THREAD

**Issue by zhangZzz-Free** [alibaba/ice#5298]
![image](https://user-images.githubusercontent.com/74129548/164587885-e0ca0ef4-e1a3-498b-91ea-4d70b3fcce6f.png)
版本升级后，运行时，会进行报错

**Comment by ClarkXia** [comment]
能提供更加详细的错误 或者提供下复现 demo 吗

**Comment by zhangZzz-Free** [comment]
> 
项目因为是公司的，可能不太方便提供
但是我的操作流程可以说下：
  由于原本项目ice是1.16版本的，想提升到2.0，所以参考了官网进行版本升级，升级操作流程如下
  1 进入package.json 修改
  		"ice.js": "^2.0.0",
		"react": "^17.0.2",
    	        "react-dom": "^17.0.2",
    	        "@types/react": "^17.0.2",
                "@types/react-dom": "^17.0.2",
 2 依照官网，把状态管理也更改了下，然后运行 就报这个错误了
![image](https://user-images.githubusercontent.com/74129548/164604874-117a6e96-7478-41d5-8402-84dc74914ede.png)

**Comment by zhangZzz-Free** [comment]
![image](https://user-images.githubusercontent.com/74129548/164605490-ace4feb8-221d-42f8-b6a5-2ff6976d6bb3.png)

**Comment by zhangZzz-Free** [comment]
> 能提供更加详细的错误 或者提供下复现 demo 吗

之前有随手建一个 ice1.x的项目，按照官网提示进行升级，也是依旧报这个错，但是那个项目被我删了。。。

**Comment by ClarkXia** [comment]
看下 headerBackground.png 在代码里怎么使用的

**Comment by zhangZzz-Free** [comment]
> 看下 headerBackground.png 在代码里怎么使用的
项目是一个子应用，
![image](https://user-images.githubusercontent.com/74129548/164613492-32161736-51cd-4c19-a2b0-dc3484fd80f8.png)
，如果我在public中把这个png给删了，他就会报font里面的文件 is not cwd

**Comment by zhangZzz-Free** [comment]
> 看下 headerBackground.png 在代码里怎么使用的

只要public下有除了index.html以外的文件，都会报这个error

**Comment by ClarkXia** [comment]
> > 看下 headerBackground.png 在代码里怎么使用的
> 
> 只要public下有除了index.html以外的文件，都会报这个error

OK 我们复现修复下

**Comment by zhangZzz-Free** [comment]
> > > 看下 headerBackground.png 在代码里怎么使用的
> > 
> > 
> > 只要public下有除了index.html以外的文件，都会报这个error
> 
> OK 我们复现修复下

找到问题所在了，好像是路径中不能出现中文，我项目是放在桌面上的，我把它搬到其他位置，在运行，就可以了，不会报错了，但是为啥 我新建的2.x项目，即使放在桌面也不会报错，这个 1 升级 2 的就会报错

**Comment by ClarkXia** [comment]
提供下系统信息，路径报错关联 issue https://github.com/alibaba/ice/issues/5285

**Comment by zhangZzz-Free** [comment]
> 提供下系统信息，路径报错关联 issue #5285

系统 win10 家庭版
文件原路径 D:\桌面\bossoft\web-gpx-ocenter
文件修改后路径： D\Desktop\web-gpx-ocenter  运行正常

**Comment by zhangZzz-Free** [comment]
> 提供下系统信息，路径报错关联 issue #5285

您好，我还发现下一个问题，还是在1升2的时候，就是当前项目在本地 npm run build:dev , next组件样式有打包到index.css文件中，
但是，项目放到Jenkins 上面去构建，next组件样式丢失，我看打包分析的map文件，发现并没有引入next组件的样式，这是什么原因
![QQ截图20220424170944](https://user-images.githubusercontent.com/74129548/164969128-fdab82dd-86fe-4bfe-a07c-bcf8429e0130.png)
![QQ截图20220424170909](https://user-images.githubusercontent.com/74129548/164969137-87d8f871-1f0e-4253-ba9a-f5b8f79d3e1e.png)

**Comment by ClarkXia** [comment]
可以提供下使用 next 的最小复现 demo

**Comment by zhangZzz-Free** [comment]
> 可以提供下使用 next 的最小复现 demo

问题解决了，插件的问题 麻烦了

**Comment by zhangZzz-Free** [comment]
> 可以提供下使用 next 的最小复现 demo

不好意思，我又来问个小问题了。。。，就是 1升2的项目，我开启vite模式，会报错
![image](https://user-images.githubusercontent.com/74129548/165057129-0ed0719a-79a5-4535-a1b0-10ddfab883ad.png)
，然后我再build.json 中增加如下配置
![image](https://user-images.githubusercontent.com/74129548/165057226-b002780e-ee3f-42f2-ac85-301cbb7c8c99.png)
还是报一样的问题，是配错了吗

**Comment by zhangZzz-Free** [comment]
> > 可以提供下使用 next 的最小复现 demo
> 
> 不好意思，我又来问个小问题了。。。，就是 1升2的项目，我开启vite模式，
![image](https://user-images.githubusercontent.com/74129548/165065380-a6af9ccc-6634-4c54-aa7a-0cad7c60a771.png)
是 node的问题 还是什么其他的

**Comment by zhangZzz-Free** [comment]
> > > 可以提供下使用 next 的最小复现 demo
> > 
> > 
> > 不好意思，我又来问个小问题了。。。，就是 1升2的项目，我开启vite模式，
> > ![image](https://user-images.githubusercontent.com/74129548/165065380-a6af9ccc-6634-4c54-aa7a-0cad7c60a771.png)
> > 那个问题好像是 之前html中有使用 htmlwebpackplugin 中的变量导致的，改了之后，vite运行成功，但是运行打包的时候，插件报错了
![image](https://user-images.githubusercontent.com/74129548/165211426-ff0415b2-1ddc-4591-af97-91b273a7d499.png)
![image](https://user-images.githubusercontent.com/74129548/165211454-19d5b990-1070-4e74-9f27-0c68f889a7c8.png)

**Comment by ClarkXia** [comment]
提供下 build.json 的配置

**Comment by ClarkXia** [comment]
提供 demo 后重开 issue
