### ISSUE TITLE
support other ide

### ISSUE THREAD

**Issue by hvsy** [alibaba/ice#53]
webstorm
atom
or custom bin 
...

**Comment by yuanyan** [comment]
主流的 WebStorm 、Atom 我们会加进去，也会支持自定义

**Comment by noyobo** [comment]
软件打开目前不具备通用的流程，软件路径规则以及注册表等。 0.1.6 增加 webstorm 和 atom 。 

后续自定义的部分通过类似拖拽的方式打开。
