### ISSUE TITLE
Using SWC in build.json: unknown field `tsx`, expected one of `jsx` ..

### ISSUE THREAD

**Issue by skitsanos** [alibaba/ice#5302]
When you select `swc` as a builder, it can launch the app (`icejs start`) but it fails with building it:

`unknown field `tsx`, expected one of `jsx`,...`

More detailed:
```
ERR! Error: failed to deserialize as builder_swc::TransformOptions
ERR! JSON: {"jsc":{"parser":{"jsx":true,"dynamicImport":true,"functionBind":true,"exportDefaultFrom":true,"exportNamespaceFrom":true,"decorators":true,"syntax":"ecmascript","tsx":false},"target":"es2020","keepClassNames":true},"module":{"type":"es6","noInterop":false,"ignoreDynamic":true},"env":{"loose":true,"targets":"last 2 versions, Firefox ESR, > 1%, ie >= 9, iOS >= 8, Android >= 4","mode":"entry","coreJs":3},"sourceMaps":false,"filename":"/Projects/react/demo-icejs-boilerplate/src/app.js"}

```

If you look into https://swc.rs/docs/configuration/swcrc there is no such field as 'tsx' in config.

Here is `build.json` file:

```json
{
	"outputDir": "dist",
	"minify": false,
	"swc": {
		"sourceMaps": false,
		"jsc": {
			"target": "es2020",
			"keepClassNames": true,
			"parser": {
				"syntax": "ecmascript",
				"jsx": true
			}
		}
	},
	"customWebpack": true,
	"plugins": [
		[
			"build-plugin-ignore-style",
			{
				"libraryName": "antd"
			}
		]
	]
}
```

**Comment by SoloJiang** [comment]
I will try it for a moment

**Comment by SoloJiang** [comment]
It may be a bug, I will fix it.

**Comment by skitsanos** [comment]
Okay, so how do i fix this error? Anything i should add to my build.json so it would not put that tsx field?

**Comment by SoloJiang** [comment]
You need remove the `parser` options in `jsc` or not config `syntax` and `jsx` field

**Comment by skitsanos** [comment]
Okay, did that. Got 2 problems:

1. Routing doesn't work properly, it does not see `/pages/index.js` and falls back on `404.js'
2. `icejs build` fails on sealing 

You can see the whole thing here: https://github.com/skitsanos/wip-icejs-research

**Comment by ClarkXia** [comment]
If you are working on a new project, icejs prefer use `routes.ts` than file-system routing.

**Comment by ClarkXia** [comment]
ice.js support file-system routing for some simple usage, we will look into the problems if it is urgent needed

**Comment by skitsanos** [comment]
On a side note, I think translating the whole thing into English would do a great job for other developers and win some stars on GitHub, don't you think?

**Comment by ClarkXia** [comment]
😊 we've got a plan to improve experience of official document including English Docs in next major version.

**Comment by skitsanos** [comment]
Let me know if you need any help. I teach here how to use Ant.Design, ahooks and Umi.js, as well as a bunch of other things from Alibaba, so I can help with some docs on ice.js as well.

**Comment by ClarkXia** [comment]
We've working on a new document on [ a github branch](https://github.com/ice-lab/ice-next/tree/docs-rework), welcome to starring the project and show your ❤️ and support
