### ISSUE TITLE
webpack模式下打包 public下的js会被压缩

### ISSUE THREAD

**Issue by cuiaiguanggh** [alibaba/ice#5308]
## What is the current behavior? 发生了什么？
webpack模式下打包 public下的js会被压缩

![image](https://user-images.githubusercontent.com/23047484/165724925-45dd523f-ef47-427a-8bd5-cca91cd8e242.png)

## What is the expected behavior? 期望的结果是什么？
webpack模式下打包 public下的js不要被压缩
## Any additional comments? 相关环境信息？

- **ice.js Version**：2.6.2
- **build.json Configuration**：
- **Node Version**:16.14.2
- **Platform**:mac

**Comment by ClarkXia** [comment]
压缩上是 [copy-webpack-plugin](https://github.com/webpack-contrib/copy-webpack-plugin#info) 是的能力，对于 public 目录下的内容而言，的确不应该被压缩
