### ISSUE TITLE
图片base64编译能否自定义最小阈值

### ISSUE THREAD

**Issue by zhtx8090** [alibaba/ice#5312]
![image](https://user-images.githubusercontent.com/44771332/166889900-0222593a-49ae-4204-829a-0ddd1e9ce8ec.png)
目前资源小于8k会转成base64，能否开放最小阈值，让用户自定义设置

**Comment by ClarkXia** [comment]
这个配置并不常用，也并不推荐用户修改，如果真的有自定义需求可以参考[自定义](https://ice.work/docs/guide/basic/build#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%B7%A5%E7%A8%8B%E9%85%8D%E7%BD%AE)的方式修改


```js
module.exports = ({ context, onGetWebpackConfig }) => {
  onGetWebpackConfig((config) => {
   // type 可以为：woff2 / ttf / eot / svg / img
    config.module.rule(type)
    .set('parser', {
      dataUrlCondition: {
        maxSize: 8 * 1024 // 8kb
      }
    });
  });
};

```
