### ISSUE TITLE
刷新如何持久化state

### ISSUE THREAD

**Issue by strongyc** [alibaba/ice#5314]
刷新后页面所有的状态消失，在后台操作时，一刷新由于权限控制就跳回了登录，该如何持久化state

**Comment by usercao** [comment]
搜索一下`Redux LocalStorage 数据持久化` [Where to write to localStorage in a Redux app?](https://stackoverflow.com/questions/35305661/where-to-write-to-localstorage-in-a-redux-app)

**推荐使用 [Recoil](https://recoiljs.org/zh-hans/docs/introduction/getting-started/)**

**Comment by usercao** [comment]
请参考 [ice-test](https://github.com/usercao/ice-test/blob/main/src/models/account/index.ts#L3)，大部分常见业务场景都有

**Comment by strongyc** [comment]
感谢，学习学习

**Comment by luhc228** [comment]
页面刷新的话，可以考虑把数据存到 localStorage 中
