### ISSUE TITLE
history.block 回调参数丢失

### ISSUE THREAD

**Issue by Yelfive** [alibaba/ice#5317]
## What is the current behavior? 发生了什么？

根据 [remix-run/history](https://github.com/remix-run/history)，icejs 缺少 `retry` 方法

https://github.com/remix-run/history/blob/dev/docs/api-reference.md#historyblockblocker-blocker

```js
// To start blocking location changes...
let unblock = history.block(({ action, location, retry }) => {
  // A transition was blocked!
});

// Later, when you want to start allowing transitions again...
unblock();
```

## What is the expected behavior? 期望的结果是什么？

提供 `retry` 方法，否则无法阻止页面跳转

## Any additional comments? 相关环境信息？

- **ice.js Version**：2.0.0

**Comment by ClarkXia** [comment]
内置的 history 基于 react-router v5 版本，并不是最行版，这个需求我们统一在支持 react-router v6 中考虑 #4917
