### ISSUE TITLE
文档支持到组件源码的跳转

### ISSUE THREAD

**Issue by chenjun1011** [alibaba/ice#532]
如题

希望在官网的组件介绍页，能增加个按钮，快速跳转到组件对应的源码仓库

**Comment by wssgcg1213** [comment]
组件对外目前被阻塞的条件:
  - dev-tool 支持组件开发
  - 组件按照 devtool 格式进行修改, 去除 abc 等文件

目前组件源码已经在 biz_components 分支下

**Comment by wssgcg1213** [comment]
speed up
