### ISSUE TITLE
tnpm i ice.js 有 574M 大小，安装速度和更新速度很慢，有优化安装包大小计划吗

### ISSUE THREAD

**Issue by zwhu** [alibaba/ice#5323]
如下图通过 `$: tnpm i ice.js` 

![image](https://user-images.githubusercontent.com/2899806/167754922-720f86e5-8077-405d-8c61-9285d2920b3c.png)

通过 `$:du -sm node_modules` 查看 node_modules 大小，有 **574M** 

![image](https://user-images.githubusercontent.com/2899806/167755003-a7dd4ccd-a1aa-4102-b42d-a6a0f48ffce4.png)

操作系统如下：

![image](https://user-images.githubusercontent.com/2899806/167755173-90faa972-4b0c-4d64-b141-3071df1bd981.png)

作为对比 umi 的安装包有 **124M**

![image](https://user-images.githubusercontent.com/2899806/167755533-05411ab3-1fa2-45db-b769-bb3ecb0de78e.png)

**Comment by ClarkXia** [comment]
主要是 esbuild 和 swc 等应该按系统下载二进制包，目前看是下载了全系统的包，推荐先升级下包管理工具版本

**Comment by ClarkXia** [comment]
主要是二进制包带来的大小，后续将在 3.0 版本上进行的优化
