### ISSUE TITLE
状态管理 useEffect 问题

### ISSUE THREAD

**Issue by preedomly** [alibaba/ice#5324]
## What is the current behavior? 发生了什么？
Link 在执行重复url的时候，view的 useEffect 会重复加载一次，导致数据获取失败

Demo: https://github.com/preedomly/iceDemo

<img width="689" alt="image" src="https://user-images.githubusercontent.com/22881032/167801667-40677c8b-b0f9-44b6-8586-6220ba260120.png">

## What is the expected behavior? 
重复点击同一个页面的时候，数据不需要重复刷新

**Comment by luhc228** [comment]
Link 在执行重复url的时候 没理解

**Comment by ClarkXia** [comment]
根据现有 demo 无法复现，如果还是有问题 可以提供更加详细的复现步骤及日志
