### ISSUE TITLE
icejs 如何动态修改路由 modifyRoutes

### ISSUE THREAD

**Issue by Gallado** [alibaba/ice#5330]
## Any additional comments? 相关环境信息？

- **ice.js Version**：
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by Gallado** [comment]
搭配使用pageConfig 的 keep-alive 。初始化路由keepAlive = false。根据情况要把该路由下keepAlive置成true。

**Comment by ClarkXia** [comment]
那这个诉求是 pageConfig 的动态修改，跟 modifyRoutes 关系不大

**Comment by Gallado** [comment]
请问如何动态修改pageConfig下的配置，并重新加载路由，让修改的pageConfig配置生效

**Comment by ClarkXia** [comment]
目前 pageConfig 不支持动态修改均是以静态配置的方式提供，如果有动态诉求，对于 keep-alive 组件的渲染需要在组件内部控制

**Comment by ClarkXia** [comment]
目前 pageConfig 不支持动态修改均是以静态配置的方式提供，如果有动态诉求，对于 keep-alive 组件的渲染需要在组件内部以业务逻辑控制
