### ISSUE TITLE
pwa无效

### ISSUE THREAD

**Issue by caixianglin** [alibaba/ice#5336]
"pwa": {
    "sw": "weather-service-worker.js",
    "runTimeCaching": []
  }
配置了pwa，build的时候提升文件生成了，但是实际没有，被删除了
![image](https://user-images.githubusercontent.com/10279815/170493623-cb9e2cf1-5703-44ab-a89e-5d4189c0877f.png)
![image](https://user-images.githubusercontent.com/10279815/170493685-adde0ad1-be8c-4aa6-842a-efca71926e16.png)

**Comment by ClarkXia** [comment]
pwa 暂时无法配合 vite 进行工作

**Comment by caixianglin** [comment]
![image](https://user-images.githubusercontent.com/10279815/170624755-510975c5-3836-432f-a809-62d763552b5e.png)
去掉vite报错？

**Comment by caixianglin** [comment]
那webpack还得额外配置？错误信息也没有

**Comment by caixianglin** [comment]
弃坑了，换umi

**Comment by ClarkXia** [comment]
如果有问题可以提供下复现 demo

**Comment by ClarkXia** [comment]
提供 demo 后重开 issue
