### ISSUE TITLE
CodeSandBox复现无限重启(ice+fusion)

### ISSUE THREAD

**Issue by aspirantzhang** [alibaba/ice#5337]
## What is the current behavior? 发生了什么？
为了反馈ice问题，在CodeSandBox做复现，基于ice安装了fusion+ts的lite版，发现server无限重启，vite报错，无法正常使用。

https://codesandbox.io/s/github/aspirantzhang/icejs-fusion-typescript-sandbox

```
[vite] server connection lost. polling for restart... 
[vite] connecting... 
```
其中terminal正常，3333端口开启，浏览器短暂有正常显示
![image](https://user-images.githubusercontent.com/24559988/170650553-3aa604b9-4b2d-4ce4-8360-b22bb36ab98d.png)

但console显示vite无限重启，尝试关闭vite后依旧。
![image](https://user-images.githubusercontent.com/24559988/170650477-483d2461-35d0-4f96-b957-45b02b6b0300.png)

## What is the expected behavior? 期望的结果是什么？
正常使用，以便通过最小复现反馈问题。
CodeSandBox是制作复现最重要的途径，我没有找到好的复现模板，所以npx create自行安装了ice，并发布到 [github](https://github.com/aspirantzhang/icejs-fusion-typescript-sandbox) ，然后导入codesandbox，开启了terminal方便调试。确定原代码在本地Win10和Debian运行正常。

## Any additional comments? 相关环境信息？

- **ice.js Version**：
v2.6.4，使用最新版npx create ice命令创建
- **build.json Configuration**：
未改动
- **Node Version**:
指定node16
- **Platform**:
CodeSandBox

**Comment by ClarkXia** [comment]
表现上像 hmr 的服务一直无法链接，我们看下能否处理掉
