### ISSUE TITLE
高阶组件无法Route Props 中pgaeConfig

### ISSUE THREAD

**Issue by strongyc** [alibaba/ice#5339]
import React from 'react';
import { Redirect } from 'ice';

const AuthWrapper = (WrappedComponent) => {
  const AuthWrappedPage = (props) => {
    // const [auth, setAuth] = useAuth();
    const { location, history, searchParams, match, pageConfig } = props;
    // console.log('useauth---------', props);
    console.log('pagesCionfig-------------', pageConfig);
    // console.log('auth00000000000000', auth);
    const isLogin = true; // 替换成业务逻辑
    return <>{isLogin ? <WrappedComponent {...props} /> : <Redirect to="/login" />}</>;
  };
  return AuthWrappedPage;
};

export default AuthWrapper;
![image](https://user-images.githubusercontent.com/51156342/170828451-1d5b97ce-5b57-4b00-8491-cc8166e73081.png)

在高阶函数中，无法获取到props中的属性，在正常函数可以获取到，该如何在高阶函数中捕获？

**Comment by ClarkXia** [comment]
提供下 AuthWrapper 的使用方式

**Comment by strongyc** [comment]
![image](https://user-images.githubusercontent.com/51156342/170905812-cd72b02e-3df1-4386-b55b-bedfe2323440.png)
使用到路由鉴权

**Comment by ClarkXia** [comment]
目前没有直接通过 props 透传，而是直接读取了组件上的属性，后续版本我们将统一通过 hooks 方式获取

```js
const AuthWrapper = (Component) => {
  return (props) => {
    console.log('props ==>', props, Component.pageConfig);
    return <Component {...props} />;
  };
};
```
