### ISSUE TITLE
config 配置里的webpackPlugins不支持为插件传多个参数

### ISSUE THREAD

**Issue by lipten** [alibaba/ice#5340]
## What is the current behavior? 发生了什么？
config 配置里的webpackPlugins不支持为插件传多个参数

我想使用webpack的内置插件NormalModuleReplacementPlugin，它的用法如下：
```
new webpack.NormalModuleReplacementPlugin(
  /some\/path\/config\.development\.js/,
  './config.production.js'
);
```
需要传入两个参数，而webpackPlugins只支持传一个Options对象参数，从源码看得出use(plugin, [options]);只传了一个options参数
源码处：https://github.com/alibaba/ice/blob/3573652ae0535ebc64cd2ddec8bda03f8752c797/packages/build-user-config/src/userConfig/webpackPlugins.js#L24

## What is the expected behavior? 期望的结果是什么？
希望options支持数组传多个参数或者加多一个args字段作为多参数的用法形式
## Any additional comments? 相关环境信息？

- **ice.js Version**：2.5.1
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by ClarkXia** [comment]
webpack chain 具体调用的时候会解构 https://github.com/neutrinojs/webpack-chain/blob/da73fab944e5ba6e1e902a7e134709907c8bea50/src/Plugin.js#L14
自定义的时候直接 `config.plugin(pluginName).use(plugin, [options1, options2]);` 即可

**Comment by lipten** [comment]
@ClarkXia 我的问题是ice的配置文件里用webpack的内置插件不支持多参数，你说的自定义工程配置我可以用，但是要以npm包形式打包很不友好(不支持相对路径文件加载、不支持ts文件的包)，我想用这种方式ice配置：
```
 webpackPlugins: {
        'webpack.NormalModuleReplacementPlugin': [/some\/path\/config\.development\.js/,
  './config.production.js'],
 },
```

> webpack chain 具体调用的时候会解构 https://github.com/neutrinojs/webpack-chain/blob/da73fab944e5ba6e1e902a7e134709907c8bea50/src/Plugin.js#L14 自定义的时候直接 `config.plugin(pluginName).use(plugin, [options1, options2]);` 即可

**Comment by lipten** [comment]
@ClarkXia 我的问题描述里的源码是ice解析用户配置config文件里的webpackPlugins配置项的处理逻辑，里面的options只传了一个元素的数组 pluginRule = config.plugin(pluginName).use(plugin, [options]); 
所以我不管在配置里怎么传，ice解析配置文件的时候也只传了一个参数，你明白我的意思吗？
