### ISSUE TITLE
ice-scripts2.0修改 babel 配置 出现问题

### ISSUE THREAD

**Issue by buyingshi** [alibaba/ice#5341]
1. 添加如下配置后, 部分页面组件, 功能会受到影响, 加载不出来
['jsx'].forEach((rule) => {
      config.module
        .rule(rule)
        .use('babel-loader')
        .tap((options) => {
          // 添加一条 babel plugin，同理可添加 presets
          options.plugins.push(require.resolve('vuera/babel'));
          return options;
        });
    });

2. 我想要实现的是在 .babelrc 中添加如下配置
{
    "presets": ["react-app"],
    "plugins": [
        "vuera/babel"
    ]
}

3. 我的版本是"ice-scripts": "^2.1.16"

4. chainWebpack全部配置如下:
chainWebpack: (config, { command }) => {
    // 开发模式
    config.when(process.env.NODE_ENV === 'development', config => {
      config.set("devtool", "eval-source-map");
    });
    config.module
      .rule('new-rule')
      .test(/\.vue$/)
      .use('vue-loader')
      .loader('vue-loader');
    config
      // 定义插件名称
      .plugin('VueLoaderPlugin')
      // 第一项为具体插件，第二项为插件参数
      .use(VueLoaderPlugin, [[
        {
          libraryName: /@ali\/ice-.*/,
          stylePath: 'style.js',
        },
      ]]);

    ['jsx'].forEach((rule) => {
      config.module
        .rule(rule)
        .use('babel-loader')
        .tap((options) => {
          // 添加一条 babel plugin，同理可添加 presets
          options.plugins.push(require.resolve('vuera/babel'));
          return options;
        });
    });

  },

**Comment by ClarkXia** [comment]
可以先通过 config.toConfig() 确认好配置是否修改成功

**Comment by ClarkXia** [comment]
先通过上述方式确认配置正确，另外 ice-scripts 已停止维护推荐按照文档升级 https://ice.work/docs/guide/upgrade
