### ISSUE TITLE
Can't find package stackframe@^1.3.0

### ISSUE THREAD

**Issue by Jerryqun** [alibaba/ice#5343]
"ice.js": "^1.0.0"
    
     内网 tnpm i   报错
[build-plugin-fast-refresh@1.7.0 › @pmmmwh/react-refresh-webpack-plugin@0.3.3 › error-stack-parser@2.1.1 › stackframe@^1.3.0] Can't find package stackframe@^1.3.0

**Comment by CalmDownJ** [comment]
npm config set registry https://registry.npmmirror.com

**Comment by wssgcg1213** [comment]
上游 registry 有问题, 已经处理完毕了 https://github.com/cnpm/cnpm/issues/382
