### ISSUE TITLE
在Codespaces云编译构建失败

### ISSUE THREAD

**Issue by oneQiu** [alibaba/ice#5352]
git推出了Codespaces在线编辑功能，尝试性的使用了，但是在npm start的时候出错了
![image](https://user-images.githubusercontent.com/50658231/173265460-c84ae388-7f5a-4d27-b585-db94307c4044.png)

**Comment by ClarkXia** [comment]
这个是用来打开浏览器，如果是云端环境可以禁止默认打开 `icejs start --disable-open`

**Comment by oneQiu** [comment]
> --disable-open

可以了 感谢
