### ISSUE TITLE
vite 模式下，本地环境和生成环境的样式引用顺序不一致

### ISSUE THREAD

**Issue by destiny4** [alibaba/ice#5354]
## What is the current behavior? 发生了什么？
vite 模式下使用 antd+tailwindcss
在本地开发环境，组件的样式顺序是对的（tail 的样式覆盖了 antd 的样式），但是打包之后，组件的样式引用顺序就错了（antd 的样式覆盖了 tail 的样式），代码里面是先引用的 antd 的样式

## What is the expected behavior? 期望的结果是什么？

理论上来说，打包之后的样式，也应该是先引用 antd，再引用 tailwind，这样就会正确实现样式覆盖，但是我不知道打包做了什么处理，会导致样式引用顺序发生变化

## Any additional comments? 相关环境信息？

- **ice.js Version**：2.6.4
- **build.json Configuration**：{
  "vite": true,
  "hash": true,
  "minify": "esbuild",
  "plugins": [
    [
      "build-plugin-ignore-style",
      {
        "libraryName": "antd"
      }
    ]
  ]
}
- **Node Version**:
- **Platform**:

**Comment by ClarkXia** [comment]
能否提供一个复现 demo 供排查
