### ISSUE TITLE
[QUESTION]如何解决微前端使用unocss/tailwindcss的CSS循序问题？

### ISSUE THREAD

**Issue by xmsz** [alibaba/ice#5357]
背景
父应用
```
<div className='w-1 md:w-2'/>
```

子应用
```
<div className='w-1'/>
```

那么最后父应用的样式只会是w-1，因为子应用的加载顺序在父应用后面，且子应用里也没有md:w-2，
<img width="399" alt="image" src="https://user-images.githubusercontent.com/5879146/173764192-caa9fecf-019a-4406-b99f-5180a18a8426.png">

需求
这种情况要怎么解决

**Comment by ClarkXia** [comment]
推荐应用上选择 css modules 这样可以较大程度上避免样式污染，如果改造成本比较大可以参考下 issue
https://github.com/ice-lab/icestark/issues/413
