### ISSUE TITLE
路由懒加载有一个无法命名的bundle

### ISSUE THREAD

**Issue by 213de513** [alibaba/ice#5358]
## What is the current behavior? 发生了什么？
 我们路由懒加载 把所有路由都命名为一个chunkname 但是还是打出来一个看起来都是依赖的 未命名(一个数字)的bundle 这个有办法规避或者给它命名吗
![image](https://user-images.githubusercontent.com/29298644/173775259-b7563516-24e9-4d27-b537-1d9b2c17b9a5.png)

## What is the expected behavior? 期望的结果是什么？
可以给其固定命名

**Comment by ClarkXia** [comment]
内部走答疑，不要将内部截图在外部 issue 提问
