### ISSUE TITLE
vite模式下配置postcssOptions 运行报错

### ISSUE THREAD

**Issue by CL-nevins** [alibaba/ice#5359]
## What is the current behavior? 发生了什么？

我想在ice vite模式里开启`postcss nested`，使用`npm init ice <project-name>`创建项目，模板选择为`TypeScript + FuSion Design`，安装完依赖后，我参照官方配置文档，尝试在`build.json`里，添加`postcssOptions`配置：

```diff
{
  "vite": true,
  "plugins": [
    [
      "build-plugin-moment-locales",
      {
        "locales": ["zh-cn"]
      }
    ],
    [
      "build-plugin-ignore-style",
      {
        "libraryName": "@alifd/next"
      }
    ]
  ],
+ "postcssOptions": {
+ "plugins": {
+      "postcss-preset-env": {
+        "browsers": ["last 2 versions"]
+    },
+    "postcss-import": false,
+    "postcss-short": { "prefix": "x" }
+  },
+  "syntax": "sugarss",
+   "parser": "sugarss",
+ "stringifier": "sugarss"
+ }
}

```

运行`npm start`后，提示:

```md
ERR! CONFIG Failed to get config.
ERR! Cannot find module 'postcss-preset-env'
```

这是什么情况，`postcss-preset-env`不是内置了吗？ 我将`postcss-preset-env`换成`postcss-nested`也是一样，提示未找到模块；

## What is the expected behavior? 期望的结果是什么？

- 为什么会报这个错误
- 我在postcssOptions中配置 postcss-nested 的写法是否正确:

```diff
{
  "vite": true,
  "plugins": [
    [
      "build-plugin-moment-locales",
      {
        "locales": ["zh-cn"]
      }
    ],
    [
      "build-plugin-ignore-style",
      {
        "libraryName": "@alifd/next"
      }
    ]
  ],
+ "postcssOptions": {
+   "plugins": {
+    "postcss-nested": true
+  }
+ }
}

```

## Any additional comments? 相关环境信息？

- **ice.js Version**：2.0.0
- **build.json Configuration**：上面已贴出
- **Node Version**:v16.13.1
- **Platform**: win10 vscode IDE

**Comment by ClarkXia** [comment]
vite 模式下默认没有内置任何 plugins，至于 postcss-preset-env require 不到是因为内置的 postcss 相关插件都已经经过预打包

**Comment by CL-nevins** [comment]
了解了，安装了`postcss-nested`后设置生效了，谢谢
