### ISSUE TITLE
新建项目警告报错

### ISSUE THREAD

**Issue by strongyc** [alibaba/ice#5360]
:10 [vite] warning: Top-level "this" will be replaced with undefined since this file is an ECMAScript module
5  |
6  |  const Guide = () => {
7  |    return <div className={styles.container} __self={this} __source={{
   |                                                     ^
8  |      fileName: _jsxFileName,
9  |      lineNumber: 6,

**Comment by ClarkXia** [comment]
简单的 demo  `@alifd/scaffold-simple` 无法复现你的问题，看下具体是那个 demo 会报错
