### ISSUE TITLE
切换build.json 为build.json.ts启动报错

### ISSUE THREAD

**Issue by strongyc** [alibaba/ice#5362]
切换build.json 为build.json.ts启动报错
![image](https://user-images.githubusercontent.com/51156342/174240899-67d3dfeb-f74f-4d07-80dd-ced8505235e2.png)

实际报错
import vitePluginForArco from '@arco-plugins/vite-react';

export default {
  vite: true,
  vitePlugins: [vitePluginForArco()],
};
ice.js 2.6.4
ERR! CONFIG config file(undefined) is not exist
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS D:\ICEProject\naqu-frontend> yarn start
yarn run v1.22.19
warning ..\..\package.json: No license field
$ icejs start
ice.js 2.6.4
ERR! CONFIG config file(undefined) is not exist
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by ClarkXia** [comment]
文件名为 `build.config.ts`

**Comment by strongyc** [comment]
收到，文档看错，感谢
