### ISSUE TITLE
ssr render 为什么依赖的json 是要传本地路径

### ISSUE THREAD

**Issue by h615861768** [alibaba/ice#5363]
ssr render 为什么依赖的json 有传本地路径, 这样的限制

在做远程配置ssr 版本的话, 每次都得在server里面写入新的文件. 

----------新
刚刚发现 loadable.json 模块被缓存了. 

每次写入到服务端硬盘的loadable.json得加个时间戳 传入使用才行.

**Comment by luhc228** [comment]
实现上我们依赖了 [@loadable/component](https://loadable-components.com/docs/server-side-rendering/)，它并不支持传 webpack stats 的配置，仅支持传路径。

你的问题是不是可以考虑设置缓存时间？

**Comment by h615861768** [comment]
> 

好的, 了解了, 我这边是通过每次json文件名加时间戳解决的.
