### ISSUE TITLE
vite 模式如何删除路由路径上的#？

### ISSUE THREAD

**Issue by strongyc** [alibaba/ice#5365]
已在app.tsx中配置
   router: {
      type: 'browser',
      basename: '/',
      fallback: <Spin dot />,
      modifyRoutes: (routes) => {
        return routes;
      },
但显示的还是有#

**Comment by ClarkXia** [comment]
配置 router.type = 'browser'  后，可以正常使用 browser 路由

**Comment by strongyc** [comment]
![image](https://user-images.githubusercontent.com/51156342/174794330-bceb90df-9fb6-4793-9c62-9459c2d6aa9a.png)
![image](https://user-images.githubusercontent.com/51156342/174794370-63297362-6631-4784-9c77-66305e207936.png)
本地环境，配置了browser，但还是有#

**Comment by strongyc** [comment]
你好，增加了没作用
![image](https://user-images.githubusercontent.com/51156342/174948139-18395af3-eda4-4f43-ad4e-4556017f8b02.png)
![image](https://user-images.githubusercontent.com/51156342/174948156-d4726f9c-51eb-4b6a-888e-1d282cb0851a.png)

**Comment by usercao** [comment]
传个demo上来看看

**Comment by strongyc** [comment]
[test-antd.zip](https://github.com/alibaba/ice/files/8954765/test-antd.zip)

**Comment by strongyc** [comment]
你好，我删除node_modules重新安装就可以啦，顺便问一下，antd 动态主题不生效是什么原因呢

**Comment by usercao** [comment]
<img width="234" alt="image" src="https://user-images.githubusercontent.com/13760476/174960883-9b63861e-4911-4b82-b3a6-294d8697987c.png">

我这里测试没问题，你重新`yarn install`试试

**Comment by usercao** [comment]
<img width="223" alt="image" src="https://user-images.githubusercontent.com/13760476/174964062-1714e8dc-c59a-4acd-8e00-8d2e0e0b195f.png">

```json
"themeConfig": {
    "primary-color": "#f40"
}
```

定制主题看了也没有问题，动态主题没试

**Comment by strongyc** [comment]
你好，定制主题可以的，动态主题不行，方便看一下是什么原因吗？

**Comment by ClarkXia** [comment]
> 你好，定制主题可以的，动态主题不行，方便看一下是什么原因吗？

动态定制需要自己开发 切换样式逻辑，目前官方支持了基于 sass 的动态主题，可以参考 https://ice.work/docs/plugin/list/fusion/

**Comment by ClarkXia** [comment]
> 这个是什么原因呢，我重新建一个项目，配置如上#又出来了，我删除了node_modules也一样，这是我电脑配置的原因吗？时好时坏？

提供完整的操作路径 不然无法根据你的描述复现

**Comment by strongyc** [comment]
你好，是我配置的问题，已解决
