### ISSUE TITLE
vite打包@antv/data-set可以，但是因为内涵dagre里有require，页面无法渲染

### ISSUE THREAD

**Issue by owendswang** [alibaba/ice#5366]
## What is the current behavior? 发生了什么？

前端用到了@antv/data-set里的tag-cloud生成，但是里面用到的dagre包里有require引用，平时开发的时候可以，但是build之后就不行了，console里显示graphlib_1 is undefined。
关掉minify，仔细查看打包出来的js文件，发现这个变量用了require来定义，所以定义不生效。

## What is the expected behavior? 期望的结果是什么？

我知道这个应该属于是@antv/data-set的问题，但是我搜了解决办法，是在vite打包配置里添加如下选项：
```
build: {
  commonjsOptions: {
    ignoreTryCatch: false,
  },
},
```
但是我在飞冰的文档里找不到配置这个选项的方法。

## Any additional comments? 相关环境信息？

- **ice.js Version**：2.6.4
- **build.json Configuration**：
```
{
  "vite": true,
  "minify": false,
  "plugins": [
    [
      "build-plugin-ignore-style",
      {
        "libraryName": "antd"
      }
    ], [
      "build-plugin-css-assets-local",
      {
        "outputPath": "assets",
        "relativeCssPath": "../"
      }
    ], [
      "build-plugin-antd",
      {
        "disableModularImport": true,
        "themeConfig": {
          "primary-color": "@blue-base"
        }
      }
    ]
  ],
  "proxy": {
    "/api": {
      "enable": true,
      "target": "http://127.0.0.1:3000"
    },
    "/uploads": {
      "enable": true,
      "target": "http://127.0.0.1:3000"
    }
  }
}
```
- **Node Version**: 16.15.1
- **Platform**: Ubuntu 20.04 x64

**Comment by ClarkXia** [comment]
vite 推荐使用标准的 esm 包，如果混用 esm 和 cjs 就会导致报错

**Comment by owendswang** [comment]
> vite 推荐使用标准的 esm 包，如果混用 esm 和 cjs 就会导致报错

多谢百忙中回复。

但是ice的vite打包，是会转换require的，只是commonjs转换require时忽略了try catch里的require，所以导致报错。

vite的确不推荐cjs，但是@antv/data-set也是阿里家的啊…… 我就因为都是阿里的，所以用了bizcharts，bizcharts引用了data-set，可ice却不支持这个，有点难受……

并且vite本身支持commonjs配置选项，可ice却不支持配置。

**Comment by ClarkXia** [comment]
`@antv/data-set` 维护的团队不一样，一个方案是去 @antv/data-set 去提 issue，另外 ice 兼容所有 vite 配置项：

```js
export default {
  vite: {
    // 这里可以配置所有 vite 相关配置，最终会合并进去
  }
};
```

**Comment by owendswang** [comment]
> 

哇，能这样的话，那真是太好了，希望能写到doc里去。

**Comment by owendswang** [comment]
试了一下，的确好使！十分感谢！

build.config.ts文件内容如下：
```
export default {
  "vite": {
    "build": {
      "commonjsOptions": {
        "ignoreTryCatch": false,
      },
    },
  },
};
```
