### ISSUE TITLE
icejs 引入wasm模块，重新编译提示错误

### ISSUE THREAD

**Issue by appeathoul** [alibaba/ice#5367]
开启webpack5 新特性支持 wasm 模块导入
```
config.merge({
      experiments: {
        asyncWebAssembly: true,
      },
    });
```

wasm模块采用 rust模块 wasm-pack打包编译

在测试环境测试wasm包无问题，内部方法可以正确执行

在icejs项目中导入wasm
`import * as rust from '@/wasm/pkg';`

项目可以正确启动
但是刷新报错

报错如下信息

1. 报错 Module not found: Error: Can't resolve 'wbg'

2. 报错

<img width="816" alt="image" src="https://user-images.githubusercontent.com/6290739/174710105-ea5e25fa-b64e-48db-902b-33f9af85d1ca.png">

- **ice.js Version**: 2.6.4
- **build.json Configuration**：
- **Node Version**: v16.14.0
- **Platform**:macOS 12.4

**Comment by appeathoul** [comment]
解决了

**Comment by xmsz-stu** [comment]
怎么解决的？
