### ISSUE TITLE
has no exported member 'createStore

### ISSUE THREAD

**Issue by WuDuShanCheng** [alibaba/ice#5368]
import { createStore } from 'ice'; 找不到这个createStore
我查了一下以前的问题 说是要在src目录下 我这个是在src目录下的 可以看看原因吗
![image](https://user-images.githubusercontent.com/67892538/174935547-0a64dc68-04ea-4994-b2cb-bfb3be28ef58.png)

**Comment by FuzzyFade** [comment]
重启一下 IDE 或者重新 npm 启动一下项目

**Comment by WuDuShanCheng** [comment]
感谢 已解决
