### ISSUE TITLE
如果做一个权限管理相关的系统。左侧的菜单树应该怎样动态处理

### ISSUE THREAD

**Issue by ChinPangLung** [alibaba/ice#537]
后台返回用户的对应权限菜单信息。请问前端用iceworks可以做么？

**Comment by noyobo** [comment]
iceworks 主要做项目工程管理的。

权限管理这个是实际的业务代码， @chenbin92 最近在整理相关权限管理的方案。可以说下。

**Comment by chenbin92** [comment]
@ChinPangLung  这块计划在 6 月下旬支持  https://github.com/alibaba/ice/issues/403

权限方案可以先参考社区的实现 https://github.com/mjrussell/redux-auth-wrapper

**Comment by ChinPangLung** [comment]
好的，谢谢

**Comment by Zzy0706** [comment]
6月下旬正在逼近

**Comment by chenbin92** [comment]
@Zzy0706  代码实现基本完成，目前正在写文档，涉及的点比较多，时间上延后了一些，预计下周四会发包

**Comment by ChinPangLung** [comment]
今天周五，不知道发布了。关于这块的发布了没。如果发布了麻烦给个链接~谢谢

**Comment by chenbin92** [comment]
@ChinPangLung  相关 MR：  https://github.com/alibaba/ice/pull/700

**Comment by chenbin92** [comment]
@ChinPangLung  可以先通过 git clone 的方式使用，🈶问题可以钉钉联系我或者在 issue 反馈给我
