### ISSUE TITLE
'webpack-dashboard/plugin' 想要使用这个插件怎么办

### ISSUE THREAD

**Issue by WuDuShanCheng** [alibaba/ice#5377]
现在只能这样配置   然后数据出不来 应该要使用 webpack-dashboard/plugin 但是build.json里面不支持这样写
"webpackPlugins": {
    "webpack-bundle-analyzer": {},
    "webpack-dashboard": {}
  },

![image](https://user-images.githubusercontent.com/67892538/176090761-1e8a6da4-24c8-4f90-8b71-d73c06c12c2e.png)

**Comment by ClarkXia** [comment]
复杂逻辑走自定义工程配置 https://ice.work/docs/guide/basic/build/#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%B7%A5%E7%A8%8B%E9%85%8D%E7%BD%AE
