### ISSUE TITLE
ice的项目，引入自己写的业务组件库，样式丢失

### ISSUE THREAD

**Issue by 2678041235** [alibaba/ice#5380]
ice工程里引入我司自己业务组件库某一组件，该组件内按照css module模块化引入样式文件，样式文件名为index.less（不是xx.module.less形式），此时样式文件会显示不出来；
<img width="802" alt="屏幕快照 2022-06-29 17 55 43" src="https://user-images.githubusercontent.com/17005599/176408805-95ee92ed-76db-4873-92f8-7bff6337808c.png">

<img width="515" alt="屏幕快照 2022-06-29 17 50 22" src="https://user-images.githubusercontent.com/17005599/176408445-a34b37a6-5058-40aa-a8db-ec0bd70384f5.png">

查看源码，发现外部穿的modules没起作用，内部有自己的判断，我们样式文件名没匹配上导致css module一直没生效。

## What is the expected behavior? 期望的结果是什么？
如何针对性的对我们的业务组件库跳开xx.module.less的校验，而是直接匹配.less

## Any additional comments? 相关环境信息？

- **ice.js Version**：
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by ClarkXia** [comment]
`import style from './index.less';` 如果想支持这种形式，必须替换内置的 less 规则

**Comment by 2678041235** [comment]
您好，您的邮件我已收到，会尽快给您答复！

**Comment by ClarkXia** [comment]
是的 参考下 https://github.com/alibaba/ice/issues/3179 中的方式

**Comment by 2678041235** [comment]
您好，您的邮件我已收到，会尽快给您答复！
