### ISSUE TITLE
@iceworks/spec 规则更新

### ISSUE THREAD

**Issue by usercao** [alibaba/ice#5381]
<img width="779" alt="image" src="https://user-images.githubusercontent.com/13760476/176476469-5aa2bd07-03ef-4af4-890f-a4a9e2992296.png">

请更新官方规则，经常报Safari@9或者iOS@9的警告，实际上这两个设备已经非常老了

**Comment by usercao** [comment]
@ClarkXia 请问有预计更新时间吗？

**Comment by luhc228** [comment]
@usercao 内部场景下，有很多因为没有兼容 ios9 导致应用页面白屏，这规则还是会开着。建议您手动关掉规则
