### ISSUE TITLE
ice-store 路由跳转store初始化问题

### ISSUE THREAD

**Issue by 15893361787** [alibaba/ice#5382]
## What is the current behavior? 发生了什么？

路由跳转store状态重置，

https://user-images.githubusercontent.com/41234952/176577268-00d6da09-aaa5-4fb5-9c11-e326ae9b4875.mov

通过配置disableResetPageState仍然无效

## What is the expected behavior? 期望的结果是什么？
路由跳转状态保留，尤其是同路径路由跳转

## Any additional comments? 相关环境信息？

最新ice版本
## 复现demo
[ice-bug.zip](https://github.com/alibaba/ice/files/9015821/ice-bug.zip)

**Comment by ClarkXia** [comment]
非常高质量的 issue，我们尽快确认修复下

**Comment by 15893361787** [comment]
这块有大致的修复时间吗   近期需要用到该功能

**Comment by luhc228** [comment]
<img width="831" alt="image" src="https://user-images.githubusercontent.com/44047106/178920347-e4301973-ad54-479d-9aea-55098db5901b.png">

**Comment by shinyshine** [comment]
> <img alt="image" width="499" src="https://user-images.githubusercontent.com/44047106/178920791-00048f6f-b31b-480f-91d2-24843a9befae.png">
> 
> 在 build.json 中设置
确实是这样的，这样设计不知道是为什么，有高人指点下吗
