### ISSUE TITLE
vite模式下，日期组件会变成英文，webpack是正常的中文

### ISSUE THREAD

**Issue by is-cool** [alibaba/ice#5383]
## vite模式下，日期组件会变成英文，webpack是正常的中文

![截屏2022-06-30 10 30 51](https://user-images.githubusercontent.com/78067806/176580328-80836d91-f155-4b24-aea2-ff74878c563e.png)

## What is the expected behavior? 期望的结果是什么？
有什么解决的办法？

## Any additional comments? 相关环境信息？

- **ice.js Version**：2.0
- **build.json Configuration**：
- **Node Version**:14.16.0
- **Platform**:

**Comment by is-cool** [comment]
![截屏2022-06-30 10 35 42](https://user-images.githubusercontent.com/78067806/176580651-636bc130-c5bb-43ff-8adb-9ef0690f431a.png)

**Comment by ClarkXia** [comment]
提供下工程配置，语言是通过一个[插件](https://ice.work/docs/plugin/list/moment-locales) 实现的，可以确认下是否是最新版

**Comment by is-cool** [comment]
<img width="596" alt="截屏2022-06-30 11 04 55" src="https://user-images.githubusercontent.com/78067806/176584185-a4f0b701-2491-4586-8e4d-08e31d1d7242.png">
