### ISSUE TITLE
项目中js使用jsx语法报错的问题

### ISSUE THREAD

**Issue by jiushigo01** [alibaba/ice#5385]
## 在react项目中使用js文件写jsx的时候，报错了。

使用build.config.ts，引入了@babel/plugin-transform-react-jsx插件，但是不起作用

![image](https://user-images.githubusercontent.com/14155026/177238147-72812f70-570d-4336-b5f5-5d4f91bc418b.png)

![image](https://user-images.githubusercontent.com/14155026/177238218-663b0c47-c622-4b89-8021-002086f400c5.png)

![image](https://user-images.githubusercontent.com/14155026/177238265-84639cd3-c1b8-4156-b82d-8d4dbb22e5c5.png)

- **ice.js Version**：2.6.4
- **build.json Configuration**：
- **Node Version**: 16.15.1
- **Platform**: mac

**Comment by ClarkXia** [comment]
vite 模式下推荐 jsx 语法下写在 `.jsx` 文件中
