### ISSUE TITLE
子应用加载报错 only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by tushuang** [alibaba/ice#5388]
第一次能正常加载页面，切到别的页面，再回来就报这个错。
![image](https://user-images.githubusercontent.com/43326212/177489957-a6ee3379-a93f-44c4-b15c-741f0b773906.png)

**Comment by tushuang** [comment]
> babel-polyfill 怎么引入的，能够提供简单的复习 demo 吗

demo可能暂时提供不了 是在入口通过import引入的

**Comment by ClarkXia** [comment]
babel-polyfill 期望单实例，考虑通过在主应用统一引入解决
