### ISSUE TITLE
突然项目启动不了 想问问是不是飞冰的原因

### ISSUE THREAD

**Issue by WuDuShanCheng** [alibaba/ice#5390]
![image](https://user-images.githubusercontent.com/67892538/177665925-478b60ac-4ed6-4ec3-a8dc-82b820cf1d04.png)
这个是截图 我什么也没改啊 报错感觉也不是自己代码出现了问题

**Comment by WuDuShanCheng** [comment]
我现在吧项目还原成昨天晚上调试好的那种 也不行了

**Comment by WuDuShanCheng** [comment]
还原了几个版本了 全都不行 全都是这个错误

**Comment by WuDuShanCheng** [comment]
npm 了好多次的 现在挺着急的 可以帮忙看看吗

**Comment by WuDuShanCheng** [comment]
![image](https://user-images.githubusercontent.com/67892538/177674206-05b8bc43-8243-4128-b6a9-39f6f76c671b.png)
![image](https://user-images.githubusercontent.com/67892538/177674234-5c530f87-6475-43bd-b24e-bc1e8f09a3a9.png)
新建了一个项目 发现现在使用store就会报这个错误

**Comment by ClarkXia** [comment]
duplicate with #5391
