### ISSUE TITLE
为啥新建项目使用store会报这个错误 以前使用的时候没有

### ISSUE THREAD

**Issue by WuDuShanCheng** [alibaba/ice#5391]
![image](https://user-images.githubusercontent.com/67892538/177674319-d2ca043c-7dfd-4797-b8ea-364aa6221d21.png)
![image](https://user-images.githubusercontent.com/67892538/177674425-d3b29eea-17c7-42ec-b3fa-702b11f9056d.png)

**Comment by ClarkXia** [comment]
store 中为什么不配置内容？

**Comment by WuDuShanCheng** [comment]
![image](https://user-images.githubusercontent.com/67892538/177675958-65033d34-98d2-4cf0-9df2-d98536ee19a7.png)
![image](https://user-images.githubusercontent.com/67892538/177676060-3cff6bc8-86cc-4ddc-96c3-29feb148a2b4.png)
按照官方的配置还是不行 就是今天发生的事情 之前那个项目早上还好好的 十分钟之后就出这个bug了

**Comment by WuDuShanCheng** [comment]
然后我就新开了一个项目 测一下这个bug在什么地方 发现是这个原因

**Comment by WuDuShanCheng** [comment]
我把这个项目发给你吧 就是新建的demo而已 什么东西都没加

**Comment by WuDuShanCheng** [comment]
[demo.zip](https://github.com/alibaba/ice/files/9059834/demo.zip)

**Comment by WuDuShanCheng** [comment]
真的挺着急的 麻烦帮忙看看吧

**Comment by WuDuShanCheng** [comment]
能帮忙解决一下吗 现在项目没办法开工了

**Comment by WuDuShanCheng** [comment]
能解决一下吗 求个回复 或者我能加一下你联系方式不

**Comment by WuDuShanCheng** [comment]
如果不能解决 感觉得换个框架了 写了一个多月了

**Comment by luhc228** [comment]
我本地试了下，是好的


<img width="1542" alt="image" src="https://user-images.githubusercontent.com/44047106/178228617-793b0f05-0a7e-4822-919a-5abf8da366c8.png">

**Comment by WuDuShanCheng** [comment]
嗯嗯 是我的问题 因为谷歌的redux-tool 插件低了导致的 卸载了插件重新安装新版本就好了
