### ISSUE TITLE
导出报错

### ISSUE THREAD

**Issue by strongyc** [alibaba/ice#5395]
import { createStore } from 'ice';
、
模块“"ice"”没有导出的成员“createStore”。
模块已经安装

**Comment by luhc228** [comment]
你需要保证有 store.ts，因为框架会根据是否有 store.ts 判断是否开启 store，开启了的话，会出入对应的 API

**Comment by luhc228** [comment]
https://ice.work/docs/guide/basic/store

**Comment by YDJSZY** [comment]
src下有store.ts，重启还是报错

**Comment by luhc228** [comment]
> src下有store.ts，重启还是报错

请提供最小可复现的 demo
