### ISSUE TITLE
store建议

### ISSUE THREAD

**Issue by strongyc** [alibaba/ice#5396]
1、在Ts中支持定义state类型
2、store支持对state中的数据进行持久化存储，防止刷新页面后数据丢失，比如全局的用户数据。

**Comment by usercao** [comment]
可以试试[Recoil](https://recoiljs.org/zh-hans/docs/guides/atom-effects)，有`effects_UNSTABLE`优雅解决方案。

**Comment by ClarkXia** [comment]
类型已支持，持久化方案已有 issue 记录，后续单独讨论
