### ISSUE TITLE
[小建议] iceworks 侧边栏的 icon 可以添加 active 状态，和 hover 时候的效果类似

### ISSUE THREAD

**Issue by ly525** [alibaba/ice#54]
> 如图所示，当前我是在 项目 部分的，侧边栏的 item 没有 active 状态
> ![image](https://user-images.githubusercontent.com/12668546/35609222-76e0cc36-0697-11e8-8180-a66a5a39d191.png)

> hover 时候的状态
> ![image](https://user-images.githubusercontent.com/12668546/35609398-143e765e-0698-11e8-94fa-f06d80d64434.png)

**Comment by yujiangshui** [comment]
目前界面正在交由设计师整体设计， 新版会优化掉，感谢反馈
