### ISSUE TITLE
vite 应用 dev 调试下会有 warning：top-level this will be replaced with undefined

### ISSUE THREAD

**Issue by luhc228** [alibaba/ice#5401]
[vite] warning: Top-level "this" will be replaced with undefined since this file is an ECMAScript module 23 | return

https://github.com/vitejs/vite/issues/8644

**Comment by ZindexYG** [comment]
``build.json``

```JSON
{
  "vite": {
    "esbuild": {
      "logOverride": { "this-is-undefined-in-esm": "silent" }
    }
  },
}
```
this work~
