### ISSUE TITLE
 .prettierignore不生效，.ice目录报eslint的error

### ISSUE THREAD

**Issue by shensai06** [alibaba/ice#5402]
## What is the current behavior? 发生了什么？

升级到最新     "ice.js": "2.6.4"  npm  start时  控制台提示.ice文件夹下的eslint错误，但是我写了 .prettierignore  对.ice下不检查，却没有生效

![image](https://user-images.githubusercontent.com/59790047/178487831-06ff7584-e205-4396-9c76-972961a679af.png)

## What is the expected behavior? 期望的结果是什么？

期望.ice下不提示eslint异常

## Any additional comments? 相关环境信息？

- **ice.js Version**：
- 2.6.4
- **build.json Configuration**：
- ···
- **Node Version**:
- v18
- **Platform**:
-mac

**Comment by ClarkXia** [comment]
提供项目配置后重开 issue
