### ISSUE TITLE
yarn start 之后 过一会会自动报 node:internal/buffer:959 错误

### ISSUE THREAD

**Issue by L1uuuovo** [alibaba/ice#5404]
## What is the current behavior? 发生了什么？
yarn start 之后 过一会会自动报 node:internal/buffer:959 错误， 全公司只有我的电脑报这个错误，其他人的都不报错

![1657772074223_922C32B9-7D66-4f6a-82D3-4F12367406A8](https://user-images.githubusercontent.com/63575799/178897681-7fe739f1-2987-4499-976a-64be90efad22.png)

## What is the expected behavior? 期望的结果是什么？
正常，不报错

## Any additional comments? 相关环境信息？

- **ice.js Version**：
- 2.6.4
- **build.json Configuration**：
- **Node Version**:
- 16.15.1
- **Platform**:
- windows 10

**Comment by ClarkXia** [comment]
有点像内存不足的问题，可以使用把 start 命令改成 `cross-env DISABLE_FS_CACHE=true icejs start` 试试

**Comment by L1uuuovo** [comment]
@ClarkXia 谢谢大佬 这个内存值的是电脑内存还是什么别的？？

**Comment by ClarkXia** [comment]
是的，问题解决了吗？

**Comment by ClarkXia** [comment]
暂时关闭，目前看是内存问题导致

**Comment by L1uuuovo** [comment]
问题解决了 感谢大佬
