### ISSUE TITLE
ice pnpm monorepo下打包后icon无法显示

### ISSUE THREAD

**Issue by CX330-jiuxi** [alibaba/ice#5405]
## What is the current behavior? 发生了什么？
相对路径（publicPath：“./” ）打包后icon 无法显示
demo：https://github.com/CX330-jiuxi/vite-build-error.git
pnpm: 7.x
复现步骤
pnpm install 后 pnpm build，双击打开build/inde.html

开发环境下，显示正常：
![image](https://user-images.githubusercontent.com/51979013/179144227-ebf8ec18-f066-48eb-8492-3a1459b1a45c.png)

打包后，本地静态打开html，icon无法显示：
![image](https://user-images.githubusercontent.com/51979013/179144334-eae6e79d-0413-4ab8-a70f-74ba926b00a8.png)

## Any additional comments? 相关环境信息？

- **ice.js Version*2.0.0*：
- **build.json Configuration**：
```json
{
  "vite": false,
  "publicPath": "./",
  "plugins": [
    [
      "build-plugin-moment-locales",
      {
        "locales": [
          "zh-cn"
        ]
      }
    ],
    [
      "build-plugin-ignore-style",
      {
        "libraryName": "@alifd/theme-mxs-dark"
      }
    ],
    [
      "build-plugin-fusion",
      {
        "themePackage": "@alifd/theme-mxs-dark"
      }
    ]
  ]
}

```
- **Node Version*16.16.0*:
- **Platform**: web

**Comment by ClarkXia** [comment]
看下打包后的 icon 地址是否正常加载

**Comment by CX330-jiuxi** [comment]
@ClarkXia 本地打开html，file://加载不了icon资源

**Comment by CX330-jiuxi** [comment]
fusion icon资源存在cdn上，下载到本地即可
