### ISSUE TITLE
如何添加自定义eslint规则

### ISSUE THREAD

**Issue by strongyc** [alibaba/ice#5406]
const { getESLintConfig } = require('@iceworks/spec');

// https://www.npmjs.com/package/@iceworks/spec
module.exports = getESLintConfig('react-ts');
在文件中如何添加自己的eslint规则，覆盖前面的？

**Comment by ClarkXia** [comment]
在 `.eslintrc.js` 里修改就行，merge 默认的规则，参考 https://github.com/alibaba/ice/blob/master/.eslintrc.js
