### ISSUE TITLE
ice.js 1.x 升级 ice.js 2.0.0 vite问题

### ISSUE THREAD

**Issue by zhangsixue-1992** [alibaba/ice#5410]
升级后启用vite报错
<img width="549" alt="image" src="https://user-images.githubusercontent.com/68992967/179903207-0de493d1-74c5-4e04-a0ad-475d57227c75.png">

build.config.js 配置
![image](https://user-images.githubusercontent.com/68992967/179903300-ba1a5e25-6613-4e76-89f9-fb5d921b2cf8.png)

请问一下需要如何解决

**Comment by ClarkXia** [comment]
看着像 react 预打包逻辑问题，试下重新启动调试

**Comment by zhangsixue-1992** [comment]
重启多次，
也自己试着解决此问题，没弄好......

如果不启用vite升级启动是没问题哒

**Comment by zhangsixue-1992** [comment]
> 看像 react 预打包逻辑问题，试下重新启动调试

重启很多次了
也自己尝试解决这个问题，没弄好......

如果不启用vite升级启动是没问题哒

**Comment by ClarkXia** [comment]
可以提供下简单的复现 demo

**Comment by zhangsixue-1992** [comment]
> 可以提供下简单的复现演示

![image](https://user-images.githubusercontent.com/68992967/179912808-c87481b6-3bae-486d-ade7-79761b827696.png)
![image](https://user-images.githubusercontent.com/68992967/179912853-9c3765f0-2c6c-4e36-8d5d-15a2eb3e26d9.png)
![image](https://user-images.githubusercontent.com/68992967/179912998-4ea25ca3-ea63-4733-9c02-e6c1ce88b30a.png)
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/68992967/179913030-c8acc10a-a33a-4f40-b9af-b15bcbcc6835.png">
不知道这样行不行

**Comment by zhangsixue-1992** [comment]
> 可以提供下简单的复现演示

![image](https://user-images.githubusercontent.com/68992967/179912808-c87481b6-3bae-486d-ade7-79761b827696.png)
![image](https://user-images.githubusercontent.com/68992967/179912853-9c3765f0-2c6c-4e36-8d5d-15a2eb3e26d9.png)
![image](https://user-images.githubusercontent.com/68992967/179912998-4ea25ca3-ea63-4733-9c02-e6c1ce88b30a.png)
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/68992967/179913030-c8acc10a-a33a-4f40-b9af-b15bcbcc6835.png">
不知道这样行不行

**Comment by ClarkXia** [comment]
不要用截图，最好有简单的代码提供，可以基于官方的 demo 试试，另外也可以看下错误栈简单定位下具体报错的语句

**Comment by zhangsixue-1992** [comment]
> 不用截图，最好有提供的代码可以根据官方的demo试试，另外也可以简单的看下错误栈，简单的定位下具体报错的语句

公司项目，从1.X网上升级......简单的断定了一下问题

**Comment by zhangsixue-1992** [comment]
> 不用截图，最好有提供的代码也可以根据官方的demo，另外可以简单的看下错误栈，简单的定位下具体报错的语句

司项目，从1.X网上升级......

报错应该是因为node_modules内文件导致的

Uncaught SyntaxError: The requested module '/node_modules/react/index.js' does not provide an export named 'Component' (at index.tsx:6:1)

**Comment by luhc228** [comment]
哪里导入了 Component ？

**Comment by zhangsixue-1992** [comment]
> Component

我全局搜索了一下，只有.ice文件内有这个引入
![image](https://user-images.githubusercontent.com/68992967/180177620-f0f99e0f-ea5e-45bf-a3d0-eee1f72daa1a.png)
但是.ice是 start 生成的文件呀

**Comment by ClarkXia** [comment]
这样比较难定位，你可以裁剪下项目 只要能够复现出来这个问题就行
