### ISSUE TITLE
本地开发服务异常退出 Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by flute** [alibaba/ice#5411]
## What is the current behavior? 发生了什么？
npm start 本地开发环境运行起来后，经常出现抛出异常，程序终止的问题。

```
_http_outgoing.js:561
    throw new ERR_HTTP_HEADERS_SENT('set');
    ^
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
```

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/5842406/179954865-661a5e2f-49f5-4df3-be67-0091e52866d7.png">

在ice-script2.x、icejs1.x版本均有出现，目前升级到了icejs2之后，出现非常频繁。

应该是设置代理的相关库存在问题。

## What is the expected behavior? 期望的结果是什么？

本地服务正常运行。

## Any additional comments? 相关环境信息？

- **ice.js Version**：2.4.6
- **build.json Configuration**：

代理设置如下：其他无特殊配置

```js
proxy: {
    '/api_web/**': {
      enable: true,
      target: 'http://xxx.xxx.com',
    },
  },
```

- **Node Version**: v14.19.3
- **Platform**: MacOS 12.3.1

**Comment by ClarkXia** [comment]
看着像 proxy 的问题，确认下 proxy 的 api 地址返回有没有什么异常

**Comment by flute** [comment]
> 看着像 proxy 的问题，确认下 proxy 的 api 地址返回有没有什么异常

api返回内容没问题的，这个可以确定。看着像 `http-proxy-middleware` 的使用问题。类似问题有：

https://github.com/chimurai/http-proxy-middleware/issues/412

https://github.com/chimurai/http-proxy-middleware/issues/472

**Comment by ClarkXia** [comment]
https://github.com/alibaba/ice/pull/5369  应该是这个逻辑影响 目前已修复
