### ISSUE TITLE
部署报错React is not defined

### ISSUE THREAD

**Issue by strongyc** [alibaba/ice#5413]
index.js:42 ReferenceError: React is not defined
    at Vt (index14.js:1:39695)
    at Fv (index.js:42:59904)
    at Wg (index.js:42:112012)
    at uy (index.js:42:99090)
    at ay (index.js:42:99018)
    at iy (index.js:42:98880)
    at Qg (index.js:42:95733)
    at index.js:42:45784
    at e.unstable_runWithPriority (index.js:33:3778)
    at Eh (index.js:42:45561)
zm @ index.js:42
Bm.n.callback @ index.js:42
$h @ index.js:42
Km @ index.js:42
fy @ index.js:42
e.unstable_runWithPriority @ index.js:33
Eh @ index.js:42
cy @ index.js:42
Qg @ index.js:42
（匿名） @ index.js:42
e.unstable_runWithPriority @ index.js:33
Eh @ index.js:42
Ch @ index.js:42
L @ index.js:33
b.port1.onmessage @ index.js:33
index.js:33 Uncaught ReferenceError: React is not defined
    at Vt (index14.js:1:39695)
    at Fv (index.js:42:59904)
    at Wg (index.js:42:112012)
    at uy (index.js:42:99090)
    at ay (index.js:42:99018)
    at iy (index.js:42:98880)
    at Qg (index.js:42:95733)
    at index.js:42:45784
    at e.unstable_runWithPriority (index.js:33:3778)
    at Eh (index.js:42:45561)

## Any additional comments? 相关环境信息？

- **ice.js Version**：
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by wssgcg1213** [comment]
需要补充清楚问题

1. external React/ReactDOM 了吗
2. 如果 external 了, 有没有在 HTML 里引入对应的 script
3. 如果没有 external, 对应的组件源码看一下是不是手动使用了 `React` 这个全局变量 (没有从包引入 React, 或者是手动 window.React)

**Comment by strongyc** [comment]
1.没有使用external 
2.import * as React from 'react'
import  { useState } from 'react';
组件里是这样用的
export default 导出 ，本地测试没有问题，打包部署就报错了

**Comment by strongyc** [comment]
> 需要补充清楚问题
> 
> 1. external React/ReactDOM 了吗
> 2. 如果 external 了, 有没有在 HTML 里引入对应的 script
> 3. 如果没有 external, 对应的组件源码看一下是不是手动使用了 `React` 这个全局变量 (没有从包引入 React, 或者是手动 window.React)
1.没有使用external
2.import * as React from 'react'
import { useState } from 'react';
组件里是这样用的
export default 导出 ，本地测试没有问题，打包部署就报错了

**Comment by strongyc** [comment]
export default {
  vite: true,
  outputDir: "dist",
  plugins: [
    [
      'build-plugin-ignore-style',
      {
        libraryName: 'antd',
      },
    ],
    [
      'build-plugin-moment-locales',
      {
        locales: ['zh-cn'],
      },
    ],
    [
      'build-plugin-antd',
      {
        disableModularImport: true,
        themeConfig: {
          'primary-color': '#3b82f6',
        },
      },
    ],
  ],
  babelPresets: [['@babel/preset-react', { runtime: 'automatic', importSource: '@emotion/react' }]],
  babelPlugins: ['@emotion/babel-plugin'],
  proxy: {
    '/api': {
      enable: true,
      // eslint-disable-next-line @iceworks/best-practices/no-http-url
      target: 'http://127.0.0.1:9401',
      changeOrigin: true,
      pathRewrite: { '/api/': '' },
    },
  },
};
是引入了css in js 的原因吗？

**Comment by wssgcg1213** [comment]
提供一下可复现的 demo 吧

**Comment by strongyc** [comment]
> 提供一下可复现的 demo 吧
你好，排查出的原因就是使用了这个插件
babelPresets: [['@babel/preset-react', { runtime: 'automatic', importSource: '@emotion/react' }]],
babelPlugins: ['@emotion/babel-plugin'],
等我差个时间弄个demo

**Comment by ClarkXia** [comment]
跟部署没关系，如果使用 `automatic` 默认会注入 react 相关的 jsx-runtime，定制的 babel 插件转化上是不是有问题
