### ISSUE TITLE
飞冰的文档能不能写的完善一点呢？

### ISSUE THREAD

**Issue by ddduanlian** [alibaba/ice#5416]
## What is the current behavior? 发生了什么？

文档写的太简单啦，根本就没有详细介绍

看看这个，https://ice.work/docs/api/about/#prompt
就一段话结束了，还有错别字

## Any additional comments? 相关环境信息？

- **ice.js Version**：
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by ClarkXia** [comment]
有什么建议和希望得到的帮助都可以提，另外这是一个开源项目，一些错误的地方可以直接 pr

**Comment by ClarkXia** [comment]
错别字已修复 其他建议可以单独 issue
