### ISSUE TITLE
ice1.0升2.0遇到错误，Dynamic require of "D:/B端/sop-kct-omfe-test/node_modules/designare-table/table.css" is not supported

### ISSUE THREAD

**Issue by wxadrtyu** [alibaba/ice#5418]
`Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
var debounce = require("lodash/debounce");
var react_1 = require("react");
var context_1 = require("./context");
var Thead_1 = require("./Thead");
var Tbody_1 = require("./Tbody");
var Pagination_1 = require("./Pagination");
var SyncScrolling_1 = require("./SyncScrolling");
var Loading_1 = require("./Loading");
var messages_1 = require("./messages");
var util_1 = require("./util");
require("./table.css");`

最后一句报错，这个是antd，table的源码

**Comment by ClarkXia** [comment]
如果开启 vite 是不支持 require 语法的，看下 designare-table 这个包的构建产物是否有 esm 标准的产物

**Comment by wxadrtyu** [comment]
好的，已经解决
