### ISSUE TITLE
vite 无法打包以下传参格式，打包样式无效

### ISSUE THREAD

**Issue by strongyc** [alibaba/ice#5419]
import React from 'react';
import classNames from 'classnames';
import styles from './index.less';

type StandardFormRowProps = {
  title?: string;
  last?: boolean;
  block?: boolean;
  grid?: boolean;
  style?: React.CSSProperties;
};

const StandardFormRow: React.FC<StandardFormRowProps> = ({
  title,
  children,
  last,
  block,
  grid,
  ...rest
}) => {
  const cls = classNames(styles.standardFormRow, {
    [styles.standardFormRowBlock]: block,
    [styles.standardFormRowLast]: last,
    [styles.standardFormRowGrid]: grid,
  });

  return (
    <div className={cls} {...rest}>
      {title && (
        <div className={styles.label}>
          <span>{title}</span>
        </div>
      )}
      <div className={styles.content}>{children}</div>
    </div>
  );
};

export default StandardFormRow;

![image](https://user-images.githubusercontent.com/51156342/180726289-2532188e-d039-45a4-b6c0-e6dba0a9554e.png)

无法对这种传参进行编译，样式失效

**Comment by ClarkXia** [comment]
使用 css module 要求文件名为 index.modules.less
