### ISSUE TITLE
使用antd组件库配置中文无效

### ISSUE THREAD

**Issue by strongyc** [alibaba/ice#5420]
![image](https://user-images.githubusercontent.com/51156342/180733265-d7132c74-d499-4df9-a2bf-8539f2842841.png)
![image](https://user-images.githubusercontent.com/51156342/180733299-3c7c33f7-945d-48ce-b330-54ffb72ce551.png)
![image](https://user-images.githubusercontent.com/51156342/180733526-8916b31b-ff25-4743-8eb9-34cf120a4ffc.png)
配置不生效

**Comment by ClarkXia** [comment]
通过插件设置即可

https://ice.work/docs/plugin/list/moment-locales

```bash
npm init ice ice-antd --template @icedesign/ice-antd-scaffold
```
初始化 antd 项目，并使用插件 [build-plugin-moment-locales](https://ice.work/docs/plugin/list/moment-locales)

![image](https://user-images.githubusercontent.com/4219965/181406113-99727232-6608-4621-966a-a3fc189898bb.png)


最终效果

![image](https://user-images.githubusercontent.com/4219965/181406060-4091022e-88ef-48a4-9c8e-1f9359886b8e.png)

**Comment by strongyc** [comment]
你好，这个在antd生效了但是在antd [ProComponents](https://procomponents.ant.design/) 还是不生效
![image](https://user-images.githubusercontent.com/51156342/181430302-7f689f1a-90df-48a6-9202-5c1c3068bb87.png)

**Comment by strongyc** [comment]
![image](https://user-images.githubusercontent.com/51156342/181442313-3decb2b7-a2ab-4e09-a908-a59d794ba3ca.png)
antd Pro中不生效

**Comment by strongyc** [comment]
![image](https://user-images.githubusercontent.com/51156342/181442313-3decb2b7-a2ab-4e09-a908-a59d794ba3ca.png)
antd Pro中不生效

**Comment by ClarkXia** [comment]
@strongyc 提供下 demo，这边看下

**Comment by strongyc** [comment]
> @strongyc 提供下 demo，这边看下
[archives-antd-pro.zip](https://github.com/alibaba/ice/files/9286135/archives-antd-pro.zip)
请查看这个demo，antd可以,antdPro失效

**Comment by ClarkXia** [comment]
![image](https://user-images.githubusercontent.com/4219965/183604672-f6bde839-c501-441f-a2de-57fab0831833.png)
提供的 demo 中文显示没有问题，可以考虑删除下 vite 缓存，node_modules/.vite

**Comment by strongyc** [comment]
> > ![image](https://user-images.githubusercontent.com/4219965/183604672-f6bde839-c501-441f-a2de-57fab0831833.png) 提供的 demo 中文显示没有问题，可以考虑删除下 vite 缓存，node_modules/.vite
> 
> 你好，我删除了node_modules/.vite，也删除了node_module重新安装,ice版本是2.6.4，现在还不是中文，还有什么解决方案吗？

![image](https://user-images.githubusercontent.com/51156342/183610011-4b9a866f-6416-46af-aaa6-997410fbe1e8.png)

**Comment by strongyc** [comment]
> > > ![image](https://user-images.githubusercontent.com/4219965/183604672-f6bde839-c501-441f-a2de-57fab0831833.png) 提供的 demo 中文显示没有问题，可以考虑删除下 vite 缓存，node_modules/.vite
> > 
> > 
> > 你好，我删除了node_modules/.vite，也删除了node_module重新安装,ice版本是2.6.4，现在还不是中文，还有什么解决方案吗？
> 
> ![image](https://user-images.githubusercontent.com/51156342/183610011-4b9a866f-6416-46af-aaa6-997410fbe1e8.png)

系统是windows11

**Comment by strongyc** [comment]
你好，目前排查出问题使用yarn安装之后就会出现一直是英文，如果使用npm就正常了，并且打包体积减少了200K，yarn已经删除了缓存在重新安装还是一样的问题，这是什么原因呢

**Comment by FuzzyFade** [comment]
> 你好，目前排查出问题使用yarn安装之后就会出现一直是英文，如果使用npm就正常了，并且打包体积减少了200K，yarn已经删除了缓存在重新安装还是一样的问题，这是什么原因呢

你用 yarn 把 lock 文件删了再重新安装所有依赖应该也能修好...

**Comment by strongyc** [comment]
> > 你好，目前排查出问题使用yarn安装之后就会出现一直是英文，如果使用npm就正常了，并且打包体积减少了200K，yarn已经删除了缓存在重新安装还是一样的问题，这是什么原因呢
> 
> 你用 yarn 把 lock 文件删了再重新安装所有依赖应该也能修好...

感谢大佬，困扰的问题得以解决，感谢！

**Comment by wx9999** [comment]
> > > 你好，目前排查出问题使用yarn安装之后就会出现一直是英文，如果使用npm就正常了，并且打包体积减少了200K，yarn已经删除了缓存在重新安装还是一样的问题，这是什么原因呢
> > 
> > 
> > 你用 yarn 把 lock 文件删了再重新安装所有依赖应该也能修好...
> 
> 感谢大佬，困扰的问题得以解决，感谢！

同样问题，以上操作并没有解决
