### ISSUE TITLE
19:04:12 [vite] warning: Top-level "this" will be replaced with undefined since this file is an ECMAScript module

### ISSUE THREAD

**Issue by anyone0034** [alibaba/ice#5422]
## What is the current behavior? 发生了什么？
> npm init ice test2 --template @alifd/fusion-design-pro-js
> cnpm start

`
> @alifd/fusion-design-pro-js@0.1.0 start
> icejs start
ice.js 2.6.4
  > Local:    http://localhost:3333/
19:04:12 [vite] warning: Top-level "this" will be replaced with undefined since this file is an ECMAScript module
64 |        ...restRouterProps
65 |      } = routerProps;
66 |      return <IceRouter {...restRouterProps} __self={this} __source={{
   |                                                     ^
67 |        fileName: _jsxFileName,
68 |        lineNumber: 44,
  Plugin: vite:esbuild
  File: E:/Code/ice/test/test2/test2/.ice/plugins/router/pluginRuntime/runtime.tsx
19:04:14 [vite] warning: Top-level "this" will be replaced with undefined since this file is an ECMAScript module
23 |            return <authConfig.NoAuthFallback {...Object.assign({}, props, {
24 |              pageConfig
25 |            })} __self={this} __source={{
   |                        ^
26 |              fileName: _jsxFileName,
27 |              lineNumber: 25,
... ...

`

## What is the expected behavior? 期望的结果是什么？
有警告信息，但能正常运行。能屏蔽掉 ` [vite] warning: Top-level "this" will be replaced with undefined since this file is an ECMAScript module`嘛。
## Any additional comments? 相关环境信息？

- **ice.js Version**：2.6.4
- **build.json Configuration**：
`
{
  "vite": true,
  "alias": {
    "venn.js": "venn.js/build/venn.js"
  },
  "plugins": [
    [
      "build-plugin-moment-locales",
      {
        "locales": [
          "zh-cn"
        ]
      }
    ],
    [
      "build-plugin-ignore-style",
      {
        "libraryName": "@alifd/next"
      }
    ]
  ]
}

`
- **Node Version**: v18.6.0
- **Platform**: windows web

**Comment by ClarkXia** [comment]
已有 issue 记录，近期会修复 https://github.com/alibaba/ice/issues/5401
