### ISSUE TITLE
vite 构建一直报错，这是什么原因？

### ISSUE THREAD

**Issue by strongyc** [alibaba/ice#5425]
22:17:05 [vite] warning: Top-level "this" will be replaced with undefined since this file is an ECMAScript module
105|    }} cancelButtonProps={{
106|      disabled: isShow
107|    }} __self={this} __source={{
   |               ^
108|      fileName: _jsxFileName,
109|      lineNumber: 83,

  Plugin: vite:esbuild
22:17:22 [vite] warning: Top-level "this" will be replaced with undefined since this file is an ECMAScript module
20 |        <StandardFormRow title={title} block style={{
21 |        paddingBottom: 5
22 |      }} __self={this} __source={{
   |                 ^
23 |        fileName: _jsxFileName,
24 |        lineNumber: 20,

  Plugin: vite:esbuild
22:17:22 [vite] warning: Top-level "this" will be replaced with undefined since this file is an ECMAScript module
24 |      [styles.standardFormRowGrid]: grid
25 |    });
26 |    return <div className={cls} {...rest} __self={this} __source={{
   |                                                  ^
27 |      fileName: _jsxFileName,
28 |      lineNumber: 28,

  Plugin: vite:esbuild
22:17:22 [vite] warning: Top-level "this" will be replaced with undefined since this file is an ECMAScript module
26 |    onChange,
27 |    value
28 |  }) => <CheckableTag checked={!!checked} key={value} onChange={state => onChange && onChange(value, state)} __self={this} __source={{
   |                                                                                                                     ^
29 |    fileName: _jsxFileName,
30 |    lineNumber: 21,
这方式在umi 没有错误啊

**Comment by wssgcg1213** [comment]
This is a warning that top level this will be replaced to `undefined`, since you know what happened you can just ignored this warning.   
If you want to dismiss this message, you can change your `ArrowFunction` into a normal one, which makes `this` not top-level.

eg. 

```jsx
const someFn = () => {
 return </>;
};
```

->

```jsx
function someFn() {
  return </>;
}
```
