### ISSUE TITLE
model 无法进行typescript 类型检查

### ISSUE THREAD

**Issue by sum1201** [alibaba/ice#5427]
## What is the current behavior? 发生了什么？
按照demo， effects 调用reducers 中的方法时， 会提示“实参数量无效，应为 2 个", 同时也无法对方法中的参数进行类型检查。 

https://github.com/alibaba/ice/blob/a27620d3d47a97b8d31f3a9ec493b84777544063/examples/basic-store/src/models/user.ts#L9-L26

## What is the expected behavior? 期望的结果是什么？

希望能完整支持 typescript

## Any additional comments? 相关环境信息？

- **ice.js Version**：
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by ClarkXia** [comment]
问题已知，计划下周发布

**Comment by ClarkXia** [comment]
通过 `createModel` 进行定义 https://github.com/alibaba/ice/pull/5443
