### ISSUE TITLE
[优化建议] effects里的rootState不是最新的，导致更新错误。建议增加getState方法

### ISSUE THREAD

**Issue by yinran100** [alibaba/ice#5432]
## effects里的rootState不是最新的，导致更新错误。建议增加getState方法

- **ice.js Version**：2.6.4
- **build.json Configuration**：
- **Node Version**: 
- **Platform**:

**Comment by luhc228** [comment]
是否能提供最小复现的 demo ?

**Comment by yinran100** [comment]
https://stackblitz.com/edit/github-rtqaka?file=src/pages/Home/index.tsx 
如果运行不了，就查看 https://github.com/yinran100/ice-store-demo.git
store里的`rootState.home.name` 并不会因为调用三次`dispatchers`变成 'demodemodemo' ,而还是'demo'，就因为effects里的rootState不是最新的

**Comment by luhc228** [comment]
> https://stackblitz.com/edit/github-rtqaka?file=src/pages/Home/index.tsx 如果运行不了，就查看 https://github.com/yinran100/ice-store-demo.git store里的`rootState.home.name` 并不会因为调用三次`dispatchers`变成 'demodemodemo' ,而还是'demo'，就因为effects里的`rootState`不是最新的 临时解决方案是增加一个 `getState` 的effect, effect需要获取`rootState` 就` rootState = await this.getState();`，而不是使用`effects`自带的`rootState`

大概看了下源码，现在在 `useEffect` 回调中连续调用了 `homeDispatchers.getUserInfo();` 三次，相当于是同步执行了，但是 home.name 的值 都还没更新过来（有点像你连续 setState 只会取最后的一次结果）。如果你在 homeDispatchers.getUserInfo(); 前增加 await 就可以了达到你想要的结果了。

**Comment by yinran100** [comment]
这不就是问题吗，如果这边是三个不同的effect，各自就不知道自己所需的state是不是最新的，如果加上了await，就将三个并行的异步任务给串行了。这样是没必要的，所以为什么需要要求增加getState的方法

**Comment by luhc228** [comment]
> 这不就是问题吗，如果这边是三个不同的effect，或者三个不同的组件触发一样的effect，各自就不知道自己所需的state是不是最新的啊。就算如果加上了await，就将三个并行的异步任务给串行了。这样是没必要的，所以我建议effects的第二个参数应该改成getState的方法

你这种情况用 reducer 更合适。effect 是用来处理默认副作用的

**Comment by yinran100** [comment]
比如分步加载树形数据结构，每个树节点的数据都是走接口异步请求的。拿到的数据，会绑定到整个树形数据中，如果因为时序问题，拿不到最新的state的话，数据就会相互覆盖。

**Comment by xmsz-stu** [comment]
我遇到一个需求是 队列执行
有个run方法，从rootState中拿到执行的数据，然后执行和修改
但是显示rootState拿到的是旧的值有点蛋疼
