### ISSUE TITLE
iceworks图标问题

### ISSUE THREAD

**Issue by long1987** [alibaba/ice#5433]
iceworks创建的项目，使用iceworks构建项目以后，断开网络，清空浏览器的缓存，打开构建后的网页，网页中的控件包含的 图标出不来，显示成了小方块，比如菜单栏，分页按钮，下拉框等。联网的时候，显示正常。麻烦回复一下，怎么解决这个问题。

**Comment by ClarkXia** [comment]
指的是 iconfont？  断网不显示不是很正常么，资源是通过 cdn 获取的
