### ISSUE TITLE
能否支持 webpack profile 配置

### ISSUE THREAD

**Issue by weiTimes** [alibaba/ice#5435]
## What is the current behavior? 发生了什么？

目前希望借助 webpack profile 参数去生成包含构建信息的 json 文件，以便进行分析。

## What is the expected behavior? 期望的结果是什么？

可否暴露 webpack 的 profile 属性，方便分析编译过程呢？
目前情况是无法准确确定消耗的准确位置。

## Any additional comments? 相关环境信息？

- **ice.js Version**：2.6.4
- **build.json Configuration**：
- **Node Version**: 14.18.0
- **Platform**: macos

**Comment by ClarkXia** [comment]
可以先通过[自定义方式](https://ice.work/docs/guide/basic/build/#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%B7%A5%E7%A8%8B%E9%85%8D%E7%BD%AE)进行配置

**Comment by weiTimes** [comment]
我自定义进行了以下配置：
config.profile(true);

但是想要在根目录下生成这个 json 文件，是需要在后面加 -- json 的参数，如下：
npx webpack --json=stats.json 

而我们现在是通过 icejs 进行构建的，不支持这个参数，这个参数可以透传给 webpack 吗

**Comment by ClarkXia** [comment]
@weiTimes 内部是执行 `webpack(webpackConfig)` 的方式做的，json 的输出也可以通过 webpack 插件进行处理

**Comment by weiTimes** [comment]
我在自定义插件中加入了 StatsWriterPlugin 的插件，代码如下：

```
config.plugin('StatsWriterPlugin').use(StatsWriterPlugin, [
      {
        filename: 'stats.json', // Default
      },
    ]);
```

构建结果如下，但好像没起作用，没有在根目录下生成构建信息文件 stats.json

<img width="858" alt="image" src="https://user-images.githubusercontent.com/21688593/182319124-4b9aa5a1-f9b4-4c0e-a855-7e31792a777b.png">

**Comment by ClarkXia** [comment]
可以简单 debug 下 StatsWriterPlugin 这个插件有没有 emit 文件的逻辑

**Comment by weiTimes** [comment]
忘了和你说了 它是写到了build目录下，之前没注意到，这个issue可以关了
