### ISSUE TITLE
ice1.0升级到2.6.4时，编译错误：Unknown error from PostCSS plugin. Your current PostCSS version is 8.4.14, but postcss-preset-env uses 7.0.39. Perhaps this is the source of the error below

### ISSUE THREAD

**Issue by wyw-s** [alibaba/ice#5436]
## What is the current behavior? 发生了什么？

我将ice1.0 升级到2.6.4时，然后执行脚本：icejs start --mode local  --disable-mock  --port 8102  --config build.config.js
出现编译错误：

`
 kylin-operation@3.0.6 start:no-mock C:\Users\WANGYAWEI\Desktop\ice2.0\kylin-operation
 cross-env envType=LOCAL publicPath=/child/kylin-operation/ icejs start --mode local  --disable-mock  --port 8102  --config build.config.js

ice.js 2.6.4
transform error with: C:/Users/WANGYAWEI/Desktop/ice2.0/kylin-operation/src/pages/Product/components/ProductTable.jsx
transform error with: C:/Users/WANGYAWEI/Desktop/ice2.0/kylin-operation/src/pages/Product/Modal/AddCatalogueModal.jsx
WARN 
    [plugin-icestark]: type should to be included, which we truly suggested. see https://ice.work/docs/guide/advanced/icestark/#type-1
   
WARN 
      [plugin-icestark]: supposed to be child type. and it is more preferable set type option with child.
      see https://ice.work/docs/guide/advanced/icestark
info 自定义 antd 组件主题变量： { 'primary-color': '#1890FF' }
error occur when parse expose content of @permit/product
Unknown error from PostCSS plugin. Your current PostCSS version is 8.4.14, but postcss-preset-env uses 7.0.39. Perhaps this is the source of the error below.
Unknown error from PostCSS plugin. Your current PostCSS version is 8.4.14, but postcss-preset-env uses 7.0.39. Perhaps this is the source of the error below.
Unknown error from PostCSS plugin. Your current PostCSS version is 8.4.14, but postcss-preset-env uses 7.0.39. Perhaps this is the source of the error below.
Unknown error from PostCSS plugin. Your current PostCSS version is 8.4.14, but postcss-preset-env uses 7.0.39. Perhaps this is the source of the error below.
Unknown error from PostCSS plugin. Your current PostCSS version is 8.4.14, but postcss-preset-env uses 7.0.39. Perhaps this is the source of the error below.
(node:17764) [DEP_WEBPACK_TEMPLATE_PATH_PLUGIN_REPLACE_PATH_VARIABLES_HASH] DeprecationWarning: [hash] is now [fullhash] (also consider using [chunkhash] or [contenthash], see documentation for details)
(Use `node --trace-deprecation ...` to show where the warning was created)
ERR! Fail to pre build dependencies {
ERR! Fail to pre build dependencies   name: 'web',
ERR! Fail to pre build dependencies   time: 19094,
ERR! Fail to pre build dependencies   errors: [
ERR! Fail to pre build dependencies     {
ERR! Fail to pre build dependencies       moduleIdentifier: 'C:\\Users\\WANGYAWEI\\Desktop\\ice2.0\\kylin-operation\\node_modules\\@builder\\pack\\deps\\css-loader\\cjs.js??ruleSet[1].rules[4].use[1]!C:\
\Users\\WANGYAWEI\\Desktop\\ice2.0\\kylin-operation\\node_modules\\@builder\\pack\\deps\\postcss-loader\\cjs.js??ruleSet[1].rules[4].use[2]!C:\\Users\\WANGYAWEI\\Desktop\\ice2.0\\kylin-operation\\node_mo
dules\\@builder\\pack\\deps\\less-loader\\cjs.js??ruleSet[1].rules[4].use[3]!C:\\Users\\WANGYAWEI\\Desktop\\ice2.0\\kylin-operation\\node_modules\\yr-loan-antd\\esm\\component\\DataDisplayCategory\\YRLoanContractSignedCard\\index.less',
ERR! Fail to pre build dependencies       moduleName: './node_modules/yr-loan-antd/esm/component/DataDisplayCategory/YRLoanContractSignedCard/index.less.webpack[javascript/auto]!=!./node_modules/@builder
/pack/deps/css-loader/cjs.js??ruleSet[1].rules[4].use[1]!./node_modules/@builder/pack/deps/postcss-loader/cjs.js??ruleSet[1].rules[4].use[2]!./node_modules/@builder/pack/deps/less-loader/cjs.js??ruleSet[1].rules[4].use[3]!./node_modules/yr-loan-antd/esm/component/DataDisplayCategory/YRLoanContractSignedCard/index.less',
ERR! Fail to pre build dependencies       message: 'Module build failed (from ./node_modules/@builder/pack/deps/postcss-loader/cjs.js):\n' +
ERR! Fail to pre build dependencies         "TypeError: Cannot read property 'raws' of undefined\n" +
ERR! Fail to pre build dependencies         '    at Parser.space (C:\\Users\\WANGYAWEI\\Desktop\\ice2.0\\kylin-operation\\node_modules\\@builder\\pack\\deps\\postcss-preset-env\\index.js:46735:25)\n' +  
ERR! Fail to pre build dependencies         '    at Parser.parseTokens (C:\\Users\\WANGYAWEI\\Desktop\\ice2.0\\kylin-operation\\node_modules\\@builder\\pack\\deps\\postcss-preset-env\\index.js:46571:14)\n' +
ERR! Fail to pre build dependencies         '    at Parser.loop (C:\\Users\\WANGYAWEI\\Desktop\\ice2.0\\kylin-operation\\node_modules\\@builder\\pack\\deps\\postcss-preset-env\\index.js:46480:12)\n' +   
ERR! Fail to pre build dependencies         '    at Parser.parse (C:\\Users\\WANGYAWEI\\Desktop\\ice2.0\\kylin-operation\\node_modules\\@builder\\pack\\deps\\postcss-preset-env\\index.js:46399:17)\n' +  
ERR! Fail to pre build dependencies         '    at parse (C:\\Users\\WANGYAWEI\\Desktop\\ice2.0\\kylin-operation\\node_modules\\@builder\\pack\\deps\\postcss-preset-env\\index.js:24883:30)\n' +
ERR! Fail to pre build dependencies         '    at C:\\Users\\WANGYAWEI\\Desktop\\ice2.0\\kylin-operation\\node_modules\\@builder\\pack\\deps\\postcss-preset-env\\index.js:24909:42\n' +
ERR! Fail to pre build dependencies         '    at Array.forEach (<anonymous>)\n' +
ERR! Fail to pre build dependencies         '    at C:\\Users\\WANGYAWEI\\Desktop\\ice2.0\\kylin-operation\\node_modules\\@builder\\pack\\deps\\postcss-preset-env\\index.js:24905:26\n' +
ERR! Fail to pre build dependencies         '    at Array.forEach (<anonymous>)\n' +
ERR! Fail to pre build dependencies         '    at getCustomPropertiesFromRoot (C:\\Users\\WANGYAWEI\\Desktop\\ice2.0\\kylin-operation\\node_modules\\@builder\\pack\\deps\\postcss-preset-env\\index.js:24901:22)'
ERR! Fail to pre build dependencies     },
ERR! Fail to pre build dependencies     {
ERR! Fail to pre build dependencies       moduleIdentifier: 'C:\\Users\\WANGYAWEI\\Desktop\\ice2.0\\kylin-operation\\node_modules\\@builder\\pack\\deps\\css-loader\\cjs.js??ruleSet[1].rules[4].use[1]!C:\
\Users\\WANGYAWEI\\Desktop\\ice2.0\\kylin-operation\\node_modules\\@builder\\pack\\deps\\postcss-loader\\cjs.js??ruleSet[1].rules[4].use[2]!C:\\Users\\WANGYAWEI\\Desktop\\ice2.0\\kylin-operation\\node_mo
dules\\@builder\\pack\\deps\\less-loader\\cjs.js??ruleSet[1].rules[4].use[3]!C:\\Users\\WANGYAWEI\\Desktop\\ice2.0\\kylin-operation\\node_modules\\yr-loan-antd\\esm\\component\\DataSelectionCategory\\YRLoanFormulaVariateEditor\\index.less',
ERR! Fail to pre build dependencies       moduleName: './node_modules/yr-loan-antd/esm/component/DataSelectionCategory/YRLoanFormulaVariateEditor/index.less.webpack[javascript/auto]!=!./node_modules/@bui
lder/pack/deps/css-loader/cjs.js??ruleSet[1].rules[4].use[1]!./node_modules/@builder/pack/deps/postcss-loader/cjs.js??ruleSet[1].rules[4].use[2]!./node_modules/@builder/pack/deps/less-loader/cjs.js??ruleSet[1].rules[4].use[3]!./node_modules/yr-loan-antd/esm/component/DataSelectionCategory/YRLoanFormulaVariateEditor/index.less',
ERR! Fail to pre build dependencies       message: 'Module build failed (from ./node_modules/@builder/pack/deps/postcss-loader/cjs.js):\n' +
ERR! Fail to pre build dependencies         "TypeError: Cannot read property 'raws' of undefined\n" +
ERR! Fail to pre build dependencies         '    at Parser.space (C:\\Users\\WANGYAWEI\\Desktop\\ice2.0\\kylin-operation\\node_modules\\@builder\\pack\\deps\\postcss-preset-env\\index.js:46735:25)\n' +  
ERR! Fail to pre build dependencies         '    at Parser.parseTokens (C:\\Users\\WANGYAWEI\\Desktop\\ice2.0\\kylin-operation\\node_modules\\@builder\\pack\\deps\\postcss-preset-env\\index.js:46571:14)\n' +
ERR! Fail to pre build dependencies         '    at Parser.loop (C:\\Users\\WANGYAWEI\\Desktop\\ice2.0\\kylin-operation\\node_modules\\@builder\\pack\\deps\\postcss-preset-env\\index.js:46480:12)\n' +   
ERR! Fail to pre build dependencies         '    at Parser.parse (C:\\Users\\WANGYAWEI\\Desktop\\ice2.0\\kylin-operation\\node_modules\\@builder\\pack\\deps\\postcss-preset-env\\index.js:46399:17)\n' +  
ERR! Fail to pre build dependencies         '    at parse (C:\\Users\\WANGYAWEI\\Desktop\\ice2.0\\kylin-operation\\node_modules\\@builder\\pack\\deps\\postcss-preset-env\\index.js:24883:30)\n' +
ERR! Fail to pre build dependencies         '    at C:\\Users\\WANGYAWEI\\Desktop\\ice2.0\\kylin-operation\\node_modules\\@builder\\pack\\deps\\postcss-preset-env\\index.js:24909:42\n' +
ERR! Fail to pre build dependencies         '    at Array.forEach (<anonymous>)\n' +
ERR! Fail to pre build dependencies         '    at C:\\Users\\WANGYAWEI\\Desktop\\ice2.0\\kylin-operation\\node_modules\\@builder\\pack\\deps\\postcss-preset-env\\index.js:24905:26\n' +
ERR! Fail to pre build dependencies         '    at Array.forEach (<anonymous>)\n' +
ERR! Fail to pre build dependencies         '    at getCustomPropertiesFromRoot (C:\\Users\\WANGYAWEI\\Desktop\\ice2.0\\kylin-operation\\node_modules\\@builder\\pack\\deps\\postcss-preset-env\\index.js:24901:22)'
ERR! Fail to pre build dependencies     },
ERR! Fail to pre build dependencies     {
ERR! Fail to pre build dependencies       moduleIdentifier: 'C:\\Users\\WANGYAWEI\\Desktop\\ice2.0\\kylin-operation\\node_modules\\@builder\\pack\\deps\\css-loader\\cjs.js??ruleSet[1].rules[4].use[1]!C:\
\Users\\WANGYAWEI\\Desktop\\ice2.0\\kylin-operation\\node_modules\\@builder\\pack\\deps\\postcss-loader\\cjs.js??ruleSet[1].rules[4].use[2]!C:\\Users\\WANGYAWEI\\Desktop\\ice2.0\\kylin-operation\\node_mo
dules\\@builder\\pack\\deps\\less-loader\\cjs.js??ruleSet[1].rules[4].use[3]!C:\\Users\\WANGYAWEI\\Desktop\\ice2.0\\kylin-operation\\node_modules\\yr-loan-antd\\esm\\component\\DataSelectionCategory\\YRLoanUserSelected\\index.less',
ERR! Fail to pre build dependencies       moduleName: './node_modules/yr-loan-antd/esm/component/DataSelectionCategory/YRLoanUserSelected/index.less.webpack[javascript/auto]!=!./node_modules/@builder/pac
k/deps/css-loader/cjs.js??ruleSet[1].rules[4].use[1]!./node_modules/@builder/pack/deps/postcss-loader/cjs.js??ruleSet[1].rules[4].use[2]!./node_modules/@builder/pack/deps/less-loader/cjs.js??ruleSet[1].rules[4].use[3]!./node_modules/yr-loan-antd/esm/component/DataSelectionCategory/YRLoanUserSelected/index.less',
ERR! Fail to pre build dependencies       message: 'Module build failed (from ./node_modules/@builder/pack/deps/postcss-loader/cjs.js):\n' +
ERR! Fail to pre build dependencies         "TypeError: Cannot read property 'raws' of undefined\n" +
ERR! Fail to pre build dependencies         '    at Parser.space (C:\\Users\\WANGYAWEI\\Desktop\\ice2.0\\kylin-operation\\node_modules\\@builder\\pack\\deps\\postcss-preset-env\\index.js:46735:25)\n' +  
ERR! Fail to pre build dependencies         '    at Parser.parseTokens (C:\\Users\\WANGYAWEI\\Desktop\\ice2.0\\kylin-operation\\node_modules\\@builder\\pack\\deps\\postcss-preset-env\\index.js:46571:14)\n' +
ERR! Fail to pre build dependencies         '    at Parser.loop (C:\\Users\\WANGYAWEI\\Desktop\\ice2.0\\kylin-operation\\node_modules\\@builder\\pack\\deps\\postcss-preset-env\\index.js:46480:12)\n' +   
ERR! Fail to pre build dependencies         '    at Parser.parse (C:\\Users\\WANGYAWEI\\Desktop\\ice2.0\\kylin-operation\\node_modules\\@builder\\pack\\deps\\postcss-preset-env\\index.js:46399:17)\n' +  
ERR! Fail to pre build dependencies         '    at parse (C:\\Users\\WANGYAWEI\\Desktop\\ice2.0\\kylin-operation\\node_modules\\@builder\\pack\\deps\\postcss-preset-env\\index.js:24883:30)\n' +
ERR! Fail to pre build dependencies         '    at C:\\Users\\WANGYAWEI\\Desktop\\ice2.0\\kylin-operation\\node_modules\\@builder\\pack\\deps\\postcss-preset-env\\index.js:24909:42\n' +
ERR! Fail to pre build dependencies         '    at Array.forEach (<anonymous>)\n' +
ERR! Fail to pre build dependencies         '    at C:\\Users\\WANGYAWEI\\Desktop\\ice2.0\\kylin-operation\\node_modules\\@builder\\pack\\deps\\postcss-preset-env\\index.js:24905:26\n' +
ERR! Fail to pre build dependencies         '    at Array.forEach (<anonymous>)\n' +
ERR! Fail to pre build dependencies         '    at getCustomPropertiesFromRoot (C:\\Users\\WANGYAWEI\\Desktop\\ice2.0\\kylin-operation\\node_modules\\@builder\\pack\\deps\\postcss-preset-env\\index.js:24901:22)'
ERR! Fail to pre build dependencies     },
ERR! Fail to pre build dependencies   ]
ERR! Fail to pre build dependencies }
`

## What is the expected behavior? 期望的结果是什么？

编译不出现以上错误

## Any additional comments? 相关环境信息？

- **ice.js Version**：2.6.4
- **build.json Configuration**：

`
module.exports = {
  publicPath,
  remoteRuntime: true,
  devPublicPath: `${packageJson.appEntry}/`, 
  browserslist: {
    chrome: 49,
    ie: 11
  },
  hash: 'contenthash',
  plugins: [
    [
      'build-plugin-icestark',
      {
        umd: true
      }
    ],
    [
      'build-plugin-antd',
      {
        themeConfig: {
          'primary-color': '#1890FF'
        }
      }
    ],
    [
      'build-plugin-moment-locales',
      {
        locales: ['zh-cn']
      }
    ],
  ],
};
`

- **Node Version**:  14.17.4
- **Platform**: win11

**Comment by ClarkXia** [comment]
升级的话 确保已完全删除 node_modules，如果可以提供个简单的复现 demo

**Comment by flyce** [comment]
`npm i --save postcss` 即可

**Comment by ClarkXia** [comment]
npm list postcss 可以看下 postcss 整体的依赖关系，确认下依赖是否正确
