### ISSUE TITLE
升级到2.6.4之后编译时很多warning

### ISSUE THREAD

**Issue by komaedaXnagito** [alibaba/ice#5445]
## What is the current behavior? 发生了什么？

warning: Top-level "this" will be replaced with undefined since this file is an ECMAScript module
<img width="953" alt="image" src="https://user-images.githubusercontent.com/26919146/183600677-d33cdfae-797b-4407-bb01-56e9a1391882.png">

## Any additional comments? 相关环境信息？

- **ice.js Version**：
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by ClarkXia** [comment]
已有 issue 记录，可以参考配置 vite 配置项，后续将内置优化 #5401

**Comment by ZindexYG** [comment]
配置优化如下 ``build.json``

```JSON


{
  "vite": {
    "esbuild": {
      "logOverride": { "this-is-undefined-in-esm": "silent" }
    }
  },
}
```
