### ISSUE TITLE
请问下vite模式下如何自定义配置工程，目前我们需要增加第三方vite插件，但不知道如何下手，文档也没看到，也是走chainWebpack这套吗

### ISSUE THREAD

**Issue by jeryqwq** [alibaba/ice#5446]
## Any additional comments? 相关环境信息？

- **ice.js Version**：
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by ClarkXia** [comment]
vite 字段下可以配置 vite 相关配置：

```js
{
  vite: { ...viteConfig }
}
```

**Comment by jeryqwq** [comment]
感谢

**Comment by jeryqwq** [comment]
感谢 @ClarkXia
