### ISSUE TITLE
如何在app.tsx中使用路由跳转？

### ISSUE THREAD

**Issue by strongyc** [alibaba/ice#5456]
在实际使用过程中，在app.tsx中对返回值进行判断，比如过期后跳转至登录页，但是在response 不支持使用history，该如何进行跳转
 response: {
        onConfig: (response) => {
          NProgress.done();
          // 请求成功：可以做全局的 toast 展示，或者对 response 做一些格式化
          console.log(response.data.code);
          if (
            response.data.code === 1011006 ||
            response.data.code === 1011007 ||
            response.data.code === 1011008 ||
            response.data.code === 1011009
          ) {
            message.error('登录过期,请重新登录');
            sessionStorage.clear();
     
   
            // return
          }
          if (!response.data.success) {
            message.error(response.data.message);
          }
          // console.log('respopnse----', response)
          return response;
        },

**Comment by ClarkXia** [comment]
```js
import { history } from 'ice';

// 在请求回调里面调用 history 相关 api
```
