### ISSUE TITLE
vite模式创建脚手架后修改静态文件代码无法热刷新

### ISSUE THREAD

**Issue by hdl1995** [alibaba/ice#5460]
vite模式创建脚手架后修改静态文件代码无法热刷新，需要怎么配置呀

**Comment by ClarkXia** [comment]
![image](https://user-images.githubusercontent.com/4219965/185862037-69e4e2ee-8ae8-4d44-9421-c14b957538e1.png)
确认下 具体修改的是什么文件

**Comment by hdl1995** [comment]
修改public的html文件，这个是不能进行热刷新编译的吗

**Comment by ClarkXia** [comment]
public 目录不参与编译 也就不会热更新 刷新下页面即可
