### ISSUE TITLE
通过 npm link 调试组件

### ISSUE THREAD

**Issue by ClarkXia** [alibaba/ice#5462]
通过 npm link 方式调试项目，会导致项目启动卡死

**Comment by Maconzhang** [comment]
我也是!!!  51%就卡死了!

**Comment by ClarkXia** [comment]
通过软链的方式调试，如果依赖复杂可能会造成循环依赖解析，导致 webpack 进度卡住，可以通过依赖方式解决：

```js
// 新增 ice 插件，配置相应的软链设置

module.exports = ({ onGetWebpackConfig }) => {
  onGetWebpackConfig((config) => {
    config.resolve.symlinks(false);
  });
};
```

参考文档 webpack [resolve.symlinks](https://webpack.js.org/configuration/resolve/#resolvesymlinks)
