### ISSUE TITLE
index.html根据不同的环境需要加载不同的js监控文件到head里边,该怎么做

### ISSUE THREAD

**Issue by hyuanyuanlisiwei** [alibaba/ice#5464]
## Any additional comments? 相关环境信息？

- **ice.js Version**：
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by hyuanyuanlisiwei** [comment]
![2F2F7951-D40F-4923-B127-F644DD3D75AF](https://user-images.githubusercontent.com/11502089/186051084-b5f32658-5177-47ae-a1cf-7c3ee892e387.png)
![41E1DCE9-E533-425D-95AF-0A77F2D0D385](https://user-images.githubusercontent.com/11502089/186051097-a102017a-dc76-4b49-9c78-7df6b8086fdf.png)

**Comment by hyuanyuanlisiwei** [comment]
我这样写, 会出现白屏,  这样写不对吗

**Comment by ClarkXia** [comment]
注入方式参考 https://github.com/alibaba/ice/blob/master/packages/plugin-mpa/src/index.ts#L216
使用方式参考 https://ice.work/docs/guide/advanced/mpa/#%E9%80%9A%E8%BF%87-ejs-%E8%AF%AD%E6%B3%95%E5%AE%9A%E5%88%B6%E4%B8%8D%E5%90%8C%E9%A1%B5%E9%9D%A2%E7%9A%84-html-%E5%86%85%E5%AE%B9
