### ISSUE TITLE
ice不用vite模式打包报错

### ISSUE THREAD

**Issue by wxadrtyu** [alibaba/ice#5466]
ValidationError: Invalid options object. Less Loader has been initialized using an options object that does not match the API schema.
ERR!  - options has an unknown property 'modifyVars'. These properties are valid:
ERR!    object { lessOptions?, additionalData?, sourceMap?, webpackImporter?, implementation? }

**Comment by wxadrtyu** [comment]
我项目中没有用less

**Comment by wxadrtyu** [comment]
更没有less的配置

**Comment by ClarkXia** [comment]
配置以及 package.json 信息提供下，大概率是版本之间的匹配问题，可以先尝试 更新下依赖

**Comment by ClarkXia** [comment]
官方 demo 无法复现，提供复现项目后可以重开 issue
