### ISSUE TITLE
定制antd 主题 不管用

### ISSUE THREAD

**Issue by hyuanyuanlisiwei** [alibaba/ice#5469]
["build-plugin-antd", {
      "disableModularImport": true,
      "themeConfig": {
        "primary-color": "#007db8"
      }
    }]

**Comment by ClarkXia** [comment]
disableModularImport 后，你的样式是怎么加载的

**Comment by hyuanyuanlisiwei** [comment]
> disableModularImport 后，你的样式是怎么加载的
在 global.css中引入
@import 'antd/dist/antd.min.css';

**Comment by hyuanyuanlisiwei** [comment]
我用的是 postcss 没有用 less

**Comment by ClarkXia** [comment]
参考 #5473 的回复
