### ISSUE TITLE
[QUESTION]如何设置style属性的默认像素单位

### ISSUE THREAD

**Issue by xmsz** [alibaba/ice#5472]
背景
代码
```
<div style={{
   fontSize: 24
}}>asd</div>

```
默认情况下，react会补全为24px

如果我想要把他变成vw，或者搭配其他px2vw的插件 有没有什么好的做法？

**Comment by ClarkXia** [comment]
如果支持类似做法需要劫持 jsx-runtime，这种方式并不推荐，样式上可以统一成 css 文件的方式，走 postcss 插件

**Comment by xmsz** [comment]
> 如果支持类似做法需要劫持 jsx-runtime，这种方式并不推荐，样式上可以统一成 css 文件的方式，走 postcss 插件

就是推荐把样式写在css文件中是吗
我看3.0有支持raxjs属性转换成rpx的能力

**Comment by ClarkXia** [comment]
单一项目样式逻辑统一，既都写到 css 中。
3.0 考虑以插件形式提供这个转换能力，提供 css 和 style 的统一转换（rpx to vw），但是也不支持不写单位的
