### ISSUE TITLE
怎么定制antd 主题样式.

### ISSUE THREAD

**Issue by hyuanyuanlisiwei** [alibaba/ice#5473]
1, 使用 post css + css module.
2, build.json中配置如下:
![image](https://user-images.githubusercontent.com/11502089/187108658-095e56b1-b8d8-442e-8bf3-8227bd669033.png)
3, global.css 文件中引入样式:![image](https://user-images.githubusercontent.com/11502089/187108702-920bbd9a-91ae-41da-b44c-f31adde46af7.png)

请问大佬我这样写 为啥设置的 primary-color不生效呢

**Comment by ClarkXia** [comment]
themeConfig 仅对 less 样式生效，如果导入 css 可以考虑 css variables 的变量方案

**Comment by hyuanyuanlisiwei** [comment]
> css variables 的变量方案  有文档吗

**Comment by hyuanyuanlisiwei** [comment]
> themeConfig 仅对 less 样式生效，如果导入 css 可以考虑 css variables 的变量方案

算了 我用less

**Comment by ClarkXia** [comment]
> > css variables 的变量方案  有文档吗

参考 dist/antd.variable.css 文件

**Comment by aiqin-bao** [comment]
为什么不考虑scss ？？？
