### ISSUE TITLE
通过ice工程编译后，css样式的选择器名字会变化，怎么保持不变

### ISSUE THREAD

**Issue by onion555** [alibaba/ice#5475]
比如我有个css文件，
里面有个类选择器
.hello {
 background:red
}

但是启动网页后，类选择器名字会变为
._hello_x5e3o_16

请问怎么禁止掉这个行为

**Comment by ClarkXia** [comment]
参考下 https://ice.work/docs/guide/basic/style
如果不使用 css modules，可以将文件命名为 index.css 直接 `import './index.css'` 就行
