### ISSUE TITLE
useParams取值问题

### ISSUE THREAD

**Issue by Chengminshu** [alibaba/ice#5479]
build.json文件中添加build-plugin-keep-alive插件会导致全局使用useParams取值为空对象

**Comment by ClarkXia** [comment]
build-plugin-keep-alive 暂时不推荐使用，会存在一些问题，方案正常重新设计（依赖 react-router v6），临时可以参考 #5304

**Comment by luuwang** [comment]
> build-plugin-keep-alive 暂时不推荐使用，会存在一些问题，方案正常重新设计（依赖 react-router v6），临时可以参考 #5304

您好，这个方案重新设计有时间规划吗，预计什么时候可以使用，谢谢
