### ISSUE TITLE
使用Appworks下载物料后 install依赖出现问题

### ISSUE THREAD

**Issue by chengjunjian2020** [alibaba/ice#5481]
## What is the current behavior? 发生了什么？

![image](https://user-images.githubusercontent.com/40468022/189264150-b1f0fbd7-3b40-4412-93bc-43210cbe0de9.png)
采用这个物料下载后安装失败
![image](https://user-images.githubusercontent.com/40468022/189264183-266eea03-c12d-43e7-a678-893128283dba.png)
是因为物料react版本问题吗？需要设置到react16版本?

## What is the expected behavior? 期望的结果是什么？

我期望正确安装运行起来
## Any additional comments? 相关环境信息？
nodejs 17.0.0
npm 8.1.0

**Comment by ClarkXia** [comment]
嗯 bizchart 写的 peerDependencies 要求 react 是 15 / 16，实际为 17，临时可以通过 `npm install --legacy-peer-deps` 来处理
