### ISSUE TITLE
edge浏览器 开发环境下，sourcemap无效，是我这里的个例么？

### ISSUE THREAD

**Issue by inier** [alibaba/ice#5482]
chrome浏览器
![image](https://user-images.githubusercontent.com/7600897/189633165-eb86fe3f-45ee-4f19-a462-2f6806341de9.png)

edge
![image](https://user-images.githubusercontent.com/7600897/189633344-e8ae229f-db30-497a-90a6-47a876a7f3ac.png)

奇怪了

**Comment by inier** [comment]
发现问题了，http被限制了，开启https就可以了。还有其他方案么？

**Comment by wssgcg1213** [comment]
是不是你的 origin 是 https 协议, 由于同源策略被限制了?

**Comment by ClarkXia** [comment]
http 被限制应该是浏览器同源策略影响
