### ISSUE TITLE
HookWebpackError: __dirname is not defined

### ISSUE THREAD

**Issue by wuwei111467** [alibaba/ice#5483]
## Any additional comments? 相关环境信息？

- **ice.js Version**：
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by wuwei111467** [comment]
"ice.js": "2.6.4",
{
  "mpa": true,
  "outputDir": "../dist/assets",
  "publicPath": "./",
  "minify": "esbuild",
  "plugins": [
    [
      "build-plugin-fusion",
      {
        "themePackage": "@alifd/theme-design-pro"
      }
    ],
    [
      "build-plugin-moment-locales",
      {
        "locales": [
          "zh-cn"
        ]
      }
    ],
    "build-plugin-css-assets-local",
    "./build.plugin.js"
  ]
}

**Comment by ClarkXia** [comment]
提供下详细的错误堆栈，已经自定义插件中的内容

**Comment by wuwei111467** [comment]
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/13595350/190043639-5a1835d1-36eb-45a5-b47e-fd6786ea8b3c.png">

**Comment by wuwei111467** [comment]
> 

启动 apptoolkit项目报的错

**Comment by wuwei111467** [comment]
https://github.com/apptools-lab/AppToolkit/issues/84

**Comment by luhc228** [comment]
在 AppToolkit  issue 里处理
