### ISSUE TITLE
怎么配置飞冰, 让项目支持ttf 字体格式的文件

### ISSUE THREAD

**Issue by hyuanyuanlisiwei** [alibaba/ice#5488]
## Any additional comments? 相关环境信息？

- **ice.js Version**：
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by ClarkXia** [comment]
https://github.com/alibaba/ice/blob/5670bf1e17eab612a1d295e10406861056bdf930/packages/build-webpack-config/src/setWebpackLoaders.ts#L114
默认会处理 ttf 格式，看具体遇到什么问题

**Comment by hyuanyuanlisiwei** [comment]
sorry 我说错了, 怎么支持otf 文件格式
