### ISSUE TITLE
怎么配置飞冰, 支持otf 文件格式

### ISSUE THREAD

**Issue by hyuanyuanlisiwei** [alibaba/ice#5489]
## Any additional comments? 相关环境信息？

- **ice.js Version**：
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by ClarkXia** [comment]
定制下 webpack 的 [loader 配置](https://ice.work/docs/config/about/#pwa-)，比如：

```js
webpackLoaders: {
  file: {
    test: /.(otf)$/,
    type: 'asset/resource',
    loaders: {
      'file-loader': {},
    },
    include: ['src'],
  }
}
```
