### ISSUE TITLE
行内样式px转rem有方案吗？

### ISSUE THREAD

**Issue by jiang-zhong-xi** [alibaba/ice#5495]
## Any additional comments? 相关环境信息？

- **ice.js Version**：
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by ClarkXia** [comment]
行内样式需要 babel 等工具编译转化

**Comment by lbarakidouji** [comment]
可以自己写一个 loader

**Comment by ClarkXia** [comment]
行内样式 px 转 rem 并不是推荐的方式，需要自行实现对应语法的转化
