### ISSUE TITLE
vite 和 mpa 同时开启的状态下，图片引入报错

### ISSUE THREAD

**Issue by dingff** [alibaba/ice#5496]
## What is the current behavior? 发生了什么？
vite 和 mpa 同时开启的状态下，图片引入报错，使用官方Typescript+FusionDesign 模板即可复现

![image](https://user-images.githubusercontent.com/69964024/192485120-80ee09c8-25ca-4da2-bac7-ee23fa160969.png)

## What is the expected behavior? 期望的结果是什么？
期望正常显示图片
## Any additional comments? 相关环境信息？

- **ice.js Version**：2.6.6
- **build.json Configuration**：
- **Node Version**: 14.19.1
- **Platform**: macOS Monterey

**Comment by dingff** [comment]
这个是 bug 吗，还是说 mpa 不支持 vite

**Comment by ClarkXia** [comment]
在 vite 模式下推荐这样引入图片 url： `const imgUrl = new URL('./pic.png', import.meta.url).href;`
