### ISSUE TITLE
mpa 和 remoteRuntime 同时开启时报错

### ISSUE THREAD

**Issue by dingff** [alibaba/ice#5497]
## What is the current behavior? 发生了什么？
mpa 和 remoteRuntime 同时开启时报错，使用官方 typescript + fusionDesign 模板即可复现

![image](https://user-images.githubusercontent.com/69964024/192662881-631ef8c3-b6b6-4519-aa06-b6771b7f67b7.png)
## What is the expected behavior? 期望的结果是什么？
页面正常显示
## Any additional comments? 相关环境信息？

- **ice.js Version**：2.6.6
- **build.json Configuration**：
- **Node Version**：14.19.1
- **Platform**：macOS Monterey

**Comment by ClarkXia** [comment]
remoteRuntime 目前不支持 mpa 模式，后续大版本中将通过分包及编译缓存的形式提升本地调试体验
