### ISSUE TITLE
ice.js1.8.5 升级到 icejs 2.6.6 

### ISSUE THREAD

**Issue by zhouzhuifeng** [alibaba/ice#5501]
**ice.js1.8.5 升级到 icejs 2.6.6 后，路由 添加懒加载后 [webpack-dev-server] WARNING,去掉懒加载警告消失**

  import { lazy } from 'ice'; 
 const Index = lazy(() => import('@/pages/index')); 

[webpack-dev-server] WARNING
chunk vendors-node_modules___alifd_next_1_26_2_alifd_next_es_cascader-select_index_js-node_modules_-ca4093 [mini-css-extract-plugin]
Conflicting order. Following module has been added:
 * css ./node_modules/_@builder_pack@0.6.5@@builder/pack/deps/css-loader/cjs.js??ruleSet[1].rules[2].use[1]!./node_modules/_@builder_pack@0.6.5@@builder/pack/deps/postcss-loader/cjs.js??ruleSet[1].rules[2].use[2]!./node_modules/_@builder_pack@0.6.5@@builder/pack/deps/resolve-url-loader/index.js??ruleSet[1].rules[2].use[3]!./node_modules/_build-plugin-fusion@0.1.23@build-plugin-fusion/lib/webpackLoaders/unicodeLoader.js!./node_modules/_@builder_pack@0.6.5@@builder/pack/deps/sass-loader/cjs.js??ruleSet[1].rules[2].use[5]!./node_modules/_ice-skin-loader@0.3.2@ice-skin-loader/lib/index.js??ruleSet[1].rules[2].use[6]!./node_modules/_@alifd_next@1.26.2@@alifd/next/es/cascader/main.scss
despite it was not able to fulfill desired ordering with these modules:
 * css ./node_modules/_@builder_pack@0.6.5@@builder/pack/deps/css-loader/cjs.js??ruleSet[1].rules[2].use[1]!./node_modules/_@builder_pack@0.6.5@@builder/pack/deps/postcss-loader/cjs.js??ruleSet[1].rules[2].use[2]!./node_modules/_@builder_pack@0.6.5@@builder/pack/deps/resolve-url-loader/index.js??ruleSet[1].rules[2].use[3]!./node_modules/_build-plugin-fusion@0.1.23@build-plugin-fusion/lib/webpackLoaders/unicodeLoader.js!./node_modules/_@builder_pack@0.6.5@@builder/pack/deps/sass-loader/cjs.js??ruleSet[1].rules[2].use[5]!./node_modules/_ice-skin-loader@0.3.2@ice-skin-loader/lib/index.js??ruleSet[1].rules[2].use[6]!./node_modules/_@alifd_next@1.26.2@@alifd/next/es/date-picker2/main.scss
   - couldn't fulfill desired order of chunk group(s) , , , , , , , 
   - while fulfilling desired order of chunk group(s) , , , , , , , , , , , , ,

**Comment by ClarkXia** [comment]
Conflicting order 仅仅是一个提示，可以不用关心。可以通过以下方式定制参数：

```js
config.plugin('MiniCssExtractPlugin').tap(([args]) => [{ ...args,  ignoreOrder: true }]);
```
