### ISSUE TITLE
Strange error message

### ISSUE THREAD

**Issue by usercao** [alibaba/ice#5503]
https://user-images.githubusercontent.com/13760476/194694673-ddcbca70-3970-416f-a1c4-c5c0a732c58d.mp4

升级`2.6.6`后控制台一直有不断的log产生

**Comment by luhc228** [comment]
2.6.5 是没有问题？

**Comment by usercao** [comment]
是的

**Comment by usercao** [comment]
可复现项目[icejs](https://github.com/usercao/ice-test)

**Comment by usercao** [comment]
@luhc228 同时这个问题 #5288 也再次出现了，希望一同修正

**Comment by ClarkXia** [comment]
![image](https://user-images.githubusercontent.com/4219965/195244704-c69b2b58-05ee-490b-b2b4-1da50b9c2959.png)
这个日志不是 ice 输出的，browserlist 问题下个版本统一修复
