### ISSUE TITLE
animation没生效

### ISSUE THREAD

**Issue by samaritanz** [alibaba/ice#5510]
## What is the current behavior? 发生了什么？

animation中name没有混淆，@keyframes中name混淆了，导致animation无法生效

<img width="795" alt="截屏2022-10-16 18 40 10的副本2" src="https://user-images.githubusercontent.com/62387737/196030828-2534b1c6-0bce-4d8e-b379-9e4728fa6edc.png">

## What is the expected behavior? 期望的结果是什么？
animation动画正常运行
## Any additional comments? 相关环境信息？

- **ice.js Version**：^2.0.0
- **build.json Configuration**：
- 
 {
  "vite": true,
  "alias": {
    "venn.js": "venn.js/build/venn.js"
  },
  "plugins": [
    [
      "build-plugin-moment-locales",
      {
        "locales": [
          "zh-cn"
        ]
      }
    ],
    [
      "build-plugin-ignore-style",
      {
        "libraryName": "@alifd/next"
      }
    ]
  ]
}

- **Node Version**:16.10.0
- **Platform**: mac

**Comment by ClarkXia** [comment]
提供下原始的 css 样式及使用方式

**Comment by luhc228** [comment]
本地试了下是 ok 的，检查下源码写得是否正确

**Comment by samaritanz** [comment]
```js

  .next-progress-line-overlay {
          height: calc(100% - 2px);
          transform: translateY(-50%);
          margin-top: 0;
          border-radius: 0;
          background: #f7931e;
          position: relative;
          display: inline-block;
          overflow: hidden;
          &::before {
            display: inline-block;
            position: absolute;
            content: '';
            left: 0;
            top: 0;
            width: 100%;
            height: 100%;
            transform: translateX(-100%);
            background: linear-gradient(120deg, transparent, red, transparent);
            animation: moveIt 5s infinite;
          }
        }

@keyframes moveIt {
  0% {
    transform: translateX(-100%);
  }

  50% {
    transform: translateX(0);
  }
  100% {
    transform: translateX(100%);
  }
}
```

单独写一个页面 加样式没问题

**Comment by samaritanz** [comment]
我的动画改到global.scss，名称都未混淆，动画可以正常出来
