### ISSUE TITLE
飞冰内依赖可以升级吗

### ISSUE THREAD

**Issue by chengjunjian2020** [alibaba/ice#5511]
我加入钉钉群 但是没看到一个群之类的加入组织呢，所以有些疑问在这里提问
关于keep-alive 好像不支持动态开启、关闭某个页面keep-alive功能？文档没有
可以升级react-router-domv6版本吗，因为v6支持很多新功能特性，不知道会不会出问题？
react支持升级到18吗？会不会出问题

**Comment by ClarkXia** [comment]
参考 https://github.com/ice-lab/ice-next

**Comment by ClarkXia** [comment]
内置依赖不推荐自己升级，因为涉及到 API 的使用

**Comment by chengjunjian2020** [comment]
> 参考https://github.com/ice-lab/ice-next

这个成熟吗？我看到是Beta版本

**Comment by ClarkXia** [comment]
近期会发布 可以使用 release 版本
