### ISSUE TITLE
template @alifd/scaffold-simple 报错

### ISSUE THREAD

**Issue by hm496** [alibaba/ice#5514]
## What is the current behavior? 发生了什么？

复现步骤：
```bash
npm init ice testProject --template @alifd/scaffold-simple
yarn
# 修改 build.json 中 vite 为 false
yarn start
# 错误信息：
ValidationError: Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
options has an unknown property 'setupMiddlewares'. 
 ```

## What is the expected behavior? 期望的结果是什么？
正常运行不报错
应该如何修改配置正常运行？

## Any additional comments? 相关环境信息？

- **ice.js Version**：2.4.2
- **build.json Configuration**：
将 vite 修改为了 false
{
  "vite": false,
  "plugins": []
}
- **Node Version**: v14.20.0
- **Platform**: Mac

**Comment by ClarkXia** [comment]
用最新版本 2.6.6

**Comment by hm496** [comment]
谢谢，我试一下
