### ISSUE TITLE
mac本地代理proxy 请求特别慢， 大于1分钟的

### ISSUE THREAD

**Issue by yxiawen** [alibaba/ice#5517]
本地proxy代理请求特别慢或者代理失败，
失败代码
proxy server error: connect ETIMEDOUT 
而且仅仅是在本地开发环境下才会出现这种情况，部署到测试环境并不会
node 版本
v18.11.0
 "ice.js": "^2.0.0",
<img width="274" alt="image" src="https://user-images.githubusercontent.com/21170741/197447044-01b549da-cbc9-48f4-875c-587e9dd957da.png">

![image](https://user-images.githubusercontent.com/21170741/197446102-65016b07-781b-4818-afa5-1f4b817506ae.png)

**Comment by ClarkXia** [comment]
可以判断下代理地址和本地之间的网络情况

**Comment by ClarkXia** [comment]
proxy 网络问题可以先简单定位下原因，后续有更多信息 可以重开 issue
