### ISSUE TITLE
Monorepo 子项目配置问题

### ISSUE THREAD

**Issue by aak1247** [alibaba/ice#5518]
是否支持Monorepo 子项目继承通用配置？

**Comment by ClarkXia** [comment]
项目配置可以配置成 js，可用走模块的方式扩展

**Comment by aak1247** [comment]
是只有ice3才能享受的高级特性么= ice2似乎还不支持啊

**Comment by ClarkXia** [comment]
ice2 也支持 js 的配置

**Comment by aak1247** [comment]
多问一句 @ClarkXia 用ice3的ice.config.mts吗？(依赖@ice/app）
