### ISSUE TITLE
ice-scripts1.x升级到ice.js1.x后，菜单样式缺失

### ISSUE THREAD

**Issue by Symous** [alibaba/ice#5523]
## What is the current behavior? 发生了什么？
最近将一个老的项目（ice-scripts+@icedesign组件）升级到了ice.js1.x，经过各种各样的兼容性处理，最终成功跑了起来，但是遇到一个棘手的问题，原本的菜单部分（@icedesign/menu）样式缺失导致显示异常，除此其他组件全部显示正常；

原本的样式：
![image](https://user-images.githubusercontent.com/13534034/199386743-2bfc5680-708e-4b5b-ad50-f639ebd01790.png)

升级后的样式：
![image](https://user-images.githubusercontent.com/13534034/199386772-c3778e55-7784-4c36-a022-a1fc32612253.png)

观察到相关的ice-menu样式未加载成功，查找了相关issue及官方文档都没有相关的问题和方案，百思不得其解，请问改如何处理；
## Any additional comments? 相关环境信息？

- **ice.js Version**：1.86.1
- **build.json Configuration**：
```js
{
    "entry": "src/index.js",
    "alias": {
        "@": "./src/"
    },
    "disableRuntime": true,
    "plugins": [
        "./build.plugin.js",
        [
            "build-plugin-fusion",
            {
                "themePackage": "@icedesign/skin",
                "localization": true,
                "publicURL": "./"
            }
        ]
    ],
    "proxy": {
        
    }
}
```
- **Node Version**: 16.15.0
- **Platform**: MacOS 12.4

**Comment by ClarkXia** [comment]
`@icedesign/menu` 比较老的组件，在 icejs 中自动加载样式是通过组件 package.json 中的 stylePath / componentConfig 来决定的，`@icedesign/menu` 中没看到对应设置，可以先手动导入

**Comment by Symous** [comment]
@ClarkXia 抱歉，刚刚issue没写完误点了提交，我补充了一下内容；
没太理解我具体需要怎么做，能不能指点一下，目前除了menu显示异常，其他都是正常的，谢谢。

**Comment by Symous** [comment]
@ClarkXia 我搜了一下过往的issue，发现之前你们的配置[记录日志](https://github.com/alibaba/ice/issues/3179)里面有提到stylePath，我按照里面的demo改造了一下，发现问题解决了。
```js
config
            .plugin('WebpackPluginImport')
            .use(WebpackPluginImport, [[
                {
                    libraryName: '@icedesign/menu',
                    stylePath: 'style.js',
                }
            ]])
```

**Comment by Symous** [comment]
不过我还是没太理解出现这个问题的原因是什么，是ice.js的bug吗。

**Comment by ClarkXia** [comment]
> `@icedesign/menu` 比较老的组件，在 icejs 中自动加载样式是通过组件 package.json 中的 stylePath / componentConfig 来决定的，`@icedesign/menu` 中没看到对应设置，可以先手动导入

上面回复中已经说明原因了

**Comment by Symous** [comment]
@ClarkXia 后续我又把ice.js升级到了最新的2.6.6，发现一个十分诡异的问题，上面提到的样式引入配置：
```js
config
            .plugin('WebpackPluginImport')
            .use(WebpackPluginImport, [[
                {
                    libraryName: '@icedesign/menu',
                    stylePath: 'style.js',
                }
            ]])
```

无论怎么改动（比如注释或关闭注释等）都不生效，即使我把dev-server关掉再重启也不行，必须要修改一下build.json才会使其生效，同时我也观察到一个启动速度的差异，只有修改build.json后，才像是”完全重启“了。未排查出具体原因，能不能把这个issue reopen一下。
