### ISSUE TITLE
build-plugin-css-assets-local实际无效

### ISSUE THREAD

**Issue by Symous** [alibaba/ice#5526]
## What is the current behavior? 发生了什么？
在build.json中根据[官方文档](https://ice.work/docs/plugin/list/css-assets-local/)使用build-plugin-css-assets-local插件本地化css相关资源时无效，在ice1.x和ice2.x均进行了测试；但是如果自行配置ExtractCssAssetsWebpackPlugin是可以正常工作的；

1. 使用build-plugin-css-assets-local时，可以看到相关字体文件未成功打包：
```
            "build-plugin-css-assets-local",
            {
                "outputPath": "assets",
                "relativeCssPath": "../"
            },
```
![image](https://user-images.githubusercontent.com/13534034/199864861-b0e700df-d138-4c64-a2cd-a0dc07650e1c.png)

2. 使用ExtractCssAssetsWebpackPlugin时，可以看到相关字体文件已成功打包：
```js
        config.plugin('ExtractCssAssetsWebpackPlugin')
            .use(ExtractCssAssetsWebpackPlugin, [{
                outputPath: 'assets',
                relativeCssPath: '../',
            }]);
```
![image](https://user-images.githubusercontent.com/13534034/199864992-d7374f23-cb4a-471d-9af7-101d0e457af5.png)

## Any additional comments? 相关环境信息？

- **ice.js Version**：2.6.6
- **build.json Configuration**：
```
{
    "entry": "src/index.js",
    "alias": {
        "@": "./src/"
    },
    "disableRuntime": true,
    "plugins": [
        "./build.plugin.js",
        [
            "build-plugin-fusion",
            {
                "themePackage": "@icedesign/skin",
            },
            // FIXME: 升级到2.x后，仍然无效...
            "build-plugin-css-assets-local",
            {
                "outputPath": "assets",
                "relativeCssPath": "../"
            }
        ]
    ],
    "proxy": {
        
    }
}

```
- **Node Version**: 16.15.0
- **Platform**: MacOS 12.4

**Comment by zaoy** [comment]
ice.js 2 >= 2.6.5 可以加 forceLocal 这个参数
[
      "build-plugin-css-assets-local",
      {
        "outputPath": "assets",
        "relativeCssPath": "../",
        "forceLocal": true,
        "activeInDev": true
      }
]

**Comment by ClarkXia** [comment]
插件有单独 dev 控制，可以参考 @zaoy 的回复
