### ISSUE TITLE
CONFIG Failed to load webpack config.

### ISSUE THREAD

**Issue by hcsygit** [alibaba/ice#5528]
## What is the current behavior? 发生了什么？
运行突然报错，使用1.18.6 就不会报这个错

<img width="1190" alt="image" src="https://user-images.githubusercontent.com/27758285/200566634-c1d1fb86-0270-4b3d-b0f4-cd060e0aef23.png">

## Any additional comments? 相关环境信息？

- **ice.js Version**：2.6.6
- **build.json Configuration**：{
  "devServer": {
    "writeToDisk": true
  },
  "mpa": true,
  "vendor": false,
  "publicPath": "./",
  "outputDir": "../build",
  "plugins": [
    [
      "build-plugin-fusion",
      {
      }
    ],
    [
      "build-plugin-moment-locales",
      {
        "locales": ["zh-cn"]
      }
    ],
    [
      "build-plugin-css-assets-local",
      {
        "activeInDev": true
      }
    ],
    "./build.plugin.js"
  ]
}

- **Node Version**: v14.19.3
- **Platform**: mac

**Comment by ClarkXia** [comment]
重新删除依赖再安装
