### ISSUE TITLE
使用history 需要怎么更改

### ISSUE THREAD

**Issue by 160905** [alibaba/ice#553]

**Comment by noyobo** [comment]
你的需求是什么？

**Comment by 160905** [comment]
路由模式选用这个BrowserRouter,当浏览器刷新的时候会出现404,我知道这个需要后台的支持.
我应该哪里去配置

**Comment by noyobo** [comment]
需要将 `/*` 所有路由都能请求到一个 html 文件。例如首页。

iceworks 里暂不支持  BrowserRouter 的调试模式。

**Comment by 160905** [comment]
我试过了 不管用

**Comment by noyobo** [comment]
那是配置没有生效吧，首先先看下 是否能请到到 html

**Comment by 160905** [comment]
<img width="435" alt="wx20180530-153657 2x" src="https://user-images.githubusercontent.com/22002759/40706182-8a66afc4-641f-11e8-8ad8-93b592f244ba.png">
这个配置没问题 吧

**Comment by noyobo** [comment]
不支持这样的写法吧，你可以 debug 下。

或者使用中间件来重定向

**Comment by noyobo** [comment]
我看文档中没有这样的写法的， 你 debug 下？ 请求进入这个逻辑么。

**Comment by chenbin92** [comment]
@160905 相关配置参考：

* https://github.com/ReactTraining/react-router/blob/v3/docs/guides/Histories.md#browserhistory

**Comment by F-loat** [comment]
``` js
// .webpackrc.js
module.exports = {
  devServer: {
    historyApiFallback: {
      rewrites: [
        { from: /.*/, to: 'http://localhost:4444/' },
      ]
    },
  },
};
```

**Comment by 160905** [comment]
谢谢 收到了


原始邮件
发件人:柴茂源notifications@github.com
收件人:alibaba/iceice@noreply.github.com
抄送:zznzzn497598593@126.com; Mentionmention@noreply.github.com
发送时间:2018年8月1日(周三) 16:40
主题:Re: [alibaba/ice] 使用history 需要怎么更改 (#553)


// .webpackrc.js module.exports = { devServer: { historyApiFallback: { rewrites: [ { from: /.*/, to: 'http://localhost:4444/' }, ] }, }, };
