### ISSUE TITLE
开启vite编译，antd时间组件国际化中文失败

### ISSUE THREAD

**Issue by p919533** [alibaba/ice#5530]
## What is the current behavior? 发生了什么？
antd 时间组件  国际化中文失败
<RangePicker />
<RangePicker showTime />

![image](https://user-images.githubusercontent.com/26241954/200798036-4dd8d4dd-b5b4-4229-b528-62c8651373e6.png)

## What is the expected behavior? 期望的结果是什么？
![image](https://user-images.githubusercontent.com/26241954/200798783-f358ad94-d0ae-46a3-b008-bb933aaaf93a.png)

## Any additional comments? 相关环境信息？

- **ice.js Version**：2.6.2
- **build.json Configuration**：
- {
  "vite": true, // 为false可以汉化
  "plugins": [
    [
      "build-plugin-ignore-style",
      {
        "libraryName": "antd"
      }
    ]
  ]
}
- **Node Version**: v14.17.1
- **Platform**:

**Comment by ClarkXia** [comment]
参考 https://github.com/alibaba/ice/issues/5420
