### ISSUE TITLE
希望build-plugin-css-assets-local插件relativeCssPath支持动态值

### ISSUE THREAD

**Issue by zaoy** [alibaba/ice#5531]
## What is the current behavior? 发生了什么？
ice 2.x 的 build-plugin-css-assets-local 插件的 relativeCssPath 无法设置动态值，比如不支持
```
[
      {
        "outputPath": "assets",
        "relativeCssPath": "`${window.childPublicPath}/`"
      }
]
```

## What is the expected behavior? 期望的结果是什么？
希望和 build-plugin-fusion-css 插件的 icon-font-path、font-custom-path 一样可以设置动态值
这样对微应用会很友好，可以适应不同的主应用而不需要修改代码。

## Any additional comments? 相关环境信息？

- **ice.js Version**：2.x
- **build.json Configuration**：
- **Node Version**: 16.x
- **Platform**: MacOS

**Comment by ClarkXia** [comment]
构建的完成后 对应路径应该就已经确定了
