### ISSUE TITLE
ice2不支持axios1.1.3

### ISSUE THREAD

**Issue by zangguojun** [alibaba/ice#5532]
## What is the current behavior? 发生了什么？
<img width="883" alt="image" src="https://user-images.githubusercontent.com/49148972/201054022-52992428-8dd4-4e02-b7cf-1b36412aea0e.png">

## What is the expected behavior? 期望的结果是什么？
应该是axios使用了module的形式export，而ice未能读取到
## Any additional comments? 相关环境信息？
- **ice.js Version**：1.6.6
- **build.json Configuration**：无特殊
- **Node Version**:v14.17.3
- **Platform**:macOS

**Comment by ClarkXia** [comment]
ice.js 1.x 版本还是 2.x 版本
可以提供下引入的方式，以及工程配置
