### ISSUE TITLE
Dev 阶段格式化页面源码

### ISSUE THREAD

**Issue by wssgcg1213** [alibaba/ice#5549]
> https://github.com/ice-lab/ice-next/issues/198

评估是否能在 Dev 阶段产生格式化的源码，方便查看

![](https://user-images.githubusercontent.com/1303018/167336380-0f7313a6-d2bc-4f0b-bbc7-8555b1285403.png)

**Comment by chenjun1011** [comment]
方案一：勾选自动换行，进行格式化
方案二：禁用 JS，在控制台 Elements 面板，查看页面结构
