### ISSUE TITLE
如何创建第三方scaffold实践

### ISSUE THREAD

**Issue by james-cain** [alibaba/ice#555]
理解iceworks和模板之间是**完全解耦**。
例如，[router配置方案](https://github.com/james-cain/cain-ice-template/blob/master/src/router.js)。
另外，还需要注意，页面必须是放在pages目录下，iceworks会监测这个目录中的所有页面，否则会发现iceworks中的页面列表是空的。
想要了解更多，可以参考[wiki](https://github.com/james-cain/cain-ice-template/wiki/How-to-use) 里面讲解的很详细。
目前使用还存在两个问题：1.页面创建时，输入路由路径默认只能输入两级，我需要构建三级菜单，还需要官方可以定制下；2.如果修改了routerConfig.js的代码，会导致iceworks无法自动更新routerConfig.js
最后，非常感谢ice团队做的这个开源项目，极大的节省了开发成本和开发投入。而且团队成员都非常耐心，非常👍

**Comment by yujiangshui** [comment]
你说的这两个问题我们会尽快 review 排期处理，感谢反馈。

**Comment by chenbin92** [comment]
> 并不是一定需要按照官方提供的脚手架模板或者ice-devtools的创建scaffold方式去构建新的模板

如何维护 `db.json` 元数据?

**Comment by james-cain** [comment]
还是要用ice-devtools创建一个开发工具，然后将工程导入到scaffold中，去创建db.json元数据 @chenbin92

**Comment by chenbin92** [comment]
@james-cain  你上面的描述有一些误导性，可以从新在梳理一下完整的流程可能会更好

**Comment by james-cain** [comment]
@chenbin92 我把误导的回撤了。不做误解性的流程说明
