### ISSUE TITLE
钉钉社区群全员禁言了，希望恢复

### ISSUE THREAD

**Issue by lbarakidouji** [alibaba/ice#5559]
如题

**Comment by lbarakidouji** [comment]
> 受到钉钉 > 500 人群政策影响，原来的社区群暂时用不了了 (包括管理员也无法发言、发布和修改群公告)，我们最近想想办法看后续如何继续这种 Discussion 性质的群组

T T v2 的文档没有保留吗

**Comment by aak1247** [comment]
（必须得用钉钉群吗

**Comment by ClarkXia** [comment]
暂时推荐通过 GitHub issue
