### ISSUE TITLE
DataBinder有BUG？

### ISSUE THREAD

**Issue by 276562578** [alibaba/ice#557]
`@DataBinder({
  dataSource: {
    url: '/build/show.php',
    type: 'get',

      // 回传给处理函数
      // 不做回传处理会导致数据更新逻辑中断
      serializeArray: false,
     success: (res, defaultCallback, originResponse) => {
      console.log('res', res, originResponse);
      defaultCallback();
    },
    error: (res, defaultCallback, originResponse) => {
      console.log('res', res, originResponse);
      defaultCallback();
    },
    defaultBindingData: [{
      // 配置接口返回数据的字段的初次默认值
      title: '',
      subject:
      '',
      pic: '',
      url: '',
    }]}})
componentDidMount() {
    this.enquireScreenRegister();
    this.props.updateBindingData('dataSource');
  }
render() {
    const { isMobile } = this.state;
    const logoWidth = isMobile ? 150 : 195;
    const logoHeight = isMobile ? 150 : 175;
    var { dataSource } = this.props.bindingData.dataSource;
    console.log("dataSource",this.props.bindingData.dataSource);
`
以上代码在console里的log如图
[https://www.picb.cc/image/2pJTEJ](https://www.picb.cc/image/2pJTEJ)
[https://www.picb.cc/image/2pJxar](https://www.picb.cc/image/2pJxar)
可以看到数据已经获取到本地了，但不能正常使用

**Comment by 276562578** [comment]
#558

**Comment by noyobo** [comment]
#559
