### ISSUE TITLE
Pro 模版下 data-loader 过大

### ISSUE THREAD

**Issue by ClarkXia** [alibaba/ice#5577]
使用 `@ice/antd-pro-scaffold` 构建时，打出的 data-loader.js 产物过大

**Comment by imsobear** [comment]
多大

**Comment by chenjun1011** [comment]
> 多大

350k，把插件的代码构建进去了

**Comment by answershuto** [comment]
> 

it's not just big, it's huge!!！

**Comment by answershuto** [comment]
> 多大

it's not just big, it's huge!!！

**Comment by luhc228** [comment]
> 暴露的另一个问题是 plugin-store 是不是过于大了

react-redux 就是这么的大
