### ISSUE TITLE
怎么替换BrandDisplay里面的DataSource为网络上的数据？

### ISSUE THREAD

**Issue by 276562578** [alibaba/ice#558]
`const dataSource = [
  {
    title: '飞利浦',
    subject:
      '一场内容营销活动获得超百万的进店点击，定位新广告的达人+积极迎接内容时代的品牌，如何刷新内容营销的定义？',
    pic: 'https://img.alicdn.com/tfs/TB1n6H_SXXXXXc3XpXXXXXXXXXX-616-348.png',
    url: 'https://alibaba.github.io/ice',
  },
  {
    title: '万家乐',
    subject:
      '策划『生活改造家』主题全案，联合一线大咖制作图文、直播、短视频全域引流，助力品牌升级和高端人群种草，结合行业活动割草。',
    pic: 'https://img.alicdn.com/tfs/TB1bHO6SXXXXXaiXFXXXXXXXXXX-308-174.png',
    url: 'https://alibaba.github.io/ice',
  },
  {
    title: '职场游乐园',
    subject: '2017年以“职场游乐园”为主题，全方位推动Lee牛仔专家与创新者形象。',
    pic: 'https://img.alicdn.com/tfs/TB17bzrSXXXXXbpaFXXXXXXXXXX-616-348.png',
    url: 'https://alibaba.github.io/ice',
  },
  {
    title: '品味百味人生',
    subject:
      '吃货的世界你不懂，看着直播镜头里心仪的零食恨不得舔屏，从种草到剁手分分钟一气呵成。',
    pic: 'https://img.alicdn.com/tfs/TB1IkEjSXXXXXb1XXXXXXXXXXXX-616-348.png',
    url: 'https://alibaba.github.io/ice',
  },
];`
这个默认的数据渲染的页面，如何可以使他从网络上获取数据之后再渲染页面呢？
前端小白，基本只写过后端代码，试了axios和databinder，不是很会用，感谢大佬们

**Comment by noyobo** [comment]
#559
