### ISSUE TITLE
Pro 模板启动 WARN 问题

### ISSUE THREAD

**Issue by lbarakidouji** [alibaba/ice#5582]
pnpm 使用 Pro 模板创建 ice3 项目，项目可以正常启动，控制台存在 WARN 

![image](https://user-images.githubusercontent.com/83287204/202464649-c0b5d711-dfbf-4543-8e6f-cf19798764c1.png)
1. Pro 模版默认开启了 server 配置，WARN 也会输出类似 useLayoutEffect 不生效
2. 红框，我看 minify 默认只在 build 生效，手动设置 minify 在开发阶段仍存在

**Comment by luhc228** [comment]
@lbarakidouji 感谢反馈。根据您的意见，我们做了一些优化，您可以重新创新一个新的 pro 模板进行开发

https://github.com/ice-lab/react-materials/pull/211
