### ISSUE TITLE
build-plugin-ice-app 引用了未声明的依赖

### ISSUE THREAD

**Issue by answershuto** [alibaba/ice#5589]
![image](https://user-images.githubusercontent.com/17812136/202640951-11a1f758-f098-4f29-9ed2-a81bf99a85db.png)
![image](https://user-images.githubusercontent.com/17812136/202640988-ba80885f-23f1-487a-b189-35e46f7cefff.png)

**Comment by ClarkXia** [comment]
这个包将标记 deprecate，暂时可以在项目中添加 inquirer 依赖 (^6.5.1)，后续建议项目升级为 ice.js
