### ISSUE TITLE
[QUESTION]vite模式下有什么办法可以优化文件大小吗？

### ISSUE THREAD

**Issue by xmsz** [alibaba/ice#5595]
之前最简单的方式是通过 externals 用CDN加载，但是vite模式下不支持
还有用rollupOptions.output.manualChunks，但是这个不知道在哪配置

我现在基础的依赖包都2mb了 

需求
- vite模式下，有什么办法可以优化构建出来的文件大小/拆包

**Comment by ClarkXia** [comment]
可以直接配置在 vite 字段下面即 `vite.build.rollupOptions.output.manualChunks`
