### ISSUE TITLE
意外退出

### ISSUE THREAD

**Issue by eshun** [alibaba/ice#56]
![image](https://user-images.githubusercontent.com/11847678/35657536-ef929e5c-0737-11e8-96cf-5b1cbff289cc.png)

**Comment by zxhycxq** [comment]
我这里每次都这样的，我以为是我安装的方式不对。也是最新版的。

**Comment by wssgcg1213** [comment]
感谢反馈, 我们会尽快修复

**Comment by wssgcg1213** [comment]
![image](https://user-images.githubusercontent.com/3922719/35664057-4ca8a50a-075b-11e8-95a0-7751a4d0fbdb.png)
