### ISSUE TITLE
iceworks.exe被卡巴斯基识别为恶意软件

### ISSUE THREAD

**Issue by JianxunRao** [alibaba/ice#560]
`iceworks.exe`被卡巴斯基识别为**恶意软件**
![_20180527211800](https://user-images.githubusercontent.com/13062911/40586355-9e30c52c-61f3-11e8-9c82-e7cef8db166c.png)

**Comment by wssgcg1213** [comment]
可以尝试把iceworks所在的目录设置为信任目录  
https://support.kaspersky.com/us/3025
