### ISSUE TITLE
ice3 引入 definePageConfig报错 

### ISSUE THREAD

**Issue by gdc1998** [alibaba/ice#5600]
## What is the current behavior? 发生了什么？
ice3 引入 definePageConfig报错 不存在这个方法 ，移动端如何配置页面标题

## Any additional comments? 相关环境信息？

- **ice.js Version**：3.0
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by ClarkXia** [comment]
`npm list @ice/app` 确认下版本

**Comment by gdc1998** [comment]
> npm list @ice/app

@ice/app@3.0.0-rc.8

**Comment by ClarkXia** [comment]
正式版本已发布，@ice/app 安装 ^3.0.0 即可
