### ISSUE TITLE
How @ice/plugin-auth combine with defineDataLoader

### ISSUE THREAD

**Issue by maoxiaoke** [alibaba/ice#5625]
I got a little issue here：

- a request called from `defineDataLoader`(original `getData`) should be attached with some authorization info like user id. While I found the request maked by `defineAuthConfig` was called later then the request made by dataLoader. This cause a problem and there is no workaround about this.

**Comment by luhc228** [comment]
https://github.com/ice-lab/react-materials/blob/master/scaffolds/ice3-antd-pro/src/app.ts
https://github.com/ice-lab/react-materials/pull/217
看下这个能帮到你么？

**Comment by maoxiaoke** [comment]
@luhc228 有可能我还没有更新到正式版导致的问题
