### ISSUE TITLE
npm run start:wechat 运行@ice/miniapp-scaffold创建的小程序项目报错

### ISSUE THREAD

**Issue by mvpmvp25** [alibaba/ice#5627]
试了几个版本的node环境 都是报这个错误。
![111](https://user-images.githubusercontent.com/14303912/204215784-5f2561e0-264c-4f77-a552-cd4dacdb5117.png)

**Comment by ClarkXia** [comment]
提供下使用的 @ice/app 版本

**Comment by mvpmvp25** [comment]
>

**Comment by mvpmvp25** [comment]
> 提供下使用的 @ice/app 版本
3.0.0

**Comment by wssgcg1213** [comment]
使用 3.0.1 应该可以解决, related to https://github.com/alibaba/ice/pull/5623  

`node_modules` 下的文件会在 npm 安装新包时被删除, 新版本已经修复这个问题

**Comment by mvpmvp25** [comment]
> 



> 使用 3.0.1 应该可以解决, related to #5623
> 
> `node_modules` 下的文件会在 npm 安装新包时被删除, 新版本已经修复这个问题

![112](https://user-images.githubusercontent.com/14303912/204545798-61088fcc-8638-40ed-895e-103f88c4cfd0.png)
可现在报了另一种错误
