### ISSUE TITLE
飞冰利用webpack打包，如何配置build.config.js在生成的js文件顶部添加banner信息

### ISSUE THREAD

**Issue by Bingjiajia** [alibaba/ice#5631]
问题：
利用webpack打包，如何在生成的js文件头部添加package.json里面的版本、版权、描述等信息。

配置：
- **ice.js Version**：2.0.0

**Comment by ClarkXia** [comment]
简单信息你可以自行在构建完成后进行文件的读写操作

**Comment by Bingjiajia** [comment]
效果：
`
/*!
 * @icedesign/stark-child-scaffold
 * 0.1.0
 *
 */`

配置：
`
  webpackPlugins: {
    'webpack.BannerPlugin': {
      options: {
        banner: name + '\n' + version + '\n',
      },
    },
  },
`

利用通过上面配置显示出的效果，在编辑的过程中利用webpack.BannerPlugin的options.banner可以接收string和function,如何设置function的方式添加banner

**Comment by ClarkXia** [comment]
函数形式的走自定义插件的方式追加，参考 https://github.com/alibaba/ice/issues/3179
