### ISSUE TITLE
[RFC] 通过插件形式支持 Bundle Analyze

### ISSUE THREAD

**Issue by wssgcg1213** [alibaba/ice#5635]
提供类似 rax-app 的 --analyzer-target 一键分析 bundle-size 的命令，在分析包大小做性能优化时候会比较方便

## Usage

```bash
ice start --analyze
ice build --analyze
```

```tsx
// ice.config.mts
export default defineConfig(() => ({
   plugins: [analyzer()],
}));
```

Stdout:

Analyzer server at https://127.0.0.1:xxxx

**Comment by ClarkXia** [comment]
默认就有 ice start --analyzer

**Comment by wssgcg1213** [comment]
<img width="1970" alt="image" src="https://user-images.githubusercontent.com/3922719/204489094-7f6d3e1c-a5f8-4526-be1c-f1d9e9c892d5.png">
<img width="513" alt="image" src="https://user-images.githubusercontent.com/3922719/204489127-b81daa6a-b612-4ed4-b330-3fe529b3769a.png">

文档: https://v3.ice.work/docs/guide/basic/cli/#start
