### ISSUE TITLE
ice 2.x 创建项目的命令变成什么了？为什么2.x的文档上的命令创建的却是ice 3 的模板

### ISSUE THREAD

**Issue by edc-hui** [alibaba/ice#5644]
## Any additional comments? 相关环境信息？

- **ice.js Version**：
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by ClarkXia** [comment]
默认推荐 3.0，如果用 2.0 可以指定模版
https://v2.ice.work/docs/guide/start/

![image](https://user-images.githubusercontent.com/4219965/204731117-ea77d6a6-1be9-4034-88b2-a59213a4d169.png)
