### ISSUE TITLE
求问如何监听location变化？在主应用且不用build-plugin-icestark的情况下

### ISSUE THREAD

**Issue by aak1247** [alibaba/ice#5645]
需求是通过pathname去做一些条件判定，但是不希望使用router（别问为什么。。。），有没有build-plugin-icestark中监听pathname的办法呢？

**Comment by aak1247** [comment]
哦对，另外有一些数据是希望能根据路由渲染的，这个也没法用router去实现。

**Comment by aak1247** [comment]
目前在同一个主应用的route下，pathname变化不会触发layout的重新渲染，也无法触发侧边栏的重新渲染（但是在build-plugin-icestark下是可以的）。尽管layout能够获取到location，但是由于没有重新渲染所以后续的侧边栏都无法正常显示

**Comment by aak1247** [comment]
ice 2.6.6 ice-stark 2.7.3

**Comment by ClarkXia** [comment]
> 需求是通过pathname去做一些条件判定，但是不希望使用router（别问为什么。。。），有没有build-plugin-icestark中监听pathname的办法呢？

监听原生的 history 相关事件就行，跟 build-plugin-icestark 没关系，类似逻辑应该是业务自己消费

**Comment by aak1247** [comment]
build-plugin-icestark 中提供了主应用的pathname监听途径
![image](https://user-images.githubusercontent.com/13048547/204798391-a10d871c-b77f-43ae-be21-b4703f57b615.png)

ice原生未提供类似监听，直接监听浏览器除非强制每次pathname变化整个应用全部重新加载，但是spa下这不合理呀。

由于我的router相对简单，我目前是通过ruoter的回调完成（代码形式，非route配置，配置方式目前是拿不到的。。。）。
