### ISSUE TITLE
build-plugin-fusion 开启 usePx2Vw 编译失败

### ISSUE THREAD

**Issue by ClarkXia** [alibaba/ice#5647]
错误信息如下：
![image](https://user-images.githubusercontent.com/4219965/204954528-7ab4771f-5b8f-4bc6-be1b-1120a3bc62e2.png)

**Comment by wssgcg1213** [comment]
版本问题?

**Comment by ClarkXia** [comment]
Fixed in https://github.com/ice-lab/builder-deps/pull/32
