### ISSUE TITLE
hash路由 + splitchunk:false. hotreload不生效

### ISSUE THREAD

**Issue by fattydevelop** [alibaba/ice#5649]
## What is the current behavior? 发生了什么？

hotreload不生效了  如果是hash + splitchunk false, 能看到页面刷了 但是并不是新的页面 必须手动刷一下 。scss 更新是可以reload的  js更新不行 

- **ice.js Version**： "@ice/runtime": "1.0.0-beta.25",  "@ice/app": "3.0.1-beta.3",
- **build.json Configuration**：
```
import { defineConfig } from '@ice/app';
import def from '@ali/ice-plugin-def';
// The project config, see https://v3.ice.work/docs/guide/basic/config
export default defineConfig({
  // Set your configs here.
  splitChunks: false,
  ssr: false,
  ssg: false,
  externals: {
    xlsx: 'XLSX',
    react: 'React',
    'react-dom': 'ReactDOM',
    '@alifd/next': 'Next',
  },
  plugins: [def()],
  routes: {
    ignoreFiles: ['**/(mods|components)/**'],
  },
});

```
- **Node Version**: 16.17.0
- **Platform**: macos

**Comment by ClarkXia** [comment]
用 hash-router 的 [example](https://github.com/alibaba/ice/tree/master/examples/hash-router) 增加 splitChunks: false 无法复现，需要提供更多信息
