### ISSUE TITLE
插件间存在相互依赖问题

### ISSUE THREAD

**Issue by ClarkXia** [alibaba/ice#5651]
### 问题

部分官方插件相互之间存在先后依赖关系，如果顺序出现问题 将导致功能失效

### 解决方案

**原则上插件之间的功能不应该有相互依赖的关系**

为插件的生命周期提供额外的 enforce 选项，支持 pre（前置），post（后置）的能力

```js
onHook('after.build.compile', () => {}, { enforce: 'post' });
```

**Comment by xianghongai** [comment]
@ClarkXia  大佬，有飞冰生命周期相关的文档，我想了解 App(defineAuthConfig、defineStoreConfig、defineDataLoader)、Layout、Page 这些元素之间的执行情况，尤其是在内部包含异步逻辑、异步之间有依赖情况下。

现在感觉 defineAuthConfig、defineStoreConfig、defineDataLoader 这些方法用不着，登录时候已经将信息写入 Store 了。
