### ISSUE TITLE
编写组件时出现语法错误，修正后devserver不能重新热更新，需重启才可

### ISSUE THREAD

**Issue by songjiafan** [alibaba/ice#5654]
## What is the current behavior? 发生了什么？
编写组件时出现语法错误，修正后devserver不能重新热更新，需重启才可
![这是图片](https://gw.alicdn.com/imgextra/i4/O1CN01RCX9fF248yh8emcpK_!!6000000007347-2-tps-1826-882.png)

## What is the expected behavior? 期望的结果是什么？
无需重启服务，直接刷新页面可以热更

## Any additional comments? 相关环境信息？

- **ice.js Version**：3.01
- **build.json Configuration**：
- **Node Version**: v14.21.0
- **Platform**: macos

**Comment by ClarkXia** [comment]
fixed in @ice/app@3.0.3
