### ISSUE TITLE
[SSR] SSR模式下使用lazy懒加载页面时报错

### ISSUE THREAD

**Issue by smat0096** [alibaba/ice#5672]
## What is the current behavior? 发生了什么？
SSR模式下使用lazy懒加载页面模块报错

lazyComponent._result 的值为null
![企业微信截图_16703816884570](https://user-images.githubusercontent.com/20716152/206076696-d8d80be2-22a4-4982-b376-6d0ea27f0ace.png)
![image](https://user-images.githubusercontent.com/20716152/206077148-a8652491-e9fd-4813-9a80-da8de03d5c63.png)

## What is the expected behavior? 期望的结果是什么？
ssr模式下能正确使用懒加载页面
## Any additional comments? 相关环境信息？

- **ice.js Version**：2.6.6
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by ClarkXia** [comment]
提供下复现 demo 和路径

**Comment by smat0096** [comment]
@ClarkXia 
定位到原因了 ,ssr模式下 ice2.x的routes.ts文件是在commonjs规范下执行, 如果 src/routes.js 里有import xx路由 from 'routes/index.ts' 之类代码, 会导致在node ssr环境下lazy加载产物不一致, 导致报错, 可使用ice提供的lazy的第二个loadable入参解决, 或者优化下ssr场景下的lazy更优雅, 
 另外是否可以在3.x版本提供2.x版本的配置式路由, 可以用于非ice项目平滑迁移到ice, 约定式路由太僵硬了, 作为一个更自由的插件式前端工程框架并不合适
