### ISSUE TITLE
关闭默认按照路由代码分割 splitChunks 配置失效   ice3 

### ISSUE THREAD

**Issue by breakfriday** [alibaba/ice#5673]
```
export default defineConfig(() => ({
  ssr: false,
  ssg: false,
  splitChunks: false,
  plugins: [
    request(),
    store(),
    auth(),
  ],
}));
```
本地开发模式，关闭默认按照路由策略代码分割 失效。 ice3 

使用标准官方 模板复现

![image](https://user-images.githubusercontent.com/3796846/206103345-3b39b141-2ecf-4405-90ce-e0ca5ae4bae4.png)

**Comment by ClarkXia** [comment]
代码中默认存在路由级别 lazy 加载

**Comment by breakfriday** [comment]
...  我的问题是 这个默认开关 splitChunks   配置false 不生效 没法关闭，

**Comment by ClarkXia** [comment]
你是怎么判断 splitChunks 不生效，关闭 splitChunks 后不会再生成 framwork 和以 id 为命名的 chunk

**Comment by ClarkXia** [comment]
lazy 现在默认开启 不支持关闭
