### ISSUE TITLE
嵌套路由下 rax-view 引起样式覆盖

### ISSUE THREAD

**Issue by chenjun1011** [alibaba/ice#5686]
## 问题

如下工程

![image](https://user-images.githubusercontent.com/1303018/206424984-81df0d5f-4b2a-4b89-9715-3e158ac5780b.png)

假设 index.tsx 和 layout.tsx 都依赖 rax-view

rax-view 的样式会被重复打包到 index.css 和 layout.css 中

![image](https://user-images.githubusercontent.com/1303018/206425425-ca879471-0783-41de-a6c9-9d582bfa5dc7.png)

这样 layout 中的组件样式，有可能会因为后加载了 index.css，导致  rax-view 样式覆盖了组件样式

![image](https://user-images.githubusercontent.com/1303018/206425370-eeb0651f-de0f-4955-a361-8c1260197cb0.png)

## 解决思路

单独将 rax-view 和 rax-text 的样式 通过 splitChunk 配置，独立构建和加载

```ts

        cacheGroups: {
            raxStyles: {
                type: "css/mini-extract",
                name: "rax-style",
                test(module) {
                    return /(rax-view|rax-text)[/\\]/.test(module.nameForCondition() || '');
                },
                enforce: true,
            },
        }
```

![image](https://user-images.githubusercontent.com/1303018/206426307-c8d12c27-57d1-4277-b0b2-5ff24fac4960.png)

**Comment by ClarkXia** [comment]
- 如果是 rax 基础组件存在的问题，可以考虑在 rax-compat 层面上支持一些官方基础组件的逻辑，该逻辑将会把 rax 基础组件的样式单独抽离成一个 css chunk
- 如果考虑更加普适性的 splitChunk 策略，可以拓展 splitChunk 的字段，并确定几种推荐策略，比如目前默认策略、vendors 策略等

**Comment by chenjun1011** [comment]
临时解决方案是在 defineConfig 中修改 webpack 配置

```ts
  webpack: (webpackConfig) => {
    webpackConfig.optimization.splitChunks.cacheGroups['rax-style'] = {
      type: "css/mini-extract",
      name: "rax-style",
      test(module) {
          return /(rax-view|rax-text)[/\\]/.test(module.nameForCondition() || '');
      },
      enforce: true,
    }
    return webpackConfig;
  }
```
