### ISSUE TITLE
环境切换后，重装依赖后报错 Error: Decorating class property failed

### ISSUE THREAD

**Issue by chenhongen** [alibaba/ice#569]
## 环境信息

- 操作系统：WIN
- Iceworks 版本： 2.1

## 问题描述

台式机开发运行正常，把项目除了node_modules（因为文件多，会比较慢）以外的文件拷到笔记本。通过iceworks重装依赖。运行出问题了，可能原因是因为重装后一些依赖包升成了新版本。现在的解决方案是把原版node_modules拷到笔记本。。。

![1](https://user-images.githubusercontent.com/16499303/40823089-9e1badfc-65a1-11e8-89dd-7d06ef3e0179.png)

**Comment by yuanyan** [comment]
@chenhongen 运行出问题是提示什么信息？

**Comment by noyobo** [comment]
组件都是兼容的，可以看下具体的错误信息。
