### ISSUE TITLE
流式渲染下资源加载策略

### ISSUE THREAD

**Issue by chenjun1011** [alibaba/ice#5691]
## 问题

默认情况下，框架的 JS 加载是阻塞性的，而流式返回的 chunk 追加在 HTML 标签结束符后。这会导致流式的内容上屏受 JS Bundle 的阻塞，流式返回的片段需要等到这些 JS Bundle 加载解析完成后，才能上屏。

![image](https://user-images.githubusercontent.com/1303018/206620139-1a2d64a3-bfa7-416e-b979-30e704cd2789.png)

这样流式渲染的意义其实不大了，通过 Chrome Preformance  面板（Slow 3G）可以看到页面的 Loading 状态被阻塞了很久，然后才是页面内容一次性上屏。 

![image](https://user-images.githubusercontent.com/1303018/206620731-af0d68cf-7055-4f85-b4f6-9eb432d2c94f.png)

因此需要调整 JS  的加载优先级，有两种方式

## defer 模式

设置为 defer 后，loading 状态几乎看不到了，页面内容很快上屏了。但会带来的问题是，JS 需要等待所有 HTML 返回后，才会执行，如果有片段返回特别慢，会导致在这之前，页面完全不能交互。

![image](https://user-images.githubusercontent.com/1303018/206621189-7bb43eba-1739-485f-8ab1-6141677e2513.png)

## async 模式

相比来说，async 的模式相对较优，会先继续加载 chunk，等待 JS 加载完成后，再执行 JS（这个时候如果还有 chunk 没返回，那么是被阻塞的）。

![image](https://user-images.githubusercontent.com/1303018/206621450-89e9bd89-b3d1-4e92-88ec-63fe6398a12d.png)

目前实现中采用的是 async 模式。但还存在问题是：JS 在解析执行时，会导致图片无法上屏，因此图片的显示时机仍然比较滞后。

**Comment by ClarkXia** [comment]
aysnc 执行是乱序的，如果前置脚本没有执行，而先执行了 main，应该会导致多次加载

**Comment by chenjun1011** [comment]
推荐的做法是，是使用 async 或 defer 加载资源

async 适用场景：
- 流式过程较短
- 希望先完成整个页面的加载，再执行 JS

defer 适用场景：
- 流式过程较长
- 希望加载过程中，部分区块可以先进行交互

后续以文档形式体现

**Comment by ClarkXia** [comment]
推荐解法用 defer
