### ISSUE TITLE
根据文档，splitChunks，webpack都提示错误

### ISSUE THREAD

**Issue by lirongfei123** [alibaba/ice#5694]
## What is the current behavior? 发生了什么？
[Config File] Config key 'webpack' is not supported
[Config File] Config key 'splitChunks' is not supported

![image](https://user-images.githubusercontent.com/3190071/206660351-1a8d7328-9047-4dec-a26c-9978a6aa5a75.png)

## Any additional comments? 相关环境信息？

- **ice.js Version**：
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by luhc228** [comment]
webpack 和 splitChunks 只是 ice.js 3 的配置

**Comment by lirongfei123** [comment]
懂了，只是脚手架生成的ice.js 都是2开头的，好多配置和文档不一致

**Comment by lirongfei123** [comment]
我懂了，脚手架基于fustion的都是v2的
