### ISSUE TITLE
嵌套 Suspense 的写法导致请求串行

### ISSUE THREAD

**Issue by chenjun1011** [alibaba/ice#5697]
使用嵌套路由实现 Suspense 能力时，会导致请求的串行

layout.tsx
```tsx
    <Suspense fallback={<Spinner />}>
      <Header />
      <Outlet />
    </Suspense>
```

index.tsx
```tsx
    <Suspense fallback={<Spinner />}>
      <Comments />
    </Suspense>
```

以上面的代码为示例，layout.tsx 在 Suspense 的过程中，内部的路由组件 index.tsx 不会被执行

这就到导致了 index 的数据请求必须等到 layout 的数据加载完成后，才会被触发

**Comment by ClarkXia** [comment]
如果是通过 dataLoader 的方式定义 数据请求的具体逻辑应该是可以提前知道的吧？
