### ISSUE TITLE
导入加解密模块出错

### ISSUE THREAD

**Issue by wangqiuyuan1994** [alibaba/ice#5699]
![image](https://user-images.githubusercontent.com/115388698/206745375-a75d7df0-76b9-4550-8a19-aee163be4fff.png)

Module not found: Error: Can't resolve './JSEncrypt' in
Did you mean 'JSEncrypt.js'?
BREAKING CHANGE: The request './JSEncrypt' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

如题，我创建完一个app之后，想载入jsencrypt库，结果报错。希望有人帮忙看下，是哪里配置不对的问题。

**Comment by ClarkXia** [comment]
感觉是 jsencrypt 库的问题，'./JSEncrypt' 在 esm 的标准下应该是要增加后缀识别的
