### ISSUE TITLE
代码保存报错 Cannot find module 'eslint'

### ISSUE THREAD

**Issue by yueyp** [alibaba/ice#5701]
## What is the current behavior? 发生了什么？
ice.config.mts 文件里配置eslint：true，首次运行没有问题，代码修改后保存，页面会报错，页面上报错如下：

Compiled with problems:X

ERROR

Cannot find module 'eslint'
Require stack:
- D:\work\cpms-outer\node_modules\.pnpm\@ice+bundles@0.1.1\node_modules\@ice\bundles\compiled\eslint-webpack-plugin\index.js

## What is the expected behavior? 期望的结果是什么？
页面正常运行，能够校验eslint错误

## Any additional comments? 相关环境信息？
  "dependencies": {
    "@ice/runtime": "^1.0.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@ice/app": "^3.0.0",
    "@types/react": "^18.0.0",
    "@types/react-dom": "^18.0.0",
    "postcss-pxtorem": "^6.0.0"
  },

- **ice.js Version**：
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by ClarkXia** [comment]
eslint 默认已经依赖，确保依赖正确安装即可
