### ISSUE TITLE
似乎发现一个跟 dataLoader 相关，以及相关讨论

### ISSUE THREAD

**Issue by maoxiaoke** [alibaba/ice#5707]
## 现象

提前准备了一个测试 [Demo](https://github.com/maoxiaoke/ice-data-loader-error)，该 Demo 在 `pages/about` 目录下新增了一个 layout 页面，用来测试什么时候会执行 layout 的 `dataloader`.

同时新增了 `pages/about/index` 和 `pages/about/another` 来验证：

- 同 Layout 下的路由切换，layout dataLoader 和 page dataloader 的执行策略
- 不同 Layout 下的路由切换，layout dataloader 和 page dataloader 的执行策略

> 代码可见仓库 https://github.com/maoxiaoke/ice-data-loader-error/tree/master/src/pages/about

测试结果不符合预期。如下：

1. 当在 `/` 路由下加载，每次切换 `/about` 路由，都会执行 layout dataloader 和 page dataloader

https://nazha-image-store.oss-cn-shanghai.aliyuncs.com/others/ice-data-loader-error-fetching-from-origin.mp4

2. 当在 `/about` 路由下加载，每次跳回首页并**再次切回** `/about` 路由，不再执行 layout dataloader 和 page dataloader

https://nazha-image-store.oss-cn-shanghai.aliyuncs.com/others/ice-data-loader-fetching-on-about.mp4

## A hint

在这个 [PR 中](https://github.com/alibaba/ice/pull/5706)，处理了两个问题：

1. `loadInitialDataInClient` 只执行一次，后续的处理中对首次请求的结果进行 caching，导致一个不一致的问题：后续其他路由的请求为何不 caching

https://github.com/alibaba/ice/pull/5706/files#diff-0b6196628ebae13aa5acf71bcc775dfb8542ee7a2f6160e55f38e9943e49e859R90

> PR 里的修改没有考虑 caching 的方案问题

2. 对 history 的监听依赖了 state，但没有把 state 放入依赖列表，会导致执行闭包

https://github.com/alibaba/ice/pull/5706/files#diff-857497dd52d1088d5d4ccd6bbccd06b485c8fccd9a1392499769b5f3f770189fL205-L218

这个 PR 会得到如下结果：

- 相同 Layout 下的路由切换，layout dataLoader 不会重复执行，而 pageLoader 会重复执行
- 不同 Layout 下路由切换，layout dataLoader 和 page dataLoader 都会重复执行

## 问题

1. 在上述的两个场景下，**相同 Layout 下的路由切换** 和 **不同 Layout 下路由切换**，layout dataLoader 和 page dataLoader 合适的策略应该是什么（需不需要重复执行）？

2. dataLoader 是目前是阻塞渲染的，在 dataLoader 二次执行的时候（此时脚本资源已经加载了），是否也要等 dataLoader 的数据返回后再渲染？

**Comment by chenjun1011** [comment]
> dataLoader 是目前是阻塞渲染的，在 dataLoader 二次执行的时候（此时脚本资源已经加载了），是否也要等 dataLoader 的数据返回后再渲染？

现在的设计是统一要等，后面确实要考虑不阻塞的实现
