### ISSUE TITLE
开启SSR，使用 npm run analyzer 报错：Error: listen EADDRINUSE: address already in use 127.0.0.1:9000

### ISSUE THREAD

**Issue by xyJen** [alibaba/ice#5716]
## What is the current behavior? 发生了什么？

npm run analyzer 报错：Error: listen EADDRINUSE: address already in use 127.0.0.1:9000

![image](https://user-images.githubusercontent.com/24266963/207755780-07346b83-cc73-4032-9154-f26b77be01cc.png)

![image](https://user-images.githubusercontent.com/24266963/207755817-f1857830-c09b-4ac5-ab7e-49eacb3ac898.png)

## What is the expected behavior? 期望的结果是什么？

可以展示bundle 分析图

## Any additional comments? 相关环境信息？

- **ice.js Version**：2.6.6
- **build.json Configuration**：
```
{
  "vite": false,
  "ssr": true,
  "plugins": [
    [
      "build-plugin-moment-locales",
      {
        "locales": [
          "zh-cn"
        ]
      }
    ],
    [
      "build-plugin-ignore-style",
      {
        "libraryName": "@alifd/next"
      }
    ],
    "@ali/build-plugin-ice-def"
  ]
}
```
- **Node Version**: 14.x 16.x
- **Platform**: MacOS

**Comment by xyJen** [comment]
demo： https://github.com/xyJen/ice-ssr-test

**Comment by ClarkXia** [comment]
开启 ssr 的场景下，因为会启动多个任务，因此会多次在 9000 端口启动服务。通过 analyzer 分析的时候可以先暂时关闭 ssr，后续我们优化下 analyzer 的逻辑

**Comment by ClarkXia** [comment]
推荐升级 ice.js 3，不会存在多端口占用问题
