### ISSUE TITLE
numberPicker在type=‘inline’时，手动设置inputWidth，会出问题

### ISSUE THREAD

**Issue by zhangshichun** [alibaba/ice#572]
## 环境信息

- 操作系统：
- Iceworks 版本： icedesign/base 0.2.1

## 问题描述
如题，numberPicke当type=‘inline’时，手动设置inputWidth，会变形

![menu saveimg savepath20180529230402](https://user-images.githubusercontent.com/15374687/40667476-d7995f7a-6394-11e8-8242-ab2d76e099fb.jpg)
![menu saveimg savepath20180529230433](https://user-images.githubusercontent.com/15374687/40667485-dd55e03c-6394-11e8-8f7b-201ec274e045.jpg)

**Comment by yuanyan** [comment]
@zhuzhaoyuan 感谢反馈，inline 模式下 inputWidth 的确有问题，我们看下如何修复

**Comment by wssgcg1213** [comment]
@zhangshichun 这边修复了, 尝试升级到 icedesign/base 0.2.2 试一下, 如果ok 的话帮忙关一下issue

**Comment by zhangshichun** [comment]
0.22修改了该问题
