### ISSUE TITLE
已声明“request”，但从未读取其值。ts(6133) 模块“"ice"”没有导出的成员“request”。ts(2305)

### ISSUE THREAD

**Issue by wulisensen** [alibaba/ice#5725]
![image](https://user-images.githubusercontent.com/22022130/208122747-219a6c93-6f58-4fd0-852f-cead12556b78.png)

**Comment by wulisensen** [comment]
![image](https://user-images.githubusercontent.com/22022130/208122869-929e64ea-b7f9-4c50-968c-07f0f7b2988a.png)

**Comment by ClarkXia** [comment]
确认下是否已经安装 并使用 request 插件 https://v3.ice.work/docs/guide/advanced/request
