### ISSUE TITLE
白屏

### ISSUE THREAD

**Issue by no33jou** [alibaba/ice#573]
## 环境信息

- 操作系统：macOS 10.13.4
- Iceworks 版本： 2.1.0

## 问题描述
![image](https://user-images.githubusercontent.com/12016782/40694160-ccf43b36-63ed-11e8-9a6c-c5bda419612f.png)

更新最新版本后打开就白屏了

**Comment by noyobo** [comment]
@no33jou 可以打开 帮助>切换开发人员工具   看下有没有报错的信息。

**Comment by no33jou** [comment]
![image](https://user-images.githubusercontent.com/12016782/40694425-0b4ed4d0-63ef-11e8-9274-fc17bf337ba6.png)

原来的项目被我删了,现在打不开原有项目.
但是我现在想换个项目换不了

**Comment by noyobo** [comment]
现在还是白屏吗？

可以通过菜单 项目>清空项目列表 重新打开软件。

**Comment by no33jou** [comment]
已经好了,多谢
