### ISSUE TITLE
[error] connot find module 'isarray' 

### ISSUE THREAD

**Issue by lanxuan4444** [alibaba/ice#575]
## 环境信息

- 操作系统：
- Iceworks 版本： 

## 错误信息

- 
![image](https://user-images.githubusercontent.com/17310230/40697284-20a10d32-63fc-11e8-8c8f-7fe2d0134259.png)

-

**Comment by noyobo** [comment]
可以将控制台放大些，截图完整信息么？

**Comment by lanxuan4444** [comment]
最新版本2.1.0
启动空白报错
![image](https://user-images.githubusercontent.com/17310230/40697664-f7adbe28-63fd-11e8-9cf5-6dc6c23a9799.png)

**Comment by noyobo** [comment]
方便加下我钉钉沟通下吗？ 现在看不出错误的调用栈。

**Comment by lanxuan4444** [comment]
方便，钉钉号是的多少

**Comment by noyobo** [comment]
![image](https://ice.alicdn.com/assets/images/ice-group.png)
加下群然后加我就好了,  群主 宝码

**Comment by lanxuan4444** [comment]
ok

**Comment by noyobo** [comment]
@lanxuan4444  或者我加你？
