### ISSUE TITLE
开启vendor,打包引用@ant-design/plots 和 @ant-design/graphs组件后,报错

### ISSUE THREAD

**Issue by liusheng-zhainanya** [alibaba/ice#5759]
发生了什么
"ice.js": "^2.6.4",不打开配置vendor,打包后页面正常, 打开配置vendor,打包后页面报错.
@ant-design/plots 和 @antv/g6 或者 @ant-design/graphs 在同一代码库,开启vendor,同时引用打包后页面出错

错误截图
![image](https://user-images.githubusercontent.com/56863304/209625857-96f011de-8242-40ba-8596-bb709b972c42.png)

期望的结果是什么
不应该报错

相关环境信息
    "@ant-design/graphs": "^1.3.2",
    "@ant-design/icons": "^4.8.0",
    "@ant-design/maps": "^1.0.6",
    "@ant-design/plots": "^1.2.2",
    "@antv/g6": "^4.8.1",
    "ice.js": "^2.6.4",

**Comment by ClarkXia** [comment]
能否提供一个复现 demo

**Comment by liusheng-zhainanya** [comment]
抱歉,第一次提,我需要提供什么样的demo,代码库地址还是 @ClarkXia

**Comment by ClarkXia** [comment]
> 抱歉,第一次提,我需要提供什么样的demo,代码库地址还是 @ClarkXia

代码参考和 zip 文件都行～

**Comment by liusheng-zhainanya** [comment]
我仔细看了下,用内部的组件配置太多了,无法提供相关zip文件,辛苦先关闭吧,谢谢 @ClarkXia
