### ISSUE TITLE
【RFC】build-plugin-component umd模式支持dist 也起服务

### ISSUE THREAD

**Issue by younyzhu** [alibaba/ice#5765]
### 需求背景

icestark 推荐用build-scripts框架来启动微模块，然后被icestark微模块使用。

微模块加载器通过加载 http://${url}/index.js 来加载微模块资源

大部分情况下，在线上或者预发环境 想直接调试和开发本地代码。
由于当前build-plugin-component  打包出来umd是 dist 文件目录，但不会启动服务，服务被占用了demo.

建议另外启动一个dist文件的server,譬如：http://127.0.0.1:3334

**Comment by ClarkXia** [comment]
在 https://github.com/ice-lab/icepkg/issues/430 跟进
