### ISSUE TITLE
构建产物js不执行

### ISSUE THREAD

**Issue by kiscall** [alibaba/ice#5771]
通过`npm create ice`选择`Web Lite Scaffold`初始化ice3项目，浏览器访问构建产物`build/index.html`
会发现默认模板代码的按钮点击事件无响应
![image](https://user-images.githubusercontent.com/10861193/210063045-ad4e8678-9741-43f2-981e-c5bb433198e2.png)
如果关闭ssr和ssg，页面会白屏
猜测js并未执行，导致了第一种情况的点击无反应和第二种情况的的白屏问题

期望表现：正常渲染

**Comment by wssgcg1213** [comment]
感觉是 client 端的 js 没有执行到，我们这边来确认下

**Comment by wssgcg1213** [comment]
需要使用服务器托管访问, 因为路由匹配的原因, 打开的是 `/build/index.html`, 而内置的路由匹配规则是到达 `/` 的
