### ISSUE TITLE
增强 MemoryRouter 的使用场景

### ISSUE THREAD

**Issue by ClarkXia** [alibaba/ice#5774]
目前 ice3 支持配置 [memory router](https://v3.ice.work/docs/guide/basic/app#initialentries)，但需要明确在多个路由的场景下，如何进行支持渲染路由。

比较理想的使用方式为获取主入口 + 对应页面的 bundle即可完成单独路由的渲染。

### 考虑适用的场景

- 微前端
- MPA 单页面部署

**Comment by wssgcg1213** [comment]
有点像使用 memory router 来部分替代 MPA 的功能?

**Comment by luhc228** [comment]
梳理 initialEntries 使用的场景

**Comment by kiscall** [comment]
现在多个路由的场景每个html文件渲染都是initialEntries指定的最后一个路径页面，还没有完全模拟MPA。理论上应该每个html渲染对应的页面
