### ISSUE TITLE
修改 SSR 选项默认值为 false

### ISSUE THREAD

**Issue by wssgcg1213** [alibaba/ice#5776]
https://github.com/alibaba/ice/blob/master/packages/ice/src/config.ts#L125

修改选项 ssr 的默认值为 false, 保留 ssg 的默认值为 true

---

原因是 SSR 的使用是有部署门槛的，大部分的用户还是建议使用 SSG + Client Render，对于需要使用 SSR 的用户显示声明开启更符合直觉。

**Comment by ClarkXia** [comment]
默认值修改，对应的模版也需要同步更新

**Comment by wssgcg1213** [comment]
模版更新要与 release/3.0 的发布同步 cc @luhc228
