### ISSUE TITLE
ice3期望把入口entry和runApp放开, 以此可使用qiankun等第三方库,并动态生成入口文件

### ISSUE THREAD

**Issue by smat0096** [alibaba/ice#5778]
## What is the current behavior? 发生了什么？

如题,期望 ice3把入口entry和runApp放开, 以此可使用qiankun等第三方库,并动态生成入口文件
## Any additional comments? 相关环境信息？

- **ice.js Version**：
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by ClarkXia** [comment]
其实是有自定义入口能力的，但目前 entry.client 的逻辑比较复杂，如果开放出去，开发者初始化成本较高，我们内部需要先验证下这个流程。
另外你这边也可以先将使用场景具体描述下（可以以原先的 runApp 为例）

**Comment by smat0096** [comment]
我们因业务的需求, 以ice2.x为基础建设了一套基础template, 实现:
1. 使用qiankun实现接入微前端
2. 接入lowcode; 参考 https://github.com/alibaba/lowcode-demo
3. 启用module federation 能力实现远程共享组件;
以上能力均需要动态改写entry文件逻辑, 动态配置路由,  
之前采取的策略是编写插件, 在 onGetWebpackConfig 编译时把不同场景的入口文件动态和路由配置写到临时文件夹, 再通过 modifyUserConfig 指定入口文件;
目前在调研升级ice3, 发现无合适的api

**Comment by ClarkXia** [comment]
> 我们因业务的需求, 以ice2.x为基础建设了一套基础template, 实现:
> 
> 1. 使用qiankun实现接入微前端
> 2. 接入lowcode; 参考 https://github.com/alibaba/lowcode-demo
> 3. 启用module federation 能力实现远程共享组件;
>    以上能力均需要动态改写entry文件逻辑, 动态配置路由,
>    之前采取的策略是编写插件, 在 onGetWebpackConfig 编译时把不同场景的入口文件动态和路由配置写到临时文件夹, 再通过 modifyUserConfig 指定入口文件;
>    目前在调研升级ice3, 发现无合适的api

看 demo 都是基于 build-scripts + build-pugin-react-app 的，我理解你的诉求是希望只使用 icejs 的工程能力？

**Comment by smat0096** [comment]
可以这么理解,
希望可以在使用icejs的沉淀出来的模块/插件, 比如build-pugin-react-app, store, route等模块的同时, 
能够自由使用其工程能力, 在编译时对其进行改造, 以应对复杂的业务需求;
@ClarkXia

**Comment by ClarkXia** [comment]
目前还没打算单独开发工程能力，框架目前的启动和运行时是耦合的

**Comment by ClarkXia** [comment]
qiankun 目前支持接入，如果有其他定制能力速度 可以单独提 issue
