### ISSUE TITLE
普通组件支持 Suspense

### ISSUE THREAD

**Issue by chenjun1011** [alibaba/ice#5801]
### Motivation | 背景

只在路由组件支持 Suspense，存在一定的限制：当页面中有多个区块需要被流式返回，以嵌套路由来实现，会导致子组件必须等待父组件 Suspense 成功后才会被执行，请求发起时间相对滞后。https://github.com/alibaba/ice/issues/5697

更理想的方式是普通组件也支持 Suspense，不同区块间相对独立的执行自己的 Suspense 流程。

### Detailed design | 方案设计

通过 ice 导出 `withSuspense` 的高阶组件，用于包裹需要被流式渲染的组件

通过 `withSuspense` 包裹后的组件，额外接受以下参数：
- id 用于唯一标记组件
- fallback 子组件在加载过程中，展示的内容

子组件的编码要求：
- 通过 useSuspenseData 包裹 `数据请求`
- 如需要区分环境，发起不同的数据请求，可以通过  `process.env.ICE_CORE_SSR` 来判断 Server 端环境

代码示例：

```tsx
import { withSuspense, useSuspenseData } from 'ice';

function Comments() {
  const comments = useSuspenseData(getData);

  console.log('Render: Comments');

  return (
    <div>
      {comments.map((comment, i) => (
        <p className="comment" key={i}>
          {comment}
        </p>
      ))}
    </div>
  );
}

export default withSuspense(Comments);
```

使用组件：

```tsx
import { Suspense } from 'react';
import Comments from './Comments';

export default function App() {
  return (
      <Comments id="xxx" fallback={<Loading />} />
  );
}
```

### Additional context | 额外信息

路由组件如需实现 Suspense 能力，可以参考普通组件的做法，将页面中的区块进行流式返回

**Comment by ClarkXia** [comment]
这里传入 dataLoader 的作用是为了能够对数据请求做出差异化的处理，比如 streaming 的时候 throw error 出来，那是不是也可以做成类似一个 hooks，比如

```js
import { getData, Suspense } from 'ice';
function Comments() {
  // useRequest 内部处理好 throw error / 立即执行
  const comments = useRequest(process.env.ICE_CORE_SSR === 'true' ? () => fetch('/a') : () => fetch('/b'));

  return (
    <div>
      {comments.map((comment, i) => (
        <p className="comment" key={i}>
          {comment}
        </p>
      ))}
    </div>
  );
}

export default function SuspenseComments() {
  return (
    <Suspense
      loading={<Loading />}
      fallback={<Fallback />}
    >
      <Comments />
    </Suspense>
  );
}
```

id 的具体作用是什么，如果是为了对应数据和渲染时候的消费，应该也可以在 Suspense 在捕获 error 后生成一个唯一 id

**Comment by chenjun1011** [comment]
- useRequest 可以有，初步验证了可行
- id，前期还是手动传吧，后面结合 Document 改造，看能不能把 useId 用起来

**Comment by chenjun1011** [comment]
还需要讨论的一个问题是：
- 路由组件是否还需要提供 Suspense 能力？ 是不是可以直接使用普通组件来实现 Suspense 能力？这样就不用维护两套实现了

**Comment by ClarkXia** [comment]
> 还需要讨论的一个问题是：
> 
> * 路由组件是否还需要提供 Suspense 能力？ 是不是可以直接使用普通组件来实现 Suspense 能力？这样就不用维护两套实现了

可以从实际效果和使用上考虑下：
- 如果大多数情况只需要启用路由级别就能达到很好的优化效果，这种一键开启的方式对用户体验是最好的
- 反之，如果大多数请求都是要基于组件级别的 Suspense，那路由级别的能力就显得鸡肋，前期可以统一提供通用的 Suspense 能力 即可

**Comment by DremyGit** [comment]
上述的方案有一些值得优化的部分：
* 在组件内部通过 useSuspenseData 进行数据请求，会为组件本身的渲染逻辑带来额外的复杂度，且还需要开发者自行根据 `process.env.ICE_CORE_SSR` 分别进行 Server 请求与 Client 请求，一方面增加开发者上手成本，另一方面还会使得组件逻辑更加混杂。
* 通过 ice 定制 `Suspense` 组件对 `React.Suspense` 组件和 ErrorBoundary 组件等进行封装，会不会与 React 本身所提供的 `Suspense` 组件相混淆？举个例子，一些场景需要通过 `React.lazy` 进行 Client Bundle 的 Code Splitting 优化（React 18 已支持 `React.lazy` on SSR），需要为 lazy 组件使用 `Suspense` 组件进行封装，如何让用户能理解该使用哪一个 `Suspense` 组件？

ice 框架 SSR 通过 dataLoader 和 serverDataLoader 在代码结构层面就对 Client 与 Server 请求做了区分，组件的数据加载方案是不是可以也参考一下？

我这边设想的 Suspense 组件数据加载方案，提供两个 API：
* `withDataLoader`：通过 HOC 封装数据请求、hydration 数据传递、错误处理等核心逻辑
* `useSuspenseData`：通过 React Hook 封装数据取值逻辑

下面是一个该方案的 Demo，首先是创建一个数据组件 DataComponent：

```jsx
import { withDataLoader, useSuspenseData } from 'ice';

const DataComponent = () => {
  // 通过 useSuspenseData API 获取组件数据
  const data = useSuspenseData()
  return (
    <div>{data}</div>
  )
}

/**
 * SSR 降级到 CSR 后的数据获取，透传组件 props
 */
const dataLoader = async (props) => {
  // Client 请求
}

/**
 * 服务端 SSR 数据获取，通过 ctx 传递服务端能力
 */
const serverDataLoader = async (props, ctx) => {
  // Server 请求
}

// 通过 withDataLoader 封装 DataWrapper 和 Error Boundary
export default withDataLoader(DataComponent, {
  // 必须配置 Client 请求方法
  dataLoader,
  // 如果未配置 serverDataLoader，则仅通过 Client 进行请求，满足部分只能通过 Client 进行请求的场景
  serverDataLoader,
  // 当服务端与客户端数据加载或渲染都异常时，在 Client 展示 fallback 组件，支持以下两种写法
  fallback: <div>something wrong...</div>,
  fallback: (error) => <div>Error: {error.message}</div>
});
```

外层组件通过 React 提供的 `Suspense` 组件对数据组件进行包裹，提供流式渲染的组件隔离：

```jsx
import React, { Suspense } from 'react';
import Loading from './component/Loading';
import DataComponent from './component/DataComponent';

// 支持 code spliting 优化
const LazyDataComponent = React.lazy(() => import('./component/DataComponent'))

const App = () => {
  return (
    <div className="app">
      <h1>Ice 3 Suspense SSR</h1>
      <Suspense fallback={<Loading />}>
        {/* 需要为每个数据组件配置页面唯一 id */}
        <DataComponent id="data-component-1" />
      </Suspense>
      <Suspense fallback={<Loading />}>
        <LazyDataComponent id="data-component-2" />
      </Suspense>
    </div>
  )
}
```

**Comment by chenjun1011** [comment]
@DremyGit 提到的两个问题，可以概括为：
- 是否使用 dataLoader 和 serverDataLoader？ 目前的结论是不使用，因为：
   - 使用 serverDataLoader 涉及到需要对所有组件开启代码移除，会存在误伤
   - 另外普通组件的 DataLoader 不存在预加载能力，容易引起混淆
- 是否使用 HOC 的方式来提供 Suspense 能力，我认为两种方式各有利弊，可以再讨论下 @ClarkXia @wssgcg1213 
   - 使用 HOC 的方式，可以直接从 React 引入 Suspense，不用额外说明
   - 使用目前从 ice 导出的 Suspense 的方式，用法比较简单，和 React 保持一致

使用 HOC 的方式，可能的调用方式应是下面这样

```tsx
import { withSuspense, useSuspenseData } from 'ice';

function Comments() {
  const comments = useSuspenseData(getData);

  console.log('Render: Comments');

  return (
    <div>
      {comments.map((comment, i) => (
        <p className="comment" key={i}>
          {comment}
        </p>
      ))}
    </div>
  );
}

export default withSuspense(Comments);
```

```tsx
import { Suspense } from 'react';
import Comments from './Comments';

export default function App() {
  return (
    <Suspense fallback={<Loading />}>
      <Comments />
    </Suspense>
  );
}
 ```

**Comment by chenjun1011** [comment]
对比 HOC 的两种方式：
- 方案一，开启 Suspense 能力需要 3 个步骤
  - 1.  使用 useSuspenseData 包裹数据请求
  - 2.  使用 withSuspense 包裹组件
  - 3.  外层使用 React  Suspense 包裹 

- 方案二，缺点是
  -  组件在使用时，需要额外的传入 fallback、id 等 Suspense 场景下特定的属性，不直观

当前方案，开启 Suspense 只需要两个步骤
-  1.  使用 useSuspenseData 包裹数据请求
- 3.  外层使用 ICE  Suspense 包裹 

总的来说，还是当前方案比较简单直接点

**Comment by chenjun1011** [comment]
线下讨论的结论为 采用方案二，主要原因：
* 和 react 差异化 api
* 额外的属性可通过类型提示解决
* id 问题框架层面进行优化
