### ISSUE TITLE
react微应用带state跳转，vue主应用通过onRouteChange进行router .push 跳转（主要用来加多tab页签），此时页面的state会丢失

### ISSUE THREAD

**Issue by chengiaogiao** [alibaba/ice#5828]
### Describe the bug

react微应用带state跳转，vue主应用通过onRouteChange进行router .push 跳转（主要用来加多tab页签），此时页面的state会丢失

### Expected behavior

react微应用带state跳转，vue主应用通过onRouteChange进行router .push 跳转（主要用来加多tab页签），此时页面的state会丢失

### Version of ice.js

2.0.0

**Comment by ClarkXia** [comment]
duplicate with https://github.com/ice-lab/icestark/issues/655
