### ISSUE TITLE
swc 异常报错

### ISSUE THREAD

**Issue by answershuto** [alibaba/ice#5830]
### Describe the bug

![image](https://user-images.githubusercontent.com/17812136/213850904-3934b1fe-7245-45de-ba8b-4a22e52cfe26.png)

![image](https://user-images.githubusercontent.com/17812136/213851084-9d98cae4-9f7c-42ba-9ead-701c334fdce2.png)

63ca047363367f05652ae329

### Expected behavior

不报错

### Version of ice.js

3.0

**Comment by HomyeeKing** [comment]
这个跟项目代码有没有关系？ 感觉如果是swc的问题的话 初始化的项目应该就打不开

**Comment by HomyeeKing** [comment]
大概排查了下 跟defineDataLoader([]) 有关系

**Comment by answershuto** [comment]
@chenjun1011 帮忙瞅瞅？似乎是 defineDataLoader 的构建问题。

**Comment by chenjun1011** [comment]
原因是 dataLoader 的逻辑使用的是 esbuild 构建

当 esbuild 的 target 设置为 esnext 时，esbuild 会将如下代码转换成 optional chain 的形式

示例：

```js
options === null || options === void 0 ? void 0 : options.ssg
```

转换后

![image](https://user-images.githubusercontent.com/1303018/215720492-aa5865e8-7b36-4b4f-ae8a-4fad968726aa.png)

而在部分 Android 环境下，optional chain 还不支持，导致 JS 解析错误

目前的解决方案是，dataLoader 构建时，默认使用 es2015 标准，和主 Bundle 的 loose 模式保持一致，如果用户自定义了 browserList，则以自定义的为准
