### ISSUE TITLE
分包能力统一

### ISSUE THREAD

**Issue by ClarkXia** [alibaba/ice#5839]
### Motivation | 背景

目前支持 `splitChunks: false` 禁止多余 chunks 的生成，但是框架默认进行了路由级别的 lazy import，导致依旧产出多个 bundle，期望支持 bundle 级别的定制

### Detailed design | 方案设计

统一分包概念，增加 codeSpiliting 的配置，支持以下预置配置：

- `vendors` 策略：将异步 chunks 里的三方依赖统一打入到 vendor.js 中，避免重复，在依赖不变的情况下有效利用缓存。缺陷是如果项目过大会导致单文件尺寸过大。
- `page` 策略：所有路由级别组件按需加载，效果同 `splitChunks: false`。
- `chunks` 策略：在路由级别组件按需加载的基础上，根据模块体积大小自动拆分 chunks，为框架默认推荐策略。

暂时不在 userConfig 上开放 webpack 的 splitChunks，根据用户使用场景逐步优化或增加内置策略

**Comment by wssgcg1213** [comment]
入参类型：Boolean | Enum | Function

- false 表示单 bundle  
- 枚举值
  - "all"
  - "page"
  - "xxx"
- 函数参考下 webpack splitChunk 的处理策略
