### ISSUE TITLE
table 展开行的问题

### ISSUE THREAD

**Issue by JiangJun1994** [alibaba/ice#584]

**Comment by chenbin92** [comment]
检查一下你设置的 `key` 是否都是一样的

**Comment by JiangJun1994** [comment]
我看api没有参数设置key呢？请问你说的key是？我打印onExpandedChange这个函数的参数
expandedRowKeys 和 currentRowKey都是undefined，所以觉得很奇怪。

**Comment by chenbin92** [comment]
@JiangJun1994  参考下这个 demo 对比一下你的代码， `onExpandedChange` 参数验证过没问题。

或者麻烦提供一下最小可复现的代码
