### ISSUE TITLE
ice打包问题咨询

### ISSUE THREAD

**Issue by shaoqun** [alibaba/ice#5842]
你好，我是ice的用户，目前在使用ice的过程中，npm run build打包后的产物

![image](https://user-images.githubusercontent.com/5077811/215931082-75aa96fe-06b8-480e-bc53-855c64b6c880.png)

有这么多的js文件，想咨询下大佬，我如何配置构建参数，才能使所有的js合成一个js，所有的css合成一个css。
![image](https://user-images.githubusercontent.com/5077811/215931134-7ec4cccf-9518-416d-bf30-57bbe5a7f758.png)

目前是这个项目结构，使用ice默认的vite打包。
打包参数如下：
![image](https://user-images.githubusercontent.com/5077811/215931151-4789b83d-4b00-4867-8ac2-20c877831565.png)

**Comment by ClarkXia** [comment]
先确认下项目中是否存在 dynamic import，比如 `lazy(() => import('./xx'))` 的形式

**Comment by shaoqun** [comment]
![image](https://user-images.githubusercontent.com/5077811/215978261-eba77e0f-7e30-4001-88af-f41c9ea435b2.png)
存在你说的dynamic import，但是我去掉后重新build，还是一样

**Comment by shaoqun** [comment]
> 先确认下项目中是否存在 dynamic import，比如 `lazy(() => import('./xx'))` 的形式
![image](https://user-images.githubusercontent.com/5077811/215978261-eba77e0f-7e30-4001-88af-f41c9ea435b2.png)
存在你说的dynamic import，但是我去掉后重新build，还是一样

**Comment by ClarkXia** [comment]
变成 import xxx from 'xxx'; 的形式哈
