### ISSUE TITLE
@alifd/mobile-layout 在 rax-compat 模式下报错

### ISSUE THREAD

**Issue by answershuto** [alibaba/ice#5863]
### Describe the bug

 ice3 工程 使用了 raxcampat 插件，安装 rax 组件 @alifd/mobile-layout，构建报错 报错内容： pragma cannot be set when runtime is automatic
 
原因是 aotumatic 下遇到了 /* @jsx createElement */

### Expected behavior

不报错

### Version of ice.js

3.1.0

**Comment by wssgcg1213** [comment]
写个插件干掉 pragma?

**Comment by answershuto** [comment]
> 写个插件干掉 pragma?

是一种思路
