### ISSUE TITLE
单页面保存， Cannot read properties of null (reading 'store')

### ISSUE THREAD

**Issue by 52myu** [alibaba/ice#5872]
### Describe the bug

fusion创建的项目，首次进入没有问题，只有在单独的页面保存的时候才会报错。
![image](https://user-images.githubusercontent.com/11611897/216930767-b0fc4c7d-e9ae-4004-8147-a41141d9e374.png)
![image](https://user-images.githubusercontent.com/11611897/216931036-33c049ca-6e0a-4656-8b7f-27ef95e26537.png)

![image](https://user-images.githubusercontent.com/11611897/216929910-38305610-1acd-47e4-b587-b5bbe98c8a36.png)
![image](https://user-images.githubusercontent.com/11611897/216930051-e402d420-ff80-4739-8de9-8dcc028c89c1.png)

### Expected behavior

页面保存能正常访问，而不是直接白屏

### Version of ice.js

"ice.js": "^2.0.0"

**Comment by luhc228** [comment]
能否提供一个可复现的 demo? @52myu

**Comment by 52myu** [comment]
项目地址：https://gitee.com/joil12/react-test-layout.git
项目运行后，在BasicLayout页面保存则报错，如不出出现，多ctrl + s一下。
![image](https://user-images.githubusercontent.com/11611897/217745164-2831bb29-69e9-4f8b-80c2-642382011675.png)

**Comment by 52myu** [comment]
> 能否提供一个可复现的 demo? @52myu

项目地址：https://gitee.com/joil12/react-test-layout.git
项目运行后，在BasicLayout页面保存则报错，如不出出现，多ctrl + s一下。
image

**Comment by luhc228** [comment]
> > 能否提供一个可复现的 demo? @52myu
> 
> 项目地址：https://gitee.com/joil12/react-test-layout.git 项目运行后，在BasicLayout页面保存则报错，如不出出现，多ctrl + s一下。 ![image](https://user-images.githubusercontent.com/11611897/217757107-d394eabc-3a4c-406c-b2ab-2d4fcf433f6f.png)

安装依赖后项目启动不起来

**Comment by 52myu** [comment]
> > > 能否提供一个可复现的 demo? @52myu
> > 
> > 
> > 项目地址：https://gitee.com/joil12/react-test-layout.git 项目运行后，在BasicLayout页面保存则报错，如不出出现，多ctrl + s一下。 ![image](https://user-images.githubusercontent.com/11611897/217757107-d394eabc-3a4c-406c-b2ab-2d4fcf433f6f.png)
> 
> 安装依赖后项目启动不起来

是用yarn安装的依赖的么，我删除了node_moubles,直接执行yarn就可以安装跑起来了

**Comment by luhc228** [comment]
跑不起来，你搞一个最小可复现 demo 吧

**Comment by 52myu** [comment]
> 跑不起来，你搞一个最小可复现 demo 吧 @52myu

最小化demo已经上传，
https://gitee.com/joil12/react-test-layout.git
master分支

**Comment by luhc228** [comment]
你项目还是有点复杂。我用 https://github.com/alibaba-fusion/materials/tree/master/scaffolds/fusion-design-pro 在 layout 里面使用了 store，热更新没有问题。你要不自行检查一下差异吧。

<img width="1364" alt="image" src="https://user-images.githubusercontent.com/44047106/220272307-7a2adf5f-40d4-4dca-b680-35b440c98afb.png">
