### ISSUE TITLE
@ice/pkg 1.4.1 版本 构建报错roperty '${variables}' of exported interface has or is using private name '${internal object}'.

### ISSUE THREAD

**Issue by microTT** [alibaba/ice#5873]
### Describe the bug

@ice/pkg 1.4.1版本报错如下图
![image](https://user-images.githubusercontent.com/6782488/216930853-a6ae234a-1a97-4bd2-9046-87bdd756edcc.png)

版本号锁定至1.4.0正常

### Expected behavior

不报错

### Version of ice.js

@ice/pkg 1.4.1

**Comment by ClarkXia** [comment]
https://github.com/ice-lab/icepkg icepkg 相应问题可以到对应仓库提交
