### ISSUE TITLE
修改本地开发端口不生效

### ISSUE THREAD

**Issue by solo-xwz** [alibaba/ice#5874]
### Describe the bug

方法1：
![image](https://user-images.githubusercontent.com/89335154/217118261-c043ebbe-a5f9-4416-ace9-1bfda5a9425d.png)
方法2:
项目根目录创建.env.local
写入DEV_PORT=8081
两种方案都不行，是哪里出问题了

### Expected behavior

端口正确修改

### Version of ice.js

3.1.0

**Comment by ClarkXia** [comment]
通过 `ice start --port 3333` 进行指定。对于环境变量的支持我们在下个版本进行处理
