### ISSUE TITLE
useSuspenseData 中错误处理顺序不对，导致错误没能被处理

### ISSUE THREAD

**Issue by DremyGit** [alibaba/ice#5881]
### Describe the bug

![image](https://user-images.githubusercontent.com/12777132/217464138-040239cf-400d-40e4-868c-46b4699052a0.png)

`done` 和 `error` 的判断顺序不对，导致出错的时候拿不到正确的 `error`，出错被当成成功，但没能被处理

### Expected behavior

上图中 `done` 和 `error` 的判断顺序需要调换

### Version of ice.js

@ice/app@3.1.0, @ice/runtime@1.1.0

**Comment by ClarkXia** [comment]
Fix in #5956
