### ISSUE TITLE
ice 3.0 创建项目 引用图片后报服务端渲染错误

### ISSUE THREAD

**Issue by dengying918** [alibaba/ice#5885]
### Describe the bug

ice 3.0 默认创建应用  启动了ssr 但是  文档写了默认关闭需要手动开启

### Expected behavior

文档需要些正确

### Version of ice.js

3.0

**Comment by ClarkXia** [comment]
ssr 默认关闭，但 ssg 是开启的，推荐写同构代码，可以提供下具体的错误

**Comment by ClarkXia** [comment]
图片问题在 #5937 修复
