### ISSUE TITLE
启动和热更新阶段，建议同 2.x 版本一样增加进度条

### ISSUE THREAD

**Issue by lbarakidouji** [alibaba/ice#5892]
### Motivation | 背景

ice.js 2.x 版本在启动、热更新时都会显示进度条和阶段
3.x 版本目前缺乏，建议增加

### Detailed design | 方案设计

延续 2.x 的设计即可

**Comment by ClarkXia** [comment]
终端日志希望简洁明了，后续考虑提供详细模式，输出处理的模块信息进度，但不会再沿用 webpack bar

**Comment by wssgcg1213** [comment]
进度条其实都是假的, 因为构建是一个边 resolve 边转译的过程, 依赖树有多深是不在一开始就知道的
