### ISSUE TITLE
配置了 browserslist 无效

### ISSUE THREAD

**Issue by answershuto** [alibaba/ice#5894]
### Describe the bug

https://browsersl.ist/#q=supports+es5
配置了 browserslist 无效

### Expected behavior

配置了 browserslist 有效

### Version of ice.js

3.1.0

**Comment by ClarkXia** [comment]
.browserslistrc 设置 ie 10
![image](https://user-images.githubusercontent.com/4219965/218048565-508a5095-aa0a-4d1a-ad8c-dff1cf6141f5.png)

.browserslistrc 设置 chrome 55
![image](https://user-images.githubusercontent.com/4219965/218048316-530d17e2-d6e9-4d31-8dce-baecee438ea3.png)

产物大小有差异 应该是生效的

**Comment by HomyeeKing** [comment]
@ClarkXia  试试 `supports es5` 
看看产物还有没有箭头函数

**Comment by luhc228** [comment]
supports es5 是合法的么

**Comment by HomyeeKing** [comment]
https://browsersl.ist/#q=supports+es5

**Comment by HomyeeKing** [comment]
@ClarkXia  是发了个beta版吗 我看本地start没有生效 部署后是可以的
