### ISSUE TITLE
【fusion样式优先级问题】在global.scss中书写的样式无法覆盖组件库原有样式，体现在优先级低于原有样式

### ISSUE THREAD

**Issue by mocheng119** [alibaba/ice#5903]
### Describe the bug

你好。在使用ice中，我使用了fusion主题并且设计了自定义主题样式，按照文档规范进行了样式引入。其中，各配置文件如下：build.jsonglobal.scss写法如下。但样式未能按照预期进行覆盖。在dev模式下，表现是：初次编译后，样式的顺序能够符合预期，如下图![image](https://user-images.githubusercontent.com/17424780/218360192-92f71757-024c-4981-803d-1c54f62d06eb.png).但当在界面做一次点击操作后，样式的顺序发生了变化，项目内样式优先级低于原组件样式优先级。如下图：
![image](https://user-images.githubusercontent.com/17424780/218362141-347b3086-f156-492f-b9d2-19f67e71d7f1.png)
工程配置如下：build.json
![image](https://user-images.githubusercontent.com/17424780/218362231-ae8c1262-2c67-4b6e-b24b-a9f5f001cdc3.png)
项目中 globa.scss写法
![image](https://user-images.githubusercontent.com/17424780/218362275-1bbd5d1a-1dbb-4e34-8538-70920562d8aa.png)
项目工程dev依赖项版本
![image](https://user-images.githubusercontent.com/17424780/218362470-4ef85567-b74c-4741-a18a-1ed247768291.png)
主题项依赖版本
![image](https://user-images.githubusercontent.com/17424780/218362556-c1734917-a00e-4116-a3d5-a16cb52b00ff.png)

### Expected behavior

预期是：在global.scss中书写的样式应高于fusion原有样式

### Version of ice.js

2.6.6

**Comment by ClarkXia** [comment]
内置的样式权重明显比你配置的高

**Comment by mocheng119** [comment]
> 

https://user-images.githubusercontent.com/17424780/218360192-92f71757-024c-4981-803d-1c54f62d06eb.png  但这图打包出来，自定义的样式优先级是高的。 我不理解它为什么会有如此表现。即使他比我高，那也应该是都高于，而不是在界面有了操作后产生了变化，类名是完全一致的。

**Comment by mocheng119** [comment]
> 

https://user-images.githubusercontent.com/17424780/218360192-92f71757-024c-4981-803d-1c54f62d06eb.png  但这图打包出来，自定义的样式优先级是高的。 我不理解它为什么会有如此表现。即使他比我高，那也应该是都高于，而不是在界面有了操作后产生了变化，类名是完全一致的。

**Comment by mocheng119** [comment]
> 内置的样式权重明显比你配置的高   @ClarkXia 

https://user-images.githubusercontent.com/17424780/218360192-92f71757-024c-4981-803d-1c54f62d06eb.png 但这图打包出来，自定义的样式优先级是高的。 我不理解它为什么会有如此表现。即使他比我高，那也应该是都高于，而不是在界面有了操作后产生了变化，类名是完全一致的。

**Comment by ClarkXia** [comment]
使用了 build-plugin-ignore-style 插件的情况下，fusion 样式应该只会在 global.scss 中引入，可以判断下覆盖的样式来自哪里。
目前暂时无法复现出来这个问题，可以提供个简单的 demo 后重开 issue
