### ISSUE TITLE
阿里低代码引擎中使用rax编写物料，拖拽出了一个页面，想在微信小程序中渲染出这个页面，实现小程序页面热更新，如何实现

### ISSUE THREAD

**Issue by Pzy1990** [alibaba/ice#5916]
### Motivation | 背景

阿里低代码引擎中使用rax编写物料，拖拽出了一个页面，想在微信小程序中渲染出这个页面，实现小程序页面热更新，如何实现

### Detailed design | 方案设计

阿里低代码引擎中使用rax编写物料，拖拽出了一个页面，想在微信小程序中渲染出这个页面，实现小程序页面热更新，如何实现

**Comment by ClarkXia** [comment]
你这个问题是想是搭建的页面支持热更新？如果底层框架不支持基于 ice.js 的需要自行查找微信小程序相关文档

**Comment by wssgcg1213** [comment]
你的问题看起来跟本项目没有关系, 先 Close 了, 如有补充可以 Reopen.
