### ISSUE TITLE
请问ice3.0 怎么配置错误边界处理事件，和配置错误边界页面

### ISSUE THREAD

**Issue by dengying918** [alibaba/ice#5918]
### Summary | 概述

请问ice3.0 怎么配置错误边界处理事件，和配置错误边界页面

### Motivation | 背景

请问ice3.0 怎么配置错误边界处理事件，和配置错误边界页面

### Usage example | 使用示例

请问ice3.0 怎么配置错误边界处理事件，和配置错误边界页面

### Detailed design | 方案设计

请问ice3.0 怎么配置错误边界处理事件，和配置错误边界页面

### Additional context | 额外信息

请问ice3.0 怎么配置错误边界处理事件，和配置错误边界页面

**Comment by ClarkXia** [comment]
https://ice3.alibaba-inc.com/v3/docs/guide/basic/router#%E5%B8%83%E5%B1%80%E7%BB%84%E4%BB%B6  增加一个全局的布局组件，将 <Outlet /> 包再 ErrorBoundary 组件内
