### ISSUE TITLE
切换项目的时候有卡顿的现象

### ISSUE THREAD

**Issue by noyobo** [alibaba/ice#592]
## 环境信息

- 操作系统：
- Iceworks 版本： 2.1.1

**Comment by github-ai** [comment]
![image](https://user-images.githubusercontent.com/6387082/40838932-e0daebe0-65d2-11e8-8fd7-b094b4388ff2.png)
在这里点击切换项目的时候，会卡顿 10 秒左右

**Comment by imsobear** [comment]
新版本目测已经没有这个问题了。
