### ISSUE TITLE
线上资源需代理本地mock数据

### ISSUE THREAD

**Issue by calvinlee2022** [alibaba/ice#5923]
### Summary | 概述

希望线上资源能代理本地mock数据，解决跨域问题

### Motivation | 背景

在代理现在资源开发的时候，有时候需要代理本地mock数据，当发生了跨域行为，希望支持。

### Detailed design | 方案设计

希望本地mock能够添加跨域头

**Comment by ClarkXia** [comment]
明确下是哪个版本的 icejs

**Comment by wssgcg1213** [comment]
https://v3.ice.work/docs/guide/basic/mock

使用框架提供的 mock 能力应该是同域的, 不会存在跨域问题;
