### ISSUE TITLE
ice.js1.x升级按指南升级2.6.6后，npm start提示错误

### ISSUE THREAD

**Issue by rootsli** [alibaba/ice#5924]
升级指南：https://v2.ice.work/docs/guide/upgrade
提示错误如下：options has an unknown property 'before'. These properties are valid(before方法再新版webpack中已被废弃)

`
xxx@roots web-gpx-xxx % npm start 

> xxxx@0.1.0 start /Users/xxxx/Desktop/bss-project/xxxxx
> icejs start --mode local --https

ice.js 2.6.6
info 使用 Fusion 组件主题包： @alifd/theme-20694
HTTPS 证书生成失败，已转换为HTTP
ERR! Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'before'. These properties are valid:
   object { allowedHosts?, bonjour?, client?, compress?, devMiddleware?, headers?, historyApiFallback?, host?, hot?, http2?, https?, ipc?, liveReload?, magicHtml?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, server?, setupExitSignals?, setupMiddlewares?, static?, watchFiles?, webSocketServer? } 
ValidationError: Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'before'. These properties are valid:
   object { allowedHosts?, bonjour?, client?, compress?, devMiddleware?, headers?, historyApiFallback?, host?, hot?, http2?, https?, ipc?, liveReload?, magicHtml?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, server?, setupExitSignals?, setupMiddlewares?, static?, watchFiles?, webSocketServer? }
    at validate (/Users/xxx/Desktop/bss-project/web-gpx-xxx/node_modules/@builder/pack/deps/schema-utils4/index.js:1:22207)
    at new Server (/Users/xxx/Desktop/bss-project/web-gpx-xxx/node_modules/@builder/pack/deps/webpack-dev-server/lib/Server.js:231:5)
    at /Users/xxx/Desktop/bss-project/web-gpx-xxx/node_modules/build-scripts/lib/service/start.js:91:25
    at Generator.next (<anonymous>)
    at fulfilled (/Users/xxx/Desktop/bss-project/web-gpx-xxx/node_modules/build-scripts/lib/service/start.js:5:58) {
  errors: [
    {
      instancePath: '',
      schemaPath: '#/additionalProperties',
      keyword: 'additionalProperties',
      params: [Object],
      message: 'must NOT have additional properties',
      schema: false,
      parentSchema: [Object],
      data: [Object]
    }
  ],
  schema: {
    title: 'Dev Server options',
    type: 'object',
    definitions: {
      AllowedHosts: [Object],
      AllowedHostsItem: [Object],
      Bonjour: [Object],
      Client: [Object],
      ClientLogging: [Object],
      ClientOverlay: [Object],
      ClientProgress: [Object],
      ClientReconnect: [Object],
      ClientWebSocketTransport: [Object],
      ClientWebSocketTransportEnum: [Object],
      ClientWebSocketTransportString: [Object],
      ClientWebSocketURL: [Object],
      Compress: [Object],
      DevMiddleware: [Object],
      HTTP2: [Object],
      HTTPS: [Object],
      HeaderObject: [Object],
      Headers: [Object],
      HistoryApiFallback: [Object],
      Host: [Object],
      Hot: [Object],
      IPC: [Object],
      LiveReload: [Object],
      MagicHTML: [Object],
      OnAfterSetupMiddleware: [Object],
      OnBeforeSetupMiddleware: [Object],
      OnListening: [Object],
      Open: [Object],
      OpenBoolean: [Object],
      OpenObject: [Object],
      OpenString: [Object],
      Port: [Object],
      Proxy: [Object],
      Server: [Object],
      ServerType: [Object],
      ServerEnum: [Object],
      ServerString: [Object],
      ServerObject: [Object],
      ServerOptions: [Object],
      SetupExitSignals: [Object],
      SetupMiddlewares: [Object],
      Static: [Object],
      StaticObject: [Object],
      StaticString: [Object],
      WatchFiles: [Object],
      WatchFilesObject: [Object],
      WatchFilesString: [Object],
      WebSocketServer: [Object],
      WebSocketServerType: [Object],
      WebSocketServerEnum: [Object],
      WebSocketServerFunction: [Object],
      WebSocketServerObject: [Object],
      WebSocketServerString: [Object]
    },
    additionalProperties: false,
    properties: {
      allowedHosts: [Object],
      bonjour: [Object],
      client: [Object],
      compress: [Object],
      devMiddleware: [Object],
      headers: [Object],
      historyApiFallback: [Object],
      host: [Object],
      hot: [Object],
      http2: [Object],
      https: [Object],
      ipc: [Object],
      liveReload: [Object],
      magicHtml: [Object],
      onAfterSetupMiddleware: [Object],
      onBeforeSetupMiddleware: [Object],
      onListening: [Object],
      open: [Object],
      port: [Object],
      proxy: [Object],
      server: [Object],
      setupExitSignals: [Object],
      setupMiddlewares: [Object],
      static: [Object],
      watchFiles: [Object],
      webSocketServer: [Object]
    }
  },
  headerName: 'Dev Server',
  baseDataPath: 'options',
  postFormatter: null
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! web-gpx-xxx@0.1.0 start: `icejs start --mode local --https`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the web-gpx-xxx@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2023-02-16T05_03_00_348Z-debug.log
`

**Comment by ClarkXia** [comment]
看着像部分依赖没有升级成功，提供下 package.json 和 build.json 信息

**Comment by rootsli** [comment]
`package.json
{
  "name": "web-gpx-subapp",
  "version": "0.1.0",
  "scripts": {
    "start": "icejs start --mode local",
  },
  "dependencies": {
    "@alifd/next": "^1.22.17",
    "@alifd/theme-20694": "^2.2.2",
    "@ice/stark-app": "^1.4.0",
    "@ice/stark-data": "^0.1.2",
    "ahooks": "^2.9.6",
    "bigdecimal": "^0.6.1",
    "build-plugin-icestark": "^1.7.2",
    "echarts": "^4.9.0",
    "echarts-for-react": "^2.0.16",
    "js-base64": "^2.5.2",
    "js-big-decimal": "^1.3.4",
    "js-cookie": "^2.2.1",
    "moment": "^2.29.1",
    "prop-types": "^15.7.2",
    "qrcode.react": "^3.0.2",
    "react": "^16.14.0",
    "react-countdown": "^2.3.1",
    "react-dom": "^16.14.0",
    "react-to-print": "^2.12.3",
    "react-use-websocket": "^1.6.1",
    "sc-gpx-react-fusion-component-common-dialog": "^2.0.11",
    "sc-gpx-react-fusion-component-common-tab": "^2.0.1",
    "sc-gpx-react-fusion-component-create-form": "^2.0.55",
    "sc-gpx-react-fusion-component-doc-seal": "^2.0.26",
    "sc-gpx-react-fusion-component-dynamic-list": "^2.0.7",
    "sc-gpx-react-fusion-component-fixed-footer": "^2.0.1",
    "sc-gpx-react-fusion-component-info-list": "^2.0.2",
    "sc-gpx-react-fusion-component-loading": "^2.0.2",
    "sc-gpx-react-fusion-component-pagination-card-list": "^2.0.3",
    "sc-gpx-react-fusion-component-pdf-seal": "^2.0.19",
    "sc-gpx-react-fusion-component-portal": "^2.0.1",
    "sc-gpx-react-fusion-component-print": "^2.0.2",
    "sc-gpx-react-fusion-component-purchaser-select-dialog": "^2.0.1",
    "sc-gpx-react-fusion-component-quick-dialog": "^2.0.6",
    "sc-gpx-react-fusion-component-scroll-card-list": "^2.0.0",
    "sc-gpx-react-fusion-component-search-form": "^2.0.7",
    "sc-gpx-react-fusion-component-search-tag": "^2.0.2",
    "sc-gpx-react-fusion-component-step": "^2.0.1",
    "sc-gpx-react-fusion-component-subpage-layout": "^2.1.18",
    "sc-gpx-react-fusion-component-supplier-select-dialog": "^2.0.2",
    "sc-gpx-react-fusion-component-tab": "^2.0.1",
    "sc-gpx-react-fusion-component-table": "^2.0.5",
    "sc-gpx-react-fusion-component-upload": "^2.0.9",
    "spark-md5": "^3.0.1",
    "use-animate-number": "^1.0.5"
  },
  "devDependencies": {
    "@ice/spec": "^1.0.0",
    "build-plugin-css-assets-local": "^0.1.0",
    "build-plugin-fusion": "^0.1.13",
    "build-plugin-moment-locales": "^0.1.0",
    "eslint": "^6.0.1",
    "ice.js": "^2.6.6",
    "react-dev-inspector": "^1.8.1",
    "stylelint": "^13.11.0"
  },
  "ideMode": {
    "name": "ice-react"
  },
  "iceworks": {
    "type": "react",
    "adapter": "adapter-react-v3"
  },
  "resolutions": {
    "colorette": "1.2.0",
  },
  "engines": {
    "node": ">=8.0.0"
  },
  "private": true,
  "originTemplate": "sc-gpx-react-fusion-scaffold-spa"
}
`

`build.json
{
  "publicPath": "/gpx-subapp/",
  "hash": "contenthash",
  "outputDir": "dist",
  "polyfill": "entry",
  "eslint": false,
  "sourceMap": false,
  "compileDependencies": [""],
  "modeConfig": {
    "local": {
      "sourceMap": true
    },
    "dev": {
      "sourceMap": true
    },
    "prod": {
      "minify": {
        "type": "terser",
        "options": {
          "compress": {
            "drop_console": true,
            "drop_debugger": true
          }
        }
      }
    },
    "publish": {
      "outputDir": "build"
    }
  },
  "browserslist": {
    "chrome": 49,
    "ie": 11
  },
  "plugins": [
    "react-dev-inspector/plugins/ice",
    "build-plugin-icestark",
    [
      "build-plugin-fusion",
      {
        "themePackage": "@alifd/theme-20694"
      }
    ],
    "./build.plugin.js",
    [
      "build-plugin-moment-locales",
      {
        "locales": ["zh-cn"]
      }
    ],
    [
      "build-plugin-css-assets-local",
      {
        "outputPath": "assets",
        "relativeCssPath": "../",
        "activeInDev": false
      }
    ]
  ],
  "proxy": {
  }
}

`

> 看着像部分依赖没有升级成功，提供下 package.json 和 build.json 信息

@ClarkXia

**Comment by rootsli** [comment]
@ClarkXia 已解决，react-dev-inspector组件问题。
