### ISSUE TITLE
升级到3.1.0后启动报错，并且错误提示中代码位置有误

### ISSUE THREAD

**Issue by anobaka** [alibaba/ice#5931]
### Describe the bug

![image](https://user-images.githubusercontent.com/2888789/219320946-62219e80-4d80-4903-bdf0-4df9710dddeb.png)
![image](https://user-images.githubusercontent.com/2888789/219321102-024ef9e2-4ecf-4001-8517-f0c74566b321.png)

### Expected behavior

2.x版本正常
希望至少能有正确的代码位置，否则很难找到问题

### Version of ice.js

3.1.0

### Content of build.json or ice.config.mts

```TypeScript
import { defineConfig } from '@ice/app';
import store from '@ice/plugin-store';

// The project config, see https://v3.ice.work/docs/guide/basic/config
export default defineConfig(() => ({
  ssr: false,
  ssg: false,
  plugins: [
    store(),
  ],
  routes: {
  },
}));
```

**Comment by ClarkXia** [comment]
最好提供复现问题的代码片段

**Comment by anobaka** [comment]
感谢您的回复，
不好意思由于项目紧急，调整为`自定义路由`(by `defineRoutes`)后可以正常运行。
暂时先关闭issue，等后续有空了再提供minimal repro。
