### ISSUE TITLE
@ice/lite-scaffold 模板，配置 fusion 主题包后，logo 图片加载失败

### ISSUE THREAD

**Issue by AlbertXiao1994** [alibaba/ice#5933]
### Describe the bug

如图所示，配置主题包后，logo 加载失败，不配置时正常
![image](https://user-images.githubusercontent.com/23646755/219340392-b125e859-b983-4f63-ae17-5586f25ac55a.png)

![image](https://user-images.githubusercontent.com/23646755/219340137-c0c00cb2-ce06-415d-b20d-e8fc96726731.png)

### Expected behavior

正常加载图片

### Version of ice.js

3.1.0

**Comment by ClarkXia** [comment]
确认为 fusion 插件问题，下周一修复发布
