### ISSUE TITLE
.ice 目录下的类型错误

### ISSUE THREAD

**Issue by ClarkXia** [alibaba/ice#5939]
### Motivation | 背景

![image](https://user-images.githubusercontent.com/4219965/219611491-4dd68b81-e74c-4754-b151-fe1d14a10b05.png)

### Detailed design | 方案设计

包下面增加 type.d.ts 文件以支持 exports 导入的类型提示

**Comment by luhc228** [comment]
### 方案

假设现在在 esm 目录有以下的 d.ts 产物：

```md
esm
   ├── hooks.js
   ├── hooks.d.ts
   ├── request.js
   └──  request.d.ts
```

并且我们明确知道这两个文件是需要被导出的：

```json
{
  "exports": {
    "./hooks": {
      "import": "./esm/hooks.js"
    },
   "./request": {
      "import": "./esm/request.js"
    }
  }
}
```

那么我们可以在根目录下新建两个 d.ts 文件：
```md
├── hooks.d.ts
├── request.d.ts
 └──  package.json
```

```ts
// hooks.d.ts
export * from './esm/hooks';
```

这样在 `import hooks from 'your-package-name/hooks';` 的时候编辑器就不会报错了

**Comment by wssgcg1213** [comment]
@luhc228 所以这个本质原因是 exports 里面声明的导出也需要有同名的 `.d.ts` 文件吗?
