### ISSUE TITLE
使用build-plugin-keep-alive  如何自定义取消缓存呢

### ISSUE THREAD

**Issue by wx9999** [alibaba/ice#5942]
### Describe the bug

<img width="379" alt="image" src="https://user-images.githubusercontent.com/42061047/219955301-bb06c02c-3a6c-4f96-a237-4f3b7d6ac689.png">
用户如何自定义销毁缓存呢，有没有具体的文档

### Expected behavior

用户如何自定义销毁缓存，有没有具体的文档

### Version of ice.js

2.0.0

**Comment by ClarkXia** [comment]
具体指什么，动态变化 keepAlive 的值？

**Comment by wx9999** [comment]
> 具体指什么，动态变化 keepAlive 的值？
> 
> What exactly does that mean, dynamically changing the value of keepAlive?
是的呢，
<img width="511" alt="image" src="https://user-images.githubusercontent.com/42061047/220055852-85c0c090-bd97-4f79-a785-e5eb6c25d028.png">
希望可以点击刷新的时候 销毁缓存

**Comment by ClarkXia** [comment]
目前还没有这个动态的机制，需要设计下

**Comment by wx9999** [comment]
> 目前还没有这个动态的机制，需要设计下

请问有其他方案可以替代嘛

**Comment by ClarkXia** [comment]
> > 目前还没有这个动态的机制，需要设计下
> 
> 请问有其他方案可以替代嘛

可以不借助插件 自行使用 keepAlive 组件 https://github.com/alibaba/ice/blob/stable/2.x/packages/plugin-keep-alive/src/runtime.tsx
