### ISSUE TITLE
ice3是否能提供支持页面按需加载的方式

### ISSUE THREAD

**Issue by tanyafuzhou** [alibaba/ice#5943]
当应用中页面逐渐增加时, 应用的构建速度就会相应减慢; 
ice3是否能支持页面按需加载的方式: 某次构建, 只构建某个页面, 其他页面不构建

**Comment by ClarkXia** [comment]
暂时不会考虑类似的构建方式，可以参考以下逻辑进行构建的优化：
目前不论是 start 还是 build，构建后都会有对应的 cache。可以考虑将 cache 内容也作为构建的依赖，这样未变更的逻辑将会通过缓存大大提升
