### ISSUE TITLE
ice3.0初始化项目后，./ice/index.tsx 内部的引入资源报错，造成useRequest没有正确的参数提示。

### ISSUE THREAD

**Issue by HowCanLove** [alibaba/ice#5959]
### Describe the bug

<img width="1315" alt="屏幕快照 2023-02-22 下午11 42 47" src="https://user-images.githubusercontent.com/15058500/220675794-3299eaf5-6087-4de8-addb-e828db07b9ef.png">

是ts哪里少配置了什么东西么？

### Expected behavior

ts依赖正常加载

### Version of ice.js

3.0

**Comment by luhc228** [comment]
重复 issue #5922
