### ISSUE TITLE
开启 hash 路由后，无法获取页面配置

### ISSUE THREAD

**Issue by luhc228** [alibaba/ice#5961]
### Describe the bug

开启 hash 路由后，在插件中无法通过 [`useConfig`](https://v3.ice.work/docs/guide/plugins/plugin-dev#useconfig) 的方式获取页面配置（获取到的内容是 `{}`）

### Expected behavior

能正常获取页面配置

### Version of ice.js

3.1.1

**Comment by ClarkXia** [comment]
fixed in 3.2.0+
