### ISSUE TITLE
编译时经常会卡在37%和51%，有没有什么办法可以知道原因？

### ISSUE THREAD

**Issue by aak1247** [alibaba/ice#5962]
比如37%和51%对应的阶段是什么？或者有没有办法查看更详细的编译日志？

**Comment by aak1247** [comment]
尝试了DEBUG=icejs，但是在这两个节点没有输出东西

**Comment by ClarkXia** [comment]
版本信息提供下  考虑增加 https://www.npmjs.com/package/speed-measure-webpack-plugin 来确定具体是什么节点耗时比较久

**Comment by aak1247** [comment]
> 版本信息提供下 考虑增加 https://www.npmjs.com/package/speed-measure-webpack-plugin 来确定具体是什么节点耗时比较久

node: 16.13

```json
{
  "devDependencies": {
    "hife-spec": "*",
    "@iceworks/spec": "^1.6.0",
    "@types/react-window": "^1.8.5",
    "@types/react": "^17.0.14",
    "@types/react-dom": "^17.0.9",
    "@babel/preset-react": "^7.18.6",
    "cz-conventional-changelog": "^3.3.0",
    "cz-conventional-emoji": "^1.0.2",
    "style-loader": "^1.2.1",
    "css-loader": "^3.6.0",
    "postcss": "^8.4.17",
    "eslint": "7.30.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-prettier": "^4.2.1",
    "html-webpack-plugin": "^4.3.0",
    "extract-text-webpack-plugin": "^3.0.2",
    "build-plugin-antd": "^0.1.0",
    "build-plugin-fusion": "^0.1.23",
    "build-plugin-icestark": "^2.5.5",
    "build-plugin-moment-locales": "^0.1.0",
    "husky": "^7.0.2",
    "lint-staged": "^10.0.7",
    "ice.js": "^2.6.6",
    "stylelint": "^13.7.2"
  }

}

```

**Comment by ClarkXia** [comment]
推荐通过自定义方式增加 https://www.npmjs.com/package/speed-measure-webpack-plugin 插件进心排查 https://ice2.alibaba-inc.com/docs/guide/basic/build#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%B7%A5%E7%A8%8B%E9%85%8D%E7%BD%AE

**Comment by ClarkXia** [comment]
先通过上述插件排查，如果有更多信息提供，再重开 issue

**Comment by aak1247** [comment]
这个插件的用法比较特殊：
```js
const SpeedMeasurePlugin = require("speed-measure-webpack-plugin");

const smp = new SpeedMeasurePlugin();

const webpackConfig = smp.wrap({
  plugins: [new MyPlugin(), new MyOtherPlugin()],
});
```

**Comment by linshaoye** [comment]
@aak1247 你知道如何在ice里使用speed-measure-webpack-plugin"

**Comment by xinyiPig** [comment]
> 推荐通过自定义方式增加 https://www.npmjs.com/package/speed-measure-webpack-plugin 插件进心排查 https://ice2.alibaba-inc.com/docs/guide/basic/build#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%B7%A5%E7%A8%8B%E9%85%8D%E7%BD%AE

这个链接能打开？

**Comment by xinyiPig** [comment]
> 自定义方式

有下文的话，滴我一下，谢谢

**Comment by xinyiPig** [comment]
>  @aak1247 你知道如何在ice里使用speed-measure-webpack-plugin"
有下文的话，请滴我一下

**Comment by dlpuzhangyue** [comment]
<img width="476" alt="image" src="https://github.com/alibaba/ice/assets/29819173/fd2867ba-23e9-4823-88c2-ed17b5b6d445">
复现了！
@ClarkXia

**Comment by aak1247** [comment]
@dlpuzhangyue 快让我学习一下

**Comment by dlpuzhangyue** [comment]
> @dlpuzhangyue 快让我学习一下

文件多了一下Loader过程缓慢，但是无法定位是什么loader导致的

**Comment by dlpuzhangyue** [comment]
> @dlpuzhangyue快让我学习一下

作者回复了 让升级3.x 我这升一下太痛了 放弃了 卡着去吧

**Comment by aak1247** [comment]
> 作者回复了 让升级3.x 我这升一下太痛了 放弃了 卡着去吧
确实有点困难。。。
