### ISSUE TITLE
ice3增加modifyRoutes的能力

### ISSUE THREAD

**Issue by wittech** [alibaba/ice#5970]
### Motivation | 背景

原有业务中有许多场景需要使用modifyRoutes，根据服务端配置动态调整前端的路由，升级ice3后发现无法支持。

### Detailed design | 方案设计

建议ice3增加modifyRoutes的支持

**Comment by ClarkXia** [comment]
有点像 https://github.com/alibaba/ice/issues/4973 这个逻辑，服务端可以下发，但实际上路由组件可能是前端提前写好的。
可以考虑动态路由 / 权限控制的方式去做。
也可以详细描述下项目之前 modifyRoutes 的用法

**Comment by wittech** [comment]
动态路由目前看是同一个文件只能支持一个路由地址，我们之前的逻辑是多个路由都指向的同一个页面地址，这个需求应该如何解决呢？

**Comment by wittech** [comment]
同一个路由组件只能分配一条路由规则，即同时执行以下语句时，仅生效后执行的逻辑。

route('/about-me', 'about.tsx');
route('/about-you', 'about.tsx');

这里能支持多个规则？

**Comment by ClarkXia** [comment]
类似如下逻辑

```js
// 比如 ice.config.mts 里增加一条动态规则

route('/:route', 'route.tsx');


// route.tsx 内部再进行渲染的确定

function Route() {
  const { route } = useParams();
  return route === 'about-me' ? <AboutMe /> : <AboutYou />;
}
```

**Comment by wittech** [comment]
好的，我试试这个方案，感谢！
