### ISSUE TITLE
dataLoader dev 阶段抛找不到 object-inspect 的异常

### ISSUE THREAD

**Issue by answershuto** [alibaba/ice#5974]
### Describe the bug

![image](https://user-images.githubusercontent.com/17812136/221151357-3240b7ae-878d-4316-b76f-b26007780695.png)

### Expected behavior

正常构建

### Version of ice.js

3.1.1

**Comment by chenjun1011** [comment]
这个问题在于 `object-inspect` 有几个特殊之处：

1 对 `util.inspect` 文件的引用是这样的

```js
var utilInspect = require('./util.inspect');
```

2. 同时在 package.json 声明了

```json
  "browser": {
    "./util.inspect.js": false
  },
```

意思是在构建产物为 browser 时，ignore 掉文件 `./util.inspect.js` 

esbuild 会识别上面这个配置，不会在 onLoad 的时候为文件 path  补上 `.js` 后缀

在 ICE 的 tansform 逻辑中，会基于 esbuild 给的文件 path 去读取真实文件，由于没有带文件后缀，文件读取失败报错
