### ISSUE TITLE
主应用中@alifd/next的样式未加载正确的类名

### ISSUE THREAD

**Issue by lanlinxi** [alibaba/ice#5977]
### Describe the bug

主应用构建添加了css-prefix后，使用@alifd/next组件类名添加了前缀但是项目加载的css未添加前缀

### Expected behavior

组件的css正常加载

### Version of ice.js

2.x

### Content of build.json or ice.config.mts

```TypeScript
{
  "vite": true,
  "plugins": [
    "@ali/build-plugin-faas",
    [
      "build-plugin-moment-locales",
      {
        "locales": [
          "zh-cn"
        ]
      }
    ],
    [
      "build-plugin-ignore-style",
      {
        "libraryName": "@alifd/next"
      }
    ],
    "@ali/build-plugin-ice-def",
    [
      "build-plugin-icestark", 
      {
        "type": "framework",
        "uniqueName": "frameworkJsonp"
      }
    ],
    [
      "build-plugin-fusion", 
      {
        "themeConfig": {
          "css-prefix": "next-icestark-",
          "next-prefix": "next-icestark-",
          "nextPrefix": "next-icestark-"
        }
      }
    ]
  ]
}
```

**Comment by ClarkXia** [comment]
全量样式怎么引入的？，可以考虑去掉 build-plugin-ignore-style 按需引入样式试下

**Comment by lanlinxi** [comment]
在global.scss中
@import '@alifd/theme-weaving/variables.scss';
@import '@alifd/theme-weaving/dist/next.css';

**Comment by ClarkXia** [comment]
@alifd/theme-weaving/dist/next.css 是编译好的全量 css 文件，要么引入 scss 要么可以参考 
https://github.com/ice-lab/react-materials/blob/master/scaffolds/icestark-layout 官方 demo 做法

**Comment by lanlinxi** [comment]
直接引入这个文件？ @import '@alifd/next/index.scss';

**Comment by ClarkXia** [comment]
> 直接引入这个文件？ @import '@alifd/next/index.scss';

是的

**Comment by lanlinxi** [comment]
引入scss文件就行了，感谢
