### ISSUE TITLE
React模板ICE Design CMS启动报错

### ISSUE THREAD

**Issue by lilegang1589** [alibaba/ice#598]
## 环境信息

- 操作系统：win 10
- Iceworks 版本： 
2.1.1
## 问题描述
ICE Design CMS
该模板启动报错

## 错误信息
'ice' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @icedesign/cms-scaffold@1.0.0 start: `ice dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @icedesign/cms-scaffold@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lileg\AppData\Roaming\npm-cache\_logs\2018-06-02T14_21_11_568Z-debug.log

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\lileg\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.0.0
3 info using node@v6.10.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle @icedesign/cms-scaffold@1.0.0~prestart: @icedesign/cms-scaffold@1.0.0
6 info lifecycle @icedesign/cms-scaffold@1.0.0~start: @icedesign/cms-scaffold@1.0.0
7 verbose lifecycle @icedesign/cms-scaffold@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle @icedesign/cms-scaffold@1.0.0~start: PATH: C:\Users\lileg\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\lileg\iceworks-workspace\ReactDemo\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Java\jdk1.8.0_66\bin;C:\Program Files\Java\jdk1.8.0_66\jre\bin;C:\tomcat8.0\lib;C:\tomcat8.0\bin;C:\maven3.3.9\bin;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\MySQL\MySQL Server 5.1\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\lileg\AppData\Local\Microsoft\WindowsApps;C:\Users\lileg\AppData\Roaming\npm;C:\Users\lileg\AppData\Local\atom\bin;C:\Program Files\Microsoft VS Code\bin
9 verbose lifecycle @icedesign/cms-scaffold@1.0.0~start: CWD: C:\Users\lileg\iceworks-workspace\ReactDemo
10 silly lifecycle @icedesign/cms-scaffold@1.0.0~start: Args: [ '/d /s /c', 'ice dev' ]
11 silly lifecycle @icedesign/cms-scaffold@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle @icedesign/cms-scaffold@1.0.0~start: Failed to exec start script
13 verbose stack Error: @icedesign/cms-scaffold@1.0.0 start: `ice dev`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\lileg\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:283:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\lileg\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:886:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid @icedesign/cms-scaffold@1.0.0
15 verbose cwd C:\Users\lileg\iceworks-workspace\ReactDemo
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\lileg\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v6.10.2
19 verbose npm  v6.0.0
20 error code ELIFECYCLE
21 error errno 1
22 error @icedesign/cms-scaffold@1.0.0 start: `ice dev`
22 error Exit status 1
23 error Failed at the @icedesign/cms-scaffold@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by chenbin92** [comment]
项目依赖安装失败了，需要重新安装一下依赖

![](https://img.alicdn.com/tfs/TB1mCJjvDtYBeNjy1XdXXXXyVXa-1598-226.png)
