### ISSUE TITLE
如何在ice中引入ant design？

### ISSUE THREAD

**Issue by huyifan** [alibaba/ice#602]
看了下antd的官网介绍

```
npm install --save-dev antd 
```
然后需要怎么做呢？

直接在代码里引用
```
import { Button } from 'antd';

```
并没有什么效果

**Comment by chenbin92** [comment]
ICE 模板中都默认引入了 icedesign 基础组件包，如果需要引入 antd-design 可以按照他们的提供配置文档做自定义接入，具体参考 [使用 babel-plugin-import](https://ant.design/docs/react/use-with-create-react-app-cn#%E4%BD%BF%E7%94%A8-babel-plugin-import) 

另外，可能有样式的重复加载和冲突需要注意下。
