### ISSUE TITLE
build 失败，dev正常

### ISSUE THREAD

**Issue by solo-xwz** [alibaba/ice#6022]
### Describe the bug

1. build失败：

```
webpack 5.75.0 compiled successfully in 17929 ms
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, open 'E:\MyProject\xice\build\*.html'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'E:\\MyProject\\xice\\build\\*.html'
```
而且制定了ssg和ssr均为false，编译产物怎么还有server

2. 指定开发端口无效 `cross-env PORT=8088 npm start`

### Expected behavior

正常编译

### Actual behavior

编译失败

### Version of ice.js

3.1.2

**Comment by ClarkXia** [comment]
windows 下通配路由生成的特殊字符的问题，下个版本将会修复

**Comment by solo-xwz** [comment]
> windows 下通配路由生成的特殊字符的问题，下个版本将会修复

请问下个版本什么时候发布

**Comment by ClarkXia** [comment]
> > windows 下通配路由生成的特殊字符的问题，下个版本将会修复
> 
> 请问下个版本什么时候发布

下周四 如果紧急要用，明天可以发布一个 beta 版本

**Comment by solo-xwz** [comment]
急用，麻烦发个beta版，谢谢

**Comment by solo-xwz** [comment]
> > > windows 下通配路由生成的特殊字符的问题，下个版本将会修复
> > 
> > 
> > 请问下个版本什么时候发布
> 
> 下周四 如果紧急要用，明天可以发布一个 beta 版本

急用，麻烦发个beta版，谢谢

**Comment by ClarkXia** [comment]
https://www.npmjs.com/package/@ice/app/v/3.1.3-alpha.0
