### ISSUE TITLE
页面 models 调用 页面 services 错误

### ISSUE THREAD

**Issue by rskmin** [alibaba/ice#6028]
### Describe the bug

我在页面级的 models 下尝试调用页面级的 services 出现了错误，这属于正常现象么？

![image](https://user-images.githubusercontent.com/49187760/223409685-2060dcfb-94e7-4efc-9109-a661707623cf.png)

![image](https://user-images.githubusercontent.com/49187760/223411494-9df5396f-dc3f-4014-bbdd-0eb224745af7.png)

![image](https://user-images.githubusercontent.com/49187760/223409049-4f64e711-a4fd-4682-81d4-27dec98fa3d1.png)

### Expected behavior

页面 models 下能正常调用页面 services 下定义的 API

### Version of ice.js

3.0.0

**Comment by rskmin** [comment]
我将页面级数据请求提升为全局数据请求解决了这个问题，但是我依旧无法理解为什么页面级 models 无法使用页面级 services，我希望能得到一份详细的说明。

**Comment by ClarkXia** [comment]
提供下 `ice.config.mts` 的配置

**Comment by luhc228** [comment]
你需要添加类似 `pages/*/services/**` 到 [`routes.ignoreFiles`](https://v3.ice.work/docs/guide/basic/config#ignorefiles)，否则它会当做是路由文件去进行处理。

**Comment by rskmin** [comment]
是的我通过添加 routes.ignoreFiles 成功了，感谢，这太容易被忽视了
