### ISSUE TITLE
ice3能否支持react17？

### ISSUE THREAD

**Issue by suprise** [alibaba/ice#6030]
### Motivation | 背景

ice3能否支持react17？如果不支持的话，很多依赖的物料库和三方库需要同步升级react18，依赖和成本都比较大

### Detailed design | 方案设计

ice3支持react17

**Comment by ClarkXia** [comment]
ice 3 设计上把 SSR 的实践放在比较重要的位置，内部应用了比较多的 react 18 特性
从之前的实践上来看，大部分 react 17 组件可以在 react 18 下运行，可以看下具体需要改造的成本以及具体 API 是哪些
