### ISSUE TITLE
SSG 默认情况下是否应该关闭？

### ISSUE THREAD

**Issue by linbudu599** [alibaba/ice#6049]
### Describe the bug

SSG 感觉和日常的 CSR 页面还是有一定差异，并不能完全兼容使用场景与心智习惯。我前段时间在内部创建了第一个 ICE3 应用，遇到了 `styled-components` 与 `window.lib.mtop` 无法使用的问题，从报错出发疑似为 SSR 相关，但显式关闭后仍然存在，提了答疑工单才知道还有个 SSG。

- SSG 默认开启确实会有一定性能优化，但是否会影响此前无相关经验的同学首次使用，尤其是外部社区的使用者？
- 一些内部库也无法在 SSG 下正常工作，如 universal-user 会在全局注入 `window.__preload_scripts__`，这些是否有相关考量？
- 如果 SSG 开启的构建失败，是否能自动降级后重新构建？

### Expected behavior

默认关闭 SSG，或在 SSG 构建失败时自动降级。

### Version of ice.js

3.1.0

**Comment by ClarkXia** [comment]
默认开启就是为了提前暴露一些代码库潜在的问题，比如立即执行逻辑。
对于纯 assets 项目目前是在模版的配置上关闭的，但对于简单的 C 端项目，我们期望培养大家这方面的意识，前置知道一些问题。
后续也会考虑推进以下的事情：
- 常用基础库的同构，比如上面提到的 mtop、universal-xxx 等
- SSG 构建失败的更加完善的日志提示
