### ISSUE TITLE
在安装@ice/plugin-request插件之后，dataLoader.js 出现 Cannot use import statement outside a module

### ISSUE THREAD

**Issue by 1ncounter** [alibaba/ice#6059]
### Describe the bug

在安装@ice/plugin-request插件，启动项目出现如下错误提示：
![image](https://user-images.githubusercontent.com/19562558/225195386-3b0c2558-753b-45ef-b9c8-609d12aa3d06.png)
具体代码错误点如下：
![image](https://user-images.githubusercontent.com/19562558/225195654-2959db9c-dc1d-44a8-b160-553d810dc055.png)

### Expected behavior

不出现异常提示

### Actual behavior

如上

### Version of ice.js

3.1.2

### Content of build.json or ice.config.mts

```TypeScript
import request from '@ice/plugin-request';

plugins: [
  request()
]
```

**Comment by wssgcg1213** [comment]
本地试了一下, 本没有复现成功

@ice/app 3.1.2 + request 插件 1.0.1
