### ISSUE TITLE
能不能提供基础组件，比如文本框，下拉框，供用户做更灵活的页面的定制

### ISSUE THREAD

**Issue by Aubergines** [alibaba/ice#606]
## 环境信息

- 操作系统：
- Iceworks 版本：

**Comment by noyobo** [comment]
https://alibaba.github.io/ice/component/input
https://alibaba.github.io/ice/component/select

这类基础组件是否满足需求？

**Comment by Aubergines** [comment]
这些也可以，不过作为一个后端开发人员来说，写这个也是比较费劲的，希望有一个可供简单的拖拽基础组件就能生成对应的页面，毕竟中后台的产品，很多时候需要的东西都很灵活，繁杂

**Comment by noyobo** [comment]
这块功能我们有在研发，预计在 8 月会开放使用。
