### ISSUE TITLE
ICE Design CMS 模板在 IE11 下一篇空白

### ISSUE THREAD

**Issue by yujiangshui** [alibaba/ice#607]
## 环境信息

- 操作系统：win IE 11
- Iceworks 版本： 

## 问题描述

https://alibaba.github.io/ice/scaffold-preview/ice-design-cms.html#/ 这套模板在 IE11 下有兼容性问题。

## 错误信息

![image](https://user-images.githubusercontent.com/2942913/40964505-e2d39efc-68dd-11e8-96cd-84127d2f6ecb.png)

**Comment by wssgcg1213** [comment]
有ES6没有编译, 可以定位一下具体的包
