### ISSUE TITLE
Ice.js 2.x版本下，如何在配置中添加 Node 核心模块的支持？

### ISSUE THREAD

**Issue by Lpbzzz** [alibaba/ice#6077]
这个Issue 中解答了webpack模式下的方法：https://github.com/alibaba/ice/issues/4654
 如何在vite模式下使用？

**Comment by ClarkXia** [comment]
client 本身就不应该使用 node 内置包，如果真的有应用场景，可以考虑通过 alias 的方式。比如内置 path 模块可以 alias 到 path-browserify

**Comment by Lpbzzz** [comment]
> client 本身就不应该使用 node 内置包，如果真的有应用场景，可以考虑通过 alias 的方式。比如内置 path 模块可以 alias 到 path-browserify

好吧。这种需求，有些第三方包绕不过去。
