### ISSUE TITLE
编辑器可以支持hbuilder吗

### ISSUE THREAD

**Issue by collaborator-one** [alibaba/ice#608]
## 环境信息

- 操作系统：
- Iceworks 版本：

**Comment by collaborator-one** [comment]
可以支持hbuilder吗

**Comment by chenbin92** [comment]
@collaborator-one  麻烦详细描述下你的需求

**Comment by noyobo** [comment]
编辑器的预设目前只有几个常用的，这块通过自定义编辑器来支持。

**Comment by noyobo** [comment]
2.6.0 版本通过设置 编辑器启动脚本   例如 `subl ${cwd}`
