### ISSUE TITLE
build-plugin-pwa一直打印workbox日志

### ISSUE THREAD

**Issue by jwzha** [alibaba/ice#6100]
### Describe the bug

使用"build-plugin-pwa": "1.1.2-alpha.0"，workbox日志一直打印，每次重新刷新页面将近5000条日志

### Expected behavior

关闭workbox日志打印

### Version of ice.js

2

**Comment by ClarkXia** [comment]
通过[自定义插件](https://v2.ice.work/docs/guide/basic/build/#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%B7%A5%E7%A8%8B%E9%85%8D%E7%BD%AE)的方式修改 workbox 插件配置

```js
module.exports = ({ context, onGetWebpackConfig }) => {
  onGetWebpackConfig((config) => {
   config
      .plugin('workbox-webpack-plugin')
      .tap(([args]) => {
        return [{...args, disableDevLogs: true}];
      });
  });
};

```
