### ISSUE TITLE
table 锁列和额外渲染行一起使用会出现的样式问题

### ISSUE THREAD

**Issue by JiangJun1994** [alibaba/ice#612]
![image](https://user-images.githubusercontent.com/25809468/41029481-5254b0e2-69ae-11e8-9eff-51b7d7bb8634.png)
![image](https://user-images.githubusercontent.com/25809468/41029482-52a40a70-69ae-11e8-908e-e3547c269285.png)
展开某一行的额外渲染行之后，设置锁列的地方会错位。

**Comment by wssgcg1213** [comment]
cc @frankqian

**Comment by chenbin92** [comment]
@JiangJun1994 请提供可复现的 demo 可以重新打开该 issue
