### ISSUE TITLE
app.ts中defineAuthConfig函数中使用history.push('/login')跳转路由报错

### ISSUE THREAD

**Issue by minesjm** [alibaba/ice#6129]
### Describe the bug

Route "login/index" has no component! Please go add a `default` export in the route module file.

### Expected behavior

跳到登陆页面正常显示登录页面

### Actual behavior

1. 启动项目, 访问首页
2. app.ts中dataLoader获取用户数据, 没权限获取失败401
3. 期望跳到登陆页面，history跳转了，但是报错，页面无法显示

### Version of ice.js

v3

### Content of build.json or ice.config.mts

```TypeScript
import { defineConfig } from '@ice/app';
import request from '@ice/plugin-request';
import store from '@ice/plugin-store';
import auth from '@ice/plugin-auth';

// The project config, see https://v3.ice.work/docs/guide/basic/config
const minify = process.env.NODE_ENV === 'production' ? 'swc' : false;
export default defineConfig(() => ({
  ssg: false,
  minify,
  plugins: [request(), store(), auth()],
  routes: {
    ignoreFiles: ['**/components/**'],
  },
  compileDependencies: false,
}));
```

### Additional context

// app.ts
export const authConfig = defineAuthConfig(async (appData) => {
  history?.push(`/login?redirect=${window.location.pathname}`);
  const { userInfo = {} } = appData;
  if (userInfo.error) {
    history?.push(`/login?redirect=${window.location.pathname}`);
  }
  return {
    initialAuth: {
      admin: userInfo.userType === 'admin',
      user: userInfo.userType === 'user',
    },
  };
});

export const dataLoader = defineDataLoader(async () => {
  const userInfo = await getUserInfo();
  return {
    userInfo,
  };
});

async function getUserInfo() {
  try {
    const userInfo = await fetchUserInfo();
    return userInfo;
  } catch (error) {
    return {
      error,
    };
  }
}

// services/user.ts
export async function fetchUserInfo() {
  return await request.post('/user/userinfo');
}

**Comment by ClarkXia** [comment]
app.ts 入口代码补充完整

**Comment by minesjm** [comment]
// app.ts 基本上没什么变化， 刚用脚手架创建的项目，只是改了获取userinfo信息的接口改成了调用后端的
import { defineAppConfig, history, defineDataLoader, useNavigate } from 'ice';
import { fetchUserInfo } from './services/user';
import { defineAuthConfig } from '@ice/plugin-auth/types';
import { defineStoreConfig } from '@ice/plugin-store/types';
import { defineRequestConfig } from '@ice/plugin-request/types';
import { routerHistory } from '@ice/runtime/esm/history';

// App config, see https://v3.ice.work/docs/guide/basic/app
export default defineAppConfig(() => ({}));

export const authConfig = defineAuthConfig(async (appData) => {
  history?.push(`/login?redirect=${window.location.pathname}`);
  const { userInfo = {} } = appData;
  if (userInfo.error) {
    history?.push(`/login?redirect=${window.location.pathname}`);
  }
  return {
    initialAuth: {
      admin: userInfo.userType === 'admin',
      user: userInfo.userType === 'user',
    },
  };
});

export const storeConfig = defineStoreConfig(async (appData) => {
  const { userInfo = {} } = appData;
  return {
    initialStates: {
      user: {
        currentUser: userInfo,
      },
    },
  };
});

export const requestConfig = defineRequestConfig(() => ({
  baseURL: 'http://localhost:19001/api',
}));

export const dataLoader = defineDataLoader(async () => {
  const userInfo = await getUserInfo();
  return {
    userInfo,
  };
});

async function getUserInfo() {
  try {
    const userInfo = await fetchUserInfo();
    return userInfo;
  } catch (error) {
    return {
      error,
    };
  }
}

**Comment by llz383455526** [comment]
<img width="1335" alt="image" src="https://user-images.githubusercontent.com/788738/229147534-34a526c9-f13b-4e0d-9552-b57c75b704ff.png">
我这边情况类似，在authConfig里执行了history.push跳转，报图中的错误

**Comment by minesjm** [comment]
在app.ts文件中, defineAuthConfig函数中使用history.push('/login'), 就会报错, 期待尽快恢复, 或者有其他方式可以跳转到/login路由吗？我试了几种办法都不行

**Comment by minesjm** [comment]
在app.ts文件中, defineAuthConfig函数中使用history.push('/login'), 就会报错, 期待尽快回复, 或者有其他方式可以跳转到/login路由吗？我试了几种办法都不行

**Comment by ClarkXia** [comment]
对于 defineAuthConfig 是用于权限信息的配置，不建议有一些路由操作，但是这个问题下个版本会修复。
跳转到其他页面可以在[布局组件](https://v3.ice.work/docs/guide/basic/router#%E5%B8%83%E5%B1%80%E7%BB%84%E4%BB%B6)中通过 useAppData 获取数据后再进行跳转

**Comment by minesjm** [comment]
好的, 谢谢
