### ISSUE TITLE
webpackrc 配置devServer没有效果

### ISSUE THREAD

**Issue by zhengki** [alibaba/ice#613]
## 环境信息

- 操作系统：win10
- Iceworks 版本： 2.1.1

## 问题描述

启动项目不自动打开页面，路由换成browerrouter页面刷新报can't get/xx     .webpackrc 配置devServer没有效果

**Comment by noyobo** [comment]
文件名是 `.webpackrc.js` 

飞冰的末班启动项目没有自动打开页面的功能。
