### ISSUE TITLE
3.x版本start访问正常，build后使用nginx部署访问pages路径报404错误

### ISSUE THREAD

**Issue by lyf-coder** [alibaba/ice#6130]
### Describe the bug

使用 `start` 启动可以正常访问页面，但是 `build` 以后使用 `nginx` 部署，访问`/` 路径没问题，访问其他页面路径直接报 `404`

### Expected behavior

可正常访问页面路径

### Version of ice.js

3.1.6

### Content of build.json or ice.config.mts

```TypeScript
import {defineConfig} from '@ice/app';
import request from '@ice/plugin-request';
// The project config, see https://v3.ice.work/docs/guide/basic/config
const minify = process.env.NODE_ENV === 'production' ? 'swc' : false;
export default defineConfig(() => ({
    // Set your configs here.
    minify,
    server: {
        onDemand: true,
        format: 'esm',
    },
    ssr:false,
    ssg:false,
    publicPath: '/',
    plugins: [
    //     store(),
        request(),
    ],
    // externals:{
    //     react: 'React',
    // }
}));
```

**Comment by lyf-coder** [comment]
nginx 配置
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/58352715/229299225-9c14220f-748b-42e6-a4e3-1c96620beca8.png">

build文件
<img width="469" alt="image" src="https://user-images.githubusercontent.com/58352715/229299304-c8e6d673-f017-4357-9555-97bce18fec2d.png">

**Comment by lyf-coder** [comment]
`start` 访问 `/` 路径是报错的，所以 `build` 后的访问空白，解决了 `start` 访问报的错误后，重新 `build`可以访问 `/`路径了，但是我访问 `/xx` 路径还是 `404`

**Comment by lyf-coder** [comment]
切换其他框架有类似刷新 404的问题，应该是nginx配置的问题。

**Comment by sima675** [comment]
nginx的配置问题 跟ice没有关系 history都有404的问题
