### ISSUE TITLE
怎么指定sourcemap生成的.map文件的文件夹呢？

### ISSUE THREAD

**Issue by wxadrtyu** [alibaba/ice#6131]
### Summary | 概述

怎么指定sourcemap生成的.map文件的文件夹呢？

### Motivation | 背景

要做前端监控，需要将map文件放到某个文件夹

### Detailed design | 方案设计

无

**Comment by ClarkXia** [comment]
https://v3.ice.work/docs/guide/basic/config#sourcemap 配置 sourceMap 字段
