### ISSUE TITLE
如何将构建结果本地化，可离线预览

### ISSUE THREAD

**Issue by willcong** [alibaba/ice#614]
## 环境信息

- 操作系统：
- Iceworks 版本： 

## 错误信息

构建 js css 等里有相关的网络请求，例如图片，字体文件等

**Comment by noyobo** [comment]
什么需求？

**Comment by willcong** [comment]
需要在离线下通过electron打开app

**Comment by noyobo** [comment]
没理解，electron 打开什么 App ？

**Comment by chenhongen** [comment]
本地化参考[link](https://gist.github.com/wssgcg1213/813083b31806ad75c6bd88fc715d6f36#file-webpackrc-js-L29)

**Comment by noyobo** [comment]
生成的模板都是基于 react-router 的单页应用 @willcong

**Comment by willcong** [comment]
离线状态下就无法请求网络图片了，想知道怎么配置项目，让这些资源读本地的

**Comment by noyobo** [comment]
网路图片需要编写的时候就使用本地图片例如 `<img src={require('../../a.jpg')} />`

**Comment by willcong** [comment]
嗯嗯，图片这个懂了。还有两个问题请教的。
1、发布后html内的script、css路径要改为相对的，应该怎么配置呢？
例：<script type="text/javascript" src="/js/index.js"></script> 要改为 <script type="text/javascript" src="./js/index.js"></script>
2、关于动态图标使用本地资源问题。
const CustomIcon = DynamicIcon.create({
  fontFamily: 'iceicon2',
  prefix: 'ice-icon-stable',
  css: 'https://at.alicdn.com/t/font_107674_7dns782b1jsb57b9.css'
});
这个css路径也是网络的， 我试过用require，不成功。要改成本地的话应该怎么处理呢？

**Comment by noyobo** [comment]
构建本地化的支持预计在月底完成。现在暂不支持配置。
