### ISSUE TITLE
ice3.0怎么添加 Provider

### ISSUE THREAD

**Issue by fastLazy** [alibaba/ice#6141]
### Motivation | 背景

集成第三方client，需要在Provider上添加，但是不知道添加

### Detailed design | 方案设计

暂无

**Comment by ClarkXia** [comment]
https://v3.ice.work/docs/guide/basic/router#%E5%B8%83%E5%B1%80%E7%BB%84%E4%BB%B6 添加布局组件，用于 Provider 的包裹
