### ISSUE TITLE
plugin中的runtime配置报错问题

### ISSUE THREAD

**Issue by wangmengdie-1** [alibaba/ice#6162]
### Describe the bug

如图所示，runtime配置【绝对路径】后，运行项目报错
![image](https://user-images.githubusercontent.com/124342041/232367067-46094702-cd5f-4ae3-beba-cb0f4d4a4a77.png)

### Expected behavior

希望工程正常运行

### Version of ice.js

3.0

### Content of build.json or ice.config.mts

```TypeScript
import { defineConfig } from '@ice/app';
import store from '@ice/plugin-store';
import request from '@ice/plugin-request';
import cssAssetsLocal from '@ice/plugin-css-assets-local';
import auth from '@ice/plugin-auth';
import devPlugin from './src/plugins/dev';
import runtimePlugin from './src/plugins/runtime';
import { transformSync } from '@babel/core';
// 定制化路由
// import routeConfig from './src/routes';
console.log('process.env.inspection', process.env.inspection);

// The project config, see https://v3.ice.work/docs/guide/basic/config
const minify = process.env.NODE_ENV === 'production' ? 'swc' : false;
export default defineConfig(() => ({
  // Set your configs here.
  ssr: false,
  ssg: false,
  minify,
  publicPath: './',
  hash: true,
  polyfill: 'usage',
  // ssr ssg配置项
  // server: {
  //   onDemand: false,
  //   format: 'cjs',
  //   bundle: true,
  //   ignores: [{
  //     resourceRegExp: /jlf-universal-toolkit/,
  //     // contextRegExp: /moment$/,
  //   }],
  // },
  // routes: {
  //   ignoreFiles: ['**'],
  //   config: routeConfig,
  // },
  plugins: [
    store(),
    request(),
    cssAssetsLocal(),
    auth(),
    devPlugin(),
    runtimePlugin(),
  ],
  // transform: async (source, id) => {
  //   // 过滤条件
  //   if (id.match(/\.(j|t)s(x)?$/)) {
  //     // if (id.match(/\.(j|t)s(x)?$/) && !id.includes("node_modules")) {
  //     // 借助 babel 编译
  //     const { code, map } = transformSync(source, {
  //       plugins: [
  //         "@babel/preset-env",
  //         {
  //           targets: {
  //             chrome: "49",
  //             ios: "10",
  //           },
  //         },
  //       ],
  //     });
  //     return { code, map };
  //   }
  // },
  // webpack: (webpackConfig) => {
  //   // if (process.env.NODE_ENV !== "test") {
  //   //   // 添加 webpack 插件
  //   //   webpackConfig.plugins?.push(new SpeedMeasurePlugin());
  //   // }
  //   webpackConfig.devServer = {
  //     headers: {
  //       'Access-Control-Allow-Origin': '*',
  //     },
  //     host: 'test.c3data.com.cn',
  //     // historyApiFallback: true,
  //     // allowedHosts: 'all',
  //     allowedHosts: ['.c3data.com.cn'],
  //     // https: false,
  //     server: {
  //       type: 'https',
  //       options: {
  //         key: './ca/test.c3data.com.cn-key.pem',
  //         cert: './ca/test.c3data.com.cn.pem',
  //         requestCert: true,
  //       },
  //     },
  //   };
  //   return webpackConfig;
  // },
}));
```

**Comment by luhc228** [comment]
打印一下 `path.resolve(__dirname, './runtimeConfig.tsx')` 看看

**Comment by wangmengdie-1** [comment]
> 打印一下 `path.resolve(__dirname, './runtimeConfig.tsx')` 看看
这个路径是对的
![image](https://user-images.githubusercontent.com/124342041/232372640-2f8909d2-2938-469a-8cc8-87eb8f12e748.png)

**Comment by ClarkXia** [comment]
提供包含 runtime 路径的 `ice.config.mts` 配置

**Comment by wangmengdie-1** [comment]
> 提供包含 runtime 路径的 `ice.config.mts` 配置，特别是 ./src/plugins/runtime 中的内容

import type { Plugin } from '@ice/app/types';
import path from 'path';
import fs from 'fs';

console.log(path.resolve(__dirname, './runtimeConfig.tsx'), 9090);
const plugin: Plugin = () => ({
  name: 'runtime-config-plugin',
  setup: ({
    context,
    onGetConfig,
    onHook,
    registerUserConfig,
    registerCliOption,
    modifyUserConfig,
    registerTask,
    getAllTask,
    generator,
    watch,
  }) => {
    // console.log('context', context);
  },
  runtime: path.resolve(__dirname, './runtimeConfig.tsx'),
});

export default plugin;

**Comment by wangmengdie-1** [comment]
> 提供包含 runtime 路径的 `ice.config.mts` 配置，特别是 ./src/plugins/runtime 中的内容

import { defineConfig } from '@ice/app';
import store from '@ice/plugin-store';
import request from '@ice/plugin-request';
import cssAssetsLocal from '@ice/plugin-css-assets-local';
import auth from '@ice/plugin-auth';
import devPlugin from './src/plugins/dev';
import runtimePlugin from './src/plugins/runtime';
import { transformSync } from '@babel/core';
// 定制化路由
// import routeConfig from './src/routes';
console.log('process.env.inspection', process.env.inspection);

// The project config, see https://v3.ice.work/docs/guide/basic/config
const minify = process.env.NODE_ENV === 'production' ? 'swc' : false;
export default defineConfig(() => ({
  // Set your configs here.
  ssr: false,
  ssg: false,
  minify,
  publicPath: './',
  hash: true,
  polyfill: 'usage',
  // ssr ssg配置项
  // server: {
  //   onDemand: false,
  //   format: 'cjs',
  //   bundle: true,
  //   ignores: [{
  //     resourceRegExp: /jlf-universal-toolkit/,
  //     // contextRegExp: /moment$/,
  //   }],
  // },
  // routes: {
  //   ignoreFiles: ['**'],
  //   config: routeConfig,
  // },
  plugins: [
    store(),
    request(),
    cssAssetsLocal(),
    auth(),
    devPlugin(),
    runtimePlugin(),
  ],
  // transform: async (source, id) => {
  //   // 过滤条件
  //   if (id.match(/\.(j|t)s(x)?$/)) {
  //     // if (id.match(/\.(j|t)s(x)?$/) && !id.includes("node_modules")) {
  //     // 借助 babel 编译
  //     const { code, map } = transformSync(source, {
  //       plugins: [
  //         "@babel/preset-env",
  //         {
  //           targets: {
  //             chrome: "49",
  //             ios: "10",
  //           },
  //         },
  //       ],
  //     });
  //     return { code, map };
  //   }
  // },
  // webpack: (webpackConfig) => {
  //   // if (process.env.NODE_ENV !== "test") {
  //   //   // 添加 webpack 插件
  //   //   webpackConfig.plugins?.push(new SpeedMeasurePlugin());
  //   // }
  //   webpackConfig.devServer = {
  //     headers: {
  //       'Access-Control-Allow-Origin': '*',
  //     },
  //     host: 'test.c3data.com.cn',
  //     // historyApiFallback: true,
  //     // allowedHosts: 'all',
  //     allowedHosts: ['.c3data.com.cn'],
  //     // https: false,
  //     server: {
  //       type: 'https',
  //       options: {
  //         key: './ca/test.c3data.com.cn-key.pem',
  //         cert: './ca/test.c3data.com.cn.pem',
  //         requestCert: true,
  //       },
  //     },
  //   };
  //   return webpackConfig;
  // },
}));
