### ISSUE TITLE
为什么官方文档提供的addWrapper 示例代码会报错？

### ISSUE THREAD

**Issue by CX330-jiuxi** [alibaba/ice#6169]
### Describe the bug

官网demo：
![image](https://user-images.githubusercontent.com/51979013/232711205-04675b8c-aed8-42e1-a926-34011440f847.png)

cv：
<img width="722" alt="image" src="https://user-images.githubusercontent.com/51979013/232711275-22178013-c3c2-472c-aa1b-9da813f27d0b.png">

报错：
![image](https://user-images.githubusercontent.com/51979013/232711514-4a0d13d3-2481-465c-a365-392cbd477db5.png)

### Expected behavior

至少官网demo能跑通

### Actual behavior

官网超过来的代码，也报错了

### Version of ice.js

3.0

### Content of build.json or ice.config.mts

```TypeScript
import { defineConfig } from '@ice/app';
import request from '@ice/plugin-request';
import store from '@ice/plugin-store';
import auth from '@ice/plugin-auth';
import i18n from '@ice/plugin-i18n';
import providerPlugin from "./plugins/provider-plugin";
import authPlugin from "./plugins/auth-plugin";

// The project config, see https://v3.ice.work/docs/guide/basic/config
const minify = process.env.NODE_ENV === 'production' ? 'swc' : false;

export default defineConfig(() => ({
  ssg: false,
  minify,
  plugins: [request(), store(), auth(), providerPlugin(), authPlugin() ],
  routes: {
    ignoreFiles: ['**/components/**'],
  },
  compileDependencies: false,
}));
```

**Comment by ClarkXia** [comment]
示例代码是 2.0 的代码，先参考 
https://github.com/alibaba/ice/blob/30e2cb182a0dab0a0450e2d867fc87ad78dd07b0/packages/plugin-auth/src/runtime/index.tsx#L11-L57

我们更新下文档

**Comment by CX330-jiuxi** [comment]
@ClarkXia  对了咨询下，Redirct是不是没了，重定向是不是只能push
