### ISSUE TITLE
提供 pr 级别的 alpha 版本发送脚本或能力

### ISSUE THREAD

**Issue by answershuto** [alibaba/ice#6174]
### Summary | 概述

现在某个 pr 单独发 alpha 版本在修改较多的情况下还是挺麻烦的，有时候会引起版本不兼容的问题，提供一个 pr 级别同时发布多个包的脚本或能力。

### Motivation | 背景

现在某个 pr 单独发 alpha 版本在修改较多的情况下还是挺麻烦的，有时候会引起版本不兼容的问题，提供一个 pr 级别同时发布多个包的脚本或能力。

### Detailed design | 方案设计

现在某个 pr 单独发 alpha 版本在修改较多的情况下还是挺麻烦的，有时候会引起版本不兼容的问题，提供一个 pr 级别同时发布多个包的脚本或能力。

**Comment by luhc228** [comment]
我先讲一下整个大的背景：

现在发布 Beta 版本时候，由于 changesets 工具的机制，需要把每个包的 beta 版本信息记录在 `pre.json` 中，以便于在发布下一个 beta 版本，基于上一个版本 +1（比如 `1.0.1-beta.0` -> `1.0.1-beta.1`）。比如：
```json
{
  "mode": "exit",
  "tag": "beta",
  "initialVersions": {
    "@ice/pkg-plugin-docusaurus": "1.4.7-beta.0",
  },
  "changesets": [
    "fast-seahorses-lick"
  ]
}
```

这个时候需要把这个文件和当前即将发布的 npm 包的 package.json 的变更合并到主分支上，保证其他人能发布下一个beta版本。整个流程还是比较麻烦，可能还会带来代码冲突等问题。

我们基于当前分支/ PR 发测试的版本，并不希望/不需要合并到主分支上，这里提供两个方案：

这里提供两个方案：
1. 使用 changeset 提供的 [snapshot-release]，(https://github.com/changesets/changesets/blob/main/docs/snapshot-releases.md) ：这种是发布 snapshot 版本（比如 0.0.0-bulbasaur-20230421022305），发布完不需要把代码变更提交到远程仓库
2. 在当前该分支上发布 alpha 版本：这种就是先调用 changeset，得到本次需要发布的 npm 包，写一个脚本读取每个 npm 包最新的 alpha 版本，并进行 +1，然后发布

可以讨论一下使用哪个方案更好。

**Comment by luhc228** [comment]
方案1：
```bash
$ pnpm changeset version --snapshot canary && pnpm install --frozen-lockfile false
$ pnpm build 
$ pnpm changeset publish  --tag canary --no-git-tag --snapshot
```
