### ISSUE TITLE
yarn start运行起来，在页面使用了window.navigator ,控制台报错

### ISSUE THREAD

**Issue by imyann** [alibaba/ice#6177]
### Describe the bug

<img width="543" alt="image" src="https://user-images.githubusercontent.com/18695873/233589805-c38c2a35-0962-43fd-a618-8f85a273da41.png">
<img width="794" alt="image" src="https://user-images.githubusercontent.com/18695873/233589861-e97a1e87-25f4-418b-baf1-5f262f94c99c.png">

### Expected behavior

yarn start 不报错

### Version of ice.js

 "@ice/app": "^3.0.0",

**Comment by ClarkXia** [comment]
框架默认以同构方式执行，如果涉及 window 变量，可以考虑关闭 ssg https://v3.ice.work/docs/guide/basic/config#ssg
