### ISSUE TITLE
创建ICE Design Pro新项目后根据提示点了安装依赖，出现[object Object]错误

### ISSUE THREAD

**Issue by chenhongen** [alibaba/ice#618]
## 环境信息

- 操作系统：WIN7
- Iceworks 版本： 2.2.0

## 问题描述

创建ICE Design Pro新项目后根据提示点了安装依赖，出现[object Object]错误

## 错误信息

![2018-06-08_231840](https://user-images.githubusercontent.com/16499303/41166373-ae31bed0-6b72-11e8-8eb1-f583f5df6890.png)

**Comment by noyobo** [comment]
看错误日志是在安装的过程中丢包了。设置面板切换下 npm 源试下。 

弹窗的问题，我看下

**Comment by gailufeng** [comment]
MAC下也出现了，更换npm源后正常
