### ISSUE TITLE
ssr 部署是 把项目部署到服务器，然后npm start吗？

### ISSUE THREAD

**Issue by HowCanLove** [alibaba/ice#6180]
### Summary | 概述

ssr后detail/$.tsx
匹配/detail/:id的这种方式，打包出来的server内容如何部署。
官网没有对应的demo。看的有点懵逼，不知道ssr后如何处理。

### Motivation | 背景

开启ssr后的部署问题

### Detailed design | 方案设计

我也不知道

**Comment by ClarkXia** [comment]
https://github.com/alibaba/ice/issues/6092 后面官方会提供相关文档指引
