### ISSUE TITLE
rax-compat 兼容 rax portal 的场景

### ISSUE THREAD

**Issue by chenjun1011** [alibaba/ice#6209]
### Describe the bug

目前，在 rax 迁移的项目中，如果有依赖  [rax-portal](https://github.com/raxjs/rax-components/blob/master/packages/rax-portal/src/index.tsx) 或 [rax-create-portal](https://github.com/alibaba/rax/blob/master/packages/rax-create-portal/src/index.js) 组件，会导致如下报错

![image](https://user-images.githubusercontent.com/1303018/236363874-76d2c605-1bb2-4683-8d30-c2ea1a54e284.png)

这是因为 [rax-unmount-component-at-node](https://github.com/alibaba/rax/tree/master/packages/rax-unmount-component-at-node) 组件依赖了 rax shared. Instance, 而在兼容模式下无法对齐。

### Expected behavior

不报错，直接使用 react 的 portal 能力

### Version of ice.js

3

**Comment by chenjun1011** [comment]
一种解决思路是把 react protal 发个单独的包，然后 alias 过去

**Comment by echosoar** [comment]
确实没有兼容，我看看如何兼容下 https://github.com/alibaba/ice/blob/master/packages/rax-compat/src/unmount-component-at-node.ts#L4

**Comment by wssgcg1213** [comment]
ref https://github.com/alibaba/ice/pull/6232
