### ISSUE TITLE
网络切换导致IDE崩溃

### ISSUE THREAD

**Issue by IceSeaOnly** [alibaba/ice#621]
## 环境信息

- 操作系统：
- Iceworks 版本： 所有版本

## 问题描述

本机网络一单切换，会导致ICE环境立即崩溃

**Comment by noyobo** [comment]
什么操作系统？ 操作步骤是怎样的？ 可以提供下吗

**Comment by IceSeaOnly** [comment]
Win10 专业版，笔记本，启动IceWorks之后，启动调试服务，此时断开WIFI或切换WIFI均会导致IceWroks和Node进程直接崩溃退出。

**Comment by imsobear** [comment]
问题过于久远，还存在的话麻烦再 reopen 下。
