### ISSUE TITLE
unknown option '--no-proxy'

### ISSUE THREAD

**Issue by linzhixin** [alibaba/ice#6210]
![image](https://user-images.githubusercontent.com/24630964/236398819-bc9637df-3d98-4dbd-9a1a-eed1090c73ff.png)
今天根据ice文档初始化项目的时候不成功，遇到了这个问题

**Comment by ClarkXia** [comment]
https://github.com/alibaba/ice/blob/master/packages/ice/bin/ice-cli.mjs#L49C1-L59
不支持 no-proxy 的，你这个是哪里看到的
