### ISSUE TITLE
有考虑使用Alova替代axios及部分重复能力

### ISSUE THREAD

**Issue by inier** [alibaba/ice#6211]
### Summary | 概述

有考虑使用Alova替代axios及部分重复能力，框架部分仅提供前后置拦截器。

### Motivation | 背景

有考虑使用Alova替代axios及部分重复能力，框架部分仅提供前后置拦截器。

### Detailed design | 方案设计

有考虑使用Alova替代axios及部分重复能力，框架部分仅提供前后置拦截器。

**Comment by ClarkXia** [comment]
Alova 相比于 axios 会有什么优势？

**Comment by ClarkXia** [comment]
如果有兴趣可以按 @ice/plugin-request 方式实现一个 Alova 版本

**Comment by inier** [comment]
体积小，不用单独封装 缓存、重复请求等能力
________________________________
发件人: ClarkXia ***@***.***>
发送时间: 2023年5月6日 14:29
收件人: alibaba/ice ***@***.***>
抄送: inier ***@***.***>; Author ***@***.***>
主题: Re: [alibaba/ice] 有考虑使用Alova替代axios及部分重复能力 (Issue #6211)


Alova 相比于 axios 会有什么优势？

―

**Comment by xmsz-stu** [comment]
好像没啥特别优势
