### ISSUE TITLE
ice 配置proxy不生效

### ISSUE THREAD

**Issue by well410** [alibaba/ice#6216]
ice 配置proxy不生效
build.json中配置  "proxy": {
    "/userDimension": {
      "enable": true,
      "changeOrigin": true,
      "target": "https://local.alibaba-inc.com/userDimension"
    },
    "/category": {
      "changeOrigin": true,
      "target": "https://pre-stargraphs.alibaba-inc.com/category"
    }
  }
不生效，怎么解决啊

**Comment by ClarkXia** [comment]
提供下完整的 build.json 配置

**Comment by ClarkXia** [comment]
目前无法复现，可以提供 demo 后重开 issue

**Comment by Bingjiajia** [comment]
你这问题解决了吗
