### ISSUE TITLE
ice3.x发布后如何创建基于ice2.x的项目

### ISSUE THREAD

**Issue by awen1988** [alibaba/ice#6218]
如题，无论使用v3文档中介绍的npm create ice app还是v2文档中介绍的npm init ice创建出来的项目都是基于v3版本的项目，如何创建ice2.x的项目

**Comment by ClarkXia** [comment]
https://v2.ice.work/docs/guide/start/ 通过 cli 指定具体的模版

**Comment by awen1988** [comment]
并不行，好像官方把模板都删掉了，就算指定模板依然会弹出模板选择，只有v3版本的模板可供选择

**Comment by luhc228** [comment]
> 并不行，好像官方把模板都删掉了，就算指定模板依然会弹出模板选择，只有v3版本的模板可供选择

npm init ice@1.7.5 your-project-name
