### ISSUE TITLE
麻烦请教一下 icework制作好的spa应用 该怎么结合electron 开发成桌面应用程序

### ISSUE THREAD

**Issue by lhz1208** [alibaba/ice#623]
## 环境信息

- 操作系统：win10
- Iceworks 版本： iceworks 2.1.1

## 问题描述
麻烦请教一下 icework制作好的spa应用 该怎么结合electron 开发成桌面应用程序

**Comment by noyobo** [comment]
electron 应用和 web 应用是有所不同的。

目前 iceworks 创建的项目不适配 electron。

如果要开发 electron 应用可以看下 https://electronjs.org/community  里推荐的 Boilerplates。
