### ISSUE TITLE
新开的项目,无法生产环境编译

### ISSUE THREAD

**Issue by pangxianfei** [alibaba/ice#6231]
### Describe the bug

![图片](https://github.com/alibaba/ice/assets/9346931/f8aeeabc-cac8-466c-99dd-d9cd2dfa224b)
![图片](https://github.com/alibaba/ice/assets/9346931/c2056993-308d-4308-8971-839105cfdc37)
安装
![图片](https://github.com/alibaba/ice/assets/9346931/7432a163-90fc-4ade-824a-b9d043c1de67)
安装完成
![图片](https://github.com/alibaba/ice/assets/9346931/358be0ec-ce64-42df-9386-a84deb7c21b5)
执行yarn build
![图片](https://github.com/alibaba/ice/assets/9346931/c5a70225-20a4-4485-9234-7b2ba632a5c2)
编译结果
![图片](https://github.com/alibaba/ice/assets/9346931/e227b539-7409-4350-9ca3-e83a94b142eb)

### Expected behavior

新的全新项目，使用npm create ice ice-app创建；
![图片](https://github.com/alibaba/ice/assets/9346931/5e83aeed-4b3d-46ce-823d-0ff91ab8d828)

### Version of ice.js

3.0

### Content of build.json or ice.config.mts

```TypeScript
import { defineConfig } from '@ice/app';
import request from '@ice/plugin-request';
import store from '@ice/plugin-store';
import auth from '@ice/plugin-auth';

// The project config, see https://v3.ice.work/docs/guide/basic/config
const minify = process.env.NODE_ENV === 'production' ? 'swc' : false;
export default defineConfig(() => ({
  ssg: false,
  minify,
  plugins: [request(), store(), auth()],
  routes: {
    ignoreFiles: ['**/components/**'],
  },
  compileDependencies: false,
}));
```

### Additional context

飞冰及微前端都是一样的bug.

**Comment by ClarkXia** [comment]
确认下是否因为中文目录的影响

**Comment by pangxianfei** [comment]
确实是中文目录的原因。

**Comment by pangxianfei** [comment]
操作系统给我的桌面(目录名称变成中文造成的)
