### ISSUE TITLE
how to use addProvider to add HelmetProvider

### ISSUE THREAD

**Issue by Douganer** [alibaba/ice#6234]
### Describe the bug

export default ({ addProvider }) => {
  function Provider({ children }) {
    return (
      <div>{children}</div>
    )
  }

  const StoreProvider = ({ children }) => {
    return <Provider>{children}</Provider>;
  };
  addProvider(StoreProvider);
};

### Expected behavior

// src/app.js
import { addProvider } from 'ice';
import { HelmetProvider } from 'react-helmet-async';

import App from './app';

addProvider(() => {
  return <HelmetProvider>{App()}</HelmetProvider>;
});

### Version of ice.js

3.1.7

### Content of build.json or ice.config.mts

```TypeScript
import {defineConfig} from '@ice/app';

export default defineConfig(() => ({
    outputDir: 'dist',

    ssr: true,
    ssg: false,

    splitChunks: false,

    hash: false,

    syntaxFeatures: {
        exportDefaultFrom: true
    },

    dropLogLevel: 'warn'
}));
```

**Comment by luhc228** [comment]
you can add `<HelmetProvider>` in `pages/layout.tsx`
