### ISSUE TITLE
如何在飞冰框架中引入jquery写的插件

### ISSUE THREAD

**Issue by caizhen229** [alibaba/ice#6237]
### Describe the bug

用jquery写好了一个电话条插件（包括已经写好的js，css等），想在飞冰框架中直接使用，请问要如何引入？

### Expected behavior

写好的插件可以正常使用

### Version of ice.js

1.18.3

**Comment by ClarkXia** [comment]
引入 jquery 的 cdn 地址，在 react 节点mount 阶段用 jquery 操作具体节点就行
