### ISSUE TITLE
windows 启动提示发生未知的错误，Could not call remote function 'spawn'

### ISSUE THREAD

**Issue by lanxuan4444** [alibaba/ice#624]
## 环境信息

- 操作系统：
- Iceworks 版本： 

## 问题描述

![image](https://user-images.githubusercontent.com/17310230/41215728-5012103e-6d84-11e8-9bee-007472ceaefe.png)

**Comment by noyobo** [comment]
可能有杀毒软件误删了 iceworks 内容，可以信任后重试下。
