### ISSUE TITLE
[vuex] vuex requires a Promise polyfill in this browser. 

### ISSUE THREAD

**Issue by xcsweb** [alibaba/ice#626]
## 环境信息

- 操作系统：
- Iceworks 版本：最新版本 

## 问题描述
![image](https://user-images.githubusercontent.com/20693737/41274127-e43bf2c8-6e4e-11e8-92dd-26ee82129675.png)

![image](https://user-images.githubusercontent.com/20693737/41274112-d13c2d46-6e4e-11e8-8ff1-5aed29a51b5a.png)

![image](https://user-images.githubusercontent.com/20693737/41274134-eeefd112-6e4e-11e8-8c7d-8480de545579.png)
![image](https://user-images.githubusercontent.com/20693737/41274167-0d58368a-6e4f-11e8-8196-75d07acdbf6b.png)
how can slove this problem

**Comment by chenbin92** [comment]
参考这个 issue ：https://github.com/vuejs-templates/webpack/issues/474
