### ISSUE TITLE
小程序兼容 withSuspense 和 useSuspenseData 两个API

### ISSUE THREAD

**Issue by hzyhbk** [alibaba/ice#6260]
### Describe the bug

业务上接了流式 SSR 之后，项目中想要实现一套代码编译成钉钉小程序，ice 这边编译正常，但是到小程序开发者工具中就报错 TypeError: (0 , c.withSuspense) is not a function ，看起来是小程序 runtime 需要实现 withSuspense 和 useSuspenseData 这两个API

### Expected behavior

打包成小程序可以正常编译

### Version of ice.js

3.2.0

**Comment by ClarkXia** [comment]
release/next 分支合并掉了，需要重新提交下
