### ISSUE TITLE
多个 jsx-runtime 混用，引发 esbuild 构建错误

### ISSUE THREAD

**Issue by chenjun1011** [alibaba/ice#6269]
### Describe the bug

现象

TypeError: Cannot read properties of undefined (reading 'jsx')

![image](https://github.com/alibaba/ice/assets/1303018/6b5b409e-56e2-4b61-a407-c00e90a79eac)

复现方式：
* rax-compat 项目，同时引入 pkg 组件

原因：
* 普通 ICE 组件，例如 document.tsx 依赖的 jsx 从 @ice/runtime/jsx-runtime 导出（同步 import）
* PKG 组件，依赖的 jsx 从 @ice/jsx-runtime/jsx-runtime 导出（页面入口是异步import的）
* Rax Compat 的组件，依赖的 jsx 从 rax-compat/runtime/jsx-runtime 导出（页面入口异步import的）

当以上三种方式，同时在一个项目出现时，esbuild 构建的产物就会存在问题

以下面的产物为例，在消费 jsx 变量时，jsx 尚未被初始化

![image](https://github.com/alibaba/ice/assets/1303018/410a368a-0dc3-408f-9070-f106eb2c3017)

可复现的示例代码：

index.js
```js
import { jsx as _jsx } from "@ice/runtime/jsx-runtime";

var makeReactElement = function() {
  var element = /*#__PURE__*/ _jsx("div", {
      children: 'index'
  });

  return element;
};

import('./home');
makeReactElement();

```

home.js
```js
import { jsx as _jsx1 } from "@ice/jsx-runtime/jsx-runtime";
import { jsx as _jsx2 } from "rax-compat/runtime/jsx-runtime";

export var ComponentA = function() {
  var element = /*#__PURE__*/ _jsx1("div", {
      children: 'component a'
  });
  return element;
};

export var ComponentB = function() {
  var element = /*#__PURE__*/ _jsx2("div", {
      children: 'component b'
  });
  return element;
};
```

直接使用 esbuild 构建，就会出现上述问题

### Expected behavior

jsx 在调用时，已完成初始化

### Version of ice.js

3

**Comment by ClarkXia** [comment]
将多个 runtime 指向同一个依赖，比如：
```diff
// 在 ice.config.mts 中增加 alias
export default defineConfig({
  // Set your configs here.
+  alias: {
+    '@ice/runtime/react/jsx-runtime': '@ice/jsx-runtime/jsx-runtime',
+  },
}
```

默认需要在 rax-compat 插件中处理
