### ISSUE TITLE
ice 编译H5 报错

### ISSUE THREAD

**Issue by CayChance** [alibaba/ice#6271]
### Describe the bug

ice编译H5报错，提示信息：
Starting the development server at:

    - Local  : https://localhost/
    - Network: https://30.79.211.31/

 ERROR  Server compiled with errors.  
 
EntryPoints: {"index":"/Users/chance/Documents/chronic_disease_cycle/ice-app/.ice/entry.server.ts"} 
Build failed with 3 errors:

.ice/routes.tsx:2:9: ERROR: No matching export in "node_modules/_@ice_runtime@1.1.8@@ice/runtime/esm/index.js" for import "createRouteLoader"

.ice/routes.tsx:2:28: ERROR: No matching export in "node_modules/_@ice_runtime@1.1.8@@ice/runtime/esm/index.js" for import "WrapRouteComponent"

.ice/routes.tsx:2:48: ERROR: No matching export in "node_modules/_@ice_runtime@1.1.8@@ice/runtime/esm/index.js" for import "RouteErrorComponent"

### Expected behavior

正常启动

### Version of ice.js

"ice": "^3.7.72",

**Comment by ClarkXia** [comment]
"ice": "^3.7.72" 这个是什么奇怪的版本

**Comment by CayChance** [comment]
@ClarkXia   抱歉，目前本地是如下版本，这边依赖 @ice/app 3.2.0 版本中小程序的功能所以升级到了3.2.0。
"@ice/app": "^3.2.0",
"@ice/miniapp-html-styles": "^1.0.0",
"@ice/miniapp-runtime": "^1.0.1",
"@ice/plugin-miniapp": "^1.1.0",
"@ice/runtime": "^1.0.0",

 刚试了一下，降级到3.1.7就可以编译成功了，我理解这个是不是3.2.0 版本的问题？

**Comment by ClarkXia** [comment]
如果用 3.2.0 版本，@ice/runtime 同样需要配套升级 1.2.0，目前版本有兼容性问题，预计下周一发布

**Comment by CayChance** [comment]
@ClarkXia  请问 @ice/runtime 是否可以更新到 1.2.0 ？

**Comment by ClarkXia** [comment]
兼容性处理已发布，使用最新版本即可
