### ISSUE TITLE
ice.js 3 新版本中不再支持 vite 模式

### ISSUE THREAD

**Issue by lime2019** [alibaba/ice#6274]
可以问一下具体原因吗？

**Comment by ClarkXia** [comment]
2.x 支持了 vite 和 webpack，框架做了很多差异抹平，在 3.0 我们期望能基于 webpack 来作为底层构建的原因是我们期望能够在一条链路上持续发展，而 vite 作为 es module 标准，对于一些历史项目支持的不友好
