### ISSUE TITLE
工程启动卡死

### ISSUE THREAD

**Issue by linshaoye** [alibaba/ice#6283]
第一种是启动超级慢，卡的不动
![image](https://github.com/alibaba/ice/assets/41201374/2f17ec8a-d822-4379-8e80-61988cc0fc3e)

第二种 启动完毕后页面显示
![image](https://github.com/alibaba/ice/assets/41201374/23501231-1c90-4283-8c08-09fb7019afb2)

**Comment by linshaoye** [comment]
node 版本 14.17.6

**Comment by ClarkXia** [comment]
提供下复现的 demo

**Comment by ClarkXia** [comment]
第一种情况考虑 @alifd/next 和 ice.js 的版本是否最新，第二个问题，提供复现 demo 后重开 issue
