### ISSUE TITLE
请问开发自定义物料时，如何处理依赖的第三方ui库

### ISSUE THREAD

**Issue by PichurChill** [alibaba/ice#629]
## 环境信息

- 操作系统： win10
- Iceworks 版本： v2.2.0

## 问题描述

想基于 element-ui 自定义物料，已经按文档用 ice-devtools 新建并跑起来了，能够在本地实时预览，但是例如`<el-button>按钮</el-button>`这类自定义组件是如何渲染出来的，（在项目里我知道是要在 main.js 引入 element-ui），不知道在这里开发物料时该如何操作 ，也没看到入口文件，求指教

## 错误信息
无

**Comment by chenbin92** [comment]
@PichurChill  目前 ice-devtools 提供的 Vue 自定义物料默认是基于  element-ui 的，也就是开发区块时预览页面通过 CDN 的方式加载了 element-ui 的依赖资源。所有你在开发区块时可以直接使用组件

![image](https://user-images.githubusercontent.com/3995814/41330748-d75804de-6f07-11e8-81e8-0a2a225220b9.png)

**Comment by PichurChill** [comment]
谢谢！那请问，如果使用其他第三方组件库或者时自己的组件库，是不是只能也通过类似的方式？
