### ISSUE TITLE
新建页面退出提示app unhandled rejection at

### ISSUE THREAD

**Issue by eshun** [alibaba/ice#63]
![image](https://user-images.githubusercontent.com/11847678/35667421-8dc51250-0768-11e8-9208-de0dcacfbd56.png)
进入创建页面无返回按钮点击项目返回项目列表，提示是否离开ok之后出现上图提示

**Comment by eshun** [comment]
非ice创建的项目兼容性不是很好，项目一直显示调试服务启动中，但是已经可以访问了，新建页面基本不能用

**Comment by wssgcg1213** [comment]
感谢建议, 非ice创建的项目在下个版本会得到兼容

**Comment by noyobo** [comment]
暂先关闭，非 ice 的兼容项目暂未纳入开发日程。
