### ISSUE TITLE
Iceworks 构建提示问题

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#630]
## 环境信息

- 操作系统：
- Iceworks 版本： 2.2.0

## 问题描述

日志显示构建错误，对应的提示显示`构建完成，点击查看构建结构`，其实是没有生成任何文件的。建议提示改成 `构建失败`

## 错误信息

![image](https://user-images.githubusercontent.com/3995814/41334082-cbaee9ea-6f16-11e8-8f3f-af9aeab3fccf.png)

**Comment by noyobo** [comment]
构建完成 构建成功 是不同的概念，这里描述的是过程已经结束，但是并不知道构建后的结果。

 webpack 这里的错误我看看是否可以捕获到。
