### ISSUE TITLE
history.push有bug

### ISSUE THREAD

**Issue by Aokyz** [alibaba/ice#6309]
### Describe the bug

最新版本的ice，使用了history.push(/xxx)之后，新页面的window.history.length就比原页面的多了2，发现是重复pushstate了，导致使用新页面使用window.history.back需要执行两次才能退出页面，以前是没有问题的，不知道是从哪个版本出现这个问题的

### Expected behavior

希望调用history.push之后pushState就一次，然后使用window.hisory.back能正常返回

### Version of ice.js

3.2.3

**Comment by spicylemonhaha** [comment]
ice的history使用的是@remix-run/router导出的createBrowserHistory等函数生成的，似乎在这个库中的当前使用版本中如果要使得history.push触发路由重新渲染需要给history的生成函数加上v5Compat: true参数，但是这会导致pushState多次执行。具体原因通过stack看了一下可能是这里导致了再次触发：https://github.com/remix-run/react-router/blob/610ce6edf0993384300ff3172fc6db00ead50d33/packages/router/history.ts#L650   

暂时想得到的解决方案也许可能是换一个库例如history，或者对现在的histroy做一些加强or垫片。

另外，我感觉路由的话你可以用useNavigate会更好一些，毕竟history.push()的路由方式在react-router v6已经不再建议使用。

**Comment by Aokyz** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我已经收到你的来信！

**Comment by spicylemonhaha** [comment]
我来尝试解决一下，尽快给出结果
