### ISSUE TITLE
global.less里面写html标签的样式不生效

### ISSUE THREAD

**Issue by Aokyz** [alibaba/ice#6311]
### Describe the bug

global.less里面写html标签的样式不生效，比如在global.less里面写
`html: {height: 100%; overflow:hidden}` 页面上并不生效

### Expected behavior

正常应该生效

### Version of ice.js

3.2.3

**Comment by ClarkXia** [comment]
main.css 中有对应样式吗

**Comment by Aokyz** [comment]
没有，我的项目里面没有main.css文件

**Comment by ClarkXia** [comment]
main.css 是构建后的产物，验证了下暂时无法复现，如果有复现 demo 可以提供下重开 issue
