### ISSUE TITLE
build 与 start 阶段差异开关

### ISSUE THREAD

**Issue by answershuto** [alibaba/ice#6312]
### Summary | 概述

build 与 start 阶段存在差异会使用户产生误解导致一些 start 阶段正常，但是 build 以后异常的 case，比如 js 的严格模式的差异，考虑加一个开关来排除这些差异。

### Motivation | 背景

build 与 start 阶段存在差异会使用户产生误解导致一些 start 阶段正常，但是 build 以后异常的 case，比如 js 的严格模式的差异，考虑加一个开关来排除这些差异。

### Detailed design | 方案设计

build 与 start 阶段存在差异会使用户产生误解导致一些 start 阶段正常，但是 build 以后异常的 case，比如 js 的严格模式的差异，考虑加一个开关来排除这些差异。

**Comment by ClarkXia** [comment]
暂不考虑这种情况，目前比较多 build 与 start 阶段的差异在编译和压缩上，都已有对应强制开启的方式
