### ISSUE TITLE
创建应用之后，启动控制台打印Error，但是应用是可以正常访问的

### ISSUE THREAD

**Issue by edc-hui** [alibaba/ice#6327]
### Describe the bug

具体表现如下图：

![image](https://github.com/alibaba/ice/assets/33356467/c11e02b5-0472-4f00-b6f7-93145c8298e4)

![image](https://github.com/alibaba/ice/assets/33356467/c598dd00-cb65-4867-974b-d68ee8e1d24c)

### Expected behavior

控制台正常打印  不报error

### Actual behavior

ice.js版本信息如下图：
![image](https://github.com/alibaba/ice/assets/33356467/136eff45-dda0-4e1d-8f78-07a1580d368f)

### Version of ice.js

3.2.5

### Additional context

node 版本是18.16.0
npm版本是9.5.1
操作系统是win 10

**Comment by edc-hui** [comment]
补充ice.config.mts配置图:
![image](https://github.com/alibaba/ice/assets/33356467/42a2fb9e-1fa5-481b-b41b-dcd380d74485)

**Comment by ClarkXia** [comment]
有点类似 https://github.com/alibaba/ice/issues/6323
但目前在 win10 上复现（基于官方的初始化命令启动 npm create ice ice-app --template @ice/lite-scaffold）
