### ISSUE TITLE
无法引入@alifd/layout/lib/index.js，报错  Failed to load module @alifd/layout/lib/index.js, Esbuild name esbuild-transform-pipe      

### ISSUE THREAD

**Issue by frogo** [alibaba/ice#6328]
### Describe the bug

![image](https://github.com/alibaba/ice/assets/3413313/0ef05049-2eb2-4978-b868-af8c760ff5a6)
![image](https://github.com/alibaba/ice/assets/3413313/5afbef43-460a-417a-a2a1-98d6fed10434)

我使用低代码生成的index.jsx，放在ice3脚手架中，但是报以上错误，不知道怎么引用才对，请大佬帮忙

### Expected behavior

希望能正常引入

### Version of ice.js

3.0.0

**Comment by luhc228** [comment]
提供可复现 demo

**Comment by frogo** [comment]
> 提供可复现 demo

[test.zip](https://github.com/alibaba/ice/files/11795642/test.zip)

大佬，请下载以上文件按照以下步骤复现：
1、解压test.zip后，cd  ./test
2、pnpm i 
3、 成功后pnpm start
4、访问http://localhost:3000/swap，查看node控制台
说明：我在阿里的lowcode低代码生成的出码代码，因为自带的是ice1.0，我想移植到3.0，所以把页面文件拷贝到ice3.0下面了。
下面图片是报错信息
![image](https://github.com/alibaba/ice/assets/3413313/1bca49a7-aab6-4916-a95b-6b76bb8d7699)

**Comment by frogo** [comment]
> > 提供可复现 demo
> 
> [test.zip](https://github.com/alibaba/ice/files/11795642/test.zip)
> 
> 大佬，请下载以上文件按照以下步骤复现： 1、解压test.zip后，cd ./test 2、pnpm i 3、 成功后pnpm start 4、访问[http://localhost:3000/swap，查看node控制台](http://localhost:3000/swap%EF%BC%8C%E6%9F%A5%E7%9C%8Bnode%E6%8E%A7%E5%88%B6%E5%8F%B0) 说明：我在阿里的lowcode低代码生成的出码代码，因为自带的是ice1.0，我想移植到3.0，所以把页面文件拷贝到ice3.0下面了。 下面图片是报错信息 ![image](https://user-images.githubusercontent.com/3413313/247001494-1bca49a7-aab6-4916-a95b-6b76bb8d7699.png)

页面还是可以打开，但是就是 node报错

**Comment by frogo** [comment]
`
import {
  Page as FDPage,
  Section as FDSection,
  Block as FDBlock,
  Cell as FDCell,
} from '@alifd/layout/lib/index.js';
`
这个代码写在index.jsx 里面报错

**Comment by frogo** [comment]
> 为什么不直接 `import { Page, Section, Block, Row, Col, Cell, P, Text, Space } from '@alifd/layout';` ？

阿里的低代码出码后要求是这样的，我不想改出码的代码

**Comment by frogo** [comment]
> > 为什么不直接 `import { Page, Section, Block, Row, Col, Cell, P, Text, Space } from '@alifd/layout';` ？
> 
> 阿里的低代码出码后要求是这样的，我不想改出码的代码

大佬，这个忽略吧，重点看一下#6335吧
