### ISSUE TITLE
Pagination 组件启用下拉选择时，报警告

### ISSUE THREAD

**Issue by busyfree** [alibaba/ice#633]
## 环境信息

- 操作系统：maos 10.13.5
- Iceworks 版本： 2.2.0

## 问题描述

分页组件，启用下拉列表时，报警告

![image](https://user-images.githubusercontent.com/504251/41397359-9372bcc0-6fe6-11e8-8818-a80e299c5b65.png)

组件代码r如下：
![image](https://user-images.githubusercontent.com/504251/41397466-dfcf84ae-6fe6-11e8-90e7-3ec1c7a650ce.png)

## 错误信息

index.js:2178 Warning: Failed prop type: Invalid prop `value` supplied to `Select`.
    in Select (created by LocaleProvider(Select))
    in LocaleProvider(Select) (created by Pagination)
    in div (created by Pagination)
    in div (created by Pagination)
    in Pagination (created by LocaleProvider(Pagination))

**Comment by Symous** [comment]
+1

**Comment by 515445681** [comment]
+1

**Comment by wssgcg1213** [comment]
升级到 @icedesign/base@0.2.3 修复这个问题

**Comment by wssgcg1213** [comment]
![image](https://user-images.githubusercontent.com/3922719/42448702-a867e924-83b0-11e8-85d6-e475cd3aaa07.png)
支持number类型
