### ISSUE TITLE
ice 0.x 升级到ice 1.x

### ISSUE THREAD

**Issue by xiaodoubaoldl** [alibaba/ice#6331]
### Describe the bug
// qiankun相关配置项：打包输入umd代码
output: {
      library: 'xcosBase',
      libraryTarget: 'umd',
      jsonpFunction: `webpackJsonp_${name}`,
      globalObject: 'window',
    },

### Expected behavior

 jsonpFunction: `webpackJsonp_${name}`,
      globalObject: 'window',
在build.json    这两个参数如何配置，查看官方文档没有找到对应配置参数位置

### Version of ice.js

1.x

**Comment by ClarkXia** [comment]
1.x 通过自定义的工程的方式定制
https://v2.ice.work/docs/guide/basic/build#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%B7%A5%E7%A8%8B%E9%85%8D%E7%BD%AE
