### ISSUE TITLE
lite 模版添加 store 插件后报错

### ISSUE THREAD

**Issue by webzzz888** [alibaba/ice#6332]
### Describe the bug

@ice/lite-scaffold 案例，在ice.config.mts文件中加上插件store启动报错
![image](https://github.com/alibaba/ice/assets/91381942/2b2c2606-fa97-4eef-ab79-b60b480fa582)
![image](https://github.com/alibaba/ice/assets/91381942/b2a6d5c6-debd-4093-a13c-1ef75ef95c22)

### Expected behavior

正常启动

### Version of ice.js

3

**Comment by ZRR641182473** [comment]
在plugins 中加入@ice/plugin-store 导致整体项目无法启动

**Comment by ClarkXia** [comment]
Please update to the latest version
