### ISSUE TITLE
Webpack compile error when run "new Web3(ethereum)"

### ISSUE THREAD

**Issue by onlyLiru** [alibaba/ice#6333]
### Describe the bug

When I introduce webjs and instantiate the object, the compilation will report an error

### Expected behavior

compile normally

### Actual behavior

import Web3 from 'web3';

cosnt ethereum = window.ethereum
const web3 = new Web3(ethereum);

and then compile error

<img width="988" alt="image" src="https://github.com/alibaba/ice/assets/7598528/2fd3c30c-fc17-4b49-8bc0-a6d92e7fed87">

### Version of ice.js

3.0.0

**Comment by onlyLiru** [comment]
Please take a look at this question, it is urgent, thank you

**Comment by ClarkXia** [comment]
Fixed in #6472
