### ISSUE TITLE
打包后无法预览，也没报错

### ISSUE THREAD

**Issue by frogo** [alibaba/ice#6335]
### Describe the bug

![image](https://github.com/alibaba/ice/assets/3413313/bf894a03-e6c9-459b-ab60-a05d7f254f75)
不明白打包后的结构
本地anywhere启动一个serve后，访问html，不显示页面内容

### Expected behavior

期望正常显示内容

### Version of ice.js

3.1.0

**Comment by ClarkXia** [comment]
具体访问的什么路径，框架默认是 browser 的路由，如果访问 xxx.html 是无法匹配到路由的

**Comment by frogo** [comment]
> 具体访问的什么路径，框架默认是 browser 的路由，如果访问 xxx.html 是无法匹配到路由的

http://xxx.xxx.xxx.xxx:8081/swapCard   类似这样，
另外问一下。默认有一个layout公共组件，默认我路由跳转一个页面，如何设置

**Comment by frogo** [comment]
> > 具体访问的什么路径，框架默认是 browser 的路由，如果访问 xxx.html 是无法匹配到路由的
> 
> http://xxx.xxx.xxx.xxx:8081/swapCard 类似这样， 另外问一下。默认有一个layout公共组件，默认我路由跳转一个页面，如何设置

我用的版本是ice 3.1.0

**Comment by ClarkXia** [comment]
这个问题 需要你提供下复现的 demo，代码精简成一个路由，或者通过官方 demo 复现即可

**Comment by frogo** [comment]
> 这个问题 需要你提供下复现的 demo，代码精简成一个路由，或者通过官方 demo 复现即可
![微信图片_20230626111123](https://github.com/alibaba/ice/assets/3413313/8404f04d-684b-42e7-877f-d821ce4f62f0)

官方脚手架启动npm run start 也报错

**Comment by ClarkXia** [comment]
那你之前的项目是怎么启动的？

**Comment by frogo** [comment]
> 这个问题 需要你提供下复现的 demo，代码精简成一个路由，或者通过官方 demo 复现即可

[your-project-slug.zip](https://github.com/alibaba/ice/files/11864241/your-project-slug.zip)

pnpm i
pnpm build

**Comment by ClarkXia** [comment]
![image](https://github.com/alibaba/ice/assets/4219965/fbde01fd-6cc3-46cf-a0b9-bea19438c88d)
提供的 demo 本身就是白屏

**Comment by frogo** [comment]
> ![image](https://user-images.githubusercontent.com/4219965/248710765-fbde01fd-6cc3-46cf-a0b9-bea19438c88d.png) 提供的 demo 本身就是白屏

不好意思，大佬，我没有精简路由，这个swapDetail页面有问题，麻烦您访问一下http://localhost:3000/swap和http://localhost:3000/swapCard，另外默认我不知道为什么路由会是http://localhost:3000/swapDetail,当我默认启动的时候
![image](https://github.com/alibaba/ice/assets/3413313/62638c41-1a02-4d8c-a157-4c8f13ca11c8)
![image](https://github.com/alibaba/ice/assets/3413313/4af48162-4381-4f3b-9eee-daf4118512a0)

**Comment by frogo** [comment]
我找到原因了，因为使用了   codeSplitting: 'page', 没有生成index.html，但是奇怪为什么会这样

**Comment by frogo** [comment]
pages下面有layout

**Comment by frogo** [comment]
还是不对，我没有设置路由的原因

**Comment by frogo** [comment]
好像是我pages下面没有index,jsx，打包后才没有index.html的，我设置了路由就有了，我奇怪这个约定路由的方式

**Comment by ClarkXia** [comment]
OK，约定式基于路由规则生成 html，至于 SPA 场景下默认都走 index.html 的场景 后面我们提供个实践
