### ISSUE TITLE
使用fusion组件报错

### ISSUE THREAD

**Issue by frogo** [alibaba/ice#6338]
### Describe the bug

按照官方3.0文档配置，pnpm start 跑起来报错
![image](https://github.com/alibaba/ice/assets/3413313/407dd4e0-129b-4250-b067-566e776b95d6)

### Expected behavior

正常

### Version of ice.js

3.0.0

**Comment by ClarkXia** [comment]
补充下相关使用方式

**Comment by frogo** [comment]
> 补充下相关使用方式

按照3.0的文档接入的

**Comment by ClarkXia** [comment]
![image](https://github.com/alibaba/ice/assets/4219965/c7ce45bb-64d7-4622-889e-f0c20cbd21f5)
![image](https://github.com/alibaba/ice/assets/4219965/a19ae2db-df8a-439a-8feb-44e45bbfb63d)
两种方式均验证过无法复现，可以提供下 demo 后重开 issue
