### ISSUE TITLE
ice3 路由不匹配时候如何配置

### ISSUE THREAD

**Issue by Bingjiajia** [alibaba/ice#6344]
ice3 约定式路由，如果路由不匹配，如何引导到404页面组件

**Comment by ClarkXia** [comment]
https://v3.ice.work/docs/guide/basic/router#%E9%80%9A%E9%85%8D%E8%B7%AF%E7%94%B1 通过通配路由来定义404 页面

**Comment by Bingjiajia** [comment]
如果在page下面又layout，如何将通配路由约束在layout之外，  
// 过滤未套用该布局的页面
  if (['/login', '/register', '/bigscreen'].includes(location.pathname)) {
    return <Outlet />;
  }
