### ISSUE TITLE
ice3如何配置多个entry

### ISSUE THREAD

**Issue by Zenilia** [alibaba/ice#6348]
### Describe the bug

ice3如何配置以达到传统mpa的效果，根据pages中每个文件夹打包成多份index.js和index.css供后台vm模板引用。前端项目不希望引入路由功能

### Expected behavior

ice3如何配置以达到传统mpa的效果，根据pages中每个文件夹打包成一份index.js和index.css供后台vm模板引用。

### Version of ice.js

v3

**Comment by ClarkXia** [comment]
ice3 不支持多 entry，对于 MPA 的诉求目前通过 SPA 下的拆包逻辑来达到访问路由时仅加载当前路由资源的效果。

**Comment by Zenilia** [comment]
那如果要多入口的话，目前是只能降级使用ice v2吗？

**Comment by ClarkXia** [comment]
先看看用上面的方式有什么问题吧
