### ISSUE TITLE
ice3 和 fusion组件库结合使用 menu菜单样式问题

### ISSUE THREAD

**Issue by Bingjiajia** [alibaba/ice#6349]
### Describe the bug

ice3框架配合fusion组件库使用时候，menu菜单展开样式显示异常

### Expected behavior

希望menu才能展开显示正常

### Version of ice.js

ice3

**Comment by ClarkXia** [comment]
具体异常情况需要描述并提供相关 demo

**Comment by ClarkXia** [comment]
提供 demo 后重开 issue
