### ISSUE TITLE
物料源加载失败或设置有误，请检查

### ISSUE THREAD

**Issue by qifengle** [alibaba/ice#636]
## 环境信息

- 操作系统：
- Iceworks 版本： 2.2.0

## 问题描述

构建了一次项目后，就提示物料源加载失败或设置有误，请检查，然后模版也没法打开，官网也进不去

**Comment by noyobo** [comment]
这看起来像是网络有问题？  <http://ice.alicdn.com/assets/react-materials.json> 物料源的地址。 可以看看能不能打开

**Comment by qifengle** [comment]
@noyobo 不能打开，提示这个错误
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<RequestId>5B2325E296CC86DD37423C34</RequestId>
<HostId>iceworks.oss-cn-hangzhou.aliyuncs.com</HostId>
<Key>assets/react-materials.json</Key>
</Error>

**Comment by noyobo** [comment]
我查下

**Comment by noyobo** [comment]
好了

**Comment by qifengle** [comment]
@noyobo 好了，麻烦您了

**Comment by f497196689** [comment]
@noyobo 我可以访问那个地址 但是我的React物料源显示加载失败或者配置有误。

![image](https://user-images.githubusercontent.com/15325854/43632891-08726ec4-973a-11e8-8778-25f0035f2065.png)

![image](https://user-images.githubusercontent.com/15325854/43632911-206d1ca4-973a-11e8-95f3-1058058e0778.png)
