### ISSUE TITLE
ice  正式环境偶发问题  The requested module './index.js' does not provide an export named 'cn'

### ISSUE THREAD

**Issue by wx9999** [alibaba/ice#6366]
### Describe the bug

<img width="867" alt="image" src="https://github.com/alibaba/ice/assets/42061047/bd83c435-14f0-4a15-8365-1ca9107de1c5">
<img width="512" alt="image" src="https://github.com/alibaba/ice/assets/42061047/219bb34d-9d6a-48f4-9ac1-0f15cf7a4e4f">

### Expected behavior

期待知道这是什么原因产生的

### Version of ice.js

2.0.0

**Comment by ClarkXia** [comment]
需要提供复现代码

**Comment by ClarkXia** [comment]
提供复现代码后重开 issue
