### ISSUE TITLE
构建路径如何修改，默认是/

### ISSUE THREAD

**Issue by xcsweb** [alibaba/ice#637]
## 环境信息

- 操作系统：
- Iceworks 版本： 

## 问题描述
构建路径如何修改，默认是/

**Comment by noyobo** [comment]
https://github.com/alibaba/ice/wiki/%E5%BC%80%E5%90%AF%E5%8A%A8%E6%80%81%E5%8A%A0%E8%BD%BD%E5%A6%82%E4%BD%95%E9%83%A8%E7%BD%B2#%E4%BF%AE%E6%94%B9-webpackrcjs

**Comment by noyobo** [comment]
参考 【修改 .webpackrc.js】 部分
