### ISSUE TITLE
请教一下子应用开启了路由代码分割，主应用该如何引用资源？

### ISSUE THREAD

**Issue by Sharang-heng** [alibaba/ice#6371]
### Describe the bug

子应用使用了代码分割，打包后如下图
![Snipaste_2023-07-05_11-27-13](https://github.com/alibaba/ice/assets/69613396/153ad435-846b-48b2-87b9-69a269b6e983)
![Snipaste_2023-07-05_11-26-30](https://github.com/alibaba/ice/assets/69613396/26241f43-7e13-42bd-b74d-f3509534b52a)

然后我在主应用通过url引用资源url：['/ac-api/js/index.js', '/ac-api/css/index.css']
此时出现的效果为index.js正常请求成功，但是代码分割后的内容请求会报404，这里为了区分主应用和子应用的请求在子应用的请求前面统一加了个/ac-api，感觉是打包后引用地址为相对路径所以导致这个问题
![Snipaste_2023-07-05_15-14-21](https://github.com/alibaba/ice/assets/69613396/5d129588-3ace-4505-9f09-91e1f0e4d52d)
![Snipaste_2023-07-05_15-13-55](https://github.com/alibaba/ice/assets/69613396/a190bc90-16d9-4985-9041-e04802567826)
想请教一下这种情况应该怎么处理？

### Expected behavior

主应用能正常引用子应用代码分割部分

### Version of ice.js

2.6.6

**Comment by ClarkXia** [comment]
加载主 bundle 就好了，至于加载其他 chunk 主 bundle 会自动去做， https://micro-frontends.ice.work/docs/faq#%E5%BA%94%E7%94%A8%E5%90%AF%E7%94%A8-lazy-%E5%90%8Echunk-%E5%8A%A0%E8%BD%BD%E5%A4%B1%E8%B4%A5 参考下
