### ISSUE TITLE
Vue 项目如何修改 publicPath  构建路径

### ISSUE THREAD

**Issue by xcsweb** [alibaba/ice#638]
## 环境信息

- 操作系统：
- Iceworks 版本： 

## 问题描述

感觉这个文件没有起作用，例如:
![](https://ws1.sinaimg.cn/large/af65cd95gy1fsbuvwm7jej20ju07eglr.jpg)

![](https://ws1.sinaimg.cn/large/af65cd95gy1fsbuxiux8qj20dv04mjrg.jpg)

**Comment by noyobo** [comment]
看下你的构建日志

**Comment by xcsweb** [comment]
![](https://ws1.sinaimg.cn/large/af65cd95gy1fsbuz5uudrj20gx09twet.jpg)

**Comment by noyobo** [comment]
你用的是 vue 的工程吧 ？

**Comment by xcsweb** [comment]
![](https://ws1.sinaimg.cn/large/af65cd95gy1fsbuzv3xvxj20hh0bodg7.jpg)
嗯

**Comment by noyobo** [comment]
哦。 我以为你的是 ice 的。  

@chenbin92  你看下

**Comment by xcsweb** [comment]
ice 里面选择的vue模板，然后构建的

**Comment by chenbin92** [comment]
@xcsweb  vue 项目使用的是 vue 官方提供的 [vue-cli](https://github.com/vuejs/vue-cli) 工程套件，所有的配置可参考 [vue-cli 文档](https://cli.vuejs.org/)

**Comment by xcsweb** [comment]
![image](https://user-images.githubusercontent.com/20693737/41454471-12e11338-70ac-11e8-9a95-85c649ed8d0c.png)
icoworks 创建的只能创建模板，其他的配置项，要用vue-cli的呗，.webpackrc.js不能使用

**Comment by noyobo** [comment]
是的。 vue 的还是使用社区的工具。

**Comment by chenbin92** [comment]
不同的项目类型使用的不同构建工具
* vue 项目使用 vue-cli，配置按照 vue-cli 文档
* ice react 项目使用 ice-scripts，可以配置 .webpackrc.js
