### ISSUE TITLE
ice3框架无用warning治理

### ISSUE THREAD

**Issue by bloody-ux** [alibaba/ice#6385]
### Describe the bug

<img width="897" alt="image" src="https://github.com/alibaba/ice/assets/19991767/287bdbdb-84e8-493a-9aaf-651e3473af74">

ice框架报了warning，而这个warning的触发源本身就是ice框架自己写的
能否治理下，否则太奇怪了，干扰开发人员排查

### Expected behavior

去除不必要的warning

### Version of ice.js

3.2.7

**Comment by ClarkXia** [comment]
这个 warning 目前只在 basic-project demo 中出现，为了验证 warning 效果。其他官方插件我们近期会修正该用法
