### ISSUE TITLE
ice3 dataloader兼容性未感知browserlist配置，而是写死了es6

### ISSUE THREAD

**Issue by bloody-ux** [alibaba/ice#6388]
### Describe the bug

无论如论配置.browserlist文件，data-loader生成的始终是es6格式

### Expected behavior

期望根据browserlist配置，生成对应的兼容性的data-loader，保持和主bundle一致

实现建议

``` javascript
import browserslistToEsbuild from 'browserslist-to-esbuild'

const { outputFiles, error } = await this.serverCompiler({
    target: browserslistToEsbuild(), // read browserlist， 注意，在start命令下，必须写死es6，否则会报错
    format: 'iife',
    entryPoints: [filePath],
    write: false,
    logLevel: 'silent', // The main server compile process will log it.
}, {})
```

### Version of ice.js

ice3.2.7

**Comment by ClarkXia** [comment]
感谢反馈！
serverCompiler 默认还会追加一个编译的插件，该插件会将代码根据 browserslists 的设置进行编译，这里设置 es6 的原因是不想让 esbuild 做过多的语法编译，如果在实际使用上发现兼容性问题，可以另外提一个 issue
