### ISSUE TITLE
创建时的模板可以支持自定义吗

### ISSUE THREAD

**Issue by ZRR641182473** [alibaba/ice#6389]
### Describe the bug

在文档上没有找到关于模板自定义

### Expected behavior

可以像官方的模板进行自己定制

### Version of ice.js

3.0.0

**Comment by ClarkXia** [comment]
https://v3.ice.work/docs/guide/start#%E5%88%9B%E5%BB%BA%E5%BA%94%E7%94%A8

```bash
$ npm create ice ice-app --template @ice/lite-scaffold
```

通过 --template 指定
