### ISSUE TITLE
路由间跳转有多次重复渲染

### ISSUE THREAD

**Issue by aspirantzhang** [alibaba/ice#6390]
### Describe the bug

路由间跳转有多次重复渲染
![GIF 2023-7-14 14-15-58](https://github.com/alibaba/ice/assets/24559988/eef5c2d7-0cf6-4765-a731-454fc2b1109f)

### Expected behavior

仅一次渲染

### Version of ice.js

3.2.7

### Content of build.json or ice.config.mts

```TypeScript
import { defineConfig } from '@ice/app';

const minify = process.env.NODE_ENV === 'production' ? 'swc' : false;
export default defineConfig(() => ({
  ssg: false,
  minify,
  server: {
    onDemand: true,
    format: 'esm',
  },
}));
```

### Additional context

ice.js 3 lite 模板搭建，已经关闭SSG了，页面之间跳转依然是二次渲染，这个也太奇葩了

**Comment by ClarkXia** [comment]
目前定位到跟 react-router v5_compat 相关，下个版本将优化下渲染逻辑

**Comment by ClarkXia** [comment]
已修复

**Comment by aspirantzhang** [comment]
已升级到最新的 ice v3.2.9 依然存在问题

https://codesandbox.io/p/sandbox/elated-frog-frp23r

@ClarkXia
