### ISSUE TITLE
ice3 proxy失效

### ISSUE THREAD

**Issue by Bingjiajia** [alibaba/ice#6393]
### Describe the bug

利用ice3进行跨域代理，无法返回response, 后端也没有接到request，但是浏览器显示返回状态200
`import { defineConfig } from '@ice/app';
import request from '@ice/plugin-request';
import store from '@ice/plugin-store';
import auth from '@ice/plugin-auth';

const minify = process.env.NODE_ENV === 'production' ? 'swc' : false;

export default defineConfig(() => ({
  ssg: false,
  minify,
  plugins: [request(), store(), auth()],
  routes: {
    ignoreFiles: ['**/components/**'],
  },
  compileDependencies: false,
  proxy: {
    '/api': {
      target: 'http://192.168.137.21:8080/',
      changeOrigin: true,
      pathRewrite: { '^/api': '' }
    }
  }
}));`

注册调用
`/**
 * 注册
 * @param userinfo 用户信息
 * */
export const register = (userinfo) => {
  return sepdHttp.post('/user/saveUserXXB', userinfo);
};`

### Expected behavior

期望可以正常跨域，正常返回数据

### Version of ice.js

ice3

**Comment by xianghongai** [comment]
您好，遇到同样问题，您是如何解决的？
