### ISSUE TITLE
使用 @ice/plugin-request 插件后编译报错

### ISSUE THREAD

**Issue by Tyrentselector** [alibaba/ice#6394]
### Describe the bug

ice 3 使用 @ice/plugin-request 插件后编译报错
![image](https://github.com/alibaba/ice/assets/16445903/d78ad5d4-d0b3-494a-868d-dc9cd0ffbf9f)

### Expected behavior

编译可以正常通过

### Version of ice.js

latest

**Comment by Tyrentselector** [comment]
nodejs 版本 18.6.0 和 16.13.0 都尝试过

**Comment by Tyrentselector** [comment]
![image](https://github.com/alibaba/ice/assets/16445903/19e3cca0-b66f-4deb-ba8d-baae88bbb02c)
配置 onDemand 为 true 时编译报错，为 false 时可以通过编译

**Comment by ClarkXia** [comment]
ok 我们修复下 onDemand 下的使用场景

**Comment by ClarkXia** [comment]
Fixed in #6466
