### ISSUE TITLE
icejs构建工程缓慢，总是卡在69%很长时间，飞冰如何使用speed-measure-webpack-plugin插件分析

### ISSUE THREAD

**Issue by linshaoye** [alibaba/ice#6395]
### Describe the bug

背景：随着项目工程越来越大，构建速度也越来越慢，因此想使用speed-measure-webpack-plugin插件分析项目。
工程依赖包：
=
![Uploading 卡.png…]()

### Expected behavior

期望飞冰可以支持speed-measure-webpack-plugin插件分析构建性能

### Actual behavior

[](url)

### Version of ice.js

1.18.0

**Comment by ClarkXia** [comment]
69% 应该处于文件压缩阶段，ice.js 1.x 可以基于插件机制对 webpack 进行定制，增加 speed-measure-webpack-plugin 即可 https://v2.ice.work/docs/config/about#webpackplugins-

**Comment by linshaoye** [comment]
@ClarkXia 有使用的例子吗？为啥我配置完插件没有生效那，而且我看speed-measure-webpack-plugin 需要按如下形式使用，不知道在ice中如何引入
const smp = new SpeedMeasurePlugin();

const webpackConfig = smp.wrap({
  plugins: [new MyPlugin(), new MyOtherPlugin()],
});

**Comment by zhangZzz-Free** [comment]
老哥解决了嘛，不清楚在哪个位置配置 speed-measure-webpack-plugin，该尝试的都试了，要么报错，要么没效果
