### ISSUE TITLE
mac 新建项目长时间无响应（无完成状态）

### ISSUE THREAD

**Issue by Michaelooo** [alibaba/ice#64]
1. mac 新建项目长时间无响应（无完成状态），手动切换 设置 - 项目 后，项目不见了，手动打开项目才可以;
2. 试用了几个，的确挺方便的，果然是0配置，配上 eggjs 食用更佳。那么，公测结束未来是开源还是付费道路呢。

**Comment by wssgcg1213** [comment]
新建项目较慢的问题是因为npm安装依赖较多, 后面我们会把进度和日志补充上来

**Comment by yujiangshui** [comment]
@Michaelooo 开源免费，而且我们会开放部分 VIP 名额给重度使用的用户或者公司来 1V1 的支持，主要目的是为了能有足够的需求逐步迭代。商业化是比较远的事情。
