### ISSUE TITLE
You are calling ReactDOMClient.createRoot() on a container /  Text content did not match. Server: "124" Client: "123"

### ISSUE THREAD

**Issue by xmsz-stu** [alibaba/ice#6402]
### Describe the bug

- 添加pages/layout.tsx
- 修改layout里的内容
- 浏览器报错
- 且如果修改的是className则不会更新，需要手动刷新，或者修改文本才行

<img width="1415" alt="image" src="https://github.com/alibaba/ice/assets/139225486/82f86c8c-e8dd-4b58-9bab-38bb2fb9a548">

### Expected behavior

正常运行

### Version of ice.js

3.0

### Content of build.json or ice.config.mts

```TypeScript
import { defineConfig } from '@ice/app';

// The project config, see https://v3.ice.work/docs/guide/basic/config
const minify = process.env.NODE_ENV === 'production' ? 'swc' : false;
export default defineConfig(() => ({
  // Set your configs here.
  minify,
  server: {
    onDemand: true,
    format: 'esm',
  },
}));
```

### Additional context

DEMO:https://github.com/xmsz/demo-20230720

**Comment by Damisko** [comment]
thanks

**Comment by xmsz-stu** [comment]
我发现跟layout好像没关系 我创建一个子页面 然后里面更新也会报这个错 并且因为有这个错误 会导致无法触发组件的unmount

**Comment by ClarkXia** [comment]
Fixed in #6442
