### ISSUE TITLE
某些情况下构建速度很慢至少1秒以上

### ISSUE THREAD

**Issue by xmsz-stu** [alibaba/ice#6403]
### Describe the bug

- 改变任何内容
- 更新需要至少1s以上，经常需要2、3秒
<img width="349" alt="image" src="https://github.com/alibaba/ice/assets/139225486/25bfb932-446d-403e-9bd6-2c7683664ea5">

### Expected behavior

如何解决这种情况

### Version of ice.js

3.0

### Content of build.json or ice.config.mts

```TypeScript
import { defineConfig } from '@ice/app';

// The project config, see https://v3.ice.work/docs/guide/basic/config
const minify = process.env.NODE_ENV === 'production' ? 'swc' : false;
export default defineConfig(() => ({
  // Set your configs here.
  minify,
  server: {
    onDemand: true,
    format: 'esm',
  },
  postcss: {
    plugins: ['tailwindcss'],
  },
  ssg: false,
}));
```

### Additional context

DEMO: https://github.com/xmsz/demo-2023072002

**Comment by ClarkXia** [comment]
某些情况下具体是指哪些

**Comment by xmsz-stu** [comment]
> 某些情况下具体是指哪些

复现是100%，但我不确定不确定是什么情况造成的

我做了一些尝试
- global.scss中注释掉 ic.scss  -> 速度变快
- 卸载semiUI -> 速度变快
- global.scss中注释tailwind -> 速度变快

可能是太多样式文件处理吗？

**Comment by ClarkXia** [comment]
大量的 sass 处理的确会导致 hmr 的速度变慢，目前我们也在接入 rust 的一些工具来提升编译速度，欢迎关注 https://github.com/alibaba/ice/pull/6440
