### ISSUE TITLE
ExtractCssAssetsWebpackPlugin 插件报Asset download failed 错误，是否有不下发请求，本地化的方案

### ISSUE THREAD

**Issue by linshaoye** [alibaba/ice#6406]
### Describe the bug

背景：在构建时总是报下面的错误，看报错像是下载失败，由于构建环境为内部局域网，是否有办法本地远程下载的文件。

emitting[ExtractCssAssetsWebpackPlugin] Warning: Asset download failed http://at.alicdn.com/t/font_2835669_uwbshf7itqo.eot
    <?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>NoSuchKey</Code>
  <Message>The specified key does not exist.</Message>
  <RequestId>64B8F7999DDDB030382351D3</RequestId>
  <HostId>at.alicdn.com</HostId>
  <Key>t/font_2835669_uwbshf7itqo.eot</Key>
  <EC>0026-00000001</EC>
</Error>

[ExtractCssAssetsWebpackPlugin] Warning: Asset download failed http://at.alicdn.com/t/font_2835669_uwbshf7itqo.eot
    <?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>NoSuchKey</Code>
  <Message>The specified key does not exist.</Message>
  <RequestId>64B8F7999DDDB030382351D3</RequestId>
  <HostId>at.alicdn.com</HostId>
  <Key>t/font_2835669_uwbshf7itqo.eot</Key>
  <EC>0026-00000001</EC>
</Error>

### Expected behavior

提供本地化的方案，不下发请求

### Version of ice.js

1.18.0

**Comment by ClarkXia** [comment]
如果要资源本地化，那就要先下载好对应的资源，然后通过 fusino css 资源地址替换的能力实现，参考 https://v2.ice.work/docs/plugin/list/css-assets-local#%E5%9C%BA%E6%99%AF-2%E6%9E%84%E5%BB%BA%E9%83%A8%E7%BD%B2%E5%92%8C%E7%BD%91%E7%AB%99%E8%BF%90%E8%A1%8C%E6%97%B6%E9%83%BD%E8%AF%B7%E6%B1%82%E4%B8%8D%E5%88%B0-cdn-%E6%96%87%E4%BB%B6
