### ISSUE TITLE
在单元测试中使用已经编写的mock数据

### ISSUE THREAD

**Issue by tsingsun** [alibaba/ice#6410]
### Describe the bug

在开发实践中,mock服务很好的帮助了前端开发人员.当开发UI控件时,需要同步写一些单元测试,目前不知如何在单元测试中使用ice mock功能.使已经编写好的mock服务可以复用.

### Expected behavior

1. 可以在单元测试中使用mock功能.
2. 有相应的文档指导.

### Version of ice.js

3.2.6

**Comment by ClarkXia** [comment]
mock 文档可以参考 https://v3.ice.work/docs/guide/basic/mock

**Comment by tsingsun** [comment]
集成测试已经有在用了..在单元测试中使用, 将单元测试jest或者vitest中的请求也可以转发到mock.

**Comment by ClarkXia** [comment]
jest 或者 vitest 本身就有 mock request 请求的能力，mock 写法上也是对象，可以在单元测试中直接导入，作为 mock request 的返回值即可
