### ISSUE TITLE
ice3用antd5开启紧凑主题出错

### ISSUE THREAD

**Issue by eqyun** [alibaba/ice#6413]
### Describe the bug

Error: Cannot find module 'antd/dist/theme'

### Expected behavior

能否提供兼容antd4的紧凑主题，从antd4升级到antd5,主题各种乱套

### Version of ice.js

3

**Comment by ClarkXia** [comment]
先解决 antd/dist/theme 找不的问题，确认下路径

**Comment by ClarkXia** [comment]
https://github.com/ice-lab/react-materials/tree/master/scaffolds/ice3-antd-pro  官方 demo 供参考，后续也可以提供下出问题的 demo
