### ISSUE TITLE
ice-skin-loader 插件构建速度慢

### ISSUE THREAD

**Issue by linshaoye** [alibaba/ice#6414]
### Describe the bug

1.使用speed-measure-webpack-plugin 插件分析ice-skin-loader 插件构建速度缓慢.
2.构建时老是卡在69%，之前怀疑是文件压缩，"minify"设置false 关闭压缩后依然卡在69%,性能分析结果如下图
![image](https://github.com/alibaba/ice/assets/41201374/ea9f76d7-f35a-4961-b470-cf252106ca1e)

![image](https://github.com/alibaba/ice/assets/41201374/b2ffacda-e5d6-40e8-b056-fe6c5f3491e4)
![image](https://github.com/alibaba/ice/assets/41201374/210cdf96-a9d9-47ba-b716-b45cfeb472e3)
### Expected behavior

有优化ice-skin-loader 插件插件的方案

### Version of ice.js

1.18.0

**Comment by ClarkXia** [comment]
ice-skin-loader 基本不再维护，推荐升级 ice.js 版本

**Comment by xinyiPig** [comment]
@ClarkXia 请问新版ice.js 怎么使用 speed-measure-webpack-plugin

**Comment by ClarkXia** [comment]
ice.js 都是基于 webpack 的，可以直接配置插件 https://v3.ice.work/docs/guide/basic/config#webpack
