### ISSUE TITLE
[QUESTION] 开启 hash=contenthash 则global.scss无法热更新

### ISSUE THREAD

**Issue by xmsz-stu** [alibaba/ice#6417]
### Describe the bug

// ice.config.mts 
开启hash:"contenthash"

// global.scss
修改则无热更新，需要重新构建

### Expected behavior

正常热更新

### Actual behavior

无法热更新

### Version of ice.js

3.0

### Additional context

临时：正式环境才开启hash

**Comment by ClarkXia** [comment]
开启 hash 后样式无法热更新是 MiniCssExtractPlugin 的一个问题，目前社区也没有比较好的解法，我们会持续关注相关生态的情况，参考 https://github.com/webpack-contrib/mini-css-extract-plugin/issues/444
