### ISSUE TITLE
global.less 中 import 未生效

### ISSUE THREAD

**Issue by answershuto** [alibaba/ice#6425]
### Describe the bug

```js
@import '~@ali/bees-yuumi-theme-mobile/esm/themes/index.css';
```

### Expected behavior

import 的可以生效

### Version of ice.js

3.3.0

**Comment by luhc228** [comment]
没问题 ，是可生效的

**Comment by 2018212632** [comment]
我重新看了我的例子，并没有生效。
询问上下文（包含例子复现仓库）：https://links.alibaba-inc.com/app/room/5f717ef787f98104f34edc18/64c3236051a53d06275c24b0/ ；
