### ISSUE TITLE
router.type="hash"时不能配置basename

### ISSUE THREAD

**Issue by xmsz-stu** [alibaba/ice#6426]
### Describe the bug

原先是用默认的history模式，并且放在CDN的子目录下，basename也调整了，不过首页能访问，其他路由刷新就空白
只能改成hash模式，部署后就空白了

后来把basename去掉就正常了

### Expected behavior

希望可以提示一下

### Version of ice.js

3.0

**Comment by ClarkXia** [comment]
可以描述清楚前后的 basename 设置以及访问的路由链接。

**Comment by xmsz-stu** [comment]
> 可以描述清楚前后的 basename 设置以及访问的路由链接。

访问路径: xxx.com/a/

原先：
路由模式为: history
basename设置为: a
表现
- 访问xxx.com/a/可用，跳转正常
- 但跳转后(/a/b)刷新页面空白，因为CDN找不到/a/b下的文件


只能调整：
路由模式为:  history
basename还是不变: a
表现
- 访问xxx.com/a/白屏，不报错


然后我将basename去除后，访问正常

**Comment by ClarkXia** [comment]
路由模式为分 browser 和 hash，一般请求下页面跳转后正常，刷新后空白的原因是由于服务端，比如 nginx 需要配置一个通用规则，比如 /a 和 /a/b 都输出统一的 html 内容，执行 html 中的 js 后由前端接管路由渲染

**Comment by xmsz-stu** [comment]
> 路由模式为分 browser 和 hash，一般请求下页面跳转后正常，刷新后空白的原因是由于服务端，比如 nginx 需要配置一个通用规则，比如 /a 和 /a/b 都输出统一的 html 内容，执行 html 中的 js 后由前端接管路由渲染

是的 我的需求

1. 有没有hash模式下设置basename的场景
2. 如果没有的话，希望在文档里备注一下，basename在hash模式下不支持，并且不能填写，填写会有影响

**Comment by ClarkXia** [comment]
hash 模式也是支持 basename 的，原 hash 路径为 /#/a，添加 basename 后变为 /#/basename/a。文档说明上我们再优化下
