### ISSUE TITLE
ice 动态配置basename

### ISSUE THREAD

**Issue by Wangjing991** [alibaba/ice#6431]
### Describe the bug

![image](https://github.com/alibaba/ice/assets/19301714/d3c494d9-7352-4bea-aa34-1ce85acba1d1)
由于项目需要 basename  再不同服务器上不同，需要动态basename
![image](https://github.com/alibaba/ice/assets/19301714/738d0747-c8ad-4322-95d1-7afdff63a492)
现在da打包报错，有没有其他可替代方案

### Expected behavior

支持动态basename

### Version of ice.js

3.1.8

**Comment by ClarkXia** [comment]
appConfig 需要为同构数据，需要支持在 node 执行，可以判断下 location 是否存在进行兼容

**Comment by Wangjing991** [comment]
> appConfig 需要为同构数据，需要支持在 node 执行，可以判断下 location 是否存在进行兼容
不太明白，具体怎么操作？
