### ISSUE TITLE
Support absolute config path

### ISSUE THREAD

**Issue by linbudu599** [alibaba/ice#6435]
### Describe the bug

当前 `--config` 参数不支持使用绝对路径的地址，因为内部会固定 `path.join` 一次，见 [`createService`](https://github.com/alibaba/ice/blob/master/packages/ice/src/createService.ts#L225).

```typescript
const userConfigHash = await getFileHash(path.join(rootDir, fg.sync(configFile, { cwd: rootDir })[0]));
```

### Expected behavior

在接收到绝对路径时，直接使用而不需要 `join`。

### Version of ice.js

LATEST

**Comment by ClarkXia** [comment]
这个在 https://github.com/ice-lab/build-scripts/pull/130 支持了，后续直接拿 context 上的信息
