### ISSUE TITLE
启动命令 --https 无法生成自签名证书

### ISSUE THREAD

**Issue by whinc** [alibaba/ice#6436]
### Describe the bug

最近一次 npm install 后，就会出现自签名证书失效问题，导致转换成 http 

![image](https://github.com/alibaba/ice/assets/5096493/430e6407-b028-414d-be27-c32a4cbc99a3)

![image](https://github.com/alibaba/ice/assets/5096493/964591ab-95a6-4ce8-a4eb-a15134a5b4f4)

### Expected behavior

![image](https://github.com/alibaba/ice/assets/5096493/f9f70a82-05bf-43f4-a7b6-d746b9af2ae9)

### Version of ice.js

2.6.6

**Comment by whinc** [comment]
> 不要锁定版本重新安装依赖，同时删除原先的 ~/.trusted-cert 目录，然后重新执行

按重新安装依赖后，启动依然会存在这个问题
```
rm package-lock.json
rm -rf node_modules
rm -rf ~/.trusted-cert
npm install
```

**Comment by whinc** [comment]
开启 debug 模式后输出的 webpack 配置中显示 https 是关闭状态

![image](https://github.com/alibaba/ice/assets/5096493/e2c4a279-3e14-4fc4-9fe1-500625b92557)

**Comment by ClarkXia** [comment]
npm list trusted-cert 看下版本

**Comment by whinc** [comment]
> npm list trusted-cert
```
└─┬ ice.js@2.6.6
  └─┬ build-plugin-react-app@2.2.3
    └─┬ @builder/user-config@2.2.5
      └── trusted-cert@1.1.4
```

**Comment by whinc** [comment]
目前暂时通过指定锁定 trusted-cert@1.1.3 版本解决了该问题

**Comment by ClarkXia** [comment]
上一个版本的证书在最新的 chrome 下是不受信的，这边暂时无法复现，后续如果有稳定复现的 demo，可以重开下 issue
