### ISSUE TITLE
如何在飞冰中配置限制编译进程数量以及内存最大值限制，在chunk assets阶段 内存飙升

### ISSUE THREAD

**Issue by linshaoye** [alibaba/ice#6437]
### Describe the bug

背景：由于公司编译机器内存有限制，在编译时chunk assets阶段node会出现多个进程，此时会导致内存溢出，因此想通过牺牲时间减少进程，来保证编译成功。
![image](https://github.com/alibaba/ice/assets/41201374/b1b7a7f9-6393-474f-a0bf-acfd4fc44fd5)

![image](https://github.com/alibaba/ice/assets/41201374/dfc0ce21-9bf8-474e-be0a-7dc5f3435847)

### Expected behavior

期望可以提供减少进程数量的方式或配置

### Version of ice.js

1.18.0

**Comment by ClarkXia** [comment]
可以先看下是不是本身在打包的时候三方依赖过多导致

**Comment by ClarkXia** [comment]
另外可以考虑升级版本，1.x 以上的版本支持 webpack 5 以及其他原生压缩工具，可以有效解决内存问题
