### ISSUE TITLE
修改组件源码无效

### ISSUE THREAD

**Issue by Symous** [alibaba/ice#644]
## 环境信息

- 操作系统：macOS 10.13.5
- Iceworks 版本： 2.3.1

## 问题描述

在使用过程中发现Pagination组件有些问题，想自己通过源码修改一下，根据引用路径找到@icedesign/base/lib/_components/@alife/next-pagination/lib/pagination.js进行修改后，发现并没有任何效果。这个问题可能比较蠢，见谅...

**Comment by noyobo** [comment]
重启后是否生效？ 或者可以加个 `debugger` 看断点

**Comment by Symous** [comment]
@noyobo 重新构建项目无效，重新启动飞冰客户端然后开始调试服务后生效了。难道每次修改代码都要重新启动的吗？

**Comment by Symous** [comment]
@noyobo 测试了一下，修改源码后，先点击停止调试服务，然后点击启动调试服务后，代码修改生效，有没有办法修改代码后即时生效呢？

**Comment by noyobo** [comment]
没即时生效是以为 在 node_module 目录下有很多文件，监听文件变动会消耗很大资源。所以默认这个是不监听的。

有什么问题？ 可以提供个 demo 代码，我这边看下。

**Comment by Symous** [comment]
@noyobo 问题请见这里， #633 。
请问将来我们第三方开发者使用这个库修改代码都不可以即时生效的吗，这样的话可能修改起来不太方便。

**Comment by noyobo** [comment]
修改代码可以通过  `npm link` 的方式将文件位置修改，而不要去改 node_modules 里的代码。 

由于 `@icedesign/base` 代码未开源，发布的也是压缩版本的代码，暂无源码下载。
