### ISSUE TITLE
ICECream Integration Issues

### ISSUE THREAD

**Issue by linbudu599** [alibaba/ice#6441]
### Summary | 概述

这个 issue 记录在 ICECream 在与 ICE 整合过程中遇到的问题。

## [Feature] Programmatic API

Support Programmatic API for higher wrapper so they can invoke ICE programmatically:

```typescript
import { createICEService } from 'ice';

createICEService('start', { }); // Works as same as `ice start`
createICEService('build', { }); // Works as same as `ice build`
```

## [Feature] Absolute Config

Supported in [build-scripts#130](https://github.com/ice-lab/build-scripts/pull/130)

## [Feature] Absolute Routes

Support absolute route path in ICE config:

```typescript
defineRoutes('/hi', '/...path.jsx'); // path.jsx 位于项目内，但不在 `src/pages` 下。
```

## [Bug] DefineRoutes & Layout

[ice-defineRoutes](https://github.com/linbudu599/ice-defineRoutes-bug-repro)

### Detailed design | 方案设计

_

**Comment by ClarkXia** [comment]
> [Bug] DefineRoutes & Layout 

这个问题是因为路由优先匹配的规则导致的，推荐定义上还是用以下方式：

```js
routes: {
  ignoreFiles: ['**']
  defineRoutes: (routes) => {
    routes("/", "layout.tsx", () => {
      routes("", "generated/index/index.tsx");
    });
  }
}
```

由于通过约定分析的结果也存在根路由，将会优先匹配第一个中，可以通过 ignoreFiles 的方式忽略对应页面规则，然后通过上述方式自定义。
如果要修正将会改变路由匹配优先级（自定义 > 约定），会有 breakchange，暂不做修复。
