### ISSUE TITLE
ice-script升级ice，报错

### ISSUE THREAD

**Issue by deshanmoon** [alibaba/ice#6443]
### Describe the bug

`{
  "name": "BaikalDB",
  "version": "1.0.0",
  "description": "BaikalDB",
  "dependencies": {
    "@alifd/fusion-collector": "1.3.5",
    "@alifd/next": "^1.13.4",
    "@antv/data-set": "^0.8.9",
    "@babel/runtime": "^7.0.0-beta.55",
    "@ice/runtime": "^1.0.0",
    "@icedesign/base": "^0.2.6",
    "@icedesign/container": "^0.1.4",
    "@icedesign/data-binder": "^0.1.9",
    "@icedesign/form-binder": "^0.1.7",
    "@icedesign/icon": "^0.1.1",
    "@icedesign/img": "^0.1.0",
    "@icedesign/layout": "^0.1.0",
    "@icedesign/menu": "^0.1.0",
    "@icedesign/panel": "^0.1.6",
    "@icedesign/skin": "^0.1.0",
    "bizcharts": "^3.2.2",
    "classnames": "^2.2.5",
    "extract-text-webpack-plugin": "^4.0.0-beta.0",
    "foundation-symbol": "^0.1.0",
    "js-cookie": "^2.2.0",
    "mock": "^0.1.1",
    "mockjs": "^1.0.1-beta3",
    "prop-types": "^15.5.8",
    "react": "^16.4.1",
    "react-dom": "^16.4.1",
    "react-router": "^4.3.1",
    "react-router-dom": "^4.2.2"
  },
  "devDependencies": {
    "@babel/core": "^7.22.9",
    "@babel/plugin-proposal-decorators": "^7.22.7",
    "@ice/app": "^3.0.0",
    "babel-eslint": "^8.0.3",
    "eslint": "^4.13.1",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-plugin-babel": "^4.1.1",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-react": "^7.5.1"
  },
  "scripts": {
    "start": "ice start",
    "build": "ice build",
    "lint": "eslint . --ext '.js,.jsx' --fix"
  },
  "publishConfig": {
    "registry": "http://registry.npmjs.com",
    "access": "public"
  },
  "buildConfig": {
    "theme": "@icedesign/skin",
    "entry": "src/index.js",
    "localization": false
  },
  "themeConfig": {
    "primaryColor": "#0079f2"
  },
  "scaffoldConfig": {
    "name": "ice-task-management-admin",
    "title": "ICE Task Management Admin",
    "categories": [
      "行业领域"
    ],
    "screenshot": "https://img.alicdn.com/tfs/TB1RICXdSrqK1RjSZK9XXXyypXa-2840-1580.png"
  },
  "title": "BaikalDB"
}
`

`import { defineConfig } from '@ice/app';
import { transformSync } from '@babel/core';

// The project config, see https://v3.ice.work/docs/guide/basic/config
const proxyTarget = "http://10.99.192.52:8808";
const minify = process.env.NODE_ENV === 'production' ? 'swc' : false;
export default defineConfig(() => {

    return ({
        // Set your configs here.
        minify,
        server: {
            onDemand: true,
            format: 'esm',
        },
        alias: {
            '~': './src/',
        },
        proxy: {
            '/test': {
                target: proxyTarget,
                changeOrigin: true,
                pathRewrite: { "^/test": "" },
                bypass: function (req, res, proxyOpt) {
                    // 添加 HTTP Header 标识 proxy 开启
                    res.set('X-ICE-PROXY', 'on');
                    res.set('X-ICE-PROXY-BY', proxyTarget);
                }
            },
        },
        transform: async (source, id) => {
            console.log(111);

            // 过滤条件
            if (id.match(/\.(j|t)s(x)?$/) && !id.includes('node_modules')) {
                // 借助 babel 编译
                const { code, map } = transformSync(source, {
                    plugins: ['transform-decorators-legacy'],
                });
                return { code, map };
            }
        },
        // transform: (originalCode, id) => {
        //     if (!id.includes('node_modules')) {
        //       // 借助 babel 编译
        //       const { code, map } = transformSync(originalCode, {
        //         plugins: ['transform-decorators-legacy'],
        //       });
        //       return { code, map };
        //     }
        //   },
    })
})
`

`{
    "plugins": [
        [
            "@babel/plugin-proposal-decorators",
            {
                "version": "2023-01"
            }
        ]
    ]
}`

报错› 
1。 Build failed with 1 error:                                                           scan-modules 21:44:27
src/pages/Tables/TableRegion.jsx:7:0: ERROR: JavaScript decorators are not currently supported

2. TypeError: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined

### Expected behavior

正常run

### Version of ice.js

ice 3

**Comment by ClarkXia** [comment]
类似的 case 需要提供复现的 demo，协助排查

**Comment by deshanmoon** [comment]
ice 3 如何支持装饰器语法？

**Comment by ClarkXia** [comment]
ice 3 支持装饰器语法的方式我们近期提供下

**Comment by ClarkXia** [comment]
https://github.com/alibaba/ice/blob/42718fd65dca97fc4e529e214606b1cd54c0f0d5/packages/shared-config/src/unPlugins/compilation.ts#L213
https://github.com/alibaba/ice/blob/42718fd65dca97fc4e529e214606b1cd54c0f0d5/packages/shared-config/src/unPlugins/compilation.ts#L243

框架默认支持 class decorators(stage 1)，不用额外配置，如果还有问题，提供复现代码
