### ISSUE TITLE
在windows10系统上启动项目会报错，mac上没问题

### ISSUE THREAD

**Issue by TomLilione** [alibaba/ice#6446]
### Describe the bug

![Uploading 12001691487893_.pic.jpg…]()

### Expected behavior

它不应该只在一个系统上报错，window版本10，node18，16，14都会报错，项目启动工具idea

### Version of ice.js

3.2.9

**Comment by TomLilione** [comment]
![12111691489466_ pic](https://github.com/alibaba/ice/assets/47802577/317f0cab-ea65-4d5d-b894-a12973241d40)

**Comment by TomLilione** [comment]
![12001691487893_ pic](https://github.com/alibaba/ice/assets/47802577/463a872b-909f-469e-ad1d-68e30acab39f)

**Comment by ClarkXia** [comment]
可以先尝试关闭 onDemand
