### ISSUE TITLE
自定义主题包iconfont资源能否改为依赖本地资源而非cdn，避免内网环境打包拉取不到资源

### ISSUE THREAD

**Issue by rootsli** [alibaba/ice#6447]
### Describe the bug

![image](https://github.com/alibaba/ice/assets/4099803/ab45d8ac-3e85-47ed-8bad-bcab9fdef40c)

### Expected behavior

cdn资源地址改为本地地址

### Version of ice.js

自定义主题包

**Comment by ClarkXia** [comment]
如果想在生成主题包的时候就改写那需要 fusion 自定义主题包支持，如果要本地化资源参加 https://v3.ice.work/docs/guide/advanced/css-assets-local/

**Comment by ClarkXia** [comment]
参考 https://v2.ice.work/docs/plugin/list/css-assets-local#%E5%9C%BA%E6%99%AF-2%E6%9E%84%E5%BB%BA%E9%83%A8%E7%BD%B2%E5%92%8C%E7%BD%91%E7%AB%99%E8%BF%90%E8%A1%8C%E6%97%B6%E9%83%BD%E8%AF%B7%E6%B1%82%E4%B8%8D%E5%88%B0-cdn-%E6%96%87%E4%BB%B6
