### ISSUE TITLE
Layout 不存在的容错处理

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#645]
## 环境信息

- 操作系统：
- Iceworks 版本： 

## 问题描述

新增物料源 http://g.alicdn.com/bizcharts-material/scripts/0.0.2/material-assets.json， 没有 layouts 的情况下区块合并以后出现以下截图错误

![image](https://user-images.githubusercontent.com/3995814/41636091-0b89a826-747f-11e8-806e-f7b450c00e46.png)

**Comment by noyobo** [comment]
v2.5.0 fixed
