### ISSUE TITLE
V2版本在React 18下出现版本兼容警告

### ISSUE THREAD

**Issue by kevinat** [alibaba/ice#6450]
### Describe the bug

React 18下console出现下面警告：
Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead.

### Expected behavior

希望能修改ice v2，以支持React 18

### Version of ice.js

2.6.6

**Comment by ClarkXia** [comment]
v2 版本的运行时代码没有兼容 react 18，如果期望用 react 18 的能力，建议升级下 3.0 版本

**Comment by kevinat** [comment]
3.0版变化太大了，之前项目迁移到3.0失败了，就还在用v2

**Comment by ClarkXia** [comment]
可以看下具体迁移失败的 case，如果是通用问题，我们可以提供工具支持

**Comment by kevinat** [comment]
> 可以看下具体迁移失败的 case，如果是通用问题，我们可以提供工具支持

谢谢！
还有一个主要原因是3.0不支持Fusion的多主题，请问有相关计划吗？

**Comment by ClarkXia** [comment]
css variables 形式的多主题实现相对简单，我们近期可以快速支持，历史基于 sass 编译多主题的逻辑暂时优先级会比较低

**Comment by kevinat** [comment]
> css variables 形式的多主题实现相对简单，我们近期可以快速支持，历史基于 sass 编译多主题的逻辑暂时优先级会比较低

 👍

我理解v2不会提供React 18支持了对吗？是的话我可以把issue关闭掉

**Comment by ClarkXia** [comment]
是的，推荐上还是尽量往 v3 上，v2 不做功能迭代了

**Comment by kevinat** [comment]
> 是的，推荐上还是尽量往 v3 上，v2 不做功能迭代了

好的，期待支持多主题的v3发布，我们再尝试迁移到v3
