### ISSUE TITLE
ice-scripts1

### ISSUE THREAD

**Issue by xiaodoubaoldl** [alibaba/ice#6451]
### Summary | 概述

打包报错
ERROR in js/index.js from UglifyJs
Unexpected token punc «{», expected punc «(» [js/index.js:11550,13]

### Motivation | 背景

步骤2
查看[webpack](https://so.csdn.net/so/search?q=webpack&spm=1001.2101.3001.7020)是否用uglifyjs-webpack-plugin插件

步骤3
const UglifyJsPlugin = require("uglifyjs-webpack-plugin")
换成
const TerserPlugin = require("terser-webpack-plugin");

### Usage example | 使用示例

不知道如何覆盖
uglifyjs-webpack-plugin

### Detailed design | 方案设计

``

**Comment by xiaodoubaoldl** [comment]
> ice-scripts 1.0 的版本？

是的

**Comment by xiaodoubaoldl** [comment]
> > ice-scripts 1.0 的版本？
> 
> 是的

在webpackrc.js里添加terser-webpack-plugin这个插件，覆盖不掉uglifyjs

**Comment by ClarkXia** [comment]
ice-scripts 1.0 本身定制能力较弱，无法细粒度定制，至少升级到 ice-scripts 2.x 就可以基于 webpack-chain 进行定制
