### ISSUE TITLE
使用build-plugin-keep-alive 进行组件缓存，在配置时，怎么能把缓存数据的name配置上？

### ISSUE THREAD

**Issue by wangmengdie-1** [alibaba/ice#6452]
### Describe the bug

引入keepAlive插件后，通过useAliveController中的getCachingNodes方法可以查看到缓存的组件，看到缓存的每个组件name值都是undefined。需求是：想要销毁某组件，需要调用useAliveController中的dropScope(name)方法，但是name为undefined，且无配置入口，导致我调用该事件时无法传入name，故无法销毁。
![image](https://github.com/alibaba/ice/assets/124342041/c440ae5c-e83c-4c4a-a8b8-8ec4ffa11764)
![image](https://github.com/alibaba/ice/assets/124342041/cdd98b51-ea45-450d-8b6c-f158d0674a1e)

### Expected behavior

可以动态传入keepAlive的name配置值。最好将路由path作为name值配置到keepAlive的数据中。

### Version of ice.js

2.0

**Comment by ClarkXia** [comment]
可以直接参考 https://github.com/alibaba/ice/tree/stable/2.x/packages/plugin-keep-alive
