### ISSUE TITLE
ice v3.2.9 definePageConfig 设置 title, 浏览器页面title不会显示

### ISSUE THREAD

**Issue by j787701730** [alibaba/ice#6453]
### Describe the bug

npm create ice ice-app 新建的项目, 就升级了package包 , 用的是antd组件, 浏览器是桌面Edge. 
ice v3.2.9 definePageConfig 设置 title, 页面的title 无效;
export const pageConfig = definePageConfig(() => {
  return {
    title: '成功页',
  };
});

### Expected behavior

definePageConfig 设置 title 生效

### Version of ice.js

"@ice/app": "^3.2.9"

**Comment by wssgcg1213** [comment]
未能复现你说的情况，可以提供最小 demo, 排除其它动态逻辑修改 document.title 的情况

另外, 确保你的 document 定义中包含了 <Title> 组件：
<img width="698" alt="image" src="https://github.com/alibaba/ice/assets/3922719/5419db6c-dac9-49f2-bd3e-c7774996856c">

**Comment by j787701730** [comment]
@wssgcg1213 我的document文件没改过, 是不是没在menuConfig.tsx文件中配置asideMenuConfig项, 就不会自动添加页面title, 就算配置了definePageConfig的title也是无效的.
