### ISSUE TITLE
升级icejs

### ISSUE THREAD

**Issue by xiaodoubaoldl** [alibaba/ice#6454]
### Describe the bug

jsonpFunction: `webpackJsonp_${name}`,
globalObject: 'window',

使用基于qiankun的微服务需要在webpackrc.js里配置以上两个配置项，
升级到icejs1.0以后官方推荐使用build.json文件进行配置，
但是buildjson对应的配置文档没有找到以上两项对应的配置。
未配置的情况下造成qiankun微服务刷新出现主应用崩溃的问题

`
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
`

### Expected behavior

解决方案

### Version of ice.js

1.x

### Content of build.json or ice.config.mts

```TypeScript
{
    "entry": "src/index.js",
    "plugins": [
        [
            "build-plugin-fusion", {
                "themePackage": "@icedesign/skin",
                "themeConfig": {
                    "primaryColor": "#908ce1"
                }
            }
        ],
        "./build.plugin.js"
    ],
    "devServer": {
        "headers": {
          "Access-Control-Allow-Origin": "*"
        },
        "historyApiFallback": false,
        "hot": false,
        "watchContentBase": false
      },
    "alias": {
        "@": "./src/",
        "@components": "./src/components/",
        "@comComponent": "./src/comComponent/dist/",
        "@api": "src/api/",
        "@utils": "src/utils",
        "@pages": "src/pages/"
    },
    "library": "xcosBase",
    "libraryTarget": "umd",
    "disableRuntime": true,
    "proxy": {
        "/main/**": {
          "enable": true,
          "target": "https://pre-hibo.jddj.com/",
          "headers": {
            "referer": "https://pre-hibo.jddj.com/"
          }
        },  
}
```

**Comment by ClarkXia** [comment]
没有直接开发 jsonpFunction 这种配置，可以通过插件的方式定制下 webpack 配置 https://v2.ice.work/docs/guide/basic/build#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%B7%A5%E7%A8%8B%E9%85%8D%E7%BD%AE
