### ISSUE TITLE
 ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by baibing0620** [alibaba/ice#6459]
### Describe the bug

![image](https://github.com/alibaba/ice/assets/114003336/2e0d8319-8043-42c2-bb4e-d8e8cae20f96)
微信小程序内报错
 ReferenceError: regeneratorRuntime is not defined

### Expected behavior

正常使用

### Version of ice.js

3.2.9

**Comment by wssgcg1213** [comment]
先手动引入 regenerator-runtime 看看
