### ISSUE TITLE
路由间跳转有多次重复渲染

### ISSUE THREAD

**Issue by aspirantzhang** [alibaba/ice#6461]
### Describe the bug

https://github.com/alibaba/ice/issues/6390

已升级到最新的 ice v3.2.9 依然存在问题

复现：https://codesandbox.io/p/sandbox/elated-frog-frp23r

### Expected behavior

仅一次渲染

### Version of ice.js

3.2.9

**Comment by ClarkXia** [comment]
现在是离开组件的时候，当前组件会渲染一次，这是一个 loading 态，参考
https://github.com/remix-run/react-router/blob/496b1fe8253643171ecca6e6a945d98386c4eb00/packages/router/router.ts#L1519-L1544

以及 react-router 的文档 https://reactrouter.com/en/main/hooks/use-navigation

**Comment by aspirantzhang** [comment]
哎呀妈原来还有这么个事，看来少学哪一环都不行啊。我再研究研究。
