### ISSUE TITLE
以及装完依赖包，但是项目启动报错（如下）

### ISSUE THREAD

**Issue by Juncheng-wu** [alibaba/ice#6463]
<img width="714" alt="image" src="https://github.com/alibaba/ice/assets/113349164/340cdb32-30b9-47dc-83fd-e00cb8b1b00d">

已经按照错误提示重新安装 node-sass，还是会出现同样的报错

**Comment by ClarkXia** [comment]
什么机器，node-sass 已停止维护，部分新架构的机器可以不支持 node-sass 了

**Comment by ClarkXia** [comment]
用版本锁定的方式升级下 node-sass 试试吧，目前这个 node-sass 不支持你的机器
