### ISSUE TITLE
可以嵌套动态路由吗？

### ISSUE THREAD

**Issue by honeysweetful** [alibaba/ice#6470]
### Summary | 概述

在动态路由后面再嵌套多层动态路由，而不是使用通配路由。

### Motivation | 背景

比如当前页面有一个表格，点击表格的详情根据数据id打开一个新的表格，再点击这个表格的详情，根据数据id再打开一个表格，这两个id都出现在动态路由里面（这么做面包屑导航还有效）

### Detailed design | 方案设计

需要支持动态路由嵌套

**Comment by ClarkXia** [comment]
理论上可以，可以具体描述下期望访问的链接规则

**Comment by honeysweetful** [comment]
> 类似这种：/list/:rowId/:columnId/:fieldId
例如当前路由是/list/12/13/14
此时的面包屑：列表 / 行列表 / 列列表 / 字段详情

const params = useParams(); // { rowId: 12, columnId: 13, fieldId: 14 }

**Comment by ClarkXia** [comment]
```
├── src
│ ├── pages
|  |  ├── $rowId
|  |   |  ├── $columnId.tsx
|  |  └── index.tsx
```

上述的目录结构既能支持访问 /1（对应 pages/$rowId/index.tsx）也能访问 /1/2 （对应 pages/$rowId/$columnId.tsx），如果想继续嵌套以此类推
