### ISSUE TITLE
build报错(PipeToString error, downgrade to CSR. TypeError: l is not a function)

### ISSUE THREAD

**Issue by honeysweetful** [alibaba/ice#6471]
### Describe the bug

打包出错
<img width="813" alt="2" src="https://github.com/alibaba/ice/assets/25976987/8ee466c3-d993-4c53-b1e6-4f75ea433be9">

### Expected behavior

不要报错

### Version of ice.js

v3.2.9

**Comment by ClarkXia** [comment]
提供 demo，或者开启 build 阶段的 sourcemap 继续定位
sourcemap 开启方式 https://v3.ice.work/docs/guide/basic/config#sourcemap

**Comment by honeysweetful** [comment]
demo：https://github.com/honeysweetful/ice-bug-demo-4
已经找到避免办法，项目使用了zustand，在页面home中创建了store.ts文件，把这个文件单独放到文件夹，配置路由忽略就可以了；但是不放到文件夹还是不行。建议官方处理下这种。

**Comment by honeysweetful** [comment]
demo：https://github.com/honeysweetful/ice-bug-demo-4
已经找到避免办法，项目使用了zustand，在页面home中创建了store.ts文件，把这个文件单独放到文件夹，配置路由忽略就可以了；但是不放到文件夹还是不行。建议官方处理下这种。

**Comment by ClarkXia** [comment]
参考 #6474
