### ISSUE TITLE
开启SSG时，useData()返回值永远是undefined

### ISSUE THREAD

**Issue by honeysweetful** [alibaba/ice#6473]
### Describe the bug

<img width="570" alt="3" src="https://github.com/alibaba/ice/assets/25976987/cf0b0805-d0ea-415d-8043-689309d0c4fa">

### Expected behavior

开启CSG时useData能正常工作

### Version of ice.js

v3.2.9

### Content of build.json or ice.config.mts

```TypeScript
`import { defineConfig } from '@ice/app';

// The project config, see https://v3.ice.work/docs/guide/basic/config
const minify = process.env.NODE_ENV === 'production' ? 'swc' : false;
export default defineConfig(() => ({
  // Set your configs here.
  minify,
  server: {
    onDemand: false,
    format: 'esm',
  },
  routes: {
    ignoreFiles: [
      '**/components/**', // 如果每个页面下有 components 目录存放当前页面的组件，可以通过添加此配置忽略被解析成路由组件
    ],
  },
  ssg: true,
}));`
```

**Comment by honeysweetful** [comment]
环境：nodejs16.18.0 + Windows10

**Comment by ClarkXia** [comment]
https://v3.ice.work/docs/guide/basic/ssg#ssg-%E7%9A%84%E6%95%B0%E6%8D%AE%E8%AF%B7%E6%B1%82 开启 SSG 后，配置了 dataLoader 的同时配置 staticDataLoader 试试

**Comment by honeysweetful** [comment]
> https://v3.ice.work/docs/guide/basic/ssg#ssg-%E7%9A%84%E6%95%B0%E6%8D%AE%E8%AF%B7%E6%B1%82 开启 SSG 后，配置了 dataLoader 的同时配置 staticDataLoader 试试
可以了，谢谢
