### ISSUE TITLE
提供 demo，或者开启 build 阶段的 sourcemap 继续定位

### ISSUE THREAD

**Issue by honeysweetful** [alibaba/ice#6474]
demo：https://github.com/honeysweetful/ice-bug-demo-4
已经找到避免办法，项目使用了zustand，在页面home中创建了store.ts文件，把这个文件单独放到文件夹，配置路由忽略就可以了；但是不放到文件夹还是不行。建议官方处理下这种。

**Comment by ClarkXia** [comment]
默认为约定式路由，而 store.ts 不是一个页面组件，目前只能通过路由配置的方式忽略，可以同通配的方式忽略所有 store 文件
