### ISSUE TITLE
[SSG] build时，不会调用页面的getInitialProps函数

### ISSUE THREAD

**Issue by maskTAQ** [alibaba/ice#6476]
### Describe the bug

ssg模式打包时不会触发页面组件的getInitialProps函数，导致打包出来的页面没有默认数据，seo不友好

### Expected behavior

打包时能调用getInitialProps函数，以注入默认数据

### Version of ice.js

2.6.6

**Comment by ClarkXia** [comment]
推荐升级 ice.js 3.x，有独立 API 获取 SSG 数据 https://v3.ice.work/docs/guide/basic/ssg#ssg-%E7%9A%84%E6%95%B0%E6%8D%AE%E8%AF%B7%E6%B1%82
