### ISSUE TITLE
飞冰客户端创建页面有时无反应卡死

### ISSUE THREAD

**Issue by Symous** [alibaba/ice#648]
## 环境信息

- 操作系统：macOS 10.13.5
- Iceworks 版本： 2.3.1

## 问题描述

在已有项目中，选择区块新建页面，输入路由名称等候，点击确定，无反应并且无法关闭窗口，需要强制退出一次或几次以后才可以正常新建页面。

**Comment by noyobo** [comment]
新建过程通过 npm 在下载区块并且安装依赖。这个时间可能受网络影响有些长。后面我优化把具体的信息以及进度展示出来。

**Comment by mtsee** [comment]
windows 也卡死，不是默认配置的cnpm 么。没正常使用过就算了。从没入门就放弃了~

**Comment by yujiangshui** [comment]
@mtsee 只要没报错，就在 working

**Comment by mtsee** [comment]
建议给个中途退出的选项。有时候卡住了就只有关闭整个应用，很不方便

**Comment by Symous** [comment]
不是的，据我观察在mac中确实是假死了，而不是working，因为我等了真的很久。然后不得已强制退出，再次重新进行，很快就可以了。

**Comment by sjq597** [comment]
环境信息
操作系统：Ubuntu 16.04
Iceworks 版本： Linux 2.0.0 beta

创建新页面一直卡死,不知道是网的问题还是其他问题，看不到日志，也不能取消

**Comment by noyobo** [comment]
创建页面的网络状态下个版本会实时显示出来，并可取消。

**Comment by imsobear** [comment]
已优化下载过程。
