### ISSUE TITLE
生产包下通过Link进入动态路由后，刷新页面后变成空白。

### ISSUE THREAD

**Issue by honeysweetful** [alibaba/ice#6483]
### Describe the bug

现在有一个动态路由配置/dynamic/:id/:type，生产环境通过父页面点进去，页面渲染正常，当前路由为/dynamic/12/string,但是点击刷新后，页面404；这种怎么解决？nginx好像也没法配置吧……

### Expected behavior

页面可以正常渲染

### Version of ice.js

v3.2.9

**Comment by wssgcg1213** [comment]
服务器需要返回对应 html 内容, 你需要配置一下 (比如 nginx)

**Comment by honeysweetful** [comment]
可以给个例子嘛，动态路由嵌套动态路由
