### ISSUE TITLE
在预览物料时，出现：抱歉, 编译错误： @icedesign/application-progress-block/src/index.js

### ISSUE THREAD

**Issue by Southhill** [alibaba/ice#65]
具体错误信息：抱歉, 编译错误: @icedesign/application-progress-block/src/index.js, 麻烦提交 issue 等待修复（预览进度条指向51%）
出现错误的URL：[https://alibaba.github.io/ice/#/block/584/preview](https://alibaba.github.io/ice/#/block/584/preview)

**Comment by wssgcg1213** [comment]
好的, 我们修复一下

**Comment by wssgcg1213** [comment]
https://alibaba.github.io/ice/#/block/application-progress/preview

@Southhill 现在可以访问吗?

**Comment by Southhill** [comment]
@wssgcg1213 Chrome浏览器是可以正常显示的，但火狐浏览器显示还是同样的问题（Edge浏览器也是这样的问题，私认为不是火狐插件的问题）。控制台有如下的报错信息：

![火狐报错信息截图](https://user-images.githubusercontent.com/7621504/35685614-2e042832-07a5-11e8-83f4-63d0dd6a9331.png)

**Comment by wssgcg1213** [comment]
OK, 高估了火狐的兼容性  我调试一下看看
