### ISSUE TITLE
[QUESTION]跨目录引用提示`Can't resolve '@ice/runtime/jsx-dev-runtime'`

### ISSUE THREAD

**Issue by xmsz-stu** [alibaba/ice#6506]
背景
- 比如引用 ../../1.tsx(在项目目录外) 或者 shared/1.tsx（repo项目）都会出现

需求
- 如何解决

**Comment by ClarkXia** [comment]
怎么会有跨项目引用的场景呢？

**Comment by xmsz-stu** [comment]
> 怎么会有跨项目引用的场景呢？

比如使用monorepo的时候

**Comment by ClarkXia** [comment]
关注下执行目录下是否安装了 @ice/runtime

**Comment by xmsz-stu** [comment]
我重新试了一下 通了 不确定哪个环节的
等下次遇到我再补充
