### ISSUE TITLE
不支持插件多实例

### ISSUE THREAD

**Issue by tony3212** [alibaba/ice#6512]
### Describe the bug
在 webpack 中可以多次实例化new HtmlWebpackPlugin({...}),但是在飞冰中实现不了

### Expected behavior

可以多次实例化new HtmlWebpackPlugin({...})

### Version of ice.js
2.6.0

**Comment by ClarkXia** [comment]
提供更多有效的信息，比如 Version of ice.js
ice.js 3.x 版本的页面渲染通过执行 document 的方式输出，不需要使用 HtmlWebpackPlugin

**Comment by tony3212** [comment]
只是说明要多实例的情况，例如我要多次使用webpack.DllReferencePlugin({})的情况

>
