### ISSUE TITLE
本地项目运行时视频（mp4）文件如何加载？

### ISSUE THREAD

**Issue by ChrisXYF** [alibaba/ice#6515]
### Summary | 概述

官方提供了这些资源的方式
![image](https://github.com/alibaba/ice/assets/38465558/c7ac5622-df51-4323-bb87-9db7a128dc2d)
但是，如果要引用视频，直接写视频路径会加载不出来，用import引用会出错误，请问该怎么解决
![image](https://github.com/alibaba/ice/assets/38465558/2bc9b2f8-b26f-4e19-b5d5-0350c2279005)

### Motivation | 背景

视频引用问题

### Detailed design | 方案设计

需要提供除http引用外的本地加载视频的方案

**Comment by Bingjiajia** [comment]
你是如何修复的
