### ISSUE TITLE
ICE 3 CSS 分包策略失效

### ISSUE THREAD

**Issue by Mr-TNF** [alibaba/ice#6523]
### Describe the bug

{
  splitChunks: true,
  codeSplitting: 'page-vendors',
}

配置了上述属性，依旧把所有的css打进一个文件里

### Expected behavior

期望根据页面打成不同的css js

### Version of ice.js

3.3.0

**Comment by ClarkXia** [comment]
需要提供复现项目，另外只需要配置 codeSplitting 即可

**Comment by ClarkXia** [comment]
提供复现 demo 后重开 issue
