### ISSUE TITLE
url 对象不存在导致 PHA 插件 start 阶段挂掉了

### ISSUE THREAD

**Issue by answershuto** [alibaba/ice#6524]
### Describe the bug

![image](https://github.com/alibaba/ice/assets/17812136/2e99916f-7e8c-463f-aa87-94a6035c9b30)

### Expected behavior

url 对象不存在导致 PHA 插件 start 阶段挂掉了
before start

### Version of ice.js

3.3.1

**Comment by wssgcg1213** [comment]
什么情况下可以复现这个异常

**Comment by answershuto** [comment]
> 什么情况下可以复现这个异常

啥情况下都可以复现 =。= ice 前阵子版本改动导致的
