### ISSUE TITLE
ssr/csr 逻辑执行顺序不一致

### ISSUE THREAD

**Issue by HomyeeKing** [alibaba/ice#6535]
### Describe the bug

ssr下：
![image](https://github.com/alibaba/ice/assets/49113249/f95ed132-b966-4b4e-855e-b48d5bdf9b1c)

csr下：
![image](https://github.com/alibaba/ice/assets/49113249/125ac333-0472-4b2c-9499-0882864eaea3)

### Expected behavior

期望执行顺序保持一致，

应该是 `app.ts > document dataloader >  app dataloader >  page dataloader`
也就是按照当前ssr的执行顺序为准

### Version of ice.js

@ice/app@3.3.1 @ice/runtime@1.2.9

### Additional context

reproduce repo https://github.com/HomyeeKing/ice-repro/tree/dataloader

**Comment by ClarkXia** [comment]
默认情况下 data-loader 请求在 CSR 阶段会独立打出 bundle 并前置，如果特定场景下需要保证执行顺序，可以在 ice.config.mts 中关闭独立打出 bundle 的配置，设置 `dataLoader: false`
