### ISSUE TITLE
public下存在png文件时候就会报错

### ISSUE THREAD

**Issue by WenDaaa** [alibaba/ice#6542]
### Describe the bug

![image](https://github.com/alibaba/ice/assets/44088914/b508e787-320d-4ea9-b265-4d6fcc30c603)
默认第一个图片会提示error，将第一个移除提示的error就变成了第二个png图片，但是不影响程序运行。

### Expected behavior

public下的存在png文件无报错

### Actual behavior

运行完成以后就会提示一个error显示pubilc下的png文件is not in cwd，

### Version of ice.js

2.6.6

### Additional context

同事的mac下无显示问题 感觉跟这个issue的问题类似[6514](https://github.com/alibaba/ice/issues/6514)

**Comment by WenDaaa** [comment]
不确定是不是路径的原因导致的 错误信息前面的是/来区分的 后面的是\来区分的

**Comment by ClarkXia** [comment]
> 不确定是不是路径的原因导致的 错误信息前面的是/来区分的 后面的是\来区分的

可以先排除中文目录的影响

**Comment by WenDaaa** [comment]
> > 不确定是不是路径的原因导致的 错误信息前面的是/来区分的 后面的是\来区分的
> 
> 可以先排除中文目录的影响

牛蛙牛蛙 老哥 才发现我把目录放在桌面了 ，移到其他的盘就ok了
