### ISSUE TITLE
配置了https和host后，终端里显示的地址和自动打开的页面地址和配置不一致

### ISSUE THREAD

**Issue by anyuxuan** [alibaba/ice#6551]
### Describe the bug

配置：
- server: https 
- host: 0.0.0.0
<img width="310" alt="image" src="https://github.com/alibaba/ice/assets/24931869/daeea991-8508-467b-995f-e43d75b5cb55">

终端显示的地址和自动打开的页面地址是：
<img width="635" alt="image" src="https://github.com/alibaba/ice/assets/24931869/b130a939-b17d-4154-a838-b151c8cb4e46">

### Expected behavior

期望终端显示地址和自动打开页面地址是：https://0.0.0.0:4000

### Version of ice.js

1.5.13

**Comment by ClarkXia** [comment]
ice-pkg 问题提到 https://github.com/ice-lab/icepkg/issues
