### ISSUE TITLE
约定式路由中如何优雅地为登录页和注册页使用独立的布局组件?

### ISSUE THREAD

**Issue by ochive** [alibaba/ice#6557]
我现在的写法是在默认的全局layout.tsx中添加跳转代码.

```tsx
  if (['/session/login'].includes(location.pathname)) {
    return (
      <ConfigProvider
        locale={locale}
        theme={{
          algorithm: theme.defaultAlgorithm,
          token: {
            colorPrimary: '#00b96b',
          },
          components: {},
        }}
      >
        <App>
          <Outlet />
        </App>
      </ConfigProvider>
    );
  }
```

现在准备将登陆页和注册页放一个目录里, 给他们单独使用一个layout. 
有没有优雅的办法, 让这个layout不走全局layout走?
同时让这个专用layout能享受到全局layout中配置的国际化, 主题等设置?

**Comment by ClarkXia** [comment]
推荐上是约定式，比如 /session/register/index.tsx /session/register/layout.tsx

如果 session 路由下有些需要 Layout，有些又不需要的话，且路由数量较多的情况下，解决方案跟 issue 中的类似，通过路由地址判断渲染 Layout，具体代码实践上可以将多种 Layout（包括 Provider）封装成组件，在一个全局 Layout 下分发

PS：同一个路由前缀下还是推荐统一的 Layout，可以考虑规划下路由地址
