### ISSUE TITLE
配置devPublicPath后，访问不了public目录下的文件

### ISSUE THREAD

**Issue by wulianpu** [alibaba/ice#6561]
### Describe the bug

通过devPublicPath配置前缀后，并通过前缀访问public目录下的文件，显示404。
去掉前缀，直接访问public目录下的文件，显示成功。

我不确定是这样设计的还是忘记考虑这块了，麻烦大佬们回复一下！！！

### Version of ice.js

3.2.10

**Comment by ClarkXia** [comment]
[devPublicPath](https://v3.ice.work/docs/guide/basic/config/#publicpath) 等同于 webpack 下配置 output.publicPath 只不过仅在 dev 阶段生效，即只影响 js / css 等打包资源的输出位置。

如果有对应 public 目录访问地址定制的需要，可以另提一个 issue 说明使用场景
