### ISSUE TITLE
微前端 unmount 失效

### ISSUE THREAD

**Issue by AlbertXiao1994** [alibaba/ice#6570]
### Describe the bug

![image](https://github.com/alibaba/ice/assets/23646755/7c4aaac6-849d-42e5-94b8-f054fbefd4a1)

微前端卸载时会执行 .ice/entry.client.tsx 文件里的 unmount 方法。但是由于 render 方法没有返回值，导致 root 永远为 undefined。也就是说，unmount 方法里的 root?.then((res) => res.unmount()) 永远不会执行

### Expected behavior

`
// 现有实现
const render = (customOptions: Partial<RunClientAppOptions> = {}) => {
  renderApp(app, customOptions);
};

// 期望实现
const render = (customOptions: Partial<RunClientAppOptions> = {}) => {
  // 返回 root
  return renderApp(app, customOptions);
};
`

### Version of ice.js

3.3.3

**Comment by ClarkXia** [comment]
fixed in 3.3.4
