### ISSUE TITLE
请问在ice3里如何正确配置fallback？

### ISSUE THREAD

**Issue by lilithyang2018** [alibaba/ice#6573]
@ClarkXia 请问在ice3里如何正确配置fallback？
在ice.config.mts里配置如下
![webpack](https://github.com/alibaba/ice/assets/39897706/0d679350-112e-4ed0-b14a-57c6723c8f4d)
启动时会报如下错误
![resolve](https://github.com/alibaba/ice/assets/39897706/0920b155-1fe4-48fe-860e-115bfeec7056)
如果使用@ice/webpack-config，又该如何配置呢

_Originally posted by @lilithyang2018 in https://github.com/alibaba/ice/issues/5271#issuecomment-1754599534_

**Comment by ClarkXia** [comment]
这个情况可以有两种配置策略：
1. 直接配置 alias
```js
import { defineConfig } from '@ice/app';

export default defineConfig(() => ({
  alias: {
    'crypto': 'crypto-browserify',
  },
}));
```

表现为 server 端和 client 端的 crypto 都指向 crypto-browserify

2. 配置 fallback

```js
import { defineConfig } from '@ice/app';

export default defineConfig(() => ({
  webpack: (config) => {
    // @ts-ignore
    config.resolve.fallback = {
      ...(config.resolve?.fallback || {}),
      crypto: 'crypto-browserify',
    };
    return config;
  }
}));
```

server 端存在 crypto 时直接使用， client 端打包是 fallback 到 crypto-browserify


目前第二种配置有预编译问题，已修复待发布

**Comment by lilithyang2018** [comment]
@ClarkXia  请问对于buffer的话要如何polyfill？使用下面的自定义插件 配合 alias ，仍然会得到Buffer is not defined
`import * as path from 'path';
import type { Plugin } from '@ice/app/types';
import pkg from 'webpack';
const { ProvidePlugin } = pkg;

interface PluginOptions {
    [key: string]: string;
}

const plugin: Plugin<PluginOptions> = () => ({
    name: '@ice/plugin-webpack',
    setup: ({ onGetConfig }) => {
        onGetConfig((config) => {
            config.configureWebpack ??= [];
            config.configureWebpack.push((webpackConfig) => {
                // eslint-disable-next-line @typescript-eslint/ban-ts-comment
                // @ts-ignore
                webpackConfig.plugins?.push(new ProvidePlugin({
                    Buffer: ['buffer', 'Buffer'],
                }));
                return webpackConfig;
            });
        });
    },
    runtime: path.join(__dirname, 'runtime.tsx'),
});

export default plugin;`

**Comment by ClarkXia** [comment]
Buffer 的配置比较特殊
1. 配置 fallback
```js
config.resolve.fallback = {
  ...(config.resolve?.fallback || {}),
  Buffer: require.resolve('buffer'),
}
```
3. 配置 ProvidePlugin

```js
config.plugins?.push(new ProvidePlugin({
    Buffer: ['buffer', 'Buffer'],
}));
```
