### ISSUE TITLE
请问类似于app.tsx或者index.tsx的程序入口在哪里?

### ISSUE THREAD

**Issue by ochive** [alibaba/ice#6583]
需要在程序入口里配置UI库的ConfigProvider

app.ts不是jsx, 没办法配置组件.

目前是在全局布局组件里， 在ProLayout外套了层壳完成这个工作的。

**Comment by ClarkXia** [comment]
Provider 的诉求，目前的确是推荐通过全局布局组件处理的 https://v3.ice.work/docs/guide/basic/router#%E5%B8%83%E5%B1%80%E7%BB%84%E4%BB%B6
