### ISSUE TITLE
DataBinder支持使用自定义的ajax

### ISSUE THREAD

**Issue by 2goyoung** [alibaba/ice#659]
由于项目对ajax模块进行了统一配置和通用处理的封装，希望DataBinder可以使用自定义的ajax模块，实现类似下面的代码：
```javascript
import DataBinder from '@icedesign/data-binder';
import api from 'src@/api';

@DataBinder({
  demo: {
    ajax(params) {
      return api.order.getList(params); // 返回一个Promise对象
    },
    data: {
      index: 0,
      length: 20
    },
    ...
  }
})
```

**Comment by noyobo** [comment]
这个需求有点特殊，DataBinder 根据一定的数据格式来完成。如果可更改 ajax， 接口返回的数据格式需要按一定格式，你封装的模块格式应该也存在区别。

**Comment by 2goyoung** [comment]
@noyobo 其实，我想要的是可以定义 (0, _axios2.default)(_extends({}, newRequestOptions)) 这一段，最后也是返回一个Promise ，responseFormatter依然可以格式化数据。
从设计上DataBinder通过配置url就可以发送异步请求这确实挺方便，但每个项目基本都会有一个ajax方案，可能是axios，也可能不是，或者将来更优秀的方案，会出现冗余的情况；对于数据交互可能是ajax，也可能是Electron开发时用到I/O获取数据或者读取数据库，如果DataBinder去掉axios，只做异步托管和回调处理，那么DataBinder的使用场景更广，希望可以提供一个无axios版的DataBinder。

**Comment by wssgcg1213** [comment]
理解你说的, 数据获取的方法可以抽象, 不仅仅是 ajax 也可能走ws, 走其它rpc方式;  
databinder 会加一个参数允许自定义请求方法, 作为高级用法, 时间上尽量本周 @2goyoung
