### ISSUE TITLE
webpack --watch

### ISSUE THREAD

**Issue by yunliang-ding** [alibaba/ice#6595]
使用 icejs2.x 如何能够实现类似 webpack --watch 只对代码实时监听编译到内存即可，不启动服务

**Comment by ClarkXia** [comment]
icejs 2.x 不支持，如果是 3.x 版本，可以通过插件定制 useDevServer 为 false 即可

```js
const plugin = () => ({
  setup: ({ onGetConfig }) => {
    onGetConfig((config) => { config.useDevServer = false })
  },
})
export default plugin;
```

插件开发文档：https://v3.ice.work/docs/guide/plugins/plugin-dev/#ongetconfig

**Comment by yunliang-ding** [comment]
> icejs 2.x 不支持，如果是 3.x 版本，可以通过插件定制 useDevServer 为 false 即可
> 
> ```js
> const plugin = () => ({
>   setup: ({ onGetConfig }) => {
>     onGetConfig((config) => { config.useDevServer = false })
>   },
> })
> export default plugin;
> ```
> 
> 插件开发文档：https://v3.ice.work/docs/guide/plugins/plugin-dev/#ongetconfig

你好，我升级到ice3.x，之后按照配置插件的形式不开启useDevServer，但是运行 npm start 之后，还是3000端口服务启动了服务

**Comment by yunliang-ding** [comment]
> icejs 2.x 不支持，如果是 3.x 版本，可以通过插件定制 useDevServer 为 false 即可
> 
> ```js
> const plugin = () => ({
>   setup: ({ onGetConfig }) => {
>     onGetConfig((config) => { config.useDevServer = false })
>   },
> })
> export default plugin;
> ```
> 
> 插件开发文档：https://v3.ice.work/docs/guide/plugins/plugin-dev/#ongetconfig

你好，我按照开发文档，尝试升级到3.x之后，在插件配置里面关闭了useDevServer，但是npm start 之后还是 启动了 3000端口，还需要额外的配置嘛，去实现 webpack --watch 的功能
