### ISSUE TITLE
功能改进的一个建议

### ISSUE THREAD

**Issue by fangkyi03** [alibaba/ice#660]
希望增加的功能
1.使用git地址来生成模板 如提供一个自己项目的git地址 直接clone下来 并且支持安装对应的package文件等
2.保持现有ice的区块 布局等功能 但是仅仅只是在自身目录下创建出来对应的布局文件 方便在原有项目中直接进行引入
3.支持直接将当前项目中的组件文件直接添加到ice中 并且可以直接提交到自己公司的git项目中 这样会方便很多 或者可以改成可以在ice中新建一个组件组 提供添加git地址 然后将自己项目中的文件直接添加进去并做详细说明 如组件备注 组件截图等 然后整合一下 直接提交到自己公司的git地址上 这样所有的项目都可以共用一个了
4.提供对typescript的支持 现在用ts的项目也越来越多了 如果可以兼容ts最好不过了 如果需要js的话也可以直接用ts进行转换 两不耽误

**Comment by noyobo** [comment]
不是必须强制使用我们的模板，区块的生成是需要一定规则的。 例如你看到的 `menuConfig.js` `routerConfig.js` `src/pages/xxx` 等，基于一定的条件来生成。 我想你以前的项目并不是这样的。  

关于这个规则是怎样的，目前是一套固定的规则。规则的定制目前正在开发，未来你对你的项目定义了规则即可在 Iceworks 里使用。

关于 git clone、提交区块、这些需求未来可能会做，暂不是目前的重点。

ts 语法支持，可以作为一个扩展，近期我考虑下。

**Comment by fangkyi03** [comment]
我希望的是 只保留你这个ice可以直接拖放生成的部分 其他的依旧使用原来项目的 同时我可以将我自己写的东西也直接放到ice里面变成区块等东西 这样 我可以变成一个单独的库 以后有其他项目的时候 也可以直接拿过来用 因为我们现在的项目是用ts写的 根本不可能直接就用你这种来开发 你要多考虑一下 我们这种前期不是用ice开发的人

**Comment by noyobo** [comment]
你说的这个链路就是自定义物料 <https://alibaba.github.io/ice/docs/materials/custom-react-materials>

你可以先看下，自定义的你用 ts 写也可以。

**Comment by fangkyi03** [comment]
ice-devtools这个东西 我用npm全局安装以后 init没问题 但是只要add依旧就直接奔溃 试了多次都如此

**Comment by fangkyi03** [comment]
我希望可以直接在ice work中图形化的方式来维护本地的物料 也可以直接支持导入本地项目文件等 这样更加可视化

**Comment by chenbin92** [comment]
@fangkyi03 看了你的一些建议很不错，ice-devtools 是可以基于你本地的模板进行开发的，另外，你说的 add 之后报错具体是什么，可以贴一下你的错误信息或者加入飞冰答疑群联系我

**Comment by fangkyi03** [comment]
什么时候能把ice work开源一下呢

**Comment by fangkyi03** [comment]
![image](https://user-images.githubusercontent.com/30390014/41810572-7a76d554-7733-11e8-8bdf-4b893d85540f.png)

**Comment by fangkyi03** [comment]
其次 为啥要叫ice-devtools这么长的名字 直接ice init  ice add这样不是更爽吗

**Comment by chenbin92** [comment]
Iceworks 开源在计划中，稳定后会开源。 目前有 ice-scripts 对应 `ice` 命令，ice-devtools 对应开发者工具，两者使用场景不一样，如果使用起来觉得长，建议自定义配置一个 `alias`

**Comment by fangkyi03** [comment]
建议iceworks在开源的时候 将现有的生成逻辑抽离出来一版 这样可以更加的自定义
1.一个版本是完全用ice开发的 包括打包什么的都必须用ice的逻辑
2.另一个版本是把模板 区块 生成部分独立出来 但是没有ice的打包逻辑 可以遍历package来获取原有script的命令来生成 ice只做库管理以及视图管理的工作 这样会更加友好一点 不然其他原有项目迁移是个大问题

**Comment by fangkyi03** [comment]
如果你们那边开源这个要很久的话 我都打算我自己基于electron写一个了
我打算把网络请求什么的 都一块加进去 这一块我目前还想思考
不过核心还是围绕这个工具只是辅助开发用的 没有像现在ice那么强制的必须要按照某个规范去开发
可以自由控制写的东西是开源还是私有 可以直接在里面搜索别人写好的东西 并且直接可视化操作等等
能说一下大概的开源时间吗

**Comment by noyobo** [comment]
启动和构建都是调用 npm start 和 npm run build 并不是必须使用 ice  的打包。

添加区块的是需要一定规则，这个自定义的过程已在开发中预计7月初发布。

开源时间预计 9 月。

**Comment by fangkyi03** [comment]
11月了 ide有开源打算吗
