### ISSUE TITLE
如何提前加载设置了lazy引入的文件

### ISSUE THREAD

**Issue by Sharang-heng** [alibaba/ice#6614]
### Describe the bug

const MapDetail = lazy(() => import(/* webpackChunkName: 'MapDetail' */'@/pages/DataMap'));
使用了lazy的路由引用方式，切换到该路由时用户有明显的loading等待时间，体验不好

### Expected behavior

希望通过某种方式在浏览器空闲时提前加载这块资源，降低因懒加载带来的页面等待时间

### Version of ice.js

2.6.6

**Comment by ClarkXia** [comment]
ice.js 3 下，默认会生成 asset-mainfest.json，可以知道对应访问路径下所有的资源信息
