### ISSUE TITLE
基于微框架集成应用时，子应用切换主题变量会被清除掉，并且出现闪现问题

### ISSUE THREAD

**Issue by rootsli** [alibaba/ice#6620]
例如基于微框架集成应用，主题切换到了主题A，但切换子应用时，子应用加载默认会再执行一遍changeTheme('主题B')[在应用配置里，主题B被设置为默认主题]，如果业务代码再手动运行changeTheme('主题A')会出现主题闪现切换效果。

请问这个要如何处理？

另，从子应用A(基于icejs的react应用)切换到子应用B（vue应用），发现css var会被清除掉，这个有解决方案吗？

**Comment by rootsli** [comment]
@ClarkXia

**Comment by ClarkXia** [comment]
changeTheme 的逻辑如果自己控制是不是就可以了，另外推荐统一的控制逻辑都放在主应用

**Comment by MarshalShan** [comment]
也遇到同样的问题，使用场景：

**Comment by rootsli** [comment]
> changeTheme 的逻辑如果自己控制是不是就可以了，另外推荐统一的控制逻辑都放在主应用

@ClarkXia 好像不行，动态注入的主题变量在切换应用时会被清除掉，在载入新应用时才会再次设置，从清除到再设置之间的空隙会取不到css var导致页面颜色闪现。除非框架切换子应用时，注入的css var不被清除才行~

**Comment by ClarkXia** [comment]
@rootsli 可以通过 API 控制下 css var 不被清除
