### ISSUE TITLE
build-plugin-fusion@0.1.23 构建icon乱码

### ISSUE THREAD

**Issue by renkexin21** [alibaba/ice#6623]
### Describe the bug

使用build-plugin-fusion构建，主题中unicode大于\uffff 的icon乱码。

### Expected behavior

```
.next-icon-shouqi:before {
  content: '\e650';
}
.next-icon-subfolder:before {
  content: '\12655';
}
.next-icon-t2s-logo:before {
  content: '\e62c';
}
.next-icon-test:before {
  content: '\124F5';
}
```

### Actual behavior

```
.next-icon-shouqi:before {
  content: '\e650';
}
.next-icon-subfolder:before {
  content: '𒙕';
}
.next-icon-t2s-logo:before {
  content: '\e62c';
}
.next-icon-test:before {
  content: '𒓵';
}
```

### Version of ice.js

无

**Comment by ClarkXia** [comment]
最好提供复现 demo

**Comment by renkexin21** [comment]
抱歉，忘记贴图了。这个是build-plugin-fusion的处理逻辑
![8A3ABED3-D4C3-4CAB-A929-594785062074](https://github.com/alibaba/ice/assets/48679837/ff55efbe-b663-4119-a6ef-29cb5c962664)

复现demo如果还需要的话，我晚点再提供。谢谢。

**Comment by ClarkXia** [comment]
最好有 demo 提供，乱码一般由页面编码导致

**Comment by renkexin21** [comment]
内网demo地址：https://code.alibaba-inc.com/renkexin.rkx/icon-build-demo。
您申请下仓库访问权限，谢谢

**Comment by ClarkXia** [comment]
可以参考 build-plugin-fusion 中 unicodeLoader 的处理方式，看是否还可以复现
