### ISSUE TITLE
vite 打包时问题

### ISSUE THREAD

**Issue by wx9999** [alibaba/ice#6629]
### Describe the bug

<img width="1078" alt="image" src="https://github.com/alibaba/ice/assets/42061047/2688b8db-34e4-4be9-842e-51820227bae7">

### Expected behavior

请问有什么配置可以屏蔽这些显示

### Version of ice.js

2.0.0

**Comment by ClarkXia** [comment]
考虑配置下 vite 的 logLevel 选项
