### ISSUE TITLE
热更新缓存文件无限变大

### ISSUE THREAD

**Issue by WenDaaa** [alibaba/ice#6630]
### Describe the bug

node_modules/.cache/web_development/下存在大量的.pack文件，每次热更新的时候就无限慢慢会增大，从刚开始的1g已经长到了60g，删除后无任何影响。
![image](https://github.com/alibaba/ice/assets/44088914/71394973-502a-4e9d-b2bd-2219fd8baf2e)

### Expected behavior

感觉可能是webpack5的cache的配置filesystem导致的，但是不知道怎么去配置他，希望不要这样无限制的一直增量。

### Version of ice.js

2.6.6

### Content of build.json or ice.config.mts

```TypeScript
module.exports = {
  publicPath,
  devPublicPath: `${packageInfo.appEntry}/`, // 本机服务 基座调试时使用
  browserslist: {
    chrome: 49,
    ie: 11
  },
  define: {

  },
  sourceMap: NODE_ENV === 'development',
  postcssrc: true,
  hash: 'contenthash',
  plugins: [
    [
      'build-plugin-icestark',
      {
        type: 'child'
      }
    ],
    [
      'build-plugin-antd',
      {
        themeConfig: {
          disableModularImport: true,
          'primary-color': '#1890ff',
          'root-entry-name': 'variable'
        }
      }
    ],
    './build.plugin.js'
  ],
  modeConfig: {
    // 本地开发
    local: {
      proxy: {

      }
    }
  }
};
```

**Comment by ClarkXia** [comment]
理论上不会无限增大，在 build.json 配置变化后，旧缓存将会失效

**Comment by WenDaaa** [comment]
> 理论上不会无限增大，在 build.json 配置变化后，旧缓存将会失效

![image](https://github.com/alibaba/ice/assets/44088914/26c254ed-45da-47ca-8bbc-c90e6448908b)
额 就挺奇怪的目前基本上每次保存后热更新就会出现 昨晚刚删除的 今天就已经有4个g了 是不是需要设置缓存保留时间之类的

**Comment by ClarkXia** [comment]
看是否可以提供个复现路径或者 demo，目前复现的结果是虽然尺寸也比较大，但多次编译不会无限制增加

**Comment by aspirantzhang** [comment]
![image](https://github.com/alibaba/ice/assets/24559988/5b44833e-ed35-4814-80bb-62b1bd71e95d)
有点意思啊，我这个最早的还有9月份的，但总体很小，才2.5G

**Comment by WenDaaa** [comment]
> 看是否可以提供个复现路径或者 demo，目前复现的结果是虽然尺寸也比较大，但多次编译不会无限制增加

这东西在沙盒上不太好弄啊 我本地把业务代码删干净了以后，去尝试复现，发现他并不是每次热更新都会生成，感觉生成的时机有点随机。

**Comment by WenDaaa** [comment]
> ![image](https://user-images.githubusercontent.com/24559988/280975003-5b44833e-ed35-4814-80bb-62b1bd71e95d.png) 有点意思啊，我这个最早的还有9月份的，但总体很小，才2.5G

我这几个小伙伴一起开发的，看了下每个人的cache都是有几十个g，基本上10来分钟都会生成一个，而且每个文件的均值都相对较大

**Comment by aiqin-bao** [comment]
ice如果在每次启动的时候不使用缓存啊 ？

**Comment by ClarkXia** [comment]
> ice如果在每次启动的时候不使用缓存啊 ？

npm start -- --force

**Comment by WenDaaa** [comment]
按照这个解决了 hash: process.env.NODE_ENV === 'production' ? 'contenthash' : false [https://github.com/alibaba/ice/issues/5241](url)

**Comment by aspirantzhang** [comment]
看了一眼，5G了，果然越来越大，这么配置不错，有帮助了
