### ISSUE TITLE
怎么能不让生成entry.server.ts文件

### ISSUE THREAD

**Issue by lirongfei123** [alibaba/ice#6636]
### Describe the bug

我不需要服务端构建这些能力，ssg，ssr都设置成false了，但是还是会生成这个文件，占用很多电脑资源

### Expected behavior

提供选项禁止生成这个文件

### Version of ice.js

3.0

**Comment by ClarkXia** [comment]
entry.server.ts 的生成理论上不会占用过多资源，即便 SSR 和 SSG 关闭，这个入口还需要用于将 document.tsx 解析并生成 html，后续我们考虑下纯 CSR 的 bundle 输出模式
