### ISSUE TITLE
vite 模式下使用 KeepAlive 后报错

### ISSUE THREAD

**Issue by wx9999** [alibaba/ice#6639]
### Describe the bug

<img width="882" alt="image" src="https://github.com/alibaba/ice/assets/42061047/e4884ce4-113f-4d2d-945f-db142306ac19">
遇到报错
<img width="503" alt="image" src="https://github.com/alibaba/ice/assets/42061047/33786fb6-7c99-43b2-ab11-04139a9b4e32">

### Expected behavior

应该如何操作呢

### Version of ice.js

2.6.6

**Comment by ClarkXia** [comment]
从描述上看不出问题， vite 模式可以考虑先切回 webpack 看还能不能复现，最好提供下 demo

**Comment by wx9999** [comment]
> 从描述上看不出问题， vite 模式可以考虑先切回 webpack 看还能不能复现，最好提供下 demo

import { lazy, useLocation } from 'ice';
import { nanoid } from 'nanoid';
import KeepAlive, { withAliveScope, useAliveController, AliveScope } from 'react-activation'
import Layout from '@/Layouts/BasicLayout';
import MyClueList from '@/pages/customer/mycluelist'

const routerConfig = [
 
  {
    path: '/',
    component: Layout,
    children: [
      {
        path: '/my_clue_list',
        exact: true,
        component: MyClueList,
        keepAlive: true,
        pageConfig: {
          title: '我的线索'
        }
      },
    ],
  },
];

const RouterConfig = (router) => {
  // 加上KeepAlive
  const result = [];
  router.forEach((item) => {
    if (item.keepAlive) {
      item.component = <KeepAlive id={nanoid()} name={item.path} key={item.path}>{item.component}</KeepAlive>
    }
    if (item.children) {
      item.children = RouterConfig(item.children);
    }
    result.push(item);

  });
  return result;
};

export default RouterConfig(routerConfig);

**Comment by wx9999** [comment]
webpack 同样跑不起来

**Comment by ClarkXia** [comment]
看下具体错误，如果是运行时的问题需要看下 react-activation 的用法

**Comment by ClarkXia** [comment]
先通过 react-activation 的使用排查，keepAlive 是运行时逻辑，跟工程构建没太大关系
