### ISSUE TITLE
yarn start热更新很慢，如何优化呢。

### ISSUE THREAD

**Issue by anyone0034** [alibaba/ice#6640]
### Describe the bug

yarn start热更新很慢，如何优化呢。启动需要几分钟，每次热更新 ，都需要响应10秒，有时20多秒。

### Expected behavior

尽量能缩短热更新的时间。

### Version of ice.js

^3.2.10

### Content of build.json or ice.config.mts

```TypeScript
export default defineConfig(() => ({
    devPublicPath: '/',
    hash: 'contenthash',
    ssg: false,
    // minify,
    plugins: [
        request(),
        store(),
        auth(),
        antd({
            importStyle: true,
        }),

    ],

    server: {
        onDemand: true,
        format: 'esm',
    },

    dropLogLevel: 'log',
    codeSplitting: 'page',
   

    webpack: (webpackConfig) => {

        return webpackConfig;
    },
    // sourceMap:false,
}));
```

### Additional context

![image](https://github.com/alibaba/ice/assets/15609924/796708af-af2c-45bb-8d14-3025cb8b279c)

**Comment by ClarkXia** [comment]
参考 https://github.com/alibaba/ice/blob/1e1b543506eaaa9291521ef93458b4ce326422d6/examples/basic-project/ice.config.mts#L33-L37

观察下耗时久的任务

**Comment by yyyyffqqqq** [comment]
我的也遇到这个问题，热更新慢而且多次热更新以后，程序就会挂掉，需要重启

**Comment by yyyyffqqqq** [comment]
<img width="450" alt="截屏2023-11-20 15 35 01" src="https://github.com/alibaba/ice/assets/19225441/862844e9-6f8c-48fa-bd04-a58ff5dc3b92">

**Comment by yyyyffqqqq** [comment]
minify: process.env.NODE_ENV === 'production' ? 'swc' : false,

**Comment by yyyyffqqqq** [comment]
ice.config.mts

**Comment by yyyyffqqqq** [comment]
ice.config.mts文件中配置minify: process.env.NODE_ENV === 'production' ? 'swc' : false，热更新慢的问题可以解决

**Comment by ClarkXia** [comment]
dev 默认情况下 应该不压缩的

**Comment by larryspace** [comment]
同样的问题，随着路由增加，速度越来越慢

**Comment by anyone0034** [comment]
> dev 默认情况下 应该不压缩的，关注下压缩配置项是不是默认被开启成 true 如果还有问题，可以提供复现的 demo

用的是默认的demo，什么配置都没有修改，热更新慢，不知道问题原因。

1 npm create ice ice-app_demo
2 cd .\ice-app_demo\
3 yarn
4 yarn start
yarn run v1.22.19
warning package.json: No license field
$ ice start --speedup
√ web compiled successfully in 83557 ms                                                        
                                                                             
 Starting the development server at:

    - Local  : http://localhost:3000/
    - Network: http://192.168.0.33:3000/

√ web compiled successfully in 23206 ms                                                                                        
√ web compiled successfully in 18523 ms                                                                                            
√ web compiled successfully in 19039 ms
