### ISSUE TITLE
离线化构建项目以后，在windows下打包时候资源路径用的右斜杠，导致找不到路径

### ISSUE THREAD

**Issue by kbiao** [alibaba/ice#665]
## 环境信息

- 操作系统： win 10
- Iceworks 版本： 2.3.1

## 问题描述

参考https://github.com/alibaba/ice/wiki/%E7%A6%BB%E7%BA%BF%E5%8C%96%E6%9E%84%E5%BB%BA%E9%A1%B9%E7%9B%AE

离线化构建项目以后，在windows下打包时候资源路径用的右斜杠，导致找不到路径。

## 错误信息

![image](https://user-images.githubusercontent.com/13586915/41830433-aec60942-7873-11e8-971a-e37ae723e20f.png)

**Comment by noyobo** [comment]
安装  ice-scripts@next  1.6.0-1 版本。
