### ISSUE TITLE
Cannot read properties of null (reading 'mount')

### ISSUE THREAD

**Issue by JinYue127** [alibaba/ice#6652]
### Describe the bug

通过模板快速创建一个微前端的框架应用，报错Cannot read properties of null (reading 'mount')，主应用： npm init ice icestark-framework @icedesign/stark-layout   子应用：npm init ice icestark-child @icedesign/stark-child

### Expected behavior

正常显示

### Version of ice.js

"@ice/app": "^3.0.0",     "@ice/plugin-icestark": "^1.0.0",     "@ice/plugin-fusion": "^1.0.0",     "@ice/stark-app": "^1.5.0",  node：v18.17.0

**Comment by ClarkXia** [comment]
提供下主应用的配置

**Comment by JinYue127** [comment]
import { defineAppConfig } from 'ice';
import { defineFrameworkConfig } from '@ice/plugin-icestark/types';
import FrameworkLayout from './layouts/FrameworkLayout';
import PageLoading from './components/PageLoading';

export const icestark = defineFrameworkConfig(() => ({
  layout: FrameworkLayout,
  getApps: () => ([{
    path: '/seller',
    title: '商家平台',
    loadScriptMode: 'import',
    entry: 'https://iceworks.oss-cn-hangzhou.aliyuncs.com/icestark/child-seller-ice-vite/index.html',
  }, {
    path: '/test',
    title: 'Test',
    loadScriptMode: 'import',
    entry: '//localhost:3000',
  },{
    path: '/waiter',
    title: '小二平台',
    loadScriptMode: 'import',
    entry: 'https://iceworks.oss-cn-hangzhou.aliyuncs.com/icestark/child-vue3-vite/index.html',
  }, {
    path: '/angular',
    title: 'Angular',
    sandbox: true,
    // Angular app demo: https://github.com/ice-lab/icestark-child-apps/tree/master/child-common-angular
    entry: 'https://iceworks.oss-cn-hangzhou.aliyuncs.com/icestark/child-common-angular/index.html',
  }]),
  appRouter: {
    LoadingComponent: PageLoading,
  },
}));

export default defineAppConfig(() => ({
  app: {
    rootId: 'app',
  },
}));

**Comment by ClarkXia** [comment]
`loadScriptMode: 'import'` 仅用于支持 vite 模式打包的产物，正常子应用走 `loadScriptMode: 'fetch'`，后续我们增加下模版上面的说明

**Comment by JinYue127** [comment]
感谢，改用fetch后，首页能加载出来，但是微应用内部跳转会报错Uncaught SyntaxError: Unexpected token '<' (at p_list-index.js:1:1)
![image](https://github.com/alibaba/ice/assets/96155112/38f58f5b-e785-4105-a845-566a77460279)

**Comment by ClarkXia** [comment]
这个问题可以先确认子应用独立运行是否正常，关注在本地调试分包子应用时需要设置 devPublicPath

**Comment by JinYue127** [comment]
感谢，上述办法成功解决我的问题

**Comment by JinYue127** [comment]
o

**Comment by xmsz-stu** [comment]
> devPublicPath

这个问题是怎么解决的
