### ISSUE TITLE
依赖一直无法下载

### ISSUE THREAD

**Issue by gongxm0412** [alibaba/ice#666]
## 环境信息

- 操作系统：MacOS
- Iceworks 版本： 2.3.1 

## 问题描述

最近新建的项目  依赖无法下载，用最简单的模板 create-react-app 。
Log日志

## 错误信息
2595 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...arball":"http://regis'
2595 verbose stack     at JSON.parse (<anonymous>)
2595 verbose stack     at parseJson (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-better-errors/index.js:7:17)
2595 verbose stack     at consumeBody.call.then.buffer (/Applications/Iceworks.app/Contents/Resources/app/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/body.js:96:50)
2595 verbose stack     at <anonymous>
2595 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
2596 verbose cwd /Users/xmgong/WORKSPAE/study/simpleDemo
2597 verbose Darwin 17.5.0
2598 verbose argv "/Applications/Iceworks.app/Contents/Resources/bin/node" "/Applications/Iceworks.app/Contents/Resources/bin/npm" "install" "--no-package-lock"
2599 verbose node v8.9.4
2600 verbose npm  v5.6.0
2601 error Unexpected end of JSON input while parsing near '...arball":"http://regis'
2602 verbose exit [ 1, true ]

**Comment by chenbin92** [comment]
@gongxm0412  我这边试了一下可以正常安装，可以在设置面板设置一下 NPM 源

![image](https://user-images.githubusercontent.com/3995814/41891628-d86e6e0e-7947-11e8-8739-5290cbe1ba0e.png)

**Comment by chenbin92** [comment]
先暂时关闭，如何还未能解决问题，可以在开启或者通过飞冰钉钉群联系我们

**Comment by anyexinglu** [comment]
还真是，我把源从taobao改成npmjs的反而好了
![image](https://user-images.githubusercontent.com/8243326/42410036-405a6e06-8216-11e8-99e7-7e0510c95c26.png)
