### ISSUE TITLE
FormBinder组件type=‘number’校验出现问题

### ISSUE THREAD

**Issue by Symous** [alibaba/ice#667]
## 环境信息

- 操作系统：macOS 10.13.5
- Iceworks 版本： 2.3.1

## 问题描述

```js
<FormBinderWrapper value={this.state.lockPosition} onChange={this.lockPosChanged}>
                <div>
                  <FormBinder  type='number'>
                    <Input addonBefore='纬度' name='latitude' htmlType='number'/>
                  </FormBinder>
                  <FormError name='latitude'/>
                  <FormBinder type='number'> 
                    <Input addonAfter='经度' name='longitude' htmlType='number'/>
                  </FormBinder>
                  <FormError name='longitude' />
                </div>
              </FormBinderWrapper>
```
当修改Input内的值的时候，即使为数字，仍然会校验失败，如下图：
![image](https://user-images.githubusercontent.com/13534034/41908410-6e5c0010-7976-11e8-8367-872497920503.png)

**Comment by wssgcg1213** [comment]
number 指的是 typeof val === 'number';  不是字符串匹配`\d`, 这里建议用` pattern={/\d+/}` 来判断

**Comment by wssgcg1213** [comment]
![image](https://user-images.githubusercontent.com/3922719/43177837-cf1d162c-8ffc-11e8-8cbb-3dae6c3adabb.png)

**Comment by Symous** [comment]
@wssgcg1213 经过验证此方法pattern={/\d+/}也行不通，只可以验证第一位，比如输入a时会正常报错，但是输入a1234fhs这种类似的仍然会通过验证不报错。
