### ISSUE TITLE
如何配置@svgr-webpack

### ISSUE THREAD

**Issue by oneQiu** [alibaba/ice#6670]
目前import引入的svg会自动转为base64，我想使用mui的SvgIcon组件，所以需要配置@svgr/webpack转化为react组件不知道我哪里配置错了，还是会有问题。
![image](https://github.com/alibaba/ice/assets/50658231/1ce2c0a3-28d6-4b86-a985-78a42c5b1c3e)
![image](https://github.com/alibaba/ice/assets/50658231/8a5c3fe3-1d9a-4eec-b7e0-567109bf3ac6)
![image](https://github.com/alibaba/ice/assets/50658231/4114f91b-cb87-4851-8860-ae305339ce05)

**Comment by ClarkXia** [comment]
```js
import { defineConfig } from '@ice/app';

export default defineConfig(() => ({
  // Disable ssg
  ssg: false,
  webpack: (config) => {
    console.log('config', config);
    // Remove rule of .svg
    config.module.rules = config.module.rules.filter((rule) => {
      if (rule.test instanceof RegExp) {
        return !rule.test.test('.svg');
      }
      return true;
    });
    // Add rule of .svg with @svgr/webpack
    config.module.rules.push({
      test: /\.svg$/,
      use: [
        {
          loader: '@svgr/webpack',
          options: {
          },
        },
      ],
    });
    return config;
  },
}));
```

@svgr/webpack 的方式目前 SSR / SSG 不支持需要关闭，然后移除默认的 .svg 规则并替换即可
