### ISSUE TITLE
使用ice.js的过程中webpack总是崩溃

### ISSUE THREAD

**Issue by ssmoon** [alibaba/ice#6671]
### Describe the bug

之前两个项目用ice.js没有出过类似的问题（至少半年前了），最近的新项目，总是在修改项目components下的文件时发生webpack崩溃，google了半天也没有找到类似的错误。我也不是很确定是ice的问题还是webpack的问题。
错误信息如图。
![企业微信截图_17010879725118](https://github.com/alibaba/ice/assets/5524107/fcae9460-e3aa-4d2f-8e6f-19487c3388b9)

### Expected behavior

webpack不再因为修改文件而崩溃

### Actual behavior

修改components下的文件webpack会崩溃，没有找到规律，崩溃很频繁，不断修改的时候1-2分钟即会崩溃

### Version of ice.js

3.3.0

### Content of build.json or ice.config.mts

```TypeScript
import { defineConfig } from '@ice/app';
import request from '@ice/plugin-request';
import jsxPlus from '@ice/plugin-jsx-plus';

// The project config, see https://v3.ice.work/docs/guide/basic/config
const minify = process.env.NODE_ENV === 'production' ? 'swc' : false;
export default defineConfig(() => ({
  // Set your configs here.
  minify,
  ssr: false,
  ssg: false,
  server: {
    onDemand: true,
    format: 'esm'
  },
  plugins: [
    jsxPlus(),
    request(),
  ],
  proxy: {
    '/api': {
      target: 'http://localhost:8080/api/',
      changeOrigin: true,
      pathRewrite: { '^/api' : '' },
    },
  },
}));
```

**Comment by ClarkXia** [comment]
看着像 rspack 模式下的错误，可以将 package.json 中 —speedup 移除试试，另外也可以提供一下报错文件代码 方便我们复现

**Comment by ssmoon** [comment]
> 看着像 rspack 模式下的错误，可以将 package.json 中 —speedup 移除试试，另外也可以提供一下报错文件代码 方便我们复现

你好，去掉speedup后正常了，代码上没啥特别的，我所有的component文件，随意修改两下都会报错。
感谢。

**Comment by ClarkXia** [comment]
@ice/app@3.4.1 版本修复了多数 hmr 问题 可以尝试下
