### ISSUE TITLE
支持配置 preBundleDeps 

### ISSUE THREAD

**Issue by linbudu599** [alibaba/ice#6683]
### Summary | 概述

支持配置或插件 API 来修改 preBundleDeps 时 ESBuild 构建配置，如

```ts
setup(build){
  build.updatePreBundleOptions({
    // 与内置的配置 deep merge
    loader: {
      '.png': 'dataurl',
      '.jpg': 'dataurl',
      // ...
    }
  })
}
```

### Motivation | 背景

ICECream 会在 .ice 文件中提供额外的文件注册，其中可能包括一些静态资源：

```ts
.ice/site-meta.ts
export const siteLogo = require('path/to/asset.png');
```

在启用 SSG 情况下，此文件会经过 preBundleDeps 处理，从而导致一个错误：`No loader is configured for '.png'`，这个错误可以通过为 ESBuild 配置资源 Loader 解决。

另外，在 SSG 下 ICECream 可能希望对 preBundleDeps 的配置进一步定制，这需要 ICE 对外提供 preBundleDeps 的定制能力。

### Detailed design | 方案设计

待定

**Comment by ClarkXia** [comment]
会先修复 prebundle 对于 assets 的处理，由于 prebundle 的配置有比较高的确定下，暂时先不考虑提供过于灵活的自定义能力
