### ISSUE TITLE
2.x Suspense  动态加载打包问题

### ISSUE THREAD

**Issue by wmy94827** [alibaba/ice#6685]
### Describe the bug

2版本的项目中 使用了<Suspense  根据名称 动态加载组件

但是打包后由于未引用 没有被打包出来。想问一下旧版本中 build.config.ts 中如何配置可以全部打包呀

### Expected behavior

正常打包

### Actual behavior

打包部分

### Version of ice.js

2.6

**Comment by ClarkXia** [comment]
lazy import 默认无法被打包的主 bundle，但可以通过 magic comments 处理参考 https://webpack.js.org/api/module-methods/#webpackmode
