### ISSUE TITLE
页面级Store报错：Cannot read properties of null (reading 'store')

### ISSUE THREAD

**Issue by oneQiu** [alibaba/ice#6686]
### Describe the bug

使用页面级别store的时候报错
![image](https://github.com/alibaba/ice/assets/50658231/62d336e4-32e4-4b7e-b4ea-ea5949adc44b)
这是我的路由结构，是否和$review.$id有关系？
![image](https://github.com/alibaba/ice/assets/50658231/7231367e-eb64-4dc9-8e28-d2a6defacb02)

### Expected behavior

正常使用

### Version of ice.js

v3.3.0

**Comment by citrusyahello** [comment]
@luhc228 我用https://github.com/alibaba/ice/issues/4750#issuecomment-1551000333的测试项目icejs升级到2.6.8依然报错，
![企业微信截图_17090006123503](https://github.com/alibaba/ice/assets/56066787/491451c2-1dd9-4b47-b9c2-829f53d1ff56)
![企业微信截图_17090006277819](https://github.com/alibaba/ice/assets/56066787/da916a59-ddd1-4ff7-88ff-b18928544824)

**Comment by luhc228** [comment]
> @luhc228 我用[#4750 (comment)](https://github.com/alibaba/ice/issues/4750#issuecomment-1551000333) 的测试项目icejs升级到2.6.8依然报错， ![企业微信截图_17090006123503](https://private-user-images.githubusercontent.com/56066787/308015194-491451c2-1dd9-4b47-b9c2-829f53d1ff56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMTI3MDcsIm5iZiI6MTcwOTAxMjQwNywicGF0aCI6Ii81NjA2Njc4Ny8zMDgwMTUxOTQtNDkxNDUxYzItMWRkOS00YjQ3LWI5YzItODI5ZjUzZDFmZjU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDA1NDAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhNDE2MjZjNzFiZTM4YTg5ZDFhMmM5NGYyZjcyMTE3OWRmMzIxYzM2Y2E1NTcxMmNmNzVkMDAwOTRlYmNmYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2DFac0_FvZwT2ohYm9drm44oWFFuLS9jHkVk1cVBRP4) ![企业微信截图_17090006277819](https://private-user-images.githubusercontent.com/56066787/308015199-da916a59-ddd1-4ff7-88ff-b18928544824.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMTI3MDcsIm5iZiI6MTcwOTAxMjQwNywicGF0aCI6Ii81NjA2Njc4Ny8zMDgwMTUxOTktZGE5MTZhNTktZGRkMS00ZmY3LTg4ZmYtYjE4OTI4NTQ0ODI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDA1NDAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyNWM2YzI0ZDA2NzQ0ODc0Y2NlMTcwYTM3OGRkZjUxNzE4NWY5YWYxYWM1NmU0OTAzZmIzNGJiOWViNDUxMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xMJzTw0fjEpo5lAcYGa04NqtfwnEmOlgSE2Ukmec2Cs)

我这里是好的。可以新开一个 issue 把复现路径写出来。

**Comment by LzPhp25** [comment]
这个一直都没有解决

**Comment by luhc228** [comment]
> 这个一直都没有解决

尝试最新的版本 2.6.9
