### ISSUE TITLE
图片加载不出来

### ISSUE THREAD

**Issue by Sharang-heng** [alibaba/ice#6692]
### Describe the bug

静态资源文件放在了assets目录下
import Frame from "@/assets/Frame.png";
查看代码来源也没显示
![image](https://github.com/alibaba/ice/assets/69613396/329d36fe-e063-44a8-9446-9cdc850bf20e)
![image](https://github.com/alibaba/ice/assets/69613396/a9df719c-eb08-4aea-8ca6-6896413eaee5)
显示效果
![image](https://github.com/alibaba/ice/assets/69613396/e5bbb499-ec59-4a4d-b05c-99814ce790cd)

### Expected behavior

显示图片

### Actual behavior

确认了路径是没问题的，但图片不显示

### Version of ice.js

3.3.0

**Comment by ClarkXia** [comment]
提供下 package.json 信息

**Comment by wssgcg1213** [comment]
<img width="1346" alt="image" src="https://github.com/alibaba/ice/assets/3922719/1127aed2-d59c-427f-b958-c72a582d5b98">

我本地试了下是正常显示的, 3.3.0-beta.0, 看下有没有更多信息

**Comment by Sharang-heng** [comment]
> 提供下 package.json 信息

{
  "version": "0.1.0",
  "description": "AI助手",
  "dependencies": {
    "@ice/runtime": "^1.2.7",
    "ahooks": "^3.7.8",
    "ali-react-table": "^2.6.1",
    "antd": "^5.12.1",
    "crypto-js": "^4.2.0",
    "immutability-helper": "^3.1.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-infinite-scroll-component": "^6.1.0",
    "request-cache": "^1.0.1",
    "vditor": "^3.9.6"
  },
  "devDependencies": {
    "@applint/spec": "^1.2.3",
    "@ice/app": "^3.3.0",
    "@ice/plugin-request": "^1.0.3",
    "@ice/plugin-store": "^1.1.2",
    "@types/node": "^18.11.17",
    "@types/react": "^18.0.0",
    "@types/react-dom": "^18.0.0",
    "configplugin": "^0.0.2",
    "copy-webpack-plugin": "^5.1.2",
    "eslint": "^8.35.0",
    "stylelint": "^15.2.0",
    "typescript": "^4.9.5"
  },
  "scripts": {
    "start": "ice start --speedup --port 3333",
    "build": "ice build",
    "eslint": "eslint ./src --cache --ext .js,.jsx,.ts,.tsx",
    "eslint:fix": "npm run eslint -- --fix",
    "stylelint": "stylelint \"src/**/*.{css,scss,less}\" --cache",
    "stylelint:fix": "npm run stylelint -- --fix"
  },
  "repository": "git@github.com:ice-lab/react-materials.git"
}

**Comment by yymelo** [comment]
3.3.0加载不了svg资源，我在另一个issue里看到3.3.8修复了就升级了3.3.8，现在图片也是显示不了
package.json 信息如下：
{
  "name": "@ice/antd-pro-scaffold",
  "version": "1.2.0",
  "description": "ice.js 3 Pro 模板（基于 Ant Design）",
  "dependencies": {
    "@ant-design/charts": "^1.4.2",
    "@ant-design/icons": "^4.8.1",
    "@ant-design/pro-form": "^2.2.8",
    "@ant-design/pro-layout": "^7.1.6",
    "@ant-design/pro-table": "^3.0.17",
    "@ice/runtime": "^1.2.7",
    "antd": "^4.24.0",
    "lodash": "^4.17.21",
    "node-sass": "npm:sass",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-helmet": "^6.1.0",
    "sass": "^1.69.5"
  },
  "devDependencies": {
    "@applint/spec": "^1.2.3",
    "@ice/app": "^3.3.8",
    "@ice/plugin-antd": "^1.0.2",
    "@ice/plugin-auth": "^1.0.0",
    "@ice/plugin-request": "^1.0.0",
    "@ice/plugin-store": "^1.0.0",
    "@types/node": "^18.11.17",
    "@types/react": "^18.0.0",
    "@types/react-dom": "^18.0.0",
    "eslint": "^8.35.0",
    "stylelint": "^15.2.0",
    "typescript": "^4.8.4"
  },
  "scripts": {
    "start": "ice start --speedup",
    "build": "ice build",
    "eslint": "eslint ./src --cache --ext .js,.jsx,.ts,.tsx",
    "eslint:fix": "npm run eslint -- --fix",
    "stylelint": "stylelint \"src/**/*.{css,scss,less}\" --cache",
    "stylelint:fix": "npm run stylelint -- --fix"
  },
  "publishConfig": {
    "access": "public"
  },
  "repository": "git@github.com:ice-lab/react-materials.git"
}

**Comment by ClarkXia** [comment]
下个版本将会修复

**Comment by ClarkXia** [comment]
安装 @ice/app@3.4.0
