### ISSUE TITLE
打包后图片访问不到

### ISSUE THREAD

**Issue by hanyahui123** [alibaba/ice#6697]
assets在根目录下，访问路径多了/css

![image](https://github.com/alibaba/ice/assets/50311889/bf27866b-bbcf-409a-80f4-3108f2bd76f9)

**Comment by ClarkXia** [comment]
提供下简单的复现工程

**Comment by ClarkXia** [comment]
提供复现 demo 后重开 issue

**Comment by maixiachen** [comment]
的确有怎么问题，怎么解决？
