### ISSUE TITLE
CheckBox不渲染

### ISSUE THREAD

**Issue by lilegang1589** [alibaba/ice#670]
## 环境信息
win10
- 操作系统：
- Iceworks 版本： 
2.3.1
## 问题描述
ICE Design CMS

登录界面的checkbox初始化定义不起作用
this.state = {
        account: undefined,
        password: undefined,
        checkbox: false,//无论true还是false，界面渲染都是未选中，
      },
    };
并且渲染的html如下，但是界面未渲染
<input type="checkbox" value="true" aria-checked="false">
不知是不是组件引入问题，望知晓

**Comment by lilegang1589** [comment]
`<input type="checkbox" value="true" aria-checked="false">`

**Comment by chenbin92** [comment]
@lilegang1589  初始状态设置 `defaultChecked` 属性

`defaultChecked={this.state.checkbox}`
