### ISSUE TITLE
在ice3 仓库里，添加了@ice/plugin-rax-compat插件，使用 rax 组件，项目中有props 驼峰命名告警。

### ISSUE THREAD

**Issue by zhangzyi** [alibaba/ice#6702]
### Describe the bug

在ice3仓库里，添加了@ice/plugin-rax-compat插件，使用rax组件会有以下的报错
react-dom.development.js:86 Warning: React does not recognize the `ignoreExp` prop on a DOM element.

原因是因为，rax 组件使用驼峰命名规范，传递props到 <rax-view></rax-view>, 再经过编译，创建转化为原生html dom节点，rax 在编译 rax-view 到 div 这个过程中，会将驼峰命名转化为小写的props属性传递到真实的div节点

在 ice3 的工程里面，使用插件 rax-compat  会直接拿到props，通过createElement创建成 div 节点，拿到的 props 如果是驼峰命名的属性，不符合react规范因此报错

### Expected behavior

期望在rax-compat这一层，能否将传递给<rax-view>的 props 驼峰命名的属性，在createElement ，创建dom节点，将驼峰命名的属性转为小写，传递给dom节点。

### Version of ice.js

3.0

**Comment by zhangzyi** [comment]
可以阿里钉联系--竹仪

**Comment by ClarkXia** [comment]
默认设计，rax-compat 只是一个兼容模式，长期来看期望都是以 React 规范进行开发，不自动转化和屏蔽错误是为了开发者的开发习惯尽早能够按 React 规范进行
