### ISSUE TITLE
addWrapper 插件是如何使用？文档上不太清晰，ice2的 route里面可以直接配置wrapper，现在还支持吗？

### ISSUE THREAD

**Issue by jelly823** [alibaba/ice#6703]
### Describe the bug

https://ice3.alibaba-inc.com/v3/docs/guide/plugins/plugin-dev#addwrapper 关于路由如何包裹一个 wrapper，文档上介绍的不太清楚，之前的 ice2的 route里面可以直接配置wrapper，现在还支持吗？__

### Expected behavior

有一个可以参考的例子，使用 addWrapper ，或者 route 配置，可以支持wrapper

### Version of ice.js

3

**Comment by ClarkXia** [comment]
现在只能通过 api 来做，可以参考 https://github.com/alibaba/ice/tree/master/packages/plugin-auth 的实现
