### ISSUE TITLE
vue3子系统打开图片地址错乱

### ISSUE THREAD

**Issue by lijinchengGIT** [alibaba/ice#6704]
### Describe the bug

在vue3构建的主系统中打开子系统中使用相对地址加载图片，图片默认获取的是主系统的originUrl加载，无法获取子系统的资源

### Expected behavior

子系统中的图片从子系统部署的文件夹获取资源

### Version of ice.js

2.6.1

**Comment by lijinchengGIT** [comment]
![Uploading 微信图片_20231220114702.png…]()

**Comment by lijinchengGIT** [comment]
![1703044008169](https://github.com/alibaba/ice/assets/40062193/bdd3a934-c4de-4554-b0d3-ff2b2619b174)

**Comment by ClarkXia** [comment]
子应用的地址路径在调试的时候可以通过 publicPath 指定成绝对地址

**Comment by ClarkXia** [comment]
https://micro-frontends.ice.work/docs/faq#%E5%BE%AE%E5%BA%94%E7%94%A8-bundle-%E5%8A%A0%E8%BD%BD%E5%A4%B1%E8%B4%A5 类似这个
