### ISSUE TITLE
ice store支持计算属性吗

### ISSUE THREAD

**Issue by oneQiu** [alibaba/ice#6706]
场景：我现在有一个List，然后我需要点击某个按钮来过滤掉状态为1的，再点击回到之前数据。

目前是store里面维护了一个filterFlag以及list，和sourceList三个字段。因为使用的地方比较多，不太适合那种哪里用哪里进行filter的

**Comment by ClarkXia** [comment]
目前没有类似 computer 的设计，可以先抽象一个数据处理的函数进行实现
