### ISSUE TITLE
Bizcharts 物料接入

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#671]
## 环境信息

- 操作系统：
- Iceworks 版本： 2.3.1

## 问题描述

Bizcharts 物料接入 Iceworks 的一些问题

## 错误信息

步骤一：

使用 Bizcharts 物料源：http://g.alicdn.com/bizcharts-material/scripts/0.0.2/material-assets.json

步骤二：

使用 Bizcharts 模板创建项目

![image](https://user-images.githubusercontent.com/3995814/42142253-dc448642-7de0-11e8-927e-ca5ea79af1e5.png)

![image](https://user-images.githubusercontent.com/3995814/42142384-9dc97016-7de1-11e8-9add-b572e946bd11.png)

步骤三：使用 Bizcharts 区块新建页面
![image](https://user-images.githubusercontent.com/3995814/42142353-6a8f6a84-7de1-11e8-9b05-794f0f066776.png)

![image](https://user-images.githubusercontent.com/3995814/42142367-820103c6-7de1-11e8-8d98-f939f683677a.png)

**Comment by noyobo** [comment]
v2.5.0 fixed 待物料推送
