### ISSUE TITLE
从列表页通过Link跳转到详情页时，dataLoader拿到的ctx中的pathname是跳转前的列表页路由，无法拿到跳转后的路由内容

### ISSUE THREAD

**Issue by 903129400** [alibaba/ice#6720]
### Describe the bug

之前开发的时候详情页的dataLoader会在路由跳转前后都触发一次，第一次拿到列表页的pathname，第二次拿到详情页的，但在近期迭代时更新了依赖，发现第二次dataLoader不触发了，导致无法在dataLoader中通过拿路由参数发起详情页内容的请求

### Expected behavior

在csr跳转时，dataLoader中的ctx.pathname(或者location中)能正确获取到跳转后的url

### Actual behavior

之前是会触发两次dataLoader，第一次获取到跳转之前的pathname，第二次拿到详情页的
更新依赖后只会触发第一次拿到跳转前pathname的dataLoader

### Version of ice.js

3.2.10

### Content of build.json or ice.config.mts

```TypeScript
import { defineConfig } from '@ice/app';
import faas from '@ali/ice-plugin-faas';
import def from '@ali/ice-plugin-def';
import routerConfig from './routes';
import request from '@ice/plugin-request';
import spm from '@ali/ice-plugin-spm';

export default defineConfig(() => ({
  ssr: true,
  plugins: [def(), faas({ defaultRender: false }), request(), spm()],
  routes: {
    config: routerConfig,
  },
  // dropLogLevel: 'log',
  publicPath: '/',
  polyfill: 'entry',
}));
```

**Comment by ClarkXia** [comment]
先用最新版本 3.3.9 尝试
