### ISSUE TITLE
子应用的公共样式会覆盖主应用的样式

### ISSUE THREAD

**Issue by explorefit** [alibaba/ice#6735]
### Describe the bug

![image](https://github.com/alibaba/ice/assets/24665389/690db007-4219-48dc-9c49-f39a80e447ec)
子应用的样式覆盖了主应用的样式

### Expected behavior

样式应该隔离。主应用不受影响

### Actual behavior

子应用的样式覆盖了主应用的样式

### Version of ice.js

3.3.9

### Content of build.json or ice.config.mts

```TypeScript
import { defineConfig } from '@ice/app';
import request from '@ice/plugin-request';
import store from '@ice/plugin-store';
import auth from '@ice/plugin-auth';
import icestark from '@ice/plugin-icestark';
import routesConfig from './src/routesConfig';
import antd from '@ice/plugin-antd';

// The project config, see https://v3.ice.work/docs/guide/basic/config
const minify = process.env.NODE_ENV === 'production' ? 'swc' : false;
const env = process.env.ICE_CORE_MODE
console.log('config-env:', env)
const outputDirList = {
    local: 'build-local',
    test1: 'test-v1-bms-build',
    test2: 'test-v2-bms-build',
    demo: 'demo-bms-build',
    prod: 'prod-bms-build',
    nbc: 'nbc-bms-build',
    bw: 'bw-bms-build',
    az: 'az-bms-build',
    dsr: 'dsr-bms-build',
}
export default defineConfig(() => ({
    ssg: false,
    minify: minify,
    plugins: [
        request(), store(), auth(),
        // 设置应用类型为框架应用 framework
        icestark({ type: 'framework' }),
        antd({
            theme: {
                "css-prefix": "bms-patient-"
            }
        }),
    ],
    compileDependencies: false,
    routes: {
        config: routesConfig,
    },
    crossOriginLoading: 'anonymous',
    outputDir: outputDirList[env],
    publicPath: "/bms/",
    devPublicPath: "/bms/", 
}));
```

**Comment by ClarkXia** [comment]
基础样式隔离推荐通过组件库提供的 css-prefix 解决

**Comment by explorefit** [comment]
> 基础样式隔离推荐通过组件库提供的 css-prefix 解决

使用antd的 ConfigProvider 组件里的 prefixCls 属性，加上前缀后，看着className的名字改了，但是antd的样式都不在了
![image](https://github.com/alibaba/ice/assets/24665389/ff5c9370-fa3a-4f3b-b551-434c8a472c8f)

**Comment by explorefit** [comment]
> ```
> [
>   'build-plugin-antd',
>   {
>     themeConfig: {
>       'primary-color': '#1890FF',
>       'ant-prefix': 'prefix'
>     }
>   }
> ],
> ```
> 
> 试一下这个配置

用这个后，还是不行
![image](https://github.com/alibaba/ice/assets/24665389/fb728423-7327-4633-91d6-60e1c9f16388)

![image](https://github.com/alibaba/ice/assets/24665389/b43bab59-5f5c-4831-ae57-267f52f48749)

**Comment by ClarkXia** [comment]
确认下 antd 的版本， antd 5 的样式适配可以先参考官网，目前插件未做支持

**Comment by explorefit** [comment]
> 确认下 antd 的版本， antd 5 的样式适配可以先参考官网，目前插件未做支持 #6724

项目里使用的 antd 版本是 4.24.15

**Comment by ClarkXia** [comment]
Step1:
![image](https://github.com/alibaba/ice/assets/4219965/8d37cb71-f662-41d2-8e30-9e1c69f0227f)
Step2: 
![image](https://github.com/alibaba/ice/assets/4219965/741f9b18-e056-41af-9b4f-d637c44ce2f6)
![image](https://github.com/alibaba/ice/assets/4219965/138bdca5-57df-4414-ad43-61e38067fb58)

> 确保自己没有全量引入 antd 的 css

**Comment by explorefit** [comment]
> Step1: ![image](https://private-user-images.githubusercontent.com/4219965/296945757-8d37cb71-f662-41d2-8e30-9e1c69f0227f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzODU5MjcsIm5iZiI6MTcwNTM4NTYyNywicGF0aCI6Ii80MjE5OTY1LzI5Njk0NTc1Ny04ZDM3Y2I3MS1mNjYyLTQxZDItOGUzMC05ZTFjNjlmMDIyN2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTZUMDYxMzQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWNjNzRmNDYwYTViZTA3YzdkOTMzMTQ1ZmFhMGJhOWQyODE3OGM4M2U3ZDAxYzY3MWJhZjM4ODhkZDE2OTY2MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tfrTuAFA8lzmCU7CXa02ZTNeWa_IRl4v_prjy-7IDa4) Step2: ![image](https://private-user-images.githubusercontent.com/4219965/296945807-741f9b18-e056-41af-9b4f-d637c44ce2f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzODU5MjcsIm5iZiI6MTcwNTM4NTYyNywicGF0aCI6Ii80MjE5OTY1LzI5Njk0NTgwNy03NDFmOWIxOC1lMDU2LTQxYWYtOWI0Zi1kNjM3YzQ0Y2UyZjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTZUMDYxMzQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjRjMTk4OWVkYTNkYzAyNTcyMGQwMTI4OGI1ZjNjODgzMjBiYmQxZTgxYzg4YzQ5MWI2NWQyYzhkZjBkZTQ2YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yHQROg2XVGthaF3lY2XuGGkgT7RgzfQU1pjoRG6-550) ![image](https://private-user-images.githubusercontent.com/4219965/296945717-138bdca5-57df-4414-ad43-61e38067fb58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzODU5MjcsIm5iZiI6MTcwNTM4NTYyNywicGF0aCI6Ii80MjE5OTY1LzI5Njk0NTcxNy0xMzhiZGNhNS01N2RmLTQ0MTQtYWQ0My02MWUzODA2N2ZiNTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTZUMDYxMzQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDMzMzAwMTdlMDk1YzNiYTYyNWNlZjdjYTRhMmFkYjhkMzNhNGJkZDlkNzE5NGNkMTgwNmU3YTVkNzU4OWE3NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.AaH1IhynlQYTN4hrvFo-cPA_ftSF0b_PwYcQ6rUscdE)
> 
> > 确保自己没有全量引入 antd 的 css

我在项目中使用了 @ant-design/pro-components  这个库，
![image](https://github.com/alibaba/ice/assets/24665389/b03ea70d-b717-47e4-90cf-eeda93cf20e0)
修改后，页面样式都没了
![image](https://github.com/alibaba/ice/assets/24665389/db730494-0bff-412a-ba25-c050e2b2c1a9)
![image](https://github.com/alibaba/ice/assets/24665389/c4ffd0e7-3afa-46e0-8737-c257adcfecc3)

**Comment by ClarkXia** [comment]
@explorefit `npm list antd` 看下背后依赖的组件到底是不是 antd 4

**Comment by explorefit** [comment]
> @explorefit `npm list antd` 看下背后依赖的组件到底是不是 antd 4

![image](https://github.com/alibaba/ice/assets/24665389/06b3530b-d14a-4a1c-8474-fa952d54248c)
