### ISSUE TITLE
构建报错 Error: `env` and `jsc.target` cannot be used together 

### ISSUE THREAD

**Issue by guoshencheng** [alibaba/ice#6743]
### Describe the bug

构建报错
Error: `env` and `jsc.target` cannot be used together

原因是因为ice自己定义了swc的配置，但是swc默认会在每个文件的编译的时候，从文件的目录去读取最近的swcrc的文件。需要通过 swcrc: false 的options进行关闭，因此，建议ice能够默认关闭这个选项，或者提供options来关闭这个选项

### Expected behavior

在调用swc.trasform的时候，设置options.swcrc = false

### Version of ice.js

v3

**Comment by ClarkXia** [comment]
我们内置关闭下 swcrc，其他 swc options 目前是可以通过插件的方式修改的，比如 https://github.com/alibaba/ice/blob/2e4449f727d766eb730307493244bdded8214198/packages/plugin-rax-compat/src/index.ts#L124-L130

**Comment by guoshencheng** [comment]
OK。明白，就是我可以先通过插件关闭一下，内置的我建议还是的已关闭或者提供选项直接关闭，我会继续关注这个issue
