### ISSUE TITLE
怎么使用react-activation实现keepalive

### ISSUE THREAD

**Issue by yxiawen** [alibaba/ice#6745]
### Motivation | 背景

需求需要tabs切换页面时不重置

### Detailed design | 方案设计

文档说明使用 Keep Alive 能力需要安装 react 和 react-dom 的 experimental 版本，因此暂时不使用，希望能用其他实现，比如 react-activation

**Comment by ClarkXia** [comment]
直接参考 react-activation 的文档就好，如果有什么需要框架支持的，可以再补充

**Comment by ClarkXia** [comment]
框架后续将默认实现 keepalive 能力，如果使用 react-activation 可以直接参考其官方文档。
一些全局 Provider 可以新增  `src/pages/layout.tsx` 进行处理

**Comment by yxiawen** [comment]
已实现： 动态import渲染
![image](https://github.com/alibaba/ice/assets/21170741/ef993d85-f200-4a64-bafc-f5c58c703ee6)
<img width="671" alt="image" src="https://github.com/alibaba/ice/assets/21170741/0c46b03d-5f66-43e3-b712-310507e6496c">
