### ISSUE TITLE
权限管理中NoAuthFallback报错

### ISSUE THREAD

**Issue by yymelo** [alibaba/ice#6762]
### Describe the bug

```js
export const authConfig = defineAuthConfig(async appData => {
  const { currentUser = {} } = appData

  if (!currentUser?.enabled) {
    history?.push('/');
  }

  return {
    initialAuth: {
      user: currentUser?.id ? true : false,
    },
    NoAuthFallback: (routeConfig) => {
      console.log('routeConfig ', routeConfig);
      return (
        <div>123</div>
      )
    },
  }
})
```
<img width="364" alt="2f6d510927ae160998a7c8ca6ba93d4" src="https://github.com/alibaba/ice/assets/36154066/36e1222b-8bfd-4e86-9efa-108a335518d5">

上述代码中<div>123</div>部分标红报错

### Expected behavior

期望与官方文档描述一致https://v3.ice.work/docs/guide/advanced/auth#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%9D%83%E9%99%90%E7%BB%84%E4%BB%B6

### Actual behavior

代码报错无法编译

### Version of ice.js

3.3.0

**Comment by ClarkXia** [comment]
提供下具体编译错误信息

**Comment by yymelo** [comment]
> 提供下具体编译错误信息
<img width="347" alt="7423b42b7da5f80eeeb965e28d406f3" src="https://github.com/alibaba/ice/assets/36154066/1e5539ac-47d6-4206-af1c-b7f1795e3485">

就是上图那样的问题，写html标签就报错了

**Comment by yymelo** [comment]
脑子不清醒，官方文档给的是tsx，工程里起来的是ts。。。。没注意，犯傻了
