### ISSUE TITLE
ICE路由参数如何实现

### ISSUE THREAD

**Issue by oneQiu** [alibaba/ice#6763]
比方说我现在有一个项目，有通用的Layout，但是我有一些页面是不需要Layout显示的，我该怎么解决。（路由path不能改，产品定的路径，所以我不能单独对有layout放在一个文件夹里）。

方案1：使用Store状态管理，但是会出现闪烁的问题，因为先出现后修改
方案2：直接在layout里面通过判断pathname，维护不方便，判断可能出现问题。
方案3：类似react-router的路由参数，这个能实现吗
```ts
const routes = [
{
    path: '/',
    exact: true,
    layout: true, // Indicates that layout should be applied
    component: Home,
  }
]

const Layout = ({ route }) => {
  const { layout } = route;

  return (
    <div>
      {layout ? (
        <>
          <Header />
          {/* Content with layout */}
          <Footer />
        </>
      ) : (
        <div>
          {/* Content without layout */}
        </div>
      )}
    </div>
  );
};
```

**Comment by ClarkXia** [comment]
https://github.com/alibaba/ice/issues/6584 有点类似这个场景

**Comment by oneQiu** [comment]
> #6584 有点类似这个场景

是的，我们的情况只能采用方案一，我就是想知道内部判断有什么标识嘛，类似definePageConfig里面我加一个layout: false，我在Layout能获取到，但是感觉好像不太行，感觉只能通过path来判断了吗，路由太多了

**Comment by ClarkXia** [comment]
目前没有提供 layout: false 的能力
