### ISSUE TITLE
无法使用i18next-hmr插件

### ISSUE THREAD

**Issue by justrustc** [alibaba/ice#6766]
### Describe the bug

编译报错

### Expected behavior

正常编译

### Actual behavior

<img width="1170" alt="image" src="https://github.com/alibaba/ice/assets/5822190/9067db00-ca4e-40e8-ab91-e1e958a5b7ab">

### Version of ice.js

3.4.2

### Content of build.json or ice.config.mts

```TypeScript
import path from 'path'
import { fileURLToPath } from 'url'
import { I18NextHMRPlugin } from 'i18next-hmr/webpack'

const __dir = path.dirname(fileURLToPath(import.meta.url))

export default defineConfig(() => ({
  webpack(config) {
    if (process.env.NODE_ENV === 'development') {
      config.plugins!.push(
        new I18NextHMRPlugin({
          localesDir: path.join(__dir, 'public/locales'),
        }),
      )
    }
    return config
  },
}))
```

**Comment by ClarkXia** [comment]
工程上默认开启了基于 rspack 的 speedup 模式，如果三方 webpack 插件 API 还未兼容，可以先关闭 speedup 模式
修改 package.json 下的 start 脚本，去掉 --speedup 即可
