### ISSUE TITLE
icejs 启动缓慢卡51%

### ISSUE THREAD

**Issue by dlpuzhangyue** [alibaba/ice#6771]
### Describe the bug

speed-measure-webpack-plugin日志如下
 SMP  ⏱  
General output time took 1 min, 2.6 secs

 SMP  ⏱  Loaders
@builder/pack took 59.62 secs
  module count = 2837
modules with no loaders took 11.74 secs
  module count = 1402
@builder/pack, and 
@builder/pack, and 
@builder/user-config took 0.375 secs
  module count = 1
webpack-plugin-import took 0.259 secs
  module count = 2

### Expected behavior

 SMP  ⏱  
General output time took 1 min, 2.6 secs

 SMP  ⏱  Loaders
@builder/pack took 59.62 secs
  module count = 2837
modules with no loaders took 11.74 secs
  module count = 1402
@builder/pack, and 
@builder/pack, and 
@builder/user-config took 0.375 secs
  module count = 1
webpack-plugin-import took 0.259 secs
  module count = 2

### Version of ice.js

2.6.6

### Content of build.json or ice.config.mts

```TypeScript
module.exports = {
  define: {
    env: process.env.NODE_ENV,
  },
  vite: false,
  hash: true,
  minify: false,
  publicPath: '/interaction/',
  devPublicPath: 'http://127.0.0.1:2001/',
  outputDir: 'dist',
  eslint: false,
  outputAssetsPath: {
    js: 'js',
    css: 'css',
  },
  externals: {
    react: 'React',
    'react-dom': 'ReactDOM',
    '@alifd/next': 'Next',
    moment: 'moment',
    echarts: 'echarts',
    exceljs: 'exceljs',
    swiper: 'swiper',
  },
  plugins: [
    [
      'build-plugin-icestark',
      {
        umd: true,
        type: 'child',
        uniqueName: 'interaction2',
      },
    ]
  ],
};
```

**Comment by ClarkXia** [comment]
2.x 不再进行性能优化相关的修复，推荐升级 3.x，如果有升级问题 可以通过 issue 反馈

**Comment by dlpuzhangyue** [comment]
> 2.x 不再进行性能优化相关的修复，推荐升级 3.x，如果有升级问题 可以通过 issue 反馈

升级3.x向下兼容吗。有心智负担吗
