### ISSUE TITLE
子应用vite-plugin-mock mock数据调不通

### ISSUE THREAD

**Issue by Gallado** [alibaba/ice#6778]
### Describe the bug

npm init ice icestark-child @vue-materials/icestark-child-app 创建的子应用。本身用vite-plugin-mock 做mock数据，子应用单独可以显示。接入主应用后子应用的mock数据不显示，接口没返回
![image](https://github.com/alibaba/ice/assets/34369109/e8d5f4ef-d2c0-4c5c-b5d6-8f0cc6096193)
![image](https://github.com/alibaba/ice/assets/34369109/a7ca33f0-b29a-4c80-b7de-a516d9a2f912)
主应用端口3333
子应用端口3002

### Expected behavior

在主应用中：和子应用一样能正常显示

### Version of ice.js

3.0

**Comment by ClarkXia** [comment]
关注下数据请求的地址，是不是走到子应用的服务上

**Comment by Gallado** [comment]
http://localhost:3333/mock-userList?pageNum=1&amp;pageSize=10&nbsp; &nbsp;目前看在主应用的端口上拉起
没有在子应用的端口 3002






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/ice"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月1日(星期四) 中午11:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/ice] 子应用vite-plugin-mock mock数据调不通 (Issue #6778)





 
关注下数据请求的地址，是不是走到子应用的服务上

**Comment by ClarkXia** [comment]
这个可以关注下 vite-plugin-mock 有没有类似的配置，或者在 dev 阶段可以通过环境变量等方式强制给所有请求加 baseUrl
