### ISSUE TITLE
global.css配置的样式未生效

### ISSUE THREAD

**Issue by Bingjiajia** [alibaba/ice#6783]
### Describe the bug

package.json 如下：
`{
  "name": "@ice/fusion-pro-scaffold",
  "version": "1.3.0",
  "description": "ice.js 3 Pro 模板（基于 Fusion Design）",
  "dependencies": {
    "@alifd/next": "^1.26.8",
    "@alifd/theme-design-pro": "^0.8.0",
    "@ice/runtime": "^1.4.0",
    "bizcharts": "^3.5.10",
    "moment": "^2.28.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@applint/spec": "^1.2.3",
    "@ice/app": "^3.4.0",
    "@ice/plugin-auth": "^1.0.0",
    "@ice/plugin-request": "^1.0.0",
    "@ice/plugin-store": "^1.0.0",
    "@types/react": "^18.0.0",
    "@types/react-dom": "^18.0.0",
    "@types/node": "^18.11.17",
    "eslint": "^8.35.0",
    "stylelint": "^15.2.0",
    "typescript": "^4.8.4"
  },
  "scripts": {
    "start": "ice start",
    "build": "ice build",
    "eslint": "eslint ./src --cache --ext .js,.jsx,.ts,.tsx",
    "eslint:fix": "npm run eslint -- --fix",
    "stylelint": "stylelint \"src/**/*.{css,scss,less}\" --cache",
    "stylelint:fix": "npm run stylelint -- --fix"
  },
  "publishConfig": {
    "access": "public"
  },
  "repository": "git@github.com:ice-lab/react-materials.git"
}`
问题描述：global.css配置的样式未生效
global.css代码如下：
`@import '@alifd/theme-design-pro/variables.css';
@import '@alifd/theme-design-pro/dist/next.var.css';

@import "@/scss/main.scss";

* {
  margin: 0;
  padding: 0;
}

body {
  margin: 0;
  padding: 0;
  -webkit-font-smoothing: antialiased;
}

#homepage {
  width: 100%;
  height: 100vh;
}

.next-loading {
  position: unset;
}
`

### Expected behavior

希望在global里面配置的样式生效

### Version of ice.js

ice3

### Content of build.json or ice.config.mts

```TypeScript
import { defineConfig } from '@ice/app';
import request from '@ice/plugin-request';
import store from '@ice/plugin-store';
import auth from '@ice/plugin-auth';

// The project config, see https://v3.ice.work/docs/guide/basic/config
const minify = process.env.NODE_ENV === 'production' ? 'swc' : false;
export default defineConfig(() => ({
  ssg: false,
  minify,
  plugins: [request(), store(), auth()],
  routes: {
    ignoreFiles: ['**/components/**'],
  },
  compileDependencies: false,
}));
```

**Comment by ClarkXia** [comment]
![image](https://github.com/alibaba/ice/assets/4219965/c4e02eb8-cdce-45c9-90b4-69f38b855704)
![image](https://github.com/alibaba/ice/assets/4219965/e9546c2c-2fde-4089-b2b2-741dd74280c8)
无法通过官方的 fusion-pro 复现，需要提供更加具体的复现步骤和说明

**Comment by Bingjiajia** [comment]
global.css 如下配置
`@import '@alifd/theme-design-pro/variables.css';
@import '@alifd/theme-design-pro/dist/next.var.css';

/*@import "@/scss/main.scss";*/

* {
  margin: 0;
  padding: 0;
}

body {
  margin: 0;
  padding: 0;
  -webkit-font-smoothing: antialiased;
}

#homepage {
  width: 100%;
  height: 100vh;
}

.next-loading {
  position: unset;
}`
调试时候样式没生效
