### ISSUE TITLE
为啥NPM上还是老版本

### ISSUE THREAD

**Issue by aspirantzhang** [alibaba/ice#6784]
### Describe the bug

为啥 npmjs 的最新的还是 3.3.9 版本，而 github 上已经是3.4.3
https://www.npmjs.com/package/@ice/app

### Expected behavior

-

### Version of ice.js

-

**Comment by ClarkXia** [comment]
由于 3.4.0 版本变动较大，这个属于我们的放量策略，新增的模版我们已经都修改了，如果用最新版本 可以设置成 ^3.4.0
