### ISSUE TITLE
[SSG] 打包后的html没有link css文件，而是通过js动态引入的css文件导致页面加载的时候只有dom结构没有样式

### ISSUE THREAD

**Issue by maskTAQ** [alibaba/ice#6786]
### Describe the bug

<img width="440" alt="image" src="https://github.com/alibaba/ice/assets/19301145/6f330e86-eb35-4814-8a5c-36943ac0c8b4">

之前的css文件在打包后是写在html文件中的，但是因为重新执行的npm i,打包后的产物就没有了，定位不到问题是出在哪个模块

### Expected behavior

ssg模式打包后能在html文件中引入css文件而不是通过js来引入

### Version of ice.js

2.6.6

**Comment by ClarkXia** [comment]
提供先复现 demo，另外 2.6.6 版本推荐升级到 3.x 版本

**Comment by ClarkXia** [comment]
推荐优先使用 3.x 版本，或者提供复现 demo 后重启 issue
