### ISSUE TITLE
[SSG] 打包后通过 example.com/test 可以访问 example.com/test/index.html 页面白屏

### ISSUE THREAD

**Issue by maskTAQ** [alibaba/ice#6787]
### Describe the bug

example.com/test/index.html 浏览器显示空白
但是访问example.com/test 是有内容的

### Expected behavior

期望 example.com/test/index.html 的页面结果跟 访问example.com/test 一致

### Version of ice.js

2.6.6

**Comment by ClarkXia** [comment]
关注下页面路由匹配规则，如果路由为 test，需要 nginx 等服务配置将 test 路径内容输出 test.html 即可，否则你路由配置就应该设置成 test.html

**Comment by ClarkXia** [comment]
先参考上述方式，如果还有其他问题可以再重开 issue
