### ISSUE TITLE
如何指定hot-update.json的请求host

### ISSUE THREAD

**Issue by justrustc** [alibaba/ice#6789]
我们的项目是微前端，我在尝试把子应用迁移到ice，除了热更新别的都没问题
举例：
访问https://developer.test.com/projecta，
在开发模式下基座会去加载localhost:3000，静态资源加载都没问题，但是加载hot-update.json的时候请求的https://developer.test.com/xxx.hot-update.json，
如何指定hot-update.json请求到localhost
我试了在 ice.config.mts 指定devPublicPath = 'http://localhost:3000/' 和 webpack config.devServer.devMiddleware.publicPath = 'http://localhost:3000/'
，都没用

**Comment by ClarkXia** [comment]
参考 https://webpack.js.org/configuration/dev-server/#websocketurl

**Comment by lxzy-yun** [comment]
我是用 xswitch 代理了这个 update.json，就可以在基座中热更新了
![image](https://github.com/alibaba/ice/assets/26783322/51d7ae18-e630-4cf1-a3a4-9cfdd59c5cd4)
