### ISSUE TITLE
ice v3 创建项目后启动异常

### ISSUE THREAD

**Issue by keleus** [alibaba/ice#6793]
### Describe the bug

- node:18.19.0

操作过程：
```shell
nvm use 18.19.0

npm create ice ice-test

// 选择Web Lite Scaffold

cd ice-test
pnpm install
pnpm start
```

页面打开，报错：

![image](https://github.com/alibaba/ice/assets/38204020/22091c3b-9ab9-4870-b0e2-efb12947a25f)

页面上`count+1`按钮点击无效

### Expected behavior

模板正常启动不要报错，点击正常

### Actual behavior

打开页面报错一闪而过，控制台打印了异常信息，下方页面按钮点击无效

![image](https://github.com/alibaba/ice/assets/38204020/673719e6-4d82-4789-9ad5-96735bc06160)

### Version of ice.js

3.4.0

### Content of build.json or ice.config.mts

```TypeScript
import { defineConfig } from '@ice/app';

// The project config, see https://v3.ice.work/docs/guide/basic/config
const minify = process.env.NODE_ENV === 'production' ? 'swc' : false;
export default defineConfig(() => ({
  // Set your configs here.
  minify,
  server: {
    onDemand: true,
    format: 'esm',
  },
}));
```

**Comment by ClarkXia** [comment]
先确保版本 @ice/app 3.4.3 @ice/runtime 1.4.1

**Comment by keleus** [comment]
> 先确保版本 @ice/app 3.4.3 @ice/runtime 1.4.1

1. 版本是你们脚手架模板决定的
2. lock文件里版本确实就是 `@ice/app 3.4.3 @ice/runtime 1.4.1`

**Comment by ClarkXia** [comment]
暂时无法复现，提供更多安装信息，比如 npm / pnpm 版本

**Comment by keleus** [comment]
> 暂时无法复现，提供更多安装信息，比如 npm / pnpm 版本

npm 10.2.3
pnpm 8.15.1

使用的淘宝源，初始化的项目里pnpm start 执行的是 ice start --speedup

**Comment by ClarkXia** [comment]
@keleus 如果生成了 lock 文件，可以将 lock 文件提供下

**Comment by cheqianxiao** [comment]
[reproduction repo](https://github.com/cheqianxiao/ice-test-6793-reproduction/tree/master)

**Comment by cheqianxiao** [comment]
[reproduction repo](https://github.com/cheqianxiao/ice-test-6793-reproduction/tree/master)

**Comment by cheqianxiao** [comment]
[reproduction repo](https://github.com/cheqianxiao/ice-test-6793-reproduction/tree/master) 

node: v18.19.0
npm: 10.2.3

**Comment by ClarkXia** [comment]
@cheqianxiao 你也是同样的问题？

**Comment by keleus** [comment]
> @keleus 如果生成了 lock 文件，可以将 lock 文件提供下

如下，由于github限制文件后缀名，下载后需要去掉`.txt`

[pnpm-lock.yaml.txt](https://github.com/alibaba/ice/files/14327235/pnpm-lock.yaml.txt)

**Comment by cheqianxiao** [comment]
> @cheqianxiao 你也是同样的问题？

是的

**Comment by ClarkXia** [comment]
> > @keleus 如果生成了 lock 文件，可以将 lock 文件提供下
> 
> 如下，由于github限制文件后缀名，下载后需要去掉`.txt`
> 
> [pnpm-lock.yaml.txt](https://github.com/alibaba/ice/files/14327235/pnpm-lock.yaml.txt)

使用 lock 恢复依旧无法复现，请再提供下系统信息

**Comment by keleus** [comment]
> > > @keleus 如果生成了 lock 文件，可以将 lock 文件提供下
> > 
> > 
> > 如下，由于github限制文件后缀名，下载后需要去掉`.txt`
> > [pnpm-lock.yaml.txt](https://github.com/alibaba/ice/files/14327235/pnpm-lock.yaml.txt)
> 
> 使用 lock 恢复依旧无法复现，请再提供下系统信息

@ClarkXia 
```
版本	Windows 11 专业工作站版
版本	23H2
操作系统版本	22631.3155
```
试试看不要走阿里内网？另外你们VSCode的插件现在安装后会要求登录你们内网？

**Comment by keleus** [comment]
补充：使用了`nvm-windows`，版本`1.1.10`

**Comment by ClarkXia** [comment]
试下
"@ice/runtime": "1.4.2-canary-5f11d4d35-20240222035641"
"@ice/app": "3.4.4-canary-5f11d4d35-20240222035641"

**Comment by keleus** [comment]
> 试下 "@ice/runtime": "1.4.2-canary-5f11d4d35-20240222035641" "@ice/app": "3.4.4-canary-5f11d4d35-20240222035641"

@ClarkXia 试了一下这个版本，问题修复了

**Comment by ClarkXia** [comment]
> > 试下 "@ice/runtime": "1.4.2-canary-5f11d4d35-20240222035641" "@ice/app": "3.4.4-canary-5f11d4d35-20240222035641"
> 
> @ClarkXia 试了一下这个版本，问题修复了

👍 下周一将发布正式版本

**Comment by ClarkXia** [comment]
fixed in @ice/runtime 1.4.2 @ice/app 3.4.4
