### ISSUE TITLE
通过小程序专用的模板创建项目启动失败

### ISSUE THREAD

**Issue by H5DevHoward** [alibaba/ice#6807]
根据官方文档 https://v3.ice.work/docs/guide/miniapp/start
$ npm create ice ice-app --template @ice/miniapp-scaffold
$ cd ice-app
$ npm install
![image](https://github.com/alibaba/ice/assets/17853595/b32997e1-b61e-43f8-9ca7-be2d4d0cd224)

依赖：
![image](https://github.com/alibaba/ice/assets/17853595/a909c98f-b156-4364-8078-394a40a518b2)

**Comment by ClarkXia** [comment]
小程序链路我们需要重新设计改造，目前投入优先级较低，建议先使用社区其他小程序方案
