### ISSUE TITLE
请问一下build-plugin-keep-alive有清理的配置吗？

### ISSUE THREAD

**Issue by dengying918** [alibaba/ice#6825]
### Describe the bug

  场景是这样的：Tab导航模式，切换导航时，会回到keepalive的页面，关闭该导航重新打开菜单时，需要重新mount

### Expected behavior

  场景是这样的：Tab导航模式，切换导航时，会回到keepalive的页面，关闭该导航重新打开菜单时，需要重新mount

### Version of ice.js

2.0

**Comment by ClarkXia** [comment]
暂时没有对应的配置，build-plugin-keep-alive 基于 react-activation，可以考虑自定义的实现
