### ISSUE TITLE
babelpulgins的配置不生效

### ISSUE THREAD

**Issue by WenDaaa** [alibaba/ice#6830]
### Describe the bug

antv内部依赖ml-matrix使用了新的语法，然后使用@babel/plugin-transform-private-methods进行转化未生效。
![image](https://github.com/alibaba/ice/assets/44088914/93141d7e-244e-49b9-ab68-d8e7dad00408)

### Expected behavior

预期正常运行无报错

### Version of ice.js

1.18.6

**Comment by ClarkXia** [comment]
编译 node_modules 需要额外配置 https://v2.ice.work/docs/config/about/#compiledependencies-
