### ISSUE TITLE
justify-content: end;  建议修改为justify-content: flxe-end;

### ISSUE THREAD

**Issue by flyrain917** [alibaba/ice#6839]
### Summary | 概述

在v1.27.8 的 input 的main.scss 里面 
```
#{$input-prefix}-textarea-control {
            display: flex;
            justify-content: end;
            padding: 0 $input-l-icon-padding-right 4px;
        }
```
实际项目的某些插件会识别报错: autoprefixer: end value has mixed support, consider using flex-end instead
建议修改为justify-content: flxe-end;

### Motivation | 背景

使用@alifd/nextv1.27.8  时 postcss-loader 暴露的问题

### Detailed design | 方案设计

justify-content: end;  建议修改为justify-content: flxe-end;

**Comment by ClarkXia** [comment]
fusion 组件问题，可以到 https://github.com/alibaba-fusion/next 提交
