### ISSUE TITLE
创建新项目，运行报错，还有就是创建新页面，也一直提示连接超时，没有设置代理

### ISSUE THREAD

**Issue by qyjandroid** [alibaba/ice#684]
## 环境信息

- 操作系统：
- Iceworks 版本： win 64

## 问题描述

创建新的项目，运行报错

## 错误信息
![image](https://user-images.githubusercontent.com/6645414/42357456-a197f1f0-810a-11e8-9a1e-104df8af0457.png)

**Comment by noyobo** [comment]
依赖 ice-scripts@1.5.5 新版本更新。解决运行报错问题，升级下依赖或者整体重装依赖。

 iceworks 没有代理功能，使用系统网路设置。

**Comment by qyjandroid** [comment]
可以了，谢谢
