### ISSUE TITLE
icejs 2.6.9，页面级store非vite模式下的项目仍然会报错

### ISSUE THREAD

**Issue by citrusyahello** [alibaba/ice#6840]
### Describe the bug

2.6.9目前只修复了vite模式下的项目报错，请问是否可以修复下非vite模式下的项目报错

Demo：https://github.com/citrusyahello/ice2-demo
启动后访问：http://localhost:3333/#/test-fn-component

![企业微信截图_17113474846648](https://github.com/alibaba/ice/assets/56066787/f095dd60-26b9-4d6a-a1b9-14cb09d862e0)

### Expected behavior

非vite模式下 页面store不报错

### Version of ice.js

2.6.9

### Content of build.json or ice.config.mts

```TypeScript
{
  "publicPath": "./",
  "vite": false
}
```

**Comment by ClarkXia** [comment]
推荐升级到 3.x 版本
