### ISSUE TITLE
npm run start:wechat报错 缺少 miniappManifest，请检查！

### ISSUE THREAD

**Issue by gnarace** [alibaba/ice#6845]
### Describe the bug

$ npm create ice ice-app --template @ice/miniapp-scaffold
$ cd ice-app
$ npm install
npm run start:wechat报错 缺少 miniappManifest，请检查！
<img width="745" alt="sadfds" src="https://github.com/alibaba/ice/assets/29112428/c720a037-6c97-4995-aed7-18dba6bd81e2">

### Expected behavior

正常运行npm run start:wechat命令

### Version of ice.js

3.4.6

**Comment by ClarkXia** [comment]
小程序链路目前没有投入维护，推荐使用社区其他方案
