### ISSUE TITLE
使用webpackPlugins打包报错

### ISSUE THREAD

**Issue by WenDaaa** [alibaba/ice#6851]
### Describe the bug

需要增加一个plugin，传入的一个正则表达式，然后加了以后报错
![image](https://github.com/alibaba/ice/assets/44088914/3e8314d7-10ff-4390-8b6a-aa77a248c19b)

### Expected behavior

希望可以正常运行

### Actual behavior

项目中引入@gradio/client报错 UnhandledSchemeError: Reading from "node:buffer" is not handled by plugins 根据这篇文章（[https://www.saoniuhuo.com/question/detail-2735070.html](https://www.saoniuhuo.com/question/detail-2735070.html)）的配置webpackplugin

### Version of ice.js

2.6.6

**Comment by ClarkXia** [comment]
应该是参数配置有问题，可以先通过自定义插件来添加 NormalModuleReplacementPlugin  https://v2.ice.work/docs/plugin/develop/build
