### ISSUE TITLE
在使用build-plugin-fusion的0.1.23版本发布指定物料的主题时，有些组件的样式缺失了

### ISSUE THREAD

**Issue by shiwofeiwo** [alibaba/ice#6854]
### Describe the bug

在使用build-plugin-fusion的0.1.23版本发布指定物料的@alifd/theme-x主题时，有些fusion/next组件的样式缺失了(例如Step, Rating)

### Expected behavior

生成的css中应该包含所有@alifd/theme-x的中所有的样式

### Version of ice.js

2.x

**Comment by ClarkXia** [comment]
提供复现 demo 方便排查

**Comment by shiwofeiwo** [comment]
复现demo
[https://codesandbox.io/p/devbox/test-materials-z58tgz?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clut34iyz0007356jbbm6xahx%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clut34iyy0002356jcovsi2ms%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clut34iyy0004356jomadn8pw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clut34iyy0006356jr0pd1tje%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B66.00091959308006%252C33.999080406919944%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clut34iyy0002356jcovsi2ms%2522%253A%257B%2522id%2522%253A%2522clut34iyy0002356jcovsi2ms%2522%252C%2522activeTabId%2522%253A%2522clut3k0zw008y356j4rjtmwmw%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clut34iyx0001356jjfr3sgny%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpnpm-lock.yaml%2522%252C%2522id%2522%253A%2522clut3k0zw008y356j4rjtmwmw%2522%252C%2522mode%2522%253A%2522temporary%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clut34iyy0006356jr0pd1tje%2522%253A%257B%2522id%2522%253A%2522clut34iyy0006356jr0pd1tje%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clut34iyy0004356jomadn8pw%2522%253A%257B%2522id%2522%253A%2522clut34iyy0004356jomadn8pw%2522%252C%2522activeTabId%2522%253A%2522clut36n8x0074356jkalhixlk%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clut36n8x0074356jkalhixlk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clut36nl401bgdkec8bwafw1m%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D](url)

**Comment by ClarkXia** [comment]
https://github.com/alibaba/ice/blob/825afd2761b9407b66250b884578a3c158f2a85b/packages/plugin-fusion/src/index.js#L356 umd 打包默认就是忽略样式注入的

**Comment by shiwofeiwo** [comment]
> https://github.com/alibaba/ice/blob/825afd2761b9407b66250b884578a3c158f2a85b/packages/plugin-fusion/src/index.js#L356
> 
> umd 打包默认就是忽略样式注入的

请问我要怎么配置才能让view.css里存在指定theme的fusion/next样式呢
