### ISSUE TITLE
构建后的build 文件 点击index.html 直接访问提示路径报错

### ISSUE THREAD

**Issue by dengying918** [alibaba/ice#6862]
### Describe the bug

构建后的build 文件 点击index.html 直接访问提示路径报错
<img width="965" alt="企业微信截图_17128887018580" src="https://github.com/alibaba/ice/assets/99648444/5b8c52c8-a041-4aca-a289-ae47fff92592">

### Expected behavior

构建后的build 文件 点击index.html 直接访问提示路径报错
<img width="965" alt="企业微信截图_17128887018580" src="https://github.com/alibaba/ice/assets/99648444/5b8c52c8-a041-4aca-a289-ae47fff92592">

### Version of ice.js

3.0

**Comment by ClarkXia** [comment]
参考 https://v3.ice.work/docs/guide/basic/config/#publicpath
window 下可以试试将 publicPath 设置成 ./，如果最终是要部署到服务器的，需要配置成部署的服务器地址

**Comment by dengying918** [comment]
路由设置为 hash 这样静态页面访问就没问题了
