### ISSUE TITLE
pageConfig.title能继承父级配置

### ISSUE THREAD

**Issue by xmsz-stu** [alibaba/ice#6888]
### Motivation | 背景

```
router : {
   path:"/a",
   pageConfig: {title:"a"},
   children: [{path: "/b'}]
}
```
用户访问a/b的时候，标题还是默认的，不是a

### Detailed design | 方案设计

希望能够继承父级的配置
不能每个子页面设置都很麻烦

**Comment by ClarkXia** [comment]
什么版本，目前 3.0 如果 layout 上有 title，具体页面不设置的话 以 layout 为准

**Comment by xmsz-stu** [comment]
> 什么版本，目前 3.0 如果 layout 上有 title，具体页面不设置的话 以 layout 为准

2.x

**Comment by ClarkXia** [comment]
2.x 目前没有这个逻辑，可以通过中心化配置路由文件的方式降低这块的维护成本

**Comment by xmsz-stu** [comment]
> 2.x 目前没有这个逻辑，可以通过中心化配置路由文件的方式降低这块的维护成本

那2.x还会更新吗
我现在就是在route.ts配置，但是会遇到很多需要重复配置

**Comment by ClarkXia** [comment]
2.x 没有重大 bug 的情况下 不会更新了，另外也推荐升级 3.x 看看效果
