### ISSUE TITLE
如果组件包含const a = [] 热更新会失效

### ISSUE THREAD

**Issue by xmsz-stu** [alibaba/ice#6904]
### Describe the bug

```
const a = []
export default () => {
  return <div>2</div>;
};


```
热更新就失效了，必须刷新页面

但是如果我把a=[] 放在其他页面，然后引入就正常

不确定是否和这个问题有关https://github.com/vitejs/vite/discussions/4577

### Expected behavior

正常热更新

### Version of ice.js

2.x

**Comment by ClarkXia** [comment]
热更新依赖具名函数，不能是匿名函数
