### ISSUE TITLE
appts中无法正确的使用history

### ISSUE THREAD

**Issue by sunshineLi2019** [alibaba/ice#6908]
### Describe the bug

```js 
export const requestConfig = defineRequestConfig({
  baseURL: "/api",
  // withCredentials: true,
  // 拦截器
  interceptors: {
    response: {
      onError: (error) => {
        if (error.response && error.response.status === 500) {
          history.pushState(null, "", "/login");
        }
        return Promise.reject(error);
      },
    },
  },
});
```
我期望在所有的请求中,当token失效的时候跳转到登录页,然而history在appts中是未加载的null.
![image](https://github.com/alibaba/ice/assets/54090374/e4cbf07a-9ffc-4785-814a-d9d17a9ce4a9)
我使用了官方文档的处理方式
```js
import { history } from "ice";

export function linkto(link: string) {
  
  if (history !== null) {
    // 在这里使用 myHistory 变量
    history.push(link);
  }
}
```

### Expected behavior

我期望获取到history

### Actual behavior

实际上仍然为null.
我现在只能使用原生js的history进行路由跳转,但是这并不优雅.
我希望获取到合适的解决方案.用于处理当token失效的时候跳转到登录页这个需求.

### Version of ice.js

3.4.8

### Content of build.json or ice.config.mts

```js
import { defineConfig } from "@ice/app";
import request from "@ice/plugin-request";
import store from "@ice/plugin-store";
import auth from "@ice/plugin-auth";
import i18n from "@ice/plugin-i18n";
import antd from "@ice/plugin-antd";
// The project config, see https://v3.ice.work/docs/guide/basic/config
const minify = process.env.NODE_ENV === "production" ? "swc" : false;
export default defineConfig(() => ({
  ssg: false,
  minify,
  routes: {
    ignoreFiles: [
      "**/pages/**", 
      "**/components/**", 
      "**/services/**",
    ],
  },
  plugins: [
    request(),
    store(),
    auth(),
    i18n({
      locales: ["zh-CN"],
      defaultLocale: "zh-CN",
    }),
  ],
  compileDependencies: false,
}));

```

**Comment by sunshineLi2019** [comment]
> 补充下 ice.config.mts 配置

你好,已经更新了信息

**Comment by sunshineLi2019** [comment]
@ClarkXia 
![image](https://github.com/alibaba/ice/assets/54090374/5fb5c39b-d7b0-46b3-bfbe-479ecbcb1d52)
当我使用defineDataLoader的时候页面会加载两次,无法正确的获取到history.
当我在app.ts请求拦截defineDataLoader的请求的时候history无法正确加载,其他页面的请求可以正确的使用history进行跳转

**Comment by ClarkXia** [comment]
@sunshineLi2019 dataLoader 仅打包请求相关逻辑，因此入口 history 初始化等逻辑均未执行，后续我们在文档中标注下

**Comment by xianghongai** [comment]
> [@sunshineLi2019](https://github.com/sunshineLi2019) dataLoader 仅打包请求相关逻辑，因此入口 history 初始化等逻辑均未执行，后续我们在文档中标注下

如果在 `app.ts` 中通过 defineDataLoader 触发 API 401，然后通过 ice history 跳转到 Login，不能实现？
