### ISSUE TITLE
speedup 模式下支持 after.start.compile

### ISSUE THREAD

**Issue by ClarkXia** [alibaba/ice#6915]
### Describe the bug

speedup 模式下目前 after.start.compile 的钩子不会被执行

### Expected behavior

speedup 模式下支持 after.start.compile

### Version of ice.js

3.4.9

**Comment by songjiafan** [comment]
跟一个issue speedup模式下不支持配置compileDependencies 字符串和正则都会报错

**Comment by ClarkXia** [comment]
已确认 目前 hooks 是对齐的
