### ISSUE TITLE
KeepAliveOutlet能否去掉外层的div

### ISSUE THREAD

**Issue by oneQiu** [alibaba/ice#6924]
我看KeepAliveOutlet的实现类似antd的tabs组件，将它挂载到了另外的div上面，但是这样做具有破坏性会影响到内部组件的样式。

至少说当前可见的组件不需要这层div。

![image](https://github.com/alibaba/ice/assets/50658231/93d94fa4-fdbd-45b6-b904-dbdc7e128f45)

**Comment by ClarkXia** [comment]
现在其实有两种模式去使用 keep alive，https://github.com/alibaba/ice/blob/master/packages/runtime/src/KeepAliveOutlet.tsx#L6

如果通过 React 内置支持的（19 版本），则不会有额外元素
如果是目前的实现 这一层用于控制显示隐藏，是必须的
