### ISSUE TITLE
如何打包单个html文件

### ISSUE THREAD

**Issue by oneQiu** [alibaba/ice#6928]
如何打包单个html文件，或者说能在首次就让js文件都加载完，我们的服务是部署在国外的，开了cdn还是比较慢的，首次进入没什么问题，但是切路由的时候就会导致页面卡住，因为他要重新加载新的js文件，这个多html文件模式并不适用所有的项目，希望能给个配置方式关掉

**Comment by ClarkXia** [comment]
https://v3.ice.work/docs/guide/basic/config#codesplitting 关闭 codeSpliting

**Comment by oneQiu** [comment]
> https://v3.ice.work/docs/guide/basic/config#codesplitting 关闭 codeSplitting

好像关了还是会打包成多个。
![image](https://github.com/alibaba/ice/assets/50658231/0046557d-51d3-45fb-ac56-5358e8dcf032)
![image](https://github.com/alibaba/ice/assets/50658231/42d27107-1cdc-4651-bd38-f800b112b0e1)
![image](https://github.com/alibaba/ice/assets/50658231/37c34de4-aa01-41c7-b215-70324657523e)

**Comment by ChaseWindYoungs** [comment]
我的也是，配置了codeSplitting为false，还是会打出很多的html文件
