### ISSUE TITLE
Iceworks 新建页面时不应该默认选中第一个 layout

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#693]
## 环境信息

- 操作系统：
- Iceworks 版本： 

## 错误信息

![image](https://user-images.githubusercontent.com/3995814/42491665-5808c546-8448-11e8-9776-2680d78235b3.png)

**Comment by noyobo** [comment]
是报错。还是不要这个功能，如果报错，解决这个报错的问题。 

同时可以支持不选择？ 是这样吗？

**Comment by chenbin92** [comment]
@noyobo  现在的实现是不同的物料源的layout都会在这里展示处理，但是不同物料源的layout不是通用的，也就说 A 物料源的 layout 放在 B 物料源的模板就会出错。

我的建议是按照物料源进行区分 layout，并且默认不要选中第一个

**Comment by FairyEver** [comment]
在集成第三方的物料库的时候我主要遇到了这几个问题

* 新的物料库设计规范和通用的 vue 物料不符合，比如说我新建了一套物料，这套物料的组件库和 ice 提供的现有组件库不是一个（比方说通用的是element，而新的脚手架使用的是iview这种情况），用户混合后效果肯定不好。
* 新的物料库的 layout 和 ice 目前提供的物料设计不符合，比如新的脚手架里提供的有一个为这个脚手架高度耦合的一个布局组件，ice 自带的布局组件就无法在这个新的脚手架上使用。

总结建议：是否可以在通用选项的基础上，如果物料库需要，为物料库提供自己的一套物料选项（布局，物料），最后达到的效果是使用 A 物料脚手架搭建的项目时，新建页面的时候用户看不到通用物料库和其它物料的物料库（如果A物料脚手架可以设置过某个参数），达到设计风格和代码上物料和脚手架统一。

**Comment by zzfjing** [comment]
我也碰到类似问题。
1 我已经选了项目模板里面带有布局了。当添加页面时候，没有意识到，还可以再变布局。（有默认选中布局）。--这里我个人觉得可以加上提示之类的。
2 当添加页面的布局和原来的布局有冲突（名字一样）。导致原来的布局失效。我碰到的是header突然变了。对比半天才发现是同名导致。我觉得这里是个bug。

**Comment by chenbin92** [comment]
@zzfjing  这周的版本会解决

**Comment by noyobo** [comment]
v2.5.0 fixed
