### ISSUE TITLE
文档-关于页面多个链接失效

### ISSUE THREAD

**Issue by chenbihao** [alibaba/ice#6931]
### Describe the bug

文档-关于页面多个链接失效 

例如：
- appworks.site 整个站点无效
- https://pkg.ice.work/scenarios/react
- https://ice.work/docs/resource/front-basic 前端基础知识

### Expected behavior

文档能正常访问

### Version of ice.js

docs

**Comment by ClarkXia** [comment]
访问具体哪个地址，我们更新下链接

**Comment by chenbihao** [comment]
> 访问具体哪个地址，我们更新下链接

关于页面：  https://v3.ice.work/docs/guide/about

**Comment by chenbihao** [comment]
https://v3.ice.work/ 的插件化卡片也失效了 ：https://v3.ice.work/docs/plugins/plugin-dev
