### ISSUE TITLE
能否配置只生成一个index.html

### ISSUE THREAD

**Issue by oneQiu** [alibaba/ice#6932]
目前是根据路由生成，我猜是为了避免404的问题，但是我们nginx已经配置了重定向了，能否只需要生成一个html。

目前是想htmlGenerating关闭，然后自己再去改webpack加一个htmlwebpackplugin？

**Comment by ClarkXia** [comment]
生成多个 html 是目前分包的情况下，每个路由的资源不同，如果没有性能优化诉求，可以只需要在页面中加入 entry（assets-manifest 中可以查看） 相关资源
