### ISSUE TITLE
iceworks安装失败

### ISSUE THREAD

**Issue by jpxgkh** [alibaba/ice#694]
## 环境信息

- 操作系统： win7 sp1
- Iceworks 版本： 2.3.1

## 问题描述

安装程序双击之后进度条走着走着就提示windows找不到文件
## 错误信息
C:\Windows\System32\config\systemprofile\AppData\Local\program...\Iceworks.exe
请确定文件名是否正确后再试一次

是操作系统的原因吗？

**Comment by noyobo** [comment]
可以有截图看下么？

的安装地址是在用户目录下。

**Comment by jpxgkh** [comment]
![qq 20180710144202](https://user-images.githubusercontent.com/16203995/42493499-dac57e64-844f-11e8-83b7-dfa3691e80fa.png)

我从飞冰官网下的安装程序，放在桌面双击安装他自己开始跑了，进度条走着走着就变这样了。
总不会跟环境变量有关吧？

希望大佬解惑

**Comment by noyobo** [comment]
这边测试 windows 都没有复现该情况，你的  C 盘容量还有剩余空间么？

**Comment by jpxgkh** [comment]
我也很无奈，c盘还有80+G的空间，我安装包是放在桌面上的。会跟环境变量或者默认安装路径有关吗？

**Comment by noyobo** [comment]
应该没有关系，这种情况看起来像是安装的过程中文件被删除了。  有尝试过别的地方存放吗

**Comment by noyobo** [comment]
最新版  2.5.2 再尝试安装下？

**Comment by jpxgkh** [comment]
嗯，在同事电脑上安装完2.3+的版本然后把文件夹copy过来自己电脑放到跟他安装完一样的路径之后现在能用了。。。但是前段时间我试着更新最新的版本，更新完进去还是2.3+。。。我一会试试2.5.2的，谢谢您还记着这个issue
