### ISSUE TITLE
icejs3.x微应用接入icejs2.x主应用问题

### ISSUE THREAD

**Issue by dlpuzhangyue** [alibaba/ice#6944]
### Describe the bug

1. 3.x微应用setLibraryName('child');报错
<img width="983" alt="image" src="https://github.com/alibaba/ice/assets/29819173/027904c2-bac3-4b2f-9c1a-4e7d9ed8d7b0">
2. ice3.x构建仅支持cjs，esm，而其他主/微应用均使用webapck配置生成umd产物。导致ice3.x无法接入
<img width="769" alt="image" src="https://github.com/alibaba/ice/assets/29819173/2139c7d2-77dc-4e59-9e38-be9627cfd422">
根据返回的错误链接https://micro-frontends.ice.work/error/?code=1&arg=/ireport查看获得信息，ice3.x版本构建esm产物与连接中图中有些许差异，不知是否是此原因导致

### Expected behavior

想知道 ice.3x能否做为微应用接入ice2.x主应用当中 可以的话能否提供一个demo

### Version of ice.js

3.4.0

**Comment by dlpuzhangyue** [comment]
其他主/微应用均使用icestark生成 icejs版本2.9.6

**Comment by ClarkXia** [comment]
setLibraryName 是往 window 上挂变量，看执行是在 服务端报错，确保 setLibraryName 仅在 client 端执行即可

**Comment by dlpuzhangyue** [comment]
> setLibraryName 是往 window 上挂变量，看执行是在 服务端报错，确保 setLibraryName 仅在 client 端执行即可

该应开始3.x 默认开始ssg的原因 还有在serve配置format： 'esm'后构建产物看着像umd

<img width="1654" alt="image" src="https://github.com/alibaba/ice/assets/29819173/dc0e7244-237b-4ee5-b90a-a6dc9e39f102">

**Comment by ClarkXia** [comment]
可以增加环境判断处理
```js
if (import.meta.renderer === 'client') {
  setLibraryName('xxx')
}
```
