### ISSUE TITLE
examples/with-first-chunk-cache-ssr，浏览器访问没有缓存首chunk

### ISSUE THREAD

**Issue by tsy77** [alibaba/ice#6948]
### Describe the bug

本地启动examples/with-first-chunk-cache-ssr，走了正常的流失渲染，但是没有缓存的逻辑，是否携带FirstChunkCache表现一致

### Expected behavior

首chunk缓存

### Version of ice.js

3.4.10

**Comment by ClarkXia** [comment]
缓存逻辑需要跟端（ER）配合
