### ISSUE TITLE
关于在飞冰上开发前端程序的源代码问题

### ISSUE THREAD

**Issue by france24365** [alibaba/ice#6949]
一、开发需求：
1、通过飞冰无代码开发一个APP。主要用于在公司内部定期发布一些工作任务和数据统计，由相关责任人通过互动文档，在时限内给与回复。第一阶段非常简单，能够实现上述功能即可。后续再增加其他功能；
2、在一阶段开发过程中，我们需要源代码。以便于后期我们可以通过低代码方式参与到新功能开发、维护优化等工作中。
二、询问事由：
1、之前没有接触过飞冰，针对一阶段这样相对简单的功能，是我们通过页面操作自己完成还是由你们专业人员完成？
2、这样的需求，如何收费？
3、是否能提供源代码？

谢谢。我的电话是13005439456，可以直接和我联系。

**Comment by ClarkXia** [comment]
飞冰所有代码开源，通过开源社区形式运作，暂时不提供商业化形式的咨询服务

**Comment by france24365** [comment]
在开发过程中，如果有需要咨询的问题，能有指定的对接人员吗？

**Comment by ClarkXia** [comment]
走开源协作方式即可
