### ISSUE TITLE
刚搭建微前端项目 起主应用

### ISSUE THREAD

**Issue by sgfily** [alibaba/ice#6968]
![image](https://github.com/user-attachments/assets/a57b7072-17f8-4e3c-bb0d-947b718a2619)
比如上述 Shell里面各种失效组件 

另外 history push 也会报警告react18移除 相关 麻烦解答下

**Comment by sgfily** [comment]
![image](https://github.com/user-attachments/assets/f22c6dd5-d7a6-49c5-bac0-2847e83914d1)

**Comment by ClarkXia** [comment]
主要是一些基础组件对于 react 18 API 兼容问题，我们升级下底层依赖

**Comment by sgfily** [comment]
> 主要是一些基础组件对于 react 18 API 兼容问题，我们升级下底层依赖

你好，那你这边大概什么时候升级依赖 我这边已经做了一些事情 想看下怎么做升级。
另外关于微前端的部分文档 感觉也不是很全。，
切换环境变量 我现在用的--mode local/development/production的方式 不知道对不对，文档中没有关于模式切换的说明

**Comment by ClarkXia** [comment]
这个主要是底层依赖 fusion 组件的问题，你可以考虑换成 antd

**Comment by sgfily** [comment]
> 这个主要是底层依赖 fusion 组件的问题，你可以考虑换成 antd

你们现在放弃fusion了吗 换成antd的话 整体的变动比较大吧

**Comment by ClarkXia** [comment]
@sgfily 不是我们放弃 fusion  是 fusion 迭代太慢
