### ISSUE TITLE
Button动画没有效果，官网在线例子隔离模式

### ISSUE THREAD

**Issue by farzer** [alibaba/ice#697]
## 环境信息

- 操作系统：OSX
- Iceworks 版本： 0.2.3

## 问题描述
按钮点击没有产生动画效果，官网一般模式有动画效果，隔离模式没有动画效果

**Comment by wssgcg1213** [comment]
在项目中如果需要启用这个动效, 可以在 `index.js`  中加入

```
import '@icedesign/skin/override.js';
```

站点中会去除这个动效以免造成困扰.

**Comment by farzer** [comment]
好的，多谢。这个可以写入button的文档。我找了好一会也找不到呢
