### ISSUE TITLE
使用request 后无法正常访问页面

### ISSUE THREAD

**Issue by 814372978** [alibaba/ice#6972]
### Describe the bug

![image](https://github.com/user-attachments/assets/fbe93e22-014e-40bc-965a-39dbec964812)
![image](https://github.com/user-attachments/assets/741fb682-d966-4b53-826c-7f26d9ddcf3a)

### Expected behavior

无法正常的访问页面

### Actual behavior

![image](https://github.com/user-attachments/assets/81a4299f-1daa-4621-88f2-391909b6eaed)
初始化项目  安装 request 插件
网络请求是可选能力，在使用前需要单独安装 @ice/plugin-request 插件。

npm i @ice/plugin-request -D

在配置文件中添加插件：

ice.config.mts
import { defineConfig } from '@ice/app';
import request from '@ice/plugin-request';

export default defineConfig(() => ({
  plugins: [
    request(),
  ],
}));
之后出现问题

### Version of ice.js

3

**Comment by ClarkXia** [comment]
内部插件和项目走答疑
