### ISSUE TITLE
react dom 本地package化

### ISSUE THREAD

**Issue by farzer** [alibaba/ice#698]
## 环境信息

- 操作系统：OSX
- Iceworks 版本： lastest

## 问题描述

看了一下是阿里的cdn，如何本地化该包？因为有时候开发的时候没有网络

**Comment by noyobo** [comment]
https://github.com/alibaba/ice/wiki/%E7%A6%BB%E7%BA%BF%E5%8C%96%E6%9E%84%E5%BB%BA%E9%A1%B9%E7%9B%AE
