### ISSUE TITLE
icejs v3.4.0 使用其他webpack插件时，start异常

### ISSUE THREAD

**Issue by wangchongwei** [alibaba/ice#6996]
### Describe the bug

<img width="1131" alt="image" src="https://github.com/user-attachments/assets/fadbeab4-c483-481b-a179-8ae245c95e3d">
⠙ loading config...<e> [webpack-dev-middleware] [Error:   × TypeError: The 'compilation' argument must be an instance of Compilation
<e>   │     at Function.getCompilationHooks (/Users/justin.wang/workspace/master/scb-webapp/node_modules/@ice/bundles/compiled/webpack/bundle.js:78434:10)
<e>   │     at Object.fn (/Users/justin.wang/workspace/master/scb-webapp/node_modules/@univerjs/webpack-plugin/lib/index.js:117:37)
<e>   │     at SyncHook.callAsyncStageRange (/Users/justin.wang/workspace/master/scb-webapp/node_modules/@ice/bundles/compiled/@rspack/core/dist/lite-tapable/index.js:207:21)
<e>   │     at SyncHook.callStageRange (/Users/justin.wang/workspace/master/scb-webapp/node_modules/@ice/bundles/compiled/@rspack/core/dist/lite-tapable/index.js:225:14)
<e>   │     at QueriedHook.call (/Users/justin.wang/workspace/master/scb-webapp/node_modules/@ice/bundles/compiled/@rspack/core/dist/lite-tapable/index.js:186:26)
<e>   │     at function (/Users/justin.wang/workspace/master/scb-webapp/node_modules/@ice/bundles/compiled/@rspack/core/dist/Compiler.js:800:25)
<e>   │     at last.function (/Users/justin.wang/workspace/master/scb-webapp/node_modules/@ice/bundles/compiled/@rspack/core/dist/Compiler.js:782:19)
<e>   │ 
<e> ] {
<e>   code: 'GenericFailure'
<e> }

### Expected behavior

想使用@univerjs 在线电子表格，需要新增一个plugin
webpack: (webpackConfig) => {
    webpackConfig.plugins?.push(new UniverPlugin());
    return webpackConfig;
  },

此时执行 npm start即会异常，异常如上面提供的截图所示

### Version of ice.js

3.4.0

### Content of build.json or ice.config.mts

```TypeScript
import { defineConfig } from '@ice/app';
import store from '@ice/plugin-store';
import auth from '@ice/plugin-auth';
import { UniverPlugin } from '@univerjs/webpack-plugin'

export default defineConfig(() => ({
  publicPath: '/',
  hash: 'contenthash',
  proxy: {
    '/rest': {
      enable: true,
      target: 'http://loan-webapp-dev.zerofinance.net',
      changeOrigin: true,
    },
    '/cas': {
      enable: true,
      target: 'http://loan-webapp-dev.zerofinance.net',
      changeOrigin: true,
    },
    '/token': {
      enable: true,
      target: 'http://loan-webapp-dev.zerofinance.net',
      changeOrigin: true,
    },
  },
  // TypeScript 类型检测
  tsChecker: false,
  plugins: [
    store(),
    auth(),
  ],
  webpack: (webpackConfig) => {
    webpackConfig.plugins?.push(new UniverPlugin());
    return webpackConfig;
  },
  ssr: false,
  ssg: false,
  routes: {
    // 忽略 src/pages 下所有 components 目录
    ignoreFiles: ['**/components/**', '**/*Dialog.tsx', '**/dialog*.tsx'],
  },
  compileDependencies: false
}));
```

**Comment by ClarkXia** [comment]
该插件与 rspack 不兼容，考虑关闭 speedup 模式

**Comment by wangchongwei** [comment]
> 该插件与 rspack 不兼容，考虑关闭 speedup 模式

关闭 speedup  已可以正常运行
