### ISSUE TITLE
can't open the link

### ISSUE THREAD

**Issue by zxhycxq** [alibaba/ice#7]
http://gitlab.alibaba-inc.com/ice/notes/issues/480

内部链接？

**Comment by wssgcg1213** [comment]
sorry, forget to clean up; 

这里面主要是对使用 react-router@3.x 构建单页应用的描述, 后续我们会把这些文档成体系放出, 现在可以参考一下开源社区里对 react-router 的使用 case, 用法都是大同小异的

**Comment by wssgcg1213** [comment]
ref: 
> https://github.com/ReactTraining/react-router/tree/v3/docs
> cn translation: https://react-guide.github.io/react-router-cn/
