### ISSUE TITLE
预览服务hang

### ISSUE THREAD

**Issue by SLRXXX** [alibaba/ice#70]
点击“预览页面”后，弹出框中一直是“预览服务启动中”
退出后，项目一直处在“调试服务启动中”的状态
osx

**Comment by yujiangshui** [comment]
预览实际的实现是在背后起了项目的调试服务，并生成临时文件。看起来的确是在启动中。

可以麻烦你再试下先在项目里『启动调试服务』等待显示本地 ip 之后，再创建页面预览一下看看？有可能是性能问题感觉像是卡住了。

**Comment by SLRXXX** [comment]
先点“启动调试服务”也是一样的，的确是卡在了“调试服务”上
关于性能……机器是普通的osx机器，可能会慢一点，但不应该卡住

**Comment by SLRXXX** [comment]
建议给个选项，可以查看控制台输出，这样也方便查看信息，毕竟面向的用户群体也是偏前端的

**Comment by yujiangshui** [comment]
那这个估计是报错了。可以先升级下最新版 iceworks 0.1.4 然后重新创建一个项目试下。
还有问题可以到上面『帮助』里面菜单找到运行日志贴过来。

查看控制台输出的功能，已经列到我们正式版中，感谢反馈。

**Comment by yujiangshui** [comment]
@SLRXXX 正式版已经发布，查看控制台输出功能已经添加，可以升级尝试，如有问题再反馈感谢。
