### ISSUE TITLE
打包的时候如何加载推送到远程的静态资源

### ISSUE THREAD

**Issue by oneQiu** [alibaba/ice#7003]
1. 比如我的静态资源推送到了oss上，这个时候我需要把html的js,css的本地引用改掉，有没有什么办法。
2. 我开启了codesplit以后，js就特别多，我自己很难知道哪个html里面要加载哪个js

**Comment by ClarkXia** [comment]
配置 publicPath，配置内容就是你推送的 OSS 位置
