### ISSUE TITLE
无网环境下icon显示不出来？

### ISSUE THREAD

**Issue by echolxltf** [alibaba/ice#7005]
### Describe the bug

1、在无网环境下icon显示不出来；
2、如何下载icon以及样式内置进去？

### Expected behavior

无

### Version of ice.js

2.x

**Comment by ClarkXia** [comment]
v2 参考文档 https://v2.ice.work/docs/plugin/list/css-assets-local

**Comment by echolxltf** [comment]
目前用的v3，按照文档https://v3.ice.work/docs/guide/advanced/css-assets-local 进行配置，依然没有效果，icon图标还是加载不出来

**Comment by echolxltf** [comment]
目前用的v3，按照文档https://v3.ice.work/docs/guide/advanced/css-assets-local 进行配置，依然没有效果，icon图标还是加载不出来， @ClarkXia

**Comment by ClarkXia** [comment]
提供下配置文件 ice.config.mts

**Comment by echolxltf** [comment]
已解决，两种方式，本地开发无网和有网的两种情况
![image](https://github.com/user-attachments/assets/3871f3fd-0faa-4968-9f6e-ee0b304ddbdd)
