### ISSUE TITLE
ice2 keep-alive 可否支持，页面回退时，滚动条不置顶

### ISSUE THREAD

**Issue by wh1teYu** [alibaba/ice#7011]
### Describe the bug

ice2 keep-alive 可否支持，页面回退时，滚动条不置顶

### Expected behavior

ice2 keep-alive 可否支持，页面回退时，滚动条不置顶

### Version of ice.js

2.6.10

**Comment by ClarkXia** [comment]
默认根据页面切换时内容高度决定，如果有类似诉求，可以在代码层面进行滚动条位置的记录，待页面重新激活后滚到到记录位置
