### ISSUE TITLE
主应用中，如何使用KeepAliveOutlet来进行页面缓存？（切换不同的微应用时）

### ISSUE THREAD

**Issue by yyyyffqqqq** [alibaba/ice#7012]
### Describe the bug

主应用跳转到的A微应用， 再切换到微应用B， 在A应用使用的KeepAliveOutlet进行缓存的页面，就是失效

### Expected behavior

不同微应用互相切换也能缓存页面

### Version of ice.js

"@ice/app": "3.4.12"

**Comment by ClarkXia** [comment]
微前端的缓存参考 https://micro-frontends.ice.work/docs/api/ice-stark/#cached
