### ISSUE TITLE
terser 关闭 commets 打包报错 

### ISSUE THREAD

**Issue by wh1teYu** [alibaba/ice#7015]
### Describe the bug

  "minify": {
    "type": "terser",
    "options": {
      "compress": {
        "unused": true,
        "drop_console": true
      },
      "format": {
        "comments": false
      }
    }
  },

### Expected behavior

希望打包可以正常

### Version of ice.js

2.6.10

**Comment by wh1teYu** [comment]
RR! js/MiddleQuaTopic.9cbdad.js from Terser
ERR! Error: Please only specify either output or format option, preferrably format.
ERR! 
ERR! js/Maintenance.9cbdad.js from Terser
ERR! Error: Please only specify either output or format option, preferrably format.
ERR! 
ERR! js/OrderList.9cbdad.js from Terser
ERR! Error: Please only specify either output or format option, preferrably format.
ERR! 
ERR! js/HighDetail.9cbdad.js from Terser
ERR! Error: Please only specify either output or format option, preferrably format.
ERR! 
ERR! js/MiddleDefTopic.9cbdad.js from Terser
ERR! Error: Please only specify either output or format option, preferrably format.
ERR! 
ERR! js/Logins.9cbdad.js from Terser
ERR! Error: Please only specify either output or format option, preferrably format.
ERR! 
ERR! js/Calculator.9cbdad.js from Terser
ERR! Error: Please only specify either output or format option, preferrably format.
ERR! 
ERR! js/OrderDetail.9cbdad.js from Terser
ERR! Error: Please only specify either output or format option, preferrably format.
ERR! 
ERR! js/CalculatorResult.9cbdad.js from Terser
ERR! Error: Please only specify either output or format option, preferrably format.
ERR! 
ERR! js/CalculatorSelection.9cbdad.js from Terser
ERR! Error: Please only specify either output or format option, preferrably format.
ERR! 
ERR! js/RankingList.9cbdad.js from Terser
ERR! Error: Please only specify either output or format option, preferrably format.

**Comment by ClarkXia** [comment]
https://github.com/alibaba/ice/blob/55e7259e8186bc9d03551b0bc6528e7719186b1f/packages/build-user-config/src/userConfig/minify.js#L74

这里是一个合并逻辑，ouput 和 format 同时存在了，简单配置无法满足的场景可以通过插件方式定制下
