### ISSUE TITLE
ice start --https启动项目未使用系统信任的ca证书

### ISSUE THREAD

**Issue by karthest** [alibaba/ice#7020]
### Describe the bug

系统 : macos Sequoia 15.1
问题描述 : 使用mkcert生成自签名ca证书，添加至钥匙串并设置信任。使用ice start --https启动项目，效果如图：
<img width="696" alt="image" src="https://github.com/user-attachments/assets/39275991-7f92-4176-a7dd-58c962ef4f27">
使用的ca证书:
<img width="586" alt="image" src="https://github.com/user-attachments/assets/618f3e00-d35c-4771-b422-ee1d5212accc">
于此同时另一个umi启动的项目表现正常：
<img width="1059" alt="image" src="https://github.com/user-attachments/assets/5cf34caf-dc6a-416d-80cf-ee9d1690f43a">

### Expected behavior

不发生net::ERR_CERT_AUTHORITY_INVALID错误。

### Version of ice.js

3.2.5

**Comment by ClarkXia** [comment]
`ice start --https self-signed` 使用自签证书

**Comment by karthest** [comment]
> `ice start --https self-signed` 使用自签证书

已解决，感谢
