### ISSUE TITLE
关于ice3路由权限问题

### ISSUE THREAD

**Issue by jackHuang-123** [alibaba/ice#7022]
### Describe the bug

当前在ice.config.mts中，固定路由是下图这样的写法，想要通过登录时获取的路由进行对比，从而实现动态权限。
![image](https://github.com/user-attachments/assets/3f01af8e-1d3f-4425-8e08-736a653d285c)

### Expected behavior

想要通过登录时获取的路由进行对比，从而实现动态权限。

### Actual behavior

想要通过登录时获取的路由进行对比，从而实现动态权限。

### Version of ice.js

3.0

**Comment by jackHuang-123** [comment]
权限会根据角色变化，角色的权限路由也是可变的。

**Comment by ClarkXia** [comment]
参考 https://github.com/alibaba/ice/issues/6926
