### ISSUE TITLE
docker里面构建失败

### ISSUE THREAD

**Issue by oneQiu** [alibaba/ice#7028]
昨天构建的时候没有问题的，但是今天同样的项目代码，出现了问题，排查问题的时候发现可能和ice/app的更新有关系，想确认一下是不是有关联。
![image](https://github.com/user-attachments/assets/a688bea7-33c2-4192-8e2b-06fcd3ac3617)

**Comment by ClarkXia** [comment]
锁定下 @swc/types 版本到 0.1.12

**Comment by wssgcg1213** [comment]
related to https://github.com/swc-project/swc/issues/9753
