### ISSUE TITLE
字体如何本地化

### ISSUE THREAD

**Issue by farzer** [alibaba/ice#703]
## 环境信息

- 操作系统：OSX
- Iceworks 版本： latest

## 问题描述

按照了官方的离线化方案做，发现字体还是引用了网络字体，这导致网络慢的时候文件已经修改重新编译的话就卡主了(不知道是不是这个原因)，全局了一下路径是sass的$font-custom-path的原因，请问下怎么把字体本地化啊。官方是否可以提供一个字体包？

**Comment by noyobo** [comment]
根据文档 https://github.com/alibaba/ice/wiki/%E7%A6%BB%E7%BA%BF%E5%8C%96%E6%9E%84%E5%BB%BA%E9%A1%B9%E7%9B%AE  配置后还有问题是吗？

现在遇到的问题下载不了吗？ 错误信息有么？

**Comment by farzer** [comment]
是的，根据文档来着，错误信息没有显示，如下图

![image](https://user-images.githubusercontent.com/9881593/42726511-290baf8c-87c8-11e8-8f1a-0726ea42ff55.png)

**Comment by farzer** [comment]
官方如果还没有准备解决这个的话求一份字体包┭┮﹏┭┮

**Comment by farzer** [comment]
#282

**Comment by noyobo** [comment]
目前本地化的构建方案是 检测到 css 中有网络资源，会下载到本地。`i.alicdn.com` 这个域名的地址你网络是屏蔽掉了么？

**Comment by noyobo** [comment]
修改后重新编译，又触发重新下载，所以进度卡在 95%  等待下载过程。  这个重复下载我想办法优化下。

**Comment by farzer** [comment]
![image](https://user-images.githubusercontent.com/9881593/42801474-46a1b788-89d2-11e8-8532-fffa860828d5.png)
是可以ping通的，是重新下载的问题

> 修改后重新编译，又触发重新下载，所以进度卡在 95% 等待下载过程。 这个重复下载我想办法优化下。

**Comment by farzer** [comment]
有时候重新启动也会卡在这里

**Comment by noyobo** [comment]
@farzer 最新版的增加了超的处理。 可以升级下  ice-scripts

**Comment by noyobo** [comment]
https://github.com/alibaba/ice/wiki/%E5%A6%82%E4%BD%95%E5%AD%97%E4%BD%93%E6%9C%AC%E5%9C%B0%E5%8C%96
