### ISSUE TITLE
图片本地化之后Iceworks新建页面下载图片损坏

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#705]
## 环境信息

- 操作系统：2.3.x
- Iceworks 版本： 

## 错误信息

![image](https://user-images.githubusercontent.com/3995814/42681395-2184ca96-86ba-11e8-97fd-c23c5c5e31cf.png)

**Comment by noyobo** [comment]
哪个区块呀

**Comment by chenbin92** [comment]
所有区块

**Comment by noyobo** [comment]
v2.4.0 fixed
