### ISSUE TITLE
not support react-redux redux?

### ISSUE THREAD

**Issue by nkli** [alibaba/ice#71]

**Comment by yujiangshui** [comment]
我们并没有在官方的代码里引入 redux 或者 flux 等数据流管理工具，原因是因为经过一两年的实践，我们发现并没有太多应用复杂到必须使用 redux 才可以解决，大部分强行引入 redux 等，反而增加了交接、了解、维护成本。

但是我们官方代码并不会禁止使用 redux，如有需求还是可以自行引入 redux 或者任意的工具。本身我们的目录结构足够简单，组件代码也完全是最基础的 React 代码，并不会太多的约束大家。
