### ISSUE TITLE
加个className打包直接卡死95%

### ISSUE THREAD

**Issue by cyl66466** [alibaba/ice#710]
## 环境信息

- 操作系统：window 64
- Iceworks 版本： 2.3.1

## 问题描述
标签加了个className，或者图片换个不一样的路径，有时打包一直卡死在95%

**Comment by cyl66466** [comment]
标签加了个className，或者图片换个不一样的路径，有时打包一直卡死在95%

**Comment by cyl66466** [comment]
不好意思，准确说是点击调试服务

**Comment by noyobo** [comment]
调试服务一直开着的是吧？

**Comment by cyl66466** [comment]
是的一直开着，加个className 按理正常自动编译，但是就一直卡在95%

**Comment by noyobo** [comment]
好的，我查下

**Comment by cyl66466** [comment]
好的，麻烦了，另外有个信息是，不单是这次加个className，前些天也有不同位置className也会出现这个问题，同时有次只是换了一个不一样的img链接（绝对能正常打开），也会出现这种情况，希望对你排查有用

**Comment by cyl66466** [comment]
应该是iceworks的版本问题，我刚更新到最新版本2.4.0这个问题就没有了，谢谢您的反馈！

**Comment by noyobo** [comment]
已优化了资源下载的错误提示，下载资源错误后给出日志提示。
