### ISSUE TITLE
无论预览页面还是生成页面，都是空白页

### ISSUE THREAD

**Issue by leo9082** [alibaba/ice#718]
## 环境信息

- 操作系统：windows10
- Iceworks 版本： 2.4.0

## 问题描述
新建页面后，打开空白

**Comment by chenbin92** [comment]
使用的是那套模板，有对应的错误信息吗

**Comment by leo9082** [comment]
自定义模板或预设的模板都有这问题

这是预览界面，生成后就是空白页

发送自 Windows 10 版邮件应用

发件人: chenbin92
发送时间: 2018年7月17日 23:43
收件人: alibaba/ice
抄送: Leo; Author
主题: Re: [alibaba/ice] 无论预览页面还是生成页面，都是空白页 (#718)

使用的是那套模板，有对应的错误信息吗

**Comment by noyobo** [comment]
预览页面是否有相关的错误信息？

**Comment by date13** [comment]
我也遇到这个问题,应该是和网络有关,用移动卡的热点就全是空白页
换成电信的或者其他宽带就是好的,官网也是这个问题
https://alibaba.github.io/ice/docs/ice-design

报错
Failed to load resource: net::ERR_TIMED_OUT
index.js:1 GET https://ice.alicdn.com/assets/docs.json?visitHash=0.514993048959753 0 ()
(anonymous) @ index.js:1
e @ index.js:17
e @ index.js:17
e @ index.js:18
Promise.then (async)
e @ index.js:18
o.(anonymous function) @ index.js:18
e @ index.js:17
s @ 0.scalable-layout.js:13
e @ 4.documentation.js:672
tryCatch @ polyfill.min.js:3
invoke @ polyfill.min.js:3
t.(anonymous function) @ polyfill.min.js:3
r @ 4.documentation.js:672
(anonymous) @ 4.documentation.js:672
(anonymous) @ 4.documentation.js:672
e @ 4.documentation.js:672
e.notifyAll @ ??react/15.6.2/dist/react-with-addons.min.js,react-dom/15.6.2/dist/react-dom.min.js:20
close @ ??react/15.6.2/dist/react-with-addons.min.js,react-dom/15.6.2/dist/react-dom.min.js:22
closeAll @ ??react/15.6.2/dist/react-with-addons.min.js,react-dom/15.6.2/dist/react-dom.min.js:23
perform @ ??react/15.6.2/dist/react-with-addons.min.js,react-dom/15.6.2/dist/react-dom.min.js:23
perform @ ??react/15.6.2/dist/react-with-addons.min.js,react-dom/15.6.2/dist/react-dom.min.js:23
perform @ ??react/15.6.2/dist/react-with-addons.min.js,react-dom/15.6.2/dist/react-dom.min.js:22
k @ ??react/15.6.2/dist/react-with-addons.min.js,react-dom/15.6.2/dist/react-dom.min.js:22
closeAll @ ??react/15.6.2/dist/react-with-addons.min.js,react-dom/15.6.2/dist/react-dom.min.js:23
perform @ ??react/15.6.2/dist/react-with-addons.min.js,react-dom/15.6.2/dist/react-dom.min.js:23
batchedUpdates @ ??react/15.6.2/dist/react-with-addons.min.js,react-dom/15.6.2/dist/react-dom.min.js:22
u @ ??react/15.6.2/dist/react-with-addons.min.js,react-dom/15.6.2/dist/react-dom.min.js:22
r @ ??react/15.6.2/dist/react-with-addons.min.js,react-dom/15.6.2/dist/react-dom.min.js:22
enqueueSetState @ ??react/15.6.2/dist/react-with-addons.min.js,react-dom/15.6.2/dist/react-dom.min.js:22
r.setState @ ??react/15.6.2/dist/react-with-addons.min.js,react-dom/15.6.2/dist/react-dom.min.js:10
(anonymous) @ index.js:18
(anonymous) @ index.js:17
(anonymous) @ index.js:17
o @ index.js:17
(anonymous) @ index.js:17
(anonymous) @ index.js:19
o @ index.js:1
(anonymous) @ 4.documentation.js:1
index.js:17 Uncaught (in promise) Error: Network Error
    at e (index.js:17)
    at XMLHttpRequest.e (index.js:17)
e @ index.js:17
e @ index.js:17
Promise.then (async)
r @ 4.documentation.js:672
(anonymous) @ 4.documentation.js:672
(anonymous) @ 4.documentation.js:672
e @ 4.documentation.js:672
e.notifyAll @ ??react/15.6.2/dist/react-with-addons.min.js,react-dom/15.6.2/dist/react-dom.min.js:20
close @ ??react/15.6.2/dist/react-with-addons.min.js,react-dom/15.6.2/dist/react-dom.min.js:22
closeAll @ ??react/15.6.2/dist/react-with-addons.min.js,react-dom/15.6.2/dist/react-dom.min.js:23
perform @ ??react/15.6.2/dist/react-with-addons.min.js,react-dom/15.6.2/dist/react-dom.min.js:23
perform @ ??react/15.6.2/dist/react-with-addons.min.js,react-dom/15.6.2/dist/react-dom.min.js:23
perform @ ??react/15.6.2/dist/react-with-addons.min.js,react-dom/15.6.2/dist/react-dom.min.js:22
k @ ??react/15.6.2/dist/react-with-addons.min.js,react-dom/15.6.2/dist/react-dom.min.js:22
closeAll @ ??react/15.6.2/dist/react-with-addons.min.js,react-dom/15.6.2/dist/react-dom.min.js:23
perform @ ??react/15.6.2/dist/react-with-addons.min.js,react-dom/15.6.2/dist/react-dom.min.js:23
batchedUpdates @ ??react/15.6.2/dist/react-with-addons.min.js,react-dom/15.6.2/dist/react-dom.min.js:22
u @ ??react/15.6.2/dist/react-with-addons.min.js,react-dom/15.6.2/dist/react-dom.min.js:22
r @ ??react/15.6.2/dist/react-with-addons.min.js,react-dom/15.6.2/dist/react-dom.min.js:22
enqueueSetState @ ??react/15.6.2/dist/react-with-addons.min.js,react-dom/15.6.2/dist/react-dom.min.js:22
r.setState @ ??react/15.6.2/dist/react-with-addons.min.js,react-dom/15.6.2/dist/react-dom.min.js:10
(anonymous) @ index.js:18
(anonymous) @ index.js:17
(anonymous) @ index.js:17
o @ index.js:17
(anonymous) @ index.js:17
(anonymous) @ index.js:19
o @ index.js:1
(anonymous) @ 4.documentation.js:1

**Comment by noyobo** [comment]
http://ice.alicdn.com/assets/react-materials.json  可加载下对应的物料，看是否可以打开。
