### ISSUE TITLE
“新建页面”后立即“移除项目”导致项目状态显示异常

### ISSUE THREAD

**Issue by dondevi** [alibaba/ice#72]
运行版本： 0.1.3

重现步骤：
1. 找到一个未启动调试的项目
2. 点击“新建页面“
3. 返回项目列表，此时显示“调试服务启动中 {百分比}%“
4. 点击”移除项目“
5. 点击”打开项目“，重新打开刚才的项目
6. 项目状态显示为“未启动调试服务”

问题描述：
- 刷新界面，本地服务仍然有效
- 点击“启动调试服务”没有反应
- 点击“新建页面”后返回项目列表，显示“未启动调试服务 {百分比}%”
- 退出程序时提示“Iceworks quit unexpectedly.”

问题分析：
- 点击“新建页面”后，会自动启动调试服务
- 启动调试服务需要一定时间
- 在启动结束前“移除项目”，**没有终止启动操作**
- 重新打开项目时，**状态被重置**，导致无法结束调试服务

**Comment by dondevi** [comment]
PS：退出程序后恢复正常

**Comment by noyobo** [comment]
感谢如此详细的反馈，将会在下个版本修复该问题。

**Comment by yujiangshui** [comment]
@dondevi 感谢你十分详细的反馈，可以发你的收货地址和联系方式到 ice-admin@alibaba-inc.com ，正式发布后我们会寄送小礼品给你
