### ISSUE TITLE
Upload组件与FormBinder初始化问题

### ISSUE THREAD

**Issue by 515445681** [alibaba/ice#724]
## 环境信息

- 操作系统：macos 10.13.6
- Iceworks 版本：2.4.0 

## 问题描述

一般来讲，进入详情需要先获取服务器端图片数据以后进行填充。

我使用FormBinder绑定图片信息。并且使用axios获取图片信息后setState进行设置defaultFileList和fileList。

但Upload组件并没有初始化显示图片。

如果是我操作错误，麻烦贴一下正确代码。

官方示例使用field进行初始化setValue。但我希望使用FormBinder。

## 错误信息

没有显示图片。

**Comment by ashenone** [comment]
手动把表单值赋值给 `Upload` 组件的 `fileList` 参数即可

**Comment by Restry** [comment]
赋值后如果需要添加里面的值呢? 初始化给fileList值是可以显示出来.

但是如果需要手动添加一个图片到fileLIst中, 直接push也是不更新的

**Comment by chenbin92** [comment]
如还有疑问，请提供可复现的 demo 并重新打开改 issue
