### ISSUE TITLE
支持  iceworks 之外的环境 build

### ISSUE THREAD

**Issue by wkclz** [alibaba/ice#725]
## 环境信息

- 操作系统：Mac OS X 10.13.6
- Iceworks 版本： 2.5.0

## 问题描述

当前项目支持在 iceworks 界面，或 iceworks 的终端 build，但无法脱离iceworks。
是否能够支持 在 iceworks 之外的环境也能  build，以解决服务器自动部署问

## 错误信息
 iceworks 中的 node-sass 是 Wrapper ，并不是 项目的依赖。
外部环境则提示要安装  node-sass。安装之后，外部环境无法的 build，iceworks 也需要 删除 node-sass 才能运行。

**Comment by noyobo** [comment]
node-sass 会有其他依赖包依赖到的。 

为什么在 iceworks 下可以构建，因为 iceworks 环境下集成了 node-sass 因此构建是没有问题的，如果脱离 iceworks ，那么就需要重新把依赖安装一次，将依赖以当前环境安装完成后即可 build。

如果安装后依然无法构建，可提供下错误信息。

**Comment by wkclz** [comment]
> 在 iceworks 能 build 的情况下，在 cmd 内进行操作：
- 直接 npm run build 报缺少 node-sass
![1.png](https://upload-images.jianshu.io/upload_images/10319521-795cbe811497d178.png)
- 安装 node-sass
![2.png](https://upload-images.jianshu.io/upload_images/10319521-3deaf1a892f953d0.png)
- 再次 build，已经不认识 ice 了
![3.png](https://upload-images.jianshu.io/upload_images/10319521-a2aec3b96c690c5a.png)
- 这里是错误日志
![4.png](https://upload-images.jianshu.io/upload_images/10319521-6af0b5552ab17f8d.png)
- 最后，回到 iceworks 里面 build，和 cmd 内是同样的错，去掉 node-sass 后，恢复正常

**Comment by wkclz** [comment]
然后再 npm install 后，能正常 build。
# 结论
在 iceworks 和 外部 cmd 下，环境不一样， npm install 所得到的依赖结果也不一样。在不同的环境，可以通过重装依赖解决。
