### ISSUE TITLE
新建页面区块代码不完整

### ISSUE THREAD

**Issue by bdoycn** [alibaba/ice#727]
## 环境信息

- 操作系统：WIN 17134.165
- Iceworks 版本： 2.5.0

## 问题描述
使用区块新建页面时，生成的代码不完整，或者完全为空（有时也会正常，但目前错误几率很大）

## 错误信息
![tim 20180723150521](https://user-images.githubusercontent.com/31044988/43062679-37a1a9dc-8e8c-11e8-8397-3ead325bdb14.png)
![tim 20180723150550](https://user-images.githubusercontent.com/31044988/43062684-39ae7b06-8e8c-11e8-8abc-01da74f15c14.png)
![tim 20180723150747](https://user-images.githubusercontent.com/31044988/43062686-3bb44a8e-8e8c-11e8-81b5-1c70273074df.png)
![tim 20180723151259](https://user-images.githubusercontent.com/31044988/43062689-3c8df784-8e8c-11e8-9834-b6663642e64a.png)

**Comment by noyobo** [comment]
感谢反馈，我排查下

**Comment by noyobo** [comment]
@bdoycn  是否可以和你联系下，我这边没能复现问题，给你发个包测试下？

**Comment by bdoycn** [comment]
@noyobo bdoycn@vip.qq.com

**Comment by noyobo** [comment]
联系用户，确认用户网络环境丢包情况较严重引起。
