### ISSUE TITLE
点击"新建页面"后重新生成已手动删除的代码

### ISSUE THREAD

**Issue by dondevi** [alibaba/ice#73]
运行版本：0.1.3

使用场景：
- 想删除之前生成的页面。

重现步骤：
1. 点击“新建页面” --> “生成界面”，命名为“Test”
2. 手动删除 `pages/Test` 文件夹
3. 手动删除 `routes.jsx` 中生成的代码
3. 重新点击“新建界面”

问题描述：
- `routes.jsx` 中 “Test” 的代码又重新生成了：
```
...
import Test from './pages/Test';
const autoGeneratedRoutes = [
  {
    path: '/test',
    ...
  }
];
```

&emsp;后来发现，删除 **`generator.json`** 中的 `routes` 信息是正解，但是这样并不会自动删除 `pages/Test` 文件夹，还有 `navs.js` 里的 `autoGenAsideNavs`。

**Comment by wssgcg1213** [comment]
是的 `generator.json` 描述的是项目页面信息, 后面会有页面管理的面板提供出来, 在GUI上操作删除页面

**Comment by yujiangshui** [comment]
@wssgcg1213 generator.json 应该只作为第一次生成项目的配置信息，以及后续通过 iceworks 操作记录的辅助信息而已。删除页面等操作应该是直接操作文件的，而不是来操作 generator.json 配置，这样无形中增加了新的概念和维护成本。之在 GUI 上面操作 generator.json 这个方案走远了吧。

**Comment by yuanyan** [comment]
@wssgcg1213 对`generator.json`的定位应该只是一个可读文件，并且之在项目初始化时读

**Comment by wssgcg1213** [comment]
OK, 那么现在的表现应该是一个 bug, 需要在下一个版本中修复

**Comment by yujiangshui** [comment]
第一次生成后干掉，排查关联读取依赖。

**Comment by chenhongen** [comment]
+1

**Comment by noyobo** [comment]
#242

**Comment by yujiangshui** [comment]
fixed
