### ISSUE TITLE
离线化构建scss加载图片路径有误

### ISSUE THREAD

**Issue by willcong** [alibaba/ice#738]
## 环境信息

- 操作系统：win10
- Iceworks 版本： 2.5.0

## 问题描述
根据 离线化构建项目 步骤，通过scss加载图片，调试服务器可以正常显示图片，如果构建后，本地运行离线项目，图片路径有问题导致图片加载失败。没有声明publicPath。如果直接在jsx里通过require方法是可以正常加载图片的。
scss文件内容：
![image](https://user-images.githubusercontent.com/9913266/43239409-ad8c5838-90c4-11e8-85e6-16fc68ae2694.png)
资源项目路径：
![image](https://user-images.githubusercontent.com/9913266/43239424-bb6b35fa-90c4-11e8-8c63-6c5a32351223.png)
构建后资源路径：
![image](https://user-images.githubusercontent.com/9913266/43239474-efa5bae8-90c4-11e8-814b-e29edd3850a6.png)

## 错误信息
![image](https://user-images.githubusercontent.com/9913266/43239662-b5a9a966-90c5-11e8-9978-e22904d33629.png)
路径上多了个css

**Comment by noyobo** [comment]
请将 ice-scripts 升级到  1.6.4
