### ISSUE TITLE
npm run lint  的 error

### ISSUE THREAD

**Issue by xingqiyi** [alibaba/ice#74]
通过 iceworks 新建的页面

### npm run lint  的 error

```
components/FilterList/SingleItem/SingleItem.jsx
  5:16  error  Component should be written as a pure function  react/prefer-stateless-function

components/BrandDisplay/BrandDisplay.jsx
  42:16  error  Component should be written as a pure function  react/prefer-stateless-function
```

**Comment by wssgcg1213** [comment]
生成的代码格式只是一个示例, 是不是可以考虑放宽 `prefer-stateless-function` 这一 lint 限制? @yujiangshui

**Comment by yujiangshui** [comment]
放

**Comment by wssgcg1213** [comment]
@chenbin92 麻烦修改一下所有脚手架的 eslint 规则, 放行 `react/prefer-stateless-function`  

----

@xingqiyi 出现这个的原因是我们的 eslint 规则过于严格, 对于通过iceworks自动生成的页面代码, eslint 认为不符合规范, 我们生成的代码大致格式如下: 

```jsx
import React, { Component } from 'react';

export default class XXXPage extends Component {

  render() {
     return (
       <div>
          <BlockA />
          <BlockB />
       </div>
     );
  }
}
```

这个代码只是一个类似脚手架的示范, 使用者可以根据自身需求在页面上使用 React 的生命周期方法

所以我们决定放行这一条 eslint 规则, 如果是已经创建的项目, 只需要在 .eslintrc 文件的 rules 字段加上 
```js
'react/prefer-stateless-function': 0
```
就可以了

**Comment by yuanyan** [comment]
@xingqiyi 感谢反馈，可以发你的收货地址和联系方式到 ice-admin@alibaba-inc.com ，正式发布后我们会寄送小礼品给你
