### ISSUE TITLE
npm run start 报错 

### ISSUE THREAD

**Issue by yangfancoming** [alibaba/ice#755]
## 环境信息

- 操作系统：  win10
- Iceworks 版本： 2.5.1 

## 问题描述
 我找到问题原因了！

将项目中 .babelrc 文件中的 @babel/preset-stage-2 代码块 注释掉 项目就可以正常启动了。
请问下 这个 @babel/preset-stage-2 对项目功能上 没有什么影响的吧？

**Comment by chenbin92** [comment]
@yangfancoming  vue-cli 的依赖问题，已修复，重新生成项目或者执行 `npm i @babel/preset-stage-2 -D`。

具体可以查看 vue-cli 官方的相关 issue：https://github.com/vuejs/vue-cli/issues/1162

相关文章 [vue-cli 3.0 特性速读](https://juejin.im/post/5ad862c95188252eb3237752)
