### ISSUE TITLE
React 物料 Dashboard 疑似笔误 OverviewSatesChart

### ISSUE THREAD

**Issue by cncolder** [alibaba/ice#757]
## 环境信息

- 操作系统：
- Iceworks 版本： 

## 问题描述

`OverviewSatesChart` 应该叫 `OverviewStatsChart` 吗? 因为内文中 head 文本是 `QUICK STATS`

## 错误信息

https://github.com/alibaba/ice/blob/6a9997923f7f962fd6cb3b51c036c0a7bf08f8f8/react-materials/scaffolds/ice-design-dashboard/src/pages/Dashboard/components/OverviewSatesChart/OverviewSatesChart.jsx#L45

**Comment by chenbin92** [comment]
感谢反馈，区块考虑的是通用的场景，需要进行二次开发的；可能有些情况表达不精确，可以按需修改。

**Comment by cncolder** [comment]
我的意思是: `Sate` 这个单词是什么意思? 沙嗲? 厌倦?

**Comment by chenbin92** [comment]
@cncolder  应该改成 `state`

**Comment by cncolder** [comment]
@chenbin92 我觉得不是 `state`, 应该是 `stat`, 正确的组件名应该是 `OverviewStatsChart`.
