### ISSUE TITLE
项目启动后首页报错

### ISSUE THREAD

**Issue by taotoxht** [alibaba/ice#762]
## 环境信息

- 操作系统：windows
- Iceworks 版本： 2.5.1

## 问题描述

升级2.5.1后创建项目成功，访问 ：http://localhost:4444/ 页面报错。错误如下：
`Failed to compile
./src/routerConfig.js
Module not found: `E:\git4\cms-1\src\layouts\dashboard\index.js` does not match the corresponding path on disk `Dashboard`.
This error occurred during the build time and cannot be dismissed.`

## 错误信息

![image](https://user-images.githubusercontent.com/16130118/43449813-f8fc762c-94e3-11e8-938a-747f73226e23.png)

**Comment by noyobo** [comment]
【创建项目成功 】是哪个项目？ 我试下

**Comment by taotoxht** [comment]
我试了两个都不行， 比如 ice-material-dashboard，感觉像是升级到最新版才出的问题

**Comment by taotoxht** [comment]
@noyobo 控制台错误信息如下：
![image](https://user-images.githubusercontent.com/16130118/43450279-f4bc00ea-94e4-11e8-8708-6dfd89de50a6.png)

**Comment by noyobo** [comment]
看下  src/routerConfig 文件内容

**Comment by taotoxht** [comment]
可以了 @noyobo  可能是  我建了一个页面后 开始报错的  /sysUser 是我新建的页面
然后 我删掉项目重新创建 项目还是报错。我现在 去文件夹删掉，重新创建项目好了。

**Comment by noyobo** [comment]
问题找到了，新建页面生成的文件名大小不一致造成的。

**Comment by noyobo** [comment]
`import Dashboard from './layouts/dashboard';` 应该是大写

**Comment by taotoxht** [comment]
@noyobo 好的，多谢。
![image](https://user-images.githubusercontent.com/16130118/43456026-7b72952c-94f4-11e8-8911-b5b9e69a713e.png)
这个应该是自动生成的呀?我没有改过

**Comment by chenbin92** [comment]
@taotoxht 这个是生成的问题，我们这边会修复然后发版本，你那边先手动改一下

**Comment by chenbin92** [comment]
https://github.com/alibaba/ice/issues/774

**Comment by noyobo** [comment]
v2.5.2 fixed
