### ISSUE TITLE
SelectableTable全选问题

### ISSUE THREAD

**Issue by xyl5k5k** [alibaba/ice#763]
## 环境信息

- 操作系统：mac
- Iceworks 版本： 2.3.1

## 问题描述
用到SelectableTable组件时候，加入分页
点击全选后不保留其他页面已选内容

## 错误信息
![image](https://user-images.githubusercontent.com/38687923/43459617-a0b3ebea-9500-11e8-8c5a-0af00069ed46.png)
可以看到全选后只有这个页面的20条信息被选择了，其他页面的选择内容丢失

**Comment by noyobo** [comment]
http://alibaba.github.io/ice/block/selectable-table/preview  是这个区块么?

**Comment by chenbin92** [comment]
@xyl5k5k 是的，全新的时候只会记录当前的，如果需要记录所有选择的缓存起来就可以
