### ISSUE TITLE
iceworks 问题反馈

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#77]
* 预览页面之后，并没有创建页面，会将选择的区块的 `mock` 文件都同步到项目里，这是多余的
* iceworks 生成路由
   * 需要支持二级路由，类似 `user/list`
   * 需要支持可填写菜单名
* 需要支持二次选择区块到指定的项目页面
   > 场景：假设用户选择了一些区块，然后生成页面，在实际开发中，可能需要增加另外区块到该页面，现在的做法只能是手动清除，然后在重新生成一遍
* 考虑支持删除创建但未做过更改的页面
  > 场景: 假设用户选择了一些区块，然后生成页面，发现区块有一个区块不对，需要增加新的区块来替代，如何处理

**Comment by yujiangshui** [comment]
1. 预览页面的 mock 生成文件规范建议特殊标记，结束预览后遍历删掉。
2. 这块交互比较复杂，需要设计一下。优先级中。
3. 二次生成模块的流程需要整体设计下，优先级高。
4. 跟二次生成流程一样，不需要区分是否做过更改。

**Comment by wssgcg1213** [comment]
关于 mock, 昨夜洗澡的时候有一些新的想法   
保留原有的 `mock/xx.json`, 扩展一种 `mock/yy.mock.js/json`, 其可以定义 jsonschema based的mock数据自动生成的定义, 同时可以包括 GET/POST/.../跨域情况下 等多种情况的自定义  
暂且把这个文件和其包含的格式称之为`mock定义`, 创建该`mock定义`的路径可以是手写js/json, 或使用我们提供的 demo dev 工具使用GUI/表单的形式创建  @yujiangshui

**Comment by wssgcg1213** [comment]
关于二次编辑&添加block到已创建的页面中这条链路, 我希望可以做到基于AST分析 + code diff 算法和three way merge 类似的方式半自动地完成, 这个就需要有一个前提:

首先需要提供页面的管理方案, 不仅仅是目前的add, 还需要考虑到 modify, delete, pull block to exists page

**Comment by wssgcg1213** [comment]
有了页面管理方案之后, 第三个就是路由的管理, 基于已有的页面列表信息, GUI方式创建路由信息比较容易, 这块主要问题在于导航栏的数据标准化, 目前我们已经有 `navs.js`, 但是我觉得仍不够好用

**Comment by wssgcg1213** [comment]
Need a discussion next monday

**Comment by yujiangshui** [comment]
今天讨论下

**Comment by yujiangshui** [comment]
先开发上以下功能：

1. [ ] 二次下来模块到已有页面
2. [ ] 页面列表支持页面删除功能

**Comment by noyobo** [comment]
删除功能关联到 https://github.com/alibaba/ice/issues/242
