### ISSUE TITLE
Mac item2 命令行 启动项目编译失败

### ISSUE THREAD

**Issue by hellobeifeng** [alibaba/ice#776]
## 环境信息

- 操作系统：mac
- Iceworks 版本： 1.0
- node版本 8.1
- vue版本 2

## 问题描述
通过系统命令行，执行 npm run start 启动，编译失败，基本上都是node-sass相关的错误信息

## 错误信息

Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: ENOENT: no such file or directory, scandir  '/我的项目目录/node_modules/node-sass/vendor'

**Comment by noyobo** [comment]
项目依赖 node-sass  鉴于 node-sass 二进制的包下载在国内需要科学上网的原因（或者很慢）， iceworks 集成了 node-sass 环境。 在环境内构建是 ok 的。 

通过系统命令行，使用的是系统的环境，你可以 删除 node_modules 后重新安装依赖解决。

**Comment by hellobeifeng** [comment]
是的，我在项目内单独安装 node-sass后，运行成功
