### ISSUE TITLE
ICE 启动报错，error：invalid protocol ：127.0.0.1

### ISSUE THREAD

**Issue by zqjilove** [alibaba/ice#778]
## 环境信息

- 操作系统：win10 
- Iceworks 版本： 2.5.2

## 问题描述

启动后，直接弹窗报错，显示error：invalid protocol ：127.0.0.1。关闭报错弹窗，所有的物料源都不能显示。

![123](https://user-images.githubusercontent.com/300924/43681706-3a474500-988e-11e8-83ff-069e678e942c.jpg)

 
![111](https://user-images.githubusercontent.com/300924/43681709-4bd0c666-988e-11e8-9786-ddf37a6272e2.jpg)

**Comment by coolseven** [comment]
@zqjilove 可能是 proxy 的环境变量设置不正确导致的

win10 的 cmd  中查看当前的 proxy 环境变量
```bat
set http_proxy
```

如果结果是 
`127.0.0.1:1080`

那么需要修改成 `http://127.0.0.1:1080`  
```bat
set http_proxy=http://127.0.0.1:1080
```

使用同样的方法, 检查 https_proxy

最后,重启 ice 客户端

**Comment by noyobo** [comment]
启动时 会创建 socket 链接，请检查下是否支持。

**Comment by huangcong12** [comment]
我的也出现了这种情况，环境：win10 64位，飞冰版本：2.12.1，按照coolseven的方式设置代理了，也未能解决。在这里报错以后，未生成日志，所以没有日志提供。
![image](https://user-images.githubusercontent.com/2867782/48749062-268f6400-ecb4-11e8-9def-d9a04eefb0aa.png)
![image](https://user-images.githubusercontent.com/2867782/48749073-3313bc80-ecb4-11e8-8adf-c9eec4ede9c6.png)
