### ISSUE TITLE
在 Linux 下打包异常

### ISSUE THREAD

**Issue by wkclz** [alibaba/ice#779]
## 环境信息

- 操作系统：Mac OS，CentOS 7.4
- 源(Mac && CentOS)：https://registry.npmjs.org/
- Linux : node -v = v6.14.3;  npm -v = 3.10.10
- Mac : node -v = v8.9.1;  npm -v = 5.5.1

## 问题描述
使用模板：React物料->ICE Design CMS
在 Mac 下，npm install 和 npm run build 正常
在 CentOS 7 下
~~~
# npm install
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN @icedesign/cms-scaffold@1.0.0 No repository field.
npm WARN @icedesign/cms-scaffold@1.0.0 No license field.
# npm run build 
95% emitting(node:32623) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Object.entries is not a function
~~~
然后就没有结果了，build 是被中断

**Comment by wkclz** [comment]
标题没打完不小心 Enter 了。标题应为：在 Linux 下打包异常

**Comment by wkclz** [comment]
尝试升级Linux 版本再继续。
待续...

**Comment by chenbin92** [comment]
Linux 目前相比 Mac 和 Windows 平台会更新比较慢，我们会进来保持同步更新

**Comment by noyobo** [comment]
@chenbin92  模板里的  package.json 可以声明 engines 字段

**Comment by wkclz** [comment]
需要证实一下是否真的与node 版本有关。如果是有关系，
在创建项目的时候将 engines 直接设置到  package.json

**Comment by chenbin92** [comment]
https://github.com/alibaba/ice/pull/796

**Comment by levinit** [comment]
其實你直接解開 deb  然後按照rpm打包就是了 我給arch打aur就是這樣做的 簡單點
