### ISSUE TITLE
站点问题反馈

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#78]
##### [Button 按钮](https://alibaba.github.io/ice/#/component/button)

![image](https://user-images.githubusercontent.com/3995814/35766565-d26a28b0-0915-11e8-8a45-ac4480dddb12.png)

#####  [IceIcon 业务组件图标](https://alibaba.github.io/ice/#/component/iceicon)
![image](https://user-images.githubusercontent.com/3995814/35766581-1e8319be-0916-11e8-9011-2b0d6278cc34.png)

#####  [IceImg 图片组件](https://alibaba.github.io/ice/#/component/iceimg)
![image](https://user-images.githubusercontent.com/3995814/35766591-3d4157ee-0916-11e8-93ad-946615a83bc0.png)

#####  [IceLabel 标签组件](https://alibaba.github.io/ice/#/component/icelabel)
![image](https://user-images.githubusercontent.com/3995814/35766601-5bbf2426-0916-11e8-8cee-59e5927dfaf8.png)

#####  [IceLayout 页面布局](https://alibaba.github.io/ice/#/component/icelayout)
    * demo 排版混乱

#####  [Calendar 日历](https://alibaba.github.io/ice/#/component/calendar)

![image](https://user-images.githubusercontent.com/3995814/35766635-b98e1a80-0916-11e8-9a18-52ff67fe946c.png)

#####  [IceFormBinder ICE 表单粘合剂](https://alibaba.github.io/ice/#/component/iceformbinder)
  * 图片没有自适应
  * demo 示例背景需要优化

#####   [Tab 选项卡](https://alibaba.github.io/ice/#/component/tab)
    * tab 高度过高
    * 排版混乱
 
![image](https://user-images.githubusercontent.com/3995814/35766700-d69000b6-0917-11e8-8742-056ffb1904dd.png)

#####  [Table 表格](https://alibaba.github.io/ice/#/component/table)
   * demo 排版混乱
   * table 高度过高
![image](https://user-images.githubusercontent.com/3995814/35766714-2272d1c0-0918-11e8-9137-8af6d060b28c.png)

#####  [IcePanel 面板组件](https://alibaba.github.io/ice/#/component/icepanel)
    * demo 示例没出来

#####   [Overlay 弹层](https://alibaba.github.io/ice/#/component/overlay)
![image](https://user-images.githubusercontent.com/3995814/35766729-67ab58ca-0918-11e8-926b-1fc602005a39.png)

**Comment by wssgcg1213** [comment]
1. 幽灵按钮的特性是背景透明, 所以截图中的效果是期待的
2. 需要优化 iceicon 的 demo
3. 图片过大, 我看下
4. demo 中排版的问题基本上是 markdown 的格式影响到了其下的demo, 需要进行css隔离
5. 需要优化基础组件的 demo, 这个一直是原生 button, 周一推动一下

**Comment by wssgcg1213** [comment]
剩下demo本身的问题, 因为组件本身的代码没有开源, 转内部处理吧 cc @chenbin92
