### ISSUE TITLE
vue版npm run 报错

### ISSUE THREAD

**Issue by leinue** [alibaba/ice#780]
## 环境信息

- 操作系统：osx
- Iceworks 版本： 2.5.2

## 问题描述

npm dev 后报错

## 错误信息

Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] /Users/xieyang/iceworks-workspace/test/src/main.js: 
As of v7.0.0-beta.55, we've removed Babel's Stage presets.
Please consider reading our blog post on this decision at
https://babeljs.io/blog/2018/07/27/removing-babels-stage-presets
for more details. TL;DR is that it's more beneficial in the
  long run to explicitly add which proposals to use.

For a more automatic migration, we have updated babel-upgrade,
https://github.com/babel/babel-upgrade to do this for you with
"npx babel-upgrade".

![image](https://user-images.githubusercontent.com/2469688/43683176-a2583058-98b8-11e8-85eb-4848fe6c5c49.png)

**Comment by chieh301** [comment]
遇到一樣狀況

**Comment by chenbin92** [comment]
这个是 babel 升级到 7.x 导致的，可以先删掉 node_modules 然后重装应该就可以了。我这边同步升级下模板

**Comment by MrEggs** [comment]
同遇到 还没找到解决办法

**Comment by holtenko** [comment]
同遇到这个问题

**Comment by holtenko** [comment]
@chenbin92 删掉重装了貌似还不行

**Comment by chenbin92** [comment]
@holtenko  直接按照 babel 官方的升级指南即可  https://github.com/babel/babel-upgrade

在命令行执行以下命令：
```
# npx lets you run babel-upgrade without installing it locally
npx babel-upgrade --write

# or install globally and run
npm install babel-upgrade -g
babel-upgrade --write
```

模板已更新

**Comment by chenbin92** [comment]
https://github.com/alibaba/ice/pull/784

**Comment by leinue** [comment]
@chenbin92 好像还是不行诶

**Comment by leinue** [comment]
``` javascript
,
    ["@babel/preset-stage-2", {
      "useBuiltIns": true,
      "decoratorsLegacy": true
    }]
```

去掉这段后好了
