### ISSUE TITLE
希望 vue 版支持 vuex 和 iview

### ISSUE THREAD

**Issue by leinue** [alibaba/ice#785]
## 环境信息

- 操作系统：osx
- Iceworks 版本： 2.5.5

## 问题描述

希望vue版支持 vuex 和 iview

不用把state生成到vuex中，起码初始化一下，这样也省的之后自己再安装vuex，然后配置各种目录了

**Comment by chenbin92** [comment]
@leinue Vue 主要是由社区共建支持，类似 [d2-admin](https://github.com/d2-projects/d2-admin) 基于 ice 的模板。欢迎来 PR
