### ISSUE TITLE
构建完成项目，安装依赖的时候Iceworks占用内存6G多，不知道个别情况还是什么？

### ISSUE THREAD

**Issue by FruitPineapple** [alibaba/ice#788]
## 环境信息

- 操作系统：
- Iceworks 版本： 

## 问题描述
系统win7，选择Vue 模板 D2Admin ICE 构建完成，在安装依赖的时候，内存一下占用高达6G+ 希望有空的时候可以看下

**Comment by FruitPineapple** [comment]
![srhz z b77aoc11 2to08q](https://user-images.githubusercontent.com/27752454/43757170-8de444ac-9a4a-11e8-9809-9c8d863bd7f8.png)

后来我又试了一次，还是一样的，这次补上图片

**Comment by yuanyan** [comment]
安装依赖会npm install，在windows内存使用的有点夸张了，你直接npm会占用那么多内存吗？

**Comment by FruitPineapple** [comment]
手动安装依赖的时候内存使用正常
![image](https://user-images.githubusercontent.com/27752454/43810212-0f382278-9ae9-11e8-8607-0d19e04f2e38.png)

另外，我又试了一次Icework的安装依赖，内存一开始还好，内存从几百M到几G，是慢慢涨上去的，是不是哪里内存泄漏了？

**Comment by XuedaoYuan** [comment]
那我经常闪退可能也是这个问题

**Comment by chenbin92** [comment]
相关工具和工程已优化，如还有类似问题可重现打开该 issue
