### ISSUE TITLE
项目中引入 antd/dist/antd.css 在打包之后样式丢失

### ISSUE THREAD

**Issue by rungobier** [alibaba/ice#789]
飞冰前端项目中使用了antd 的Switch 组件，代码中引入了 antd.css ，在本地调试环境中 Switch 的样式是没有问题的，但是使用打包好的环境中 Switch 的样式完全丢失了。我查了下代码，发现飞冰自身引入的是.scss ，而我在使用antd时引用的是.css ，是不是不能打包引入css？

**Comment by yuanyan** [comment]
css 应该也是支持的，你直接把css后缀名改为scss可以最快解决问题

**Comment by noyobo** [comment]
> 注意，任何导入的文件都会受到 tree shaking 的影响。这意味着，如果在项目中使用类似 css-loader 并导入 CSS 文件，则需要将其添加到 side effect 列表中，以免在生产模式中无意中将它删除：

> Note that any imported file is subject to tree shaking. This means if you use something like css-loader in your project and import a CSS file, it needs to be added to the side effect list so it will not be 
unintentionally dropped in production mode:

ref: https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free

由于 antd 的包 package.json  sideEffect 指定了特定文件导致在生成环境  production 下打包 css 丢失。

https://github.com/ant-design/ant-design/blob/287d08890ab52033bccd345bbb0940b2a1343dc3/package.json#L230

**Comment by noyobo** [comment]
已提交 PR https://github.com/ant-design/ant-design/pull/11653

在此合并之前你可以将  antd.css 拷贝到项目中引用。
