### ISSUE TITLE
ice-design-pro 代码更新完了，但是在客户端中创建仍然是老版本

### ISSUE THREAD

**Issue by yujiangshui** [alibaba/ice#79]
github 已经更新完了，但线上站点和客户端生成时候还是老版本的。需要处理。

**Comment by yujiangshui** [comment]
@wssgcg1213 补充下这条链路的文档吧

**Comment by yujiangshui** [comment]
还是说就是上次那个？但是目前没生效

**Comment by wssgcg1213** [comment]
yes, the generate and publish routine is the same as publishing blocks;  
iceworks will check db that located at `https://g.alicdn.com/ice-assets/ice-design/databases/scaffords.db.json`

**Comment by wssgcg1213** [comment]
老版本的数据需要先手动维护一下

**Comment by wssgcg1213** [comment]
看来是 taobao 源更新不够及时...看看能不能搞一个 ci 服务来持续调用sync
