### ISSUE TITLE
ice与ant.design是什么关系呀？看到ICE Design Pro的文档中一些链接直接去了antd

### ISSUE THREAD

**Issue by kalsolio** [alibaba/ice#797]
在前后端分离设计中，通常的做法是由服务端提供权限数据接口，前端根据接口数据做对应的路由拦截控制和页面数据的渲染。在模板中，我们使用 [Authorized](https://pro.ant.design/components/Authorized-cn/) 权限组件实现了基本的权限管理方案，你可以基于模板结合实际的业务进行开发，模板中主要包含菜单权限控制和路由权限控制。

**Comment by chenbin92** [comment]
@kalsolio  可参考相关链接 https://github.com/alibaba/ice/issues/66
