### ISSUE TITLE
卡住

### ISSUE THREAD

**Issue by wangwanzhong** [alibaba/ice#799]
## 环境信息

- 操作系统：Win10
- Iceworks 版本： 2.5.2

## 问题描述

新建 angular 项目使用默认 ng-admin 模板，新建页面后卡主，除了软件总的关闭键，点任何键都没反应
## 错误信息

![kk](https://user-images.githubusercontent.com/5986825/43892541-d019c3dc-9bfe-11e8-8836-5ff6c04e43ca.png)

**Comment by imsobear** [comment]
已有话下载链路，可以升级体验下
