### ISSUE TITLE
@icedesign/form-binder 双向绑定协议没有兼容 onChange 第一个参数是 event 类型的情况

### ISSUE THREAD

**Issue by ihaichao** [alibaba/ice#803]
## 环境信息

- 操作系统：macOS High Sierra 10.13.6
- Iceworks 版本： 无

## 问题描述

在 @icedesign/form-binder 中，双向绑定协议约定组件会调用 onChange 并把新的 value 作为第一个参数抛出，但是在 Ant Design 的 Input 组件当中，抛出的第一个参数是 event 类型，目前并没有兼容这种情况。

## 错误信息

![image](https://user-images.githubusercontent.com/8586268/43947846-b0443386-9cbb-11e8-8e82-7eb52abe740a.png)

**Comment by yujiangshui** [comment]
可以试试自定义接受参数？ https://alibaba.github.io/ice/component/formbinder 下面常见问题的 “部分表单组件输出的 value 不符合要求，希望进行转换后提交，如何处理？”这个可以解决吗？

**Comment by yujiangshui** [comment]
![image](https://user-images.githubusercontent.com/2942913/43984603-1fec28ba-9d34-11e8-9a86-e1ac1eeee961.png)

**Comment by yujiangshui** [comment]
@ihaichao rule type text 感觉像是给组件传的 props 的值类型或者内容有问题？这块的代码方便贴一下？应该跟 event 参数两个问题。

下面这个是 github.io 的地址，按理说访问 github.io 可以的话应该就可以看到，是没渲染出东西空白还是直接打不开？

**Comment by yujiangshui** [comment]
@ihaichao 你这个代码没必要加 valueFormatter 因为 Input 本身给你的是 str。我在 playground 里面试了下没复现报错，可以在这里搞一个可以复现的贴一下吗？我的代码是：

```
import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import {
  FormBinderWrapper as IceFormBinderWrapper,
  FormBinder as IceFormBinder,
  FormError as IceFormError,
} from '@icedesign/form-binder';
import {
  Input,
  Button,
  Select,
  Grid,
} from '@icedesign/base';
const { Row, Col } = Grid;
const { Combobox } = Select;

class App extends Component {
  constructor(props) {
    super(props);

    this.state = {
      value: {
        phoneNum: '',
      },
    };
  }

  formChange = value => {
    console.log('value', value);
    this.setState({
      value,
    });
  };

  validateAllFormField = () => {
    this.refs.form.validateAll((errors, values) => {
      console.log('errors', errors, 'values', values);
    });
  };

  render() {
    return (
      <div>
        <IceFormBinderWrapper
          onChange={this.formChange}
          value={this.state.value}
        >
          <IceFormBinder name="phoneNum">
            <Input />
          </IceFormBinder>
        </IceFormBinderWrapper>
        <div
          style={{
            border: '1px solid #ccc',
            background: '#cacaca',
            marginTop: 20,
            padding: 10,
          }}
        >
          <strong>当前表单数据：</strong>
          <pre>
            {JSON.stringify(this.state.value, null, 2)}
          </pre>
        </div>
      </div>
    );
  }
}

ReactDOM.render(<App />, mountNode);
```

playground 地址：https://alibaba.github.io/ice/playground?from=demo 整个贴过去就可以看到效果

**Comment by ihaichao** [comment]
@yujiangshui 我使用的是 `antd` 里的 `Input`，抛出的参数类型是 `event`，下面的 demo 可以复现：
https://codesandbox.io/s/pjlw0vpv2j

**Comment by yujiangshui** [comment]
@ihaichao 查了下是因为 antd 组件 props 上面有个 type 导致跟 validate 里面的校验的 type 概念冲突了导致的。

![image](https://user-images.githubusercontent.com/2942913/44093228-84f61bfc-a005-11e8-9b01-05e99b852696.png)

快速的解决方法是在 FormBinder 上面加一个 type = string。

这是之前为了方便用户随意放置 validate rules 规则做的过度设计，没想到 React 里面没法区分是组件被人为设置的 props 还是本身默认的 props。 @wssgcg1213 可以看看要不要生个 br 版本把这个读取下层组件 props 的逻辑去掉。
