### ISSUE TITLE
Iceworks安装后打不开

### ISSUE THREAD

**Issue by yuanjiahui** [alibaba/ice#805]
## 环境信息

- 操作系统：Win10 
- Iceworks 版本： 2.5.2

## 问题描述

安装完后双击打不开，重复卸载安装很多次还是打不开

## 错误信息

![image](https://user-images.githubusercontent.com/5235098/44009560-6df4bf34-9edf-11e8-81ab-ccd554910486.png)

**Comment by fenglai0802** [comment]
直接双击没反应？
先卸载赶紧，然后再关闭杀毒按软件之后重新下载，并用管理员权限运行。
