### ISSUE TITLE
@icedesign/form-binder 包裹 Select 组件时，Select 的 defaultValue 失效，而且 value 不能回填

### ISSUE THREAD

**Issue by ihaichao** [alibaba/ice#806]
## 环境信息

- 操作系统：macOS High Sierra 10.13.6
- Iceworks 版本： 无 

## 问题描述

@icedesign/form-binder 包裹 Select 组件时，Select 的 defaultValue 失效，而且 value 不能回填

## 错误信息

无

**Comment by wssgcg1213** [comment]
当包裹 form-binder 的时候, 组件上会传递 value 属性   
表单组件的一个特性是当传递 value 属性的时候, 进入`受控模式`, 这个模式下 defaultValue 会失效, value 的值优先使用。

你说的不能回填能给提供更多信息吗, 比如复现的代码, 我们好帮你排查一下

**Comment by ihaichao** [comment]
下面的代码可以复现：

```
<FormBinderWrapper
  value={{ status: 1 }}
>
  <FormItem>
    <FormBinder name="status">
        <Select>
            <Option value="1">1</Option>
            <Option value="2">2</Option>
        </Select>
     </FormBinder>
  </FormItem>
</FormBinderWrapper>
```

**Comment by noyobo** [comment]
status 是 number 类型。 value 这里是字符串

**Comment by ihaichao** [comment]
@noyobo 跟这个好像没关系，把 status 改成字符串也不行

**Comment by ihaichao** [comment]
@wssgcg1213 找到问题了，需要在 `FormBinderWrapper` 上添加 `onChange` 手动回填 `value`。
建议在[文档](https://alibaba.github.io/ice/docs/advanced/how-to-make-form)中的示例添加相应代码。

**Comment by wssgcg1213** [comment]
好的
