### ISSUE TITLE
看不到datepicker源码，请问如何实现点击按钮，弹出date-picker弹窗，选择日期后将值填到一个span标签中

### ISSUE THREAD

**Issue by tlzzu** [alibaba/ice#807]
如题，很简单的一个需求，请问如何实现？
## 环境信息

- 操作系统：win10
- Iceworks 版本： 0.2.3

## 问题描述

请问如何实现点击按钮，弹出date-picker弹窗，选择日期后将值填到一个span标签中

## 错误信息

无

**Comment by yujiangshui** [comment]
需求是 “显示 date-picker 弹窗” 还是 “显示一个弹窗上面有 date-picker 然后选中点确定弹窗消失填入 span”？

**Comment by tlzzu** [comment]
我看过npm里的源码了，可否将datePanel对象暴露出来？我只需要弹窗，不需要输入框
![image](https://user-images.githubusercontent.com/13477114/44013353-9c0c72c8-9ef7-11e8-9bba-e682bbe09ab5.png)

**Comment by tlzzu** [comment]
我看到
`_@icedesign_base@0.2.3@@icedesign\base\lib\_components\@alife\next-date-picker\lib\view\date-picker.js`
能否把369行 datePanel暴露出来？
![image](https://user-images.githubusercontent.com/13477114/44013689-a454dc02-9ef9-11e8-8bb6-cb566e5f4057.png)

**Comment by wssgcg1213** [comment]
这是一个calendar组件吧 
![](https://gw.alicdn.com/tfs/TB14TG5n8jTBKNjSZFuXXb0HFXa-898-906.png)

**Comment by tlzzu** [comment]
这个是备选，这里没有time组件，相对而言没有date-picker合适

**Comment by noyobo** [comment]
```
<DatePicker 
        open={true}
        onChange={console.log}
        onOpenChange={console.log}>
      </DatePicker>
```

这样是一个打开状态的时间选择。通过其他弹窗组合使用。

**Comment by tlzzu** [comment]
好的
