### ISSUE TITLE
Debian容器是否能运行iceworks

### ISSUE THREAD

**Issue by adoo123** [alibaba/ice#808]
执行dpkg -i Iceworks-amd64-2.0.0-beta.deb时提示需要安装很多依赖，发现这些依赖都安装不上

root@cc677f148c06:/tmp/test# dpkg -i Iceworks-amd64-2.0.0-beta.deb
(Reading database ... 31715 files and directories currently installed.)
Preparing to unpack Iceworks-amd64-2.0.0-beta.deb ...
Unpacking iceworks-desktop (2.0.0-beta) over (2.0.0-beta) ...
dpkg: dependency problems prevent configuration of iceworks-desktop:
 iceworks-desktop depends on gconf2; however:
  Package gconf2 is not installed.
 iceworks-desktop depends on gconf-service; however:
  Package gconf-service is not installed.
 iceworks-desktop depends on libnotify4; however:
  Package libnotify4 is not installed.
 iceworks-desktop depends on libappindicator1; however:
  Package libappindicator1 is not installed.
 iceworks-desktop depends on libxtst6; however:
  Package libxtst6 is not installed.
 iceworks-desktop depends on libnss3; however:
  Package libnss3 is not installed.
 iceworks-desktop depends on libxss1; however:
  Package libxss1 is not installed.

dpkg: error processing package iceworks-desktop (--install):
 dependency problems - leaving unconfigured
Processing triggers for mime-support (3.60) ...
Errors were encountered while processing:
 iceworks-desktop

**Comment by sjq597** [comment]
应该是可以的，Ubuntu也是Debian分支的,可以运行，如果你缺这些依赖，把这些依赖装上应该就可以了吧
