### ISSUE TITLE
Table Component: Warning: Encountered two children with the same key

### ISSUE THREAD

**Issue by chenhongen** [alibaba/ice#811]
## 环境信息

- 操作系统：WIN7/10
- Iceworks 版本： 2.1.1/2.5.0

## 问题描述
使用stationId作为primaryKey，并且数据源里并没有重复的键值。但是出现了下图警告。。。
Using 'stationId' as primaryKey,and there are not same stationId in my datasource.However,it warning like the git.could you help me?

```
import React, { Component } from 'react';
import axios from 'axios';
import { Dialog, Table, Button, Icon, Pagination } from '@icedesign/base';


export default class SelectableTable extends Component {

  getData = () => {
    let result =     [
        {"stationId": 6        }, 
        {"stationId": 7        }, 
        {"stationId": 9        }, 
        {"stationId": 0        }, 
        {"stationId": 10       }, 
        {"stationId": 3        }
    ];

    return result;
  };

  render() {
    return (
          <Table dataSource={this.getData()} primaryKey="stationId">
            <Table.Column title="工厂" dataIndex="factoryCode" width={100} />
            <Table.Column title="车间" dataIndex="workshopCode" width={120} />
            <Table.Column title="生产线" dataIndex="workshopLine" width={100} />
          </Table>
    );
  }
}
```
## 错误信息

Warning: Encountered two children with the same key, `3`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
![qq 20180814170740](https://user-images.githubusercontent.com/16499303/44083090-a2c05bea-9fe5-11e8-8e0b-54473d43e39c.gif)

**Comment by noyobo** [comment]
primaryKey 不支持为 0
