### ISSUE TITLE
iceworks中添加使用@DataBinder的区块后，编译报错

### ISSUE THREAD

**Issue by shellhong6** [alibaba/ice#822]
## 环境信息

- 操作系统：mac
- Iceworks 版本：2.5.2 

## 问题描述

iceworks中添加使用@DataBinder的区块（例如：OperationTable）后，编译报错

@DataBinder字段处提示：
Syntax error: Unexpected token (11:0)

## 错误信息

@DataBinder字段处提示：
Syntax error: Unexpected token (11:0)

**Comment by noyobo** [comment]
看下启动日志

**Comment by noyobo** [comment]
将整个文件代码提供下。

**Comment by chenbin92** [comment]
@shellhong6  https://github.com/alibaba/ice/blob/master/react-materials/blocks/OperationTable/src/OperationTable.jsx  OperationTable 区块没有使用 @databinder，提供一下具体信息

**Comment by noyobo** [comment]
https://github.com/facebook/create-react-app/issues/214

**Comment by noyobo** [comment]
react-scripts 不推荐使用 es6 decorator 语法

更换个写法可以绕过 

```js
/* eslint no-underscore-dangle:0 */
import React, { Component } from 'react';
import dataBinder from '@icedesign/data-binder';

const { Group: RadioGroup } = Radio;

class TimeFilterTable extends Component {}


export default dataBinder({
  tableData: {
    // options
  },
})(TimeFilterTable);

```
