### ISSUE TITLE
FeedBack.toast的显示位置问题

### ISSUE THREAD

**Issue by Symous** [alibaba/ice#831]
## 环境信息

- 操作系统：macOS 10.13.6
- Iceworks 版本： 2.5.2

## 问题描述

在利用FeedBack.toast的时候，显示的位置总是在屏幕的正中央。但是有这样的一种使用场景：
使用左侧边栏的布局方式，当在右侧的显示内容中使用FeedBack.toast的时候，显示的位置是屏幕的正中央，而不是用户所关注区域(即侧边栏右侧内容区域)的正中央，会造成一种错位的错觉。

**Comment by chenbin92** [comment]
> 当在右侧的显示内容中使用FeedBack.toast的时候，显示的位置是屏幕的正中央，而不是用户所关注区域(即侧边栏右侧内容区域)的正中央
`Feeback.toast` 的设计场景就是全局的一种信息提示，所以位于屏幕的正中央。如果按照你所说的位于右侧的内容的正中央，这个需要根据你的右侧内容去计算，属于业务的定制需求了，而不是组件的通用功能，另外，你说的需求类似于在右侧有一个大表格，这个表格在点击操作的时候需要某个提示，这个提示的设计应该是针对你的表格去设计的，而不是使用 `Feeback.toast`  去实现，类似于表格加载的 loading 动画一样。
