### ISSUE TITLE
linux2.6版本没法下载

### ISSUE THREAD

**Issue by lu592674374** [alibaba/ice#837]
## 环境信息

- 操作系统：
- Iceworks 版本： 

## 错误信息
![image](https://user-images.githubusercontent.com/15523855/44439600-e35f1f80-a5f6-11e8-9cb9-c8c84b44710d.png)

**Comment by noyobo** [comment]
## 2.6.0-beta
  - [Iceworks-x86_64-2.6.0-beta.AppImage](https://iceworks.oss-cn-hangzhou.aliyuncs.com/linux/Iceworks-x86_64-2.6.0-beta.AppImage)
  - [Iceworks-amd64-2.6.0-beta.deb](https://iceworks.oss-cn-hangzhou.aliyuncs.com/linux/Iceworks-amd64-2.6.0-beta.deb)
