### ISSUE TITLE
vue user-login 登录页样式

### ISSUE THREAD

**Issue by wyh497823256** [alibaba/ice#853]
## 环境信息

chrome 版本 68.0.3440.106（正式版本） （64 位）
- 操作系统：mac os
- Iceworks 版本： 
2.6
## 问题描述
border:none; 无效
见下图

**Comment by wyh497823256** [comment]
<img width="1074" alt="1" src="https://user-images.githubusercontent.com/8830870/44572688-38499400-a7b7-11e8-9fb4-b245e2c721e7.png">

**Comment by wyh497823256** [comment]
![d1e14ed5-5769-47c3-a9fb-ca32983e383e](https://user-images.githubusercontent.com/8830870/44572727-57482600-a7b7-11e8-8fe8-c658e83576ba.png)

**Comment by chenbin92** [comment]
这里的 scss 有 scope 的概念，具体可以自行了解
