### ISSUE TITLE
TreeSelect组件消失回调方法

### ISSUE THREAD

**Issue by Symous** [alibaba/ice#860]
## 环境信息

- 操作系统：macOS 10.13.6
- Iceworks 版本： 2.6.0

## 问题描述

可否提供一个TreeSelect组件的窗口关闭回调，比如onDismiss，因为在允许多选的某些情况下，我们想要在选择完需要的多个条目以后，在执行某一特定的操作，这样的话onChange回调会显得效率低一些。

**Comment by myronliu347** [comment]
```
onVisibleChange = {(visible) => if (!visible) { // TODO } }
```

**Comment by imsobear** [comment]
@Symous issue 我先 close 了，你看下是否解决问题，没解决的话再 reopen 下。
