### ISSUE TITLE
文件上传视频，后台返回的状态是200，但是每次都是进入onError的钩子函数里。

### ISSUE THREAD

**Issue by simian0826** [alibaba/ice#861]
## 环境信息

- 操作系统：
- Iceworks 版本： 

## 问题描述

文件上传视频，后台返回的状态是200，但是每次都是进入onError的钩子函数里。

![image](https://user-images.githubusercontent.com/12445947/44774464-c487fc80-aba5-11e8-8003-5758fad85fff.png)
![image](https://user-images.githubusercontent.com/12445947/44774530-ee412380-aba5-11e8-842b-ee510b5d5989.png)

![image](https://user-images.githubusercontent.com/12445947/44774547-f305d780-aba5-11e8-895b-1e2202e7943a.png)

**Comment by noyobo** [comment]
![image](https://user-images.githubusercontent.com/1292082/44856654-891e2880-aca0-11e8-8441-a7a2aff0a1b8.png)

**Comment by noyobo** [comment]
![image](https://user-images.githubusercontent.com/1292082/44856718-aa7f1480-aca0-11e8-9aab-f7f7882a79f4.png)
