### ISSUE TITLE
ICE本地开发调试liveload速度慢体验差

### ISSUE THREAD

**Issue by woiweb** [alibaba/ice#862]
## 问题描述

* 本地开发调试过程中(num run start)，修改某个文件(html,css,js)后，都不能实时看到效果，必须等这个编译完事才行，而这个编译时间有些久（我本地2个js，build的时间为1.8s），build完成后再触发浏览器刷新大概又要1s+，完全没有liveload的效果，还不如手动刷新快，体验比较差。

这块是否可以做下优化呢，缩短build和热部署时间。

## 控制台信息

Entrypoint home = css/vendor.css js/vendor.js js/vendor.js.map css/vendor.css.map css/home.css js/home.js css/home.css.map js/home.js.map Entrypoint test = css/vendor.css js/vendor.js js/vendor.js.map css/vendor.css.map css/test.css js/test.js test.897571a188c212115137.hot-update.js css/test.css.map js/test.js.map test.897571a188c212115137.hot-update.js.map Compiled successfully in 1.8s!

**Comment by chenbin92** [comment]
请下载最新版的 ice-scripts 做了对应的优化。如果还有类似的问题可以提供录屏重新打开该 issue
