### ISSUE TITLE
FormBinder表单组件输出的value不符合要求时如何转换

### ISSUE THREAD

**Issue by Symous** [alibaba/ice#863]
## 环境信息

- 操作系统：macOS 10.13.6
- Iceworks 版本： 2.6.0

## 问题描述

当我们使用FormBinder包裹一个组件A的时候，假设组件A接收的值是bool类型，但是FormBinder中对应的属性是其他类型，比如数字类型，这个时候我们应该如何在加一层逻辑判断，将非bool值转换为bool值以便传递到组件A呢？以下是我的一段代码：
```js
<Col xxs="16" s="10" l="6">
     <FormBinder name="approved" >
            <FBSwitch disabled name="approved"/>
     </FormBinder>
     <div style={styles.formErrorWrapper}>
             <FormError name="approved" />
     </div>
</Col>
```
其中FBSwitch是我封装的一个支持表单规范的组件，由于我的approve字段为数字类型，所以会产生错误，我看官方文档中有一个valueFormatter方法，但是尝试了一下未能成功。

**Comment by noyobo** [comment]
valueFormatter 是针对 onChange 之后的数据格式化。 并不是使用在这场景。

>假设组件A接收的值是bool类型

那么 FormBinderWrapper 的 value 对应的字段也是一个 bool 类型。

**Comment by Symous** [comment]
@noyobo 使用了一下beta版本还是有一点问题，详见：#864 。
