### ISSUE TITLE
ice-scripts webpackHotDevClient 问题

### ISSUE THREAD

**Issue by chenbin92** [alibaba/ice#866]
## 环境信息

- 操作系统：
- Iceworks 版本： 

## 问题描述

在开发环境中 ice-scripts 依赖了 [react-dev-utils/webpackHotDevClient](https://unpkg.com/react-dev-utils@5.0.2/webpackHotDevClient.js) 模块，而它又依赖了 [strip-ansi](https://github.com/chalk/strip-ansi) 模块，strip-ansi  主要是 node 环境下的包， 没有做 es6 to es5 的编译操作，导致在 IE 下不支持。

相关 issue：
  * https://github.com/dvajs/dva/issues/1233  
  * https://github.com/facebook/create-react-app/issues/2691

**Comment by imsobear** [comment]
Close #1337

**Comment by chenbin92** [comment]
解决方案：https://github.com/SamVerschueren/babel-engine-plugin/
