### ISSUE TITLE
Input 组件中的 multiple 模式下的 placeholder 如何写入换行的提示信息？

### ISSUE THREAD

**Issue by rungobier** [alibaba/ice#868]
见标题

**Comment by noyobo** [comment]
html 中是如何写的 ？

**Comment by rungobier** [comment]
看到的有三种方案
1. CSS 来控制 以\A 来切分 （不理想）
2. &#13;&#10; （尝试不行）
3. 使用js代码来动态添加 placeholder 属性 （不理想）

**Comment by rungobier** [comment]
2 是 & # 13 ; & # 10 ;

**Comment by rungobier** [comment]
好了，问题解决了，解决方式是：
var test_code = "#include <stdio.h>\nint main(){\nprintf(\"hello....\\n\");\n}\n"
<Input multiple placeholder={test_code} />
