### ISSUE TITLE
Table数据源过滤需求

### ISSUE THREAD

**Issue by Symous** [alibaba/ice#874]
## 环境信息

- 操作系统：macOS 10.13.6 
- Iceworks 版本： 2.7.0

## 问题描述

Table组件中有没有考虑过加入这一一个功能：
通过一个搜索框Search组件，输入一些关键字进行快速的全字段模糊过滤，
比如数据表格目前为:

| id | name | age |
| ------ | ------ | ------ |
| 1 | name1 | 11 |
| 2 | name2 | 12 |
|3  | name3 | 30|

当我们输入一个过滤条件，比如1，可以把第一行和第二行都过滤出来，输入2仅可以过滤出第2行。
这种方式类似于AngularJS的filter过滤器，用起来我个人觉得非常方便。

或者目前除了遍历检索数据源来手动组成新的数据源以外还有没有更好的方式呢？

**Comment by youluna** [comment]
没有这样的计划哦
