### ISSUE TITLE
无法启动Iceworks程序

### ISSUE THREAD

**Issue by sharh** [alibaba/ice#879]
## 环境信息

- 操作系统：
- Iceworks 版本： 2.7.0

## 问题描述

下载安装windows-64位， 运行环境：64位，Win 7 及以上。

无法进行运行，点击Iceworks，没有任何反应

## 错误信息

无法启动Iceworks程序，没有相关界面显示，一直点击都没有反应。重新下载安装后还是没有反应

操作系统：Windows 7 旗舰版 Service Pack 1

处理器： Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz

系统类型： 64位操作系统

内存： 8G

**Comment by imsobear** [comment]
请关闭杀毒软件，然后用管理员权限启动试下，如果还有问题，麻烦 reopen 下
