### ISSUE TITLE
VUE  的d2admin 构建失败

### ISSUE THREAD

**Issue by BensonMax** [alibaba/ice#880]
## 环境信息

- 操作系统：win10
- Iceworks 版本： 2.7.0

## 问题描述

VUE  的d2admin 构建失败

#### 构建界面错误信息无法复制粘贴上来，详细的话看截图
![image](https://user-images.githubusercontent.com/31434954/44971663-012e6c00-af89-11e8-8e9d-a74e76159fd3.png)
![image](https://user-images.githubusercontent.com/31434954/44971669-05f32000-af89-11e8-9dea-37bd384e7d61.png)

**Comment by chenbin92** [comment]
@BensonMax eslint 错误处理下即可
