### ISSUE TITLE
Iceworks mac版本，合上mac盖子并回到家里。唤醒mac时看到客户端崩溃。

### ISSUE THREAD

**Issue by EngsShi** [alibaba/ice#881]
## 环境信息

- 操作系统：mac
- Iceworks 版本： 2.7.0

## 问题描述

合上mac盖子并回到家里。唤醒mac时看到客户端崩溃。

## 错误信息

无

**Comment by noyobo** [comment]
合上盖子前，客户端运行状态吗？ 比如项目在运行

**Comment by EngsShi** [comment]
@noyobo 有个之前启动的项目没停止。

**Comment by fenglai0802** [comment]
可以提供崩溃信息吗。
现在的版本还会不会有这个问题。
如果有，麻烦你重新打开这个issue并附上出错信息，谢谢
