### ISSUE TITLE
Mac版总是闪退

### ISSUE THREAD

**Issue by XuedaoYuan** [alibaba/ice#883]
## 环境信息

- 操作系统：
- Iceworks 版本： 2.6.0

## 问题描述

总是闪退， 意外退出

## 错误信息

日志没记录

**Comment by XuedaoYuan** [comment]
一天要重启10几次， 有点受不了了。 不知道是我电脑问题还是这个软件问题

**Comment by noyobo** [comment]
@XuedaoYuan  开着应用的情况下吗

**Comment by XuedaoYuan** [comment]
> @XuedaoYuan 开着应用的情况下吗

是的， 开着

**Comment by LosEcher** [comment]
Iceworks(31317,0x70001af3d000) malloc: *** error for object 0x7fc59bd46eb0: pointer being freed was not allocated

**Comment by LosEcher** [comment]
version 2.8.0 and 2.9.0 ; Iceworks will crash after running a while, it crashes no matter whether there is an application running or not.

**Comment by imsobear** [comment]
try Iceworks@2.17.0

**Comment by XuedaoYuan** [comment]
> try Iceworks@2.17.0

 My global VPN might make the problem, I found it crash after I toggle global ans PAC.
