### ISSUE TITLE
Table.Column lock属性有问题

### ISSUE THREAD

**Issue by shuaidiao** [alibaba/ice#896]
## 环境信息

- 操作系统：windows7  qq浏览器
- Iceworks 版本： 2.7.0

## 问题描述

初始化时有问题的状态：
![image](https://user-images.githubusercontent.com/42376214/45207661-238ef500-b2bb-11e8-862f-1fb6f97f9d27.png)

列表长度刚好是这么长的时候第一次进去会显示两个相同的锁列，只要调整窗口的大小就正常了，不管窗口怎么调整大小，以后都正常了，就在初始化的时候有问题

正常状态：
![image](https://user-images.githubusercontent.com/42376214/45207689-33a6d480-b2bb-11e8-8d92-6831f82118d3.png)

**Comment by chenbin92** [comment]
已同步更新
