### ISSUE TITLE
明明已安装了vscode ，但是icework 依然提示安装vscode 编辑器

### ISSUE THREAD

**Issue by geekyouth** [alibaba/ice#899]
## 环境信息

- 操作系统：win10 64 

- Iceworks 版本： 2.7.0

## 问题描述

明明已安装了vscode ，但是icework 依然提示安装vscode 编辑器

## 错误信息

![image](https://user-images.githubusercontent.com/12899262/45257399-54b11780-b3d8-11e8-8455-8e74ba27aea4.png)

**Comment by noyobo** [comment]
查找编辑器的方法受安装环境影响，可能无法正确获取地址。

可通过自定义启动脚本配置  https://github.com/alibaba/ice/wiki/custom-editor
