### ISSUE TITLE
无法部署到WEB服务器二级目录

### ISSUE THREAD

**Issue by holtenko** [alibaba/ice#902]
## 环境信息

- 操作系统：OSX
- Iceworks 版本： 2.7.0

## 问题描述

构建后部署到web服务器只能部署到根目录，部署到二级目录会找不到资源文件。

**Comment by holtenko** [comment]
.webpackrc.js这个文件是要自己创建吗？项目里没找到呢

**Comment by noyobo** [comment]
自己创建


https://github.com/alibaba/ice/wiki/%E8%AE%BE%E7%BD%AE%E8%B5%84%E6%BA%90%E5%8A%A0%E8%BD%BD%E8%B7%AF%E5%BE%84-publicPath

**Comment by noyobo** [comment]
需要指定 publicPath
