### ISSUE TITLE
table 使用cell渲染单元格时，卡顿

### ISSUE THREAD

**Issue by liulingli** [alibaba/ice#904]
切换状态
切换前
![image](https://user-images.githubusercontent.com/15230114/45336959-651fe880-b5b8-11e8-8654-b72229eb7863.png)
切换后
![image](https://user-images.githubusercontent.com/15230114/45336948-51748200-b5b8-11e8-8e3e-5566afc30be1.png)
中间过程需要好几秒

**Comment by noyobo** [comment]
table 在处理复杂数据时存在性能问题。

可尝试使用  https://react-table.js.org/#/story/readme
