### ISSUE TITLE
默认进入页面自动校验了所有必填项

### ISSUE THREAD

**Issue by bluexuchun** [alibaba/ice#907]
## 环境信息

- 操作系统：Mac
- Iceworks 版本： 2.7.0

## 问题描述

默认进入页面自动校验了所有必填项

## 错误信息

``` jsx
// 提交表单 校验
submit = () => {
    const that = this;
    that.formRef.validateAll((error, value) => {

      if(error){
        Feedback.toast.error("请填写完整信息");
        return false;
      }
    });
};

// 代码
render() {
	<IceContainer style={styles.container}>
	    <IceFormBinderWrapper
	        ref={(formRef) => {
	          this.formRef = formRef;
	        }}
	        value={this.state}
	        onChange={this.onFormChange}
	    >
	        <div>
	          <Tab onChange={this.tabChange} defaultActiveKey={1}>
	            {tabs.map(item => (
	              <TabPane key={item.key} tab={item.tab} onClick={this.tabClick}>

	              </TabPane>
	            ))}
	          </Tab>
	          <Row style={styles.formItem}>
	            <Col xxs="6" s="2" l="4" style={styles.formLabel}>
	              公司名称：
	            </Col>

	            <Col s="12" l="10">
	              <IceFormBinder name="name" required={true} message="公司名称必须填写">
	                <Input style={{
	                    width: '100%'
	                  }}
	                  placeholder="请输入公司名称"/>
	              </IceFormBinder>
	              <IceFormError name="name"/>
	            </Col>
	          </Row>
	       </div>
	     </IceFormBinderWrapper>
	</IceContainer>
}
```
进入页面后
![image](https://user-images.githubusercontent.com/22693912/45353517-9535ae80-b5ed-11e8-8a39-70e6b666c526.png)
![image](https://user-images.githubusercontent.com/22693912/45353521-9a92f900-b5ed-11e8-8c0b-53c8e298be50.png)
默认自动校验

**Comment by rickytjx** [comment]
发一下 componentWillMount() componentDidMount() 代码

**Comment by rickytjx** [comment]
> > 发一下 componentWillMount() componentDidMount() 代码
> 
> ```
>   componentWillMount(){
>     const activityId = this.props.history.params.activityId;
>     // 正确获取到activityId的值，去获取他的值
>     if(activityId != 'create'){
>       ajaxTo('api.php?entry=sys&c=logistics&a=company&do=detail',{'id':activityId})
>       .then((res)=>{
>         console.log(res)
>         let currentData = {...res};
> 
>         // 给地图初始信息
>         if(res.address && res.latitude && res.longitude){
>           let mapDataSource = {...this.state.mapDataSource};
>           mapDataSource.location = {
>             type:'change',
>             name:'',
>             longitude:res.longitude,
>             latitude:res.latitude
>           }
>           this.setState({
>             mapDataSource:mapDataSource
>           })
>         }
> 
>         console.log(this.state.mapDataSource)
> 
>         currentData.contactLists = res.contactLists ? res.contactLists : [{}];
> 
>         currentData.bg_picture = res.bg_picture ? this.changeImg(res.bg_picture) : [];
>         currentData.cd_picture = res.cd_picture ? this.changeImg(res.cd_picture) : [];
>         currentData.mt_picture = res.mt_picture ? this.changeImg(res.mt_picture) : [];
>         currentData.other_picture = res.other_picture ? this.changeImg(res.other_picture) : [];
> 
>         currentData.phonelits = res.phonelits ? res.phonelits : [{}];
> 
> 
>         currentData.status = res.status == 1 ? true : false;
>         currentData.is_recommend = res.is_recommend == 1 ? true : false;
>         currentData.hotline = res.hotline == 1 ? true : false;
>         currentData.contact = !res.contact ? [{}] : res.contact;
> 
> 
>         this.setState({
>           ...currentData,
>           introduce:res.introduce
>         });
>       })
>     }else{
>       let mapDataSource = {...this.state.mapDataSource};
>       mapDataSource.location = {
>         type:'init',
>         name:'',
>         longitude:0,
>         latitude:0
>       }
>       this.setState({
>         propties:1,
>         mapDataSource:mapDataSource
>       })
> 
>       setTimeout(() => {
>         // 防止输入表格无限初始化地图
>         mapDataSource.location.type = 'normal';
>         this.setState({
>           mapDataSource:mapDataSource
>         })
>       },2000)
>     }
>   }
> 
>   componentDidMount(){
> 
>   }
> ```
> 
> 大佬看一下

看了下官网源码，只要props发生改变就会调用validateAll()。

FormBinderWrapper.jsx
`_createClass(IceFormBinderWrapper, [{
    key: 'componentWillReceiveProps',
    value: function componentWillReceiveProps(nextProps) {
      if ('value' in nextProps) {
        this.setState({
          value: nextProps.value || {}
        }, this.validateAll);
      }
    }
  }`

**Comment by bluexuchun** [comment]
> > > 发一下 componentWillMount() componentDidMount() 代码
> > 
> > 
> > ```
> >   componentWillMount(){
> >     const activityId = this.props.history.params.activityId;
> >     // 正确获取到activityId的值，去获取他的值
> >     if(activityId != 'create'){
> >       ajaxTo('api.php?entry=sys&c=logistics&a=company&do=detail',{'id':activityId})
> >       .then((res)=>{
> >         console.log(res)
> >         let currentData = {...res};
> > 
> >         // 给地图初始信息
> >         if(res.address && res.latitude && res.longitude){
> >           let mapDataSource = {...this.state.mapDataSource};
> >           mapDataSource.location = {
> >             type:'change',
> >             name:'',
> >             longitude:res.longitude,
> >             latitude:res.latitude
> >           }
> >           this.setState({
> >             mapDataSource:mapDataSource
> >           })
> >         }
> > 
> >         console.log(this.state.mapDataSource)
> > 
> >         currentData.contactLists = res.contactLists ? res.contactLists : [{}];
> > 
> >         currentData.bg_picture = res.bg_picture ? this.changeImg(res.bg_picture) : [];
> >         currentData.cd_picture = res.cd_picture ? this.changeImg(res.cd_picture) : [];
> >         currentData.mt_picture = res.mt_picture ? this.changeImg(res.mt_picture) : [];
> >         currentData.other_picture = res.other_picture ? this.changeImg(res.other_picture) : [];
> > 
> >         currentData.phonelits = res.phonelits ? res.phonelits : [{}];
> > 
> > 
> >         currentData.status = res.status == 1 ? true : false;
> >         currentData.is_recommend = res.is_recommend == 1 ? true : false;
> >         currentData.hotline = res.hotline == 1 ? true : false;
> >         currentData.contact = !res.contact ? [{}] : res.contact;
> > 
> > 
> >         this.setState({
> >           ...currentData,
> >           introduce:res.introduce
> >         });
> >       })
> >     }else{
> >       let mapDataSource = {...this.state.mapDataSource};
> >       mapDataSource.location = {
> >         type:'init',
> >         name:'',
> >         longitude:0,
> >         latitude:0
> >       }
> >       this.setState({
> >         propties:1,
> >         mapDataSource:mapDataSource
> >       })
> > 
> >       setTimeout(() => {
> >         // 防止输入表格无限初始化地图
> >         mapDataSource.location.type = 'normal';
> >         this.setState({
> >           mapDataSource:mapDataSource
> >         })
> >       },2000)
> >     }
> >   }
> > 
> >   componentDidMount(){
> > 
> >   }
> > ```
> > 大佬看一下
> 
> 看了下官网源码，只要props发生改变就会调用validateAll()。
> 
> FormBinderWrapper.jsx
> `_createClass(IceFormBinderWrapper, [{ key: 'componentWillReceiveProps', value: function componentWillReceiveProps(nextProps) { if ('value' in nextProps) { this.setState({ value: nextProps.value || {} }, this.validateAll); } } }`

噢。。原来是这样啊 那有没有办法能够点击按钮去触发 而不是自动触发呢？

**Comment by rickytjx** [comment]
> > > > 发一下 componentWillMount() componentDidMount() 代码
> > > 
> > > 
> > > ```
> > >   componentWillMount(){
> > >     const activityId = this.props.history.params.activityId;
> > >     // 正确获取到activityId的值，去获取他的值
> > >     if(activityId != 'create'){
> > >       ajaxTo('api.php?entry=sys&c=logistics&a=company&do=detail',{'id':activityId})
> > >       .then((res)=>{
> > >         console.log(res)
> > >         let currentData = {...res};
> > > 
> > >         // 给地图初始信息
> > >         if(res.address && res.latitude && res.longitude){
> > >           let mapDataSource = {...this.state.mapDataSource};
> > >           mapDataSource.location = {
> > >             type:'change',
> > >             name:'',
> > >             longitude:res.longitude,
> > >             latitude:res.latitude
> > >           }
> > >           this.setState({
> > >             mapDataSource:mapDataSource
> > >           })
> > >         }
> > > 
> > >         console.log(this.state.mapDataSource)
> > > 
> > >         currentData.contactLists = res.contactLists ? res.contactLists : [{}];
> > > 
> > >         currentData.bg_picture = res.bg_picture ? this.changeImg(res.bg_picture) : [];
> > >         currentData.cd_picture = res.cd_picture ? this.changeImg(res.cd_picture) : [];
> > >         currentData.mt_picture = res.mt_picture ? this.changeImg(res.mt_picture) : [];
> > >         currentData.other_picture = res.other_picture ? this.changeImg(res.other_picture) : [];
> > > 
> > >         currentData.phonelits = res.phonelits ? res.phonelits : [{}];
> > > 
> > > 
> > >         currentData.status = res.status == 1 ? true : false;
> > >         currentData.is_recommend = res.is_recommend == 1 ? true : false;
> > >         currentData.hotline = res.hotline == 1 ? true : false;
> > >         currentData.contact = !res.contact ? [{}] : res.contact;
> > > 
> > > 
> > >         this.setState({
> > >           ...currentData,
> > >           introduce:res.introduce
> > >         });
> > >       })
> > >     }else{
> > >       let mapDataSource = {...this.state.mapDataSource};
> > >       mapDataSource.location = {
> > >         type:'init',
> > >         name:'',
> > >         longitude:0,
> > >         latitude:0
> > >       }
> > >       this.setState({
> > >         propties:1,
> > >         mapDataSource:mapDataSource
> > >       })
> > > 
> > >       setTimeout(() => {
> > >         // 防止输入表格无限初始化地图
> > >         mapDataSource.location.type = 'normal';
> > >         this.setState({
> > >           mapDataSource:mapDataSource
> > >         })
> > >       },2000)
> > >     }
> > >   }
> > > 
> > >   componentDidMount(){
> > > 
> > >   }
> > > ```
> > > 大佬看一下
> > 
> > 
> > 看了下官网源码，只要props发生改变就会调用validateAll()。
> > FormBinderWrapper.jsx
> > `_createClass(IceFormBinderWrapper, [{ key: 'componentWillReceiveProps', value: function componentWillReceiveProps(nextProps) { if ('value' in nextProps) { this.setState({ value: nextProps.value || {} }, this.validateAll); } } }`
> 
> 噢。。原来是这样啊 那有没有办法能够点击按钮去触发 而不是自动触发呢？

因为你componentWillMount()中有数据交互并更新状态，你可以更新完状态数据后再渲染IceFormBinderWrapper组件

**Comment by bluexuchun** [comment]
> > > > > 发一下 componentWillMount() componentDidMount() 代码
> > > > 
> > > > 
> > > > ```
> > > >   componentWillMount(){
> > > >     const activityId = this.props.history.params.activityId;
> > > >     // 正确获取到activityId的值，去获取他的值
> > > >     if(activityId != 'create'){
> > > >       ajaxTo('api.php?entry=sys&c=logistics&a=company&do=detail',{'id':activityId})
> > > >       .then((res)=>{
> > > >         console.log(res)
> > > >         let currentData = {...res};
> > > > 
> > > >         // 给地图初始信息
> > > >         if(res.address && res.latitude && res.longitude){
> > > >           let mapDataSource = {...this.state.mapDataSource};
> > > >           mapDataSource.location = {
> > > >             type:'change',
> > > >             name:'',
> > > >             longitude:res.longitude,
> > > >             latitude:res.latitude
> > > >           }
> > > >           this.setState({
> > > >             mapDataSource:mapDataSource
> > > >           })
> > > >         }
> > > > 
> > > >         console.log(this.state.mapDataSource)
> > > > 
> > > >         currentData.contactLists = res.contactLists ? res.contactLists : [{}];
> > > > 
> > > >         currentData.bg_picture = res.bg_picture ? this.changeImg(res.bg_picture) : [];
> > > >         currentData.cd_picture = res.cd_picture ? this.changeImg(res.cd_picture) : [];
> > > >         currentData.mt_picture = res.mt_picture ? this.changeImg(res.mt_picture) : [];
> > > >         currentData.other_picture = res.other_picture ? this.changeImg(res.other_picture) : [];
> > > > 
> > > >         currentData.phonelits = res.phonelits ? res.phonelits : [{}];
> > > > 
> > > > 
> > > >         currentData.status = res.status == 1 ? true : false;
> > > >         currentData.is_recommend = res.is_recommend == 1 ? true : false;
> > > >         currentData.hotline = res.hotline == 1 ? true : false;
> > > >         currentData.contact = !res.contact ? [{}] : res.contact;
> > > > 
> > > > 
> > > >         this.setState({
> > > >           ...currentData,
> > > >           introduce:res.introduce
> > > >         });
> > > >       })
> > > >     }else{
> > > >       let mapDataSource = {...this.state.mapDataSource};
> > > >       mapDataSource.location = {
> > > >         type:'init',
> > > >         name:'',
> > > >         longitude:0,
> > > >         latitude:0
> > > >       }
> > > >       this.setState({
> > > >         propties:1,
> > > >         mapDataSource:mapDataSource
> > > >       })
> > > > 
> > > >       setTimeout(() => {
> > > >         // 防止输入表格无限初始化地图
> > > >         mapDataSource.location.type = 'normal';
> > > >         this.setState({
> > > >           mapDataSource:mapDataSource
> > > >         })
> > > >       },2000)
> > > >     }
> > > >   }
> > > > 
> > > >   componentDidMount(){
> > > > 
> > > >   }
> > > > ```
> > > > 大佬看一下
> > > 
> > > 
> > > 看了下官网源码，只要props发生改变就会调用validateAll()。
> > > FormBinderWrapper.jsx
> > > `_createClass(IceFormBinderWrapper, [{ key: 'componentWillReceiveProps', value: function componentWillReceiveProps(nextProps) { if ('value' in nextProps) { this.setState({ value: nextProps.value || {} }, this.validateAll); } } }`
> > 
> > 
> > 噢。。原来是这样啊 那有没有办法能够点击按钮去触发 而不是自动触发呢？
> 
> 因为你componentWillMount()中有数据交互并更新状态，你可以更新完状态数据后再渲染IceFormBinderWrapper组件

好的 谢谢 我去尝试下

**Comment by noyobo** [comment]
`@icedesign/form-binder@0.1.13` 修复此问题
