### ISSUE TITLE
自定义模板勾选登录注册示例后运行时无法直接使用登录注册功能

### ISSUE THREAD

**Issue by urright** [alibaba/ice#908]
## 环境信息

- 操作系统：Win10专业版
- Iceworks 版本： 2.8

## 问题描述
自定义模板勾选登录注册示例后运行时无法直接使用登录注册功能,退出无效。

**Comment by chenbin92** [comment]
@urright 可以在浏览器地址栏输入路由进入，顶部导航的菜单链接没有改过来，下个版本会修复

**Comment by chenbin92** [comment]
已修复
