### ISSUE TITLE
Button.Split onClick无效

### ISSUE THREAD

**Issue by Symous** [alibaba/ice#914]
## 环境信息

- 操作系统：macOS 10.13.6
- Iceworks 版本： 2.8.0

## 问题描述

Button.Split 的 onClick属性并没有作用，参考官方文档中的示例：https://alibaba.github.io/ice/playground?from=demo

**Comment by noyobo** [comment]
请补充相应代码，和错误描述步骤。

**Comment by Symous** [comment]
@noyobo 不清楚为什么官方文档中的在线预览（playgroud）总是跳转到同一个页面，所以我粘贴的例子失效了。其实就是SplitButton的示例代码，请移步这里：https://codesandbox.io/s/r5l1y04rq4 。

**Comment by Symous** [comment]
https://codesandbox.io/s/r5l1y04rq4 已删掉其中的无用代码。

**Comment by Symous** [comment]
是我理解的问题，这个组件没毛病...    :D
