### ISSUE TITLE
创建项目页面

### ISSUE THREAD

**Issue by mowatermelon** [alibaba/ice#92]
## 1 页面布局建议
建议`创建项目按钮`在小屏情况下，可以使用居中对齐，但是在`渲染进程`全屏情况下，或者按钮的计算出来的宽度超过了`步骤盒子`(创建项目的三个步骤所在的盒子)，这个时候希望`创建项目按钮`能够和`步骤盒子`左对齐。

![image](https://user-images.githubusercontent.com/18508817/35794304-2cc1b618-0a90-11e8-9a94-217dae7f6208.png)

## 2 页面按键注册

希望在创建项目这个页面默认注册一个按键行为，点击`Enter`键就直接触发了创建项目事件。

**Comment by yujiangshui** [comment]
视觉这块我们已经出了新版设计稿，会在正式版整体优化掉，届时界面可能会变化很多。
