### ISSUE TITLE
support for english and other languages

### ISSUE THREAD

**Issue by Nitinrajyadav** [alibaba/ice#921]
are there any plans for English and other languages support?

**Comment by yuanyan** [comment]
@Nitinrajyadav Yes, we will support english in November.

**Comment by vincentclaes** [comment]
any concrete date yet about the release in english?

**Comment by markrey** [comment]
Is it planned for launch soon?

**Comment by imsobear** [comment]
At present, internationalization is a big project, we are planning now, and progress will be synchronized to you.

**Comment by imsobear** [comment]
ICE internationalization includes the following aspects:

- Iceworks i18n
- ice-scripts/ice-devtools i18n
- docs i18n
- maybe we will create another react-materils for international

**Comment by starcruizer** [comment]
Hi @imsobear, I would like to solve this issue as a part of my SoC2019 and would like contribute to the open source. Can you please guide me in preparing my proposal, as it is my first time.
