### ISSUE TITLE
vue 区块“基于element的标签页表格组合”不合适地使用 key 作为属性名称

### ISSUE THREAD

**Issue by FairyEver** [alibaba/ice#925]
## 环境信息

- 操作系统：macOS 10.13.4
- Iceworks 版本： 2.8.0

## 问题描述

vue 区块 “基于element的标签页表格组合” 代码有语法错误，`key` 属性不应该在循环的组件中被使用

https://github.com/alibaba/ice/blob/5e94ee4accc25d5b2760ed53e63ea314dd809d96/vue-materials/blocks/TabTable/src/TabTable.vue#L21-L22

组件：

https://github.com/alibaba/ice/blob/7d02c7c6f21618876942f09d5ebf8244d65c83df/vue-materials/blocks/TabTable/src/components/DeleteBalloon.vue#L23-L26

https://github.com/alibaba/ice/blob/7d02c7c6f21618876942f09d5ebf8244d65c83df/vue-materials/blocks/TabTable/src/components/EditDialog.vue#L65-L68

## 错误信息

```
[Vue warn]: "key" is a reserved attribute and cannot be used as component prop.
```

## 建议

可以给 `key` 更改一个非保留名称

**Comment by chenbin92** [comment]
@FairyEver  可以提个 MR
