### ISSUE TITLE
阿里云OSS上传报错

### ISSUE THREAD

**Issue by cat952445230** [alibaba/ice#927]
## 环境信息

- 操作系统：
- Iceworks 版本： 2.8.0

## 问题描述

![9e7c8de3-d580-4c97-96e6-bc74cde866b7](https://user-images.githubusercontent.com/19665517/45794069-6d1e0d80-bcc7-11e8-98e6-13a4f5ffc548.png)

## 错误信息

The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.

**Comment by LuciferLi** [comment]
+1

**Comment by noyobo** [comment]
最新版本已经解决这个问题，升级后看下  @LuciferLi

**Comment by LuciferLi** [comment]
升级图形化工具吗？
