### ISSUE TITLE
配置字体本地化和离线化构建项目后，依旧访问alicdn的字体

### ISSUE THREAD

**Issue by sc8816** [alibaba/ice#928]
## 环境信息

- 操作系统：win10
- Iceworks 版本： 2.8.0

## 问题描述
![image](https://user-images.githubusercontent.com/30044191/45793641-b79e8a80-bcc5-11e8-811d-738136b726d3.png)
![image](https://user-images.githubusercontent.com/30044191/45793656-cbe28780-bcc5-11e8-8ad8-72da6475625a.png)
![image](https://user-images.githubusercontent.com/30044191/45793681-e3ba0b80-bcc5-11e8-9183-b53a723fa766.png)
在完成此配置后dev环境下正常，prod环境下字体文件是本地访问，但是字体文件路径不对
少了pms/manage/，
然后在发布时候写了脚本给package.json buildConfig 上加了publicUrl：pms/manage/
![image](https://user-images.githubusercontent.com/30044191/45794474-760fde80-bcc9-11e8-9cd8-38dbed739e6f.png)

## 错误信息
本地dev环境下
![image](https://user-images.githubusercontent.com/30044191/45794304-8ffcf180-bcc8-11e8-92e1-50092048e2a8.png)
服务器环境下
![image](https://user-images.githubusercontent.com/30044191/45794193-09e0ab00-bcc8-11e8-8082-50389e9be367.png)

**Comment by noyobo** [comment]
离线化构建限定 publicPath 必须为 './'

**Comment by sc8816** [comment]
请问如果我想把字体文件打包在pms/manage/下有解决办法吗

**Comment by noyobo** [comment]
将构建后的内容放到 `服务器/pms/manage/` 目录下就可以了，前提 index.html 与资源不在同一个文件夹下。
