### ISSUE TITLE
添加删除项目所在目前的功能

### ISSUE THREAD

**Issue by yuanyan** [alibaba/ice#93]
目前在 iceworks 里删除项目只是删除记录，不删除真实项目目录，需要这个功能的可以 +1，不需要可以 -1

**Comment by xujiaqi1994** [comment]
+1

**Comment by GGStupid** [comment]
+1

**Comment by mowatermelon** [comment]
+1

**Comment by liforgithub** [comment]
+1

**Comment by adamqqqplay** [comment]
+1

**Comment by wssgcg1213** [comment]
具体一些, 这个我觉得应该是一个选择或者是 checkbox 的选项, 类似这种交互的UI @noyobo 
![image](https://user-images.githubusercontent.com/3922719/36581156-8bee71a2-18a6-11e8-8479-ae79e7285cfa.png)
