### ISSUE TITLE
表格提供支持选择分页大小配置

### ISSUE THREAD

**Issue by newRomantic** [alibaba/ice#932]
## 环境信息

- 操作系统：macOS 10.13.4 
- Iceworks 版本： 2.6.0

## 问题描述

表格提供支持选择分页大小配置，诸如分页时可以选择分页 pageSize 10/25/50，可扩展性会更佳。

## 错误信息

无

**Comment by noyobo** [comment]
表格当前页的数据就是 dataSource 的长度。

**Comment by newRomantic** [comment]
No，不是这个意思。是前端提供 pageSize（10/25/50） 参数去请求，返回特定条数（10/25/50）的 数据。
