### ISSUE TITLE
Rating控件无法打0分以及对应的onchange事件中参数过少，只能取到一个value参数

### ISSUE THREAD

**Issue by ShaoYQ** [alibaba/ice#941]
## 环境信息

- 操作系统：
- Iceworks 版本： 2.8.0

## 问题描述

1.Rating控件无法打0分，能否增加此项配置？
2.Rating控件的onchange事件中参数过少，只能取到一个value参数。有没有办法取到事件的event参数？

## 错误信息

无

**Comment by boiawang** [comment]
@youluna 看下这个问题
