### ISSUE TITLE
vue-cli-service & dist/index.html &  absolute path bug

### ISSUE THREAD

**Issue by xyzdata** [alibaba/ice#947]
## 环境信息

- 操作系统：win10pro x64
- Iceworks 版本： 2.8

## 问题描述

> vue-cli-service & dist/index.html & absolute path bug

![image](https://user-images.githubusercontent.com/29531779/45997884-a85b7a80-c0d3-11e8-9d73-dc86686368e9.png)

## 错误信息

> resources path error

![image](https://user-images.githubusercontent.com/29531779/45998274-ec02b400-c0d4-11e8-8773-1e175ee29ef6.png)

**Comment by xyzdata** [comment]
# wanted

> relative path

![image](https://user-images.githubusercontent.com/29531779/45997946-d2ad3800-c0d3-11e8-8a80-d1b414b7bc25.png)

**Comment by chenbin92** [comment]
@xyzdata  vue 工程使用的是 vue-cli，可以参考 vue-cli 相关文档自行解决
