### ISSUE TITLE
创建项目

### ISSUE THREAD

**Issue by fuqihan** [alibaba/ice#95]
windows下
1. 创建项目时点击设置，在点回项目，没有看见创建的项目，需要点击打开项目才能导入....
2. 安装中的项目启动其他服务会报错，感觉可以安装完成之前禁用....

**Comment by yujiangshui** [comment]
已经记录下，将在下个版本中修复，感谢反馈

**Comment by noyobo** [comment]
1. 任务修改为在后台运行，创建成功后自动添加。

**Comment by noyobo** [comment]
问题1  已在 0.1.5 版本优化了

问题2 安装过程中，或者依赖缺失启动都会失败，已对安装过程中做了禁用处理。
