### ISSUE TITLE
不支持ie

### ISSUE THREAD

**Issue by cpa0701** [alibaba/ice#950]
## 环境信息

- 操作系统：window
- Iceworks 版本： 2.6.0

## 问题描述

用icework客户端新建项目
![image](https://user-images.githubusercontent.com/24648209/46121668-6e12ea00-c247-11e8-917d-962e64f2e844.png)，ie浏览器无法兼容

## 错误信息

index.js中的箭头函数报错

**Comment by chenbin92** [comment]
支持 IE10 +
