### ISSUE TITLE
Table组件不支持表头<th>和表内容<td>独立样式和布局

### ISSUE THREAD

**Issue by chenhongen** [alibaba/ice#953]
## 环境信息

- 操作系统：all
- Iceworks 版本： all

## 问题描述

现在Table组件仅有align与style/classname属性作用于整个列，无法实现表头<th>和表内容<td>独立样式和布局。比如实现如下效果：

![demo](https://user-images.githubusercontent.com/16499303/46239412-fcfc3f80-c3ca-11e8-824f-7e271aead96c.png)

**Comment by chenbin92** [comment]
可以通过 `Table.ColumnGroup` 自定义
