### ISSUE TITLE
FormBinder: error message 出现的权重值

### ISSUE THREAD

**Issue by SoloJiang** [alibaba/ice#956]
## 环境信息

- 操作系统：10.13.4
- Iceworks 版本： 2.9.0

## 问题描述

写法1：
![image](https://user-images.githubusercontent.com/14757289/46241259-68a0d580-c3e8-11e8-8895-8bf409181a2c.png)
当输入框为空时，出现的是： 必须输入数字；
预期效果：必填 或者 必填，必须输入数字；
写法2：
![image](https://user-images.githubusercontent.com/14757289/46241280-e533b400-c3e8-11e8-92f8-6fbe9b7122af.png)
当输入框中数字小于200时，出现的是： 必填；
预期效果：数字部分累加要超过 200

**Comment by noyobo** [comment]
目前如果声明了 message ，则使用。  你可以把 message 中的去掉。解决这个问题。下个版本后。我们会优化次此处的逻辑

**Comment by chenbin92** [comment]
fixed
