### ISSUE TITLE
Formbinder & 表单组件：IceFormBinderWrapper 中 value 和 组件 defaultValue 的优先级

### ISSUE THREAD

**Issue by SoloJiang** [alibaba/ice#957]
## 环境信息

- 操作系统：10.13.4
- Iceworks 版本： 2.90

## 问题描述

当 IceFormBinderWrapper  存在 value 时，组件的 defaultValue 不生效，这一块需要讨论默认值的优先级问题。

**Comment by SoloJiang** [comment]
formbinder 校验 value 的 type 时，所有的 value 都当成 string 去处理了，type 为 number 等值的时候都不生效。

**Comment by noyobo** [comment]
非 string 类型的校验可通过 validator 自定义方法校验。

如果声明了 number 同时需要 组件的返回值需要是一个 number 。

同时是否可以有 demo 演示下您的场景 ， 可 fork https://codesandbox.io/s/w78wrkx81l 这个例子提交下。
