### ISSUE TITLE
支持水平导航栏布局功能问题

### ISSUE THREAD

**Issue by turkeyaa** [alibaba/ice#964]
## 环境信息

- 操作系统：
- Iceworks 版本： Mac

## 问题描述

在新建自定义模板的时候，布局模块下。目前是侧边栏，有没有顶部导航栏的功能？或者如何更简单的扩展该功能？

## 错误信息

无

## 功能扩展

实现水平导航栏布局功能

## 截图

<img width="289" alt="layout" src="https://user-images.githubusercontent.com/7940089/46589421-edbc7680-cadb-11e8-9c77-c3b87488741f.png">

**Comment by noyobo** [comment]
上面的顶部导航是否满足你的需求？

布局通过这些参数生成了对应的布局框架，你可以在框架里填入符合自己的导航内容。你看看生成后的代码。

**Comment by turkeyaa** [comment]
顶部导航栏不支持。我是希望能够把侧边栏导航布局，可以转换成水平导航栏布局。 类似于那种博客的框架。感觉现在都是基于后台管理的一套框架来实现的，不知道有没有考虑水平导航的布局功能，或者自己来扩展

**Comment by noyobo** [comment]
布局和组件实现我理解是没有关系的。

水平导航你看看这个 demo https://ice.alibaba-inc.com/component/nav#%E5%9F%BA%E6%9C%AC  是否是这样的？

**Comment by turkeyaa** [comment]
感谢了，可能我还不到熟悉。但是上面的链接我打不开😂

**Comment by noyobo** [comment]
https://alibaba.github.io/ice/component/nav

**Comment by turkeyaa** [comment]
感觉是可以的...
但是，上面的组件是基于react的框架的吧，我看的是vue，没有组件文档。能支持vue吗？

**Comment by noyobo** [comment]
自定义模板是 react 的。  VUE 的主要由社区参与共建，布局的导航组件的，你可以看下  iview 或者 element-ui

**Comment by turkeyaa** [comment]
清楚了,thx...

**Comment by chenbin92** [comment]
@turkeyaa 目前 Iceworks 内置的 vue 模板是使用的 element-ui ，对应的水平导航 http://element-cn.eleme.io/#/zh-CN/component/menu
