### ISSUE TITLE
ICELAND 可视化区块搭建 Beta 版本使用手册

### ISSUE THREAD

**Issue by Empireo** [alibaba/ice#973]
## 特性介绍

Iceland 是一个搭建产品，帮助搭建者基于丰富的物料快速拖拽出想要的区块，重新定义前端区块搭建流程，使区块搭建更加智能化。

产品集成了海量高质量物料，全程可视化搭建，代码一键生成，区块一键导入页面等特性，提供了区块搭建的全新解决方案。

产品目前还处于测试阶段，我们将持续倾听用户诉求，朝着搭建智能化的目标不断更新，如果使用过程中存在问题，请钉钉扫描最下方二维码加入飞冰交流群，随时向我们反馈。

## 快速开始

这部分将引导你通过 Iceland 快速搭建一个简单的区块，并通过 Iceworks 用它生成你的页面，使你快速体验到可视化搭建的魅力。

本文档只对搭建自定义区块到生成页面整个操作流程做一个简单的介绍，Iceland 的更多特性和用法，用户可以在实际使用中继续发掘。

### 新建区块

首先启动 <a href="https://alibaba.github.io/ice/">Iceworks</a> ，打开【区块】页面，选择【自定义区块】选项卡；

<img src="https://img.alicdn.com/tfs/TB16WhegpzqK1RjSZFCXXbbxVXa-982-712.png">

点击【新建自定义区块】，为区块命名，点击【创建区块】；

<img src="https://img.alicdn.com/tfs/TB1LDphgyrpK1RjSZFhXXXSdXXa-982-712.png">

下载必要的物料数据后，弹出 Iceland 搭建页面。

<img src="https://img.alicdn.com/tfs/TB1go4rgSzqK1RjSZFjXXblCFXa-1392-832.png">

### 添加选项卡

接下来让我们用 Iceland 搭建一个带搜索的选项卡区块，首先点击物料面板上的【组件】按钮，选择【选项卡】分类或在【搜索栏】搜索选项卡，将选项卡添加到画布；

<img src="https://img.alicdn.com/tfs/TB1m20rgMHqK1RjSZFkXXX.WFXa-1392-832.png">

通过拖拽或者调整属性面板的属性的方式，调整选项卡的宽度，接着点击图层面板中的【选项卡面板】图层，调整选项卡的高度，在【选项卡】图层的属性面板的【属性配置】中可以修改选项卡的标题。

<img src="https://img.alicdn.com/tfs/TB1D38rgQvoK1RjSZFNXXcxMVXa-1392-832.png">

> 进阶技巧：

1. 觉得图层面板好多图层的名字都一样，分辨不清怎么办？
	
	答：双击图层面板里的图层可以对图层进行重命名
	
2. 觉得调整属性好麻烦，只想靠拖拽解决一切怎么办？

	答：点击标尺可以设置参考线，用参考线辅助组件固定位置

### 添加输入框

接下来让我们添加输入框，首先在物料面板点击【组件】按钮，通过搜索或选择分类的方式找到【主要搜索框】组件，添加组件到画布中，在属性面板的【属性配置】中可以修改搜索框的内容；

<img src="https://img.alicdn.com/tfs/TB1yeXrgQvoK1RjSZPfXXXPKFXa-1392-832.png">

> 可选步骤： 

1. 鼠标框选画布中的多个图层，或者 Cmd/Ctrl + 鼠标点击多选图层，通过右上角菜单面板的【群组】按钮将图层整合为一组；

> 进阶技巧：

1. 有时添加组件到画布上，却点不到组件是为什么？

	答：可能是图层被覆盖住了，可以通过右上角菜单面板的【排序】按钮重排顺序；

接下来我们可以在物料面板的【图标】项添加 iconfont ，在【元件】面板添加富文本或其他内容，或调整组件颜色等方式美化完善我们的区块，这部分可根据自己需要进行，就不再演示了；
	
### 区块生成页面

点击【预览】按钮，可以查看我们的区块在前端展示的效果，点击【截图并保存】保存我们的区块；

<img src="https://img.alicdn.com/tfs/TB1EaVkgxTpK1RjSZFMXXbG_VXa-1392-832.png">

关闭搭建页面，回到 Iceworks ，在生成页面界面选择我们的自定义区块，就可以将你自己搭建的区块转换成代码；

<img src="https://img.alicdn.com/tfs/TB1LINggsbpK1RjSZFyXXX_qFXa-982-712.png">

# 新特性-Table搭建

## 功能
- 画布Editor可以进行删除与加减行列的操作
- 可以选中单元格进入单元格搭建模式，单元格中可以添加任意复杂组件
- 支持对每行的单元格中的组件进行差异化的属性配置，满足多样化的设计需求

## 画布Editor

![](https://cdn.nlark.com/lark/0/2018/png/184/1535011258743-26eb3a63-28f1-444d-9ed9-d94979020586.png "")

- 选中Table后会在Table显示一个操作层Editor，按区域划分分成四个区域
    - 表格选择区
        - 选中该区域时属性面板上显示Table的属性面板，在对Table自身的属性进行配置之外，还可以对整体的行列进行加减操作。
        

![](https://cdn.nlark.com/lark/0/2018/png/184/1535011810972-3ae6f7b3-6a48-41a0-8cdf-b1a74225bdf5.png "")

- 列选择区
  - 选中该区域时点击右边的箭头展示配置menu，可以进行加减列操作，同时属性面板显示列对应的属性面板
        

![](https://cdn.nlark.com/lark/0/2018/png/184/1535012640500-6d2901ed-7f75-4aa0-8b26-e75f1f45c864.png "")

        
        

![](https://cdn.nlark.com/lark/0/2018/png/184/1535012708469-eb98f3b1-d25f-45ef-be9d-b928208f6306.png "")

- 行选择区
  - 选中该区域时点击下边的箭头展示配置menu，可以进行加减行操作，同时属性面板显示行对应的属性面板，可以调整行高
        

![](https://cdn.nlark.com/lark/0/2018/png/184/1535012803890-ef132ffe-8709-46b1-9ae1-03cfa3889f42.png "")

        

![](https://cdn.nlark.com/lark/0/2018/png/184/1535012845910-a4a15c54-a51e-4143-9011-3a53e2ac4b40.png "")

    
- 单元格选择区
  - 点击单元格选择区，进入单元格编辑模式，弹出一个黑色透明蒙层，可以从组件面板中添加组件到单元格中，点击蒙层时退出单元格编辑模式
        

![](https://cdn.nlark.com/lark/0/2018/png/184/1535012976524-0fb88783-57bb-4bfa-80e1-991a842bef8b.png "")

注：单元格编辑模式中的一些联动说明
- 在单元格中对组件进行删除操作时，会将同一行其他所有其他单元格中相应组件删除
- 进行移动操作时，会改变同行中其他单元格的位置
- 只有改变组件属性时不会影响到其他单元格        

如果使用过程中遇到任何问题或者有对产品的建议，欢迎扫码加入答疑钉钉群向我们反馈：

<img src="https://ice.alicdn.com/assets/images/ice-group.png">

**Comment by geek4go** [comment]
太好了！

**Comment by geek4go** [comment]
离可视化编程越来越近了

**Comment by furfar** [comment]
目前处定义的区块只支持PC端，不支持移动端，还是说是自动自适应的？

**Comment by chenbin92** [comment]
@furfar  目前只支持 PC 端，后面会基于 flex 布局可以自适应

**Comment by automano** [comment]
以后做前端开发的，都是现在的美工。现在前端的，以后都变成了前端后台开发。哈哈哈。美好的未来指日可待啊！

**Comment by Empireo** [comment]
> 点击预览没有反应。

已经向画布添加物料了吗，没有物料是不会开启预览的

**Comment by moxun33** [comment]
我发现是添加了对话框后点击预览就会没反应，添加其他组件可以预览。已重试过几次，问题相同。 @Empireo

**Comment by Empireo** [comment]
> 我发现是添加了对话框后点击预览就会没反应，添加其他组件可以预览。已重试过几次，问题相同。 @Empireo

@moxun33 感谢你的反馈，请先不要使用这个物料，我们会尽快修复这个问题

**Comment by Empireo** [comment]
@yuanchanglong 未来会进行开源，目前产品还不够成熟

**Comment by yuanchanglong** [comment]
> @yuanchanglong 未来会进行开源，目前产品还不够成熟

好的，谢谢！

**Comment by 672064406zerui** [comment]
这个自定义 只支持react吗

**Comment by imsobear** [comment]
@672064406zerui 是的，搭建部分目前支持 React

**Comment by zlapexdev** [comment]
最新的icework，怎么没有自定义区块了呢？

**Comment by alvinhui** [comment]
@zlapexdev 我们在 4.0 版本中重新优化上线了这个功能。

**Comment by someoneoylp** [comment]
现在是没有这个功能了吗？

**Comment by imsobear** [comment]
> 现在是没有这个功能了吗？

https://ice.work/docs/iceworks/guide/visual-construction

**Comment by someoneoylp** [comment]
> > 现在是没有这个功能了吗？
> 
> https://ice.work/docs/iceworks/guide/visual-construction

请问如何将fusion组件导入呢？是在Add Material Source地方导入吗？如果是的话，url应该填什么呢？

**Comment by imsobear** [comment]
> > > 现在是没有这个功能了吗？
> > 
> > 
> > https://ice.work/docs/iceworks/guide/visual-construction
> 
> 请问如何将fusion组件导入呢？是在Add Material Source地方导入吗？如果是的话，url应该填什么呢？

默认已经集成了 fusion 的物料呀
