### ISSUE TITLE
无法唤起VS CODE

### ISSUE THREAD

**Issue by wqh17101** [alibaba/ice#979]
## 环境信息

- 操作系统：Win10
- Iceworks 版本： 2.10.0

## 问题描述

已安装vs code,但是无法使用默认的设置调用VS CODE

使用脚本启动也不太对

## 错误信息

![image](https://user-images.githubusercontent.com/26429138/46934375-19b29b80-d08a-11e8-9783-7bc609ef13be.png)
![image](https://user-images.githubusercontent.com/26429138/46934380-20d9a980-d08a-11e8-8f42-5d71aa5102bd.png)
![image](https://user-images.githubusercontent.com/26429138/46934395-2d5e0200-d08a-11e8-8ffb-146924b86b13.png)
![image](https://user-images.githubusercontent.com/26429138/46934408-38189700-d08a-11e8-817d-dd723e0d90b6.png)

**Comment by noyobo** [comment]
```
code ${cwd}
```

**Comment by wqh17101** [comment]
解决了，谢谢
