### ISSUE TITLE
模板选择引导，lite 与 pro 的区别。

### ISSUE THREAD

**Issue by noyobo** [alibaba/ice#98]
- lite 是简单的模块，页面较少，配置少。
  - 需要添加页面
- pro 提供丰富的区块组合，多页面展示。
  - 使用上需要删除更多的内容

目前用户无法感知到两者的差异

**Comment by chenbin92** [comment]
* [ice-design-lite](https://github.com/alibaba/ice/tree/master/scaffords/ice-design-lite)  模板的目的是让用户从 0 到 1 的过程，只提供基础的页面，路由和菜单展示。

*  [ice-design-pro](https://github.com/alibaba/ice/tree/master/scaffords/ice-design-pro) 是基于区块搭建的集合，主要用于展示区块组合之后的效果以及现有区块的分类。

*  后续会提供其他基于行业性质的模板，以及主题方案，丰富模板物料

**Comment by chenbin92** [comment]
@yuanyan  done
