### ISSUE TITLE
可以提供一个nuxt的物料源嘛

### ISSUE THREAD

**Issue by KloveML** [alibaba/ice#982]
可以提供一个nuxt的物料源嘛
这是我写的关于nuxt的后台模板，能根据接口返回的参数来进行权限跳转
https://github.com/KloveML/nuxt_project_template.git
想添加进去 有什么办法吗

**Comment by noyobo** [comment]
可以提交模板到  vue-materials/scaffolders 下 . https://alibaba.github.io/ice/docs/materials/custom-vue-materials

**Comment by chenbin92** [comment]
建议以第三方物料源的形式开发，官网目前只接受基于 element-ui 的物料
