### ISSUE TITLE
使用markdown docs 如何插入代码块

### ISSUE THREAD

**Issue by wqh17101** [alibaba/ice#983]
## 环境信息

- 操作系统：win10
- Iceworks 版本： 2.10

## 问题描述
我发现语法是markdown docs 页面的语法是

![image](https://user-images.githubusercontent.com/26429138/46992069-0ca1b500-d13b-11e8-9a14-07501e2a688c.png)

如果 {markdown code} 中含有代码块 ` 该怎么写

**Comment by noyobo** [comment]
可以使用反斜杠输入

```
const text = `
code
\`\`\`
markdown
\`\`\`
`
```

**Comment by QinanWu** [comment]
code
`Hello Word`

**Comment by G202liukaili** [comment]
c.choseLesson(s1.name);
		c.needtui(s1.name);

**Comment by y00273676** [comment]
\`\`\`
123
\`\`\`

**Comment by y00273676** [comment]
‘’‘
123
’‘’

**Comment by y00273676** [comment]
`123
123`
