### ISSUE TITLE
ice 不使用Iceworks 创建react 单页面项目 无法加载css 样式

### ISSUE THREAD

**Issue by Sessionh** [alibaba/ice#984]
## 环境信息

- 操作系统：
- Iceworks 版本： 不使用iceworks 使用create-app-react app 方式

## 问题描述

![error1](https://user-images.githubusercontent.com/27348840/47060516-7fc12f00-d200-11e8-9065-052cd04057ac.png)
![error2](https://user-images.githubusercontent.com/27348840/47060543-9d8e9400-d200-11e8-81f5-873fff69d035.png)

**Comment by noyobo** [comment]
单独使用基础组件，再引入 `@icedesign/base/index.scss`
