### ISSUE TITLE
react物料ice-material-dashboard不能使用

### ISSUE THREAD

**Issue by awawu** [alibaba/ice#989]
## 环境信息

- 操作系统：windows 10 pro
- Iceworks 版本： 2.10.0

## 问题描述

从 ice-material-dashboard 模板创建项目之后，没有经过任何修改，马上启动调试服务，页面显示错误，构建项目也出现错误。

## 错误信息
请查看附件。
![ice-material-dashboard-chrome-console](https://user-images.githubusercontent.com/19378642/47124586-41377d00-d2b1-11e8-89be-f25d463f437d.jpg)
![ice-material-dashboard-](https://user-images.githubusercontent.com/19378642/47124591-4a284e80-d2b1-11e8-9914-767cab16cd14.jpg)
![ice-material-dashboard-](https://user-images.githubusercontent.com/19378642/47124594-4d233f00-d2b1-11e8-800f-e39de6a9f022.jpg)

**Comment by yesterday679** [comment]
问题解决方案 
see : https://github.com/mui-org/material-ui/issues/12407

npm install --save-exact @babel/runtime@7.0.0-beta.55

**Comment by chenbin92** [comment]
babel 升级问题引起的
