### ISSUE TITLE
内网, 飞冰无法访问外网, 打开飞冰2.11.1后界面一片空白

### ISSUE THREAD

**Issue by gemmi** [alibaba/ice#995]
## 环境信息

- 操作系统：win7
- Iceworks 版本： 2.11.1 

## 问题描述

内网, 飞冰无法访问外网, 打开飞冰后界面一片空白.
之前用2.5版本的时候, 会显示模板/区块...等按钮,只是具体物料/区块无法显示, 但可以从外网下载物料json文件后, 在设置中配置本地的物料json文件url和搭建本地npm仓进而使用.

**Comment by chenbin92** [comment]
内网, 飞冰无法访问外网是指什么？

直接钉钉我

**Comment by chenbin92** [comment]
Fixed
